### ISSUE TITLE
如何部署，能给个详细说明吗

### ISSUE THREAD

**Issue by slwl** [jxxghp/nas-tools#1]

**Comment by jxxghp** [comment]
Docker的下载安装可能需要参考网上的教程。
关注本程序的配置我在config/config.ini示例配置文件中添加了详细的注释说明，请看下是否能解答你的疑问。
后面抽空再精简下配置，现在的配置确实有点复杂。

**Comment by jxxghp** [comment]
重构了下配置，增加了注释。
