### ISSUE TITLE
部分历史记录无法删除

### ISSUE THREAD

**Issue by Pollo3470** [jxxghp/nas-tools#1014]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4
>
> 环境: docker
>

## 你遇到什么问题了？是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 部分目录同步的历史记录无法删除

## 你的问题能重现嘛？

> 权力的游戏无法删除，点击删除后历史记录还在，同步的文件也还在

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/90445326/188699418-d0ac0fca-22da-40ed-bd39-b5c9a3877cc1.png)

**Comment by netduke777** [comment]
我遇到过类似问题, 记录删除了,但是硬链接目录还在.  试了下, 感觉是文件/目录权限的问题, 虽然nas-tools 的权限不是ADMIN,但是好像在生成硬链接的过程中, 操作的目录会变成ADMIN的, 然后NAS-TOOLS就删除不了了, 我建了一个全盘CHOWN的批处理, 没事经常执行下.  
我的问题和建议是:  删除了记录后, 再次同名文件拷入同步文件夹, nas-tools将不再识别 ,必须改下名字,方可. 虽然不是什么大问题,但是有时候剧集因为比较多,这样就会有些麻烦,不知道能否修正为无需改名字,只需要经过一个重新拷入即可激活再次识别, 或者提供一个NAS-TOOLS记录(真正的记录)位置删除的入口.

**Comment by netduke777** [comment]
另外,和jellyfin配合时也会出现图片刮削不到,或者出现媒体类别不识别,无法播放, 感觉都是目录权限的问题, 最好经常把媒体目录的权限或者所有人统一改为一个账号为好. 反正我是将两者都统一一个不是admin的账号,但是在过程中, 还是会发现有些目录,特别是剧集,有些目录的所有帧变为admin , 这样就造成jellyfin无法刮削或者播放的问题.    现在是用笨方法,没事用批处理全盘更改下所有权

**Comment by jxxghp** [comment]
> 我遇到过类似问题, 记录删除了,但是硬链接目录还在.  试了下, 感觉是文件/目录权限的问题, 虽然nas-tools 的权限不是ADMIN,但是好像在生成硬链接的过程中, 操作的目录会变成ADMIN的, 然后NAS-TOOLS就删除不了了, 我建了一个全盘CHOWN的批处理, 没事经常执行下.  
> 
> 我的问题和建议是:  删除了记录后, 再次同名文件拷入同步文件夹, nas-tools将不再识别 ,必须改下名字,方可. 虽然不是什么大问题,但是有时候剧集因为比较多,这样就会有些麻烦,不知道能否修正为无需改名字,只需要经过一个重新拷入即可激活再次识别, 或者提供一个NAS-TOOLS记录(真正的记录)位置删除的入口. 

服务那里有个清空转移缓存

**Comment by netduke777** [comment]
服务那里有个清空转移缓存!  
收到收到,万分感谢, 会了, 第一次我是重装的,尴尬,呵呵,谢谢!
另外再请教下,    `# 媒体目录，多个目录需要分别映射进来` \ ,是像其他的docker,采用子目录的方式映射, 还是可以采用同级目录的方式, 如jellyifin是采用:-v $DATA1:/media/volume1  -v $DATA2:/media/volume2  这种方式,谢谢

**Comment by Pollo3470** [comment]
> 我遇到过类似问题, 记录删除了,但是硬链接目录还在. 试了下, 感觉是文件/目录权限的问题, 虽然nas-tools 的权限不是ADMIN,但是好像在生成硬链接的过程中, 操作的目录会变成ADMIN的, 然后NAS-TOOLS就删除不了了, 我建了一个全盘CHOWN的批处理, 没事经常执行下. 我的问题和建议是: 删除了记录后, 再次同名文件拷入同步文件夹, nas-tools将不再识别 ,必须改下名字,方可. 虽然不是什么大问题,但是有时候剧集因为比较多,这样就会有些麻烦,不知道能否修正为无需改名字,只需要经过一个重新拷入即可激活再次识别, 或者提供一个NAS-TOOLS记录(真正的记录)位置删除的入口.

但我的问题是，我这个记录都删不掉，点了删除没反应

**Comment by netduke777** [comment]
但我的问题是，我这个记录都删不掉，点了删除没反应

检查一下容器目录的权限所有者,还有硬链接目录的权限和所有者, 另外删除个其他的记录试试,感觉8成是权限问题, 如果所有记录都删不掉, 那就重装下, 应该不存在这个问题的.

**Comment by Pollo3470** [comment]
> 但我的问题是，我这个记录都删不掉，点了删除没反应
> 
> 
> 
> 检查一下容器目录的权限所有者,还有硬链接目录的权限和所有者, 另外删除个其他的记录试试,感觉8成是权限问题, 如果所有记录都删不掉, 那就重装下, 应该不存在这个问题的.

root权限应该不是问题，其他的都删的掉，就只有这个删不掉

**Comment by netduke777** [comment]
那就手工删除硬链接目录试下, 我有时搞忘了,就手工先删除了硬链接目录, 然后再回到这里删除记录, 早上作者又教了清除缓存,这样再重新放入文件,试下, 重启下容器?

**Comment by Pollo3470** [comment]
> 那就手工删除硬链接目录试下, 我有时搞忘了,就手工先删除了硬链接目录, 然后再回到这里删除记录, 早上作者又教了清除缓存,这样再重新放入文件,试下, 重启下容器? 当然我遇到几次都是记录能删掉,但是目录没有删完,只删除了部分.

删了硬链接，还是删不掉历史记录，这下好了，连洗版都洗不成

**Comment by jxxghp** [comment]
文件不在了就行，历史记录我有空的时候看看能不能重现
