### ISSUE TITLE
api.themoviedb.org 始终无法正常连通

### ISSUE THREAD

**Issue by bigdongdongCLUB** [jxxghp/nas-tools#1015]
>威联通下docker安装的 v2.0.4

api.themoviedb.org 怎么都连不上

nas已经翻墙使用passwall 无论是中国列表外还是gfw都不行

通过搜索有朋友表示添加以下到威联通nas的host文件 无果

13.226.238.76 api.themoviedb.org
13.224.161.90 api.themoviedb.org
13.35.7.102 api.themoviedb.org
13.225.103.26 api.themoviedb.org
13.226.191.85 api.themoviedb.org
13.225.103.110 api.themoviedb.org
52.85.79.89 api.themoviedb.org
13.225.41.40 api.themoviedb.org
13.226.251.88 api.themoviedb.org
13.225.89.239 api.thetvdb.com
13.249.175.212 api.thetvdb.com
13.35.161.120 api.thetvdb.com

准确的说可能会有那么一瞬间是通的，但会立刻不通。
本地网络Ping还是在nas里ping api.themoviedb.org 都是通的。。

<img width="761" alt="image" src="https://user-images.githubusercontent.com/43647204/188709013-779f9a1f-ffe8-4eb4-9daa-fcb25546fdc9.png">

很邪门 求解

**Comment by asdf23567890** [comment]
昨天尝试配置时我也遇到了类似问题。我的环境是使用了威联通的docker挂载了clash作为代理服务器。最终经过对clash的规则调整解决了问题。（重要：每次修改完代理服务器配置请重启nas-tools！然后再尝试测试网络）

**Comment by mizb** [comment]
上加密dns

**Comment by Rocky-CN** [comment]
桥接模式下，nas-tools和威联通被分别视为两台机器，所以修改威联通的host是没用的。
解决方法：
1. nas-tools左侧栏，选择`设置`-->`基础设置`-->`代理服务器`，填上梯子的IP+端口。梯子里要开`allow Lan`。
2. 部署nas-tools时，网络模式选择`host模式`。

**Comment by bigdongdongCLUB** [comment]
> 

梯子的IP+端口？有什么协议可以只用IP+端口就能用啊。。只有socks5啊。为此我专门搭了个socks5服务器填进去

最好的情况就是这样了。
<img width="835" alt="截屏2022-09-15 02 04 47" src="https://user-images.githubusercontent.com/43647204/190229946-b2cf8e16-8c9b-4fb5-b274-cafc211e8e52.png">

**Comment by Rocky-CN** [comment]
> > 
> 
> 梯子的IP+端口？有什么协议可以只用IP+端口就能用啊。。只有socks5啊。为此我专门搭了个socks5服务器填进去
> 
> 最好的情况就是这样了。 <img alt="截屏2022-09-15 02 04 47" width="835" src="https://user-images.githubusercontent.com/43647204/190229946-b2cf8e16-8c9b-4fb5-b274-cafc211e8e52.png">

**使用http代理试试**。我用的是clash，填sock5的代理端口不行，填http的代理端口就正常，具体原因不明。

**Comment by bigdongdongCLUB** [comment]
> 已可切换使用tmdb.org，这个网络连通性更好。
> 
> 且提供了tmdb服务代理功能。

额 替换的issue就是我替的 感谢大佬采纳！
