### ISSUE TITLE
电视剧分类细化

### ISSUE THREAD

**Issue by xnoods** [jxxghp/nas-tools#1016]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4
>
> 环境: docker or synology

**Comment by xnoods** [comment]
个人觉得加一个“其它剧”就行了

**Comment by netduke777** [comment]
修改那个分类文件呀, 很简单的,把下面的国家代码复制上来就行了, 原来以为大神都给分好了,就没动,结果发现, 维京传奇给搞成未分类了结果发现欧美剧没有覆盖很多国家, 就重新自己改了下 , 把日韩改成亚洲, 从下面拷贝想加入的国家代买到上面就ok了,
nas-tools/config/default-category.yaml
  欧美剧:
    # 匹配 origin_country 国家，主要欧美国家列表
    origin_country: 'US,FR,GB,DE,ES,IT,NL,PT,RU,UK,IE,CA,DK,DE,CH,AT,IS,NZ,SE,UA,BE,GK,RO'
  亚洲剧:
    # 匹配 origin_country 国家，主要亚洲国家列表
    origin_country: 'JP,KP,KR,TH,IN,SG'
引号里加入你想加入的国家代码,文件的下面作者给出了部分, 找不到就百度 2位国家代码, 然后加入就OK了

**Comment by jxxghp** [comment]
参考楼上自己改配置文件
