### ISSUE TITLE
文件转移失败

### ISSUE THREAD

**Issue by liangYuHan** [jxxghp/nas-tools#1017]
> NASTool 版本: v2.0.4
>
> 环境: docker
>
> 问题：手动转移文件失败，报错：硬链接失败，错误码 256

> 能够重现

> 希望能正常转移文件
<img width="675" alt="image" src="https://user-images.githubusercontent.com/51392885/188772260-d4226f38-baee-437b-b018-07b975cfcc0d.png">

**Comment by huluohu** [comment]
> > NASTool 版本: v2.0.4
> > 环境: docker
> > 问题：手动转移文件失败，报错：硬链接失败，错误码 256
> 
> > 能够重现
> 
> > 希望能正常转移文件
> 
> <img alt="image" width="675" src="https://user-images.githubusercontent.com/51392885/188772260-d4226f38-baee-437b-b018-07b975cfcc0d.png">

看一下这个 #1003
