### ISSUE TITLE
日志报错，订阅都不见了

### ISSUE THREAD

**Issue by psychopasss** [jxxghp/nas-tools#102]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/11738089/167370140-61c2b295-17b7-4cb9-8c4d-0d72363e17ef.png">
这个剧是豆瓣同步过来的，之前没有加到rss订阅中。

**Comment by psychopasss** [comment]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/11738089/167370799-df677db4-5926-486f-b35f-6c6ca8c0fd5c.png">
<img width="743" alt="image" src="https://user-images.githubusercontent.com/11738089/167370817-55f42de6-3df3-44ab-99c9-e08deecd734b.png">
订阅都不见了。

**Comment by jxxghp** [comment]
你是把数据库文件删了？这种问题进群发吧，就不要在这提了。
