### ISSUE TITLE
【建议】刷流任务增加自定义RSS功能

### ISSUE THREAD

**Issue by samyang211** [jxxghp/nas-tools#1020]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4
>
> 环境: docker （unraid）

## 你想要新增或者改进什么功能？

> 站点管理 - 刷流任务 下新建任务是依照站点维护内的RSS链接进行匹配，无法道道movie tv分别存在不同目录的需求
1、希望再创建刷流任务时，可以自定义rss链接，不默认采用站点维护内的链接
2、这样同个站点就可以根据movie tv创建不同rss链接，进行刷流
3、最终保存的媒体文件会根据类型进行存储

## 这个功能有什么可以参考的资料吗？

> 暂时没有.

**Comment by samyang211** [comment]
另外：
刷流任务的，“做种人数限制”不准确，测试站点sky、lemon；设置为2后，会下载到几十人 上百人再做种的文件。
此现象在创建任务后第一次启动出现（后面不会出现，是因为新增的肯定是只有1人做种的情况）


最后最后，感谢项目组提供这么强大的工具，祝大家身体健康

**Comment by jxxghp** [comment]
#935
