### ISSUE TITLE
订阅无法下载

### ISSUE THREAD

**Issue by chen8571** [jxxghp/nas-tools#1023]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2022.9.7最新版
>
> 环境: docker群晖
>

## 你遇到什么问题了？是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 描述一下你遇到的问题
订阅动漫后匹配到种子无法添加到下载软件

## 你的问题能重现嘛？

订阅动漫《彻夜之歌》在观众pt匹配到资源后显示错误信息：下载出现异常，not a valid bencoded string
![136DABDB-FE45-4F93-976E-2B50EC98C7DC](https://user-images.githubusercontent.com/102362145/188822776-61ace72f-e905-406f-a239-08f7f4e7fe29.png)
![Uploading E61B8A23-95CC-4249-A8E9-4BC0A6EA01CA.jpeg…]()

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UIBUG请提供截图及配置文件截图，其它问题提供后台日志

**Comment by chen8571** [comment]
![Uploading 9A0DF556-5487-46E1-8B39-07F0857AC5E1.jpeg…]()

**Comment by jxxghp** [comment]
信息太少没办法分析，检查cookie是否有效
