### ISSUE TITLE
关于简化telegram与nastools交互的建议

### ISSUE THREAD

**Issue by JJJDand** [jxxghp/nas-tools#1024]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.0.4
>
> 环境:docker

## 你想要新增或者改进什么功能？

> 现在nastools和telegram的交互应该是使用webhook的方式，但是需要vps,ssl,且只能使用常用端口，限制较多。查了一下telegram的api还有一个getUpdates的api，可使用长轮询的方式可以获得tg发送的消息，不需要其他的设置，希望可以支持此功能。

## 这个功能有什么可以参考的资料吗？

> 可参考
![image](https://user-images.githubusercontent.com/31849833/188823765-58e92407-6539-4fc7-b715-2a2bd840a5a5.png)
![image](https://user-images.githubusercontent.com/31849833/188824188-3a2a0cd6-557d-4530-895b-bdf1dd276fc3.png)
https://blog.30sparks.com/develop-telegram-bot-introduction/
https://core.telegram.org/bots/api#setwebhook

**Comment by Earendil-C** [comment]
https://t.me/nastool_mi
频道里面有个很方便的docker应用，不用设置https

**Comment by JJJDand** [comment]
> https://t.me/nastool_mi 频道里面有个很方便的docker应用，不用设置https

我有在用这个，但感觉可以内置到nastool里

**Comment by jxxghp** [comment]
别人写了工具了，先用着吧。或者PR
