### ISSUE TITLE
Plex启用双重认证后，无法正常通过测试

### ISSUE THREAD

**Issue by josch0510** [jxxghp/nas-tools#1033]
## 你使用的 NASTool 是什么版本，什么环境？

NASTool 版本: v2.0.4 3869afd
环境: docker

## 你遇到什么问题了？是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

Plex启用双重认证后，无法正常通过测试。

## 你的问题能重现嘛？

能够重现

## 你期望的结果

能正常连接Plex服务器

## 给出程序界面截图、后台运行日志或配置文件

ERROR - 【PLEX】Plex服务器连接失败：(401) unauthorized; https://plex.tv/users/sign_in.xml <?xml version="1.0" encoding="UTF-8"?> <errors> <error>Invalid email, username, password or verification code.</error> </errors>

**Comment by jxxghp** [comment]
不支持双重认证
