### ISSUE TITLE
媒体库计数为0

### ISSUE THREAD

**Issue by yizhitangtongxue** [jxxghp/nas-tools#1034]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4
>
> 环境: Docker on Synology
>

## 你遇到什么问题了？是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 媒体库的计数为0，但是鼠标放上去会显示已有的视频数量

## 你的问题能重现嘛？

> 能够重现

## 你期望的结果

> 计数正确

## 给出程序界面截图、后台运行日志或配置文件

<img width="895" alt="image" src="https://user-images.githubusercontent.com/22952680/188929564-8107a4e4-d059-43a6-9dd6-0a9a611cd64b.png">

**Comment by colorsakura** [comment]
应该是没有连接emby这些，所以没有数据
