### ISSUE TITLE
有考虑过处理音频吗

### ISSUE THREAD

**Issue by Eronana** [jxxghp/nas-tools#1036]
Plex, Emby, Jellyfin都支持管理音乐. 但是下载下来的音频也有很多问题:
1. 命名不规范导致识别有误
2. 有些格式不支持(比如TTA), 需要转码
3. 不支持cue, 需要去切分

虽然有很大的不同, 但是音频的这些问题在某些层面上来说, 和视频是一致的.
所以nas-tools在未来是否有可能会支持音频的转移, 重命名, 格式转换和切分?

**Comment by liaobadadi** [comment]
+1 ，我也看，为啥音频不能转移重命名呢？
