### ISSUE TITLE
刷流做种人数介于的介绍

### ISSUE THREAD

**Issue by rockhia** [jxxghp/nas-tools#1037]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4
>
> 环境: docker

> 描述一下你遇到的问题
刷流的时候，做种人数设置为介于0,2，会下载做种人数为2的种子。
因此想确定一下介于是否有包含。比如介于0,2，满足要求的数值为1，还是0，1，2

## 你期望的结果
确定一下介于是否包含设置地两个数值，并在设置地方稍微描述清楚

**Comment by rockhia** [comment]
![Screenshot_20220908_131338_com yandex browser_edit_591861898659167](https://user-images.githubusercontent.com/90016652/189039900-46cbdf68-493e-4a14-ab4c-3e2609effeb6.jpg)
![Screenshot_20220908_131410](https://user-images.githubusercontent.com/90016652/189039909-675c0a9f-9d77-4bc0-bfb7-71377f10385b.jpg)

**Comment by link2fun** [comment]
不是直接有小于的么, 用小于不就好了

**Comment by rockhia** [comment]
用小于会下载做种人数为0的种子，导致长期占用下载数。
猫站经常遇到这种情况。

**Comment by penwyp** [comment]
“介于0-2”表示0和2都包含，后续我改一下吧
