### ISSUE TITLE
【功能建议】配置了代理的话能否同步增加git代理

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#1040]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4
>
> 环境: docker

服务里面配置了代理服务器的话能否同步增加git全局代理 
git config --global http.proxy
git config --global https.proxy

每次拉取新镜像之后都要手动执行上述命令，不然拉取最新代码挺慢的。

**Comment by jxxghp** [comment]
比较麻烦，docker已经预留了github的代理入口，看下docker安装的说明，用这个吧。
