### ISSUE TITLE
rss bug反馈

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#1041]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4 7585ccc
>
> 环境: docker 
>

## 你遇到什么问题了？是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

电视剧订阅 出现非订阅组别
我在nastool-站点-rss地址，已经把官方网站提供的rss项目筛选出了官组并且订阅到nastool里，然而在电视剧订阅时候，仍出现非官组的情况。

## 你的问题能重现嘛？

> 能够重现

## 你期望的结果

能够严格按照rss订阅筛选

## 给出程序界面截图、后台运行日志或配置文件

> 如UIBUG请提供截图及配置文件截图，其它问题提供后台日志
![IMG_1628](https://user-images.githubusercontent.com/39802246/189046577-c23bb7a7-fb24-4ad2-83b3-bbf297aef4f1.JPG)
马赛克部分为官组名称。由于站点要求，只能马赛克

**Comment by jxxghp** [comment]
这个是索引器的定时搜索，你把订阅定时搜索关掉或者订阅时不要选中搜索站点
