### ISSUE TITLE
过滤规则误伤

### ISSUE THREAD

**Issue by Pollo3470** [jxxghp/nas-tools#1042]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4
>
> 环境: docker
>

## 你遇到什么问题了？是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 用的内置日常观影过滤规则，Thor Love and Thunder 2022 V1 1080p WEB-DL DDP5.1 H264-AQLJ@HDSky 会被过滤掉

## 你的问题能重现嘛？

> 能够重现

## 你期望的结果

> 该资源应该属于1080p特效

## 给出程序界面截图、后台运行日志或配置文件

> ![image](https://user-images.githubusercontent.com/90445326/189054730-3bb2395d-fa9a-4aa6-b33d-fd97f7507831.png)

**Comment by log-time** [comment]
![3QBHQSFJNE7AW$V F 5`YO3](https://user-images.githubusercontent.com/66826612/189066802-b89a5fe9-9ac5-46c1-8610-9f38fce74732.png)
测试了下，应该是正确过滤了才对啊

**Comment by Pollo3470** [comment]
> ![3QBHQSFJNE7AW$V F 5`YO3](https://user-images.githubusercontent.com/66826612/189066802-b89a5fe9-9ac5-46c1-8610-9f38fce74732.png) 测试了下，应该是正确过滤了才对啊

奇怪，我这里加入副标题测试显示未匹配
![image](https://user-images.githubusercontent.com/90445326/189069049-f3a230be-1f17-47f9-92ca-f877afe79e85.png)

**Comment by Pollo3470** [comment]
重置了一下过滤规则依旧是未匹配，估计是新版的过滤规则有问题

**Comment by log-time** [comment]
> 重置了一下过滤规则依旧是未匹配，估计是新版的过滤规则有问题

可以看看你使用的规则不？我的也是最新版，貌似没问题

**Comment by log-time** [comment]
> ![image](https://user-images.githubusercontent.com/90445326/189070882-0ccdb0e8-e994-4795-917e-7814370d3e62.png)
> 
> 重置了一下过滤规则依旧是未匹配，估计是新版的过滤规则有问题

这个规则是匹配不上的，因为资源是web-dl资源，你发的规则是匹配bluray来源的

**Comment by log-time** [comment]
> ![image](https://user-images.githubusercontent.com/90445326/189071346-d7b71d63-32e5-4f81-ba42-5d2a68bc204d.png)
> 
> 重置了一下过滤规则依旧是未匹配，估计是新版的过滤规则有问题
> 
> 不懂正则表达式，麻烦作者大大看一下

默认规则做了分级匹配，可以直接用，不需要修改

**Comment by Pollo3470** [comment]
> > ![image](https://user-images.githubusercontent.com/90445326/189071346-d7b71d63-32e5-4f81-ba42-5d2a68bc204d.png)
> > 重置了一下过滤规则依旧是未匹配，估计是新版的过滤规则有问题
> > 不懂正则表达式，麻烦作者大大看一下
> 
> 默认规则做了分级匹配，可以直接用，没有特殊需求不需要修改

没有修改，有个1080特效-其他来源，没法匹配
方便发一下你过滤规则的截图吗

**Comment by Pollo3470** [comment]
找到原因了，该种子的副标题有"DIY"，导致被排除

副标题：雷神4：爱与雷霆 / 雷神奇侠4 / 雷神索尔【DIY 简繁英四特效字幕】

建议修改一下默认规则，空很多种子副标题带diy字样

![image](https://user-images.githubusercontent.com/90445326/189129251-34acb264-c7de-4baf-a64c-4fa9c0f6643c.png)

**Comment by Shurelol** [comment]
> 

建议自己修改，过滤规则都可以编辑，增加或删除

**Comment by Pollo3470** [comment]
> > 
> 
> 建议自己修改，过滤规则都可以编辑，增加或删除 ![image](https://user-images.githubusercontent.com/16237201/189130540-7689ca9c-2080-452f-a288-8e818fbea66b.png)

已修改，个人建议去掉这条
