### ISSUE TITLE
推送及强制做种配置开关问题

### ISSUE THREAD

**Issue by MiaOcean** [jxxghp/nas-tools#1044]
刷流任务第一次设置打开推送或者强制做种按钮以后保存了之后未生效，要点编辑进去再打开一次。望作者大大有时间修复下3Q

**Comment by tevenfeng** [comment]
这个问题是由于新增刷流任务时，taskid不存在，保存开关到SYSTEM_DICT时没有该任务的唯一标识，所以会存在这个问题。

@jxxghp 比较快速的修复方法是，把任务名称字段设置为唯一，这样可以在存储开关信息时有唯一的标识

**Comment by jxxghp** [comment]
> 这个问题是由于新增刷流任务时，taskid不存在，保存开关到SYSTEM_DICT时没有该任务的唯一标识，所以会存在这个问题。
> 
> 
> 
> @jxxghp 比较快速的修复方法是，把任务名称字段设置为唯一，这样可以在存储开关信息时有唯一的标识

保存开关的时候用站点的id

**Comment by tevenfeng** [comment]
> > 这个问题是由于新增刷流任务时，taskid不存在，保存开关到SYSTEM_DICT时没有该任务的唯一标识，所以会存在这个问题。
> > @jxxghp 比较快速的修复方法是，把任务名称字段设置为唯一，这样可以在存储开关信息时有唯一的标识
> 
> 保存开关的时候用站点的id

但是实际上同一个站点也有可能同时设置多个刷流任务的吧
