### ISSUE TITLE
搜索页面的过滤器希望能对电视剧筛选具体的集数

### ISSUE THREAD

**Issue by shanyan-wcx** [jxxghp/nas-tools#1045]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4 4a87602
>
> 环境: docker 

## 你想要新增或者改进什么功能？

> 搜索页面的过滤器希望能对电视剧筛选具体的集数，不然所有集混在一起找起来太乱。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
搜索框其实是可以带季和集的：西部世界第四季第1集
