### ISSUE TITLE
RARBG是否支持添加到站点进行RSS定时检索

### ISSUE THREAD

**Issue by VectorZhao** [jxxghp/nas-tools#1047]
**站点维护添加了RARBG的订阅链接**
![image](https://user-images.githubusercontent.com/16644993/189105741-734838a0-6a25-45b2-85d4-5f8597448c8d.png)

**配置里面添加了RSS订阅地址**
![image](https://user-images.githubusercontent.com/16644993/189106569-9d2d85f1-6c14-42c8-8037-50d5db9e50e9.png)

**运行日志如下：**
18:53:54 INFO - 【RSS】开始RSS订阅...
18:53:54 INFO - 【RSS】电影订阅清单：龙珠超：超级英雄 阿凡达2：水之道 新神榜：杨戬 急速首尔 诱捕正义 航海王：红发歌姬 四叠半时光机 铃芽户缔
18:53:54 INFO - 【RSS】电视剧订阅清单：女浩克 指环王：力量之戒 龙之家族
18:53:54 INFO - 【RSS】正在处理：rarbg-movie
18:53:55 WARN - 【RSS】rarbg-movie 未下载到数据
18:53:55 INFO - 【RSS】正在处理：rarbg-tv
18:53:56 WARN - 【RSS】rarbg-tv 未下载到数据
18:53:56 INFO - 【RSS】所有RSS处理结束，共 0 个有效资源

**Comment by jxxghp** [comment]
程序上是支持的，但是RARBG的网站有cf墙，所以很难连上，现在索引都是通过第三方网站的API来绕过的。
将来可能会内嵌浏览器实现破墙。
