### ISSUE TITLE
添加PT任务出错：No attribute find

### ISSUE THREAD

**Issue by wgltony** [jxxghp/nas-tools#105]
06:20:42 ERROR - 【PT】添加PT任务出错：Query failed with result "invalid or corrupt torrent file".

06:29:59 ERROR - 【PT】添加PT任务出错：No attribute find 

求助 一直出现这个错误， 用的 prowlarr + transmission

transmission界面可以看到新建的下载任务，但是一直没有速度

**Comment by jxxghp** [comment]
不是bug
