### ISSUE TITLE
【功能请求】希望支持搜索剧集多季或全季打包的资源

### ISSUE THREAD

**Issue by Pollo3470** [jxxghp/nas-tools#1050]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 不少已完结或已更新多季的剧集资源都是以多季打包的方式存在的，希望可以搜索全季打包或多季打包资源

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/189143730-cec7eff6-670b-4814-8eef-dd606a52fcf2.png)
高级搜索

**Comment by Pollo3470** [comment]
> ![image](https://user-images.githubusercontent.com/16237201/189143730-cec7eff6-670b-4814-8eef-dd606a52fcf2.png)
> 高级搜索

感谢解答，平时喜欢在首页搜索框搜索，没发现这个功能
