### ISSUE TITLE
建议: 同名片子删除功能的加强, 另有没有可能增加一种空的刮削功能,谢谢

### ISSUE THREAD

**Issue by netduke777** [jxxghp/nas-tools#1051]
## 你使用的 NASTool 是什么版本，什么环境？
> NASTool 版本: vx.x.x
>2.0.5
> 环境: docker or windows or synology
docker
## 你想要新增或者改进什么功能？
工具会根据片子的质量进行同名片子的导入,如果片子质量不一样就不导入,相同就不导入(即使名字不同),这点非常优秀!!
但是如果删除不同质量片子中的任何一个都会将整个目录删除,也就是说多个质量不同的同名片子,删除一个就相当于全部删除,但是记录上仍仅是去除了删除的片子,其他片子仍显示存在(实际上都被删除了). 这点还是比较麻烦,尤其是jellyfin工作时,由于有时权限不一样会造成比较混乱的情况,有些目录存在但是其中没有连接了,仅是几张图片而已.
> 你想要新增或者改进什么功能？
1. 能否做到同名的几个连接,在操作记录中删除时仅是删除所选的连接, 保留目录,直到最后一个同名片子被删除时才删除整个目录, 谢谢,辛苦!
2. 能否增加一种空的刮削功能--也就是在人工识别处,增加一个选项,无需到TMD去刮削,而是直接产生硬链接,来方便管理一些没有注册的节目, 比如一些电视台的专题节目,不是发行的,所以刮削不到 .这时候利用这个功能仅把nas-tools当做硬链接管理和目录整理工具.如果能够提供一个自定义图片的导入功能就更完美了. 前面我遇到了一个国外的记录片,豆瓣有,TMD没有,只好在TMD上新建了一个片子才成功.还有几个电视专题记录片, 豆瓣也没有, 但是我仍想用nas-tools来建立硬链接来管理.
## 这个功能有什么可以参考的资料吗？
效果就像硬链接一样,只有最后一个硬链接被删除时才真正删除源文件(相当于目录)
> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
1.效果同linux的硬链接.
2.在人工识别对话框处,增加一个按钮==无需查找直接按照源目录结构产生新的片子的硬链接, 同时可以提供另一个按钮用于选择自定义的一些背景图片.谢谢

**Comment by fxqq** [comment]
第二个功能已经有了，在目录同步里你不勾选识别并重命名，仅开启同步就是单独的硬链了，

**Comment by Shurelol** [comment]
![IMG_20220910_020534_819](https://user-images.githubusercontent.com/16237201/189416255-ece6033a-170a-486c-9600-44297e042d69.jpg)

可以关闭识别只进行转移

**Comment by netduke777** [comment]
> ![IMG_20220910_020534_819](https://user-images.githubusercontent.com/16237201/189416255-ece6033a-170a-486c-9600-44297e042d69.jpg)
> 
> 可以关闭识别只进行转移

学习到了,谢谢!
但是这个是个总的,我是说,仅是个别一两个, 毕竟大部分都是可识别的, 只有极少数不需搜刮的.
另外我不知道这里关闭了,然后转移了一个文件, 再打开是否有更大的影响.

既然这里有了这个功能, 那在人工识别处再增加一个按钮估计难度不大吧,☺, 嘿嘿, 主要是最好同时增加一个这样插入自定义图片的按钮,一遍成!!

**Comment by netduke777** [comment]
> > 前面我遇到了一个国外的记录片,豆瓣有,TMD没有,只好在TMD上新建了一个片子才成功.还有几个电视专题记录片, 豆瓣也没有
> 
> 感觉应该到TMDB上新建，这样以后下载的也能识别了，如果一直没人新建，那就所有人都一直识别不到。

我也建了,本来是准备用,新建对话框里的IMDb号来查找的,(因为TVDB好像只有新建时才会有输入IMDB的可能,是否有其他地方可以输入请告知),结果一下子就新建成功了, 害得我还满世界BD, 找图片补全信息,好忙的. 那是一个国家地理的高分纪录片,按理说不应该没有, 不知道怎么回事. 
上面兄台介绍的关闭刮削,是整个总的.这里不应该来回动把, 我觉得就在人工识别处的弹出对话框上,增加两个按钮. 
1, 是免刮削,直接硬连.
2, 然后弹出询问是否要自定义插入, 需要则可以选择, 不要关闭即可.

**Comment by netduke777** [comment]
删除功能大家都不需要吗?  没回应呀...这个很重要呀, 经常需要更新片源, 然后节省空间的时候, 只能手工删除了呀

**Comment by Shurelol** [comment]
emby等软件里直接删掉就行了，会把媒体文件一起删掉的。
如果是硬链接，源文件刚好能保留下来做种。没理解这个功能的必要性。
