### ISSUE TITLE
【Rss订阅】订阅下载不匹配

### ISSUE THREAD

**Issue by Eao-Kind** [jxxghp/nas-tools#1053]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4
>
> 环境: docker
>

## 你遇到什么问题了？是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 订阅综艺，综艺名字十分相似，仅差三个字母，导致匹配错误，下错视频

## 你的问题能重现嘛？

> 能够重现

## 你期望的结果

> 正确匹配

## 给出程序界面截图、后台运行日志或配置文件

订阅
![image](https://user-images.githubusercontent.com/53032373/189172442-0d20d63d-806a-4481-b7fd-418c14d5e34a.png)

日志
> 【RSS】开始处理：[大陆][20220908][密室大逃脱 第四季][Room.Escape.VIP.S04E09.2022.1080p.WEB-DL.H264.AAC-TJUPT][MP4][密室大逃脱 第四季 | 大神版第9期：大神团上演“逃脱者联盟” 黄子弘凡伪装镇民混入NPC | TJUPT小组作品 转载请注明北洋园PT [每周三四五更新]]
【RSS】[大陆][20220908][密室大逃脱 第四季][Room.Escape.VIP.S04E09.2022.1080p.WEB-DL.H264.AAC-TJUPT][MP4][密室大逃脱 第四季 | 大神版第9期：大神团上演“逃脱者联盟” 黄子弘凡伪装镇民混入NPC | TJUPT小组作品 转载请注明北洋园PT [每周三四五更新]] 识别为 密室大逃脱 (2019)S04 E09 匹配订阅成功
【RSS】种子描述：<img alt="image" src="/pic/Infinity-1.2s-64px.svg" data-src="https://img9.doubanio.com/view/photo/l_ratio_poster/public/p2875779207.jpg" /><br />
【RSS】密室大逃脱 (2019) S04 数据库记录的缺失集：[9, 10, 11, 12, 13]
【META】正在查询TMDB电视剧：89861 ...
【DOWNLOADER】密室大逃脱 (2019) 第4季 共有 13 集
【DOWNLOADER】密室大逃脱 (2019) 第4季 缺失集：9、10、11、12、13
【RSS】密室大逃脱 (2019) S04 媒体库缺失剧集：[{'season': 4, 'episodes': [9, 10, 11, 12, 13], 'total_episodes': 13}]
【RSS】开始处理：[大陆][20220908][密室大逃脱 第四季][Room.Escape.S04E09.2022.1080p.WEB-DL.H264.AAC-TJUPT][MP4][密室大逃脱 第四季 | 第9期：小镇怪谈（下）| TJUPT小组作品 转载请注明北洋园PT [每周三四五更新]]
【RSS】[大陆][20220908][密室大逃脱 第四季][Room.Escape.S04E09.2022.1080p.WEB-DL.H264.AAC-TJUPT][MP4][密室大逃脱 第四季 | 第9期：小镇怪谈（下）| TJUPT小组作品 转载请注明北洋园PT [每周三四五更新]] 识别为 密室大逃脱 (2019)S04 E09 匹配订阅成功
【RSS】种子描述：<img alt="image" src="/pic/Infinity-1.2s-64px.svg" data-src="https://img9.doubanio.com/view/photo/l_ratio_poster/public/p2875779207.jpg" /><br />
【RSS】密室大逃脱 (2019) S04 数据库记录的缺失集：[9, 10, 11, 12, 13]
【META】正在查询TMDB电视剧：89861 ...
【DOWNLOADER】密室大逃脱 (2019) 第4季 共有 13 集
【DOWNLOADER】密室大逃脱 (2019) 第4季 缺失集：9、10、11、12、13
【RSS】密室大逃脱 (2019) S04 数据库记录的缺失集：[9, 10, 11, 12, 13]
【RSS】密室大逃脱 (2019) 缺失剧集：[{'season': 4, 'episodes': [9, 10, 11, 12, 13], 'total_episodes': 13}]
【DOWNLOADER】添加下载任务：[大陆][20220908][密室大逃脱 第四季][Room.Escape.VIP.S04E09.2022.1080p.WEB-DL.H264.AAC-TJUPT][MP4][密室大逃脱 第四季 | 大神版第9期：大神团上演“逃脱者联盟” 黄子弘凡伪装镇民混入NPC | TJUPT小组作品 转载请注明北洋园PT [每周三四五更新]] ...
【DOWNLOADER】添加下载任务：https://www.tjxxxxx.org/download.php?id=313982&passkey=
【MSG】发送telegram消息：title=密室大逃脱 (2019) S04 E09, text=RSS订阅的电视剧 密室大逃脱 (2019)S04 E09 已开始下载

下载的视频为
> Room.Escape.VIP.S04E09.2022.1080p.WEB-DL.H264.AAC-TJUPT

期望下载的视频为
> Room.Escape.S04E09.2022.1080p.WEB-DL.H264.AAC-TJUPT][MP4

Rss订阅部分内容如下
```
<item>
<title>[大陆][20220908][密室大逃脱 第四季][Room.Escape.VIP.S04E09.2022.1080p.WEB-DL.H264.AAC-TJUPT][MP4][密室大逃脱 第四季 | 大神版第9期：大神团上演“逃脱者联盟” 黄子弘凡伪装镇民混入NPC | TJUPT小组作品 转载请注明北洋园PT [每周三四五更新]]</title>
<description>
...
</description>
<pubDate>Thu, 08 Sep 2022 14:44:49 +0000</pubDate>
<link>https://www.tjupt.org/details.php?id=313982&hit=1</link>
<guid isPermaLink="false">836872bb7504a6f943acee159befde196a2ca955</guid>
<author>anonymous@www.tjupt.org (anonymous)</author>
<enclosure type="application/x-bittorrent" length="746401213" url="https://www.tjupt.org/download.php?id=313982&passkey=da8322b23dcfd4d815a0a6681393319c"/>
<comments>https://www.tjupt.org/details.php?id=313982&cmtpage=0#startcomments</comments>
<category>
<![CDATA[ 综艺 ]]>
</category>
<dc:creator>anonymous@www.tjupt.org (anonymous)</dc:creator>
<slash:comments>0</slash:comments>
</item>

<title>[大陆][20220908][密室大逃脱 第四季][Room.Escape.S04E09.2022.1080p.WEB-DL.H264.AAC-TJUPT][MP4][密室大逃脱 第四季 | 第9期：小镇怪谈（下）| TJUPT小组作品 转载请注明北洋园PT [每周三四五更新]]</title>
<description>
<![CDATA[ <img alt="image" src="/pic/Infinity-1.2s-64px.svg" data-src="https://img9.doubanio.com/view/photo/l_ratio_poster/public/p2875779207.jpg" /><br /> <br /> ◎译　　名　密室大逃脱 第四季<br /> ◎片　　名　密室大逃脱 第四季<br /> ◎年　　代　2022<br /> ◎产　　地　中国大陆<br /> ◎类　　别　真人秀<br /> ◎语　　言　汉语普通话<br /> ◎上映日期　2022-07-08(中国大陆)<br /> ◎豆瓣链接　<a class="faqlink" href="https://movie.douban.com/subject/35740857/" target="_blank">站外链接 :: https://movie.douban.com/subject/35740857/</a><br /> ◎单集片长　110分钟<br /> ◎集　　数　12<br /> ◎演　　员　杨幂 / Mi Yang<br /> 　　　　　　大张伟 / Wowkie Zhang<br /> 　　　　　　黄明昊 / Justin<br /> 　　　　　　张国伟 / Guowei Zhang<br /> 　　　　　　陈伟霆 / William Chan<br /> 　　　　　　彭昱畅 / Yuchang Peng<br /> <br /> ◎简　　介　<br /> <br /> 　　《密室大逃脱》是一档大型益智类实景解密互动真人秀。节目由嘉宾玩家倾力合作，进入不同主题故事置景内的“密室“演播室，全未知、不限时，每一期通过不同的角色扮演，与节目中的素人嘉宾进行益智力、创造力、决策力、洞察力、协作力和逆行力等多维度多元化的游戏对抗，最终解除重重困难，逃出节目组搭建的密室空间，传递出分工协作、合作共赢和永不放弃等正向价值。<br /> <br /> <font face="Courier New"><br /><div class="codetop">代码</div><div class="codemain" style='max-width: 1000px; overflow-x: auto'><pre> RELEASE.NAME..........: Room.Escape.S04E09.2022.1080p.WEB-DL.H264.AAC-TJUPT RELEASE.SiZE..........: 1.07 GiB RUNTiME...............: 51 min 16 s FRAMERATE.............: 25.000 ViDEO.CODEC...........: AVC ViDEO.BITRATE.........: 2 598 kb/s RESOLUTiON............: 1 920 pixels x 1 080 pixels AUDiO.CODEC...........: AAC LC AUDiO.BITRATE.........: 384 kb/s SOURCE................: WEB-DL / MangoTV </pre></div><br /></font><br /> <br /> <img alt="image" src="/pic/Infinity-1.2s-64px.svg" data-src="https://oss.lijishi.com/2022/09/08/496e5fe9a1437.jpg" /> ]]>
</description>
<pubDate>Thu, 08 Sep 2022 14:40:41 +0000</pubDate>
<link>https://www.tjupt.org/details.php?id=313981&hit=1</link>
<guid isPermaLink="false">01c9523bb9eb63613019f6e58d2bf24e19f2d4bd</guid>
<author>anonymous@www.tjupt.org (anonymous)</author>
<enclosure type="application/x-bittorrent" length="1148679610" url="https://www.tjupt.org/download.php?id=313981&passkey=da8322b23dcfd4d815a0a6681393319c"/>
<comments>https://www.tjupt.org/details.php?id=313981&cmtpage=0#startcomments</comments>
<category>
<![CDATA[ 综艺 ]]>
</category>
<dc:creator>anonymous@www.tjupt.org (anonymous)</dc:creator>
<slash:comments>0</slash:comments>
</item>
<item>
```

## 其他

TMDB中 密室大逃脱 和 密室大逃脱第四版 有不同的tmdbid。

**Comment by Shurelol** [comment]
过滤规则添加排除VIP

**Comment by Eao-Kind** [comment]
> 过滤规则添加排除VIP

感谢，添加过滤规则可以排除不匹配的。
对于这种命名相似的视频，是否有其他便捷的方法可以区分开呢，假设订阅了一部电视剧，一般很难关注到有命名如此相似的另外一部剧。

**Comment by Shurelol** [comment]
> > 过滤规则添加排除VIP
> 
> 感谢，添加过滤规则可以排除不匹配的。 对于这种命名相似的视频，是否有其他便捷的方法可以区分开呢，假设订阅了一部电视剧，一般很难关注到有命名如此相似的另外一部剧。

一般来说有同名会用发布年份来区分，这个剧情况太特殊。

**Comment by Eao-Kind** [comment]
> > > 过滤规则添加排除VIP
> > 
> > 
> > 感谢，添加过滤规则可以排除不匹配的。 对于这种命名相似的视频，是否有其他便捷的方法可以区分开呢，假设订阅了一部电视剧，一般很难关注到有命名如此相似的另外一部剧。
> 
> 一般来说有同名会用发布年份来区分，这个剧情况太特殊。

好吧，确实是情况特殊了。感谢大佬的回复。
