### ISSUE TITLE
[功能新增] 过滤规则 增加 恢复默认 

### ISSUE THREAD

**Issue by link2fun** [jxxghp/nas-tools#1057]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4
> 
> 环境: docker 

## 你想要新增或者改进什么功能？
过滤规则增加 重置(更新) 按钮
### 功能说明
 删除已有规则, 自动将最新的建议规则添加/覆盖到 过滤规则
### 使用场景
1. 不小心改坏(删除)了规则, 还原成默认
2. 建议的过滤规则有更新 好能及时更新

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
最新代码已支持，等更新
