### ISSUE TITLE
系列问题，主要是关于硬链接

### ISSUE THREAD

**Issue by ocean521** [jxxghp/nas-tools#106]
几个问题请教一下各位大神：
1.硬链接过去的就是一个中文名的空文件夹？
日志中存在如下报错“08:20:32 INFO - 【RMT】开始处理：/media/ptdown/千与千寻的神隐.Spirited.Away.2001.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS
08:20:32 INFO - 【RMT】正在转移文件：Spirited.Away.2001.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS.mkv 到 千与千寻 (2001) - 1080p.mkv
08:20:32 ERROR - 【RMT】文件 Spirited.Away.2001.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS.mkv 硬链接失败，错误码：1
08:20:32 INFO - 【RMT】/media/ptdown/千与千寻的神隐.Spirited.Away.2001.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS 处理完成，总数：1，失败：0
08:20:32 ERROR - 【SYNC】/media/ptdown 处理失败：文件转移失败，错误码：1”

2.现阶段是否还不支持存量PT资源硬链接？

3.发现如果下载中途将PT任务删除，之后再次点想看，似乎也不会再次下载；

4.我的网络环境如下：NAS(物理机) + OPENWRT（物理机） +PLEX (在openwrt中配置的DOCKER)，将NAS下载文件夹挂载给OPENWRT,再将OPENWRT的挂载目录分别给PLEX和NASTOOL作为媒体库.
![A441F41E-2F2E-4FC8-A1CB-A5A0EA6E1C05](https://user-images.githubusercontent.com/13881865/167747154-b090ccfe-4229-4fd0-b459-a4fdadca1ff7.png)

**Comment by ocean521** [comment]
根据网友意见调整了一下映射，还是不行
![4B6E6783-D658-4FF1-A71D-89CA74C62DCC](https://user-images.githubusercontent.com/13881865/167782045-1a158938-a53f-40fe-8d2f-5adf46f60211.png)

**Comment by jxxghp** [comment]
这类问题自己研究或者进群求助群友，常见问题WIKI和群置顶都有写，先仔细看完，提issues不合适

**Comment by ocean521** [comment]
好吧，谢谢大佬，如果方便还请帮我分析一下，指点迷津，搞了几天了。始终不得要领，帖子看了好几个了，可能是我网络环境比较特殊，多了一层映射。
