### ISSUE TITLE
关于目录同步无法识别具体集数导致同步失败

### ISSUE THREAD

**Issue by guanyi1024** [jxxghp/nas-tools#1060]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4
>VPS:buyvm 系统:ubantu 20.0.4
> 环境: docker

##你所遇到的问题是什么？

> 首先说一下我的使用过程。我平时看综艺多一些，所以我一般会RSS一些站的综艺看 
但是国内综艺近些年出现了衍生节目，会跟随正剧集一起播出，比如 加更版，超前版，醇享版等
一些VIP可观看内容。这些内容会跟随正剧一起出现在PT站的种子中。命名就有些乱 例如：以S01E01为例
可能会出现以下命名
S01E01SP1，S01SP，S01E01.Extra，S01E01.Plus，S01E01.PartA，S01E01.PartB，S01E01.PartC，S01E01.VIP，
S01E01.Part1，S01E01.Part2，S01E01.Part3，S01E01.EX，S01E01.Pure，S01E01.Special，S01E01.pre，第01期
在我使用目录同步 想将这些节目Rclone到网盘中的时候 会出现如下内容

```
16:46:57 INFO - 【SYNC】开始转移监控目录文件...
16:46:57 INFO - 【RMT】开始处理：/downloads/tv/Chinese.Restaurant.S06.2022.1080p.WEB-DL.H264.AAC-TJUPT，转移方式：Rclone复制
16:46:57 INFO - 【META】正在查询TMDB电视剧：91914 ...
16:46:57 INFO - 【META】Chinese Restaurant 识别到 电视剧：TMDBID=91914, 名称=中餐厅, 首播日期=2017-07-22
16:46:57 ERROR - 【RMT】拼装文件路径错误，无法从文件名中识别出集数：/downloads/tv/Chinese.Restaurant.S06.2022.1080p.WEB-DL.H264.AAC-TJUPT/Chinese.Restaurant.S06SP1.2022.1080p.WEB-DL.H264.AAC-TJUPT.mp4
16:46:57 INFO - 【RMT】/downloads/tv/Chinese.Restaurant.S06.2022.1080p.WEB-DL.H264.AAC-TJUPT 处理完成，总数：1，失败：1
16:46:57 INFO - 【MSG】发送telegram消息：title=/downloads/tv/Chinese.Restaurant.S06.2022.1080p.WEB-DL.H264.AAC-TJUPT 有 1 个文件转移失败，请登录NASTool查看, text=
16:46:58 WARN - 【SYNC】/downloads/tv/Chinese.Restaurant.S06.2022.1080p.WEB-DL.H264.AAC-TJUPT转移失败：识别失败，无法从文件名中识别出集数
```
软件成功识别了节目名字以及是哪一季 但是由于文件名字的花哨 导致无法识别具体集数 最终判定失败 无法转移 这些并没有
像未识别出来是什么节目的那样被转移到unknown文件夹去  由于下载东西比较多 导致得一个夹子一个夹子得去对比看哪些文件
没有被转移

## 你想要新增或者改进什么功能？
> 我希望能改进一下目录同步的判断 
第一种是无法识别具体集数后 将未识别的也按源文件命名转移到unknown文件夹中
第二种就是通过哪一季来判读 因为文件名中季是始终存在的 不判断具体集数 将所有同季的文件都转移到 XXXX（2022）/Season X/下 
这样就不会没有被同步的了
第三种就是 我上面有从我遇到的剧集中筛出来的后缀加入判断中。

突然想到还要重命名 这个地方我就不知道怎么弄了 我一直都是用原始文件名 大部分都可以扫出来(只要带有SXXEXX的都可以)
没有的也就个别S01SP1这种的

还有一个就是能不能增加一个 下载完成的种子完全同步后删除种子的功能

## 这个功能有什么可以参考的资料吗？

> 没有参考资料 就是我从我下载的综艺节目中筛选出来的在季集后面的后缀 应该算是很全了
S01E01SP1，S01SP，S01E01.Extra，S01E01.Plus，S01E01.PartA，S01E01.PartB，S01E01.PartC，S01E01.VIP，
S01E01.Part1，S01E01.Part2，S01E01.Part3，S01E01.EX，S01E01.Pure，S01E01.Special，S01E01.pre，第01期

目前我自己的解决办法是只能关闭识别重命名开关  直接转移到网盘 完了我自己手动改文件夹和文件名字来适配emby 的刮削

如果大佬能看到 能增加一下这个功能最好了 这样完全省去了重命名的时间  

再次感谢大佬能做出这么优秀能解放双手回归看剧的项目！手动点赞！ 点赞！

**Comment by Shurelol** [comment]
![Screenshot_20220910-023106_Chrome](https://user-images.githubusercontent.com/16237201/189420097-e908e34e-65cb-405a-8bf6-7b03e3796088.jpg)
转移失败的记录保存在媒体整理-手动识别这里，手动识别下就好

**Comment by guanyi1024** [comment]
> ![Screenshot_20220910-023106_Chrome](https://user-images.githubusercontent.com/16237201/189420097-e908e34e-65cb-405a-8bf6-7b03e3796088.jpg) 转移失败的记录保存在媒体整理-手动识别这里，手动识别下就好

您是没看明白我的意思  手动识别也是识别不了的~因为他中间可能缺少集数信息 我想的是没有集数有季数的一起移动到文件夹自己手动改名就好了

**Comment by Shurelol** [comment]
> > ![Screenshot_20220910-023106_Chrome](https://user-images.githubusercontent.com/16237201/189420097-e908e34e-65cb-405a-8bf6-7b03e3796088.jpg) 转移失败的记录保存在媒体整理-手动识别这里，手动识别下就好
> 
> 您是没看明白我的意思 手动识别也是识别不了的~因为他中间可能缺少集数信息 我想的是没有集数有季数的一起移动到文件夹自己手动改名就好了

手动识别可以手动定位季和集数
![image](https://user-images.githubusercontent.com/16237201/189492019-88461738-a791-4538-b79f-be368fd13bc5.png)

**Comment by guanyi1024** [comment]
> > > ![Screenshot_20220910-023106_Chrome](https://user-images.githubusercontent.com/16237201/189420097-e908e34e-65cb-405a-8bf6-7b03e3796088.jpg) 转移失败的记录保存在媒体整理-手动识别这里，手动识别下就好
> > 
> > 
> > 您是没看明白我的意思 手动识别也是识别不了的~因为他中间可能缺少集数信息 我想的是没有集数有季数的一起移动到文件夹自己手动改名就好了
> 
> 手动识别可以手动定位季和集数 ![image](https://user-images.githubusercontent.com/16237201/189492019-88461738-a791-4538-b79f-be368fd13bc5.png)

是可以识别季 但是文件名中没有集怎么指定比如说S01SP1这个怎么匹配

**Comment by Shurelol** [comment]
> > > > ![Screenshot_20220910-023106_Chrome](https://user-images.githubusercontent.com/16237201/189420097-e908e34e-65cb-405a-8bf6-7b03e3796088.jpg) 转移失败的记录保存在媒体整理-手动识别这里，手动识别下就好
> > > 
> > > 
> > > 您是没看明白我的意思 手动识别也是识别不了的~因为他中间可能缺少集数信息 我想的是没有集数有季数的一起移动到文件夹自己手动改名就好了
> > 
> > 
> > 手动识别可以手动定位季和集数 ![image](https://user-images.githubusercontent.com/16237201/189492019-88461738-a791-4538-b79f-be368fd13bc5.png)
> 
> 是可以识别季 但是文件名中没有集怎么指定比如说S01SP1这个怎么匹配

没法匹配，因为tmdb里中餐厅的条目既没有专门放sp的第0季，每一季里也没有收入sp。tmdb都没有，怎么匹配？
![image](https://user-images.githubusercontent.com/16237201/189539832-c6f738ac-9fa0-43d6-8aa1-aeda511a19f7.png)
![image](https://user-images.githubusercontent.com/16237201/189539845-6ad16d66-b296-47b3-89b7-861b7512eab8.png)

**Comment by guanyi1024** [comment]
> > > > > ![Screenshot_20220910-023106_Chrome](https://user-images.githubusercontent.com/16237201/189420097-e908e34e-65cb-405a-8bf6-7b03e3796088.jpg) 转移失败的记录保存在媒体整理-手动识别这里，手动识别下就好
> > > > 
> > > > 
> > > > 您是没看明白我的意思 手动识别也是识别不了的~因为他中间可能缺少集数信息 我想的是没有集数有季数的一起移动到文件夹自己手动改名就好了
> > > 
> > > 
> > > 手动识别可以手动定位季和集数 ![image](https://user-images.githubusercontent.com/16237201/189492019-88461738-a791-4538-b79f-be368fd13bc5.png)
> > 
> > 
> > 是可以识别季 但是文件名中没有集怎么指定比如说S01SP1这个怎么匹配
> 
> 没法匹配，因为tmdb里中餐厅的条目既没有专门放sp的第0季，每一季里也没有收入sp。tmdb都没有，怎么匹配？ ![image](https://user-images.githubusercontent.com/16237201/189539832-c6f738ac-9fa0-43d6-8aa1-aeda511a19f7.png) ![image](https://user-images.githubusercontent.com/16237201/189539845-6ad16d66-b296-47b3-89b7-861b7512eab8.png)

是啊 因为没办法匹配所以才想说不匹配的全部在rclone复制的时候一起复制过去 以源文件名复制到unknown文件啊
