### ISSUE TITLE
请问群晖套件版的NAStool能否通过网页更新？

### ISSUE THREAD

**Issue by EliteOtaku** [jxxghp/nas-tools#1062]
## 你使用的 NASTool 是什么版本，什么环境？
> NASTool 版本: v2.0.4
>
> 环境: docker or windows or Synology
>Synology矿神套件版
![image](https://user-images.githubusercontent.com/29235152/189461410-5070a492-d105-46e0-9f24-9d2a8a0c1522.png)

我想问一下，以后矿神套件版的更新，是需要等待矿神那边更新SPK吗？
我试过点击下拉菜单的更新，就是直接重启，如果以后版本升级了，是否能在这里更新？

**Comment by scieny** [comment]
为什么不能添加矿神的源
