### ISSUE TITLE
希望添加新功能，一个订阅资源，除了自动选择下载，添加手动选择来源不同的种子资源

### ISSUE THREAD

**Issue by appotry** [jxxghp/nas-tools#107]
如题，自动选择的，可能不是用户最想要的那个资源。人工选择可以根据种子数目，文件大小，音轨，编码格式，分辨率等等

**Comment by jxxghp** [comment]
不考虑支持，需要这么复杂的应该是用PT助手之类的手动下载，不应该用自动化工具。
