### ISSUE TITLE
不使用豆瓣联想，无法搜索动漫的其他季

### ISSUE THREAD

**Issue by colorsakura** [jxxghp/nas-tools#1073]
![图片](https://user-images.githubusercontent.com/32534829/189485030-2e1e94cf-fe7d-445b-8896-3ae605d8030c.png)

**Comment by Shurelol** [comment]
有没有一种可能，在tmdb里一部剧的所有季都在同一个tmdb id里？你说的的第二季就在第一个结果里？
![Screenshot_20220910_212814](https://user-images.githubusercontent.com/16237201/189485590-9439f15e-9c71-4e1c-9a0d-9de539cf5e2d.jpg)

**Comment by colorsakura** [comment]
> 有没有一种可能，在tmdb里一部剧的所有季都在同一个tmdb id里？你说的的第二季就在第一个结果里？ ![Screenshot_20220910_212814](https://user-images.githubusercontent.com/16237201/189485590-9439f15e-9c71-4e1c-9a0d-9de539cf5e2d.jpg)

是这样，但是搜索出来的结果，没有办法直接按季订阅下载，它默认最新季
我尝试修改下，看作者到时候合并不

**Comment by Shurelol** [comment]
> 是这样，但是搜索出来的结果，没有办法直接按季订阅下载，它默认最新季 我尝试修改下，看作者到时候合并不
要改的话，建议订阅按钮直接跳转到新增订阅界面，而不是直接开始一个订阅
![image](https://user-images.githubusercontent.com/16237201/189485817-17b63323-7adb-4f32-ae3e-1d71ee2e3306.png)

**Comment by jxxghp** [comment]
在搜索框中直接输入xxxx第X季即可，会自动识别的。第x集都行
![image](https://user-images.githubusercontent.com/51039935/189506476-86bbd6e3-4e11-44e4-8b7f-08eab9f35a3e.png)

**Comment by colorsakura** [comment]
实际不是那么好使
![图片](https://user-images.githubusercontent.com/32534829/189506573-64d682b4-a558-4fa1-806e-397d97dd4d46.png)

**Comment by Shurelol** [comment]
搜不到，就用高级搜索，别纠结
![image](https://user-images.githubusercontent.com/16237201/189507782-225825dc-3d9f-4c74-9fdb-1687ddf02737.png)
![image](https://user-images.githubusercontent.com/16237201/189507786-2eee2419-fcf0-42b9-b245-81fa06a012d8.png)
