### ISSUE TITLE
能否在 正在下载 页面中的任务增加一个重新识别电影的选项，用ptpp推送的下载，nastools有时会识别错误

### ISSUE THREAD

**Issue by PoenL** [jxxghp/nas-tools#1078]
![屏幕截图 2022-09-10 232047](https://user-images.githubusercontent.com/74692633/189490241-6d1723e2-b7d6-43da-8d93-3243d60ae5ae.png)

**Comment by Shurelol** [comment]
识别错误的去历史记录里找，然后重新识别
![image](https://user-images.githubusercontent.com/16237201/189491895-c6916cb2-e8c9-49c3-b686-da9108829912.png)
未识别的去手动识别里找，然后重新识别
![image](https://user-images.githubusercontent.com/16237201/189491947-a570dc47-f096-43dc-a84e-c1fba230b5d3.png)

另外请按模板发issue
