### ISSUE TITLE
资源搜索界面无法显示，也无法通过订阅搜索资源

### ISSUE THREAD

**Issue by flywalt** [jxxghp/nas-tools#1079]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v.2.0.4
>
> 环境: Synology
>

## 你遇到什么问题了？是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 点击资源搜索按钮无反应，在其他页面的搜索框里面搜索影片后，点击放大镜搜索，也不会跳转到下载页面，但是会显示搜索资源的浮窗，实时日志也能看到搜索到了资源。比较奇怪的是有一个资源自动就调动了qb下载完成，并且进行了目录同步，但nastool里面没有下载记录

## 你的问题能重现嘛？

> 能够重现

## 你期望的结果

> 解决这一问题

## 给出程序界面截图、后台运行日志或配置文件

> 
<img width="775" alt="bug1" src="https://user-images.githubusercontent.com/56569425/189490442-c4bf305a-bc27-4426-b5de-a819939ca9eb.png">
<img width="624" alt="bug2" src="https://user-images.githubusercontent.com/56569425/189490453-45c45895-b5d9-4179-9aae-63d8f52179b2.png">

<img width="531" alt="bug3" src="https://user-images.githubusercontent.com/56569425/189490459-2adddac1-b660-4c7f-849e-d52f003b7a70.png">

**Comment by ChestnutHeng** [comment]
+1 裂开了

**Comment by flywalt** [comment]
卸载重新安装以后该问题解决，出现新问题是搜索到资源，点击下载后，提示下载任务失败，正在下载也无法看到这个任务，但是在qb中能看到正常在下载
