### ISSUE TITLE
日志问题

### ISSUE THREAD

**Issue by xxzj990** [jxxghp/nas-tools#108]
使用版本：v0.8.09
操作系统：unraid 6.9.1

大佬，现在日志文件不切割了吗？这两天的日志已经14MB了，还是单独的一个文件log.txt，没有按日期分割的文件。太大了，打开有压力～

**Comment by xxzj990** [comment]
![截屏2022-05-11 上午10 02 01](https://user-images.githubusercontent.com/5134154/167753970-61dcc2fc-86cb-43f8-81b4-c7342c53b979.png)

**Comment by xxzj990** [comment]
我看了一下日志内容，从5月8号到现在一直是这一个文件。

**Comment by jxxghp** [comment]
不知道哪里的问题，参数都有送，你更新下再观察下看看。

**Comment by xxzj990** [comment]
> 

好的

**Comment by xxzj990** [comment]
观察了几天，新版本好了～。～
