### ISSUE TITLE
字幕下载无法成功。

### ISSUE THREAD

**Issue by Lolicon-A** [jxxghp/nas-tools#1082]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.0.4
>
> 环境: Synology
>

## 你遇到什么问题了？

> 用OpenSubtitles无法下载字幕，日志里显示调用OpenSubtitles下载对应字幕，但是就没有下文了。既不显示错误提示，也没有成功提示。

> 用ChineseSubFinder，有个bug，可能我网速慢了，.nfo文件下载慢了点，NASTool发给ChineseSubFinder下载字幕老提示缺少.nfo文件，然后我去文件夹里面看，.nfo文件已经下载好了。。。不知道这算不算一个bug。

**Comment by jxxghp** [comment]
现在是生成好了nfo才发通知的。
nastool配置csf时有个路径转换，看下是不是没设对。

**Comment by Lolicon-A** [comment]
> 现在是生成好了nfo才发通知的。
> nastool配置csf时有个路径转换，看下是不是没设对。

路径应该没错吧，我看日志里显示的路径是对的，也没有提示找不到媒体文件

**Comment by sunpjx** [comment]
我也是这样，只有一条前往opensubtitles下载某字幕，然后就没有下文了，只能通过jellyfin的字幕插件手动下载。

**Comment by jxxghp** [comment]
Opensubtitles的问题需要抽空检查下

**Comment by jxxghp** [comment]
#1346
