### ISSUE TITLE
Tmdb显示有31集，订阅返回只有一集

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#1084]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 0dcfd3f19434f54ff63bc52580d6d5a1aadd7bf0
>
> 环境: docker
>

## 你遇到什么问题了？

你安全吗？

这个电视剧我看在tmdb有一季31集

订阅后刷新显示只有一集，然后订阅完成了
![F79C707A-C5A0-4213-B38C-5291F274D4EC](https://user-images.githubusercontent.com/54088512/189534644-114ca45c-51fe-4df7-801e-5d9067e41925.png)
![1893E75A-7448-4EDF-9266-7F9DEC9D9CF1](https://user-images.githubusercontent.com/54088512/189534651-1c7c62b9-4c70-4975-9d5e-16b032261e92.png)

**Comment by jxxghp** [comment]
清下TMDB缓存，估计是TMDB最开始是一集后面被人改正确了
