### ISSUE TITLE
手机端页面顶部显示不出添加订阅按钮

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#1085]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 0dcfd3f19434f54ff63bc52580d6d5a1aadd7bf0
>
> 环境: docker
>

有时候无法上滑到最顶端，例如搜索框，添加订阅，刷新媒体库之类的，
可以下划看到，但会自动回滚，无法点击，且此时最底部版本号能完整展示出来。

还有一种正好相反的情况是能下划到顶部搜索框，订阅按钮，但是底部版本号无法正常显示，可以上滑展示但无法固定。

![8B35F88F-40AE-4944-9091-182CA22D389C](https://user-images.githubusercontent.com/54088512/189535331-6190ccb2-2946-4293-b3d9-a53c7ab6bd8b.png)
![BDCEFFCC-1605-4FA2-8BFF-0B31B621BD22](https://user-images.githubusercontent.com/54088512/189535345-db44223d-24ae-457c-b738-e042fc63619b.png)

**Comment by jxxghp** [comment]
无法重现

**Comment by c939984606** [comment]
chrome手机浏览器确实有这个问题
