### ISSUE TITLE
咨询一件事

### ISSUE THREAD

**Issue by leo8912** [jxxghp/nas-tools#1086]
大佬好
关于过滤规则，有一个情况，因为现在很多电视剧没有4k。如果过滤规则增加1080p保底，那默认下载电影时，因为很多时候都是1080p先出，会导致电影也下1080p的。所以微信/tg/jellyseer等渠道添加订阅后需要到web端再修改一下

所以想问问设置默认规则时，是否可以设置电影一个默认规则，电视剧一个默认规则？

**Comment by jxxghp** [comment]
#1076
