### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by xiangyaoyao** [jxxghp/nas-tools#1089]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4

> 环境: unraid docker

## 你想要新增或者改进什么功能？

建议可以增加一个可以自动生成包含排除规则的功能，比如说给几个选项，包含什么什么，排除什么什么，最后自动生成规则，最后自己把规则填到过滤规则的地方，降低自己写规则的门槛

## 这个功能有什么可以参考的资料吗？

无

**Comment by jxxghp** [comment]
另一个大佬已经增加了模板功能，等更新吧
