### ISSUE TITLE
nfo文件中的资源跨平台无法正常使用

### ISSUE THREAD

**Issue by l552121229** [jxxghp/nas-tools#1093]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4 ae65487
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望可以增加一个选项让生成的nfo中的资源使用相对路径, 现在是绝对路径导致我的资源通过nfs共享给播放盒子后路径不一致无法正常使用

## 这个功能有什么可以参考的资料吗？

> 没有

![Screenshot_1](https://user-images.githubusercontent.com/35548398/189597023-b15e4778-f2df-4970-83a5-ef7fca4ee36b.png)

**Comment by jxxghp** [comment]
<art>并不是nastool生成的，nastool只生成图片，不会把图片路径写到nfo里
