### ISSUE TITLE
下载器115网盘cookies测试永远都是失败

### ISSUE THREAD

**Issue by 521655** [jxxghp/nas-tools#1098]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.5
>
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> 下载器那里115网盘填写cookies测试永远都是失败，已经根据网上的教程填写了正确的cookies

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

>  希望下载器里115网盘可以正常使用

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by leodu0926** [comment]
我也是一样的，测试一直不通

**Comment by leodu0926** [comment]
@521655 更新一下，虽然显示测试失败，实际上115里已经生成了下载任务，可以下载，问题可以关闭
