### ISSUE TITLE
nastools界面直接点更新，升级到2.0.5，内建索引没看到CARPT 和 梓喵，求解

### ISSUE THREAD

**Issue by EdisonXxu** [jxxghp/nas-tools#1099]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.0.5
>
> 环境: docker
>

## 你遇到什么问题了？

> nastools界面直接点更新，升级到2.0.5，内建索引没看到CARPT 和 梓喵，只有rarbg/dmhy和eztv，请问要显示新增的内置索引是要重新安装吗？

**Comment by Shurelol** [comment]
先分清bt和pt
