### ISSUE TITLE
Transmission不支持PT删种

### ISSUE THREAD

**Issue by rockhia** [jxxghp/nas-tools#110]
PT自动删种对Transmission下载器无效
![Screenshot_20220511_185117_net yupol transmissionremote app_edit_17890333824352](https://user-images.githubusercontent.com/90016652/167833802-8d2073bb-971b-4925-8719-a84c67e54f51.jpg)
![Screenshot_20220511_185107_com kevinforeman nzb360](https://user-images.githubusercontent.com/90016652/167833818-ba3fa6eb-cffe-42cd-815b-f54297887d31.jpg)

**Comment by jxxghp** [comment]
你这添加任务都会报超时，确定不是连接不上的原因？

**Comment by rockhia** [comment]
虽然报错但还是正常下载了，这种问题时不时会出现。还没出现过下载失败的情况

**Comment by jxxghp** [comment]
merge了个代码，应该解决了
