### ISSUE TITLE
群晖docker重启自动更新后无法访问登陆界面

### ISSUE THREAD

**Issue by tangougou** [jxxghp/nas-tools#1100]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.05自动更新
>
> 环境:  Synology with docker 
>

## 你遇到什么问题了？

> nastools自动更新后web界面无法访问，重启容器能够登陆，点几下就会卡死，刷新后再也无法访问

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已浏览过issues和wiki，TG群提问有相同案例。

>日志如下
[jxxghp-nas-tools1.csv](https://github.com/jxxghp/nas-tools/files/9548858/jxxghp-nas-tools1.csv)

**Comment by Shurelol** [comment]
![Uploading Screenshot_20220913-080208_Telegram.jpg…]()

**Comment by jxxghp** [comment]
重置后重拉镜像就能解决问题，issues中已关闭的问题中也有
