### ISSUE TITLE
目录同步qb开启.!qB 还是会被上传！

### ISSUE THREAD

**Issue by guanyi1024** [jxxghp/nas-tools#1101]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.5
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 使用rclone复制 目录同步  qb已经开启.!qB  还是会被上传！

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 下载完后再同步

## 给出程序界面截图、后台运行日志或配置文件
![001](https://user-images.githubusercontent.com/60825150/189797379-db81fe83-55b0-4d98-a975-cedd37d6def1.jpg)
![002](https://user-images.githubusercontent.com/60825150/189797398-7b93877b-69ba-47e4-bd4a-ba4fa5861a6c.jpg)
![003](https://user-images.githubusercontent.com/60825150/189797427-6e3b6125-7414-4bf5-904b-60955335c010.jpg)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
没开启识别重命名吧？ 非识别重命名模式所有文件都会同步啊。
自己先搞清楚再提问题。

**Comment by guanyi1024** [comment]
> 没开启识别重命名吧？ 非识别重命名模式所有文件都会同步啊。 自己先搞清楚再提问题。

是没开启识别重命名 目前综艺识别有些识别不了 所以就没开 目前已找到解决办法 qb开启未完成下载到缓存目录 完成后在转移到下载目录就可以了
