### ISSUE TITLE
刷流删种后会反复再次下载

### ISSUE THREAD

**Issue by guanyi1024** [jxxghp/nas-tools#1102]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.5
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 刷流任务设置做种3小时后删种 过段时间下载过的又会被再次下载
补充：貌似我早上起来重启或是更新了一下nastool 是不是重启会导致缓存丢失再次下载

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 解决bug

## 给出程序界面截图、后台运行日志或配置文件

10:57:35 INFO - 【BRUSH】成功添加下载：The Hero S01 2021 1080p WEB-DL H265 AAC-ADWeb[最后的赢家 全10集 | 主演: 李易峰 / 关晓彤 【完结打包】][36.55 GB]

10:57:35 INFO - 【MSG】发送telegram消息：title=【刷流任务 观众综艺 新增下载】, text=种子名称：The Hero S01 2021 1080p WEB-DL H265 AAC-ADWeb[最后的赢家 全10集 | 主演: 李易峰 / 关晓彤 【完结打包】][36.55 GB] 种子大小：36.55G

10:57:36 INFO - 【BRUSH】The Hero S01 2021 1080p WEB-DL H265 AAC-ADWeb[最后的赢家 全10集 | 主演: 李易峰 / 关晓彤 【完结打包】][36.55 GB] 已下载过

10:57:37 INFO - 【SYNC】开始同步 /downloads/zy/最后的赢家.The.Hero.S01.2021.1080p.WEB-DL.H265.AAC-ADWeb/最后的赢家.The.Hero.S01E07.Part2.2021.1080p.WEB-DL.H265.AAC-ADWeb.mp4.!qB

10:57:47 INFO - 【BRUSH】成功添加下载：Between Love and Friendship S01E06 2022 1080p TVING WEB-DL x264 AAC-ADWeb[按照各自的本能 / 각자의 본능대로 / 友愛旅行 第06期 | 类型：真人秀 *内封简繁中字*][3.67 GB]

10:57:47 INFO - 【MSG】发送telegram消息：title=【刷流任务 观众综艺 新增下载】, text=种子名称：Between Love and Friendship S01E06 2022 1080p TVING WEB-DL x264 AAC-ADWeb[按照各自的本能 / 각자의 본능대로 / 友愛旅行 第06期 | 类型：真人秀 *内封简繁中字*][3.67 GB] 种子大小：3.67G

10:57:47 WARN - 【SYNC】/downloads/zy/最后的赢家.The.Hero.S01.2021.1080p.WEB-DL.H265.AAC-ADWeb/最后的赢家.The.Hero.S01E07.Part2.2021.1080p.WEB-DL.H265.AAC-ADWeb.mp4.!qB 同步失败，错误码：256

10:57:47 INFO - 【SYNC】开始同步 /downloads/zy/最后的赢家.The.Hero.S01.2021.1080p.WEB-DL.H265.AAC-ADWeb/最后的赢家.The.Hero.S01E04.Part2.2021.1080p.WEB-DL.H265.AAC-ADWeb.mp4.!qB

10:57:48 INFO - 【BRUSH】Between Love and Friendship S01E06 2022 1080p TVING WEB-DL x264 AAC-ADWeb[按照各自的本能 / 각자의 본능대로 / 友愛旅行 第06期 | 类型：真人秀 *内封简繁中字*][3.67 GB] 已下载过

10:57:59 INFO - 【BRUSH】成功添加下载：The Rap of China S01 2022 1080p WEB-DL H265 AAC-ADWeb[中国说唱巅峰对决 又名: 中国新说唱2022 / 中国新说唱4 / 中国新说唱 第四季 / 中国有嘻哈 第5季 全12期 含加更 *加更期重新命名*【完结打包】][72.65 GB]

10:57:59 INFO - 【MSG】发送telegram消息：title=【刷流任务 观众综艺 新增下载】, text=种子名称：The Rap of China S01 2022 1080p WEB-DL H265 AAC-ADWeb[中国说唱巅峰对决 又名: 中国新说唱2022 / 中国新说唱4 / 中国新说唱 第四季 / 中国有嘻哈 第5季 全12期 含加更 *加更期重新命名*【完结打包】][72.65 GB] 种子大小：72.65G

10:58:00 INFO - 【BRUSH】The Rap of China S01 2022 1080p WEB-DL H265 AAC-ADWeb[中国说唱巅峰对决 又名: 中国新说唱2022 / 中国新说唱4 / 中国新说唱 第四季 / 中国有嘻哈 第5季 全12期 含加更 *加更期重新命名*【完结打包】][72.65 GB] 已下载过

10:58:04 WARN - 【BRUSH】[TV Shows(综艺)][Let It Be 2022 S01E09 1080p WEB-DL H264 AAC-LeagueWEB][牧野家族/亲爱的·客栈/亲爱的客栈 第9集 | 类型:真人秀 主演:王子文/吴永恩/张翰 [国语中字]][2.22 GB] 添加下载任务出错

10:58:04 WARN - 【BRUSH】Ting Shuo Hen Hao Chi 2021 S01 1080p WEB-DL H264 AAC-PTerWEB[听说很好吃 全12集 | 导演：郑也纳 | 主演：王耀庆 孟美岐 林依轮 薛兆丰 颜如晶 [国语中字]][42.56 GB][Free][Top1 Sticky] 添加下载任务出错

10:58:26 INFO - 【BRUSH】成功添加下载：Whats So Wrong With Azatoi S01E73 2020 1080p KKTV WEB-DL x264 AAC-ADWeb[有点心机又如何 / あざとくて何が悪いの？第73期 | 日综][640.65 MB]

10:58:26 INFO - 【MSG】发送telegram消息：title=【刷流任务 观众综艺 新增下载】, text=种子名称：Whats So Wrong With Azatoi S01E73 2020 1080p KKTV WEB-DL x264 AAC-ADWeb[有点心机又如何 / あざとくて何が悪いの？第73期 | 日综][640.65 MB] 种子大小：640.65M

10:58:27 INFO - 【BRUSH】Whats So Wrong With Azatoi S01E73 2020 1080p KKTV WEB-DL x264 AAC-ADWeb[有点心机又如何 / あざとくて何が悪いの？第73期 | 日综][640.65 MB] 已下载过

10:58:32 INFO - 【BRUSH】成功添加下载：Racing Mangers 2022 S01 E07 1080p WEB-DL H264 AAC-PTerWEB[100道光芒 第07期 | 主演: 何炅 汪涵 张阳 [国语中字]][1.97 GB][Free][Top2 Sticky]

10:58:32 INFO - 【MSG】发送telegram消息：title=【刷流任务 猫站综艺 新增下载】, text=种子名称：Racing Mangers 2022 S01 E07 1080p WEB-DL H264 AAC-PTerWEB[100道光芒 第07期 | 主演: 何炅 汪涵 张阳 [国语中字]][1.97 GB][Free][Top2 Sticky] 种子大小：1.97G

10:58:33 INFO - 【BRUSH】Racing Mangers 2022 S01 E07 1080p WEB-DL H264 AAC-PTerWEB[100道光芒 第07期 | 主演: 何炅 汪涵 张阳 [国语中字]][1.97 GB][Free][Top2 Sticky] 已下载过

10:58:49 INFO - 【SYNC】/downloads/zy/最后的赢家.The.Hero.S01.2021.1080p.WEB-DL.H265.AAC-ADWeb/最后的赢家.The.Hero.S01E04.Part2.2021.1080p.WEB-DL.H265.AAC-ADWeb.mp4.!qB 同步完成

10:58:49 INFO - 【SYNC】开始同步 /downloads/zy/最后的赢家.The.Hero.S01.2021.1080p.WEB-DL.H265.AAC-ADWeb/最后的赢家.The.Hero.S01E10.Part1.2021.1080p.WEB-DL.H265.AAC-ADWeb.mp4.!qB

10:59:06 WARN - 【SYNC】/downloads/zy/最后的赢家.The.Hero.S01.2021.1080p.WEB-DL.H265.AAC-ADWeb/最后的赢家.The.Hero.S01E10.Part1.2021.1080p.WEB-DL.H265.AAC-ADWeb.mp4.!qB 同步失败，错误码：256

10:59:06 INFO - 【SYNC】开始同步 /downloads/zy/Between.Love.and.Friendship.S01.2022.1080p.TVING.WEB-DL.x264.AAC-ADWeb/Between.Love.and.Friendship.S01E06.2022.1080p.TVING.WEB-DL.x264.AAC-ADWeb.mkv.!qB

10:59:15 WARN - 【SYNC】/downloads/zy/Between.Love.and.Friendship.S01.2022.1080p.TVING.WEB-DL.x264.AAC-ADWeb/Between.Love.and.Friendship.S01E06.2022.1080p.TVING.WEB-DL.x264.AAC-ADWeb.mkv.!qB 同步失败，错误码：256

10:59:15 INFO - 【SYNC】开始同步 /downloads/zy/中国说唱巅峰对决.The.Rap.of.China.S01.2022.1080p.WEB-DL.H265.AAC-ADWeb/中国说唱巅峰对决.The.Rap.of.China.S01E06.Part1.2022.1080p.WEB-DL.H265.AAC-ADWeb.mp4.!qB

10:59:53 INFO - 【BRUSH】成功添加下载：Xi Yu Zhou S01E10 2022 1080p WEB-DL H265 AAC-ADWeb[戏宇宙 第10期 | 类型: 歌舞 制片国家/地区: 中国大陆][2.09 GB]

10:59:53 INFO - 【MSG】发送telegram消息：title=【刷流任务 观众综艺 新增下载】, text=种子名称：Xi Yu Zhou S01E10 2022 1080p WEB-DL H265 AAC-ADWeb[戏宇宙 第10期 | 类型: 歌舞 制片国家/地区: 中国大陆][2.09 GB] 种子大小：2.09G

10:59:54 INFO - 【BRUSH】Xi Yu Zhou S01E10 2022 1080p WEB-DL H265 AAC-ADWeb[戏宇宙 第10期 | 类型: 歌舞 制片国家/地区: 中国大陆][2.09 GB] 已下载过

11:00:01 WARN - 【BRUSH】[TV Shows(综艺)][Qi Xi Qi Miao You 2022 2160p WEB-DL H265 AAC-LeagueWEB][2022七夕奇妙游 全1集 类型: 综艺/晚会/真人秀 主演: 张杰/刘丰/厦门六中合唱团 [国语/中英双语硬字] | *4K*有台标*][1.11 GB] 添加下载任务出错

11:00:25 INFO - 【SYNC】/downloads/zy/中国说唱巅峰对决.The.Rap.of.China.S01.2022.1080p.WEB-DL.H265.AAC-ADWeb/中国说唱巅峰对决.The.Rap.of.China.S01E06.Part1.2022.1080p.WEB-DL.H265.AAC-ADWeb.mp4.!qB 同步完成

11:00:25 INFO - 【SYNC】开始同步 /downloads/zy/最后的赢家.The.Hero.S01.2021.1080p.WEB-DL.H265.AAC-ADWeb/最后的赢家.The.Hero.S01E08.Part1.2021.1080p.WEB-DL.H265.AAC-ADWeb.mp4.!qB

11:00:46 INFO - 【BRUSH】成功添加下载：Go Fighting S08E11 2022 1080p WEB-DL H.265 AAC-ADWeb[极限挑战 第八季 第11期 主演: 王迅 / 岳云鹏 / 贾乃亮 / 郭京飞 / 黄明昊 / 黄景瑜 / 杨超越 / 龚俊][3.14 GB]

11:00:46 INFO - 【MSG】发送telegram消息：title=【刷流任务 观众综艺 新增下载】, text=种子名称：Go Fighting S08E11 2022 1080p WEB-DL H.265 AAC-ADWeb[极限挑战 第八季 第11期 主演: 王迅 / 岳云鹏 / 贾乃亮 / 郭京飞 / 黄明昊 / 黄景瑜 / 杨超越 / 龚俊][3.14 GB] 种子大小：3.14G

11:00:47 INFO - 【BRUSH】Go Fighting S08E11 2022 1080p WEB-DL H.265 AAC-ADWeb[极限挑战 第八季 第11期 主演: 王迅 / 岳云鹏 / 贾乃亮 / 郭京飞 / 黄明昊 / 黄景瑜 / 杨超越 / 龚俊][3.14 GB] 已下载过

11:01:42 WARN - 【BRUSH】Masked Dancer 2022 S03E10 2160p WEB-DL H265 AAC-PTerWEB[蒙面舞王第3季 会员版 第10期 | 主演: 张纯烨 张信哲 [国语中字]4K版][3.86 GB][50%][None Sticky] 添加下载任务出错

11:01:43 INFO - 【BRUSH】成功添加下载：China Restaurant S06E05 2022 1080p WEB-DL H264 AAC-ADWeb[中餐厅 第六季 第5期 1080p 主演: 黄晓明 / 殷桃 / 陈立农][1.74 GB]

11:01:43 INFO - 【MSG】发送telegram消息：title=【刷流任务 观众综艺 新增下载】, text=种子名称：China Restaurant S06E05 2022 1080p WEB-DL H264 AAC-ADWeb[中餐厅 第六季 第5期 1080p 主演: 黄晓明 / 殷桃 / 陈立农][1.74 GB] 种子大小：1.74G

11:01:44 INFO - 【BRUSH】China Restaurant S06E05 2022 1080p WEB-DL H264 AAC-ADWeb[中餐厅 第六季 第5期 1080p 主演: 黄晓明 / 殷桃 / 陈立农][1.74 GB] 已下载过

11:02:17 INFO - 【BRUSH】成功添加下载：China Restaurant S06E02 2022 1080p WEB-DL H264 AAC-ADWeb[中餐厅 第六季 直拍 第2期 1080p 主演: 黄晓明 / 殷桃 / 陈立农][478.98 MB]

11:02:17 INFO - 【MSG】发送telegram消息：title=【刷流任务 观众综艺 新增下载】, text=种子名称：China Restaurant S06E02 2022 1080p WEB-DL H264 AAC-ADWeb[中餐厅 第六季 直拍 第2期 1080p 主演: 黄晓明 / 殷桃 / 陈立农][478.98 MB] 种子大小：478.98M

11:02:17 INFO - 【BRUSH】China Restaurant S06E02 2022 1080p WEB-DL H264 AAC-ADWeb[中餐厅 第六季 直拍 第2期 1080p 主演: 黄晓明 / 殷桃 / 陈立农][478.98 MB] 已下载过

11:02:18 INFO - 【BRUSH】任务 观众综艺 本次添加了 8 个下载

11:02:23 WARN - 【BRUSH】[TV Shows(综艺)][Qi Xi Qi Miao You 2022 1080p WEB-DL H264 AAC-LeagueWEB][2022七夕奇妙游 | 主演: 张杰/刘丰/石容山/厦门六中合唱团 [国语/中英双语硬字] | *有台标*][2.79 GB] 添加下载任务出错

11:02:33 INFO - 【SYNC】/downloads/zy/最后的赢家.The.Hero.S01.2021.1080p.WEB-DL.H265.AAC-ADWeb/最后的赢家.The.Hero.S01E08.Part1.2021.1080p.WEB-DL.H265.AAC-ADWeb.mp4.!qB 同步完成

11:02:33 INFO - 【SYNC】开始同步 /downloads/zy/最后的赢家.The.Hero.S01.2021.1080p.WEB-DL.H265.AAC-ADWeb/最后的赢家.The.Hero.S01E10.Part3.2021.1080p.WEB-DL.H265.AAC-ADWeb.mp4.!qB

11:02:47 WARN - 【BRUSH】Masked Dancer 2022 S03E10 1080p WEB-DL H264 AAC-PTerWEB[蒙面舞王第3季 会员版 第10期 | 主演: 张纯烨 张信哲 [国语中字]][1.52 GB][50%][None Sticky] 添加下载任务出错

11:03:08 WARN - 【BRUSH】[TV Shows(综艺)][Shao Nian Qi Miao You 2022 1080p WEB-DL H264 AAC-LeagueWEB][少年奇妙游 *网易大话西游携手河南卫视* 全1集 | 类型: 剧情/动作/奇幻/冒险/武侠/古装 [国语中字] | *高码*有台标*][16.93 GB] 添加下载任务出错

> 如UI BUG请提供截图及配置文件截图
![005](https://user-images.githubusercontent.com/60825150/189800236-3d7e2ab3-3b4a-4e06-8464-2307c44f1760.png)
![006](https://user-images.githubusercontent.com/60825150/189800465-a14c3fb4-3309-402f-a4c2-0805da588707.png)

> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
1.重启缓存会丢失。
2.刷全部真勇敢，看清楚说明，别刷爆了。

**Comment by guanyi1024** [comment]
> 1.重启缓存会丢失。 2.刷全部真勇敢，看清楚说明，别刷爆了。

感谢大佬回复~明白了
刷爆不存在的 我自己能把握 感谢提醒~
