### ISSUE TITLE
希望能增加音乐、专辑自动订阅功能

### ISSUE THREAD

**Issue by EliteOtaku** [jxxghp/nas-tools#1103]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.05
>
> 环境: synology

## 你想要新增或者改进什么功能？

> 目前我也用Emby来管理音乐，但目前群晖上的音乐下载功能都比较麻烦，需要自己去折腾搜索、识别之类的，如果NAStool能把这一块整合起来就好了，已经可以比较方便的订阅电影，那就可以用同样的方法处理音乐。比如自己喜欢的歌手出了新专辑，就可以方便的订阅，这样后台管理起来就容易了。

## 这个功能有什么可以参考的资料吗？

> https://www.v2ex.com/t/878015 我看过一个V2EX的网友这样整理的，虽然自己也可以做到，但部署起来还是比较麻烦，如果整合起来就好了。比如网易云音乐现在还有自有NCM格式，如果能批量转为MP3之类可以识别的就好了。

**Comment by netduke777** [comment]
这个估计不好实现,现在音乐被国企鹅管理的,比片子难多了, 几个私链也都是要钱的,只是钱不多罢了 , 现在音乐下载太难了. 手里现在的基础还是电驴还在的时候下载的那些, 多少年没有批量更新了

**Comment by EliteOtaku** [comment]
> 这个估计不好实现,现在音乐被国企鹅管理的,比片子难多了, 几个私链也都是要钱的,只是钱不多罢了 , 现在音乐下载太难了. 手里现在的基础还是电驴还在的时候下载的那些, 多少年没有批量更新了

是的，目前我看到比较简单的方案是ROON的，但价钱不便宜。

自己用的是网易云音乐，感觉要不然集成一个工具，比如用自己的音乐平台ID（QQor网易or咪咕or apple music之类）登录后，可以把音乐库里面的自动同步到NAS里面，这样万一后面灰了的话，NAS里面的不受影响。这样算是比较折衷的方法吧？

**Comment by Shurelol** [comment]
> > 这个估计不好实现,现在音乐被国企鹅管理的,比片子难多了, 几个私链也都是要钱的,只是钱不多罢了 , 现在音乐下载太难了. 手里现在的基础还是电驴还在的时候下载的那些, 多少年没有批量更新了
> 
> 是的，目前我看到比较简单的方案是ROON的，但价钱不便宜。
> 
> 自己用的是网易云音乐，感觉要不然集成一个工具，比如用自己的音乐平台ID（QQor网易or咪咕or apple music之类）登录后，可以把音乐库里面的自动同步到NAS里面，这样万一后面灰了的话，NAS里面的不受影响。这样算是比较折衷的方法吧？

github上有相关项目，建议找找

**Comment by EliteOtaku** [comment]
> > > 这个估计不好实现,现在音乐被国企鹅管理的,比片子难多了, 几个私链也都是要钱的,只是钱不多罢了 , 现在音乐下载太难了. 手里现在的基础还是电驴还在的时候下载的那些, 多少年没有批量更新了
> > 
> > 
> > 是的，目前我看到比较简单的方案是ROON的，但价钱不便宜。
> > 自己用的是网易云音乐，感觉要不然集成一个工具，比如用自己的音乐平台ID（QQor网易or咪咕or apple music之类）登录后，可以把音乐库里面的自动同步到NAS里面，这样万一后面灰了的话，NAS里面的不受影响。这样算是比较折衷的方法吧？
> 
> github上有相关项目，建议找找

请问有什么线索吗？我不太熟悉github。如果可以的话，请私信我，谢谢。
