### ISSUE TITLE
希望增加适配刷流或者说下载请求下多分辨率多编码归档或者直接覆盖（有些影片并不会4k和1080p同时出，又不是订阅的）

### ISSUE THREAD

**Issue by zhattyt** [jxxghp/nas-tools#1104]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.5
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

**想改进一下这个高质量入库覆盖功能和手动识别功能。还有个想法，能否增加未识别文件删除功能，针对很多刮削不到，自己也不需要不想看的片，直接在手动识别里直接删除源文件**

1.我发现在刷流时下载4k不同编码同一个片子，他是会用同一个刮削，重名命名先入库的，后面入库的就会在有几个文件的基础上，不断加几遍名称，而不会像搜索或者请求时会洗版，而且没有开关或者说功能在刮削整理、目录同步对文件进行洗版或者归档一个文件夹，不知道可否有建议的配置或者操作？

例如：第一个是wish (2020)，第二个是 wish wish (2020)，第三个就会变成 wish wish wish (2020)这样。

希望适配不同编码只适配名字、分辨率、（编码或者其他筛选条件）和大小这几个条件（当然如果能自定义最好，但是功能就复杂了）。

建议是直接将同名称下不同编码不同分辨率直接归入一个文件夹。

2.手动识别只支持tmdb这个感觉选项太窄了，其实有些时候他没有翻译片名的时候，可以提供豆瓣信息或者imdb选项，有些英文并不会影响什么，换句话说tmdb对于非英语系和冷门片支持的并不好。

## 这个功能有什么可以参考的资料吗？

暂时没有参考资料，总感觉以前在哪里见过，但是又不记得，以前都是手动的拷贝的多。

**Comment by Shurelol** [comment]
建议您能提供可用的豆瓣和imdb的api

**Comment by jxxghp** [comment]
问题1给个图和日志
