### ISSUE TITLE
媒体库同步数量为0，热门电影状态不显示心形颜色

### ISSUE THREAD

**Issue by wangrui1573** [jxxghp/nas-tools#1107]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.5，emby 4.7.6.0
>
> 环境: docker 
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

2.0.4之前热门电影会显示媒体库状态，升级2.0.5后全不显示，手动同步瞬间完成显示为0
但首页emby播放记录，媒体库电影、电视机、动漫数量正常

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是，我尝试手动删除media.db,user.db 均不支持

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果
全部同步

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图

![image](https://user-images.githubusercontent.com/42831156/189817097-dbd83ff3-02b8-4bd9-8e43-619a7e91e14b.png)
·
![image](https://user-images.githubusercontent.com/42831156/189817123-a1cb625c-6a6a-42de-bbe7-7f227f063f9c.png)
![image](https://user-images.githubusercontent.com/42831156/189817144-c5f55371-d1ed-4c36-a033-f6b2e76b9e35.png)

> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

tail -n 20 logs/supervisor/nas-tools-stdout---supervisor-lr_diy40.log
    Rss.rsssearch_all (trigger: interval[1800 days, 0:00:00], pending)
    DouBan.sync (trigger: interval[1:00:00], pending)
    MediaServer.sync_mediaserver (trigger: interval[4:00:00], pending)
    Config.init_config (trigger: interval[0:10:00], pending)
    MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
    Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
    Rss.rsssearch (trigger: interval[0:05:00], pending)
    Sites.refresh_pt_date_now (trigger: interval[6:00:00], pending)
    Rss.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
    MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
    get_login_wallpaper (trigger: interval[1:00:00], pending)
当前日期：20220913
 * Serving Flask app 'web.main'
 * Debug mode: off
2022-09-13 13:32:16,808 INFO: 【MEDIASERVER】开始同步媒体库数据...
2022-09-13 13:32:17,020 INFO: 【MEDIASERVER】媒体库数据同步完成，同步数量：0
2022-09-13 13:34:29,505 INFO: 【MEDIASERVER】开始同步媒体库数据...
2022-09-13 13:34:29,719 INFO: 【MEDIASERVER】媒体库数据同步完成，同步数量：0
2022-09-13 13:34:32,608 INFO: 【MEDIASERVER】开始同步媒体库数据...
2022-09-13 13:34:32,792 INFO: 【MEDIASERVER】媒体库数据同步完成，同步数量：0

**Comment by wangrui1573** [comment]
![image](https://user-images.githubusercontent.com/42831156/189818347-6d37859c-ceca-4458-afe7-a5b76654e9cc.png)

**Comment by jxxghp** [comment]
emby里媒体库的设置截图看看，是不是有什么特殊的

**Comment by ati121** [comment]
> emby里媒体库的设置截图看看，是不是有什么特殊的

我测试下来也有同样的问题..一个媒体库在单硬盘上的会正确显示..一个媒体库分开在多个硬盘上的就会出现这样的情况

**Comment by jxxghp** [comment]
我无法重现，需要提供Emby媒体库的设置情况，应该是跟媒体库设置有关。

**Comment by ati121** [comment]
EMBY媒体库 share跟share3 分别在2个不同的硬盘上
![e3](https://user-images.githubusercontent.com/72114654/190861563-79b21dbc-79d6-46ed-bf83-3c1f56a2a742.jpg)
nastools媒体库
![66](https://user-images.githubusercontent.com/72114654/190861577-37f330aa-1322-4fbf-9a56-e5a841db23a1.jpg)
已经点了同步后的nastools界面雷神跟坠落库里都有不显示勾.
![9](https://user-images.githubusercontent.com/72114654/190861593-3354f73b-8a38-4b5c-a10a-0df5dcce704a.jpg)

**Comment by wangrui1573** [comment]
我也是媒体库多硬盘 多路径

**Comment by ZevAlain** [comment]
我是单路径，也不行

**Comment by sleikang** [comment]
![image](https://user-images.githubusercontent.com/23020770/190888579-9dd87498-5b55-4674-9050-c85247b4bc14.png)
@jxxghp 遍历媒体库应该才有递归函数 如果是文件夹应该递归进入再次遍历，可以参考https://github.com/sleikang/EmbyChineseNameSynchronous/blob/main/media.py我项目的__check_media_info__函数

**Comment by sleikang** [comment]
更新后测试还是无法同步每次同步只同步了17部电视剧
![image](https://user-images.githubusercontent.com/23020770/191017717-384d4a60-02f1-4a53-8739-6f396dfffc87.png)

**Comment by wangrui1573** [comment]
更新后测试还是无法同步，还是为0，重建了一台空的emby服务器可以，放弃了。。。

**Comment by sleikang** [comment]
> 更新后测试还是无法同步，还是为0，重建了一台空的emby服务器可以，放弃了。。。
> 
> 

我提交的版本已经可以了，但是作者目前考虑到进度条在获取emby媒体的时候不会刷新没有合并

**Comment by reorx** [comment]
打扰一下各位，请教下「媒体库同步 」这个功能的作用究竟是什么，我点了一下显示从我的 Plex 里同步了 65 个，但 nas-tools 的界面没找到任何一处显示这些媒体或者有什么变化…
