### ISSUE TITLE
新功能请求：自动刷新指定媒体库

### ISSUE THREAD

**Issue by Hazard804** [jxxghp/nas-tools#1109]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.5
>
> 环境: docker

> 你想要新增或者改进什么功能？

>由于采用rclone挂载gd的方式存储视频资源，文件系统不受支持，emby实时监控媒体库功能无法使用，因此希望能够增加刷新**指定**媒体库的功能，而不是直接全部刷新，在emby资源较多的情况下会耗费很长的时间。

## 这个功能有什么可以参考的资料吗？

未发现其他参考资料。
但是有一个设想：通过抓取绑定的emby客户端中**扫描媒体库文件**这一选项的链接，在创建新的影片订阅时添加选项，选择需要刷新的媒体库，在相应影片转移完成后将上面获取到的链接post出去，从而实现自动刷新指定媒体库。另外由于rclone同步可能需要一些时间，可以设定一个延迟时间。

感谢！

**Comment by Hazard804** [comment]
发现emby api文档中有相应的功能 
![image](https://user-images.githubusercontent.com/82299110/189905205-7e3e74d6-902e-44d6-931d-89e316dffad3.png)

**Comment by Hazard804** [comment]
> ![image](https://user-images.githubusercontent.com/16237201/190015204-80c78251-bcba-4cb1-88ac-76ab832b6f6a.png)

这个是刷新的全部媒体库吧？

**Comment by Shurelol** [comment]
> > ![image](https://user-images.githubusercontent.com/16237201/190015204-80c78251-bcba-4cb1-88ac-76ab832b6f6a.png)
> 
> 这个是刷新的全部媒体库吧？

看代码，可能是全部刷新么？
