### ISSUE TITLE
电视剧分季重复的问题

### ISSUE THREAD

**Issue by Travel2Here** [jxxghp/nas-tools#1110]
不知是我个人设置的问题还是咱们工具的问题 麻烦大佬解析一下。
现象：使用的jellyfin管理，实际存储只有一份视频，电视剧会出现两个“季文件夹” 有时候封面不同 我怀疑是来自两个meta源（比如tmdb和tvdb）
难道媒体库获取meta信息不能多选来源？不应该是这逻辑吧 谢谢
（删除各剧文件夹中的nfo后再拉取依然重现）

↓两个例子
![image](https://user-images.githubusercontent.com/99887507/189862112-8a6ac2db-bfba-4f08-8065-d34bc22d13d2.png)

![image](https://user-images.githubusercontent.com/99887507/189862675-12bd3bd8-f5af-4e75-be3f-68869f2df7b7.jpeg)

↓媒体库设置
![image](https://user-images.githubusercontent.com/99887507/189862728-110b73e7-7eed-46fa-8b3c-a15462bb82f8.png)

**Comment by jxxghp** [comment]
这个跟本工具应该没关系

**Comment by Travel2Here** [comment]
> 这个跟本工具应该没关系

好吧，可能是jellyfin的问题，发完这issue后搜到一些国外用户吐槽它其他类目（音乐）的重复问题。
但暂无找到解，如果有其他哥们研究到了麻烦分享下~
