### ISSUE TITLE
【功能请求】刷流任务支持自定义rss链接

### ISSUE THREAD

**Issue by Pollo3470** [jxxghp/nas-tools#1113]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.5
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 刷流支持使用自定义的rss链接。
>拿我举例，我的站点管理里的rss订阅是筛选了电影和剧集且排除了原盘的，在刷流任务中则无此必要，且很多下载人数较多的种子都是原盘。
>希望可以在刷流任务中使用单独的rss订阅

**Comment by Shurelol** [comment]
站点rss订阅链接建议不要做过滤，设置里有专门的过滤规则可以进行原盘等的过滤。
![image](https://user-images.githubusercontent.com/16237201/190014347-11e5a98c-97bd-4a72-bdf5-7d4749bee93a.png)

**Comment by Pollo3470** [comment]
> 站点rss订阅链接建议不要做过滤，设置里有专门的过滤规则可以进行原盘等的过滤。 ![image](https://user-images.githubusercontent.com/16237201/190014347-11e5a98c-97bd-4a72-bdf5-7d4749bee93a.png)

那rss能否过滤官种

**Comment by Shurelol** [comment]
> > 站点rss订阅链接建议不要做过滤，设置里有专门的过滤规则可以进行原盘等的过滤。 ![image](https://user-images.githubusercontent.com/16237201/190014347-11e5a98c-97bd-4a72-bdf5-7d4749bee93a.png)
> 
> 那rss能否过滤官种

自己可以加正则，想怎么过滤怎么过滤，官种写包含官组的正则就行

**Comment by Pollo3470** [comment]
好的，之前担心种子数量过多导致检查间隙会有种子直接被挤掉，不过似乎一天也不会发这么多种，感谢解答
