### ISSUE TITLE
刷流功能在手动删除种子后，总体积统计错误，希望可以修复或者添加重置刷流任务功能

### ISSUE THREAD

**Issue by JJJDand** [jxxghp/nas-tools#1115]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本:2.0.5
>
> 环境: docker
>

## 你遇到什么问题了？

> 刷流功能在手动删除种子后（有可能死种之类的，或者不想要的种子），总体积统计错误。举例导致实际上qb上1000g的种子，手动删除500g以后，刷流统计仍然是1000g，导致不能继续新增下载。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的

## 你期望的结果

> 希望刷流统计是正确的，不好修的话希望增加重置刷流的功能，把数据库清一清。

## 给出程序界面截图、后台运行日志或配置文件

> 15:55:54 INFO - 【BRUSH】开始站点 Audiences 的刷流任务：Audiences...
15:55:54 INFO - 【BRUSH】开始站点 HDFans 的刷流任务：HDFans...
15:55:54 INFO - 【BRUSH】开始站点 HDTime 的刷流任务：HDTime...
15:55:54 WARN - 【BRUSH】刷流任务 Audiences 已达到保种体积 800GB，不再新增下载
15:55:54 WARN - 【BRUSH】刷流任务 HDFans 已达到保种体积 200GB，不再新增下载
15:55:54 WARN - 【BRUSH】刷流任务 HDTime 已达到保种体积 300GB，不再新增下载

**Comment by Pollo3470** [comment]
同样的问题，希望能完善一下

**Comment by eadorothy86** [comment]
同样问题，希望作者能配置一下

**Comment by alkalixin** [comment]
同样的问题，希望能完善一下

**Comment by jxxghp** [comment]
己支持
