### ISSUE TITLE
目录同步使用非默认的文件转移方式，刮削失败后，手动识别会使用默认的文件转移方式

### ISSUE THREAD

**Issue by xuanqb** [jxxghp/nas-tools#1117]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.5 d14fcf6
>
> 环境: docker 
>

## 你遇到什么问题了？

> 目录同步使用的文件转移方式是：移动，刮削失败后，手动识别会使用默认的文件转移方式：硬链接

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 手动识别时 使用目录同步配置的文件转移方式

## 给出程序界面截图、后台运行日志或配置文件

目录同步

> 2022-09-14 17:03:12,961	INFO: 【SYNC】读取到监控目录：/mnt/share/volume2/download2/Aliyun_rclone/待识别/tv，目的目录：/mnt/share/volume2/download2/Aliyun_rclone/tv，转移方式：移动
> 2022-09-14 17:03:12,969	INFO: 【RUN】/mnt/share/volume2/download2/Aliyun_rclone/待识别/tv 的监控服务启动...
> 2022-09-14 17:03:21,036	INFO: 【RMT】开始处理：/mnt/share/volume2/download2/Aliyun_rclone/待识别/tv/脱口秀大会，转移方式：移动
> 2022-09-14 17:03:21,101	ERROR: 【RMT】0913第3期上_Coolapk_Tacit0924.mp4 无法识别媒体信息！
> 2022-09-14 17:03:21,102	INFO: 【RMT】/mnt/share/volume2/download2/Aliyun_rclone/待识别/tv/脱口秀大会 处理完成，总数：6，失败：6
> 2022-09-14 17:03:21,102	INFO: 【MSG】发送wechat消息：title=/mnt/share/volume2/download2/Aliyun_rclone/待识别/tv/脱口秀大会 有 6 个文件转移失败，请登录NASTool查看, text=
> 2022-09-14 17:03:21,695	ERROR: 【SYNC】/mnt/share/volume2/download2/Aliyun_rclone/待识别/tv 处理失败：无法识别媒体信息

手动识别

> 2022-09-14 17:03:57,807	INFO: 【META】正在查询TMDB电视剧：93509 ...
> 2022-09-14 17:03:57,833	INFO: 【RMT】开始处理：/mnt/share/volume2/download2/Aliyun_rclone/待识别/tv/脱口秀大会，转移方式：硬链接
> 2022-09-14 17:03:57,836	DEBUG: 【RMT】文件清单：['/mnt/share/volume2/download2/Aliyun_rclone/待识别/tv/脱口秀大会/0830第1期上_Coolapk_Tacit0924.mp4']
> 2022-09-14 17:03:58,062	INFO: 【RMT】正在转移文件：0830第1期上_Coolapk_Tacit0924.mp4 到 /mnt/share/volume2/download2/Aliyun_rclone/tv/脱口秀大会 (2017)/Season 5/脱口秀大会 - S05E01 - 第1集.mp4
> 2022-09-14 17:03:58,065	ERROR: 【RMT】文件 0830第1期上_Coolapk_Tacit0924.mp4 硬链接失败，错误码 256

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Shurelol** [comment]
默认文件转移方式不是可以改么？？

**Comment by xuanqb** [comment]
> 



> 默认文件转移方式不是可以改么？？

qb下载的用的默认硬链接 
这个报错是阿里云盘的  ，改默认转移方式， qb下载的就不适用了

**Comment by Shurelol** [comment]
> > 
> 
> > 默认文件转移方式不是可以改么？？
> 
> qb下载的用的默认硬链接 这个报错是阿里云盘的 ，改默认转移方式， qb下载的就不适用了

手动完了改回来呀，总不能刚好那么巧，就在手动识别的时候，就有在qb下好的在转移

**Comment by jxxghp** [comment]
己支持
