### ISSUE TITLE
刷流任务CHD无法过滤free种

### ISSUE THREAD

**Issue by Pollo3470** [jxxghp/nas-tools#1118]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.5
>
> 环境: docker
>

## 你遇到什么问题了？

> 刷流任务即使设置了过滤free种，CHD仍会下载非free种

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

>是

## 你期望的结果

> 能有效过滤free种

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Pollo3470** [comment]
一个没注意给下了200多g，直接变peasant

**Comment by jxxghp** [comment]
提供下相关数据，群里之前发过文档

**Comment by Pollo3470** [comment]
请问需要什么数据，没在群里找到

**Comment by jxxghp** [comment]
[协助NASTool支持更多FREE站点检测.zip](https://github.com/jxxghp/nas-tools/files/9584373/NASTool.FREE.zip)

**Comment by Pollo3470** [comment]
已在tg汇报

**Comment by Pollo3470** [comment]
大佬，我看到dev分支里的chd free判断规则并没有变，但这样是没法有效排除非free种的
