### ISSUE TITLE
 使用“目录同步"且移动方式为”移动“同步文件时，文件就消失。

### ISSUE THREAD

**Issue by LGuangming** [jxxghp/nas-tools#1120]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.5
> v2.0.5

> 环境: 
>QNAP-docker

## 你遇到什么问题了？

> 使用“目录同步"且移动方式为”移动“同步文件时，会有几率移动失败，这个文件就消失了。

>已经浏览过Issues、Wiki及TG公众号无法解决

## 你期望的结果

> 移动文件时

不丢失文件

## 给出程序界面截图、后台运行日志或配置文件
![fail](https://user-images.githubusercontent.com/51586004/190159904-6bd39511-e8d1-49b7-b0a4-131bb623709f.jpg)

框出的文件最终就消失了

**Comment by huluohu** [comment]
跨盘了吧，NAS中不同的共享文件夹视为跨盘，转移会消失🫠

**Comment by ati121** [comment]
测试了几次..确实有这样的问题.如果下载连续剧直接到监控目录,比如1.mkv先下载完,就会识别转移,然后nastool就会认为这个目录为空,直接删除文件夹..后面的所有.!qB 后缀未下载完的就直接被删除了..日志里面就会出现移动失败的错误..
![3](https://user-images.githubusercontent.com/72114654/190535551-a18a514b-976b-46af-8bfb-94fae465645d.jpg)
如图,上面只下载完成了3集,其他的其实还在下载中.目录就被删除了..

**Comment by huluohu** [comment]
> 测试了几次..确实有这样的问题.如果下载连续剧直接到监控目录,比如1.mkv先下载完,就会识别转移,然后nastool就会认为这个目录为空,直接删除文件夹..后面的所有.!qB 后缀未下载完的就直接被删除了..日志里面就会出现移动失败的错误.. ![3](https://user-images.githubusercontent.com/72114654/190535551-a18a514b-976b-46af-8bfb-94fae465645d.jpg) 如图,上面只下载完成了3集,其他的其实还在下载中.目录就被删除了..

像是个bug

**Comment by huluohu** [comment]
你改成硬链接试试，不会删种
