### ISSUE TITLE
2.0.5中无法和jackett测试成功

### ISSUE THREAD

**Issue by lswang6** [jxxghp/nas-tools#1123]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.5
>
> 环境: 威联通5.0 Container
>

## 无法和jackett通信，测试不成功

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是的

**Comment by jxxghp** [comment]
是不是没维护索引，jackett里有索引才能测试成功

**Comment by lswang6** [comment]
> 是不是没维护索引，jackett里有索引才能测试成功

对头，现在维护了索引，测试成功了！感谢！！！
