### ISSUE TITLE
订阅剧集分集种子先下完的集数移动完影响到还没下载完的集数

### ISSUE THREAD

**Issue by wangguosu520** [jxxghp/nas-tools#1124]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>2.0.5
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 订阅剧集分集种子(1-5集,6-10集,11-20集)如果1-5集先下载完成,过一会就会移动,这时候6-10集和11-20集还没下载完,但是他们都在同一个文件夹下,1-5集移动完成就会把这个文件夹删除,导致后面的集数全部消失

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 剧集订阅建议先把1-5集转移完再添加下一个种子,避免同时添加,先完成的转移完成后影响到还没下载完的集数

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Shurelol** [comment]
建议用硬链接，既可以做种也可以整理媒体库，并且只占一份硬盘空间。如果不想做种，去下载器把种子删掉就行，也不影响。

**Comment by ati121** [comment]
我也遇到了.移动模式下判定问题,先完成的移动后会直接删除文件夹,其实后面的还在下载....复制和硬链接模式没这个问题
