### ISSUE TITLE
开启只管理NASTool添加的下载选项时，正在下载界面不显示通过资源搜索添加的任务

### ISSUE THREAD

**Issue by JAM2199562** [jxxghp/nas-tools#1125]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker or windows orn Synology
>
运行在群晖Docker中的NASTools 2.0.5版本
## 你遇到什么问题了？

> 描述一下你遇到的问题

开启**只管理NASTool添加的下载**选项时，正在下载界面不显示通过**资源搜索**手动添加的任务

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
已经搜索过，确认情况如此

## 你期望的结果

> 描述以下你期望的结果

应该是个小bug，主要影响部分强迫症患者，希望作者的项目越来越好！

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

![image](https://user-images.githubusercontent.com/10511667/190443385-ad52107c-d500-4065-9b04-20382a89fd4e.png)
![image](https://user-images.githubusercontent.com/10511667/190443448-1aeefc58-d206-47ef-9dc8-18932f1ad96b.png)

![image](https://user-images.githubusercontent.com/10511667/190443572-5de5457c-2f49-45cb-b9e6-2190d1c6529b.png)
![image](https://user-images.githubusercontent.com/10511667/190443608-7e41c1c1-710a-474d-93e6-c02aa40c884e.png)

**Comment by Shurelol** [comment]
请提供下qb版本

**Comment by daoye** [comment]
![图片](https://user-images.githubusercontent.com/5357004/190841424-62b37d68-df1f-4653-b0fe-247b0bf63e0d.png)
![图片](https://user-images.githubusercontent.com/5357004/190841434-4cd49026-dd23-4c5c-b499-089ede9b66b2.png)
![图片](https://user-images.githubusercontent.com/5357004/190841442-65c0614c-f278-4ccc-82b0-6cb4493859e8.png)
![图片](https://user-images.githubusercontent.com/5357004/190841450-04b4484d-c4b8-42fc-89ad-58708140dc3e.png)

使用Transmissation 似乎也存在相同的问题。

**Comment by jxxghp** [comment]
据我所知是TR跟QB的版本问题，尽量用新一点的版。我本地使用正常。

**Comment by DDS-ALL** [comment]
我这边也遇到了相同的问题，是更新v2.1.0后才出现的

Transmission版本从来没有变过

在v2.1.0之前的版本都没有这个问题，今天更新v2.1.0后才出现了正在下载的电影在近期下载里面

**Comment by jxxghp** [comment]
> 我这边也遇到了相同的问题，是更新v2.1.0后才出现的
> 
> 
> 
> Transmission版本从来没有变过
> 
> 
> 
> 在v2.1.0之前的版本都没有这个问题，今天更新v2.1.0后才出现了正在下载的电影在近期下载里面

你这说的是同一个问题吗？正在下载的一直都是会立即出现在近期下载啊

**Comment by gwx06** [comment]
我也出现这个问题，在nastool页面添加任务显示失败，正在下载也无显示，但是qb里面已经开始任务了，nastool版本是套件版2.1.0，qb也是套件版，升级版本之前无此问题，折腾两天了也没解决，qb重装也没用，求解决！

**Comment by jxxghp** [comment]
> 我也出现这个问题，在nastool页面添加任务显示失败，正在下载也无显示，但是qb里面已经开始任务了，nastool版本是套件版2.1.0，qb也是套件版，升级版本之前无此问题，折腾两天了也没解决，qb重装也没用，求解决！

跟升级版本没关系吧，我昨天才发布的2.1就折腾两天了吗。

**Comment by Xu-525** [comment]
大神，我也是这个问题，和版本没关系，我没升级2.1.0也这样，换了好几个版本qb  tr套件或者docker，都是自动下载失败，正在下载不显示，但是qb下载任务。

**Comment by gwx06** [comment]
> 

咱俩同样问题，解决了说一声

**Comment by gwx06** [comment]
> > 我也出现这个问题，在nastool页面添加任务显示失败，正在下载也无显示，但是qb里面已经开始任务了，nastool版本是套件版2.1.0，qb也是套件版，升级版本之前无此问题，折腾两天了也没解决，qb重装也没用，求解决！
> 
> 跟升级版本没关系吧，我昨天才发布的2.1就折腾两天了吗。

不好意思，有点着急，昨天晚上出现的，没找到原因！

**Comment by DDS-ALL** [comment]
> > 我这边也遇到了相同的问题，是更新v2.1.0后才出现的
> > Transmission版本从来没有变过
> > 在v2.1.0之前的版本都没有这个问题，今天更新v2.1.0后才出现了正在下载的电影在近期下载里面
> 
> 你这说的是同一个问题吗？正在下载的一直都是会立即出现在近期下载啊

我的意思是正在下载里面没有当前正在下载的资源
近期下载是正常的

**Comment by devangle** [comment]
> 我的环境是 nastools 2.1.0 ， docker qb 版本 荒野无灯 的 4.3.5 ， docker
> 
> 现在描述：
> 
> 1. 之前使用 qb 4.4.5 套件版本 + nastool 2.0.5 没发现问题。
> 2. 我升级了nastools 2.1.0 ,并降级了 docker qb 4.3.5  之后出现。
> 3. nastools 搜索 并点击下载资源 ， 在nastools 的下载管理 可查看下载进度。
> 4. 但在qb web界面无法看到任务 ， qb日志上可以看到有该 下载种子的添加记录。
> 5. 更为诡异的是， 我的 docker qb 4.3.5 的之前所有完成的种子  以及 分类配置 全部不见了。
> 
> 差异操作：
> 
> 1. 我升级了 nastools 2.1.0
> 2. 我降级了 qb 4.3.5
>    但因为  通过nastools 添加任务之后  qb 4.3.5 的全部任务 及原先标签配置不见， 因此怀疑是否是添加任务的动作引起的问题。
> 
> 感谢 。

简单验证了下：   nas 2.0.5 + qb 4.4.5 正常

**Comment by JAM2199562** [comment]
分享一些信息给大家，qbittorrent 4.4.5版本应该确实是有点问题，我使用jackett的订阅连接在nastools中创建站点的时候刷流不工作，于是我降低了4.4.3，然后刷流就正常工作了，然后刚刚无意间发现搜索下载的任务也能出现在正在下载了，我的qbittorrent用的是https://hub.docker.com/layers/linuxserver/qbittorrent/4.4.3/images/sha256-f78b6de466c0791b099c13443373d0444609385a94ead02dfc07a9942b79eb84?context=explore

**Comment by Xu-525** [comment]
> 分享一些信息给大家，qbittorrent 4.4.5版本应该确实是有点问题，我使用jackett的订阅连接在nastools中创建站点的时候刷流不工作，于是我降低了4.4.3，然后刷流就正常工作了，然后刚刚无意间发现搜索下载的任务也能出现在正在下载了，我的qbittorrent用的是[linuxserver/qbittorrent:4.4.3](https://hub.docker.com/layers/linuxserver/qbittorrent/4.4.3/images/sha256-f78b6de466c0791b099c13443373d0444609385a94ead02dfc07a9942b79eb84?context=explore)

感谢，确实退到了4.4.3正常了，感谢解答

**Comment by gwx06** [comment]
希望下个版本解决这个问题，qb4.4.5确实支持不好！

**Comment by JAM2199562** [comment]
> 
话也不是这么说，本来大家一起齐步走，结果你突然多迈一步，这很难怪我没跟上你啊
