### ISSUE TITLE
后台硬链接转移完成后一直重复执行转移

### ISSUE THREAD

**Issue by huluohu** [jxxghp/nas-tools#1128]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.5
>
> 环境: docker
>

## 你遇到什么问题了？

> 硬链接转移完成的视频，还会一直在后台转移

## 给出程序界面截图、后台运行日志或配置文件
<img width="677" alt="image" src="https://user-images.githubusercontent.com/7138642/190538542-e2c106d7-31a0-4a98-a5d4-330c3484c5a8.png">

**Comment by Shurelol** [comment]
可以看到每次转移之间间隔是5分钟，因为下载转移的监控周期是五分钟。转移后会在下载器中给任务加上已整理的tag。这样下次就会跳过有该tag的任务。

所以你的问题是下载器由于某种原因没有打上“已整理”tag，可以尝试手动加上

**Comment by huluohu** [comment]
> 可以看到每次转移之间间隔是5分钟，因为下载转移的监控周期是五分钟。转移后会在下载器中给任务加上已整理的tag。这样下次就会跳过有该tag的任务。
> 
> 所以你的问题是下载器由于某种原因没有打上“已整理”tag，可以尝试手动加上

切换到qb，解决。
