### ISSUE TITLE
PT下载的问题

### ISSUE THREAD

**Issue by sukiqwq** [jxxghp/nas-tools#113]
NAStool中检索到的番剧似乎无法推送至qb和tr下载，显示 ”添加PT任务：NONE“
日志如下：
![QQ截图20220512200303](https://user-images.githubusercontent.com/40717982/168186282-03dd311a-8cfd-470f-b1ea-12650104a284.png)

**Comment by jxxghp** [comment]
检查PROWLARR版本，0.2.0.1678 版本正常使用。
另外，建议使用jackett
