### ISSUE TITLE
请求增加支持邮箱的消息发送和接收

### ISSUE THREAD

**Issue by xiaoguiwk** [jxxghp/nas-tools#1133]
由于企业微信设置门槛较高、telegram需要代理，而邮箱门槛低，容易设置，墙内友好，请求增加支持。
感谢。

**Comment by ati121** [comment]
支持爱语飞飞啊.这个简单的很

**Comment by xiaoguiwk** [comment]
> 支持爱语飞飞啊.这个简单的很

我的意思是需要支持发送功能，也就是说可以用邮箱来实现搜索下载，不是单向的推送消息，单向的话是很简单

**Comment by Shurelol** [comment]
![Screenshot_20220917-153103_Chrome](https://user-images.githubusercontent.com/16237201/190845887-9bea5844-4570-4bb5-a4a0-665f18029000.jpg)

手机上很难用么，直接在手机上用不就行了么
