### ISSUE TITLE
媒体识别问题

### ISSUE THREAD

**Issue by cunbow** [jxxghp/nas-tools#114]
![image](https://user-images.githubusercontent.com/42895319/168194803-f92b3ece-0179-41ad-8be5-1476dde2ab83.png)
ID带英文的识别不了
https://www.themoviedb.org/movie/760104-x

**Comment by xxzj990** [comment]
> ![image](https://user-images.githubusercontent.com/42895319/168194803-f92b3ece-0179-41ad-8be5-1476dde2ab83.png) ID带英文的识别不了 https://www.themoviedb.org/movie/760104-x

兄弟，你填的id是错的，这个电影的id是760104，没有后面的东西
