### ISSUE TITLE
【功能请求】电影订阅可以同时选择多个制作组

### ISSUE THREAD

**Issue by Pollo3470** [jxxghp/nas-tools#1143]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 在进行电影订阅时，可以同时选择多个制作组
>
>适用于在电影还未有资源发布时进行订阅，若任意一个心仪的制作组发布了资源，就可以第一时间自动下载电影

**Comment by jxxghp** [comment]
用过滤规则实现
