### ISSUE TITLE
使用socks5代理时，没有代理 DNS 导致无法正常链接

### ISSUE THREAD

**Issue by kkkgo** [jxxghp/nas-tools#1145]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0
>
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 描述一下你遇到的问题

使用socks5代理时，tmdb无法正常链接，经过排查发现是DNS污染，但我在设置里面配置了socks5代理，不应该受到影响。我尝试更换http代理后链接正常。手动配置docker的DNS也正常。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

有类似的issue，我也是从这个issue得到启发：
https://github.com/jxxghp/nas-tools/issues/1015#issuecomment-1247551609

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

使用socks5代理的时候，DNS通过socks5进行代理

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
程序里貌似没办法解决DNS的问题吧，知道的话可以说明一下

**Comment by kkkgo** [comment]
我找到一些python代码并测试有效，希望对你有帮助。
https://stackoverflow.com/questions/13184205/dns-over-proxy
