### ISSUE TITLE
求个一键深度删除功能

### ISSUE THREAD

**Issue by simon428** [jxxghp/nas-tools#115]
请求考虑添加个一键深度删除功能，一键深度删除，同时删除源文件 和硬链接 和EMBY，还有同时删除下载记录 和订阅记录，就更加好了，为了防止小白，可以加个开关。不然有些电影不想看了，删除了硬链接，还要去找源文件删，麻烦些。

**Comment by jxxghp** [comment]
这玩意真不敢加，昨天还因为安全问题被人攻击了。
搞个软件挺难的。
