### ISSUE TITLE
自定义订阅的蜜柑计划分类是电视剧，而且下载不全

### ISSUE THREAD

**Issue by shanyan-wcx** [jxxghp/nas-tools#1152]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.1.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 自定义订阅的蜜柑计划分类是电视剧，而且下载不全，43集只下了14集
rss地址是https://mikanani.me/RSS/Bangumi?bangumiId=2570&subgroupid=302

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 分类为动漫

## 给出程序界面截图、后台运行日志或配置文件

> [nas-tools-stdout---supervisor-43w7i2q0.log](https://github.com/jxxghp/nas-tools/files/9593729/nas-tools-stdout---supervisor-43w7i2q0.log)

**Comment by jxxghp** [comment]
你的RSS里有43集吗？

**Comment by jxxghp** [comment]
分类是什么你要用名字去识别测试看看

**Comment by shanyan-wcx** [comment]
有43集，蜜柑的种子都是https://mikanani.me/Download/20220918/32fb5fcaf9d080e7d6e570d18dca9d07688941d1.torrent这样的，没法正常识别，不能改成创建任务的时候设置分类吗

**Comment by shanyan-wcx** [comment]
【驯兽师联盟】数码宝贝/数码暴龙/数码兽幽灵游戏[Digimon Ghost Game][43][1080p][简日字幕]
这玩意用识别测试识别出来是电视剧，这是为什么

**Comment by jxxghp** [comment]
> 

这个就识别不到TMDB信息，命名的问题
![image](https://user-images.githubusercontent.com/51039935/190900064-a6cc2646-4e8a-4b95-87a2-42fcf82eb6b7.png)

**Comment by Shurelol** [comment]
自定义识别词，把那一连串中文干扰项屏蔽掉就好了
![image](https://user-images.githubusercontent.com/16237201/191072805-eba6716b-cc0c-43cd-a2db-a8aef8523527.png)
![image](https://user-images.githubusercontent.com/16237201/191072844-6f243cfa-be9a-4f4a-8068-14da9107ef64.png)
