### ISSUE TITLE
希望能够新增定时目录同步功能

### ISSUE THREAD

**Issue by edhnt455** [jxxghp/nas-tools#1153]
在群晖中docker安装的nt，用clouddrive挂载阿里云，识别率很高，但是无法触发自动目录同步功能，可能是挂载的原因。能否在设置里添加一个定时的目录同步功能，来解决这个问题呢？

**Comment by hbxnlsy123** [comment]
我也是想用来整理网盘，但是rclone和webdav都无法触发自动同步，同求定时同步的方法
