### ISSUE TITLE
下载管理统计近期下载的资源视频

### ISSUE THREAD

**Issue by Aqr-K** [jxxghp/nas-tools#1158]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0
>
> 环境: docker 
>下载器：Qbittorrent v4.4.5

## 你遇到什么问题了？

> 描述一下你遇到的问题
初次下载是2.0版本，配置成功后下载管理页面，能显示正在下载的项目，但是下载完成后都会消失，不会导入近期下载，升级v2.1后问题依然在

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 暂时找不到解决方法

## 你期望的结果

> 正在下载完成后能正常导入近期下载里显示

## 给出程序界面截图、后台运行日志或配置文件

> 
![image](https://user-images.githubusercontent.com/95741669/190916568-184df7a0-3e26-469a-978f-0770ceef8a59.png)
![image](https://user-images.githubusercontent.com/95741669/190916639-cd74196b-ea34-452f-bb65-583fe03c019a.png)
![image](https://user-images.githubusercontent.com/95741669/190916675-4c9c8997-c997-44f9-b763-3dde9948f3c3.png)

> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
无法重现，试了很多都能正常显示

**Comment by Aqr-K** [comment]
> 无法重现，试了很多都能正常显示

可已经升级到最新版本还是无法显示，只会显示正在下载的，会不会是qb的设置问题？能否放一下你们正常显示的qb的设置配置
