### ISSUE TITLE
刷流任务添加的部分种子处于”已暂停“状态

### ISSUE THREAD

**Issue by Pollo3470** [jxxghp/nas-tools#1160]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0
>
> 环境: docker
>

## 你遇到什么问题了？

>刷流任务添加的种子，有个别会一直处于暂停状态，需手动开始任务

## 你期望的结果

> 刷流任务添加的种子能正常开始下载

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/90445326/190921777-6ac5f405-00dd-4dc1-b873-4bec74a5e1a4.png)

**Comment by Pollo3470** [comment]
![image](https://user-images.githubusercontent.com/90445326/191351614-425347b6-4433-4a7b-93e8-044eb30e36b5.png)
已经有20多个种子添加了以后暂停了

**Comment by Pollo3470** [comment]
暂停的种子在日志里显示添加失败

**Comment by jxxghp** [comment]
应该是你的QB版本问题，不支持标签，导致加了任务后查询不到无法控制

**Comment by Pollo3470** [comment]
但是大部分种子还是添加成功了的
我的QB版本是4.4.5，docker安装

**Comment by Pollo3470** [comment]
我观察到暂停的种子有两个标签，一个是“已整理”，另一个是一串密码。
成功添加的种子只有“已整理”这一个标签
![image](https://user-images.githubusercontent.com/90445326/192087888-406c672b-f654-45cd-b9a9-d2cb480be547.png)

**Comment by c939984606** [comment]
> 

同样的问题，经常老是出现一大串数字那种，状态都是暂停的，qb 4.4.5 和nastool都是最新版


<img width="218" alt="iShot_2022-09-25_11 45 55" src="https://user-images.githubusercontent.com/34211368/192127478-ed403eaa-00f9-422c-8715-940ba38be861.png">

**Comment by jxxghp** [comment]
QB适配的问题吧，4.4.5可能有适配问题，退一下版本试试看吧
