### ISSUE TITLE
ttg无法显示做种人数

### ISSUE THREAD

**Issue by Pollo3470** [jxxghp/nas-tools#1161]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 在搜索结果中ttg无法显示做种人数

## 你期望的结果

> ttg在搜索结果中能显示做种人数

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/90445326/190924428-86534162-75e9-4d7a-ab4f-7f3951b5c8f8.png)

**Comment by Pollo3470** [comment]
<span id="dlstatus">28 做种者，0 下载者 = 28 活跃用户</span>

种子页面的元素，供参考

**Comment by jxxghp** [comment]
更新最新代码
