### ISSUE TITLE
在搜索返回结果界面添加种子和下载数量

### ISSUE THREAD

**Issue by hostage007** [jxxghp/nas-tools#1163]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.5
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 在搜索返回结果界面添加种子数、下载数等信息，防止传送到下载器一个死种干等。

## 这个功能有什么可以参考的资料吗？

> 在Jackett里面手动搜索时可以返回S/L等信息的，希望可以有设置选项让我们在搜索返回界面看到这些信息。昨天在HDTime下了个康斯坦丁，免费+200%上传，挂了一晚上发现没进度，去站点看了一下发现是死种，反而有些50%DL的是活种。希望能给出这些信息协助判断吧。另外希望企业微信推送信息的时候也给一个选项，有点担心自动选择下载又给个死种出来。

**Comment by jxxghp** [comment]
你确定没有？

**Comment by hostage007** [comment]
重新调整了一下氪金狗眼看了一下，有种的确实会显示数量，但是死种不显示0。这个可否让返回结果为0的时候也显示呢？
