### ISSUE TITLE
忘记管理员密码了请问怎么修改

### ISSUE THREAD

**Issue by warrenhoo** [jxxghp/nas-tools#1164]
请问各位大佬，忘记管理员密码了请问怎么修改，root登录进docker对应目录，有一个config文件，管理员账户能看到，但密码不是明文的

**Comment by Shurelol** [comment]
删了改就行

**Comment by jxxghp** [comment]
配置文件里，把 login_password 后面的全部删掉，包括[hash]字样，改成你自己的密码就行，重启后会重新加密。
