### ISSUE TITLE
nas-tools docker映射的文件缺少

### ISSUE THREAD

**Issue by zgwu1** [jxxghp/nas-tools#1168]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.5
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？
nas-tools docker映射的文件缺少
> 描述一下你遇到的问题
我映射通过cloud drive挂载到本地的阿里云盘，在做软连接的时候发现软连接少很多，我有750不电影，只做了430部电影的软连接。
通过查看ls 命令查看docker 内的文件，确实少了很多。在host主机查看文件数量不少，也查看了emby在docker中显示的数量也是正确的。
host 主机是OMV(树莓派4B)，群辉6.2.1(X86)。
所以请确定是不是nas-tools的docker系统有问题，无法映射到全部数量的文件
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果
希望可以正确显示全部的文件
> 描述以下你期望的结果
希望可以正确显示全部的文件
## 给出程序界面截图、后台运行日志或配置文件
docker显示的文件
![27363bb96d0968b04a3233b13decd04](https://user-images.githubusercontent.com/113878828/190961813-f0664059-dcba-4200-9435-152adb80fe8e.png)

host主机显示的文件
![5d9784927c36c52868dd4518b0d84e4](https://user-images.githubusercontent.com/113878828/190955727-f3d92baf-487a-4610-b31d-10c57543dfad.png)
明显少了红框内的部分文件
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by zgwu1** [comment]
图片传错了，下面这张是docker里面显示的，没有A开头的部分文件
![27363bb96d0968b04a3233b13decd04](https://user-images.githubusercontent.com/113878828/190956119-ab8611c2-d7ca-4f6b-a8a0-88b6b67985d5.png)

**Comment by jxxghp** [comment]
说实话，完全不知道你说的是啥。
1、你得知道这个工具是干什么的，什么原理，以及告诉我你现在用的是什么功能，如何设置的。
2、知道看日志。

**Comment by zgwu1** [comment]
HI Jxxghp,首先感谢这么好用的tools.我的问题是nas-tools docker挂载的文件显示不全。这个问题我找到原因了
NAS_tools docker使用的是Alpine作为基本镜像，Alpine使用musl-linc库，这个库本身存在目录显示不全的问题下面是CloudDrive的作者声明的问题：
1. 基于musl-libc的系统挂载的目录文件可能存在显示不全，包括openwrt、Alpine Linux等，Web界面不受影响
再次感谢作者，也希望可以我们可以更换基础的Linux镜像。
Reopen  issues是希望作者可以看到这个问题，看到后请关掉这个问题。谢谢

**Comment by zgwu1** [comment]
> 说实话，完全不知道你说的是啥。 1、你得知道这个工具是干什么的，什么原理，以及告诉我你现在用的是什么功能，如何设置的。 2、知道看日志。

HI Jxxghp,首先感谢这么好用的tools.我的问题是nas-tools docker挂载的文件显示不全。这个问题我找到原因了
NAS_tools docker使用的是Alpine作为基本镜像，Alpine使用musl-linc库，这个库本身存在目录显示不全的问题下面是CloudDrive的作者声明的问题：

基于musl-libc的系统挂载的目录文件可能存在显示不全，包括openwrt、Alpine Linux等，Web界面不受影响
再次感谢作者，也希望可以我们可以更换基础的Linux镜像。
Reopen issues是希望作者可以看到这个问题，看到后请关掉这个问题。谢谢
