### ISSUE TITLE
手动识别时报拼装文件路径错误，可能媒体类型不正确

### ISSUE THREAD

**Issue by fireice1988** [jxxghp/nas-tools#117]
手动识别时报拼装文件路径错误，可能媒体正确
动画片同一个目录下有多个文件，每个文件是一集，有些剧集能手动识别出来，有些报错：拼装文件路径错误，可能媒体类型不正确
错误截图如下
![识别报错](https://user-images.githubusercontent.com/36370085/168310662-ccff5318-18e2-48a6-90c6-468ce3814ea5.jpg)

**Comment by jxxghp** [comment]
更新到最新版，提示信息更清晰

**Comment by fireice1988** [comment]
更新后的错误变成了:识别失败，无法从文件名中识别出集数
