### ISSUE TITLE
连接tmmb报错

### ISSUE THREAD

**Issue by qqwas** [jxxghp/nas-tools#118]
07:39:49 ERROR - 【META】连接TMDB出错：('Connection aborted.', OSError(22, 'Invalid argument'))
07:39:49 INFO - 【META】正在识别电影：The Great Escape, 年份=1963 ...
07:39:53 ERROR - 【META】连接TMDB出错：('Connection aborted.', OSError(22, 'Invalid argument'))
07:39:53 INFO - 【META】正在识别电影：The Great Escape, 年份= ...
07:39:56 ERROR - 【META】连接TMDB出错：('Connection aborted.', OSError(22, 'Invalid argument'))
07:39:56 INFO - 【META】正在识别电影：Chinatown, 年份=1974 ...
07:39:59 ERROR - 【META】连接TMDB出错：('Connection aborted.', OSError(22, 'Invalid argument'))
07:39:59 INFO - 【META】正在识别电影：Chinatown, 年份= ...
07:40:03 ERROR - 【META】连接TMDB出错：('Connection aborted.', OSError(22, 'Invalid argument'))
07:40:03 INFO - 【META】正在识别电影：Mr Smith Goes to Washington, 年份=1939 ...
07:40:06 ERROR - 【META】连接TMDB出错：('Connection aborted.', OSError(22, 'Invalid argument'))
07:40:06 INFO - 【META】正在识别电影：Mr Smith Goes to Washington, 年份= ...
07:40:09 ERROR - 【META】连接TMDB出错：('Connection aborted.', OSError(22, 'Invalid argument'))
07:40:09 INFO - 【META】正在识别电影：Das Boot, 年份=1981 ...
07:40:13 ERROR - 【META】连接TMDB出错：('Connection aborted.', OSError(22, 'Invalid argument'))
07:40:13 INFO - 【META】正在识别电影：Das Boot, 年份= ...
07:40:16 ERROR - 【META】连接TMDB出错：('Connection aborted.', OSError(22, 'Invalid argument'))

**Comment by jxxghp** [comment]
api或者代理的配置问题吧

**Comment by ivo-ou** [comment]
解决了吗？我也遇到这个问题，用的sock5代理，代理没问题，API也没问题

**Comment by qqwas** [comment]
不是所有的都报错，部分报错，甚至从tmmb拿到id来手动识别，也有部分会报这个错。
