### ISSUE TITLE
建议字幕增加射手网（伪）字幕网站字幕下载

### ISSUE THREAD

**Issue by dxbzth** [jxxghp/nas-tools#1180]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0
>
> 环境: synology

## 你想要新增或者改进什么功能？

> 字幕中增加射手网（伪）https://secure.assrt.net/，字幕下载。

## 这个功能有什么可以参考的资料吗？

> EMBY插件：[91270](https://github.com/91270)
/
[MeiamSubtitles](https://github.com/91270/MeiamSubtitles)

**Comment by Shurelol** [comment]
已经支持https://github.com/allanpk716/ChineseSubFinder

建议去ChineseSubFinder反馈
