### ISSUE TITLE
新电视剧检索及RSS不能正确匹配

### ISSUE THREAD

**Issue by somethingwjy** [jxxghp/nas-tools#1181]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 电视剧《底线》(Draw The Line) 检索及订阅不能正确匹配  搜索使用名称为 Draw The Line 识别结果为 Draw the Line (2022)  但提示不匹配

## 你期望的结果

> 识别电视剧名后，正常匹配下载

## 给出程序界面截图、后台运行日志或配置文件
尝试打开 实验室-精确搜索使用英文名称   英文名字完全一致依然提示不匹配.
>开始检索 **_Draw The Line_**            
>Draw.the.Line.2022.WEB-DL.4k.H265.AAC-HDCTV 识别为 电视剧 **_Draw the Line (2022)_** 不匹配

下为两个站点分别尝试订阅的日志截图

**1.mao**

![底线](https://user-images.githubusercontent.com/35595344/191057894-00c2ce41-e126-4eaa-8947-60c74a14c87f.jpg)

**2.瓷器**

![底线2](https://user-images.githubusercontent.com/35595344/191058646-424cd543-716f-4959-8320-bd6171d7f7d7.jpg)
****瓷器RSS**
![3](https://user-images.githubusercontent.com/35595344/191060535-3b8f12b1-d7a7-45b5-8a4f-b2022ba2cc9b.jpg)

## 注：其他电视剧订阅都可以正常匹配后下载   是否与该电视剧为新剧有关呢？   该电视剧今日上映，刚刚出种2h

**Comment by somethingwjy** [comment]
![image](https://user-images.githubusercontent.com/35595344/191066585-3f1ae841-3ac2-4404-a41f-c77b304d8a31.png)

tmdb能够被正确识别，但资源搜索后也无法查找到资源

**Comment by Shurelol** [comment]
识别有问题就先去做名称测试
![image](https://user-images.githubusercontent.com/16237201/191070733-a45bb1e9-16a0-4d5b-8c2b-d458633199b3.png)
显然，根据名称中的英文是识别为了tmdb上另外一个条目
![image](https://user-images.githubusercontent.com/16237201/191070883-a1cca390-0394-43c8-acc0-4a55e4854216.png)
![image](https://user-images.githubusercontent.com/16237201/191070861-6be1e092-b95b-44c2-a126-ec7f1525f6df.png)

**Comment by somethingwjy** [comment]
> ###首先，有专门的识别问题issue，不需要单独开贴
> 
> ###其次，识别有问题就先去做名称测试
> 
> ![image](https://user-images.githubusercontent.com/16237201/191071774-cd9d2e24-bde5-4b1d-ac0e-6abe4bff7b01.png)
> 
> ###显然，根据名称中的英文是识别为了tmdb上另外一个条目
> 
> ![image](https://user-images.githubusercontent.com/16237201/191071856-362e8702-a63c-489a-a108-3002590a3838.png) ![image](https://user-images.githubusercontent.com/16237201/191070861-6be1e092-b95b-44c2-a126-ec7f1525f6df.png)
> 
> ###最后，怎么解决，自定义识别词把Draw.the.Line替换成底线即可正确识别 ![image](https://user-images.githubusercontent.com/16237201/191072136-78d116aa-4abc-487d-8d16-0a406e36deae.png) ![image](https://user-images.githubusercontent.com/16237201/191072211-4647a82a-14a8-4405-9049-f95ddc51b7b2.png)

非常感谢您的解答!   下次一定注意已存在issue    再次感谢大佬!
