### ISSUE TITLE
在某站搜索到多个资源的时候，是否可以有选择功能？

### ISSUE THREAD

**Issue by superain7** [jxxghp/nas-tools#1184]
## 你使用的 NASTool 是什么版本，什么环境？
群晖 920+ 6.2.4版本
> NASTool 版本: vx.x.x
>2.1.0
> 环境: docker or windows or synology
docker
## 你想要新增或者改进什么功能？
**在搜索功能中，在PT站搜索到多个资源，比如一季多集，未完结情况时候，是不是可以有多选功能，进行一次性操作下载**
> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？
无
> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
还是有其他操作功能我没有发现。
<a href="https://imgse.com/i/xCGISK"><img src="https://s1.ax1x.com/2022/09/20/xCGISK.png" alt="xCGISK.png" border="0" /></a>

**Comment by Shurelol** [comment]
建议添加rss订阅，会首先搜索已存在的资源，然后后续更新通过rss获取。

比如一部剧总共20集，已经更新10集。

添加rss订阅，那么前面10集会首先搜索已有资源下载，后面10集会通过rss链接进行后续更新
