### ISSUE TITLE
NAS-tools  docker 文件显示不全

### ISSUE THREAD

**Issue by zgwu1** [jxxghp/nas-tools#1186]
> 说实话，完全不知道你说的是啥。 1、你得知道这个工具是干什么的，什么原理，以及告诉我你现在用的是什么功能，如何设置的。 2、知道看日志。

HI Jxxghp,首先感谢这么好用的tools.我的问题是nas-tools docker挂载的文件显示不全。这个问题我找到原因了
NAS_tools docker使用的是Alpine作为基本镜像，Alpine使用musl-linc库，这个库本身存在目录显示不全的问题下面是CloudDrive的作者声明的问题：

基于musl-libc的系统挂载的目录文件可能存在显示不全，包括openwrt、Alpine Linux等，Web界面不受影响
再次感谢作者，也希望可以我们可以更换基础的Linux镜像。
Reopen issues是希望作者可以看到这个问题，看到后请关掉这个问题。谢谢

_Originally posted by @zgwu1 in https://github.com/jxxghp/nas-tools/issues/1168#issuecomment-1251772281_

**Comment by jxxghp** [comment]
你这么说就明白了，应该不影响工具读取目录吧，目前没有看到类似问题的反馈。

**Comment by zgwu1** [comment]
> 你这么说就明白了，应该不影响工具读取目录吧，目前没有看到类似问题的反馈。

影响的，nas-tools docker查询出的文件数量就会少，nas-tools程序读到的也肯定少，我就是目录同步的时候发现少建了大概一半的文件（780部电影，大概建了430）。目前我现在host 机从cloud drive映射的目录建立软连接到其他目录，然后在将软连接映射到nas-tools，就会显示全部。所以猜测大概是alpine读取cloud driver映射的目录有问题。
