### ISSUE TITLE
TG群无故禁言，能给个说法吗？

### ISSUE THREAD

**Issue by lengxii** [jxxghp/nas-tools#1188]
我在群里提意见，就把我禁言了，有这么权限人的么

新版加了个自定义关键字过滤，公告里没写要手动更新，我不清楚，就在群里提了一个意见，然后一堆人怼我，说我不看教程。然后TG群的群主还把我禁言了？这是什么操作。

**Comment by lengxii** [comment]
难道 在这群里全凭管理心情 心情不好就直接禁言你？

**Comment by jxxghp** [comment]
不要跑这里来提这种问题，跟这个项目有什么关系？无语。。。。

**Comment by lengxii** [comment]
这群是你放在介绍的里官方群，管理无故禁言，就不管了吗？
