### ISSUE TITLE
增加TMDB ID黑名单功能

### ISSUE THREAD

**Issue by leihao** [jxxghp/nas-tools#119]
同名电视剧错误自动识别，是不是可以加个黑名单识别的时候略过它？
我的王者天下 Kingdom 一直在被识别为拳击王国 Kingdom

**Comment by jxxghp** [comment]
在历史记录或手动识别中进行手工进行识别过的会自动加入黑名单

**Comment by leihao** [comment]
> 在历史记录或手动识别中进行手工进行识别过的会自动加入黑名单

不行诶，这个功能好像没生效
![Screenshot_20220515-074958_Chrome](https://user-images.githubusercontent.com/1472064/168451646-5bc1e3bb-3494-47e0-a49a-393326cc2a1a.jpg)
