### ISSUE TITLE
希望企业微信搜索结果可以以点击方式选择，而不是回复数字来选择。

### ISSUE THREAD

**Issue by bhj128128** [jxxghp/nas-tools#1191]
## 你使用的 NASTool 是什么版本，什么环境？
omv-docker
> NASTool 版本: 2.1.0
>
> 环境: docker or windows or synology

## 你想要新增或者改进什么功能？
在利用企业微信搜索电影时，会匹配好几个结果。以前的操作方式是匹配哪个，就回复对应的数字，是否可以改为直接手机点击匹配结果即可进行下载。现在是点击，会链接到nastools主页。

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
微信的交互是要么发消息要么通过链接跳转，如果点击链接要跳转到一个新页面，那使用体验并不好。
