### ISSUE TITLE
自定义订阅增加下载位置选项

### ISSUE THREAD

**Issue by leo8912** [jxxghp/nas-tools#1193]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
**>v2.1.0**
> 环境: docker or windows or synology
**>docker v2.1.0 b8a63ab**
## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
**1、自定义订阅功能下是否可以新增一个下载目录的设置。
这适用空间非常大，甚至可以订阅电子书戏曲这一类，但这些是无法识别的，所以是否可以增加一个下载目录的设置**

**2、另外，不知道之前的版本是不是这样，我设置了未识别的目录。但有个别资源是可以tmdb识别的，我手动识别成功后，未识别目录下仍然会保留该硬链，是否手动识别以后能同时删除这个未识别的硬链。
![image](https://user-images.githubusercontent.com/22719866/191195639-dc0f282c-784f-42f9-be5c-0038c039e6a1.png)
**
![image](https://user-images.githubusercontent.com/22719866/191199192-31171db4-95bb-4c0b-b91b-12c2a9bdbe6a.png)

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
2.不要设置未识别目录就行

**Comment by ati121** [comment]
支持下..自定义订阅下载能指定储存位置的话就非常科学了.能订阅各种..

**Comment by jxxghp** [comment]
已支持
