### ISSUE TITLE
点击自动下载后没有反应

### ISSUE THREAD

**Issue by Losiyu** [jxxghp/nas-tools#1196]
## 版本环境

> NASTool 版本: latest
>
> 环境: docker 
>

## 问题

新手小白，我是按照这个[教程](https://zhuanlan.zhihu.com/p/563493451)配置的。nastool 点击自动下载后，过一会会显示添加下载成功，但实际上qb和正在下载都没有反应，只有近期下载会有显示。nastool下载器界面上qb的测试是成功的。可以帮忙看看出什么问题了吗

## 截图
![image](https://user-images.githubusercontent.com/55306639/191269505-e0b4ad99-d334-44b5-9465-b87882e78914.png)
![image](https://user-images.githubusercontent.com/55306639/191270427-0a6540fa-b053-425d-b323-f6937efbd930.png)
![image](https://user-images.githubusercontent.com/55306639/191270502-23048835-bf5f-4ade-9aa4-9949e6e4bac8.png)

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/191283098-72317add-3436-47ba-96a4-7280b2afd5c1.png)

问：下载器这个目录到底应该怎么配置？

答：
这么理解：
第一列是传给下载器的，你下载器里设置的啥这里就填啥；
第二列是nastool访问你的下载目录的，也就是下载器的目录映射到nastool容器里的路径；
第三列可选，你如果想用下载器的分类功能就填，否则就不填，不明白是干啥的就不填。

实在搞不明白的，就把映射前和映射后的路径填成一样的，会少很多理解问题

可以参考下

另外关注[NASTool小秘书频道](https://t.me/nastool_mi)获取教程及问题自助

**Comment by Losiyu** [comment]
谢谢您的回答，问题已经解决，这里写一下问题的原因

教程依然是对的，我在container创建容器时候填写映射错了，没有给予qbit在local中downloads的映射位置，导致出现了四个选项，并且点击自动下载后没有反应。

谢谢您
