### ISSUE TITLE
自定义添加的订阅删除，重新添加后显示已处理

### ISSUE THREAD

**Issue by xyswordzoro** [jxxghp/nas-tools#1197]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0
>
> 环境: docker

> 你想要改进功能

自定义订阅，已经添加到下载了，全部删除想重新添加自定义订阅，再添加后显示已处理（缓存啥的都清理过了），应该和qb的rss已阅读类似，希望增加个清理的按钮便于重新添加
PS订阅地址是同一个地址
![QQ截图20220920214655](https://user-images.githubusercontent.com/86150433/191276642-bf5e738e-5ec6-4f94-a92d-760266ccc602.jpg)

**Comment by Shurelol** [comment]
顺便问下，后面每个rss订阅加个modal显示已获取下载的文章怎么样。
类似这种感觉
![image](https://user-images.githubusercontent.com/16237201/191286077-3b202795-8c93-45d7-ab1e-d987b54c6248.png)

**Comment by jxxghp** [comment]
> 顺便问下，后面每个rss订阅加个modal显示已获取下载的文章怎么样。 类似这种感觉 ![image](https://user-images.githubusercontent.com/16237201/191286077-3b202795-8c93-45d7-ab1e-d987b54c6248.png)

交给你了
