### ISSUE TITLE
使用高级搜索搜电视剧全季时，未排除单季内容

### ISSUE THREAD

**Issue by Pollo3470** [jxxghp/nas-tools#1198]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 使用高级搜索搜电视剧时，若选择全部，则排除掉单季内容
> 目前的情况是全季内容会被排在最后，不便于查看
> 截图为筛选站点的结果，若全部结果则更难找到

![image](https://user-images.githubusercontent.com/90445326/191354181-78f519f2-df4f-487e-9ed9-86c30315e4b0.png)

**Comment by jxxghp** [comment]
加个季的过滤估计会更实用
