### ISSUE TITLE
对已有的视频进行改名

### ISSUE THREAD

**Issue by cqboyone** [jxxghp/nas-tools#12]
请问可以对已有的视频进行改名吗？有的种子含有文件夹，有的是单个电影，导致下载下来的电影，有的是英文文件夹，有的就是一个mkv文件。然后emby刮削后，有在根目录生成了一堆info、jpg文件，导致文件夹下面非常混乱。请问可以出一个文件整理的功能吗？

**Comment by jxxghp** [comment]
支持，请详细看介绍页面。
