### ISSUE TITLE
【媒体识别-历史记录】文件信息能否显示完整的源目录路径呢?

### ISSUE THREAD

**Issue by Linyue-GitHub** [jxxghp/nas-tools#120]
![网页捕获_15-5-2022_14268_10 0 0 128](https://user-images.githubusercontent.com/71179298/168460209-5ed76891-1e14-4986-be9a-de298b39b3e6.jpeg)
有时候某个剧识别错误了，不好找源文件，按照季的方式命名的，只显示季目录文件名

**Comment by jxxghp** [comment]
不能，这个显示全就UI就没法看了。
你这些是已经被识别过的？正常新下的PT资源上级目录也不会是这样名字。
