### ISSUE TITLE
白兔无法过滤free种

### ISSUE THREAD

**Issue by Pollo3470** [jxxghp/nas-tools#1200]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 白兔无法筛选free种

## 给出程序界面截图、后台运行日志或配置文件

```
免费：<b class="free">免费</b>

X2免费：<b class="twoupfree">2X免费</b>
```

**Comment by jxxghp** [comment]
加了，等更新
