### ISSUE TITLE
更新至2.10 f2b7adf，目录同步-硬连接转移失败报错误码256

### ISSUE THREAD

**Issue by sungamma** [jxxghp/nas-tools#1202]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.10
>
> 环境: docker 
>

## 更新到2.10后，硬连接转移失败

> 更新到2.10后，硬连接转移失败，手动硬连接转移也失败，报错误码256。更新前一切正常。回退到2.05一切正常。
uid，gid设置按照id输出的结果填写的，权限没有问题。目录没有跨盘，也没有跨共享文件夹，具体见下图
![image](https://user-images.githubusercontent.com/33790/191409065-92b50407-dd7b-4895-beaa-1be0901a33be.png)
![image](https://user-images.githubusercontent.com/33790/191409091-4395fd7a-b6fe-4225-8c19-9bb5dcee846c.png)

## 已浏览过Issues、Wiki及TG公众号仍无法解决

> #1003 提出的加入高权限，经过验证没有用，而且从原理上来说这样做也没啥道理。Wiki提到的跨盘情况也不存在。#1003 里@Aqr-K 也有此问题。

**Comment by zhwejjj** [comment]
个别硬链接有同样问题，例如少年白马醉春风

**Comment by jxxghp** [comment]
更新了代码，看还会不会了

**Comment by zhwejjj** [comment]
我这问题还是存在的 但是就这么一个 其他都正常识别并硬链接

**Comment by jxxghp** [comment]
> 我这问题还是存在的 但是就这么一个 其他都正常识别并硬链接

更新了最新的代码了吗？贴下日志看看

**Comment by sungamma** [comment]
我试了下已经解决了，目前已经解决了。更新到的版本是v2.1.0 c6c47534
原来的文件是这样的
`/volume1/movie/QB/哈尔的移动城堡.Howl's.Moving.Castle.2004.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS/`
@zhwejjj 你再试下，确定下右下角的提交号，有时候更新不一定成功

**Comment by zhwejjj** [comment]
解决了 估计就是没拉到最新的
