### ISSUE TITLE
可以搜到电影，但使用内建索引器搜索资源时总是匹配不到结果

### ISSUE THREAD

**Issue by River-deng** [jxxghp/nas-tools#1205]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>v2.1.0
> 环境: docker or windows or Synology
>群晖套件安装

## 你遇到什么问题了？

> 可以搜到电影，但使用内建索引器搜索资源时总是匹配不到结果

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![1663745591810](https://user-images.githubusercontent.com/101177407/191443389-cbe404af-e4a1-4292-ba5c-13e5bc9214b1.jpg)
![1663745591279](https://user-images.githubusercontent.com/101177407/191443430-a8462477-5472-4d8b-9bde-9fb7f7389603.jpg)
![1663745591295](https://user-images.githubusercontent.com/101177407/191443474-b910a04d-a89b-4b54-ad55-b62780494f26.jpg)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
这些都是公开bt外站，你得去看下站里有没有资源啊。又不是想要的都能有。
