### ISSUE TITLE
询问下关于带文件夹BT任务下载时目录监控是否给出预期行为的问题

### ISSUE THREAD

**Issue by bcseputetto** [jxxghp/nas-tools#1211]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.1.0 b8a63ab3
>
> 环境: docker【群晖】
>

## 你遇到什么问题了？

> 我并非使用nastool上提供的下载器连接下载，而是使用群晖自带的DownloadStation，做RSS订阅自动下载。
我发现下载的是不含文件夹的BT任务会正常触发转移监控文件。如果BT任务下载是会额外带一个文件夹时就不会触发。
这是BUG，还是就是这么设计的？

## 给出程序界面截图、后台运行日志或配置文件

![日志](https://user-images.githubusercontent.com/29139573/191638356-617ab2ec-6f2c-45f4-b04e-3c2a92d6b04e.png)
![RSS自动下载完成后的通知](https://user-images.githubusercontent.com/29139573/191638372-2d485898-d41d-43ca-af22-750dc3179bef.png)
![目录](https://user-images.githubusercontent.com/29139573/191638377-5b0fcc9e-5642-488d-b1b6-b9b3041ed87c.png)

**Comment by jxxghp** [comment]
根目录下的实时处理。子文件夹下的5分钟cd
