### ISSUE TITLE
名称识别出错

### ISSUE THREAD

**Issue by EliteOtaku** [jxxghp/nas-tools#1213]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

在服务-名称识别测试中发现出错

> 描述一下你遇到的问题
输入“[NEOQSW] MACROSS7 THE MOVIE [The_Galaxy_Is_Calling_Me][1440x1080 10Bit-HEVC FLAC].mkv”
然后点击下面绿色的TMDB数字，跳出的是某演员页面https://www.themoviedb.org/tv/45932-chichin-puipui，
不是电影页面，正确的应该是https://www.themoviedb.org/movie/45932-macross-7-the-galaxy-is-calling-me

怀疑这里feedback的时候弄错了

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Shurelol** [comment]
### 首先，有专门的识别问题issue #408，不需要单独开贴

### 其次，识别有问题请先去服务-名称识别测试
![image](https://user-images.githubusercontent.com/16237201/191722197-a4f48119-73b3-4e20-a1d9-90948383de57.png)

### 显然，根据识别结果，名称中 **MACROSS7 THE MOVIE** 为干扰项，如果去除可以正常识别
![image](https://user-images.githubusercontent.com/16237201/191722395-b31d037b-aeda-4562-a71c-563861fe0f25.png)

### 最后，怎么解决，自定义识别词添加屏蔽词**MACROSS7 THE MOVIE**即可正确识别
![image](https://user-images.githubusercontent.com/16237201/191722589-44694427-9798-4f5b-92bf-988303f75625.png)
![image](https://user-images.githubusercontent.com/16237201/191722828-faaf2fbd-5a3b-489a-9a66-67e05c1a9f9d.png)

#### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助
