### ISSUE TITLE
硬链接失败，错误码 512

### ISSUE THREAD

**Issue by Matzoh** [jxxghp/nas-tools#1215]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0
>
> 环境: docker
>

## 你遇到什么问题了？
【RMT】文件 Breaking Bad (2008) - S01E02 - Cat's in the Bag... (1080p BluRay x265 Silence).mkv 硬链接失败，错误码 512

> 绝命毒师第二集无法转移，怀疑是文件名中包含“.”

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 未解决

## 你期望的结果

> 可正常识别转移（记得之前的版本转移成功过）

## 给出程序界面截图、后台运行日志或配置文件

> 【RMT】文件 Breaking Bad (2008) - S01E02 - Cat's in the Bag... (1080p BluRay x265 Silence).mkv 硬链接失败，错误码 512

**Comment by jxxghp** [comment]
是单引号的问题，已经更新了代码，看是否解决。如未解决再粘日志重提吧。
