### ISSUE TITLE
企业微信代理添加socks代理支持

### ISSUE THREAD

**Issue by JavaZeroo** [jxxghp/nas-tools#1218]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 企业微信消息通知，添加socket代理

## 这个功能有什么可以参考的资料吗？

我本身有其他服务用的是这个项目https://github.com/Lozy/danted

然后想直接在nastools上面用。并且服务端用这个项目配置方便很多，不需要会caddy那些反向代理

**Comment by jxxghp** [comment]
太复杂，自已动手
