### ISSUE TITLE
部分国家语言命名文件硬连接的目标文件名重命名不符预期

### ISSUE THREAD

**Issue by huiyaoren** [jxxghp/nas-tools#1219]
## 你使用的 NASTool 是什么版本，什么环境？

NASTool 版本: v2.1.0

环境: docker

## 你遇到什么问题了？

重新指定电影重命名格式包含 {original_title} 后部分国家语言命名文件硬连接的目标文件名重命名不符预期

电影重命名格式：
{title} ({year})/{original_title}.{year}.{videoFormat}.{edition}.{videoCodec}.{audioCodec}

源文件：
/media/Movie/Download/Capharnaum.2018.1080p.BluRay.x264-MkvCage.mkv

目标文件：
/media/Movie/Link/外语电影/何以为家 (2018)/کفرناحوم.2018.1080p.BluRay.x264.mkv

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

目标文件的文件名称按照正常顺序命名

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

16:22:15 INFO - 【RMT】开始处理：/media/Movie/Download/Capharnaum.2018.1080p.BluRay.x264-MkvCage.mkv，转移方式：硬链接
16:22:16 INFO - 【META】正在查询TMDB电影：517814 ...
16:22:16 INFO - 【META】Capharnaum 识别到 电影：TMDBID=517814, 名称=何以为家, 上映日期=2018-09-20
16:22:16 INFO - 【RMT】正在转移文件：Capharnaum.2018.1080p.BluRay.x264-MkvCage.mkv 到 /media/Movie/Link/外语电影/何以为家 (2018)/کفرناحوم.2018.1080p.BluRay.x264.mkv
16:22:16 INFO - 【RMT】文件 Capharnaum.2018.1080p.BluRay.x264-MkvCage.mkv 硬链接完成
16:22:16 INFO - 【SUBTITLE】ChineseSubFinder任务添加成功：4fcaeea33235e9a0ddc31ed88352573234f3796d3c26d772297aac2190855f35
16:22:16 INFO - 【MSG】发送serverchan消息：title=何以为家 (2018) 转移完成, text=评分：8.2，类型：电影，类别：外语电影，质量：BluRay 1080p，大小：3.0G，来自：目录同步
16:22:17 ERROR - 【MSG】发送消息失败：未获取到返回信息
16:22:17 INFO - 【META】正在查询TMDB电影：517814 ...
16:22:18 INFO - 【NFO】正在生成电影NFO文件：کفرناحوم.2018.1080p.BluRay.x264
16:22:19 INFO - 【NFO】豆瓣该影片或剧集无演员 Zain Al Rafeea 信息
16:22:20 INFO - 【NFO】豆瓣该影片或剧集无演员 Yordanos Shifera 信息
16:22:22 INFO - 【NFO】豆瓣该影片或剧集无演员 Cedra Izzam 信息
16:22:22 INFO - HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/person/2226542?api_key=ad2b37f5ccc84013919f6d2561a6f384&append_to_response=combined_credits,translations,external_ids&language=zh-CN (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
16:22:24 INFO - 【NFO】豆瓣该影片或剧集无演员 Joseph Jimbazian 信息
16:22:25 INFO - 【NFO】豆瓣该影片或剧集无演员 Samira Chalhoub 信息
16:22:26 INFO - 【NFO】豆瓣该影片或剧集无演员 Farah Hasno 信息
16:22:26 INFO - 【NFO】正在保存 poster 图片：/media/Movie/Link/外语电影/何以为家 (2018)
16:22:29 INFO - 【NFO】正在保存 fanart 图片：/media/Movie/Link/外语电影/何以为家 (2018)
16:22:31 INFO - 【NFO】正在保存 background 图片：/media/Movie/Link/外语电影/何以为家 (2018)
16:22:33 INFO - 【NFO】正在保存 logo 图片：/media/Movie/Link/外语电影/何以为家 (2018)
16:22:35 INFO - 【NFO】正在保存 disc 图片：/media/Movie/Link/外语电影/何以为家 (2018)
16:22:38 INFO - 【NFO】正在保存 banner 图片：/media/Movie/Link/外语电影/何以为家 (2018)
16:22:40 INFO - 【NFO】正在保存 thumb 图片：/media/Movie/Link/外语电影/何以为家 (2018)
16:22:42 INFO - 【RMT】/media/Movie/Download/Capharnaum.2018.1080p.BluRay.x264-MkvCage.mkv 处理完成，总数：1，失败：0
16:22:42 INFO - 【SUBTITLE】通知ChineseSubFinder下载字幕: /media/Movie/Link/外语电影/何以为家 (2018)/کفرناحوم.2018.1080p.BluRay.x264.mkv

**Comment by Shurelol** [comment]
建议可以用{en_title}，用{original_title}的话语言可能适配会出现问题

**Comment by huiyaoren** [comment]
应该是语言语序导致的 
波斯文语序从右到左 字体会选择从右侧开始排列波斯文 和其他语言文字一起排放就会出现上述情况 本身文件命名顺序是正确的 

另外使用 {en_title} 的情况有时会出现解析结果为空字符的情况。暂时没法复现，有可能是网络原因导致的。
