### ISSUE TITLE
地区描述问题

### ISSUE THREAD

**Issue by lzxxdfx1** [jxxghp/nas-tools#1221]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0
>
> 环境:  Synology

## 你遇到什么问题了？

> 建议改下default-category.yaml中对台湾地区描述，，当心被冲

**Comment by jxxghp** [comment]
嗯，最开始专门留意改了，但只改了上面一个，漏改了下面的。
