### ISSUE TITLE
无法设置过滤规则以及豆瓣（2.1.0）

### ISSUE THREAD

**Issue by violin321** [jxxghp/nas-tools#1224]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0
>
> 环境: Synology套件
>

## 你遇到什么问题了？

> 2.1.0版本之前正常使用，升级到2.1.0版本后点击设置中的过滤规则以及豆瓣闪屏无法进入设置，启动日志中显示“豆瓣未配置”，其余日志无异常，尝试重启套件以及群晖均无法解决。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 未发现可参考案例

## 你期望的结果

> 能正常设置

## 给出程序界面截图、后台运行日志或配置文件
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/40025669/191776748-64aa3857-f916-4dfe-bd22-372d1860c5ba.png">
<img width="721" alt="image" src="https://user-images.githubusercontent.com/40025669/191777296-196c973d-1040-411a-94c8-87d4a1350b73.png">

[brushtask.txt](https://github.com/jxxghp/nas-tools/files/9626867/brushtask.txt)
[rss.txt](https://github.com/jxxghp/nas-tools/files/9626868/rss.txt)
[run.txt](https://github.com/jxxghp/nas-tools/files/9626870/run.txt)

> 附截图及配置文件

**Comment by jxxghp** [comment]
估计是旧配置兼容的问题，如果是个例就删了重新配置下吧，无法重现就很难排查。

**Comment by violin321** [comment]
在config.yaml中豆瓣配置消失，重新添加后可使用。想问问过滤规则的配置文件是哪个呢？


# 【配置豆瓣账号信息】：配置后会自动同步豆瓣收藏，豆瓣标记想看内容后，后台自动下载
douban:
  # 【用户ID列表】：豆瓣电影点个我主页people后面的那一串数字，或者使用豆瓣App个人信息中查看。可以配置多个，注意要加引号
  # 这里可以是自己的，也可以是别人的，比如填写几个大V的账号ID，实现热门影视自动下载
  users:
  - ''
  # 【豆瓣Cookie】：选配，嫌麻烦的可以不用配置，可能影响个别电影的同步
  cookie:
  # 【同步天数】：同步多少天内加入的数据
  days: 30
  # 【同步间隔】：多久同步一次数据，单位小时，建议不要太频繁，避免被检测到后封号
  interval:
  # 【同步数据类型】：同步哪些类型的收藏数据：do 在看，wish 想看，collect 看过，用逗号分隔配置
  types: wish
  # 【自动开载开关】：同步到豆瓣的数据后是否自动检索站点并下载（需要配置Jackett）
  auto_search: true
  # 【自动添加RSS开关】：站点检索找不到的记录是否自动添加RSS订阅（可实现未搜索到的自动追更）
  auto_rss: true
