### ISSUE TITLE
刷流保种体积计算不正确

### ISSUE THREAD

**Issue by zhixiangjoy** [jxxghp/nas-tools#1228]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 设置了两个站点的刷流配置，每个设置了保重50G（最开始设置的100G,中途修改过几次刷流配置）,运行了三天，两个站下载的总体积早已超过50G（已经近1T多了）,仍没有停止下载，依旧有添加新的下载任务。因为聆音是刚加入的站，然后再nt里启用的刷流，偶然间看到保种体积已经1T了就知道不对，不知道那里设置的问题，还是bug。刷流下载的文件夹是单独的，我统计文件夹大小确实也超过50G了。另外修改刷流配置后，会重新计算保种体积吗？

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 超过设置的保种体积，停止添加新的下载任务。

## 给出程序界面截图、后台运行日志或配置文件
下载器为docker nve的qb v4.4.5版本：
![image](https://user-images.githubusercontent.com/15685217/191884159-4f652fca-4182-4ae4-9d58-da20ac9a9a8e.png)
刷流配置截图：
![image](https://user-images.githubusercontent.com/15685217/191884050-d564c9c5-b4e4-4075-a0ab-0735d829356f.png)
运行了大概3天后的数据统计（聆音是新入的站，然后开启的刷流，自己手动添加了几个种子，其它都是刷流下载的）：
![image](https://user-images.githubusercontent.com/15685217/191884235-6e4dc2b2-4d70-4ef6-88b5-75764090eb49.png)
刷流下载的文件放在单独的文件夹下，方便统计整理：
![image](https://user-images.githubusercontent.com/15685217/191884511-aae56289-3f3b-4d17-9904-46468b07f58a.png)

**Comment by zhixiangjoy** [comment]
【补充】大概率是刷流出问题了，我刷流都暂停了，还收到刷流添加的种子通知。
![image](https://user-images.githubusercontent.com/15685217/191889582-88e19a93-f40b-4911-8c9e-72775bd403e4.png)

**Comment by link2fun** [comment]
删种好像是出问题了... 我设置的超3天删除, 结果一周前的还保留着....

**Comment by Pollo3470** [comment]
似乎更改刷流设置以后会重新统计，原来的就不会被管理了
