### ISSUE TITLE
站点历史柱状图中上传下载数据弄反了

### ISSUE THREAD

**Issue by alkalixin** [jxxghp/nas-tools#1229]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
> v2.1.0 c6c47534
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 站点历史柱状图中上传下载数据弄反了

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 正确显示数据

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/5803465/191886035-b55bf43f-356d-4255-895e-441bf05d4c73.png)
![image](https://user-images.githubusercontent.com/5803465/191886083-9d2908ef-c3d9-44b7-a1c2-d12a8935790d.png)

**Comment by jxxghp** [comment]
@lightolly

**Comment by jxxghp** [comment]
修复了
