### ISSUE TITLE
通过jackett搜索出来的密柑资源无法下载

### ISSUE THREAD

**Issue by HBSpy** [jxxghp/nas-tools#1231]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0 c6c47534
>
> 环境: docker

## 你遇到什么问题了？

> 密柑，通过jackett搜索出来的资源也进了要求有站点信息的逻辑

密柑的搜索结果enclosure是这样的，Mikan http://127.0.0.1:9117/dl/mikan/?jackett_apikey=

然后就进了下面的逻辑

```python
# download/downloader.py
if url.startswith("http"):
            # 获取站点维护中的信息
            site_info = self.sites.get_sites(siteurl=url).   // 这儿当然没有
            print(site_info)
            if site_info:
                cookie = site_info.get("cookie")
                ua = site_info.get("ua")
            else:
                # 获取公开站点信息
                site_info = SiteConf().get_public_sites(url=url)
                if not site_info:
                    return None, "找不到下载链接对应的站点配置"    // 在这儿报错了
                log.warn("【DOWNLOADER】无法从站点配置中获得Cookie，尝试自动获取Cookie ...")

```

dmhy 的结果直接是magnet:?xt=urn:btih:xxxxx

## 你期望的结果

> 正常下载喽

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/3386804/191884009-527ff47b-6a5c-4228-ba62-4f99f41da4f1.png)

**Comment by jxxghp** [comment]
已修复
