### ISSUE TITLE
突然不能下载任何资源,

### ISSUE THREAD

**Issue by squaly1** [jxxghp/nas-tools#1233]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>v2.1.0 cbc702f3
> 环境: docker or windows or Synology
>群晖 docker 

## 你遇到什么问题了？
可以搜索到种子,但是不能下载

> 描述一下你遇到的问题
资源搜索,任何资源都下载不了,可以显示出种子,无法下载
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by link2fun** [comment]
**日志日志 没有日志**

**Comment by squaly1** [comment]
群晖docker重启后又可以正常下载了,我再观察一下
