### ISSUE TITLE
部分影片会提示查询不到媒体信息，请确认名称是否正确！

### ISSUE THREAD

**Issue by six00** [jxxghp/nas-tools#1234]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.0 c6c47534
>
> 环境: docker
>

## 你遇到什么问题了？

> tmdb访问正常 但是页面搜索《流金岁月》‘Best Friend's Story 2020’这部电视剧会出现以上问题，查询其他影片正常

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 无法解决

## 你期望的结果

> 正常搜索到该影片

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
![image](https://user-images.githubusercontent.com/18079439/191932966-0a5694a3-e264-4f16-a336-ece34505aa16.png)
2022-09-23 16:57:30,142	INFO: 【DOUBAN】流金岁月 2020 更新到电视剧订阅中...
2022-09-23 16:57:30,527	ERROR: 【META】连接TMDB出错：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-09-23 16:57:30,527	INFO: 【META】流金岁月 以年份 2020 在TMDB中未找到电视剧信息!

**Comment by link2fun** [comment]
日志已经写了
```log
2022-09-23 16:57:30,527 ERROR: 【META】连接TMDB出错：('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**连接TMDB出错**

**Comment by six00** [comment]
我也说了 网络没问题 而且查询其他影片正常 就这个出现问题 导致一直显示订阅中

**Comment by link2fun** [comment]
> 我也说了 网络没问题 而且查询其他影片正常 就这个出现问题 导致一直显示订阅中

说了 是 不通畅 **不是不通**, **不稳定**的意思

**Comment by six00** [comment]
试了好几个其他影片 全都正常 唯独这个 就次次都失败？请问你试过吗 真是网络问题我都不会发这个issue

**Comment by link2fun** [comment]
> 流金岁月

![image](https://user-images.githubusercontent.com/19241982/191959331-696784b3-5d31-4ca9-b883-02420f24e999.png)
![image](https://user-images.githubusercontent.com/19241982/191959369-9722d03c-6b3d-4b56-919d-d1c12001f33c.png)
![image](https://user-images.githubusercontent.com/19241982/191959515-1dbf69d7-3e8c-48f4-96eb-9a6f7a6e369f.png)


三板斧 
1. 再重试
2. 重启
3. 重建容器

**Comment by link2fun** [comment]
![image](https://user-images.githubusercontent.com/19241982/191960544-c0b06a4e-0825-4205-9402-9a2c1dc57a3b.png)
![image](https://user-images.githubusercontent.com/19241982/191960554-af2d0366-3abf-4176-8d3c-07a91d5152f7.png)

**Comment by six00** [comment]
> > 流金岁月
> 
> ![image](https://user-images.githubusercontent.com/19241982/191959824-487f3274-6c5b-4a29-91dd-530137c4ff44.png)
> 
> ![image](https://user-images.githubusercontent.com/19241982/191959369-9722d03c-6b3d-4b56-919d-d1c12001f33c.png) ![image](https://user-images.githubusercontent.com/19241982/191959515-1dbf69d7-3e8c-48f4-96eb-9a6f7a6e369f.png)
> 
> 三板斧
> 
> 1. 再重试
> 2. 重启
> 3. 重建容器

看到了 我这边再排查下 谢谢
