### ISSUE TITLE
PT文件转移问题

### ISSUE THREAD

**Issue by xxzj990** [jxxghp/nas-tools#124]
最近下载的一部电视剧S02识别错误，我在【手动识别】里正确识别后还是一直打印如下日志：

> 2022-05-16 08:59:06,489	INFO: 【PT】开始转移文件...
> 2022-05-16 08:59:06,501	INFO: 【RMT】开始处理：/downloads/nas-tools/pt/tv/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV
> 2022-05-16 08:59:06,534	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E01.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,535	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E01.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,536	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E01.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,536	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E02.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,537	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E02.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,538	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E02.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,538	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E03.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,538	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E03.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,539	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E03.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,539	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E04.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,540	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E04.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,540	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E04.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,541	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E05.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,541	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E05.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,542	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E05.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,542	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E06.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,543	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E06.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,544	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E06.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,544	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E07.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,544	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E07.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,545	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E07.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,545	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E08.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,546	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E08.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,547	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E08.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,547	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E09.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,547	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E09.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,548	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E09.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,549	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E10.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,549	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E10.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,550	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E10.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,550	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E11.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,551	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E11.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,552	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E11.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,552	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E12.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,552	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E12.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,553	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E12.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,554	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E13.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,554	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E13.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,555	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E13.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,555	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E14.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,556	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E14.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,557	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E14.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,557	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E15.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,557	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E15.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,558	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E15.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,559	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E16.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,559	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E16.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,560	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E16.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,560	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E17.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,561	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E17.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,562	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E17.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,562	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E18.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,562	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E18.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,564	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E18.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,564	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E19.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,564	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E19.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,565	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E19.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,566	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E20.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,566	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E20.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,567	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E20.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,568	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E21.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,568	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E21.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,570	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E21.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,570	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E22.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,571	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E22.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,572	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E22.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,572	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E23.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,573	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E23.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,574	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E23.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,574	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E24.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,575	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E24.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,576	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E24.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,576	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E25.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,577	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E25.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,578	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E25.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,578	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E26.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 无法识别媒体信息！
> 2022-05-16 08:59:06,578	WARNING: 【RMT】颤抖吧阿部之朵星风云.Let's.Shake.It.S02E26.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 按原文件名转移到unknown目录：/downloads/nas-tools/links/other
> 2022-05-16 08:59:06,580	WARNING: 【RMT】/downloads/nas-tools/links/other/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV/颤抖吧阿部之朵星风云.Let's.Shake.It.S02E26.V2.1080p.WEB-DL.H264.AAC-OurTV.mp4 文件已存在
> 2022-05-16 08:59:06,580	INFO: 【RMT】/downloads/nas-tools/pt/tv/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV 处理完成，总数：26，失败：26
> 2022-05-16 08:59:06,580	WARNING: 【PT】/downloads/nas-tools/pt/tv/颤抖吧阿部之朵星风云.Let's.Shake.It.S02.V2.1080p.WEB-DL.H264.AAC-OurTV 转移失败：无法识别媒体信息

日志已经打印爆了，14MB大小了。。。这种手动识别成功后还一直尝试转移文件有方法处理吗？非常谢谢～

**Comment by xxzj990** [comment]
我详细看了一下日志，貌似所有【无法识别媒体信息！】的这种都会出这个问题，不是这部剧的特例

**Comment by jxxghp** [comment]
PT转移5分钟就处理一次，最新代码已修复。

**Comment by xxzj990** [comment]
> PT转移5分钟就处理一次，最新代码已修复。

已升级测试，好了🎉
