### ISSUE TITLE
 老电影订阅不能下载

### ISSUE THREAD

**Issue by unyielding2013** [jxxghp/nas-tools#1240]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker
>

## 你遇到什么问题了？

> 电影订阅不能下载，日志提示是电视剧不是电影，比如订阅老电影《无双》。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

>订阅 正常下载

## 给出程序界面截图、后台运行日志或配置文件

> 22:09:01 INFO - 【INDEXER】Project Gutenberg 2018 1080p WEB-DL H264 AAC-fuckbt 是 电视剧，不是 电影
   22:09:01 INFO - 【INDEXER】Project Gutenberg 2018 2160p WEB-DL AAC x265-NYHD 是 电视剧，不是 电影
   22:09:01 INFO - 【INDEXER】Project Gutenberg 2018 4K WEB-DL H265 AAC-NYHD 是 电视剧，不是 电影
   22:09:01 INFO - 【INDEXER】Project Gutenberg 2018 1080p WEB-DL AAC H265-OurTV 是 电视剧，不是 电影
   22:09:01 INFO - 【INDEXER】Project Gutenberg 2018 WEB-DL 4K H264 AAC-NYHD 是 电视剧，不是 电影
   22:09:01 INFO - 【INDEXER】Project Gutenberg 2018 1080p WEB-DL H264 AAC-TJUPT 是 电视剧，不是 电影

**Comment by jxxghp** [comment]
清TMDB缓存

![image](https://user-images.githubusercontent.com/51039935/191983856-f788f375-c00e-471b-9fbb-6d47f51f6713.png)

**Comment by unyielding2013** [comment]
> 清TMDB缓存
> 
> ![image](https://user-images.githubusercontent.com/51039935/191983856-f788f375-c00e-471b-9fbb-6d47f51f6713.png)

还真是
