### ISSUE TITLE
添加更多签到方式

### ISSUE THREAD

**Issue by DDS-ALL** [jxxghp/nas-tools#1242]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.1
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 目前的签到方式只支持大多数普通的PT站点，向hdarea这种站点就不能正常签到，所以想添加更多签到站点的支持

## 这个功能有什么可以参考的资料吗？

> https://github.com/aLuvletter/pt_res
>也是用Python写的，应该有参考价值

**Comment by jxxghp** [comment]
后续会使用浏览器仿真签到
