### ISSUE TITLE
诚求一下windows下如何外网访问的方法

### ISSUE THREAD

**Issue by fayswing** [jxxghp/nas-tools#1244]
你使用的 NASTool 是什么版本，什么环境？
NASTool 版本: v2.1.1

环境: windows

你想要新增或者改进什么功能？

想新增windows下外网访问的方法        
映射了3000端口     可是外网无法访问 
wiki里能增加下说明就更好了    谢谢

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/192092208-65206a6f-1d88-44bc-96e5-c7fbb00145ba.png)

#### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助

**Comment by fayswing** [comment]
修改以后就无法启动   出现了下面的错误

![image](https://user-images.githubusercontent.com/44943458/192093156-17b4d5a2-89b0-4d4d-b174-f30a008bfda0.png)


> ![image](https://user-images.githubusercontent.com/16237201/192092208-65206a6f-1d88-44bc-96e5-c7fbb00145ba.png)
> 
> #### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助
