### ISSUE TITLE
为什么在tmdb能搜到的电影，在nastools搜不到

### ISSUE THREAD

**Issue by Wanderingkang** [jxxghp/nas-tools#1246]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>2.1
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 在tmdb上能搜到电影，在nastools搜不到
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/192092138-cfa7e754-4d45-4743-b11b-22c3c4f19a29.png)
没有任何有效信息，无法分析
