### ISSUE TITLE
当媒体库设置成根目录时候,启用二级分类不会触发自动同步目录

### ISSUE THREAD

**Issue by ati121** [jxxghp/nas-tools#1251]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.11
>
> 环境: docker 
>

## 你遇到什么问题了？

![999](https://user-images.githubusercontent.com/72114654/192086754-7e9a27e4-281f-41f4-83bd-3284d4951576.jpg)
在这个帖子看到作者的这个方案,非常好.可以不改现有媒体库结构的情况启用自动分类入库..但是我测试了下.有个小BUG.
当我把所有媒体库目录都设置成根目录的时候..同步目录实时监控并不会触发,只有手动,以剧集为例,
![97](https://user-images.githubusercontent.com/72114654/192086959-84d7993f-1279-4266-aa91-7798f5b973a3.jpg)
![77](https://user-images.githubusercontent.com/72114654/192086970-2f8f1cc3-21bd-49d5-8dd8-46ae8d35711d.jpg)
vido3是根目录.二级分类已经设置好,
同步目录为图所设.
![66](https://user-images.githubusercontent.com/72114654/192087066-af8c51d8-2961-4633-a63a-7dda53265f47.jpg)
测试.这时候我移动一个文件到video3的PT目录下,目录同步并不会自动触发(之前测试重启容器,删除user.db等,最多等了30分钟都没动).如果手动可以识别并转移.
![98](https://user-images.githubusercontent.com/72114654/192087280-a4873006-f0cb-4b0d-8bce-f77d7f419132.jpg)
如果我把媒体库目录设置到根目录的二级目录下(然后重启容器,重新把文件剪切到同步目录),同步目录监控就会立马触发识别并转移
![11](https://user-images.githubusercontent.com/72114654/192087364-b6d59d45-ba59-4adb-a577-42b8fdc5c69c.jpg)
![999999999999999](https://user-images.githubusercontent.com/72114654/192087608-03d81717-3e53-4502-a651-064a23e8608c.jpg)

这个根目录为媒体库方案非常好,适合各种不想改变现有结构的.都可以适配.望查看下这个问题.

**Comment by jxxghp** [comment]
这都嵌套了，再同步就死循环了
