### ISSUE TITLE
企业微信代理

### ISSUE THREAD

**Issue by JavaZeroo** [jxxghp/nas-tools#1253]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.1
>
> 环境: docker
## 你想要新增或者改进什么功能？
![image](https://user-images.githubusercontent.com/71128095/192102953-0687fdea-be5c-4a44-ac08-3af0aac11a9e.png)
把这个socks代理功能也添加给企业微信的代理上面

## 这个功能有什么可以参考的资料吗？
复制一下

**Comment by jxxghp** [comment]
竟然是用来做微信代理的，一般都是正常网络能连上的吧，不然怎么做为代理

**Comment by JavaZeroo** [comment]
> 竟然是用来做微信代理的，一般都是正常网络能连上的吧，不然怎么做为代理

微信的代理要用https或者socks，目前socks部署比https简单一点。

我想着，既然本来就支持socks代理，为何不让企业微信的代理也支持socks代理

**Comment by jxxghp** [comment]
> > 竟然是用来做微信代理的，一般都是正常网络能连上的吧，不然怎么做为代理
> 
> 
> 
> 微信的代理要用https或者socks，目前socks部署比https简单一点。
> 
> 
> 
> 我想着，既然本来就支持socks代理，为何不让企业微信的代理也支持socks代理

微信的消息代理的目的是为了让有公网IP的服务器透传改掉源IP，换成socks协议办不到吧

**Comment by JavaZeroo** [comment]
> > > 竟然是用来做微信代理的，一般都是正常网络能连上的吧，不然怎么做为代理
> > 
> > 
> > 微信的代理要用https或者socks，目前socks部署比https简单一点。
> > 我想着，既然本来就支持socks代理，为何不让企业微信的代理也支持socks代理
> 
> 微信的消息代理的目的是为了让有公网IP的服务器透传改掉源IP，换成socks协议办不到吧

是可以做到的，因为折腾不来https。然后socks可以直接一键部署，所以试了一下。
![image](https://user-images.githubusercontent.com/71128095/193036374-742a7e5e-8411-4fc8-84a4-73efd6d208e5.png)

**Comment by jxxghp** [comment]
有能力的话PR吧
