### ISSUE TITLE
> 没法分析，重新安装配置吧

### ISSUE THREAD

**Issue by Dr-Lee-Go** [jxxghp/nas-tools#1254]
> 没法分析，重新安装配置吧

user.db数据库，刷流表里有脏数据，我删掉后恢复了，谢谢。

_Originally posted by @huluohu in https://github.com/jxxghp/nas-tools/issues/1207#issuecomment-1255072372_
      你好的，我尝试删除user,db后，确实可以打开刷流界面了，但是发现“站点维护”的站点都没没了。站点稍多，重新输入好头疼，请教能否修改这个db文件来修复此问题，求教！谢谢！

**Comment by huluohu** [comment]
> ```
>     > 没法分析，重新安装配置吧
> ```
> 
> user.db数据库，刷流表里有脏数据，我删掉后恢复了，谢谢。
> 
> _Originally posted by @huluohu in [#1207 (comment)](https://github.com/jxxghp/nas-tools/issues/1207#issuecomment-1255072372)_ 你好的，我尝试删除user,db后，确实可以打开刷流界面了，但是发现“站点维护”的站点都没没了。站点稍多，重新输入好头疼，请教能否修改这个db文件来修复此问题，求教！谢谢！

不要删除整个user.db啊，只需要删除里面表中的数据即可。
