### ISSUE TITLE
设备移动文件夹后，重启NAS不能继续下载，文件丢失

### ISSUE THREAD

**Issue by SheepChao** [jxxghp/nas-tools#1255]
> NASTool 版本: v2.1.1 daedc63
>qnap docker 
qBittorrent v4.4.5
emby 4.7.6.0

在媒体同步文件夹里面设置了移动文件，在qBittorrent还没有下载完成，nastools已经开始移动文件了，nas重启后qBittorrent就找不到旧的文件了，不能继续下载了。同时在emby里面可以看到有媒体图片和字幕了，但是无法播放。重启前可以看到qBittorrent 中依然在下载，但是在指定的下载文件夹里面已经没有文件了。

**Comment by Shurelol** [comment]
![Screenshot_20220925-102059_Telegram](https://user-images.githubusercontent.com/16237201/192125487-f64f1f66-e545-464e-8b5d-1d40863bdc84.jpg)
#### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助
