### ISSUE TITLE
0.9.05 jellyfin中未开启显示每季缺少剧集选项，订阅未下载的剧集时，提示剧集已全部存在。

### ISSUE THREAD

**Issue by Linyue-GitHub** [jxxghp/nas-tools#126]
日志：
12:43:03 - 配置文件地址：/config/config.yaml
12:43:03 - NASTool 当前版本号：v0.9.05
12:43:03 - 日志输出类型为：file
12:43:03 - 日志将写入文件：/config/logs
12:43:03 INFO - WEB管理页面用户：linyue
12:43:03 INFO - 未启用https，请使用 http://IP:3000 访问管理页面
12:43:03 INFO - TMDB匹配模式：正常模式
12:43:03 INFO - 媒体管理软件设置为：jellyfin
12:43:03 WARN - 未配置分类策略
12:43:03 INFO - 目录同步转移模式为：硬链接
12:43:03 INFO - PT下载软件设置为：qbittorrent
12:43:03 INFO - PT下载文件转移模式为：硬链接
12:43:03 INFO - PT检索软件设置为：jackett
12:43:03 INFO - PT保种时间未配置，自动删种功能已关闭
12:43:03 INFO - 下载软件监控未开启，PT下载监控功能已关闭
12:43:03 - 开始启动进程...
12:43:04 INFO - 【RUN】scheduler.pt_signin启动...
12:43:04 INFO - 【RUN】scheduler.rss_download启动...
12:43:04 INFO - 【RUN】scheduler.douban_sync启动...
12:43:04 INFO - 【SYNC】读取到监控目录：/PT/电影，目的目录：/PT/jellyfin_video/电影
12:43:04 INFO - 【SYNC】读取到监控目录：/PT/耽美/电影，目的目录：/PT/jellyfin_video/耽美/电影
12:43:04 INFO - 【SYNC】读取到监控目录：/PT/动漫/电影，目的目录：/PT/jellyfin_video/动漫/电影
12:43:04 INFO - 【SYNC】读取到监控目录：/PT/电视剧，目的目录：/PT/jellyfin_video/电视剧
12:43:04 INFO - 【SYNC】读取到监控目录：/PT/耽美/真人剧集，目的目录：/PT/jellyfin_video/耽美/真人剧集
12:43:04 INFO - 【SYNC】读取到监控目录：/PT/动漫/剧集，目的目录：/PT/jellyfin_video/动漫/剧集
12:43:04 INFO - 【SYNC】读取到监控目录：/PT/耽美/动画剧集，目的目录：/PT/jellyfin_video/耽美/动画剧集
12:43:04 INFO - 【RUN】/PT/电影 的monitor.media_sync启动...
12:43:04 INFO - 【RUN】/PT/耽美/电影 的monitor.media_sync启动...
12:43:04 INFO - 【RUN】/PT/动漫/电影 的monitor.media_sync启动...
12:43:04 INFO - 【RUN】/PT/电视剧 的monitor.media_sync启动...
12:43:04 INFO - 【RUN】/PT/耽美/真人剧集 的monitor.media_sync启动...
12:43:04 INFO - 【RUN】/PT/动漫/剧集 的monitor.media_sync启动...
12:43:04 INFO - 【RUN】/PT/耽美/动画剧集 的monitor.media_sync启动...
12:43:17 INFO - 消息内容：数码宝贝幽灵游戏
12:43:17 INFO - 【SEARCHER】正在识别 数码宝贝幽灵游戏 的媒体信息...
12:43:18 INFO - 类型：动漫，标题：数码宝贝：幽灵游戏，年份：2021
12:43:19 INFO - 【META】正在查询TMDB：134843 ...
12:43:19 INFO - 【PT】动漫 数码宝贝：幽灵游戏 (2021) 共有 1 季
12:43:20 INFO - 【PT】数码宝贝：幽灵游戏 (2021) 第1季 共26集 已全部存在

jellyfin设置截图
![网页捕获_16-5-2022_12478_10 0 0 128](https://user-images.githubusercontent.com/71179298/168522008-22d83827-1326-4706-8aad-3560abbbee61.jpeg)

**Comment by jxxghp** [comment]
一直示找到原因，有人正常吗？

**Comment by JimyZhang** [comment]
我好像也遇到了这个问题，提示已存在我在媒体库找了几遍也没找到，我还奇怪怎么回事。
<img width="809" alt="image" src="https://user-images.githubusercontent.com/39080199/169196110-9a111dde-d3a7-4d5c-b183-eba479b19ee0.png">

**Comment by zhuxiangxiao** [comment]
> 一直没找到原因，有人正常吗？

@jxxghp 这个应该就是我刚刚pr的那个fix。我也是这个问题

**Comment by jxxghp** [comment]
> > 一直没找到原因，有人正常吗？
> 
> @jxxghp 这个应该就是我刚刚pr的那个fix。我也是这个问题

正常如果是有配置emby/plex，是会优先从emby/plex判重的，这两个没配置才会到基于媒体库目录文件判重

**Comment by jxxghp** [comment]
这个问题应该解决了，v1.1.1
