### ISSUE TITLE
目录同步报错[Errno 24] inotify instance limit reached

### ISSUE THREAD

**Issue by rockhia** [jxxghp/nas-tools#1262]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.1
>
> 环境: docker 
>

## 你遇到什么问题了？
改了一次媒体库发现不能自动硬链接，便又改回去了。
更改为原来设置，同时也使用过修改前的备份，都出现同样的错误。
同时双开的一个只用于刷流的docker，在设置同步目录时，也会报相同的错误
![Screenshot_20220925_160718](https://user-images.githubusercontent.com/90016652/192134998-87426fee-2615-4171-a94f-b411cb807f87.jpg)
[Errno 24] inotify instance limit reached
在报错后使用过以下方法：
1、文件夹权限设置为every one
2，使用修改前备份的配置文件
3，使用只配置了刷流的docker版nas-tool
上述方法均会复现错误

## 你期望的结果
找到能解决该错误的方法。

**Comment by rockhia** [comment]
在服务内，手动点击目录同步可以生成硬链接转移成功，但是不能实时监视，自动同步

**Comment by jxxghp** [comment]
wiki里大大的字写着不先看一下
