### ISSUE TITLE
希望大佬适配下https://www.hd.ai/这个种自站

### ISSUE THREAD

**Issue by lzxxdfx1** [jxxghp/nas-tools#1267]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>2.1.1
> 环境: docker or windows or synology
docler
## 你想要新增或者改进什么功能？
新增https://www.hd.ai/种子站

**Comment by huluohu** [comment]
这个自己添加站点就行

**Comment by jxxghp** [comment]
这个站貌似难度比较大，是动态响应的

**Comment by jxxghp** [comment]
太难，放弃
