### ISSUE TITLE
目录同步的模式能否稍微调整一点？

### ISSUE THREAD

**Issue by EliteOtaku** [jxxghp/nas-tools#1268]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.1 7212cf2e
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 各位尊敬的开发者大佬，你们好，请先看下图
![image](https://user-images.githubusercontent.com/29235152/192145320-00147263-9503-4de4-b72a-b16615483d9a.png)
![image](https://user-images.githubusercontent.com/29235152/192145345-c948e9b7-8ac7-4fb2-9cbe-693ecf1265d7.png)
![image](https://user-images.githubusercontent.com/29235152/192145678-d64f502d-c430-4611-a451-d393e8e79324.png)

https://share.dmhy.org/topics/list?keyword=%E8%93%9D%E5%AE%9D%E7%9F%B3%E4%B9%8B%E8%B0%9C
下载回来的蓝宝石之谜中，有字幕组塞进去的PV和特典，这些东西在TMDB数据库里面基本是没办法对应的，有时候我还会在Season 0里面存放一些OST作为纪念，有些电影也是，会保存一些幕后花絮，这些无法识别的，都不能通过目录同步功能转移到媒体库中，只能手动操作。因为NASTool貌似只会同步识别出来的剧集。

如果能调整一下，增加一个同步剧集目录下的所有文件，可以给大家多一个选择也不错，比如这样的情况，可以把目录蓝宝石之谜 高清重制版 (2012)下所有文件一股脑儿同步到媒体库那边，就可以做到优雅的全自动了，多谢大大们！

**Comment by netduke777** [comment]
我前面也向老大们建议增加一个不搜刮而直接建立硬连的功能需求, 兄弟们给的回应是暂时关闭整个目录的搜刮来解决,感觉不好.
我当时的建议是: 在导入媒体时,给一个按钮是直接建连接而不搜刮, 并且可以给出选项让人自动建立一些背景图,或简介啥的选项.
