### ISSUE TITLE
多語言

### ISSUE THREAD

**Issue by huskyy8y8** [jxxghp/nas-tools#1269]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.1
>
> 环境: windows 

## 你想要新增或者改进什么功能？

> 多語言，希望支持繁體中文，主頁,搜索,推薦 支援更多語言

## 这个功能有什么可以参考的资料吗？

> 無

**Comment by Shurelol** [comment]
使用chrome浏览器，页面空白处右键点击，翻成中文（繁体）或其他语言

#### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助
