### ISSUE TITLE
站点签到失效

### ISSUE THREAD

**Issue by kscu** [jxxghp/nas-tools#1270]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.1
>
> 环境:  Synology
>

## 你遇到什么问题了？

> 站点签到服务正常运行，但是在每天规定的时间没有执行签到任务。上一版正常

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 修正BUG

## 给出程序界面截图、后台运行日志或配置文件

> 看程序日志内站点签到确实没有运行日志。
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
站点里重新选择一下用途
