### ISSUE TITLE
电视剧识别错误问题？被随机合并在一起

### ISSUE THREAD

**Issue by yilin101** [jxxghp/nas-tools#1271]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.1 7212cf2e
>
> 环境: docker  

## 你遇到什么问题了？

> 几个电视剧都能识别出来 但是在plex 随机合并在一起，有的甚至不显示出来，
删除重新识别N次了,一直解决不了，电影没有此问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 搜索了 没找到相关问题

## 你期望的结果

> 帮忙解决这个问题

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
![](https://i.niupic.com/images/2022/09/26/a5wZ.png
![](https://i.niupic.com/images/2022/09/26/a5x2.png
![](https://i.niupic.com/images/2022/09/26/a5x0.png
![](https://i.niupic.com/images/2022/09/26/a5x3.png
![](https://i.niupic.com/images/2022/09/26/a5x1.png
![](https://i.niupic.com/images/2022/09/26/a5x4.png

**Comment by yilin101** [comment]
![](https://i.niupic.com/images/2022/09/26/a5wZ.png)
![](https://i.niupic.com/images/2022/09/26/a5x2.png)
![](https://i.niupic.com/images/2022/09/26/a5x0.png)
![](https://i.niupic.com/images/2022/09/26/a5x3.png)
![](https://i.niupic.com/images/2022/09/26/a5x1.png)
![](https://i.niupic.com/images/2022/09/26/a5x4.png)

**Comment by Solarisxcao** [comment]
我也碰到过这个问题，好像是因为是他把一级目录作为一个媒体然后二级目录看做是不同的season了，你多分几个媒体库就解决了

**Comment by yilin101** [comment]
> 我也碰到过这个问题，好像是因为是他把一级目录作为一个媒体然后二级目录看做是不同的season了，你多分几个媒体库就解决了

多分几个媒体库是什么意思？

**Comment by baozaodetudou** [comment]
> > 我也碰到过这个问题，好像是因为是他把一级目录作为一个媒体然后二级目录看做是不同的season了，你多分几个媒体库就解决了
> 
> 多分几个媒体库是什么意思？

plex应该是涉及到多级目录的问题了吧

**Comment by yilin101** [comment]
> > > 我也碰到过这个问题，好像是因为是他把一级目录作为一个媒体然后二级目录看做是不同的season了，你多分几个媒体库就解决了
> > 
> > 
> > 多分几个媒体库是什么意思？
> 
> plex应该是涉及到多级目录的问题了吧

把两个文件夹分成两个媒体库？

**Comment by Solarisxcao** [comment]
> > > > 我也碰到过这个问题，好像是因为是他把一级目录作为一个媒体然后二级目录看做是不同的season了，你多分几个媒体库就解决了
> > > 
> > > 
> > > 多分几个媒体库是什么意思？
> > 
> > 
> > plex应该是涉及到多级目录的问题了吧
> 
> 把两个文件夹分成两个媒体库？

就比如说 
-tv
|
----动漫
|
----欧美剧
tv 下有 动漫，欧美剧两个文件夹
plex会默认文件夹为一个媒体
你的媒体库设置路径为tv
它会扫描tv下的文件夹
他扫到里面有两个文件夹
ok，那他觉得你有两部剧
然后他会把这两个文件夹下的目录当成不同的season
大概运行逻辑就是这样
所以你要把每个二级目录都变成一个媒体库，而不是就tv一个。

**Comment by yilin101** [comment]
> > > > > 我也碰到过这个问题，好像是因为是他把一级目录作为一个媒体然后二级目录看做是不同的season了，你多分几个媒体库就解决了
> > > > 
> > > > 
> > > > 多分几个媒体库是什么意思？
> > > 
> > > 
> > > plex应该是涉及到多级目录的问题了吧
> > 
> > 
> > 把两个文件夹分成两个媒体库？
> 
> 就比如说 -tv | ----动漫 | ----欧美剧 tv 下有 动漫，欧美剧两个文件夹 plex会默认文件夹为一个媒体 你的媒体库设置路径为tv 它会扫描tv下的文件夹 他扫到里面有两个文件夹 ok，那他觉得你有两部剧 然后他会把这两个文件夹下的目录当成不同的season 大概运行逻辑就是这样 所以你要把每个二级目录都变成一个媒体库，而不是就tv一个。

感谢 高手 果然可以了 就是分类有点多 每个都得添加一遍

**Comment by jxxghp** [comment]
这个不是工具的问题
