### ISSUE TITLE
目录同步无法自动进行

### ISSUE THREAD

**Issue by EliteOtaku** [jxxghp/nas-tools#1272]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.1 7212cf2e
>
> 环境: docker 
>

## 你遇到什么问题了？

> 设定好目录同步后，每次影片会自动分类并硬链接到hlink目录下的子目录中，但需要手动执行一次同步，才会将子目录下的剧集同步到Emby的媒体库。

这是用default-category.yaml分类后保存的（上次这个问题已经解决了，非常感谢大佬们的指点）
![image](https://user-images.githubusercontent.com/29235152/192197104-205bec54-f64e-4b8a-8470-bb7e38a59013.png)

![image](https://user-images.githubusercontent.com/29235152/192197152-b0ff8ad0-1dfb-4241-82c1-61206142ed4f.png)
![image](https://user-images.githubusercontent.com/29235152/192197221-bbb0e53e-b259-4845-b182-32c6e704be0c.png)

![image](https://user-images.githubusercontent.com/29235152/192197399-ee8e81df-fc79-4441-81ac-045f61c3041c.png)
![image](https://user-images.githubusercontent.com/29235152/192197461-f725faf3-105b-4327-a024-5b635eab96b7.png)

怀疑是不是因为硬链接的问题，但我确认这几个文件夹都是在同一个存储池的，应该可以排除这方面的问题。
希望大佬能指点一下是哪里操作失误了，非常感谢。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 浏览过了，也按小秘书的方法执行过。
※  问题描述
 •   目录同步无法自动同步或只有部份目录正常，但在服务中手动启动可以正常同步

※  解决办法：
 •   宿主机上（不是docker容器里），执行以下命令：
  echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
  echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
  sudo sysctl -p

**Comment by baozaodetudou** [comment]
目录监控打开了吗？

**Comment by EliteOtaku** [comment]
> 目录监控打开了吗？

按上面图片显示应该是开了的，我一会再测试一下，貌似整理到hlink目录后，要等一段时间才会再次硬链接到Emby媒体库

**Comment by baozaodetudou** [comment]
> > 目录监控打开了吗？
> 
> 按大家应该是查看的图片链接，我一会再显示一下，表情整理到目录后，要等会用硬件链接链接到媒体库

硬链接成功的话就不会存在跨盘，至于emby显示慢，是因为emby需要刮削第一次慢后来就快了

**Comment by EliteOtaku** [comment]
![image](https://user-images.githubusercontent.com/29235152/192232122-8a1869bc-97d3-4145-9298-6ea5fd72e56b.png)


> > > 目录监控打开了吗？
> > 
> > 
> > 按大家应该是查看的图片链接，我一会再显示一下，表情整理到目录后，要等会用硬件链接链接到媒体库
> 
> 硬链接成功的话就不会存在跨盘，至于emby显示慢，是因为emby需要刮削第一次慢后来就快了

和Emby显示慢没关系，因为我看到hlink目录下已经出现了新的剧集，但是这时候去群晖的文件夹里面看，Emby的目录下没有出现对应的剧集，所以我觉得奇怪
![image](https://user-images.githubusercontent.com/29235152/192234367-0f574c55-e83f-4504-ac95-b0ac331126c9.png)

你看，我在16：38在media目录下放了一个黑话律师的剧集，立刻就被Nastool监控了，然后硬链接到hlink目录下的tv子目录，到此为止都是正常的，但之后，按我目录同步的设置，这里应该也会立刻硬链接到Emby的tv子目录里面，可我在群晖里面查看的时候，发现并没有同时进行，所以我才纳闷。

**Comment by EliteOtaku** [comment]
> 
对了，解释一下，因为我是把Emby的媒体库设置在另外一个目录下，这样可以避免和hlink目录下的合在一起，这样分开来，以后移动的时候，只需要记住保存Emby的那个库即可，不容易出错。简而言之，就是增量同步。

**Comment by jxxghp** [comment]
你这个把我看迷糊了，为啥要分两步，最后一条不是硬链接完了吗，上面这些又往上级目录再链接一次？

**Comment by EliteOtaku** [comment]
> 

哈哈，能把老大弄迷糊，我也是佩服我自己了。

我的思路是，因为我自己以前已经有一个Emby媒体库（简称A），然后下载器下载到了目录media（简称B），然后目录media根据default-category.yaml分类硬链接到hlink目录（简称C），按道理，我是可以直接把Emby媒体库增加一个分支目录指向C即可在Emby中浏览观看，但是我担心自己以后备份或者移动A的时候，会忘记了C，导致C不小心被删除，所以需要把C再次硬链接同步到A中，这样以后维护或者更换主机的时候，只需要记住把A移动过去就好了。不知道这样解释，老大是否理解了？

PS：之前我提议的目录同步时，把Seanson 0和Extras之类的一并同步，老大是否会考虑呢？

希望老大的肝永远年轻

**Comment by gatalon** [comment]
我这里也遇到了需要手动执行的问题，实时日志显示已经正常监控目录了，但还是需要手工执行一下才行。

**Comment by CookieSir** [comment]
> 我这里也遇到了需要手动执行的问题，实时日志显示已经正常监控目录了，但还是需要手工执行一下才行。

我也是怎么弄都无解

**Comment by yubanmeiqin9048** [comment]
目录同步失效的情况确实是偶有发生，原因不明

**Comment by xyx208** [comment]
> 我这里也遇到了需要手动执行的问题，实时日志显示已经正常监控目录了，但还是需要手工执行一下才行。

我也遇到这个问题了，手动执行没问题。另外有没有可以在外部执行的命令（类似这样的：docker exec -it nas-tools app sync
）来执行目录同步，变相解决这个问题。@EliteOtaku 感谢您的辛苦付出。

**Comment by wangrui1573** [comment]
> 
我也遇到了这个问题，我监控的目录不是本地，是挂载的SMB，自动不行，手动可以，最后设置了定时任务来透过API执行

`#! /bin/bash  
  



 #获取token到json
    curl -X 'POST' \
	      'http://IP:3000/api/v1/user/login' \
	        -H 'accept: application/json' \
		  -H 'Authorization: obKOWZYADsCn43hG' \
		    -H 'Content-Type: application/x-www-form-urlencoded' \
		      -d 'username=admin&password=改成密码' \
		      > /tmp/token.json
 #获取token到txt
 cat /tmp/token.json  | awk -F '", "apikey' '{print $1}'| awk -F 'token": "' '{print $2}' > /tmp/token.txt
 #读取token
token=$(cat /tmp/token.txt)


 #打印token
 echo $token
 #发起搜索

   curl -X 'POST' \
	     'http://IP:3000/api/v1/service/run' \
	       -H 'accept: application/json' \
	       -H 'Authorization:'$token'' \
		   -H 'Content-Type: application/x-www-form-urlencoded' \
		     -d 'item=sync'


`

**Comment by jxxghp** [comment]
#1870
