### ISSUE TITLE
请问是否可以选择保留外语剧集和电影的原始名称而不转化为中文

### ISSUE THREAD

**Issue by vincexo** [jxxghp/nas-tools#1275]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.1
>
> 环境: synology

目前NasTool里自动化电影和剧集，遇到外文剧集，搜刮整理后就会重命名为中文。当实用dlna浏览文件的时候，经常不知道这个到底是哪个剧。

请问能否添加一个功能，选择是否以外文原始剧名重命名，或者同时以中外文命名。

比如源文件为：[House.of.the.Dragon.S01E06.HDR.2160p.WEB.h265-TRUFFLE]，
目前系统会自动把下载的文件重命名为：龙之家族 - S01E05 - 第五集
是否可以让我们选择以外文原始剧名来重命名，比如： House.of.the.Dragon.S01E06

这个功能对于生活在中国的外国人至关重要，非常感谢你能做出如此伟大的作品。

**Comment by ati121** [comment]
> ## 你使用的 NASTool 是什么版本，什么环境？
> > NASTool 版本: v2.1.1
> > 环境: synology
> 
> 目前NasTool里自动化电影和剧集，遇到外文剧集，搜刮整理后就会重命名为中文。当实用dlna浏览文件的时候，经常不知道这个到底是哪个剧。
> 
> 请问能否添加一个功能，选择是否以外文原始剧名重命名，或者同时以中外文命名。
> 
> 比如源文件为：[House.of.the.Dragon.S01E06.HDR.2160p.WEB.h265-TRUFFLE]， 目前系统会自动把下载的文件重命名为：龙之家族 - S01E05 - 第五集 是否可以让我们选择以外文原始剧名来重命名，比如： House.of.the.Dragon.S01E06
> 
> 这个功能对于生活在中国的外国人至关重要，非常感谢你能做出如此伟大的作品。

认真看提示啊.软件有这个功能
![9](https://user-images.githubusercontent.com/72114654/192263545-6f6acf3c-dc87-48dc-825e-c1d833c0876b.jpg)

**Comment by ati121** [comment]
![9](https://user-images.githubusercontent.com/72114654/192263804-cc892903-9032-4b04-aab0-2d8f46243a25.jpg)
