### ISSUE TITLE
站点管理-数据统计，点击菜单后页面无反应

### ISSUE THREAD

**Issue by ThierryCheng** [jxxghp/nas-tools#1277]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 站点管理-数据统计，点击菜单后页面无反应。
通过在线升级，点击无反应；
dokcer重置升级后，仍然点击无反应

> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
点击后无法应，实时日志和docker下均未产生日志

**Comment by Shurelol** [comment]
### 站点维护中将需要数据统计的站点设置上数据统计用途
![image](https://user-images.githubusercontent.com/16237201/192292120-cf1bccd4-af38-4064-a010-70fa8c35e9ee.png)
#### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助
