### ISSUE TITLE
关于媒体整理中的"重新识别"和"历史记录"删除功能上的建议和需求,谢谢

### ISSUE THREAD

**Issue by netduke777** [jxxghp/nas-tools#1278]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>2.2.1
> 环境: docker or windows or synology
docker qnap
## 你想要新增或者改进什么功能？
关于重新识别片源后, 源文件依旧存在, 需要手动删除, 其实质和添加一个新片没有区别, 这就和"重新识别"的含义有点不一致了. 
感觉应该是自动删除或重新命名原有文件夹, 然后重新刮削文件(可能删除来的简单些). 另外重新识别,在NAS-TOOLS的历史中也是存在了2个项目(相当于新增一个不同文件),这在开始的时候没啥, 但是当有几千个文件时, 很麻烦,如果能自动删除并新建就好了. 
另外有的时候洗板后,历史记录中有多个记录,但是片库中仅有一个(最高分辨率)片子, 但是这时候删除仍和一个老的记录都=删除这个片子的唯一的目录(相当于洗板后称为多个记录对应一个目录). 如果能改进成为删除老的片子仅是删除历史记录或是其对应的硬链接文件,直到这个目录对应的最后一个片子删除时才真正删除其片子对应的目录就完美了, 不知道实现上是否有难度.
这点上总是感觉有点别扭, 在实现难度不大的情况下, 望大大能给予改进, 谢谢.

> 你想要新增或者改进什么功能？
重新识别==自动删除原有片子的目录, 然后新建一个新的片子目录;
删除旧的导入历史记录==能查看此片子目录是否仅唯一对应此记录, 唯一则删除目录, 不唯一仅删除本记录对应的文件.
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
历史记录有删除功能。
写的太乱了，一个个问题说明，提供日志和截图。
