### ISSUE TITLE
请问为什么searcher查询不到媒体信息

### ISSUE THREAD

**Issue by Ks-luow** [jxxghp/nas-tools#128]
![Screenshot_2022-05-17-07-50-05-247_com tencent mtt](https://user-images.githubusercontent.com/64978950/168702279-b9784bf4-cd87-460f-a2f5-67702927c22d.jpg)
在调用searcher查询时会瞬间返回查询不到，请问这个searcher走的什么，我查询了jk的log，并没有相关的访问记录

**Comment by jxxghp** [comment]
查询TMDB
