### ISSUE TITLE
NAS迅雷支持

### ISSUE THREAD

**Issue by CatNeverCodes** [jxxghp/nas-tools#1283]
## 你使用的 NASTool 是什么版本，什么环境？
> NASTool 版本: v2.1.1 b323a1dc
> 环境: docker 群晖DSM7.x

## 你想要新增或者改进什么功能？
下载器支持，新增迅雷下载支持。

## 这个功能有什么可以参考的资料吗？
> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
https://nas.xunlei.com/
https://open.thunderurl.com/#/

**Comment by Shurelol** [comment]
### 用迅雷干嘛呢？下bt？
### 一边用迅雷吸血，一边说bt没人做种下不动，不矛盾吗？

**Comment by CatNeverCodes** [comment]
> 

我也刚接触NAS版的迅雷，未熟悉情况留下这条 issue。发现速度是有，却有收费限制。 此 issue 我会关闭。 打扰了。
