### ISSUE TITLE
每次进入NASTOOL或者刷新显示的存储空间容量不同

### ISSUE THREAD

**Issue by wangguosu520** [jxxghp/nas-tools#1285]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>2.1.1
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 每次进入NASTOOL或者刷新显示的存储空间容量不同,这个存储空间占用量是在下载器里获取的吗

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 
![1](https://user-images.githubusercontent.com/76019309/192414434-f5eee35e-bceb-4957-aa88-108c3ab256af.png)
![2](https://user-images.githubusercontent.com/76019309/192414443-33ad85d6-e0d9-42ff-bdf5-a1ef95b36bb9.png)
![3](https://user-images.githubusercontent.com/76019309/192414447-f8a3fa7d-a524-4091-82a1-d1ea751c54df.png)

**Comment by jxxghp** [comment]
给下媒体库目录的配置

**Comment by wangguosu520** [comment]
> 给下媒体库目录的配置

![屏幕截图 2022-09-27 201939](https://user-images.githubusercontent.com/76019309/192524699-e9f01a45-d9d1-4288-8ba1-e5c69048f38e.jpg)
