### ISSUE TITLE
请教Jellyfin的webhook问题

### ISSUE THREAD

**Issue by firstvip** [jxxghp/nas-tools#129]
请教大佬，企业微信通知测试可以收到。但jellyfin播放通知怎么搞都不行，不知道错在哪里了能否指点一下，谢谢！
![8C67C81F-F113-4644-BA97-688212A633A5](https://user-images.githubusercontent.com/41404652/168712233-8aa00613-a3eb-470d-98f0-543e76d7c837.jpeg)
![C0AD3F60-A128-4755-BBA6-13383B43B1F4](https://user-images.githubusercontent.com/41404652/168712246-7333ed75-50d3-4a2e-a3ed-fa652a67c59a.png)
![BFF895D9-94FB-480E-9617-8A985982E077](https://user-images.githubusercontent.com/41404652/168712251-ae2fb01d-07f5-43f1-93b0-36ea4cc5ccfb.png)

**Comment by jxxghp** [comment]
暂时没环境测试，建议用emby

**Comment by leo8912** [comment]
同问，解决了吗？

**Comment by firstvip** [comment]
试了很多次，实在搞不定

**Comment by jxxghp** [comment]
优化过了，还有问题的再提吧
