### ISSUE TITLE
季的集编号不是从1开始的，识别缺失集有问题

### ISSUE THREAD

**Issue by yugoai** [jxxghp/nas-tools#1292]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 动漫 “海贼王” 年份1999， 最新第21季一共149集，集数编号是从892开始的，Nastools识别是从1-149集，PT站的编号也是从892开始，导致无法正常识别并下载。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的

## 你期望的结果

> 希望能按TMDB的集顺序正常识别

## 给出程序界面截图、后台运行日志或配置文件

> 
One Piece 1999 E1031 1080p WEB-DL H264 AAC-OurTV 海贼王/航海王 第1031集 日语中字 官方 中字 禁转
替换词：
One Piece 1999@One Piece 1999 S21

![1](https://user-images.githubusercontent.com/97602933/192427075-fe4e9247-f9d2-4d8c-8f17-40f2a0698eeb.jpg)
![2](https://user-images.githubusercontent.com/97602933/192427123-a2268e8b-8bd4-4d57-b8d5-17fe04ecd7b6.jpg)
![3](https://user-images.githubusercontent.com/97602933/192427139-2c8bc7e5-d59e-45ad-a626-4a6d17dd057f.jpg)
![4](https://user-images.githubusercontent.com/97602933/192427159-33a46f92-ced0-4be2-b244-5531e3643cb3.jpg)

**Comment by xyswordzoro** [comment]
![QQ截图20221016122804](https://user-images.githubusercontent.com/86150433/196018013-4d8f1ab7-83bc-4e8d-a34a-2964a06e0fac.png)
![QQ截图20221016122723](https://user-images.githubusercontent.com/86150433/196018016-d75212c0-ffb6-4264-90e3-1ab7e112015b.png)
![QQ截图20221016122812](https://user-images.githubusercontent.com/86150433/196018019-bf704872-0745-4d61-ae10-2488da4ea7ed.png)
我把总集数设置成2000了，可以下载，供参考

**Comment by yugoai** [comment]
你自定义替换词怎么写的呢？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月16日(星期天) 中午12:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jxxghp/nas-tools] 季的集编号不是从1开始的，识别缺失集有问题 (Issue #1292)





 

 
 
 我把总集数设置成2000了，可以下载，供参考

**Comment by cs0663c** [comment]
我也困扰很久,订阅不成功,
![image](https://user-images.githubusercontent.com/59052041/196441755-425bf895-d34c-464b-a20a-7edea77f2317.png)

**Comment by Caiyou1001** [comment]
> 我也困扰很久,订阅不成功, ![image](https://user-images.githubusercontent.com/59052041/196441755-425bf895-d34c-464b-a20a-7edea77f2317.png)

同样问题，请问怎么解决的哈

**Comment by jxxghp** [comment]
已支持用自定义识别词处理集偏移。
