### ISSUE TITLE
本地名称与TMDB上的名称差异优化建议

### ISSUE THREAD

**Issue by ilolita945** [jxxghp/nas-tools#1304]
>
> NASTool 版本: 2.1.1
>
> 环境: Windows
>

## 你遇到什么问题了？

> 本地番剧文件夹名称：龙珠超：龙珠英雄 (2018)
> 本地tvshow.nfo标题名称：龙珠超：龙珠英雄 (2018)
> TMDB名称：超级龙珠英雄 (2018)
> 当出现这种本地文件夹和tvshow.nfo标题与TMDB标题名称不一致时，即便使用了替换词（龙珠超：龙珠英雄@超级龙珠英雄）也无法正确读取本地现有集数（名称识别显示没问题）。

> [](url)
> 本地的文件夹名称（tvshow.nfo标题也是《龙珠超：龙珠英雄》） 本地集数为4集
![1](https://user-images.githubusercontent.com/49525838/192490111-1d43d667-60ac-46ef-97f5-1059a73cd409.jpg)

> 使用了替换词
![2](https://user-images.githubusercontent.com/49525838/192490106-e42aa013-9d14-4766-b2fc-64f17561a8d7.jpg)

> 名称识别测试
![3](https://user-images.githubusercontent.com/49525838/192490118-856a147a-f7f6-456b-9c32-3cfe840021e9.jpg)

> 清理过RSS和TMDB缓存，也取消了订阅，并重新订阅刷新还是无法读出正确的本地集数
![4](https://user-images.githubusercontent.com/49525838/192490087-c9a75436-b53d-4872-8f45-4002681e2405.jpg)

## 你期望的结果

> 建议使用TMDBID进行匹配，这样无论本地文件夹或者tvshow.nfo标题改成什么样都不会受到影响

**Comment by jxxghp** [comment]
判本地不是查的文件系统，是调的媒体服务器api，判tmdbid的话emby、jellyfin应该可以作为补充。plex估计就不行了，目前拿到的数据没有tmdbid。

**Comment by ilolita945** [comment]
期待您的优化

**Comment by ilolita945** [comment]
> 

期待对emby这方面的优化
