### ISSUE TITLE
错误:识别失败，无法从文件名中识别出集数

### ISSUE THREAD

**Issue by fireice1988** [jxxghp/nas-tools#131]
更新到9.0.7版本后不能识别动漫的文件，错误:识别失败，无法从文件名中识别出集数
![cec26be8544da771428b4ae5c4cf993](https://user-images.githubusercontent.com/36370085/169061108-a925029a-5a46-4f15-b08d-7765c4a144f7.jpg)

**Comment by jxxghp** [comment]
你这个确实没有集数啊，命名严重不规范。
