### ISSUE TITLE
学校的数据统计没出现

### ISSUE THREAD

**Issue by hmy1210** [jxxghp/nas-tools#1311]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>2.1.1
> 环境: docker or windows or Synology
>unraid下的docker容器

## 你遇到什么问题了？
btschool 配置好全部，能搜索到种子，但是数据统计不出现，种子搜索是正常的。
![image](https://user-images.githubusercontent.com/30746089/192693802-e381ccc6-8278-4805-97db-85fe25cce12e.png)

![image](https://user-images.githubusercontent.com/30746089/192694037-fee174e1-fa92-4281-abe3-17304e88b456.png)

> 描述一下你遇到的问题
![image](https://user-images.githubusercontent.com/30746089/192693420-66918398-735e-47cb-a3d0-1fe372e05ce7.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是的
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
加上统计

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by xiangyaoyao** [comment]
可能是因为学校的盾，导致了数据不能刷新。jxxphp大佬可以参考一下ptpp，这个软件可以刷新。有的站点大概1-2s就可以刷新数据，学校可能需要5-6s才能刷新，但是nt这个软件可能是全部都是默认1-2s刷新，就导致了学校刷不了数据

**Comment by jxxghp** [comment]
ptpp本身就是基于浏览器的，运行环境都不一样无法参考啊。
打开浏览器进入站点，过盾后，重新抓取Cookie和UA（一定要同时抓这个），维护到站点里，在网络正常的情况下一般是可以过盾的，因为cookie里会保存过盾的信息，比如馒头等都可以通过这个方式绕过。

**Comment by JKnuts** [comment]
> ptpp本身就是基于浏览器的，运行环境都不一样无法参考啊。 打开浏览器进入站点，过盾后，重新抓取Cookie和UA（一定要同时抓这个），维护到站点里，在网络正常的情况下一般是可以过盾的，因为cookie里会保存过盾的信息，比如馒头等都可以通过这个方式绕过。

解决了，我这数据统计有ptschool了

**Comment by tevenfeng** [comment]
> > ptpp本身就是基于浏览器的，运行环境都不一样无法参考啊。 打开浏览器进入站点，过盾后，重新抓取Cookie和UA（一定要同时抓这个），维护到站点里，在网络正常的情况下一般是可以过盾的，因为cookie里会保存过盾的信息，比如馒头等都可以通过这个方式绕过。
> 
> 解决了，我这数据统计有ptschool了

你是咋解决的呀，我这边cookie和ua都贴了发现还不得行

**Comment by JKnuts** [comment]
> > > ptpp本身就是基于浏览器的，运行环境都不一样无法参考啊。 打开浏览器进入站点，过盾后，重新抓取Cookie和UA（一定要同时抓这个），维护到站点里，在网络正常的情况下一般是可以过盾的，因为cookie里会保存过盾的信息，比如馒头等都可以通过这个方式绕过。
> 
> > 
> 
> > 解决了，我这数据统计有ptschool了
> 
> 
> 
> 你是咋解决的呀，我这边cookie和ua都贴了发现还不得行

就是按大佬说的，过盾之后贴cookie和ua，不过我ua是贴在基本设置里，相当于全局设置，所有站都走新的ua

**Comment by hmy1210** [comment]
> > > > ptpp本身就是基于浏览器的，运行环境都不一样无法参考啊。 打开浏览器进入站点，过盾后，重新抓取Cookie和UA（一定要同时抓这个），维护到站点里，在网络正常的情况下一般是可以过盾的，因为cookie里会保存过盾的信息，比如馒头等都可以通过这个方式绕过。
> > 
> > 
> > > 
> > 
> > 
> > > 解决了，我这数据统计有ptschool了
> > 
> > 
> > 你是咋解决的呀，我这边cookie和ua都贴了发现还不得行
> 
> 就是按大佬说的，过盾之后贴cookie和ua，不过我ua是贴在基本设置里，相当于全局设置，所有站都走新的ua

成功了~感谢 秒刷出来

**Comment by hmy1210** [comment]
> ptpp本身就是基于浏览器的，运行环境都不一样无法参考啊。 打开浏览器进入站点，过盾后，重新抓取Cookie和UA（一定要同时抓这个），维护到站点里，在网络正常的情况下一般是可以过盾的，因为cookie里会保存过盾的信息，比如馒头等都可以通过这个方式绕过。

感谢感谢~

**Comment by HAN915** [comment]
> > > ptpp本身就是基于浏览器的，运行环境都不一样无法参考啊。 打开浏览器进入站点，过盾后，重新抓取Cookie和UA（一定要同时抓这个），维护到站点里，在网络正常的情况下一般是可以过盾的，因为cookie里会保存过盾的信息，比如馒头等都可以通过这个方式绕过。
> > 
> > 
> > 解决了，我这数据统计有ptschool了
> 
> 你是咋解决的呀，我这边cookie和ua都贴了发现还不得行

大佬，过盾是什么意思？需要怎么操作吗？
