### ISSUE TITLE
关于Plex建议

### ISSUE THREAD

**Issue by nicholastz** [jxxghp/nas-tools#1312]
功能1：使X-Plex-Token长期有效
描述：目前NASTOOLS最新版采用的是X-Plex-Token方式登录Plex，总体来说解决了plex经常出现一些奇奇怪怪的问题，但由于X-Plex-Token有一定的时效性，参考了官方网站提出如何使token长期有效的方式
参考：https://forums.plex.tv/t/authenticating-with-plex/609370

功能2：仅针对更新的媒体库进行扫描
描述：每当有新媒体添加，Plex会把整个媒体库全部扫描一遍。
参考：暂无

**Comment by nxuu** [comment]
plex 可以自己设置 只扫描局部 不要全局扫描。

**Comment by jxxghp** [comment]
有点复杂，暂时不考虑，欢迎PR
