### ISSUE TITLE
站点管理的数据统计页面打不开

### ISSUE THREAD

**Issue by zhushu11** [jxxghp/nas-tools#1314]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>2.1.1
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> 描述一下你遇到的问题
更新套件版本的2.1.1后，站点管理的数据统计页面打不开，需要签到的网站也没有自动签到
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
未找到答案

## 你期望的结果

> 描述以下你期望的结果
解决BUG
## 给出程序界面截图、后台运行日志或配置文件
![屏幕截图 2022-09-28 161052](https://user-images.githubusercontent.com/114567896/192726669-48a7cacc-1a29-4b4d-a39b-08842644dc0b.jpg)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/192753763-3a67f75a-75c5-490f-9033-2cf3595de17b.png)
#### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助
