### ISSUE TITLE
下载部分非PT站内容后，由于命名非标准化命名，比如名字前有BT站的网址。导致识别失败。

### ISSUE THREAD

**Issue by feixu0530** [jxxghp/nas-tools#132]
下载部分非PT站内容后，由于命名非标准化命名，比如名字前有BT站的网址。导致识别失败。
在没有使用nas-tools之前，我是写了一段脚本，每5分钟轮询一次，检查下载文件夹内是否有包含所下网址的视频名称，有的话直接用命令行重命名去除网址。这样通过Jellyfin就能自动刮削信息。

**Comment by jxxghp** [comment]
这前类情况太多了，没办法都兼容，选规范点的站点吧

**Comment by feixu0530** [comment]
能否加一个识别前执行一个可执行脚本的功能。当然这个可执行脚本就我自己写了。
