### ISSUE TITLE
自定义识别词bug

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#1323]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.1 43309260
>
> 环境: docker 
>

## 你遇到什么问题了？

替换词（S21后面有个空格）    One Piece 1999 (?=E(103[0-9]|1040))@One Piece 1999 S21 
识别名称                                   One Piece 1999 E1034 1080p WEB-DL H264 AAC-PTerWEB
目的                                           海贼王到1040属于第21季

保存替换词截图
![image](https://user-images.githubusercontent.com/54088512/192923875-2d663d89-5469-4282-8949-bdc1a464793d.png)

识别截图，一直识别中，应该已经失败了，没日志
![image](https://user-images.githubusercontent.com/54088512/192923164-4a0509f3-e7f8-4e5c-8994-eaee043b44b7.png)

再回去看自定义设置，原来的|没了，自动换行了。
![image](https://user-images.githubusercontent.com/54088512/192923845-f6ef4097-ac1c-4580-82a7-e0e06d5e627f.png)

**Comment by thsrite** [comment]
![image](https://user-images.githubusercontent.com/54088512/192924277-ce2585d6-589b-42e3-bae3-17bd66dc7bf2.png)
拆成多条是没问题的。

![image](https://user-images.githubusercontent.com/54088512/192924354-e21e32b5-707c-4b22-813b-353fe20575f0.png)

**Comment by Shurelol** [comment]
更新，重新设置下替换词，该问题已修复

**Comment by thsrite** [comment]
效率

> 更新，重新设置下替换词，该问题已修复

效率 感谢
