### ISSUE TITLE
群辉套件关闭后无法启动

### ISSUE THREAD

**Issue by jikuohong** [jxxghp/nas-tools#1326]
## 你使用的 NASTool 是什么版本，什么环境？
群辉套件矿神源2.1.1

套件停用后再次启动，无法登陆webui。
套件显示已启动，但是资源监控里的任务管理器没有发现该进程。然后SSH进去用TOP命令也没有发现该进程。
tg上有DOCKER版的处置办法，套件版应该怎么处理？（重新安装再配置很麻烦。）

**Comment by jikuohong** [comment]
![1664429347351](https://user-images.githubusercontent.com/34758287/192947856-4caf19b4-4936-4aad-8d37-e78665ab1b8e.jpg)

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/192969416-e421739d-81a4-4223-b76c-642c4577ecf7.png)
