### ISSUE TITLE
媒体库同步不全

### ISSUE THREAD

**Issue by x25648** [jxxghp/nas-tools#1334]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>2.1.2
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 描述一下你遇到的问题
我的媒体库里电视剧只有3部，而我的nas里有8部，电影数量多的
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
无法解决
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![IMG_20220929_201742](https://user-images.githubusercontent.com/49601820/193029348-c2777b9b-883e-4566-8dfa-5892239c4550.jpg)
![IMG_20220929_201742](https://user-images.githubusercontent.com/49601820/193029413-2b6d0d09-f7c3-42d8-9466-c401edde72a2.jpg)

![16644541596338460279908362495483](https://user-images.githubusercontent.com/49601820/193030237-b0293584-ae86-4d9b-b2a9-763ef7d33a25.jpg)
![16644542165705156345898069161267](https://user-images.githubusercontent.com/49601820/193030775-d02288bf-22ca-4470-b5b4-97d533a5b5f8.jpg)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Shurelol** [comment]
脖子无法转弯，无法分析

**Comment by x25648** [comment]
![16644571198355206426906611500228](https://user-images.githubusercontent.com/49601820/193040728-385d81ca-8467-4c1c-b116-065842883d9e.jpg)
![Uploading 16644572227131189502096824108919.jpg…]()

**Comment by x25648** [comment]
![Uploading 1664457433320117643211459118780.jpg…]()

**Comment by x25648** [comment]
![Uploading 16644574892164489573958030096488.jpg…]()

**Comment by x25648** [comment]
- [

**Comment by x25648** [comment]
![CDC60E22-D09D-4946-997E-D3A1C97580B8](https://user-images.githubusercontent.com/49601820/193043018-ef2bc563-8e2b-44cd-b3de-64ccfaf60f35.png)

**Comment by x25648** [comment]
![5D711B2B-8B98-4101-8DF0-949DDDE5A8A4](https://user-images.githubusercontent.com/49601820/193043462-778e1c40-b41c-4e51-9c3f-21f13c3a1708.png)

**Comment by Shurelol** [comment]
参考 #1271
