### ISSUE TITLE
NASTOOL刷流任务进入QB之后，QB始终处于等待，不会下载，手动从PT站添加QB则正常

### ISSUE THREAD

**Issue by wang923345843** [jxxghp/nas-tools#1336]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.1
>
> 环境: docker or windows or Synology
>群晖套件

## 你遇到什么问题了？

>NASTOOL刷流任务进入QB之后，QB始终处于等待，不会下载，手动从PT站添加QB则正常
QB显示
![图片](https://user-images.githubusercontent.com/100781270/193075315-4ff2cdbd-57cc-4664-bb19-796e1cb57655.png)
![图片](https://user-images.githubusercontent.com/100781270/193075357-2a02cb57-2ace-47dd-a715-bc4dba768ae5.png)
![Uploading 图片.png…]()

qb版本为docker，4.4.3.1

**Comment by wang923345843** [comment]
![图片](https://user-images.githubusercontent.com/100781270/193077109-fcaddfca-cfb5-43ca-8a92-d4c0df2e3a1d.png)

**Comment by link2fun** [comment]
> ![图片](https://user-images.githubusercontent.com/100781270/193077109-fcaddfca-cfb5-43ca-8a92-d4c0df2e3a1d.png)

连不上站点 所以无法开始
