### ISSUE TITLE
添加下载后，近期下载间隙性没有记录

### ISSUE THREAD

**Issue by hijakke** [jxxghp/nas-tools#1339]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.2 2f3757dd
> 环境: docker
>qb版本：4.4.5

## 你遇到什么问题了？

> 添加下载后，近期下载间隙性没有记录，刚开始使用时没有记录，中间有一短时间有记录，有可能是版本升级过程中部分版本和qb4.4.5的兼容性问题。 目前升级到最新的版本仍然没有记录。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

>  未解决

## 你期望的结果

> 反馈问题

## 给出程序界面截图、后台运行日志或配置文件

![微信图片_20220930125009](https://user-images.githubusercontent.com/3991171/193192786-50c8ba55-18a0-4434-b0e3-2d84f040b28f.jpg)
![微信图片_20220930125012](https://user-images.githubusercontent.com/3991171/193192789-d2dc04cc-7bad-4acd-9ec3-aef6b6c98306.jpg)

**Comment by jxxghp** [comment]
近期下载个qb没关系的，无法重现这个问题

**Comment by hijakke** [comment]
应该是关闭了推送开关中的新增下载导致的

SqlHelper.insert_download_history是在send_download_message方法中调用的，但是这两个功能逻辑上应该是独立的，不应该相互影响，可以考虑优化下。

**Comment by hijakke** [comment]
> 近期下载个qb没关系的，无法重现这个问题

应该是关闭了推送开关中的新增下载导致的

SqlHelper.insert_download_history是在send_download_message方法中调用的，但是这两个功能逻辑上应该是独立的，不应该相互影响，可以考虑优化下。
