### ISSUE TITLE
希望增加在webui中删除影视之后能够联动删除源文件以及硬链接文件

### ISSUE THREAD

**Issue by ihujin** [jxxghp/nas-tools#1342]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.1.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望增加在webui中删除影视之后能够联动删除源文件以及硬链接文件（影视文件较多的时候硬链接整理好的能够很快速的找到对应的影视，但是在源文件目录中就很难查找到对应的影视文件）

## 这个功能有什么可以参考的资料吗？

> 主要就是在WEBUI中能够在对应的下载记录中进行管理nas中的源文件以及硬链接文件（当影视文件有几千个的时候源文件基本是很难查找的到）

**Comment by Shurelol** [comment]
#### 硬链接的特点就是源文件和链接文件的独立性

#### 点杯橙汁喝，不想要有橙子味，合适么？

#### 想要源文件和链接文件一起没，建议用软链接

**Comment by ihujin** [comment]
文件多了之后不能很方便的找到源文件，但是由于硬链接是已经处理过的（白话文名称）所以能很快速的找到，这就导致源文件的整理就会很混乱甚至找不到

**Comment by Shurelol** [comment]
源文件通过下载器删除，链接文件通过媒体服务器删除

**Comment by ihujin** [comment]
好的，谢谢
