### ISSUE TITLE
资源搜索下载时，1337x站点资源自动下载报错

### ISSUE THREAD

**Issue by sunpjx** [jxxghp/nas-tools#1345]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.2
>
> 环境: docker
>

## 你遇到什么问题了？

> 搜索资源（自动搜索或主动搜索）1337x站点的资源全部下载报错（aria2下载器）提示“匹诺曹 (2022) 添加下载失败 cannot marshal <class 'lxml.etree._ElementUnicodeResult'> objects！”。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 实时日志：16:39:02 WARN - 【DOWNLOADER】公开站点，尝试自动获取Cookie ...
16:39:09 INFO - 【DOWNLOADER】添加下载任务：Pinocchio.2022.1080p.WEB.h264-KOGi magnet:?xt=urn:btih:8E3062CF648FCE31B4C8D6E81CD5D888E304E234&dn=Pinocchio.2022.1080p.WEB.h264-KOGi&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2880%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2750%2Fannounce&tr=udp%3A%2F%2Ftracker.thinelephant.org%3A12800%2Fannounce&tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14790%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce
16:39:09 ERROR - 【DOWNLOADER】添加下载任务出错：cannot marshal <class 'lxml.etree._ElementUnicodeResult'> objects
16:46:51 WARN - 【DOWNLOADER】公开站点，尝试自动获取Cookie ...
16:46:55 INFO - 【DOWNLOADER】添加下载任务：Pinocchio.2022.720p.DSNP.WEBRip.800MB.x264-GalaxyRG magnet:?xt=urn:btih:0E9C1938C417B0387DACDC43385571474D8A320D&dn=Pinocchio.2022.720p.DSNP.WEBRip.800MB.x264-GalaxyRG&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.birkenwald.de%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce&tr=udp%3A%2F%2Fopentor.org%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2970%2Fannounce&tr=https%3A%2F%2Ftracker.foreverpirates.co%3A443%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce
16:46:55 ERROR - 【DOWNLOADER】添加下载任务出错：cannot marshal <class 'lxml.etree._ElementUnicodeResult'> objects

**Comment by jxxghp** [comment]
试了下是正常的，无法重现问题，你这个看起来是下载软件报的错。
