### ISSUE TITLE
opensubtitle字幕下载一直一个都么有成功

### ISSUE THREAD

**Issue by sunpjx** [jxxghp/nas-tools#1346]
每次自动刮削完成后会进行字幕下载提醒，只会有这么一条SUBTITLE日志，然后没有下文了，也没有报错也没有成功提示。

**Comment by Lolicon-A** [comment]
俺也一样~

**Comment by jxxghp** [comment]
容器能访问opensubtitles网站吗

**Comment by Lolicon-A** [comment]
> 容器能访问opensubtitles网站吗

我挂了http代理了，可以访问

**Comment by sunpjx** [comment]
> 容器能访问opensubtitles网站吗

可以，我的jellyfin安装opensubtitles插件可以正常下载，jellyfin使用的opensubtitles.com的api。nastools使用的是open subtitles.org的账号密码。容器是可以访问这个地址的。

**Comment by sunpjx** [comment]
> > 容器能访问opensubtitles网站吗
> 
> 我挂了http代理了，可以访问

求教怎么设置

**Comment by Knownniu001** [comment]
> 每次自动刮削完成后会进行字幕下载提醒，只会有这么一条SUBTITLE日志，然后没有下文了，也没有报错也没有成功提示。

我也是这个情况

**Comment by Lolicon-A** [comment]
> > > 容器能访问opensubtitles网站吗
> > 
> > 
> > 我挂了http代理了，可以访问
> 
> 求教怎么设置

在设置-》基础设置-》代理服务器，里面有代理设置

**Comment by Daxigua001** [comment]
相同问题
