### ISSUE TITLE
搜索展示页面馒头部分种子名字显示不全..看不到制作组

### ISSUE THREAD

**Issue by ati121** [jxxghp/nas-tools#1347]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.12
>
> 环境: docker

## 你遇到什么问题了？

> 在搜索过程中偶然发现馒头的部分种子显示不全,就看不到制作组不好选择版本:),同样的种子文件名在其他站显示正常..
举列:
同样的种子,馒头显示不全,观众显示正常
![MT](https://user-images.githubusercontent.com/72114654/193265928-a56f4436-c89f-410b-8ad1-9f7187be6148.jpg)
![观众](https://user-images.githubusercontent.com/72114654/193265981-f35769f6-3f63-4d83-8c7e-993047eb718c.jpg)

![其他](https://user-images.githubusercontent.com/72114654/193266563-ff0bb325-a657-4875-ae9e-0b4b6c859fe0.jpg)

**Comment by jxxghp** [comment]
最新代码修复了
