### ISSUE TITLE
某些pt网站cookie隔很短时间就会发生变化，导致无法正常下载

### ISSUE THREAD

**Issue by YoshiPark** [jxxghp/nas-tools#1350]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.1
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？
馒头cookie频繁变化，导致无法正常下载，是否是已开启二步验证的原因

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

>是

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
要么放弃这个站，要么放弃这个工具

**Comment by YoshiPark** [comment]
首先对软件作者衷心献上感谢，辛苦软件作者了，现在采取方法就是，先在相同环境上登上该pt网站，然后将cookie复制过去，只要保证软件和pt网站用相同网络环境登录，并且之后不要用其他ip地址登录，cookie就不会变，不是软件的问题，再次感谢软件作者！
