### ISSUE TITLE
内建搜索可以增加网站request超时多少次或多少时间自动跳过吗

### ISSUE THREAD

**Issue by c939984606** [jxxghp/nas-tools#1356]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>v2.1.2
> 环境: docker or windows or Synology
>docker 

## 你遇到什么问题了？

> 内建搜索可以增加网站request超时多少次或多少时间自动跳过吗，比如我的私有站点有26个，每次搜索的时候偶尔有些就打不开，然后搜索就一直卡在那里不显示结果了，

**Comment by jxxghp** [comment]
现在是20秒
