### ISSUE TITLE
所有媒体信息无法识别

### ISSUE THREAD

**Issue by ltsj** [jxxghp/nas-tools#1357]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>latest
> 环境: docker or windows or Synology
>docker 

## 你遇到什么问题了？

无法识别媒体信息 (所有的都没办法识别了 不是命名问题 

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

是

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/30733960/193408583-ac715864-e66d-462f-b278-25f9f0d8df0f.png)
![image](https://user-images.githubusercontent.com/30733960/193408715-f9483c27-5643-4a06-8d94-cd7ee892faca.png)
tmdb api key 没问题 网络也正常...

**Comment by Shurelol** [comment]
### 设置-基础设置-实验室-自定义识别吃，打开保存下。

#### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助

**Comment by ltsj** [comment]
> ### 设置-基础设置-实验室-自定义识别吃，打开保存下。
> #### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助

是所有的都没办法识别 不单单是这一个 而且"名称识别测试"无法使用 "正在下载"点不进去

**Comment by Shurelol** [comment]
试试再说

**Comment by Shurelol** [comment]
发下自定义识别词的设置截图

**Comment by ltsj** [comment]
发现原因了  新版本好像是支持了转义字符 \  我之前填的是]  现在要\]  才行 不然就会出现我那个情况

**Comment by Shurelol** [comment]
现在支持正则表达式，特殊字符要转义
