### ISSUE TITLE
文件转移后，ChineseSubFinder报错

### ISSUE THREAD

**Issue by rockhia** [jxxghp/nas-tools#136]
ChineseSubFinder已经部署成功。
下载并转移文件后，ChineseSubFinder出现报错信息physical video file not found
<img width="586" alt="mmexport1652953525016" src="https://user-images.githubusercontent.com/90016652/169264740-a141d6c1-2fc9-436f-be8f-9470f9a4637a.png">
<img width="358" alt="mmexport1652953528077" src="https://user-images.githubusercontent.com/90016652/169264748-8a215989-4cee-4f5b-869f-9a4dd9190518.png">

**Comment by rockhia** [comment]
ChineseSubFinder监控的是作硬链接后的文件夹。

**Comment by jxxghp** [comment]
目录在两个容器里是一样的路径吗？发下两个容器的映射图

**Comment by rockhia** [comment]
映射没问题，CAHINESESUB库里面的影片和硬链接后的文件夹一致
![Screenshot_20220519_202840](https://user-images.githubusercontent.com/90016652/169293494-e20b69e3-5230-4e6c-92af-42331b5d4495.jpg)
![Screenshot_20220519_202817](https://user-images.githubusercontent.com/90016652/169293503-e27fe478-c2ae-44be-8445-db6446d3068b.jpg)

**Comment by rockhia** [comment]
映射的最终文件夹地址一致，都和emby进行了关联

**Comment by shanyan-wcx** [comment]
+1

**Comment by ershouqingge** [comment]
兄弟 我的问题和你的差不多，你说的那个容器内的映射必须要和nas-tool一致，才可以。

我的视频文件实际源目录在/volume2/video
NASTOOL中设置源目录在/volume2/video，硬链接目的目录在/volume2/video/link
docker版中国esesubfinder将/volume2/video/link装载到/media，chinesesubfinder中设置视频目录为/media

那么docker里面也要NASTOOL中设置的一样，源目录在/volume2/video，硬链接装载到/volume2/video/link吗？

**Comment by ershouqingge** [comment]
> 兄弟 我的问题和你的差不多，你说的那个容器内的映射必须要和nas-tool一致，才可以。
> 
> 我的视频文件实际源目录在/volume2/video NASTOOL中设置源目录在/volume2/video，硬链接目的目录在/volume2/video/link docker版中国esesubfinder将/volume2/video/link装载到/media，chinesesubfinder中设置视频目录为/media
> 
> 那么docker里面也要NASTOOL中设置的一样，源目录在/volume2/video，硬链接装载到/volume2/video/link吗？

但是它要求只能装载到/media下哦

**Comment by needquit** [comment]
把硬链接后的文件夹映射给chinesesubfinder，比如video/link，然后nastool的同步目录就是video->video/link，再去nastool里把二级目录分类给注释掉就能用。我就说这么操作的
