### ISSUE TITLE
自动分类出错

### ISSUE THREAD

**Issue by EliteOtaku** [jxxghp/nas-tools#1362]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.2 cdbe7c05
>
> 环境: docker
>

## 你遇到什么问题了？

> 自动分类出错，似乎硬链接也不工作了。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是之前没见过的错误代码，确实无法理解，看起来是代码出错了？希望老大国庆愉快。不着急回复。

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
12:37:37 INFO - 【RMT】开始处理：/media/media/The.Lord.of.the.Rings.The.Rings.of.Power.S01E06.720p.AMZN.WEBRip.DDP5.1.x264-SMURF[rartv]，转移方式：硬链接
12:37:37 ERROR - 【RMT】发生错误：bad character range h-R at position 109 - Traceback (most recent call last): File "/nas-tools/app/media/media.py", line 705, in get_media_info_on_files meta_info = MetaInfo(title=file_name) File "/nas-tools/app/media/meta/metainfo.py", line 27, in MetaInfo ignored_words = re.compile(r'' + ignored_words) File "/usr/lib/python3.10/re.py", line 251, in compile return _compile(pattern, flags) File "/usr/lib/python3.10/re.py", line 303, in _compile p = sre_compile.compile(pattern, flags) File "/usr/lib/python3.10/sre_compile.py", line 788, in compile p = sre_parse.parse(p, flags) File "/usr/lib/python3.10/sre_parse.py", line 955, in parse p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0) File "/usr/lib/python3.10/sre_parse.py", line 444, in _parse_sub itemsappend(_parse(source, state, verbose, nested + 1, File "/usr/lib/python3.10/sre_parse.py", line 599, in _parse raise source.error(msg, len(this) + 1 + len(that)) re.error: bad character range h-R at position 109
12:37:37 ERROR - 【RMT】检索媒体信息出错！
12:37:37 ERROR - 【SYNC】/media/media 处理失败：检索媒体信息出错
12:37:37 INFO - 【RMT】开始处理：/media/media/[NC-Raws] Ginga Eiyuu Densetsu: Die Neue These - Sakubou - 37 (CR 1920x1080 AVC AAC MKV) [03A43A97].mkv，转移方式：硬链接
12:37:37 ERROR - 【RMT】发生错误：bad character range h-R at position 109 - Traceback (most recent call last): File "/nas-tools/app/media/media.py", line 705, in get_media_info_on_files meta_info = MetaInfo(title=file_name) File "/nas-tools/app/media/meta/metainfo.py", line 27, in MetaInfo ignored_words = re.compile(r'' + ignored_words) File "/usr/lib/python3.10/re.py", line 251, in compile return _compile(pattern, flags) File "/usr/lib/python3.10/re.py", line 303, in _compile p = sre_compile.compile(pattern, flags) File "/usr/lib/python3.10/sre_compile.py", line 788, in compile p = sre_parse.parse(p, flags) File "/usr/lib/python3.10/sre_parse.py", line 955, in parse p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0) File "/usr/lib/python3.10/sre_parse.py", line 444, in _parse_sub itemsappend(_parse(source, state, verbose, nested + 1, File "/usr/lib/python3.10/sre_parse.py", line 599, in _parse raise source.error(msg, len(this) + 1 + len(that)) re.error: bad character range h-R at position 109

**Comment by Shurelol** [comment]
### 设置-基础设置-实验室-自定义识别吃，打开保存下。

#### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助

**Comment by EliteOtaku** [comment]
> 

![image](https://user-images.githubusercontent.com/29235152/193440595-aecfda73-b2c3-48fb-8a00-3b1efe66bb96.png)
请问是这里点击保存吗？我刚刚试过了，还是会出错。

**Comment by Shurelol** [comment]
#### 你这个问题去看小秘书，现在识别词支持正则表达式，特殊字符要转意

#### 小秘书目录里找 tips-自定义识别词支持正则表达式

**Comment by EliteOtaku** [comment]
> 

搞定了，删除之前的设置后，重新弄了一遍，搞定了
