### ISSUE TITLE
关于下载的视频无法正常播放的问题

### ISSUE THREAD

**Issue by yzxh24** [jxxghp/nas-tools#1367]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.2 9a012ddb
>
> 环境: OpenMediaVault 5 docker
>

## 你遇到什么问题了？

> 下载下来的视频无法播放，提示 流错误

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

已经根据 wiki 给宿主机添加了以下设置
> echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
> echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
> sudo sysctl -p

## 你期望的结果

> 视频能够正常播放

## 给出程序界面截图、后台运行日志或配置文件

<img width="708" alt="image" src="https://user-images.githubusercontent.com/5319741/193482322-510f7ca8-b175-4c71-b57f-4b077307aef0.png">

我选择的文件转移方式是【复制】，通过上面的日志可以看到 19:00:11 时添加了下载任务，到 19:00:40 时就开始了文件复制，但是这时候文件并没有真正下载下来，复制过去的视频文件肯定是播放不了的。

我也将文件转移方式设置为【移动】和【硬链接】进行过测试，结果都是下载任务一添加完就马上操作文件，这些下载完的视频文件都没法播放，需要我先把相应到视频文件删除，然后在后台点击【服务】->【清理转移缓存】，再点击【服务】->【目录同步】，这时候移动过去的视频文件才能正常播放。

请问一下这是软件本身的机制还是有什么其他设置我错过了？

**Comment by xiangyaoyao** [comment]
可以在qb下载软件中为没有下载完的文件添加一个！qb的后缀，这样只有等下载完成后才会触发目录同步

**Comment by yzxh24** [comment]
> 可以在qb下载软件中为没有下载完的文件添加一个！qb的后缀，这样只有等下载完成后才会触发目录同步

这样的话不是每次下载一个电影都要修改一次，而且有一些下载是通过订阅进行的，这种没办法修改。

其实我不明白的是为什么 下载任务 添加成功后马上就开始 复制/移动 文件，正常流程应该是等文件下载完成以后才触发 复制/移动 服务才对吧？

**Comment by Shurelol** [comment]
#### [xiangyaoyao](https://github.com/xiangyaoyao) 提到的是这个问题最好的解决办法
![image](https://user-images.githubusercontent.com/16237201/193514510-941d40a5-848d-48ca-a6e6-ab61ba02b18c.png)
#### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助

**Comment by yzxh24** [comment]
> #### [xiangyaoyao](https://github.com/xiangyaoyao) 提到的是这个问题最好的解决办法
> ![image](https://user-images.githubusercontent.com/16237201/193514510-941d40a5-848d-48ca-a6e6-ab61ba02b18c.png)
> 
> #### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助

感谢，原来可以自动添加，我之前一直用aria2做下载器。

**Comment by yzxh24** [comment]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/5319741/193558470-ee7e66d1-6c9d-4dfd-a164-0fbc63a7e99c.png">
将下载器换成 qbittorrent 并按上图设置后问题解决。
