### ISSUE TITLE
订阅绑定下载路径和媒体库路径

### ISSUE THREAD

**Issue by lingyizhuzhu** [jxxghp/nas-tools#1369]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.1.2
>
> 环境: 群晖

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
订阅里面可以直接分类为电视剧或者动漫等，然后和下载路径绑定，对应下载路径和媒体库路径绑定，识别转移之后只会到和下载路径绑定的媒体库路径。
（如下载路径“动漫”里面的东西识别之后只会往媒体库“动漫”里面转移，目前就是斗破苍穹2022这个废词条和苍兰诀这个还在更新的剧会下载在动漫，识别转移到电视剧里面了。）
## 这个功能有什么可以参考的资料吗？
暂无
> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by lingyizhuzhu** [comment]
指定路径之后识别类型错了也没关系，这种情况很少，至少能保证他被转移到了我期望的路径。

**Comment by Shurelol** [comment]
#### 苍兰诀 电视剧和动漫在tmdb上的词条，名称，英文名称，年份均一致。无法从文件名识别时电视剧还是动漫。建议手动识别，输入tmdbid

#### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助

**Comment by lingyizhuzhu** [comment]
好的，谢谢
