### ISSUE TITLE
开始下载后日志立刻显示为下载完成并删除订阅

### ISSUE THREAD

**Issue by shanyan-wcx** [jxxghp/nas-tools#137]
![image](https://user-images.githubusercontent.com/58252651/169294807-3a2e3681-a492-40e7-8a56-5cef2ffed235.png)
这是特意设计成这样的还是bug？而且没必要把订阅删掉吧，以后找到更高质量的文件自动覆盖不是更好？

**Comment by jxxghp** [comment]
电影订阅完当然删了。
那是你的想法。
