### ISSUE TITLE
rss 站点资源为空

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#1385]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker or windows or Synology
>docker

> 描述一下你遇到的问题

站点管理-站点维护中，站点添加了rss链接，部分站点站点资源处为空
为空的站点为：pterclub （ 猫站 ）ourbits（我堡）
其中在资源搜索处 无法搜到猫站的资源 我堡的可以在资源搜索处搜到

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
没有相关问题

> 描述以下你期望的结果
可以使用我堡和猫站

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

<img width="867" alt="截屏2022-10-04 16 03 38" src="https://user-images.githubusercontent.com/39802246/193766951-f90d5965-72f2-4c6a-96cb-f14120e960e7.png">

**Comment by Tartarus2014** [comment]
> ## 你使用的 NASTool 是什么版本，什么环境？
> > NASTool 版本: vx.x.x
> > 环境: docker or windows or Synology
> > docker
> 
> > 描述一下你遇到的问题
> 
> 站点管理-站点维护中，站点添加了rss链接，部分站点站点资源处为空 为空的站点为：pterclub （ 猫站 ）ourbits（我堡） 其中在资源搜索处 无法搜到猫站的资源 我堡的可以在资源搜索处搜到
> 
> > 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
> > 没有相关问题
> 
> > 描述以下你期望的结果
> > 可以使用我堡和猫站
> 
> > 如UI BUG请提供截图及配置文件截图
> > 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
> 
> <img alt="截屏2022-10-04 16 03 38" width="867" src="https://user-images.githubusercontent.com/39802246/193766951-f90d5965-72f2-4c6a-96cb-f14120e960e7.png">



> ## 你使用的 NASTool 是什么版本，什么环境？
> > NASTool 版本: vx.x.x
> > 环境: docker or windows or Synology
> > docker
> 
> > 描述一下你遇到的问题
> 
> 站点管理-站点维护中，站点添加了rss链接，部分站点站点资源处为空 为空的站点为：pterclub （ 猫站 ） 
其中在资源搜索处 无法搜到猫站的资源 
> 
> > 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
> > 没有相关问题
> 
> > 描述以下你期望的结果
> > 可以使用我堡和猫站
> 
> > 如UI BUG请提供截图及配置文件截图
> > 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
>

**Comment by jxxghp** [comment]
dev已修复
