### ISSUE TITLE
刷流任务过滤条件问题

### ISSUE THREAD

**Issue by yunjie-li** [jxxghp/nas-tools#1387]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.3
>
> 环境: docker
>

## 你遇到什么问题了？

> hdchina刷流任务，过滤条件增加后无法新增种子，怀疑是过滤条件判断有问题，修改config.yaml, 打开debug日志。 
“2022-10-04 16:54:52,013	DEBUG: 【BRUSH】Jade.Stars.Academy.S02.2022.HDTV.1080i.H264-HDCTV[声梦传奇 第二季 全15集 | 繁简DvbSub字幕 *聲夢傳奇2 傳奇誕生*] 解析详情, free: None, free2x: None, peer_count: 0, hr: None” 感觉这里解析出来的值有些问题。比如 种子是free的， peer_count 也是大于0 的，对应hdchina 链接：https://hdchina.org/details.php?id=638974

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已确认。

## 你期望的结果

> 正确解析

## 给出程序界面截图、后台运行日志或配置文件

2022-10-04 16:54:52,013	DEBUG: 【BRUSH】Jade.Stars.Academy.S02.2022.HDTV.1080i.H264-HDCTV[声梦传奇 第二季 全15集 | 繁简DvbSub字幕 *聲夢傳奇2 傳奇誕生*] 解析详情, free: None, free2x: None, peer_count: 0, hr: None

![image](https://user-images.githubusercontent.com/15187773/193781925-799ac50c-f5ba-4023-90ae-1fb01fa5d085.png)
![image](https://user-images.githubusercontent.com/15187773/193782067-a2fa955b-0ac0-4618-927f-d06f9daecd2e.png)

**Comment by jxxghp** [comment]
需要提供一下代码：
[协助NASTool支持更多FREE站点检测.zip](https://github.com/jxxghp/nas-tools/files/9715546/NASTool.FREE.zip)

**Comment by yunjie-li** [comment]
站点网址： https://hdchina.org/index.php

FREE:  <img class="pro_free" src="pic/trans.gif" alt="Free" onmouseover="domTT_activate(this, event, 'content', '<b><font class=&quot;free&quot;>免费</font></b>　剩余时间：<b><span title=&quot;2022-10-06 21:38:38&quot;>10时51分</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);" id="__autoId1">

2XFREE: 无

HR: 无

**Comment by yunjie-li** [comment]
站点网址： https://hdchina.org/index.php

FREE:  <img class="pro_free" src="pic/trans.gif" alt="Free" onmouseover="domTT_activate(this, event, 'content', '<b><font class=&quot;free&quot;>免费</font></b>　剩余时间：<b><span title=&quot;2022-10-06 21:38:38&quot;>10时51分</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);" id="__autoId1">

2XFREE: 无

HR: 无

做种人数： <b>608个做种者</b>

**Comment by yunjie-li** [comment]
已发送邮件到 jxxghp@163.com， 这里评论显示不出来free信息，里面可能包含了特殊字符被过滤了。
