### ISSUE TITLE
能否增加订阅的内容，每次使用jackett搜素的开关

### ISSUE THREAD

**Issue by KevinZjYang** [jxxghp/nas-tools#139]
我没理解错的话，现在的订阅是使用“订阅站点”里的rss在更新。
◆我遇到的问题：
我想下动漫，jackett里面配置好了可以搜素并正常下载。但是由于几个动漫站点都是bt站，无法添加订阅站点。
◆导致的结果：
订阅的动漫不会自动更新，需要每次我知道更新了，去订阅里点一下“立即搜素”。如下图所示。
![image](https://user-images.githubusercontent.com/31529584/169439079-4e630e8f-c261-4675-b6ae-7cefeaecc543.png)
◆功能需求：
希望可以在订阅里增加可以使用jackett搜素的功能。有个开关就行，不需要的不打开就默认是rss。

**Comment by jxxghp** [comment]
增量内容用反复搜索来达到目的对PT站会造成压力，不太人道

**Comment by KevinZjYang** [comment]
@jxxghp 那退而求其次，能不能降低频率，一天一次，或者两天一次都可以。至少可以不用自己去点。

**Comment by jxxghp** [comment]
暂不会考虑
