### ISSUE TITLE
搜索功能无法使用

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [jxxghp/nas-tools#1390]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.3 98c92e0c
>
> 环境: Synology
>

## 你遇到什么问题了？

搜索无法使用

## 给出程序界面截图、后台运行日志或配置文件

18:19:50 INFO - 【WEB】开始检索 子弹列车 ...
18:19:54 INFO - 【INDEXER】开始并行检索 子弹列车，线程数：8 ...
18:19:54 INFO - 【INDEXER】开始检索Indexer：北洋园 ...
18:19:54 INFO - 【INDEXER】开始检索Indexer：馒头 ...
18:19:54 INFO - 【INDEXER】开始检索Indexer：观众 ...
18:19:54 INFO - 【INDEXER】开始检索Indexer：猫站 ...
18:19:54 INFO - 【INDEXER】开始检索Indexer：U2 ...
18:19:54 INFO - 【INDEXER】开始检索Indexer：动漫花园 ...
18:19:54 INFO - 【INDEXER】开始检索Indexer：MiKan ...
18:19:54 INFO - 【INDEXER】开始检索Indexer：MioBT ...
18:19:56 WARN - 【INDEXER】馒头 返回数据：8
18:19:56 INFO - 【INDEXER】Bullet Train 2022 2160p WEB-DL DDP5.1 DV MP4 x265-DVSUX 子弹列车 2022 2160p 杜比视界P5版本 识别为 子弹列车 (2022) 匹配成功
18:19:56 INFO - 【INDEXER】Bullet Train 2022 2160p MA WEB-DL DDP5.1 Atmos H.265-CMRG 子弹列车/新干线/杀手列车(港)/杀手界·疾风号/杀手疾风号/瓢虫 [SDR版本] [内封中字] 大卫·雷奇导演作品 布拉德·皮特 识别为 子弹列车 (2022) 匹配成功
18:19:56 INFO - 【INDEXER】Bullet Train 2022 2160p MA WEB-DL DDP5.1 Atmos HDR H.265-CMRG 子弹列车/新干线/杀手列车(港)/杀手界·疾风号/杀手疾风号/瓢虫 [HDR10版本] [内封中字] 大卫·雷奇导演作品 布拉德·皮特 识别为 子弹列车 (2022) 匹配成功
18:19:56 INFO - 【INDEXER】Bullet Train 2022 2160p ATV WEB-DL DDP Atmos 5.1 Hybrid DV HDR H.265-HONE 子弹列车/新干线/杀手列车(港)/杀手界·疾风号/杀手疾风号/瓢虫 [Dolby Vision版兼容HDR10] [内封中字] 大卫·雷.. 识别为 子弹列车 (2022) 匹配成功
18:19:56 INFO - 【INDEXER】Bullet Train 2022 2160p WEB-DL HDR H.265 DD5.1-HDHome 子弹列车/杀手疾风号/杀手列车(港)内封官译简繁字幕/HDR10版本 识别为 子弹列车 (2022) 匹配成功
18:19:56 INFO - 【INDEXER】Bullet Train 2022 1080p AMZN WEB-DL DDP5.1 H.264-FLUX 子弹列车 ブレット・トレイン 新干线 杀手列车(港) 杀手界·疾风号 杀手疾风号 瓢虫 | 导演：大卫·雷奇 | 主演：布拉德·皮特 乔.. 识别为 子弹列车 (2022) 匹配成功
18:19:56 INFO - 【INDEXER】Bullet Train 2022 2160p WEB-DL DD5.1 HDR HEVC-CMRG 子弹列车/新干线/杀手列车(港)/杀手界·疾风号/杀手疾风号/瓢虫 [HDR10版本] 大卫·雷奇导演作品 布拉德·皮特 识别为 子弹列车 (2022) 匹配成功
18:19:56 INFO - 【INDEXER】Bullet Train 2022 2160p WEB-DL DD5.1 HEVC-CMRG 子弹列车/子彈列車/殺手列車 4k非HDR 识别为 子弹列车 (2022) 匹配成功
18:19:56 INFO - 【INDEXER】馒头 共检索到 8 条数据，过滤 0，不匹配 0，有效资源 8，耗时 2 秒
18:19:56 WARN - 【INDEXER】U2 未检索到数据
18:19:57 WARN - 【INDEXER】MiKan 未检索到数据
18:19:57 WARN - 【INDEXER】北洋园 返回数据：8
18:19:57 INFO - 【INDEXER】[日本/美国][子弹列车][Bullet Train 2022 1080p WEBRip DDP5.1 Atmos x264-iFT] 识别为 子弹列车 (2022) 匹配成功
18:19:57 WARN - 【INDEXER】观众 返回数据：12
18:19:57 INFO - 【INDEXER】Bullet Train 2022 2160p MA WEB-DL DDP 5.1 Atmos SDR H.265-SKiZOiD 子弹列车 / 杀手疾风号 / 杀手列车(港) / 新干线 / 瓢虫 | 类型：喜剧 动作 惊悚 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】[日本/美国][子弹列车][Bullet.Train.2022.2160p.MA.WEB-DL.DDP5.1.Atmos.H.265-CMRG] 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】Bullet Train 2022 2160p WEB-DL HDR H.265 DD5.1-HDHome 中字HDR10子弹列车/杀手疾风号/杀手列车(港)[内封官译简繁字幕/HDR10版本] 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】Bullet Train 2022 2160p MA WEB-DL DD+ 5.1 Atmos DoVi HDR H.265-HDT 中字Dolby VisionHDR10子弹列车 / 杀手疾风号 / 杀手列车(港) / 新干线 / 瓢虫 | 类型：喜剧 动作 惊悚 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】[日本/美国][子弹列车][Bullet.Train.2022.2160p.MA.WEB-DL.DDP5.1.Atmos.HDR.H.265-CMRG] 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】[日本/美国][子弹列车][Bullet.Train.2022.2160p.WEB-DL.DDP5.1.Atmos.HDR.H.265-SKiZOiD] 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】[日本/美国][子弹列车][Bullet.Train.2022.2160p.ATV.WEB-DL.DDP.Atmos.5.1.Hybrid.DV.HDR.H.265-HONE] 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】Bullet Train 2022 2160p MA WEB-DL DDP5.1 Atmos H.265-CMRG 中字子弹列车/新干线/杀手列车(港)/杀手界·疾风号/杀手疾风号/瓢虫 [SDR版本] [内封中字] 大卫·雷奇导演作品 布拉德·皮特 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】Bullet Train 2022 2160p MA WEB-DL DDP5.1 Atmos HDR H.265-CMRG 中字HDR10子弹列车/新干线/杀手列车(港)/杀手界·疾风号/杀手疾风号/瓢虫 [HDR10版本] [内封中字] 大卫·雷奇导演作品 布拉德·皮特 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】[日本/美国][子弹列车][Bullet.Train.2022.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX] 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】Bullet Train 2022 2160p ATV WEB-DL DDP Atmos 5.1 Hybrid DV HDR H.265-HONE 中字Dolby VisionHDR10子弹列车/新干线/杀手列车(港)/杀手界·疾风号/杀手疾风号/瓢虫 [Dolby Vision版兼容HDR10] [内封中字] 大卫·雷奇导演作品 布拉德·皮特 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】[日本/美国][子弹列车][Bullet.Train.2022.2160p.WEB-DL.DD5.1.HDR.HEVC-CMRG] 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】Bullet Train 2022 2160p WEB-DL DD5.1 HEVC-CMRG 子弹列车/新干线/杀手列车(港)/杀手界·疾风号/杀手疾风号/瓢虫 [SDR版本] 大卫·雷奇导演作品 布拉德·皮特 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】Bullet Train 2022 2160p WEB-DL DD5.1 HDR HEVC-CMRG HDR10子弹列车/新干线/杀手列车(港)/杀手界·疾风号/杀手疾风号/瓢虫 [HDR10版本] 大卫·雷奇导演作品 布拉德·皮特 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】Bullet Train 2022 1080p AMZN WEB-DL DDP5.1 H.264-FLUX 子弹列车 / 杀手疾风号 / 杀手列车(港) / 新干线 / 瓢虫 | 类型：喜剧 动作 惊悚 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】[日本/美国][子弹列车][Bullet.Train.2022.1080p.WEB-DL.DDP5.1.H.264-EVO] 识别为 子弹列车 (2022) 匹配成功
18:19:57 WARN - 【INDEXER】MioBT 返回数据：6
18:19:57 INFO - 【INDEXER】Bullet Train 2022 2160p WEB-DL DD5.1 HDR HEVC-EVO HDR10子弹列车 / 杀手疾风号 / 杀手列车(港) / 新干线 / 瓢虫 | 类型：喜剧 动作 惊悚 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】北洋园 共检索到 8 条数据，过滤 0，不匹配 0，有效资源 8，耗时 3 秒
18:19:57 INFO - 【INDEXER】Bullet Train 2022 1080p WEB-DL DDP5.1 H.264-EVO 子弹列车 / 杀手疾风号 / 杀手列车(港) / 新干线 / 瓢虫 | 类型：喜剧 动作 惊悚 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】Bullet Train 2022 2160p WEB-DL DoVi DD5.1 HEVC-EVO Dolby Vision子弹列车 / 杀手疾风号 / 杀手列车(港) / 新干线 / 瓢虫 | 类型：喜剧 动作 惊悚 识别为 子弹列车 (2022) 匹配成功
18:19:57 INFO - 【INDEXER】观众 共检索到 12 条数据，过滤 0，不匹配 0，有效资源 12，耗时 3 秒
18:19:59 WARN - 【INDEXER】动漫花园 未检索到数据
18:20:00 WARN - 【SPIDER】错误：Expected selector, got <DELIM ')' at 25> - Traceback (most recent call last): File "/volume1/@appstore/NASTool/nas-tools/app/indexer/client/spider.py", line 461, in parse self.torrents_info_array.append(copy.deepcopy(self.Getinfo(PyQuery(torn)))) File "/volume1/@appstore/NASTool/nas-tools/app/indexer/client/spider.py", line 400, in Getinfo self.Getpubdate(torrent) File "/volume1/@appstore/NASTool/nas-tools/app/indexer/client/spider.py", line 334, in Getpubdate pubdate = torrent(selector.get('selector', '')) File "/var/packages/NASTool/target/lib/python3.9/site-packages/pyquery/pyquery.py", line 261, in __call__ result = self._copy(*args, parent=self, **kwargs) File "/var/packages/NASTool/target/lib/python3.9/site-packages/pyquery/pyquery.py", line 247, in _copy return self.__class__(*args, **kwargs) File "/var/packages/NASTool/target/lib/python3.9/site-packages/pyquery/pyquery.py", line 232, in __init__ xpath = self._css_to_xpath(selector) File "/var/packages/NASTool/target/lib/python3.9/site-packages/pyquery/pyquery.py", line 243, in _css_to_xpath return self._translator.css_to_xpath(selector, prefix) File "/var/packages/NASTool/target/lib/python3.9/site-packages/cssselect/xpath.py", line 192, in css_to_xpath for selector in parse(css)) File "/var/packages/NASTool/target/lib/python3.9/site-packages/cssselect/parser.py", line 415, in parse return list(parse_selector_group(stream)) File "/var/packages/NASTool/target/lib/python3.9/site-packages/cssselect/parser.py", line 428, in parse_selector_group yield Selector(*parse_selector(stream)) File "/var/packages/NASTool/target/lib/python3.9/site-packages/cssselect/parser.py", line 436, in parse_selector result, pseudo_element = parse_simple_selector(stream) File "/var/packages/NASTool/target/lib/python3.9/site-packages/cssselect/parser.py", line 544, in parse_simple_selector raise SelectorSyntaxError( cssselect.parser.SelectorSyntaxError: Expected selector, got <DELIM ')' at 25>
18:20:00 WARN - 【INDEXER】猫站 未检索到数据

**Comment by jxxghp** [comment]
猫站索引报错的问题dev分支最新代码己修复

**Comment by jxxghp** [comment]
#1376
