### ISSUE TITLE
资源搜索能搜到间谍过家家第二季，但订阅的时候说不存在

### ISSUE THREAD

**Issue by shanyan-wcx** [jxxghp/nas-tools#1394]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.1.3
>
> 环境: docker
>

## 你遇到什么问题了？

> 资源搜索能搜到间谍过家家第二季，但订阅的时候说不存在

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 能订阅上

## 给出程序界面截图、后台运行日志或配置文件

> 
![image](https://user-images.githubusercontent.com/58252651/193815626-e3011e77-776d-4259-8e77-0ef0a78728cb.png)
![image](https://user-images.githubusercontent.com/58252651/193815725-7aa508a4-7165-40ab-8bd7-b6ced5e4fa82.png)

**Comment by Jay-Young** [comment]
豆瓣将上下两部分作为第一季、第二季，而我在TMDB编辑资料的时候发现国外都是作为一季的（因为我就是按照豆瓣错误地提交了所谓第二季的信息，已经请求tmdb删除了），包括Netflix上也是这样，最新的一集标记为第13集，我觉得可能是这个原因？

![image](https://user-images.githubusercontent.com/8641055/193824772-6207647f-a914-443b-839d-2f7e5f332f03.png)


![image](https://user-images.githubusercontent.com/8641055/193824731-e6912c90-230c-44e1-b250-148d4ac41752.png)

**Comment by jxxghp** [comment]
关掉豆瓣开关

**Comment by shanyan-wcx** [comment]
要是订阅第一季的话会下载前十二集的集合然后就删除订阅了，我现在只能用自定义订阅
