### ISSUE TITLE
无法搜索到黄金神威1-4季

### ISSUE THREAD

**Issue by linyuan0213** [jxxghp/nas-tools#1399]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.3
>
> 环境: docker
>

## 你遇到什么问题了？

> 搜索订阅不显示黄金神威1-4季，只有一部剧场版，但是豆瓣和tmdb都有，豆瓣app标记想看之后只展示未知电视剧无法订阅，并且无法删除

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 正常订阅

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/26356991/193963967-c4fc599f-38a0-456c-9c59-336f5f72c933.png">
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/26356991/193964023-b26bc88f-f19f-4d72-b9de-1c03698b92e2.png">
<img width="1870" alt="image" src="https://user-images.githubusercontent.com/26356991/193964066-f58cb516-d14b-4566-8662-c037a4241fe3.png">

**Comment by Shurelol** [comment]
#### 首先，豆瓣并没有黄金神威的番剧
![image](https://user-images.githubusercontent.com/16237201/193994586-18165ab3-f905-4784-953e-48d68561a131.png)
#### 其次，你提供的搜索结果截图中根据id都是豆瓣，自然没有黄金神威番剧
![image](https://user-images.githubusercontent.com/16237201/193994609-bd87ecd8-fb0e-4f8f-af97-9425d4454165.png)
#### 最后，你点击订阅的是2023年的黄金神威真人版，tmdb上无该词条

#### 解决办法 ，设置-基础设置-实验室关闭豆瓣名称联想
![image](https://user-images.githubusercontent.com/16237201/193995109-ce8067b5-1d43-47d2-a453-e4f1a056575c.png)

**Comment by linyuan0213** [comment]
<img width="1481" alt="image" src="https://user-images.githubusercontent.com/26356991/193995422-0e9e68f2-340b-4f02-a41d-d0391e4e5877.png">
我搜了有的啊

**Comment by linyuan0213** [comment]
这是我在豆瓣上订阅的，这个不是真人版
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/26356991/193995984-2969bd44-5a8a-4e35-9f84-3780099cb400.png">

**Comment by jxxghp** [comment]
豆瓣不能查到详情，有可能是没有设置cookie

**Comment by linyuan0213** [comment]
> 豆瓣不能查到详情，有可能是没有设置cookie
不是cookie问题，刚才重新设置过还是一样
