### ISSUE TITLE
部分历史记录无法删除，权限已给，其他可以正常删除，但是部分删除之后记录一直存在，文件已经手动删除

### ISSUE THREAD

**Issue by wuzhuwei111** [jxxghp/nas-tools#1400]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.3
>
> 环境: docker
>

## 你遇到什么问题了？

> 部分历史记录无法删除，权限已给777，其他可以正常删除记录并且删除硬链接，但是部分（良医2017）删除之后记录一直存在，硬链接文件手动删除一样无法删除记录。记录一直存在。

**Comment by jxxghp** [comment]
提供一下无法删除这条记录的详情

**Comment by wuzhuwei111** [comment]
@jxxghp
