### ISSUE TITLE
刷流排除HR选项无响应，选择了依然照下HR种子

### ISSUE THREAD

**Issue by eadorothy86** [jxxghp/nas-tools#1402]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>v2.1.3 98c92e0c 
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 选择了排除HR种子，依然照下HR

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

>可以排除HR

## 给出程序界面截图、后台运行日志或配置文件
提供排除HR选项勾选后自动下载HR的种

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
![2022-10-05 17 05 54](https://user-images.githubusercontent.com/85786428/194023709-0630b50f-51d5-4ef8-a121-aedeeeaecaf5.jpg)
![2022-10-05 17 08 26](https://user-images.githubusercontent.com/85786428/194024163-acdf193b-ea42-4235-9adb-e91a7edfa909.jpg)

**Comment by jxxghp** [comment]
需要说明一下具体的站点，提供种子详情页的HR代码。

**Comment by eadorothy86** [comment]
我目前有HR的站只有CHD，其他站点无法测试。抱歉HR代码不知道怎么提供

**Comment by jxxghp** [comment]
[协助NASTool支持更多FREE站点检测.zip](https://github.com/jxxghp/nas-tools/files/9715420/NASTool.FREE.zip)

参考这个提供

**Comment by xyswordzoro** [comment]
<b>H&amp;R:&nbsp;</b>

**Comment by xyswordzoro** [comment]
**<b>H&amp;R:&nbsp;</b>**
