### ISSUE TITLE
通过tmdb来识别剧集 该集属于哪一集

### ISSUE THREAD

**Issue by MrLv0816** [jxxghp/nas-tools#1403]
> NASTool 版本: v2.1.3
> 环境: synology

通过tmdb来识别剧集属于哪一季,例如海贼王,其目前分为了21季,但是大多数资源命名均不规范,导致无法正常识别季,通过tmdb则可以通过集数来搜索到属于那一季

但是这样搜索必然会造成效率下降,可以在订阅中添加新的开关来单独开启这一识别模式

**Comment by Shurelol** [comment]
#### 自定义识别词就是用来在识别前，对名称进行预处理，使其能被正确识别
