### ISSUE TITLE
监控下载软件自动文件转移时，使用下载目录( save_path)作为源目录，而不是使用访问目录(save_containerpath)，在特定情况下自动转移失败。

### ISSUE THREAD

**Issue by fengted** [jxxghp/nas-tools#1405]
## 你使用的 NASTool 是什么版本，什么环境？

>NASTool 版本: v2.1.3
>
>环境: docker

## 你遇到什么问题了？

> 在监控下载软件自动文件转移的设定下，当下载器完成下载，nastools开始处理文件转移时，在特定情况下导致文件转移报错。
> 初步分析原因（纯属推测），是因为nastools使用了下载器设定中的下载目录(save_path)，而不是访问目录(save_containerpath)来定位源文件。

具体触发条件：

1、nastools 和 下载器（qBittorrent)均已docker方式，在同一宿主机上运行；
2、nastools和qBittorrent对一物理目录的存储空间映射命名不同；
nastools:  -v /Video:/videos
qBittorrent: -v /Video:/video

从实时日志看，nastools使用了/video来定位源文件，但nastools其实并没有这个目录。

<img width="688" alt="image" src="https://user-images.githubusercontent.com/7495610/194086856-f4223154-87c9-40f7-9570-dd98d210dbaa.png">

经测试，将nastools和qBittorrent，对目录/Video的目录映射采用同一命名/videos后，文件转移运行正确。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是。

## 你期望的结果

> 虽然通过修改docker的目录映射，可以解决此问题。但从程序逻辑上，nastools应该使用下载器设置中的访问目录(save_containerpath)来定位源文件，而不应使用下载目录来定位源文件。（因为下载目录只是传递给下载器使用，并不表示nastools就可以利用这个路径访问到源文件）。

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by davidlin88** [comment]
我也有这个问题，docker qb的下载目录被当做磁盘真实目录了，我的解决方案是给qb映射存储路径时，容器的路径也写成真实的磁盘路径（形如/volumn4/Downloads/pt），之后要重启下nas-tools。可以参考下

**Comment by liushuaikobe** [comment]
请问这个在最新版本里面修复了吗？

**Comment by Shurelol** [comment]
nastool监控下载软件，定位下载任务的的位置
既不是用在nastool填写的下载目录（例如D:/1）
也不是用在nastool填写的访问目录（例如/media）。

而是通过api获取下载器中下载任务的保存路径（例如D:/1/movie），再将改路径中包含的下载路径（D:/1）替换为访问目录（/media），生成nastool访问下载文件的路径（/media/movie）

**Comment by liushuaikobe** [comment]
> 

十分感谢解答。

请问 nas-tools 将 **下载完毕的文件** 同步到 **媒体库** 是自动完成的吗？

这个跟 “目录同步” 里面的配置项有关系或关联吗，是必须要在 目录同步 里面配置好一条规则（即 将所谓的 “nastool访问下载文件的路径（/media/movie）”）同步 到 媒体库目录，才会做同步的操作是吗？
