### ISSUE TITLE
媒体识别记录。

### ISSUE THREAD

**Issue by ocean521** [jxxghp/nas-tools#141]
剧集硬链接后，均未出现在媒体识别-历史记录里，主要是有一些错误的需要手工识别，未在历史记录出现就不能手工操作，找了一个正确识别的剧集，在日志中找关键字也未发现日志中有有关内容。

**Comment by ocean521** [comment]
现在只要一个未识别的，通过人工识别，出现在历史记录中了

**Comment by jxxghp** [comment]
不是程序问题
