### ISSUE TITLE
建议增加别名搜索

### ISSUE THREAD

**Issue by linyuan0213** [jxxghp/nas-tools#1418]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.3
>
> 环境: docker
>

## 你遇到什么问题了？

> 搜索的时候部分番剧在dmhy等站点使用的名称不是标准名称，而是别名，导致番剧无法搜索到

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 添加别名搜索正常搜索到番剧

## 给出程序界面截图、后台运行日志或配置文件
<img width="1798" alt="image" src="https://user-images.githubusercontent.com/26356991/194246628-140b385f-b80c-49fc-a811-2e08d292d87a.png">
<img width="659" alt="image" src="https://user-images.githubusercontent.com/26356991/194246852-4bfc6f87-1b89-4f72-9d44-b1150ec92931.png">
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/26356991/194246971-82c1be54-ab1d-4a51-9812-1c2ebae2ae5b.png">

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
![image](https://user-images.githubusercontent.com/51039935/194271492-393caaa0-882c-4838-a235-c4c8830262de.png)

**Comment by jxxghp** [comment]
![image](https://user-images.githubusercontent.com/51039935/194273657-05602e7f-f64e-495b-a602-efb5209955b1.png)

**Comment by jxxghp** [comment]
别名这么多，没法每个都搜索一遍，还有更不规范的，用自定义识别词替换掉

**Comment by linyuan0213** [comment]
> 别名这么多，没法每个都搜索一遍，还有更不规范的，用自定义识别词替换掉

普通搜索替换了还是没法搜索到，切换到高级搜索可以，不知道这是不是bug
