### ISSUE TITLE
Jackett搜索资源存在但是资源类型对不上是什么原因

### ISSUE THREAD

**Issue by mywinr** [jxxghp/nas-tools#142]
23:32:17 INFO - 【SEARCHER】正在识别 亚当计划 的媒体信息...
23:32:17 INFO - 【META】正在识别电视剧：亚当计划, 年份= ...
23:32:18 WARN - 【META】亚当计划 未找到媒体信息!
23:32:18 INFO - 【SEARCHER】亚当计划 查询不到媒体信息
23:32:25 INFO - 消息内容：亚当计划
23:32:25 INFO - 【SEARCHER】正在识别 亚当计划 的媒体信息...
23:32:26 INFO - 类型：电影，标题：The Adam Project，年份：2022
23:32:27 INFO - 【SEARCHER】开始检索 The Adam Project ...
23:32:27 INFO - 【JACKETT】开始并行检索 The Adam Project，线程数：6
23:32:27 INFO - 【JACKETT】开始检索Indexer：acgsou ...
23:32:27 INFO - 【JACKETT】开始检索Indexer：dmhy ...
23:32:27 INFO - 【JACKETT】开始检索Indexer：eztv ...
23:32:27 INFO - 【JACKETT】开始检索Indexer：lemonhd ...
23:32:27 INFO - 【JACKETT】开始检索Indexer：pttime ...
23:32:27 WARN - 【JACKETT】eztv 未检索到资源
23:32:27 WARN - 【JACKETT】dmhy 未检索到资源
23:32:27 INFO - 【JACKETT】开始检索Indexer：rarbg ...
23:32:27 WARN - 【JACKETT】lemonhd 返回数据：4
23:32:27 WARN - 【JACKETT】rarbg 未检索到资源
23:32:28 INFO - 【JACKETT】The Adam Project 2022 2160p NF WEB-DL x265 10bit HDR DDP5.1 Atmos-SCOBELL 是 电视剧，不匹配类型
23:32:28 INFO - 【JACKETT】The Adam Project 2022 1080p DSNP WEB-DL DDP5.1 Atmos Multiple Audios X264 ASS-DIY@JAKET789 是 电视剧，不匹配类型
23:32:28 INFO - 【JACKETT】The Adam Project 2022.1080p NF WEB-DL DDP5.1 Atmos HDR HEVC-TEPES 是 电视剧，不匹配类型
23:32:28 INFO - 【JACKETT】The Adam Project 2022 1080p Netflix WEB-DL H.264 DDP5.1-OurTV 是 电视剧，不匹配类型
23:32:28 INFO - 【JACKETT】lemonhd 共检索到 0 条有效资源
23:32:30 WARN - 【JACKETT】pttime 未检索到资源
23:32:37 WARN - 【JACKETT】acgsou 未检索到资源
23:32:37 INFO - 【JACKETT】所有API检索完成，有效资源数：0
23:32:37 INFO - The Adam Project 未检索到任何资源

**Comment by jxxghp** [comment]
把配置目录下meta.dat删掉，重新搜索试下

**Comment by jxxghp** [comment]
确认这个没有问题，一般原因可能是网络原因导致的错误缓存，重启或者删除meta.dat后重启。
