### ISSUE TITLE
希望能在订阅中安排一个选项，订阅完成后不删除订阅

### ISSUE THREAD

**Issue by Earendil-C** [jxxghp/nas-tools#1423]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.3
>
> 环境: docker

## 你想要新增或者改进什么功能？

>希望能在订阅中安排一个选项，订阅完成后不删除订阅。有部分比较冷门的番剧/电视剧在tmdb更新不太及时（如总集数），订阅时会订阅较少的集数（如只有第一集），完成后订阅自动被删除，需要再添加一次。此外也可用于搭配前面一个issue所说的强制覆盖洗版功能在完结后进行洗版

## 这个功能有什么可以参考的资料吗？

> 无

**Comment by Earendil-C** [comment]
以及发现订阅中的电视剧总集数不会在刷新后重新在tmdb中抓取新的总集数，需要删除订阅后重新订阅，希望能在刷新时同时更新一下总集数

**Comment by jxxghp** [comment]
1、#1533 这个已经增加了相关的功能，TMDB集数不对的，手工输入总集数订阅。
2、遇到命名不规范没有集数的，现在会解析种子文件看里面了集数了。
