### ISSUE TITLE
搜索电影时能不能检查自己的片库里面是否有改资源，避免重复下载

### ISSUE THREAD

**Issue by zjnjava** [jxxghp/nas-tools#1425]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.1.3
>
> 环境: synology

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
搜索电影时能不能检查自己的片库里面是否有改资源，片库里面的资源太多忘记了看到的影片是否在自己的片库李存在，每次下载前都要在片库里搜索一遍。否则会重复下载
## 这个功能有什么可以参考的资料吗？
目前无参考资料
> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
了解清楚再提问
