### ISSUE TITLE
集数偏移识别错误

### ISSUE THREAD

**Issue by linyuan0213** [jxxghp/nas-tools#1431]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 设置集数偏移之后，数字全部减去偏移量

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 正确识别

## 给出程序界面截图、后台运行日志或配置文件
<img width="714" alt="image" src="https://user-images.githubusercontent.com/26356991/194325435-3d9f1bd9-9e28-499d-b352-3c7339530a8c.png">

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Shurelol** [comment]
### 请问能理解什么叫使前后定位词之间的数字为集数么？

#### 没有设置后定位词，那么从前定位词往后所有的数字均会被认为是集数进行偏移
![image](https://user-images.githubusercontent.com/16237201/194370489-4a77247d-902c-467b-94a1-0df436791b03.png)
![image](https://user-images.githubusercontent.com/16237201/194370507-6ec4b09e-8b63-4d9e-8078-0f8fe483814f.png)
#### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助

**Comment by linyuan0213** [comment]
> ### 请问能理解什么叫使前后定位词之间的数字为集数么？
> ### 没有设置后定位词，那么从前定位词往后所有的数字均会被认为是集数进行偏移
> ![image](https://user-images.githubusercontent.com/16237201/194370489-4a77247d-902c-467b-94a1-0df436791b03.png) ![image](https://user-images.githubusercontent.com/16237201/194370507-6ec4b09e-8b63-4d9e-8078-0f8fe483814f.png)
> 
> #### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助

我理解你后定位词的意思，但是这个后定位词本身就是不确定的，为什么要加，还有为什么不使用非贪婪匹配，匹配最近一个？
