### ISSUE TITLE
剧集订阅UI交互逻辑优化建议

### ISSUE THREAD

**Issue by yubanmeiqin9048** [jxxghp/nas-tools#1433]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.2.0
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 因为订阅电影、电视剧或者动漫的时候想使用不同的规则，在搜索点击订阅后又得回到电视剧订阅或者电影订阅栏点击刚才订阅的内容才可以修改对应的规则，这样略微有些繁琐，所以希望可以在可以在点击订阅后弹出一个可供进入自定义订阅编辑订阅的按钮

## 这个功能有什么可以参考的资料吗？

>比如在这里
![`T%M4_K)5({ZO5Z75E(P2MU](https://user-images.githubusercontent.com/64676973/194356596-7ae69557-948c-4650-8835-5f88c8226213.png)
>
>或者是点击订阅的时候，不过秉承自动化原则我认为还是上一种情况好一些

**Comment by jxxghp** [comment]
没看懂，是指订阅完后的提示有按钮可以直接编辑订阅吗？

**Comment by yubanmeiqin9048** [comment]
> 没看懂，是指订阅完后的提示有按钮可以直接编辑订阅吗？

是的
