### ISSUE TITLE
标题包含part 被识别成剧集名称Part了

### ISSUE THREAD

**Issue by Bohe621** [jxxghp/nas-tools#1435]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1.3 98c92e0c
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 剧集 标题包含part 被识别成剧集名称Part了。。
如下图：The.Good.Doctor.S01E11.Islands.Part.One.Part.1.1080p.AMZN.WEB-DL.DDP5.1.x265.10bit-Yumi@FRDS
这集刚好叫Part.1。。是否可以考虑识别出季度集数之后忽略part？
![bug1](https://user-images.githubusercontent.com/51063830/194370893-d63a9888-a5a2-4737-af52-6d4cc0ea622c.jpg)
![bug2](https://user-images.githubusercontent.com/51063830/194370900-e752d679-2c5d-4882-bd7c-1d461a707fc5.jpg)

**Comment by jxxghp** [comment]
正确的part就是应该在季数后。
