### ISSUE TITLE
希望添加一个字幕转移的选项

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [jxxghp/nas-tools#1439]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.0
>
> 环境: synology

## 你想要新增或者改进什么功能？

> 希望添加一个手动转移字幕的选项，我的钢炼fa下载完成后我把同命名的ass文件放到对应目录后进行手动转移，但字幕并不有重命名硬连接，而视频会重命名硬连接，希望能添加单独的手动识别字幕的功能，这样哪怕不是同命名的字幕也可以利用nastool的名称识别借由tmdb的资料库识别重命名，避免手动去excel重命名字幕文件的麻烦

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
现在放在同目录下的字幕，不是名字完全一样也能识别转移的。

**Comment by ironstress** [comment]
> 现在放在同目录下的字幕，不是名字完全一样也能识别转移的。

使用目录同步会转移吗?

**Comment by jxxghp** [comment]
> > 现在放在同目录下的字幕，不是名字完全一样也能识别转移的。
> 
> 使用目录同步会转移吗?

会
