### ISSUE TITLE
季识别问题

### ISSUE THREAD

**Issue by TSZXni** [jxxghp/nas-tools#1440]
## 版本
> NASTool 版本: 2.1.3
## 环境
> 环境: Synology
## 你遇到什么问题了？
> 不知道是设置问题还是什么，手动目录同步的时候，多季只能完成一季，并且，是第二季识别顶替了第一季
[2016][New Game!][BDRIP][1080P][1-12Fin+SP]
[2017][New Game!!][BDRIP][1080P][1-12Fin+SP]
点开文件查看，在season1目录下硬链接的是第二季，且没办法同步出season2文件夹

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
命名问题，服务中识别测试
