### ISSUE TITLE
订阅剧集从指定集数开始订阅

### ISSUE THREAD

**Issue by yourber** [jxxghp/nas-tools#1447]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.2.0
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 订阅剧集从指定集数开始订阅，比如一些动漫特别长，前100集都看过了，订阅的时候可以选择直接从101集开始订阅，再比如一些新播的剧集，在电视上看了前几集，订阅的时候这几集就没必要再下载一遍，订阅的时候将它们排除掉。

## 这个功能有什么可以参考的资料吗？

> 暂无

**Comment by yourber** [comment]
我觉得可以弄一个订阅集数区间，比如 100~无限、100~200、无限~无限，这个样子。

**Comment by Shurelol** [comment]
#### 过滤规则使用正则表达式订阅100集以后，包含 第[1-9][0-9][0-9]集
#### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助

**Comment by jxxghp** [comment]
#1533
