### ISSUE TITLE
【建议】改进壁纸获取方式

### ISSUE THREAD

**Issue by wangweiwei104** [jxxghp/nas-tools#1451]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.2.0
>
> 环境:synology

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

建议增加“是否开启tmdb海报作为壁纸”的开关，或者增加自定义壁纸的功能，原因如下：
1.在定义url与函数映射之前，调用tmdb海报作为壁纸（main.py:75行），一旦网络出现问题，会造成无法启动服务，用户无法进入登录页面。
造成这种现象的（可复现）情景：本人配置了ipv6，但是由于最近的特殊情况，ipv6不通，但是这种情况会造成程序卡在cached_request（）中。。。。

2.由于是随机获取的方式，壁纸的质量高低不一，好看的海报无法保存，丑的海报吓人一跳。。。。比如有个大眼睛的海报，吓我一跳。。。。

**Comment by jxxghp** [comment]
1的问题应该没有了

**Comment by jxxghp** [comment]
```
app: 
   # 【登录界面壁纸】：themoviedb、bing，设置为themoviedb时需要配置TMDB API Key时才生效
    wallpaper: bing
```

**Comment by Tasle** [comment]
> ```
> app: 
>    # 【登录界面壁纸】：themoviedb、bing，设置为themoviedb时需要配置TMDB API Key时才生效
>     wallpaper: bing
> ```

大大能不能增加个关闭随机壁纸只用初始的纯色背景的按钮功能啊？觉得初始的挺好的，每次换来换去的确实有时候有点吓人有时候又不适合在公众场合打开
