### ISSUE TITLE
影视推荐中添加 爱奇艺/腾讯视频的高分新片

### ISSUE THREAD

**Issue by shawnzhou1120** [jxxghp/nas-tools#1456]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本:

 v2.0.5
>
> 环境: 

docker in synology

## 你想要新增或者改进什么功能？

在影视推荐里面，能否加上爱奇艺/腾讯视频的高分新片的内容？最近疫情，外国的电影更新都比较慢且有间断性的片荒，但是国产的 网络片，有时仍然有一些值得看的网络电影，所以能否增加把爱奇艺的新片/腾讯的新片也拉入推荐 里，这样就可以一间选片顺便PT里寻找下载了

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Tartarus2014** [comment]
再加个哔哩哔哩的高分新片可以么

**Comment by evakenshin** [comment]
豆瓣里应该都有吧

**Comment by jxxghp** [comment]
得有api吧，这些都是动态网站，不好爬。

**Comment by Tartarus2014** [comment]
哔哩哔哩的话用cookie应该可以做到？

**Comment by zhaokun0721** [comment]
就豆瓣足够了把 这些视频网站上的评分不具备参考价值 感觉

**Comment by shawnzhou1120** [comment]
豆瓣不全的，现在已经有很多爱奇艺或者腾讯的自制或者独家片，这些片子都不纳入豆瓣中的。另外一个好处是，爱奇艺和腾讯出来了，一般PT就有下的了

**Comment by evakenshin** [comment]
> 豆瓣不全的，现在已经有很多爱奇艺或者腾讯的自制或者独家片，这些片子都不纳入豆瓣中的。另外一个好处是，爱奇艺和腾讯出来了，一般PT就有下的了

能举些例子吗？确实没关注过，一般想看的剧在豆瓣搜索都会有。还没见过没有的
