### ISSUE TITLE
电视剧订阅填字幕组报不符合高级过滤条件

### ISSUE THREAD

**Issue by HBSpy** [jxxghp/nas-tools#1457]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.2.0 032aa492
>
> 环境: docker
>

## 你遇到什么问题了？

> 不填过滤规则里的字幕组时匹配成功
> 2022-10-07 22:15:48,218 INFO: 【JACKETT】[桜都字幕组] 宇崎学妹想要玩！ω / Uzaki-chan wa Asobitai! Double [01][1080p][繁 体内嵌]  识别为 宇崎学妹想要玩！ (2020) S02 E01 匹配成功
> 添加后匹配失败
> 2022-10-07 22:17:03,974 INFO: 【JACKETT】[桜都字幕组] 宇崎学妹想要玩！ω / Uzaki-chan wa Asobitai! Double [01][1080p][繁 体内嵌] 不符合高级过滤条件

Uzaki-chan wa Asobitai! Double 有自定义替换成了Uzaki-chan wa Asobitai! [S02]

## 你期望的结果

> 正常匹配

## 给出程序界面截图、后台运行日志或配置文件

![QQ截图20221007222136](https://user-images.githubusercontent.com/3386804/194576060-a8ec1098-caef-4a9a-8082-15586d5b0c9a.png)

先提个issue，如果明天上班不忙再跟跟代码

**Comment by Shurelol** [comment]
#### 动漫替换季数时，请用 第x季 而非 S0x
![image](https://user-images.githubusercontent.com/16237201/194586207-89dde49b-5715-4b1c-8163-192ee824a77a.png)
![image](https://user-images.githubusercontent.com/16237201/194586228-88c9d0f3-c0d3-4cf3-b4ab-166dfce92bff.png)
![image](https://user-images.githubusercontent.com/16237201/194586247-8ba326b9-d917-4cb7-9921-a6d1d5becd0b.png)

#### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助

**Comment by HBSpy** [comment]
好家伙，还有这种操作

**Comment by jxxghp** [comment]
高级过滤条件直接使用种子名，不会使用自定义识别词（只用于识别，不用于过滤）
话说搜索站点是你自己改了吗，怎么显示怪怪的。

**Comment by Shurelol** [comment]
这个 不符合高级过滤条件 应该是 字幕组不符合吧

**Comment by HBSpy** [comment]
> 

没啊，JACKETT里添加的站点，怪在哪里了
不过我按[Shurelol](https://github.com/Shurelol)的改法的确好了
