### ISSUE TITLE
【致命BUG】核心操作/do 接口未登录可以随意调用重启服务，甚至初始化管理员

### ISSUE THREAD

**Issue by pofey** [jxxghp/nas-tools#146]
https://github.com/jxxghp/nas-tools/blob/28f10e09457317918726ff58a57676d8235aeb97/web/main.py#L1005

![IMG_6581](https://user-images.githubusercontent.com/1396975/169664605-cc78119e-f48c-4737-a059-070d174bace8.jpg)

管理好自己的群成员，别什么事都扯到我们，被迫害妄想症么，自信一点好好开发自己的软件。

**Comment by jxxghp** [comment]
有问题好好提issues，不要把这些乱七八糟的事情弄到开源项目里来，真恶心。
没有会傻到在开源故意留后门，请不要恶意攻击。

**Comment by jxxghp** [comment]
接口认准的问题稍后修复

**Comment by pofey** [comment]
> 有问题好好提issues，不要把这些乱七八糟的事情弄到开源项目里来，真恶心。
> 没有会傻到在开源项目中故意留后门，请不要恶意攻击。

你tm是个傻逼吧，谁攻击你了

**Comment by fallenyy** [comment]
> 你 tm 是个吧，谁攻击你了 别什么屎盆子都往我和 movie robot 上扣，自己代码写出问题，我气的来你这里分析提 issue ，还在这 bb ，你有点了。

你个傻逼享受着开源的便利到处当婊子立牌坊敛财，你是什么人别人知道看过你这个项目历史的人都清楚，不折不扣的流氓，别人做个免费开源项目挡着你行骗敛财了？到处宣传自己的项目收钱诋毁别人，动不动就骂人。最近收入变少了吗见人就咬？到别人群里发体验码？恶心至极。

**Comment by M-chacha** [comment]
> > 你 tm 是个吧，谁攻击你了 别什么屎盆子都往我和 movie robot 上扣，自己代码写出问题，我气的来你这里分析提 issue ，还在这 bb ，你有点了。
> 
> 你个傻逼享受着开源的便利到处当婊子立牌坊敛财，你是什么人别人知道看过你这个项目历史的人都清楚，不折不扣的流氓，别人做个免费开源项目挡着你行骗敛财了？到处宣传自己的项目收钱诋毁别人，动不动就骂人。最近收入变少了吗见人就咬？到别人群里发体验码？恶心至极。

你TM算个什么玩意。又当又立的不是nastool？白嫖狗还以为自己赚了？写的代码是什么垃圾玩意，发个开源仓库以为自己是根葱了？挑起事情的哪次不是你们的群？一堆脑瘫在那里无端猜测阴谋论。这作者多少次先在张大妈MR文章下说用他的nastool。没动脑在这吠什么呢？

**Comment by fallenyy** [comment]
> 你TM算个什么玩意。又当又立的不是nastool？白嫖狗还以为自己赚了？写的代码是什么垃圾玩意，发个开源仓库以为自己是根葱了？挑起事情的哪次不是你们的群？一堆脑瘫在那里无端猜测阴谋论。这作者多少次先在张大妈MR文章下说用他的nastool。没动脑在这吠什么呢？
  行了垃圾狗，到处乱吠。你这种人还谈什么尊重开源 。网络的巨人，现实的落魄矮子。当好你的婊子角色继续演，看看那些人是怎么说你的。

**Comment by DaBo0219** [comment]
> > 你TM算个什么玩意。又当又立的不是nastool？白嫖狗还以为自己赚了？写的代码是什么垃圾玩意，发个开源仓库以为自己是根葱了？挑起事情的哪次不是你们的群？一堆脑瘫在那里无端猜测阴谋论。这作者多少次先在张大妈MR文章下说用他的nastool。没动脑在这吠什么呢？
> 
>   
> 
> 行了垃圾狗，到处乱吠。你这种人还谈什么尊重开源 。网络的巨人，现实的落魄矮子。当好你的婊子角色继续演，看看那些人是怎么说你的。
> 
> 

> 我真的怀疑你们是来蹭movie robot热度的  。 还喷人。 你是网络里的执法者？ 山上的野猴子 你也配？ 可别出来丢人现眼了 在你的小圈子里蜷缩好 别再出来吠了 做个人

**Comment by DaBo0219** [comment]
> > 你TM算个什么玩意。又当又立的不是nastool？白嫖狗还以为自己赚了？写的代码是什么垃圾玩意，发个开源仓库以为自己是根葱了？挑起事情的哪次不是你们的群？一堆脑瘫在那里无端猜测阴谋论。这作者多少次先在张大妈MR文章下说用他的nastool。没动脑在这吠什么呢？
> 
>   
> 
> 行了垃圾狗，到处乱吠。你这种人还谈什么尊重开源 。网络的巨人，现实的落魄矮子。当好你的婊子角色继续演，看看那些人是怎么说你的。
> 
> 

我真的怀疑你们是来蹭movie robot热度的 。 还喷人。 你是网络里的执法者？ 山上的野猴子 你也配？ 可别出来丢人现眼了 在你的小圈子里蜷缩好 别再出来吠了 做个人

**Comment by fallenyy** [comment]
> 我真的怀疑你们是来蹭movie robot热度的 。 还喷人。 你是网络里的执法者？ 山上的野猴子 你也配？ 可别出来丢人现眼了 在你的小圈子里蜷缩好 别再出来吠了 做个人

有点脑子，到别人项目里来哔哔到底是谁蹭谁的热度。来不来就喷人的也就你们这种物以类聚的东西了

**Comment by jxxghp** [comment]
> > 有问题好好提issues，不要把这些乱七八糟的事情弄到开源项目里来，真恶心。
> > 没有会傻到在开源项目中故意留后门，请不要恶意攻击。
> 
> 你tm是个傻逼吧，谁攻击你了 别什么屎盆子都往我和movie robot上扣，自己代码写出问题，我气的来你这里分析提issue，还在这bb，你有点不要脸了。

我哪知道你是谁呀，昨天确定有人来群里说我故意留后门，然后还攻击了我们群里一个人的账号。
文明说话，不要骂人。

**Comment by leverule** [comment]
吃瓜，笑死。nastool作者你好，开发的这个项目很赞很努力。咱就是说，代码出问题用户被干，就有狗乱咬MR，那玩意没脑子可你有啊，这么容易被带节奏么。比如管好楼上那只

**Comment by fallenyy** [comment]
> 吃瓜，笑死。nastool作者你好，开发的这个项目很赞很努力。咱就是说，代码出问题用户被干，就有狗乱咬MR，那玩意没脑子可你有啊，这么容易被带节奏么。比如管好楼上那只

带你妈的节奏啊，都尼玛什么狗一来就乱咬。吃瓜吃到你吗YD里面了吗。你是MR刚牵来的傻狗吗

**Comment by DaBo0219** [comment]
> > > 有问题好好提issues，不要把这些乱七八糟的事情弄到开源项目里来，真恶心。
> 
> > > 没有会傻到在开源项目中故意留后门，请不要恶意攻击。
> 
> > 
> 
> > 你tm是个傻逼吧，谁攻击你了 别什么屎盆子都往我和movie robot上扣，自己代码写出问题，我气的来你这里分析提issue，还在这bb，你有点不要脸了。
> 
> 
> 
> 我哪知道你是谁呀，昨天确定有人来群里说我故意留后门，然后还攻击了我们群里一个人的账号。
> 
> 文明说话，不要骂人。

先管好你们群里的人吧。 张口闭口喷粪。

**Comment by DaBo0219** [comment]
> > 我真的怀疑你们是来蹭movie robot热度的 。 还喷人。 你是网络里的执法者？ 山上的野猴子 你也配？ 可别出来丢人现眼了 在你的小圈子里蜷缩好 别再出来吠了 做个人
> 
> 
> 
> 有点脑子，到别人项目里来哔哔到底是谁蹭谁的热度。来不来就喷人的也就你们这种物以类聚的东西了
> 
> 

要不你攻击我们这的开发者 谁想来你们这。脑子没问题吧

**Comment by leverule** [comment]
咯咯，别停，狗子叫唤的好呀

**Comment by jxxghp** [comment]
> 吃瓜，笑死。nastool作者你好，开发的这个项目很赞很努力。咱就是说，代码出问题用户被干，就有狗乱咬MR，那玩意没脑子可你有啊，这么容易被带节奏么。比如管好楼上那只

昨天晚上确实有人在群里恶意搞事攻击，然后又有人来这贴另一个群里的聊天截图，自然就联系到一块去了。我说恶心的意思也是指这些无聊的事情能不能不要搞到项目里来，issues只提问题就好了啊。

别人干什么我管不着，我也没有拉帮结派的意思。我代码写的不好，但也请不要来这里污染，与项目无关的不要贴到这里来。

你们看看上面这些无聊的对骂，有意义吗？都停了吧。

**Comment by M-chacha** [comment]
> > 吃瓜，笑死。nastool作者你好，开发的这个项目很赞很努力。咱就是说，代码出问题用户被干，就有狗乱咬MR，那玩意没脑子可你有啊，这么容易被带节奏么。比如管好楼上那只
> 
> 昨天晚上确实有人在群里恶意搞事攻击，然后又有人来这贴另一个群里的聊天截图，自然就联系到一块去了。我说恶心的意思也是指这些无聊的事情能不能不要搞到项目里来，issues只提问题就好了啊。
> 
> 别人干什么我管不着，我也没有拉帮结派的意思。我代码写的不好，但也请不要来这里污染，与项目无关的不要贴到这里来。
> 
> 你们看看上面这些无聊的对骂，有意义吗？都停了吧。

你管好你群里的人，什么事都没有。别动不动扯什么哪个人是MR用户过去的。MR用户不会你们nts人的阴谋论及口臭。物以类聚只存在你群，懂？
