### ISSUE TITLE
Win版更新2.2版本后 站点管理-数据统计无法打开 一直转圈  恢复2.1.3版本后 就正常了 .

### ISSUE THREAD

**Issue by zhaokun0721** [jxxghp/nas-tools#1461]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.2.0
>
> 环境: windows
>

## 你遇到什么问题了？

> Window更新2.2版本后 站点管理-数据统计无法打开 一直转圈  恢复2.1.3版本后 就正常了 .

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Antonchenxr** [comment]
群晖套件版本一样遇到了该问题

**Comment by jxxghp** [comment]
Windows版本后面有更新过的，确认下是否有下载最新的（最新的有仿真开关，无法打开的偿试关掉）

**Comment by jxxghp** [comment]
升级最新程序，在设置实验室中关掉浏览器仿真

**Comment by Antonchenxr** [comment]
实验室没有开启这个选项，并且已经尝试开启后再关闭，版本号是2.2.0-1  （矿神的群晖库里拉取）
站点资源、自动签到都是ok的，唯独数据统计无限加载，谷歌，Safari、360极速、edge均该现象。

**Comment by MrH723** [comment]
一样的问题。关掉了浏览器仿真也进不去.不知道群晖怎么退回2.1.3.

**Comment by zhaokun0721** [comment]
> 升级最新程序，在设置实验室中关掉浏览器仿真

老大 默认并没有打开  尝试打开后 再关闭 问题依旧。

**Comment by jxxghp** [comment]
都是套件吗？

**Comment by MrH723** [comment]
> 都是套件吗？

是的。群晖套件。删除重装。关掉仿真。再重启nas。都是无限转圈。。

**Comment by jxxghp** [comment]
> > 都是套件吗？
> 
> 
> 
> 是的。群晖套件。删除重装。关掉仿真。再重启nas。都是无限转圈。。
> 
> 大佬能在官网放历届历史版本的spk吗，如果有问题能很快找到历史版本回溯.

群晖套件我没有在维护

**Comment by jxxghp** [comment]
> > 都是套件吗？
> 
> 
> 
> 是的。群晖套件。删除重装。关掉仿真。再重启nas。都是无限转圈。。
> 
> 大佬能在官网放历届历史版本的spk吗，如果有问题能很快找到历史版本回溯.

群晖套件我没有在维护

**Comment by Antonchenxr** [comment]
矿神在套件中心推送了2.2.0-2版本，更新以后已经可以刷新出大部分站点数据了，我还有一个馒头没有刷新出来，还在找原因。
