### ISSUE TITLE
【BUG】已订阅的电影无法编辑

### ISSUE THREAD

**Issue by JKnuts** [jxxghp/nas-tools#1462]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.0 57ea43c1
>
> 环境: docker
>

## 你遇到什么问题了？

> 左边两部是V2.2版本之前的订阅，龙珠是v2.2之后刚才测试的，3部点击编辑按钮均无反应
![image](https://user-images.githubusercontent.com/91355283/194683303-7c529503-6f74-4457-a652-8064fdfc20e2.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 搜索过，无法解决

## 你期望的结果

> 修复bug

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
[nas-tools-stdout---supervisor-p3cqhga7.log](https://github.com/jxxghp/nas-tools/files/9738236/nas-tools-stdout---supervisor-p3cqhga7.log)

**Comment by jxxghp** [comment]
无法重现哦，F12控制台看看有没有报错

**Comment by JKnuts** [comment]
> 无法重现哦，F12控制台看看有没有报错

是指这个吗？
![image](https://user-images.githubusercontent.com/91355283/194686112-6db0c018-2139-4df4-9d6a-62618b18c5bd.png)

**Comment by jxxghp** [comment]
> > 无法重现哦，F12控制台看看有没有报错
> 
> 
> 
> 是指这个吗？
> 
> ![image](https://user-images.githubusercontent.com/91355283/194686112-6db0c018-2139-4df4-9d6a-62618b18c5bd.png)
> 
> 

你是用代理什么的开了缓存？可以页面资源不是最新的。

**Comment by JKnuts** [comment]
重新再拉了一次镜像就没问题了，浏览器仿真的开关也有了
