### ISSUE TITLE
海豚和海豹没法签到

### ISSUE THREAD

**Issue by zph308** [jxxghp/nas-tools#1464]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: [v2.2.0]
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 海豚和海豹站点签到失败 ping网址可以ping通
不知道是不是Gazelle框架的原因

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 正常打开页面签到

## 给出程序界面截图、后台运行日志或配置文件

<img width="286" alt="微信截图_20221008105907" src="https://user-images.githubusercontent.com/63138532/194685050-f6ebe560-98c7-4261-9181-43d38772f924.png">
<img width="681" alt="微信截图_20221008110109" src="https://user-images.githubusercontent.com/63138532/194685058-e9a1f7ba-29f2-47e3-959d-4d381cbef551.png">

**Comment by jxxghp** [comment]
你要用浏览器打开看下，而且可能当时确实连不上（超时时间30秒），后面又可以了。
有其它成功的情况下，无法打开网站这个错不会是假报的。
