### ISSUE TITLE
Emby无法发现已经存在的电视剧集

### ISSUE THREAD

**Issue by fivedays5** [jxxghp/nas-tools#1465]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>V2.2.0
> 环境: docker or windows or Synology
>windows 10, python 3.10

## 你遇到什么问题了？

> 添加新的订阅时，无法发现已经存在的电视剧集

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 描述以下你期望的结果

## 导致问题的原因是Emby使用的是英文标题，而Nas tool使用的是中文标题进行的搜索。进而无法发现已经存在的电视剧集。希望可以增加英文标题搜索的选项。PS. 英文搜索时，如大小写不匹配，也无法发现已经存在的剧集。

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
不要重复提问
