### ISSUE TITLE
手动识别

### ISSUE THREAD

**Issue by tert6789yh12** [jxxghp/nas-tools#1467]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 
>2.1
> 环境: docker or windows or synology
群晖套件版
## 你想要新增或者改进什么功能？
手动识别增加识别成功反馈
> 你想要新增或者改进什么功能？
并且反馈识别成功后可以直接进行下一个
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
你个图吧，不知道说啥
