### ISSUE TITLE
演员信息豆瓣无法识别

### ISSUE THREAD

**Issue by tert6789yh12** [jxxghp/nas-tools#1468]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.1
>
> 环境: synology

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
豆瓣识别演员信息全部识别不出来，能不能改成之前的TMDB识别
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
仔细研究清楚设置吧
