### ISSUE TITLE
请求订阅电影时，增加副标题筛选功能

### ISSUE THREAD

**Issue by rockhia** [jxxghp/nas-tools#147]
现在新出的大片翻译效果相对较差，期望能出较好的字幕或者特效字幕后，再下载。
因此请求在订阅电影的时候，可以输入包含条件，对RSS副标题的信息进行筛选。
例如包含“特效字幕”，则当副标题有相关信息后，才命中进行下载，避免下载一些观感体验差的电影。
![Screenshot_20220522_141259_com kevinforeman nzb360_edit_163126537882920](https://user-images.githubusercontent.com/90016652/169681809-d10d845c-e04a-4bc8-8213-349fb079da2b.jpg)

**Comment by jxxghp** [comment]
已经支持了

**Comment by rockhia** [comment]
大佬说的已经支持地地方应该是设置站点的时候可以进行条件设置吧。
但是如果我在这里的包含里面增加了“特效字幕”会导致这个站点的国产电视剧无法命中吧！
![Screenshot_20220522_155411](https://user-images.githubusercontent.com/90016652/169684821-f6a7eab6-bd80-47ef-ba1c-1191d254e052.jpg)

**Comment by jxxghp** [comment]
资源搜索 右上角按钮旁边的小按钮
站点订阅 右上角按钮旁边的小按钮

**Comment by rockhia** [comment]
我期望是非特效字幕的电影不下载。
站点订阅那里应该是优选条件，如果没有特效字幕的电影出来了，也会自动下载。
![Screenshot_20220522_182927_com kevinforeman nzb360](https://user-images.githubusercontent.com/90016652/169691021-4495971b-bfd3-447e-b2e9-69ef0d68c81c.jpg)
