### ISSUE TITLE
新版RSS识别问题,之前一直正常订阅自动下载的,更新后RSS识别出现问题

### ISSUE THREAD

**Issue by ati121** [jxxghp/nas-tools#1475]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.2  978b64b5
>
> 环境: docker

之前版本一直是正常订阅自动下载.今天发现几部动漫都没自动更新.就看了下日志..发现RSS识别出问题.拿其中2个举例
dou luo da lu S01E229 2018 2160p WEB-DL H265 AAC-ADWeb 
![99](https://user-images.githubusercontent.com/72114654/194712692-d0a1c414-df18-4d23-ba9b-5f83d1ad2158.jpg)
![92](https://user-images.githubusercontent.com/72114654/194712766-e79014cf-e44a-4a17-97c6-22b712aa6065.jpg)

Noumin Kanren no Skill Bakka Agetetara Naze ka Tsuyoku Natta S01E02 2022 1080p B-Global WEB-DL x264 AAC-AnimeS@ADWeb
![66](https://user-images.githubusercontent.com/72114654/194712900-be1e7a5b-84b2-4628-a6f6-71f01db10db9.jpg)
![63](https://user-images.githubusercontent.com/72114654/194712907-93d45659-d354-4806-9612-220ce20cf02f.jpg)

这应该是把副标题也识别到主标题里面了吗?

**Comment by jxxghp** [comment]
这个是哪个站的资源？貌似是触发了之前的Bug，用[]把副标题包到RSS标题中的，会被错误截位。

**Comment by ati121** [comment]
> 这个是哪个站的资源？貌似是触发了之前的Bug，副标题里含国漫/新番这些动漫字样的就会被错误截位。

观众的
