### ISSUE TITLE
希望能适配PT速递网站，目前不能正确下载。

### ISSUE THREAD

**Issue by aviton** [jxxghp/nas-tools#1476]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: V2.2
>
> 环境: 威联通docker
>

## 你遇到什么问题了？

> 设置了私有站点PT速递（https://pt.msg.vg/index.php），搜索没有问题，但是点击自动下载，总是提示：添加下载失败 下载种子文件出现异常：not a valid bencoded string，可能站点Cookie已过期或触发了站点首次种子下载！但是Cookie并没有过期，也不是首次下载，其他私有站点没有问题。可能是站点适配问题。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 无

## 你期望的结果

> 希望能正确下载。

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
[nas-tools-stdout---supervisor-8kuojdfk.log](https://github.com/jxxghp/nas-tools/files/9739526/nas-tools-stdout---supervisor-8kuojdfk.log)
[run.txt](https://github.com/jxxghp/nas-tools/files/9739527/run.txt)

**Comment by Lolicon-A** [comment]
https://pt.soulvoice.club/
这个网站突然也这样了 2.3.0版本
