### ISSUE TITLE
希望增加对动漫的支持

### ISSUE THREAD

**Issue by qingahan** [jxxghp/nas-tools#1478]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 最新版本
> 环境: docker or windows or synology

## 你想要新增或者改进什么功能？

> 希望在目前电影，电视剧订阅分类之外增加动漫分类，在不同订阅分类之中使用不同的过滤规则，在rss订阅与搜索订阅使用的是当前分类的过滤规则，而不是目前搜索和订阅使用同一套规则，方便下载到自己需要的资源，同时希望能够在推荐列表中增加一个新番推荐列表

## 这个功能有什么可以参考的资料吗？
无

**Comment by jxxghp** [comment]
说的太模糊了

**Comment by qingahan** [comment]
> 说的太模糊了

简单来说就是希望增加一个动漫订阅分类，而不是目前和电视剧一起使用同一个分类。然后不同的分类订阅下载时希望可以使用不同的过滤规则，订阅电影时使用的是电影过滤规则，订阅动漫时使用的是动漫过滤规则。这样订阅下载电影和动漫的时候过滤规则就不会互相干扰。我目前是对每个每个动漫的订阅手动设置过滤规则，这样就有点麻烦
然后就是如果可以的话希望在推荐中增加季度新番列表，方便每个季度订阅新番
