### ISSUE TITLE
连接tmmb报os错误

### ISSUE THREAD

**Issue by qqwas** [jxxghp/nas-tools#148]
不是所有的都报错，部分报错，甚至从tmmb拿到id来手动识别，也有部分会报这个错。
14:47:20 INFO - 【META】正在查询TMDB：78132 ...
14:47:24 - ('Connection aborted.', OSError(22, 'Invalid argument'))
14:47:46 INFO - 【META】正在查询TMDB：78132 ...
14:47:49 - ('Connection aborted.', OSError(22, 'Invalid argument'))

**Comment by jxxghp** [comment]
检查下代理的配置

**Comment by qqwas** [comment]
网页访问tmmb是正常的

**Comment by qqwas** [comment]
17:43:41 - ('Connection aborted.', OSError(22, 'Invalid argument'))
用网页查出id然后用nastool手动，依然报错

**Comment by qqwas** [comment]
17:56:17 - HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/414906?api_key=8788fc2612c72e2817333517c5c213ff&append_to_response=videos,trailers,images,casts,translations,keywords,release_dates&language=zh-CN (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16c95373a0>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by jxxghp** [comment]
没遇到过，试下把配置删了，通过页面重新配置

**Comment by qqwas** [comment]
试过了，还是一样
能不能加个调试，把和tmmb连接的信息打印出来

**Comment by jxxghp** [comment]
可以确认的是目前没有发现类似问题，应该是配置原因，自己研究下吧。
