### ISSUE TITLE
fix #1475 好像还是会识别到副标题

### ISSUE THREAD

**Issue by ati121** [jxxghp/nas-tools#1483]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.2
>
> 环境: docker 
Noumin Kanren no Skill Bakka Agetetara Naze ka Tsuyoku Natta S01E02 2022 1080p KKTV WEB-DL x264 AAC-AnimeS@ADWeb
![9](https://user-images.githubusercontent.com/72114654/194734283-5f709533-3ac0-46e3-add1-2d6939492ded.jpg)

**Comment by jxxghp** [comment]
包括中文起贴出来吧，别只贴一半

**Comment by ati121** [comment]
主标题:Noumin Kanren no Skill Bakka Agetetara Naze ka Tsuyoku Natta S01E02 2022 1080p KKTV WEB-DL x264 AAC-AnimeS@ADWeb 
副标题:2022年10月新番 点满农民相关技能后，不知为何就变强了。 / 農民関連のスキルばっか上げてたら何故か強くなった。 第02集 *内封简繁软字幕*

**Comment by jxxghp** [comment]
![image](https://user-images.githubusercontent.com/51039935/194783703-b066b1d7-774b-450d-8963-e2b933276e3d.png)
![image](https://user-images.githubusercontent.com/51039935/194783763-d2cb6013-9aec-4f0b-97fb-82591e8d3faf.png)

应该可以了，再试试
