### ISSUE TITLE
群晖更新到最新版本怎么打不开了呢   修复了也提示无法启动

### ISSUE THREAD

**Issue by liuwqq** [jxxghp/nas-tools#1488]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by zhushu11** [comment]
我也遇到了一样的问题，因为都配置好了，也不敢随便卸载重装

**Comment by jxxghp** [comment]
套件的问题在群里艾特矿神或者群下大佬吧，我解决不了

**Comment by tabris233** [comment]
我是docker版本 刚刚更新了 v2.2.0，然后就打不开 web 页面了。

但看 run.txt 还是有日志的。

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/29500388/194776277-346a72b0-2665-4ea9-bf79-a171a1eb0ae8.png">

**Comment by jxxghp** [comment]
具了解，需要先安装python 3.10，套件的更新日志中有写。

![image](https://user-images.githubusercontent.com/51039935/194869118-369b3772-c49a-49df-93b0-3255317c0e3f.png)
