### ISSUE TITLE
群晖套件更新2.2.0-3后无法启动无法修复

### ISSUE THREAD

**Issue by zhushu11** [jxxghp/nas-tools#1489]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>2.2.0-3
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> 描述一下你遇到的问题
通过套件中心更新到最新版本后显示无法启动，点击修复后仍然无法启动
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
未找到类似答案

## 你期望的结果

> 描述以下你期望的结果
修复问题，正常使用
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
<img width="1440" alt="截屏2022-10-09 21 00 49" src="https://user-images.githubusercontent.com/114567896/194758265-b822e041-5627-4cad-b685-2f57d9bef939.png">

**Comment by jxxghp** [comment]
#1488
