### ISSUE TITLE
求个支持DSM7的版本

### ISSUE THREAD

**Issue by darkz1984** [jxxghp/nas-tools#15]
求个支持DSM7的版本， 或者能否告知如何生成7版本的包

**Comment by baozaodetudou** [comment]
你可以用 docker 或者自己安装 python3后台运行脚本

**Comment by cicai1631** [comment]
同求一个7的

**Comment by baozaodetudou** [comment]
https://github.com/jxxghp/nas-tools/wiki/%E7%BE%A4%E8%BE%89pm2%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B 可以曲线救国

**Comment by jxxghp** [comment]
有会dsm7的，帮忙打个包

**Comment by liuxiaoleo** [comment]
是啊，如果有dsm7的就好了。实在不想搞那个“电影机器人”。
