### ISSUE TITLE
请求添加新功能

### ISSUE THREAD

**Issue by Soff-X** [jxxghp/nas-tools#150]
请求添加选项功能 电影下载目录不区分外语国语  统一在电影目录下·
请求添加自动重命名中文功能
请求添加推荐列表年份月份筛选排序功能
请求添加订阅过滤规则

**Comment by log-time** [comment]
电影目录分类可以自定义的，config文件夹下的default-category.yaml了解下
自动重命名中文功能是啥意思？现有的方案不就是硬链后改名吗？
订阅过滤规则也已经有了，订阅管理-订阅站点-新增站点旁边的那个按钮点下试试？
