### ISSUE TITLE
资源搜索存在bug

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#1507]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker 

> 描述一下你遇到的问题
美剧：特殊病人 第一季 第1-3集 在chd上，CHD官组明明存在4k资源，然而nastools只能搜索到1080p

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
无

> 描述以下你期望的结果
能够正确搜索

## 给出程序界面截图、后台运行日志或
![IMAGE 2022-10-10 19:52:25](https://user-images.githubusercontent.com/39802246/194860390-97e156d1-6814-455e-a5bf-94416d4c5b59.jpg)
配置文件

**Comment by git-0101** [comment]
![Screenshot_20221010_233927](https://user-images.githubusercontent.com/115487446/194905363-7c45ae36-2164-4a4d-abdb-b24fbc54128c.jpg)
