### ISSUE TITLE
删除一个电视剧订阅后，页面已经不显示，但是日志和消息中心在报错

### ISSUE THREAD

**Issue by feixu0530** [jxxghp/nas-tools#151]
删除风骚律师的订阅后，日志和消息中心一直在报错：
【DB】执行SQL出错
SELECT COUNT(1) FROM RSS_TORRENTS WHERE TITLE='Better Call Saul Presents: Slippin' Jimmy' AND YEAR='2022' AND SEASON='S06' AND EPISODE='E06'，near "Jimmy": syntax error

但是页面上的订阅管理-电视剧订阅内已经不显示该订阅了

**Comment by jxxghp** [comment]
这是因为标题有个单引号导致，最新的代码已经修复，更新一下重启。

**Comment by feixu0530** [comment]
谢谢！会再观察一下。
