### ISSUE TITLE
希望针对私有站点和公开站点的下载能配置不同的下载方式

### ISSUE THREAD

**Issue by huzilaoge** [jxxghp/nas-tools#1515]
### **你使用的 NASTool 是什么版本，什么环境？**

---

> NASTool 版本: v2.2.1
> 环境: docker

### **你想要新增或者改进什么功能？**

---

> 
> 希望针对私有站点和公开站点的下载能配置不同的下载方式。
> 比如同样的电视剧订阅，假如我是使用自己PT私有站点自动搜索到的，肯定是走某个PT做种文件夹然后硬链接或者复制之类的。然后开启做种。
> 但是假如是公开站点BT搜索到的，我想要使用另外一个文件夹下载，这个文件夹就是类似吸血那种，使用转移方式不做种，最好QB那边也有不同的标签控制。
> 像这种需求现在有什么办法能解决吗？

**Comment by luoxiao-xy** [comment]
确实，希望可以对BT公开站点设置不做种。下载了基本都是吸血，特别是某雷不停的吸。

**Comment by jxxghp** [comment]
已支持
