### ISSUE TITLE
下载器分类设置无效

### ISSUE THREAD

**Issue by yujianhui21** [jxxghp/nas-tools#1516]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1 16adaeca
>
> 环境: docker
>

## 你遇到什么问题了？

> qbittiorrent 不能进行分类管理，就是设置下载分类，无效，会在未分类里面

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 看过了，没有，记得之前的版本就可以设置下载分类

## 你期望的结果

> 添加下载会自动分类，并且自动选择自动Torrent管理，这样配置好分类就可以自动根据类型下载到对应分类的文件夹，然后根据目录同步进行自动同步到对应的硬链接的文件夹
## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/58041488/194916276-d3668513-2c03-41ff-a943-bd998b5b37e4.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by git-0101** [comment]
1.目前可以设置qbittorrent为手动管理模式可以让这里的设置路径生效。
2.想要qbittorrent自动管理，还要下到这里的设置目录。根据你的截图，可以设置qbittorrent默认下载地址为：/downloads/PT/。

**Comment by sjtuross** [comment]
我配置了电影和电视，但在前端只显示一条。另外，我并不指定具体下载目录，而是由QB分类决定。访问目录也不设置的，因为我是用目录同步功能的。这些在v2,2,1之前都是正常工作的

```
  # 下载文件保存路径，传递给下载器使用
  save_path:
    movie: '|radarr'
    tv: '|sonarr'
    anime: ''
```
![image](https://user-images.githubusercontent.com/940110/194986042-fe6ad686-35bd-42ee-85ec-daab93db4bd2.png)

**Comment by jxxghp** [comment]
由于较多人对于标签的作用理解不清，最新的程序都需要填写目录，且会强制QB为手工管理模式。

如不填写保存目录，则会使用QB的默认下载目录。

**Comment by jxxghp** [comment]
配置文件已经不用下载器下的了，在单独的配置项下。

**Comment by sjtuross** [comment]
下载目录我可以重复填一下，希望不会影响QB后续分类目录的转移。但强制QB为手工模式是为何？

**Comment by sjtuross** [comment]
较多人对于标签的作用理解不清，那不要用标签不就行了？个人觉得原来的设计挺好的

**Comment by jxxghp** [comment]
> 下载目录我可以重复填一下，希望不会影响QB后续分类目录的转移。但强制QB为手工模式是为何？

只是当前种子是手工模式，不然就会生效标签，有的人qb里没维护分类标签，发现跟自己填的目录对不上又认为是bug。

只要有标签就会传给qb，应该不会影响的，可以试试看。

**Comment by sjtuross** [comment]
刚刚试了一下，分类没有传过去，目录也没生效，下载到了默认目录了，生效的貌似只有手工模式

**Comment by jxxghp** [comment]
> 刚刚试了一下，分类没有传过去，目录也没生效，下载到了默认目录了，生效的貌似只有手工模式

目录设置堆个图看看

**Comment by sjtuross** [comment]
![image](https://user-images.githubusercontent.com/940110/194991480-6463f14a-d71e-45cf-b96f-87bb8254d153.png)

**Comment by jxxghp** [comment]
![image](https://user-images.githubusercontent.com/51039935/194991841-f57780b1-94b0-43cc-ad57-4152c24acc6c.png)
![image](https://user-images.githubusercontent.com/51039935/194991926-14725041-cb70-4369-ba05-7c020c3b3dc6.png)
![image](https://user-images.githubusercontent.com/51039935/194991968-c7952a22-7018-4384-90c3-6715da0f8d3f.png)

没有问题

**Comment by sjtuross** [comment]
访问目录也一定要填吗？标签你那边传过去了吗？

![image](https://user-images.githubusercontent.com/940110/194992269-57f88674-6299-4dbc-9a97-00367cc248f2.png)

**Comment by jxxghp** [comment]
> 访问目录也一定要填吗？标签你那边传过去了吗？
> 
> ![image](https://user-images.githubusercontent.com/940110/194992269-57f88674-6299-4dbc-9a97-00367cc248f2.png)

图2左上角的红框就是标题正确归类的。我在QB设置不改成自动模式也不影响，都是正常传递的。

**Comment by sjtuross** [comment]
设置了访问目录后正常了

**Comment by sjtuross** [comment]
另外能否考虑加个设置或开关，把种子设置成自动模式呢？否则影响到后续的分类迁移

**Comment by sjtuross** [comment]
感觉为了考虑一些用户对于标签的作用理解不清，损失了本可自动化的功能

**Comment by git-0101** [comment]
标签功能挺好的。这就是相当于分类。自动与否在qbittorrent设置就行。前面我给的思路，和作者的一样。自动管理模式下，qbittorrent默认下载路径设置成你要下载到的分类目录的上级目录就可以了。自动管理模式下，如果qbittorrent默认下载路径设置成其它的目录，它就会在这个目录下自动建立分类目录了。

**Comment by git-0101** [comment]
![Screenshot_20221011_103027](https://user-images.githubusercontent.com/115487446/194994427-7b0ba76e-0907-4d4f-a400-304d124a598b.jpg)
这版更新还有一个好处就是这个界面会按NasTool下载目录设置按顺序排列，非常整齐。之前版本探索到在qb里自己设置的分类，整个排序毫无规则，非常乱。

**Comment by sjtuross** [comment]
分类目录未必在默认目录下的，这样相当于限制了QB使用

**Comment by sjtuross** [comment]
现在的问题并不是不支持QB分类，而是

1. 下载目录和访问目录变成必填项，否则就下载到了默认目录无分类
2. 添加的种子默认不再是自动模式

**Comment by git-0101** [comment]
你可以qbittorrent设置自动管理模式，然后nt里下载设置个分类Movie,下载个资源，点自动下载看看是否在qb默认下载目录里会出现这个Movie文件夹。

**Comment by sjtuross** [comment]
会啊，QB默认就是这样的，不设置分类目录，默认就在默认目录之下建目录

但是跟现在的问题有什么关系呢？

**Comment by jxxghp** [comment]
> 设置了访问目录后正常了。我是用目录同步功能，不用QB监控变化的，这个访问目录没用吧？以前我只要设置一个分类就行了，现在要重复设置一堆冗余的目录

不想设置，你不升级不就行了

**Comment by jxxghp** [comment]
> 设置了访问目录后正常了。我是用目录同步功能，不用QB监控变化的，这个访问目录没用吧？以前我只要设置一个分类就行了，现在要重复设置一堆冗余的目录

所以现在的问题就是除了要设置标签，现在还要多设置一下标签对应的目录，还有其它问题吗？如果觉得多设置个目录很困难，你可以不升级。

**Comment by jxxghp** [comment]
我没理解为什么会影响文件迁移

**Comment by sjtuross** [comment]
设置冗余的目录也无所谓了，手工模式下，如果改了分类，QB不会自动转移到对应的目录

**Comment by git-0101** [comment]
所以设置个标签对应目录也很容易，然后自动下载选择还整齐根据自己的从上到下设置的标签排序多好多整齐。

**Comment by sjtuross** [comment]
也是，不过我怀疑下载目录和访问目录在代码里是否搞反了？否则提这个问题的人咋不行呢？

**Comment by jxxghp** [comment]
> 也是，不过我怀疑下载目录和访问目录在代码里是否搞反了？否则提这个问题的人咋下载到了默认目录呢？而且我刚刚也是填了访问目录之后才正常了

这个应该就是我说的旧程序的问题吧，他设了标签，但是QB里并没有建分类，QB是自动模式不用我传的下载目录了。这样的情况之前有很多，这次干脆改掉。

**Comment by sjtuross** [comment]
能否改成这样，填了下载目录则手动模式，不填则自动模式？

**Comment by jxxghp** [comment]
> 能否改成这样，填了下载目录则手动模式，不填则自动模式？

好像也可以，我改下

**Comment by git-0101** [comment]
之前版本试过不设置路径，只设置标签，在自动下载旁边的选项中会出现一个“.”，这个点选择后下载到了qb设置的默认下载路径。

**Comment by sjtuross** [comment]
@jxxghp 感谢做了这个逻辑上的改动，但是下载目录配置界面还有点问题，就是如果不填保存目录，设置无法保存或者丢失

**Comment by YanceyWang** [comment]
> downloaddir:
>   /media/bt/tvshow/:
>     type: 电视剧
>     category: ''
>     path: ''
>     label: tvshow
>   /media/bt/movie/:
>     type: 电影
>     category: ''
>     path: ''
>     label: movie

@sjtuross  这个 save_path 和 access_path 的区别是啥？
