### ISSUE TITLE
对于特定影视telegram通知失效

### ISSUE THREAD

**Issue by Earendil-C** [jxxghp/nas-tools#1524]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1 637f43c2
>
> 环境: docker
>

## 你遇到什么问题了？

> 对于特定影视下载转移会产生通知错误：发送消息失败：未获取到返回信息。同时绝大部分其他影视不会导致该错误，问题在同一个电视剧上可以复现。如番剧 前进吧！登山少女 Next Summit

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是，不确定#1301 是否遇到同样的问题

## 你期望的结果

> 修复通知bug，辛苦开发大大！

## 给出程序界面截图、后台运行日志或配置文件

> ![photo_2022-10-11_11-11-47](https://user-images.githubusercontent.com/55442093/194988817-07e7e3ee-6519-4b41-a53a-b088f33da411.jpg)

**Comment by jxxghp** [comment]
跟这个应该是相同问题 #1301
