### ISSUE TITLE
搜索建议

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#1525]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker 

> 你想要新增或者改进什么功能？

站点维护这里有可能添加个制作组啥的么
已便在nastools里搜索想要的组别资源
![578D9DC7-0186-43B4-95C8-3C565904B0D8](https://user-images.githubusercontent.com/39802246/194991667-310c8c1a-4b63-4480-a365-7c1ef4cb34a4.jpeg)

（主要是想只搜索和下载官组资源，好顺便保种）

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Tartarus2014** [comment]
![6E5BE7A5-94C6-4971-AB7D-2697E3B1AE4A](https://user-images.githubusercontent.com/39802246/194991919-4d88d734-132e-4a81-b3ab-0b26653e905b.png)

现在会搜索全部资源，不知道能否加个制作组限制限制，以便只搜索想要的组别资源

**Comment by jxxghp** [comment]
站点跟制作组有啥关系，要搜特定制作组的资源，在高级搜索里，自定义 那个框填制作组的名字
