### ISSUE TITLE
希望匹配信息可以根据TMDBID和电视剧订阅里面TMDBID进行匹配而不是只根据名字

### ISSUE THREAD

**Issue by pikaqiu2222** [jxxghp/nas-tools#1526]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1
>
> 环境: docker or windows or synology

12:07:51 INFO - 【RSS】[爱恋&漫猫字幕组] 名侦探柯南 零的日常/Detective Conan: Zero no Tea Time (01-06Fin WEBRIP 1080p AVC AAC 2022年4月 繁中) 识别为 名侦探柯南：零的日常 (2022) S01 E01 不在订阅范围 
其实这种识别信息都识别出来了，应该是有tmdbid了，如果可以直接和订阅里面电视剧直接匹配TMDBID进行下载，这样可以忽略名字上的差异进行匹配

**Comment by jxxghp** [comment]
看代码了吗，就是通过TMDBID匹配的啊
