### ISSUE TITLE
关于部分影片搜索时 显示“查询不到媒体信息，请确认名称是否正确！”

### ISSUE THREAD

**Issue by cnsilvan** [jxxghp/nas-tools#1527]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 灵异侦缉档案 查询不到媒体信息，请确认名称是否正确！

根据查询代码发现查询该影片最后会调用
https://github.com/jxxghp/nas-tools/blob/637f43c2ee07c81f9f40f44db0db86d78915f55a/app/media/media.py#L299
```
request:
https://api.themoviedb.org/3/search/tv?api_key=xxx&language=zh-CN&query=灵异侦缉档案&page=1&first_air_date_year=2003
response:
{
	"page": 1,
	"results": [
		{
			"backdrop_path": "/dsgmRxagw3moztWdv5kQaA4goYG.jpg",
			"first_air_date": "",
			"genre_ids": [
				80,
				9648
			],
			"id": 93143,
			"name": "灵异侦缉档案",
			"origin_country": [
				"HK"
			],
			"original_language": "zh",
			"original_name": "靈異偵緝檔案",
			"overview": "在一次危险的任务中，叶胜辉（陶大宇 饰）开枪误伤了一名无辜的女学生，这场意外令叶胜辉的事业跌落了谷底，不仅如此，他的精神亦走到了濒临崩溃的边缘。上司将叶胜辉送往了心理医生李嘉雯（李珊珊 饰）处接受心理治疗，对于出现在叶胜辉身边的种种诡异事件，李嘉雯只当它们全都是叶胜辉的幻觉。  　　叶胜辉被调到了古董仓工作，在那里，有一颗摆放了二十五年无人认领的人头，当死者的弟弟江文杰远道而来认领尸首时，道出了此案和曾经的灭门惨案之间千丝万缕的关联，所有的矛头都指向了一位名叫陈石的男人。之后，当叶胜辉重新来到灭门惨案发生现场之时，震惊的发现，自己竟然获得了能够看到鬼魂的特殊能力",
			"popularity": 1.803,
			"poster_path": "/pKeLTj84R6tlcOvL0K7HhGO0SW9.jpg",
			"vote_average": 0,
			"vote_count": 0
		}
	],
	"total_pages": 1,
	"total_results": 1
}
```
这里因为TMDB未返回first_air_date
导致continue跳过了。
我没仔细看其他代码，只是有个疑问，模式为normal是否应该直接返回这个唯一的结果。
或者官方希望采取什么策略 我可以pr

**Comment by jxxghp** [comment]
目前的策略，对于从豆瓣等过来的数据，是会按年份匹配的，有没有年份的直接返回也有问题，遇到很多都是同样的名字有年份和没年份的同时存在，如果这样就可能会返回错误的匹配了。
这个情况有两种方式：
1、去TMDB上补一下信息，方便自己也方便别人，可能不是实时生效的，要等。
2、把豆瓣的开关关掉，用TMDB的数据就没这个问题了。

**Comment by cnsilvan** [comment]
> 目前的策略，对于从豆瓣等过来的数据，是会按年份匹配的，有没有年份的直接返回也有问题，遇到很多都是同样的名字有年份和没年份的同时存在，如果这样就可能会返回错误的匹配了。 这个情况有两种方式： 1、去TMDB上补一下信息，方便自己也方便别人，可能不是实时生效的，要等。 2、把豆瓣的开关关掉，用TMDB的数据就没这个问题了。

谢谢 了解了
