### ISSUE TITLE
重命名格式增加HDR和Dolby Vision

### ISSUE THREAD

**Issue by codomo8848** [jxxghp/nas-tools#1530]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.1.1
>
> 环境: synology

> 你想要新增或者改进什么功能？
同一部电影同一个分辨率可能下了好几个版本，所以希望能够自动重命名识别高动态范围HDR和Dolby Vision的选项，添加{hdr}重命名格式，和非HDR的影片能够区分开。

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
比如：xxx.2022.2160p.HDR.mkv 能够自动重命名为: xxx(2022) - 2160p HDR.mkv

**Comment by jxxghp** [comment]
#1660
