### ISSUE TITLE
【BUG】无法识别4k分辨率动漫标题

### ISSUE THREAD

**Issue by lowking** [jxxghp/nas-tools#1534]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1 d241224
>
> 环境: pve
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
无法识别动漫花园《诛仙》这部动漫的4k资源
名称：
[GM-Team][国漫][诛仙][Jade Dynasty][2022][11][HEVC][GB][4K]
[GM-Team][国漫][诛仙][Jade Dynasty][2022][12][AVC][GB][1080P]

## 你期望的结果

> 描述以下你期望的结果
能正常识别下载4k资源

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/33308659/195112447-4fc51ecb-ac3a-4797-bcbc-d5bda29d692e.png)
只要取消选中4k就可以正常下载1080p的
输出了下媒体的resource_pix参数，发现是None
![image](https://user-images.githubusercontent.com/33308659/195113004-48267b62-8d2e-452a-9268-03ed634945c2.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by lowking** [comment]
跟踪完发现是```app/media/meta/metaanime.py```
```
anitopy_info = anitopy.parse(title)
```
转换标题的时候无法识别上面4k的标题
```
>>> anitopy.parse('[GM-Team][国漫][诛仙][Jade Dynasty][2022][11][HEVC][GB][1080p]')
{'file_name': '[GM-Team][国漫][诛仙][Jade Dynasty][2022][11][HEVC][GB][1080p]', 'video_resolution': '1080p', 'video_term': 'HEVC', 'anime_year': '2022', 'episode_number': '11', 'anime_title': 'Jade Dynasty', 'release_group': 'GM-Team'}
>>> anitopy.parse('[GM-Team][国漫][诛仙][Jade Dynasty][2022][11][HEVC][GB][4K]')
{'file_name': '[GM-Team][国漫][诛仙][Jade Dynasty][2022][11][HEVC][GB][4K]', 'video_term': 'HEVC', 'anime_year': '2022', 'episode_number': '11', 'anime_title': 'Jade Dynasty', 'release_group': 'GM-Team'}
```

**Comment by Shurelol** [comment]
如果只是解决使用，可以添加替换词`(?<=\[)4K(?=\])@2160P`，或者在过滤规则中排除1080P
![image](https://user-images.githubusercontent.com/16237201/195216918-9e08507d-80e0-44ed-a9af-e0f084afe970.png)
