### ISSUE TITLE
新微信代理测试失败

### ISSUE THREAD

**Issue by aiwu12** [jxxghp/nas-tools#1535]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1
>
> 环境: docker or windows or Synology
>docker Synology

## 你遇到什么问题了？
![image](https://user-images.githubusercontent.com/61082200/195119885-6195c598-a03f-4f66-a64a-8ff082fe0747.png)

> 之前使用旧版微信代理地址没有问题，今晚更改新代理测试失败，其他人也反馈失败，是否还需要修改其他地方？

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
看日志写啥

**Comment by aiwu12** [comment]
> 看日志写啥

ERROR - 【MSG】发送消息失败：参数未配置或配置不正确,只修改了代理地址其他均未修改

**Comment by jxxghp** [comment]
![image](https://user-images.githubusercontent.com/51039935/195216889-48805028-7574-4864-adf7-c47744afd0f5.png)
