### ISSUE TITLE
删除源文件以后，硬连接和历史记录自动删除。

### ISSUE THREAD

**Issue by aerosmith2020** [jxxghp/nas-tools#1537]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1
>
> 环境: synology

## 你想要新增或者改进什么功能？
删除源文件以后，硬连接和历史记录自动删除。

## 这个功能有什么可以参考的资料吗？
hlink 修剪功能

**Comment by aerosmith2020** [comment]
从qb删除源文件以后，硬连接所在文件夹 和 历史记录 一并删除

**Comment by link2fun** [comment]
清理软连接的还差不多, 清硬链接的话 为何不直接用软连接

**Comment by jxxghp** [comment]
特别不能理解为什么要把媒体库跟保种绑定在一起。

硬链接又不会多占用多少空间，媒体库的目的是观影和收藏，我不想要的通过媒体管理软件删掉，要的保留。下载的保种我能保多少尽量保，不能保了就批量删掉一些，但并不需要花太多精力去关注啊。媒体库中的影片海报墙、观影才是核心呀。

为什么要通过源文件来反向管理媒体库的硬链接？那用这个软件的意义是啥。。。不还在一样的花心思关注那些下载文件吗？

**Comment by aerosmith2020** [comment]
> 清理软连接的还差不多, 清硬链接的话 为何不直接用软连接

我同意这样做，确实违背硬连接的存在的意义（文件安全+链接指向同一个inode）。不管是硬和软，其实我就想实现这么一个功能：_目录同步_实现”真“单向同步，即源目录和nastool整理好的目标目录“真”同步。比如，如果源目录被删掉，目标目录所在**文件夹**也被删掉（包括nfo. jpge.等）

**Comment by aerosmith2020** [comment]
> 有二个可行的逻辑： 一个是类似与hlink的正向修剪。 另外一个是，设置好nastool媒体库联动jellyfin/emby以后，如果nastool检测到源文件 xxx(2022) 被删除，通过jellyfin api，告诉jellyfin删除该电影/电视剧 xxx(2022)文件夹



> 特别不能理解为什么要把媒体库跟保种绑定在一起。
> 
> 硬链接又不会多占用多少空间，媒体库的目的是观影和收藏，我不想要的通过媒体管理软件删掉，要的保留。下载的保种我能保多少尽量保，不能保了就批量删掉一些，但并不需要花太多精力去关注啊。媒体库中的影片海报墙、观影才是核心呀。
> 
> 为什么要通过源文件来反向管理媒体库的硬链接？那用这个软件的意义是啥。。。不还在一样的花心思关注那些下载文件吗？

**Comment by aerosmith2020** [comment]
> 特别不能理解为什么要把媒体库跟保种绑定在一起。
> 
> 硬链接又不会多占用多少空间，媒体库的目的是观影和收藏，我不想要的通过媒体管理软件删掉，要的保留。下载的保种我能保多少尽量保，不能保了就批量删掉一些，但并不需要花太多精力去关注啊。媒体库中的影片海报墙、观影才是核心呀。
> 
> 为什么要通过源文件来反向管理媒体库的硬链接？那用这个软件的意义是啥。。。不还在一样的花心思关注那些下载文件吗？

作者大大，我突然懂了你的意思，体会到了这个软件真正的意义。媒体库与保种分开，确实是更正确的方向。谢谢你。
