### ISSUE TITLE
媒体库中电视剧的目录无法删除

### ISSUE THREAD

**Issue by diao597576613** [jxxghp/nas-tools#1545]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1 e8ff590
>
> 环境: docker or windows or Synology
>Synology套件版

## 你遇到什么问题了？

> 描述一下你遇到的问题
媒体库中电视剧的目录有一个始终无法删除，疯狂点x会闪烁一下但是还是无法删除，新建其他目录就可以删除
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/58315346/195334901-b8fd6404-c741-431e-838f-853e2eb6f14a.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
手动改配置文件删

**Comment by diao597576613** [comment]
> 手动改配置文件删

q求问大哥配置文件在哪

**Comment by diao597576613** [comment]
> 

找到了，改好了，感谢大哥
