### ISSUE TITLE
UI遮挡

### ISSUE THREAD

**Issue by git-0101** [jxxghp/nas-tools#1548]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1
>
> 环境: docker
>

发现UI遮挡

> 
![Screenshot_20221012_234628](https://user-images.githubusercontent.com/115487446/195392993-0d49d9cd-76a9-419d-818a-641af0513247.jpg)

**Comment by jxxghp** [comment]
应该是屏幕太小的原因，不好处理
