### ISSUE TITLE
存储空间 无法获取

### ISSUE THREAD

**Issue by AuroraFrowned** [jxxghp/nas-tools#156]
Linux Centos7 PM2启动
存储空间 0TB
无法获取

**Comment by jxxghp** [comment]
存储空间是从媒体库目录读的，确保媒体库目录已配置，且目录正确

**Comment by AuroraFrowned** [comment]
> 确保媒体库目录已配置，且目录正确

目录配置正确 发现是GoogleDrive无法获取有效使用空间 已解决
