### ISSUE TITLE
qBittorrent 下载完成后转移文件出错，路径组装错误，报文件不存在

### ISSUE THREAD

**Issue by EkkoG** [jxxghp/nas-tools#1561]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1
>
> 环境: docker
>

## 你遇到什么问题了？

> qBittorrent 下载完成后转移文件出错，路径组装错误，报文件不存在

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的

## 你期望的结果

> 正确组装路径并转移

## 给出程序界面截图、后台运行日志或配置文件

qBittorrent 下载路径 /downloads/

qBittorrent 下载路径在 nas-tool 中的位置 /nas-media/downloads/

以下两个文件一个成功组装了路径并转移成功，另一个路径中没有前缀 /nas-media/downloads/ 报文件不存在

> 10:41:27 INFO - 【RMT】开始处理：/nas-media/downloads/How To Train Your Dragon The Hidden World (2019) [WEBRip] [1080p] [YTS.AM]，转移方式：硬链接
10:41:27 INFO - 【RMT】正在转移文件：How.To.Train.Your.Dragon.The.Hidden.World.2019.1080p.WEBRip.x264-[YTS.AM].mp4 到 /nas-media/movies/动画电影/驯龙高手3 (2019)/驯龙高手3 (2019) - 1080p.mp4
10:41:27 INFO - 【RMT】文件 How.To.Train.Your.Dragon.The.Hidden.World.2019.1080p.WEBRip.x264-[YTS.AM].mp4 硬链接完成
10:41:27 INFO - 【Meta】正在查询TMDB电影：166428 ...
10:41:29 INFO - 【Message】发送telegram消息：title=驯龙高手3 (2019) 转移完成, text=评分：7.8，类型：电影，类别：动画电影，质量：WEBRip 1080p，大小：1.59G，来自：Qbittorrent
10:41:30 INFO - 【Emby】开始刷新Emby媒体库...
10:41:30 INFO - 【RMT】/nas-media/downloads/How To Train Your Dragon The Hidden World (2019) [WEBRip] [1080p] [YTS.AM] 处理完成，总数：1，失败：0
10:41:30 INFO - 【SUBTITLE】开始从Opensubtitle.org检索字幕: How To Train Your Dragon The Hidden World
10:41:30 ERROR - 【SUBTITLE】未找到浏览器内核，当前环境无法检索opensubtitles字幕！
10:41:30 INFO - 【SUBTITLE】How To Train Your Dragon The Hidden World 未检索到字幕
10:41:30 INFO - 【DownloaderType.QB】设置qBittorrent种子状态成功
10:41:30 INFO - 【RMT】开始处理：/The King's Speech (2010) [BluRay] [1080p] [YTS.AM]，转移方式：硬链接
10:41:30 ERROR - 【RMT】文件转移失败，文件不存在：/The King's Speech (2010) [BluRay] [1080p] [YTS.AM]
10:41:30 WARN - 【DOWNLOADER】/The King's Speech (2010) [BluRay] [1080p] [YTS.AM] 转移失败：文件不存在
10:41:30 INFO - 【DownloaderType.QB】设置qBittorrent种子状态成功

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Earendil-C** [comment]
v2.2.1 50bec658遇到同样问题

**Comment by jxxghp** [comment]
更新一下程序，早上有个PR解决了：2a7aa37aa5cf248e65f1fd31a1afead0d2ed15bd

**Comment by EkkoG** [comment]
> 更新一下程序，早上有个 PR 解决了：2a7aa37aa5cf248e65f1fd31a1afead0d2ed15bd

应该不是同一个问题，2a7aa37aa5cf248e65f1fd31a1afead0d2ed15bd 解决的是用错路径

现在是用的路径名是对的，只是少了前缀

可以对比日志和种子信息
![CleanShot 2022-10-13 at 15 59 51](https://user-images.githubusercontent.com/3138493/195538263-4c5cd876-f6fa-40f3-9b75-517d648519dd.png)

The King's Speech (2010) [BluRay] [1080p] [YTS.AM] 确实是文件存放的路径，不是种子名字了

**Comment by Earendil-C** [comment]
> > 更新一下程序，早上有个 PR 解决了：2a7aa37aa5cf248e65f1fd31a1afead0d2ed15bd
> 
> 应该不是同一个问题，2a7aa37aa5cf248e65f1fd31a1afead0d2ed15bd 解决的是用错路径
> 
> 现在是用的路径名是对的，只是少了前缀
> 
> 可以对比日志和种子信息 ![CleanShot 2022-10-13 at 15 59 51](https://user-images.githubusercontent.com/3138493/195538263-4c5cd876-f6fa-40f3-9b75-517d648519dd.png)
> 
> The King's Speech (2010) [BluRay] [1080p] [YTS.AM] 确实是文件存放的路径，不是种子名字了

发现了，你看看你的下载目录是不是没有斜杠，例如我的/home/downloads转移失败，而/home/downloads/就转移成功了

**Comment by EkkoG** [comment]
下载目录打斜杠会在 https://github.com/jxxghp/nas-tools/blob/50bec658f9ca3551fbb385b9fb1e3733256169e1/app/downloader/client/client.py#L153 normpath 时去掉

根本原因是在 https://github.com/jxxghp/nas-tools/blob/50bec658f9ca3551fbb385b9fb1e3733256169e1/app/downloader/client/qbittorrent.py#L141 这里得到的 trans_name 会以 / 开头，这样在后续的 join 时就会出错，例子如下

>/nas-media/downloads/ /Be.Melodramatic.S01.KOREAN.WEBRip.x264-ION10
{'path': '/Be.Melodramatic.S01.KOREAN.WEBRip.x264-ION10', 'id': 'b95cc3a9580565c5c7303882fa825d0f26d030fc'}
/nas-media/downloads/ An Elephant Sitting Still (2018) [BluRay] [1080p] [YTS.LT]
{'path': '/nas-media/downloads/An Elephant Sitting Still (2018) [BluRay] [1080p] [YTS.LT]', 'id': '28578671d5e855f173072f1a5abc13b976003537'}

开头没有斜杠的就正常，有斜杠的就出错了，已提 PR 修复

**Comment by EkkoG** [comment]
trans_name 是不以斜杠开关由 save_path 决定，而 save_path 最后是不返回斜杠是不确定的，所以才导致了这个问题
