### ISSUE TITLE
希望增加对远程挂载盘（局域网NAS）的监控支持

### ISSUE THREAD

**Issue by Nothend** [jxxghp/nas-tools#1565]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1 50bec658
>
> 环境: PVE下LXC的Docker环境

## 你想要新增或者改进什么功能？

> 1.首先感谢作者这么好的工具，真是好用的很。
  2.我的环境是这样的，一个软路由（PVE环境下），里面的LXC安装了dokcer环境，NASTool就安装在这里。
  3.局域网中有一个Windows版本的NAS，里面smb协议共享了一个文件夹。
  4.LXC通过远程挂载，把Windows的共享文件夹挂载进了LXC。
  5.LXC中安装docker，然后再安装NASTool，可以使用Windows的共享文件夹。
  6.但是目录无法自动同步。根据小秘书的常见问题，设置了相关命令也不行
        `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
    echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
  sudo sysctl -p`

 7.其中第六步，我是在PVE的环境下输入的命令。按道理我这里NASTool的宿主是LXC，可是在LXC环境下，提示权限不足，但是我本身就是root权限。
 8.希望大佬能对这个问题考虑考虑，谢谢！

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by sjtuross** [comment]
据我所知，网络共享是不支持inotify的，只能期望nas-tool主动调用媒体服务器接口触发扫描

**Comment by Nothend** [comment]
> 据我所知，网络共享是不支持inotify的，只能期望nas-tool主动调用媒体服务器接口触发扫描

好的，明白了，就是系统层面不支持

**Comment by jxxghp** [comment]
非windows的smb协议局域网共享是支持的，我目前就是一台nas smb共享到另一台linux实现监控。

windows smb共享到linux不行。nfs共享不行。

**Comment by jxxghp** [comment]
windows nas的话，配置文件里面有一个隐藏的配置nas_sys我没有开放，你可以改一下应该也能监控，但是效率很差。

**Comment by Nothend** [comment]
> 非windows的smb协议局域网共享是支持的，我目前就是一台nas smb共享到另一台linux实现监控。
> 
> windows smb共享到linux不行。nfs共享不行。

谢谢提供这么重要的信息，我是windows 共享的，确实不行，有机会试试Linux 或者truenas

**Comment by ihnic** [comment]
> 非windows的smb协议局域网共享是支持的，我目前就是一台nas smb共享到另一台linux实现监控。
> 
> windows smb共享到linux不行。nfs共享不行。

大佬，你的nas是群晖还是其他？ 目前我的是群晖，不支持
