### ISSUE TITLE
希望删除订阅可以同步删除源文件

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#1566]
希望历史识别页面删除订阅可以删除源文件

如果emby里面删除订阅能同步删除历史识别里面的记录和源文件就更好了。

大佬，辛苦

**Comment by link2fun** [comment]
有没有一种可能, 我是说 剧集完播后 这个订阅会消失
你是想一完结 不管你看没看 都给你全删了么

**Comment by thsrite** [comment]
> 有没有一种可能, 我是说 剧集完播后 这个订阅会消失
> 你是想一完结 不管你看没看 都给你全删了么

不是。是有的不想看了想删除。
现在需要emby或者nastool历史识别里面删除硬链后的文件，再去tr或qb删除源文件。

**Comment by thsrite** [comment]
因为要保种，所以选择的硬链接方式。

但是有些实在不想看或者下载其他版本的时候，就要把之前的删除。
希望删除硬链接文件的时候可以删除源文件。

**Comment by thsrite** [comment]
至于tr或qb里面的做种，可以定期手动删除。
如果也能同步删除就再方便不过了

**Comment by link2fun** [comment]
参见 https://github.com/jxxghp/nas-tools/issues/1537

这功能基本不会做, 跟硬链接意义违背, 你这种建议你用软连接, 你下载器删完之后手动清理失效软连接就行

**Comment by jxxghp** [comment]
实现比较复杂，还涉及是否在做种的情况，暂时不会考虑。
