### ISSUE TITLE
save_path 和 save_container_path 的作用是啥？

### ISSUE THREAD

**Issue by YanceyWang** [jxxghp/nas-tools#1567]
https://github.com/jxxghp/nas-tools/blob/c63d500939f40f8ca141d65634f796e4921919b1/app/downloader/client/client.py#L143

看这段代码，如果save_path 和 传入的path相同，就返回 container_path?

**Comment by link2fun** [comment]
save_path = 下载器下载用的保存目录
container_path =  转移用的目录

**Comment by YanceyWang** [comment]
@link2fun 
在这里设置了save_path 和 container_path
https://github.com/jxxghp/nas-tools/blob/41bb46c3d5ae1d5fe4c15de44535ed2b1b8f4857/web/templates/setting/downloader.html#L299

转移目录不是这里设置的吗？这两个不一样吧，我理解错了？
https://github.com/jxxghp/nas-tools/blob/50bec658f9ca3551fbb385b9fb1e3733256169e1/web/templates/setting/library.html#L37

**Comment by link2fun** [comment]
> 移目录不是这里设置的吗？这两个不一样吧，我理解错了

container_path 和资源库里面 的 movie_path 都是nastools容器内的目录
Downloader 里面的 save_path 是nastools 容器外的目录
save_path 和 container_path 应该是为了做 下载转移的, 因为下载器里面的路径跟 nastools 里面的路径可能不一致 所以需要转换
不知道你在纠结啥
