### ISSUE TITLE
下载器使用Qbittorrent，下载管理无法打开

### ISSUE THREAD

**Issue by firstvip** [jxxghp/nas-tools#157]
请教一下大佬
我下载器使用的是Qbittorrent，目录配置如图1
Nastools中设置目录如图2，测试也成功了。
但是点击下载管理无法打开
哪位好心能给指点一下吗！

**Comment by firstvip** [comment]
![Uploading 107A9A9D-122F-470E-B687-C6A4033FE4ED.png…]()

**Comment by firstvip** [comment]
![微信图片_20220523000737](https://user-images.githubusercontent.com/41404652/169705361-cc838576-1686-474c-9e8c-0b5e503e1253.png)
1

**Comment by firstvip** [comment]
![微信图片_20220523000726](https://user-images.githubusercontent.com/41404652/169705378-5ba9cbab-49c0-4696-b9e8-91d100adb873.png)
2

**Comment by firstvip** [comment]
![微信图片_20220523000733](https://user-images.githubusercontent.com/41404652/169705389-64431d45-bbf2-4c28-87df-abb739249d91.png)

**Comment by jxxghp** [comment]
下载管理打不开，一般是QB连不上，排查下环境跟地址端口配置

**Comment by jxxghp** [comment]
可以进群求助一下看看，那个群我已经不在了，即将退出，实在是没有太多精力。
