### ISSUE TITLE
如果可能，能出一个把视频的音频转成其他格式的功能吗？

### ISSUE THREAD

**Issue by KevinZjYang** [jxxghp/nas-tools#1570]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>V2.2.1
> 环境: docker or windows or synology
truenas scale应用中环境拉取docker镜像创建

## 你想要新增或者改进什么功能？

> 如果可能，能出一个把视频的音频转成其他格式的功能吗？
经常下载的视频音频格式是EAC3的，电视不能直接播放，需要转码。如果能在加一个功能，在发现音频格式是指定的格式时，在后台开启转码，转码结束后再转移。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
没有，也不知道能不能实现，只是遇到这个问题，就提出来了。

**Comment by link2fun** [comment]
jellyfin emby plex 换个媒体播放软件吧

**Comment by KevinZjYang** [comment]
> jellyfin emby plex 换个媒体播放软件吧

我买的emby，但是实时转码不好使。I5 10500的CPU。所以想要个在闲置情况下自动转好的。

**Comment by link2fun** [comment]
> > jellyfin emby plex 换个媒体播放软件吧
> 
> 我买的emby，但是实时转码不好使。I5 10500的CPU。所以想要个在闲置情况下自动转好的。

刚看了 emby 有自动转换的功能 可以实现你说的功能 你直接emby 客户端 长按媒体库 选择转换就行
转换为 选替换还是生成新版本你自己看
配置选择自定义 custom
音频编码选 aac 或mp3
最后有一个 自动转换新内容  你给勾上 就行了
over
