### ISSUE TITLE
Bark通知存在bug

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#1573]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1 50bec658
>
> 环境: docker 

## 你遇到什么问题了？

> 描述一下你遇到的问题
bark存在不通知情况

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
无

> 描述以下你期望的结果
正确获取到通知

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
20:16:36 INFO - 【RSS】共有 1 个电影订阅需要检索
20:16:36 INFO - 【Meta】正在查询TMDB电影：372343 ...
20:16:36 INFO - 【SEARCHER】开始检索 The Snowman ...
20:16:36 INFO - 【Indexer】开始检索 The Snowman，站点：['hhanclub'] ...
20:16:36 INFO - 【Indexer】开始检索Indexer：hhanclub ...
20:16:38 WARN - 【Indexer】hhanclub 返回数据：1
20:16:38 INFO - 【Meta】The Snowman 识别到 电影：TMDBID=372343, 名称=雪人, 上映日期=2017-10-12
20:16:38 INFO - 【Indexer】The Snowman 2017 1080p AMZN WEB-DL DDP5.1 H264-HHWEB 官方WEB中字雪人/雪中罪(港)/The Snowman | 类型:剧情/悬疑/惊悚/犯罪 | 主演:迈克尔法斯宾德/丽贝卡弗格森/詹姆斯达西/科洛塞维尼/方基默 识别为 雪人 (2017) 匹配成功
20:16:38 INFO - 【Indexer】hhanclub 共检索到 1 条数据，过滤 0，不匹配 0，有效资源 1，耗时 2 秒
20:16:38 INFO - 【Indexer】所有站点检索完成，有效资源数：1，总耗时 2 秒
20:16:38 INFO - 【DOWNLOADER】添加下载任务：The Snowman 2017 1080p AMZN WEB-DL DDP5.1 H264-HHWEB ...
20:16:44 INFO - 【DOWNLOADER】添加下载任务：The Snowman 2017 1080p AMZN WEB-DL DDP5.1 H264-HHWEB，目录：/downloads/，Url：https://hhanclub.top/download.php?id=2965
20:16:44 INFO - 【Message】发送bark消息：title=雪人 (2017) 评分：5.2, text=RSS订阅的电影 雪人 (2017) 已开始下载 站点：hhanclub 质量：WEB-DL 1080p 大小：4.34G 种子：The Snowman 2017 1080p AMZN WEB-DL DDP5.1 H264-HHWEB 做种数：35 促销：免费 描述：官方WEB中字雪人/雪中罪(港)/The Snowman | 类型:剧情/悬疑/惊悚/犯罪 | 主演:迈克尔法斯宾德/丽贝卡弗格森/詹姆斯达西/科洛塞维尼/方基默
20:16:45 ERROR - 【Message】发送消息失败：未获取到返回信息
20:16:45 INFO - 【SEARCHER】实际下载了 1 个资源
20:16:45 INFO - 【RSS】电影 雪人 下载完成，删除订阅...

**Comment by torgelee** [comment]
我发现是消息中如果有/就会出问题，例如这个“NHL 2022-2023 / RS / 13.10.2022 / Washington Capitals @ Toronto Maple Leafs [Hockey, WEB-DL HD/720p/60fps, MKV/H.264, EN/NBCSWA]”
