### ISSUE TITLE
下载文件后触发自动转存失败，但是目录同步功能可正常使用

### ISSUE THREAD

**Issue by HolyDumpling** [jxxghp/nas-tools#1577]
## 你使用的 NASTool 是什么版本，什么环境？
> NASTool 版本: Docker jxxghp/nas-tools:v2.2.1 50bec658
> qbittorrent 版本: Docker linuxserver/qbittorrent:14.3.9
> 设备环境: 威联通TS262C
> Docker路径映射:
>> NASTool :
>>>  /HdMedia : /share/HdMedia
>> 
>> qbittorrent:
>>>  /HdMedia : /share/HdMedia
>> 

## 你遇到什么问题了？
> qBittottent下载文件后触发自动转存失败，但是目录同步功能可正常使用

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
> 已浏览Issues，未找到相关记录

## 你期望的结果
> 下载自动转存功能正常工作

## 给出程序界面截图、后台运行日志或配置文件
复现步骤如下：
1. 下载器目录配置如下：
![下载器完整路径](https://user-images.githubusercontent.com/32377323/195626079-b330ec00-c8e1-47de-b53d-97eeccca6326.png)
2. 媒体库路径配置如下：
![媒体库路径设置](https://user-images.githubusercontent.com/32377323/195626577-cfe7b414-2cd8-4ade-9aee-771fec52fe73.png)
3. 基础设置信息配置如下：
![基础设置信息](https://user-images.githubusercontent.com/32377323/195627516-a0b6d757-e91c-4a5f-a491-49e91e1f37fb.png)
4. 添加下载任务，等待下载完成
5. 触发下载转存，查看日志如下：
![触发下载转存报路径错误](https://user-images.githubusercontent.com/32377323/195627828-ec7f183d-e10c-4cf5-a8b4-546557f03068.png)
6. 保持各项配置不变，新建“目录同步”选项：
![目录同步配置项](https://user-images.githubusercontent.com/32377323/195628059-0745fd00-b5b4-46a9-b831-e0c1c48ede61.png)
7. 服务——手动执行“目录同步”任务
8. 查看日志，硬链接可正常创建：
![其他信息不变，配置目录同步，服务-手动执行“目录同步”成功](https://user-images.githubusercontent.com/32377323/195628271-5f2e6970-ba25-4906-b203-2cb797c3e669.png)
9. 附录日志文件如下：
[nas-tools-stdout---supervisor-_2riqgo_.log](https://github.com/jxxghp/nas-tools/files/9777865/nas-tools-stdout---supervisor-_2riqgo_.log)

**Comment by jxxghp** [comment]
Movie的访问目录为什么不填？

**Comment by HolyDumpling** [comment]
> Movie的访问目录为什么不填？

![uTools_1665675119718](https://user-images.githubusercontent.com/32377323/195640873-69e0f5e7-4c34-472a-9537-063357dfa661.png)
下载器中“电影”分类的访问路径在第一张图中已经填写。“未分类”的访问路径未写，但是与此无关，已尝试删除第一张图中“未分类”这一行，下载后依然报路径错误

**Comment by HolyDumpling** [comment]
附录日志：
23:25:12 INFO - 【Meta】The Butcher the Chef and the Swordsman 识别到 电影：TMDBID=58679, 名称=刀见笑, 上映日期=2011-03-17
23:25:15 INFO - 【DOWNLOADER】添加下载任务：The Butcher the Chef and the Swordsman 2010 GER BluRay 1080p x265 DTS-HD MA 5.1-CarPT，目录：/HdMedia/Download/Video/Movie/，Url：https://carpt.net/download.php?id=14721
23:25:20 INFO - 【Message】发送iyuu消息：title=刀见笑 (2011) 评分：5.3, text=WEB搜索的电影 刀见笑 (2011) 已开始下载 站点：车 质量：BluRay 1080p 大小：5.6G 种子：The Butcher the Chef and the Swordsman 2010 GER BluRay 1080p x265 DTS-HD MA 5.1-CarPT 做种数：27 促销：免费
23:30:50 INFO - 【DOWNLOADER】开始转移下载文件...
23:30:50 INFO - 【RMT】开始处理：/[刀见笑]The.Butcher.the.Chef.and.the.Swordsman.2010.GER.BluRay.1080p.x265.DTS-HD.MA.5.1-CarPT.mkv，转移方式：硬链接
23:30:50 ERROR - 【RMT】文件转移失败，文件不存在：/[刀见笑]The.Butcher.the.Chef.and.the.Swordsman.2010.GER.BluRay.1080p.x265.DTS-HD.MA.5.1-CarPT.mkv
23:30:50 WARN - 【DOWNLOADER】/[刀见笑]The.Butcher.the.Chef.and.the.Swordsman.2010.GER.BluRay.1080p.x265.DTS-HD.MA.5.1-CarPT.mkv 转移失败：文件不存在
23:30:50 INFO - 【DownloaderType.QB】设置qBittorrent种子状态成功
23:30:50 INFO - 【DOWNLOADER】下载文件转移结束

**Comment by Always67** [comment]
遇到了同样问题，最后怎么解决的？
