### ISSUE TITLE
剧集刮削，每集产生的nfo文件，无法正确链接到trakt

### ISSUE THREAD

**Issue by xuanqb** [jxxghp/nas-tools#1580]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1 b4e9715
>
> 环境: Synology-docker

## 你遇到什么问题了？

> 使用ns刮削剧集时，每集会产生一个nfo文件，在emby中可以直接链接到trakt同步观影记录，但是现在产生的全是错误的链接，现在只能取消emby中使用本地nfo的选项，让emby自己刮削，才能生成正确的trakt链接

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 没有此类型的问题

## 你期望的结果

> 希望能正常链接到trakt

## 给出程序界面截图、后台运行日志或配置文件
<img width="905" alt="image" src="https://user-images.githubusercontent.com/25526210/195637450-a2bb0ff9-33a2-4d27-a260-7e666a9c80db.png">
[emby自己刮削的能正常识别](https://trakt.tv/search/imdb/tt19363126)

<img width="768" alt="image" src="https://user-images.githubusercontent.com/25526210/195639050-ce9f25ef-2dda-40d5-9393-0a3c0ee8d7a9.png">
[使用本地nfo文件就有问题](https://trakt.tv/search/tmdb/135312?id_type=episode)

**Comment by jxxghp** [comment]
DEV偿试修复了，更新后试试

**Comment by xuanqb** [comment]
刚刚试了下，有imdbid的可以正确链接到trakt了 。但是有的剧集只有tmdbid，还是有问题的。这块应该是没有比较好的解决方式了，要是在nfo文件中不生成tmdbid/imdbid是不是就没有这个问题了？
