### ISSUE TITLE
站点访问问题

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#1581]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker 

> 你想要新增或者改进什么功能？
大部分PT网站在国内因为特殊原因无法直连访问。在open clash等一系列代理软件中，部分站点访问地址和tracker又一样，没法在代理软件中为pt访问单独添加分流。是否可以为PT站点访问也开启代理服务器，或者和现有的代理服务器拆开，单独新增加一个PT站访问代理。

**Comment by JJJDand** [comment]
+1，内置搜索和查看站点资源不是每次都能成功，需要重复多次，希望能给站点访问单独设置代理

**Comment by jxxghp** [comment]
代理挂外面不行吗

**Comment by Tartarus2014** [comment]
> 代理挂外面不行吗
很多站点tracker和网址是相通的。。。
