### ISSUE TITLE
新增加的自定义识别词有概率性会导致config文件损坏

### ISSUE THREAD

**Issue by Aqr-K** [jxxghp/nas-tools#1582]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1 e8ff590f
>
> 环境: docker
>

## 你遇到什么问题了？

> 部分动漫的字幕组是纯英文或者后面有招聘公告，会导致识别错误，在进行自定义识别词设定时，突然间web就打不开了
portainer日志显示INFO exited错误，循环请求各个pid
通过进入容器ssh使用python run.py后，发现提升”config文件严重损坏“
在查看config文件后就剩下这一点内容了，只能删出config文件重新生成容器默认config
在重新生成配置后，重新按照原来的进行配置又没有出现这个状况，这次查看config是完整的

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 

## 你期望的结果

> 描述以下你期望的结果

![image](https://user-images.githubusercontent.com/95741669/195695229-16780dab-e020-4700-9dcf-f915e8f52b52.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
已改为数据库存储
