### ISSUE TITLE
网页交互响应有BUG

### ISSUE THREAD

**Issue by sleikang** [jxxghp/nas-tools#1585]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1
>
> 环境: windows
>

索引是自带索引，所有公开站点全部选中，浏览器用的EDGE
直接搜索比如（海贼王），会出现无限制搜索，经过调试测试发现网页前端点击后如果短时间没有完成会无限制重复触发响应，等于第一次还没搜索完成然后就触发了下次搜索请求，如果是结果响应快就没事

**Comment by jxxghp** [comment]
不会吧

**Comment by sleikang** [comment]
> 不会吧

![image](https://user-images.githubusercontent.com/23020770/195814303-c6e6d2d5-0b02-47b5-82ab-631f597f06ce.png)
我只点了一次搜索，然后一直在反复搜索，进度条会一直开始结束 开始结束

**Comment by sleikang** [comment]
![image](https://user-images.githubusercontent.com/23020770/195816045-0f902d83-480e-42c4-a391-885cf222230f.png)
只要不点其他位置关闭这个搜索进度窗口，一会儿就搜索了上百次了

**Comment by jxxghp** [comment]
无法重现
