### ISSUE TITLE
无法正常监控transmission

### ISSUE THREAD

**Issue by BCYDTZ** [jxxghp/nas-tools#1586]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>v2.2.1 fe946e3e
> 环境: docker or windows or Synology
>Synology  docker

## 你遇到什么问题了？
无法正常监控transmission
> 描述一下你遇到的问题
无法正常监控transmission，添加下载以后，nas-tools正在下载里面看不到数据，空白,并且设置里面开启下载软件监控以后，transmission下载完成以后，nas-tools并没有获取到，不执行媒体整理
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
正常监控transmission
## 给出程序界面截图、后台运行日志或配置文件
Transmission 版本：3.00 (bb6b5a062e), RPC: 16, WEB Control: 1.6.1(20200913）
nas-tools：v2.2.1 fe946e3e
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
#1558

不任何有助于分析的数据
