### ISSUE TITLE
OpenSubtitles字幕下载提示找不到浏览器内核，无法下载

### ISSUE THREAD

**Issue by evakenshin** [jxxghp/nas-tools#1587]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1
>
> 环境: windows 
>

## 你遇到什么问题了？

> 提示为找到浏览器内核，无法下载
![2022-10-14 10 06 45](https://user-images.githubusercontent.com/13158959/195750306-cd55e81b-3eb9-47cf-ad6e-0c6315ee66bb.jpg)

**Comment by link2fun** [comment]
发版说明都不看的么?
![image](https://user-images.githubusercontent.com/19241982/195752454-cf098c12-16a9-4735-928c-38b6a2fe3d75.png)

**Comment by git-0101** [comment]
设置，实验室，打开仿真游览器试试

**Comment by evakenshin** [comment]
> 发版说明都不看的么? ![image](https://user-images.githubusercontent.com/19241982/195752454-cf098c12-16a9-4735-928c-38b6a2fe3d75.png)

没看懂这段要怎么做？从新下载然后重制所有设置？   
而且这个我也是昨天才下的windows版本安装的呀。

**Comment by jxxghp** [comment]
裙晖套件和windows没有
