### ISSUE TITLE
原盘格式电影硬链接后出现多个文件夹

### ISSUE THREAD

**Issue by lyk1988** [jxxghp/nas-tools#1588]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1 aabae2bf
>
> 环境: docker for Qnap 
>

## 你遇到什么问题了？

>原盘格式电影硬链接后出现多个文件夹

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是，和BDMV格式转移失败那个lssues相似，但我的不是合集原盘

## 你期望的结果

> 得到解决办法

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及
![微信截图_20221014143319](https://user-images.githubusercontent.com/115774774/195781384-f0fd97f7-bb19-4bb6-9102-8683526420d1.png)

![微信截图_20221014143309](https://user-images.githubusercontent.com/115774774/195781370-ffe828df-f403-497e-bf66-6d7fb8cc9be5.png)
配置文
![微信截图_20221014143021](https://user-images.githubusercontent.com/115774774/195781359-9fc676a0-802d-49d8-9daa-eb88b8b9f897.png)
件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
![微信截图_20221014142556](https://user-images.githubusercontent.com/115774774/195781346-240b0b7c-143f-4848-bc06-39697f10ef93.png)

**Comment by lyk1988** [comment]
还有就是下载所有原盘电影时，刚开始下载就全部识别成一个叫M.V.的电影
15:29:07 INFO - 【SYNC】开始转移监控目录文件...
15:29:07 INFO - 【RMT】开始处理：/download/VIDEO/The.Lord.of.the.Rings.The.Fellowship.of.the.Ring.2001.Extended.UHD.BluRay.2160p.HEVC.TrueHD.Atmos.7.1-BeyondHD/LOTR_FELLOWSHIP_OF_THE_RING_P1/BDMV/STREAM，转移方式：硬链接
15:29:07 WARN - 【RMT】文件 /download/link/video/外语电影/M.V. (1978)/M.V (1978).m2ts 已存在
15:29:07 INFO - 【RMT】/download/VIDEO/The.Lord.of.the.Rings.The.Fellowship.of.the.Ring.2001.Extended.UHD.BluRay.2160p.HEVC.TrueHD.Atmos.7.1-BeyondHD/LOTR_FELLOWSHIP_OF_THE_RING_P1/BDMV/STREAM 处理完成，总数：1，失败：1
15:29:07 INFO - 【SYNC】开始转移监控目录文件...
15:29:07 INFO - 【RMT】开始处理：/download/VIDEO/The.Lord.of.the.Rings.The.Fellowship.of.the.Ring.2001.Extended.UHD.BluRay.2160p.HEVC.TrueHD.Atmos.7.1-BeyondHD/LOTR_FELLOWSHIP_OF_THE_RING_P2/BDMV/STREAM，转移方式：硬链接
15:29:07 INFO - 【RMT】文件 /download/link/video/外语电影/M.V. (1978)/M.V (1978).m2ts 已存在，覆盖...
15:29:07 INFO - 【RMT】正在删除已存在的文件：/download/link/video/外语电影/M.V. (1978)/M.V (1978).m2ts
15:29:07 INFO - 【RMT】正在转移文件：00073.m2ts 到 /download/link/video/外语电影/M.V. (1978)/M.V (1978).m2ts
15:29:07 INFO - 【RMT】文件 00073.m2ts 硬链接完成
15:29:08 INFO - 【META】正在查询TMDB电影：502739 ...
15:29:08 INFO - 【MSG】发送wechat消息：title=M.V. (1978) 转移完成, text=类型：电影，类别：外语电影，大小：74.92G，来自：目录同步，1个文件已存在
15:29:08 INFO - 【EMBY】开始刷新Emby媒体库...
15:29:08 INFO - 【EMBY】Emby媒体库刷新完成
15:29:08 INFO - 【RMT】/download/VIDEO/The.Lord.of.the.Rings.The.Fellowship.of.the.Ring.2001.Extended.UHD.BluRay.2160p.HEVC.TrueHD.Atmos.7.1-BeyondHD/LOTR_FELLOWSHIP_OF_THE_RING_P2/BDMV/STREAM 处理完成，总数：1，失败：0
15:29:08 INFO - 【SUBTITLE】通知ChineseSubFinder下载字幕: /download/link/video/外语电影/M.V. (1978)/M.V (1978).m2ts
15:29:08 INFO - 【SYNC】开始转移监控目录文件...
15:29:08 INFO - 【RMT】开始处理：/download/VIDEO/The.Lord.of.the.Rings.The.Two.Towers.2002.EXTENDED.COMPLETE.UHD.BLURAY-BOREDOR/Disc2/BDMV/STREAM，转移方式：硬链接
15:29:08 WARN - 【SUBTITLE】ChineseSubFinder下载字幕出错：physical video file not found
15:29:08 WARN - 【RMT】文件 /download/link/video/外语电影/M.V. (1978)/M.V (1978).m2ts 已存在
15:29:08 INFO - 【RMT】/download/VIDEO/The.Lord.of.the.Rings.The.Two.Towers.2002.EXTENDED.COMPLETE.UHD.BLURAY-BOREDOR/Disc2/BDMV/STREAM 处理完成，总数：1，失败：1
15:29:08 INFO - 【SYNC】开始转移监控目录文件...
15:29:08 INFO - 【RMT】开始处理：/download/VIDEO/The.Lord.of.the.Rings.The.Two.Towers.2002.EXTENDED.COMPLETE.UHD.BLURAY-BOREDOR/Disc1/BDMV/STREAM，转移方式：硬链接
15:29:08 WARN - 【RMT】文件 /download/link/video/外语电影/M.V. (1978)/M.V (1978).m2ts 已存在
15:29:08 INFO - 【RMT】/download/VIDEO/The.Lord.of.the.Rings.The.Two.Towers.2002.EXTENDED.COMPLETE.UHD.BLURAY-BOREDOR/Disc1/BDMV/STREAM 处理完成，总数：1，失败：1

**Comment by jxxghp** [comment]
不支持原盘多层文件夹

**Comment by jxxghp** [comment]
#1502
不要重复开问题
