### ISSUE TITLE
为站点索引下载限速

### ISSUE THREAD

**Issue by nicholastz** [jxxghp/nas-tools#1594]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1 1c8c26b4
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 1.为索引器中的某些公开站点设置上传下载限制，#有些时候会从索引器中命中订阅，可是上传跑满，下载均无速度
2.新功能【自定义识别词】每个规则增加编辑按钮

## 这个功能有什么可以参考的资料吗？

> 暂无

**Comment by jxxghp** [comment]
没这必要吧，自己下载器限啊
