### ISSUE TITLE
通过 IMDB id 在 TMDB 进行搜索而非名字

### ISSUE THREAD

**Issue by EkkoG** [jxxghp/nas-tools#1601]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1 32ff445
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 同步豆瓣「想看」并下载

## 这个功能有什么可以参考的资料吗？

> 目前是通过电影/电视剧的名字在 TMDB 进行查找，大部分时候工作的挺好，但是在一些翻译不一致时成功率会比较低

比如这个 https://movie.douban.com/subject/30442376/ 在 TMDB 是搜不到的

实际上用「我要准时下班」这个名字是搜得到的 https://www.themoviedb.org/search/tv?query=%E6%88%91%E8%A6%81%E5%87%86%E6%97%B6%E4%B8%8B%E7%8F%AD

TMDB 支持通过 IMDB id 进行查找，IMDB 可以在豆瓣网页里拿到，这样会比较精确，没有翻译不一致的问题，通过名字可以作为补充方法

TMDB API https://developers.themoviedb.org/3/find/find-by-id

**Comment by jxxghp** [comment]
douban的api如果有imdb就好了，不然还要抓网

**Comment by jxxghp** [comment]
貌似效果并不理由，查不到的还是查不到

**Comment by EkkoG** [comment]
这么快！我还在看代码怎么改您就做好了

我刚试了一下上文中的例子是可以拿到信息的，你是试了某个账号的数据得出的结论吗

ahh = Media().get_meida_by_imdbid('tt9657710')

{'adult': False, 'backdrop_path': '/l7dQcVIdzVMlkhUquzyKmW7Gr0r.jpg', 'id': 88646, 'name': '我要准时下班', 'original_language': 'ja', 'original_name': 'わたし、定時で帰ります。', 'overview': '东山结衣是一个32岁单身白领，因为过去的经历贯彻“到下班时间就回家”的理念，但她并非工作不努力，而是比其他人更努力更高效地完成工作，也更重视私生活，她在休息时间会享受美食，就像所有普通上班族一样。这项看似“我行我素”的原则，源于她曾经过度加班而牺牲健康的惨痛教训。虽然不加班的前提是在法定工作时间内高效有序地完成任务，但到点下班的东山还是不免遭到部长的质疑和责难。', 'poster_path': '/uO0awrVLDgmeBfaNGjBow876EOF.jpg', 'media_type': 'tv', 'genre_ids': [18], 'popularity': 5.396, 'first_air_date': '2019-05-14', 'vote_average': 6.917, 'vote_count': 6, 'origin_country': ['JP'], 'meida_type': <MediaType.TV: '电视剧'>}
