### ISSUE TITLE
多字幕只转移繁体字幕

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [jxxghp/nas-tools#1605]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1 3048e5a6
>
> 环境: Synology
>

## 你遇到什么问题了？

> 我在下载动漫时如果一集对应多个比如繁体和简体字幕时只会转移繁体字幕，无法两个字幕都转移并重命名

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已看过

## 你期望的结果

> 多个字幕时都能转移并重命名，最好能保留字幕自带的.tc或.sc这种后缀

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by SchrodingerBarbatos** [comment]
今天尝试别的动漫部分字幕又是转移的简体并且会有后缀，感觉字幕这块识别有困难，希望还是能有个手动转移重命名字幕的功能

**Comment by shenye0521** [comment]
赞成，同时希望使用官方推荐的命名格式([EMBY](https://support.emby.media/support/solutions/articles/44001159160-subtitles%EF%BC%8C)|[PLEX](https://support.plex.tv/articles/200471133-adding-local-subtitles-to-your-media/))，比如：将简体字幕从"xxxx.sc.ass"重命名为"xxxx.zh-CN.ass"，而不是pt站常见的"xxxx.chs.ass"，原因：照顾PLEX用户，PLEX不能正确识别到"sc.ass"和"chs.ass"，会识别为unknown(未知语言)，但是EMBY可以正常识别
