### ISSUE TITLE
老大，能加个微信搜索，遇到同名称，不同tmdb ID的电影，给出个选择，然后再下载。

### ISSUE THREAD

**Issue by 26712681** [jxxghp/nas-tools#161]
![image](https://user-images.githubusercontent.com/77581926/169741504-1a831838-397b-4cc2-a9f9-a0771fb993ba.png)

如图所示，搜索 “当男人恋爱时”关键字  会直接下载第一个，台湾的。  但是我想要的是第二个韩国的。  所以我后面又去豆瓣查了年代，然后又重新下载一次。  有点麻烦。

能不能遇到这种情况，微信直接回复一个消息：
遇到同名电影几部，请选择
1、台湾版、2017年上映，豆瓣评分6.5
2、韩国版、2014年上映，豆瓣评分7.5
3、美国版、2020年上映，豆瓣评分6.0

然后这个东西是个带链接的直接点也可以，或者我们再回复一条消息。  1 ，  2  这样

**Comment by jxxghp** [comment]
一直在考虑，只是还没空，等吧

**Comment by jxxghp** [comment]
v1.5.2
