### ISSUE TITLE
win版nastools在使用一段时间后会自动开启另一个nastools程序

### ISSUE THREAD

**Issue by nether13** [jxxghp/nas-tools#1610]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.2.1
> 
> 环境: windows
>

## 你遇到什么问题了？
nastools在使用一段时间后会自动开启另一个nastools程序，关闭其中一个会将所有打开的nastools全部关闭。

![image](https://user-images.githubusercontent.com/114297462/195934533-430232d8-4e1c-4cdd-b5a6-59ff28e8cb82.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是

## 你期望的结果
请问是程序BUG，还是本来就是这样的，比较小白还请解答一下，谢谢。

**Comment by Shurelol** [comment]
能否提供下出现多个nastool托盘时，任务管理器里nastool的进程截图

**Comment by nether13** [comment]
![image](https://user-images.githubusercontent.com/114297462/195969087-36b996f1-607b-4c91-a167-e77ad2c97a11.png)
