### ISSUE TITLE
（建议）希望在搜索界面增加快速切换下载器和索引器按钮的功能

### ISSUE THREAD

**Issue by solosing** [jxxghp/nas-tools#1619]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境: docker 

## 你想要新增或者改进什么功能？

> 希望在搜索界面增加快速切换下载器和索引器按钮的功能，因为个人在使用中常存在切换下载器的需求（比如习惯用qb下pt，tr下载bt），还有各个索引器对下载站点的支持不同，常想切换站点搜索，每次要去设置里面更改，比较繁琐，希望大神考虑。

**Comment by jxxghp** [comment]
个人习惯就fork过去自己改
