### ISSUE TITLE
windows里下载目录配置问题，访问目录如何填写其他盘符？

### ISSUE THREAD

**Issue by mdjs147** [jxxghp/nas-tools#1627]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本:v2.2.2
>
> windows 
>

## 你遇到什么问题了？

>windows电脑，其中Y盘和Z盘都为网络驱动器，本地qb会下载文件到Y盘里面（没有问题），但转移文件会提示文件不存在。之前版本（2.1.3）同样的配置情况下没有问题。

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
<img width="966" alt="屏幕截图 2022-10-15 182154" src="https://user-images.githubusercontent.com/5328294/195981463-a73138f7-79b4-4ca0-b4f8-c98e35011684.png">
<img width="1039" alt="屏幕截图 2022-10-15 182355" src="https://user-images.githubusercontent.com/5328294/195981465-2b2b8a21-19f6-494b-b65a-9f25c709f634.png">
<img width="547" alt="屏幕截图 2022-10-15 182425" src="https://user-images.githubusercontent.com/5328294/195981470-62bc44e1-83f6-497d-a44b-feecd217e8a1.png">
<img width="812" alt="屏幕截图 2022-10-15 182452" src="https://user-images.githubusercontent.com/5328294/195981472-07b5a862-6e91-4486-afc0-fa163f739d68.png">

**Comment by jxxghp** [comment]
直接输

**Comment by mdjs147** [comment]
图片就是直接输入的，但是转移提示找不到文件，之前版本没有问题
