### ISSUE TITLE
提一个建议

### ISSUE THREAD

**Issue by leo8912** [jxxghp/nas-tools#163]
关于国产综艺，有很多分part A,partB,plus等这类命名，与tmdb信息对不上。
所以在转移时是否可以考虑保留part这部分信息？下载时也在同一个站点追。这样在emby中还是可以选择播放的，追剧也不会漏集

**Comment by jxxghp** [comment]
现在支持part/disk/disc/dvd+数字，但不支持你说的这个综艺，这种国内综艺特色奇葩的命名不打算支持了。

**Comment by leo8912** [comment]
> 现在支持part/disk/disc/dvd+数字，但不支持你说的这个综艺，这种国内综艺特色奇葩的命名不打算支持了。

哦，看到支持加数字了，还可以考虑多加个abc
不过现在看，可能还是去pt站rss综艺比较简单。。。
