### ISSUE TITLE
无法通过 http://IP:3000  访问，只能通过http://localhost:3000/访问

### ISSUE THREAD

**Issue by FireGodson** [jxxghp/nas-tools#1632]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>2.2.2
> 环境: docker or windows or Synology
>windows

## 你遇到什么问题了？

> 描述一下你遇到的问题
无法通过 输入http://IP:3000  访问，只能通过安装服务的当前电脑 http://localhost:3000/访问，尝试把防火墙关了也不行
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是的
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
是的

## 你期望的结果

> 描述以下你期望的结果
希望能通过IP地址从其他电脑访问
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
![Snipaste_2022-10-15_21-01-33](https://user-images.githubusercontent.com/32048420/195987846-da66d04e-fe6b-44c7-bfab-b695ee06814d.png)

![Snipaste_2022-10-15_20-55-01](https://user-images.githubusercontent.com/32048420/195987878-2023b6a4-1a13-4ecf-89c7-433b7b80e57e.png)

**Comment by FireGodson** [comment]
不好意思，查看配置文件后，修改成0.0.0.0后解决

**Comment by yanggea** [comment]
> 不好意思，查看配置文件后，修改成0.0.0.0后解决

请问改哪里，我也是这个问题

**Comment by yanggea** [comment]
> 不好意思，查看配置文件后，修改成0.0.0.0后解决

搞定了，谢谢

**Comment by FireGodson** [comment]
才看到。。不用客气
