### ISSUE TITLE
分类需求希望添加

### ISSUE THREAD

**Issue by SmllXzBZ** [jxxghp/nas-tools#1634]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> synology

## 你想要新增或者改进什么功能？

> 在视频页面能否增加视频分类？比如电影能否增加类别：爱情，剧情，科幻等等，电视剧和动漫类似，希望能够分类查看视频

## 这个功能有什么可以参考的资料吗？

> 类似一些网站的视频分类，包括https://dandanzan.net/dianying/，类似这样

**Comment by link2fun** [comment]
视频界面是哪个界面

**Comment by SmllXzBZ** [comment]
推荐里面的TMDB最新电影/热门电影/热门电视剧等，这些能添加一个分类查看吗？
