### ISSUE TITLE
删除未完成的下载任务时，同步删除对应的同步目录

### ISSUE THREAD

**Issue by HinSIU** [jxxghp/nas-tools#1635]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境: synology

## 你想要新增或者改进什么功能？

>删除未完成的下载任务时，同步删除对应的同步目录

## 这个功能有什么可以参考的资料吗？

>无

**Comment by link2fun** [comment]
这是啥需求? 没下载完的? 没下载完的应该没同步啊?

**Comment by HinSIU** [comment]
> 这是啥需求? 没下载完的? 没下载完的应该没同步啊?

下载中的任务，查看历史记录是已经有同步操作了
![image](https://user-images.githubusercontent.com/98629603/195995847-8681dd4b-16ca-4803-a9bd-17c2d8ed3550.png)
![image](https://user-images.githubusercontent.com/98629603/195995870-3e29c991-6777-4c70-8e24-a3a6a6c15af7.png)
