### ISSUE TITLE
订阅的站点站点优先级未生效。

### ISSUE THREAD

**Issue by leo8912** [jxxghp/nas-tools#164]
订阅设置了站点优先级，但是并未生效，下载资源仍然是从观众下载的，这个片源质量也并没有比其他站点要符合优先规则。但是搜索时的排序就比较符合设定的优先级。订阅是走jackett的吗？但是换了顺序也没生效啊。。。
另外，这个搜索下载的，为什么通知提示的是动漫。。
![IMG_20220523_192538_986.jpg](https://user-images.githubusercontent.com/22719866/169809364-3704d9a2-8422-4175-81dc-c7f267d2a11b.jpg)
![IMG_20220523_192545_006.jpg](https://user-images.githubusercontent.com/22719866/169809705-2f4ae707-e7d0-435a-b443-b3460a38d8f7.jpg)
![IMG_20220523_192535_386.jpg](https://user-images.githubusercontent.com/22719866/169809721-11e41de2-7509-4246-b689-6cca2732b2c3.jpg)

![IMG_20220523_193232.jpg](https://user-images.githubusercontent.com/22719866/169810242-3f36a7f8-800a-4293-8a9f-4370a77c5c7c.jpg)

**Comment by jxxghp** [comment]
搜索是用的jackett，站点优先级要看你在Feeds里配置的顺序，同时站点优先级只是其中的一项优先级并不高。
优先级顺序：排除规则 包含规则 优先规则 站点顺序 做种数量，前提是总子名称规范能正确识别，不能识别的是不会出来的。
