### ISSUE TITLE
电视剧订阅点击后无反应

### ISSUE THREAD

**Issue by sently** [jxxghp/nas-tools#1646]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.2.2
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 在nastool中点击订阅管理中其他订阅均可以跳转页面，但是电视剧订阅转圈之后无法跳转

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是，已经搜索过

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by 757957414** [comment]
我也遇到这个问题了
![image](https://user-images.githubusercontent.com/23210825/196152985-9fdc7b52-cb9f-47d4-aee6-487c52ea06e9.png)

**Comment by KevinZjYang** [comment]
我也遇到了
![erro](https://user-images.githubusercontent.com/31529584/196157184-3f3f405e-c0c9-4954-a02e-9de640a4a4db.png)

![image](https://user-images.githubusercontent.com/31529584/196157489-8f72ed31-53c0-4f20-890f-555ded1773de.png)

**Comment by KevinZjYang** [comment]
![image](https://user-images.githubusercontent.com/31529584/196205418-b57b9d1e-982d-4a84-8076-271044eed269.png)
应该就是由于订阅的信息电视剧没有获取到信息导致的。 
#1672
我觉得这个可以关闭了

**Comment by 757957414** [comment]
我尝试修改数据库，发现并不能修复这个问题

**Comment by KevinZjYang** [comment]
> 我尝试修改数据库，发现并不能修复这个问题

直接删除错误的那一整条数据，我删除后就正常了。不要尝试去修改。

**Comment by sently** [comment]
> 

你好，请问怎么删除啊？

**Comment by sently** [comment]
> > 我尝试修改数据库，发现并不能修复这个问题
> 
> 直接删除错误的那一整条数据，我删除后就正常了。不要尝试去修改。

你好，请问怎么删除啊

**Comment by 757957414** [comment]
> > 我尝试修改数据库，发现并不能修复这个问题
> 
> 直接删除错误的那一整条数据，我删除后就正常了。不要尝试去修改。

我也试了删除了，没有恢复。要趴一下代码看看为什么

**Comment by 757957414** [comment]
> > > 我尝试修改数据库，发现并不能修复这个问题
> > 
> > 
> > 直接删除错误的那一整条数据，我删除后就正常了。不要尝试去修改。
> 
> 你好，请问怎么删除啊

在user.db （SQLite数据库）里面改 RSS_TVS表就好了

**Comment by sently** [comment]
#1672 跟这个应该是一样的类型

**Comment by KevinZjYang** [comment]
> #1672 跟这个应该是一样的类型

就是一样的，前面我艾特你的时候也链接这个了。

**Comment by sently** [comment]
> > #1672 跟这个应该是一样的类型
> 
> 就是一样的，前面我艾特你的时候也链接这个了。

已经解决了 谢谢！
