### ISSUE TITLE
老大，推荐页面按评分排序好弄吗

### ISSUE THREAD

**Issue by 26712681** [jxxghp/nas-tools#1649]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>2.2.2
> 环境: docker or windows or synology
docker
## 你想要新增或者改进什么功能？
推荐页面按评分排序
> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？
![image](https://user-images.githubusercontent.com/77581926/196026072-d532e0a1-c795-49af-919d-54ff56ee432d.png)

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
我有空研究下看看

**Comment by Shurelol** [comment]
排序好做，翻页麻烦。

**Comment by jxxghp** [comment]
合并到一个问题：#2500
