### ISSUE TITLE
关于订阅一个电视剧遇见的小问题

### ISSUE THREAD

**Issue by zwf19870623** [jxxghp/nas-tools#165]
安装体验了一段时间，感觉工具很贴近使用习惯，首先感谢作者的无私付出，然后大概描述一下最近碰到的小问题，麻烦看下是不是属于bug

    我想追某个正在更新的剧，这里遇见的问题是《暗夜行者》目前更新到第6集，但是从tmdb可以看到总共是24集的，但是下载了6集就自动把订阅删除了

    另不知道算不算需求：电视剧追剧不用“订阅”作为前缀是否可以将已经完结的下完自动清除订阅，未完结的下了已经更新的，自动加入订阅等待继续更新。

**Comment by wangxunhuan** [comment]
你没有在订阅站点的地方 添加PT站，好像是不会订阅更新的，你只添加了Jackett，NAStool只是单纯的帮你搜索下载，并没有起到订阅更新的作用！ 反过来说，就是你要自动更新订阅，就需要添加 订阅站点

**Comment by zwf19870623** [comment]
> 


> 你没有在订阅站点的地方 添加PT站，好像是不会订阅更新的，你只添加了Jackett，NAStool只是单纯的帮你搜索下载，并没有起到订阅更新的作用！ 反过来说，就是你要自动更新订阅，就需要添加 订阅站点

也就是说这两个可以是完全独立的功能，我如果只想追剧，可以不录入jk，只添加订阅站点就行了吗。主要是我没录入订阅站点，订阅了某个剧也会自动下导致我有点疑惑。感觉两个都录入有点重复了

**Comment by wangxunhuan** [comment]
简单的说：夹克只负责搜索的，订阅追剧需要 配置 【站点订阅】这个两个各司其职的

**Comment by zwf19870623** [comment]
我使用订阅站点功能录入了几个站测试了一下，发现如果这里录入了站点的rss链接，它会扫这个rss链接目前推送过来的电影然后判断是否是你订阅的电影，我认为这个功能是供给有自定义订阅的人用的，比如用这个软件之前我会去某个站订阅一个剧的RSS，然后把这个地址填入QB里进行下载并且定期查询更新用的，如果链接没有指定剧名就会刷新出你指定条数的最新电影，不符合使用要求啊。

附一部分日志：
这里我只订阅了一个剧《再次我的人生》，但是RSS订阅开始后他会扫所有订阅地址获取到的所有电影。

23:19:40 INFO - 【META】正在识别电影：监狱风云2：逃犯, 年份= ...
23:19:41 INFO - >电影ID：56251, 电影名称：监狱风云2：逃犯, 上映日期：1991-06-22
23:19:42 INFO - 【RSS】电影: 监狱风云2：逃犯 (1991) 不匹配订阅
23:19:42 INFO - 【RSS】开始处理：【监狱风云2：逃犯/監獄風雲II逃犯】国粤双语 低码强降噪 Repack音轨(修正轨道问题)
23:19:42 INFO - 【RSS】电影: 监狱风云2：逃犯 (1991) 不匹配订阅
23:19:42 INFO - 【RSS】开始处理：【监狱风云/監獄風雲】国粤双语 高码版 Repack音轨(修正轨道问题)
23:19:42 INFO - 【META】正在识别电影：监狱风云, 年份= ...
23:19:45 INFO - >电影ID：53653, 电影名称：监狱风云, 上映日期：1987-11-13
23:19:48 INFO - 【RSS】电影: 监狱风云 (1987) 不匹配订阅
23:19:48 INFO - 【RSS】开始处理： 【监狱风云/監獄風雲】国粤双语 降噪低码版 Repack音轨(修正轨道问题)
23:19:48 INFO - 【RSS】电影: 监狱风云 (1987) 不匹配订阅
23:19:48 INFO - 【RSS】开始处理：【翡翠明珠】国粤双语 简繁字幕 Repack音轨(修正声道问题)
23:19:48 INFO - 【META】正在识别电影：翡翠明珠, 年份= ...
23:19:50 INFO - >电影ID：46129, 电影名称：翡翠明珠, 上映日期：2010-08-18
23:19:56 INFO - 【RSS】电影: 翡翠明珠 (2010) 不匹配订阅
23:19:56 INFO - 【RSS】frd 处理结束，匹配到 0 个有效资源
23:19:56 INFO - 【RSS】正在处理：ob
23:20:06 WARN - 【RSS】ob 未下载到数据
23:20:06 INFO - 【RSS】正在处理：hdsky
23:20:09 INFO - 【RSS】hdsky 获取数据：10
23:20:09 INFO - 【RSS】开始处理：Rake S05 1080p BluRay FLAC2.0 x264-SbR
23:20:09 INFO - 【RSS】电视剧: Rake (2010) S05 BluRay 1080p 不匹配订阅
23:20:09 INFO - 【RSS】开始处理：The Treasure Hunter 2009 CHN Blu-ray 1080p AVC TrueHD 7.1-doraemon
23:20:09 INFO - 【META】正在识别电影：The Treasure Hunter, 年份=2009 ...
23:20:13 INFO - >电影ID：37848, 电影名称：刺陵, 上映日期：2009-12-09
23:20:14 INFO - 【RSS】电影: 刺陵 (2009) BluRay 1080p 不匹配订阅
23:20:14 INFO - 【RSS】开始处理：Darker than Black S01 2007 1080p KKTV WEB-DL x264 AAC-ADWeb
23:20:14 INFO - 【META】正在识别电视剧：Darker than Black, 年份=2007 ...
23:20:17 INFO - >电视剧ID：31718, 电视剧名称：黑之契约者, 上映日期：2007-04-06
23:20:18 INFO - 【RSS】动漫: 黑之契约者 (2007) S01 WEB-DL 1080p 不匹配订阅
23:20:18 INFO - 【RSS】开始处理：Godspeed 2022 1080p NF WEB-DL x264 DDP5.1-ADWeb
23:20:18 INFO - 【META】正在识别电影：Godspeed, 年份=2022 ...
23:20:20 INFO - >电影ID：971647, 电影名称：疗伤旅程, 上映日期：2022-05-23
23:20:23 INFO - 【RSS】电影: 疗伤旅程 (2022) WEB-DL 1080p 不匹配订阅
23:20:23 INFO - 【RSS】开始处理：Sisters Who Make Waves Plus S02 2021 1080p WEB-DL H.264 AAC-ADWeb
23:20:23 INFO - 【META】正在识别电视剧：Sisters Who Make Waves Plus, 年份=2021 ...
23:20:23 WARN - 【META】Sisters Who Make Waves Plus 未找到媒体信息!
23:20:23 INFO - 【META】正在识别电视剧：Sisters Who Make Waves Plus, 年份= ...
23:20:24 WARN - 【META】Sisters Who Make Waves Plus 未找到媒体信息!
23:20:24 INFO - 【RSS】Sisters Who Make Waves Plus S02 2021 1080p WEB-DL H.264 AAC-ADWeb 未查询到媒体信息
23:20:24 INFO - 【RSS】开始处理：My Girl S01 2020 2160p WEB-DL H.265 AAC-ADWeb
23:20:24 INFO - 【META】正在识别电视剧：My Girl, 年份=2020 ...
23:20:27 INFO - >电视剧ID：105087, 电视剧名称：99分女朋友, 上映日期：2020-06-17
23:20:29 INFO - 【RSS】电视剧: 99分女朋友 (2020) S01 WEB-DL 2160p 不匹配订阅
23:20:29 INFO - 【RSS】开始处理：Sisters Who Make Waves VIP Extra S01 2020 1080p WEB-DL H.264 AAC-ADWeb
23:20:29 INFO - 【META】正在识别电视剧：Sisters Who Make Waves VIP Extra, 年份=2020 ...
23:20:30 WARN - 【META】Sisters Who Make Waves VIP Extra 未找到媒体信息!
23:20:30 INFO - 【META】正在识别电视剧：Sisters Who Make Waves VIP Extra, 年份= ...
23:20:33 WARN - 【META】Sisters Who Make Waves VIP Extra 未找到媒体信息!
23:20:33 INFO - 【RSS】Sisters Who Make Waves VIP Extra S01 2020 1080p WEB-DL H.264 AAC-ADWeb 未查询到媒体信息
23:20:33 INFO - 【RSS】开始处理：Kung Fu Cop S01 2020 1080p WEB-DL H.265 AAC-ADWeb
23:20:33 INFO - 【META】正在识别电视剧：Kung Fu Cop, 年份=2020 ...
23:20:33 INFO - >电视剧ID：114113, 电视剧名称：功夫战警, 上映日期：2020-12-03
23:20:36 INFO - 【RSS】电视剧: 功夫战警 (2020) S01 WEB-DL 1080p 不匹配订阅
23:20:36 INFO - 【RSS】开始处理：Father Brown 2013 S09 1080p Blu-ray Remux AVC DTS-HD MA 5.1-SiCFoI
23:20:36 INFO - 【RSS】电视剧: 布朗神父 (2013) S09 BluRay 1080p 不匹配订阅
23:20:36 INFO - 【RSS】开始处理：tai wan hua wen shu ku part5
23:20:36 INFO - 【META】正在识别电影：tai wan hua wen shu ku, 年份= ...
23:20:37 WARN - 【META】tai wan hua wen shu ku 未找到媒体信息!
23:20:37 INFO - 【META】正在识别电视剧：tai wan hua wen shu ku, 年份= ...
23:20:38 WARN - 【META】tai wan hua wen shu ku 未找到媒体信息!
23:20:38 INFO - 【RSS】tai wan hua wen shu ku part5 未查询到媒体信息
23:20:38 INFO - 【RSS】hdsky 处理结束，匹配到 0 个有效资源
23:20:38 INFO - 【RSS】正在处理：lemon
23:20:39 INFO - 【RSS】lemon 获取数据：10
23:20:39 INFO - 【RSS】开始处理：[TV Series(电视剧)][Rake S05 1080p BluRay FLAC2.0 x264-SbR][法庭浪子 第五季 全8集 澳大利亚剧][51.88 GB]
23:20:39 INFO - 【RSS】电视剧: Rake (2010) S05 BluRay 1080p 不匹配订阅
23:20:39 INFO - 【RSS】开始处理：[TV Series(电视剧)][Who Rules the World 2022 S01 Complete 1080p NF WEB-DL H264 DDP-LeagueNF][且试天下 全40集 | 类型:剧情/爱情/古装 主演:杨洋/赵露思/张丰毅 [国语/多国软字幕] | *E35-E40仅繁中字幕*][64.50 GB]
23:20:39 INFO - 【META】正在识别电视剧：Who Rules the World, 年份=2022 ...
23:20:40 INFO - >电视剧ID：127323, 电视剧名称：且试天下, 上映日期：2022-04-18
23:20:49 INFO - 【RSS】电视剧: 且试天下 (2022) S01 WEB-DL 1080p 不匹配订阅
23:20:49 INFO - 【RSS】开始处理：[Movie][Piranha 2010 Blu-Ray 1080p AVC DTS-HD MA 5.1@TTG][食人鱼 原盘中字纯2D版本/官方中文字幕 台版原盘，亮点较多，低调下载。][42.20 GB]
23:20:49 INFO - 【META】正在识别电影：Piranha, 年份=2010 ...
23:20:52 INFO - >电影ID：43593, 电影名称：食人鱼3D, 上映日期：2010-08-20
23:20:52 INFO - 【RSS】电影: 食人鱼3D (2010) BluRay 1080p 不匹配订阅
23:20:52 INFO - 【RSS】开始处理：[TV Series(电视剧)][Leverage 2022 S01E38-E39 2160p WEB-DL H264 AAC-LeagueWEB][杠杆 第38-39集 | 类型:剧情/悬疑/犯罪 主演:郭京飞/于毅/佟丽娅 [国语/中字] | *4K*][6.82 GB]
23:20:52 INFO - 【META】正在识别电视剧：Leverage, 年份=2022 ...
23:20:53 INFO - >电视剧ID：201199, 电视剧名称：杠杆, 上映日期：2022-05-03
23:20:53 INFO - 【RSS】电视剧: 杠杆 (2022) S01 E38-E39 WEB-DL 2160p 不匹配订阅
23:20:53 INFO - 【RSS】开始处理：[TV Series(电视剧)][Leverage 2022 S01E38-E39 1080p WEB-DL H265 DDP-LeagueWEB][杠杆 第38-39集 | 类型:剧情/悬疑/犯罪 主演:郭京飞/于毅/佟丽娅 [国语/中字]][1.64 GB]
23:20:53 INFO - 【RSS】电视剧: 杠杆 (2022) S01 E38-E39 WEB-DL 1080p 不匹配订阅
23:20:53 INFO - 【RSS】开始处理：[TV Series(电视剧)][Father Brown 2013 S09 1080p Blu-ray Remux AVC DTS-HD MA 5.1-SiCFoI][布朗神父 第九季/Father Brown Season 9 全10集][109.02 GB]
23:20:53 INFO - 【RSS】电视剧: 布朗神父 (2013) S09 BluRay 1080p 不匹配订阅
23:20:53 INFO - 【RSS】开始处理：[Animations(动画片)][[死狂/剑豪生死斗][Shigurui][シグルイ][2007][BDMV][1080][TV Series][TV 01-12 Fin][FRA][DragonMax]][死狂/剑豪生死斗 @DragonMax Audio : Japanese | French - Subtitles : French ][58.54 GB]
23:20:53 INFO - 【RSS】[Animations(动画片)][[死狂/剑豪生死斗][Shigurui][シグルイ][2007][BDMV][1080][TV Series][TV 01-12 Fin][FRA][DragonMax]][死狂/剑豪生死斗 @DragonMax Audio : Japanese | French - Subtitles : French ][58.54 GB] 未查询到媒体信息
23:20:53 INFO - 【RSS】开始处理：[TV Series(电视剧)][Love in Flames of War 2022 S01E40-E41 2160p WEB-DL 60fps H265 10bit AAC-LeagueWEB][良辰好景知几何 第40-41集 | 类型:剧情/爱情 主演:窦骁/陈都灵/胡军 [国语中字] | *4K*][3.40 GB]
23:20:53 INFO - 【META】正在识别电视剧：Love in Flames of War, 年份=2022 ...
23:20:54 INFO - >电视剧ID：200961, 电视剧名称：良辰好景知几何, 上映日期：2022-04-30
23:20:54 INFO - 【RSS】电视剧: 良辰好景知几何 (2022) S01 E40-E41 WEB-DL 2160p 不匹配订阅
23:20:54 INFO - 【RSS】开始处理：[TV Series(电视剧)][Love in Flames of War 2022 S01E40-E41 1080p WEB-DL 60fps H265 10bit AAC-LeagueWEB][良辰好景知几何 第40-41集 | 类型:剧情/爱情 主演:窦骁/陈都灵/胡军 [国语中字]][1.25 GB]
23:20:54 INFO - 【RSS】电视剧: 良辰好景知几何 (2022) S01 E40-E41 WEB-DL 1080p 不匹配订阅
23:20:54 INFO - 【RSS】开始处理：[TV Series(电视剧)][The Expanse 2021 S06 Complete 2160p AMZN WEB-DL H265.10bit HDR DDP5.1-LeagueWEB][苍穹浩瀚/无垠的太空/太空无垠/浩瀚天穹 第六季 全6集 | 类型:剧情/动作/科幻 主演:索瑞·安达斯鲁/史蒂文·斯崔特/卡卡琪 [国英双语/多国软字幕]][32.54 GB]

**Comment by zwf19870623** [comment]
再次验证了一下，我提的应该不是bug，订阅站点那里不用加东西，只需要在微信里输入 “订阅 暗夜行者 第一季”就可以成功在电视剧订阅中显示正确的集数，先前我输入的是"订阅 暗夜行者" 就只会下载到目前更新的集数然后删除订阅信息。不知道为什么会出现这种情况

**Comment by wangxunhuan** [comment]
> 我使用订阅功能录入了几个站点测试过的站点，它会发现这里录入的录入了某个电影的链接，它会发现这个录入的摄像头，现在如果我认为这个功能是你的这个电影然后确定订阅的功能，然后是我的订阅功能有自定义订阅用的，这个之前我会去查询用什么网站里的软件把某个剧集的RSS这个地址填入QB的，并进行定期更新用，如果链接没有指定剧名就可以会出你指定数的最新电影，不符合要求啊。
> 
> 附上所有日志： 这里我只订阅了一部剧《再次我的人生》，但RSS订阅开始后他会扫一扫地址获取到的所有电影。
> 
> 23:19:40 INFO - 【META】正在识别：电影犯罪风云2：逃，年份= ... >23:19:41 INFO - 电影电影ID：56251，名称：监狱风云2：，公开日期： 1991-06-22 23:19:42 FO - 【RSS：监狱风云2：逃（1991） 不匹配 订阅23:19:42 INFO - 【RSS】开始处理：【监狱风云2：逃犯/犯风云】 II逃犯】低强轨道国道：双包音轨码（问题问题23:142） 【RSS】电影：监狱修改风云2：逃犯（1991） 【不匹配订阅 23:19:42】 RSS】开始处理：【监狱风云/监狱风云轨】国粤双语高码版重装音轨（修改轨道问题） 33:19:42 INFO - 【META正在识别：监狱风云，年= ... 23】 19:45 INFO - 电影名称：监狱风云 上映日期：1987-11-13 23:19:48 INFO - 【RSS】电影：监狱风云 (1987) 不匹配 23:19:48 INFO - 【RSS】：【监狱风云/监狱风云版/监狱风云开始处理音轨码 】23:19:48 INFO - 【RSS】电影：监狱风云（1987）不匹配订阅23:19:48 INFO - 【RSS】处理开始：【翡翠明珠】国粤双语简字幕重装音轨（翠繁修改问题） 23:1:48 INFO - 【META】正在识别电影：翡翠明珠，年份= ... 23:19:50 INFO - >电影ID：46129 电影名称：翡翠明珠 上映日期：2010-08-18 23:19:56 INFO - 【RSS】电影：翡翠明珠(2010) 不匹配订阅 23:19 :56 INFO - 【RSS】frd 处理结束，匹配到0个有效资源 23:19:56 INFO - 【RSS】正在处理：ob 23:20:06 WARN - 【RSS】ob 未下载到数据 23:20: 06 INFO - 【RSS】正在处理：hdsky 23:20:09 INFO - 【RSS】hdsky 获取数据：10 23:20:09 INFO - 【RSS】开始处理：Rake S05 1080p BluRay FLAC2.0 x264-SbR 23: 20:09 INFO - 【RSS】电视剧：Rake (2010) S05 BluRay 1080p 不匹配 订阅23:20:09 INFO - 【RSS】开始：寻宝者2009 CHN Blu-ray 1080p AVC TrueHD 7.1-哆啦A梦 23:20 :09 INFO - 【META】正在识别电影：寻宝者，年份=2009 ... 23:20:13 INFO - >电影ID：37848，电影名称：刺陵，上映日期：2009-12-09 23： 20:14 INFO - 【RSS】电影：刺陵 (2009) BluRay 1080p 不匹配订阅 23:20:14 INFO - 【RSS】处理开始：Darker than Black S01 2007 1080p KKTV WEB-DL x264 AAC-ADWeb 23:20:14 INFO - 【META】正在电视剧：Darker than Black, 年份=2007 .识别。 . 23:20:17 INFO - > 电视剧ID：31718, 电视剧名称：黑之契约者, 上映日期：2007-04-06 23:20:18 INFO - 【RSS】动画：黑之契约者 (2007) S01 WEB-DL 1080p 不匹配 订阅23:20:18 INFO - 【RSS】开始处理：Godspeed 2022 1080p NF WEB-DL x264 DDP5.1-ADWeb 23:20:18 INFO - 【META】正在识别电影：Godspeed, 年份=2022 ... 23:20:20 INFO - > ID：9716, 电影名称：47岁疗伤旅行社 上映日期：2022-05-23 23:20:23 INFO - 【RSS】电影：疗伤旅行社 (2022) WEB -DL 1080p 不匹配 订阅23:20:23 INFO - 【RSS】开始处理：撩妹加S02 2021 1080p WEB-DL H.264 AAC-ADWeb 23:20:23 INFO - 【META】正在识别电视剧：造浪姐妹加，年=2021... 23:20:23 WARN - 【META】Sisters Who Make Waves Plus 未找到媒体信息！ 23:20:23 INFO - 【META】正在识别电视剧：掀起波澜的姐妹，年份= ... 23:20:24 WARN - 【META】掀起波澜的姐妹们未找到媒体信息！ 23:20:24 INFO - 【RSS】造浪姐妹加 S02 2021 1080p WEB-DL H.264 AAC-ADWeb 未查询到媒体信息 23:20:24 INFO - 【RSS】开始处理：My Girl S01 2020 2160p WEB-DL.265 AAC-HADWeb 23:20:24 INFO - 【META】正在识别电视剧：My Girl, 年份=2020 ... 23:20:27 INFO -> 电视剧ID：105087, 电视剧名称：99分好友, 上线日期：2020-06-17 23:20:29 INFO - 【RSS】电视剧：99分朋友 (2020) S01 WEB-DL 2160p 不匹配 订阅23:20:29 INFO - 【RSS】开始处理：浪姐VIP Extra S01 2020 1080p WEB-DL H.264 AAC-ADWeb 23:20:29 INFO - 【META】正在识别电视剧：浪姐VIP Extra, 年份=2020 ... 23:20:30 WARN - 【META】Sisters Who Make Waves VIP Extra 未找到媒体信息！ 23:20:30 INFO - 【META】正在识别电视剧：Sisters Who Makes VIP Extra, 年份= ... 23:20:33 WARN - 【META】Sisters Who Makes Waves VIP Extra 未媒体信息！ 23:20:33 INFO - 【RSS】撩妹VIP Extra S01 2020 1080p WEB-DL H.264 AAC-ADWeb 未到媒体信息 23:20:33 INFO - 【RSS】开始查询：功夫警察S01 2020 1080p WEB-DL H.265 AAC-ADWeb23 :20:33 INFO - 【META】正在识别电视剧：功夫警察，那年=2020 ... 23:20:33 INFO -> 电视剧ID：114113, 电视剧名称：功夫战警, 上映日期 2020-12-03 23:20:36 INFO - 【RSS】电视剧：功夫战警 (2020) S01 WEB-DL 1080p 不订阅匹配 23:20:36 INFO - 【RSS】开始处理：布朗神父 2013 S09 1080p Blu-ray Remux AVC DTS-HD MA 5.1-SiCFoI 23:20:36 INFO - 【RSS】电视剧：布朗神父 (2013) S09 BluRay 1080p 不匹配 23:20:36 INFO - 【RSS】开始处理：大湾华文书库 part5 23:20: 6 INFO - 【META】正在识别电影：大湾华文书库，年份= ... 23:20： 37 WARN - 【META】tai wan hua wen shu ku 未找到媒体信息！ 23:20:37 INFO - 【META】正在识别电视剧：tai wan hua wen shu ku, 年代= ... 23:20:38 WARN - 【META】tai wan hua wen shu ku 未找到媒体信息！ 23:20:38 INFO - 【RSS】tai wan hua wen shu ku part5 未查询到媒体信息 23:20:38 INFO - 【RSS】hdsky 结束，匹配到0个有效资源 23:20:38 INFO - 【处理RSS】正在处理：lemon 23:20:39 INFO - 【RSS】lemon 获取数据：10 23:20:39 INFO - 【RSS】开始处理：[TV Series(电视剧)][Rake S05 1080p BluRay FLAC2.0 x264 -SbR[法庭浪子季第五季全8集澳大利亚剧][51.88 GB] 23:20:39 INFO - 【RSS】电视剧：Rake (2010) S05 BluRay 1080p 不匹配订阅 23:20:39 INFO - 【RSS】天下处理开始：[电视剧(电视剧)][谁主宰世界2022 S01 Complete 1080p NF WEB-DL H264 DDP-LeagueNF][且试一试40集 | 类型：剧情/爱情/古装 主演：杨洋/赵露思/张丰毅 [国语/多国软字幕] | _E35-E40仅繁中字幕_][64.50 GB] 23:20:39 INFO - 【META】正在识别电视剧：谁主宰世界，年份=2022 ... 23:20:40 INFO -> 电视剧ID：127323,电视剧名称：且试看天下, 上映日期：2022-04-18 23:20:49 INFO - 【RSS】电视剧订阅：且试天下 (2022) S01 WEB-DL 1080p 不匹配 23:20:49 INFO - 【RSS】 】[Piranha 2010 Blu1080p AVCTS-HD MA 5.1TTG][食人鱼原盘中字2010Blu1080p AVCTS-HD MA 5.1TTG开始处理] 42.20 GB] 23:20:49 INFO - 【META】正在上映电影：食人鱼，年份=2010 ... 23:20:52 INFO - >电影ID：43593，电影名称：食人3D，上映日期：2010- 08-20 23:20:52 INFO - 【RSS】电影：食人鱼3D (2010) BluRay 1080p 不匹配订阅 23:20:52 INFO - 【RSS】开始处理：[电视剧(电视剧)][利用2022 S01E38-E39 2160p WEB-DL H264 AAC-LeagueWEB][常规第38-39集 | 类型：剧情/悬疑/犯罪 主演：郭京飞/于毅/佟丽娅 [国语/中字] | _4K_ [6.82 GB] 23:20:52 INFO -META】正在识别电视剧：Leverage, 当年=2022 ... 23:20:53 INFO ->电视剧ID：201199,电视剧名称：电视剧,日期：2022 -05-03 23:20:53 INFO - 【RSS】电视剧：经典（2022）S01 E38-E39 WEB-DL 2160p 不匹配 订阅23:20:53 INFO - 【RSS】处理：[电视剧（电视剧开始） ][杠杆2022 S01E38-E9 1080p WEB-DL H265 DDP-LeagueWEB][第三季第38-39集 | 类型 剧情/悬疑/犯罪 演员郭京飞/于佟丽娅 [国语/中字]/佟丽娅 [国语/中字]/佟丽娅 [国语/中字]/佟丽娅 [国语/中字]/佟丽娅 [1.64 GB] 23:20:53 INFO - 【RSS】电视剧：平凡（2022）S01 E38-E39 WEB-DL 108p 不订阅订阅23:20:5 INFO - 【RSS】：[电视剧（电视剧开始）][布朗神父2013 S09 1080p Blu-ray Remux AVC DTS-HD MA 5.1-SiCFoI][布朗神父第九季处理/布朗神父第9季全10集][109.02 GB] 23:53 INFO - 【RSS】电视剧：布朗神父(2013) S09 BluRay 1080 不匹配 订阅23:20:53 INFO - 【RSS】：[Animations(开始处理)p][[死狂/剑豪]生死斗][Shigurui][シグルイ][2007][BDMV][1080][TV Series][TV 01-12 Fin][FRA][DragonMax]][狂/剑豪生死斗@DragonMax音频：日语 | 法语 - 法语 : 法语 : 8.54 GB] 23:2: 53 INFO][动画][字幕][5个][RSS][[死狂/剑豪生死斗][Shigurui][シグルイ][2007][ 1080][电视剧][TV 01-12 Fin][FRA][DragonMax]][死狂/剑豪生死斗@DragonMax音频：日语 | 法语 - 字幕 : 法语 ][58.54 GB]未到媒体信息 23:20:53 INFO - 【RSS】开始处理：[电视剧(电视剧)][战火纷飞2022 S01E40-E41 2160p WEB-DL 60fps H265 10bit AAC-LeagueWEB][良辰好景知几何第40-41集| 类型：剧情/爱情 演员：窦骁/陈都灵/胡军 _4K_ [3.40 GB] 23:20:53 INFO - 【META】正在识别电视剧：战火纷飞，年=2022 ... 23:20:54 INFO -> 电视剧ID：200961, 电视剧：良辰好景知几何,最晚日期：2022-04-30 23:20:54 INFO - 【RSS】电视剧: 良辰好景知几何 (2022) S01 E40-E41 WEB-DL 2160p 不匹配 订阅23:20:54 INFO - 【RSS】 】处理开始：[电视剧(电视剧)][战火纷飞2022 S01E40-E41 1080p WEB-DL 60fps H265 10bit AAC-LeagueWEB][良景好知几何第40-41集 | 类型：剧情/爱情 演员：窦骁/陈都灵/胡军 [国语中字]][1.25 GB] 23:20:54 INFO - 【RSS】 电视剧：良辰好景知几何 (2022) S01 E40-E41 WEB- DL 1080p 不匹配订阅 23:20:54 INFO - 【RSS】瀚处理开始：[TV Series(电视剧)][The Expanse 2021 S06 Complete 2160p AMZN WEB-DL H265.10bit HDR DDP5.1-LeagueWEB][苍穹浩/无垠的太空]无垠/浩瀚天穹第六季全6集| 类型：剧情/动作/剧情：索瑞·安达斯鲁/史文·斯特/卡琪[国英双语/多国软字幕]][32.54 GB]

以前我也是这么理解的，以为【订阅站点】只是用来自定义PT站点的，后来作者告诉我 不是这么玩的，反正我的理解，就是一部新剧 如果一共30集，现在只更新到第五集，你设置了【订阅站点】它就一直会持续帮您追踪下载完30集，才会删除订阅任务。如果你不设置【订阅站点】它只会帮你从夹克里面 随意搜索 匹配一个资源 帮你下载。

**Comment by jxxghp** [comment]
> 再次验证了一下，我提的应该不是bug，订阅站点那里不用加东西，只需要在微信里输入 “订阅 暗夜行者 第一季”就可以成功在电视剧订阅中显示正确的集数，先前我输入的是"订阅 暗夜行者" 就只会下载到目前更新的集数然后删除订阅信息。不知道为什么会出现这种情况
> 
> 

wiki常见问题、群置顶看一下，有说的。
