### ISSUE TITLE
应用替换词后，正在下载界面与替换词不匹配

### ISSUE THREAD

**Issue by marcosteam** [jxxghp/nas-tools#1653]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2 bec0b367
>
> 环境: docker
>

## 你遇到什么问题了？

例：密室大逃脱第四季，应用替换词 Great Escape@Mi Shi Da Tao Tuo，成功添加订阅及开始下载正确的资源，但是正在下载显示的是电影《密室逃脱》。

![image](https://user-images.githubusercontent.com/25745812/196033047-38a83ec2-413a-4a0e-a969-3cd9a5cbd0e5.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

是的

## 你期望的结果

此处应该显示的是应用替换词的结果，即密室大逃脱 第四季

**Comment by jxxghp** [comment]
你要看下载器里的任务名

**Comment by Shurelol** [comment]
正在下载显示的是根据下载器中任务名识别的结果
你添加的替换Great Escape@Mi Shi Da Tao Tuo，可能对任务名不生效

因为任务名中很可能是Great.Escape而不是Great Escape
