### ISSUE TITLE
2.2.1版本后添加qb下载不自动添加分类。

### ISSUE THREAD

**Issue by mfksss** [jxxghp/nas-tools#1657]
比如 ：我有多分区 ，我是让电影放在分区2的下载目录，让电视剧下载在分区3，如果在NASTOOL添加分类后，QB会自动下载到相应分区的文件夹下.现在是因为NASTOOL不会为QB添加分类，那就会自动下载到默认文件夹下，而不是分类下的下载文件夹下.现在不会在下载的时候自动给所下载的视频添加分类了 ， 再加上QB上还有一个默认下载文件夹 等于是如果在NASTOOL添加一个新的下载文件后.如果NASTOOL让QB自动舔加分类后 如电视剧. （包括动画续集 美剧 综艺只要TMDB分类为电视剧的都要自动下载到 分区3/VIDEOS/TD 下）然后自动转移到相应的我二级分类下.

**Comment by jxxghp** [comment]
1.升到最新
2.保存目录、访问目录不填，只填标签

**Comment by XINGYUZHMM** [comment]
> 1.升到最新 2.保存目录、访问目录不填，只填标签

2.2.2版本试了，只填分类不行，下载的时候只有自动下载的选项，下载目录和分类都填上推送到qb下载后只有下载目录没有分类。

**Comment by sjtuross** [comment]
首先同名QB分类要预先存在，另外在我这里没有用到二级分类是正常的，会不会跟二级分类有关？

**Comment by mfksss** [comment]
> 首先同名QB分类要预先存在，另外在我这里没有用到二级分类是正常的，会不会跟二级分类有关？

首先之前版本都没这个问题，这是更新到2.2.1后包括2.2.2。如果是一个分区应该是只需要标签就够了 如果是多分区，那么这个自动添加到分类是很有用作用的。因为自动添加了分类后会等qb自动下载完后会自动转移到相应分区还不会影响做种。

**Comment by mfksss** [comment]
> 1.升到最新
> 2.保存目录、访问目录不填，只填标签

经测试还是和之前一样。
群晖套件版，2.2.2。

**Comment by mfksss** [comment]
> 1.升到最新
> 2.保存目录、访问目录不填，只填标签

最新版本2.2.3 5fcadc群晖套件版 
问题还是存在.如果不在保存目录 填写路径，那么通过nastool资源搜索，用下载器下载的电影或视频就会下到下载器默认文件夹。需手动添加分类才会在下载完后自动移动到需要的分区下的文件夹。如果在保存目录填入需要的路径，通讯软件或订阅下载就不会给分类。我觉得还是恢复到2.2.0之前版本更好。那样就不会出现现在这样的问题。

**Comment by jxxghp** [comment]
> 给作者提了，直接关闭了…其实很简单的思路，现在弄得这么复杂，还产生了bug。看了这么多提问无外乎就是添加的任务是否是自动管理模式，然后qb设置不自动下载是否生效，监控下载模式下文件不转移提示没有发现文件，还有你这个问题…
> 
> nt的目录设置目的，就是把资源下到相应的自己想要的文件夹里让nt对它执行下一步操作。无非就三种设置方式：1，只设置前面的路径，这时候就下载到相应的路径就行。2，设置路径和标签，这时候就在qb里生成一个以标签命名的分类，地址就是设置的这个路径。3，只设置标签，这时候就在qb里生成一个以标签命名的分类，地址就是qb默认的下载地址/标签。至于种子任务自动管理模式与否，是否自动下载等等都看qb的设置。这样基本所有使用方式都不会造成混乱，每个人按自己习惯设置就行。在这个基础上，可以弄得更人性。今天看有人提出增加选择是否自动下载，这个时候如果手动选择，优先级就按选择的来。

之前问题中，我已经解释了为什么要现在这样设计的原因。用得了你就用，没有人逼你用，不用在这里吐槽，这是开源项目，你自己有需求自己fork自己改。要别人给你解决使用习惯还这个态度？
