### ISSUE TITLE
时间段签到没有成功过。

### ISSUE THREAD

**Issue by mfksss** [jxxghp/nas-tools#1658]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境: Synology 
>

## 你遇到什么问题了？
![image](https://user-images.githubusercontent.com/112247130/196048280-c7272372-cbf4-4827-8416-293b14331f10.jpeg)
> 描述一下你遇到的问题
使用时间段内如00:15-01:00 ，但从来没有自动签到。使用固定时间签到没问题。
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
选个非0点的时间段
