### ISSUE TITLE
资源搜索 与 Jackett搜索结果不一致

### ISSUE THREAD

**Issue by AuroraFrowned** [jxxghp/nas-tools#166]
在“资源搜索” 与 在"Jackett"搜索结果不一致
Jackett返回14条结果 资源搜索只返回4条
日志显示
20:12:16 WARN - 【META】***** 未找到媒体信息!

20:12:18 INFO - 【JACKETT】所有API检索完成，有效资源数：6
20:12:18 INFO - 【WEB】共检索到 6 个有效资源
20:12:18 INFO - 【WEB】分组择优后剩余 4 个有效资源

应该是在Jackett搜索后进行了匹配 有无办法可以禁止预先匹配 返回所有结果

**Comment by jxxghp** [comment]
你的建议跟工具的目的不符
