### ISSUE TITLE
（建议）希望电影重命名功能添加关于HDR和SDR版本区分的占位符

### ISSUE THREAD

**Issue by Kai-0x10c** [jxxghp/nas-tools#1660]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境: docker in synology

## 你想要新增或者改进什么功能？

> 希望电影重命名功能添加关于HDR和SDR版本区分的占位符，现有的{videoCodec}(视频编码)和{edition}(版本)不对是否为hdr版本做区分，希望添加新的关于HDR的占位符在重命名时识别HDR或SDR版本。
![1](https://user-images.githubusercontent.com/114797758/196053149-6860f412-8560-4b81-8b7c-961c40c50cee.jpg)
![2](https://user-images.githubusercontent.com/114797758/196053152-1f2d68c9-4199-433f-93b4-8088e16b4d58.jpg)

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Tartarus2014** [comment]
可以顺便加个hdr10/10+，杜比视界这些么

**Comment by 3e4r5t6y** [comment]
我自己的HDR和杜比这俩可以通过自定义识别器替换来实现自动重命名效果。不过大部分SDR的种子命名规则不是很规范，SDR没试过

**Comment by lengxii** [comment]
> 我自己试过 SDR HDR和杜比这仨可以通过自定义识别器替换来实现自动重命名效果。不过大部分SDR的种子命名规则不是很规范

大佬 能截图看下你是怎么设置的吗？
九龙镇天棺.Nine.Dragons.Sky.Coffin.2022.2160p.WEB-DL.H265.AAC-ADWeb
九龙镇天棺.Nine.Dragons.Sky.Coffin.2022.2160p.WEB-DL.H265.DV.DDP2.0-ADWeb
比如我这2个版本，要怎么设置

**Comment by jxxghp** [comment]
HDR DV都已支持
