### ISSUE TITLE
转移文件时使用复制模式，会发现在文件还未下载完成的时候，已经提示转移成功了

### ISSUE THREAD

**Issue by KevinZjYang** [jxxghp/nas-tools#1667]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>V2.2.2
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 转移文件时使用复制模式，会发现在文件还未下载完成的时候，已经提示转移成功了，这会导致文件损坏问题。目前已经复现了十几次。需要手动删除转移的文件，然后在转移历史记录里面，重新识别。重新转移后文件就是正常的了。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已查找，未发现相同问题。

## 你期望的结果

> 希望可以等文件下载完成后再运行转移。

## 给出程序界面截图、后台运行日志或配置文件
![QQ图片20221017142947](https://user-images.githubusercontent.com/31529584/196104616-00ddbdda-d223-438e-82f0-f93167b7a809.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by link2fun** [comment]
QB 或 TR 配置一下 不完整文件文件扩展名 或使用临时目录
![image](https://user-images.githubusercontent.com/19241982/196114809-b9b5324d-ef27-49eb-b338-c3507497fd0e.png)

**Comment by KevinZjYang** [comment]
> QB 或 TR 配置一下 不完整文件文件扩展名 或使用临时目录 ![image](https://user-images.githubusercontent.com/19241982/196114809-b9b5324d-ef27-49eb-b338-c3507497fd0e.png)

谢谢，我去试试。感觉应该不会出问题了。

**Comment by KevinZjYang** [comment]
> > QB 或 TR 配置一下 不完整文件文件扩展名 或使用临时目录 ![image](https://user-images.githubusercontent.com/19241982/196114809-b9b5324d-ef27-49eb-b338-c3507497fd0e.png)
> 
> 谢谢，我去试试。感觉应该不会出问题了。

已测试，正常了。谢谢。
