### ISSUE TITLE
【识别并重命名】和【只管理NAStool添加的下载】这两项功能 都是无效的

### ISSUE THREAD

**Issue by wangxunhuan** [jxxghp/nas-tools#167]
我单独用 监控下载器 并勾选 只管理NAStool添加下载的时候，把之前不是nastool添加的  都全部 硬链接转移了。

我又单独使用 目录同步 去掉识别 并重命名，还是识别和重命名。

每次修改设置，都重启了
<img src="https://s1.xoimg.com/i/2022/05/23/zjhiz3.jpg" alt="不识别" />
<img src="https://s1.xoimg.com/i/2022/05/23/zjholg.jpg" alt="只管理" />

**Comment by jxxghp** [comment]
这个开关只针对新增的加载，因为下载的时候要打标记才知道哪些是NASTool加的。
识别重命名开关没问题的，有很多人包括我自己都正常使用，再检查下自己的配置吧，比较目录配置是不是有嵌套。

**Comment by leo8912** [comment]
> 这个开关只针对新增的加载，因为下载的时候要打标记才知道哪些是NASTool加的。
> 识别重命名开关没问题的，有很多人包括我自己都正常使用，再检查下自己的配置吧，比较目录配置是不是有嵌套。

![Screenshot_2022-05-25-08-13-40-585_com.android.browser.png](https://user-images.githubusercontent.com/22719866/170152385-7d72ea19-53fa-4e3e-8fb4-0ae91ab93d2a.png)![Screenshot_2022-05-25-08-16-10-656-edit_com.android.browser.jpg](https://user-images.githubusercontent.com/22719866/170152392-c1c1f84d-41e8-4b51-b8e1-205bfd4c9f98.jpg)
第二点我也有这问题，他还是识别了
