### ISSUE TITLE
订阅暂未上映的电视剧，导致【电视剧订阅】功能按钮无法打开。

### ISSUE THREAD

**Issue by Alaskalaofei** [jxxghp/nas-tools#1672]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境: docker or windows or Synology
>windows

## 你遇到什么问题了？
订阅暂未上映的电视剧，导致【电视剧订阅】功能按钮无法打开。
例子:订阅10月28将上映的【假面骑士黑日】后随之重新打开管理页面，【电视剧订阅】按钮无法打开。
个人临时解决方案:从db文件删除【假面骑士黑日】订阅信息，即可打开【电视剧订阅】。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是

## 你期望的结果
触发这个问题的关键点是:提前订阅未上映的电视剧。

做出了此类操作导致【电视剧订阅】功能无法打开该怎么办?
希望作者能跟进一下此bug.

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/51311487/196200230-de0959aa-30c6-4078-8d2e-65c0e75a3058.png)

**Comment by link2fun** [comment]
已FIX 等 merge，不过这个主要原因应该还是TMDB中没有剧集信息

**Comment by wjjchen** [comment]
遇到同样问题，是那个db文件？

**Comment by Alaskalaofei** [comment]
> 遇到同样的问题，是那个db文件吗？
user.db-》RSS_TVS表

**Comment by sently** [comment]
我发现我是由于死神：千年血战篇 无法在TMDB中读取出来导致的问题，然后对这个取消订阅即可。
另外，请看下死神千年血战篇的查询是不是有问题，因为他不属于正常的第几季，但是在TMDB中显示为第二季。
[https://www.themoviedb.org/tv/30984-bleach/season/2](url)

**Comment by ZiGmaX809** [comment]
发现不用去操作db文件（群晖套件操作起来也麻烦），直接在推荐资源（或者搜索，没试）里面找到出错的剧集取消订阅就行了

**Comment by jxxghp** [comment]
应该解决了，已同步到master。
