### ISSUE TITLE
v2.2.2版本qBittorrent刷流推送成功但是不计算下载导致无限推送

### ISSUE THREAD

**Issue by XINGYUZHMM** [jxxghp/nas-tools#1676]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境: windows
>

## 你遇到什么问题了？

> v2.2.2版本qBittorrent刷流推送成功但是nastool不计算下载导致无限推送，换了几个站点都是同样的情况，用transmission则正常。

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/112518475/196286773-41e42851-06bc-4a7c-8edd-52c247f61ab6.png)
![image](https://user-images.githubusercontent.com/112518475/196286890-a5872b1a-637f-4e4d-8265-5f83bc2ecc4e.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by xuanqb** [comment]
+1

**Comment by jxxghp** [comment]
换QB版本

**Comment by XINGYUZHMM** [comment]
> 换QB版本

nastool换2.13就没问题了，跟qb版本应该无关。

**Comment by xuanqb** [comment]
> 换QB版本

今天突然想到和qb版本可能有关系，之前用的是4.2.5有问题，刚刚换成4.4.5就正常了
