### ISSUE TITLE
订阅刷新无法下载显示未含集数信息，但是实际搜索可搜索到。

### ISSUE THREAD

**Issue by XINGYUZHMM** [jxxghp/nas-tools#1677]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境:windows
>

## 你遇到什么问题了？

> 订阅刷新无法下载显示未含集数信息，但是实际搜索可搜索到（用的订阅界面刷新按钮旁边的搜索按钮），索引器是jackett。

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/112518475/196293301-f7ae1df8-42fe-4cd7-a946-b45f2065f2b3.png)
![image](https://user-images.githubusercontent.com/112518475/196293306-ec7944d2-389e-4934-8fc0-d2283d759d1b.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
哪里包含集数了？有的话会显示EXX。
解析种子文件后如果文件名不包括集数也是识别不了的，会跳过。

**Comment by XINGYUZHMM** [comment]
> 哪里包含集数了？有的话会显示EXX。 解析种子文件后如果文件名不包括集数也是识别不了的，会跳过。

可是这是一整季啊。我是同步豆瓣然后不自动下载，手动按刷新按钮下载一整季，以前都可以识别出一整季下载的。
