### ISSUE TITLE
2.2.2 快速搜索与高级搜索下过滤规则无效

### ISSUE THREAD

**Issue by ati121** [jxxghp/nas-tools#1679]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2 f6d9839
>
> 环境: docker 
无意中发现快速搜索与高级搜索下过滤规则无效..用默认规则测试了几次都一样. 默认小于30G过滤原盘之类.搜索后无一过滤.全出来了
![9](https://user-images.githubusercontent.com/72114654/196302679-598acb47-e64b-4074-8ec4-c135eb730dd5.jpg)
![66](https://user-images.githubusercontent.com/72114654/196302813-a41bc4f8-15fc-4baa-9302-7554936e4476.jpg)

**Comment by git-0101** [comment]
这两个模式默认就是不过滤应该。为了搜索时搜不到，然后直接再快速搜索。

**Comment by ati121** [comment]
> 这两个模式默认就是不过滤应该。为了搜索时搜不到，然后直接再快速搜索。

噢.之前没试过.这两个如果默认不过滤就那就只有走TMDB模式搜索过滤

**Comment by jxxghp** [comment]
就是这么设计的
