### ISSUE TITLE
请求更新资源搜索方式

### ISSUE THREAD

**Issue by Soff-X** [jxxghp/nas-tools#168]
在订阅里面点立即搜索搜不出来，搜索资源也搜不出来
![1653320790(1)](https://user-images.githubusercontent.com/46675694/169858069-e5f80a9b-a657-4252-b4bd-7c99496b4d62.jpg)
输入日语才能出来
![image](https://user-images.githubusercontent.com/46675694/169858037-d21c722c-fa3a-403d-b39f-c92e21dcfaa1.png)

**Comment by jxxghp** [comment]
这个是核心功能，不是程序Bug，自己研究一下吧
