### ISSUE TITLE
只设置下载目录的标签不能转移文件

### ISSUE THREAD

**Issue by git-0101** [jxxghp/nas-tools#1682]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境: docker
>

## 你遇到什么问题了？

> 新版本现在在qb里设置不自动下载也不生效，另外自动管理模式逻辑也有问题。自动管理与否应该看qb设置。nt下载文件设置里设置了标签和路径，qb设置了自动管理模式。这时候应该在qb生成一个相对应的分类，并且是前面设置的这个路径的分类。还是自动管理模式。现在这样设置默认就是手动管理模式。现在如果只填标签是自动管理模式，然后默认会在qb的默认下载地址下生成这两个分类。右键看qb的分类，这时候分类地址是空的，虽然下载确实能下进来，但是转移时不能识别地址，导致转移失败。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 改进下载目录设置逻辑修复bug

## 给出程序界面截图、后台运行日志或配置文件

> 
![Screenshot_20221018_082102](https://user-images.githubusercontent.com/115487446/196310696-43a74dfa-8628-4064-9519-fbe1db3fca5f.jpg)

**Comment by jxxghp** [comment]
你要用qb自动管理，就用目录同步。
要用nastool的目录管理就填好目录。
