### ISSUE TITLE
希望能够增加下载请求的功能

### ISSUE THREAD

**Issue by hijakke** [jxxghp/nas-tools#1684]
> NASTool 版本: v2.2.2 63a3aedb
>
> 环境: docker
## 你想要新增或者改进什么功能？

给家人开下载用户让他们下载自己想看的资源，但是家人并不清楚要下载哪个资源，或者我不想他们可以直接操作我的PT账号进行下载。

所以需要增加下载请求功能，只提交想看的资源，由我来完成资源的搜索和下载。

## 这个功能有什么可以参考的资料吗？

>overseerr等同类软件中有此功能

**Comment by link2fun** [comment]
如果是要自动化 那么 用豆瓣的 想看 功能
如果要手动 直接微信告诉你不就行了

你是要半自动? 手动添加订阅 你来筛选资源? 这会不会很奇怪.....

**Comment by hijakke** [comment]
> 如果是要自动化 那么 用豆瓣的 想看 功能 如果要手动 直接微信告诉你不就行了
> 
> 你是要半自动? 手动添加订阅 你来筛选资源? 这会不会很奇怪.....

不需要自动化，自动化下载的资源并不一定是我想要的，而且我PT站点有好几个，我还是希望手动选择资源。

当然微信上直接说也是一个方式，只是不太高效，方便和准确。

我理想的状态是，可以专门开个nastool的账号，只开资源搜索功能提供给朋友和家人，他们只是提交想看的片，我来决定下载不下载或者下载什么样的资源。overseerr中是有这个功能的。

**Comment by link2fun** [comment]
> > 如果是要自动化 那么 用豆瓣的 想看 功能 如果要手动 直接微信告诉你不就行了
> > 你是要半自动? 手动添加订阅 你来筛选资源? 这会不会很奇怪.....
> 
> 不需要自动化，自动化下载的资源并不一定是我想要的，而且我PT站点有好几个，我还是希望手动选择资源。
> 
> 当然微信上直接说也是一个方式，只是不太高效，方便和准确。
> 
> 我理想的状态是，可以专门开个nastool的账号，只开资源搜索功能提供给朋友和家人，他们只是提交想看的片，我来决定下载不下载或者下载什么样的资源。overseerr中是有这个功能的。

nastool 好像是可以集成 overseerr的, 有个接口设置, 你配置下

**Comment by jxxghp** [comment]
现在就支持overseerr和jellyseerr啊
