### ISSUE TITLE
当从豆瓣网页中取名字时，如果有简繁两个名字，则会重新拼接

### ISSUE THREAD

**Issue by EkkoG** [jxxghp/nas-tools#1685]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境: docker
>

## 你遇到什么问题了？

> 当从豆瓣网页中取名字时，如果有简繁两个名字，则会重新拼接，名字就不对了

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 只取简体名字

## 给出程序界面截图、后台运行日志或配置文件

问题代码示例

```python
title = '笼民 籠民'
if StringUtils.is_chinese(title) and " " in title:
    titles = title.split()
    title = titles[0]
    for _title in titles[1:]:
        if not StringUtils.is_japanese(_title) \
                and not StringUtils.is_korean(_title):
            title = f"{title} {_title}"
            break
        else:
            break

print(title)
```

在项目中的位置 https://github.com/jxxghp/nas-tools/blob/f6d9839a6dd57169412f6941450b51f843d794cd/app/media/douban.py#L140

**Comment by jxxghp** [comment]
刚刚改好也

**Comment by jxxghp** [comment]
修复了
