### ISSUE TITLE
剧集重命名时，可以带上tmdb的剧集标题

### ISSUE THREAD

**Issue by EliteOtaku** [jxxghp/nas-tools#1686]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2 dd112f72
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望在剧集重命名时，可以带上tmdb的标题
![image](https://user-images.githubusercontent.com/29235152/196323663-2fccae15-ef10-4a16-9896-ffb108cbab8c.png)
目前刮削的时候，按默认的{title} ({year})/Season {season}/{title}-{part} - {season_episode}，刮削出来的没有剧集的标题（不是title）。
希望增加一个代码，可以在重命名时，带上剧集的标题，比如
https://www.themoviedb.org/tv/94997-house-of-the-dragon/season/1
![image](https://user-images.githubusercontent.com/29235152/196323952-caeda7c4-25dc-433e-8c09-60584c39d311.png)
估计需要考虑原语种和中文标题两种代码，希望开发者大大能考虑一下这个需求，非常感谢！

**Comment by Shurelol** [comment]
集命的问题是，如果你是追剧，那么很可能在你下到最新一集时，tmdb上还没有更新这一集的标题或者中文标题

**Comment by EliteOtaku** [comment]
> 集命的问题是，如果你是追剧，那么很可能在你下到最新一集时，tmdb上还没有更新这一集的标题或者中文标题

humm，确实，这个nastool没法解决，只能指望tmdb上更新的快一些了。
