### ISSUE TITLE
请求支持配置FlareSolverr以解决部分站点开启防护盾

### ISSUE THREAD

**Issue by lcylgs** [jxxghp/nas-tools#1687]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境: docker 

## 你想要新增或者改进什么功能？

> 支持配置FlareSolverr以解决部分站点开启防护盾

## 这个功能有什么可以参考的资料吗？

> https://github.com/FlareSolverr/FlareSolverr

**Comment by hijakke** [comment]
比较奇怪的是我用jackett + flaresolverr 也访问不了馒头，但是nastool直接可以。

**Comment by huluohu** [comment]
> 比较奇怪的是我用jackett + flaresolverr 也访问不了馒头，但是nastool直接可以。

因为Nastool已经内置了headless browser

**Comment by baozaodetudou** [comment]
nastool已经内置无界面浏览器来进行站点的访问签到等，针对馒头等站点也有内置的索引器了；已经解决了防护盾的问题了

**Comment by lcylgs** [comment]
> 



> nastool已经内置无界面浏览器来进行站点的访问签到等，针对馒头等站点也有内置的索引器了；已经解决了防护盾的问题了

btschool站点签到失败，应该是防护盾的问题。

**Comment by jxxghp** [comment]
> > 
> 
> > nastool已经内置无界面浏览器来进行站点的访问签到等，针对馒头等站点也有内置的索引器了；已经解决了防护盾的问题了
> 
> btschool站点签到失败，应该是防护盾的问题。

btschool 支持签到了，站点维护打开浏览器仿真
