### ISSUE TITLE
首页媒体库数量与实际不一致

### ISSUE THREAD

**Issue by HarryChong** [jxxghp/nas-tools#1688]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境: Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
首页媒体库数量与实际不一致，jellyfin实际总量是100电影，5电视剧，但nastool统计时总是多一个，不知道为何

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
> 已经查找issues，但未找到解决方案

## 你期望的结果

> 描述以下你期望的结果
希望统计正常，和jellyfin媒体库数量保持一致
## 给出程序界面截图、后台运行日志或配置文件

> 截图
媒体库截图：
<img width="1580" alt="image" src="https://user-images.githubusercontent.com/13514061/196348475-bd7a7d08-bd9e-4898-b8c3-b33f938e92fb.png">
nastool截图：
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/13514061/196348629-a1a36bd0-312c-43f5-862f-1e5fe27a4f91.png">
后台日志截图：
<img width="760" alt="image" src="https://user-images.githubusercontent.com/13514061/196348837-ee24b652-6262-49d5-be1c-d6d7a9e25be8.png">

**Comment by hijakke** [comment]
同样一直有这个问题，而且最近音乐一项也一直显示1，我在emby里面没有添加音乐库。

**Comment by jxxghp** [comment]
API返回的，我也不知道为啥

**Comment by HarryChong** [comment]
> API返回的，我也不知道为啥
如果是API的话是不是只能卸载重新安装才行，有没有其它解决办法能试试，比如清除nastool的媒体库缓存，重新匹配
