### ISSUE TITLE
对于部分资源 server酱 发送的消息不完整

### ISSUE THREAD

**Issue by ijkzen** [jxxghp/nas-tools#1691]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境: docker
>

## 你遇到什么问题了？

> server酱发送的消息不完整

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的，issues 并没有 server酱的相关问题

## 你期望的结果

> server酱发送的信息完整

## 给出程序界面截图、后台运行日志或配置文件
日志里的发送的消息，中间有个空格，可能是因为这个；
![image](https://user-images.githubusercontent.com/31531836/196393896-8919a14d-540b-46d6-abd4-c2d105237d45.png)
微信里收到的消息内容
![3866da0dbb4aad125e65c5d2e281d9d](https://user-images.githubusercontent.com/31531836/196394152-0e5c8a00-e921-4f55-8f91-9470c70a9b6e.jpg)

**Comment by jxxghp** [comment]
看了下代码，是有编码的，感觉是title不能显示太长的原因。
这个消息内容优化了，更新下代码后试试下，有问题再重新打开吧。
