### ISSUE TITLE
硬链接失败 错误码：1

### ISSUE THREAD

**Issue by zero617** [jxxghp/nas-tools#1696]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境: windows11
>

## 你遇到什么问题了？

> 在同一块硬盘下硬链接失败 错误码：1
> 尝试过使用管理员运行程序，无效

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已经浏览过Issues、Wiki及TG公众号仍无法解决

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> ![image](https://user-images.githubusercontent.com/67105838/196439144-25969f05-4f9f-4fef-9d73-6352308b4ffa.png)

**Comment by ccculing** [comment]
![Screenshot_20221022_205144.jpg](https://user-images.githubusercontent.com/103477836/197339966-48e6b298-abcf-4335-a2bb-7aab570a9bbd.jpg)

**Comment by lywly** [comment]
@zero617 请问最后怎么解决的啊，我现在遇到的问题和你一样。如果有解决方案了麻烦细说一下，谢谢，抱拳

## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.1
>
> 环境: windows 11
>

## 你遇到什么问题了？

> 在同一个盘内转移韩剧[`请回答1988`](https://www.themoviedb.org/tv/64010-1988)报错：`硬链接失败，错误码1`
<img width="544" alt="Snipaste_2022-10-29_18-23-41" src="https://user-images.githubusercontent.com/31092835/198827321-7c3dffa7-69a6-49ae-858c-b411cc220b69.png">

## 给出程序界面截图、后台运行日志或配置文件
> 配置文件如下
[config.txt](https://github.com/jxxghp/nas-tools/files/9893477/config.txt)
> 运行日志截图
<img width="540" alt="Snipaste_2022-10-29_18-25-14" src="https://user-images.githubusercontent.com/31092835/198827308-1f942ff2-b9b9-4208-b4e1-77726105ba0e.png">

**Comment by Crazy-FuQing** [comment]
同问    nastool_win_v2.3.1  win10
![image](https://user-images.githubusercontent.com/46838021/198861322-eee4f54c-ef82-4da4-9637-5f67216c19e5.png)

**Comment by zero617** [comment]
> 同问 nastool_win_v2.3.1 win10 ![image](https://user-images.githubusercontent.com/46838021/198861322-eee4f54c-ef82-4da4-9637-5f67216c19e5.png)

我最新版也出现了这个问题，连移动都不行了

**Comment by Crazy-FuQing** [comment]
源和目的是同一个文件夹中的两个文件夹  也会报错误1
![image](https://user-images.githubusercontent.com/46838021/198861575-0f9b0155-0394-4999-9524-d4a1aa94c23a.png)

**Comment by Crazy-FuQing** [comment]
选择同步方式中的所有模式都会报错误1

**Comment by lywly** [comment]
刚更新了v2.3.2 [`728d79b`](https://github.com/jxxghp/nas-tools/commit/728d79b5dfc90f7dc634e355fb59cc91ffd4902d)，还是一样的[问题](https://github.com/jxxghp/nas-tools/issues/1696#issuecomment-1295801567)

<img width="540" alt="Snipaste_2022-10-30_16-51-18" src="https://user-images.githubusercontent.com/31092835/198870421-bd871ef5-f70b-46d1-88a8-a04343fffdf1.png">

@jxxghp 大佬看看，需要什么信息我可以提供，期待修复

**Comment by jxxghp** [comment]
@Shurelol

**Comment by Shurelol** [comment]
win平台的，目录同步路径换成\试试。
打开编辑，直接保存应该就会变

**Comment by lywly** [comment]
有效，手动识别的时候也需要调整为`\`

**Comment by lywly** [comment]
再试第二部电影[阿凡达](https://www.themoviedb.org/movie/19995-avatar)的时候又不行了
<img width="539" alt="Snipaste_2022-10-30_19-16-14" src="https://user-images.githubusercontent.com/31092835/198875754-1c4bb17a-c85e-4534-b9fc-b487d13ec939.png">
<img width="538" alt="Snipaste_2022-10-30_19-17-12" src="https://user-images.githubusercontent.com/31092835/198875756-1a781b54-6fbe-4c3c-b7e4-c4a5553cf9cf.png">
