### ISSUE TITLE
豆瓣一直登录失败报错，微信收不到消息推送

### ISSUE THREAD

**Issue by fxqq** [jxxghp/nas-tools#170]
1、豆瓣一直拉不到数据，报错如下
<img src="https://img.picgo.net/2022/05/24/QQ20220524193613.png" alt="QQ20220524193613.png" border="0">
2、微信收不到消息通知，看日志里也有报错不知道原因，微信配置的url回调地址是填的基础设置里填的地址，地址是可以外网访问的，之前是可以的，但是现在收不到信息了
<img src="https://img.picgo.net/2022/05/24/QQ20220524194014.png" alt="QQ20220524194014.png" border="0">
<img src="https://img.picgo.net/2022/05/24/QQ20220524194320.png" alt="QQ20220524194320.png" border="0">

**Comment by jxxghp** [comment]
你的容器连不上外网，微信也连不上。

**Comment by fxqq** [comment]
> 你的容器连不上外网，微信也连不上。

我是用的unraid。所以是需要这个docker设置为host模式吗？目前是bridge模式
