### ISSUE TITLE
HTTPSConnectionPool超时，希望超时参数能改长一点

### ISSUE THREAD

**Issue by Loyoan** [jxxghp/nas-tools#1701]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境: docker（Synology）
>

## 你遇到什么问题了？

> 在网络不太好的情况下会经常出现连接超时的错误：ERROR - 【Meta】连接TMDB出错：HTTPSConnectionPool(host='tmdb.nastool.cn', port=443): Read timed out. (read timeout=5)，希望可以吧超时时间改长一点

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> Issues列表未找到

## 你期望的结果

> 希望能吧这个参数改长一点

## 给出程序界面截图、后台运行日志或配置文件

>![image](https://user-images.githubusercontent.com/9997604/196574068-b4e51631-bffb-4b0e-b3c2-0590f521e2ec.jpeg)

**Comment by jxxghp** [comment]
dev已经改成10s
