### ISSUE TITLE
RSS订阅新下载的视频在Plex中显示【不可用】的问题

### ISSUE THREAD

**Issue by AkaiShuichi7** [jxxghp/nas-tools#1702]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境: docker
> 媒体服务器: Plex
> 目录同步方式: 复制
>

## 你遇到什么问题了？

> 通过RSS订阅，自动下载视频，企业微信会直接通知【开始下载】和【同步完成】，没有时间间隔；通过目录同步方式为【复制】将视频文件同步到媒体库文件夹下，文件确实是同步过去了，但是在Plex中无法进行播放，显示【不可用】，然后删除媒体库中的文件，手动执行【服务】->【清理转移缓存】->【目录同步】操作重新同步后，Plex中的视频就可以播放，不再显示【不可用】了。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 日志一切正常。

**Comment by link2fun** [comment]
https://github.com/jxxghp/nas-tools/issues/1667
