### ISSUE TITLE
美剧<24小时>的第24集无法正确识别

### ISSUE THREAD

**Issue by wyyqyl** [jxxghp/nas-tools#1709]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2 2dc7f126
>
> 环境: docker
>

## 你遇到什么问题了？

> [24小时](https://www.themoviedb.org/tv/1973-24) 每一季的第二十四集都无法识别 其他集都可以识别
难道是名字和集数都是24导致的bug?

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 能识别第二十四集

## 给出程序界面截图、后台运行日志或配置文件

<img width="527" alt="S05E23" src="https://user-images.githubusercontent.com/787659/196690723-efd8b6a1-e838-44dd-a43a-a65cf3a2159f.png">
<img width="528" alt="S05E24" src="https://user-images.githubusercontent.com/787659/196690747-e8eadb81-4f88-4e51-beb7-99ac353ce802.png">
<img width="345" alt="file" src="https://user-images.githubusercontent.com/787659/196691107-3656e694-5c78-4d4d-b621-da5f0b092a15.png">

**Comment by ZiGmaX809** [comment]
测试好像剧名和E24冲突导致无法识别，不光S05其他季也会识别失败

替换成中文名可以识别，添加以下替换：

被替换词：(?<=24)(\.S\d+E\d+)(?=\.)      

替换词：小时\1

![CleanShot 2022-10-20 at 09 11 46](https://user-images.githubusercontent.com/25289280/196833042-4a9cf231-5d27-4f99-a82a-0ef6f0bb753a.png)

![CleanShot 2022-10-20 at 09 12 14](https://user-images.githubusercontent.com/25289280/196833066-c5a4efa6-9198-4826-9c08-6c39d40c725c.png)
