### ISSUE TITLE
自动更新无效， 本地莫名有未提交的commit

### ISSUE THREAD

**Issue by JohnZp** [jxxghp/nas-tools#171]
![image](https://user-images.githubusercontent.com/25192317/170048734-63657bb1-4512-4df4-8b2f-97e4b5e15b0a.png)

**Comment by devome** [comment]
什么操作系统

**Comment by JohnZp** [comment]
> 



> 

docker, 建议在git pull 之前 git checkout .

**Comment by jxxghp** [comment]
除了配置文件目录，程序不会读写任何容器内的文件，除非你没有把配置目录映射出来

**Comment by BarryLoo** [comment]
2.0.3版本。git更新的尾缀修一下

![image](https://user-images.githubusercontent.com/12878832/187714698-29cf683d-954c-488d-9915-d82ff232169a.png)

**Comment by BarryLoo** [comment]
> 2.0.3版本。git更新的尾缀修一下
> 
> ![image](https://user-images.githubusercontent.com/12878832/187714698-29cf683d-954c-488d-9915-d82ff232169a.png)

`.git/`
