### ISSUE TITLE
报错 执行SQL出错

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#1711]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2 9c60da44
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
20:53:26 ERROR - 【Db】执行SQL出错：sql:SELECT ID, IGNORED, ENABLED FROM IGNORED_WORDS; parameters:None; no such table: IGNORED_WORDS
20:53:26 ERROR - 【Db】执行SQL出错：sql:SELECT ID, REPLACED, REPLACE, ENABLED FROM REPLACED_WORDS; parameters:None; no such table: REPLACED_WORDS
20:53:26 ERROR - 【Db】执行SQL出错：sql:SELECT ID, FRONT, BACK, OFFSET, ENABLED, REPLACED_WORD_ID FROM OFFSET_WORDS; parameters:None; no such table: OFFSET_WORDS
20:53:26 ERROR - 【Db】执行SQL出错：sql:DROP TABLE IGNORED_WORDS; parameters:None; no such table: IGNORED_WORDS
20:53:26 ERROR - 【Db】执行SQL出错：sql:DROP TABLE REPLACED_WORDS; parameters:None; no such table: REPLACED_WORDS
20:53:26 ERROR - 【Db】执行SQL出错：sql:DROP TABLE OFFSET_WORDS; parameters:None; no such table: OFFSET_WORDS

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
无

> 描述以下你期望的结果

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
20:53:26 ERROR - 【Db】执行SQL出错：sql:SELECT ID, IGNORED, ENABLED FROM IGNORED_WORDS; parameters:None; no such table: IGNORED_WORDS
20:53:26 ERROR - 【Db】执行SQL出错：sql:SELECT ID, REPLACED, REPLACE, ENABLED FROM REPLACED_WORDS; parameters:None; no such table: REPLACED_WORDS
20:53:26 ERROR - 【Db】执行SQL出错：sql:SELECT ID, FRONT, BACK, OFFSET, ENABLED, REPLACED_WORD_ID FROM OFFSET_WORDS; parameters:None; no such table: OFFSET_WORDS
20:53:26 ERROR - 【Db】执行SQL出错：sql:DROP TABLE IGNORED_WORDS; parameters:None; no such table: IGNORED_WORDS
20:53:26 ERROR - 【Db】执行SQL出错：sql:DROP TABLE REPLACED_WORDS; parameters:None; no such table: REPLACED_WORDS
20:53:26 ERROR - 【Db】执行SQL出错：sql:DROP TABLE OFFSET_WORDS; parameters:None; no such table: OFFSET_WORDS

**Comment by jxxghp** [comment]
这个是正常的，无视即可

**Comment by Tartarus2014** [comment]
> 这个是正常的，无视即可

之前没版本没出现过呀😂😂

**Comment by Nothend** [comment]
> > 这个是正常的，无视即可
> 
> 之前没版本没出现过呀😂😂

确实也遇到了，但是好像没什么影响
