### ISSUE TITLE
添加同时推送消息给不同账号，以及不同需求消息。

### ISSUE THREAD

**Issue by mfksss** [jxxghp/nas-tools#1716]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.2
>
> 环境: synology

## 你想要新增或者改进什么功能？

推送消息给几个不同的telegram或微信。只好给后台加入telegram id 或微信添加管理员 ，这样几个好友或家人可以收到更新视频的消息。因为现在像telegram已经可以多个管理员输入下载了。最好可选推送相关内容到相对应的需求id。如个别账号只需转移完成的消息。

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？
无
> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
- 无

**Comment by aerosmith2020** [comment]
关于爱语飞飞推送消息，可否提供多个爱语飞飞token添加。这样可以老婆孩子都可以用，设置简单，易操作。

参考资料：IYUUplus 可以添加多个token，给不同微信账号提供通知。
大佬辛苦了。
