### ISSUE TITLE
媒体库支持电影和电视剧的拼音首字母排序

### ISSUE THREAD

**Issue by sq1220** [jxxghp/nas-tools#1721]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.3 
>
> 环境: docker

## 你想要新增或者改进什么功能？
使emby和jellyfin支持电影和电视剧的拼音首字母排序

**Comment by xyswordzoro** [comment]
是不是傻，去emby jellyfin提

**Comment by sq1220** [comment]
> 是不是傻，去emby jellyfin提

https://github.com/hisune/emby_pinyin  这个不是能做到吗
