### ISSUE TITLE
自定义识别失败

### ISSUE THREAD

**Issue by eschcn** [jxxghp/nas-tools#1722]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.2.3
>
> 环境: docker
>

## 你遇到什么问题了？

> 自定义识别错误,看日志是识别了4次,但是这4次都识别成了第一集,集数定位我用的是: 北斗神拳 拉奥外传 天之霸王{ep}{a}.mkv

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 我希望能识别出13集

## 给出程序界面截图、后台运行日志或配置文件

> 

https://ibb.co/9wvW5mR
https://ibb.co/9pqj5Qt
https://ibb.co/3hs40TD

> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Shurelol** [comment]
北斗神拳 拉奥外传 天之霸王{ep} {a}.mkv
另外第2，3集集数和集名间加上空格

**Comment by eschcn** [comment]
> 
谢谢
{a}这个变量并不能囊括空格吗?
另外大佬能否多出点自定义识别次的正则案例,昨晚看了下你在小秘书发的,网上也搜了些正则教程,看了2小时,也搞不定能适用于这个的正则.

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/197105601-507b83e9-af99-416d-ab1e-2ce2af8f0897.png)
查下tmdb上名字，然后加替换词，集数识别不了就加E

**Comment by eschcn** [comment]
> ![image](https://user-images.githubusercontent.com/16237201/197105601-507b83e9-af99-416d-ab1e-2ce2af8f0897.png) 查下tmdb上名字，然后加替换词，集数识别不了就加E

谢谢,原来这么简单...
