### ISSUE TITLE
关于对接chinesesubfinder

### ISSUE THREAD

**Issue by ershouqingge** [jxxghp/nas-tools#1727]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本:2.23
>
> 环境:群晖套件
>

## 你遇到什么问题了？
>
使用最新docker版chinesesubfinder对接无法下载
视频文件实际源目录在/volume2/video

NASTOOL中设置源目录在/volume2/video，硬链接目的目录在/volume2/video/link
docker版chinesesubfinder将/volume2/video/link装载到/media，chinesesubfinder中设置视频目录为/media
nastool中chinesesubfinder设置本地和远程路径为/volume2/video/link或者/media均失败，提示physical video file not found
是因为路径的问题吗？nastool中chinesesubfinder设置本地和远程路径需要填哪个呢？

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已经浏览过

## 你期望的结果

> 希望可以对接chinesesubfinder正常下载字幕

**Comment by DDS-ALL** [comment]
link 目录

**Comment by DDS-ALL** [comment]
详见 https://github.com/jxxghp/nas-tools/issues/136

**Comment by ershouqingge** [comment]
> 详见 #136

我看到了这个
“重新设置后，可以正常使用。重点是映射必须完全一致，不仅仅针对物理位置。容器内的映射必须要和nas-tool一致，才可以。"

我的视频文件实际源目录在/volume2/video
NASTOOL中设置源目录在/volume2/video，硬链接目的目录在/volume2/video/link
docker版中国esesubfinder将/volume2/video/link装载到/media，chinesesubfinder中设置视频目录为/media

意思是要把docker里设置CSF将/volume2/video/link装载到/video/link吗？
还是把docker里设置CSF将/volume2/video装载到/volume2/video/link？

感谢回复

**Comment by ershouqingge** [comment]
> > 详见 #136
> 
> 我看到了这个 “重新设置后，可以正常使用。重点是映射必须完全一致，不仅仅针对物理位置。容器内的映射必须要和nas-tool一致，才可以。"
> 
> 我的视频文件实际源目录在/volume2/video NASTOOL中设置源目录在/volume2/video，硬链接目的目录在/volume2/video/link docker版中国esesubfinder将/volume2/video/link装载到/media，chinesesubfinder中设置视频目录为/media
> 
> 意思是要把docker里设置CSF将/volume2/video/link装载到/video/link吗？ 还是把docker里设置CSF将/volume2/video装载到/volume2/video/link？
> 
> 感谢回复

但是它要求只能装载到/media下

**Comment by ershouqingge** [comment]
我刚设置了/volume2/video装载到/media/link  还是不行
