### ISSUE TITLE
内置索引器公开站点希望可以编辑地址

### ISSUE THREAD

**Issue by dxbzth** [jxxghp/nas-tools#1729]
> NASTool 版本: 2.2.3
>
> 环境:synology
> 内建索引器公开站点网址自行编辑
> 很多公开站点被墙，翻不出去的其实还有其它地址没有被墙的，例如海盗湾另外的网址：https://tpb.skynetcloud.site/，墙内访问很快。X1337站点，网址：https://x1337x.ws/，墙内访问也很快。如果不能自行编辑，希望将这些网址加入到相关公开站点中。我们这些墙内出墙很麻烦，用了很多的机场关的很快，稳定的机场又价格太高。

**Comment by 15823382203** [comment]
能实现的话。这个可以有。方便自己添加
