### ISSUE TITLE
希望可以按照剧情分类来自动下载到不同的文件夹的功能

### ISSUE THREAD

**Issue by lokyeye** [jxxghp/nas-tools#1732]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>2.2.3 5f9cadcd

> 环境: docker or windows or synology
docker 
## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
希望可以按照剧情分类来自动下载到不同的文件夹的功能，比如科幻剧下载到科幻剧文件家，动作片下载到动作片文件夹这样分
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
你没搞懂怎么用不代表现在就不支持

**Comment by lokyeye** [comment]
大佬！在哪里能找到我要的功能！我在电报群哪里没翻到！跪求大佬指点&nbsp;


┗翻折、寂寞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mr ***@***.***&gt;; 
发送时间: 2022年10月22日(星期六) 上午10:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jxxghp/nas-tools] 希望可以按照剧情分类来自动下载到不同的文件夹的功能 (Issue #1732)





 
你没搞懂怎么用不代表现在就不支持
