### ISSUE TITLE
资源搜索时，会弹出一个黑框

### ISSUE THREAD

**Issue by ilolita945** [jxxghp/nas-tools#1737]
#> NASTool 版本: 2.2.3
>
> 环境: Windows 10
>

## 你遇到什么问题了？

> 资源搜索时，会弹出一个黑框，请问如何隐藏？
![20221022120838](https://user-images.githubusercontent.com/49525838/197318493-7bf9e86f-b5de-4ab1-a40b-18fabcb4d290.png)

**Comment by ilolita945** [comment]
索引器经过一系列排查，弹框为勾选海盗湾所致

**Comment by jxxghp** [comment]
用docker吧
