### ISSUE TITLE
请问整个剧集有办法刮削封面吗？

### ISSUE THREAD

**Issue by YanceyWang** [jxxghp/nas-tools#1738]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
> latest
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

对电视剧通过硬链接进行了连接分类，但是在emby里面对分类的文件夹无法显示封面
![image](https://user-images.githubusercontent.com/6010208/197322250-242f4a12-0878-4e7d-995f-fb9350787725.png)

![image](https://user-images.githubusercontent.com/6010208/197322287-29232ffc-ab7c-42f3-bbf0-a5a6f542d794.png)

## 你期望的结果

> 描述以下你期望的结果

请问emby里面怎么整个聚集刮削封面啊？或者说怎么做能更美观一些。

**Comment by jxxghp** [comment]
仔细看看设置说明，已经有的功能就不要再来提问了
