### ISSUE TITLE
执行SQL出错

### ISSUE THREAD

**Issue by lixiang037** [jxxghp/nas-tools#1739]
## 你使用的 NASTool 是什么版本，什么环境？

16:01:52 INFO - 配置文件地址：/var/packages/nastool/target/config/config.yaml
16:01:52 INFO - NASTool 当前版本号：v2.2.3
dsm7 套件
## 你遇到什么问题了？

16:01:53 ERROR - 【Db】执行SQL出错：sql:SELECT ID, IGNORED, ENABLED FROM IGNORED_WORDS; parameters:None; no such table: IGNORED_WORDS
16:01:53 ERROR - 【Db】执行SQL出错：sql:SELECT ID, REPLACED, REPLACE, ENABLED FROM REPLACED_WORDS; parameters:None; no such table: REPLACED_WORDS
16:01:53 ERROR - 【Db】执行SQL出错：sql:SELECT ID, FRONT, BACK, OFFSET, ENABLED, REPLACED_WORD_ID FROM OFFSET_WORDS; parameters:None; no such table: OFFSET_WORDS
16:01:53 ERROR - 【Db】执行SQL出错：sql:DROP TABLE IGNORED_WORDS; parameters:None; no such table: IGNORED_WORDS
16:01:53 ERROR - 【Db】执行SQL出错：sql:DROP TABLE REPLACED_WORDS; parameters:None; no such table: REPLACED_WORDS
16:01:53 ERROR - 【Db】执行SQL出错：sql:DROP TABLE OFFSET_WORDS; parameters:None; no such table: OFFSET_WORDS

**Comment by link2fun** [comment]
提问前 不会搜索的么? 提示不看的么?

https://github.com/jxxghp/nas-tools/issues/1711
