### ISSUE TITLE
每次转移时都会有这个报错

### ISSUE THREAD

**Issue by leo8912** [jxxghp/nas-tools#174]
![Screenshot_2022-05-25-08-07-39-827_com.android.browser.png](https://user-images.githubusercontent.com/22719866/170151699-8731ca81-6bb5-448d-9d44-9e81f099f817.png)

每次转移都会报这个错，是哪方面问题？

**Comment by jxxghp** [comment]
在日志文件里面看下日志

**Comment by leo8912** [comment]
> 

![Snipaste_2022-05-25_18-00-35](https://user-images.githubusercontent.com/22719866/170239863-324980ac-b7bf-4ee4-9a20-747e8d262acf.png)

不知道这些信息够不够，我搜了下，出现这种类似报错的就这几种情况

**Comment by leo8912** [comment]
![Snipaste_2022-05-25_18-00-57](https://user-images.githubusercontent.com/22719866/170240043-52b78123-b491-4128-be86-6a8481f3d355.png)

![Snipaste_2022-05-25_18-01-35](https://user-images.githubusercontent.com/22719866/170240094-ac611ec0-129b-41e3-bc6f-29a6152633b9.png)

![Snipaste_2022-05-25_18-01-54](https://user-images.githubusercontent.com/22719866/170240148-716dd139-7bb7-4b1e-a8f9-b20fbf7504f6.png)

**Comment by jxxghp** [comment]
感觉是代理的配置问题，你使用WEB页面重新配置保存下看看

**Comment by leo8912** [comment]
> 

那我重新配置再看看

**Comment by leo8912** [comment]
> 感觉是代理的配置问题，你使用WEB页面重新配置保存下看看

我重新设置了一遍没问题了
