### ISSUE TITLE
TMDB No image available 

### ISSUE THREAD

**Issue by woosley** [jxxghp/nas-tools#1740]
Nastools in docker 

## 你遇到什么问题了？

> 描述一下你遇到的问题
![image](https://user-images.githubusercontent.com/61531/197328035-ca11a129-394b-4d17-a144-100dd0144ac8.png)

我自己build 了一个docker image，在/etc/hosts 加上了tmdb的 ip地址用来科学上网。 

问题是现在所有的image都是如上图所示，无法正确显示。 请问这里是通过什么样的方式，在什么地址下载图像？

**Comment by link2fun** [comment]
1. 你自己build, 你怎么build的 改了什么
2. 加 host 完全可以通过映射文件来进行
3. tmdb 提供了内置代理
4. 查看图片地址需要使用开发者控制台 F12, 请自行了解相关知识
