### ISSUE TITLE
希望能增加下载各主流视频网站对应的下载的视频弹幕功能。

### ISSUE THREAD

**Issue by liangliang-wh** [jxxghp/nas-tools#1742]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.3
>
> 环境: docker

## 你想要新增或者改进什么功能？
  
> 你想要新增或者改进什么功能？
   增加自动下载各主流视频网站（bibi、优酷、爱奇艺、腾讯视频）对应的此视频的弹幕功能。
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
   我也没有参考资料咧。

**Comment by link2fun** [comment]
自己装插件去吧
https://blog.xn--7ovq92diups1e.com/post/homelab-emby-danmaku/

https://github.com/std4453/jfdmk

https://www.dandanplay.com/
