### ISSUE TITLE
自定义的RSS订阅出现重复下载的问题

### ISSUE THREAD

**Issue by EliteOtaku** [jxxghp/nas-tools#1745]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.3 5f9cadcb
>
> 环境: docker

## 你遇到什么问题了？

> 用自定义rss订阅时出现了重复下载的问题

http://172.20.0.7:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=lr1dopci18a8eezmzgqr4avwx7gsepwy&t=search&cat=100041&q=The+Peripheral+1080p+NTb

我用jackett作为索引器，用以上链接设为自订阅，然后下载之后
![image](https://user-images.githubusercontent.com/29235152/197336077-d0a514c4-6d91-4a02-bc43-151b7688afd4.png)
已经显示为已处理，然后直接点击运行，不会重复下载，但过一段时间又会重复下载，不知哪里出现了bug。怀疑是rarbg的问题，因为用同样方式处理的mikan的rss订阅没有出现过重复下载的问题。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by EliteOtaku** [comment]
![image](https://user-images.githubusercontent.com/29235152/197338941-b4638549-cee5-4133-b77d-4678d608212b.png)
就在刚才，我刷新后发现已经下载的剧集又变成未处理……

**Comment by EliteOtaku** [comment]
![image](https://user-images.githubusercontent.com/29235152/197338980-4c6fd417-4259-4f6f-b665-0091baf371d7.png)
我目前自定义订阅中，mikan那几个都没有出现重复下载的情况，就是rarabg的会出现，有点莫名其妙了

**Comment by EliteOtaku** [comment]
![image](https://user-images.githubusercontent.com/29235152/197342764-25e20dba-6e55-40a0-aaad-c26953883ea5.png)
呃，发现自己可能是误解了这个设定，现在改为订阅模式，看看是否会出现问题，如果恢复正常，说明需要用订阅模式才是正确的。

**Comment by EliteOtaku** [comment]
2021-11-18 06:06:17

再次测试后发现，RSS用下载模式会出错的，确实只有rarbg，我联想起rarbg有一个人机检测功能，就是需要你登陆一下，输入识别码后才会正常访问。
![image](https://user-images.githubusercontent.com/29235152/197365106-793172d9-ae0a-46c1-9f42-387593fdac35.png)


目前我发现的情况是，如果一段时间没打开rarbg网页，那么nastool里面的rarbg RSS订阅就无法获得报文，需要登陆后，通过了识别码才会进入网站，这时候再去预览rarbg的RSS订阅，就会发现可以获得报文了，但是获得的结果会全部变成未处理的情况，估计这就是造成出现重复下载的原因。希望开发者可以留意下，这个问题还是有点烦人的……

**Comment by link2fun** [comment]
首先 有下载链接的订阅 确实应该用 下载类型
其次 需要更多日志 
最后 判重是根据下载链接来进行的, 请留意 RSS 报文的下载链接是否在发生变化
最最后 为啥不用内置的?

**Comment by EliteOtaku** [comment]
> 首先 有下载链接的订阅 确实应该用 下载类型 其次 需要更多日志 最后 判重是根据下载链接来进行的, 请留意 RSS 报文的下载链接是否在发生变化 最最后 为啥不用内置的?

首先非常感谢及时回复，我想问一下，如果用下载类型的话，那么刷新间隔是按RSS自定义里面的时间，还是按搜索间隔？
![image](https://user-images.githubusercontent.com/29235152/197365903-bda820a5-de37-4f17-a214-968b99a51e5f.png)
我这里RSS订阅是30分钟刷新一次，搜索间隔默认就是一天一次……


我也想提供详细的日志，但因有刷流日志的干扰，难以找出准确出错的内容。看到你提起判重，我怀疑是rarbg提供的rss报文下载链接有变化导致的，等后面我再测试一下看看。

内置的现在是有所改进，但对于rarbg来说，依然会收到人机检测的干扰，所以有时候搜不到，我有时候和jackett会轮流切换使用。

**Comment by EliteOtaku** [comment]
https://github.com/jxxghp/nas-tools/issues/1047 搜了下，貌似是CF的锅……我暂时观望了……

**Comment by link2fun** [comment]
> > 首先 有下载链接的订阅 确实应该用 下载类型 其次 需要更多日志 最后 判重是根据下载链接来进行的, 请留意 RSS 报文的下载链接是否在发生变化 最最后 为啥不用内置的?
> 
> 首先非常感谢及时回复，我想问一下，如果用下载类型的话，那么刷新间隔是按RSS自定义里面的时间，还是按搜索间隔？ ![image](https://user-images.githubusercontent.com/29235152/197365903-bda820a5-de37-4f17-a214-968b99a51e5f.png) 我这里RSS订阅是30分钟刷新一次，搜索间隔默认就是一天一次……
> 
> 我也想提供详细的日志，但因有刷流日志的干扰，难以找出准确出错的内容。看到你提起判重，我怀疑是rarbg提供的rss报文下载链接有变化导致的，等后面我再测试一下看看。
> 
> 内置的现在是有所改进，但对于rarbg来说，依然会收到人机检测的干扰，所以有时候搜不到，我有时候和jackett会轮流切换使用。

刷新时间是 订阅里面的
![image](https://user-images.githubusercontent.com/19241982/197367765-5597ced9-a8bd-4f2f-bb6f-2915abf39608.png)

**Comment by EliteOtaku** [comment]
刚才用1337x测试了下，用的是下载模式，居然也会出现重复下载的问题，而且1337x并没有人机检验机制……这就有点奇怪了
