### ISSUE TITLE
订阅日历加载容易卡界面

### ISSUE THREAD

**Issue by ilolita945** [jxxghp/nas-tools#1749]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.3
>
> 环境: Windows 10 21H2
>

## 你遇到什么问题了？

> 订阅日历加载很卡，会导致页面浏览器页面卡死（40个订阅）

## 你期望的结果

> 日历使用缓存，不用每次点开都全部查询一轮，或者默认按周/日程显示，这样信息量小没那么卡

## 给出程序界面截图、后台运行日志或配置文件

> 
![20221022215859](https://user-images.githubusercontent.com/49525838/197343103-7099403d-362c-4824-a489-0367d8e54583.png)

![20221022220051](https://user-images.githubusercontent.com/49525838/197343219-ffa385da-68d4-4125-867c-2804aa48b95e.png)

**Comment by jxxghp** [comment]
现在是有缓存的，缓存128个请求，超过了才会重新请求

**Comment by ilolita945** [comment]
要不把默认按月改为按周显示 这样点进去不会卡，因为本身没有记忆  点到就卡十几秒

**Comment by jxxghp** [comment]
加大了缓存，改成默认显示周（但其实所有信息还是会加载，并没有什么用）

**Comment by ilolita945** [comment]
感谢大佬优化
