### ISSUE TITLE
页面推荐豆瓣图片无法加载

### ISSUE THREAD

**Issue by zwf19870623** [jxxghp/nas-tools#175]
在页面的推荐项目中，tmdb加载正常，豆瓣的所有电影图片都无法加载。

复制了两个右键图片的链接地址
javascript:show_media_info('dbhm', '%E7%9E%AC%E6%81%AF%E5%85%A8%E5%AE%87%E5%AE%99', '', '', '30314848', '7.8')
javascript:show_media_info('dbhm', '%E5%A5%87%E5%A5%87%E4%B8%8E%E8%92%82%E8%92%82%EF%BC%9A%E6%95%91%E6%8F%B4%E7%AA%81%E5%87%BB%E9%98%9F', '', '', '33957717', '7.3')

我看配置文档中有cookie选项，但是页面中没有，和这个有关吗（如果需要的话，能否也加入到页面配置中），还是需要把豆瓣某个地址也加入科学列表中

**辛苦作者大大~~**

下面是具体截图

![FireShot Capture 002 - NASTool - nt zhaoyuhuai com](https://user-images.githubusercontent.com/49951252/170154325-d0017081-1aa2-45c5-bd6a-e8ece769a90a.png)

**Comment by jxxghp** [comment]
看WIKI常见问题，webservice.fanart.tv 需要代理
