### ISSUE TITLE
自定义识别词能够用于识别命名

### ISSUE THREAD

**Issue by ilolita945** [jxxghp/nas-tools#1750]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.3
>
> 环境: Windows 10 21H2

## 你想要新增或者改进什么功能？

> 自定义识别词能够用于识别命名（手动修正命名）

![1](https://user-images.githubusercontent.com/49525838/197343939-c4e9012e-2aa5-4902-992c-0528ace25923.png)
![2](https://user-images.githubusercontent.com/49525838/197343941-e93eb9af-7b49-46ea-8468-1ddd10e22b8b.png)
![3](https://user-images.githubusercontent.com/49525838/197343944-ab8fe6bd-1f79-444f-9114-b11daf254f30.png)
![4](https://user-images.githubusercontent.com/49525838/197343949-716115fc-66aa-4da6-bb92-3875937a39a0.png)

**Comment by link2fun** [comment]
虽然但是 你好像写反了, 替换词与 被替换词

**Comment by ilolita945** [comment]
反过来也不行，可以加个吗

**Comment by ilolita945** [comment]
![FS~Z(J_J6_15ULAERZL%73K](https://user-images.githubusercontent.com/49525838/197367099-6e59856a-f52c-437e-ae00-db7f4ade51f2.png)
在这里加个可以用于命名选项吧

**Comment by link2fun** [comment]
哦哦哦 我理解错了.... 你是想覆盖 TMDB 返回的 媒体名称
........
建议你试一下 TMDB 缓存的修改功能
![image](https://user-images.githubusercontent.com/19241982/197367687-ef146b92-46c7-4732-be5f-9a930f6d0701.png)
![image](https://user-images.githubusercontent.com/19241982/197367691-1cd629bb-971f-49c3-b255-69a1363aa077.png)

可能会有用

**Comment by ilolita945** [comment]
这里我试着将“4个人各自有着自己的秘密”改为“四个人各自有着自己的秘密”不行，点击修改了没反应
![111](https://user-images.githubusercontent.com/49525838/197367731-ba280939-955e-4ce4-82c6-7d0b313b5c4f.png)

**Comment by xyswordzoro** [comment]
![QQ截图20221023211207](https://user-images.githubusercontent.com/86150433/197394247-f660186c-7467-4390-9ade-a9ae62f1751c.png)
你是不是有什么误解  tmdb的标题就是这样的 是根据tmdb的命名来的

**Comment by ilolita945** [comment]
我没有误解，详见#1755
