### ISSUE TITLE
高清MP4吧的访问URL有错误

### ISSUE THREAD

**Issue by Jie2GG** [jxxghp/nas-tools#1753]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.3
>
> 环境: docker or Synology
>

## 你遇到什么问题了？

> NASTool无法访问搜索结果为**高清MP4吧**的项

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 期望更正获取的URL

## 给出程序界面截图、后台运行日志或配置文件

> 程序日志无问题, 初步排查原因可能是URL解析错误, 导致 NAS-Tool 访问的URL后多了一个 "!" 导致访问失败. 具体可看下两张图

![image](https://user-images.githubusercontent.com/39112172/197370467-05ae82c9-594a-4977-b43d-9a07aa638379.png)
![image](https://user-images.githubusercontent.com/39112172/197370506-11f7eaae-cf92-4c68-9253-cd41eb97ef61.png)

**Comment by jxxghp** [comment]
```
show_fail_modal(name + " 添加下载失败 " + ret.retmsg + "！");
```
不是这个原因，那个！号是自己加的。貌似这个网站开了反爬

**Comment by Jie2GG** [comment]
原来是这样, 我以为是URL错误导致的. 感谢修复
