### ISSUE TITLE
名称识别测试没问题，转移时提示无法识别媒体信息。

### ISSUE THREAD

**Issue by fallenyy** [jxxghp/nas-tools#1754]
## 环境，版本

> NASTool 版本: v2.2.3 5f9cadcb
>
> 环境: docker
>

## 你遇到什么问题了？

> 文件“斗破苍穹年番.Fights.Break.Sphere.2022.S01E15.2160p.WEB-DL.H265.AAC-OurTV.mp4 ”通过名称识别测试没问题，RSS正确下载。但是识别转移时失败。提示无法识别媒体信息。

## 相关日志与截图
>

11:03:18 INFO - 【RMT】开始处理：/NAStools源目录/斗破苍穹年番.Fights.Break.Sphere.S01.2022.2160p.WEB-DL.H265.AAC-OurTV，转移方式：复制
11:03:18 WARN - 【RMT】斗破苍穹年番.Fights.Break.Sphere.2022.S01E15.2160p.WEB-DL.H265.AAC-OurTV.mp4 无法识别媒体信息！
11:03:18 ERROR - 【RMT】斗破苍穹年番.Fights.Break.Sphere.2022.S01E15.2160p.WEB-DL.H265.AAC-OurTV.mp4 无法识别媒体信息！
![名称是别测试](https://user-images.githubusercontent.com/70746058/197371476-4977858a-a5e4-431c-86a8-31d99f59c29e.png)

![image](https://user-images.githubusercontent.com/70746058/197371562-821bfede-9e41-49d4-90d0-8d780a3a0c83.png)

**Comment by pikaqiu2222** [comment]
tmdbid都没出来肯定是没成功识别啊

**Comment by fallenyy** [comment]
> tmdbid都没出来肯定是没成功识别啊

感谢大佬解惑！确实是没识别。替换词有误。
