### ISSUE TITLE
希望能对单部作品指定转移路径和独立的命名规则

### ISSUE THREAD

**Issue by ilolita945** [jxxghp/nas-tools#1755]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.3
>
> 环境: Windows 10 21H2

## 你想要新增或者改进什么功能？

> 希望能对单部作品指定转移路径和独立的命名规则，用于解决本地标题与TMDB标题不符以及存盘位置不同问题。
> 意图很简单，自动订阅下载完成命名后转移可以依照本地结构来满足不同需求

大概这样
![photo_2022-10-23_11-41-57](https://user-images.githubusercontent.com/49525838/197372796-4b67b8a2-1ac3-4f6c-9e8e-13018ba6e05f.jpg)

这是我的媒体库
![QQ截图20221023115412](https://user-images.githubusercontent.com/49525838/197372866-93e681ee-ec7c-41c2-be8c-b90b2e06e0bd.png)

这是我设置的同步目录
![QQ截图20221023115421](https://user-images.githubusercontent.com/49525838/197372869-d787db5e-bfc9-4807-8074-f440ba6ba054.png)

实际效果：
订阅下载转移——W:\「连载动画」\电锯人 (2022)\Season 1\S01Exx  （这是订阅转移命名后的）
想要的效果——  Z:\「连载动画」\链锯人 (2022)\Season 1\S01Exx  （这是我本地实际标题和存放盘的路径）

这样能解决#1304、#1750反馈的问题同时还能满足不同需求

其它工具与此相比，意图很简单，设置关键字、保存路径、设置下载订阅的地址
![222](https://user-images.githubusercontent.com/49525838/197373155-4c7c37cb-b9b2-4be9-8a6f-c158f2619e13.png)

所以这次提建议目的也是为了满足一个需求，自动订阅+手动参与修正标题和存盘路径问题

**Comment by jxxghp** [comment]
虽然说的很清楚、解释的很详细，赞。
但是过于复杂，脱离自动化的初衷，不打算实现了。
