### ISSUE TITLE
文件夹中已有未分文件夹的电影，不能自动根据名字识别电影影片信息

### ISSUE THREAD

**Issue by Mrxlei** [jxxghp/nas-tools#1756]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本:v2.2.3 5
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 文件夹中已有未分文件夹的电影，不能自动根据名字识别电影影片信息；能否增加单文件识别或者以影片文件名识别+文件夹名混合的模式来处理。

**Comment by xyswordzoro** [comment]
没配置好吧，单文件是可以识别的

**Comment by Mrxlei** [comment]
只能选择到文件夹啊，不会列出文件
