### ISSUE TITLE
希望能在手机端加入搜索结果分类

### ISSUE THREAD

**Issue by stone10104** [jxxghp/nas-tools#1758]
![image](https://user-images.githubusercontent.com/57288734/197386809-2fc9ba80-fd99-4bfc-ae21-897dafbadafb.png)
网页端搜索结果比较多时，会出现分类选择，手机端没有这个功能，当搜索结果比较多的时候，一点一点往下翻会比较麻烦。希望能在手机端也加入这个分类。

**Comment by xyswordzoro** [comment]
横屏显示分类

**Comment by stone10104** [comment]
> 横屏显示分类

我横屏也没看见，看来是我手机浏览器设置问题，软件本身是有的？

**Comment by xyswordzoro** [comment]
> > 横屏显示分类
> 
> 我横屏也没看见，看来是我手机浏览器设置问题，软件本身是有的？

![ad7345f9e6bd3ae514283697ee29924](https://user-images.githubusercontent.com/86150433/197394051-fea6f399-98f4-4b3d-8f6e-f3020b521cb3.jpg)
如果搜索内容不多可能没有

**Comment by jxxghp** [comment]
主要是手机UI太小，没想好怎么做

**Comment by stone10104** [comment]
> > > 横屏显示分类
> > 
> > 
> > 我横屏也没看见，看来是我手机浏览器设置问题，软件本身是有的？
> 
> ![ad7345f9e6bd3ae514283697ee29924](https://user-images.githubusercontent.com/86150433/197394051-fea6f399-98f4-4b3d-8f6e-f3020b521cb3.jpg) 如果搜索内容不多可能没有

感谢，我打开浏览器的“访问桌面版”之后也有了，不过我想这还是桌面版才有，web端貌似暂时是没的

**Comment by stone10104** [comment]
> 主要是手机UI太小，没想好怎么做

![image](https://user-images.githubusercontent.com/57288734/197396913-5d7c5beb-e8a1-4022-9443-4314ed736e12.png)
横着放在最上面这个区域怎么样，菜单向下拉

**Comment by jxxghp** [comment]
已支持
