### ISSUE TITLE
建议：搜索或订阅时通过tmdb获取中文和英文名称后中英文均作为搜索关键词

### ISSUE THREAD

**Issue by firstvip** [jxxghp/nas-tools#176]
不知道技术上好不好实现，只是提个建议：
搜索或订阅时不管输入中文还是英文关键词都会通过tmdb获得中英文名称，然后使用中文和英文同时进行搜索。
这样即使是英文站也可以使用中文搜索出结果。

**Comment by jxxghp** [comment]
这样需要搜索两遍的

**Comment by shanyan-wcx** [comment]
两遍没关系啊，只要结果全，慢一点无所谓

**Comment by jxxghp** [comment]
不是所有人都这么想的
