### ISSUE TITLE
电视剧订阅手动设置总集数问题

### ISSUE THREAD

**Issue by yugoai** [jxxghp/nas-tools#1765]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.3
>
> 环境: docker
>

## 你遇到什么问题了？

> 电视剧订阅设置总集数有问题，显示错误并且没有到指定集数就自动完成订阅！试过很多部电视剧设置总集数都是类似问题。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的

## 你期望的结果

> 希望能按设置的总集数订阅

## 给出程序界面截图、后台运行日志或配置文件

![~RQRXAI{S7573PBPC8~Y7UG](https://user-images.githubusercontent.com/97602933/197446837-2f7dbaa8-f6b1-4264-a74c-3b7d13f40830.png)

![$9SDT WR~CZ49AAL2GOOZJ5](https://user-images.githubusercontent.com/97602933/197446870-0b205dd4-0cb1-4545-9320-7cf6f1eb25e0.png)

![7(6D5Q{5BX63@)(JO)9XL)1](https://user-images.githubusercontent.com/97602933/197446884-c46238d0-39e0-403d-8ee5-c756648bfa28.png)

![$7`J0RESL0)BED~4951Y6HM](https://user-images.githubusercontent.com/97602933/197446898-0110ef87-6340-428a-b9a3-2db8cf5e1cc3.png)

**Comment by jxxghp** [comment]
dev 分支已修复，等发版
