### ISSUE TITLE
添加下载失败 无法打开链接，获取站点cookie失败！

### ISSUE THREAD

**Issue by Lolicon-A** [jxxghp/nas-tools#1766]
群晖nas套件更新最新版，
使用的QBT和jackett，这两个都正常。
这两天出现报错：
13:37:05 WARN - 【Downloader】http://192.168.36.108:9117/dl/bitsearch/?jackett_apikey=wj9zteku05r8s9mtvn8uq9y4npjf6uf9&path=Q2ZESjhDQkt1bmd1YUZkRmotejVGT3prYVBVcDIyX19wQVp3SEc5MGstUUNzQWg0TENYbGJieGh3REx4NDZxNzVsZVZoaG9XaHVyM1lyYmd0Z2t1MENPSEQ4NndoVElQUjUtRkZ5TWhGV0ExRnFfTXRFS08zVGpfa3ZGeFVad3hZclhzaTcxbXV0SlYtbnRCVW53YkhyRjRqRjBJdkN2RHMxaHJ5VWFjRFdyWkdjdVNBU2RmRnlBUXJIRTNsLW5fc3ZmRG1nUU5NbFRDWXpJN0owZXlac2tid1M2UUJ6T3JuVnNJUWZKYjRVNlJBd1d4eHRmQlotOTBwa1BvNGdURmJFU2pQY3E4cm1ma0hRMnB1UmdCRkxQaHVGUQ&file=%E7%9C%9F%E6%AD%A3%E8%83%9C%E8%B4%9F%E7%AC%AC05%E9%9B%86.mp4 获取站点cookie失败！
13:39:15 WARN - 【Downloader】http://192.168.36.108:9117/dl/btsow/?jackett_apikey=wj9zteku05r8s9mtvn8uq9y4npjf6uf9&path=Q2ZESjhDQkt1bmd1YUZkRmotejVGT3prYVBVUnJhLTVoTkZSWW45NXVxcnZockxRUU9JRFFBdGhCZDU3bTFKaE5fVGV2WTlWQ3FPNlYxcy1YN1FYZU9kYmV1RF8ySjdOeUhQMjZBaXNzWGx6WG5pMGZCbmxTYmRBQ3hVTGU5UkE1TnJBWERxdGt0dllTVlhlRF9yTEFRYU9NNmFKN0NGVkgyZDVBMTdzX2lZM1VhRWZWcFBuN01nanpqMG0wc1dxUFJzRGRfeXA3OTBSTTJ4aGxlZnpSWnFPWkxj&file=%E7%9C%9F%E6%AD%A3%E8%83%9C%E8%B4%9F.Bad.Prosecutor.2022.EP+01-06.HD+1080P.X264.AAC.Korean.CHS.BDYS 获取站点cookie失败！
13:39:34 WARN - 【Downloader】http://192.168.36.108:9117/dl/btsow/?jackett_apikey=wj9zteku05r8s9mtvn8uq9y4npjf6uf9&path=Q2ZESjhDQkt1bmd1YUZkRmotejVGT3prYVBVUnJhLTVoTkZSWW45NXVxcnZockxRUU9JRFFBdGhCZDU3bTFKaE5fVGV2WTlWQ3FPNlYxcy1YN1FYZU9kYmV1RF8ySjdOeUhQMjZBaXNzWGx6WG5pMGZCbmxTYmRBQ3hVTGU5UkE1TnJBWERxdGt0dllTVlhlRF9yTEFRYU9NNmFKN0NGVkgyZDVBMTdzX2lZM1VhRWZWcFBuN01nanpqMG0wc1dxUFJzRGRfeXA3OTBSTTJ4aGxlZnpSWnFPWkxj&file=%E7%9C%9F%E6%AD%A3%E8%83%9C%E8%B4%9F.Bad.Prosecutor.2022.EP+01-06.HD+1080P.X264.AAC.Korean.CHS.BDYS 获取站点cookie失败！
13:39:49 WARN - 【Downloader】http://192.168.36.108:9117/dl/btsow/?jackett_apikey=wj9zteku05r8s9mtvn8uq9y4npjf6uf9&path=Q2ZESjhDQkt1bmd1YUZkRmotejVGT3prYVBVUnJhLTVoTkZSWW45NXVxcnZockxRUU9JRFFBdGhCZDU3bTFKaE5fVGV2WTlWQ3FPNlYxcy1YN1FYZU9kYmV1RF8ySjdOeUhQMjZBaXNzWGx6WG5pMGZCbmxTYmRBQ3hVTGU5UkE1TnJBWERxdGt0dllTVlhlRF9yTEFRYU9NNmFKN0NGVkgyZDVBMTdzX2lZM1VhRWZWcFBuN01nanpqMG0wc1dxUFJzRGRfeXA3OTBSTTJ4aGxlZnpSWnFPWkxj&file=%E7%9C%9F%E6%AD%A3%E8%83%9C%E8%B4%9F.Bad.Prosecutor.2022.EP+01-06.HD+1080P.X264.AAC.Korean.CHS.BDYS 获取站点cookie失败！
13:39:51 WARN - 【Downloader】http://192.168.36.108:9117/dl/btsow/?jackett_apikey=wj9zteku05r8s9mtvn8uq9y4npjf6uf9&path=Q2ZESjhDQkt1bmd1YUZkRmotejVGT3prYVBVUnJhLTVoTkZSWW45NXVxcnZockxRUU9JRFFBdGhCZDU3bTFKaE5fVGV2WTlWQ3FPNlYxcy1YN1FYZU9kYmV1RF8ySjdOeUhQMjZBaXNzWGx6WG5pMGZCbmxTYmRBQ3hVTGU5UkE1TnJBWERxdGt0dllTVlhlRF9yTEFRYU9NNmFKN0NGVkgyZDVBMTdzX2lZM1VhRWZWcFBuN01nanpqMG0wc1dxUFJzRGRfeXA3OTBSTTJ4aGxlZnpSWnFPWkxj&file=%E7%9C%9F%E6%AD%A3%E8%83%9C%E8%B4%9F.Bad.Prosecutor.2022.EP+01-06.HD+1080P.X264.AAC.Korean.CHS.BDYS 获取站点cookie失败！
13:39:54 WARN - 【Downloader】http://192.168.36.108:9117/dl/btsow/?jackett_apikey=wj9zteku05r8s9mtvn8uq9y4npjf6uf9&path=Q2ZESjhDQkt1bmd1YUZkRmotejVGT3prYVBVUnJhLTVoTkZSWW45NXVxcnZockxRUU9JRFFBdGhCZDU3bTFKaE5fVGV2WTlWQ3FPNlYxcy1YN1FYZU9kYmV1RF8ySjdOeUhQMjZBaXNzWGx6WG5pMGZCbmxTYmRBQ3hVTGU5UkE1TnJBWERxdGt0dllTVlhlRF9yTEFRYU9NNmFKN0NGVkgyZDVBMTdzX2lZM1VhRWZWcFBuN01nanpqMG0wc1dxUFJzRGRfeXA3OTBSTTJ4aGxlZnpSWnFPWkxj&file=%E7%9C%9F%E6%AD%A3%E8%83%9C%E8%B4%9F.Bad.Prosecutor.2022.EP+01-06.HD+1080P.X264.AAC.Korean.CHS.BDYS 获取站点cookie失败！
13:41:17 WARN - 【Downloader】http://192.168.36.108:9117/dl/btsow/?jackett_apikey=wj9zteku05r8s9mtvn8uq9y4npjf6uf9&path=Q2ZESjhDQkt1bmd1YUZkRmotejVGT3prYVBVUnJhLTVoTkZSWW45NXVxcnZockxRUU9JRFFBdGhCZDU3bTFKaE5fVGV2WTlWQ3FPNlYxcy1YN1FYZU9kYmV1RF8ySjdOeUhQMjZBaXNzWGx6WG5pMGZCbmxTYmRBQ3hVTGU5UkE1TnJBWERxdGt0dllTVlhlRF9yTEFRYU9NNmFKN0NGVkgyZDVBMTdzX2lZM1VhRWZWcFBuN01nanpqMG0wc1dxUFJzRGRfeXA3OTBSTTJ4aGxlZnpSWnFPWkxj&file=%E7%9C%9F%E6%AD%A3%E8%83%9C%E8%B4%9F.Bad.Prosecutor.2022.EP+01-06.HD+1080P.X264.AAC.Korean.CHS.BDYS 获取站点cookie失败！
13:46:56 WARN - 【Downloader】http://192.168.36.108:9117/dl/btsow/?jackett_apikey=wj9zteku05r8s9mtvn8uq9y4npjf6uf9&path=Q2ZESjhDQkt1bmd1YUZkRmotejVGT3prYVBVUnJhLTVoTkZSWW45NXVxcnZockxRUU9JRFFBdGhCZDU3bTFKaE5fVGV2WTlWQ3FPNlYxcy1YN1FYZU9kYmV1RF8ySjdOeUhQMjZBaXNzWGx6WG5pMGZCbmxTYmRBQ3hVTGU5UkE1TnJBWERxdGt0dllTVlhlRF9yTEFRYU9NNmFKN0NGVkgyZDVBMTdzX2lZM1VhRWZWcFBuN01nanpqMG0wc1dxUFJzRGRfeXA3OTBSTTJ4aGxlZnpSWnFPWkxj&file=%E7%9C%9F%E6%AD%A3%E8%83%9C%E8%B4%9F.Bad.Prosecutor.2022.EP+01-06.HD+1080P.X264.AAC.Korean.CHS.BDYS 获取站点cookie失败！
13:49:59 WARN - 【Downloader】http://192.168.36.108:9117/dl/btsow/?jackett_apikey=wj9zteku05r8s9mtvn8uq9y4npjf6uf9&path=Q2ZESjhDQkt1bmd1YUZkRmotejVGT3prYVBVUnJhLTVoTkZSWW45NXVxcnZockxRUU9JRFFBdGhCZDU3bTFKaE5fVGV2WTlWQ3FPNlYxcy1YN1FYZU9kYmV1RF8ySjdOeUhQMjZBaXNzWGx6WG5pMGZCbmxTYmRBQ3hVTGU5UkE1TnJBWERxdGt0dllTVlhlRF9yTEFRYU9NNmFKN0NGVkgyZDVBMTdzX2lZM1VhRWZWcFBuN01nanpqMG0wc1dxUFJzRGRfeXA3OTBSTTJ4aGxlZnpSWnFPWkxj&file=%E7%9C%9F%E6%AD%A3%E8%83%9C%E8%B4%9F.Bad.Prosecutor.2022.EP+01-06.HD+1080P.X264.AAC.Korean.CHS.BDYS 获取站点cookie失败！

**Comment by jxxghp** [comment]
这个网站反爬了，下个版本支持

**Comment by jxxghp** [comment]
下个版本修改提示
