### ISSUE TITLE
下载HDTime的种子提示”下载种子文件出现异常：not a valid bencoded string“，怀疑和种子链接有关系

### ISSUE THREAD

**Issue by code1k** [jxxghp/nas-tools#1769]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
> v2.2.3 5f9cadcb
> 环境: docker or windows or Synology
> docker 

## 你遇到什么问题了？
> 下载HDTime的种子的时候会显示“下载种子文件出现异常：not a valid bencoded string，可能站点Cookie已过期或触发了站点首次种子下载！”。可能原因：hdtime特殊的种子链接（ https://hdtime.org/download.php?downhash=1111|5555 ），怀疑带有|导致发生失败。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
> 任无法解决

## 你期望的结果
> 添加下载任务成功

## 给出程序界面截图、后台运行日志或配置文件
> ![image](https://user-images.githubusercontent.com/13743087/197533865-427031e8-afb4-4dcc-8913-0a2b827b6034.png)
> 日志截图
> ![image](https://user-images.githubusercontent.com/13743087/197534677-2d50f5d6-1728-4312-97ea-9d58df590c3b.png)

**Comment by huluohu** [comment]
1、到站点，种子的页面，点下载种子，然后勾选“以后不再提示”，点下载。
2、重新回到nastools，下载即可

**Comment by code1k** [comment]
> 1、到站点，种子的页面，点下载种子，然后勾选“以后不再提示”，点下载。 2、重新回到nastools，下载即可

可以解决，感谢！
