### ISSUE TITLE
新功能需求：签到/收藏/订阅/回收及刷流优化

### ISSUE THREAD

**Issue by icczm** [jxxghp/nas-tools#1770]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.3
>
> 环境: windows

签到
nastool可以分享给多用户使用，如果其它（家人）用户不懂pt规则无脑下载和容易炸号，给个信息能抢救一下。
签到信息增加 分享率 下载/上传（昨天数据）显示：
馒头：分享率3✅ 100g/200g 签到成功 模拟失败
朋友：分享率2⚠️ 100g/200g 签到成功 模拟失败
春天：分享率1⛔ 100g/200g 签到成功 模拟失败
校园：连接失败：https://pt.btschool.club
柠檬：Cookie 已过期

收藏
针对流量不足恐惧症，小家宽几十T的下载量扛不住，应用情景：
豆瓣/微信搜索影片，豆瓣点看过/微信回复编号1加xx参数，仅把种子下载下来，并非马上提交到下载器，等到国庆，清明，元旦大型节日，大多站点开启站免的时候一键0元购（网页），适用于看过经典怀旧电影，或者洗板功能等，把宝贵的下载量留给追新的电影剧集。

管理/回收站
管理 已经有人提了 #1669 #1635 #1566
通过Emby删媒体库或软件内删除记录联动删种
针对压制组翻车啦，画面撕裂音画不同步\澳门赌场削刮错了\这部电影就是一坨X！等情况。毕竟在上千条种子翻出对应的那个，还要反向跟踪把演员，背景，硬链接等文件都删除还是很痛苦的。
![4](https://user-images.githubusercontent.com/116572979/197553724-d0b2f50c-320f-4897-9fee-29fb81e797d5.png)
应用2：当匹配到“你下载的种子'xxx'被管理员删除。原因：xxx”格式的站内消息则自动删除指定对应的种子，大部分网站都是同一个框架，格式都通用的吧。

回收站
联动删种功能进阶版，主要针对有hr种子或手贱删错，当在媒体库删除电影时，不是马上执行，而是移动到目录下临时文件夹，7天后自动删除，可通过网页端恢复。

订阅榜单（高危功能）
不知道看什么，那就订阅各大排行榜的高分（自定义分数）电影。

隐藏脚本窗口
硬链接好像是通过bat脚本执行？执行脚本cmd一闪而过，当大量硬链会疯狂闪屏，可以为新建软硬链接的脚本添加隐藏脚本窗口的代码，如：
if "%1" == "h" goto begin 
mshta vbscript:createobject("wscript.shell").run("%~nx0 h",0)(window.close)&&exit 
:begin

增加刷流规则与优化流程
先说硬件，300/30联通ipv6，使用刷流算了快一个月，用起来总是感觉有点呆呆的，下载和硬盘都全部拉满，上传量却不尽人意，横向对比Vertex发现隔壁太过于粗暴(大量r种然后按照规则暴力删种，只留下有上传速度的，但家宽上传没那么稳定)，比较适合大水管，没办法所以想优化一下刷流逻辑。
如图所示：
![1](https://user-images.githubusercontent.com/116572979/197552194-7ddb0934-5683-4998-a0b9-380f79f48a61.png)
a种子已完成下载并高速上传，却面临删种规则“做种24小时”的威胁，一般新种免费时间是12到48小时，超过免费时间也可以有上传，可以设置更大的保种时间，但治根不治本，删种规则“平均上传速度”只适合判断是否黑车。
![2](https://user-images.githubusercontent.com/116572979/197552224-089358a5-7949-4a43-b2a2-776c025804ff.png)
![3](https://user-images.githubusercontent.com/116572979/197552241-f1816ff2-63c4-40f3-847b-b506fed0b5a4.png)
b号种子原来有不低的上传速率，不过被c号种子拖慢了下载速度导致跟不上大部队沦为黑车，如果限制同时下载的数量又会出现这种情况，顶着盒子的进度跑上传还是跑不满。c号种子在现有的任务已经跑满上传的情况下依然被不断的添加进来，导致强行占满宽带和硬盘。
新增删种规则：最近活动
只要你还有上传，你想保多久都行，超过多久没人链接就删除。
新增选种规则：上传速度
每次执行选种规则，当上传速度大于（自定义）MiB/s时跳过选种，因为你就算加了任务也没有上传给你，浪费宽带硬盘。
优化刷流顺序：刷流执行判断>删种（最近活动）>选种（上传速度）
先执行删种是为了腾出空间（SSD的空间还是蛮珍贵的，特别是开启预分配磁盘空间功能容易爆满），以及空出同时下载数量，如上面提到的“种子'xxx'被管理员删除”和“平均上传速度”过低的黑车，让出车位。

请教：添加一个windows版本启动时自动打开网页的开关  #1675
这个提议是要自己重新编译一个exe吗，我在2.2.3版本没找到到网页开关。。。

请教:“RSS解析种子详情”功能是否能获取种子的“剩余时间”参数？如否则无视此提议（本来想在群里问的，没说两句被ban了）
![QQ拼音截图未命名](https://user-images.githubusercontent.com/116572979/198865436-c25da403-4a73-4a21-aef2-a76f77c4142e.png)
提议针对网站性种动态免费时间，大多数网站发布的新种免费时间总是固定的，但有部分站点会根据发表的资源的类型设置不同免费时间，如官组36小时，web资源24小时，大包合集48小时等，或完全随机。一般情况为了不被反薅下载量，会下默认设置“下载耗时(24小时)”，但却会对大包造成误伤（通常大包有更高的上传量比例，小包都是盒子机房内网互传秒拉屁股都看不到），故想为“下载耗时(24小时)”增加一个自动模式，在添加任务是，获取free种子”剩余时间“的参数，计算得出：剩余时间+当前系统时间=免费时间，可以把免费时间写入”标签里（”已整理=已转移识别“逻辑改为”部位空=已转移识别“），每次执行删种规则：当系统时间>免费时间则删除任务（仅对正在下载的任务执行）。
新增删种规则：下载耗时（自动）模式

**Comment by Dreamray** [comment]
你说了我想说的，但开发者才貌似没有此计划
