### ISSUE TITLE
新需求:希望能增加不同站点可以单独设置下载器

### ISSUE THREAD

**Issue by Rotel11** [jxxghp/nas-tools#1771]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.2.3
>
> 环境: docker

## 你想要新增或者改进什么功能？
资源站点的下载器自定义选择

> 你想要新增或者改进什么功能？

因为有了bt的存在，希望大佬加入站点下载器的自定义
选择，主要想bt和pt分开下载器下载，这样比较方便

**Comment by jxxghp** [comment]
#1515
