### ISSUE TITLE
馒头刷流无法辨识free和非free种子？

### ISSUE THREAD

**Issue by qnsonqnson** [jxxghp/nas-tools#1774]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>v2.2.3 5f9cadcb
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 馒头刷流无法辨识free和非free种子？刷流设置里我已经选择了free。但是，还是会下载到非free的种子。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 能不能帮看看馒头刷流free是否过滤有效？谢谢！

## 给出程序界面截图、后台运行日志或配置文件
![p1](https://user-images.githubusercontent.com/58600078/197600912-25d386d4-9326-4676-9d68-b4dbd7e4e50e.png)
![p2](https://user-images.githubusercontent.com/58600078/197600918-fa1345bc-b328-400a-80e6-a56de55c1f83.png)
![p3](https://user-images.githubusercontent.com/58600078/197600922-9fdeed89-7261-4738-adf9-6d1b0f94918e.png)

**Comment by Tartarus2014** [comment]
有些种子过了免费都没出种

**Comment by qnsonqnson** [comment]
我只订阅mt官方组的种子，他们的种子刚发布的时候：有部分不是free的，但是，nas-tools没有过滤成功。
