### ISSUE TITLE
目录同步使用的路径了Qb的默认下载路径

### ISSUE THREAD

**Issue by qqeszw** [jxxghp/nas-tools#1779]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
> v2.2.3
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？
目录同步使用的路径是Qb的默认下载路径

![image](https://user-images.githubusercontent.com/4793839/197756203-93f67a8a-6536-4188-a901-760e6d70f9a5.png)

![image](https://user-images.githubusercontent.com/4793839/197755893-8cd5c6c6-8eae-4b16-9844-d498a3b2d98f.png)

![image](https://user-images.githubusercontent.com/4793839/197756006-5b30fe48-a63f-43b9-b05b-39cc021bea28.png)

![image](https://user-images.githubusercontent.com/4793839/197756059-7f0c7c99-7430-4335-9b26-592c89473590.png)

**Comment by Shurelol** [comment]
TIPS
———————-
※  NASTool包含两种文件转移方法
 •  下载软件监控
 •  目录同步
 •  两者二选其一

※  下载软件监控
 •   监控下载器中的下载任务，在下载任务完成时，将文件从下载目录按电影、电视剧、动漫分类转移至媒体库目录（设置-媒体库）
 •   下载器目录设置
 (https://t.me/nastool_mi/23) •   已识别转移的下载任务会被添加已整理标签，删除该标签可重新转移识别该下载任务
 •   在（设置-基础设置-服务-下载软件监控）开启，可选（只管理NASTool添加的下载），文件转移方式按照（设置-基础设置-媒体-默认文件转移方式）

※  目录同步
 •   监控源目录中的文件，将新增文件转移至目的目录
 •   在（设置-目录同步）进行设置，注意同步方式若为硬链接则源目录和目的目录不能跨盘（群晖中，不同的共享文件夹会被系统认为是跨盘）
 •   目的目录不要在源目录下
 •   在（服务-清除转移缓存）清除缓存，可以重新转移已转移过的文件
 •   QBittorrent下载器请在设置-下载中开启为不完整的文件添加扩展名.!qB

**Comment by qqeszw** [comment]
感谢，搞定了， 开始走的下载软件监控模式，估计是下载器配置有问题，直接修改为目录同步方式搞定了。
