### ISSUE TITLE
搜索好像需要优化下，现在有点问题

### ISSUE THREAD

**Issue by shanyan-wcx** [jxxghp/nas-tools#178]
![屏幕截图 2022-05-25 145020](https://user-images.githubusercontent.com/58252651/170199178-81957b37-b9f9-41e6-9782-b8d08b2c3160.png)
![屏幕截图 2022-05-25 145150](https://user-images.githubusercontent.com/58252651/170199185-e21dbd35-8abb-420d-a262-a382fc2122c8.png)

比如说我直接搜索银翼杀手2049，只有一个结果，但我搜索银翼杀手，下面却有三个银翼杀手2049的结果。

**Comment by shanyan-wcx** [comment]
14:49:55 INFO - 【WEB】开始检索 银翼杀手2049 ...
14:49:55 INFO - 【JACKETT】开始并行检索 银翼杀手2049，线程数：13
14:49:55 INFO - 【JACKETT】开始检索Indexer：None ...
14:49:55 INFO - 【JACKETT】开始检索Indexer：snowpt ...
14:49:55 INFO - 【JACKETT】开始检索Indexer：pttime ...
14:49:55 INFO - 【JACKETT】开始检索Indexer：hdtime ...
14:49:55 INFO - 【JACKETT】开始检索Indexer：haidan ...
14:49:55 INFO - 【JACKETT】开始检索Indexer：1ptbar ...
14:49:55 INFO - 【JACKETT】开始检索Indexer：52pt ...
14:49:55 INFO - 【JACKETT】开始检索Indexer：oshenpt ...
14:49:55 INFO - 【JACKETT】开始检索Indexer：mikan ...
14:49:55 INFO - 【JACKETT】开始检索Indexer：dmhy ...
14:49:55 INFO - 【JACKETT】开始检索Indexer：miobt ...
14:49:55 INFO - 【JACKETT】开始检索Indexer：acgsou ...
14:49:55 INFO - 【JACKETT】开始检索Indexer：nyaasi ...
14:49:56 WARN - 【JACKETT】52pt 返回数据：2
14:49:56 WARN - 【JACKETT】snowpt 未检索到资源
14:49:56 WARN - 【JACKETT】haidan 返回数据：1
14:49:56 WARN - 【JACKETT】None 未检索到资源
14:49:56 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 122.31G 不符合大小要求
14:49:56 WARN - 【JACKETT】acgsou 返回数据：1
14:49:56 WARN - 【JACKETT】nyaasi 未检索到资源
14:49:56 WARN - 【JACKETT】oshenpt 返回数据：3
14:49:56 INFO - 【JACKETT】haidan 共检索到 0 条有效资源
14:49:56 WARN - 【JACKETT】miobt 返回数据：1
14:49:56 WARN - 【JACKETT】pttime 返回数据：8
14:49:56 WARN - 【JACKETT】hdtime 返回数据：8
14:49:56 WARN - 【JACKETT】1ptbar 返回数据：2
14:49:56 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 75.75G 不符合大小要求
14:49:56 WARN - 【JACKETT】mikan 未检索到资源
14:49:56 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 62.64G 不符合大小要求
14:49:56 WARN - 【JACKETT】dmhy 返回数据：1
14:49:56 INFO - 【JACKETT】Blade Runner 2049 2017 BluRay 2160p x265.10bit HDR 4Audio mUHD-FRDS 不符合过滤条件
14:49:56 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 62.64G 不符合大小要求
14:49:56 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 122.31G 不符合大小要求
14:49:56 INFO - 【META】正在识别电影：科幻經典電影, 年份=2017 ...
14:49:56 - Token(category = TokenCategory.DELIMITER, content = " ", enclosed = False is not in list
14:49:56 - Token(category = TokenCategory.DELIMITER, content = " ", enclosed = True is not in list
14:49:56 - Token(category = TokenCategory.DELIMITER, content = " ", enclosed = False is not in list
14:49:56 INFO - 【JACKETT】2017【美國】科幻經典電影☪ [雷利史考克] [銀翼殺手2049 / 銀翼殺手2 Blade Runner 2049] [BDrip] [BlueRay] [1080p] [藍光] [BIG5] [繁體&英文] 未查询到媒体信息
14:49:56 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 62.64G 不符合大小要求
14:49:56 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 75.75G 不符合大小要求
14:49:56 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 62.64G 不符合大小要求
14:49:56 INFO - 【META】正在识别电影：科幻經典電影, 年份=2017 ...
14:49:56 INFO - 【JACKETT】miobt 共检索到 0 条有效资源
14:49:56 INFO - 【JACKETT】Blade Runner 2049 (2017) QHD x265.10bit HDR TrueHD Atmos Mandarin DTS-HD MA 7 1-Yqkl mkv 不符合过滤条件
14:49:56 INFO - 【JACKETT】Blade Runner 2049 2017 1080p UHD DTS HDR x265 D-Z0N3 不符合过滤条件
14:49:56 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 83.52G 不符合大小要求
14:49:56 INFO - 【JACKETT】1ptbar 共检索到 0 条有效资源
14:49:56 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 78.01G 不符合大小要求
14:49:56 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 122.31G 不符合大小要求
14:49:56 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 122.31G 不符合大小要求
14:49:56 INFO - 【JACKETT】[银翼杀手2049/银翼杀手2][Blade.Runner.2049.2017.BluRay.2160p.x265.10bit.HDR.4Audio.mUHD-FRDS][剧情/科幻/惊悚][北美] 不符合过滤条件
14:49:56 INFO - 【JACKETT】pttime 共检索到 0 条有效资源
14:49:56 INFO - 【JACKETT】Blade Runner 2049 2017 UHD BluRay 2160p 10bit HDR 2Audio TrueHD(Atmos) 7 1 x265-beAst 不符合过滤条件
14:49:56 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 83.59G 不符合大小要求
14:49:56 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 122.31G 不符合大小要求
14:49:56 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 83.52G 不符合大小要求
14:49:57 WARN - 【META】科幻經典電影 未找到媒体信息!
14:49:57 INFO - 【META】正在识别电视剧：科幻經典電影, 年份=2017 ...
14:49:57 WARN - 【META】科幻經典電影 未找到媒体信息!
14:49:57 INFO - 【META】正在识别电视剧：科幻經典電影, 年份=2017 ...
14:49:57 INFO - 【JACKETT】电影：Blade Runner 2049 EUR 2160p UHD BluRay HEVC TrueHD ATMOS 7.1-BHY@CHDbits 银翼杀手 (1982) 不匹配名称：['银翼杀手2049', '银翼杀手2049']
14:49:57 INFO - 【JACKETT】52pt 共检索到 0 条有效资源
14:49:57 INFO - 【JACKETT】电影：Blade Runner 2049 1080p WEB-DL H264 AC3-EVO 银翼杀手 (1982) 不匹配名称：['银翼杀手2049', '银翼杀手2049']
14:49:57 INFO - 【JACKETT】hdtime 共检索到 0 条有效资源
14:49:58 INFO - 【JACKETT】电影：Blade Runner 2049 EUR 2160p UHD BluRay HEVC TrueHD ATMOS 7.1-BHY@CHDbits 银翼杀手 (1982) 不匹配名称：['银翼杀手2049', '银翼杀手2049']
14:49:58 INFO - 【JACKETT】oshenpt 共检索到 1 条有效资源
14:49:58 WARN - 【META】科幻經典電影 未找到媒体信息!
14:49:58 INFO - 【META】正在识别电视剧：科幻經典電影, 年份= ...
14:49:58 WARN - 【META】科幻經典電影 未找到媒体信息!
14:49:58 INFO - 【META】正在识别电视剧：科幻經典電影, 年份= ...
14:49:58 WARN - 【META】科幻經典電影 未找到媒体信息!
14:49:58 INFO - 【META】正在识别电影：科幻經典電影, 年份= ...
14:49:58 WARN - 【META】科幻經典電影 未找到媒体信息!
14:49:58 INFO - 【META】正在识别电影：科幻經典電影, 年份= ...
14:49:59 WARN - 【META】科幻經典電影 未找到媒体信息!
14:49:59 INFO - 【JACKETT】2017【美國】科幻經典電影☪ [雷利史考克] [銀翼殺手2049 / 銀翼殺手2 Blade Runner 2049] [BDrip] [BlueRay] [1080p] [藍光] [BIG5] [繁體&英文] 未查询到媒体信息
14:49:59 INFO - 【JACKETT】acgsou 共检索到 0 条有效资源
14:49:59 WARN - 【META】科幻經典電影 未找到媒体信息!
14:49:59 INFO - 【JACKETT】2017【美國】科幻經典電影☪ [雷利史考克] [銀翼殺手2049 / 銀翼殺手2 Blade Runner 2049] [BDrip] [BlueRay] [1080p] [藍光] [BIG5] [繁體&英文] 未查询到媒体信息
14:49:59 INFO - 【JACKETT】dmhy 共检索到 0 条有效资源
14:49:59 INFO - 【JACKETT】所有API检索完成，有效资源数：1
14:49:59 INFO - 【WEB】共检索到 1 个有效资源
14:49:59 INFO - 【WEB】分组择优后剩余 1 个有效资源
14:50:57 INFO - 【WEB】开始检索 银翼杀手 ...
14:50:57 INFO - 【JACKETT】开始并行检索 银翼杀手，线程数：13
14:50:57 INFO - 【JACKETT】开始检索Indexer：None ...
14:50:57 INFO - 【JACKETT】开始检索Indexer：snowpt ...
14:50:57 INFO - 【JACKETT】开始检索Indexer：pttime ...
14:50:57 INFO - 【JACKETT】开始检索Indexer：hdtime ...
14:50:57 INFO - 【JACKETT】开始检索Indexer：haidan ...
14:50:57 INFO - 【JACKETT】开始检索Indexer：1ptbar ...
14:50:57 INFO - 【JACKETT】开始检索Indexer：52pt ...
14:50:57 INFO - 【JACKETT】开始检索Indexer：oshenpt ...
14:50:57 WARN - 【JACKETT】None 返回数据：4
14:50:57 INFO - 【JACKETT】开始检索Indexer：mikan ...
14:50:57 INFO - 【JACKETT】开始检索Indexer：dmhy ...
14:50:57 INFO - 【JACKETT】开始检索Indexer：miobt ...
14:50:57 INFO - 【JACKETT】开始检索Indexer：acgsou ...
14:50:57 INFO - 【JACKETT】开始检索Indexer：nyaasi ...
14:50:57 WARN - 【JACKETT】1ptbar 返回数据：2
14:50:57 WARN - 【JACKETT】52pt 返回数据：3
14:50:57 WARN - 【JACKETT】oshenpt 返回数据：4
14:50:57 WARN - 【JACKETT】haidan 返回数据：2
14:50:57 WARN - 【JACKETT】snowpt 返回数据：2
14:50:57 WARN - 【JACKETT】hdtime 返回数据：15
14:50:58 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 122.31G 不符合大小要求
14:50:58 WARN - 【JACKETT】acgsou 返回数据：6
14:50:58 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 75.75G 不符合大小要求
14:50:58 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 62.64G 不符合大小要求
14:50:58 WARN - 【JACKETT】mikan 返回数据：5
14:50:58 WARN - 【JACKETT】pttime 返回数据：12
14:50:58 INFO - 【META】正在识别电影：银翼杀手：2022大断电, 年份=2022 ...
14:50:58 WARN - 【JACKETT】nyaasi 未检索到资源
14:50:58 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 122.31G 不符合大小要求
14:50:58 WARN - 【JACKETT】miobt 返回数据：6
14:50:58 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 62.64G 不符合大小要求
14:50:58 INFO - 【JACKETT】1ptbar 共检索到 0 条有效资源
14:50:58 INFO - 【JACKETT】Blade Runner 1982 The Final Cut 2160p UHD Blu-ray HEVC TrueHD 7 1-HDRINVASION 不符合过滤条件
14:50:58 INFO - 【META】正在识别电影：Blade Runner Collection, 年份= ...
14:50:58 INFO - 【JACKETT】电影：银翼杀手 (1982) 126.2G 不符合大小要求
14:50:58 INFO - 【JACKETT】Blade Runner 2049 2017 BluRay 2160p x265.10bit HDR 4Audio mUHD-FRDS 不符合过滤条件
14:50:58 INFO - 【JACKETT】Blade Runner 1982 The Final Cut 2160p BluRay HEVC TrueHD 7.1.Atmos-HDRINVASION 不符合过滤条件
14:50:58 INFO - 【JACKETT】电影：银翼杀手 (1982) 126.2G 不符合大小要求
14:50:58 INFO - 【JACKETT】52pt 共检索到 0 条有效资源
14:50:58 INFO - 【JACKETT】oshenpt 共检索到 1 条有效资源
14:50:58 WARN - 【META】银翼杀手：2022大断电 未找到媒体信息!
14:50:58 INFO - 【META】正在识别电视剧：银翼杀手：2022大断电, 年份=2022 ...
14:50:58 WARN - 【META】Blade Runner Collection 未找到媒体信息!
14:50:58 INFO - 【META】正在识别电视剧：Blade Runner Collection, 年份= ...
14:50:58 INFO - 【JACKETT】[SweetSub][银翼杀手：黑暗浩劫 2022][Blade Runner Black Out 2022][JPN Ver.][720P][AVC 8bit][CHS] 不符合过滤条件
14:50:59 WARN - 【META】银翼杀手：2022大断电 未找到媒体信息!
14:50:59 INFO - 【META】正在识别电视剧：银翼杀手：2022大断电, 年份= ...
14:50:59 WARN - 【META】Blade Runner Collection 未找到媒体信息!
14:50:59 INFO - 【JACKETT】Blade Runner Collection 1080p x264 TrueHD -Grym 未查询到媒体信息
14:50:59 INFO - 【JACKETT】haidan 共检索到 0 条有效资源
14:50:59 INFO - 【JACKETT】电影：有声书 - 作者: - 菲利普·迪克科幻作品集 - 演播: - M4A - HDSAB 山村犹有读书声 (2002) 不匹配名称：['银翼杀手', '银翼杀手']
14:50:59 INFO - 【JACKETT】[SweetSub][银翼杀手：黑暗浩劫 2022][Blade Runner Black Out 2022][JPN Ver.][720P][AVC 8bit][CHT] 不符合过滤条件
14:50:59 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 62.64G 不符合大小要求
14:50:59 INFO - 【JACKETT】[SweetSub][银翼杀手：黑暗浩劫 2022][Blade Runner Black Out 2022][JPN Ver.][720P][AVC 8bit][CHS] 不符合过滤条件
14:50:59 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 75.75G 不符合大小要求
14:50:59 - Token(category = TokenCategory.DELIMITER, content = " ", enclosed = True is not in list
14:50:59 INFO - 【JACKETT】2017【美國】科幻經典電影☪ [雷利史考克] [銀翼殺手2049 / 銀翼殺手2 Blade Runner 2049] [BDrip] [BlueRay] [1080p] [藍光] [BIG5] [繁體&英文] 未查询到媒体信息
14:50:59 INFO - 【JACKETT】[SweetSub][銀翼殺手：黑暗浩劫 2022][Blade Runner Black Out 2022][JPN Ver.][720P][AVC 8bit][CHT] 不符合过滤条件
14:50:59 INFO - 【JACKETT】[SweetSub][银翼杀手：黑暗浩劫 2022][Blade Runner Black Out 2022][JPN Ver.][720P][AVC 8bit][CHS] 不符合过滤条件
14:50:59 - Token(category = TokenCategory.DELIMITER, content = " ", enclosed = False is not in list
14:50:59 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 78.01G 不符合大小要求
14:50:59 INFO - 【JACKETT】Blade Runner 2049 2017 UHD BluRay 2160p 10bit HDR 2Audio TrueHD(Atmos) 7 1 x265-beAst 不符合过滤条件
14:50:59 - Token(category = TokenCategory.UNKNOWN, content = "2022", enclosed = True is not in list
14:50:59 INFO - 【JACKETT】[SweetSub][银翼杀手：黑暗浩劫 2022][Blade Runner Black Out 2022][1080P][HEVC 10bit][日英双音轨][简繁内封][v2] 未查询到媒体信息
14:50:59 - Token(category = TokenCategory.DELIMITER, content = " ", enclosed = True is not in list
14:50:59 INFO - 【JACKETT】2017【美國】科幻經典電影☪ [雷利史考克] [銀翼殺手2049 / 銀翼殺手2 Blade Runner 2049] [BDrip] [BlueRay] [1080p] [藍光] [BIG5] [繁體&英文] 未查询到媒体信息
14:50:59 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 83.59G 不符合大小要求
14:50:59 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 122.31G 不符合大小要求
14:50:59 INFO - 【JACKETT】[SweetSub][銀翼殺手：黑暗浩劫 2022][Blade Runner Black Out 2022][JPN Ver.][720P][AVC 8bit][CHT] 不符合过滤条件
14:50:59 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 83.52G 不符合大小要求
14:50:59 INFO - 【JACKETT】[SweetSub][银翼杀手：黑暗浩劫 2022][Blade Runner Black Out 2022][JPN Ver.][720P][AVC 8bit][CHS] 不符合过滤条件
14:50:59 INFO - 【JACKETT】电影：银翼杀手 (1982) 81.81G 不符合大小要求
14:50:59 INFO - 【JACKETT】hdtime 共检索到 6 条有效资源
14:51:00 WARN - 【META】银翼杀手：2022大断电 未找到媒体信息!
14:51:00 INFO - 【META】正在识别电影：银翼杀手：2022大断电, 年份= ...
14:51:00 INFO - 【JACKETT】None 共检索到 3 条有效资源
14:51:00 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 62.64G 不符合大小要求
14:51:00 INFO - 【JACKETT】Blade Runner 2049 (2017) QHD x265.10bit HDR TrueHD Atmos Mandarin DTS-HD MA 7 1-Yqkl mkv 不符合过滤条件
14:51:00 WARN - 【META】银翼杀手：2022大断电 未找到媒体信息!
14:51:00 INFO - 【JACKETT】Blade Runner 2049 2017 1080p UHD DTS HDR x265 D-Z0N3 不符合过滤条件
14:51:00 INFO - 【JACKETT】Blade Runner 1982 The Final Cut BluRay 720p x264 AC3 2Audios-CMCT 不符合过滤条件
14:51:00 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 83.52G 不符合大小要求
14:51:00 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 122.31G 不符合大小要求
14:51:00 INFO - 【JACKETT】电影：银翼杀手2049 (2017) 122.31G 不符合大小要求
14:51:00 INFO - 【JACKETT】[VCB-Studio&SweetSub] 银翼杀手：2022大断电 / Blade Runner Black Out 2022 / BLADE RUNNER BLACK OUT 2022 (BDRip 1080p WEB HEVC 10bit AC-3 MKV) 未查询到媒体信息
14:51:00 INFO - 【JACKETT】电影：银翼杀手 (1982) 61.47G 不符合大小要求
14:51:00 INFO - 【JACKETT】snowpt 共检索到 1 条有效资源
14:51:00 INFO - 【JACKETT】[银翼杀手2049/银翼杀手2][Blade.Runner.2049.2017.BluRay.2160p.x265.10bit.HDR.4Audio.mUHD-FRDS][剧情/科幻/惊悚][北美] 不符合过滤条件
14:51:00 INFO - 【JACKETT】pttime 共检索到 2 条有效资源
14:51:00 INFO - 【JACKETT】mikan 共检索到 3 条有效资源
14:51:01 INFO - 【JACKETT】miobt 共检索到 2 条有效资源
14:51:01 INFO - 【JACKETT】acgsou 共检索到 3 条有效资源
14:51:27 - HTTPConnectionPool(host='192.168.1.9', port=9117): Read timed out. (read timeout=30)
14:51:27 WARN - 【JACKETT】dmhy 未检索到资源
14:51:27 INFO - 【JACKETT】所有API检索完成，有效资源数：21
14:51:28 INFO - 【WEB】共检索到 21 个有效资源
14:51:28 INFO - 【WEB】分组择优后剩余 21 个有效资源

**Comment by jxxghp** [comment]
不同的搜索关键字返回数据不一样是很正常，Jackett返回的可能就不一样，因为都是搜的副标题
