### ISSUE TITLE
目录监控转移使用rclone模式识别上传后视频和刮捎文件不在同一目录

### ISSUE THREAD

**Issue by Tasle** [jxxghp/nas-tools#1783]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.3 5f9cadcb
>
> 环境: docker
>

## 你遇到什么问题了？

> rclone模式下(转移/复制)的视频文件和刮捎的nfo、图片等不是上传到同一目录下。
>比如gd根目录挂载到本地 /net/gd 目录下，视频会传到gd的/net/gd目录下，而nfo等文件会创建到gd的根目录下
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 视频文件和nfo等文件在同一目录下

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
信息不足，不知道说啥
