### ISSUE TITLE
一个关于查询结果分页显示的小bug，解决后希望能加入自定义显示查询结果数量

### ISSUE THREAD

**Issue by atreeofroy** [jxxghp/nas-tools#1785]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>v2.2.3 5f9cadcb
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 描述一下你遇到的问题
/history页加入查询结果行数/history?pagenum=100后，报500错误。查看源码发现request.args.get方法获取的rownum为字符串型，未转为整数型就传入sqlhelper，导致页面报错。
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
建议将/web/main.py第1126行：
PageNum = request.args.get("pagenum")
改为
PageNum = int(request.args.get("pagenum"))
然后在history.html等查询结果显示页面中增加查询结果行数选择（30,50,100等）。
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Shurelol** [comment]
建议提pr，提交到dev分支

**Comment by jxxghp** [comment]
dev改了
