### ISSUE TITLE
希望追剧日历能同步到手机日历！！

### ISSUE THREAD

**Issue by sently** [jxxghp/nas-tools#1787]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.2.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望追剧日历可以跟手机日历同步

## 这个功能有什么可以参考的资料吗？

> 就是感觉追剧日历很酷

**Comment by jxxghp** [comment]
手机浏览器打开主页，保存图标到桌面。点开就是个APP。
