### ISSUE TITLE
希望搜索下载时可以自定义下载目录名称

### ISSUE THREAD

**Issue by wjw054509** [jxxghp/nas-tools#1788]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: lateat
>
> 环境: docker 

## 你想要新增或者改进什么功能？
希望搜索下载时增加可以自定义下载目录名称的功能（类似于油猴插件pptp的下载方式），方便自己整理文件命名方式，这样自己整理的文件夹更加整齐

**Comment by wjw054509** [comment]
类似于我设置 下载器目录为  /downloads/movie/<...>       ，点击下载后就会跳出输入框填入 文件夹名称来代替<...>，

**Comment by wjw054509** [comment]
点击下载和订阅可以自定义保存文件夹的名称

**Comment by jxxghp** [comment]
那还用这个工具干啥，用pptp不香吗

**Comment by wjw054509** [comment]
主要是两边都有想用的功能，如果能整合就更好了
