### ISSUE TITLE
资源搜索 - 搜索到的资源无法下载， 日志里提示 [Downloader]: <jackett url>获取站点cookies失败

### ISSUE THREAD

**Issue by Jaywwwww** [jxxghp/nas-tools#1789]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.3

> 环境: docker on synology

## 你遇到什么问题了？

资源搜索 -> 搜索到的资源无法下载， 日志里提示 [Downloader]: <jackett url>获取站点cookies失败
jackett里无相关错误日志，Transmission里也没有下载记录

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是，没有找到有设置jackett cookies的地方

## 你期望的结果

> 资源搜索成功后，应能自动调用下载器下载。

## 给出程序界面截图、后台运行日志或配置文件

<img width="380" alt="image" src="https://user-images.githubusercontent.com/42517682/198193943-b49c0fa0-4f64-4b5f-883f-5d10d8c0bfb8.png">

log：
12:47:35 WARN - 【Downloader】http://192.168.2.8:9117/dl/1337x/?jackett_apikey=61w30s867lv5qvqgn9rv615hki1cjfzu&path=Q2ZESjhEV1I5cFVpN0hOR2tVZmVDRnNmck5VSkhITjRBTjc4VDBXZkVUTHI2bjVyT2xZMDVqU0oxSHc1Zk5lUW1hWjVzRjNrQ19NS19ucGVxOVZ4N2kzNmFYVGFsb1VLRFFkMmFWTDdmaEJHOV9ZaDh5YzBxRmRyRmxvQmNnRFctQXZoME14NWNhalpxMWxVU0k3YldQamJDdVl0em5jeVZiMndZdWRkYXE2T1UtY3kydDJDeTJBTkRSRTF0cEN5clcxM0tUVVNKQ0pHLW5DbElhMGdMMzJXcVg2Q2RQd0FoTVNuS2gxZEdRS2s0WVp1ZF96NkhKSFpFckFJRjNoNWV3N2oxQQ&file=Dragon.Ball.Super.Super.Hero.2022.ENGLISH.SUBBED.720p.HDCAM.x265-iDiOTS 获取站点cookie失败！

**Comment by atreeofroy** [comment]
这个应该是jackett没配置好吧

**Comment by Jaywwwww** [comment]
> 这个应该是jackett没配置好吧

感谢回复
没有搞清楚jackett该如何配置。jackett 的log里根本就没有看到相关信息。
用1337x和btsow indexer都有这个问题，用EZTV就正常

**Comment by jxxghp** [comment]
这只是个警告日志，不是真正原因。下个版本会取消这个日志输出

**Comment by Jaywwwww** [comment]
> 这只是个警告日志，不是真正原因。下个版本会取消这个日志输出

谢谢回复。麻烦您指点一下应该如何进一步排错，nastool除此之外没有其他log，jackett也没有相关log。难道是下载器的问题？

**Comment by atreeofroy** [comment]
> > 这个应该是jackett没配置好吧
> 
> 感谢回复 没有搞清楚jackett该如何配置。jackett 的log里根本就没有看到相关信息。 用1337x和btsow indexer都有这个问题，用EZTV就正常

jackett里的test后面有绿色的对勾吗？没有的话，应该是cookie没取好。有些站点用工具取的cookie不能用。docker里装firefox试试。
看一下这个：https://post.smzdm.com/p/an3on5dp/
