### ISSUE TITLE
添加下载无反应

### ISSUE THREAD

**Issue by Sincejunly** [jxxghp/nas-tools#1791]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.2.3
>
> 环境: DSM 7.1.1-4296 Update 1
>

## 你遇到什么问题了？

> 搜索的资源无法下载

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是，无结果

## 你期望的结果

> 能够正常添加下载

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/96775034/198281829-d76d3120-acd7-42eb-8f49-f46c18339926.png)
> ![image](https://user-images.githubusercontent.com/96775034/198280769-8af94cde-3546-4160-883c-653fb1c9c6ae.png)
> ![image](https://user-images.githubusercontent.com/96775034/198280820-957af7c9-d9f4-451a-895e-2befd29e0806.png)
![image](https://user-images.githubusercontent.com/96775034/198281021-5c1b7b9e-b6c8-41fa-baf3-84aaf26e22b9.png)
![image](https://user-images.githubusercontent.com/96775034/198280899-bf799f08-fb13-4b2c-89f5-04320b1ad023.png)
![image](https://user-images.githubusercontent.com/96775034/198280939-f26eb65e-4b62-4be2-9966-7c957152f053.png)
![image](https://user-images.githubusercontent.com/96775034/198284081-bba1c4b3-b779-4091-b6e4-aa294dda61bb.png)

**Comment by link2fun** [comment]
套件 且 无日志 是没法解决的

**Comment by Sincejunly** [comment]
> 套件 且 无日志 是没法解决的

日志在哪里弄

**Comment by link2fun** [comment]
> > 套件 且 无日志 是没法解决的
> 
> 用docker 布置了一下 同样的问题 日志：2022-10-27 20:45:40,315 INFO RPC interface 'supervisor' initialized
> 
> ```
> 2022-10-27 20:45:40,315 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> 2022-10-27 20:45:40,316 INFO supervisord started with pid 1
> 2022-10-27 20:45:41,317 INFO spawned: 'nas-tools' with pid 13
> 2022-10-27 20:45:46,322 INFO success: nas-tools entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
> 2022-10-27 22:15:40,996 WARN received SIGTERM indicating exit request
> 2022-10-27 22:15:40,996 INFO waiting for nas-tools to die
> 2022-10-27 22:15:41,729 INFO stopped: nas-tools (exit status 0)
> 2022-10-27 22:15:41,729 INFO reaped unknown pid 36 (exit status 0)
> 程序自动升级已关闭，如需自动升级请在创建容器时设置环境变量：NASTOOL_AUTO_UPDATE=true
> 以PUID=1026，PGID=100的身份启动程序...
> 注意：日志将停止打印，请通过文件或WEB页面查看日志
> 2022-10-27 22:21:29,043 INFO RPC interface 'supervisor' initialized
> 2022-10-27 22:21:29,043 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> 2022-10-27 22:21:29,044 INFO supervisord started with pid 1
> 2022-10-27 22:21:30,046 INFO spawned: 'nas-tools' with pid 12
> 2022-10-27 22:21:35,744 INFO success: nas-tools entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
> ```

日志不对
![image](https://user-images.githubusercontent.com/19241982/198327523-02f6ebc3-b1d3-4180-abd2-f3c126989732.png)

**Comment by Sincejunly** [comment]
> > > 套件 且 无日志 是没法解决的
> > 
> > 
> > 用docker 布置了一下 同样的问题 日志：2022-10-27 20:45:40,315 INFO RPC interface 'supervisor' initialized
> > ```
> > 2022-10-27 20:45:40,315 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> > 2022-10-27 20:45:40,316 INFO supervisord started with pid 1
> > 2022-10-27 20:45:41,317 INFO spawned: 'nas-tools' with pid 13
> > 2022-10-27 20:45:46,322 INFO success: nas-tools entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
> > 2022-10-27 22:15:40,996 WARN received SIGTERM indicating exit request
> > 2022-10-27 22:15:40,996 INFO waiting for nas-tools to die
> > 2022-10-27 22:15:41,729 INFO stopped: nas-tools (exit status 0)
> > 2022-10-27 22:15:41,729 INFO reaped unknown pid 36 (exit status 0)
> > 程序自动升级已关闭，如需自动升级请在创建容器时设置环境变量：NASTOOL_AUTO_UPDATE=true
> > 以PUID=1026，PGID=100的身份启动程序...
> > 注意：日志将停止打印，请通过文件或WEB页面查看日志
> > 2022-10-27 22:21:29,043 INFO RPC interface 'supervisor' initialized
> > 2022-10-27 22:21:29,043 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> > 2022-10-27 22:21:29,044 INFO supervisord started with pid 1
> > 2022-10-27 22:21:30,046 INFO spawned: 'nas-tools' with pid 12
> > 2022-10-27 22:21:35,744 INFO success: nas-tools entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
> > ```
> 
> 日志不对 ![image](https://user-images.githubusercontent.com/19241982/198327523-02f6ebc3-b1d3-4180-abd2-f3c126989732.png)

2022-10-28 00:31:18,624	ERROR: 【Db】执行SQL出错：sql:SELECT ID, IGNORED, ENABLED FROM IGNORED_WORDS; parameters:None; no such table: IGNORED_WORDS
2022-10-28 00:31:18,624	ERROR: 【Db】执行SQL出错：sql:SELECT ID, REPLACED, REPLACE, ENABLED FROM REPLACED_WORDS; parameters:None; no such table: REPLACED_WORDS
2022-10-28 00:31:18,624	ERROR: 【Db】执行SQL出错：sql:SELECT ID, FRONT, BACK, OFFSET, ENABLED, REPLACED_WORD_ID FROM OFFSET_WORDS; parameters:None; no such table: OFFSET_WORDS
2022-10-28 00:31:18,625	ERROR: 【Db】执行SQL出错：sql:DROP TABLE IGNORED_WORDS; parameters:None; no such table: IGNORED_WORDS
2022-10-28 00:31:18,625	ERROR: 【Db】执行SQL出错：sql:DROP TABLE REPLACED_WORDS; parameters:None; no such table: REPLACED_WORDS
2022-10-28 00:31:18,625	ERROR: 【Db】执行SQL出错：sql:DROP TABLE OFFSET_WORDS; parameters:None; no such table: OFFSET_WORDS
2022-10-28 00:31:18,625	INFO: WEB管理页面用户：admin
2022-10-28 00:31:18,625	INFO: 未启用https，请使用 http://IP:3000 访问管理页面
2022-10-28 00:31:18,625	ERROR: TMDB API Key未配置，媒体整理、搜索下载等功能将无法正常运行！
2022-10-28 00:31:18,625	INFO: TMDB匹配模式：正常模式
2022-10-28 00:31:18,626	INFO: 媒体管理软件设置为：emby
2022-10-28 00:31:18,626	WARNING: 微信配置不完整，将无法接收到通知消息！
2022-10-28 00:31:18,626	WARNING: 微信Token、EncodingAESKey未配置，微信控制功能将无法使用
2022-10-28 00:31:18,626	INFO: 下载软件设置为：qbittorrent
2022-10-28 00:31:18,626	INFO: 下载文件转移模式为：硬链接
2022-10-28 00:31:18,626	INFO: 索引器设置为：jackett
2022-10-28 00:31:18,626	INFO: 微信等移动端渠道搜索已开启自动择优下载
2022-10-28 00:31:18,626	INFO: 保种时间未配置，自动删种功能已关闭
2022-10-28 00:31:18,626	INFO: 下载软件监控未开启，下载器监控功能已关闭
2022-10-28 00:31:18,733	INFO: 站点自动签到服务启动
2022-10-28 00:31:18,749	INFO: RSS订阅服务启动
2022-10-28 00:31:18,750	INFO: 订阅定时搜索服务启动
2022-10-28 00:31:18,750	INFO: 媒体库同步服务启动
配置文件地址：/config/config.yaml
NASTool 当前版本号：v2.2.3
正在加载配置...
日志输出类型为：file
日志将写入文件：/config/logs
开始启动进程...
Pending jobs:
    Sites.signin (trigger: cron[hour='8', minute='1'], pending)
    Rss.rssdownload (trigger: interval[0:30:00], pending)
    Rss.rsssearch_all (trigger: interval[1 day, 0:00:00], pending)
    MediaServer.sync_mediaserver (trigger: interval[12:00:00], pending)
    Config.init_config (trigger: interval[0:10:00], pending)
    MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
    Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
    Rss.rsssearch (trigger: interval[0:05:00], pending)
    Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-10-28 00:32:18 CST)
    Rss.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
    MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
    get_login_wallpaper (trigger: interval[1:00:00], next run at: 2022-10-28 00:31:18 CST)
 * Serving Flask app 'web.main'
 * Debug mode: off
