### ISSUE TITLE
推送下载，但是实际qb并未下载，媒体库也没有

### ISSUE THREAD

**Issue by leo8912** [jxxghp/nas-tools#180]
![image](https://user-images.githubusercontent.com/22719866/170240533-3b809615-6f21-437d-9886-22a7853cb6b3.png)

如图，通知了下载，但实际并未下载。媒体库也没有。
在群里问了一下，有人说可能是tracker没连上，种子没下下来。（观众站我之前也确实有个没连上的情况）
如果是这个情况，是否是可以加一个判断，监测重试几次qb还未下载成功，就拉黑该种子换一个资源再下载？
或者是其他问题么

**Comment by jxxghp** [comment]
qb的api不会返还真实的添加状态，不太好解决。
应该还是环境相关吧，我自己用了这么久，没遇到过。
