### ISSUE TITLE
docker最新版默认密码password 无法登陆请作者看到修复一下

### ISSUE THREAD

**Issue by jusmoe** [jxxghp/nas-tools#1803]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
修复了，之前是要再重启一次才能用默认密码登录
