### ISSUE TITLE
DOCKER方式部署登录失败

### ISSUE THREAD

**Issue by shunny5887** [jxxghp/nas-tools#1808]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 登录提示用户名密码错误，尝试重新部署容器，仍无法登陆，查看log没有登陆的异常信息

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

>是

## 你期望的结果

> 正常登录
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
<img width="690" alt="image" src="https://user-images.githubusercontent.com/116858326/198478360-cf48a391-e02f-4c7c-b0e9-52a9b192ef75.png">

**Comment by jxxghp** [comment]
再重启下，或者拉下最新的程序。
昨天晚上发的有Bug，要重启两次。

**Comment by shunny5887** [comment]
> 再重启下，或者拉下最新的程序。 昨天晚上发的有Bug，要重启两次。

好的 回去我试下
