### ISSUE TITLE
关于代理proxy设置的问题

### ISSUE THREAD

**Issue by itgoyo** [jxxghp/nas-tools#181]
请问大伙都是怎么设置代理的？是家里已经有了爱快之类的设备嘛？我这边路由器刷了个老毛子，家里设备都可以自动番茄，但是这个地址要这么配置？我也尝试在nas上面安装配置clash，但是127.0.0.1:7890，没用，换成nas主机的ip地址加上端口也没用。也尝试网上很多修改host文件的也没效果，tg群问也没人说，不知道是问的问题是不是太低端了

**Comment by wab201** [comment]
NAS上配置clash是用的你NAS的地址做代理，不是127.0.0.1
