### ISSUE TITLE
自定义识别可以增加季的偏移

### ISSUE THREAD

**Issue by hbzjwyz** [jxxghp/nas-tools#1811]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.0
> 环境: docker

## 你想要新增或者改进什么功能？

> 自定义识别可以增加季的偏移
例如我下载「死神 千年血战篇」 的时候，总是给我识别成第一季的内容，并替换第一季的源文件。
实际「死神 千年血战篇」在TMDB中属于「死神」的第二季的内容。
![DE060803-12EC-4BE1-9D1E-22C7E138B86D](https://user-images.githubusercontent.com/63764017/198518198-1978711b-5fc7-4d05-a42e-a6f0b3c9000a.png)

**Comment by Shurelol** [comment]
千年血战篇直接替换成第二季不行？

**Comment by hbzjwyz** [comment]
> 千年血战篇直接替换成第二季不行？

可以了
