### ISSUE TITLE
更新2.3.0之后自定义订阅无法打开链接

### ISSUE THREAD

**Issue by Aldia098** [jxxghp/nas-tools#1815]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.3.0
>
> 环境: docker on qnap
>

## 你遇到什么问题了？

> 更新2.3.0之后自定义订阅显示无法打开链接，单独复制QB可以下载

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的

## 你期望的结果

> 解决订阅下载问题

## 给出程序界面截图、后台运行日志或配置文件

> <img src="https://p.sda1.dev/8/d0989c1bdf4adb8978a7a94b5d5e4494/QQ截图20221028193353.png" >

**Comment by link2fun** [comment]
网络不稳定所以会打不开, 特指长时间没有成功下载种子, 现在不知道多少秒
