### ISSUE TITLE
实测当前重命名方式会导致Plex剧集混乱

### ISSUE THREAD

**Issue by Always67** [jxxghp/nas-tools#182]
大佬能不能针对Plex增加一下重命名规则，或者添加自定义剧集重命名的规则选项呢？

**Comment by jxxghp** [comment]
确定吗？确定不是多层目录的原因？截图看看。

**Comment by Always67** [comment]
我现在精简了目录结构，
docker映射nas文件夹 /share/Library➡/media     /share/Sync➡/links
docker内媒体目录  电视剧  /media/电视节目
docker内目录同步  /media/电视节目 | /links/电视节目 | /links/电视节目/未识别
等我同步完再次测试

**Comment by Always67** [comment]
![微信截图_20220526150144](https://user-images.githubusercontent.com/42529007/170435708-e10a6900-b26b-4872-8003-7253e9071ffe.jpg)
感觉电视剧这一块还是有问题的。
我的R18文件夹设置了不识别，但是仍然被识别，分类了。

**Comment by Always67** [comment]
重启了，重新安装还是这样。

**Comment by Always67** [comment]
剧集识别错误应该是多层目录的问题，现在通过分别添加/media/电视节目/国产剧，纪录片……解决了。
现在就是R18的识别问题。
![微信截图_20220527082720](https://user-images.githubusercontent.com/42529007/170605121-504c651d-24b9-402c-b1de-bea2fddade9
![微信截图_20220527082647](https://user-images.githubusercontent.com/42529007/170605125-2834130c-080c-47a6-859c-5070d981c42d.png)
d.png)
![微信截图_20220527082703](https://user-images.githubusercontent.com/42529007/170605124-dab0cb21-e9ec-40ca-872e-10f59d8cf467.png)
