### ISSUE TITLE
2.3.0文件转移失败

### ISSUE THREAD

**Issue by PoiYuudachi** [jxxghp/nas-tools#1820]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>v2.3.0
> 环境: docker or windows or Synology
>windows

## 你遇到什么问题了？

> 从2.2.3升到2.3.0后文件转移失败，降回去又能转移成功，两个目录都在同一个盘内
文件名：[NC-Raws] 惑星公主蜥蜴騎士 - 16 (Baha 1920x1080 AVC AAC MP4) [83904691].mp4
转移方式：移动

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by zwwsirius** [comment]
我也遇到了一样的情况，文件转移出现错误码1

**Comment by jxxghp** [comment]
啥也没提供，怎么分析呢
