### ISSUE TITLE
现在不支持arm-v7了嘛？

### ISSUE THREAD

**Issue by muzhi1991** [jxxghp/nas-tools#1823]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.0
>
> 环境: docker  Linux raspberrypi 5.15.61-v7l+ #1579 SMP Fri Aug 26 11:13:03 BST 2022 armv7l GNU/Linux
>

## 你遇到什么问题了？
docker pull jxxghp/nas-tool
no matching manifest for linux/arm/v7 in the manifest list entries

现在是不支持arm-v7了吗，我看[文档](https://github.com/jxxghp/nas-tools/blob/master/docker/readme.md)里面是写支持 386/amd64/arm64/armv7 四大主流架构；

**Comment by jxxghp** [comment]
文档已更新
