### ISSUE TITLE
自定义RSS订阅提示下载添加下载任务失败

### ISSUE THREAD

**Issue by EliteOtaku** [jxxghp/nas-tools#1826]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本:v2.3.0 7e44d0af
>
> 环境: docker 
>

## 你遇到什么问题了？

自定义RSS订阅提示下载添加下载任务失败
![image](https://user-images.githubusercontent.com/29235152/198834346-fafcdb08-1355-434a-995a-f19662f4175c.png)

RSS链接如下
https://mikanani.me/RSS/Bangumi?bangumiId=2871&subgroupid=552
之前都运行正常，好像更新2.3后出问题了

添加下载任务失败：天竺鼠车车 (2021) S01 E04
种子：[Lilith-Raws] PUI PUI 天竺鼠车车 驾训班篇 / 天竺鼠车车 - 04 Baha1080pCHT
错误信息：无法打开链接：https://mikanani.me/Download/20221029/99ff972b8109be619f49797ee9f85f35d6ccadf1.torrent
但是点击预览后，显示又可以看到下载列表，然后点击下载按钮后会正常添加下载，所以有点莫名其妙。
![image](https://user-images.githubusercontent.com/29235152/198834418-c72374e0-b124-417b-b85c-7b6354d16fcf.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
日志我打包zip上传了，麻烦开发者大大看看是哪里的问题，非常感谢。

[nas-tools-stdout---supervisor-b__2tb5g.zip](https://github.com/jxxghp/nas-tools/files/9893794/nas-tools-stdout---supervisor-b__2tb5g.zip)

**Comment by Shurelol** [comment]
有没有想过先更新？

**Comment by EliteOtaku** [comment]
> 有没有想过先更新？

呃，你的意思是nastool需要更新下？我现在就去试试看啊

**Comment by EliteOtaku** [comment]
哇，没发现4小时前有更新了，bug消失！
