### ISSUE TITLE
建议 希望内置索引器。多增加站点。如 片库网这些

### ISSUE THREAD

**Issue by 15823382203** [jxxghp/nas-tools#1828]
强烈希望大佬可以把片库网和片源网给添加进内置索引器。这2个站资源特别丰富。特别是里面的4K中文资源源。对不玩pt的用户是很好的选择。。。或者能给个入口可以让我们自己添加站点到内置索引器里。这样就跟方便了

**Comment by jxxghp** [comment]
片源网加了，片库加不了

**Comment by 15823382203** [comment]
> 片源网加了，片库加不了

片库为什么加不了呢这个中文资源最多最全。那麻烦看下一下这几个有那些能用 bt之家  bt吧  阳光电影  bd影视  国配影迷
