### ISSUE TITLE
rss订阅报错

### ISSUE THREAD

**Issue by aiwu12** [jxxghp/nas-tools#1830]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.1
>
> 环境: docker or windows or Synology
>docker  Synology

## 你遇到什么问题了？

> 订阅了电视剧，看到订阅完成，但是并没有下载任务，第11集rss有资源也并没有下载，后来通过手动下载，并且全集16怎么就订阅完成了，日志
![image](https://user-images.githubusercontent.com/61082200/198870854-3e50ca73-42a6-4a1e-961c-8d61a0d9f127.png)

![image](https://user-images.githubusercontent.com/61082200/198856250-1e623c53-2dec-4d3d-9318-24601797acdc.png)
![image](https://user-images.githubusercontent.com/61082200/198856589-45a436e1-3c1d-4fdd-a95f-8cb8559c86eb.png)

![image](https://user-images.githubusercontent.com/61082200/198856225-64443c94-adc2-4456-bac7-b9b0b2810f3b.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
与#1817是同个问题原因
