### ISSUE TITLE
Rclone复制模式, 复制完成, 但是网盘文件夹里并没有影音文件

### ISSUE THREAD

**Issue by cls8428181** [jxxghp/nas-tools#1839]
> NASTool 版本: v 1.3.1
> 环境: 黑群晖 918 docker

rclone复制模式, 日志复制成功, 但是网盘文件夹里只有刮削文件, 没有影音文件

以下为相关截图
![image](https://user-images.githubusercontent.com/12572181/198863979-6d4fef87-f82e-494a-a03b-41167fb365a3.png)
![image](https://user-images.githubusercontent.com/12572181/198863999-db7aa02b-2218-4ff1-b61b-bb0e439395bf.png)
![image](https://user-images.githubusercontent.com/12572181/198864007-fdd9f205-bed2-4776-b838-5c4d48e31f40.png)
![image](https://user-images.githubusercontent.com/12572181/198864017-e4d3ec4e-98d9-4f12-8de2-c50b5cdcb4ff.png)
![image](https://user-images.githubusercontent.com/12572181/198864030-eb6ca42b-0255-463a-bf3f-f5b7c1e562ef.png)
![image](https://user-images.githubusercontent.com/12572181/198864064-9e7b2766-4228-481e-a901-ba7c4f4477b1.png)
其中Downloads是映射到容器内的下载目录等, Aliyun是映射到目录内的网盘路径, rclone配置文件也已经映射到容器内

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by cls8428181** [comment]
![image](https://user-images.githubusercontent.com/12572181/198864078-d9a1f23c-14ff-4a91-be69-cfd0ee596245.png)
![image](https://user-images.githubusercontent.com/12572181/198864097-3b47004c-2789-4181-80aa-2c6a96bbef50.png)
以上为复制完成之后, 网盘内文件

**Comment by Earendil-C** [comment]
检查一下你的阿里云根目录下是不是有/Aliyun这个文件夹。
要用Rclone复制的话，实际上是用rclone copy 文件 NASTOOL:/路径，也就是你媒体库设置的路径要和你要转移的网盘内路径一致，而不是实际路径。
你这样路径设置我建议使用移动，也能上传

**Comment by cls8428181** [comment]
> 检查一下你的阿里云根目录下是不是有/Aliyun这个文件夹。 要用Rclone复制的话，实际上是用rclone copy 文件 NASTOOL:/路径，也就是你媒体库设置的路径要和你要转移的网盘内路径一致，而不是实际路径。 你这样路径设置我建议使用移动，也能上传

我大概明白了, 意思我现在网盘里的根路径是家庭影院, 那么我映射到网盘内的路径就不能叫Aliyun, 应该是这样的映射 电影院/NASTOOL -> /家庭影院, 我这样理解有问题嘛? 还有因为下载的文件还需要做种, 移动的话好像就没法做种了

**Comment by Earendil-C** [comment]
> > 检查一下你的阿里云根目录下是不是有/Aliyun这个文件夹。 要用Rclone复制的话，实际上是用rclone copy 文件 NASTOOL:/路径，也就是你媒体库设置的路径要和你要转移的网盘内路径一致，而不是实际路径。 你这样路径设置我建议使用移动，也能上传
> 
> 我大概明白了, 意思我现在网盘里的根路径是家庭影院, 那么我映射到网盘内的路径就不能叫Aliyun, 应该是这样的映射 电影院/NASTOOL -> /家庭影院, 我这样理解有问题嘛? 还有因为下载的文件还需要做种, 移动的话好像就没法做种了

嗯嗯，是这样的。我建议你把你的网盘/家庭影院挂载到nastool里面去，即电影院/NASTOOL/家庭影院:/家庭影院，然后这样访问路径跟网盘路径就统一了。

**Comment by cls8428181** [comment]
> > > 检查一下你的阿里云根目录下是不是有/Aliyun这个文件夹。 要用Rclone复制的话，实际上是用rclone copy 文件 NASTOOL:/路径，也就是你媒体库设置的路径要和你要转移的网盘内路径一致，而不是实际路径。 你这样路径设置我建议使用移动，也能上传
> > 
> > 
> > 我大概明白了, 意思我现在网盘里的根路径是家庭影院, 那么我映射到网盘内的路径就不能叫Aliyun, 应该是这样的映射 电影院/NASTOOL -> /家庭影院, 我这样理解有问题嘛? 还有因为下载的文件还需要做种, 移动的话好像就没法做种了
> 
> 嗯嗯，是这样的。我建议你把你的网盘/家庭影院挂载到nastool里面去，即电影院/NASTOOL/家庭影院:/家庭影院，然后这样访问路径跟网盘路径就统一了。

好的, 感谢, 我尝试一下

**Comment by whistle003** [comment]
> > > 检查一下你的阿里云根目录下是不是有/Aliyun这个文件夹。 要用Rclone复制的话，实际上是用rclone copy 文件 NASTOOL:/路径，也就是你媒体库设置的路径要和你要转移的网盘内路径一致，而不是实际路径。 你这样路径设置我建议使用移动，也能上传
> > 
> > 
> > 我大概明白了, 意思我现在网盘里的根路径是家庭影院, 那么我映射到网盘内的路径就不能叫Aliyun, 应该是这样的映射 电影院/NASTOOL -> /家庭影院, 我这样理解有问题嘛? 还有因为下载的文件还需要做种, 移动的话好像就没法做种了
> 
> 嗯嗯，是这样的。我建议你把你的网盘/家庭影院挂载到nastool里面去，即电影院/NASTOOL/家庭影院:/家庭影院，然后这样访问路径跟网盘路径就统一了。

大佬，我和他刚好相反，我是目录同步完了有电影文件没有刮削的数据。映射如下：
本地/home/downloads是下载路径，映射到docker内的downloads，rclone挂载谷歌云盘，名称是NASTOOL，MOVIE是网盘内的路径，设置如下：
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/64147479/198966465-d55ad11b-5e71-42b1-aa30-8b7c695d2c50.png">
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/64147479/198966538-0b4024d1-b35c-4279-b9e2-52076bc1477b.png">
同步后只有电影文件，没有刮削的元数据，求救！
