### ISSUE TITLE
自定义识别词识别到有指定剧集的规则时忽略通用识别词规则

### ISSUE THREAD

**Issue by leo8912** [jxxghp/nas-tools#1843]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>**v2.3.2 728d79b5** 
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
**自定义识别词识别到特定剧集时，忽略通用规则，只使用特定剧集的识别词规则**
**一般国内综艺分上下集的问题，partA都是2*EP-1这样的，但是脱口秀大会因为有个集结篇，所以例外。我现在是把2*EP-1放在了通用规则里，但是单独添加一个脱口秀大会规则的话，规则是默认优先识别通用规则的，导致识别集数错误。**

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by leo8912** [comment]
**或者在通用规则里是否可以添加一个规则优先级排序，规则冲突时可以以优先级高的为准**

**Comment by Shurelol** [comment]
https://t.me/nastool_mi/99?comment=353896

**Comment by leo8912** [comment]
> 

![图片](https://user-images.githubusercontent.com/22719866/198868598-f7e602d7-0c15-496b-9db0-12cdd4cf0f0b.png)

这个我明白，但我的意思是一般综艺都是像喜剧大赛那样partA都是2*EP-1，只有脱口秀大会是例外，所以想的是partA=2*EP-1写进通用规则，以后只需要维护例外的就行。但现在是通用规则优先，通用替换完了，特殊的剧集识别就不起作用了
