### ISSUE TITLE
作者大佬 添加下站点到索引器 感谢啦

### ISSUE THREAD

**Issue by 15823382203** [jxxghp/nas-tools#1844]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.3.2
>
> 环境: docker 

## 你想要新增或者改进什么功能？

老大昨天和你提的加入片库和片源网。您今天更新了站点到索引器。马上去试用了搜索了资源，能收到的资源太少最后发现你添加的是hd高清片源网（这个资源不多）。不是片源网。。能不能麻烦大佬再把片源网给添加进去。 http://www.pianyuanw.com/这个片源网

然后这还有个最爱片源网 https://z2py.com/也可以加进去资源也很多。

大佬看到麻烦添加下这2个站到索引器。。万分感谢🙏🙏

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by 15823382203** [comment]
而且今天更新的这个高清片源网也无法下载。下载就提示挂载失败，无法从详情页面解析出地址。试了多个都这样
![Uploading MVIMG_20221030_210353.jpg…]()

**Comment by 15823382203** [comment]
![Uploading Screenshot_20221030-210925_Gallery.jpg…]()

**Comment by jxxghp** [comment]
bt的世界真复杂。
1、需要登录的都搞不了。
2、你的图片看不到

**Comment by 15823382203** [comment]
> bt的世界真复杂。 1、需要登录的都搞不了。 2、你的图片看不到

我发的这几个站不需要登陆也能下呢。就是进入资源详情页面后可能有几十个磁力链接。我也不知道为啥上传的图片显示不出来

> 
![Screenshot_20221030-210925_Gallery](https://user-images.githubusercontent.com/116971944/199169296-cb790d00-9983-4ea6-a937-69332a80f12f.jpg)

**Comment by 15823382203** [comment]
> bt的世界真复杂。 1、需要登录的都搞不了。 2、你的图片看不到

刚刚试了下现在片源网和片库确实要注册才能看 
下面这几个站不用注册也能访问  可以添加下   

最爱片源网  https://z2py.com/mv 不用注册
BT世界  https://btbtt12.com/  不用注册
老王磁力  https://laowangbi.top/ 不用注册
SKrBT     https://skrbtbi.top/ 不用注册
一个资源站。3个磁力搜索资源都挺多加上内置索引充实下资源
添加后你测试之能正常订阅不。反正上次更新那个高清片源网我测试时订阅不了提示错误
![Screenshot_20221101-140643_Soul](https://user-images.githubusercontent.com/116971944/199173339-71e96337-4b80-43df-834a-6a0329fbea12.jpg)
![Screenshot_20221101-140754_Soul](https://user-images.githubusercontent.com/116971944/199173363-d6ddea2a-d386-4a9a-811d-a434d5a510f9.jpg)
![Screenshot_20221101-140756_Soul](https://user-images.githubusercontent.com/116971944/199173403-990ff955-e650-4a8a-98c0-aaabc5b146a9.jpg)
![Screenshot_20221101-140956_Soul](https://user-images.githubusercontent.com/116971944/199173420-efe9b315-603d-43ee-8e38-5d8a2e32caa3.jpg)
![Screenshot_20221101-141011_Soul](https://user-images.githubusercontent.com/116971944/199173439-24560e87-d057-4b6e-b9d7-6ecdf75eb5b0.jpg)
![Screenshot_20221101-142754_Soul](https://user-images.githubusercontent.com/116971944/199173474-8794e046-9988-45dd-88bc-fefe4bfb34a2.jpg)
![Screenshot_20221101-142755_Soul](https://user-images.githubusercontent.com/116971944/199173492-7deae839-7214-4644-896d-4c1a974d3fc1.jpg)
![Screenshot_20221030-210915_Gallery](https://user-images.githubusercontent.com/116971944/199173537-4ca12a1f-83f4-45a4-a73b-53f745a43eab.jpg)

**Comment by jxxghp** [comment]
最爱片源网 https://z2py.com/mv ——要验证码，搞不了。
 https://btbtt12.com/ ——种子下载要多层链接，搞不了。
https://skrbtbi.top/——这个有cf循，估计也悬。
