### ISSUE TITLE
python安装运行报错：ModuleNotFoundError: No module named 'alembic.config'

### ISSUE THREAD

**Issue by whistle003** [jxxghp/nas-tools#1848]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.2
>
> 环境: ubuntu20.04
>

## 你遇到什么问题了？

> python3.8环境没有问题，依赖安装没有报错，运行出错：ModuleNotFoundError: No module named 'alembic.config'，alembic依赖安装的有。
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已搜索和浏览

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> root@localhost:~/nastool/nas-tools# python3 run.py
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from alembic.config import Config as AlembicConfig
ModuleNotFoundError: No module named 'alembic.config'

**Comment by whistle003** [comment]
> 使用docker安装的更新一下docker镜像就好了。
> 
> 以下是使用docker-compose的更新命令: 在nas-tools的docker-compose目录下执行
> 
> ```shell
> docker-compose pull
> docker-compose up -d --remove-orphans
> docker image prune
> ```

你好，我是直接在vps的python环境部署的

**Comment by smilexiaoyan** [comment]
> > 使用docker安装的更新一下docker镜像就好了。
> > 以下是使用docker-compose的更新命令: 在nas-tools的docker-compose目录下执行
> > ```shell
> > docker-compose pull
> > docker-compose up -d --remove-orphans
> > docker image prune
> > ```
> 
> 你好，我是直接在vps的python环境部署的

你好，尝试一下在nas-tools目录执行
```
python -m pip install -r requirements.txt
```

**Comment by whistle003** [comment]
> > > 使用docker安装的更新一下docker镜像就好了。
> > > 以下是使用docker-compose的更新命令: 在nas-tools的docker-compose目录下执行
> > > ```shell
> > > docker-compose pull
> > > docker-compose up -d --remove-orphans
> > > docker image prune
> > > ```
> > 
> > 
> > 你好，我是直接在vps的python环境部署的
> 
> 你好，尝试一下在nas-tools目录执行
> 
> ```
> python3 -m pip install -r requirements.txt
> ```

已解决，感谢大佬，python3.8版本会报这个错误，升级python3.10就不会了
