### ISSUE TITLE
windows nastool 局域网无法访问

### ISSUE THREAD

**Issue by zero617** [jxxghp/nas-tools#1851]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.2
>
> 环境: windows 
>

## 你遇到什么问题了？

> 局域网无法访问,只能本机访问
尝试过关闭防火墙 无效

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已浏览

## 给出程序界面截图、后台运行日志或配置文件

> ![image](https://user-images.githubusercontent.com/67105838/198972942-43f35b71-5cc9-4f3f-ab01-33493726baa3.png)

**Comment by AisukaYuki** [comment]
```
  # 【WEB管理界面监听地址】：如需支持ipv6需设置为::，如::无法访问可改为0.0.0.0
  web_host: '::'
```

**Comment by zero617** [comment]
> ` # 【WEB管理界面监听地址】：如需支持ipv6需设置为::，如::无法访问可改为0.0.0.0 web_host: '::'`

请问在哪里更改？
