### ISSUE TITLE
创建订阅时，默认规则不生效

### ISSUE THREAD

**Issue by lengyu-lys** [jxxghp/nas-tools#1852]
"## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> ![image](https://user-images.githubusercontent.com/40789111/198981211-a2b70c9d-2328-4304-b4c3-fa628c595e28.png) 
已经将“日常观影”设置为 默认规则，但是在创建新订阅时，默认的过滤规则依然是 “请选择”，而不是“日常观影”
![image](https://user-images.githubusercontent.com/40789111/198981597-a05424bf-9f28-46fc-8e0c-1c6ec01754ff.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 创建新订阅时，采用的过滤规则为指定的默认过滤规则

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
"

**Comment by jxxghp** [comment]
理解问题
