### ISSUE TITLE
关于合并RSS订阅和JK下载的需求

### ISSUE THREAD

**Issue by zwf19870623** [jxxghp/nas-tools#186]
首先感谢作者大大的辛苦开发

目前搜索影片是通过jk，想订阅只能通过rss订阅，而rss订阅筛选过程是通过定时筛选rss信息来过滤出订阅内容的。

这种情况下，如果每个站点rss有10条信息，录入10个站点rss链接，订阅频率为半小时，就会导致每半个小时就会扫描一次100条电影信息并进行tmdb识别与订阅的比对。

如果这半个小时之内某个站更新了11条rss记录，就会导致有一条被忽略无法获取，如果想要防止这种情况的产生，就要增加rss链接的条数，比如每个站20条以上，或者增加订阅频率，比如每15分钟订阅一次。

因为众所周知的原因，tmdb访问本身不稳定就需要一些特殊手段，这种筛选方式无形中加大了tmdb的请求数量，也降低了获取正确剧集的几率。

所以，本身jk的搜索功能，和rss订阅功能就相对有一些重复，能否直接使用jk的搜索，订阅改为按照订阅频率调用jk的搜索功能呢，这样rss链接也可以不用单独录入，当然rss订阅的机制我个人猜想应该是为了降低pt站的压力，但同样可以降低订阅频率，比如最快一小时搜索一次订阅，这样来解决。

因为包括rss订阅，各种系统规则也是摸索了好些日子才搞个差不多明白，作者开发起来应该用的精力更多，所以看看能否让它使用起来更简单，再次感谢作者的辛苦开发。

**Comment by jxxghp** [comment]
连tmdb是有缓存的，识别后的一个名称（不是一个种子）只会连接一次。
你的建议不考虑。

**Comment by zwf19870623** [comment]
jk本身录入过cookie了，也能做到订阅的工作，单独搞一个rss又有什么意义呢？

Mr Huang ***@***.***>于2022年5月26日 周四下午4:13写道：
