### ISSUE TITLE
windows目录转移提示成功，实际上没有移动

### ISSUE THREAD

**Issue by zero617** [jxxghp/nas-tools#1863]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.2
>
> 环境: windows
>

## 你遇到什么问题了？

> 目录转移提示成功，实际上没有移动
目录同步内原本填写的“/”，确认后都变成了“\”，不知道这有没有关系
![20221101_121100_229](https://user-images.githubusercontent.com/67105838/199159752-2189c50b-3225-4a8e-9530-20eb458659e4.png)
![20221101_121132_146](https://user-images.githubusercontent.com/67105838/199159780-c43a9b48-365d-4a51-8f1d-4d75d59e8487.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已经浏览过Issues、Wiki及TG公众号

## 给出程序界面截图、后台运行日志或配置文件

> 
![image](https://user-images.githubusercontent.com/67105838/199158707-a7a44e7e-5f64-4b6c-899d-bb118214930b.png)

**Comment by Shurelol** [comment]
tg下新的exe

**Comment by zero617** [comment]
> tg下新的exe

我用的是2.3.2最新版啊

**Comment by AisukaYuki** [comment]
路径自己手定填的还是点击选择的
![image](https://user-images.githubusercontent.com/17586327/199166230-9df1ad70-315e-41dc-bb38-e2fb7aeacf6f.png)
硬连接同盘，不用带盘符，/ 也会自动转义

**Comment by zero617** [comment]
> 路径自己手定填的还是点击选择的 ![image](https://user-images.githubusercontent.com/17586327/199166230-9df1ad70-315e-41dc-bb38-e2fb7aeacf6f.png) 同盘，不用带盘符，/ 也会自动转义

啊 第一张图片我放错了 我选的是移动 硬链接从以前就一直不行
