### ISSUE TITLE
新增文件无法触发自动同步功能

### ISSUE THREAD

**Issue by du724931566** [jxxghp/nas-tools#1866]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.2

> 环境: docker 

## 你遇到什么问题了？

> 同步目录无法自动检测。文件夹设置路径没有问题，之前版本是正常的，具体版本号没注意。到2.3.2的时候就失效了。已经测试过很多办法，都搞不定。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已经浏览过Issues

## 你期望的结果

> 修复

![image](https://user-images.githubusercontent.com/49524705/199275868-dfaee56a-16c0-4c54-bd2f-6ae967fb8345.png)
![image](https://user-images.githubusercontent.com/49524705/199275968-88d2ca6e-76ef-4aeb-88c8-635ab8ee4a1d.png)
设置正确，但是不会触发自动同步，必须要手动点击同步才可以。

**Comment by du724931566** [comment]
期待大佬修复，我先退回2.3.0试试看是不是正常的~~

**Comment by lengxii** [comment]
我也是这样，目前没解决，看我的链接大佬回复了
https://github.com/jxxghp/nas-tools/issues/1707

**Comment by du724931566** [comment]
> 我也是这样，目前没解决，看我的链接大佬回复了 #1707

我记得我没用硬链接的时候是可以的。之前我用的2.2.3版本好像是移动模式就没有问题。

**Comment by whistle003** [comment]
> 日志里面没有任何有用信息，因为就没有报错。应该是就没触发。

我的也是这样，我是从本地硬盘往挂载的云端网盘移动。

**Comment by yang0026** [comment]
一样，更新到2.3.2之后目录同步设置下的目录都没了，重新添加之后仍然没有用。以前的版本是正常的。

**Comment by whistle003** [comment]
> 期待大佬修复，我先退回2.3.0试试看是不是正常的~~

2.3.0可以吗？

**Comment by du724931566** [comment]
> > 期待大佬修复，我先退回2.3.0试试看是不是正常的~~
> 
> 2.3.0可以吗？

怎么说呢，有点难受，可能需要重新安装。。从232回退2.3.0没有用

**Comment by du724931566** [comment]
> > 期待大佬修复，我先退回2.3.0试试看是不是正常的~~
> 
> 2.3.0可以吗？

实测2.3.0我全部纯净安装也是没用。。。。
同步模式不管是移动还是硬链接都无效。。。。
我准备现在换成2.2.3再看看了。。。

**Comment by du724931566** [comment]
准备重新在nas上装这个nastools再试一下，我是嫌弃tmdb不稳定，所以单独在服务器起了个docker全局走科学上网。
现在出问题的nastools是我在家里服务器的LXC里面装的docker，运行的nastools。

ε=(´ο｀*)))唉，大佬没回复。目前不知道怎么办

**Comment by jxxghp** [comment]
#1870 在这里讨论

**Comment by whistle003** [comment]
> #1870 在这里讨论

感谢大佬开这个讨论区，希望能一起排查问题，帮助nastool更加完美。
