### ISSUE TITLE
2.3.2新版移动文件失败

### ISSUE THREAD

**Issue by sleikang** [jxxghp/nas-tools#1869]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.2
>
> 环境:  windows
>

2.3.2新版又把原来添加的移动模式的先重命名给去掉了 造成win下rclone挂载alist网盘无法移动文件，这样的挂载网盘方式必须先重命名然后移动文件，直接移动会失败
![image](https://user-images.githubusercontent.com/23020770/199371131-4383170e-0dca-4437-aefa-ce2cd62e9627.png)

**Comment by Shurelol** [comment]
直接用rclone移动吧

**Comment by sleikang** [comment]
win下用rlone移动有点。。。，挂载本地磁盘方便多了，前面版本我加了移动前先重命名，作者更新几次又给改没了> 直接用rclone移动吧

**Comment by sleikang** [comment]
> 4ebc2ec66bb9eb8d42834f8bb8e08d922d7f625c

啊，不好意思 我以为你更新忘了给改没了，现在的版本更新真快代码几天不看都换了一大片🤦‍，我看了下现在的移动文件接口好像都大换血了，前面那个下载目录也是把115网盘的单独下载目录给去掉了，如果115下载和其他下载器之间切换的话每次得手动修改下载目录

**Comment by Shurelol** [comment]
建议加点注释，免得其他人改

**Comment by ausar47** [comment]
请问怎么把rclone挂载的文件夹映射到Docker里？我正常步骤会显示Error response from daemon: The volume does not contain a recognized file system.Please make sure that all required file system drivers are loaded and that the volume is not corrupted.用--network-mode可以映射但是容器内实际上访问不了文件夹
