### ISSUE TITLE
瓷器无法刷流

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#1871]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker 
>

## 你遇到什么问题了？
Nastool刷流瓷器的时候 明明出现新的符合条件的种子，但是仍然不会添加
![Uploading 31790F2A-6394-431D-BB8C-ECF5C2243ABC.jpeg…]()

**Comment by jxxghp** [comment]
没帐号，暂时没法分析。先这样吧。

**Comment by tevenfeng** [comment]
最近整了一个瓷器，有空我来分析下

**Comment by tevenfeng** [comment]
试着分析了一下
非免费的种子在刷流任务里面可以正常添加下载；
免费种子无法正常识别出免费状态，看代码运行结果，是xpath匹配免费img元素的时候没匹配成功。
但是在chrome里面用nt配置里面写的xpath字符串又能正常匹配到，就很奇怪。。

**Comment by tevenfeng** [comment]
'list' object has no attribute 'replace'
