### ISSUE TITLE
建议增加同时使用中文名和英文名搜索的开关

### ISSUE THREAD

**Issue by Azure99** [jxxghp/nas-tools#1875]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.2
> 环境: docker

## 你想要新增或者改进什么功能？

> 增加同时使用中文名和英文名搜索的开关

## 这个功能有什么可以参考的资料吗？

> 目前的搜索策略为，首先以默认语言检索，如果检索到结果那么直接返回，只有当默认语言检索不到结果时，才会尝试使用后备语言检索。然而，假设我们要检索一部外文影片并默认使用中文检索，那么如果在少数的索引站点中找到了零星资源，就会直接返回而不会使用英文去检索（事实上，使用英文可能得到更优的结果）。如果打开默认英文搜索，对于大多数动漫的检索效果又会下降（中文结果多）。因此，建议增加同时使用中文名和英文名检索两次的开关，并混合两次检索的结果，避免这种情况。

**Comment by jxxghp** [comment]
极端情况用快速搜索
