### ISSUE TITLE
opensubtitles字幕下载bug，无法手动调试

### ISSUE THREAD

**Issue by Imccccc** [jxxghp/nas-tools#1876]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.3 5f9cadcb
>
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？
提示开始从opensubtitles下载字幕，没有下文了。通过命令行测试可以

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
通过opensubtitles下载字幕，若失败有相关日志（搜索不到、空等），亦或是可以打开debug

## 给出程序界面截图、后台运行日志或配置文件
无

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
<img width="1246" alt="截屏2022-11-03 上午12 51 18" src="https://user-images.githubusercontent.com/3400692/199551769-fa49dbf0-6d52-4821-b716-cd8a31d1dcfc.png">

**Comment by Imccccc** [comment]
还要一个疑问，看代码逻辑中，在开始下载日志后，会进入search方法，search的结果会有日志。
https://github.com/jxxghp/nas-tools/blob/3048e5a6b74a006261bbe217376968b817bcfc56/app/subtitle.py#L87

难道是异常被吞了？

**Comment by jxxghp** [comment]
opensubtitle下载字幕是需要启浏览器的，极有可能是浏览器内核环境有问题，浏览器没启起来。确认下是否拉取的完整镜像。

**Comment by Imccccc** [comment]
确实是完整的镜像，我去翻翻代码看看怎么启动的浏览器内核

**Comment by Imccccc** [comment]
排查了下，应该是chromedriver没加代理
`options.add_argument("--proxy-server=proxy")
`

**Comment by wzxjohn** [comment]
> opensubtitle下载字幕是需要启浏览器的，极有可能是浏览器内核环境有问题，浏览器没启起来。确认下是否拉取的完整镜像。

遇到了同样的问题，`opensubtitle.org` 直连无法访问，也没有走配置的代理。此处是否应该新增选项允许走代理下载呢？
