### ISSUE TITLE
自定义订阅的下载设置里的限速和分享率停止做种不生效

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [jxxghp/nas-tools#1879]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vv2.3.2 728d79b5
>
> 环境: Synology
>

## 你遇到什么问题了？

> 自定义订阅的下载设置里的限速和分享率停止做种不生效，下载器用的是transmission

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已经浏览

## 你期望的结果

> 可以自动限速和达到分享率停止做种

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
transmission只支持部分功能。
更新新版再试试，留意小问号说明。
