### ISSUE TITLE
微信推送工作不正常

### ISSUE THREAD

**Issue by flowdesign-github** [jxxghp/nas-tools#1881]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.2 
>
> 环境: docker 
>

## 你遇到什么问题了？

> 微信推送已调通, 在微信端(企业微信或个人微信的企业号)可以使用关键字触发搜索, 同时在web端监控RSS订阅管理触发了下载后, 相应信息也推送到微信端, 但是下载完成后并没有向微信端推送完成的消息.

> 同时也尝试了在关联的QB中手工添加种子下载, 在web端的下载管理中可以观察到种子下载的实时状态更新, 但这个下载的相关信息并没有推送到微信端.

> 在微信推送设置中所有的推送开关都是开启状态

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 没找到对应的解释...

## 你期望的结果

> 看看是不是能够解决

## 给出程序界面截图、后台运行日志或配置文件
![1912483954](https://user-images.githubusercontent.com/87160795/199692847-2cb50b52-a63a-4dd6-a2a4-84a8e52ba7f0.jpg)
这个是第一次通过订阅管理触发的下载推送
在web端看到这个订阅的状态
![image](https://user-images.githubusercontent.com/87160795/199693125-757fc813-c838-4b9b-badd-6895f533e2f1.png)
![image](https://user-images.githubusercontent.com/87160795/199693189-3fbca290-5ca7-49ee-9ddf-255b6afefd9e.png)
这是手工在QB中添加种子下载后, web端可以看到的种子状态
![image](https://user-images.githubusercontent.com/87160795/199694120-ee03e844-ed50-4012-9ae7-8f8d246d9514.png)
微信里没有任何新消息推送产生
![1041745332](https://user-images.githubusercontent.com/87160795/199694224-401e06ef-70e2-4488-959a-58a23e9b0392.jpg)

**Comment by jxxghp** [comment]
分析日志
