### ISSUE TITLE
订阅时选择内封字幕片源的简繁版本

### ISSUE THREAD

**Issue by vvb7456** [jxxghp/nas-tools#1882]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.2
>
> 环境:synology

## 你想要新增或者改进什么功能？

> 希望能在订阅时 输入字幕组信息后能选择下载简体还是繁体版

## 这个功能有什么可以参考的资料吗？

> https://bangumi.moe/search/548ee0ea4ab7379536f56354
> https://bangumi.moe/search/548ee1204ab7379536f56357

**Comment by Shurelol** [comment]
过滤规则自己写
