### ISSUE TITLE
Windows版本Bug反馈贴

### ISSUE THREAD

**Issue by zero617** [jxxghp/nas-tools#1885]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.2
>
> 环境: windows
>

## 你遇到什么问题了？

> 硬连接失败 错误码-1

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已经浏览过Issues、Wiki及TG公众号仍无法解决

## 给出程序界面截图、后台运行日志或配置文件

> 
![20221103_101115_014](https://user-images.githubusercontent.com/67105838/199742454-7e78a721-14cd-4714-a9bc-fea79fd252de.png)

**Comment by zero617** [comment]
![20221103_101139_431](https://user-images.githubusercontent.com/67105838/199748502-ec79168a-7c7a-4c46-b15c-302f67d80dea.png)

**Comment by Shurelol** [comment]
建议路径添加盘符再试试

**Comment by zero617** [comment]
> 建议路径添加盘符再试试

![20221105_101157_559](https://user-images.githubusercontent.com/67105838/200096539-66eaffb1-e7a6-4fde-9bf8-43153955bfda.png)
依旧不行

**Comment by zero617** [comment]
@jxxghp 大佬 硬连接失败这个问题什么时候修复啊 2.4.0还是这样

**Comment by jxxghp** [comment]
> @jxxghp 大佬 硬连接失败这个问题什么时候修复啊 2.4.0还是这样

是NTFS格式吗？如果不是目前不支持软硬链接。

**Comment by zero617** [comment]
> > @jxxghp 大佬 硬连接失败这个问题什么时候修复啊 2.4.0还是这样
> 
> 是NTFS格式吗？如果不是目前不支持软硬链接。

那好吧 是exFAT的

**Comment by zero617** [comment]
1. 查找到了有效资源 但没有进行下载 
![20221106_091102_895](https://user-images.githubusercontent.com/67105838/200173409-d64c7279-fcad-46e7-9168-442bb2892e27.png)
2. 无法自动触发目录同步 需要手动执行
