### ISSUE TITLE
自动版本更新后 数据库字段未执行更新 日志报错

### ISSUE THREAD

**Issue by six00** [jxxghp/nas-tools#1890]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.3
>
> 环境: docker 
>

## 你遇到什么问题了？

> 自动版本更新后 数据库字段未执行更新

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
13:02:46 ERROR - 【Db】执行SQL出错：sql:SELECT ID, IGNORED, ENABLED FROM IGNORED_WORDS; parameters:None; no such table: IGNORED_WORDS
13:02:46 ERROR - 【Db】执行SQL出错：sql:SELECT ID, REPLACED, REPLACE, ENABLED FROM REPLACED_WORDS; parameters:None; no such table: REPLACED_WORDS
13:02:46 ERROR - 【Db】执行SQL出错：sql:SELECT ID, FRONT, BACK, OFFSET, ENABLED, REPLACED_WORD_ID FROM OFFSET_WORDS; parameters:None; no such table: OFFSET_WORDS
13:02:46 ERROR - 【Db】执行SQL出错：sql:DROP TABLE IGNORED_WORDS; parameters:None; no such table: IGNORED_WORDS
13:02:46 ERROR - 【Db】执行SQL出错：sql:DROP TABLE REPLACED_WORDS; parameters:None; no such table: REPLACED_WORDS
13:02:46 ERROR - 【Db】执行SQL出错：sql:DROP TABLE OFFSET_WORDS; parameters:None; no such table: OFFSET_WORDS
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Shurelol** [comment]
升级再说
