### ISSUE TITLE
配置两个站点 设置优先级 资源同时命中 但是下载是低优先级的站点

### ISSUE THREAD

**Issue by six00** [jxxghp/nas-tools#1891]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.3
>
> 环境: docker
>

## 你遇到什么问题了？

> 配置两个站点 设置优先级 资源同时命中 但是下载是低优先级的站点 mt优先级1 lemon优先级2

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 高优先级站点下载

## 给出程序界面截图、后台运行日志或配置文件

13:22:44 INFO - 【Searcher】开始检索 The Last Castle ...
13:22:44 INFO - 【Indexer】开始并行检索 The Last Castle，线程数：2 ...
13:22:44 INFO - 【Indexer】开始检索Indexer：mt ...
13:22:44 INFO - 【Indexer】开始检索Indexer：柠檬 ...
13:22:46 WARN - 【Indexer】柠檬 返回数据：9
13:22:46 INFO - 【Indexer】The Last Castle 2001 BluRay REMUX 1080p AVC DTS-HD MA 5.1-LHD 大小：33.17G 促销：普通 不符合订阅/站点过滤规则
13:22:46 INFO - 【Indexer】The Last Castle 2001 1080p BluRay DTS x265-10bit-LHD 最后的城堡/对垒风暴/叛将风云/铁狱暗战 【简繁字幕】 识别为 最后的城堡 (2001) 匹配成功
13:22:46 INFO - 【Indexer】The Last Castle 2001 1080p BluRay DTS x264-LHD 最后的城堡/对垒风暴/叛将风云/铁狱暗战 【简繁字幕】 识别为 最后的城堡 (2001) 匹配成功
13:22:46 INFO - 【Indexer】The Last Castle 2001 1080p EUR Blu-ray AVC DTS-HD MA 5.1-DiY@HDHome 大小：39.51G 促销：普通 不符合订阅/站点过滤规则
13:22:46 INFO - 【Indexer】The Last Castle 2001 BluRay 1080p DTS-HD MA 5.1 x265 10bit-BeiTai 最后的城堡 英语DTS-HDMA5.1/英简繁SUP字幕/章节 识别为 最后的城堡 (2001) 匹配成功
13:22:46 INFO - 【Indexer】The Last Castle 2001 720p BluRay DD5.1 x264-iFT 做种数为0
13:22:46 INFO - 【Indexer】The Last Castle 2001 1080p BluRay TrueHD 5.1 x264-WiLDCAT 做种数为0
13:22:46 INFO - 【Indexer】The Last Castle 2001 1080p EUR Blu-ray AVC DTS-HD MA 5.1-NEWHAM 大小：39.41G 促销：普通 不符合订阅/站点过滤规则
13:22:46 INFO - 【Indexer】The Last Castle 2001 2160p WEBRip DD+5.1 HDR x265-BLASPHEMY 做种数为0
13:22:46 INFO - 【Indexer】柠檬 共检索到 9 条数据，过滤 3，不匹配 0，有效资源 3，耗时 2 秒
13:22:51 WARN - 【Indexer】mt 返回数据：4
13:22:51 INFO - 【Indexer】The Last Castle 2001 BluRay REMUX 1080p AVC DTS-HD MA 5.1-LHD 大小：33.17G 促销：50% 不符合订阅/站点过滤规则
13:22:51 INFO - 【Indexer】The Last Castle 2001 1080p EUR Blu-ray AVC DTS-HD MA 5.1-DiY@HDHome 大小：39.51G 促销：50% 不符合订阅/站点过滤规则
13:22:52 INFO - 【Meta】The Last Castle 识别到 电影：TMDBID=2100, 名称=最后的城堡, 上映日期=2001-10-19
13:22:52 INFO - 【Indexer】The Last Castle 2001 1080p BluRay DD+5.1 x264-iFT 最后的城堡/叛将风云/对垒风暴/铁狱暗战 识别为 最后的城堡 (2001) 匹配成功
13:22:52 INFO - 【Indexer】The Last Castle 2001 1080p Blu-ray AVC DTS-HD MA 5.1-SHAWSHANK 大小：39.41G 促销：50% 不符合订阅/站点过滤规则
13:22:52 INFO - 【Indexer】mt 共检索到 4 条数据，过滤 3，不匹配 0，有效资源 1，耗时 8 秒
13:22:52 INFO - 【Indexer】所有站点检索完成，有效资源数：4，总耗时 8 秒
13:22:56 INFO - 【Downloader】添加下载任务：The Last Castle 2001 BluRay 1080p DTS-HD MA 5.1 x265 10bit-BeiTai，目录：/downloads/Movie，Url：xxx
13:22:56 INFO - 【Message】发送wechat消息：title=最后的城堡 (2001) 评分：7.1, text=微信搜索的电影 最后的城堡 (2001) 已开始下载 站点：柠檬 质量：BluRay 1080p 大小：13.55G 种子：The Last Castle 2001 BluRay 1080p DTS-HD MA 5.1 x265 10bit-BeiTai 做种数：14 促销：普通 描述：最后的城堡 英语DTS-HDMA5.1/英简繁SUP字幕/章节
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Shurelol** [comment]
升级再说

**Comment by six00** [comment]
> 升级再说

2.2.3不支持自动更新到最新版本？
提示更新失败
能否保留配置文件夹 直接拉取最新镜像 直接用原配置文件库启动？

**Comment by jxxghp** [comment]
设置种子优先，站点优先。
不先看下设置项吗？
