### ISSUE TITLE
日志报错不停地报reaped unknown pid，目录同步不可用

### ISSUE THREAD

**Issue by c939984606** [jxxghp/nas-tools#1897]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>  v2.4.0 06e6e3ca
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？
2台机器一台群晖，一台服务器，日志报错，目录同步不可用，下载监控可以

## 给出程序界面截图、后台运行日志或配置文件
<img width="1359" alt="iShot_2022-11-06_12 11 12" src="https://user-images.githubusercontent.com/34211368/200153817-364bca6b-21ac-4a2f-8484-208001037e99.png">
<img width="680" alt="iShot_2022-11-06_12 13 48" src="https://user-images.githubusercontent.com/34211368/200153835-1ebdb77c-933f-4c3c-88be-7fee8f065f99.png">

**Comment by c939984606** [comment]
目录监控要手动服务里触发

**Comment by jxxghp** [comment]
pid这个是浏览器退出，正常的。
目录无法同步看另一个讨论贴。
