### ISSUE TITLE
Windows 2.4.0 版本 无法打开 

### ISSUE THREAD

**Issue by zhaokun0721** [jxxghp/nas-tools#1899]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.4.0
>
> 环境: windows
>

## 你遇到什么问题了？

> win版 2.4.0 打不开 错误提示 Unhandled exception in script

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![屏幕截图 2022-11-06 123020](https://user-images.githubusercontent.com/46256897/200154577-08543e8b-39dd-4091-8cae-46ebaca271b3.jpg)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
win版数据库不会自动升级导致
