### ISSUE TITLE
来自下载器的转移完成消息的问题

### ISSUE THREAD

**Issue by leihao** [jxxghp/nas-tools#190]
识别和重命名都没问题，就是集数始终是0，集数列表也为空

KetingNasTool:
骸骨骑士大人异世界冒险中 (2022) S01 转移完成
评分：7.2，类型：动漫，共0集，总大小：512.78M，来自：Qbittorrent

查看详情

夏日重现 (2022) S01 转移完成
评分：7.7，类型：动漫，共0集，总大小：565.35M，来自：Qbittorrent

查看详情

**Comment by jxxghp** [comment]
看日志，一般是跨盘了或者其它原因导致操作系统处理的时候报错了，这个问题WIKI里有写。

**Comment by leihao** [comment]
重试了一把,日志看起来没问题

19:01:57 INFO - 【RMT】开始处理：/video/下载暂存/[Sakurato] Tate no Yuusha no Nariagari Season2 [02][AVC-8bit 1080P AAC][CHS].mp4
19:01:57 INFO - 【RMT】正在转移文件：[Sakurato] Tate no Yuusha no Nariagari Season2 [02][AVC-8bit 1080P AAC][CHS].mp4 到 盾之勇者成名录 - S02E02 - 第 2 集.mp4
19:01:57 INFO - 【RMT】文件 [Sakurato] Tate no Yuusha no Nariagari Season2 [02][AVC-8bit 1080P AAC][CHS].mp4 硬链接完成
19:01:57 INFO - 【MSG】发送telegram消息：title=盾之勇者成名录 (2019) S02 转移完成, text=评分：8.9，类型：动漫，共0集，总大小：444.97M，来自：Qbittorrent
19:01:58 INFO - 【EMBY】开始刷新Emby媒体库...
19:01:58 INFO - 【EMBY】Emby媒体库刷新完成
19:01:58 INFO - 【RMT】/video/下载暂存/[Sakurato] Tate no Yuusha no Nariagari Season2 [02][AVC-8bit 1080P AAC][CHS].mp4 处理完成，总数：1，失败：0
19:01:58 INFO - 【QB】设置qBittorrent种子状态成功
19:01:58 INFO - 【PT】文件转移结束
