### ISSUE TITLE
希望能为自定义订阅增加分组，优先级功能

### ISSUE THREAD

**Issue by u93724** [jxxghp/nas-tools#1909]
## 你使用的 NASTool 是什么版本，什么环境？
> NASTool 版本:v2.4.0 06e6e3ca
> 环境: docker 

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
为自定义订阅添加分组功能，在分组中的多个订阅中设置优先级，根据优先级洗版；为分组创建独立子文件夹
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
在使用自定义订阅追番或追剧时，有时需要追多个字幕组，如下图
![image](https://user-images.githubusercontent.com/57604382/200211592-58b4d3a5-4fb5-4ca7-ac7b-63cd3f98aea0.png)
希望能为这种为追一部番而添加多个字幕组的情况设定分组功能，将多个字幕组放在一个分组中，为这个分组创建独立的子文件夹便于管理，为单个分组中的几个字幕组设定优先级，实现洗版功能。为单个分组绑定独立的TMDB ID增加识别概率

**Comment by jxxghp** [comment]
你说的难道不是过滤规则的功能吗？
