### ISSUE TITLE
群晖nastools套件新建文件夹权限问题导致其他程序无法写入

### ISSUE THREAD

**Issue by doubletry** [jxxghp/nas-tools#1911]
> NASTool 版本: v2.3.2
>
> 环境: synology

## 你想要新增或者改进什么功能？

目前套件以root权限执行，但是比如套件版本的plex以plex用户执行，并不能删除nastools创建的目录下的内容。也导致其他以非root用户执行的程序例如CSF中文字幕套件不能在该文件夹下写入。

能不能给群晖的PT下载转移filetransfer.py和目录监控部分sync.py，在os.makedirs处增加一句：

```
import pwd
...
uid = pwd.getpwnam(username).pw_uid
os.chown(target_dir, uid, -1)
```
根据配置文件中输入的用户名更改所属用户。

或者先粗暴一点，直接设置文件夹权限为777。
```
os.chmod(target_dir, 0o777)
```

**Comment by jxxghp** [comment]
项目本身没有维护套件版
