### ISSUE TITLE
豆瓣挂了

### ISSUE THREAD

**Issue by goofysun** [jxxghp/nas-tools#1913]
> NASTool 版本: v2.4.0 bf63469a
>
> 环境: docker
>

豆瓣挂了，豆瓣推荐数据以及搜索都没有数据了

**Comment by henryxuu** [comment]
同样的问题

**Comment by fsy126** [comment]
同样的问题

**Comment by swjtuhyq** [comment]
同样的问题

**Comment by johowoo** [comment]
同样的问题

**Comment by shucunbin** [comment]
是有这个问题

**Comment by levn2002cn** [comment]
我也是这个问题。v2.4.0docker运行的。

**Comment by zydq123** [comment]
我也是，更新完挂了

**Comment by shucunbin** [comment]
这问题怎么关了，最新docker 版还是有这个问题啊

**Comment by jxxghp** [comment]
> 这问题怎么关了，最新docker 版还是有这个问题啊
> 
> @jxxghp 

不看公告吗，豆瓣api停了
