### ISSUE TITLE
柠檬id显示问题

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#1914]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker
>

> 描述一下你遇到的问题
柠檬id显示不准确 显示的是其他人id

![IMAGE 2022-11-07 13:19:13](https://user-images.githubusercontent.com/39802246/200232022-de8270d8-0fe0-4de4-a63d-ac0822a0253c.jpg)

**Comment by luoxiao-xy** [comment]
确实存在该问题
