### ISSUE TITLE
能否修改下登录壁纸，经常有恐怖电影的海报

### ISSUE THREAD

**Issue by xyswordzoro** [jxxghp/nas-tools#1916]
> NASTool 版本: v2.4.0
> 环境: docker
> 你想要新增或者改进什么功能？

能否修改下登录壁纸，登录的时候经常出现恐怖片的海报还有血腥的壁纸，
能加上之前的bing壁纸吗，不加的话加个开关关闭壁纸也行，谢谢
（额 不看恐怖片的路过。。。。）

**Comment by jxxghp** [comment]
看一下配置文件，而且有相同的问题提过了
