### ISSUE TITLE
资源搜索功能搜索任何关键字都直接返回结果：未找到数据

### ISSUE THREAD

**Issue by miss1ng** [jxxghp/nas-tools#1917]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>v2.4.0 bf63469a
> 环境: docker or windows or Synology
>docker on synology

## 你遇到什么问题了？

> 资源搜索功能搜索任意关键字都瞬间返回结果未找到数据

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![1](https://user-images.githubusercontent.com/18642603/200242830-1cb21a0b-5188-45c8-b9e9-360e4eadc428.png)
日志中没有关于资源搜索相关的记录

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by cyh303** [comment]
豆瓣有问题  关闭豆瓣联想搜索试试

**Comment by c939984606** [comment]
好像跟cookies 或者 浏览器UA有关系

**Comment by jxxghp** [comment]
看频道公告
