### ISSUE TITLE
自添加pt站点搜索无显示

### ISSUE THREAD

**Issue by cyh303** [jxxghp/nas-tools#1918]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.4.0
>
> 环境:  Synology
>

## 你遇到什么问题了？

> 内置索引器可以搜索到，自添加的pt站点搜索无结果
都是可以检索到数据，返回未匹配

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

![photo_2022-11-07_15-30-51](https://user-images.githubusercontent.com/34975117/200251228-b682e9bd-fe9c-489f-8a16-13379286ca4d.jpg)

![photo_2022-11-07_15-30-38](https://user-images.githubusercontent.com/34975117/200251257-9d886404-71fc-45b2-96e9-1be69d66bc82.jpg)

![photo_2022-11-07_15-30-25](https://user-images.githubusercontent.com/34975117/200251280-5e5cabfc-2471-41e9-9527-d252eb27813f.jpg)

15:21:49 INFO - 【Meta】正在查询TMDB电影：916719 ...
15:21:52 INFO - 【Meta】正在查询TMDB电影：916719 ...
15:21:52 INFO - 【Web】从TMDB中匹配到电影：报丧女妖 (2022)
15:21:52 INFO - 【Web】开始检索 报丧女妖 ...
15:21:52 INFO - 【Indexer】开始并行检索 报丧女妖，线程数：3 ...
15:21:52 INFO - 【Indexer】开始检索Indexer：mt ...
15:21:52 INFO - 【Indexer】开始检索Indexer：pthome ...
15:21:52 INFO - 【Indexer】开始检索Indexer：nicept ...
15:21:55 WARN - 【Indexer】pthome 返回数据：3
15:21:55 INFO - 【Indexer】pthome 共检索到 3 条数据，过滤 0，不匹配 0，有效资源 0，耗时 3 秒
15:22:00 WARN - 【Indexer】mt 返回数据：6
15:22:00 INFO - 【Indexer】mt 共检索到 6 条数据，过滤 0，不匹配 0，有效资源 0，耗时 8 秒
15:22:03 WARN - 【Indexer】nicept 未检索到数据
15:22:03 INFO - 【Indexer】所有站点检索完成，有效资源数：0，总耗时 11 秒
15:22:03 INFO - 【Searcher】报丧女妖 未检索到资源,尝试通过 Code Name Banshee 重新检索 ...
15:22:03 INFO - 【Indexer】开始并行检索 Code Name Banshee，线程数：3 ...
15:22:03 INFO - 【Indexer】开始检索Indexer：mt ...
15:22:03 INFO - 【Indexer】开始检索Indexer：pthome ...
15:22:03 INFO - 【Indexer】开始检索Indexer：nicept ...
15:22:06 WARN - 【Indexer】pthome 返回数据：3
15:22:06 INFO - 【Indexer】pthome 共检索到 3 条数据，过滤 0，不匹配 0，有效资源 0，耗时 3 秒
15:22:06 WARN - 【Indexer】nicept 未检索到数据
15:22:10 WARN - 【Indexer】mt 返回数据：8
15:22:10 INFO - 【Indexer】mt 共检索到 8 条数据，过滤 0，不匹配 0，有效资源 0，耗时 7 秒
15:22:10 INFO - 【Indexer】所有站点检索完成，有效资源数：0，总耗时 7 秒
15:22:10 INFO - 【Web】报丧女妖 未检索到任何资源

**Comment by cyh303** [comment]
站点无过滤规则，缓存已清理  已重启   豆瓣联想已关闭 开启都测试过   优先英文名一样开启关闭测试过

**Comment by zydq123** [comment]
一样，无法搜索

**Comment by zydq123** [comment]
关闭豆瓣联想后恢复，应该是豆瓣联想挂了

**Comment by jxxghp** [comment]
你这个资源那里连种子标题都不显示了。
docker版本没这问题，套件不清楚具体情况。

**Comment by zydq123** [comment]
我是群晖套件版，关了豆瓣联想以后恢复正常了
