### ISSUE TITLE
目录同步问题

### ISSUE THREAD

**Issue by leo8912** [jxxghp/nas-tools#192]
因为综艺/动漫命名识别会有问题，所以开启了综艺目录不识别同步，但是同步时仍然是识别了。并且未识别的被link到了
媒体库设置项下的未识别目录，不是目录同步下设置的电影电视剧 的未识别目录。
这是不是一个bug？盼修复，这样就可以把nas的hlink计划任务删除了
![图片](https://user-images.githubusercontent.com/22719866/170614090-ee019494-5ea6-4f0d-b42c-9e6a3628c3e6.png)

![图片](https://user-images.githubusercontent.com/22719866/170614126-92da7a4d-e9c4-4f0b-9b90-a2ea5a114bde.png)

**Comment by leo8912** [comment]
![图片](https://user-images.githubusercontent.com/22719866/170616409-dd5930bd-f0f6-428e-aed7-c053eddaae27.png)

以前反馈过，好像是 说文件夹嵌套的问题，但现在的文件夹确实是不相关的

**Comment by leo8912** [comment]
把媒体库下面的未识别目录删掉可以同步没问题了。(但是日志里还是会走一步识别的过程。。）

**Comment by leo8912** [comment]
![图片](https://user-images.githubusercontent.com/22719866/170618643-a8761043-d9e1-4500-ad71-ec802d2a40c2.png)

应该是走了配置格式2 的功能，能识别的还在目的地文件目录下按分类的逻辑建了新文件夹

**Comment by leo8912** [comment]
破案了，监控后，新的文件是会不识别硬链。但如果手动点同步还是会走识别。。。
有没办法手动同步按照目录同步的设置？

**Comment by jxxghp** [comment]
原来如些。。。

**Comment by jxxghp** [comment]
最新的代码已经做了区分处理
