### ISSUE TITLE
站点cookie存否检测

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#1923]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker 

> 你想要新增或者改进什么功能？
部分站点cookie过期时间过快，是否可以增加一个cookie存活检测。

## 这个功能有什么可以参考的资料吗？
无

**Comment by jxxghp** [comment]
那站点联通性测试是用来干啥的

**Comment by Tartarus2014** [comment]
> 那站点联通性测试是用来干啥的

这个功能不可能每天点啊

加个cookie判定 每天签到时候判定一次就可以
