### ISSUE TITLE
重命名英文标题 {en_title} 返回空字符串

### ISSUE THREAD

**Issue by boeto** [jxxghp/nas-tools#1933]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x

2.4.0

> 环境: docker or windows or Synology

docker

## 你遇到什么问题了？

> 描述一下你遇到的问题

重命名英文标题 {en_title} 返回空字符串，中文标题 {title} 则重命名正确

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

是

## 你期望的结果

> 描述以下你期望的结果

重命名英文标题 {en_title} 返回英文标题命名

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

英文重命名方案：`{en_title} ({year})/Season {season}/{en_title} - {season_episode} - {episode} - {part}`
中文重命名方案：`{title} ({year})/Season {season}/{title} - {season_episode} - {episode} - {part}`

识别转移：
![0](https://raw.githubusercontent.com/boeto/image/main/uploads/20221108132044.png)

日志处理完成：
```log
INFO - 【Rmt】/media/library/unknows/animes/01死神代理篇（001一020，漫画剧情）/001.mkv 处理完成，总数：1，失败：0
```
成功转移通知：
![1](https://raw.githubusercontent.com/boeto/image/main/uploads/IMAGE%202022-11-08%2012%3A26%3A38.jpg)

最终命名结果：
第一个是英文的重命名结果，第二个是中文重命名结果
![2](https://raw.githubusercontent.com/boeto/image/main/uploads/20221108131858.png)

**Comment by jxxghp** [comment]
文件名里没英文就不会有

**Comment by boeto** [comment]
如果出现空字符串，对于偏向使用英文重命名的用户体验会差一点哈～

还是希望能将文件名里没英文这种情况优化一下呢，文件名里没英文这种概率还是挺大的。

感谢能遇到这么好的媒体管理工具！

**Comment by jxxghp** [comment]
主要是要多查一遍TMDB。
可以用 original_title  原语种标题
