### ISSUE TITLE
订阅任务编辑反显问题

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#1937]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.1
>
> 环境: docker
>

![image](https://user-images.githubusercontent.com/54088512/200487993-fc6d77d8-c7ab-46e7-91c1-fbe4afe1b403.png)
我新增了订阅，没有选择搜索站点，想通过订阅下载，点保存之后。

再点编辑进来，默认搜索站点全选了
![image](https://user-images.githubusercontent.com/54088512/200488084-391b78fe-b831-4966-91db-961fba5fc434.png)

还有底下的全选，能不能订阅和检索分别全选

**Comment by gm-fire** [comment]
关注,遇到同样问题

**Comment by Shurelol** [comment]
不选就是全选

**Comment by boweic** [comment]
> 

不太明白原理，必须要同时有订阅站点和搜索站点么？一个订阅不可以只选一个订阅站点而不需要任何搜索站点么？

**Comment by thsrite** [comment]
> 不太明白原理，必须要同时有订阅站点和搜索站点么？一个订阅不可以只选一个订阅站点而不需要任何搜索站点么？

现在不是，不勾选搜索站点，默认全选了。
