### ISSUE TITLE
历史记录中删除记录，无法删除对应已重命名的文件

### ISSUE THREAD

**Issue by boeto** [jxxghp/nas-tools#1939]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
2.4.0
> 环境: docker or windows or Synology
docker

## 你遇到什么问题了？

> 描述一下你遇到的问题

历史记录中删除记录，无法删除对应已重命名的文件

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

是

## 你期望的结果

> 描述以下你期望的结果

历史记录中删除记录，对应删除已重命名的文件

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

在历史记录中删除记录：
![](https://raw.githubusercontent.com/boeto/image/main/uploads/20221108142439.png)

检查对应已重命名的文件没有被删除：
![](https://raw.githubusercontent.com/boeto/image/main/uploads/20221108142741.png)

**Comment by jxxghp** [comment]
检查权限

**Comment by Shurelol** [comment]
如果该转移识别时应用过识别词，并且删除记录时该识别词已被删除。

是会发生这种情况，后续将会修复
