### ISSUE TITLE
文件重命名当字幕组/制作组字段不存在时仍会输出分隔符

### ISSUE THREAD

**Issue by Xm798** [jxxghp/nas-tools#1945]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.1
>
> 环境: docker

## 你想要新增或者改进什么功能？

例如动漫重命名时，部分番剧有字幕组信息，而部分番剧由于是外挂字幕或者其他原因不存在字幕组信息，目前使用如下规则：

```
{title}({year})/Season {season}/{title}.{original_title}.{part}.{season_episode}.{audioCodec}-{videoCodec}-{videoFormat}.{releaseGroup}
```

输出结果如下所示：

```
幻想万华镜.幻想万華鏡 The Memories Of Phantasm.S01E01-4k..mp4
幻想万华镜.幻想万華鏡 The Memories Of Phantasm.S01E11.AAC FLAC-HEVC-1080p..mkv
幻想万华镜.幻想万華鏡 The Memories Of Phantasm.S01E13.AAC AC3-HEVC-720p..mkv
```

可以看到不存在的 `{part}` `{audioCodec}` `{videoCodec}` 等信息不会输出前面的分隔符，但是 `{releaseGroup}` 不存在/识别不到时，仍会输出一个`.`。

**Comment by jxxghp** [comment]
所以为什么要用.呢，改成-或者空格

**Comment by jxxghp** [comment]
我改一下吧

**Comment by Xm798** [comment]
> 我改一下吧

感谢！
