### ISSUE TITLE
jackett无法链接，导致登陆加载异常

### ISSUE THREAD

**Issue by ocean521** [jxxghp/nas-tools#1948]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>2.4.1
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 我确信jackeet配置的没有问题，但是在NASTOOLS索引器中测试，返回结果为失败(11月6日还是正常的)。同时,NASTOOLS登陆加载时间非常长，约两分钟，日志中没有相关内容。调整为自建索引，情况有改善，加载时间约20秒，不知道是不是硬件配置低了，威联通462C。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已查阅

## 你期望的结果

>希望有人可以测试一下，是我个人问题还是普遍问题。

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Toylee2019** [comment]
同样情况 NASTOOLS登陆时间没问题 但是返回失败

**Comment by youfly** [comment]
我也同样的情况，被搞的没脾气，准备要放弃了。

**Comment by youfly** [comment]
我的原因找到了。看了昨天的源码，把里面的连接一个个的放在浏览器都都可以访问，所以判断是docker和jackett的网络不通的原因。
由于nastools的代理设置不支持用户名密码配置，所以我用了macvlan来设置nastools网络到翻墙网关，这导致nastools的网络和宿主机不通。
解决方案：
要使mavlan网络的宿主机互通参考：https://blog.csdn.net/weixin_44907046/article/details/123144254
或将jackett部署到其他主机，不要部署在和nastools同一个宿主机里。
或将nastools改为bridge网络，翻墙只能等nastools代理设置支持密码配置。

**Comment by Diluka** [comment]
同一个docker网络中，终端里面ping都是通的，但是测试失败
