### ISSUE TITLE
TAG 为空导致 NAS-Tool 无法监控下载及转移文件

### ISSUE THREAD

**Issue by marcosteam** [jxxghp/nas-tools#1949]
## 你使用的 NASTool 是什么版本，什么环境？

NASTool 版本:  v2.4.1 e6b3b8b4

环境: docker

## 你遇到什么问题了？

添加的下载任务无法添加 TAG，导致 NASTOOL 无法识别下载进度及转移文件

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

是

## 你期望的结果

正常添加 TAG 以管理下载

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/25745812/200558765-17ec63b4-6651-4d5b-95ff-3ce2ead8166e.png)
![image](https://user-images.githubusercontent.com/25745812/200558859-a1f369f1-f8c4-4bb8-b67a-0f1fd45ca9af.png)
![image](https://user-images.githubusercontent.com/25745812/200558915-310e62b6-f116-4c75-9144-9ea78c575438.png)

**Comment by jxxghp** [comment]
给日志
有没有TAG跟能不能看到进度没有直接关系，除非你打开了只管理NAStool添加的下载

**Comment by marcosteam** [comment]
> 给日志 有没有TAG跟能不能看到进度没有直接关系，除非你打开了只管理NAStool添加的下载

20:15:54 INFO - 【Downloader】添加下载任务：龙珠超.超级英雄.2022.4K.日语中字.Dragon.Ball.Super.Super.Hero.2160P.X264.AAC.Japanes.Chinese.4096*2048p，目录：/downloads/movie，Url：（省略）
20:15:54 INFO - 【Message】发送iyuu消息：title=龙珠超：超级英雄 (2022) 评分：8.0, text=WEB搜索的电影 龙珠超：超级英雄 (2022) 已开始下载 站点：动漫花园 质量：4k 大小：34.6G 种子：龙珠超.超级英雄.2022.4K.日语中字.Dragon.Ball.Super.Super.Hero.2160P.X264.AAC.Japanes.Chinese.4096*2048p 促销：免费

与下载相关的 Log 只有这个，而且确实开启了只管理 NAStool 添加的下载，资源的添加方式是 WEBUI 的资源搜索功能手动点击下载的，Telegram 群里也有较多人表示有这个现象。

**Comment by jxxghp** [comment]
> > 给日志 有没有TAG跟能不能看到进度没有直接关系，除非你打开了只管理NAStool添加的下载
> 
> 20:15:54 INFO - 【Downloader】添加下载任务：龙珠超.超级英雄.2022.4K.日语中字.Dragon.Ball.Super.Super.Hero.2160P.X264.AAC.Japanes.Chinese.4096_2048p，目录：/downloads/movie，Url：（省略） 20:15:54 INFO - 【Message】发送iyuu消息：title=龙珠超：超级英雄 (2022) 评分：8.0, text=WEB搜索的电影 龙珠超：超级英雄 (2022) 已开始下载 站点：动漫花园 质量：4k 大小：34.6G 种子：龙珠超.超级英雄.2022.4K.日语中字.Dragon.Ball.Super.Super.Hero.2160P.X264.AAC.Japanes.Chinese.4096_2048p 促销：免费
> 
> 与下载相关的 Log 只有这个，而且确实开启了只管理 NAStool 添加的下载，资源的添加方式是 WEBUI 的资源搜索功能手动点击下载的，Telegram 群里也有较多人表示有这个现象。

我分析下看看，应该不是2.4.1导致的问题吧，是不是2.4.0就有这个问题了？

**Comment by marcosteam** [comment]
> > > 给日志 有没有TAG跟能不能看到进度没有直接关系，除非你打开了只管理NAStool添加的下载
> > 
> > 
> > 20:15:54 INFO - 【Downloader】添加下载任务：龙珠超.超级英雄.2022.4K.日语中字.Dragon.Ball.Super.Super.Hero.2160P.X264.AAC.Japanes.Chinese.4096_2048p，目录：/downloads/movie，Url：（省略） 20:15:54 INFO - 【Message】发送iyuu消息：title=龙珠超：超级英雄 (2022) 评分：8.0, text=WEB搜索的电影 龙珠超：超级英雄 (2022) 已开始下载 站点：动漫花园 质量：4k 大小：34.6G 种子：龙珠超.超级英雄.2022.4K.日语中字.Dragon.Ball.Super.Super.Hero.2160P.X264.AAC.Japanes.Chinese.4096_2048p 促销：免费
> > 与下载相关的 Log 只有这个，而且确实开启了只管理 NAStool 添加的下载，资源的添加方式是 WEBUI 的资源搜索功能手动点击下载的，Telegram 群里也有较多人表示有这个现象。
> 
> 我分析下看看，应该不是2.4.1导致的问题吧，是不是2.4.0就有这个问题了？

没，上一个版本没有这个问题

**Comment by jxxghp** [comment]
这个提交产生的问题 #1924 ，已修复。
