### ISSUE TITLE
希望增加BT rss的功能

### ISSUE THREAD

**Issue by Linon419** [jxxghp/nas-tools#195]
好多动漫都是在bt先发的，希望支持bt 的rss

**Comment by leihao** [comment]
直接丢进去订阅就行了,PT和BT没区别

**Comment by Linon419** [comment]
> 直接丢进去订阅就行了,PT和BT没区别
大佬，是这样吗
![Screenshot_2022-05-27-22-36-02-882_com android chrome](https://user-images.githubusercontent.com/29937602/170700397-6720a43a-a624-45bc-b14d-4471eecf0199.jpg)
![Screenshot_2022-05-27-22-36-14-865_com android chrome](https://user-images.githubusercontent.com/29937602/170700410-d53f7e50-a091-4ea1-95cd-d542e72c5cdd.jpg)

**Comment by jxxghp** [comment]
是不是理解的有问题？站占只维护站点，订阅在订阅管理里维护。
BT的命名太乱了，是个大坑，无法都兼容到。
