### ISSUE TITLE
下载标签失效，导致下载任务不会出现在下载中而直接进入近期下载

### ISSUE THREAD

**Issue by kylin7647** [jxxghp/nas-tools#1954]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.1
>
> 环境:  Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
下载器标签失效，导致下载任务不会出现在下载中而直接进入近期下载
## 你期望的结果

>希望下载的资源可以正常打上分类标签进入下载器

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/22770612/200597735-57465f82-6a12-4da0-92e5-156ba6b8b319.png)
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by bluehr** [comment]
> 这个昨晚改好了

大佬，我就是用的最新版本2.4.2发现还是有这个问题，正在下载是空列表，transmission中的任务也都没有标签 Transmission 版本：3.00 (bb6b5a062e) Docker部署的

**Comment by shom** [comment]
> > 这个昨晚改好了
> 
> 大佬，我就是用的最新版本2.4.2发现还是有这个问题，正在下载是空列表，transmission中的任务也都没有标签 Transmission 版本：3.00 (bb6b5a062e) Docker部署的

一样的问题linuxserver的镜像，transmission回退到version-3.00-r5还是一样。
