### ISSUE TITLE
推荐里面的豆瓣页面点击搜索一直卡着

### ISSUE THREAD

**Issue by ati121** [jxxghp/nas-tools#1958]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.4.1 4bd6388
>
> 环境: docker
推荐里面的豆瓣页面点击搜索一直卡着..等多久都一直这样卡着没反应了.
#1964

**Comment by Melody713** [comment]
我也遇到了一样的问题。。。昨天2.4.0的时候还是正常的

**Comment by Melody713** [comment]
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/22575716/200728122-56b24807-6d5b-495a-9a4d-22cabc058511.png">
又看了下日志，里边有报错，都是通过豆瓣那边查询的时候出现的

**Comment by jxxghp** [comment]
#1964
