### ISSUE TITLE
自定义识别没有集数裁定范围和集数偏移选项

### ISSUE THREAD

**Issue by Xm798** [jxxghp/nas-tools#1959]
## 你使用的 NASTool 是什么版本，什么环境？

NASTool 版本: v2.4.0
环境: docker

## 你遇到什么问题了？

自定义识别只有集数定位，没有裁定范围和集数偏移选项。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

追踪到 #430，发现之前的 webUI 有裁定范围和集数偏移的输入选项。

> ![image](https://user-images.githubusercontent.com/48074861/200717708-35929602-4d2e-4bd0-8dab-59f95a65b09c.png)

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/48074861/200717312-2deadc73-46c1-46c6-b055-f4d8d198c8f7.png)

**Comment by jxxghp** [comment]
后面修复了，你版本没更新
