### ISSUE TITLE
订阅功能匹配成功未下载

### ISSUE THREAD

**Issue by MrLv0816** [jxxghp/nas-tools#1961]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.1
>
> 环境: Synology
>

## 你遇到什么问题了？

> 订阅海贼王,规则匹配成功,但是没有下载 , 开启洗版后仍然无法下载

![image](https://user-images.githubusercontent.com/46812909/200724564-58be0de8-df8a-4a20-be7c-b857383f8407.png)
![image](https://user-images.githubusercontent.com/46812909/200724742-6e912cd4-94c6-41a3-85d6-d168b2f6f41d.png)

**Comment by thsrite** [comment]
+1  一直没搞懂这块该怎么处理。

**Comment by xyswordzoro** [comment]
可能是订阅里的集跟实际的不匹配，我猜的，我是用自定义订阅 下载的，
建议使用自定义订阅功能 下载 海贼王
![QQ截图20221110093459](https://user-images.githubusercontent.com/86150433/200978843-00bdb452-359a-47d6-855c-8c2ba41077a9.png)

**Comment by MrLv0816** [comment]
> 可能是订阅里的集跟实际的不匹配，我猜的，我是用自定义订阅 下载的， 建议使用自定义订阅功能 下载 海贼王 ![QQ截图20221110093459](https://user-images.githubusercontent.com/86150433/200978843-00bdb452-359a-47d6-855c-8c2ba41077a9.png)

匹配成功了，并且也显示为有效资源，就是不下载，不知道为什么

**Comment by xyswordzoro** [comment]
> > 可能是订阅里的集跟实际的不匹配，我猜的，我是用自定义订阅 下载的， 建议使用自定义订阅功能 下载 海贼王 ![QQ截图20221110093459](https://user-images.githubusercontent.com/86150433/200978843-00bdb452-359a-47d6-855c-8c2ba41077a9.png)
> 
> 匹配成功了，并且也显示为有效资源，就是不下载，不知道为什么

你用自定义订阅呗 这个肯定没问题吧

**Comment by jxxghp** [comment]
日志打印的海贼王命名都是属于第1季，是通过自定义识别词强制转的？  转换词是啥，分享下我调试下。

**Comment by MrLv0816** [comment]
> 日志打印的海贼王命名都是属于第1季，是通过自定义识别词强制转的？ 转换词是啥，分享下我调试下。
eyIzIjogeyJpZCI6IDMsICJ0aXRsZSI6ICJcdTZkNzdcdThkM2NcdTczOGIiLCAieWVhciI6ICIxOTk5IiwgInR5cGUiOiAyLCAidG1kYmlkIjogMzc4NTQsICJzZWFzb25fY291bnQiOiAyMSwgIndvcmRzIjogeyI3IjogeyJpZCI6IDcsICJyZXBsYWNlZCI6ICIoPz1cXFtcdTdiMmMoODlbMi05XXw5WzAtOVswLTldfDEwWzAtM11bMC05XXwxMDRbMC0yXSkpIiwgInJlcGxhY2UiOiAiWzE5OTldW1x1N2IyYzIxXHU1YjYzXSIsICJmcm9udCI6ICIiLCAiYmFjayI6ICIiLCAib2Zmc2V0IjogIiIsICJ0eXBlIjogMiwgInNlYXNvbiI6IDIxLCAicmVnZXgiOiAxLCAiaGVscCI6ICJbT1BGYW5zXHU2N2FiXHU5NmVhXHU1MmE4XHU2ZjJiXVtPTkUgUElFQ0UgXHU2ZDc3XHU4ZDNjXHU3MzhiXVtcdTdiMmMxMDM5XHU4YmRkXVtcdTU0NjhcdTY1ZTVcdTcyNDhdWzEwODBwXVtNS1ZdW1x1N2I4MFx1N2U0MVx1NTE4NVx1NWMwMV0gIn0sICI5IjogeyJpZCI6IDksICJyZXBsYWNlZCI6ICJcdTZkNzdcdThkM2NcdTczOGIgLyBPbmUgUGllY2UgLSAoPz0oODlbMi05XXw5WzAtOVswLTldfDEwWzAtM11bMC05XXwxMDRbMC0yXSkpIiwgInJlcGxhY2UiOiAiW09uZSBQaWVjZSBcdTZkNzdcdThkM2NcdTczOGJdWzE5OTldW1x1N2IyYzIxXHU1YjYzXSAtICIsICJmcm9udCI6ICIiLCAiYmFjayI6ICIiLCAib2Zmc2V0IjogIiIsICJ0eXBlIjogMiwgInNlYXNvbiI6IDIxLCAicmVnZXgiOiAxLCAiaGVscCI6ICJbTkMtUmF3c10gXHU2ZDc3XHU4ZDNjXHU3MzhiIC8gT25lIFBpZWNlIC0gMTAzOSAoQi1HbG9iYWwgMTkyMHgxMDgwIEhFVkMgQUFDIE1LVikifSwgIjEwIjogeyJpZCI6IDEwLCAicmVwbGFjZWQiOiAiKFx1NmQ3N1x1OGQzY1x1NzM4YnxcdTZkNzdcdThjY2FcdTczOGIpXFxdKD89XFxbKDg5WzItOV18OVswLTlbMC05XXwxMFswLTNdWzAtOV18MTA0WzAtMl0pKSIsICJyZXBsYWNlIjogIlx1NmQ3N1x1OGQzY1x1NzM4Yl1bMTk5OV1bXHU3YjJjMjFcdTViNjNdIiwgImZyb250IjogIiIsICJiYWNrIjogIiIsICJvZmZzZXQiOiAiIiwgInR5cGUiOiAyLCAic2Vhc29uIjogMjEsICJyZWdleCI6IDEsICJoZWxwIjogIltTa3ltb29uLVJhd3NdW09uZSBQaWVjZSBcdTZkNzdcdThkM2NcdTczOGJdWzEwMzldW1ZpdVRWXVtXRUItRExdWzEwODBwXVtBVkMgQUFDXVtDSFRdW01QNCtBU1NdKFx1NmI2M1x1NWYwZlx1NzI0OFx1NjcyYykifX19fUBAQEBAQOa1t+i0vOeOi1MyMQ==

**Comment by Shurelol** [comment]
不下载的原因，是集数匹配不上。
tmdb上海贼王 第21季是从第892集-第1043集
而nastool自己生成的订阅集数列表是默认从1开始，也就是第21季缺第1集-152集

解决办法，订阅设置总集数2000，开始集数892

**Comment by Shurelol** [comment]
同样后续季，集数不从第1集开始的还有，[家庭教师](https://www.themoviedb.org/tv/45857-reborn/seasons)
