### ISSUE TITLE
windows版不能使用IP+端口的方式访问，只能localhost+端口本地访问

### ISSUE THREAD

**Issue by menloveszedking** [jxxghp/nas-tools#1963]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.4.1
>
> 环境: windows
>

## 你遇到什么问题了？

> windows版不能使用IP+端口的方式访问，只能localhost+端口本地访问

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> windows版使用IP+端口的方式访问

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
看配置文件中的说明web_host改成0.0.0.0
