### ISSUE TITLE
文件转移时发生错误

### ISSUE THREAD

**Issue by a18ccms** [jxxghp/nas-tools#1968]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.1 2313c4e3
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？
手动识别特定综艺的时候出错。
我的根目录结构是 `/media/video/tv/`下有四个综艺
‘’‘
├── 脱口秀大会3.Talk.Show.2020.S03.Complete.1080p.H264.AAC-PTerWEB
│   ├── 脱口秀大会3.Talk.Show.2020.S03.E01A.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── 脱口秀大会3.Talk.Show.2020.S03.E01B.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── 脱口秀大会3.Talk.Show.2020.S03.E02A.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── 脱口秀大会3.Talk.Show.2020.S03.E02B.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── 脱口秀大会3.Talk.Show.2020.S03.E03.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── 脱口秀大会3.Talk.Show.2020.S03.E04.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── 脱口秀大会3.Talk.Show.2020.S03.E05.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── 脱口秀大会3.Talk.Show.2020.S03.E06.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── 脱口秀大会3.Talk.Show.2020.S03.E07.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── 脱口秀大会3.Talk.Show.2020.S03.E08.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── 脱口秀大会3.Talk.Show.2020.S03.E09.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   └── 脱口秀大会3.Talk.Show.2020.S03.E10.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
├── Talk.Show.2019.S02.1080p.WEB-DL.H264.AAC-PTerWEB
│   ├── Talk.Show.2019.S02.E01.20190721.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── Talk.Show.2019.S02.E02.20190728.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── Talk.Show.2019.S02.E03.20190804.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── Talk.Show.2019.S02.E04.20190811.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── Talk.Show.2019.S02.E05.20190818.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── Talk.Show.2019.S02.E06.20190825.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── Talk.Show.2019.S02.E07.20190901.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── Talk.Show.2019.S02.E08.20190908.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   ├── Talk.Show.2019.S02.E09.20190915.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
│   └── Talk.Show.2019.S02.E10.20190922.1080p.WEB-DL.H264.AAC-PTerWEB.mp4
├── Talk.Show.2021.S04.1080p.WEB-DL.H265.AAC-PTerWEB
│   ├── Talk.Show.2021.S04.E01.Extra.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E01.Part1.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E01.Part2.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E02.Extra.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E02.Part1.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E02.Part2.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E03.Extra.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E03.Part1.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E03.Part2.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E04.Extra.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E04.Part1.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E04.Part2.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E05.Extra.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E05.Part1.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E05.Part2.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E06.Extra.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E06.Part1.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E06.Part2.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E07.Extra.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E07.Part1.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E07.Part2.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E08.Extra.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E08.Part1.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E08.Part2.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E09.Extra.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E09.Part1.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E09.Part2.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E10.Extra.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E10.Part1.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   ├── Talk.Show.2021.S04.E10.Part2.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
│   └── Talk.Show.2021.S04.Xain.Dao.1080p.WEB-DL.H265.AAC-PTerWEB.mp4
└── Talk Show.S1.2017.WEB-DL.1080p.H265.AAC-PThome
    ├── Talk Show.S1E01.2017.WEB-DL.1080p.H265.AAC-PThome.mp4
    ├── Talk Show.S1E02.2017.WEB-DL.1080p.VP9.Opus-PThome.mkv
    ├── Talk Show.S1E03.2017.WEB-DL.1080p.H265.AAC-PThome.mp4
    ├── Talk Show.S1E04.2017.WEB-DL.1080p.H265.AAC-PThome.mp4
    ├── Talk Show.S1E05.2017.WEB-DL.1080p.H265.AAC-PThome.mp4
    ├── Talk Show.S1E06.2017.WEB-DL.1080p.H265.AAC-PThome.mp4
    ├── Talk Show.S1E07.2017.WEB-DL.1080p.H265.AAC-PThome.mp4
    ├── Talk Show.S1E08.2017.WEB-DL.1080p.H265.AAC-PThome.mp4
    ├── Talk Show.S1E09.2017.WEB-DL.1080p.H265.AAC-PThome.mp4
    ├── Talk Show.S1E10.2017.WEB-DL.1080p.H265.AAC-PThome.mp4
    ├── Talk Show.S1E11.2017.WEB-DL.1080p.H265.AAC-PThome.mp4
    └── Talk Show.S1E12.2017.WEB-DL.1080p.H265.AAC-PThome.mp4

4 directories, 65 files
···
手动识别提示下面的错误。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是，Issues和我遇到的问题没有重合。这类错误，但是已经提示修复了。

## 你期望的结果

> 怀疑是特定的文件名造成的移动失败。我删除掉Web-Dl，能多一行成功提示，实际没有成功，因为发生错误那里还是会发生。
如果我的怀疑正确，期望修复的这个识别错误。

## 给出程序界面截图、后台运行日志或配置文件
```
2022-11-09 16:16:42,470	ERROR: 【Rmt】文件转移时发生错误：unexpected '{' in field name - Traceback (most recent call last):
  File "/nas-tools/app/filetransfer.py", line 581, in transfer_media
    dir_exist_flag, ret_dir_path, file_exist_flag, ret_file_path = self.__is_media_exists(dist_path, media)
  File "/nas-tools/app/filetransfer.py", line 853, in __is_media_exists
    dir_name, season_name, file_name = self.get_tv_dest_path(media)
  File "/nas-tools/app/filetransfer.py", line 1120, in get_tv_dest_path
    file_name = re.sub(r"[-_\s.]*None", "", self.__tv_file_rmt_format.format(**format_dict))
ValueError: unexpected '{' in field name

2022-11-09 16:16:42,471	ERROR: 【Rmt】文件转移时发生错误：unexpected '{' in field name - Traceback (most recent call last):
  File "/nas-tools/app/filetransfer.py", line 581, in transfer_media
    dir_exist_flag, ret_dir_path, file_exist_flag, ret_file_path = self.__is_media_exists(dist_path, media)
  File "/nas-tools/app/filetransfer.py", line 853, in __is_media_exists
    dir_name, season_name, file_name = self.get_tv_dest_path(media)
  File "/nas-tools/app/filetransfer.py", line 1120, in get_tv_dest_path
    file_name = re.sub(r"[-_\s.]*None", "", self.__tv_file_rmt_format.format(**format_dict))
ValueError: unexpected '{' in field name

```

删除WEB-DL后的日志
```
2022-11-09 16:27:23,481	INFO: 【Meta】正在查询TMDB电视剧：93509 ...
2022-11-09 16:27:23,490	INFO: 【Rmt】开始处理：/media/video/tv/脱口秀大会3.Talk.Show.2020.S03.Complete.1080p.H264.AAC-PTerWEB/脱口秀大会3.Talk.Show.2020.S03.E02B.1080p.H264.AAC-PTerWEB.mp4，转移方式：硬链接
2022-11-09 16:27:23,493	ERROR: 【Rmt】文件转移时发生错误：unexpected '{' in field name - Traceback (most recent call last):
  File "/nas-tools/app/filetransfer.py", line 581, in transfer_media
    dir_exist_flag, ret_dir_path, file_exist_flag, ret_file_path = self.__is_media_exists(dist_path, media)
  File "/nas-tools/app/filetransfer.py", line 853, in __is_media_exists
    dir_name, season_name, file_name = self.get_tv_dest_path(media)
  File "/nas-tools/app/filetransfer.py", line 1120, in get_tv_dest_path
    file_name = re.sub(r"[-_\s.]*None", "", self.__tv_file_rmt_format.format(**format_dict))
ValueError: unexpected '{' in field name

2022-11-09 16:27:23,494	INFO: 【Rmt】/media/video/tv/脱口秀大会3.Talk.Show.2020.S03.Complete.1080p.H264.AAC-PTerWEB/脱口秀大会3.Talk.Show.2020.S03.E02B.1080p.H264.AAC-PTerWEB.mp4 处理完成，总数：1，失败：0
```

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
你自己改了文件名的配置，而且改错了？

**Comment by a18ccms** [comment]
确实是我文件名中移动了一个参数，复制的时候多复制一个符号导致的。修复就正常了。
我修改这个文件名配置的原因是：
有个综艺：它一集分上下集。原文件名配置 生成类似文件名：`{title} ({year})/Season {season}/{title}-{part} - {season_episode} - 第{episode}集`
```
一年一度喜剧大赛-Part1 - S02E01 - 第1集.mp4
一年一度喜剧大赛-Part1 - S02E02 - 第2集.mp4
一年一度喜剧大赛-Part2 - S02E01 - 第1集.mp4
一年一度喜剧大赛-Part2 - S02E02 - 第2集.mp4
```
我认为这样生成是不对的。排序错落了.
所以我修改此处。生成变成。`{title} ({year})/Season {season}/{title} - {season_episode}-{part} - 第{episode}集`
```
一年一度喜剧大赛 - S02E01-Part1 - 第1集.mp4
一年一度喜剧大赛 - S02E02-Part1 - 第2集.mp4
一年一度喜剧大赛 - S02E01-Part2 - 第1集.mp4
一年一度喜剧大赛 - S02E02-Part2 - 第2集.mp4
```
