### ISSUE TITLE
telegram私聊搜索功能异常

### ISSUE THREAD

**Issue by AinzLimuru** [jxxghp/nas-tools#1972]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 在多用户操作机器人的过程中，发现与机器人私聊返回的搜索结果为其他用户的搜索结果。
![image](https://user-images.githubusercontent.com/59441476/200804757-bf971bba-a067-4ca5-b4a0-a01e6e86f7f0.png)
在上面的图片中连续两次输入1，第一次的结果正确，第二次应该不返回结果但是却返回了其他用户的搜索结果。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 第一次的结果正确，第二次不返回结果

## 给出程序界面截图、后台运行日志或配置文件

> ![image](https://user-images.githubusercontent.com/59441476/200804757-bf971bba-a067-4ca5-b4a0-a01e6e86f7f0.png)

**Comment by jxxghp** [comment]
现在确实是没有加用户区分的

**Comment by boysimple** [comment]
> ##
> > 第一次的结果正确，第二次不返回结果

我今天也遇到了类似的问题 我这个机器人按说是我自己用的 放在了我的一个群里面给了管理员权限 结果他监控了我在群里面的发言然后自动开始检索了一些电影，让我觉得莫名其妙……

**Comment by boysimple** [comment]
> 现在确实是没有加用户区分的

能不能在tg机器人上  加入useid和其他参数做一下区分 我的通知机器人在我的群里面有管理员权限 今天发现机器人居然监控我在自己的群里面说话 然后自动开始搜索下载电影了……

**Comment by jxxghp** [comment]
> > 现在确实是没有加用户区分的
> 
> 
> 
> 能不能在tg机器人上  加入useid和其他参数做一下区分 我的通知机器人在我的群里面有管理员权限 今天发现机器人居然监控我在自己的群里面说话 然后自动开始搜索下载电影了……

用webhook模式就没有这个问题。否则不能拉入群聊。
