### ISSUE TITLE
文件转移出错

### ISSUE THREAD

**Issue by kbuddy** [jxxghp/nas-tools#1973]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2 7579060b
>
> 环境: docker
>

## 你遇到什么问题了？

> 文件转移，采用复制方式，报错，直接在docker容器的shell中执行复制可以成功，排除权限问题。
错误日志：
19:14:04 INFO - 【Rmt】开始处理：/downloads/nastool/二十不惑2.Twenty.Your.Life.On.S02.2022.1080p.NF.WEB-DL.DDP2.0.x264-HDSWEB，转移方式：复制
19:14:04 INFO - 【Rmt】正在转移文件：二十不惑2.Twenty.Your.Life.On.S02E23.2022.1080p.NF.WEB-DL.DDP2.0.x264-HDSWEB.mkv 到 /media/电视剧/二十不惑/Season 2/二十不惑 S02E23 - 1080p WEB-DL.mkv
19:14:26 ERROR - 【Rmt】[Errno 5] I/O error: '/media/电视剧/二十不惑/Season 2/二十不惑 S02E23 - 1080p WEB-DL.mkv'
19:14:26 ERROR - 【Rmt】文件 二十不惑2.Twenty.Your.Life.On.S02E23.2022.1080p.NF.WEB-DL.DDP2.0.x264-HDSWEB.mkv 复制失败，错误码 -1

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 目前仍未解决

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
[Errno 5] I/O error:
