### ISSUE TITLE
手动识别文件会被错误识别

### ISSUE THREAD

**Issue by 757957414** [jxxghp/nas-tools#1976]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: docker
>

## 你遇到什么问题了？

> 1.手动识别会将 文件识别为目录 ，导致转移不了

![image](https://user-images.githubusercontent.com/23210825/200838132-1f689ea8-b0c6-4422-bc9e-a4bd77fcb625.png)
![image](https://user-images.githubusercontent.com/23210825/200838201-4ae52b01-c4c8-40b6-a974-d5205c5dbba1.png)

> 2.手动识别会自动继承上次转移的参数，正常不应该清空么？

![image](https://user-images.githubusercontent.com/23210825/200838324-2b11e1fe-6fa0-4b5b-98af-6f2f06038797.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 没有相关的问题

## 你期望的结果

> 正常运行

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/23210825/200838588-e0ecd02d-3f12-4d16-ad8c-979f7348e255.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
2.手动识别会自动继承上次转移的参数，正常不应该清空么？

——这个点醒了我，应该是因为上一次处理过剧集类的，填了集数定位信息，电影的时候没清空带过去了导致错误。

**Comment by eric1932** [comment]
关于1.把文件名全名复制到集数定位里面并替换集数为`{ep}`可以识别成功
