### ISSUE TITLE
自定义订阅 

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#1978]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker or
## 你想要新增或者改进什么功能？
自定义订阅任务中，可以手动更改部分剧集的状态么
（混合下载中，本地有了本集，然而自定义订阅不会改变状态，导致一直提示）

![AFC1A582-D51B-4924-A77C-53F6F394AC48](https://user-images.githubusercontent.com/39802246/200894227-4c0a4ebb-ab8e-4d5b-a447-89441cf9e979.png)

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/200895695-2e09b19c-b438-4989-aa57-78f1797c18e5.png)
不是可以手动设置已处理未处理么？

**Comment by Tartarus2014** [comment]
擦 手机端UI不可以
