### ISSUE TITLE
能不能不关联媒体服务器(jellyfin/emby/plex)

### ISSUE THREAD

**Issue by zouqiang1111** [jxxghp/nas-tools#1979]
> NASTool 版本: v2.4.2
>
> 环境: docker

## 可以不关联媒体服务器，NAS TOOLS订阅资源以后，我是搭配芝杜Z9X使用的。所以不太需要媒体服务器
现在没关联媒体服务器，首页会进行提示，其他信息看不到。如果提示，能不能以其他形式展

**Comment by xyswordzoro** [comment]
那就不关联，使用自定义订阅不就完事了，类似与qb的rss。

**Comment by zouqiang1111** [comment]
首页什么信息都看不到了，很难受



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月10日 08:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [jxxghp/nas-tools] 能不能不关联媒体服务器(jellyfin/emby/plex) (Issue #1979) |

那就不关联，使用自定义订阅不就完事了，类似与qb的rss。

**Comment by zouqiang1111** [comment]
> 不关联 首页就是看不到啊 PS 不要用邮件回复

我是说，首页提示未关联媒体服务器，原来首页那些信息就看不到了。不关联，也可以嘛，首页不需要一整页就显示那个未关联媒体服务器
