### ISSUE TITLE
希望备份功能可以备份到云端

### ISSUE THREAD

**Issue by xyswordzoro** [jxxghp/nas-tools#1980]
> NASTool 版本: v2.4.2
>
> 环境: docker

希望备份功能可以备份到云端，类似于ptpp的备份功能
当然这是锦上添花的需求，不重要，提出了供参考。

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
![QQ截图20221110084147](https://user-images.githubusercontent.com/86150433/200973056-ee369158-0dca-4fec-8d0c-399a88570d7e.png)

**Comment by jxxghp** [comment]
没这必要吧，自己下载备份传一份也不费多少事
