### ISSUE TITLE
给电视剧的每集的文件名称带上对应的每集标题

### ISSUE THREAD

**Issue by dawnsummit** [jxxghp/nas-tools#1983]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.4.2
>
> 环境: Synology docker

## 你想要新增或者改进什么功能？

> 电视剧识别的时候文件命名带上每集的标题

## 这个功能有什么可以参考的资料吗？

> MovieRobot/Sonarr.

![image](https://user-images.githubusercontent.com/172002/201007197-f461fdd2-5776-46d4-b106-f7923dfe645c.png)

**Comment by dawnsummit** [comment]
目前所有的选项里面没有每集的名称这个对应的字段

**Comment by xuanqb** [comment]
https://github.com/jxxghp/nas-tools/issues/1686

**Comment by dawnsummit** [comment]
我看了回复。Sonarr的解决方案是如果没有标题，就不会转移，有标题才会转移。就看作者想不想实现这个了。MovieRobot也是可以的。

**Comment by jxxghp** [comment]
> 我看了回复。Sonarr的解决方案是如果没有标题，就不会转移，有标题才会转移。就看作者想不想实现这个了。MovieRobot也是可以的。

你都这么说了，那我更不能实现了。 提问题模板里已经明确说了不能提及其它同类商业软件！
