### ISSUE TITLE
文件管理中的识别会识别成多个动漫

### ISSUE THREAD

**Issue by 757957414** [jxxghp/nas-tools#1985]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: docker 
>

## 你遇到什么问题了？

> 1.无法正确识别特别篇的内容（S00）
![image](https://user-images.githubusercontent.com/23210825/201021507-97d7c9f1-68ab-421f-b595-232beb5bf429.png)

![image](https://user-images.githubusercontent.com/23210825/201021467-f9af7054-cbbf-4470-be58-e4548c0e0142.png)

> 2.尝试通过文件管理中进行识别，发现会将其识别为多个不同的番剧很怪（非特别篇的就正常，但是又能正确的拿到别名。。）

![image](https://user-images.githubusercontent.com/23210825/201021613-f44bc12b-1f51-44cb-8e49-35767acefb90.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 没有相关问题

## 你期望的结果

> 正常运行

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/23210825/201022009-741d1a74-d559-48e3-ab28-2908373be661.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by 757957414** [comment]
![image](https://user-images.githubusercontent.com/23210825/201023358-e119ef5e-8f4d-4719-ad7b-c81cf552d6da.png)
补充一下日志，虽然看起来和这个功能并没什么关系....

**Comment by jxxghp** [comment]
![image](https://user-images.githubusercontent.com/51039935/201477294-a8ef2988-2d70-4375-8791-7b22eeb1f416.png)

估计是TMDB缓存的原因，清一下。
