### ISSUE TITLE
nastool下载器怎么支持群晖自带的download station

### ISSUE THREAD

**Issue by yeyinghai** [jxxghp/nas-tools#1986]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.42 d
>
> 环境: docker synology

## 你想要新增或者改进什么功能？
nastool下载器怎么支持群晖自带的download station
> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Shurelol** [comment]
不支持
