### ISSUE TITLE
通知建议

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#1988]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker 

> 你想要新增或者改进什么功能？

错误信息：请检查下载任务是否已存在 

这个可以加一个不通知么

![78288F5E-F1D8-4505-9AFB-5A67990468D5](https://user-images.githubusercontent.com/39802246/201034363-51bb91b1-1721-4c7f-a7df-38a0fbfc917a.jpeg)

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Shurelol** [comment]
推送设置里不是可以不选下推送载失败的信息？？？

**Comment by Tartarus2014** [comment]
主要是这不该算重复下载么 
这种还算下载失败么
![Uploading C771E327-523B-4F7F-8291-9DACD7BF5B46.jpeg…]()

**Comment by Tartarus2014** [comment]
![8F1E267A-24CE-45B2-A6B0-B87DEBA33DF1](https://user-images.githubusercontent.com/39802246/201222743-42bd7382-35eb-4a4f-a9e9-d417648ddb8b.jpeg)

主要是这不该算重复下载么
这种还算下载失败么
