### ISSUE TITLE
建议增加aria2下载器选项

### ISSUE THREAD

**Issue by firstvip** [jxxghp/nas-tools#199]
不知道这个难度有多大，但是增加一个Aria2的话对于非pt站真的挺有用的，希望下载器能多一个选项

**Comment by jxxghp** [comment]
其实普通bt站因为命名太不规范，这个工具在识别上体验会差很多。找些pt站玩玩吧，一些小站才是比较容易得到的。
Aria2不知道有没有大佬帮忙适配，我这边短期内不太考虑，PT应该没有人用这个的。

**Comment by firstvip** [comment]
感谢大佬回复，期待Aria2吧。
谢谢大佬辛勤刷版本

**Comment by fangguisheng** [comment]
同期待Aria2

**Comment by zhu327** [comment]
https://pypi.org/project/aria2-json-rpc/
