### ISSUE TITLE
订阅在电视剧完结前自动删除

### ISSUE THREAD

**Issue by xuanqb** [jxxghp/nas-tools#1993]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2 bdb3368b
>
> 环境: Synology docker
>

## 你遇到什么问题了？

> 为了解决`订阅在电视剧完结前自动删除`的问题，我设置了总集数为`30`，但是现在还是会自动删除，看日志是把自定义的总剧集数更新掉了

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 无

## 你期望的结果

> 保持用户设置的总集数不会变化

## 给出程序界面截图、后台运行日志或配置文件

> 2022-11-10 15:55:10,385	INFO: 【Meta】正在查询TMDB电视剧：93509 ...
2022-11-10 15:55:10,400	INFO: 【Rss】检测到TMDB信息变化，更新电视剧订阅 脱口秀大会 为 脱口秀大会，总集数为：19

**Comment by xuanqb** [comment]
> 已有pr提交，等待更新

s大 还有一个问题，是关于自定义订阅的，S00E21这集，在媒体库中实际上并不存在的，但是nt日志和前端页面都显示本地已存在，不知这次pr有没有修复
<img width="1586" alt="image" src="https://user-images.githubusercontent.com/25526210/201348732-804cfa4d-a44a-4ab3-964a-a2a5d6490cfe.png">

**Comment by jxxghp** [comment]
> > 已有pr提交，等待更新
> 
> s大 还有一个问题，是关于自定义订阅的，S00E21这集，在媒体库中实际上并不存在的，但是nt日志和前端页面都显示本地已存在，不知这次pr有没有修复 <img alt="image" width="1586" src="https://user-images.githubusercontent.com/25526210/201348732-804cfa4d-a44a-4ab3-964a-a2a5d6490cfe.png">

改了。
