### ISSUE TITLE
硬链接转移后的媒体无法在Emby播放

### ISSUE THREAD

**Issue by Loveddkr** [jxxghp/nas-tools#1998]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker/Unraid6.10.3
>

## 你遇到什么问题了？
硬链接转移后的媒体无法在Emby播放

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

无法解决

## 你期望的结果

能够通过Emby正常播放

## 给出程序界面截图、后台运行日志或配置文件
![Snipaste_2022-11-11_16-51-46](https://user-images.githubusercontent.com/24710291/201302917-1741ccfa-fb49-4d1b-b5c1-09ee70b0a499.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
[nas-tools-stdout---supervisor-xw5fu8_z.log](https://github.com/jxxghp/nas-tools/files/9988662/nas-tools-stdout---supervisor-xw5fu8_z.log)

**Comment by bluehr** [comment]
我想这应该跟你的解码设置有关，跟硬链接没关系
