### ISSUE TITLE
请求联系方式

### ISSUE THREAD

**Issue by SyngnathZ** [jxxghp/nas-tools#2]
作者您好！我这边之前也写了一个关于剧集检测更名和电影检测更名的小脚本，想看看能不能和您一起参与这个项目的开发！谢谢～

我的邮箱 Hei.jinghui@gmail.com

**Comment by BruceSuen720** [comment]
大佬们可有交流群？可以贴出来加一下吗

**Comment by jxxghp** [comment]
> 大佬们可有交流群？可以贴出来加一下吗

没有交流群哦，我主要是业余时间根据自己的需求写的，共享出来看大家有没有需要。目前没有精力做支持和维护。实在整不明白的可以提Issues或者给我发邮件：jxxghp@163.com。

**Comment by jxxghp** [comment]
> 作者您好！我这边之前也写了一个关于剧集检测更名和电影检测更名的小脚本，想看看能不能和您一起参与这个项目的开发！谢谢～
> 
> 我的邮箱 [Hei.jinghui@gmail.com](mailto:Hei.jinghui@gmail.com)

我的邮箱：jxxghp@163.com，有啥想法可以交流一起，共同完善 ：）
