### ISSUE TITLE
我媒体库用的是网盘,希望在复制,硬链,软链以外新增一个移动功能

### ISSUE THREAD

**Issue by 277383761** [jxxghp/nas-tools#200]
网盘几乎都是转存过来就等于完成下载了.原文件就可以直接移动,而用复制会很麻烦.用硬软链又多此一举,所以希望新增一个移动源文件至媒体库的功能.

**Comment by 277383761** [comment]
emby挂载的阿里网盘,转存文件至某个被监测的目录下自动批量命名后移动至电影或电视剧目录下..真不行哪怕自动批量命名也行,反正emby挂载的网盘都是手动触发扫描范围

**Comment by jxxghp** [comment]
移动是很危险的，配置错误会导致原数据损坏（不想移动的但不小心配成了移动）。总有人会配错的，不管是不是个人配置原因都有人会扯到工具上的，很麻烦。。。
