### ISSUE TITLE
自定义订阅中显示本地已存在，但媒体库中并不存在

### ISSUE THREAD

**Issue by xuanqb** [jxxghp/nas-tools#2000]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2 bdb3368b
>
> 环境: Synology docker
>

## 你遇到什么问题了？

> 自定义订阅中显示此集本地已存在，但媒体库中实际并不存在

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的

## 你期望的结果

> 自定义订阅中应显示为本地不存在

## 给出程序界面截图、后台运行日志或配置文件

> 
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/25526210/201350981-b5e8c6df-8823-4e02-b315-e3d804bb9d86.png">

**Comment by MrLv0816** [comment]
![image](https://user-images.githubusercontent.com/46812909/201352840-f17ba7ea-4255-46c7-908c-a335bd233952.png)
遇到相同问题 , 并且100%复现

**Comment by xyswordzoro** [comment]
不如不匹配tmdb信息，遇到就下载，有正则有规则一般都能控制了，因为tmdb信息更新也不及时

**Comment by jxxghp** [comment]
S00的判断有Bug，Dev已经改了，等更新。
