### ISSUE TITLE
目录同步硬链接问题

### ISSUE THREAD

**Issue by Dragon979783802** [jxxghp/nas-tools#2003]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>2.4.2
> 环境: docker or windows or Synology
>synology

## 你遇到什么问题了？
nastool在同一存储空间，但不在同一共享文件夹，跨文件夹不能硬链接问题吗，提示无法转移文件夹，错误代码-1.

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

无

## 你期望的结果
好像之前2.3版本可以在同一存储空间，可以跨文件夹硬链接。希望能改善一下。谢谢

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/113583334/201452595-2c916cd7-212f-4c3e-aa28-22efd3cdc458.png)

**Comment by jxxghp** [comment]
这类基础的问题一开始就解释过了，看看小秘书和WIKI都有。
