### ISSUE TITLE
通过NAS-TOOLS下载种子并提交到下载器

### ISSUE THREAD

**Issue by AinzLimuru** [jxxghp/nas-tools#2005]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 新增或修改NAS-TOOLS添加种子逻辑为先下载种子再提交种子的文件到下载器
> 部分场景下qb添加链接后，如果网络连接性不好或qb自身的负荷较高发生卡顿。会导致无法通过添加链接的方式进行下载。实际使用我已经遇到了这种情况，NAS-TOOL报错“Cookie过期/任务已存在/触发了站点首次种子下载”，根据源码定位分析，以及手动添加链接进行下载发现了这个问题。
> qb暂不支持将代理仅应用于torrent下载，因此通过NAS-TOOL进行下载可以避免添加种子失败的问题，同时也可以避免由于qb使用代理导致向tracker汇报的ip变为境外VPS链接的问题。

## 这个功能有什么可以参考的资料吗？

> qb上传种子的api https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#add-new-torrent
> python3下载文件 https://www.cnblogs.com/math98/p/8781901.html

**Comment by jxxghp** [comment]
现在不就是先下载种子然后传种文件内容过去的吗？磁力链除外。
```
# 下载种子文件
            content, retmsg = Torrent.get_torrent_content(url=url,
                                                          cookie=cookie,
                                                          ua=ua,
                                                          referer=page_url if referer else None)
```

**Comment by AinzLimuru** [comment]
brushtask.py的558行传入的是种子链接，并且add_torrent函数内并没有转换为种子文件直接将链接提交给了qbapi

**Comment by AinzLimuru** [comment]
下载种子文件这个函数在downloader.py内，但是查看使用后发现并未在brushtask.py内出现。

**Comment by jxxghp** [comment]
你是指刷流吗？刷流是不会先下载种子的。

**Comment by AinzLimuru** [comment]
是的，但是我无法确定这是不是我qb版本的问题我切换到4.3.8就可以了但是4.4.3.1会存在这个问题。所以如果都统一通过上传种子文件的方式进行刷流应该会更稳定。不然这段代码后面的逻辑是多次查找然后判定失败，如果网络比较差的话这么做可能也会有问题。

**Comment by ztx0079** [comment]
确实存在这个问题.希望统一下提交任务到qb的方式,提交torrent的方式会更稳定些
