### ISSUE TITLE
文件夹出现加载路径失败: [Errno 13] Permission denied错误

### ISSUE THREAD

**Issue by litanwei** [jxxghp/nas-tools#2009]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>v2.4.2
> 环境: docker or windows or Synology
>
Synology,使用框神套件安装.

## 你遇到什么问题了？

添加电影文件夹的时候出现
加载路径失败: [Errno 13] Permission denied
错误

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
提示已经这么明显，还来提问题吗

**Comment by litanwei** [comment]
> Permission denied

您好,我知道是权限的问题,我都全部设置了一遍,还是没有解决....

**Comment by kunjingdi** [comment]
我知道了   你要在共享文件夹里面设置权限，打开编辑后有一个本地用户的位置 点击然后选择系统内部账号那个选项把 nastool和sc开头  的可读写勾选保存就行了   这个设置里面可以把你其他的套件的访问权限进行修改

**Comment by RookieTerry** [comment]
> 我知道了 你要在共享文件夹里面设置权限，打开编辑后有一个本地用户的位置 点击然后选择系统内部账号那个选项把 nastool和sc开头 的可读写勾选保存就行了 这个设置里面可以把你其他的套件的访问权限进行修改

设置为只读权限，访问子文件夹时还是报这个错，访问父文件夹就没有报错
