### ISSUE TITLE
未找到数据没有找到任何电影、电视剧叫这个名字，豆瓣页面无法显示

### ISSUE THREAD

**Issue by mejeor** [jxxghp/nas-tools#2010]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: unraid docker+openwrt+ikuai
>

## 你遇到什么问题了？

1、在使用一段时间（不固定）后，搜索任何内容如：http://xxxx/medialist?s=s&f=1，返回的都是：
未找到数据没有找到任何电影、电视剧叫这个名字："s"。但是从TMBD推荐中可以正常搜索并下载。
2、豆瓣的所有内容都无法显示，页面为空白

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 未找到答案

## 你期望的结果

> 可以正常搜索或者有具体的报错日志，以方便排查

## 给出程序界面截图、后台运行日志或配置文件

> 
![image](https://user-images.githubusercontent.com/118060565/201477318-7c318192-a7a0-4e9a-afd7-27b5204465b1.png)
![image](https://user-images.githubusercontent.com/118060565/201477329-f9549bdb-e4c5-4416-8840-0d9723cff5e2.png)
![image](https://user-images.githubusercontent.com/118060565/201477347-6a3de600-1350-44e3-b715-ce261dfddc7a.png)
![image](https://user-images.githubusercontent.com/118060565/201477408-7c5bb955-d383-46b2-a7d7-83baa4751056.png)
![image](https://user-images.githubusercontent.com/118060565/201477414-1198ec34-4251-4ccd-ac67-3be9ad707db2.png)

**Comment by jxxghp** [comment]
是不是使用太频繁，豆瓣对你的IP做流控了吧。
