### ISSUE TITLE
转移已有剧集（不是通过 nas-tools）订阅 时，不产生新的 nfo 文件

### ISSUE THREAD

**Issue by ayuuli** [jxxghp/nas-tools#2012]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2 7579060b
>
> 环境: docker 
>

## 你遇到什么问题了？
当已存在的源剧集不包含念nfo 文件时，使用 nas-tools的目录转移功能，即使可以正确识别剧集内容，也不会生成新的nfo 文件
类似https://github.com/jxxghp/nas-tools/issues/329 的描述

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

是

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
程序日志：![image](https://user-images.githubusercontent.com/100129576/201486654-375bd832-edc0-439b-8cf2-3c6b67becb5b.png)
源文件夹和目的文件夹：![image](https://user-images.githubusercontent.com/100129576/201487134-dbe97c01-84d9-4056-8b34-5d7c966bf9d8.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
是的，文件已存在，不会再生成任何东西。

**Comment by ayuuli** [comment]
> 是的，文件已存在，不会再生成任何东西。

请问是指 nas-tools 只支持刮削通过nastools订阅的剧集，不支持刮削存量剧集吗？
