### ISSUE TITLE
手动识别或者更新识别是，不生产NFO文件、不下载剧集图片

### ISSUE THREAD

**Issue by Mrxlei** [jxxghp/nas-tools#2016]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2 bdb3368b
>
> 环境: docker+ Synology
>
## 你遇到什么问题了？
> 手动识别或者更新识别是，不生产NFO文件、不下载剧集图片
![1](https://user-images.githubusercontent.com/95324467/201506960-e96fc469-a4da-431d-bb1a-ba064b11372e.png)
![2](https://user-images.githubusercontent.com/95324467/201506961-cfc41803-e96d-496a-b7a6-2baed9458b6d.png)
![3](https://user-images.githubusercontent.com/95324467/201506962-c31f9466-77de-44dd-8b19-9c35c1ba87c8.png)

**Comment by RejeyFeng** [comment]
我下载了一个带字幕的，然后NAStool 不刮图片。。。郁闷，也不知道怎么手动刮

**Comment by jxxghp** [comment]
#2296
