### ISSUE TITLE
播放历史记录不刷新是怎么回事，

### ISSUE THREAD

**Issue by yilin101** [jxxghp/nas-tools#2020]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: docker  用的是plex媒体服务器
>

## 你遇到什么问题了？

> 播放历史记录不刷新，重新安装过也这样子。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 搜索过，暂未找到过解决

## 你期望的结果

> 能够刷新历史记录

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
截图
https://imgur.com/DyKWj50

> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by gradypark86** [comment]
同样是plex服务器，发现主页的播放记录一直停留在几个月前，plex播放时nastools的消息中心是有开始播放和停止播放的通知的。重新部署一次nastools发现只要设置了plex的服务器，主页的播放记录就会和之前一样出现。不知道nastools主页这个播放记录读取的是什么记录？

**Comment by yilin101** [comment]
> 同样是plex服务器，发现主页的播放记录一直停留在几个月前，plex播放时nastools的消息中心是有开始播放和停止播放的通知的。重新部署一次nastools发现只要设置了plex的服务器，主页的播放记录就会和之前一样出现。不知道nastools主页这个播放记录读取的是什么记录？

是的 我部署了几次  历史记录都没有更新过

**Comment by gradypark86** [comment]
我又仔细看了一下，发现首页的播放记录不是不更新，而是新的记录没有排在最上面。如图所示，我最近的一条播放记录（2022.12.5）排在了2022.5.26记录的下面。而我最上面的一条记录是9月12日的，在这之后的播放记录都在5.26之后才出现。

![image](https://user-images.githubusercontent.com/39909237/205554509-3612c23d-e855-4ee6-a941-9f86d7978ff2.png)

**Comment by yilin101** [comment]
> 我又仔细看了一下，发现首页的播放记录不是不更新，而是新的记录没有排在最上面。如图所示，我最近的一条播放记录（2022.12.5）排在了2022.5.26记录的下面。而我最上面的一条记录是9月12日的，在这之后的播放记录都在5.26之后才出现。
> 
> ![image](https://user-images.githubusercontent.com/39909237/205554509-3612c23d-e855-4ee6-a941-9f86d7978ff2.png)

我的也是没按时间排序，但是最近一次播放记录是10.15，都快两个月了，没有刷新
