### ISSUE TITLE
开启了模糊匹配，但是出现“未匹配到媒体信息”的电影未下载的情况

### ISSUE THREAD

**Issue by rockhia** [jxxghp/nas-tools#2023]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: docker 
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
进行了关键字模糊匹配，前面一个影片（匹配媒体信息）正常下载了，但是后面一个（未匹配到媒体信息）未下载。
![image](https://user-images.githubusercontent.com/90016652/201598284-57ca4223-835c-4b11-9140-3ac2966e5ac6.png)

![image](https://user-images.githubusercontent.com/90016652/201598496-590eee47-27e1-4e2b-9847-3596c662c6a0.png)

**Comment by lekibsha** [comment]
模糊匹配怎么弄，我一个都没找出来
15:25:00 INFO - 【Meta】正在查询TMDB电视剧：0，季：1 ...
15:25:00 INFO - 【Meta】正在查询TMDB电视剧：0，季：5 ...
15:25:00 INFO - The resource you requested could not be found.
15:25:00 INFO - The resource you requested could not be found.
15:25:00 INFO - The resource you requested could not be found.
15:25:00 INFO - 【Meta】正在查询TMDB电视剧：0，季：1 ...
15:25:00 INFO - The resource you requested could not be found.
15:25:00 INFO - The resource you requested could not be found.
15:25:00 INFO - The resource you requested could not be found.
15:25:00 INFO - 【Meta】正在查询TMDB电视剧：0，季：1 ...
15:25:00 INFO - The resource you requested could not be found.

**Comment by jxxghp** [comment]
用自定义订阅

**Comment by chunln** [comment]
> 用自定义订阅

使用模糊匹配后，无法删除此订阅了，单击仅刷新了页面，不会弹出操作窗
