### ISSUE TITLE
媒体整理-文件管理-无法下载字幕

### ISSUE THREAD

**Issue by freefly22** [jxxghp/nas-tools#2024]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: docker
>

## 你遇到什么问题了？
![image](https://user-images.githubusercontent.com/73732106/201686369-6bb47b6b-341f-44bb-a600-96b34f3973db.png)
> 描述一下你遇到的问题
如截图所示，媒体整理-文件管理-无法下载字幕。提示：未配置字幕下载器！实际是有配置字幕下载器的。
应该是bug吧

**Comment by Xecuss** [comment]
碰到同样的问题，查了下源码，/web/action.py 第3654行：
```python
success, retmsg = Subtitle().download_subtitle(items=subtitle_item, server="opensubtitles")
```
下载默认是使用"opensubtitles"，然后参考/app/subtitle.py：
```python
def download_subtitle(self, items, server=None):
        """
        字幕下载入口
        :param items: {"type":, "file", "file_ext":, "name":, "title", "year":, "season":, "episode":, "bluray":}
        :param server: 字幕下载服务器
        :return: 是否成功，消息内容
        """
        if not items:
            return False, "参数有误"
        if not server:
            server = self.__server
        if not server:
            return False, "未配置字幕下载器"
        if server == "opensubtitles":
            if self.__opensubtitles_enable:
                return self.__download_opensubtitles(items)
        elif server == "chinesesubfinder":
            return self.__download_chinesesubfinder(items)
        return False, "未配置字幕下载器"
```
目测 server=="opensubtitles"且实际配置中的opensubtitles关闭的时候，就会触发这个问题，不清楚是不是BUG。

临时解决可以进入docker的命令行，修改/web/action.py 第3654行的"opensubtitles"为"chinesesubfinder"（不要修改缩进）：
```python
success, retmsg = Subtitle().download_subtitle(items=subtitle_item, server="chinesesubfinder")
```
然后在容器命令行内执行
```shell
cd /nas-tools
supervisorctl reload
```
然后就可以使用，不过容器重启之后会还原修改。

**Comment by iwsyt** [comment]
docker运行的话可以将/web/action.py该文件挂载出来，删除第3654行中传入的server参数，此时该方法会自动从配置文件中获取用户配置的字幕下载器，我已经实验过了，可以解决该bug，不过就是页面显示还存在bug，实际添加任务成功，chinesesubfinder正常接收到任务，但显示失败
<img width="379" alt="image" src="https://user-images.githubusercontent.com/35320717/202765156-9f345a73-57dd-4506-bad0-3a67e945fb4e.png">
