### ISSUE TITLE
emby导入同步完后，emby有的片，但是nast里显示不存在

### ISSUE THREAD

**Issue by SelfEnough** [jxxghp/nas-tools#2027]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>2.4.2
> 环境: docker or windows or Synology
>win+docker同时

## 你遇到什么问题了？
emby导入同步完后，emby有的片，但是nast里显示不存在

顺便 详情能否直接链接跳转到emby详情  这样可以直接跳过去播放和管理，更方便  类似 jellyseerr

**Comment by jxxghp** [comment]
1.要说具体片名，什么界面。
2.没有计划。
