### ISSUE TITLE
猫站rss获取错误

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [jxxghp/nas-tools#2028]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2 bdb3368b
>
> 环境: docker
>

## 你遇到什么问题了？

> 猫站的rss用不了订阅功能，但是如果使用站点资源的话是能看到rss的内容的

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已浏览

## 你期望的结果

> 正确获取rss，可以使用订阅功能

## 给出程序界面截图、后台运行日志或配置文件

> 
![image](https://user-images.githubusercontent.com/78670748/201847772-06f0c345-6833-40f9-81a3-23a163deea4e.png)

**Comment by Shurelol** [comment]
建议先把rss链接粘贴到浏览器里看有没问题
