### ISSUE TITLE
PT站点能否添加TCCF和FRDS支持

### ISSUE THREAD

**Issue by yaoyiliang** [jxxghp/nas-tools#2030]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: synology

## 你想要新增或者改进什么功能？

> 添加PT站点TCCF和FRDS支持，现版本添加url、cookie和rss后可以正常显示统计数据，但是qbit和transmission自动下载会显示添加下载失败，种子信息有误。但是同样设置下TTG就可以正常下载
![image](https://user-images.githubusercontent.com/62255952/201866759-8f4c573e-7ba0-4e23-802e-dde1d654856d.png)

## 这个功能有什么可以参考的资料吗？

> 无

**Comment by jxxghp** [comment]
没帐号，测不了
