### ISSUE TITLE
消息通知增加发邮件提醒

### ISSUE THREAD

**Issue by PlexPt** [jxxghp/nas-tools#2031]
消息现在的方式都不太友好，平时使用邮件

**Comment by AinzLimuru** [comment]
如果支持交互就更好了，目前提供的方式很难在不改善网络质量的情况下实现比较方便的交互方式。微信的API目前已经没有办法个人申请，所以增加一个邮件的方式会更加的方便。

**Comment by link2fun** [comment]
> 如果支持交互就更好了，目前提供的方式很难在不改善网络质量的情况下实现比较方便的交互方式。微信的API目前已经没有办法个人申请，所以增加一个邮件的方式会更加的方便。

邮件交互是认真的么?
有那功夫网页端都操作完了

**Comment by AinzLimuru** [comment]
> > 如果支持交互就更好了，目前提供的方式很难在不改善网络质量的情况下实现比较方便的交互方式。微信的API目前已经没有办法个人申请，所以增加一个邮件的方式会更加的方便。
> 
> 邮件交互是认真的么? 有那功夫网页端都操作完了

也不一定是限定在邮件，至少是一个能够在国内网络下流畅使用的一个消息通知以及能够使用机器人进行下载操作的渠道。

**Comment by Shurelol** [comment]
比如？

**Comment by AinzLimuru** [comment]
就是希望能够在现有的社交软件上能够实现这一功能，这样的话可以更方便的分享给家人使用，毕竟不同人够接受一个新的应用或者网页能力不同。有很多现成的开源的微信机器人可以使用，简单搜了一下看上去API封装的还是比较完善的。如果可以的话可以增加这样的方式作为目前微信交互的一个替代方案。

**Comment by AinzLimuru** [comment]
类似于tg上的机器人这样的功能还是很方便的，所以希望能够继续在微信上使用这样的功能。

**Comment by Shurelol** [comment]
如果是为了分享给加人使用，不如搭个overseer或者jellyseer选片，效果更好，还方便

**Comment by AinzLimuru** [comment]
看着确实不错，我再研究一下，谢谢了

**Comment by PlexPt** [comment]
企业微信不能新增
Iyuu 3天消息就没了
server酱每天5条限制
现有的提示都有各种限制
就简单加个邮件通知就行了
@jxxghp

**Comment by PlexPt** [comment]
@Shurelol
