### ISSUE TITLE
自定义订阅，下载更新剧问题，以及确实已经下载，但显示已处理0

### ISSUE THREAD

**Issue by superain7** [jxxghp/nas-tools#2035]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: docker  Synology
>

## 你遇到什么问题了？

一，我现在有个问题，就是站点已经发布的电视剧种子，连载中的，比如现在已经更新到第3集，后续还有更新，那我订阅此剧，运行自定义后，是不是只能下载现在更新的种子，而已经发布的就没法再进行在订阅中实现下载了？

二，自定义订阅中，设置好订阅后，确实实现了下载，但显示中，依然显示已处理为0，如图所示。

<a href="https://imgse.com/i/zV427D"><img src="https://s1.ax1x.com/2022/11/16/zV427D.png" alt="zV427D.png" border="0" /></a>
> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
一、你自己试一下就知道了
二、我这里没有这个问题，如果仍有问题跟踪一下提供日志
