### ISSUE TITLE
初始化安装流程

### ISSUE THREAD

**Issue by WhileKing** [jxxghp/nas-tools#2036]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: docker 

## 你想要新增或者改进什么功能？

> 安装的过程中有些不太友好的地方：比如必须要申请 tmbd 的 key才可以，不然下载的时候提示下载成功，但是没有发送下载请求。希望可以在安装后进行一个引导式的安装过程，包含如下流程：
1. 设置管理员账号密码
2. 设置*TMDB API Key*
3. 设置是否需要二级分类策略（及二级策略的编辑）
4. 文件移动方式
5. 电影、电视剧重命名格式（默认值给确认）
6. 选择并设置媒体服务器（plex/emb/jellyifn）
7. 选择并设置下载器（Qb, tr, 115, aria2）
8. 选择并设置索引器（内建、Jackett、Prowlarr）
9. 媒体库的设置（设置路径）

目的：设置完成后，即可直接体验到`nastool` （消息推送作为可选项），初始化完成后，除消息推送外，均可直接使用。如：搜索、下载、自动重命名

## 这个功能有什么可以参考的资料吗？

> 如`gogs`、`Jenkins`的初始化安装

**Comment by jxxghp** [comment]
问题不在于是不是这样做更好，而是太费精力。

**Comment by WhileKing** [comment]
> 问题不在于是不是这样做更好，而是太费精力。

是开发层面么，这个我可以来PR。只是不是很清楚这个需求除了我以外还有多少人觉得安装比较繁琐和零散，以及项目结构可能是需要一点时间来浏览一下。
