### ISSUE TITLE
大佬你好，请问何时能把rargb的内建索引修好

### ISSUE THREAD

**Issue by laowangdegit** [jxxghp/nas-tools#2037]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 内建的索引目前已经相当不错，但是rargb用不了很难受，设备全局翻墙了也不行，欧美剧要是有rargb的加成，自己通过nastool的订阅设置一下就可以自动追剧了。不知道为啥我用jackett构建rargb也不行，曾经成功过一次就再也没成功了。之前好像看到过你在一个issue里说过可能添加chrome内核去破解，希望能把这个问题安排一下。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Shurelol** [comment]
订阅不需要索引支持，站点管理里有设置rss链接就可以。

**Comment by laowangdegit** [comment]
> 订阅不需要索引支持，站点管理里有设置rss链接就可以。

你没有看我的问题，答非所问，rargb怎么rss

**Comment by Shurelol** [comment]
不知道rarbg怎么rss就去谷歌，去百度

**Comment by laowangdegit** [comment]
> 不知道rarbg怎么rss就去谷歌，去百度

你确定能？我又不是没搜过

**Comment by laowangdegit** [comment]
> ![Screenshot_20221121-181612_Chrome.jpg](https://user-images.githubusercontent.com/16237201/203033489-6270567e-7eed-4fac-ae6e-68db049f8975.jpg)

对不起兄弟，是我声音大了，我几个月前开始用nastool的时候就是先了解到rss，想找个rss自动化的，我真查了没查到，最可能的rsshub我看了好几遍。所以你这个杂弄的，rss模板是啥
![image](https://user-images.githubusercontent.com/110841992/203037981-80ae268b-c22b-4dfc-b3bb-60868226cda8.png)
我这也有但试着修改不起作用，怎么指定内容

**Comment by laowangdegit** [comment]
> ![Screenshot_20221121-181612_Chrome.jpg](https://user-images.githubusercontent.com/16237201/203033489-6270567e-7eed-4fac-ae6e-68db049f8975.jpg)你这个不会也就是官方的那个吧，不能指定搜索的，前面没仔细看，看你前两个一样还以为是搜索的固定剧集，对不起，我刚才声音小了，你发这个有个毛用，害我浪费时间找了半天，以后看清楚问题再逼逼也不迟
