### ISSUE TITLE
Rclone复制失败，错误码5

### ISSUE THREAD

**Issue by boweic** [jxxghp/nas-tools#2040]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: docker
>

## 你遇到什么问题了？

> 使用手动管理文件，rclone到网盘，显示复制失败，错误码5

## 给出程序界面截图、后台运行日志或配置文件
![CleanShot 2022-11-16 at 23 14 11](https://user-images.githubusercontent.com/3311935/202219177-dfab9531-a14e-4ad4-b8e1-d5f286631d87.png)
<img width="211" alt="CleanShot 2022-11-16 at 23 14 39@2x" src="https://user-images.githubusercontent.com/3311935/202219283-db35dedc-f1b9-45d1-bb81-746e061a9baf.png">
<img width="437" alt="CleanShot 2022-11-16 at 23 15 12@2x" src="https://user-images.githubusercontent.com/3311935/202219432-23a36f31-0303-49fd-a2bb-e5c014bf4fe2.png">
![CleanShot 2022-11-16 at 23 16 12](https://user-images.githubusercontent.com/3311935/202219709-ecf2ae12-5f5a-49b9-8ce7-a562a5583b30.png)
![CleanShot 2022-11-16 at 23 16 33](https://user-images.githubusercontent.com/3311935/202219765-d2e729b8-ec33-4534-996d-d56d7fa08c27.png)

**Comment by Shurelol** [comment]
宿主机上rclone添加命名为NASTOOL的配置文件，然后映射到容器中。不需要实际挂载。

目录同步，目的目的直接填网盘内的路径即可

**Comment by boweic** [comment]
> 

我看了一下网盘里，文件夹都已经有了，且路径是符合预期的。就是没文件。

**Comment by boweic** [comment]
> 宿主机上rclone添加命名为NASTOOL的配置文件，然后映射到容器中。不需要实际挂载。
> 
> 目录同步，目的目的直接填网盘内的路径即可
> 
> 另外建议不要设置未识别目录，或者设置在本地而不是网盘路径



> 

我看了一下网盘里，文件夹都已经有了，且路径是符合预期的。就是没文件。

**Comment by Shurelol** [comment]
那在容器和宿主机分别直接用rclone copyto命令试试？

看看啥问题，有可能权限问题？

**Comment by boweic** [comment]
> 容器里也装rclone，进容器直接用呀

![CleanShot 2022-11-16 at 23 58 10](https://user-images.githubusercontent.com/3311935/202230306-39da60e0-2720-4b0d-9f62-e69ff8b169a3.png)
似乎是rclone设置的问题。docker容器内无法访问127.0.0.1？
所以有什么建议么？ip设置成什么可以让容器访问到宿主机的端口（小白是我）

**Comment by Shurelol** [comment]
容器网络用的什么？换成bridge试试？

**Comment by boweic** [comment]
> 容器网络用的什么？换成bridge试试？

搞定了，设置成bridge网关172.18.0.1，容器内外都可以访问了。
