### ISSUE TITLE
开启自动管理模式后，手动指定目录会导致自动分类失败，并下载到默认目录

### ISSUE THREAD

**Issue by McGuffinCN** [jxxghp/nas-tools#2041]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: 群晖7.1.1 Docker
> qbittorrent版本：docker 4.4.5

## 你遇到什么问题了？

> **操作流程**：
![image](https://user-images.githubusercontent.com/42736418/202231575-5ec6b6f7-cfef-4b24-b670-90d24e6d9579.png)
![image](https://user-images.githubusercontent.com/42736418/202231813-82f9a0b3-732f-4b58-8de9-12af17b0462a.png)
![image](https://user-images.githubusercontent.com/42736418/202231909-ffb6246b-52ef-4869-877c-910ed6f04b3b.png)
![image](https://user-images.githubusercontent.com/42736418/202232206-0d620b65-2eb8-4673-9fb2-4963c12d270f.png)
**总结：**
在开启自动管理模式后：
![image](https://user-images.githubusercontent.com/42736418/202233876-fe06856d-82d8-46b9-b77b-93f0fa214524.png)
这里的三个选项无意义，不管选哪个都会下到默认分类和默认目录。
如果选择自动下载，则分类目录都正确。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> ![image](https://user-images.githubusercontent.com/42736418/202233722-70ffb3d4-b732-4f91-acc6-0bae8694415c.png)
在开启自动管理模式后，此处的目录选项变为qb的分类选项，或者干脆把这三个选项去掉（因为不管选哪个都没用）

## 给出程序界面截图、后台运行日志或配置文件
[Uploading nas-tools-stdout---supervisor-r3sg6g6v.log…]()

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/202239246-e420cd68-98b7-4136-852e-87d4f1143b51.png)
建议多读几遍

**Comment by McGuffinCN** [comment]
> ![image](https://user-images.githubusercontent.com/16237201/202239246-e420cd68-98b7-4136-852e-87d4f1143b51.png) 建议多读几遍

qbittorrent分类标签配置无误，截图有。问题是分类并没有传递到QB
