### ISSUE TITLE
rclone复制 提示目录不存在

### ISSUE THREAD

**Issue by ltsj** [jxxghp/nas-tools#2049]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2 7579060b
>
> 环境: docker
>

## 你遇到什么问题了？

> 下载监控 模式选择 rclone 复制 提示目录不存在

![image](https://user-images.githubusercontent.com/30733960/202453030-18fae84b-6bca-4f2f-896d-3692ea95d260.png)
![image](https://user-images.githubusercontent.com/30733960/202450542-ca1240a6-5197-490b-b00e-e82378054c80.png)
![image](https://user-images.githubusercontent.com/30733960/202450787-aefaed4b-3fb9-46cb-90ee-48202ce16460.png)
![image](https://user-images.githubusercontent.com/30733960/202450897-addc27d3-9891-4777-a975-c4342ffde22e.png)

docker内测试rclone正常 另外添加目录同步的时候模式选择rclone复制 是正常的  而且也能正常同步
![image](https://user-images.githubusercontent.com/30733960/202451380-366377eb-e534-441a-be2c-c939f7bfa371.png)
![image](https://user-images.githubusercontent.com/30733960/202452564-541105ac-4da8-4ae5-ac55-b28a311a9498.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已搜索过issues 好像没有相关问题

**Comment by Shurelol** [comment]
下载监控，目的地是媒体库目录

媒体库目录改成网盘内路径

**Comment by ltsj** [comment]
> 网盘内路径

![image](https://user-images.githubusercontent.com/30733960/202454442-1b20be63-8055-4b40-88a5-c4af6bf3fe3f.png)
网盘内路径就是这个 。。。
