### ISSUE TITLE
豆瓣下载是否有bug

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#205]
![image](https://user-images.githubusercontent.com/39802246/170857898-aff8f13d-8f38-4826-b2e8-66d736291634.png)
我在自己的豆瓣上 关注了一个视频，然后在nastool里面点击豆瓣想看，搜索视频匹配到正确资源时候会卡住停止，qbit里面也没有看到相应资源增加。

**Comment by a1990210863** [comment]
我也是这个问题，请问怎么解决的呢？
