### ISSUE TITLE
媒体库自由设置能力

### ISSUE THREAD

**Issue by alsomail** [jxxghp/nas-tools#2050]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: 在群晖下搭建的docker环境
>

## 你想要新增或者改进什么功能？

>目录灵活组合能力

## 这个功能有什么可以参考的资料吗？

> 我的Plex服务器下面有多个媒体库，分类为：动漫、动漫剧场版、电影、电视剧、纪录片、综艺。
然而nastools的媒体库只有固定四个，电影、电视剧、动漫、未分类。
本来我想在媒体库下面将动漫剧场版添加到电影下，动漫、电视剧、纪录片、综艺添加到电视剧下，也就是形成如下目录：
电影
    动漫剧场版(共享目录) 奇幻(共享目录电影下子目录) 喜剧(电影下子目录) 动作(电影下子目录)……
电视剧
    动漫(共享目录) 综艺(共享目录) 纪录片(共享目录) 电视剧(共享目录)……

最后将共享目录设置为Plex服务器的媒体库。

结果识别的时候发现，只能在某个特定目录下创建子分类，无法识别我创建的目录。
这样对于Plex中的媒体库限制就比较大了，灵活度不够，希望可以增加功能解决

**Comment by alsomail** [comment]
结果识别的时候发现，只能在某个特定目录下创建子分类，无法识别我创建的目录。

也就是都将 电影 下的  喜剧 子文件夹识别为了根目录，生成了如下路径：
电影
    喜剧
        喜剧 奇幻 动作……

**Comment by Shurelol** [comment]
二级分类自己随便分

把二级分类的目录导入plex

**Comment by alsomail** [comment]
<img width="799" alt="image" src="https://user-images.githubusercontent.com/5887104/202460064-c6164f0b-fa2d-4563-a708-e6ab8b87ef5a.png">
我是想要制作成这样的效果。
<img width="404" alt="image" src="https://user-images.githubusercontent.com/5887104/202460156-f9501e58-54d3-4f1c-b155-7da7800b8d41.png">
同时分类文件也制作好了。
<img width="419" alt="image" src="https://user-images.githubusercontent.com/5887104/202460253-1af42d24-bf7e-4a47-b9d4-d0ee2cee60bc.png">
但是shi是最后下来它会以我的喜剧作为根目录创建二级目录

**Comment by Shurelol** [comment]
二级目录，会在电影/电视剧这些一级目录下建。不需要自己建。

Plex添加相应文件夹就行

**Comment by alsomail** [comment]
明白你的意思了，你的意思是plex的一个”电影“媒体库下面添加多个比如”悬疑“”奇幻“这样的文件夹。
不过其实如果这个二级目录可以自己定义位置还是有好处的，我的一个盘16t，已经占了12t了，如果电影下分类只能在一个共享目录，到最后盘满了还是有些局限性。

**Comment by jxxghp** [comment]
> 明白你的意思了，你的意思是plex的一个”电影“媒体库下面添加多个比如”悬疑“”奇幻“这样的文件夹。
> 
> 不过其实如果这个二级目录可以自己定义位置还是有好处的，我的一个盘16t，已经占了12t了，如果电影下分类只能在一个共享目录，到最后盘满了还是有些局限性。

一个分类下可以是多个盘的不同目录，会优先选择同盘的。
