### ISSUE TITLE
[WinError 1314] 客户端没有所需的特权

### ISSUE THREAD

**Issue by gyshier** [jxxghp/nas-tools#2052]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.42
>
> 环境: windows 
>

## 你遇到什么问题了？
22:43:03 INFO - 【MEDIASERVER】开始同步媒体库数据...
22:43:03 INFO - 【MEDIASERVER】媒体库数据同步完成，同步数量：0
22:49:36 INFO - 【Rmt】开始处理：G:\电视剧\Westworld.S01-S03.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH，转移方式：软链接
22:49:36 INFO - 【Rmt】正在转移文件：Westworld.S01E01.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH.mkv 到 D:\BBB\电视剧\欧美剧\西部世界 (2016)\Season 1\西部世界 - S01E01 - 第1集.mkv
22:49:36 ERROR - 【Rmt】[WinError 1314] 客户端没有所需的特权。: 'G:\\电视剧\\Westworld.S01-S03.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH\\Westworld.S01.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH\\Westworld.S01E01.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH.mkv' -> 'D:\\BBB\\电视剧\\欧美剧\\西部世界 (2016)\\Season 1\\西部世界 - S01E01 - 第1集.mkv'
22:49:36 ERROR - 【Rmt】文件 Westworld.S01E01.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH.mkv 软链接失败，错误码 -1
22:49:36 INFO - 【Rmt】正在转移文件：Westworld.S01E02.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH.mkv 到 D:\BBB\电视剧\欧美剧\西部世界 (2016)\Season 1\西部世界 - S01E02 - 第2集.mkv
22:49:36 ERROR - 【Rmt】[WinError 1314] 客户端没有所需的特权。: 'G:\\电视剧\\Westworld.S01-S03.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH\\Westworld.S01.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH\\Westworld.S01E02.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH.mkv' -> 'D:\\BBB\\电视剧\\欧美剧\\西部世界 (2016)\\Season 1\\西部世界 - S01E02 - 第2集.mkv'
22:49:36 ERROR - 【Rmt】文件 Westworld.S01E02.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH.mkv 软链接失败，错误码 -1
22:49:36 INFO - 【Rmt】正在转移文件：Westworld.S01E03.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH.mkv 到 D:\BBB\电视剧\欧美剧\西部世界 (2016)\Season 1\西部世界 - S01E03 - 第3集.mkv
22:49:36 ERROR - 【Rmt】[WinError 1314] 客户端没有所需的特权。: 'G:\\电视剧\\Westworld.S01-S03.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH\\Westworld.S01.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH\\Westworld.S01E03.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH.mkv' -> 'D:\\BBB\\电视剧\\欧美剧\\西部世界 (2016)\\Season 1\\西部世界 - S01E03 - 第3集.mkv'
22:49:36 ERROR - 【Rmt】文件 Westworld.S01E03.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH.mkv 软链接失败，错误码 -1
22:49:36 INFO - 【Rmt】正在转移文件：Westworld.S01E04.2160p.UHD.Blu-ray.REMUX.HEVC.Atmos.DoVi.TrueHD7.1-HDH.mkv 到 D:\BBB\电视剧\欧美剧\西部世界 (2016)\Season 1\西部世界 - S01E04 - 第4集.mkv
> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Shurelol** [comment]
用软连接，要右键以管理员启动

**Comment by gyshier** [comment]
> 
nastool以管理员启动？

**Comment by gyshier** [comment]
是的，软链接需要管理员
