### ISSUE TITLE
plex不能识别NASTOOL创建的软链接

### ISSUE THREAD

**Issue by gyshier** [jxxghp/nas-tools#2053]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.42
>
> 环境: windows 10

## 你遇到什么问题了？

> 描述一下你遇到的问题
电影文件用NAStool用软链接识别转移后不能被PLEX识别，显示空文件。
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Shurelol** [comment]
建议本地用命令做个软链接测试下，是plex不识别软链接还是不识别nastool做的软链接
