### ISSUE TITLE
硬链接时检测nfo文件

### ISSUE THREAD

**Issue by Cyberxxt** [jxxghp/nas-tools#2054]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: docker 
## 你想要新增或者改进什么功能？

在硬链接时检测源文件夹内nfo文件，从而匹配影视信息。在匹配完成后在目的地/源文件夹内下载代匹配信息的nfo

## 这个功能有什么可以参考的资料吗？
Emby针对文件夹内的nfo文件进行刮削识别，且搬迁数据不影响识别结果。

建议可以在硬链接之前检测一下源文件夹内nfo文件，因为以前用Emby手动匹配过很多视频，并且当时在文件夹内都刮削到了对应的nfo文件，可以先查找现有的nfo文件提升识别率。
另可以在匹配成功后在硬链接的文件夹里下载nfo，这样搬迁数据以后就不用二次匹配了。

**Comment by serenity666** [comment]
＋1

**Comment by jxxghp** [comment]
已有nfo的情况太多，不好判别的
