### ISSUE TITLE
只管理nastools添加的下载。功能无效

### ISSUE THREAD

**Issue by six00** [jxxghp/nas-tools#2056]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
> 环境: docker or windows or Synology
>docker 群晖

## 你遇到什么问题了？

> 基础设置中设置了“只管理nastools添加的下载”。然后手动在qb页面添加种子 正常开始下载后查看nastool日志 已经开始转移（这个地方也有问题 没下载完就开始转移 我尝试过qb设置为不完整文件添加后缀 也没有用 后面单独再提个issue吧） 查看文件确实已经在转移了

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 以查看

## 你期望的结果

> 设置该功能后 qb页面手动添加等任务不进行转移等操作

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/18079439/202596164-dc3127a0-6939-450a-b997-834cbacac110.png)
![image](https://user-images.githubusercontent.com/18079439/202596237-e1ded885-4be4-4aff-a680-3b4b963e07ce.png)
![image](https://user-images.githubusercontent.com/18079439/202596462-58eb3353-1dda-47c3-af59-6e272c296209.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
#1558
