### ISSUE TITLE
群晖套件2.4.2内建索引私有站搜索不到资源

### ISSUE THREAD

**Issue by 1294266616** [jxxghp/nas-tools#2057]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.4.2
>
> 环境: Synology矿神套件
>

## 你遇到什么问题了？

> 内建索引搜索不到资源，公共站点或jackett可以正常搜索且站点其他功能一切正常

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
已经搜索过了无果

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/52421598/202633627-cb8a9d0b-acc4-4485-9222-161b8825d26b.png)
![image](https://user-images.githubusercontent.com/52421598/202634487-4ae6c884-037a-4526-99dd-dea131f4f1f1.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by oreoleeus** [comment]
我也是这样的问题，PT站都是搜索后，能检索到数据，但是有效资源是0，公有站就可以，只有私有站这样

**Comment by jxxghp** [comment]
套件我没办法分析，你可以试试docker版本，如果还有问题再来提问
