### ISSUE TITLE
识别动漫电影目录不对和代理服务器问题

### ISSUE THREAD

**Issue by seanshangwenguang** [jxxghp/nas-tools#2058]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: Synology
>

## 你遇到什么问题了？

>
一：
下载动漫剧场版或者动画电影到下载文件夹后，识别到分类常常会分类到电影-外语电影下面，我看到动漫文件下面也是有外语电影这个子文价的，我都需要手动移过去。也无法使用手动识别，因为识别的时候只能选择电影不然就会显示在
tmdb里找不到这个电影，我觉得他要嘛识别到动漫-外语电影里面，要嘛识别到电影-动漫里面才对，这样不会和正常的外语电影混在一起。或者是我不知道怎么操作，可以告诉我方法吗？
二：
就是我看到有代理服务器，我有梯子但是一般梯子，用的是SSR +工具，都不是这两个格式的，请问是否考虑增加方式或者有没有解决办法？

## 你期望的结果

> 希望可以告诉我办法，谢谢

## 给出程序界面截图、后台运行日志或配置文件
<html>
<body>

名侦探柯南：万圣节的新娘 (2022)类别：外语电影 | 名侦探柯南：万圣节的新娘.mp4来自：手动整理 | 2022-11-15 15:38:40 |  
-- | -- | -- | --

<br class="Apple-interchange-newline">
</body>
</html>
> 如UI BUG请提供截图及配置文件截图

> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
一、自己配置分类和下载目录
二、只支持http、socks5
