### ISSUE TITLE
目录同步

### ISSUE THREAD

**Issue by ocean521** [jxxghp/nas-tools#206]
能否在目录同步处，为每一个待同步目录加一个开关，这样就可以单独同步某个目录，譬如下载目录呢，现在未使用NASTOOL下载的电影，监控下载似乎有些问题，没有形成硬链接

**Comment by Always67** [comment]
同样需求，有些基本不动的文件夹，每次手动点同步还会同步，有点浪费时间的感觉。

**Comment by jxxghp** [comment]
什么场景要去点手动同步，不都是增量变化自动同步吗？

**Comment by Always67** [comment]
![微信截图_20220530113605](https://user-images.githubusercontent.com/42529007/170912864-d4caa394-9272-4879-b42f-73060c36aefc.png)
比如我新增了一个文件夹，怎样触发自动同步呢？

**Comment by jxxghp** [comment]
有位同学已经PR了自定义识别的代码，在手动识别->自定义识别，可以指定目录识别，可以试试。
