### ISSUE TITLE
怎么配合alist 去使用

### ISSUE THREAD

**Issue by dl280** [jxxghp/nas-tools#2063]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.4.2
>
> 环境:  windows 
>

## 你遇到什么问题了？

> 我已经在windows上用RaiDrive将alist 的webdav挂载为本地网盘了，但无法用nas tools 去使用这些挂载的文件，目的目录不会生成视频文件

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
希望能正常使用
## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/63228072/202734366-7f359ac6-08a5-4309-816e-e12cde94ef53.png)
![image](https://user-images.githubusercontent.com/63228072/202734610-f7b68183-2e80-49d2-a1cf-116df3bf7bb1.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
去群里交流
