### ISSUE TITLE
未识别的影片没有被正确移动到“未识别目录”

### ISSUE THREAD

**Issue by northsea4** [jxxghp/nas-tools#2064]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: docker
>

## 你遇到什么问题了？

同步设置如下：
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/94440029/202744561-4248ff5b-e1b6-40d2-a428-e16bd2600dc1.png">

目录树：
```
|-- movies
|-- pending
|   `-- 千与千寻.中日双语.4K.HBR.WEB-DL.H265.AAC-AIU.mkv
`-- unknown
```

## 你期望的结果

同步执行后，因为`千与千寻.中日双语.4K.HBR.WEB-DL.H265.AAC-AIU.mkv`是不能自动识别的，所以预期应该是：

```
|-- movies
|-- pending
`-- unknown
    `-- 千与千寻.中日双语.4K.HBR.WEB-DL.H265.AAC-AIU.mkv
```

## 给出程序界面截图、后台运行日志或配置文件

但实际是下面这样的，`pending`目录也被带进去了：
```
|-- movies
|-- pending
`-- unknown
    `-- pending
        `-- 千与千寻.中日双语.4K.HBR.WEB-DL.H265.AAC-AIU.mkv
```

另外，「手动识别」里的路径也不正确。如图所示，路径是原始的路径。点击“转移”时，会提示“文件不存在”。
<img width="722" alt="image" src="https://user-images.githubusercontent.com/94440029/202746193-5bccc5de-b6a4-45fa-8ba5-2391f7425fcf.png">

**Comment by jxxghp** [comment]
你用的是docker，路径却是群晖的路径，这能成功吗？先搞清楚基础的问题。
这个版本已经运行很长时间，基本功能没有问题，先分析清楚再说，帮你看问题答复问题都需要花费别人的时间的。
