### ISSUE TITLE
nas-tool和ChineseSubFinder无法对接

### ISSUE THREAD

**Issue by tianwulele** [jxxghp/nas-tools#2065]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: [2.4.2]
>
> 环境: docker or windows or Synology
>J1900 黑群晖下的docker

## 你遇到什么问题了？

>as-tool对接ChineseSubFinder的时候，好像同步目录的时候无法下载，提示的是ChineseSubFinder下载字幕出错:physical video file not found，然后手动在nas-tool下载字幕的时候，提示未配置字幕下载插件，
然后我尝试了
nas-tool里面点击字幕侧栏
填写ChineseSubFinder的api和地址-保存-退出
然后点击旁边的opensubtitles
然后再点击ChineseSubFinder，可以正常下载字幕，
上面的操作之后 虽然界面上选定的是ChineseSubFinder
但是日志里面下载字幕的插件还是opensubtitles，
之后重启nas-tool和字幕插件又是提示未配置字幕下载插件

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 希望能够正常使用ChineseSubFinder，同时像emby和下载器一样给出测试按键，确定是否可以连接到ChineseSubFinder插件

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by jxxghp** [comment]
这个是老问题了，搜搜issues就能找到答案。
手动下载字幕强制用opensubtitles，要打开开关。
