### ISSUE TITLE
豆瓣想看列表读取成功，但是没有正常搜索下载

### ISSUE THREAD

**Issue by Mrxlei** [jxxghp/nas-tools#2066]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.4.2
>
> 环境: Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 豆瓣想看列表读取成功，但是没有正常搜索下载
![3](https://user-images.githubusercontent.com/95324467/202825514-4902907e-85ab-4590-aca1-a8e8dc5816e5.png)
![22](https://user-images.githubusercontent.com/95324467/202825523-ed5d66e8-0570-4f1f-b09d-f9b14c5f1ac5.png)

**Comment by jxxghp** [comment]
豆瓣的名字有问题，TMDB就没有叫黑豹2的，可以去加词条。

![image](https://user-images.githubusercontent.com/51039935/202834428-6ae8e8a5-5b23-4962-ae6b-ab46a846450f.png)
