### ISSUE TITLE
无法从 `HEVC-10bit` 中识别出 HEVC 视频编码

### ISSUE THREAD

**Issue by Xm798** [jxxghp/nas-tools#2070]
## 你使用的 NASTool 是什么版本，什么环境？

NASTool 版本: v2.4.2

环境: docker

## 识别测试

`[Sakurato] Spy x Family [17][HEVC-10bit 1080p AAC][CHS&CHT].mkv`

<img width="710" alt="image" src="https://user-images.githubusercontent.com/48074861/202849006-40c835d7-be1e-4305-a45f-e15e1f989a15.png">

HEVC 后加空格可正常识别/

`[Sakurato] Spy x Family [17][HEVC -10bit 1080p AAC][CHS&CHT].mkv`

<img width="709" alt="image" src="https://user-images.githubusercontent.com/48074861/202849030-85b6b431-a9c3-47e0-b774-2af99f01f996.png">

**Comment by Shurelol** [comment]
那就自定义识别词替换加个空格

**Comment by jxxghp** [comment]
动漫的我也改不了
