### ISSUE TITLE
bark 通知测试失败

### ISSUE THREAD

**Issue by zjjxwhh** [jxxghp/nas-tools#2072]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: docker
>

## 你遇到什么问题了？

bark 通知测试失败，且 bark 客户端未收到通知

![Snipaste_2022-11-20_01-17-18](https://user-images.githubusercontent.com/14367334/202863301-0e351873-8c36-48b6-ba25-f56984d6335f.jpg)

直接访问 `[服务器IP]/[API KEY]/title/message` 可正常推送

![Snipaste_2022-11-20_01-16-51](https://user-images.githubusercontent.com/14367334/202863306-2a66b27f-3e0b-4293-aedf-29a3f88b36fd.jpg)

bark 服务器部署在 docker 下

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

是

## 你期望的结果

正常推送

## 给出程序界面截图、后台运行日志或配置文件

![Snipaste_2022-11-20_01-21-24](https://user-images.githubusercontent.com/14367334/202863488-a5e57635-a0b1-4fe7-88c2-e86f25969a86.jpg)

**Comment by Shurelol** [comment]
http://192.168.9.50

**Comment by zjjxwhh** [comment]
> http://192.168.9.50:8181

成功了，非常感谢
