### ISSUE TITLE
目录同步与手动识别功能改进

### ISSUE THREAD

**Issue by youyifentian** [jxxghp/nas-tools#2076]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2 bdb3368b
>
> 环境: docker

## 1、目录同步
> 现状：目录同步和下载监控是互斥的，并且下载监控也只支持qb，tr等，比如我平时用的多的迅雷啥的就不行，这就导致，我虽然设置了目录同步，但是他跟下载监控有矛盾，就很受，因为我使用多个下载器，添加了多个下载目录需要同步，如果启用了就跟下载监控互斥了，如果不启用，连手动点也无法同步，要用的话还得先启用，然后在手动同步，然后在关闭，就比较难受，改进：添加目录同步之后，可以设置启用或不启用，并且增加手动同步按钮，这样，我添加了同步目录，但是不启用自动同步，这时候qb、tr等仍然可以享受下载监控来自动转移，而不支持下载监控的我可以通过网页或者微信来手动同步，这样就比较好了，甚至可以选择手动同步哪些目录就更好了。

## 2、手动识别
> 现状：凡是不能自动识别的，都会添加到手动识别里面，这个本来是很好的，但是，它里面的那个删除逻辑就有点难受了，竟然是直接删除不能识别的文件，甚至是目录，我有一次竟然直接把我的下载目录干掉了，这太危险了，改进：这里可以更改下删除逻辑，就像qb里面删除时候会有提示是否删除磁盘文件，这里也可以搞一下，因为大部分时候，我仅仅是想清除掉这条手动识别记录而已，并不是要删除文件甚至目录等，所以希望能改进下，

##最后还是要感谢下作者开发出这么好用的程序，非常感谢

**Comment by Loyoan** [comment]
我用的下载器是aria2，现在设置成下载完成后由aria2自己转移到另一个文件夹，nastool来监控这个文件夹，就避免了很多问题，迅雷应该也能实现类似的下载完成以后移动的功能。
不行的话下载完成以后手动移到监控目录也行啊

**Comment by youyifentian** [comment]
> 我用的下载器是aria2，现在设置成下载完成后由aria2自己转移到另一个文件夹，nastool来监控这个文件夹，就避免了很多问题，迅雷应该也能实现类似的下载完成以后移动的功能。 不行的话下载完成以后手动移到监控目录也行啊

群晖上面的迅雷没有这个功能，基本上只有下载功能了

**Comment by jxxghp** [comment]
它里面的那个删除逻辑就有点难受了，竟然是直接删除不能识别的文件，甚至是目录，我有一次竟然直接把我的下载目录干掉了，这太危险了，改进：这里可以更改下删除逻辑，就像qb里面删除时候会有提示是否删除磁盘文件，这里也可以搞一下，因为大部分时候，我仅仅是想清除掉这条手动识别记录而已，并不是要删除文件甚至目录等，所以希望能改进下
——删除未识别记录是不会删除文件的，删除历史记录会，同时会有提示。只有当前文件夹没有了媒体文件才会删整个文件夹，且删的是识别后的文件，大部分都有删除的需求。
