### ISSUE TITLE
Win版重复进程占用内存的问题

### ISSUE THREAD

**Issue by fayswing** [jxxghp/nas-tools#2078]
## 你使用的 NASTool 是什么版本，什么环境？

 NASTool 版本: v2.4.1和v2.4.2
 环境: windows

## 你遇到什么问题了？

Win版本的一晚上会出现很多同样的程序    撑爆内存 
从2.4.2换到2.4.1以后过了一晚上还是会出现同样的问题
暂时解决是每天早上把重复的进程全关了重新打开

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

是的

## 你期望的结果

内存重复消耗得到解决

## 给出程序界面截图、后台运行日志或配置文件

截图如下：

![photo_2022-11-20_15-39-25](https://user-images.githubusercontent.com/44943458/202889434-9fbb69d8-aee0-453f-8826-08557f393c83.jpg)

**Comment by jxxghp** [comment]
试下关掉浏览仿真看看，还不知道怎么解决

**Comment by fayswing** [comment]
> 试下关掉浏览仿真看看，还不知道怎么解决
谢谢大佬回复     我来试试看    明天再来汇报

**Comment by fayswing** [comment]
昨晚关掉了浏览器仿真之后   目前没有出现重复进程 
非常谢谢大佬    反正浏览器仿真我也用不到    也算得到解决了
再次感谢大佬出了这么棒的程序   追剧真的方便很多很多     再次致谢！

**Comment by jxxghp** [comment]
2.5.0默认去掉了非docker环境下的仿真功能。
