### ISSUE TITLE
希望大佬新增自定义ORC识别功能

### ISSUE THREAD

**Issue by qearlziper** [jxxghp/nas-tools#2079]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>2.5
> 环境: docker or windows or synology
docker
## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
因为PT站签到需要输入验证码，所以希望能有一个填入自己的orc识别api，以支持自动填入验证码后完成签到
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
PThelper :  https://github.com/xingsu1021/pthelper

**Comment by SouLXH** [comment]
有没有一种可能这玩意叫做 OCR不是ORC，支持OCR也就是调用人家的api，然后得自己去相关站点充值呗.

**Comment by qearlziper** [comment]
> 有没有一种可能这玩意叫做 OCR不是ORC，支持OCR也就是调用人家的api，然后得自己去相关站点充值呗.

哈哈，说错了。嗯，百度不是可以申请免费的api么，用来签到的话完全够用了
