### ISSUE TITLE
新增站点后站点资源中不显示

### ISSUE THREAD

**Issue by zjjxwhh** [jxxghp/nas-tools#2081]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: docker
>

## 你遇到什么问题了？

站点维护中添加 HDTIME 及 HAIDAN

![Snipaste_2022-11-20_18-49-29](https://user-images.githubusercontent.com/14367334/202898161-fec44cf2-aa98-4668-9c7c-5c8bcbcbee09.jpg)

站点资源中仅显示 HDTIME，不显示 HAIDAN

![Snipaste_2022-11-20_18-49-38](https://user-images.githubusercontent.com/14367334/202898184-09d5552b-9236-4599-b0a7-85158293be73.jpg)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

是

## 你期望的结果

站点资源中显示所有已添加的站点

（不太确定不显示的原因，是因为不支持？

**Comment by jxxghp** [comment]
海胆不支持，无法支持

**Comment by TerryZhang-EE** [comment]
> 海胆不支持，无法支持

想问一下有哪些站支持的？因为我只有海胆

**Comment by yuguansu** [comment]
请教一下，新装的nastool，用户认证中没有找到hdtime，如何配置？

**Comment by zjjxwhh** [comment]
> 请教一下，新装的nastool，用户认证中没有找到hdtime，如何配置？ 只有以下几个站点，我只有hdtime ![image](https://user-images.githubusercontent.com/7846769/236158732-b2ff28b4-5964-4e43-aeb4-4ad5eebd7077.png) ![image](https://user-images.githubusercontent.com/7846769/236158803-4a5e8ff6-ddf6-4c25-828f-fabfc34715e7.png)

nastools 不支持 hdtime 认证，去 [论坛](https://invites.fun/) 求 / 捐入 **杜比** 或者 **观众** 吧，这两个站 nastools 和 iyuu 认证都能用
