### ISSUE TITLE
服务页面增加“重启NAStool”选项

### ISSUE THREAD

**Issue by XcheneyX** [jxxghp/nas-tools#2083]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: synology

## 你想要新增或者改进什么功能？

> 基础设置里部分设置修改后需要重启生效，群晖套件重启操作比较麻烦，希望可以新增一个快捷重启

## 这个功能有什么可以参考的资料吗？

> 无

**Comment by JKnuts** [comment]
右上角的用户名都没点过吗？
![image](https://user-images.githubusercontent.com/91355283/202907552-dfebfc0e-6eee-4326-8a88-4aa6b77f4609.png)

**Comment by XcheneyX** [comment]
> 
额。。我的这里没有重启按钮。。。可能是因为我修改了默认admin用户名······
