### ISSUE TITLE
目录同步后视频文件被破坏，无法播放

### ISSUE THREAD

**Issue by albicoccca** [jxxghp/nas-tools#2087]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.4.2
>
> 环境: docker
>

## 你遇到什么问题了？

> 系统为omv，通过docker安装nas-tools，qbittorrent，jellyfin。
在nas-tools提交订阅，qbittorrent下载，通过nas-tools目录同步，将下载文件“移动”至媒体库，但是jellyfin无法播放该视频，提示“该客户端与媒体不兼容，服务器未发送兼容的媒体格式。”
将jellyfin报错的视频提取到windows上使用potplayer播放，也无法解码。重新在windows上下载同一资源后，使用potplayer可以正常播放，对比nas-tools“移动”后的媒体文件md5，发现文件与windows上下载的不同。
重新回到nas实验，手动用qbittorrent下载该资源后验证md5与windows一致，且可以播放，使用nas-tools手动整理移动后，md5与windows一致也可以播放。
所以推测应该是在使用目录同步“移动”后视频文件被破坏，原因不明。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 网上未找到相关讨论

## 你期望的结果

> 找到原因，解决问题

## 给出程序界面截图、后台运行日志或配置文件

> 过程中并无任何错误日志

**Comment by Shurelol** [comment]
Qb开启未完成加！qb后缀
