### ISSUE TITLE
新功能请求，一键清除硬链接只有1的视频文件

### ISSUE THREAD

**Issue by kalvinses** [jxxghp/nas-tools#209]
每次在tr删除的种子还需要再去硬链接再删除一次太麻烦了。群里的命令能简化成一个功能按键集成到NAStool里面吗？每次释放空间有点麻烦，一次性在tr里面删的多了没有及时去硬链接里面删除还会忘记都删除了哪些。

**【cd到某个目录后，下面的命令可以把硬连接数只有1的视频文件删除（根据自己需要增加修改或删除后缀）：

find . -mindepth 1 \( -iname "*.mkv" -o -iname "*.mp4" -o -iname "*.iso" -o -iname "*.ts" -o -iname "*.mpg" \) | while read file; do if [[ $(stat -c %h "$file") -eq 1 ]]; then rm -v "$file"; fi; done

删完视频后下面的命令可以把下面没有大于50000KB文件的文件夹（可能有其他小文件）删除：

find . -mindepth 1 -type d | while read path; do if [[ -d "$path" && -z $(find "$path" -type f -size '+50000k') ]]; then rm -rv "$path";  fi; done】**

**Comment by jxxghp** [comment]
这么危险的功能
