### ISSUE TITLE
【bug】v2.5 some bug…

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#2093]
<img width="848" alt="image" src="https://user-images.githubusercontent.com/54088512/203027624-f68704e1-de2e-44ec-a27b-9db67847d27c.png">

这个后台的日志是什么错误吗。还是调试日志

**Comment by thsrite** [comment]
点击下载器测试链接会打印下图日志
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/54088512/203028168-17eb0f88-2d28-415e-856b-ff735728713a.png">

**Comment by thsrite** [comment]
时不时会打印日志
could not convert string to float: '100%'
invalid literal for int() with base 10: 'Transmission/3.00'
<img width="853" alt="image" src="https://user-images.githubusercontent.com/54088512/203028993-b49f8fb3-186c-4d18-8687-5c524c0e6c64.png">

**Comment by thsrite** [comment]
点所有硬连接或者查看硬连接就转圈，没有日志打印
<img width="806" alt="image" src="https://user-images.githubusercontent.com/54088512/203029378-e90d6d17-c8d0-4f0e-a117-4ae9718b328d.png">

**Comment by thsrite** [comment]
rss没日志打印了吗。
<img width="864" alt="image" src="https://user-images.githubusercontent.com/54088512/203030292-2c8c2a7c-9a95-43f1-83f6-7403b24836db.png">

**Comment by thsrite** [comment]
![image](https://user-images.githubusercontent.com/54088512/203032649-bee9300e-9c55-4da4-834f-24dd9472c7f0.png)

所有维护的站点的rss在浏览器中能打开且正常返回数据。
更新2.5版本之前正常使用rss，更新完就gg了

**Comment by thsrite** [comment]
降级2.4.2版本，rss正常

**Comment by KevinXC5** [comment]
![image](https://user-images.githubusercontent.com/27657061/203048269-49f2025f-5706-406d-9218-d0c43d369732.png)
更新到2.5.0后无法订阅了

**Comment by SchrodingerBarbatos** [comment]
同样没法用rss订阅，站点资源是正常的

**Comment by thsrite** [comment]
2.5降级2.4.2后，所有站点的rss解析详情和过滤规则都无了。之前都勾选了
![4271236C-98F7-4755-A591-437915C9C489](https://user-images.githubusercontent.com/54088512/203052957-283447fe-2019-4536-bbad-58dd8d2986ea.png)
![2D7B582B-6467-4096-A36C-0100F22BA6BE](https://user-images.githubusercontent.com/54088512/203052975-f9cb8dfd-8fb2-4640-8826-580a43d34a72.jpeg)

**Comment by thsrite** [comment]
上图中的站点设置，能否增加批量设置。
几十个站点排着修改好麻烦。。

**Comment by jxxghp** [comment]
新版本会升级配置格式，回退丢失配置很正常啊，你版本回退了配置也要同步回退。

**Comment by jxxghp** [comment]
> <img alt="image" width="848" src="https://user-images.githubusercontent.com/54088512/203027624-f68704e1-de2e-44ec-a27b-9db67847d27c.png">
> 
> 这个后台的日志是什么错误吗。还是调试日志

没有影响不用管

**Comment by KevinXC5** [comment]
> 新版本会升级配置格式，回退丢失配置很正常啊，你版本回退了配置也要同步回退。

大佬，看看上面那个无法订阅的问题呢，是改了使用方式吗

**Comment by jxxghp** [comment]
> > 新版本会升级配置格式，回退丢失配置很正常啊，你版本回退了配置也要同步回退。
> 
> 大佬，看看上面那个无法订阅的问题呢，是改了使用方式吗

这个提示理解不了吗？还是你实际设置了订阅站点但判断有误？

**Comment by KevinXC5** [comment]
> > > 新版本会升级配置格式，回退丢失配置很正常啊，你版本回退了配置也要同步回退。
> > 
> > 
> > 大佬，看看上面那个无法订阅的问题呢，是改了使用方式吗
> 
> 这个提示理解不了吗？还是你实际设置了订阅站点但判断有误？

我没有设置任何站点，但是2.4.2版本，是可以直接订阅的呢

**Comment by KevinXC5** [comment]
> 

难道2.5.0改成了必须要自己添加站点才能使用订阅功能？2.4.2我docker启动了过后没有做任何操作是可以直接再豆瓣热门资源里订阅并且搜索种子的，升级了就不行了

**Comment by jxxghp** [comment]
> > > > 新版本会升级配置格式，回退丢失配置很正常啊，你版本回退了配置也要同步回退。
> > > 
> > > 
> > > 大佬，看看上面那个无法订阅的问题呢，是改了使用方式吗
> > 
> > 
> > 这个提示理解不了吗？还是你实际设置了订阅站点但判断有误？
> 
> 我没有设置任何站点，但是2.4.2版本，是可以直接订阅的呢

是没有PT站吗？订阅都是使用RSS的，如果没有意义不大。

**Comment by KevinXC5** [comment]
> 
没有PT站，但是2.4.2是可以订阅的，所以我就问一下是不是2.5.0改了必须自己添加站点才能使用订阅功能，2.4.2应该是内置了一个站点的吧

**Comment by KevinXC5** [comment]
> > > > > 新版本会升级配置格式，回退丢失配置很正常啊，你版本回退了配置也要同步回退。
> > > > 
> > > > 
> > > > 大佬，看看上面那个无法订阅的问题呢，是改了使用方式吗
> > > 
> > > 
> > > 这个提示理解不了吗？还是你实际设置了订阅站点但判断有误？
> > 
> > 
> > 我没有设置任何站点，但是2.4.2版本，是可以直接订阅的呢
> 
> 是没有PT站吗？订阅都是使用RSS的，如果没有意义不大。

没有PT站，但是2.4.2是可以订阅的，所以我就问一下是不是2.5.0改了必须自己添加站点才能使用订阅功能，2.4.2应该是内置了一个站点的吧

**Comment by Shurelol** [comment]
如果你想表达的是2.4.2可以不用配置站点，2
5要配置站点并启动订阅功能。

那么是的

你使用的公开站点绝大部份都提供rss功能，建议配置到站点信息

**Comment by KevinXC5** [comment]
> 如果你想表达的是2.4.2可以不用配置站点，2.5要配置站点并启动订阅功能。
> 
> 那么是的
> 
> 你使用的公开站点绝大部份都提供rss功能，建议配置到站点信息

好的，明白了，谢谢

**Comment by thsrite** [comment]
> > > > > 新版本会升级配置格式，回退丢失配置很正常啊，你版本回退了配置也要同步回退。
> > > > 
> > > > 
> > > > 大佬，看看上面那个无法订阅的问题呢，是改了使用方式吗
> > > 
> > > 
> > > 这个提示理解不了吗？还是你实际设置了订阅站点但判断有误？
> > 
> > 
> > 我没有设置任何站点，但是2.4.2版本，是可以直接订阅的呢
> 
> 是没有PT站吗？订阅都是使用RSS的，如果没有意义不大。

我有pt站，2.4.2正常使用rss，升级2.5不好使了。降级2.4.2又可以了

**Comment by aiwu12** [comment]
同理，我也一样，rss有问题

**Comment by SchrodingerBarbatos** [comment]
> > > > > > 新版本会升级配置格式，回退丢失配置很正常啊，你版本回退了配置也要同步回退。
> > > > > 
> > > > > 
> > > > > 大佬，看看上面那个无法订阅的问题呢，是改了使用方式吗
> > > > 
> > > > 
> > > > 这个提示理解不了吗？还是你实际设置了订阅站点但判断有误？
> > > 
> > > 
> > > 我没有设置任何站点，但是2.4.2版本，是可以直接订阅的呢
> > 
> > 
> > 是没有PT站吗？订阅都是使用RSS的，如果没有意义不大。
> 
> 我有pt站，2.4.2正常使用rss，升级2.5不好使了。降级2.4.2又可以了

我也是，pt站点订阅也不行
![image](https://user-images.githubusercontent.com/78670748/203063449-4a2a037f-2c0b-4995-8972-41058394d38c.png)
![image](https://user-images.githubusercontent.com/78670748/203063515-74fb678a-67d9-4808-8828-531613cd89d0.png)
![image](https://user-images.githubusercontent.com/78670748/203063589-70b82309-5d4f-485a-ac9f-cafaeea17898.png)

**Comment by Shurelol** [comment]
建议打开编辑订阅，重新保存。另外麻烦发个订阅界面的截图

**Comment by KevinXC5** [comment]
话说，好奇的问一下，出于什么考虑把2.4.2内置的订阅功能给阉割了呢，内置的开箱即用不是很好吗

**Comment by SchrodingerBarbatos** [comment]
> 建议打开编辑订阅，重新保存。另外麻烦发个订阅界面的截图

重新编辑保存了订阅还是不行
下面是订阅界面的图
![image](https://user-images.githubusercontent.com/78670748/203064994-e1ef2ea1-63d5-4877-8025-245e9b645710.png)

**Comment by Shurelol** [comment]
如果是直接在网页内升级的，建议重新拉下最新的2.5.0的镜像试试

**Comment by Shurelol** [comment]
等下修复

**Comment by SchrodingerBarbatos** [comment]
> 等下修复

十分感谢
