### ISSUE TITLE
手动远程搜索打开链接会话丢失

### ISSUE THREAD

**Issue by AinzLimuru** [jxxghp/nas-tools#2095]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.5.0
>
> 环境: docker并使用Nginx进行代理，https在Nginx配置。
>

## 你遇到什么问题了？

> 使用tg bot的手动搜索功能，搜索后点击链接打开搜索界面，但是该链接无法正常跳转到搜索界面。
现象是在菜单栏右侧的子页面中出现了登陆界面，整个网页反复的重新加载，每一次的加载都会产生一个新的session。正常刷新主页是不会发生这样的的现象。
在打开控制台后，发现当前的网页请求会返回的结果包含setcookie的操作，在已登陆的情况下返回了setcookie导致登陆过期。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 正确打开搜索界面

## 给出程序界面截图、后台运行日志或配置文件

> 这个是使用tgbot提供的链接打开网页的截图。
似乎是由于Cookie中的HttpOnly的标签导致脚本无法使用cookie，仅个人猜测。

> ![image](https://user-images.githubusercontent.com/59441476/203038059-ab9d2761-9bb8-4a22-873f-02b2c7a445c5.png)

**Comment by jxxghp** [comment]
你是代理开了缓存？ 把缓存关掉。

**Comment by AinzLimuru** [comment]
应该是找到原因了
https://github.com/jxxghp/nas-tools/blob/babbb94c38bbfa25eeda19855c3c357bb351cb73/web/main.py#L128
这里的这个if块在获取了next参数复制到GoPage之后就没有再做进一步的处理了，而是直接进行跳转到导航页或者登录页。可能是这里的原因。

**Comment by jxxghp** [comment]
我测试了是正常的，用的是群晖的代理。
GoPage在跳转的内部函数会使用到。
你说的问题之前遇到过，如果是用nginxproxymanager关掉缓存开关即可，如果是自建的nginx就不清楚了。

**Comment by Shurelol** [comment]
反代不要开缓存

**Comment by AinzLimuru** [comment]
为了进一步的排除Nginx的原因，我访问了nas-tools自己的端口，而不是使用nginx代理的80端口进行访问。
目前流量不经过nginx，但是依然出现了这个问题。

**Comment by AinzLimuru** [comment]
尝试删除容器并拉取最新镜像后重装，但问题依然没有解决。

**Comment by AinzLimuru** [comment]
找原因了，不是会话之类的问题。而是返回的链接有问题，正常的链接应该是https://domain/?next=search但是我得到的链接是https://domain/?next=https://domain?next=search
我手动删除了中间的部分得到正常的链接之后就可以使用了，应该是生成链接的代码有问题。

**Comment by AinzLimuru** [comment]
代码应该是这里出错了

https://github.com/jxxghp/nas-tools/blob/be9794abe297e51be5a3dbadd8655a2c6fc29ebe/app/message/message.py#L145
上面这个代码调用了下面这个代码，两个代码都执行了在url前添加域名动作。
https://github.com/jxxghp/nas-tools/blob/be9794abe297e51be5a3dbadd8655a2c6fc29ebe/app/message/message.py#L114

导致最后的链接上一条回复中出现的重复的问题，进而导致了无限重新加载。希望修复。
