### ISSUE TITLE
rss订阅无法使用

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [jxxghp/nas-tools#2096]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.5.0 8ff46ce5
>
> 环境: docker
>

## 你遇到什么问题了？

> rss订阅不获取rss信息，但是如果去站点资源是能看到rss的资源的

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已经浏览

## 你期望的结果

> 恢复正常

## 给出程序界面截图、后台运行日志或配置文件

> 
![image](https://user-images.githubusercontent.com/78670748/203043211-aa2bf863-60d5-47bd-b4fc-f10e019ac0a9.png)

**Comment by jxxghp** [comment]
没有问题
