### ISSUE TITLE
内建索引器中勾选的站点不在订阅管理中编辑订阅时显示

### ISSUE THREAD

**Issue by zbodo** [jxxghp/nas-tools#2097]
> NASTool 版本: v2.5.0
> 环境: Windows

## 你遇到什么问题了？

内建索引器中勾选的站点不在订阅管理中显示

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/39948021/203048615-4215cb38-d073-4eb7-8349-cec49a0bba67.png)
![image](https://user-images.githubusercontent.com/39948021/203049136-de76d7eb-99eb-4df0-8570-452462bdc4e2.png)

**Comment by krau** [comment]
我有同样的问题，这是2.5.0版本的bug

**Comment by jxxghp** [comment]
修复了
