### ISSUE TITLE
Web启动时证书文件加载报错

### ISSUE THREAD

**Issue by virualv** [jxxghp/nas-tools#2104]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.5.0
>
> 环境: Synology DSM 6.2.4 Docker
>

## 你遇到什么问题了？

> ssl证书无法加载，导致web服务无法启动，v2.5.0之前版本一直正常
> 
> 证书及秘钥文件是通过挂载文件形式挂载进容器里的

## 你期望的结果

> 正常加载证书文件，并启动web服务

## 给出程序界面截图、后台运行日志或配置文件

- 配置文件
![image](https://user-images.githubusercontent.com/42433288/203078799-93271f74-571a-4fba-a448-b9431bdbf406.png)

![image](https://user-images.githubusercontent.com/42433288/203079081-13d8e6be-b124-4d88-8c42-9bc94dc310a3.png)

- log
![image](https://user-images.githubusercontent.com/42433288/203078660-3f3c5262-b9cc-46c0-986a-3b1994578f23.png)

**Comment by Shurelol** [comment]
建议用反代，反代不要开缓存

**Comment by virualv** [comment]
这个倒是可以作为折中解决方案。

**Comment by Shurelol** [comment]
反代能统一对外端口，统一管理，自动更新证书。尽量还是用反代吧

推荐https://github.com/NginxProxyManager/nginx-proxy-manager
