### ISSUE TITLE
更新至2.5.0之后的证书错误以及解决方法

### ISSUE THREAD

**Issue by ReddotCleaner** [jxxghp/nas-tools#2105]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.5.0
>
> 环境: docker or windows or Synology
> unraid docker

## 你遇到什么问题了？

> 更新至2.5.0后，加入之前有在webui设置有ssl证书，会导致证书错误，无法启动，无法访问webui
![image](https://user-images.githubusercontent.com/34325738/203079555-477f9464-88ba-4df1-837a-da6d31c49804.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 在tg群与群友讨论后得出结论，可能与2.5.0的更新有关，在配置文件种注释掉关于ssl证书的两行后，程序正常启动

## 你期望的结果

> 如果之前有配置ssl证书的朋友在更新到2.5.0之后出现无法访问的情况可编辑```configyaml```文件，删除或注释掉证书相关内容。即可正常访问

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
#2104
