### ISSUE TITLE
字幕下载转移问题

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#2111]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: vx.x.x
>
> 环境: docker 
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
PT网站提供了字幕链接，nastool下载了字幕，但是并没有转移到相关电影文件夹里呀

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
没法解决

## 你期望的结果
可以把字幕文件转移到和视频相同文件夹里

## 给出程序界面截图、后台运行日志或配置文件
![AFBBF3DC-A1CA-42A3-BFF6-5DFAC9DED4AF](https://user-images.githubusercontent.com/39802246/203196004-23c743da-3c92-45e1-b24b-207430720016.jpeg)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
日志中有显示转移字幕，麻烦发下完整的日志信息。在目的路径中查看是否存在

**Comment by Tartarus2014** [comment]
![1F107DA5-C62E-45DE-93B3-4E9027A160A4](https://user-images.githubusercontent.com/39802246/203197664-03be8817-f519-4e57-bb85-3c8b8e241019.jpeg)

完整日志图，在目录中不存在这个目录文件

**Comment by jxxghp** [comment]
62591053725215cf1c0dae4821f98901fb6929e5
