### ISSUE TITLE
自定义识别词bug

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#2113]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.5.0
>
> 环境: docker
>

种子名称：Bleach Sennen Kessen Hen S01E01 2022 1080p KKTV WEB-DL x264 AAC-AnimeS@ADWeb

死神 千年血战篇 tmdb显示是第二季
![image](https://user-images.githubusercontent.com/54088512/203200432-0806c5f8-55cb-4a40-8f6e-c2d63d85ac91.png)
但是上述种子名显示第一季，所以设置了自定义识别词
![image](https://user-images.githubusercontent.com/54088512/203200528-601f0a88-a1ba-4604-915f-a3379930b1cc.png)
测试名称
![image](https://user-images.githubusercontent.com/54088512/203200567-d5ba9250-0799-4b73-93e7-3f5017745436.png)

然后订阅下载，没问题。
![image](https://user-images.githubusercontent.com/54088512/203200633-4ff4b0ff-b7c6-4cf5-9fbb-5e61baf6b2a6.png)

但是下载完自动识别的时候又变成第一季了，而且同步记录重复推送了两遍
![image](https://user-images.githubusercontent.com/54088512/203200700-8cb4bfbe-0ade-4e31-a171-3a85c1741108.png)

这里设置了自定义识别词，是不是同步的时候也适用下自定义识别词。
硬链接的视频文件也应按照自定义识别词后的生成，
此处应该是S02，而不是S01了

**Comment by thsrite** [comment]
> 搜索订阅，使用资源标题进行识别 即Bleach Sennen Kessen Hen S01E07 2022 2160p B-Global WEB-DL x264 AAC-AnimeS@ADWeb
> 
> 转移文件，使用文件名进行识别 即Bleach.Sennen.Kessen.Hen.S01E07.2022.2160p.B-Global.WEB-DL.x264.AAC-ADWeb.mkv
> 
> 两者往往并不相同 （正则下，词间用 . 可以兼容词间空格情形）

好的，我试试

**Comment by thsrite** [comment]
![image](https://user-images.githubusercontent.com/54088512/203204611-2a27bd55-3095-408e-93e3-01865d83363f.png)
手动整理识别了第一季，识别历史这的对应关系貌似有问题

**Comment by thsrite** [comment]
> 搜索订阅，使用资源标题进行识别 即Bleach Sennen Kessen Hen S01E07 2022 2160p B-Global WEB-DL x264 AAC-AnimeS@ADWeb
> 
> 转移文件，使用文件名进行识别 即Bleach.Sennen.Kessen.Hen.S01E07.2022.2160p.B-Global.WEB-DL.x264.AAC-ADWeb.mkv
> 
> 两者往往并不相同 （正则下，词间用 . 可以兼容词间空格情形）

大佬，这应该如何设置，不改种子视频名的前提下，如何在咱们系统里进行兼容--

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/203211924-12d5ef23-a121-428e-8f00-5df7908b6d98.png)
![image](https://user-images.githubusercontent.com/16237201/203211961-fbf65763-0ffb-4644-b568-366a47b032ee.png)
添加用 . 分隔的就行了

**Comment by thsrite** [comment]
> Bleach Sennen Kessen Hen S01E07 2022 2160p B-Global WEB-DL x264 AAC-AnimeS@ADWeb

感谢大佬
