### ISSUE TITLE
手动整理识别后，识别历史硬链接对应关系错误

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#2115]
v2.5版本
docker

![image](https://user-images.githubusercontent.com/54088512/203204611-2a27bd55-3095-408e-93e3-01865d83363f.png)
手动整理识别了第一季，识别历史这的对应关系貌似有问题

_Originally posted by @thsrite in https://github.com/jxxghp/nas-tools/issues/2113#issuecomment-1322936590_

**Comment by jxxghp** [comment]
没看明白，是啥问题，是指记录有重复吗？

**Comment by thsrite** [comment]
原视频是第241集，下面硬链接文件是第2集
原视频是第320集，下面硬链接文件是第3集
原视频是第259集，下面硬链接文件是第2集
原视频是第130集，下面硬链接文件是第1集

**Comment by jxxghp** [comment]
看起来是识别问题，你用文件名在识别测试里测一下看看

**Comment by thsrite** [comment]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/54088512/203301076-27da8e74-94b7-48bc-bf78-13c6810b79e6.png">

这个文件命名确实不规范，应该是这个问题造成的，其他规范命名的话显示是正常的
