### ISSUE TITLE
希望优化文件下载和媒体库的路径

### ISSUE THREAD

**Issue by zbodo** [jxxghp/nas-tools#2117]
## 你使用的 NASTool 是什么版本，什么环境？

NASTool 版本: v2.5.0
环境: Windows

## 你想要新增或者改进什么功能？

希望媒体库的文件存放在设定的文件夹而不要自动创建子文件夹  
举个例子，
现在的情况下把路径设为`**/Videos/动画剧集/`时，
下载的文件会存放在`**/Videos/动画剧集/动漫/`。
希望能改为直接存放在`**/Videos/动画剧集/`里

**Comment by jxxghp** [comment]
有没有一种可能，就是已经有的功能，只是你不会设置呢
