### ISSUE TITLE
关于订阅海贼王第21季时ui显示错误的问题

### ISSUE THREAD

**Issue by samir2015dzh** [jxxghp/nas-tools#2119]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.5.0
>
> 环境: docker 
>

## 你遇到什么问题了？

> 订阅海贼王的时候因为海贼王第21季是从800多集开始起步的，我本地资源已经到1040集了，订阅之后选择从1041集开始订阅，然而那个订阅显示的进度条已经超出屏幕了

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 我看了一下，是没有这个issue反馈的

## 你期望的结果

> 描述以下你期望的结果希望可以跟其他日漫一样正常的显示进度条

**Comment by thsrite** [comment]
老哥，订阅21季能识别下载吗，是加了自定义识别词吗

**Comment by jxxghp** [comment]
编辑下订阅，截图看看，总集数填了吗，没填就会用TMDB的
