### ISSUE TITLE
希望适配rarbg等国外bt网站搜索

### ISSUE THREAD

**Issue by spacey0409** [jxxghp/nas-tools#212]
tmdb提供了一个根据电影和电视搜索的api接口，该接口可以查询出电影电视的英文名称，rarbg等网站就支持搜索了

https://api.themoviedb.org/3/search/movie?api_key=${api_key}&query=${key_word}
https://api.themoviedb.org/3/search/tv?api_key=${api_key}&query=${key_word}

[https://developers.themoviedb.org/3/getting-started/search-and-query-for-details](url)

_{
page: 1,
results: [
{
adult: false,
backdrop_path: "/usw8PMcbWqAtmABo2jO7KRRSrqi.jpg",
genre_ids: [
18,
878,
53
],
id: 6479,
original_language: "en",
original_title: "I Am Legend",
overview: "Robert Neville is a scientist who was unable to stop the spread of the terrible virus that was incurable and man-made. Immune, Neville is now the last human survivor in what is left of New York City and perhaps the world. For three years, Neville has faithfully sent out daily radio messages, desperate to find any other survivors who might be out there. But he is not alone.",
popularity: 91.37,
poster_path: "/iPDkaSdKk2jRLTM65UOEoKtsIZ8.jpg",
release_date: "2007-12-12",
title: "I Am Legend",
video: false,
vote_average: 7.2,
vote_count: 13305
}
],
total_pages: 1,
total_results: 1
}_

**Comment by jxxghp** [comment]
...
