### ISSUE TITLE
电视剧订阅集数显示错误

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#2120]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.5.0
>
> 环境: docker 

死神千年血战篇，已经订阅下载了7集，但是订阅页面显示0集，订阅刷新后看日志显示缺少的集数是8及以后，但是页面还是显示0集

![image](https://user-images.githubusercontent.com/54088512/203253715-85f31609-af0b-4e02-aac7-1dac15e7158f.png)

![image](https://user-images.githubusercontent.com/54088512/203253760-5b4dec06-6804-48b1-9ba7-4a5989768093.png)

**Comment by jxxghp** [comment]
感谢，确实有这个问题，已经修复
![image](https://user-images.githubusercontent.com/51039935/203271642-d40d1fa4-f990-453f-9b53-04b025df9ca2.png)

**Comment by thsrite** [comment]
> 感谢，确实有这个问题，已经修复
> ![image](https://user-images.githubusercontent.com/51039935/203271642-d40d1fa4-f990-453f-9b53-04b025df9ca2.png)

感谢
