### ISSUE TITLE
自定义识别词刚进页面可否默认不展开

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#2122]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.5.0
>
> 环境: docker

![image](https://user-images.githubusercontent.com/54088512/203268951-ca58ee4c-1201-4ef1-952b-96260e83543c.png)

可不可以默认不展开列表，只展示词组。

如果新建词组过多的话，进入页面全部展开的话感觉会很乱。

**Comment by Shurelol** [comment]
识别词组超过8个，进入页面，默认全部折叠

**Comment by thsrite** [comment]
> 

已私信大佬

**Comment by thsrite** [comment]
> 识别词组超过8个，进入页面，默认全部折叠

收到
