### ISSUE TITLE
tg无法点击选择下载

### ISSUE THREAD

**Issue by whcvincent** [jxxghp/nas-tools#2124]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.5.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 设置中关闭了”远程搜索自动择优下载“选项，telegram搜索电源，反馈回来能找到资源，让我选择一个资源下载，但是没有对应的选择列表，消息也不可点击。

![IMG_5370](https://user-images.githubusercontent.com/57385200/203291869-ee338893-9230-4d41-91b2-f3b8b4629795.PNG)

**Comment by Shurelol** [comment]
有没有可能，没有设置外网地址

建议先把设置里❓看一遍，就没那么多问题了
