### ISSUE TITLE
添加下载失败 无法打开链接

### ISSUE THREAD

**Issue by Nemoljy** [jxxghp/nas-tools#2128]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.5.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 【资源搜索】里下载种子和【订阅】里下载种子都报错：【添加下载失败 无法打开链接：XXXX】

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的，未找到类似问题

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

例如：灵能百分百 (2016) S03 E07 添加下载失败 无法打开链接：login.php?returnto=download.php%3Fid%3D325389！
![image](https://user-images.githubusercontent.com/32947114/203341527-b415dad8-bbca-4540-b6a0-96594d78fd27.png)
站点是北洋园（tjupt.org），联通测试正常。
![image](https://user-images.githubusercontent.com/32947114/203341632-10d68e7f-2cee-4e6b-976d-fca1b486e2ff.png)

此前已正常使用订阅和其他功能多个月。

**Comment by YoshiPark** [comment]
有时候订阅RSS命中之后也会显示无法打开链接，而且也无法通知iyuu和微信，但是测试iyuu和微信是正常的，手动在订阅中刷新也能命中这个资源
![微信图片_20221122230615](https://user-images.githubusercontent.com/20967749/203348772-b8ae3f16-7fef-428b-a641-f2294f96e18c.png)

**Comment by amtoaer** [comment]
我这边 tjupt 也有相同问题

**Comment by Nemoljy** [comment]
索引器改回Jackett可正常使用，目测是内建索引器 解析tjupt的链接 或 获取链接 有bug。暂时先用Jackett了。

**Comment by jxxghp** [comment]
应该是某次自动重定向改动引起的，但这两个站我都没账号测试不了。如有账号的可以帮忙调试下。

**Comment by amtoaer** [comment]
@Nemoljy @jxxghp 刚刚一层层排查了一下，发现这个报错是由`Sites.get_sites` 获取站点信息失败引起的。
>  TJUPT 常用地址为 [https://tjupt.org/](#)
> 但通过索引器获取到的下载链接是 [https://www.tjupt.org/download.php?id=xxx](#)。 

错误出现的详细流程是：
1. 开始下载种子，分析下载链接获取到下载链接的域名：`www.tjupt.org`
2. 从`Sites._siteByUrls`字典中获取 key 为 `www.tjupt.org` 的站点信息
3. 站点信息部分配置的地址是 [https://tjupt.org/](#)，即`Sites._siteByUrls`中 TJUPT 对应的 key 是 `tjupt.org`
4. 字典中 key 为`www.tjupt.org`的站点不存在，获取站点信息失败
5. 没有获取到站点信息，下载时 cookie 为 None ，跳转至 login.php，下载失败

因此，该问题最简单的解决办法，就是把站点维护页面中 TJUPT 条目的站点地址由 [https://tjupt.org/](#) 改为 [https://www.tjupt.org/](#)。
项目层面，可以考虑使用不同站点的**一级域名**区分站点来规避此类问题。（毕竟应该没有 `a.example.com` 和 `b.example.com` 是两个 Torrent 站点的情况吧 🤣 ）

**Comment by maxin-cn** [comment]
> @Nemoljy @jxxghp 刚刚一层层排查了一下，发现这个报错是由`Sites.get_sites` 获取站点信息失败引起的。
> 
> > TJUPT 常用地址为 [https://tjupt.org/](#)
> > 但通过索引器获取到的下载链接是 [https://www.tjupt.org/download.php?id=xxx](#)。
> 
> 错误出现的详细流程是：
> 
> 1. 开始下载种子，分析下载链接获取到下载链接的域名：`www.tjupt.org`
> 2. 从`Sites._siteByUrls`字典中获取 key 为 `www.tjupt.org` 的站点信息
> 3. 站点信息部分配置的地址是 [https://tjupt.org/](#)，即`Sites._siteByUrls`中 TJUPT 对应的 key 是 `tjupt.org`
> 4. 字典中 key 为`www.tjupt.org`的站点不存在，获取站点信息失败
> 5. 没有获取到站点信息，下载时 cookie 为 None ，跳转至 login.php，下载失败
> 
> 因此，该问题最简单的解决办法，就是把站点维护页面中 TJUPT 条目的站点地址由 [https://tjupt.org/](#) 改为 [https://www.tjupt.org/](#)。 项目层面，可以考虑使用不同站点的**一级域名**区分站点来规避此类问题。（毕竟应该没有 `a.example.com` 和 `b.example.com` 是两个 Torrent 站点的情况吧 🤣 ）

hi，您好，我也是使用内建的索引器无法下载。我单独试过将种子下载下载放到qb中尝试，是可以下载的。nastools里面站点测试也是可以连通的，我按照上述帖子的修改，也无法无法成功下载。请问下应该怎么解决呢？另外数据统计是空的，我不知道是否是这个原因？
![image](https://user-images.githubusercontent.com/38418898/209434137-66096af3-301b-453a-bb9a-25522921c751.png)
![image](https://user-images.githubusercontent.com/38418898/209434150-2771341a-aa5d-4b9c-b07d-3f75bf13bc37.png)
