### ISSUE TITLE
希望可以增加对动漫BT站漫猫的支持

### ISSUE THREAD

**Issue by kaeserlin** [jxxghp/nas-tools#2129]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2
>
> 环境: Linux Python

## 你想要新增或者改进什么功能？

> 希望可以增加对动漫BT站 漫猫站点的支持，地址是：comicat.org

## 这个功能有什么可以参考的资料吗？

> 没有

**Comment by jxxghp** [comment]
这个下载地址套的太深，解析不了。

**Comment by shanyan-wcx** [comment]
漫猫就是个Miobt的镜像站吧
