### ISSUE TITLE
希望添加可以一键导入PTPP的cookie.json

### ISSUE THREAD

**Issue by Adsryen** [jxxghp/nas-tools#2130]
## 你使用的 NASTool 是什么版本，什么环境？
2.3.0   群晖docker
> NASTool 版本: vx.x.x
>
> 环境: docker or windows or synology

## 你想要新增或者改进什么功能？
希望添加可以一键导入PTPP的cookie.json
> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？
就是解析json文件吧，避免一个一个站点的添加，太麻烦了，，，，很多收割机基本上手上有60+个站点
要是可以一键导入cookie  就好了

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by SouLXH** [comment]
用插件可以直接把站点的cookie直接传到nastool里面

**Comment by Adsryen** [comment]
> 用插件可以直接把站点的cookie直接传到nastool里面

插件支持的站点太少了  而且 我一次性开60+的网页 直接浏览器拉爆哈哈哈哈   缓一哈还没的事   结果能导入的只有一小部分

**Comment by SouLXH** [comment]
> > 用插件可以直接把站点的cookie直接传到nastool里面
> 
> 插件支持的站点太少了 而且 我一次性开60+的网页 直接浏览器拉爆哈哈哈哈 缓一哈还没的事 结果能导入的只有一小部分

我说的是油猴的那个脚本，理论上支持所有站点，只是部分站点没加入到脚本的检测名单里面而已，你去控制面板手动添加进去就行了，以后每次打开pt站都会更新这个站点的cookie到nastools上。完全自动化，如果手动导入ptpp上的还更麻烦了。

 这只是我的看法，开发人员怎么认为就不知道了

**Comment by Adsryen** [comment]
> > > 用插件可以直接把站点的cookie直接传到nastool里面
> > 
> > 插件支持的站点太少了 而且 我一次性开60+的网页 直接浏览器拉爆哈哈哈哈 缓一哈还没的事 结果能导入的只有一小部分
> 
> 我说的是油猴的那个脚本，理论上支持所有站点，只是部分站点没加入到脚本的检测名单里面而已，你去控制面板手动添加进去就行了，以后每次打开pt站都会更新这个站点的cookie到nastools上。完全自动化，如果手动导入ptpp上的还更麻烦了。
> 
>  这只是我的看法，开发人员怎么认为就不知道了

诶  对噶  居然没想到自己改js  瓜了    nastool能加nexusphp以外的架构吗

**Comment by SouLXH** [comment]
> > > > 用插件可以直接把站点的cookie直接传到nastool里面
> > > 
> > > 
> > > 插件支持的站点太少了 而且 我一次性开60+的网页 直接浏览器拉爆哈哈哈哈 缓一哈还没的事 结果能导入的只有一小部分
> > 
> > 
> > 我说的是油猴的那个脚本，理论上支持所有站点，只是部分站点没加入到脚本的检测名单里面而已，你去控制面板手动添加进去就行了，以后每次打开pt站都会更新这个站点的cookie到nastools上。完全自动化，如果手动导入ptpp上的还更麻烦了。
> > 这只是我的看法，开发人员怎么认为就不知道了
> 
> 诶 对噶 居然没想到自己改js 瓜了 nastool能加nexusphp以外的架构吗

我不确定，我这个月才玩pt，没几个站，都是np的，所有没测试过，试试呗

**Comment by Adsryen** [comment]
> > > > > 用插件可以直接把站点的cookie直接传到nastool里面
> > > > 
> > > > 
> > > > 插件支持的站点太少了 而且 我一次性开60+的网页 直接浏览器拉爆哈哈哈哈 缓一哈还没的事 结果能导入的只有一小部分
> > > 
> > > 
> > > 我说的是油猴的那个脚本，理论上支持所有站点，只是部分站点没加入到脚本的检测名单里面而已，你去控制面板手动添加进去就行了，以后每次打开pt站都会更新这个站点的cookie到nastools上。完全自动化，如果手动导入ptpp上的还更麻烦了。
> > > 这只是我的看法，开发人员怎么认为就不知道了
> > 
> > 诶 对噶 居然没想到自己改js 瓜了 nastool能加nexusphp以外的架构吗
> 
> 我不确定，我这个月才玩pt，没几个站，都是np的，所有没测试过，试试呗

几个站够用就行   😏

**Comment by haoshaoyang** [comment]
> > > 用插件可以直接把站点的cookie直接传到nastool里面
> > 
> > 
> > 插件支持的站点太少了 而且 我一次性开60+的网页 直接浏览器拉爆哈哈哈哈 缓一哈还没的事 结果能导入的只有一小部分
> 
> 我说的是油猴的那个脚本，理论上支持所有站点，只是部分站点没加入到脚本的检测名单里面而已，你去控制面板手动添加进去就行了，以后每次打开pt站都会更新这个站点的cookie到nastools上。完全自动化，如果手动导入ptpp上的还更麻烦了。
> 
> 这只是我的看法，开发人员怎么认为就不知道了

m-team能够用么？其他几个pt站正常，馒头一直提示【获取的cookie为空，请使用BETA版油猴，退出脚本】，实际上已经切换到beta版了

**Comment by PTrustMe** [comment]
// 如果油猴插件是测试版(可获取更多cookie)，请填写BETA，否则默认即可
var tampermonkeyVersion = "BETA";

> > > > 用插件可以直接把站点的cookie直接传到nastool里面
> > > 
> > > 
> > > 插件支持的站点太少了 而且 我一次性开60+的网页 直接浏览器拉爆哈哈哈哈 缓一哈还没的事 结果能导入的只有一小部分
> > 
> > 
> > 我说的是油猴的那个脚本，理论上支持所有站点，只是部分站点没加入到脚本的检测名单里面而已，你去控制面板手动添加进去就行了，以后每次打开pt站都会更新这个站点的cookie到nastools上。完全自动化，如果手动导入ptpp上的还更麻烦了。
> > 这只是我的看法，开发人员怎么认为就不知道了
> 
> m-team能够用么？其他几个pt站正常，馒头一直提示【获取的cookie为空，请使用BETA版油猴，退出脚本】，实际上已经切换到beta版了

// 如果油猴插件是测试版(可获取更多cookie)，请填写BETA，否则默认即可
var tampermonkeyVersion = "BETA";
这里没写吧

**Comment by Adsryen** [comment]
> > > > 用插件可以直接把站点的cookie直接传到nastool里面
> > > 
> > > 
> > > 插件支持的站点太少了 而且 我一次性开60+的网页 直接浏览器拉爆哈哈哈哈 缓一哈还没的事 结果能导入的只有一小部分
> > 
> > 我说的是油猴的那个脚本，理论上支持所有站点，只是部分站点没加入到脚本的检测名单里面而已，你去控制面板手动添加进去就行了，以后每次打开pt站都会更新这个站点的cookie到nastools上。完全自动化，如果手动导入ptpp上的还更麻烦了。
> > 
> > 这只是我的看法，开发人员怎么认为就不知道了
> 
> m-team能够用么？其他几个pt站正常，馒头一直提示【获取的cookie为空，请使用BETA版油猴，退出脚本】，实际上已经切换到beta版了

不行吧 好像    手动也没加上

**Comment by jxxghp** [comment]
后面版本支持自动获取Cookie，只要填个名称和网址就行。
