### ISSUE TITLE
查找硬链接范围太大,找不动

### ISSUE THREAD

**Issue by Sowevo** [jxxghp/nas-tools#2135]
https://github.com/jxxghp/nas-tools/blob/6fdd0e46c15dad2de1991639980ccaa541752963/web/action.py#L3845-L3850

这里找出来的file_dir范围太大了
查起来太慢了
是不是可以从配置文件里movie_path, tv_path, anime_path几个路径里面找

https://github.com/jxxghp/nas-tools/blob/6fdd0e46c15dad2de1991639980ccaa541752963/config/config.yaml#L55-L70

**Comment by jxxghp** [comment]
是docker运行吗？  docker应该还好吧。
从配置目录找也是个方法。

**Comment by Shurelol** [comment]
如果要缩小范围的话，可以考虑

如果是用的目录同步，通过同步目录的源目录和目的目录互查


如果是用下载软件监控，通过下载目录的访问路径和媒体库目录互查

**Comment by jxxghp** [comment]
加了个目录选择，下个版本更新。
