### ISSUE TITLE
消息通知添加按钮，选择是否发送 “查看详情” 链接

### ISSUE THREAD

**Issue by n0thing2speak** [jxxghp/nas-tools#2138]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.5.1
>
> 环境: docker 

## 你想要新增或者改进什么功能？
消息通知添加按钮，选择是否发送 “查看详情” 链接

> 你想要新增或者改进什么功能？

因为分享给几个人一起看，这样的话可以拉到群里，配合v2.5的通知功能，可以用一个新的bot来做消息推送，避免暴漏后台地址

## 这个功能有什么可以参考的资料吗？
发送显示详情的代码地址：https://github.com/jxxghp/nas-tools/blob/6fdd0e46c15dad2de1991639980ccaa541752963/app/message/channel/telegram.py#L98

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
都邀请一起看了，还不让看地址吗。反正需要有密码才能登录。
不是很有必要。
