### ISSUE TITLE
chinesesubfinder配置中有大量的空格，删除后会重新出现

### ISSUE THREAD

**Issue by gudumuyu** [jxxghp/nas-tools#2139]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.5.1
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> chinesesubfinder设置中都含有好多个空格，删除重新保存后，依然存在

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 恢复正常配置

## 给出程序界面截图、后台运行日志或配置文件

> 
![image](https://user-images.githubusercontent.com/32303402/203523868-fb246024-1eb1-4cb3-bd50-23977e6e25cd.png)

**Comment by bugwd** [comment]
我也是这样 而且更改设置重启后不变
