### ISSUE TITLE
文件路径无法识别

### ISSUE THREAD

**Issue by moluyang** [jxxghp/nas-tools#214]
/share/downloads/complete/动漫识别/凡人修仙传：再别天南.A.Record.of.a.Mortal''s.Journey.to.Immortality.S03.2022.1080p.WEB-DL.AAC.H264-HDSWEB
=> /share/links/动漫识别

12:13:18 INFO - 【RMT】开始处理：/share/downloads/complete/动漫识别/凡人修仙传：再别天南.A.Record.of.a.Mortal''s.Journey.to.Immortality.S03.2022.1080p.WEB-DL.AAC.H264-HDSWEB
12:13:18 ERROR - 【RMT】文件转移失败，文件不存在：/share/downloads/complete/动漫识别/凡人修仙传：再别天南.A.Record.of.a.Mortal''s.Journey.to.Immortality.S03.2022.1080p.WEB-DL.AAC.H264-HDSWEB

文件结构
/share/downloads/complete/动漫识别/凡人修仙传：再别天南.A.Record.of.a.Mortal''s.Journey.to.Immortality.S03.2022.1080p.WEB-DL.AAC.H264-HDSWEB/凡人修仙传：再别天南.A.Record.of.a.Mortal's.Journey.to.Immortality.S03E06.2022.1080p.WEB-DL.AAC.H264-HDSWEB.mp4

**Comment by jxxghp** [comment]
文件大小？

**Comment by moluyang** [comment]
> 文件大小？

大小: 750.63 MB
凡人修仙传：再别天南.A.Record.of.a.Mortal's.Journey.to.Immortality.S03E06.2022.1080p.WEB-DL.AAC.H264-HDSWEB.mp4
凡人修仙传：再别天南. A.Record.of.a.Mortal''s.Journey.to.Immortality.S03.2022.1080p.WEB-DL.AAC.H264-HDSWEB

看群里说是s上点的问题's  到了工具里 就是俩点了

**Comment by moluyang** [comment]
> 文件大小？
文件夹 
's   真实路径里
''s  nastools 里

**Comment by lightolly** [comment]
这个转义应该可以去掉

**Comment by jxxghp** [comment]
测试了下没重现问题，这个''不知道是哪里来的，凡人修仙传之前是可以正确处理的，我自己也在订阅中。

**Comment by moluyang** [comment]
是不是我粘贴过来文字格式就变了，在sky里搜下这个种子下载下试试

**Comment by jxxghp** [comment]
有个新问题了，这个关了吧。
