### ISSUE TITLE
编辑订阅的时候, 选择的站点没有被选中

### ISSUE THREAD

**Issue by wyyqyl** [jxxghp/nas-tools#2144]
还是有个问题, 编辑订阅的时候, 选择的站点没有被选中

这里能看到我只从TJUPT这个站去下载
![QQ截图20221123213335](https://user-images.githubusercontent.com/787659/203559828-7dbf2052-c968-4c0a-a93d-f75c5640d437.png)

点编辑, 这个站没有被选中
![QQ截图20221123213354](https://user-images.githubusercontent.com/787659/203559861-d5c4274c-d31c-47df-8d49-0d710434c026.png)

_Originally posted by @wyyqyl in https://github.com/jxxghp/nas-tools/issues/2141#issuecomment-1325078542_

**Comment by jxxghp** [comment]
贴个图吧，这怎么分析呢？
