### ISSUE TITLE
V2.51  pushplus 消息推送失败。

### ISSUE THREAD

**Issue by liulian1978** [jxxghp/nas-tools#2145]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.51
>
> 环境: docker for Synology
>

## 你遇到什么问题了？

> nas-tools 2.45 升级到 2.51 以后 pushplus 消息推送失败。
> 希望后续版本中能修复

## 给出程序界面截图、后台运行日志或配置文件

> 
![image](https://user-images.githubusercontent.com/3723187/203568160-6aafe248-f0dd-4cf0-91ef-6d825632d126.png)

**Comment by jxxghp** [comment]
你不给个日志，我也没办分析

**Comment by sxyzy1016** [comment]
您好，我遇到了相同的问题，pushplus推送不工作了。

运行环境为：
NasTools v2.5.2
Debian 10 Python 3.8

添加Pushplus的token等设置项后，点击测试推送，会一直显示测试中，pushplus公众号上没有收到测试消息；
下载完成、转移完成等推送，pushplus公众号也没有收到消息；
并且上述操作后run.txt日志上没有任何关于推送的日志。

Python后台会报错，和上面@liulian1978 的一致。

敬请参考，谢谢
