### ISSUE TITLE
实时刷新媒体库不起作用

### ISSUE THREAD

**Issue by sfwilp** [jxxghp/nas-tools#2146]
在nas-toolsde 基础设置-媒体中开启“实时刷新媒体库”功能，emby没有开启实时刷新媒体库功能，完成转以后从日志观察确实有emby的媒体库刷新记录，但emby的媒体库实际上没有刷新。
观察nas-tools日志如下：
09:54:54 INFO - 【Meta】正在保存 poster 图片：/downloads/links/Movie/巴霍巴利王2：终结 (2017)
09:54:57 INFO - 【Meta】正在保存 fanart 图片：/downloads/links/Movie/巴霍巴利王2：终结 (2017)
09:54:58 INFO - 【Meta】正在保存 background 图片：/downloads/links/Movie/巴霍巴利王2：终结 (2017)
09:55:01 INFO - 【Meta】正在保存 logo 图片：/downloads/links/Movie/巴霍巴利王2：终结 (2017)
09:55:03 INFO - 【Meta】正在保存 disc 图片：/downloads/links/Movie/巴霍巴利王2：终结 (2017)
09:55:06 INFO - 【Meta】正在保存 banner 图片：/downloads/links/Movie/巴霍巴利王2：终结 (2017)
09:55:08 INFO - 【Emby】开始刷新Emby媒体库...
09:55:08 INFO - 【Emby】Emby媒体库刷新完成
09:55:08 INFO - 【Rmt】/downloads/Movie/巴霍巴利王.Baahubali（上）&（下）.BluRay.1080p.x265.10bit.MNHD-FRDS/巴霍巴利王2：终结.Baahubali.2.The.Conclusion.2017.BluRay.1080p.x265.10bit.MNHD-FRDS 处理完成，总数：1，失败：0
09:55:08 INFO - 【Subtitle】开始从Opensubtitle.org检索字幕: Baahubali 2 The Conclusion，imdbid=tt4849438

媒体库刷新从开始到结束在一秒钟内完成，怀疑没有实际开始。烦请大神排查问题。

**Comment by sfwilp** [comment]
补充下nas-tools版本号：2.5.1
emby版本号：4.7.9.0

**Comment by thsrite** [comment]
你的看当时你emby有没有正在进行扫描媒体库--
如果emby正在扫描媒体库 刮削之类的话，nastool通知emby刷新也不会进行的。

**Comment by sfwilp** [comment]
> 

这个我测了好多次，emby当时并没有扫描或刮削任务

**Comment by Earendil-C** [comment]
贴一下emby的日志

**Comment by sfwilp** [comment]
> 

emby日志没看到相关内容   不知道该粘哪些 @Earendil-C

**Comment by Earendil-C** [comment]
> > 
> 
> emby日志没看到相关内容 不知道该粘哪些 @Earendil-C

nt显示刷新完媒体库后的emby最新日志，有refresh字样

**Comment by sfwilp** [comment]
我开启debug  观察了下  nas-tool提示通知emby刷新媒体库后   emby没有任何日志 @Earendil-C      怀疑emby没有响应通知

**Comment by Earendil-C** [comment]
> 我开启debug 观察了下 nas-tool提示通知emby刷新媒体库后 emby没有任何日志 @Earendil-C 怀疑emby没有响应通知

不用开debug  普通日志下就有的
长这样Info Server: http/1.1 POST https://host1:2083/emby/Items/34362/Refresh?Recursive=true. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
如果没有的话，你的nastool连接到emby了吗

**Comment by jxxghp** [comment]
我一直在用，特意观察了一下，各种情况下都能准确刷新

**Comment by zydq123** [comment]
> 你的看当时你emby有没有正在进行扫描媒体库-- 如果emby正在扫描媒体库 刮削之类的话，nastool通知emby刷新也不会进行的。

确实是这样，之前没有更新的原因找到了，Jav插件一直占用着扫描，nastool发的更新等到前一个扫描结束才开始

**Comment by thsrite** [comment]
> > 你的看当时你emby有没有正在进行扫描媒体库-- 如果emby正在扫描媒体库 刮削之类的话，nastool通知emby刷新也不会进行的。
> 
> 确实是这样，之前没有更新的原因找到了，Jav插件一直占用着扫描，nastool发的更新等到前一个扫描结束才开始

是这样的

**Comment by sfwilp** [comment]
我没装jav插件

**Comment by jxxghp** [comment]
媒体库刷新从开始到结束在一秒钟内完成，怀疑没有实际开始。烦请大神排查问题。
——Emby的通知API就是发送个POST请求，并不会等Emby扫描完成才结束，有显示完成说明通知到了。
