### ISSUE TITLE
重命名不生效

### ISSUE THREAD

**Issue by MengQH123** [jxxghp/nas-tools#2148]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.5.1
>
> 环境: Synology
>

## 你遇到什么问题了？

> 我这边使用nastool的时候无法配置文件重命名的方式
> 已经按照要求配置了tmdb的 apikey了
> ![image](https://user-images.githubusercontent.com/37174029/203704784-7895d8e0-11f0-426c-b3ed-8f77bc4109ae.png)
> 并且已经重启过了服务，但是下载的文件依旧不是按照配置的生成对应的名字
> ![image](https://user-images.githubusercontent.com/37174029/203705712-7f6b6cec-181c-4ea6-8f45-6578e05d759e.png)
> 查看相关日志也没没发现相关问题
> ![image](https://user-images.githubusercontent.com/37174029/203730294-7996a978-dbe7-42e1-83cf-8218778f80aa.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
建议先找个教程看看怎么用的

**Comment by MengQH123** [comment]
謝謝 我這邊已經解決了&nbsp;&nbsp;


蒙清灏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月25日(星期五) 凌晨5:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jxxghp/nas-tools] 重命名不生效 (Issue #2148)





 
建议先找个教程看看怎么用的
