### ISSUE TITLE
v2.5.1 d939c813数据库问题

### ISSUE THREAD

**Issue by Mruser0** [jxxghp/nas-tools#2156]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.5.1 d939c813
>
> 环境: docker  Synology
>

## 你遇到什么问题了？
从2.5.0升级至这个版本出现的问题。

>1.数据库locked问题再次出现
   2.订阅ui问题,从推荐页添加订阅，添加成功后ui未点亮红心
   3.订阅集数不更新问题和订阅入库集数误差问题

1.数据库locked问题再次出现
![database](https://user-images.githubusercontent.com/107661622/203806887-ae3f358f-de4d-47e7-82ba-5519e5f0079c.png)

![database2](https://user-images.githubusercontent.com/107661622/203807001-7e539340-8090-4e85-8a5f-0643a520e5e3.png)

 2.订阅ui问题,从推荐页添加订阅，添加成功后ui未点亮红心
![订阅01](https://user-images.githubusercontent.com/107661622/203807942-a1f48bb4-62e4-4aa6-8477-1302405106e4.png)
![订阅02](https://user-images.githubusercontent.com/107661622/203807979-7f8e4e01-bcfe-4707-8c72-215c2ff0f287.png)

 3.订阅集数不更新问题和订阅入库集数误差问题
 
（一）订阅入库集数误差
![订阅03](https://user-images.githubusercontent.com/107661622/203816220-57c98182-8d62-4e79-a3e4-aba2e47f2819.jpg)
通过微信搜索自动下载天下长河，总集数40集，站点添加下载1-28集
![订阅04](https://user-images.githubusercontent.com/107661622/203816551-e071a7e9-1f26-48b6-a7b5-d9e732574d58.jpg)
站点缺失集数自动添加订阅

![订阅05](https://user-images.githubusercontent.com/107661622/203816665-6e5e874f-0126-4ebd-89ed-dcc1166fab65.jpg)
![订阅7](https://user-images.githubusercontent.com/107661622/203817867-d2fa1cc4-23f2-4b8e-b9bc-e1df29a75f66.png)

下载完成后，硬链接文件1-28集，这里入库集数相加为29，比实际硬链接媒体库文件多

（二）订阅集数不更新
![订阅6](https://user-images.githubusercontent.com/107661622/203817121-c05a0592-ffc3-40d5-8136-635e178a2cdd.png)
微信搜索自动添加订阅后，在已经下载完成并入库的情况下，web端订阅集数不更新

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
已浏览过

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
已查看过

## 你期望的结果
解决datebase locked 问题，修复订阅问题
> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by yourber** [comment]
我这边升级之后，电视剧订阅打不开了。

**Comment by Mruser0** [comment]
升级2.5.2后暂时没再报异常了

**Comment by Mruser0** [comment]
更新到v2.5.2 f629d44a后数据库错误又出现了
![555](https://user-images.githubusercontent.com/107661622/204123755-6a0cac03-a8bf-4fc7-aa5b-5149c7ab69ce.png)

**Comment by jxxghp** [comment]
上面列的这些问题，都是数据库锁了导致的

**Comment by Mruser0** [comment]
> 上面列的这些问题，都是数据库锁了导致的

出现datebase locked报错后，docker 容器重启会报docker api 错误，查看docker容器报错如下：
![888](https://user-images.githubusercontent.com/107661622/204176071-74985a46-beb9-4d02-af44-47d709253833.png)

百度后按照这个帖子删除nastool容器里的log.db文件后可以正常启动
帖子地址：http://www.yaotu.net/biancheng/28328.html
