### ISSUE TITLE
站点丢失

### ISSUE THREAD

**Issue by SouLXH** [jxxghp/nas-tools#2158]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.5.1
> 环境: docker or windows or Synology
>docker（UNRAID）

## 你遇到什么问题了？

> 描述一下你遇到的问题
PT站点会丢失。
 （nastool中的实时日志显示）  如图1234，第一次自动签到，站点是全的，都签到了，但是不知道为什么2：00的时候会再次签到（我设置的是1：00定时签到），这个时候有很多站点丢失了（站点维护中不可见），但是不知道原因。而且不是永久性丢失，有时候似乎还会重现（手动重启nastool，站点会恢复）
   (docker中的日志)如图5，在预设时间只签到了一次，并且只有部分站点签到了，其他站点丢失了。（临睡前确定共有12个签到站点）

该问题，手动重启nastools会恢复正常，重新显示所有站点（指站点维护中重现显示丢失的站点）
> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![Snipaste_2022-11-25_09-30-48](https://user-images.githubusercontent.com/44329481/203882946-52de2958-5a0c-4cc6-baa0-685af52bf0dd.png)
![Snipaste_2022-11-25_09-30-54](https://user-images.githubusercontent.com/44329481/203882953-a2c44f6e-1c35-430c-8d58-5d6492c891f7.png)
![Snipaste_2022-11-25_09-31-59](https://user-images.githubusercontent.com/44329481/203882958-26ffc0db-c3dc-4723-b9d0-bbe3b3b5e69b.png)
![Snipaste_2022-11-25_09-32-17](https://user-images.githubusercontent.com/44329481/203882962-8b6d4720-9699-42fa-8233-61b77cd4a229.png)
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![docker](https://user-images.githubusercontent.com/44329481/203883683-822ef22e-9988-4088-bc50-e1ac689cb537.png)

**Comment by jxxghp** [comment]
没有你说的这个情况

**Comment by SouLXH** [comment]
> 没有你说的这个情况

经过排查似乎是因为PtSiteToNas-tools这个插件导致的，2.5.0以后的版本站点添加部分 API有变化？

**Comment by dinsen80951** [comment]
你好，我HDarea和冬樱站点地址在PT站点后/attendance.php一直签到不成功，好大提示404、冬樱503，你站点后是啥
