### ISSUE TITLE
下载器监控功能打开后，重启nas-tools会默认关闭“下载器监控”

### ISSUE THREAD

**Issue by sfwilp** [jxxghp/nas-tools#2159]
版本：2.5.1
在目录同步功能关闭的情况下打开“下载器监控”，无相关日志提示。
在此情况下如果重启nas-tools会默认关闭“下载器监控”。

重启日志：
12:50:59 INFO - 配置文件地址：/config/config.yaml
12:50:59 INFO - NASTool 当前版本号：v2.5.1
12:50:59 INFO - 数据库初始化...
12:50:59 INFO - 数据库初始化已完成
12:50:59 INFO - 数据库更新...
12:50:59 INFO - 数据库更新已完成
12:50:59 INFO - 日志输出类型为：file
12:50:59 INFO - 日志将写入文件：/config/logs
12:50:59 INFO - WEB管理页面用户：ulysses
12:50:59 INFO - 未启用https，请使用 http://IP:3000 访问管理页面
12:50:59 INFO - TMDB匹配模式：正常模式
12:50:59 INFO - 媒体管理软件设置为：emby
12:50:59 INFO - 未配置分类策略
12:50:59 INFO - 下载软件设置为：qbittorrent
12:50:59 INFO - 默认文件转移模式为：硬链接
12:50:59 INFO - 索引器设置为：builtin
12:50:59 INFO - 微信等移动端渠道搜索已开启自动择优下载
12:50:59 INFO - 保种时间未配置，自动删种功能已关闭
12:50:59 INFO - 下载软件监控未开启，下载器监控功能已关闭
12:50:59 INFO - 开始启动进程...
12:51:00 INFO - 站点自动签到服务启动
12:51:01 INFO - RSS订阅服务启动
12:51:01 INFO - 订阅定时搜索服务启动
12:51:01 INFO - 媒体库同步服务启动
12:51:01 INFO - 刷流服务启动

**Comment by jxxghp** [comment]
内建的重启功能有问题，下个版本修复。
