### ISSUE TITLE
请求适配一下基于企业微信群机器人webhook的消息推送

### ISSUE THREAD

**Issue by cunbow** [jxxghp/nas-tools#2165]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.5.1
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 一个基于企业微信群机器人的消息推送
最近在玩企业微信机器人，发现这个机器人提供的功能非常强大，而且注册难度极低，个人即可注册使用，可以基于webhook推送
1.如何使用群机器人推送消息
在终端某个群组添加机器人之后，创建者可以在机器人详情页看的该机器人特有的webhookurl。开发者可以按以下说明向这个地址发起HTTP POST 请求，即可实现给该群组发送消息。
当前自定义机器人支持文本（text）、markdown（markdown）、图片（image）、图文（news）四种消息类型。

## 这个功能有什么可以参考的资料吗？

>群机器人配置说明  https://developer.work.weixin.qq.com/document/path/91770

**Comment by jxxghp** [comment]
如果只是消息通知意义不大，如果能实现交互则可以考虑。
