### ISSUE TITLE
发现一种基于腾讯云Hiflow+微信公众号的消息推送和交互的可能性

### ISSUE THREAD

**Issue by cunbow** [jxxghp/nas-tools#2166]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.5.1
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 发现了一种基于腾讯云Hiflow+微信公众号的消息推送和交互的可能性
1.推送消息：
Hiflow可以接收webhook消息，解析后通过公众号发送给用户
2.接收消息
Hiflow可以接收绑定的微信公众号的信息，并解析出各种参数，然后通过get或post发送给指定地址

## 这个功能有什么可以参考的资料吗？

> 接收消息
![image](https://user-images.githubusercontent.com/42895319/203954173-86802c04-33aa-4fc5-a692-f083f6e5b788.png)
>推送消息
![image](https://user-images.githubusercontent.com/42895319/203954439-507a0343-b85b-4be3-9fc1-de214029a999.png)
腾讯云Hiflow地址：https://hiflow.tencent.com/console/

**Comment by jxxghp** [comment]
2.接收消息
Hiflow可以接收绑定的微信公众号的信息，并解析出各种参数，然后通过get或post发送给指定地址
——这里需要公众号，普通用户是注册不了公众号的吧？ 如果不能实现交互那意义也不大。

**Comment by jxxghp** [comment]
找到个wxpusher但也只能触发流程，不能获取消息内容：
![image](https://user-images.githubusercontent.com/51039935/204066327-0f02a1e7-0a53-4819-beba-89b03f3dbdfa.png)
