### ISSUE TITLE
希望细化择优下载规则

### ISSUE THREAD

**Issue by lizling** [jxxghp/nas-tools#2168]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.5.1
>
> 环境: docker

## 你想要新增或者改进什么功能？

希望细化择优下载规则，如提供站点优先级排序功能、清晰度优先级排序功能、提供SDR/HDR/DV版选择、用户期望自动下载的文件大小优先级：优先自动下载10G以内、10-20G文件、>20G文件，这样可以保证下载命中率更高。

**Comment by jxxghp** [comment]
用过滤规则
