### ISSUE TITLE
无法识别带文件路径带‘的文件

### ISSUE THREAD

**Issue by sungamma** [jxxghp/nas-tools#217]
![image](https://user-images.githubusercontent.com/33790/171367611-62e86f54-21ba-4fa1-808d-c497fb508e67.png)
程序在处理文件名时，莫名奇妙多了一个`'`，从而导致找不到文件。此问题与 #214 问题一样。

应该是程序处理`'`时出现了差错

**Comment by jxxghp** [comment]
原来是手动识别时的问题，那知道问题在哪了。
