### ISSUE TITLE
nt企业微信emby webhook通知失效

### ISSUE THREAD

**Issue by Linyue-GitHub** [jxxghp/nas-tools#2174]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.5.2
>
> 环境: docker
>

## 你遇到什么问题了？

> 设置正常，但是企业微信未通知emby播放信息
![Screenshot_2022-11-26-11-09-57-952_com microsoft emmx](https://user-images.githubusercontent.com/71179298/204070250-3e4d2b3d-e595-4379-90e3-c8e21afa7ff1.jpg)

![Screenshot_2022-11-26-11-00-52-219_com miui videoplayer](https://user-images.githubusercontent.com/71179298/204070219-49e2c84c-00b0-403a-a7ae-60d684c3e7be.jpg)
![Screenshot_2022-11-26-11-09-10-701_com miui videoplayer](https://user-images.githubusercontent.com/71179298/204070235-1e67d223-cff2-42fb-ad56-d1b7156e0635.jpg)
![Screenshot_2022-11-26-11-09-17-137_com miui videoplayer](https://user-images.githubusercontent.com/71179298/204070237-e1c4d764-f6a3-4d7f-9d5a-b110151a4856.jpg)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 未解决

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Linyue-GitHub** [comment]
![Screenshot_2022-11-26-11-13-23-781_com tencent mm](https://user-images.githubusercontent.com/71179298/204070366-957618bb-c4f9-4111-a8bc-ed067cfef287.jpg)
10月15日都还是正常通知的，后面就不通知了，设置都没变过。

**Comment by jxxghp** [comment]
是emby改版了？配置界面都变了

**Comment by Linyue-GitHub** [comment]
@jxxghp 老大，我看代码更新了，我也更新到了最新版测试了一下，企业微信还是没有通知诶。emby版本4.7.10 webhook版本1.0.22

**Comment by jxxghp** [comment]
这么奇怪吗？我自己用已经正常了解

**Comment by Linyue-GitHub** [comment]
> 这么奇怪吗？我自己用已经正常了解

webhook的插件版本是最新版嘛？
