### ISSUE TITLE
v2.5.2版本，底层使用openwrt-docker 无法保存设置，

### ISSUE THREAD

**Issue by a1693994915** [jxxghp/nas-tools#2175]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.5.2
>
> 环境: docker openwrt
>
> 描述一下你遇到的问题

设置无法保存，更改API以及账户用户名密码后，重启系统 所有数据丢失，会被重新初始化

**Comment by snoweer** [comment]
我也是同样的问题。

**Comment by snoweer** [comment]
NASTools版本：v2.5.2
环境：UnRAID v6.11.1
配置无法保存，重启后，除目录同步信息被保存外，其他设置全部丢失。

**Comment by jxxghp** [comment]
内建的重启功能好像是还有问题，暂时不用吧。重启Docker

**Comment by SOYOJOE** [comment]
Me too!

**Comment by developer-wlj** [comment]
docker 设置问题 我也遇到过  建容器时 把nastool 配置文件夹也映射出来 就行了

**Comment by a1693994915** [comment]
更改配置文件地址，然后没有配置文件输出，应该原因出在这里

**Comment by jxxghp** [comment]
要下个版本才能解决内建重启不能保存配置的问题

**Comment by a1693994915** [comment]
OK，坐等老大下个版本
