### ISSUE TITLE
nastools Qbittorrent 连接失败

### ISSUE THREAD

**Issue by kmf32x** [jxxghp/nas-tools#2178]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v2.5.2
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 描述一下你遇到的问题
之前配置好后一直正常，昨天更新后，搜索资源链接QB下载无法下载，设置-下载器-测试连接失败。
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
是
<img width="1084" alt="图片1" src="https://user-images.githubusercontent.com/119107858/204084307-1cd9e213-ebfb-462c-822c-9e2b0831a607.png">
<img width="1051" alt="微信图片_20221126181606" src="https://user-images.githubusercontent.com/119107858/204084309-db1c1750-a2ee-4cfb-b7e8-129845f6ca7c.png">
<img width="1030" alt="微信图片_20221126181622" src="https://user-images.githubusercontent.com/119107858/204084311-5500b8cd-ce30-4a85-86e6-fd52f818ec44.png">

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by luyufan498** [comment]
请问这个问题怎么解决呢，我遇到了相同的问题，只有把TR/QB设置成和NASTOOL相同的IP地址（都设置成host模式）才能成功，不然就是 unreachable的报错
