### ISSUE TITLE
签到功能优化

### ISSUE THREAD

**Issue by YoshiPark** [jxxghp/nas-tools#2179]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> V2.5.2
> 环境: docker 

## 你想要新增或者改进什么功能？

> 在2.2的版本中，作者引入浏览器仿真功能进行签到，但目前手上有一些站点使用浏览器仿真功能时，在站点测试时候会显示Chrome模拟访问失败，关掉浏览器仿真之后，在站点测试就能正常ping通，为了更好进行签到，建议在站点维护新增站点时，可以类似RSS订阅地址一样，添加签到地址一行让添加者自行填写，填写后程序按照填入的签到地址去进行访问签到，如不填写则设置默认地址签到。

## 这个功能有什么可以参考的资料吗？

> 本人在关闭浏览器仿真条件下，对同一个站点，设置两个站点维护：
一个设置站点地址为https://pturl/index.php,设置用途为订阅刷流和统计分析，没有签到；
另新增一个签到站点并设置站点地址为https://pturl/attendance.php，其中设置用途只为签到。
这样点击签到时候pt站点页面就会显示签到已得XX。

但对同一个站点，如果只设置一个站点维护，设置站点地址为https://pturl/index.php,设置用途为签到订阅刷流和统计分析四个时，
这样点击签到后打开pt站页面，显示的是签到获得魔力（签到按钮未被点击），实际原因可能是因为关闭浏览器仿真导致无法找到签到按钮，

因此提出一个优化建议，在新增站点处添加一个签到地址url让添加者自行填写，同时也能解决一些不以attendance.php结尾的站点签到问题，希望作者可以考虑一下，谢谢

**Comment by Shurelol** [comment]
有没有一种可能，一开始就可以填签到地址？
![image](https://user-images.githubusercontent.com/16237201/204090425-92d7aefa-3df8-426d-8b56-0ab4297bd9cd.png)

**Comment by YoshiPark** [comment]
> 有没有一种可能，一开始就可以填签到地址？ ![image](https://user-images.githubusercontent.com/16237201/204090425-92d7aefa-3df8-426d-8b56-0ab4297bd9cd.png)

谢谢指正！明天签到测试一下，谢谢！
