### ISSUE TITLE
到底字幕是怎么设置的

### ISSUE THREAD

**Issue by zzfree2021** [jxxghp/nas-tools#2186]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.5.2
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
我在nastools里边设置，字幕按照默认，选择的OpenSubtitles，播放器用的是jellyfin，现在下载的所有电影都是没有字幕的，那这个字幕设置有什么用呢，按我的理解，应该是下载完，刮削，下载字幕，把整理好的文件放到整理后的文件夹，现在字幕是个问题，不知道各位是什么设置的

**Comment by Mrxlei** [comment]
一样迷茫............选择的OpenSubtitles似乎都搜不到字幕

**Comment by RejeyFeng** [comment]
我用了Chinesesuf，也搜不到，提示physical video file not found，我把地址改下，重新下载，在等测试

**Comment by cikezhu** [comment]
> 

这个错误提示是你没有设置正确目录导致的,  本地目录填写 link 硬链接的目录     远程目录填写csf的/media/ 就解决了

**Comment by cikezhu** [comment]
> 我用了Chinesesuf，也搜不到，提示physical video file not found，我把地址改下，重新下载，在等测试

这个错误提示是你没有设置正确目录导致的, 本地目录填写 link 硬链接的目录 远程目录填写csf的/media/ 就解决了

**Comment by funnysky1980** [comment]
> 

多个媒体文件夹怎么处理，本地目录和远程目录只能填写一组。

**Comment by RejeyFeng** [comment]
填上级目录，我试好了，比如媒体库:/media/links&nbsp; 远程字幕 直接/media



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月29日(周二) 下午2:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jxxghp/nas-tools] 到底字幕是怎么设置的 (Issue #2186)




   
多个媒体文件夹怎么处理，本地目录和远程目录只能填写一组。

**Comment by RejeyFeng** [comment]
已解决，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月28日(周一) 下午3:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jxxghp/nas-tools] 到底字幕是怎么设置的 (Issue #2186)




  
我用了Chinesesuf，也搜不到，提示physical video file not found，我把地址改下，重新下载，在等测试
  
这个错误提示是你没有设置正确目录导致的, 本地目录填写 link 硬链接的目录 远程目录填写csf的/media/ 就解决了

**Comment by funnysky1980** [comment]
电影和电视剧在不同的存储空间，不在一个目录里。这个怎么解决？

**Comment by RejeyFeng** [comment]
我没搞过，你可以试试映射成同一个上级目录，比如本来映射成/aa/电影→/media/电影，/bb/电视→/media/电视，然后再来讲究nastool和字幕的关联，实际上，硬连接前的目录是下载目录，那些教程误导人太深弄的太复杂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月29日(周二) 下午2:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jxxghp/nas-tools] 到底字幕是怎么设置的 (Issue #2186)




 
电影和电视剧在不同的存储空间，不在一个目录里。这个怎么解决？
