### ISSUE TITLE
媒体转移时新建文件夹的权限好像和以前不一样了

### ISSUE THREAD

**Issue by lxm9357** [jxxghp/nas-tools#2187]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.5.0~v2.5.2
>
> 环境: 威联通 NAS Docker 
>

## 你遇到什么问题了？

> 如下图所示，红框中的四个文件夹是更新到2.5及之后版本生成的，其余的是更新之前生成的文件夹
> ![图片](https://user-images.githubusercontent.com/49564012/204110703-b3b385ac-37bb-4ad1-9612-0b7cfdb5732e.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已浏览过，没找到答案。
> 自己瞎研究了一下感觉好像是UMASK的问题？但是我UMASK一直是默认值000没动过，然后发现entrypoint.sh文件中的代码“umask ${UMASK}”在11月13日的更新中被删掉了，不知道是不是这个原因导致的。
> 我代码小白，如果搞错了大佬莫怪哈。

## 你期望的结果

> 权限可以和以前一样777

## 给出程序界面截图、后台运行日志或配置文件

> 05:28:54 INFO - 【Rmt】开始处理：/share/Downloads/Movies/The.Departed.2006.BluRay.1080p.DTS-HD.MA5.1.x265.10bit-BeiTai/The.Departed.2006.BluRay.1080p.DTS-HD.MA5.1.x265.10bit-BeiTai.mkv，转移方式：软链接
> 05:28:54 INFO - 【Rmt】正在转移文件：The.Departed.2006.BluRay.1080p.DTS-HD.MA5.1.x265.10bit-BeiTai.mkv 到 /share/Media/Movies/无间道风云 (2006)/无间道风云 (2006) - 1080p.mkv
> 05:28:54 INFO - 【Rmt】文件 The.Departed.2006.BluRay.1080p.DTS-HD.MA5.1.x265.10bit-BeiTai.mkv 软链接完成
> 05:28:54 INFO - 【Meta】正在查询TMDB电影：1422 ...
> 05:28:54 INFO - 【Rmt】/share/Downloads/Movies/The.Departed.2006.BluRay.1080p.DTS-HD.MA5.1.x265.10bit-BeiTai/The.Departed.2006.BluRay.1080p.DTS-HD.MA5.1.x265.10bit-BeiTai.mkv 处理完成，总数：1，失败：0

**Comment by jxxghp** [comment]
程序不会去改文件权限，决定于你的运行环境

**Comment by lxm9357** [comment]
> 程序不会去改文件权限，决定于你的运行环境
大佬，可能我没有把问题描述清楚，但是我几乎可以确定是环境变量umask没有正确生效导致的这个问题。因为我在entrypoint.sh文件中手动加了一行“umask ${UMASK}”，然后重启docker，这个问题就解决了。之后我再次重启docker，entrypoing.sh因为自动更新被改回github中的版本，问题又出现了。麻烦大佬可以再确认一下？打扰大佬了 @jxxghp

**Comment by jxxghp** [comment]
好的，我改一下
