### ISSUE TITLE
文件管理里可以识别，自动识别就是不识别，而且更新到最新版pushplus不能用了

### ISSUE THREAD

**Issue by jamesjav** [jxxghp/nas-tools#2188]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v2.5.1:lastest
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 描述一下你遇到的问题
文件管理里可以识别，自动识别就是不识别，而且更新到最新版pushplus不能用了
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
yep
## 你期望的结果

> 描述以下你期望的结果
pushplus更新yi以后不能用，重启尝试过。为啥文件管理里能正确识别，而自动识别多次尝试仍旧无法识别
## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/70810068/204112640-f9275219-6d76-499e-bdc4-362c4f26c015.png)
![屏幕截图_20221127_072950](https://user-images.githubusercontent.com/70810068/204112696-1a1033fe-ba43-49e8-bf62-5fb98eb93c94.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
- 识别结果里有tmdbid才算识别成功
![image](https://user-images.githubusercontent.com/16237201/204113101-db126b9b-bc8f-4f30-9902-be4c954d7693.png)
- 最新版本是[eef93be](https://github.com/jxxghp/nas-tools/commit/eef93be767df4378c4f72194a9c7c8a6fda52d14)，在右下角看下
![image](https://user-images.githubusercontent.com/16237201/204113117-ac216074-30a4-4d3c-9ef1-55edc64eda8e.png)
