### ISSUE TITLE
下载器的下载设置使用非默认下载器不会起作用

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [jxxghp/nas-tools#2196]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.5.2 f629d44a
>
> 环境: docker
>

## 你遇到什么问题了？

> 我的默认下载器是tr，自定义下载添加了一个下载设置是qb，但是他匹配到资源后还是会使用tr进行下载

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已浏览

## 你期望的结果

> 能正常使用qb下载

## 给出程序界面截图、后台运行日志或配置文件

> 【Downloader】添加下载任务：【喵萌奶茶屋】★10月新番★[异世界舅舅/Isekai Ojisan][08][1080p][简日双语][招募翻译]，目录：/volume2/Download1/tr/anime，Url：https://mikanani.me/Download/20221126/be07ab9d4a382090992dfd8d7e1fadf2032bb70e.torrent
12:11:11 INFO - 【Message】发送telegram消息服务Telegram：title=异世界归来的舅舅 (2022) S01 E08 开始下载, text=评分：7.9 来自：自定义订阅 任务：异世界舅舅 质量：1080p 种子：【喵萌奶茶屋】★10月新番★[异世界舅舅/Isekai Ojisan][08][1080p][简日双语][招募翻译] 促销：免费

**Comment by Shurelol** [comment]
已修，等更新
