### ISSUE TITLE
下载目录设置-无法保存

### ISSUE THREAD

**Issue by FantasticSkyBaby** [jxxghp/nas-tools#2198]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.5.2
>
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 下载目录设置-无法保存；重启系统后之前设置又回来了，并生效

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 无

## 你期望的结果

> 正常保存生效

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by RejeyFeng** [comment]
版本2.5.0就不可以保存了，基础设置都无法保存

**Comment by jxxghp** [comment]
不要用内置的重启功能，重启Docker
