### ISSUE TITLE
预告片被错误硬链接

### ISSUE THREAD

**Issue by bobo0810** [jxxghp/nas-tools#22]
两种情况可能出问题 （1）电影和预告在同级目录  （2）预告片在子目录。
```
└─电影
└─预告片
```

```
└─电影
   └─预告片
```
可能的解决方案：例如遍历根目录 存在多个视频时，通过文件大小判断  or  丢弃小于200M的文件等。

**Comment by jxxghp** [comment]
预告片单独目录存放，不要在movie_path配置目录下。
PT下载的资源不会带预告片。

**Comment by bobo0810** [comment]
> 预告片单独目录存放，不要在movie_path配置目录下。 PT下载的资源不会带预告片。

@jxxghp 大佬好，遇到多次预告片 硬链接的情况。可能解决办法： （1）存在多个视频时，判定容量大的为正片。（2）忽略容量<200M的。 

PT站的资源是带预告片的。
![image](https://user-images.githubusercontent.com/26057879/160070522-4e146d25-a4d4-40d1-a2d2-0466e2bdd406.png)
![image](https://user-images.githubusercontent.com/26057879/160070767-0f553312-ada4-40f3-bc96-9c3ede74c50a.png)
