### ISSUE TITLE
建议：蓝光格式下的index.bdmv，不必放入手动识别的菜单下

### ISSUE THREAD

**Issue by qqeszw** [jxxghp/nas-tools#2205]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> v2.5.2
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 描述一下你遇到的问题
蓝关格式文件，会有一个index.bdmv文件提示无法识别转移，会显示在手动识别菜单下。去执行手动识别得到提示，“不支持的媒体文件格式”， 去查看目的目录下， 实际上存在这个文件。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
index.bdmv，不必放入手动识别的菜单下

## 给出程序界面截图、后台运行日志或配置文件
<img width="1635" alt="image" src="https://user-images.githubusercontent.com/4793839/204204731-6d0dff36-c9b8-4c1f-83ab-8fcf6cf46a2d.png">

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/205222114-902cfae2-c078-4b1c-979c-ce9511164fd5.png)
![image](https://user-images.githubusercontent.com/16237201/205222128-caf335cc-e6d2-411a-96dd-e2502e532fc9.png)

**Comment by jxxghp** [comment]
蓝光原盘不支持，很难搞。
