### ISSUE TITLE
pushplus推送不工作

### ISSUE THREAD

**Issue by vleboy** [jxxghp/nas-tools#2210]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.5.2
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> pushplus推送不工作

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

>浏览了，并为解决

## 你期望的结果

> 按以前一样让push工作

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
![image](https://user-images.githubusercontent.com/8954958/204230361-0953217f-dc02-4002-b388-e1293589a6c2.png)

> 其它问题提供后台日志，如为Docker请提供docker的日志
![image](https://user-images.githubusercontent.com/8954958/204230591-0e4cc99b-e2c4-4b62-af7c-fd65eb6c68ec.png)
![image](https://user-images.githubusercontent.com/8954958/204230641-fee0f641-1e03-4b93-a298-a9d8a66deb13.png)
![image](https://user-images.githubusercontent.com/8954958/204230701-e46ec896-f0b7-46ab-a46c-4f3786224618.png)

**Comment by Shurelol** [comment]
更新

**Comment by vleboy** [comment]
> 更新

v2.5.2 就是最新的版本啊？
