### ISSUE TITLE
豆瓣想看无法解析

### ISSUE THREAD

**Issue by Ice-Cream-MY** [jxxghp/nas-tools#2214]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.5.2 f629d44a
>
> 环境: docker 
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
豆瓣想看目录无法识别，结果为空，另想询问一下cookie是抓取客户端还是pc端，目前没有提供测试cookie选项无法确认cookie是否有效以及是否抓取正确。
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![image](https://user-images.githubusercontent.com/76402568/204255927-9eaa634d-bc05-4905-b795-dc4316060830.png)
![image](https://user-images.githubusercontent.com/76402568/204256153-ce8df1e3-a970-460b-9c39-e737a5855e46.png)

**Comment by jxxghp** [comment]
PC端，正常不用cookie都行

**Comment by Ice-Cream-MY** [comment]
> PC端，正常不用cookie都行

感谢，凌晨豆瓣想看又恢复正常
