### ISSUE TITLE
debian11下如何安装所需的浏览器内核？

### ISSUE THREAD

**Issue by zzzqu** [jxxghp/nas-tools#2216]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 最新
>
> 环境: 源码运行
>

## 你遇到什么问题了？

> 未 找 到 浏 览 器 内 核 ， 当 前 环 境 无 法
检 索 opensubtitles字 幕 ！

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是

**Comment by jxxghp** [comment]
非Docker版本没有开放这个功能

**Comment by YoshiPark** [comment]
> 非Docker版本没有开放这个功能

请教一下作者，docker版本开启浏览器仿真测试连通性所有站点直接显示Chrome模拟访问失败，去掉仿真之后就可以ping通，已经拉取最新的2.6.0镜像，之前的镜像测试仿真也失败，权限是root权限，想请教一下是可能有什么问题导致的，谢谢！
![微信图片_20221129173355](https://user-images.githubusercontent.com/20967749/204492757-d5f23069-7cc9-462b-a372-b17d2d2be88a.png)

**Comment by jxxghp** [comment]
改了代码，本地部署的自已安装webdriver到 /usr/lib/chromium/chromedriver，注意还要装chrome，且跟driver版本要匹配。

**Comment by jxxghp** [comment]
> > 非Docker版本没有开放这个功能
> 
> 请教一下作者，docker版本开启浏览器仿真测试连通性所有站点直接显示Chrome模拟访问失败，去掉仿真之后就可以ping通，已经拉取最新的2.6.0镜像，之前的镜像测试仿真也失败，权限是root权限，想请教一下是可能有什么问题导致的，谢谢！ ![微信图片_20221129173355](https://user-images.githubusercontent.com/20967749/204492757-d5f23069-7cc9-462b-a372-b17d2d2be88a.png)

要看日志

**Comment by jxxghp** [comment]
> > > > 非Docker版本没有开放这个功能
> 
> > > 
> 
> > > 
> 
> > > 请教一下作者，docker版本开启浏览器仿真测试连通性所有站点直接显示Chrome模拟访问失败，去掉仿真之后就可以ping通，已经拉取最新的2.6.0镜像，之前的镜像测试仿真也失败，权限是root权限，想请教一下是可能有什么问题导致的，谢谢！ ![微信图片_20221129173355](https://user-images.githubusercontent.com/20967749/204492757-d5f23069-7cc9-462b-a372-b17d2d2be88a.png)
> 
> > 
> 
> > 要看日志
> 
> 
> 
> ![微信图片_20221129201531](https://user-images.githubusercontent.com/20967749/204526734-f59426f3-592c-4ab7-aef6-bc676495005a.png)
> 
> 点击连通性测试三次，只输出这三行信息，貌似看不出来

浏览器没起来导致的，环境有问题

**Comment by YoshiPark** [comment]
> > > > > 非Docker版本没有开放这个功能
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 请教一下作者，docker版本开启浏览器仿真测试连通性所有站点直接显示Chrome模拟访问失败，去掉仿真之后就可以ping通，已经拉取最新的2.6.0镜像，之前的镜像测试仿真也失败，权限是root权限，想请教一下是可能有什么问题导致的，谢谢！ ![微信图片_20221129173355](https://user-images.githubusercontent.com/20967749/204492757-d5f23069-7cc9-462b-a372-b17d2d2be88a.png)
> > 
> > 
> > > 
> > 
> > 
> > > 要看日志
> > 
> > 
> > ![微信图片_20221129201531](https://user-images.githubusercontent.com/20967749/204526734-f59426f3-592c-4ab7-aef6-bc676495005a.png)
> > 点击连通性测试三次，只输出这三行信息，貌似看不出来
> 
> 浏览器没起来导致的，环境有问题

作者您好，环境变量如下设置，是否哪里不对，请指教，谢谢！
![微信图片_20221129204754](https://user-images.githubusercontent.com/20967749/204533280-9bfffe49-12f4-4afd-bd92-3f0f3d3987f5.png)

**Comment by jxxghp** [comment]
你试下完全删掉现在用的这个镜像和容器，重新拉取最新的镜像，重新建。

复用之前的配置文件夹，数据不会丢。

**Comment by YoshiPark** [comment]
> 你试下完全删掉现在用的这个镜像和容器，重新拉取最新的镜像，重新建。
> 
> 复用之前的配置文件夹，数据不会丢。

尝试了重新拉取最新镜像，还是起不来，是不是要以高权限运行容器?
![微信图片_20221130181006](https://user-images.githubusercontent.com/20967749/204768466-8ae9b4df-bae7-4240-bf79-8f5ca1950080.png)
