### ISSUE TITLE
 刚添加的下载文件，马上就自动转移了

### ISSUE THREAD

**Issue by FantasticSkyBaby** [jxxghp/nas-tools#2220]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.5.2
>
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 刚添加的下载文件，马上就自动转移了

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 无

## 你期望的结果

> 描述以下你期望的结果

## 下载完成之后再转移

> 如UI BUG请提供截图及配置文件截图
<img width="589" alt="12" src="https://user-images.githubusercontent.com/14800057/204349941-7efed0ea-269d-4f74-8d11-ca7a1cbae241.PNG">

> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by FantasticSkyBaby** [comment]
下载软件监控打开或关闭都是这样

**Comment by qearlziper** [comment]
自己在下载器设置下未完成文件添加后缀就不会立即同步了
