### ISSUE TITLE
容器内非root用户启动程序无法创建/.pm2/ 路径

### ISSUE THREAD

**Issue by sn066** [jxxghp/nas-tools#2223]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 容器内使用非root用户启动进程, 无法在根目录创建 /.pm2文件夹
![image](https://user-images.githubusercontent.com/32016161/204415341-10fc8c6c-e00e-4b0c-82fb-d8884cd87bc5.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

创建文件夹时路径建议放到开放权限的路径,或Dockerfile内声明需要使用的路径及权限

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by sn066** [comment]
临时解决方案建议如下:

创建一个目录挂载:
 - /data/nas-tool/.pm2:/.pm2:rw
 注意:  /data/nas-tool/.pm2  权限需要修改为启动容器需要用的UID
命令如:  chown -R 911.911 /data/nas-tool/.pm2

然后重新创建容器即可

**Comment by Loyoan** [comment]
类似的问题，启动以后报没有pm2-runtime

**Comment by jxxghp** [comment]
上午提交打版了，应该是好了
