### ISSUE TITLE
v2.6.0 Jellyfin连接失败

### ISSUE THREAD

**Issue by ronchy1** [jxxghp/nas-tools#2225]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.0
>
> 环境: docker
>

## 你遇到什么问题了？
镜像安装后导入原配置Jellyfin连接测试失败
> 描述一下你遇到的问题
通过v2.6.0镜像下载安装，导入原v2.5.2的配置文件，Jellyfin的连接测试失败，终端报“name 'Jellyfin' is not defined”，重新输入也是同样的问题
![capture-2022-11-29-09-59-18](https://user-images.githubusercontent.com/32918026/204420536-af6aba7d-5ef5-467a-a36a-b0cbc893aa3d.jpg
![capture-2022-11-29-10-02-36](https://user-images.githubusercontent.com/32918026/204420587-cd63f2c8-daeb-4c92-89e6-b125f364d597.jpg)
)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
这个是Bug，马上修复
