### ISSUE TITLE
能否把首页显示的媒体库播放信息作为消息通知里面的媒体服务直接推送到企业微信呢？

### ISSUE THREAD

**Issue by Linyue-GitHub** [jxxghp/nas-tools#2226]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.0
>
> 环境: docker

## 你想要新增或者改进什么功能？
能否把首页显示的媒体库播放信息作为消息通知里面的媒体服务直接推送到企业微信呢？
emby和jellyfin里webhook填nt的地址/emby/jellyfin 企业微信均收不到推送 plex的可以 
> 你想要新增或者改进什么功能？
![Screenshot_2022-11-29-11-02-49-797_com microsoft emmx-edit](https://user-images.githubusercontent.com/71179298/204428965-73bf9fc9-b085-48e5-8635-4dffc866a8f8.jpg)

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
有这功能啊，介绍页都没认真看。
