### ISSUE TITLE
su-exec: pm2-runtime: No such file or directory

### ISSUE THREAD

**Issue by Loyoan** [jxxghp/nas-tools#2227]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.0
>
> 环境: docker Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
已经HEAD is now at 9e2410f1 Merge pull request #2224 from jxxghp/dev
但是还是说su-exec: pm2-runtime: No such file or directory

![image](https://user-images.githubusercontent.com/9997604/204441507-dac78ba2-ddbd-4498-8e1e-d9be96809834.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![image](https://user-images.githubusercontent.com/9997604/204441675-abcef163-fbd8-433f-bccf-ec974ef47ec2.png)

**Comment by guo2239102** [comment]
同上，重建容器后一直提示此信息

**Comment by zjfeiye** [comment]
我也遇到这个问题

**Comment by FantasticSkyBaby** [comment]
同样这个问题

**Comment by zjfeiye** [comment]
把容器重置，然后启动，这时候好像不会自动更新，容器还是老版本，此时不要重启不要重启不要重启，进系统，点右上角的铃铛，点升级，升级到2.6，可临时解决，注意一重起就报这个错

**Comment by woshijie120** [comment]
![image](https://user-images.githubusercontent.com/108522192/204466146-a47cb5cf-2a57-4be2-988a-42bb4727caaa.png)
同样问题

**Comment by RejeyFeng** [comment]
用这个ontainrrr/watchtower更新，没问题。。
```
`# 手动更新容器镜像，清理旧镜像 ,自删` \
docker run --rm \
-v /var/run/docker.sock:/var/run/docker.sock \
containrrr/watchtower \
--cleanup `# 清除空镜像 ` \
--run-once `# 一次性运行，加名字指定更新`\
  jxxghp/nas-tools
```

**Comment by FantasticSkyBaby** [comment]
> 重置之前的设置还有么

**Comment by jxxghp** [comment]
报这个错则需要更新镜像

**Comment by woshijie120** [comment]
我这边是重新拉取镜像搞的，还是报错呢

**Comment by zjfeiye** [comment]
> > 重置之前的设置还有么

有的
一开始我怕没了，特意备份了一下

**Comment by jxxghp** [comment]
如果实在不想重新拉镜像的，还有一种方法，自动升级完成后进容器运行以下命令：npm install pm2 -g

**Comment by woshijie120** [comment]
> 如果实在不想重新拉镜像的，还有一种方法，自动升级完成后进容器运行以下命令：npm install pm2 -g

![image](https://user-images.githubusercontent.com/108522192/204494525-1ad30d94-5121-45ea-8615-77ab434942c0.png)
请教下这种情况还能怎么做呢？

**Comment by jxxghp** [comment]
> > 如果实在不想重新拉镜像的，还有一种方法，自动升级完成后进容器运行以下命令：npm install pm2 -g
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/108522192/204494525-1ad30d94-5121-45ea-8615-77ab434942c0.png)
> 
> 请教下这种情况还能怎么做呢？

你这个是基础包都没更新，重拉镜象吧，比这么折腾快多了。

**Comment by woshijie120** [comment]
新拉取的镜像也在报
chown: /usr/lib/chromium: No such file or directory
su-exec: pm2-runtime: No such file or directory
难道是我这里环境本身的问题？

**Comment by jxxghp** [comment]
> 新拉取的镜像也在报
> 
> chown: /usr/lib/chromium: No such file or directory
> 
> su-exec: pm2-runtime: No such file or directory
> 
> 难道是我这里环境本身的问题？

没重置容器吧，并不是你拉了就代表生效了。

**Comment by Loyoan** [comment]
#群晖docker的朋友可以试试这样
1. 在docker中手动关掉nastool
2. 打开nastool的详情页面
3. 点启动，然后很快地去“终端”页面新建一个bash页面
4. 等一会会bash页面就可以输入了
5. 输入`npm install pm2 -g `
6. 等更新程序自己走完应该就行了，不行的话手动重启一下

第一步之所以要先关掉是为了启动时检查更新能多有一点时间来输入安装pm2的指令

**Comment by woshijie120** [comment]
重新换了部署方式搞定了。。。

**Comment by zhangjian640** [comment]
# bash 列出容器
`docker container ls`
# 找到jellfin container id, 进入(xxxx替换id)
` docker exec -it xxxx bash`
# 下载、安装node
`curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -`
`apt-get install -y nodejs`
# 安装
npm install pm2 -g
