### ISSUE TITLE
使用Alist挂载的文件夹，在媒体整理中，每个文件夹仅能识别最多1200个文件，也只能刮削1200个文件

### ISSUE THREAD

**Issue by pc0289** [jxxghp/nas-tools#2229]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 
>v2.5.2 693cc082
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> 使用Alist挂载的文件夹，在媒体整理中，每个文件夹仅能识别最多1200个文件，也只能刮削1200个文件

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

>未找到同类问题

## 你期望的结果

> 希望可以读取到全部文件

## 给出程序界面截图、后台运行日志或配置文件

> ![image](https://user-images.githubusercontent.com/41770790/204468543-31a0b9c7-df15-473e-afa3-5ac2e05415d8.png)
> 此处最多显示1200个文件，但实际可能有三千多文件

**Comment by Earendil-C** [comment]
访问你挂载的文件夹里面，看看一共有几个文件

**Comment by pc0289** [comment]
> 
我挂载的文件夹里面超过1200的时候显示1200个，低于1200的时候显示实际数量

Rcloned到群晖的文件夹里显示没问题，超过1200也是正确的数量，只有NASTOOL 里面会少

**Comment by jxxghp** [comment]
进容器ls看看有多少

**Comment by pc0289** [comment]
ls数量也是正常的，我的alist是rclone挂到群晖里面的，觉得有可能是兼容问题了

另外的发现就是如果我自己把alist的那个电影文件夹（比如有3000个文件吧）软链接到另一个文件夹，就能读出3000个，但是那个原始的alist文件夹直接被NASTOOL访问的话，在nastool里面就只能显示1200个文件，在其他地方都是显示3000，比如群晖的文件管理器，比如挂到win的webdav里面，比如ssh里面，比如命令行ls之后

**Comment by jxxghp** [comment]
这个问题没有环境重现暂时无法解决
