### ISSUE TITLE
使用Clouddrive挂载的文件夹，在媒体整理中，文件夹识别文件不全，Alist挂载的可以识别全（虽然上限是1200个）

### ISSUE THREAD

**Issue by pc0289** [jxxghp/nas-tools#2230]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 
>v2.5.2 693cc082
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> 使用Clouddrive挂载的文件夹，在媒体整理中，文件夹识别文件不全，Alist挂载的可以识别全（虽然上限是1200个）

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

>未找到同类问题

## 你期望的结果

> 希望可以读取到全部文件

## 给出程序界面截图、后台运行日志或配置文件

> ![image](https://user-images.githubusercontent.com/41770790/204468880-b64c3467-5e8c-4a2d-862c-52b0681e58f8.png)
![image](https://user-images.githubusercontent.com/41770790/204469176-e4d0a3f6-8a1b-4d64-8a7d-5316c5749c2a.png)

> 相同文件夹，Alist能显示405个文件，Clouddrive只能显示200左右

**Comment by jxxghp** [comment]
#2229 提一个就行了

**Comment by pc0289** [comment]
其实是两个不同的问题来着，这个是clouddrive，不论多少都显示不全，那个是alist莫名其妙有个1200的上限，不过这个我找到答案了，好像是因为底层不一样，如果能改最好，改不了就关了吧
