### ISSUE TITLE
自动下载识别错误

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/nas-tools#224]
订阅的电视剧，下载了同名电影，而且库里面已经存在，同时清晰度也不对

![874C60CA-CEF0-4923-829E-D4A4B9C0BE72](https://user-images.githubusercontent.com/51367628/171782543-94f8449b-cb7f-42ea-957f-1aa09f8a6ecb.png)
![4EF4C65C-2611-40C2-ABD1-3D4CA0C9FC2C](https://user-images.githubusercontent.com/51367628/171782552-e10d0c3e-5424-41f6-aa29-9e4dbc900868.png)
![A5C95AE7-DF82-4734-8D18-1316EBFE672E](https://user-images.githubusercontent.com/51367628/171782554-c25663b2-4bba-468a-83ae-af2c400cd4f8.png)

**Comment by jxxghp** [comment]
1、分辨率的问题应该是副标题有720P字样导致的。

**Comment by jxxghp** [comment]
这两个电影的下载通知截图看一下，下载通知的信息比较多。

**Comment by jxxghp** [comment]
TMDB匹配模式 调整为 严格 后应该可以避免这个问题

**Comment by paysenyu** [comment]
> 这两个电影的下载通知截图看一下，下载通知的信息比较多。

截图就是，我只订阅了指环王2022 s01，结果把指环王三部曲，霍比特人三部曲都下载了。

**Comment by paysenyu** [comment]
> TMDB匹配模式 调整为 严格 后应该可以避免这个问题

这个在哪里调整呢

**Comment by paysenyu** [comment]
> TMDB匹配模式 调整为 严格 后应该可以避免这个问题

已经调整，还是一样的问题。 

订阅的时候已经识别到是美剧 指环王，实际下载的是电影指环王

**Comment by jxxghp** [comment]
最新的代码应该没这个问题了，针对指环王这部剧。
