### ISSUE TITLE
电视剧订阅制作组识别错误

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#2247]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.0
>
> 环境: docker
>

种子名称：Chainsaw Man S01E07 1080p AMZN WEB-DL H264 DDP2.0-PTerWEB

名称识别，识别出来的制作组是PTer而不是PTerWEB
![image](https://user-images.githubusercontent.com/54088512/204696404-b7dbaa4f-6aa1-42f9-b72b-2416d50d3de1.png)

以前订阅的都是填写的PTerWEB，且能识别
![image](https://user-images.githubusercontent.com/54088512/204696508-9b869fef-5f5a-4d66-9128-2a95f28f7c9c.png)

**Comment by thsrite** [comment]
种子名：Bleach Sennen Kessen Hen S01E08 2022 1080p KKTV WEB-DL x264 AAC-AnimeS@ADWeb
识别出来的Ani@ADWeb
![image](https://user-images.githubusercontent.com/54088512/204696939-a59f645f-c95a-4470-b4f2-46255d7a47ed.png)

**Comment by Shurelol** [comment]
已修复，等更新

**Comment by thsrite** [comment]
好嘞，辛苦
