### ISSUE TITLE
【问题求助】Jellyfin webhook通知设置问题

### ISSUE THREAD

**Issue by Linyue-GitHub** [jxxghp/nas-tools#2249]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
大佬们帮忙看一下jellyfin的webhook设置是否正确，我这样设置企业微信收不到消息。
![Screenshot_2022-11-30-11-07-02-092_org jellyfin mobile](https://user-images.githubusercontent.com/71179298/204698423-da3abb16-cb2a-4fa8-963a-10b538cc78bc.jpg)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
企业微信收到jellyfin推送信息
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by serenity666** [comment]
webhook url那里应该填企业微信生成的webhook地址吧

**Comment by Linyue-GitHub** [comment]
> webhook url那里应该填企业微信生成的webhook地址吧

你就是这样配置的嘛？能正常收到nt企业微信的推送？

**Comment by serenity666** [comment]
试了一下，搞不定

**Comment by serenity666** [comment]
> > webhook url那里应该填企业微信生成的webhook地址吧
> 
> 你就是这样配置的嘛？能正常收到nt企业微信的推送？

试了一下，收不到，插件项目地址没有相关教程，不知道怎能配置。

**Comment by Linyue-GitHub** [comment]
> > > webhook url那里应该填企业微信生成的webhook地址吧
> > 
> > 
> > 你就是这样配置的嘛？能正常收到nt企业微信的推送？
> 
> 试了一下，收不到，插件项目地址没有相关教程，不知道怎能配置。

等大佬回复看看吧 我也想用这个功能

**Comment by jxxghp** [comment]
要搭个测试环境好麻烦，先标记后面再看

**Comment by serenity666** [comment]
> > > > webhook url那里应该填企业微信生成的webhook地址吧
> > > 
> > > 
> > > 你就是这样配置的嘛？能正常收到nt企业微信的推送？
> > 
> > 
> > 试了一下，收不到，插件项目地址没有相关教程，不知道怎能配置。
> 
> 等大佬回复看看吧 我也想用这个功能

搞定了！！！将这两项这样填。顶部sever url填你的jellyfin地址，下面webhook url填你nastools地址。最下面有两项要这样填。
![Screenshot_2022-12-11-00-11-22-113_org jellyfin mobile](https://user-images.githubusercontent.com/64485323/206864504-7c9b4d1d-acc7-4daa-8994-2774431cfc43.jpg)

**Comment by Linyue-GitHub** [comment]
> 还要勾选Send All Properties (ignores template)这一项

老哥，你是我的神！终于可以用了，原来以前是没设置对。
![Uploading Screenshot_2022-12-11-00-28-36-552_com.tencent.mm.jpg…]()

**Comment by Linyue-GitHub** [comment]
> 还要勾选Send All Properties (ignores template)这一项

老哥，你是我的神！终于可以用了，原来以前是没设置对。
![Screenshot_2022-12-11-00-28-36-552_com tencent mm](https://user-images.githubusercontent.com/71179298/206865096-3ade8684-b064-438f-9b93-f2cf7c456d9a.jpg)

**Comment by serenity666** [comment]
@@测试下来还不够完善，上面我说的设置是将所有可用的信息全部发给nastools，由nastools选择需要的信息。我用企业微信的群内机器人可以实现下面的效果，点击海报还可以跳转到jellyfin该电影电视剧的详情界面，如果大大@jxxghp能告诉我nastools的webhook的数据格式或者模板，我可以尝试完善一下，jellyfin的webhook默认设置太基础了，需要自己编辑模板才能得到比较好的效果。
![1670813100016](https://user-images.githubusercontent.com/64485323/206949816-a8b5ae75-f440-4e14-85f2-6727207e06b8.jpg)
![1670813081993](https://user-images.githubusercontent.com/64485323/206949826-031f7cc4-b42e-4d75-970f-5dd538b26640.jpg)
以下为根据企业微信群机器人配置说明编写的部分模板，暂时比较简陋，只实现了用户登陆通知，新电影/电视剧通知，播放通知功能，并将电影的背景图设置成了通知的主图，比较美观，点击海报可以跳转到Jellyfin详情页。

**Comment by Linyue-GitHub** [comment]
> 找到了，nastools只解析了jellyfin上webhook上的三项信息，分别是：事件信息（NotificationType），项目名称（Name），和用户名（NotificationUsername），希望可以像EMBY一样添加加更多信息，比如设备名称（DeviceName），项目图片和地址啥的。

老哥，最新版3.0.3，你的jellyfin webhook通知还有效不？我的不通知了，设置没变。
