### ISSUE TITLE
建议固定一下搜索页面，筛选部分的边框

### ISSUE THREAD

**Issue by Eathan7758** [jxxghp/nas-tools#225]
首先，本人对此软件非常满意，感谢团队的辛苦付出，在此提出一点个人建议，
在资源搜索页面部分，筛选的侧边栏希望给个下拉下限，并且和搜索结果可以分开下拉
避免搜索结果过多时，空出来一块，影响美观
最后，祝软件越做越好

**Comment by jxxghp** [comment]
done
