### ISSUE TITLE
更新版本失败

### ISSUE THREAD

**Issue by lizhen789** [jxxghp/nas-tools#2253]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 更新版本后程序无法启动

![image](https://user-images.githubusercontent.com/35031472/204730080-6db4ec3d-39b5-4685-bdc6-aa75f798559a.png)

## 你期望的结果

> 正常运行

**Comment by boboink** [comment]
我们好像一样的问题

**Comment by jxxghp** [comment]
贴下子版本号，检查下是不是最新

**Comment by lizhen789** [comment]
版本号2.6.0啊，从2.5.0升级出现的问题，一开始升级的2.5.2，出现问题了，然后回退2.5.1，最后回退到2.5.0，一直是这么个问题，今天又尝试升级到2.6.0，一样问题没解决，跑步起来

**Comment by lizhen789** [comment]
？

**Comment by lizhen789** [comment]
啥都没说就 把我贴关闭了？
