### ISSUE TITLE
有没有考虑支持下usenet

### ISSUE THREAD

**Issue by hongshaoyi** [jxxghp/nas-tools#2255]
首先感谢大佬的付出
有没有考虑支持下usenet,就是sonarr和radarr的那个功能,这里面也是个庞大的下载库,如果能支持的话,我就可以彻底抛弃sonarr和
radarr了
如果大佬需要账号测试,我可以提供,indexer和下载服务商的账号我都有

**Comment by jxxghp** [comment]
没怎么用过s和r，不知道你说的是什么功能。
但这个工具也不希望功能无限扩张，不然很难稳定下来。

**Comment by hongshaoyi** [comment]
嗯,感谢大佬回复,我也是提一嘴,
这东西国外用的多,国内用的少,毕竟要付费
https://www.howtoip.com/the-how-to-geek-guide-to-getting-started-with-usenet/
这里有一篇比较详细的介绍,大佬以后有需要可以了解下
