### ISSUE TITLE
更新最新版2.6无法启动 ，多次尝试提示报错

### ISSUE THREAD

**Issue by springeddie00** [jxxghp/nas-tools#2256]
chown: /usr/lib/chromium: No such file or directory
        su-exec: pm2-runtime: No such file or directory

**Comment by Feng4** [comment]
我也是

**Comment by traceur** [comment]
遇到同样问题，麻烦管理尽快解决下吧

**Comment by Shurelol** [comment]
#2227

**Comment by zhangjian640** [comment]
https://github.com/jxxghp/nas-tools/issues/2227#issuecomment-1343898852
