### ISSUE TITLE
电报多机器人bug

### ISSUE THREAD

**Issue by dawei233** [jxxghp/nas-tools#2258]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.6.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
有多个电报机器人的情况下，1号绑定nastools，在给2号发消息的时候1号会触发
![image](https://user-images.githubusercontent.com/31338729/204807049-a8e8ddd4-1222-4e29-86a9-f60837846a5f.png)
![image](https://user-images.githubusercontent.com/31338729/204807330-cb091324-859d-4268-8a4c-c7c3c6e42296.png)
![image](https://user-images.githubusercontent.com/31338729/204807524-918d6129-b952-4aee-97d8-41d0ffe25b0e.png)
![image](https://user-images.githubusercontent.com/31338729/204807701-3c8e5f6b-d714-4d8f-9987-49f162c06bd6.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是的看了一下没leis类似情况
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
返回的消息，应该只会发给开启交互功能的那个

**Comment by dawei233** [comment]
> 返回的消息，应该只会发给开启交互功能的那个
对的返回的消息没问题，额但是不管给2号机器人发啥 1号都会给反应就很难受

**Comment by dawei233** [comment]
> 没看明白，你要贴一下你通知消息的配置。 多个机器人都绑到nastool了？

两个机器人 我nastool绑定了1号。。。但是会响应2号的消息
![image](https://user-images.githubusercontent.com/31338729/206058780-73edd400-8dc2-4bec-b249-79ef18bab723.png)

**Comment by dawei233** [comment]
![image](https://user-images.githubusercontent.com/31338729/206058906-69282c4f-54b8-4e95-897c-42fcc20b39f9.png)
就绑定了一个机器人

**Comment by jxxghp** [comment]
这个就很难理解了，不同的机器人token是不一样的呀，怎么可能会监听到别的机器人？  你另一个机器人通过telegram-helper之类的设置过了？

**Comment by dawei233** [comment]
没做过啥特殊设置啊，我也很奇怪
