### ISSUE TITLE
关于硬链接的两条建议。

### ISSUE THREAD

**Issue by lihouyu520** [jxxghp/nas-tools#226]
1.目前的建议：自动整理刮削错误的电影重新识别后，在生成新的硬链接后，原错误硬链接没有删除，建议可以重新识别后删除原硬链接
2.功能方面的建议：在媒体识别一栏增加一个已经分类好的树状硬链接显示界面，用户可以在里面手动查看/修改识别刮削。

**Comment by jxxghp** [comment]
1、历史记录时，查到错误的那条识别记录，按钮下面有个删除。

**Comment by jxxghp** [comment]
2、这一点想了下，太复杂，还是算了。

**Comment by lihouyu520** [comment]
哈哈，好的老大。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Mr Huang ***@***.***>
发送时间: Saturday, June 4, 2022 4:02:05 PM
收件人: jxxghp/nas-tools ***@***.***>
抄送: lihouyu520 ***@***.***>; Author ***@***.***>
主题: Re: [jxxghp/nas-tools] 关于硬链接的两条建议。 (Issue #226)


2、这一点想了下，太复杂，还是算了。

―
