### ISSUE TITLE
建议RSS时，为种子打上TMDB查询的原产地、原始语言标签后再套用过滤规则

### ISSUE THREAD

**Issue by gfk94508** [jxxghp/nas-tools#2260]
> NAStool 版本: v2.6.0

> 环境: docker

> 你想要新增或者改进什么功能？

加强过滤规则的自动化。RSS时，对应种子进行TMDB查询后打上原产地、原始语言标签，再套用不同过滤规则

- 目前痛点：对于港台剧，各个站点副标题或名称不能完全提取出共性关键词代表港台剧，不能完全用正则关键词套用适用港台剧的规则，举例

![1669819454394](https://user-images.githubusercontent.com/77316563/204825993-ece1df4a-7393-497e-b4db-61a9196525ad.png)

当我使用下列规则时，单条过滤规则不能完全排除或包含2个种子。如果能通过TMDB打上标签，就可以有针对性地创建过滤规则，过滤的自动化程度更高点

![1669819581564](https://user-images.githubusercontent.com/77316563/204826649-500b88ec-fbf5-4f9f-9284-afc58b1f3dba.png)

- 增加此功能的优势：过滤规则针对性更强，自动化程度更高，可以针对性大陆、港台、欧美、各原始语言设置不同的过滤规则并自动套用
- 后期也可以通过给过滤规则组打标签（而不是如图的每条加包含关键词），在订阅的时候自动套用过滤规则组

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
无

**Comment by Shurelol** [comment]
建议再研究下正则

**Comment by gfk94508** [comment]
> 建议再研究下正则

- 我理解的是正则也要有字段才可以匹配，截图的两个站点，堡就有字段表示其为台剧，柠檬没有，但是种子内容除了制作组都差不多。当我需要针对台剧（即这两个种子）套用国语或双语过滤规则的时候。我用台剧关键词的过滤规则是匹配不了柠檬这个种子的对吧？如果TMDB查询后能给柠檬这个种子加个台剧（或TMDB原产地），两个种子就有共有关键词，就能套用了

- 当然如果多建个过滤规则，订阅的时候手动套用也是可以达到目的。如果有这个功能可以混用一个过滤规则，觉得自动化程度更好一点。后期也可以考虑订阅自动套用有TMDB对应标签的过滤规则

- 只是个建议，感谢作者大大耐心阅读
