### ISSUE TITLE
希望内置索引器增加只下载免费种子的功能

### ISSUE THREAD

**Issue by banpingjiu** [jxxghp/nas-tools#2263]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.0 b00e4220

> 环境: docker 

> 我希望内置索引器增加只下载免费种子的功能

## 这个功能有什么可以参考的资料吗？

> jackett和prowlarr都有只下载免费种子的功能

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/204957983-69dc5cda-a010-4232-8f7f-8737d26c9452.png)
过滤规则里有促销选项，每个站点都可以设置过滤规则
