### ISSUE TITLE
群晖套件版升级后无法打开

### ISSUE THREAD

**Issue by elysion0619** [jxxghp/nas-tools#2264]
群晖套件版 矿神源
机型 群晖920+
系统版本 DSM 7.1.1-42962 Update 2

2.4.x->2.5.x 升级后无法访问此网页，192.168.x.x拒绝了我们的连接请求。停用后重新启用问题依旧，卸载后重装可进入，恢复备份后复现，只能重新配置。
2.5.x->2.5.2 升级后可直接使用。
2.5.2->2.6.0 升级后无法访问此网页，192.168.x.x拒绝了我们的连接请求。停用后重新启用问题依旧，卸载后重装可进入，恢复备份后复现，重新配置后可用。（遇到一次重装套件配置完后重启无法进入）

![image](https://user-images.githubusercontent.com/86302081/204955541-cc1f2ef7-3aa9-4c60-8612-e795c51d4f1d.png)

**Comment by zhengyvxiang** [comment]
我也遇到一样的问题

**Comment by elysion0619** [comment]
> 我也遇到一样的问题

试了新更新还是一样的问题，
Docker版可以正常更新用
