### ISSUE TITLE
北洋园突然不能下载了

### ISSUE THREAD

**Issue by xzshow** [jxxghp/nas-tools#2265]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.6.0
>
> 环境: docker or windows or Synology
群晖套件矿神的

## 你遇到什么问题了？
改了下北洋园的密码，更新 的NASTOOL北洋配置，一切正常，登陆，连通性都 是好的，也可以搜索，但就是不能下载了
![Q1MB$V0@MF}R`7~8$Z31HHS](https://user-images.githubusercontent.com/110080681/204975927-7c83e79a-e1e4-4bb9-a17b-d4e7c89fc534.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
没有账号可测试，可以问问别人是否有相同情况

**Comment by tevenfeng** [comment]
> 没有账号可测试，可以问问别人是否有相同情况

我有账号可以协助测试，但是我对这块调试不是很熟悉；
试着加日志调了一下，看着是在下面这块tju会返回重定向的url
```
def get_torrent_info(self, url, cookie=None, ua=None, referer=None):
        ........
        try:
            req = RequestUtils(headers=ua, cookies=cookie, referer=referer).get_res(url=url, allow_redirects=False)
            while req and req.status_code in [301, 302]:
                url = req.headers['Location']
                if url and url.startswith("magnet:"):
                    return None, url, [], f"获取到磁力链接：{url}"
                req = RequestUtils(headers=ua, cookies=cookie, referer=referer).get_res(url=url, allow_redirects=False)
            if req and req.status_code == 200:
```
