### ISSUE TITLE
群晖自动更新报错

### ISSUE THREAD

**Issue by shauew** [jxxghp/nas-tools#2271]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 最新版本
>
> 环境: docker or Synology
>

## 你遇到什么问题了？

> 自动更新动作生效但是更新日志提示权限问题。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 暂未发现有效解决方法

## 你期望的结果

> 升级到最新版本或者退回老版本，然后可以配置关闭自动更新。最好能找到问题所在，一次性解决后续问题。

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

![image](https://user-images.githubusercontent.com/14587200/205101619-a999137a-7992-43c6-9233-a1bf953f1c52.png)

[jxxghp-nas-tools.zip](https://github.com/jxxghp/nas-tools/files/10134046/jxxghp-nas-tools.zip)

**Comment by xyswordzoro** [comment]
删除容器 删除镜像， 重新下载镜像安装

**Comment by Shurelol** [comment]
#2227

**Comment by zhangjian640** [comment]
https://github.com/jxxghp/nas-tools/issues/2227#issuecomment-1343898852
