### ISSUE TITLE
有点没懂自动获取Cookie和UA，请问一下具体该怎么操作呀

### ISSUE THREAD

**Issue by Adsryen** [jxxghp/nas-tools#2272]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.6.0
> 环境: docker or windows or Synology
>群晖

## 你遇到什么问题了？

> 描述一下你遇到的问题
有点没懂自动获取Cookie和UA，具体该怎么操作呀
输入地址和名称过后  还是需要手动填  不知道是怎么操作

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
看了  或许没找到  也或许没有

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by xyswordzoro** [comment]
非自动，就是填入用户名密码更新cookie，不用去网页抓取了

**Comment by jxxghp** [comment]
点站点卡片右上角中间那个圆点。现在验证码自动识别率很低，后面会提升识别率。
