### ISSUE TITLE
目录同步文件移动模式下不会删除种子任务

### ISSUE THREAD

**Issue by git-0101** [jxxghp/nas-tools#2273]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 在使用监控模式时(文件转移模式)，文件下载完转移完成后会自动删除qb的种子。但是在选用目录同步时（文件转移模式），文件下载完转移完成后不会删除qb的种子。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 目录同步转移模式下，能跟监控模式一样，最后自动删除种子。因为转移后，种子就是无用种子了。

## 给出程序界面截图、后台运行日志或配置文件

> 
![Screenshot_20221202_040701](https://user-images.githubusercontent.com/115487446/205149386-ca8a8d69-fafb-4c6a-b200-70bdaf89be1a.jpg)

**Comment by xyswordzoro** [comment]
目录同步，就是监控的资源的文件夹，又不会监控种子的文件夹，功能不一样，再说种子那么小，有必要删除吗，可以隔几天手动删除下

**Comment by zzzqu** [comment]
> 

你在说啥啊，他说的种子就是包含文件的，确实不会删除，应该是bug

**Comment by zzzqu** [comment]
> 目录同步，就是监控的资源的文件夹，又不会监控种子的文件夹，功能不一样，再说种子那么小，有必要删除吗，可以隔几天手动删除下

他说的种子就是带上文件的，确实不会删除，应该是bug，rclone移动模式也不会删除

**Comment by Shurelol** [comment]
后面会更新自动删种功能，把显示文件丢失错误的种子删除就行了

**Comment by git-0101** [comment]
> 后面会更新自动删种功能，把显示文件丢失错误的种子删除就行了

好的。感谢大佬们的付出！！！越来越完善了！
