### ISSUE TITLE
通过网页登录nastools查看推荐加载TMDB电影时，图片无法正常加载。

### ISSUE THREAD

**Issue by zhanfei365** [jxxghp/nas-tools#2278]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.1
>
> 环境: docker on QNAP
>

## 通过网页登录nastools查看推荐加载TMDB电影时，图片无法正常加载。

> 提示：
**无法加载响应数据：No data found for resource with given identifier**

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
在CSDN上搜到了类似的问题，提示”根本原因是返回的json信息太大，nginx默认的缓冲区不足以支撑，导致nginx把返回的信息截断了，需要设置缓冲区的大小来解决这个问题“，这个需要怎么解决了啊
https://blog.csdn.net/Right__/article/details/127647744

## 你期望的结果

> 尽快解决，或者如何设置能够避免这个问题即可。

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/40481619/205279078-82a32f73-4267-4e4f-8008-07f889399ae6.png)

**Comment by Shurelol** [comment]
单纯就是梯子质量不好
