### ISSUE TITLE
中文电影，无法削刮演员信息

### ISSUE THREAD

**Issue by FantasticSkyBaby** [jxxghp/nas-tools#2279]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.1
>
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 中文（所有）电影也无法削刮演员信息

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 无

## 你期望的结果

> 正常削刮

## 给出程序界面截图、后台运行日志或配置文件

<img width="563" alt="屏幕截图_20221202_212545" src="https://user-images.githubusercontent.com/14800057/205303144-eff1230a-f933-4295-8ddd-de84590cfe26.png">

**Comment by Shurelol** [comment]
第一，这里的意思是tmdb提供的演员名单里，有些在豆瓣找不到这个演员，没法提供中文
第二，emby目前不支持nfo中非英文的演员名称自动下载演员元数据，需要手动点击演员进入演员页面，emby才会开始下载演员元数据，显示图片等
