### ISSUE TITLE
索引器的过滤规则似乎没有生效，数量显示也有些问题

### ISSUE THREAD

**Issue by shanyan-wcx** [jxxghp/nas-tools#228]
我过滤掉了HDR，体积限制30G，然而还是会搜出不符合要求的结果。我没有改动过条件，之前版本是能正常工作的，自从过滤规则移到索引器设置里之后好像就失效了。另外左侧分类的数量显示也有错误，显示数量为1，但有两个结果，或者显示为2但有三个结果。
![屏幕截图 2022-06-04 000049](https://user-images.githubusercontent.com/58252651/171903043-b13eb8b7-8d3c-429b-9f97-fb32385980ac.png)
![屏幕截图 2022-06-04 000711](https://user-images.githubusercontent.com/58252651/171903686-d678aa35-d09e-4172-aa8b-ea4c85a62b5f.png)

**Comment by jxxghp** [comment]
搜索现在不过滤了，微信/TG/豆瓣等自动下载才会按条件过滤。搜索现在通过侧边栏过滤。
