### ISSUE TITLE
内建索引pt站点只能搜索不能下载，使用jackett索引下载qb报错无权限

### ISSUE THREAD

**Issue by Ailina0728** [jxxghp/nas-tools#2280]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v2.6.1
> 环境: docker or windows or Synology
>synology

## 你遇到什么问题了？

> 使用内建索引pt站点搜索资源，无法下载，提示xxxxxx（资源标题）添加失败 url链接为空！
而且配置多个站点后，只能搜索到一个站点的资源，已经确认其他站点也存在相同资源
换成jackett索引可以添加下载任务，但是qb下载器一直报错无权限

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 帮忙给出解决方案

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![Snipaste_2022-12-02_21-51-30](https://user-images.githubusercontent.com/24652865/205317547-2f93a8b3-72cd-4b42-94d5-1bc7c347910b.png)
![Snipaste_2022-12-02_21-25-18](https://user-images.githubusercontent.com/24652865/205317650-25633304-44ec-4186-816b-05f7c0d176cf.png)
![Snipaste_2022-12-02_21-55-14](https://user-images.githubusercontent.com/24652865/205317736-5e3488d6-5696-4cc7-b31d-c2535b872cdc.png)

**Comment by jxxghp** [comment]
群晖版本，/config/sites.dat那个文件不要用旧的备份文件，要随版本升级。
QB没权限那是你自己的配置问题。

**Comment by livebelive** [comment]
> 

Ubuntu docker下的也有这个问题  版本是同样是 2.6.1  不要用旧的备份文件是什么意思啊？我没有备份文件啊，docker安装的时候 应该就是2.6.1版本 也不存在旧版本文件的情况。。。
