### ISSUE TITLE
目录同步新增同步规则（针对固态缓存、机械保种的使用情况）

### ISSUE THREAD

**Issue by tdn0102** [jxxghp/nas-tools#2281]
> NAStool 版本: v2.6.1
> 环境: synology
**> 你想要新增或者改进什么功能？**
    针对使用固态盘缓存种子然后下载完成后转移到机械硬盘再进行分类情况，可以细分一下目录同步规则。
    当前目录同步里的硬链接不能跨盘，所以只能使用复制/移动方式来进行文件转移，但苦于没有转移规则，容易把未下载完成的文件转移过去，希望可以添加文件类型排除规则（比如.!qb文件）
    或者可以考虑优化“下载完成自动迁移”的模式，将其添加一个“种子下载完成后调用qb/tr的‘更改保存目录’”功能，并能指定目标文件夹规则（如现有资源库），这样也不影响保种，实现起来也更简单。
    万分感谢。

**Comment by Shurelol** [comment]
有没有一种可能qb，tr都能设置临时目录，以及下载完后转移目录？
![image](https://user-images.githubusercontent.com/16237201/205326333-0601b9a0-d41d-42e8-a1c3-abff40ea9bd7.png)
![image](https://user-images.githubusercontent.com/16237201/205326560-0339421a-6945-4fcf-afe7-55f679a3d475.png)

另外qb，tr都支持下载完成后执行脚本，自己写个脚本就能解决
