### ISSUE TITLE
剧集订阅任务下载合集包匹配后删除种子会连带本来有的源文件被删除

### ISSUE THREAD

**Issue by OctoberCK** [jxxghp/nas-tools#2282]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> v2.6.1
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 剧集订阅任务会下载合集包做匹配，发现合集包的内容已经全部包含后会对qb发出删除任务的指令，但这时的指令会删除种子及文件，导致以前分集下载的源文件被全部移除。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 以往的issues无相同问题

## 你期望的结果

> 这里下载合集包匹配完成后发出的删除任务指令应该是只删除任务种子，但不应该删除源文件（即删除种子及文件）

## 给出程序界面截图、后台运行日志或配置文件

![photo_2022-12-02 23 46 44](https://user-images.githubusercontent.com/42833426/205331649-f0b654c9-80f2-4bb5-a6c6-111c9dcbaf96.jpeg)

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/42833426/205331840-9629f521-9725-460d-9b4d-d52f804d2cae.png">
源文件被移除。

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
应该是理解错了，这个地方删的是以暂停状态添加的不需要的任务，不会删掉别的任务的文件吧？

**Comment by OctoberCK** [comment]
> 应该是理解错了，这个地方删的是以暂停状态添加的不需要的任务，不会删掉别的任务的文件吧？

因为有些pt站会把分集打包成合集，里面的内容和分集是完全一致的，这时候把合集的任务删掉了会连带着以前下载的分集被删除。我重复尝试了几次都是一样的结果。
