### ISSUE TITLE
docker  容器 更新 2.6.1版本 无限跑日志不启动

### ISSUE THREAD

**Issue by Alaskalaofei** [jxxghp/nas-tools#2284]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.1
>
> 环境: docker or windows or Synology
>
docker
## 你遇到什么问题了？

更新v2.6.1版本后日志无限配置并无法访问webui。

重新删除容器以及拉取镜像也是如此。

stdout: 更新成功...
stdout: 以PUID=1000，PGID=100的身份启动程序...
stdout: 2022-12-03T01:52:22: PM2 log: Launching in no daemon mode
stdout: 2022-12-03T01:52:22: PM2 log: App [NAStool:0] starting in -fork mode-
stdout: 2022-12-03T01:52:22: PM2 log: App [NAStool:0] online
stdout: 正在加载配置：/config/config.yaml
stderr: Traceback (most recent call last):
stderr:   File "/nas-tools/run.py", line 67, in <module>
stderr:     from web.main import App
stderr:   File "/nas-tools/web/main.py", line 19, in <module>
stderr:     from app.brushtask import BrushTask
stderr:   File "/nas-tools/app/brushtask.py", line 13, in <module>
stderr:     from app.filter import Filter
stderr:   File "/nas-tools/app/filter.py", line 4, in <module>
stderr:     from app.media.meta.release_groups import rg_match
stderr:   File "/nas-tools/app/media/__init__.py", line 1, in <module>
stderr:     from .meta.metainfo import MetaInfo
stderr:   File "/nas-tools/app/media/meta/metainfo.py", line 6, in <module>
stderr:     from app.media.meta.metaanime import MetaAnime
stderr:   File "/nas-tools/app/media/meta/metaanime.py", line 8, in <module>
stderr:     from app.media.meta.metabase import MetaBase
stderr:   File "/nas-tools/app/media/meta/metabase.py", line 3, in <module>
stderr:     from app.media.fanart import Fanart
stderr:   File "/nas-tools/app/media/fanart.py", line 8, in <module>
stderr:     class Fanart:
stderr:   File "/nas-tools/app/media/fanart.py", line 9, in Fanart
stderr:     _proxies = Config().get_proxies()
stderr:   File "/nas-tools/config.py", line 204, in get_proxies
stderr:     return self.get_config('app').get("proxies")
stderr:   File "/nas-tools/config.py", line 212, in get_config
stderr:     return self._config.get(node, {})
stderr: AttributeError: 'NoneType' object has no attribute 'get'
stdout: 2022-12-03T01:52:38: PM2 log: App [NAStool:0] exited with code [1] via signal [SIGINT]
stdout: 2022-12-03T01:52:38: PM2 log: App [NAStool:0] starting in -fork mode-
stdout: 2022-12-03T01:52:38: PM2 log: App [NAStool:0] online

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

是

## 你期望的结果

还请作者看看

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/51311487/205355705-a2e493ad-ba98-4c19-b2de-82e5755db7aa.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
config.yaml配置文件少了app下proxies节点，自己改吧

**Comment by Alaskalaofei** [comment]
> config.yaml配置文件少了app节点，自己改吧

没有用，改了之后去网页里面做修改改 就卡住了，然后报错。
![image](https://user-images.githubusercontent.com/51311487/205367353-178b1b30-03c1-4ab8-83ff-95571fa3da6a.png)

**Comment by Alaskalaofei** [comment]
从git上的config全部复制粘贴也不行，网页做修改后 后台会自动修改config 然后卡死。

**Comment by Alaskalaofei** [comment]
> config.yaml配置文件少了app节点，自己修改吧

从git上的config全部复制粘贴也不行，网页做修改后后台会自动修改config然后卡死。
