### ISSUE TITLE
建议添加 Slack 通知及交互

### ISSUE THREAD

**Issue by xushier** [jxxghp/nas-tools#2288]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.1
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
添加可交互通知，微信由于可信代理使用麻烦，电报需要魔法网络。Slack 国内不需要魔法并且支持交互。
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
https://api.slack.com
https://www.jianshu.com/p/ce0e24764df9

**Comment by jxxghp** [comment]
支持交互的话可以考虑下
