### ISSUE TITLE
转移失败 QB 的标签问题

### ISSUE THREAD

**Issue by xushier** [jxxghp/nas-tools#2289]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.1
>
> 环境: docker
## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
下载器监控，由于路径问题转移失败之后 QB 里面标签新增的是已整理。建议转移失败 将标签设为 转移错误 或者 转移失败。
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Shurelol** [comment]
转移失败的记录可以在媒体整理手动识别里找到
