### ISSUE TITLE
sync_path目录配置4设置后，会出现无法进入bug

### ISSUE THREAD

**Issue by Eathan7758** [jxxghp/nas-tools#229]
作者大大晚上好，设置配置4后会出现bug，进不去软件，经过测试，删掉就能进入，望有时间解决，非常感谢
![photo_2022-06-03_23-53-16](https://user-images.githubusercontent.com/105968442/171903954-90dc2911-9940-4eea-8184-fcfd6aa4b202.jpg)
![photo_2022-06-03_23-39-04](https://user-images.githubusercontent.com/105968442/171904009-a6e0a75a-66be-484e-a450-7f7555ffd597.jpg)

**Comment by Eathan7758** [comment]
已经解决了，正确的格式是'[/PT/AV|/PT/Links/AV]'   另外格式不对，确实会进不去软件，试验后在此说明

**Comment by jxxghp** [comment]
用UI配吧
