### ISSUE TITLE
关于下载完成转移的 Tips 描述

### ISSUE THREAD

**Issue by xushier** [jxxghp/nas-tools#2294]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.1
>
> 环境: docker

## 你想要新增或者改进什么功能？
关于下载完成转移的 Tips 描述
> 你想要新增或者改进什么功能？
![image](https://user-images.githubusercontent.com/31540107/205444836-b7c8e80c-44cc-4b6b-89d0-33c08f874ba1.png)
关于下载完成转移，下载完成日志显示转移错误，目的路径不存在。转移的 目的目录 找了半天找不到在哪里。最后设置了媒体库目录才转移成功。所以上图中的 Tips 里讲 ”下载文件转移未配置目的目录时，媒体文件将重命名转移到该目录“，那其实并没有目的目录的配置，媒体库目录就是目的目录。。。这里可以修改下
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
![image](https://user-images.githubusercontent.com/51039935/205470077-9d6aac1a-f634-4e34-9c0c-7228906e70cc.png)
说的是目录同步功能里的目的目录不配，会自动转移到媒体库目录
