### ISSUE TITLE
无法刮削图片

### ISSUE THREAD

**Issue by AceCandy** [jxxghp/nas-tools#2296]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.1 6358e1e6
>
> 环境: docker
>

## 你遇到什么问题了？

> 刮削电影的时候图片无法刮削，只生成了nfo

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已搜索，无结果

## 你期望的结果

> 正常图片刮削

### nt配置
![image](https://user-images.githubusercontent.com/6278583/205454131-ac72dc2b-0915-4d61-a233-13c79a88515d.png)

### 后台日志
![image](https://user-images.githubusercontent.com/6278583/205454008-72337ae3-7272-4244-9615-b244b8f8d2ef.png)

### 文件夹结果
![image](https://user-images.githubusercontent.com/6278583/205454042-55807377-ee4e-4aaf-a604-f79d54f92a35.png)

**Comment by jxxghp** [comment]
我这是正常的，还有问题的可以反馈下，不确定是不是共性问题

**Comment by huahuazi** [comment]
> 我这是正常的，还有问题的可以反馈下，不确定是不是共性问题

我也是这样，一样的情况，日志中显示下载，但是实际文件夹中没有，但是这个又不是所有影片都是这样的。有一些又可以成功。
怀疑是缓存没清理干净。

**Comment by huahuazi** [comment]
> 我这是正常的，还有问题的可以反馈下，不确定是不是共性问题
![Screenshot_2022-12-04-18-29-53-440_com.mi.android.globalFileexplorer.jpg](https://user-images.githubusercontent.com/20952620/205485822-6e2eb17c-a54f-453a-abbe-ddb8ddf059b3.jpg)![Screenshot_2022-12-04-18-29-57-530_com.microsoft.emmx.jpg](https://user-images.githubusercontent.com/20952620/205485827-17bd03b2-bf71-479d-92f0-921009840bcb.jpg)

**Comment by AceCandy** [comment]
> 我这是正常的，还有问题的可以反馈下，不确定是不是共性问题

补充一下问题排查，有时候重新删dm掉文件重新识别的时候会有个报错，然后nfo也没有生成。

![image](https://user-images.githubusercontent.com/6278583/205536009-862afe48-261a-4219-8833-f85d66fe589f.png)

![image](https://user-images.githubusercontent.com/6278583/205536054-036cc3ec-f44c-4835-9c14-1c6c0ca43f3a.png)

**Comment by jxxghp** [comment]
已经加了日志，还有问题带日志来。
