### ISSUE TITLE
手动识别 增加 手动输入影视名称 输入框

### ISSUE THREAD

**Issue by xushier** [jxxghp/nas-tools#2298]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.1
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
![image](https://user-images.githubusercontent.com/31540107/205460514-2bef2132-f5df-4ef4-9fa8-fff5d5638dfc.png)
手动识别需要打开 TMDB 输入影视名查询 ID，再返回 NasTools 输入 ID，比较麻烦。建议增加 手动输入影视名称 输入框，改名后再次识别。
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by serenity666** [comment]
+1，小部分电影会识别不了，每次都要tmdb找电影的id，然后再回来粘贴，可以手动输入电影名称就不用这么麻烦了。最好把年份也加上，这样不容易出问题。

**Comment by jxxghp** [comment]
296a01cfb6747f82d056546ad5f50f676db82135

**Comment by xushier** [comment]
2.7.3 没有找到，是下个版本更新吧？
