### ISSUE TITLE
希望自动分类可以设置更多类别

### ISSUE THREAD

**Issue by stephen909** [jxxghp/nas-tools#23]
外语电影涵盖的范围太广了，电影堆积不好找，建议可以手动增加日韩电影、印度电影、纪录片（分电影类和剧集，方便emby刮削）等类别。

**Comment by buhonghao** [comment]
只需要下载目录和同步目录一一对应，就可以解决这个问题。我同步目录一对一设置了10来个(分类很细)，但是下载目录只能2个，一般就手动下载到监控目录来让它自动硬链接。

**Comment by jxxghp** [comment]
v0.3.03 版本支持自定义分类
