### ISSUE TITLE
媒体识别建议增加

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#230]
媒体识别中 手动识别希望增加手动选择文件夹识别，现在想要识别只能全部，很麻烦

**Comment by jxxghp** [comment]
举个粟子

**Comment by Tartarus2014** [comment]
现在是动漫/电影/电视剧三个文件夹，我那出现过下载一个电视剧的三季视频，然而只有两季出现在了硬链接里，还有一个没有，这时候就需要单独文件夹识别而不是全部识别。

**Comment by jxxghp** [comment]
为什么另一个没有呢，未识别的会在手动识别里出现，如果也没有，检查文件大小。

**Comment by Tartarus2014** [comment]
`
![526F3584-A929-4FCA-A0D1-3D19710A1D4A](https://user-images.githubusercontent.com/39802246/171972275-85283a89-353e-49a1-b258-f301e41aeabe.png)
`
![9D3F8B51-8336-4A85-946A-60624C452A4C](https://user-images.githubusercontent.com/39802246/171972278-c5909e30-e86e-4d0b-868a-2d90741a5ccb.jpeg)

![ED1D5D2F-2ACB-4D92-B086-CF18DFDE8902](https://user-images.githubusercontent.com/39802246/171972279-3cc05476-f523-4cac-bc3a-7c186bd439e1.png)

所有都是符合的 但是不知道为啥 第一季没有出现，未识别里面也是空的。

**Comment by jxxghp** [comment]
媒体库文件夹下也没有吗？第一季点进去的文件看看。

**Comment by Tartarus2014** [comment]
媒体库文件夹下也没有 
![18DE1B5B-B58D-4C74-978E-D059A1FEE9F8](https://user-images.githubusercontent.com/39802246/171974245-9d603a08-f139-4946-bb1c-5cdb88f1b2e1.png)

**Comment by jxxghp** [comment]
第1季应该是年份错误，实际是2019年，会不会是识别为2009年的家有六子了？

**Comment by Tartarus2014** [comment]
还真有可能， 确实多了家有六子。。 我删了从扫下（更显示出增加个手动选择文件夹识别的重要性）

**Comment by jxxghp** [comment]
> 还真有可能， 确实多了家有六子。。 我删了从扫下（更显示出增加个手动选择文件夹识别的重要性）

识别错误的可以在历史记录里找到重新手动识别，完成后删掉历史记录即可（会同步删除错误的文件）。如果是未识别的，目前是会精确到底层文件夹的，即是可以选到子目录重新识别的。

**Comment by Tartarus2014** [comment]
这样啊 第一次知道
谢谢开发者
