### ISSUE TITLE
关于字幕过滤规则问题

### ISSUE THREAD

**Issue by xushier** [jxxghp/nas-tools#2304]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
对于国产影视剧，不需要过滤字幕，符合条件下载就行。对于国外影视剧，需过滤一下，只下载带中文字幕的。但是过滤规则是写在一起的，如果过滤了中文字幕，国产影视就没有匹配结果了；不过滤的话，又会下到无字幕的国外影视。如何让国产影视忽视字幕过滤规则，国外影视匹配字幕过滤规则
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
是

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
过滤规则不是能自己修改添加？订阅不是能选择过滤规则？

**Comment by xushier** [comment]
站点是包含国产和国外的，规则只能过滤有字幕和无字幕。假如订阅一个国产影视，在A站搜索，A站点应用的 过滤规则集 是要包含中文字幕，那由于国产影视种子副标题基本很少有包含字幕信息的，所以导致匹配不到。

如果在 同一个过滤规则集 里再加入不匹配字幕的规则，那订阅国外影视的时候，又会匹配到没有字幕的种子。

**Comment by xushier** [comment]
那这个国产剧和外国剧使用不同的规则，只能手动新增订阅选择实现，刷新豆瓣想看那种应该不会自动选择吧。

**Comment by Shurelol** [comment]
自己手动改，不同的人需求都不一样，有的过滤规则十几个，怎么自动分？

**Comment by xushier** [comment]
嗯嗯，谢大佬回复。我再想想解决办法
