### ISSUE TITLE
手动转移选择季0不管用

### ISSUE THREAD

**Issue by HySand** [jxxghp/nas-tools#2305]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 纸钞屋自动识别成1-5季，但在TMDB上是两个0季（对应文件1-2季）和1-3季（文件3-5季）。https://www.themoviedb.org/tv/71446-la-casa-de-papel/seasons
在文件管理里设置手动转移选择季0还是在往1季(原本的季)转移且转移失败。

## 你期望的结果

> 增加季偏移或者修复一下

## 给出程序界面截图、后台运行日志或配置文件
<img width="543" alt="image" src="https://user-images.githubusercontent.com/77628540/205476082-52907b8f-805f-44d2-886d-ba777cb7895e.png">

<img width="515" alt="image" src="https://user-images.githubusercontent.com/77628540/205476074-e72d608e-7897-4bb1-a85f-690d3eae835e.png">

**Comment by Shurelol** [comment]
加自定义识别词，重新识别
