### ISSUE TITLE
希望支持PLEX的{[source]-[id]}命名模板以提高刮削识别率

### ISSUE THREAD

**Issue by linlinlin530** [jxxghp/nas-tools#2310]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.1
>
> 环境: synology

## 你想要新增或者改进什么功能？

> 希望支持PLEX的{[source]-[id]}命名模板以提高刮削识别率

## 这个功能有什么可以参考的资料吗？

> https://support.plex.tv/articles/naming-and-organizing-your-movie-media-files/

> _If using the (non-“legacy”) Plex Movie agent available in Plex Media Server v1.20.1 and newer, you can also include the IMDb or TheMovieDB ID number in curly braces to help match the movie. It must follow the form {[source]-[id]}._
> 
> /Movies
>    /Batman Begins (2005) {imdb-tt0372784}
>       Batman Begins (2005) {imdb-tt0372784}.mp4
> /Movies
>    /Batman Begins (2005) {tmdb-272}
>       Batman Begins (2005) {tmdb-272}.mp4

这个规则需要用到占位符 { } ，直接在命名规则里加入 {tmdb-{tmdbid}} 是不行的，不知道需要以什么方式实现呢？

**Comment by Shurelol** [comment]
nastool使用python format函数进行格式化命名，对大括号{}的转移并非在前面加\，而是使用{{}}
即{{tmdb-{tmdbid}}}

**Comment by linlinlin530** [comment]
> nastool使用python format函数进行格式化命名，对大括号{}的转移并非在前面加\，而是使用{{}} 即{{tmdb-{tmdbid}}}

感谢大佬，小白没懂py的函数，闹笑话了哈哈，感谢！
