### ISSUE TITLE
Chrome模拟访问失败

### ISSUE THREAD

**Issue by YoshiPark** [jxxghp/nas-tools#2313]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> v2.6.1
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> docker版本开启浏览器仿真测试连通性所有站点直接显示Chrome模拟访问失败，去掉仿真之后就可以ping通。更新cookie时，同样出现Chrome模拟访问失败的情况，Chrome模拟访问失败如下所示：
![Chrome模拟访问失败](https://user-images.githubusercontent.com/20967749/205481402-af7f4bc2-b27d-4afe-8369-43bea0e10510.png)
进入容器内部，使用ps -ef查看点击测试连通性时，出现了Chrome-driver的进程，应该是起来了，但为何还会显示失败，原因不明
![容器内部情况](https://user-images.githubusercontent.com/20967749/205481481-2846ecb1-c049-4c10-9d7c-52714e9ea4b7.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已浏览过仍无法解决

## 你期望的结果

> 更新cookie时可以添加除浏览器仿真外的方式进行cookie获取，或者修复Chrome模拟访问问题

## 给出程序界面截图、后台运行日志或配置文件

> 在更新2.6.1版本之后，使用浏览器仿真失败后并无出现相关日志，在更新cookie时候，会显示如下日志
> 15:18:24 INFO - 【Sites】开始更新 XXX Cookie和User-Agent ... 
> 15:18:25 ERROR - 【Sites】获取 XXX 信息失败：Chrome模拟访问失败

**Comment by jxxghp** [comment]
查看Docker的日志，看有没有报错信息

**Comment by YoshiPark** [comment]
> 查看Docker的日志，看有没有报错信息

查看了Docker的日志，在测试连通性时候，显示Chrome模拟访问失败时并没有相关日志产生，更新cookies时就显示第一个评论最后的那段日志：
15:18:24 INFO - 【Sites】开始更新 XXX Cookie和User-Agent ...
15:18:25 ERROR - 【Sites】获取 XXX 信息失败：Chrome模拟访问失败

**Comment by jxxghp** [comment]
重启docker，改root权限，如果还不行我也不清楚了。
我自己用着很正常。

**Comment by SunYu2004** [comment]
Linux下直接安装同样的问题。

**Comment by YoshiPark** [comment]
![hdchina失败截图](https://user-images.githubusercontent.com/20967749/209786554-c91c5cbf-c5b1-467c-b61d-b6d9cd9eb42c.png)
目前2.7.3版本，浏览器仿真测试显示的是网络错误，请问一下对排查有没有帮助？

**Comment by YoshiPark** [comment]
好像问题已经找到了，我之前在环境设置了HTTP_PROXY和ALL_PROXY两个参数，导致出现网络错误，在去除掉这两个参数之后，也能正常访问了，应该就是这两个代理导致的
