### ISSUE TITLE
电脑浏览器浏览时页面出现bug

### ISSUE THREAD

**Issue by Arly521** [jxxghp/nas-tools#232]
![image](https://user-images.githubusercontent.com/92666924/171974288-db472d44-396e-49c5-89f7-0cefbe426576.png)
左边的菜单会挡住部分内容。应该是UI的bug

**Comment by sungamma** [comment]
屏幕宽度不够时出现这种情况

**Comment by jxxghp** [comment]
最新的代码缩小了对屏幕宽度的要求，看下还会不会了。

**Comment by jxxghp** [comment]
v1.3.6解决了。
