### ISSUE TITLE
设置了删种条件不自动删种瓷器刷流获取不到种子

### ISSUE THREAD

**Issue by Mikcoono1** [jxxghp/nas-tools#2320]
> NAStool 版本: 2.6.0
> 环境: docker
删种策略 ＞1小时  [平均上传速度＜200k
刷流策略 种子发布时间 ＜1小时 做种人数＜2人
种子大小＜150G
HDChina 刷流获取不到符合要求的新种
同样的策略使用到其他站点无问题

![11](https://user-images.githubusercontent.com/119794060/205492010-aac5c43d-824c-4db7-8619-39f24edae7c0.png)
![333](https://user-images.githubusercontent.com/119794060/205492014-d6b809f2-c236-4989-95a4-6c5834f842a8.png)
![444](https://user-images.githubusercontent.com/119794060/205492017-3f354e88-80b0-469b-a9fb-5835868d3e3a.png)

**Comment by jxxghp** [comment]
磁器好像是有问题，等我哪一天有账号了再调试下。
或者有账号的同学帮忙调试。

**Comment by jxxghp** [comment]
#2370
