### ISSUE TITLE
关于做种数优先的一个特例

### ISSUE THREAD

**Issue by xushier** [jxxghp/nas-tools#2321]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
种子刚发布时，做种人数是1，正在下载人数很多。如果匹配到这类种子应该是要优先下载的，不知道软件内置的 按做种数优先 规则是把这类种子排最高优先级还是最低优先级呢？

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by cikezhu** [comment]
这类种子不利于你尽快的获取想要的资源 下载会比较慢 比较考验发布者的带宽
如果是为了刷流 可以用刷流功能吧

**Comment by Shurelol** [comment]
要刷流就用刷流，刷流有选种规则

正常下载资源，此类种子不存在特殊性
