### ISSUE TITLE
媒体整理手动识别/转移目录后，手动识别记录未消除

### ISSUE THREAD

**Issue by lkz134800** [jxxghp/nas-tools#2323]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.1
>
> 环境: docker 
## 你想要新增或者改进什么功能？
功能已经非常强大，感谢作者。在媒体整理里面手动识别或者通过文件管理，转移目录之后，手动识别记录仍然未消除，如果手动选择后删除记录，那么对于几十集的电视剧来说属实有些麻烦，只能一个一个选择，要么就是全选，有点抓狂。

> 你想要新增或者改进什么功能？
建议正确识别或者转移后，消除相应的手动识别记录，或者对于多选增加更为快捷的方法。一点小建议，再次感谢！

**Comment by jxxghp** [comment]
在手动识别里操作记录是会删除的吧？只是文件管理转移不删除？

**Comment by Shurelol** [comment]
并非未消除，而是页面没刷新，已经修改确认后自动刷新页面

**Comment by lkz134800** [comment]
非常感谢！
