### ISSUE TITLE
jellyfin10.8以上版本填入API KEY一直测试连接不成功

### ISSUE THREAD

**Issue by tongrali** [jxxghp/nas-tools#2325]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.6.1
>
> 环境: Synology
>

## 你遇到什么问题了？

>使用jellyfin做媒体库，jellyfin10.7.7版本填入API KEY可以测试连接成功，jellyfin10.8以上版本填入API KEY一直测试连接不成功，是不是jellyfin升级后，修改了API KEY的规则？还是NAS-TOOLS的没有匹配jellyfin10.8以上版本的API KEY？

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 没有找到解决方案

## 你期望的结果

> 希望能在jellyfin10.8以上版本配合使用。谢谢！

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![1670201087221](https://user-images.githubusercontent.com/57612301/205526486-6960d869-041c-43a2-aada-40068c3a21df.png)

**Comment by cikezhu** [comment]
重启下nas-tools试试  我这边测试正常

**Comment by tongrali** [comment]
> 重启下nas-tools试试 我这边测试正常
重启是停用再启用吗？我试过了，还是不行，是哪里有问题吗？帮我分析一下，谢谢了。
![1670207352813](https://user-images.githubusercontent.com/57612301/205536372-52dbb1b7-90c6-4b23-a689-020a8430362e.png)

**Comment by cikezhu** [comment]
> > 重启下nas-tools试试 我这边测试正常
> > 重启是停用再启用吗？我试过了，还是不行，是哪里有问题吗？帮我分析一下，谢谢了。
> > ![1670207352813](https://user-images.githubusercontent.com/57612301/205536372-52dbb1b7-90c6-4b23-a689-020a8430362e.png)

我这边测试的是jellyfin 10.8.6     测试连接成功

你先看看ip  / 端口  / apikey是否都正常

**Comment by tongrali** [comment]
> 

我安装的是nyanmisaka-jellyfin1，也是10.8.6，是我jellyfin配置问题会影响API KEY的生成吗？端口、IP应该都没问题

**Comment by cikezhu** [comment]
> > 
> 
> 我安装的是nyanmisaka-jellyfin1，也是10.8.6，是我jellyfin配置问题会影响API KEY的生成吗？端口、IP应该都没问题

再次测试确实存在问题

`            res = RequestUtils().get_res(req_url)
            if res:
                return res.json()
            else:
                log.error(f"【{self.server_type}】Items/Counts 未获取到返回数据")
                return {}`
这里报错 未获取倒返回数据 具体原因暂时未知

**Comment by cikezhu** [comment]
> > 
> 
> 我安装的是nyanmisaka-jellyfin1，也是10.8.6，是我jellyfin配置问题会影响API KEY的生成吗？端口、IP应该都没问题

测试, 需要先按确定  然后等一会儿  再次打开jellyfin设置测试  测试成功

**Comment by cikezhu** [comment]
> > 
> 
> 我这儿还是不行，帮我看看日志，谢谢了。 13:16:52 ERROR - 【Jellyfin】Items/Counts 未获取到返回数据 13:16:52 ERROR - 【Jellyfin】Users 未获取到返回数据 13:16:52 ERROR - 【Jellyfin】System/ActivityLog/Entries 未获取到返回数据 ![1670217241095](https://user-images.githubusercontent.com/57612301/205555295-e0a189ee-c0ea-4a7e-884c-878c3e77e017.png)

我已经看过代码了, 确实存在bug, 在进行测试连通性的时候, 输入的内容并没有正确的被传递到测试环节.
这边建议你的暂时处理方法是 ,确保你的设置完全正确, 直接确定!  然后保险起见, 建议重启nas-tools, 之后再打开测试连通性, 应该是正常的了

**Comment by tongrali** [comment]
> 我已经看过代码了, 确实存在bug, 在进行测试连通性的时候, 输入的内容并没有正确的被传递到测试环节. 这边建议你的暂时处理方法是 ,确保你的设置完全正确, 直接确定! 然后保险起见, 建议重启nas-tools, 之后再打开测试连通性, 应该是正常的了

我把nas-tools手动停用了，NAS重启，再启动nas-tools，进入设置，还是不行，问题依旧。

**Comment by cikezhu** [comment]
> > 我已经看过代码了, 确实存在bug, 在进行测试连通性的时候, 输入的内容并没有正确的被传递到测试环节. 这边建议你的暂时处理方法是 ,确保你的设置完全正确, 直接确定! 然后保险起见, 建议重启nas-tools, 之后再打开测试连通性, 应该是正常的了
> 
> 我把nas-tools手动停用了，NAS重启，再启动nas-tools，进入设置，还是不行，问题依旧。

是用的jellyfin镜像跟你是一样的 测试结果如下, 已知代码层面只会获取已经保存的配置进行测试 如果还是不行的话 你的问题可能不在这里
![image](https://user-images.githubusercontent.com/29982056/205557326-906b6325-bc2b-4088-9c56-ed0a9677d82c.png)

**Comment by tongrali** [comment]
> 

试过了所有的办法，我是不是把所有的都删除重新安装一遍？昨天删过了，再安装 也是这问题，安装10.7.7就没问题，怎么能把jellyfin、nas-tools彻底删除？

**Comment by tongrali** [comment]
> > > 我已经看过代码了, 确实存在bug, 在进行测试连通性的时候, 输入的内容并没有正确的被传递到测试环节. 这边建议你的暂时处理方法是 ,确保你的设置完全正确, 直接确定! 然后保险起见, 建议重启nas-tools, 之后再打开测试连通性, 应该是正常的了
> > 
> > 
> > 我把nas-tools手动停用了，NAS重启，再启动nas-tools，进入设置，还是不行，问题依旧。
> 


我设置EMBY就能正常，就是jellyfin10.8.6版本不行。

**Comment by cikezhu** [comment]
> 估计是新版本兼容问题

作者大大,  所有测试连通性的代码 在调用了 `__update_config` 方法之后 输入的测试参数就丢失了
这个修改起来涉及的文件过多, 您有空看看~

**Comment by tongrali** [comment]
> > 估计是新版本兼容问题
> 
> 作者大大, 所有测试连通性的代码 在调用了 `__update_config` 方法之后 输入的测试参数就丢失了 这个修改起来涉及的文件过多, 您有空看看~

作者大大不知道能不能看到啊

**Comment by boweic** [comment]
同样问题，emby版本：4.7.10.0 nastool版本：2.6.2
会出现emby链接不上的问题，重启后能连上，过一会又断开
2022-12-06 14:29:20,038	ERROR: 【Emby】Items/Counts 未获取到返回数据
2022-12-06 14:29:20,042	ERROR: 【Emby】Users/Query 未获取到返回数据
2022-12-06 14:29:20,045	ERROR: 【Emby】System/ActivityLog/Entries 未获取到返回数据
2022-12-06 14:29:24,394	INFO: 【Sync】读取到监控目录：/downloads/anime，目的目录：/media/anime，转移方式：Rclone复制
2022-12-06 14:29:24,396	INFO: 【Sync】/downloads/anime 不进行监控和同步：手动关闭
2022-12-06 14:29:24,397	INFO: 【Sync】读取到监控目录：/downloads/movie，目的目录：/media/movie，转移方式：Rclone复制
2022-12-06 14:29:24,397	INFO: 【Sync】/downloads/movie 不进行监控和同步：手动关闭
2022-12-06 14:29:24,398	INFO: 【Sync】读取到监控目录：/downloads/tv，目的目录：/media/tv，转移方式：Rclone复制
2022-12-06 14:29:24,398	INFO: 【Sync】/downloads/tv 不进行监控和同步：手动关闭
Scheduler is not running
Scheduler is not running
2022-12-06 14:29:24,448	ERROR: 【Emby】Library/SelectableMediaFolders 未获取到返回数据
2022-12-06 14:29:24,452	ERROR: 【Emby】Users 未获取到返回数据

**Comment by cikezhu** [comment]
> 同样问题，emby版本：4.7.10.0 nastool版本：2.6.2 会出现emby链接不上的问题，重启后能连上，过一会又断开 2022-12-06 14:29:20,038 ERROR: 【Emby】Items/Counts 未获取到返回数据 2022-12-06 14:29:20,042 ERROR: 【Emby】Users/Query 未获取到返回数据 2022-12-06 14:29:20,045 ERROR: 【Emby】System/ActivityLog/Entries 未获取到返回数据 2022-12-06 14:29:24,394 INFO: 【Sync】读取到监控目录：/downloads/anime，目的目录：/media/anime，转移方式：Rclone复制 2022-12-06 14:29:24,396 INFO: 【Sync】/downloads/anime 不进行监控和同步：手动关闭 2022-12-06 14:29:24,397 INFO: 【Sync】读取到监控目录：/downloads/movie，目的目录：/media/movie，转移方式：Rclone复制 2022-12-06 14:29:24,397 INFO: 【Sync】/downloads/movie 不进行监控和同步：手动关闭 2022-12-06 14:29:24,398 INFO: 【Sync】读取到监控目录：/downloads/tv，目的目录：/media/tv，转移方式：Rclone复制 2022-12-06 14:29:24,398 INFO: 【Sync】/downloads/tv 不进行监控和同步：手动关闭 Scheduler is not running Scheduler is not running 2022-12-06 14:29:24,448 ERROR: 【Emby】Library/SelectableMediaFolders 未获取到返回数据 2022-12-06 14:29:24,452 ERROR: 【Emby】Users 未获取到返回数据

正常保存配置成功后不应该会出现断连的问题

**Comment by burncode** [comment]
NAStool 版本: 2.6.2  
环境: unraid docker
媒体服务器: jellyfin  v10.8.8
描述： 我刚开始也是一直无法测试成功，老是链接失败，手动调用jellyfin的api试了下没有任何问题。
解决： 原来我nastool 和 jellyfin两个docker容器的网段不通导致的。。nastool使用的桥接，jellyfin用的bond。  切换网络后完美链接。 没有任何问题
@tongrali  你可以参考下 看是不是我的这个问题

**Comment by tongrali** [comment]
> NAStool 版本: 2.6.2 环境: unraid docker 媒体服务器: jellyfin v10.8.8 描述： 我刚开始也是一直无法测试成功，老是链接失败，手动调用jellyfin的api试了下没有任何问题。 解决： 原来我nastool 和 jellyfin两个docker容器的网段不通导致的。。nastool使用的桥接，jellyfin用的bond。 切换网络后完美链接。 没有任何问题 @tongrali 你可以参考下 看是不是我的这个问题

我的还是不行，我都是用的桥接方式：
17:09:00 ERROR - 【Jellyfin】Users 未获取到返回数据
17:09:00 INFO - 站点自动签到服务启动
17:09:00 INFO - 下载文件转移服务启动
17:09:00 INFO - RSS订阅服务启动
17:09:00 INFO - 豆瓣同步服务启动
17:09:00 INFO - /media/video/movie 的监控服务启动
17:09:00 INFO - /media/video/tv 的监控服务启动
17:09:00 INFO - /media/video/dongman 的监控服务启动
17:09:00 ERROR - 【Jellyfin】Items/Counts 未获取到返回数据
17:09:01 ERROR - 【Jellyfin】Items/Counts 未获取到返回数据
17:09:01 ERROR - 【Jellyfin】Items/Counts 未获取到返回数据
17:09:01 ERROR - 【Jellyfin】Items/Counts 未获取到返回数据
17:09:01 ERROR - 【Jellyfin】Items/Counts 未获取到返回数据
17:09:02 ERROR - 【Jellyfin】Items/Counts 未获取到返回数据
17:09:02 ERROR - 【Jellyfin】Items/Counts 未获取到返回数据

**Comment by burncode** [comment]
> > NAStool 版本: 2.6.2 环境: unraid docker 媒体服务器: jellyfin v10.8.8 描述： 我刚开始也是一直无法测试成功，老是链接失败，手动调用jellyfin的api试了下没有任何问题。 解决： 原来我nastool 和 jellyfin两个docker容器的网段不通导致的。。nastool使用的桥接，jellyfin用的bond。 切换网络后完美链接。 没有任何问题 @tongrali 你可以参考下 看是不是我的这个问题
> 
> 我的还是不行，我都是用的桥接方式： 17:09:00 ERROR - 【Jellyfin】Users 未获取到返回数据 17:09:00 INFO - 站点自动签到服务启动 17:09:00 INFO - 下载文件转移服务启动 17:09:00 INFO - RSS订阅服务启动 17:09:00 INFO - 豆瓣同步服务启动 17:09:00 INFO - /media/video/movie 的监控服务启动 17:09:00 INFO - /media/video/tv 的监控服务启动 17:09:00 INFO - /media/video/dongman 的监控服务启动 17:09:00 ERROR - 【Jellyfin】Items/Counts 未获取到返回数据 17:09:01 ERROR - 【Jellyfin】Items/Counts 未获取到返回数据 17:09:01 ERROR - 【Jellyfin】Items/Counts 未获取到返回数据 17:09:01 ERROR - 【Jellyfin】Items/Counts 未获取到返回数据 17:09:01 ERROR - 【Jellyfin】Items/Counts 未获取到返回数据 17:09:02 ERROR - 【Jellyfin】Items/Counts 未获取到返回数据 17:09:02 ERROR - 【Jellyfin】Items/Counts 未获取到返回数据

你直接在nastools的容器环境 curl   jellyfin的api  你试下是不是通的 或者说有没有返回信息

**Comment by jxxghp** [comment]
测试联通性确实是有问题，在这个问题里跟进吧： #2365
