### ISSUE TITLE
建议 允许给“动漫”“电影”“电视剧”分别设置不同的默认过滤规则，在资源搜索一栏增加过滤规则切换选项

### ISSUE THREAD

**Issue by Hsia97** [jxxghp/nas-tools#2329]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.6.1
> 环境: docker or windows or synology
windows
## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
既然能自动区分资源是“动漫”“电影”还是“电视剧”并自动下载到对应目录，那么为什么不能给“动漫”“电影”“电视剧”分别设置不同的默认过滤规则呢？比如电影我喜欢remux而动漫电视剧又看webdl就够了，能分别设置默认规则的话我觉得应该增加工具的易用性，
同时资源搜索也是用的同一个默认规则，手动搜索remux电影和webdl动漫时要回到设置界面切默认过滤规则感觉很麻烦，若能在资源搜索一栏增加过滤规则切换选项就好了
我是站在比较小白的角度想的，希望意见有用
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
#1199
