### ISSUE TITLE
登陆异常

### ISSUE THREAD

**Issue by log-time** [jxxghp/nas-tools#233]
跟大佬反馈个奇怪的情况，最近3个版本，nastool重启后，公网登陆卡登陆界面，无限转圈，log无异常。尝试了内网可正常登陆，无异常。
不作任何修改，公网大概过了半小时左右即可正常登陆。
同样的配置，之前的版本无异常。

https://user-images.githubusercontent.com/66826612/171977133-afd522cd-30f3-4668-93e5-d29570714776.mp4

**Comment by log-time** [comment]
![Screenshot_2022-06-04-11-03-47-726_com android chrome](https://user-images.githubusercontent.com/66826612/171977391-65e2dd4e-55d5-4eac-bb94-044d4f9af6d6.jpg)
这个是本次重启后的log，除了2个站点连接错误，无任何报错

**Comment by log-time** [comment]
![Screenshot_2022-06-04-11-17-56-656_com mixplorer silver](https://user-images.githubusercontent.com/66826612/171978430-7e065ca1-4fd7-4c96-8b25-915309770b9c.jpg)
最近一次重启的log

**Comment by log-time** [comment]
另外，站点数据方面，北洋园的数据仍然异常。

**Comment by jxxghp** [comment]
我这边也是公网访问，没有类似问题哦。
北洋园没 有账号，不太好测试。

**Comment by log-time** [comment]
我试试删除全部镜像重新部署

**Comment by log-time** [comment]
删除全部镜像，全新部署后问题解决。

**Comment by log-time** [comment]
升级重启后问题问题再次出现。很奇怪

**Comment by a872675986** [comment]
我也是这样套件版的 就是每次过一段时间就会自动退出 然后链接无法访问  必须重启套件才能打开链接

**Comment by log-time** [comment]
puid使用0登陆后，似乎又正常了。我再观察一段时间。

**Comment by log-time** [comment]
新版本似乎又没问题了，继续观察一段时间

**Comment by log-time** [comment]
确实不行，升级后第一次正常，再重启又恢复老样子

**Comment by log-time** [comment]
该故障可以重现，在我的设备上，连续两次重启后，再次登陆web页面，chrome浏览器必然卡住。最新版本似乎仍存在该问题。

**Comment by jxxghp** [comment]
我这边不会哦，看下有没有同样问题的

**Comment by log-time** [comment]
https://user-images.githubusercontent.com/66826612/174744011-26728428-5405-46be-9242-5fabbc78ce3b.mp4

最新版本问题依然存在，接近2周的观察，目前这个问题似乎，只发生在chrome内核的浏览器上，firefox就是正常的。

**Comment by jxxghp** [comment]
这个是后台重启后没刷新浏览器，在原来的框架上点了菜单吧

**Comment by log-time** [comment]
并不是，重启后，登陆框输入账号、密码后就卡在这了。大概半小时后自动恢复正常。

**Comment by jxxghp** [comment]
> 并不是，重启后，登陆框输入账号、密码后就卡在这了。大概半小时后自动恢复正常。
> 
> 登陆页面什么的都是正常的，输入账号和密码后就会卡住，刷新浏览器也没有效果。但是这个问题却不会发生在firefox浏览器上。

你这个好奇怪，没遇到到。

**Comment by log-time** [comment]
每次发生这个bug的时候，登陆状态都必然丢失，原来的cookie失效，必须重新输入账号密码才能登陆。如果不发生bug，登陆状态一般是保留的。很奇怪

**Comment by log-time** [comment]
https://user-images.githubusercontent.com/66826612/175969764-ab95eda8-b760-4746-8e8c-d5dd225786c9.mp4

**Comment by log-time** [comment]
https://user-images.githubusercontent.com/66826612/176411989-c447793e-3e4c-44de-a74b-c83ffe445484.mp4
