### ISSUE TITLE
内建搜索支持验证cookie有效性

### ISSUE THREAD

**Issue by traceur** [jxxghp/nas-tools#2331]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 
>V 2.6.1
> 环境: docker

## 你想要新增或者改进什么功能？

> 内建搜索支持验证站点下cookie有效性

## 这个功能有什么可以参考的资料吗？

> 搜索发现某站点搜索不到资源，查询后发现是cookie失效了，需求：校验站点下cookie有效性的检查。

**Comment by jxxghp** [comment]
站点维护里不是有个站点测试功能吗？
