### ISSUE TITLE
二次资源搜索疑似存在bug

### ISSUE THREAD

**Issue by Jungle-Leesin** [jxxghp/nas-tools#2338]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.2 4734e007
>
> 环境: docker
>

## 你遇到什么问题了？

> 在一次使用资源搜索(“冰雨火”电视剧)后，无法继续使用搜索功能，日志上有报错显示，经过重启docker以及重启物理机器，均无法解决这个问题，仍然存在无法使用搜索功能搜索其他资源，但是尝试搜索“冰雨火”，却可也，仅且能搜索这一个资源。(特殊说明：第一次搜索“冰雨火”时，我不确定是否使用过高级搜索)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 暂未发现相关问题的解决和讨论

## 你期望的结果

> 请确认是否为程序的bug

## 给出程序界面截图、后台运行日志或配置文件

> UI为停住不动的状态
> 当搜索“冰雨火”时候，资源显示正常
![image](https://user-images.githubusercontent.com/62128074/205647971-c5e869e6-ebf4-4519-a0a9-705c3d92fdec.png)
> 当搜索其他任意资源时候，后台显示报错
![image](https://user-images.githubusercontent.com/62128074/205648232-51d808d6-f5a4-45e2-8b2b-c67810737085.png)

**Comment by Shurelol** [comment]
修改了二级分类的default-category.yaml？
改坏了，参考项目里的改回来

**Comment by Jungle-Leesin** [comment]
> 修改了二级分类的default-category.yaml？ 改坏了，参考项目里的改回来

查看了一下，的确是，有个符号是中文的，感谢！
