### ISSUE TITLE
站点管理-站点维护-自动更新站点Cookie的功能缺陷

### ISSUE THREAD

**Issue by xnoods** [jxxghp/nas-tools#2339]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.2 4734e007
>
> 环境: docker  Synology
>

## 你遇到什么问题了？

> 站点管理-站点维护-自动更新站点Cookie的功能中发现有个bug，因为我有很多pt站点，我发现我在第一个站点输入账号和密码后再去点第二个站点进行账号密码输入时，惊奇的发现点开的对话框中竟然是第一个站点的账号和密码（貌似数据串到一起了）

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果：建议设置一个单独的保存按钮（针对单个站点账号密码的保存按钮以及定期更新cookie的按钮就十分完美了）

## 给出程序界面截图、后台运行日志或配置文件

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/18209713/205648899-5083cdd0-5a44-417b-963c-c792d1e7c74f.png">

**Comment by wyyqyl** [comment]
目测是浏览器或者插件自动填充的密码 和nastools无关

**Comment by Shurelol** [comment]
浏览器的自动填充，和nstool没关系
