### ISSUE TITLE
资源搜索过滤条件的设置

### ISSUE THREAD

**Issue by sungamma** [jxxghp/nas-tools#234]
### 版本1.3.5
在网页内直接搜索“大雄的月球探险记”,发现搜索结果不全，查看了日志，过滤了几个搜索结果，但是不知道这个过滤是根据什么规则过滤的。

如果是根据站点的规则过滤，那么有两个矛盾：

1. 搜索结果是22G，我限制的是20G
2. 丢失了一个“Doraemon the Movie Nobita‘s Chronicle of the Moon Exploration 2019 1080p BluRay x264 DTS-WiKi ”，大小：9.16 GB
![image](https://user-images.githubusercontent.com/33790/171983120-2b43133e-efa2-431b-aea5-30108fc79012.png)

### 截图如下：
![image](https://user-images.githubusercontent.com/33790/171982708-27b01f1f-2008-41dc-85cb-68cc31b8c147.png)
![image](https://user-images.githubusercontent.com/33790/171983105-78d57191-9c9a-4298-b89e-a2d14dd41876.png)
![image](https://user-images.githubusercontent.com/33790/171982724-559d0d57-318d-43a7-b8bb-00cb5093226e.png)

### 日志如下：
> 11:32:38 INFO - 【RUN】/volume1/movie/QB 的监控服务启动...
11:38:34 INFO - 【META】正在识别电影：大雄的月球探险记, 年份= ...
11:38:35 INFO - >电影ID：575222, 电影名称：哆啦A梦：大雄的月球探险记, 上映日期：2019-03-01
11:38:37 INFO - 【WEB】开始检索 大雄的月球探险记 ...
11:38:37 INFO - 【JACKETT】开始并行检索 大雄的月球探险记，线程数：2
11:38:37 INFO - 【JACKETT】开始检索Indexer：hdchina ...
11:38:37 INFO - 【JACKETT】开始检索Indexer：mteamtp ...
11:38:41 WARN - 【JACKETT】hdchina 返回数据：5
11:38:41 INFO - 【META】正在识别电影：Doraemon the Movie Nobita's Chronicle of the Moon Exploration, 年份=2019 ...
11:38:42 WARN - 【META】Doraemon the Movie Nobita's Chronicle of the Moon Exploration 未找到媒体信息!
11:38:42 WARN - 【META】Doraemon the Movie Nobita's Chronicle of the Moon Exploration 未匹配到媒体信息!
11:38:42 INFO - 【META】正在识别电视剧：Doraemon the Movie Nobita's Chronicle of the Moon Exploration, 年份=2019 ...
11:38:43 WARN - 【META】Doraemon the Movie Nobita's Chronicle of the Moon Exploration 未找到媒体信息!
11:38:43 WARN - 【META】Doraemon the Movie Nobita's Chronicle of the Moon Exploration 未匹配到媒体信息!
11:38:43 INFO - 【META】正在识别电视剧：Doraemon the Movie Nobita's Chronicle of the Moon Exploration, 年份= ...
11:38:44 WARN - 【META】Doraemon the Movie Nobita's Chronicle of the Moon Exploration 未找到媒体信息!
11:38:44 WARN - 【META】Doraemon the Movie Nobita's Chronicle of the Moon Exploration 未匹配到媒体信息!
11:38:44 INFO - 【META】正在识别电影：Doraemon the Movie Nobita's Chronicle of the Moon Exploration, 年份= ...
11:38:46 WARN - 【META】Doraemon the Movie Nobita's Chronicle of the Moon Exploration 未找到媒体信息!
11:38:46 WARN - 【META】Doraemon the Movie Nobita's Chronicle of the Moon Exploration 未匹配到媒体信息!
11:38:46 INFO - 【JACKETT】Doraemon the Movie Nobita's Chronicle of the Moon Exploration 2019 1080p BluRay x264 DTS-WiKi 未查询到媒体信息
11:38:46 INFO - 【JACKETT】Doraemon the Movie Nobita's Chronicle of the Moon Exploration 2019 720p BluRay x264-WiKi 未查询到媒体信息
11:38:46 INFO - 【JACKETT】Doraemon the Movie Nobita's Chronicle of the Moon Exploration 2019 WEB-DL 2160p H265 2DDP5 1-cfandora 未查询到媒体信息
11:38:46 INFO - 【JACKETT】Doraemon the Movie Nobita's Chronicle of the Moon Exploration 2019 1080p AVC DTS-HDMA 7 1-cfandora 未查询到媒体信息
11:38:46 INFO - 【JACKETT】hdchina 共检索到 1 条有效资源
11:38:47 WARN - 【JACKETT】mteamtp 返回数据：5
11:38:47 INFO - 【META】正在识别电影：Doraemon the Movie Nobita‘s Chronicle of the Moon Exploration, 年份=2019 ...
11:38:48 WARN - 【META】Doraemon the Movie Nobita‘s Chronicle of the Moon Exploration 未找到媒体信息!
11:38:48 WARN - 【META】Doraemon the Movie Nobita‘s Chronicle of the Moon Exploration 未匹配到媒体信息!
11:38:48 INFO - 【META】正在识别电视剧：Doraemon the Movie Nobita‘s Chronicle of the Moon Exploration, 年份=2019 ...
11:38:49 WARN - 【META】Doraemon the Movie Nobita‘s Chronicle of the Moon Exploration 未找到媒体信息!
11:38:49 WARN - 【META】Doraemon the Movie Nobita‘s Chronicle of the Moon Exploration 未匹配到媒体信息!
11:38:49 INFO - 【META】正在识别电视剧：Doraemon the Movie Nobita‘s Chronicle of the Moon Exploration, 年份= ...
11:38:51 WARN - 【META】Doraemon the Movie Nobita‘s Chronicle of the Moon Exploration 未找到媒体信息!
11:38:51 WARN - 【META】Doraemon the Movie Nobita‘s Chronicle of the Moon Exploration 未匹配到媒体信息!
11:38:51 INFO - 【META】正在识别电影：Doraemon the Movie Nobita‘s Chronicle of the Moon Exploration, 年份= ...
11:38:52 WARN - 【META】Doraemon the Movie Nobita‘s Chronicle of the Moon Exploration 未找到媒体信息!
11:38:52 WARN - 【META】Doraemon the Movie Nobita‘s Chronicle of the Moon Exploration 未匹配到媒体信息!
11:38:52 INFO - 【JACKETT】Doraemon the Movie Nobita‘s Chronicle of the Moon Exploration 2019 1080p BluRay x264 DTS-WiKi 未查询到媒体信息
11:38:52 INFO - 【JACKETT】Doraemon the Movie Nobita's Chronicle of the Moon Exploration 2019 720p BluRay x264-WiKi 未查询到媒体信息
11:38:52 INFO - 【JACKETT】Doraemon the Movie Nobita‘s Chronicle of the Moon Exploration 2019 BluRay 1080p AVC DTS-HD MA 7.1-cfandora 未查询到媒体信息
11:38:52 INFO - 【JACKETT】mteamtp 共检索到 2 条有效资源
11:38:52 INFO - 【JACKETT】所有API检索完成，有效资源数：3
11:38:52 INFO - 【WEB】共检索到 3 个有效资源
11:38:52 INFO - 【WEB】分组择优后剩余 3 个有效资源
12:02:38 INFO - 【RSS】开始RSS订阅...

**Comment by log-time** [comment]
web页面搜索，按大佬的话说，应该是不过滤的[#228](https://github.com/jxxghp/nas-tools/issues/228)

**Comment by sungamma** [comment]
补充一下jackett的搜索结果。如果没有过滤应该显示10条结果啊
![image](https://user-images.githubusercontent.com/33790/171986005-6de21588-11fa-4f39-9892-8bb8a7cef26b.png)

**Comment by sungamma** [comment]
研究了代码，大概知道是怎么回事了。对于一些动漫电影往往名字上会有the movie，NASTOOLS在搜索后，会比对tmdb，由于名称上由the movie，导致tmdb搜索不到，从而判断不符合要求，然后就过滤掉了。
