### ISSUE TITLE
Nastool Synology 版本无法登录后台，显示浏览器不能连接到服务器

### ISSUE THREAD

**Issue by michaelwu911259** [jxxghp/nas-tools#2347]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.6.1
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> 描述一下你遇到的问题

配置完之后当天还可以使用，第二天起床不能登录后台，用safari和chrome都不可以，显示如下：

<img width="1569" alt="截屏2022-12-06 14 01 47" src="https://user-images.githubusercontent.com/119918480/205832376-bdb84576-7d19-4d5b-ba2c-c8e80ea0ac42.png">

<img width="1379" alt="截屏2022-12-06 14 02 03" src="https://user-images.githubusercontent.com/119918480/205832489-f4199562-8af2-456c-9890-bfd3d4a290f2.png">

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

希望可以找到解决的方案，成功登陆后台。

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
没日志，无法分析
