### ISSUE TITLE
媒体集数识别建议

### ISSUE THREAD

**Issue by HughYo** [jxxghp/nas-tools#235]
媒体识别集数时候，建议增加全角数字的识别，或者增加单集识别失败的手动识别

举个栗子：我有一季日剧，其中集数的名称有部分是全角数字，因为需要保种的原因无法修改源文件，但是自动识别又可以识别部分集数，导致其他识别失败的集数无法导入。

**Comment by jxxghp** [comment]
贴一下文件名

**Comment by HughYo** [comment]
> 

自动识别成功的："美しい彼　第３話【萩原利久・八木勇征ダブル主演★ドラマ特区】[字]_2021-12-03_JPTVclub.ts"
其他失败的："美しい彼　第４話【萩原利久・八木勇征ダブル主演★ドラマ特区】[字]_2021-12-10_JPTVclub.ts" "美しい彼　最終話【萩原利久・八木勇征ダブル主演★ドラマ特区】[終][字]_2021-12-24_JPTVclub.ts"

**Comment by jxxghp** [comment]
这类命名都极其不规范，不是增加全角就能解决的，玩动漫的话找一个规范点的站吧。
命名识别是个大坑，实在无能为力。

**Comment by HughYo** [comment]
> 这类命名都极其不规范，不是增加全角就能解决的，玩动漫的话找一个规范点的站吧。 命名识别是个大坑，实在无能为力。

有些动漫比较冷门，站里不一定有，所以想建议下有没有可能增加单集识别失败时候的手动识别呢，可以选择自己调整
