### ISSUE TITLE
外站TorrentLeechorg无法登陆，用油猴插件导入cookies也无法使用。

### ISSUE THREAD

**Issue by serenity666** [jxxghp/nas-tools#2353]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 在置顶帖里提了，没有回复。手动更新cookies提示找不到登陆按钮，用油猴插件导入cookies后，用站点测试提示cookies无效。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 当然是适配好咯，也算个比较大的外站了。再次感谢作者及各位大佬的辛勤付出！

## 给出程序界面截图、后台运行日志或配置文件

>

**Comment by jxxghp** [comment]
已支持
