### ISSUE TITLE
docker 运行出现僵尸进程

### ISSUE THREAD

**Issue by songjianxing** [jxxghp/nas-tools#2356]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.2 9dbc3f67
>
> 环境: docker
>

## 你遇到什么问题了？

> 
docker 运行最新版本 nastool 出现僵尸进程 通过配置 docker --init 参数 仍无法解决 不能进行 kill. kill父进程会导致nastool重启
应该是下面 node 导致的 
![image](https://user-images.githubusercontent.com/18136439/206072035-1d2dd3f6-4422-4dbf-ace0-7faca61ac192.png)
![image](https://user-images.githubusercontent.com/18136439/206071907-86e7edd0-6c16-4506-a62e-975af8dfe781.png)

## 你期望的结果
> 解决僵尸进程问题 

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/18136439/206072035-1d2dd3f6-4422-4dbf-ace0-7faca61ac192.png)
![image](https://user-images.githubusercontent.com/18136439/206071907-86e7edd0-6c16-4506-a62e-975af8dfe781.png)

**Comment by jxxghp** [comment]
确实也发现了这个问题，原因未知

**Comment by jxxghp** [comment]
用2.6.3版本貌似没出现了，可以试试。2.6.3内存占用也下降了90%。

**Comment by songjianxing** [comment]
> 用2.6.3版本貌似没出现了，可以试试。 2.6.3内存占用也下降了90%。
> 经过测试发现僵尸进程依然存在 
> 这里僵尸进程 比较多的原因是我未设置 --init, 
> 上次是与 node 相关 这次与chrome相关
![image](https://user-images.githubusercontent.com/18136439/206344647-87b6692b-83f6-4276-aa75-d69d41b3cff6.png)
![image](https://user-images.githubusercontent.com/18136439/206344881-d705a88f-8419-4960-8b8d-045cd943c734.png)
