### ISSUE TITLE
订阅质量选项里没有DV或DoVi选项

### ISSUE THREAD

**Issue by git-0101** [jxxghp/nas-tools#2359]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 
![Screenshot_20221207_113512](https://user-images.githubusercontent.com/115487446/206084286-b91c6617-e8b3-4dd5-b819-e66ffae234c1.jpg)
能够增加DV选项。下面是HDR的。
![Screenshot_20221207_113341_com microsoft emmx_edit_344625180764601](https://user-images.githubusercontent.com/115487446/206084715-40ca12a0-2e4f-4b42-9ec6-78c95f2a7eeb.jpg)

## 这个功能有什么可以参考的资料吗？

> 无

**Comment by jxxghp** [comment]
给点名称参考，光提要求不行

**Comment by git-0101** [comment]
> 给点名称参考，光提要求不行

![Screenshot_20221207_180100](https://user-images.githubusercontent.com/115487446/206148436-143a1b22-f6fc-4538-b53b-3ef562884e8c.jpg)
![Screenshot_20221207_175943](https://user-images.githubusercontent.com/115487446/206148446-05eb552e-70c3-47d5-9587-b0eb3540c87d.jpg)
好的，大佬！基本主副标题就这两种情况，都是杜比视界。Dolby Vision，DV这两个感觉选一个可以。

**Comment by git-0101** [comment]
DoVi已经可以匹配到了！
DV还是匹配不到，应该还需要加一个|DV。
![Screenshot_20221211_224144_edit_596739018298007](https://user-images.githubusercontent.com/115487446/206911101-b85f688d-7cce-4965-bdd6-8e053eb1e5ea.jpg)
![Screenshot_20221211_225543](https://user-images.githubusercontent.com/115487446/206911108-c0226e29-836f-4974-bcc4-655e6ba8ef65.jpg)

**Comment by jxxghp** [comment]
dbbe3ada925cdc6a56dc28d142e72a08336433ff
