### ISSUE TITLE
瓷器

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#2370]
转别人回复：

试着分析了一下
非免费的种子在刷流任务里面可以正常添加下载；
免费种子无法正常识别出免费状态，看代码运行结果，是xpath匹配免费img元素的时候没匹配成功。
但是在chrome里面用nt配置里面写的xpath字符串又能正常匹配到，就很奇怪。。

**Comment by Tartarus2014** [comment]
> 转别人回复：
> 
> 试着分析了一下 非免费的种子在刷流任务里面可以正常添加下载； 免费种子无法正常识别出免费状态，看代码运行结果，是xpath匹配免费img元素的时候没匹配成功。 但是在chrome里面用nt配置里面写的xpath字符串又能正常匹配到，就很奇怪。。

经过分析，发现是瓷器的promotion信息是通过后续发起二次访问再获取的：
https://hdchina.org/ajax_promotion.php

应该可参考vertex的方式来实现：

const _freeHDChina = async function (url, cookie) {
  const d = await getDocument(url, cookie);
  if (d.body.innerHTML.indexOf('userdetails') === -1) {
    throw new Error('疑似登录状态失效, 请检查 Cookie');
  }
  const tid = url.match(/id=(\d*)/)[1];
  const csrf = d.querySelector('meta[name=x-csrf]').content;
  const promotion = await util.requestPromise({
    url: 'https://hdchina.org/ajax_promotion.php',
    method: 'POST',
    headers: {
      cookie
    },
    formData: {
      'ids[]': tid,
      csrf
    },
    json: true
  });
  return promotion.body.message[tid].sp_state.indexOf('pro_free') !== -1 || promotion.body.message[tid].sp_state.indexOf('pro_twoupfree') !== -1;
};

**Comment by Tartarus2014** [comment]
> 转别人回复：
> 
> 试着分析了一下 非免费的种子在刷流任务里面可以正常添加下载； 免费种子无法正常识别出免费状态，看代码运行结果，是xpath匹配免费img元素的时候没匹配成功。 但是在chrome里面用nt配置里面写的xpath字符串又能正常匹配到，就很奇怪。。

经过分析，发现是瓷器的promotion信息是通过后续发起二次访问再获取的：
https://hdchina.org/ajax_promotion.php

应该可参考vertex的方式来实现：

const _freeHDChina = async function (url, cookie) {
  const d = await getDocument(url, cookie);
  if (d.body.innerHTML.indexOf('userdetails') === -1) {
    throw new Error('疑似登录状态失效, 请检查 Cookie');
  }
  const tid = url.match(/id=(\d*)/)[1];
  const csrf = d.querySelector('meta[name=x-csrf]').content;
  const promotion = await util.requestPromise({
    url: 'https://hdchina.org/ajax_promotion.php',
    method: 'POST',
    headers: {
      cookie
    },
    formData: {
      'ids[]': tid,
      csrf
    },
    json: true
  });
  return promotion.body.message[tid].sp_state.indexOf('pro_free') !== -1 || promotion.body.message[tid].sp_state.indexOf('pro_twoupfree') !== -1;
};

**Comment by orzcz** [comment]
@jxxghp 大佬什么时候把这个问题修一下啊

**Comment by jxxghp** [comment]
已支持
