### ISSUE TITLE
点击历史记录无反应

### ISSUE THREAD

**Issue by sungamma** [jxxghp/nas-tools#2371]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.3 2bc2cf08
>
> 环境: docker 
>

## 不能打开媒体整理里面的历史记录

>点击没反应，不转圈，就是一闪，然后界面还是之前的

**Comment by jxxghp** [comment]
一般是数据问题，没办复现的话不好查。
可以历史数据可以不要，服务——》备份然后再恢复，会清掉历史记录。

**Comment by sungamma** [comment]
这样备份恢复就解决问题了
