### ISSUE TITLE
刷流任务删种规则不生效

### ISSUE THREAD

**Issue by devojony** [jxxghp/nas-tools#2375]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.6.2
>
> 环境: docker 
>

## 你遇到什么问题了？

> 自动刷流任务没有按照删种规则删种

## 给出程序界面截图、后台运行日志或配置文件
我的配置是这样的
![SCR-20221207-tvm](https://user-images.githubusercontent.com/61173062/206192356-804bd9aa-9d33-4d8f-93d5-5fdbd6a1363d.png)
这个站现在的保种体积
![SCR-20221207-toh](https://user-images.githubusercontent.com/61173062/206192516-7b911032-283b-4420-ae22-640361568950.png)
设置了保种7天，但是有10几天的任务没有被删除
![SCR-20221207-tpe](https://user-images.githubusercontent.com/61173062/206192853-d3e9d9a2-4363-4c9d-b1df-9623a7fda159.png)
分享率已经达标，也没有删除
![SCR-20221207-tqi](https://user-images.githubusercontent.com/61173062/206193062-ad57623a-f684-4d09-91a2-e5ad4030d503.png)

想请问一下，这个刷流任务，该如何配置，这个三个条件是需要同时满足吗？

**Comment by Mikcoono1** [comment]
我也是同样的情况  V2.6.1 希望能尽早解决吧

**Comment by dinsen80951** [comment]
保种体积不起作用，到容量了仍下载刷流

**Comment by SilenceEagle** [comment]
刷流任务不自动删种+1，也是`docker`+`tr`
这个问题印象中是从`2.3` 还是 `2.4` 版本开始出现的。

**Comment by jxxghp** [comment]
调整了时间判断，如有问题再重新提吧
