### ISSUE TITLE
媒体库同步信息不正确

### ISSUE THREAD

**Issue by KITblue** [jxxghp/nas-tools#2377]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>V2.6.3
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？
媒体库信息同步后，在影视页面，显示的已下载标识有误。比如：我媒体库有 2005年的电影《世界之战》，当我浏览到2022年的电视剧《世界之战》时，会显示已下载标识。
> 信息同步后

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 希望用豆瓣ID或者IMDB、tmdb的编号识别媒体，退一步讲，至少要区分下电视剧和电影，以及年份信息（有的年份信息不准的可以放开到±1年）

## 给出程序界面截图、后台运行日志或配置文件

![1](https://user-images.githubusercontent.com/68754977/206195786-30872dff-8ae6-436a-8bc7-3ac18b950109.png)
![2](https://user-images.githubusercontent.com/68754977/206195806-3ed34fbc-cd6d-45b1-b1aa-befa3191f9f0.png)

**Comment by jxxghp** [comment]
这个问题不好解决，加上年份匹配后，豆瓣推荐里面的大多数都无法正确显示，特别是电视剧年份都不对

**Comment by jxxghp** [comment]
同名的毕竟少数先这样吧
