### ISSUE TITLE
点击字幕TAB切换无法切换

### ISSUE THREAD

**Issue by l123456789jy** [jxxghp/nas-tools#2379]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.3
>
> 环境: docker 
>

## 你遇到什么问题了？

> 点击字幕TAB切换无法切换，查看日志报以下错误

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的

## 你期望的结果

> 能正常切换

## 给出程序界面截图、后台运行日志或配置文件

`stderr:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
stderr:     response = self.full_dispatch_request()
stderr:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
stderr:     rv = self.handle_user_exception(e)
stderr:   File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
stderr:     return original_handler(e)
stderr:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
stderr:     rv = self.dispatch_request()
stderr:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
stderr:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
stderr:   File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
stderr:     return current_app.ensure_sync(func)(*args, **kwargs)
stderr:   File "/nas-tools/web/main.py", line 1032, in subtitle
stderr:     return render_template("setting/subtitle.html", Config=Config().get_config())
stderr:   File "/usr/lib/python3.10/site-packages/flask/templating.py", line 148, in render_template
stderr:     return _render(
stderr:   File "/usr/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
stderr:     rv = template.render(context)
stderr:   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
stderr:     self.environment.handle_exception()
stderr:   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
stderr:     raise rewrite_traceback_stack(source=source)
stderr:   File "/nas-tools/web/templates/setting/subtitle.html", line 62, in top-level template code
stderr:     <input class="form-check-input" type="checkbox" id="subtitle.opensubtitles.enable" {% if
stderr:   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 485, in getattr
stderr:     return getattr(obj, attribute)
stderr: jinja2.exceptions.UndefinedError: 'ruamel.yaml.comments.CommentedMap object' has no attribute 'subtitle'
stderr: [2022-12-07 22:04:36,770] ERROR in app: Exception on /subtitle [POST]
stderr: Traceback (most recent call last):
stderr:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
stderr:     response = self.full_dispatch_request()
stderr:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
stderr:     rv = self.handle_user_exception(e)
stderr:   File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
stderr:     return original_handler(e)
stderr:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
stderr:     rv = self.dispatch_request()
stderr:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
stderr:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
stderr:   File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
stderr:     return current_app.ensure_sync(func)(*args, **kwargs)
stderr:   File "/nas-tools/web/main.py", line 1032, in subtitle
stderr:     return render_template("setting/subtitle.html", Config=Config().get_config())
stderr:   File "/usr/lib/python3.10/site-packages/flask/templating.py", line 148, in render_template
stderr:     return _render(
stderr:   File "/usr/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
stderr:     rv = template.render(context)
stderr:   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
stderr:     self.environment.handle_exception()
stderr:   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
stderr:     raise rewrite_traceback_stack(source=source)
stderr:   File "/nas-tools/web/templates/setting/subtitle.html", line 62, in top-level template code
stderr:     <input class="form-check-input" type="checkbox" id="subtitle.opensubtitles.enable" {% if
stderr:   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 485, in getattr
stderr:     return getattr(obj, attribute)
stderr: jinja2.exceptions.UndefinedError: 'ruamel.yaml.comments.CommentedMap object' has no attribute 'subtitle'
stderr: [2022-12-07 22:04:37,192] ERROR in app: Exception on /subtitle [POST]
stderr: Traceback (most recent call last):
stderr:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
stderr:     response = self.full_dispatch_request()
stderr:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
stderr:     rv = self.handle_user_exception(e)
stderr:   File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
stderr:     return original_handler(e)
stderr:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
stderr:     rv = self.dispatch_request()
stderr:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
stderr:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
stderr:   File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
stderr:     return current_app.ensure_sync(func)(*args, **kwargs)
stderr:   File "/nas-tools/web/main.py", line 1032, in subtitle
stderr:     return render_template("setting/subtitle.html", Config=Config().get_config())
stderr:   File "/usr/lib/python3.10/site-packages/flask/templating.py", line 148, in render_template
stderr:     return _render(
stderr:   File "/usr/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
stderr:     rv = template.render(context)
stderr:   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
stderr:     self.environment.handle_exception()
stderr:   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
stderr:     raise rewrite_traceback_stack(source=source)
stderr:   File "/nas-tools/web/templates/setting/subtitle.html", line 62, in top-level template code
stderr:     <input class="form-check-input" type="checkbox" id="subtitle.opensubtitles.enable" {% if
stderr:   File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 485, in getattr
stderr:     return getattr(obj, attribute)
stderr: jinja2.exceptions.UndefinedError: 'ruamel.yaml.comments.CommentedMap object' has no attribute 'subtitle'`

> 
![image](https://user-images.githubusercontent.com/8079253/206201963-2d9ec78f-2060-4b49-bd67-bb040e3be350.png)

**Comment by Shurelol** [comment]
config.yaml改过？subtitle 节点改坏了，照着项目里的改回来
