### ISSUE TITLE
检索媒体信息出错！

### ISSUE THREAD

**Issue by HOMMEEN** [jxxghp/nas-tools#238]
情况描述：在配置好目录同步之后，点击服务中的目录同步，就出现这种情况
![Snipaste_2022-06-05_00-15-45](https://user-images.githubusercontent.com/49138691/172015976-590dd2f2-b2e5-4b24-9286-b9f45068922c.jpg)
媒体文件是可以读到的，但是不知道啥原因，也检查过权限 已经是everyone完全控制了。
umask也是022；puid和pgid都和emby以及qb的一致。
以下是我映射的路径：
<img width="478" alt="image" src="https://user-images.githubusercontent.com/49138691/172016081-efaf8972-28e0-4c68-acaf-be19ca9eb5b9.png">
两个media下面分别有各自的links文件夹。

请教原因～

**Comment by jxxghp** [comment]
我猜一下：TMDB APIKEY没配？

**Comment by HOMMEEN** [comment]
> 

哈哈哈我好捞啊，昨天配完忘记保存了
