### ISSUE TITLE
站点详情页下载字幕无法正常同步并重命名到对应文件夹

### ISSUE THREAD

**Issue by six00** [jxxghp/nas-tools#2387]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.2
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

>站点编辑页面开启“从详情页下载字幕”
开始正常下载后查看日志提示已解析到字幕。并且开始下载 如下日志
10:37:37 INFO - 【Subtitle】开始从站点下载字幕: https://xxxx
10:37:39 INFO - 【Subtitle】找到字幕下载链接: https://xxxxx，开始下载...
10:37:39 INFO - 【Subtitle】转移字幕 /config/temp/Sea_Fog_2014_BluRay_1080p_DTS_x264-MTeam.chs.srt 到 /Download/Movie

后续查看/config/temp/目录下确实已经下载完成 但是/Download/Movie 下载目录没有字幕。目录肯定没有配置错误 下载的电影文件也是下载到这个目录的。
并且不知道我开启了目录同步的重命名功能 如果这个问题修复后 字幕能不能同时一起重命名并同步到对应的电影或电视剧文件夹
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已查询

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/18079439/206345399-f1424036-8426-4ad1-8339-6c02c8407fe3.png)
![image](https://user-images.githubusercontent.com/18079439/206345449-d8308e0c-c13e-4761-80d8-967676fc2d0a.png)
![image](https://user-images.githubusercontent.com/18079439/206345573-f2177122-b969-4760-8f74-c643790bdea8.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
对应电影的子目录里没有吗？

这个PR 修复过：#2354

**Comment by six00** [comment]
> 对应电影的子目录里没有吗？
> 
> 这个PR 修复过：#2354

问题仍然存在 目录截图我都发了 不论是下载目录 还是转移目录 都没有字幕的存在
