### ISSUE TITLE
自动删种任务误删正在下载的种子

### ISSUE THREAD

**Issue by ZS2618** [jxxghp/nas-tools#2388]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.3
> 
> 环境: docker
> 

## 你遇到什么问题了？

> qBittorrent自动删种任务的问题 - 正在下载的种子会被判断为做种时间无限长。体现在：当我把 自动删种任务 的 做种时间栏目 设为 9999(假设为无限长)，依然会有正在下载的任务会被框选。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 此问题未被提及过。

## 你期望的结果

> 希望可以修复这个问题，避免正在下载的任务被误删。

## 给出程序界面截图、后台运行日志或配置文件
<img width="488" alt="image" src="https://user-images.githubusercontent.com/72600020/206347192-038b2ded-192c-42ae-8be3-ed8132dcbba3.png">

<img width="368" alt="image" src="https://user-images.githubusercontent.com/72600020/206346761-2166f348-0e98-4fc6-a677-4064b951d69b.png">

**Comment by Shurelol** [comment]
设置种子状态

**Comment by Shurelol** [comment]
更新
