### ISSUE TITLE
希望增加自动删种任务中 关键词排除功能

### ISSUE THREAD

**Issue by ZS2618** [jxxghp/nas-tools#2389]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.3
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望增加自动删种任务中 关键词排除功能.  用于排除需要做种的PT，并删除不需要长期做种的BT资源（以免浪费宽带带宽）。

用途: 设置BT和PT分开管理的自动删种任务

- 排除所有PT站的track，不删除PT种

- 删除非PT站track的任务，删除BT种

<img width="356" alt="image" src="https://user-images.githubusercontent.com/72600020/206347867-1d9ae930-ce19-4354-8e7e-9b7cb6bedd81.png">

## 这个功能有什么可以参考的资料吗？
> Nas-tool软件的过滤规则
<img width="278" alt="image" src="https://user-images.githubusercontent.com/72600020/206347837-5e33c6ef-d24a-4cee-882e-901b59b16bb4.png">

**Comment by Shurelol** [comment]
自己写

**Comment by ZS2618** [comment]
您可以给一个例子么？

比如说我想实现 排除open和hdpt。

我根据正则写为：^(?!open).*$|^(?!hdpt).*$ 但是无法实现功能。
