### ISSUE TITLE
群晖ds6套件版会自动退出

### ISSUE THREAD

**Issue by a872675986** [jxxghp/nas-tools#239]
![image](https://user-images.githubusercontent.com/48860803/172034387-1cfbf8fc-5d10-4832-a19f-123c73d912e9.png)
群晖套件版会自动退出,然后无法访问,但是套件状态还是已启动,就是链接无法访问了,必须重启套件才行

**Comment by jxxghp** [comment]
看日志确实是收到了退出信号

**Comment by a872675986** [comment]
最近四五个版本都有这个问题,一般是开启了 就没管他了 然后发现隔一段时间就进不去了 必须重启套件

**Comment by jxxghp** [comment]
整合了矿神SPK帮忙打包的套件，试试下，有问题再提吧。
