### ISSUE TITLE
docker 僵尸进程

### ISSUE THREAD

**Issue by songjianxing** [jxxghp/nas-tools#2390]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> v2.6.3 993dd7d7
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？
docker 僵尸进程
> 描述一下你遇到的问题
> 用2.6.3版本貌似没出现了，可以试试。 2.6.3内存占用也下降了90%。
> 经过测试发现僵尸进程依然存在 
> 这里僵尸进程 比较多的原因是我未设置 --init, 
> 上次是与 node 相关 这次与chrome相关
![image](https://user-images.githubusercontent.com/18136439/206349142-e965d2bc-704b-46ab-9ba7-f198862ffce6.png)

**Comment by jxxghp** [comment]
早上又重打了镜像，再拉一下试试？

**Comment by songjianxing** [comment]
> 早上又重打了镜像，再拉一下试试？
> 版本: v2.6.3 993dd7d7
> 还是会出现
![image](https://user-images.githubusercontent.com/18136439/206353727-3ef22b67-dd05-46db-bd86-1eed84a1cde7.png)

> 软件内更新出现了一个权限问题
![image](https://user-images.githubusercontent.com/18136439/206353045-d7310a78-737e-4401-b8ba-2bfe07118a14.png)
