### ISSUE TITLE
配置问题咨询

### ISSUE THREAD

**Issue by cccwwcww** [jxxghp/nas-tools#24]
1、请问jackett下res_type留空后搜索任何资源都显示没有资源，留空则不过滤好像没有生效
2、搜索出来的资源整合选择最优，这个是择优是根据什么条件去判断的，发现搜索的资源在某个PT站点是FREE，但是没有选择最优
【JACKETT】所有API检索完成，有效资源数：28
【WEB】共检索到 28 个有效资源
【WEB】分组择优后剩余 9 个有效资源

**Comment by jxxghp** [comment]
目前没有FREE的逻辑

**Comment by jxxghp** [comment]
现在资源显示已经比原来多很多了，按站点、资料类型等显示做种最多的一个。不支持优先免费。
