### ISSUE TITLE
消息通知bug

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#2413]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker
>

## 你遇到什么问题了？
遇到多余人的消息
我明明只设置五个用户通知，然而日志里会显示六个，其中 第六个提升通知失败
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

无

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![17907EEC-EA55-4198-A341-59FDBA7E3BF2](https://user-images.githubusercontent.com/39802246/206517465-5246447d-4e7a-444a-ba13-a2e5b8910079.jpeg)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
消息服务的日志已经细化，可以再运行下，看下日志

**Comment by Tartarus2014** [comment]
已经找到问题了
谢谢开发者
