### ISSUE TITLE
第三方推送的订阅下载时希望可以进行限速

### ISSUE THREAD

**Issue by Tasle** [jxxghp/nas-tools#2415]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.3 6b83be6d
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望能可以选择默认下载器，通过第三方提交的下载、订阅都是默认下载器，推送后下载时默认的下载器不能进行限速，看到界面有开放，但是没实装不能编辑。因为下载机用的国外的，很多站点对非国内IP下载速度过快的会直接标盒，影响后续良性循环，所以希望添加可以更改默认下载器下载、上传速度的功能，谢谢。

## 这个功能有什么可以参考的资料吗？

> 非默认下载器已经可以修改上传下载速度

**Comment by Wangsc1** [comment]
下载器里面自己新建一个，然后限速，订阅的时候选择新建的下载器就好了

**Comment by Tasle** [comment]
> 下载器里面自己新建一个，然后限速，订阅的时候选择新建的下载器就好了

通过slack、jellyseerr这种第三方推送的下载或订阅都是默认的，或者能可以自己选择默认下载器也可以。

**Comment by jxxghp** [comment]
> > 下载器里面自己新建一个，然后限速，订阅的时候选择新建的下载器就好了
> 
> 
> 
> 通过slack、jellyseerr这种第三方推送的下载或订阅都是默认的，或者能可以自己选择默认下载器也可以。

支持的，你发名字的时候后面可以跟站点名和下载设置的名字，用空格隔开

**Comment by Tasle** [comment]
> > > 下载器里面自己新建一个，然后限速，订阅的时候选择新建的下载器就好了
> > 
> > 
> > 通过slack、jellyseerr这种第三方推送的下载或订阅都是默认的，或者能可以自己选择默认下载器也可以。
> 
> 支持的，你发名字的时候后面可以跟站点名和下载设置的名字，用空格隔开

请问下jellyseerr也能怎么实现啊？
