### ISSUE TITLE
有些资源自动识别不到

### ISSUE THREAD

**Issue by mygithello** [jxxghp/nas-tools#2416]
有个问题，发现有些资源自动识别不到
识别时候,发现这里通过Tempo di massacro可以在TMDB搜索到资源，但是Tempo.di.massacro.AKA.Massacre.Time.1966.1080p.BluRay.FLAC.x264-HANDJOB.mkv自动识别不出来
建议:例如如果搜索不到，通过资源名以"."分割情况，名前三个"."换成空格，进行搜索是否可以：
Tempo.di.massacro  ====> Tempo di massacro

Ballada.o.soldate.AKA.Ballad.of.a.Soldier.1959.1080p.BluRay.x264.FLAC.5.1.mkv
Ballada.o.soldate  ==> Ballada o soldate

**Comment by Tartarus2014** [comment]
自定义识别词

**Comment by mygithello** [comment]
@Tartarus2014   
是手动识别吗，这个我知道，可以通过TMDB手动识别是可以的。我想着这个自动识别如果优化一些,一些情况就不用手动识别啦

**Comment by mygithello** [comment]
@Tartarus2014 
基础设置-实验室 里有个辅助识别的开关，不确定好不好用，先打开试试看
