### ISSUE TITLE
电视剧无法整理，无法创建硬链接，返回-1

### ISSUE THREAD

**Issue by KyleTang** [jxxghp/nas-tools#2418]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.6.2
>
> 环境: Synology 7.1.1
>

## 你遇到什么问题了？

> 整理电视剧时，硬链接失败。如果这个电视剧通过samba协议上传到群晖里的，就可能出现无法整理，硬链接创建失败。如果是通过file station的网页，拖拽上传的，就没事。我仔细对比了文件夹的用户权限，是一样的。samba访问的用户用户和网页登录的file station用户是同一用户，不知道为何？

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 没有找到问题

## 你期望的结果

> 问题得到解决，并且创建硬链接失败的时候，日志上能给出更多的错误提示信息。

**Comment by Shurelol** [comment]
硬链接不能跨盘，群辉不同共享文件夹也是跨盘

**Comment by KyleTang** [comment]
没跨盘啊，也没跨共享目录啊
