### ISSUE TITLE
qb下载器中不显示任务，只能在nastools中看到进度和内容

### ISSUE THREAD

**Issue by snoweer** [jxxghp/nas-tools#2419]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 目前 v2.6.3
>第一次安装v2.4.1时，使用是正常的，后来不记得是哪次升级就不正常了，到目前为止，一直不正常。
> 环境: docker or windows or Synology
>unraid 6.11.5 docker 运行
qb nastools运行在同一台设备中，不同的容器
qb版本为:qbittorrent:4.3.5-alpine-3.13.5-amd64-full 荒野无灯稳定版本

## 你遇到什么问题了？

> 描述一下你遇到的问题
nastools下载器设置为qb，通信正常，下载正常，nastools中显示均正常，但在qb中不显示任何下载内容。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
是，搜索过，没有同类问题

## 你期望的结果

> 描述以下你期望的结果
确认一下是nastools的问题还是qb的问题

## 给出程序界面截图、后台运行日志或配置文件

![111](https://user-images.githubusercontent.com/10679629/206641532-c63dba78-a66a-4c9b-b1d0-443f13edcf43.jpg)

**Comment by Shurelol** [comment]
建议qb换官方的新镜像
