### ISSUE TITLE
订阅日历bug

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#2427]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker 

## 你遇到什么问题了？

> 描述一下你遇到的问题
订阅日历会出现双份

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志
<img width="468" alt="截屏2022-12-09 21 31 38" src="https://user-images.githubusercontent.com/39802246/206713741-a745fe67-f954-449f-8df0-cf99c58f83e0.png">
，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/206718252-f113a36b-a191-47f9-9ed7-8787e37150c7.png)
如何复现？

**Comment by jxxghp** [comment]
我也重现不了

**Comment by Tartarus2014** [comment]
我那也不是总出现。。，反正很神奇😂😂😂复现不了就算了
