### ISSUE TITLE
消息通道识别bug及消息错误

### ISSUE THREAD

**Issue by Ice-Cream-MY** [jxxghp/nas-tools#2433]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.6.1
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 描述一下你遇到的问题
![image](https://user-images.githubusercontent.com/76402568/206724207-66c794f0-e1b8-4070-a5f2-457746671693.png)
![image](https://user-images.githubusercontent.com/76402568/206724543-f6b0b3df-4e5a-44db-8379-776661423b23.png)

如图所示，纯数字无法识别，在web界面正常使用，2.6.0版本正常，另使用slack对应用单独对话时推送下载会出现此错误，但是可以正常发消息至频道

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/206764793-22b8c2d9-38c4-4282-8fa7-dd714ea09637.png)
搜不到就加年份

**Comment by Ice-Cream-MY** [comment]
> ![image](https://user-images.githubusercontent.com/16237201/206764793-22b8c2d9-38c4-4282-8fa7-dd714ea09637.png) 搜不到就加年份

感谢解答
