### ISSUE TITLE
作者大大考虑加入一个赞助二维码

### ISSUE THREAD

**Issue by Loyoan** [jxxghp/nas-tools#2436]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or synology

## 希望作者考虑弄个二维码让我们赞助一下

> 差不多每个星期都有release，良心作者我和我的同事都想支持一下。希望作者为爱发电的同时也能让我们给你买杯咖啡

**Comment by jxxghp** [comment]
感谢这份好意。
项目发展到现在已经不是我一个人的功劳，越来越多的人在加入做贡献。大家一起把它变得更好就行。

**Comment by SouLXH** [comment]
其实我也是这样，多次想要捐助（有些地方是真好用啊），但是发现没入口
