### ISSUE TITLE
电影（动漫剧场版）不规范命名无法识别反馈

### ISSUE THREAD

**Issue by qingmuhy** [jxxghp/nas-tools#2440]
# 不好意思，没注意到有汇总帖，重复发issue了，实在抱歉。
我去汇总贴里反馈吧，这里申请关闭。
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.3 
>
> 环境: docker 
>

## 你遇到什么问题了？

> 电影命名不规范无法正确识别，不知道算不算离谱的命名，故来反馈。

## 你期望的结果

> 期望能尝试识别，如果实在不规范就算了，的确识别不规范比较难搞。

## 相关文件名及内容
![无法识别截图](https://user-images.githubusercontent.com/25658951/206821671-8d8b278a-828a-46ed-a844-c99a4efc6cbe.png)
文件名：
```shell
[名侦探柯南剧场版01：引爆摩天楼].Detective.Conan.Movie.01.The.Time.Bomb.Skyscraper.1997.BluRay.1080p.x264.AC3.3Audios-CMCT.mkv
```
对应的的tmdb链接：https://www.themoviedb.org/movie/21422-meitantei-conan-tokei-jikake-no-matenrou

**Comment by jxxghp** [comment]
已经尽力了，剩下的自己用自定义识别词处理下
