### ISSUE TITLE
nastool推送下载到qb导致qb崩溃

### ISSUE THREAD

**Issue by OctoberCK** [jxxghp/nas-tools#2442]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.6.2
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> nastool推送种子到qb下载会引发qb的webui崩溃，而后导致qb整个失效需要重启。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

>已经在各处搜索过没有看到问题的解决方法

## 你期望的结果

> 希望能定位问题，我查看了日志和一部分源码，没有找到问题的所在，但是更换transmission的下载速度不如qb，希望还是能解决这个bug

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
没有日志，无法分析

**Comment by jxxghp** [comment]
那是QB对标签的处理问题，不关NASTOOL的事，试下升个QB版本
