### ISSUE TITLE
字幕文件没有跟随集数定位一起识别

### ISSUE THREAD

**Issue by Misaka09982** [jxxghp/nas-tools#2443]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.3
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
字幕文件没有跟随集数定位一起识别，tc、sc被识别成未知语言，在动漫字幕组中sc表示简中、tc表示繁中，后续希望添加这两个识别
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/41320755/206827504-06565f3f-7c5c-4e39-8c71-2c544e1d6cd9.png)

![image](https://user-images.githubusercontent.com/41320755/206827372-c38c8226-a68b-4d89-aa93-33e8a1f696ee.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by cikezhu** [comment]
#2398 支持识别动漫常见的sc、tc
#2354 fix 站点下载的字幕获取正确的文件夹
应该都支持了呀, 更新一下 看看版本号多少
![image](https://user-images.githubusercontent.com/29982056/206830339-9d0ecd92-c10a-4c0d-9de7-efb1b7453d9f.png)

**Comment by cikezhu** [comment]
字幕文件没有跟随集数定位一起识别应该是bug

**Comment by cikezhu** [comment]
![image](https://user-images.githubusercontent.com/29982056/206838495-7a5b42af-539a-4d4b-9c40-f99222429af4.png)
@Misaka09982  请暂时使用该方法完成识别, 字幕转移与集数定位暂时没有办法很好的配合

**Comment by Misaka09982** [comment]
> ![image](https://user-images.githubusercontent.com/29982056/206838495-7a5b42af-539a-4d4b-9c40-f99222429af4.png) @Misaka09982 请暂时使用该方法完成识别, 字幕转移与集数定位暂时没有办法很好的配合

不行，这个字幕还是生成一堆，都不匹配

**Comment by Misaka09982** [comment]
> ![image](https://user-images.githubusercontent.com/29982056/206838495-7a5b42af-539a-4d4b-9c40-f99222429af4.png) @Misaka09982 请暂时使用该方法完成识别, 字幕转移与集数定位暂时没有办法很好的配合

不行，这个字幕还是生成一堆，都不匹配
