### ISSUE TITLE
2.6.4不能访问

### ISSUE THREAD

**Issue by git-0101** [jxxghp/nas-tools#2446]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.4
>
> 环境: docker
>

## 你遇到什么问题了？

> 新拉取2.6.4镜像，新建容器后不能访问。
![Screenshot_20221210_135703](https://user-images.githubusercontent.com/115487446/206835450-f091b910-9129-4cc4-a86b-5ff137fd7404.jpg)
![Screenshot_20221210_141435](https://user-images.githubusercontent.com/115487446/206835448-747c36c9-6fa8-4434-9b9a-21713833d541.jpg)
修改成true后
![Screenshot_20221210_140621](https://user-images.githubusercontent.com/115487446/206835449-57a8e0b4-1f7b-4c19-851d-f082837ea3a0.jpg)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 正常访问

**Comment by Drunkwang** [comment]
同样的问题，今天一直无法启动

**Comment by woobhurk** [comment]
原来不止我一个遇到这种问题 😢

**Comment by cnfjice** [comment]
更新完2.6.4就无法访问了

**Comment by liuyunm** [comment]
openwrt上也是相同问题，应该是版本BUG

**Comment by xhrzg2017** [comment]
貌似是代码一个库没有上传还是写错了
from slack_sdk.errors import SlackApiError

**Comment by DDS-ALL** [comment]
已经修复了，请等待版本更新

**Comment by git-0101** [comment]
> 已经修复了，请等待版本更新

好的，谢谢！

**Comment by git-0101** [comment]
![Screenshot_20221211_141045](https://user-images.githubusercontent.com/115487446/206889207-cb01e815-f863-48ae-a53d-02ab0ba6b41f.jpg)
大家耐心等待，作者大佬估计很快就会更新。

**Comment by jxxghp** [comment]
2.6.4不支持Arm架构，可先不升级
