### ISSUE TITLE
站点资源种子标识

### ISSUE THREAD

**Issue by Wangsc1** [jxxghp/nas-tools#2449]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.4
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
站点资源里面瓷器没有free、50%、2x、2xfree等标识

## 你期望的结果

> 描述以下你期望的结果
希望大佬能修复下

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
![image](https://user-images.githubusercontent.com/26079238/206851897-9b4e3c28-ff9c-46a1-aad4-a37d7cbb07e3.png)

![image](https://user-images.githubusercontent.com/26079238/206851903-ac81cbcb-68c2-4a3b-8128-47c92236dd9c.jpeg)

![image](https://user-images.githubusercontent.com/26079238/206851945-8f6959a8-23db-4fe0-bb9a-baf6c42a0773.png)

**Comment by jxxghp** [comment]
是什么站都没有说？

**Comment by jxxghp** [comment]
#2370  这个站点暂没有适配
