### ISSUE TITLE
微信自定义菜单报错但服务功能正常

### ISSUE THREAD

**Issue by rainow** [jxxghp/nas-tools#245]
报错信息：
00:49:47 ERROR - 微信消息处理发生错误：'NoneType' object has no attribute 'text' - Traceback (most recent call last): File "/nas-tools/web/main.py", line 1909, in wechat content = xml_tree.find("Content").text AttributeError: 'NoneType' object has no attribute 'text'

但从web端登录后，服务-PT站签到功能正常。

企业微信自定义菜单配置：
![image](https://user-images.githubusercontent.com/7533065/172207690-22fd43d4-d3fd-4be9-8eb1-7892c4064780.png)

是我的菜单配置哪里不对吗？

**Comment by jxxghp** [comment]
这块被反复改出问题，重写了相关代码，更新新版本试试。
