### ISSUE TITLE
请教通知问题

### ISSUE THREAD

**Issue by serenity666** [jxxghp/nas-tools#2450]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.4
>
> 环境: docker
>

## 你遇到什么问题了？

> 通知用的IYUU，下载、入库等推送测试正常，但是媒体播放没有收到消息，是不是需要特别设置。翻遍WIKI好像找不到可以设置的地方。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 希望将jellyfin的播放开始信息和停止播放信息推送到IYUU。感谢！

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/64485323/206854439-3a45dc4a-5b94-4b81-8a78-26c44f9ff6a4.png)
首页能看到播放信息。
![image](https://user-images.githubusercontent.com/64485323/206854517-74b88c41-f474-4d32-aa67-466d261551f3.png)
这是推送设置
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
尝试媒体服务器webhook加nastool

**Comment by serenity666** [comment]
搞定！！！jellyfin需要特殊设置，需要把key和value按图片这样子填好。
![Screenshot_2022-12-11-00-11-22-113_org jellyfin mobile](https://user-images.githubusercontent.com/64485323/206864398-4fc35383-ddd5-4eca-9cc6-7a2c7a2dbbd8.jpg)
