### ISSUE TITLE
字幕设置页面打不开

### ISSUE THREAD

**Issue by KITblue** [jxxghp/nas-tools#2453]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.6.4
>
> 环境: docker 
>

## 你遇到什么问题了？

> 字幕设置页面崩了。点击字幕设置页面没有出来，保持上一个设置页面
之前更改了媒体库目录，出现问题后重新安装过，没解决问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是，没找到这个问题

## 你期望的结果

> 下一版修复

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![msedge_WRZvpyETnZ](https://user-images.githubusercontent.com/68754977/206866209-8f072b68-5097-4ed2-9de3-65fcd2ae34cb.png)
![msedge_g5HiAorIJ0](https://user-images.githubusercontent.com/68754977/206866211-3ac64f13-4ccc-429e-8a55-f4eff5f89f5a.png)
![msedge_7zQmnxA5X0](https://user-images.githubusercontent.com/68754977/206866212-7c758ca9-3be7-4d4d-ba26-65c32c984f06.png)

**Comment by jxxghp** [comment]
正常

**Comment by Lynnhs1n** [comment]
我的字幕设置页面也打不开，2.8.1，安装在群晖上。

**Comment by Lynnhs1n** [comment]
![image](https://user-images.githubusercontent.com/109627967/214845614-35e0844f-c1c6-4365-b2f1-53b9d7426950.png)

**Comment by Lynnhs1n** [comment]
补充一下，是安装在群晖的docker里面
