### ISSUE TITLE
希望增加自定义订阅能够指定TMDB ID和季数的功能

### ISSUE THREAD

**Issue by missing233** [jxxghp/nas-tools#2454]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.4
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 自定义订阅在识别部分资源时获取到的季数不正确。如图所示，实际应为第二季而不是第一季。希望能给自定义订阅增加指定TMDB ID和季数的功能。
![QQ截图20221211024242](https://user-images.githubusercontent.com/18642603/206870522-ee8739b0-a245-446b-919d-e7acca9212b1.png)
![QQ截图20221211023914](https://user-images.githubusercontent.com/18642603/206870489-bc05f6fb-1f29-4306-8432-f6931b77a4dc.png)

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Shurelol** [comment]
加自定义识别词
