### ISSUE TITLE
原盘的硬链接还是有问题

### ISSUE THREAD

**Issue by 26712681** [jxxghp/nas-tools#246]
![image](https://user-images.githubusercontent.com/77581926/172289553-47901228-1764-434f-9cca-7b8336287e60.png)
![image](https://user-images.githubusercontent.com/77581926/172289644-f45d96d9-544d-49ea-9705-5dea95aac4fa.png)

这种BDMV文件夹格式的，很多都没有处理

**Comment by jxxghp** [comment]
貌似目录同步模式下仍然有问题，请更新代码到最新再看看

**Comment by jxxghp** [comment]
已解决，如还有问题再重新提吧。

**Comment by mouse2008** [comment]
<img width="951" alt="image" src="https://user-images.githubusercontent.com/45554099/184497874-5004851e-5c28-4762-85be-0639bbf9edfd.png">
BDMV文件夹格式的，很多都无法识别
