### ISSUE TITLE
Slack只能接收信息，无法返回搜索结果，不能交互

### ISSUE THREAD

**Issue by YoshiPark** [jxxghp/nas-tools#2462]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> V2.6.4
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 按照教程配置好slack之后，nastools显示slack测试成功，但是搜索影片时候，slack并没有返回相关信息

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 希望可以slack可以返回搜索结果

![slack测试](https://user-images.githubusercontent.com/20967749/206896029-6e0b356c-6938-4c25-a69d-5978b3d8a74d.png)
![slack无法返回搜索结果](https://user-images.githubusercontent.com/20967749/206896038-6621299a-a935-4097-a566-8cc171f4a033.png)

> 如UI BUG请提供截图及配置文件截图
> 后台无slack相关信息

**Comment by YoshiPark** [comment]
有没有遇到这种情况的？按照tel和网站各种教程设置了，都是不能检索

**Comment by Linnnkkk** [comment]
我连收到请稍等都没有
