### ISSUE TITLE
疑似编码问题

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#2465]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker 
>

> 描述一下你遇到的问题
打开之后日志报错

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

> 描述以下你期望的结果
解决问题
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

![IMAGE 2022-12-11 19:36:34](https://user-images.githubusercontent.com/39802246/206901296-b9e008e7-6604-4e4b-a039-16b852c8262e.jpg)

**Comment by jxxghp** [comment]
这个啥也看不出来，也重现不了
