### ISSUE TITLE
[Feature Request] 自定义搜索词支持

### ISSUE THREAD

**Issue by sgpublic** [jxxghp/nas-tools#2468]
## 你使用的 NAStool 是什么版本，什么环境？

NAStool 版本: v2.7.0

环境: linux

## 你想要新增或者改进什么功能？

使用 `电视剧订阅` 功能时，支持添加自定义搜索词，适用于以下列举的场景：

+ 《灰色的乐园》

  这部番在 TMDB 里面好像是识别为《灰色的果实 第二季》，而如果用《灰色的果实 第二季》这个标题在例如 MiKan 上搜就搜不到，这个时候就可以加自定义搜索词，替换原本搜索中文名和英文名的逻辑。

+ 《弩级战队H×EROS》

  这部番在例如 MiKan 上的标题为《弩级战队HXEROS》（就是把乘号×变成了字母X），所以用《弩级战队H×EROS》这个标题同样会导致搜不到，添加自定义搜索词可解决。

我知道目前已经有 `自定义识别词` 的功能，但是个人认为不够方便，不满足 “释放双手” 的目标（doge）

## 这个功能有什么可以参考的资料吗？

如果作者大大觉得这个功能可行，我这边已经开写了（这个 commit 写了一半）：[feature (backup): add custom search keyword](https://github.com/sgpublic/nas-tools/commit/9e85677a072964456fbd064832387e973bbcc5c6)，写完测试好了我就来提 pr，或者作者大大有更优雅的方案我就坐等更新了ww

**Comment by sgpublic** [comment]
> emmm，改搜索用词和改被搜索的文件名有区别么？

我遇到的问题是用原来的标题在搜索站上搜不到词条，然后订阅就订阅不到剧集，最后就下载不下来，就比如《灰色的乐园》，订阅《灰色的果实 第二季》就只能是 0/10（也许是我用的搜索站不行？

**Comment by Shurelol** [comment]
建议去看下订阅的逻辑，订阅是去识别rss获取到的每一个种子，然后看识别出来的tmdbid和订阅的剧集tmdbid相不相同

所以重点在于，让你需要的资源能被正确的识别

**Comment by sgpublic** [comment]
> 建议去看下订阅的逻辑，订阅是去识别rss获取到的每一个种子，然后看识别出来的tmdbid和订阅的剧集tmdbid相不相同
> 
> 所以重点在于，让你需要的资源能被正确的识别

我知道 rss 订阅是什么，但是我是说 nastools 的 `电视剧订阅` 功能，如果我没理解错的话，目前的逻辑是需要给一个标题，然后去 TMDB 里面找有没有，如果有然后再拿到中文名和英文名去搜索站搜索（刚开始看逻辑没怎么整明白但应该没问题吧），这就导致我要的番剧标题必须在 TMDB 里有我才能订阅，然后如果在搜索站里对应番剧的标题不一致，最后会导致搜不到资源，就像这样：

+ 弩级战队H×EROS 搜索结果

  <img src="https://user-images.githubusercontent.com/37202870/206907159-b60f6b5c-857d-400c-acc6-70b30f434777.png" alt="home" width="560" />

+ 弩级战队HXEROS 搜索结果

  <img src="https://user-images.githubusercontent.com/37202870/206907213-e8b2bd95-2d7b-4171-85f3-fab25b1e810e.png" alt="home" width="560" />

**Comment by Shurelol** [comment]
![Screenshot_20221211_215850_Chrome.jpg](https://user-images.githubusercontent.com/16237201/206908025-629ce3d4-8b4b-44d6-a9e0-abc2fcc03b4b.jpg)

建议换个搜索对大小写不敏感的站试试

**Comment by sgpublic** [comment]
> 建议换个搜索对大小写不敏感的站试试

可是原标题他不是小写的x，是个乘号×（捂脸

**Comment by jxxghp** [comment]
这种情况搜索手工用快速搜索下载，订阅用自定义识别词转换后RSS就能匹配上。
如果没PT站，这。。。就要一个吧，不然不好玩。

**Comment by sgpublic** [comment]
行吧，感谢各位大佬的回复，我还是手动下吧（捂脸

**Comment by cofan24** [comment]
我觉得这功能我挺需要的，可能就动漫需求比较大。之前看异世界舅舅，TMDB的名字是《异世界归来的舅舅》，我看的字幕组名称是《异世界舅舅》，结果搜索不到。异世界舅舅我都是手动下载的。现在又遇到了问题，弦音，TMDB tv/83314是用同一个编号的，名称是《弦音 -风舞高中弓道部》，第二季名称实际是《弦音 -连结的一射》，现在电视剧订阅的搜索的话，搜索是用的【弦音 风舞高中弓道部】，jakett搜不到第二季的任何资源，用英文【Tsurune】可以搜到第二季的一个生肉资源。自定义识别词那边我已经做了，只要能把资源搜到，就可以识别成“弦音 -风舞高中弓道部 [S2]”，但是现在就是搜不到，只能手动下载了。
![Snipaste_2023-01-05_21-01-05](https://user-images.githubusercontent.com/119946352/210786478-eb8f9437-f6c1-4493-b6ec-8dd79fc05ecf.jpg)
![Snipaste_2023-01-05_21-01-36](https://user-images.githubusercontent.com/119946352/210786497-7308d8f6-1070-47a7-ab98-39db54908b22.jpg)

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/210786959-0f773344-3837-4c21-a755-3e82c165dbc2.png)
![image](https://user-images.githubusercontent.com/16237201/210787075-2e66a6a3-2634-4acd-a233-4b5ec0a444f1.png)
![image](https://user-images.githubusercontent.com/16237201/210787117-0378f16c-551c-4cd3-a5cd-ebcd83856f11.png)
我的建议是用dmhy，mikan，nyaa这些好点的bt资源站

**Comment by cofan24** [comment]
> ![image](https://user-images.githubusercontent.com/16237201/210786959-0f773344-3837-4c21-a755-3e82c165dbc2.png) ![image](https://user-images.githubusercontent.com/16237201/210787075-2e66a6a3-2634-4acd-a233-4b5ec0a444f1.png) ![image](https://user-images.githubusercontent.com/16237201/210787117-0378f16c-551c-4cd3-a5cd-ebcd83856f11.png) 我的建议是用dmhy，mikan，nyaa这些好点的bt资源站

搜“弦音”能搜到啊，但是搜“弦音 风舞高中弓道部”搜不到。电视剧订阅是默认用“弦音 风物高中弓道部”搜索的
![Snipaste_2023-01-05_21-10-24](https://user-images.githubusercontent.com/119946352/210787662-b300a829-dad6-4ae7-962d-c286b7d735db.jpg)

**Comment by cofan24** [comment]
我就是希望能在电视剧订阅里自定义搜索词，我定义识别词为“弦音”，这样就直接用弦音搜索，而不是用 弦音 风舞高中弓道部 去搜。

**Comment by sgpublic** [comment]
> 我就是希望能在电视剧订阅里自定义搜索词，我定义识别词为“弦音”，这样就直接用弦音搜索，而不是用 弦音 风舞高中弓道部 去搜。

代码我本地还有，既然有人跟我需求相同我就继续写下去了（doge

**Comment by cofan24** [comment]
> 

非常感谢！日本动画续篇取名字经常都不是很标准的按S2，S3来取的，经常加一些小标题，感叹号什么的，而TMDB没有进行区分，都是在同一个名称下，所以有时候会有这些问题。

**Comment by cofan24** [comment]
> ![image](https://user-images.githubusercontent.com/16237201/210789279-34e1f3af-b1ca-4d3a-a1a1-981cdaa6b3dc.png) ![image](https://user-images.githubusercontent.com/16237201/210789492-8f049d40-d832-440f-9a8f-3987325826d0.png)

可能是我表达得不是很清楚，我的意思是，用【弦音 -风物高中弓道部】搜索不到第二季，因为第二季名字是“弦音 -连结的一射”，有的字幕组在标题中加入了第二季的英文名“Tsurune: Tsunagari no Issha”，所以中文搜索完之后，搜索英文关键词【Tsurune】能搜到第二季，不过我想下B站港澳台那个，标题不带Tsurune，所以是搜不到的。

**Comment by wyxls** [comment]
不知道是不是同一个需求，我这边是完全搜不到该有的资源，导致订阅下载失败

![image](https://user-images.githubusercontent.com/8772976/212003533-496b8a4b-8695-459a-8cd3-e25b2a16e0f2.png)
![image](https://user-images.githubusercontent.com/8772976/212003589-1f8b56ed-fdc5-448c-837d-78df5215e29d.png)

**Comment by sgpublic** [comment]
> 不知道是不是同一个需求，我这边是完全搜不到该有的资源，导致订阅下载失败

在我看来是同一个需求，名字和字幕组传的不一样导致搜不到资源，结果就是订阅下载失败

**Comment by wyxls** [comment]
> > 不知道是不是同一个需求，我这边是完全搜不到该有的资源，导致订阅下载失败
> 
> 在我看来是同一个需求，名字和字幕组传的不一样导致搜不到资源，结果就是订阅下载失败

感觉也可以做成过滤规则那边支持关键词替换

**Comment by jxxghp** [comment]
已支持
