### ISSUE TITLE
下载管理-数据统计缺少部分站点

### ISSUE THREAD

**Issue by rainow** [jxxghp/nas-tools#247]
数据统计好像不打log对吧，没找到log内容

现象：站点中配置了观众，hdai和ptt，但是下载管理-数据统计中只有观众站跟hdai的，不显示ptt的数据。确定ptt站点配置正确，也能签到成功。

![image](https://user-images.githubusercontent.com/7533065/172340342-d32a8e4e-40e2-4be7-ac39-206c80d01bcb.png)

![image](https://user-images.githubusercontent.com/7533065/172340528-1e3d5a46-fdd2-40ff-9962-46140c400dc6.png)

**Comment by jxxghp** [comment]
看下cookie是不是过期了。

**Comment by jxxghp** [comment]
我没帐号测不了，等有帐号的大佬看看了

**Comment by rainow** [comment]
> 我没帐号测不了，等有帐号的大佬看看了

我扒了下代码，好像是正则匹配没匹上，pttime比较特立独行，他是这样式儿的：
<span class="mr5"><font class="color_uploaded">上传:</font>445.83GB</span>
<span class="mr5"><font class="color_downloaded"> 下载:</font>46.63GB</span>
没有“量”字

**Comment by jxxghp** [comment]
代码提了，看下行不行

**Comment by rainow** [comment]
> 代码提了，看下行不行

有了，感谢大佬，可以close了
