### ISSUE TITLE
同下载器多开支持，方便bt，pt分开管理

### ISSUE THREAD

**Issue by gghdao** [jxxghp/nas-tools#2473]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.4
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望可以增加同个下载器多个支持，我个人是PT，BT用两个不同的qbit分开下载管理，BT用qbit增强版，PT用原版。希望NAStool也能支持。

**Comment by Shurelol** [comment]
bt用qb，pt用tr

**Comment by Shurelol** [comment]
做上传建议用刷流刷，刷流可以添加任意多个下载器

**Comment by jxxghp** [comment]
多开一个QB一个TR，刷流是分开的
