### ISSUE TITLE
资源搜索界面添加豆瓣/TMDB跳转链接

### ISSUE THREAD

**Issue by serenity666** [jxxghp/nas-tools#2474]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.7
>
> 环境: docker
>

## 你遇到什么问题了？

> 如题，这样去看看影评也方便一些。

## 你期望的结果

> 通过点击豆瓣二字可以跳转到豆瓣电影详情页。

## 
![IMG_20221212_022037](https://user-images.githubusercontent.com/64485323/206921523-2e81551a-aad7-40f8-8cfd-a518382883d4.jpg)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by serenity666** [comment]
发现点标题可以跳转到tmdb😂，还是希望能转转豆瓣，毕竟国内基本用豆瓣。

**Comment by jxxghp** [comment]
TMDB数据里可没豆瓣ID
