### ISSUE TITLE
是否我使用不对，文件转移能不能不进行电影重命名和电视剧重命名

### ISSUE THREAD

**Issue by tianjincat** [jxxghp/nas-tools#2488]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v2.7.0 8415f420
> 环境: docker 

## 你遇到什么问题了？

> 在进行文件转移时，会按重命名格式进行更名，虽然这个格式可以按标准参数修改，但还是比不上大多数PT站的原始命名，是否可以在文件转移时不进行重命名呢？

## 你期望的结果

期望在文件转移时不重新命名

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/206991448-312862cc-8e9e-423c-84e0-1439243febff.png)
