### ISSUE TITLE
【需求】资源搜索结果显示PT促销信息

### ISSUE THREAD

**Issue by rainow** [jxxghp/nas-tools#249]
现在只能在Jackett中配置是否只显示freeleech，但是实际上还有2xFree，50%DL等优惠信息，对于大部分PT用户来说都还是需要根据优惠信息判断下载哪个，下不下载的。目前Jackett也能获取到对应的信息，是否可以在搜索结果中也进行显示？

![image](https://user-images.githubusercontent.com/7533065/172356914-a61da598-ab3e-49d3-bb3c-b7ecb9a97dd0.png)

**Comment by jxxghp** [comment]
下个版本支持
