### ISSUE TITLE
NT添加下载任务不会自动给TR加NASTOOLS标签

### ISSUE THREAD

**Issue by Kev1nT** [jxxghp/nas-tools#2490]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.0
>
> 环境: docker
>

## 你遇到什么问题了？

> NT添加下载任务不会自动给Transmission加NASTOOLS标签，也没有已整理那些标签。QB是正常的

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已查询，无相关问题

## 你期望的结果

> 不知是否是BUG，还是我哪里没设置对

**Comment by Shurelol** [comment]
Transmission中种子的label属性再qt和web ui中不会显示，用rpc去查

https://github.com/trim21/transmission-rpc
