### ISSUE TITLE
请问为什么我的硬链接一直不成功？

### ISSUE THREAD

**Issue by xuyf-2022** [jxxghp/nas-tools#2492]
## 你使用的 NAStool 是什么版本，什么环境？
> NAStool 版本: 2.7.0
>
> 环境: docker 
> 环境 docker

## 你遇到什么问题了？

> 根据要求建同步目录，可是都无法硬链接
目录如下截图 
![image](https://user-images.githubusercontent.com/120379019/207029513-a07574f5-015b-460e-abd0-dfcbcb43a25d.png)

源目录和Link目录都有如下中的三个文件夹
![image](https://user-images.githubusercontent.com/120379019/207030259-ef68e74f-aafb-4089-b2b1-5400618f00b8.png)

NasTool 中设置的同步目录如下截图 
![image](https://user-images.githubusercontent.com/120379019/207029614-b60bbd5f-9cf6-42c9-bff5-8081374ab746.png)

Link目录只能创建文件夹，无法生成文件硬链接，同步时报错日志如下：
![image](https://user-images.githubusercontent.com/120379019/207029756-e3154426-4f2d-4d02-a8f3-fdb9f8d55abf.png)

**折腾有1个星期了，崩溃了，请求大神帮忙，  多谢多谢@**

**Comment by jxxghp** [comment]
群里求助吧
