### ISSUE TITLE
剧集自动/手动无法识别 不使用自定义个格式和使用自定义剧集格式均无法读取。求大神指导。

### ISSUE THREAD

**Issue by Mrxlei** [jxxghp/nas-tools#2496]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.0
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 剧集自动/手动无法识别
不使用自定义格式和使用自定义剧集格式：唐人街探案{ep}.4K.HD国语中字无水印.mp4  均无法读取。求大神指导。
![02](https://user-images.githubusercontent.com/95324467/207204033-00f12d74-3cd6-4672-a410-dfc00a14a2b3.png)

08:33:00		拼装文件路径错误，无法从文件名中识别出集数：/media1/tv1/唐人街探案/唐人街探案/唐人街探案01.4K.HD国语中字无水印.mp4
08:33:00		拼装文件路径错误，无法从文件名中识别出集数：/media1/tv1/唐人街探案/唐人街探案/唐人街探案02.4K.HD国语中字无水印.mp4
08:33:00		拼装文件路径错误，无法从文件名中识别出集数：/media1/tv1/唐人街探案/唐人街探案/唐人街探案03.4K.HD国语中字无水印.mp4
08:33:00		拼装文件路径错误，无法从文件名中识别出集数：/media1/tv1/唐人街探案/唐人街探案/唐人街探案04.4K.HD国语中字无水印.mp4
08:33:00		拼装文件路径错误，无法从文件名中识别出集数：/media1/tv1/唐人街探案/唐人街探案/唐人街探案05.4K.HD国语中字无水印.mp4
08:33:00		拼装文件路径错误，无法从文件名中识别出集数：/media1/tv1/唐人街探案/唐人街探案/唐人街探案06.4K.HD国语中字无水印.mp4
08:33:00		拼装文件路径错误，无法从文件名中识别出集数：/media1/tv1/唐人街探案/唐人街探案/唐人街探案07.4K.HD国语中字无水印.mp4
08:33:00		拼装文件路径错误，无法从文件名中识别出集数：/media1/tv1/唐人街探案/唐人街探案/唐人街探案08.4K.HD国语中字无水印.mp4
08:33:00		拼装文件路径错误，无法从文件名中识别出集数：/media1/tv1/唐人街探案/唐人街探案/唐人街探案09.4K.HD国语中字无水印.mp4
08:33:00		拼装文件路径错误，无法从文件名中识别出集数：/media1/tv1/唐人街探案/唐人街探案/唐人街探案10.4K.HD国语中字无水印.mp4
08:33:00		拼装文件路径错误，无法从文件名中识别出集数：/media1/tv1/唐人街探案/唐人街探案/唐人街探案11.4K.HD国语中字无水印.mp4
08:33:00		拼装文件路径错误，无法从文件名中识别出集数：/media1/tv1/唐人街探案/唐人街探案/唐人街探案12.4K.HD国语中字无水印.mp4
08:33:00		/media1/tv1/唐人街探案/唐人街探案 处理完成，总数：12，失败：12

**Comment by yourber** [comment]
自定义识别唐词 正则替换  
唐人街探案\d+  替换成   唐人街探案S01E\1
试试！

**Comment by Mrxlei** [comment]
> 
自定义替换词 <app.db.models.CUSTOMWORDS object at 0x7f48ea20a530> 格式有误：invalid group reference

**Comment by AisukaYuki** [comment]
![image](https://user-images.githubusercontent.com/17586327/207246542-5452be3c-aead-4c6b-ab65-b8c9154e35fa.png)

**Comment by Mrxlei** [comment]
谢谢，已成功
