### ISSUE TITLE
使用豆瓣名称联想，与tmdb结果不一致。（后缀时间问题）

### ISSUE THREAD

**Issue by mizb** [jxxghp/nas-tools#2497]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.0
>
> 环境: docker or windows or Synology
>docker 

## 你遇到什么问题了？

> 开启使用豆瓣名称联想后，有些电影或者连续剧，明明已经搜索到了，但是tmdb显示没有相关内容。
排查后发现，是后缀日期的问题。
举例：豆瓣搜索 风吹半夏。得到的结果是风吹半夏（2022）
但是tmdb内只是风吹半夏。没有风吹半夏（2022）。
所以导致两者结果不一样，无法搜索

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是

## 你期望的结果

> 使用豆瓣名称联想的时候，能否加一个如果和tmdb结果不一样，加上后缀日期或者取消后缀日期，再次匹配。增加成功率。

**Comment by jxxghp** [comment]
你举的这个例子，应该去完善tmdb数据。都不去维护，是不会准的。
