### ISSUE TITLE
阿童木 - 站点资源种子标识没有

### ISSUE THREAD

**Issue by qqqaaassshu** [jxxghp/nas-tools#2498]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 阿童木 站点资源里面没有free、50%、2x、2xfree等标识

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 以搜索

## 你期望的结果

> 描述以下你期望的结果
 >希望能够正确显示标识，谢谢大佬

> 如UI BUG请提供截图及配置文件截图
> 
<img width="728" alt="image" src="https://user-images.githubusercontent.com/22878892/207220255-ac0b84fe-bf64-40b7-bd69-2bcfe7a10f2f.png">

<img width="975" alt="image" src="https://user-images.githubusercontent.com/22878892/207220230-e5fe2bf5-9328-46e4-826c-2ab9608218dc.png">

**Comment by jxxghp** [comment]
这个站我没有，需要种子列表页面标识的HTML代码

**Comment by LeoJwj** [comment]
@jxxghp 
<img class="pro_50pctdown2up" src="pic/trans.gif" alt="2X 50%" title="2X 50%">
<img class="pro_free2up" src="pic/trans.gif" alt="2X Free" title="2X免费">

<img class="pro_2up" src="pic/trans.gif" alt="2X" onmouseover="domTT_activate(this, event, 'content', '<b><font class=&quot;twoup&quot;>2X</font></b>剩余时间：<b><span title=&quot;2023-01-05 16:43:48&quot;>14天5时</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);" id="__autoId5">

<img class="pro_50pctdown" src="pic/trans.gif" alt="50%" onmouseover="domTT_activate(this, event, 'content', '<b><font class=&quot;halfdown&quot;>50%</font></b>剩余时间：<b><span title=&quot;2022-12-29 17:43:24&quot;>7天6时</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);" id="__autoId7">

<img class="pro_free" src="pic/trans.gif" alt="Free" onmouseover="domTT_activate(this, event, 'content', '<b><font class=&quot;free&quot;>免费</font></b>剩余时间：<b><span title=&quot;2023-01-20 18:03:27&quot;>29天7时</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);" id="__autoId11">

**Comment by LeoJwj** [comment]
@jxxghp 
`<img class="pro_50pctdown" src="pic/trans.gif" alt="50%" onmouseover="domTT_activate(this, event, 'content', '<b><font class=&quot;halfdown&quot;>50%</font></b>剩余时间：<b><span title=&quot;2022-12-30 10:09:22&quot;>7天23时</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);" id="__autoId2">`
`<img class="pro_free2up" src="pic/trans.gif" alt="2X Free" onmouseover="domTT_activate(this, event, 'content', '<b><font class=&quot;twoupfree&quot;>2X免费</font></b>剩余时间：<b><span title=&quot;2023-01-01 01:57:28&quot;>9天15时</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);" id="__autoId4">`
`<img class="pro_30pctdown" src="pic/trans.gif" alt="30%" onmouseover="domTT_activate(this, event, 'content', '<b><font class=&quot;thirtypercent&quot;>30%</font></b>剩余时间：<b><span title=&quot;2023-01-20 18:55:02&quot;>29天8时</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);" id="__autoId16">`
`<img class="pro_2up" src="pic/trans.gif" alt="2X" onmouseover="domTT_activate(this, event, 'content', '<b><font class=&quot;twoup&quot;>2X</font></b>剩余时间：<b><span title=&quot;2023-01-05 16:43:48&quot;>14天5时</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);" id="__autoId5">`
`<img class="pro_free" src="pic/trans.gif" alt="Free" onmouseover="domTT_activate(this, event, 'content', '<b><font class=&quot;free&quot;>免费</font></b>剩余时间：<b><span title=&quot;2023-01-20 10:46:12&quot;>29天0时</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);" id="__autoId6">`
