### ISSUE TITLE
让签到需要填写验证码的站点也能签到

### ISSUE THREAD

**Issue by yourber** [jxxghp/nas-tools#2499]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.6.4
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 集成百度OCR，让签到需要填写验证码的站点也能签到。

## 这个功能有什么可以参考的资料吗？

> pt_helper 有类似功能，但是它属于定时执行，一小时一次，感觉不太智能，个人感觉不如我们这个可以随机一个时间段内执行。

**Comment by MrLv0816** [comment]
支持 , api key可以自行申请

**Comment by jxxghp** [comment]
现在已经有了验证码ocr识别服务，并用于站点维护，问题是什么站需要验证码签到？而且我也没有。

**Comment by jxxghp** [comment]
没账号，暂时弄不了，后面可以考虑

**Comment by jxxghp** [comment]
有了空，看了下太复杂，算了，意义不大。
