### ISSUE TITLE
匹配机制问题

### ISSUE THREAD

**Issue by bobo0810** [jxxghp/nas-tools#25]
1. 网页结果缺失。比如PT有5季的资源，网页只显示3季。
2. 很多资源 ，但网页显示为空.

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/26057879/159140518-292b4186-2c71-4169-83dd-574755c56823.png">

![image](https://user-images.githubusercontent.com/26057879/159140460-6bce3a3d-9ed5-4cd1-a43d-4c8f86d4b6a4.png)

**Comment by jxxghp** [comment]
漫画是不支持的，命名格式都不一样

**Comment by bobo0810** [comment]
> 漫画是不支持的，命名格式都不一样

你好，不是漫画，是电视剧。问题1是搜美剧毒枭，问题2是国产动漫剧集。

**Comment by jxxghp** [comment]
试下最新版本是不是能支持了

**Comment by jxxghp** [comment]
最新版本已支持动漫识别，使用第三方模块Anitopy，受限于命名问题，很难完美解决。
