### ISSUE TITLE
自定义订阅模块好像不自动启动了

### ISSUE THREAD

**Issue by hbzjwyz** [jxxghp/nas-tools#2501]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 自定义订阅没办法定时启动
![image](https://user-images.githubusercontent.com/63764017/207244624-2f04dd9a-a3f5-4910-8a76-e494c0085895.png)
设定的间隔时间是1440分钟，也就是1天一次，但是显示的最后更新时间是【2022-12-06 22:25:19】。昨天通过手动触发可以正常搜索下载，就是没办法定时 运行。

而且日志好像也停止了
![image](https://user-images.githubusercontent.com/63764017/207245158-d392fb74-7195-43d2-a5ab-584e2f5e3307.png)
最后的时间还是【2022-11-22】的。

**Comment by Shurelol** [comment]
自定义订阅的日志现在在run.txt里，最后更新时间是有下载动作的时间
