### ISSUE TITLE
nastool 添加下载任务失败

### ISSUE THREAD

**Issue by zzbbluesky** [jxxghp/nas-tools#2503]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.0 8415f420
>
> 环境: docker 
>

## 你遇到什么问题了？

> 搜索到对应种子后，点击添加，一直失败

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 无对应解答

## 你期望的结果

> 帮忙找到问题来源，可以正常使用，谢谢。

## 给出程序界面截图、后台运行日志或配置文件
![WeChat9ea5611098cc8758b0cd614a878f2108](https://user-images.githubusercontent.com/10933764/207258102-d75d0b66-fe42-492c-a090-1bad7039ab72.png)

![Screen Shot 2022-12-13 at 15 55 44](https://user-images.githubusercontent.com/10933764/207258349-8a68723d-8e87-4934-8a9c-b844a999b40a.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by windblue72** [comment]
我也遇到一样问题  试过docker和套件版本都一样，换过qb，2.6.5
