### ISSUE TITLE
希望过滤促销支持多选。

### ISSUE THREAD

**Issue by luoxiao-xy** [jxxghp/nas-tools#2505]
![image](https://user-images.githubusercontent.com/49856280/207311504-d3b26c1d-530c-440a-aba5-03e62ae7aaa6.png)
希望过滤促销支持多选，比如能够勾选免费和2x免费，因为对于用户来说这两个都不计算下载量，因此希望可以一起勾，这样更加方便！再或者直接免费和2X免费合并选择

**Comment by link2fun** [comment]
多看说明
![image](https://user-images.githubusercontent.com/19241982/207318218-3a272173-5f24-4d06-aef8-c8e9b37c8b7e.png)

**Comment by JX0204** [comment]
选免费就包含了免费X2，你试试！
