### ISSUE TITLE
Windows版打开3000端口，无法通过端口外网访问

### ISSUE THREAD

**Issue by 2mabler** [jxxghp/nas-tools#2508]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.0
>
> 环境: windows
>

## 你遇到什么问题了？

>使用的是 Windows NAS,电信公网IP4,路由器里已映射端口，电脑里的jellyfin，Qbittorrent等都可以正常通过端口进行外网访问，虚拟机里群晖的套件版和docker版nastools也可以，唯独win版nastools不可以

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 描述以下你期望的结果

**Comment by 2mabler** [comment]
防火墙也进行了放行

**Comment by 2mabler** [comment]
修改 web host即可

**Comment by Murgoa** [comment]
> 修改 web host即可

请问web host在哪里修改，我尝试修改系统host，无效

**Comment by 2mabler** [comment]
是在config文件里这样改的吗？是最新的3.1.5版吗？
