### ISSUE TITLE
种子标签匹配问题

### ISSUE THREAD

**Issue by xushier** [jxxghp/nas-tools#2509]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
![image](https://user-images.githubusercontent.com/31540107/207367022-a801edb6-3345-45c4-a647-02c2b8665fd7.png)
![image](https://user-images.githubusercontent.com/31540107/207367102-3aa0490f-71a7-4e6e-93bf-1bcc66518f0e.png)
![image](https://user-images.githubusercontent.com/31540107/207367200-1c3969d4-f305-4e27-9695-e532efcd46f9.png)
![image](https://user-images.githubusercontent.com/31540107/207367395-5a4774c7-57b3-46a4-8dc9-d3c9e53725b6.png)

如图，该种子在 rss 订阅的时候没有订阅上，在测试时如果副标题加上中字标签才能匹配上。所以默认的匹配是只匹配标题和副标，不匹配副标前面的标签吗？还是只有这个站点目前不匹配？

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
浏览器打开rss链接，看看里面有吗？

**Comment by xushier** [comment]
明白了，搜索的结果包含标签信息。RSS内容不包含标签。感谢大佬解惑
