### ISSUE TITLE
PT任务偶尔添加失败

### ISSUE THREAD

**Issue by Always67** [jxxghp/nas-tools#251]
【PT】添加PT任务 http://10.0.0.88:9117/dl/mteamtp/?jackett_apikey=file=To+late+to+say+loving+you+2010+Complete+1080p+WEB-DL+AAC+x264-HQC 出错：'NoneType' object has no attribute 'add_torrent'
这是怎么回事呢？同一站点，但不是一直出现。

**Comment by jxxghp** [comment]
这个我也无法解释，这个错是QB报的。

**Comment by Always67** [comment]
通过几次观察发现，是升级docker之后，需要重新在下载器那里点一下“测试“，测试成功后，再次下载就不会报错了。
