### ISSUE TITLE
暗夜模式下 站点数据分享 部分数据不可见

### ISSUE THREAD

**Issue by Yasin27878** [jxxghp/nas-tools#2513]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.0
>
> 环境: docker 
>

## 你遇到什么问题了？

> 暗夜模式下  站点管理-》数据统计-〉站点数据分享  分享出来的图片 白色背景对应数据不可见

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 暗夜模式下 数据展示正常

## 给出程序界面截图、后台运行日志或配置文件
![nastool_statistics](https://user-images.githubusercontent.com/10019889/207383432-dc041b37-2af2-4073-af17-b1007d94e606.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
已修复，等更新
