### ISSUE TITLE
手动刷新，过滤规则错乱

### ISSUE THREAD

**Issue by xushier** [jxxghp/nas-tools#2514]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

![image](https://user-images.githubusercontent.com/31540107/207388120-f1ed1405-039c-42c4-99da-0d22dac9ecdb.png)
![image](https://user-images.githubusercontent.com/31540107/207388588-30cb8165-edd5-434f-957a-0ce521bf709f.png)
![image](https://user-images.githubusercontent.com/31540107/207388770-ee0b9dcc-5c01-4af1-a07e-ff2865c738fd.png)
![image](https://user-images.githubusercontent.com/31540107/207388954-4083fe61-5504-48ba-b229-cd4a498503cc.png)
如图，这部韩剧，订阅里没有选择规则，那应该是用的站点规则，而站点规则只有第一个是用的 “FRDS” 规则过滤，默认的规则也不是 FRDS 规则，但是日志里显示全是用 “FRDS” 规则过滤的。重启过容易也还是一样。

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
无法重现，暂时找不到问题在哪
