### ISSUE TITLE
希望可以无媒体服务器模式，首页支持搜索框或者推荐

### ISSUE THREAD

**Issue by luoxiao-xy** [jxxghp/nas-tools#2518]
现在必须设置媒体服务器，对于极空间，绿联、联想等自带影视管理功能的轻NAS设备来说，可能不会再部署其它第三方媒体库。只会用到订阅，搜索，下载管理。
希望可以支持无媒体服务器模式运行，即不设置任何媒体服务器。
首页可以支持调整为搜索界面或者推荐界面，或者搞一个综合性的首页出来。

**Comment by jxxghp** [comment]
没有媒体服务器就无法叛重，也不能查缺补漏。

**Comment by luoxiao-xy** [comment]
> 没有媒体服务器就无法叛重，也不能查缺补漏。

没有媒体服务器的用户，可以在设备自带媒体服务上自行判重和查漏补缺。以极空间为例，很多用户都没有部署其它媒体服务器，都是用的自带的极影视。自带的极影视，可以实现媒体服务器的削刮，影视墙，播放器等功能。
主要设备为国产新晋NAS存储设备，极空间、绿联（内测中，本月上线）、联想的NAS设备，都自带了媒体服务。
这部分人用nastools的目的是，影视豆瓣查看，订阅，搜索，与下载管理功能。

所以，作为轻nas的这部分用户之一，衷心希望，可以设置媒体服务为无，然后开始可以显示为推荐，搜索功能，当然也可以是下载管理页面。毕竟一打开nastools就显示一个硕大的无法连接媒体库，体验不咋友好
