### ISSUE TITLE
qb测试失败，无法连接

### ISSUE THREAD

**Issue by toodw** [jxxghp/nas-tools#2519]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v2.7.0
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> qb没有使用https，查询过nastool中的qBittorrent.py，已经写了verify webui certificate = false。qb的日志显示webapi登录成功。
在docker的nastool的控制台telnet过qb的端口，显示可以连接到IP地址，但过一会又显示connection closed by foreign host。

测试环境是n1荒野无灯的小钢炮系统，其内建了qb、Aria2等下载器，我在其docker里部署了nastool，由于只需求索引下载功能，部署时就只建了config和downloads两个文件夹。试过更换下载器为Aria2，同样测试失败。但Jellyfin可以成功连接。container网络是bridge模式，且改不了host模式。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 成功连接qb

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/120541595/207500496-d10baedd-1225-4c36-967e-65085b7f9279.png)
![image](https://user-images.githubusercontent.com/120541595/207500669-e78e1baf-2ceb-469a-9484-9ee7a0abe712.png)
![image](https://user-images.githubusercontent.com/120541595/207500747-3b8f38bc-046c-473c-be01-7314297c6a52.png)
![image](https://user-images.githubusercontent.com/120541595/207501218-604ac86d-22d8-4f13-840b-37998c0b27f0.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
环境类的问题好像别人也很难帮到你
