### ISSUE TITLE
内存溢出问题

### ISSUE THREAD

**Issue by Mirecle** [jxxghp/nas-tools#252]
在使用Nastool的过程中，log.txt日志的大小会超过10GB(运行10小时左右)，整个docker占用28G内存，NAS被卡死了，不得已重启docker，但很快log日志的大小又会达到4GB 以上，这是什么问题

**Comment by jxxghp** [comment]
无法理解。
1、日志不会这么大量，你要检查是什么原因导致
2、日志再多也是写到磁盘的，占用内存这么大更无法理解了。
3、从未遇到过类似问题，正常运行好几天日志才10M左右。

**Comment by Mirecle** [comment]
![屏幕截图 2022-06-08 210224](https://user-images.githubusercontent.com/32609935/172623128-d972bf7f-2d0e-44d9-8398-8e148a4363c6.png)

**Comment by jxxghp** [comment]
> ![屏幕截图 2022-06-08 210224](https://user-images.githubusercontent.com/32609935/172623128-d972bf7f-2d0e-44d9-8398-8e148a4363c6.png)

想办法打下看下，里面打印的是啥

**Comment by Mirecle** [comment]
日志太大，打不开，我下载到本地试试，之前看到一直报数据库的错 ... is lock

**Comment by jxxghp** [comment]
> 日志太大，打不开，我下载到本地试试，之前看到一直报数据库的错 ... is lock

数据库文件没权限或者被锁？ 你自己找找原因吧，正常不会有这个情况。现在这个工具应该很多人在用了，无未有人反馈过。
