### ISSUE TITLE
目录同步设为复制但实际执行时却使用硬链接

### ISSUE THREAD

**Issue by crek2002** [jxxghp/nas-tools#2524]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 之前目录同步里两个源目录和目的目录在一个盘，同步设置为硬链接，运行正常，后来把目的目录设置到另外的盘，同步设置为复制，但下载完成后的日志里却显示转移模式还是硬链接，导致失败。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是
这是我的目录同步设置
![Snipaste_2022-12-14_23-34-49](https://user-images.githubusercontent.com/59255846/207641242-a739ef9b-3395-44ef-be62-8807b25f178d.png)

这是日志（开启了下载软件监控）

![Snipaste_2022-12-14_23-45-02](https://user-images.githubusercontent.com/59255846/207643970-9bef8c9f-e84f-4d7d-a57f-463c8ba3ff9c.png)
![Snipaste_2022-12-14_23-47-19](https://user-images.githubusercontent.com/59255846/207644003-281add38-7b68-43b6-b287-c0f4950104b8.png)

**Comment by jxxghp** [comment]
已经关闭了还在跑？
