### ISSUE TITLE
电视剧无法整理，无法创建硬链接，返回-1，提示 Operation not permitted

### ISSUE THREAD

**Issue by KyleTang** [jxxghp/nas-tools#2526]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.6.0-2.6.4都有这个问题
>
> 环境: Synology
>

## 你遇到什么问题了？

> 有些视频文件通过samba服务复制到nas，无法创建硬链接，返回-1，提示 Operation not permitted，通过群晖的FileStation网页端上传则可以正常创建硬链接。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 关联：https://github.com/jxxghp/nas-tools/issues/2418#issue-1486091926  之前提过这个问题，在没有得到解决的情况下，被关闭了，这样不太好吧。

## 你期望的结果

>  经过我的分析，如果视频文件在win系统里，已经勾选过只读属性的，这个时候，通过samba协议复制到群晖里，会因为文件的只读属性，而无法创建硬链接。

**建议程序上进行优化，在创建硬链接之前，先执行 synoacltool -del-archive xxx.mp4 先将文件的只读属性删除，然后再创建硬链接，可提高软件的适用性** 

## 给出程序界面截图、后台运行日志或配置文件

在win系统里文件有只读属性，通过samba服务复制到群晖里，会保持此属性，如下图：
![存档属性后_20221215112520](https://user-images.githubusercontent.com/631193/207766738-6d0d3864-3a81-4335-982c-52c32b8ea6cf.png)

通过 synoacltool -del-archive 将只读属性删除
![删除存档属性后_20221215112520](https://user-images.githubusercontent.com/631193/207766744-72b3d178-661b-4f9b-9565-5a9be997ffb2.png)

**Comment by jxxghp** [comment]
你自己玩这么花，有能力你就自己解决，没能力还要强求别人来帮你解决？
你的情况解决了对别人并没有价值。官方并没有适配群晖，还要去调群晖的命令？
