### ISSUE TITLE
机器人搜索结果跳转tmdb详情页

### ISSUE THREAD

**Issue by Wangsc1** [jxxghp/nas-tools#2527]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
机器人（只试了tg和微信）搜索结果影片跳转到tmdb都是找不到影片详情页面

## 你期望的结果

> 描述以下你期望的结果
麻烦大佬看下🙏

> 如UI BUG请提供截图及配置文件截图
![image](https://user-images.githubusercontent.com/26079238/207767802-8063e9b9-e0cf-4a66-ba29-eaecef6e11c9.png)
![image](https://user-images.githubusercontent.com/26079238/207767822-71e490dc-bf48-42f7-abd8-483dd9e27c7c.png)

**Comment by jxxghp** [comment]
开豆瓣的时候确实有问题
