### ISSUE TITLE
复制模式,文件夹命名,部分剧集英文名字,有时大写开头,有时小写开头

### ISSUE THREAD

**Issue by FoolForest** [jxxghp/nas-tools#2528]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>V2.6.2以及以前版本,之后未知
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> 复制模式,文件夹命名,部分剧集英文名字,有时大写开头,有时小写开头,例:美剧边缘世界(The Peripheral),因为是订阅更新,是不同时间点分集下载的,有时候命名为:The Peripheral.边缘世界.S01E01.WEB-DL.1080p.mkv,有时候命名为:the peripheral.边缘世界.S01E03.web.1080p.mkv(2集英文名大小写不一致)
也不知道是不是这个原因,导致(文件转移失败,错误码-1),同时生成一个带日期的文件夹,复制的文件在此文件夹下,并不会与原剧集目录合并

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
Issues未见提及此问题

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
更新，如还存在此问题，再开启这个isuue
