### ISSUE TITLE
订阅里第九集已经下载完了，可是进度条还是在第八集

### ISSUE THREAD

**Issue by Linon419** [jxxghp/nas-tools#253]
第九集已经下载完了，为啥进度条还是在8。(因为刚升级完，所以日志没了)
![Screenshot_2022-06-08-23-22-52-525_com miui videoplayer](https://user-images.githubusercontent.com/29937602/172627785-d0817303-e5ec-467e-8cda-9835f17b0611.jpg)
![Screenshot_2022-06-08-23-23-10-300_com android chrome](https://user-images.githubusercontent.com/29937602/172627803-89b421da-2041-41cc-9e51-13ac9620e125.jpg)

**Comment by xxzj990** [comment]
我的这个动画也有同样问题是不是这一集都识别不出来？

![截屏2022-06-09 上午8 51 31](https://user-images.githubusercontent.com/5134154/172741427-27266ec1-73ab-4103-9812-11bb095a5f38.png)

**Comment by jxxghp** [comment]
是订阅自动下载的吗？我这里同一剧可以显示9。
RSS自动命中的才会更新数字，否则要等下一次命中，或者手工搜索下也会更新。

**Comment by xxzj990** [comment]
我这里点击了一下【立即搜索】好了，应该就是非RSS自动命中导致的。

**Comment by Linon419** [comment]
> 是订阅自动下载的吗？我这里同一剧可以显示9。 RSS自动命中的才会更新数字，否则要等下一次命中，或者手工搜索下也会更新。

是rss自动订阅下载，不过我订阅了同一部番剧的两个不同字幕组，最新第九集的字幕组和其他的不一样。不过我看媒体识别的历史记录里，识别了这一集啊
