### ISSUE TITLE
两个不同的企业的企业微信小程序搜索会错乱

### ISSUE THREAD

**Issue by Tasle** [jxxghp/nas-tools#2534]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.0 865a0535
>
> 环境: docker
>

## 你遇到什么问题了？

> 添加了两个不同企业的企业微信小程序，不交互是可以正常推送消息的，但是交互后两个`agentid`会错乱。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已浏览

## 你期望的结果

> fix

## 给出程序界面截图、后台运行日志或配置文件

> 从`MEIDA_U` 发送互动消息后，会返回`USEE_公共`错误，如下图
> 

![](https://img.urlnode.com/file/834e4465ffee14f0e36bc.png)
![](https://img.urlnode.com/file/b9484f7bc6ac312697268.png)

**Comment by jxxghp** [comment]
只有交互为开的才能接收消息，确定没发错？
没发现程序哪里有Bug

**Comment by Tasle** [comment]
> 只有交互为开的才能接收消息，确定没发错？ 没发现程序哪里有Bug

![](https://img.urlnode.com/file/b5e51ecd79017a5d35e1f.png)


没有发错，试了下是这样的，A/B是两个不同企业的，A在消息通知中排序靠前，不打开交互单纯消息推送没有问题，但是打开交互之后会有下面的bug
1. A关闭交互，B打开交互，在B发送交互信息，服务器日志会返回A的`agentid`错误日志；
2. A打开交互，B关闭，在A发送交互信息，可以正常返回信息。
3. A&B都打开交互，A正常接收信息，B会返回日志 `解密微信消息失败 DecryptMsg ret = -40001`

总结下就是不同企业的微信机器人，排序靠前的可以进行交互，排序靠后的无法使用交互
