### ISSUE TITLE
使用nastool然后进入观众站点资源解析种子文件异常

### ISSUE THREAD

**Issue by LmanTs** [jxxghp/nas-tools#2536]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.70版本. 但是上一个版本就有这个情况
> 环境: docker 

## 你遇到什么问题了？

> 在站点资源里点击下载时提示添加下载失败 请检查下载任务是否已存在（使用的站点是：观众）

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已搜索相关内容，没有得到相关结果

## 你期望的结果

> 知道如何解决即可

## 给出程序界面截图、后台运行日志或配置文件
![7f7980eb43766975a8527746446ec9d](https://user-images.githubusercontent.com/40474635/207867703-471da1c6-32b6-4113-b480-e27413437cf7.png)
![7c6322d72b794ebeadee42726a6e80b](https://user-images.githubusercontent.com/40474635/207867775-c8b2a8a6-6102-4b16-8b6a-e1809a65ad6f.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
如果只有这一个站点有问题，更换cookie和ua后，docker完整重启。

**Comment by LmanTs** [comment]
> 

我使用了你提供的方法操作了一边，先删掉了观众，然后重新添加观众，然后我手动关掉了nastool，最后关掉了docker，再启动，之后回到nastool里尝试能否开始下载，但我得到的结果是一样的，错误日志也与我上面提供的截图是一样的（补充：我总共3个站点，观众是唯一出问题的）

**Comment by jxxghp** [comment]
> > 
> 
> 我使用了你提供的方法操作了一边，先删掉了观众，然后重新添加观众，然后我手动关掉了nastool，最后关掉了docker，再启动，之后回到nastool里尝试能否开始下载，但我得到的结果是一样的，错误日志也与我上面提供的截图是一样的（补充：我总共3个站点，观众是唯一出问题的）

ua填了吗？ ua跟cookie要配套。另外，是否有在站点列表界面手工下载过种子。

**Comment by libashanxi** [comment]
你设置的观众的地址是签到的地址吗？观众的最好设置成他首页的地址，签到额外维护一个站点来签到

**Comment by 07031218** [comment]
2.7.1版本，遇到同样问题，尝试了ua跟cookie配套，docker完整重启。问题没有得到解决

**Comment by 07031218** [comment]
遇到同样问题，解决了。
楼主先到观众手动下载一次种子文件，把PT站的新手任务完成即可解决这个错误问题。

**Comment by LmanTs** [comment]
> 遇到同样问题，解决了。
> 楼主先到观众手动下载一次种子文件，把PT站的新手任务完成即可解决这个错误问题。

我感觉问题有可能就是因为新手任务，等任务完成了我再回来看看

**Comment by LmanTs** [comment]
问题总结完成
具体问题其实不是因为新手任务的原因，是因为刚入站的时候下载种子的时候会提示一个关于下载介绍的页面，而不会直接弹出下载保存窗口，需要手工的点一个种子然后点击下载，并把提示页面的下次不再提示打上勾才能顺利解决。
谢谢大家的解答
