### ISSUE TITLE
站点图标都不显示

### ISSUE THREAD

**Issue by git-0101** [jxxghp/nas-tools#2540]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 如标题：
![Screenshot_20221216_000114](https://user-images.githubusercontent.com/115487446/207914627-5e301841-6fcf-42dd-a3bb-aeebda64dca1.jpg)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 正常显示站点图标

**Comment by jxxghp** [comment]
等站点数据刷完
