### ISSUE TITLE
希望在下载管理-正在下载中显示下载文件的集数

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/nas-tools#2543]
你使用的 NAStool 是什么版本，什么环境？
NAStool 版本: v2.7.1 
环境: docker 

你想要新增或者改进什么功能？

可以加入显示正在下载文件的具体集数。

这个功能有什么可以参考的资料吗？

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/51367628/208011874-9c58b6bf-ccfe-4807-91f8-b9cba46df713.png">

如图举例， 在正在下载中只能看到S02 一整季有10个文件正在下载，其中具体是第几集则无法判断，需要自行打开TM进去查看

**Comment by jxxghp** [comment]
主要是种子标题中没写，写了就会显示
