### ISSUE TITLE
希望添加一个功能

### ISSUE THREAD

**Issue by Wanderingkang** [jxxghp/nas-tools#2548]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v2.7.1 46fb995e
> 环境: docker or windows or synology
debian
## 你想要新增或者改进什么功能？
希望添加一个无法识别媒体信息源文件名创建硬链接，这样有些媒体就可以用了！
> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/208082519-e499bc7a-b5e1-41e2-b31f-52a3917932e8.png)

**Comment by Wanderingkang** [comment]
谢谢
