### ISSUE TITLE
希望大佬在转移重命名时能在末尾跟随一个IMDBID

### ISSUE THREAD

**Issue by 740527654** [jxxghp/nas-tools#255]
如题，有时候emby的刮削非常弱智，光用电影名+免费不能保证完全刮削正常。
![Screenshot_2022_0609_090628](https://user-images.githubusercontent.com/63200055/172743805-92365e76-452e-4122-bf07-674b153be258.jpg)

**Comment by jxxghp** [comment]
有些人不喜欢这种乱乱的名字，包括我，看起来很不爽。
