### ISSUE TITLE
手动识别，目录下存在视频文件，但是无法识别

### ISSUE THREAD

**Issue by qqqaaassshu** [jxxghp/nas-tools#2553]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 动漫无法识别，手动识别，提示“目录下未找到媒体文件，当前最小文件大小限制为 0.0”

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 可以正确找到媒体文件

## 给出程序界面截图、后台运行日志或配置文件
> 1.提示界面<img width="788" alt="image" src="https://user-images.githubusercontent.com/22878892/208114177-bb351a55-c689-4a84-a20a-873842c490ba.png">2.目录显示界面<img width="745" alt="image" src="https://user-images.githubusercontent.com/22878892/208114234-30b011a7-c4ac-4678-a1cb-92b65107d079.png">3.群晖中目录
<img width="1872" alt="image" src="https://user-images.githubusercontent.com/22878892/208114345-4451cdb3-4cd2-4533-a284-df4249e86e3b.png">4.docker目录配置
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/22878892/208114445-2772af03-64c5-44ae-add2-c772535a8c7e.png">

**Comment by jxxghp** [comment]
集数定位为什么填1？去掉后也提示找不到？
