### ISSUE TITLE
删除订阅无效

### ISSUE THREAD

**Issue by simon428** [jxxghp/nas-tools#256]
之前在豆瓣热门综艺里订阅了“意外的旅程”，但是在我的订阅里一直没有这个综艺的图，点取消订阅，显示取消订阅成功，但是刷新浏览器，还是订阅状态
![This is an image](https://jerking.empornium.ph/images/2022/06/09/QQ20220609094829.png)
![This is an image](https://jerking.empornium.ph/images/2022/06/09/QQ20220609094848.png)
![This is an image](https://jerking.empornium.ph/images/2022/06/09/QQ20220609094901.png)

**Comment by jxxghp** [comment]
已找到原因，稍后提交

**Comment by simon428** [comment]
> 已找到原因，稍后提交

已更新1.4.1，但是还会不能删除这个订阅
