### ISSUE TITLE
希望新增批量重命名功能和直接修改源文件的方式整理

### ISSUE THREAD

**Issue by loveu5522** [jxxghp/nas-tools#2565]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.7.1
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 我希望媒体整理文件管理里能新增批量重命名支持正则，还有支持直接在源文件上重命名和整理的方式，这样是有助于像阿里云盘这样的资源整理。
## 这个功能有什么可以参考的资料吗？

> 没有，重名名就像一些专用的重命名软件的那样功能，或者支持正则，把源文件直接重命名整理的方式就像
《tinyMediaManager》这个软件的整理方式。

**Comment by Shurelol** [comment]
前者建议用hlink等软件，后者建议挂在后用移动转移方式
