### ISSUE TITLE
删除生成的软连接后，不会重新创建新的软连接

### ISSUE THREAD

**Issue by dl280** [jxxghp/nas-tools#2566]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.71
>
> 环境:  windows 
>

## 你遇到什么问题了？

> 删除生成的软连接后，不会重新创建新的软连接。原来的软连接被我删除了，然后手动运行目录同步，不会生成新链接。

**Comment by Shurelol** [comment]
查日志，服务里清除转移缓存
