### ISSUE TITLE
windows版本  只能localhost连接  而本地ip无法连接

### ISSUE THREAD

**Issue by crazyjaiah** [jxxghp/nas-tools#2567]
windows版本  只能localhost连接  而本地ip无法连接
![image](https://user-images.githubusercontent.com/63030602/208230743-e96dde8e-50bc-4ff2-b6c5-9ed0c4a6e224.png)
![image](https://user-images.githubusercontent.com/63030602/208230753-e5adc2d7-2685-473a-a42d-bbe9d6039aa8.png)
防火墙都已经关闭

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/208237737-b10578c8-ac88-4e3c-8af7-d64ce79919e1.png)
