### ISSUE TITLE
是否可以添加数据迁移到功能

### ISSUE THREAD

**Issue by dl280** [jxxghp/nas-tools#2568]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.71
>
> 环境: windows 

## 你想要新增或者改进什么功能？

> 我原来的机子出问题了,需要迁移到搜刮的元数据和海报，使用的是nastools+emby的组合，两个软件都是便携软件拷贝过去是可以的，海报也会显示，就是软连接会失效。我将软连接删除，重新运行目录同步，也不会生成新的软连接。是否可以增强一下这个迁移到功能，就是重新生成软连接

**Comment by Shurelol** [comment]
服务里清除转移缓存
