### ISSUE TITLE
手动识别提示找不到大于200M的媒体文件，实际上文件是800多MB

### ISSUE THREAD

**Issue by milhu** [jxxghp/nas-tools#257]
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/12318000/172783314-bfab8def-40be-46f7-99ce-1342de816307.png">
<img width="721" alt="image" src="https://user-images.githubusercontent.com/12318000/172783426-95231e36-d395-449d-aac9-40f59887bdd2.png">
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/12318000/172783583-eb74df7c-212c-458d-9c77-56c7b97d2aaf.png">
目录映射都没问题，这个自动识别失败才显示在手动识别里面的，但是手动识别就会提示没有大于200M的文件
<img width="685" alt="image" src="https://user-images.githubusercontent.com/12318000/172784003-a378bf94-f119-456d-afde-8d6975dc06da.png">
之前的版本没有遇到问题，历史记录在这，同样也是手动识别的，文件格式一样，命名格式也是一样
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/12318000/172784192-20caba77-ab11-4c35-bb50-d4f8cc3d5626.png">

**Comment by milhu** [comment]
刚刚试了重新识别之前识别过的也是同样的错误，找不到大于200M的文件，但是目前自动识别的没问题

**Comment by milhu** [comment]
docker跑在QNAP NAS上的

**Comment by milhu** [comment]
正在下载的meta信息也识别不出来，好像整个电视剧的识别现在都不工作了
<img width="474" alt="image" src="https://user-images.githubusercontent.com/12318000/172792402-33286fcb-abf4-494c-96ce-0458d77aaceb.png">

**Comment by jxxghp** [comment]
> <img alt="image" width="1293" src="https://user-images.githubusercontent.com/12318000/172783314-bfab8def-40be-46f7-99ce-1342de816307.png">
> 
> <img alt="image" width="721" src="https://user-images.githubusercontent.com/12318000/172783426-95231e36-d395-449d-aac9-40f59887bdd2.png">
> 
> <img alt="image" width="1043" src="https://user-images.githubusercontent.com/12318000/172783583-eb74df7c-212c-458d-9c77-56c7b97d2aaf.png">
> 
> 目录映射都没问题，这个自动识别失败才显示在手动识别里面的，但是手动识别就会提示没有大于200M的文件
> <img alt="image" width="685" src="https://user-images.githubusercontent.com/12318000/172784003-a378bf94-f119-456d-afde-8d6975dc06da.png">
> 
> 之前的版本没有遇到问题，历史记录在这，同样也是手动识别的，文件格式一样，命名格式也是一样
> <img alt="image" width="1279" src="https://user-images.githubusercontent.com/12318000/172784192-20caba77-ab11-4c35-bb50-d4f8cc3d5626.png">

这里是不是应该选电视剧？

**Comment by milhu** [comment]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/12318000/172807117-2606580d-0b0f-40cb-befd-82a1b18fff55.png">
<img width="716" alt="image" src="https://user-images.githubusercontent.com/12318000/172807226-cfb2ec50-64dd-4d1f-940a-8769898eb6b9.png">
效果一样，还是提示找不到200M以上的媒体文件

**Comment by jxxghp** [comment]
找到个疑似原因，已提交代码，更新下试试看

**Comment by milhu** [comment]
<img width="501" alt="image" src="https://user-images.githubusercontent.com/12318000/172808163-d3105817-c11d-4575-be6c-d5bf7171f002.png">
我是这样更新了下，不知道有没有拉到最新代码。目前还是不行
