### ISSUE TITLE
transmission连接出错

### ISSUE THREAD

**Issue by hogar0720** [jxxghp/nas-tools#2573]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.1
>
> 环境: docker（host模式） Synology
>

nastools链接transmission套件

transmission连接出错：can't connect to transmission daemon: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.1.3:9091/transmission/rpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f58380cca90>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

**Comment by Shurelol** [comment]
网络问题，地址问题，自己排查
