### ISSUE TITLE
站點Cookie老是失效

### ISSUE THREAD

**Issue by miraclesuki** [jxxghp/nas-tools#2574]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v2.7.1
> 环境: docker or windows or Synology
>QNAP, docker

## 你遇到什么问题了？

> 配置好PT站點後，連線測試老是報錯，說Cookie失效

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 通過連線測試，成功增加站點使用RSS訂閱

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![螢幕擷取畫面 2022-12-18 020121](https://user-images.githubusercontent.com/5608626/208255434-5956cf38-e945-4c53-9157-a27b3e0d0be1.png)
![螢幕擷取畫面 2022-12-18 015931](https://user-images.githubusercontent.com/5608626/208255435-a2119c43-e28e-429e-806f-872c5cb645ec.png)
![螢幕擷取畫面 2022-12-18 020026](https://user-images.githubusercontent.com/5608626/208255436-5e5145ea-ac62-4c6f-a48c-e6837d50991a.png)

如有配置上出錯，請提供站點新增的方法範例作跟進參考，感謝

**Comment by jxxghp** [comment]
站点不支持
