### ISSUE TITLE
建议增加订阅页面一键刷新所有订阅以及修改订阅时间功能

### ISSUE THREAD

**Issue by huahuazi** [jxxghp/nas-tools#2579]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.1
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 建议增加订阅页面一键刷新所有订阅以及修改订阅时间功能，目前订阅时间没有地方可以更改且无法实现一次刷新所有剧集，只能一个个刷新

## 这个功能有什么可以参考的资料吗？

> 无

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/208294079-2260d682-9003-4f10-a3b5-2806fae74fe0.png)
![image](https://user-images.githubusercontent.com/16237201/208294080-0bb3c191-ce5d-4c24-9425-7c6a157b21c3.png)
