### ISSUE TITLE
国外BT站、PT站搜索无法用中文名搜索影片

### ISSUE THREAD

**Issue by dxbzth** [jxxghp/nas-tools#258]
能否在搜索中文名影片时自动匹配TDMB信息，转换为英文名搜索，提高国外BT、PT站搜片成功率。

**Comment by jxxghp** [comment]
转为英文搜索，国内的就低了。查两遍又不好，一是慢，二是会增加PT站压力。

**Comment by jxxghp** [comment]
我试试看

**Comment by Linon419** [comment]
pt助手是用imdb编码搜索的，作者可以试试

**Comment by jxxghp** [comment]
2022-06-12 18:12:32,720	INFO: 【JACKETT】rarbg 共检索到 13 条有效资源
微信/TG已支持，WEB搜索是模糊匹配的，要搜国外站就输入英文

**Comment by ztx0079** [comment]
> 2022-06-12 18:12:32,720 INFO: 【JACKETT】rarbg 共检索到 13 条有效资源
> 微信/TG已支持，WEB搜索是模糊匹配的，要搜国外站就输入英文

但是豆瓣同步的话就只会使用中文搜索
