### ISSUE TITLE
建议添加无过滤的搜索功能

### ISSUE THREAD

**Issue by xushier** [jxxghp/nas-tools#2581]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.1
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

建议添加无过滤的搜索功能。有些种子不在规则内，或者临时下一些其他资源，或者不知什么原因匹配成功的却不在搜索结果里显示。这个时候显示过滤之前的全部种子就能找到需要的种子了。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Shurelol** [comment]
过滤规则里自己加个空规则

**Comment by xushier** [comment]
但是在资源搜索的时候，没有 选择过滤规则 的选项
