### ISSUE TITLE
数据统计经常超时，尤其在站点多的情况下

### ISSUE THREAD

**Issue by singworld** [jxxghp/nas-tools#2585]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.1 4a67d71f
>
> 环境: docker
>

## 你遇到什么问题了？

> 数据统计经常超时，尤其在站点多的情况下
请求网址: http://ip:port/statistics
请求方法: POST
状态代码: 504 Gateway Time-out

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 
1. 返回未超时的数据
2. 超时站点给予错误提示，可以单独点击超时站点重试（类似ptpp）

**Comment by jxxghp** [comment]
没明白说的是什么问题，指调API的问题？

**Comment by jxxghp** [comment]
我这里32个站，倒也没这个问题。
看下docker后台日志有服错吗？
