### ISSUE TITLE
订阅里不显示图片，点击详情闪一下没有内容出现，无法删除

### ISSUE THREAD

**Issue by simon428** [jxxghp/nas-tools#259]
之前在豆瓣热门综艺里订阅了“意外的旅程”，但是在我的订阅里一直没有这个综艺的图，点取消订阅，显示取消订阅成功，但是刷新浏览器，还是订阅状态。早上你反馈说找到问题提交了，不过我这边更新了1.4.1后，还是不能删除这个订阅。求有什么办法删除这个订阅吗
![This is an image](https://jerking.empornium.ph/images/2022/06/09/QQ20220609094829.png)
![This is an image](https://jerking.empornium.ph/images/2022/06/09/QQ20220609094848.png)
![This is an image](https://jerking.empornium.ph/images/2022/06/09/QQ20220609094901.png)

**Comment by simon428** [comment]
试过在推荐里取消再添加，还是一样。强迫症看着这个不显示图，又删除不了订阅，很不舒适，求解决办法

**Comment by jxxghp** [comment]
![image](https://user-images.githubusercontent.com/51039935/172816893-815d3bd1-f19a-485f-b220-df8e8d9fe5c1.png)
用最新的代码，能显示图，而且也能取消啊。
你在ＴＭＤＢ缓存里找到这个，然后删掉。

**Comment by simon428** [comment]
> 

ＴＭＤＢ缓存里已经删了，现在还是不能显示图，在订阅里点击详情，还是闪一下出现不了取消订阅。在推荐里点取消订阅，刷新浏览器还是订阅状态。换了浏览器操作，一样的问题
![This is an image](https://jerking.empornium.ph/images/2022/06/09/QQ20220609174908.png)

**Comment by jxxghp** [comment]
你从哪里添加订阅的？推荐里没找到。我是手工加的没问题。

**Comment by simon428** [comment]
推荐-豆瓣热门综艺-意外的旅程。
但是我记得之前好像不是在这里订阅的，订阅完就没有显示图。这两天我看推荐才在豆瓣热门综艺里看到

**Comment by jxxghp** [comment]
> 推荐-豆瓣热门综艺-意外的旅程。 但是我记得之前好像不是在这里订阅的，订阅完就没有显示图。这两天我看推荐才在豆瓣热门综艺里看到

我试了，正常添加订阅，正常取消，木有问题，你确认下版本，更新到最新的看看。

**Comment by simon428** [comment]
我让朋友测试了，他订阅取消也没有问题。只是我这个是之前订阅的，确实是取消不了，版本也是更新到最新的了。试了很多次都没有办法。刚才重装解决了。谢谢大大
