### ISSUE TITLE
刷流时 部分站点选择free种但仍有非free种被刷到 导致下载量增加

### ISSUE THREAD

**Issue by jaysshao** [jxxghp/nas-tools#2590]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 刷流时 部分站点选择free种但仍有非free种被刷到 导致下载量增加，如CHD

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 期望如CHD刷流时选free种时不会有非free被下载刷流

谢谢开发大佬了~

**Comment by jxxghp** [comment]
CHD已经有多个Issues了，提之前先看一下。
