### ISSUE TITLE
关于刷流RSS解析错误的问题

### ISSUE THREAD

**Issue by wzyqlxp** [jxxghp/nas-tools#2591]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.1 28b4b420
>
> 环境: docker 
>

## 你遇到什么问题了？

> 在“站点维护”中添加了soul的信息，并填充了COOKIE和User-agent信息，在“站点资源”中可以正常展示信息。
问题出在RSS解析上，在“刷流任务”中添加了soul的任务，RSS是在网站上选取了特定的资源（e-book）进行刷流
NAS-TOOLS可以正常推送种子，但种子内容并非是我订阅的内容。
用浏览器查看，没有找到NAS-TOOLS推送的种子信息，因此判断：
疑似SOUL网站解析RSS需要带COOKIE才正正常解析。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
已浏览过Issues、Wiki，无类似问题。

## 你期望的结果

将刷流中RSS解析带上COOKIE信息

## 给出程序界面截图、后台运行日志或配置文件
![I ZDD1U~~{A8@S 6I}7`)OP](https://user-images.githubusercontent.com/58631828/208447096-7a307d18-c2b2-4f59-81f9-46d5c944db13.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
1、rss不需要cookie
2、rss链接粘贴到浏览器，保证能正常打开，且内容为所需

**Comment by wzyqlxp** [comment]
> 1、rss不需要cookie 2、rss链接粘贴到浏览器，保证能正常打开，且内容为所需

可能你手上的站点是不需要COOKIE的，而且绝大多数站点都是不需要的。但是部分站点的确是需要带COOKIE才能正常解析，比如SOUL
