### ISSUE TITLE
关于“自定义订阅”的RSS解析问题

### ISSUE THREAD

**Issue by wzyqlxp** [jxxghp/nas-tools#2593]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.1 28b4b420
>
> 环境: docker 
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
在自定义订阅中添加的RSS和实际解析出来的RSS内容不同
疑似SOUL等部分网站需要带COOKIE才能正常解析

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
已浏览过Issues、Wiki及TG公众号仍无法解决
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
在自定义和刷流中涉及到RSS解析的，能带上COOKIE一切解析，已兼容更多的站点。
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
这是RSS实际解析的：
![`W_}4G7(8GX3`MND)1Z{APH](https://user-images.githubusercontent.com/58631828/208452603-be822cd0-70dd-45e4-8701-40a37d54d988.png)
这是我用浏览器直接打开RSS链接，删除了一些其他信息，保留了种子名称的信息
![Z7H(X8~JQN0T}_0KRBSLI{A](https://user-images.githubusercontent.com/58631828/208453156-2805a16b-9918-44cf-b365-856ff7d5e763.png)
感谢管理大大，有了NAS-TOOLS让我家里人都能更加方便使用PT资源，非常感谢
希望NAS-TOOLS能兼容更多的PT站点，感谢！

**Comment by jxxghp** [comment]
自定义订阅的解析器是可以自己配置的，你两个图展示的是RSS里两个不同的字段吧？ 下载需要种子链接和种子标题，而不是中文描述。
绝大部分的RSS都不需要Cookie，不然Rss就没有意义了。
