### ISSUE TITLE
訂閱檢索時，目標文件不能正常匹配下載

### ISSUE THREAD

**Issue by miraclesuki** [jxxghp/nas-tools#2594]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.7.1
> 环境: docker or windows or Synology
>docker qnap

## 你遇到什么问题了？
檢索完成後不能正常匹配下載

> 描述一下你遇到的问题
命中下載條件，但卻顯示 「未匹配到媒体信息」，導致不能如期自動下載
如提供的圖片所示，字幕為星空字幕組，檢索抓到相關標題卻無法匹配下載

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> yes

## 你期望的结果

> 成功自動匹配下載。
目前試過打開模糊檢索會在日志看到直接報錯，表示tmdb讀不了動畫標題，當然我是能正常連線進tmdb的。

2022-12-20 01:59:19,150 INFO: 【Meta】正在查询TMDB电视剧：0 ...
Exception: The resource you requested could not be found.
Callstack:

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![螢幕擷取畫面 2022-12-20 020658](https://user-images.githubusercontent.com/5608626/208493365-e5a0fdf6-99a9-4cfa-9f12-029a9cd2b427.png)
![螢幕擷取畫面 2022-12-20 022105](https://user-images.githubusercontent.com/5608626/208493526-0f79f518-3551-4420-96e0-9df3a3ac19f8.png)

**Comment by Shurelol** [comment]
[识别问题](https://t.me/nastool_mi/69)，加自定义识别词

**Comment by Shurelol** [comment]
(?<=\[星空字幕(?:组|組)\])\[(.*?)\]  替换 \1

![image](https://user-images.githubusercontent.com/16237201/208495414-921f5bd9-5dd5-4fa0-80b5-6dc7b75bc8a0.png)
![image](https://user-images.githubusercontent.com/16237201/208495468-f4caf7e9-2d6e-468b-93a0-353d2a7643d7.png)
