### ISSUE TITLE
这里的参数不知道是bug还是逻辑问题

### ISSUE THREAD

**Issue by Wanderingkang** [jxxghp/nas-tools#2598]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v2.7.1 56f390d5
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？
在设置-基础设置-媒体-最小文件转移是bug还是逻辑问题
> 描述一下你遇到的问题
现在我下载完视频，没有通过nastools下载，只通过qb下载完后，完成目录同步，最小文件转移设置500M，但是nastools 把所有文件转移了
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是，仍无法解决
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果
能不能实现不通过nastools 下载的视频文件，转移时只转移大于某个大小的文件，余下都不转移
> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/89479532/208592770-39aa6f34-cfcc-4158-8ae4-ba0f1cad675b.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
关掉了识别重命名的开关吗？

**Comment by Wanderingkang** [comment]
是的，关掉了。不关掉的话，不是通过nastools下载的音乐书籍有无法硬链接。这个功能我感觉大部分人都有需求吧。就是无论是否通过nastools下载的东西都能做到硬链接，而且可以根据文件大小去选择

**Comment by Shurelol** [comment]
关闭识别重命名只能引用转移屏蔽词和黑名单，不能应用最小文件大小。

目录同步和是不是通过nastool下载的没有关系

**Comment by Wanderingkang** [comment]
是否可以加上这项选择

**Comment by jxxghp** [comment]
#2504
