### ISSUE TITLE
跨设备硬链接 Cross-device link

### ISSUE THREAD

**Issue by jasonchio-cn** [jxxghp/nas-tools#26]
容器配置中的媒体目录和监控目录
![image](https://user-images.githubusercontent.com/36125147/159443100-40d7ede1-bd0f-459e-8461-361200221f2a.png)
![image](https://user-images.githubusercontent.com/36125147/159443148-fe54e7a2-8fa6-42ac-9c2f-a5aa4a23b0c2.png)
 我直接用docker run 命令把 Downloads 和 Videos 两个文件夹的上级目录映射到了容器里的 host 文件夹里，手动整理的时候依旧报跨设备链接的错误。命令如下：
![image](https://user-images.githubusercontent.com/36125147/159444354-a9169c77-f4a8-48f6-ae8e-21e49716a0bf.png)
进入容器手动整理
![image](https://user-images.githubusercontent.com/36125147/159443645-e2a39b7c-78c7-4ef2-a2ca-a83194b18e0b.png)
文件目录
![image](https://user-images.githubusercontent.com/36125147/159443889-ce763d60-1a9e-4945-979f-346410454597.png)

**Comment by jxxghp** [comment]
在群晖里不同的共享文件夾是不同的设备，硬链接不占额外空间，可放同一个共享目录内。
