### ISSUE TITLE
自定義訂閱下載完成後，轉移時季度檢測命名錯誤

### ISSUE THREAD

**Issue by miraclesuki** [jxxghp/nas-tools#2609]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.7.1
> 环境: docker or windows or Synology
>docker qnap

## 你遇到什么问题了？

> 自定义订阅下載完成後，轉移時季度檢測命名錯誤。
會把第3季的動畫當作第1季命名，如圖RSS下載完成幻櫻的傳誦之物第3季第26集後，
轉移時S03E26的動畫會當作S01E26的命名處理。

*測試時，自定义识别词里把 二人白王 替換成 S3*

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> yes

## 你期望的结果

> 文件夾及文件需正確命名季度。文件夾為Season 3，文件名帶有S03E26。

## 给出程序界面截图、后台运行日志或配置文件
![螢幕擷取畫面 2022-12-21 061017](https://user-images.githubusercontent.com/5608626/208778300-53ce23fa-e64f-4fdc-b400-98e116925001.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
https://t.me/nastool_mi/69

**Comment by Shurelol** [comment]
![Uploading Screenshot_20221219_221101_Telegram.jpg…]()

**Comment by Shurelol** [comment]
![Screenshot_20221219_221101_Telegram](https://user-images.githubusercontent.com/16237201/208779533-f7a52cb2-cef9-45d2-b9e7-9062e1095522.jpg)
