### ISSUE TITLE
订阅重复添加种子

### ISSUE THREAD

**Issue by aiwu12** [jxxghp/nas-tools#2610]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.1 56f390d5
>
> 环境: docker  Synology
>
![image](https://user-images.githubusercontent.com/61082200/208818412-5c61dfd1-904a-439d-8dc7-ec4a097dc09e.png)

![image](https://user-images.githubusercontent.com/61082200/208818312-dbed805b-95fd-4792-89b0-c340b84bb7f9.png)

![image](https://user-images.githubusercontent.com/61082200/208818260-d750b0f2-18b0-4b54-80a3-b194340540c7.png)

## 你遇到什么问题了？
> 描述一下你遇到的问题
已完成订阅后，重复添加种子
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
你这个是恰好RSS任务跟订阅搜索任务同一时间在在运行了吧。
