### ISSUE TITLE
请教：如何只刮削中文演员名？

### ISSUE THREAD

**Issue by serenity666** [jxxghp/nas-tools#2611]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 原来的影库里有3000+电影，都是已经刮削好了的，但是jellyfin只有英文演员名，实在是蛋疼，我现在只想让Nastools帮我把中文演员名刮削好，能做到么，试过全部重新刮削，废了好大的劲，有蛮多需要手动刮削不说，有时候刮着刮着INFO文件也不刮了，海报图片也不刮了，只重命名文件，我估计是TMDB限制了。所以想在原有基础上只刮削中文演员名。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 对原来已刮削好的电影只刮削需要的资料。移动更名时能把已有的图片转移，同时根据原有INFO直接更新演员信息。

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
有个专门的项目是做这个事儿的，进群问问
