### ISSUE TITLE
Windows版打开报错，无法运行

### ISSUE THREAD

**Issue by kofzhanganguo** [jxxghp/nas-tools#2617]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: nastool_win_v2.7.2
>
> 环境: Windows 10
>

## 你遇到什么问题了？

![Snipaste_2022-12-21_21-04-03](https://user-images.githubusercontent.com/32073931/208912173-e40bf0d4-eac4-49bf-83e4-e9796f6fae23.jpg)

Windows版无法使用，打开软件报错。

**Comment by zero617** [comment]
同样

**Comment by kofzhanganguo** [comment]
不知道作者发布版本后，他自己测不测试一下，我看看是不是因为配置文件的关系，重新打开看看，不用以前的配置文件。

**Comment by kofzhanganguo** [comment]
测试的结果是，双击程序后，直接报错，连配置文件都不会释放了，全新运行的。nastool_win_v2.7.2版本无法运行。

**Comment by jxxghp** [comment]
已更新附件
