### ISSUE TITLE
同步目录监控无法自动监测

### ISSUE THREAD

**Issue by edhnt455** [jxxghp/nas-tools#262]
部署环境是群晖docker,版本号是1.4.2
![Snipaste_2022-06-10_15-53-37](https://user-images.githubusercontent.com/59108157/173018485-af7501e2-b240-47ff-9b61-97256443109f.png)
![Snipaste_2022-06-10_15-55-28](https://user-images.githubusercontent.com/59108157/173018640-fcc21f47-c814-4859-85a6-e0425e918a8e.png)
在文件夹添加新文件后没有任何反应，手动启动服务一切正常

**Comment by edhnt455** [comment]
就算关闭目录同步，使用监控下载软件目录也不行。监控目录的权限已添加everyone
![Snipaste_2022-06-10_16-00-02](https://user-images.githubusercontent.com/59108157/173019486-e04fba9b-2597-46df-beed-e253e71828d9.png)

**Comment by edhnt455** [comment]
目录映射配置
![Snipaste_2022-06-10_15-53-37](https://user-images.githubusercontent.com/59108157/173020063-db3c7ddb-4743-4404-84a7-7a097bb70588.png)
![Snipaste_2022-06-10_16-03-15](https://user-images.githubusercontent.com/59108157/173020078-f8a71663-a175-410e-a064-d91422eb3f39.png)

**Comment by jxxghp** [comment]
5分钟一个CD，还不行检查群里置顶或者WIKI的说明。

**Comment by edhnt455** [comment]
请问cd在哪里设置啊
