### ISSUE TITLE
观众站刷流任务提示RSS未下载到数据

### ISSUE THREAD

**Issue by SilenceEagle** [jxxghp/nas-tools#2620]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.2
>
> 环境: docker on qnap
> 
## 你遇到什么问题了？

> 观众（`Audiences`）刷流任务总是提示**RSS未下载到数据**，即使我把选种规则都选为全部还是不行，试了重新生成rss链接，也还是不行。但搜索是能搜出观众的资源来的。
>我今年最开始使用`nas-tools`的时候（应该是`2.1.x`版本）观众站是可以正常刷流的，后来突然就不行了，我一直以为是我的设置问题，但怎么尝试都不行，每次更新版本我也都试一下，还是不行。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 感觉类似的issue有这几个：
https://github.com/jxxghp/nas-tools/issues/1877
https://github.com/jxxghp/nas-tools/issues/1132

## 你期望的结果

> 观众站也可正常刷流

## 给出程序界面截图、后台运行日志或配置文件

日志提示：
![image](https://user-images.githubusercontent.com/28215838/208926034-eba751fa-110f-4c5f-a50f-6b8052ae3c61.png)
刷流任务设置：
![image](https://user-images.githubusercontent.com/28215838/208926272-94719513-05e6-46a4-9aff-c3f6c6cf643d.png)

可搜索到观众站点到资源：
![image](https://user-images.githubusercontent.com/28215838/208927189-683b1657-e0be-40d9-90d8-b041e70ab1b5.png)

**Comment by jxxghp** [comment]
一直都是正常的：
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/51039935/209030193-27f6b898-5011-49ba-a072-4bfbdcebb759.png">
