### ISSUE TITLE
对同一影片可以持续洗版直到下载到设定的分辨率特性

### ISSUE THREAD

**Issue by trott90** [jxxghp/nas-tools#2632]
NAStool 版本: v2.72
环境: docker 
对同一影片可以持续订阅洗版直到下载到设定的分辨率/特性，而不是一旦下载了就删除订阅
比如我有如下的下优先级（实际这个优先级借用过滤规则里的可能也可以）
1. UHD REMUX
2. BLURAY REMUX
3. 1080p X265
4.  1080p WED-DL
对于影片A，我设定的需求是BLURAY REMUX， 我第一次可能下周了1080p WED-DL， 第二次洗版了 1080p X265，这时影片一直回在订阅里，知道我洗版到了BLURAY REMUX， 这是才把订阅删除

可以参考radarr里的类似设计

**Comment by n0thing2speak** [comment]
+1

**Comment by cqboyone** [comment]
+2

**Comment by jxxghp** [comment]
已支持
