### ISSUE TITLE
如何整理蓝光原盘文件

### ISSUE THREAD

**Issue by hijackerfr** [jxxghp/nas-tools#2633]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.5.1
>
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> 如何转移蓝光原盘文件，日志中提示跳过蓝光原盘

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 转移蓝光原盘文件

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/107469886/209177248-fa8267ff-6e24-4507-b272-88963438d3d5.png)

**Comment by jxxghp** [comment]
原盘只支持单层目录，多层目录不支持。
