### ISSUE TITLE
希望增加当转移文件中包含字幕时不再通知ChineseSubFinder下载字幕的功能

### ISSUE THREAD

**Issue by missing233** [jxxghp/nas-tools#2634]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 当转移文件中包含字幕时不再通知ChineseSubFinder下载字幕

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
识别不了，CSF有这个功能。
