### ISSUE TITLE
API subscribe/add 中rss_rule参数不起作用

### ISSUE THREAD

**Issue by trott90** [jxxghp/nas-tools#2635]
NAStool 版本: 2.72
环境: docker
通过API添加订阅的时候，传递的rss_rule参数值不起作用，下面的例子里传递的参数是"洗版收藏",  但在nt里，电影订阅的过滤规则里显示的还是默认的"站点规则“

curl -X 'POST' \
  'http://192.168.2.10:3000/api/v1/subscribe/add' \
  -H 'accept: application/json' \
  -H 'Authorization: xxxs' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'name=Extraction%202&type=MOV&year=2023&tmdbid=697843&rss_rule=%E6%B4%97%E7%89%88%E6%94%B6%E8%97%8F'

**Comment by jxxghp** [comment]
这个接口的参数被改过，但是漏改了API，dev已修复。
另外，过滤规则要传规则组的ID
