### ISSUE TITLE
2.7.2windows版更新后无法查看站点管理里面的数据统计

### ISSUE THREAD

**Issue by wzsage** [jxxghp/nas-tools#2636]
![QQ截图20221223102805](https://user-images.githubusercontent.com/37926975/209259144-a70cd228-3240-4091-9892-86b5218efcb0.png)
更新完最新的windows版本后，发现其他功能正常，只有数据统计功能出现了问题，尝试过了更新cookie办法无效，查看日志内容如上，请问大佬该如何解决，感激不尽。

**Comment by 48542257** [comment]
不光是WIN版本。unraid docker版也是。站点资源打开空白。无法访问PT站点的资源。站点管理功能全部失效了。

**Comment by jxxghp** [comment]
v2.7.3修复
