### ISSUE TITLE
自动删种功能建议增加根据完成后多久进行删除

### ISSUE THREAD

**Issue by 91270** [jxxghp/nas-tools#2640]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.2
>
> 环境: docker 

## 你想要新增或者改进什么功能？

自动删种功能建议增加根据完成后多久进行删除

![image](https://user-images.githubusercontent.com/61639203/209304224-03f6d7d3-183c-4a87-b696-dee70af0b9ef.png)

**Comment by jxxghp** [comment]
做种时间不是吗？

**Comment by 91270** [comment]
做种时间，是从下载完以后开始计算的么？我这边观察我有些任务，在没有下载完成之前就被删除掉了，当时的删除规则只有按做种1小时删除这个规则

**Comment by jxxghp** [comment]
@Shurelol S大看看

**Comment by Shurelol** [comment]
做种时间，有完成时间的从完成时间开始算，没有的从添加时间开始算

即正在下载和辅种的种子从添加时间算

防止正在下载的种子误删建议删种规则里设置种子状态进行规避

**Comment by 91270** [comment]
也就是说 ，按照我以下的设置　，需要　做种时间 +　种子状态　同时满足才删除对么？
![image](https://user-images.githubusercontent.com/61639203/209677117-e01ef321-c922-4c8f-ae7a-b48c42035b1c.png)

**Comment by 91270** [comment]
> 做种时间，有完成时间的从完成时间开始算，没有的从添加时间开始算
> 
> 即正在下载和辅种的种子从添加时间算
> 
> 防止正在下载的种子误删建议删种规则里设置种子状态进行规避


也就是说 ，按照我以下的设置　，需要　做种时间 +　种子状态　同时满足才删除对么？　我先看看源码吧
![image](https://user-images.githubusercontent.com/61639203/209677117-e01ef321-c922-4c8f-ae7a-b48c42035b1c.png)
