### ISSUE TITLE
有几个问题想请教下

### ISSUE THREAD

**Issue by HiPupilxD-Hao** [jxxghp/nas-tools#2643]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 我不是矿神最新版本
>
> 环境: docker or windows or Synology
>群晖

## 你遇到什么问题了？

> 描述一下你遇到的问题
1.种子如果自身有问题下到一半不下，nas tool无法取消下载重新更新种子
2.同名电影和电视剧/动漫，无法正确下载电影，而下载的整个剧集
3.对于下载好的文件管理，无法查看哪些已经正确下载，只能通过emby/plex等软件查看，并且文件本地缺失，无法找到重新更新/下载选项

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 已donate，希望协助解决上述问题

**Comment by gh279760559** [comment]
问题1，2同样遇到，求解

**Comment by jxxghp** [comment]
说的太简单，没法给你分析。反馈问题请详细说明场景、流程，贴上日志截图。就这几个字猜不出你是什么情况。

这个软件本来就不支持的功能不要做为问题提交。
