### ISSUE TITLE
辅种转种

### ISSUE THREAD

**Issue by Litter-coder** [jxxghp/nas-tools#2644]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.1
>
> 环境: docker

## 你想要新增或者改进什么功能？
增加辅种转种服务

## 这个功能有什么可以参考的资料吗？

IYUU Plus

支持下载器配置多个，是否可以支持类似IYUU的辅种转种功能

**Comment by jxxghp** [comment]
用IYUU不香吗，没这必要吧。
