### ISSUE TITLE
torrentleech更新站点Cookie失败

### ISSUE THREAD

**Issue by hongshaoyi** [jxxghp/nas-tools#2648]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.7.2
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> torrentleech连通性测试正常的，但是更新cookie会失败，提示：torrentleech Chrome模拟访问失败
>如果开启浏览器仿真，那连通性测试将失败，更新cookie也会失败，修改user-agent也无法解决
>torrentleech无二次验证和验证码
>无额外日志
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 无相关问题

## 你期望的结果

> 修复此问题

## 给出程序界面截图、后台运行日志或配置文件

>
![image](https://user-images.githubusercontent.com/8248135/209434948-ed977e5f-dfcb-476a-93b6-3a0fbfc95a3a.png)
![image](https://user-images.githubusercontent.com/8248135/209434526-4da9023a-41d1-401f-9461-9d8b9d3f9a71.png)
![image](https://user-images.githubusercontent.com/8248135/209434923-81e538f1-3cdf-413d-b26e-13aeecc1beac.png)

**Comment by jxxghp** [comment]
可以成功，这个问题不存在
