### ISSUE TITLE
是否可以增加下这项功能呢

### ISSUE THREAD

**Issue by Wanderingkang** [jxxghp/nas-tools#2649]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v2.7.2 026c31d3
> 环境: docker or windows or synology
docker
## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
是否可以增加下载软件转移，当识别不到名称时，源文件名称转移呢？因为目录同步有时未下载完成，转移导致媒体服务器错误
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
下载软件设置加后缀
