### ISSUE TITLE
希望能从fanart刮削海报poster

### ISSUE THREAD

**Issue by RockyHalf** [jxxghp/nas-tools#2650]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v2.7.2
> 环境: docker or windows or synology
docker
## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
希望能在刮削的图片设置里面选择，图片的来源，目前默认的海报（poster）是从tmdb下载的，tmdb的海报很多都有复杂的中文和一些宣传的台标之类的元素，fanart的海报要美观很多，非常简洁。希望能从fanart的网站中刮削海报（poster）。
（如果可以的话最好能像emby一样可以按优先级排序，同时加入对语言的选择，一般来说英文的fanart海报最简洁好看）
谢谢
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
emby本身的刮削里面可以自己选择图片来源的优先级，海报的地区、语言等，其他不太清楚。

**Comment by jxxghp** [comment]
之前是从fanart拿的，有的人反馈不是中文，而且太丑，改回从TMDB拿。
审美因人而异，就这样，这个问题不要再提了。

**Comment by RockyHalf** [comment]
好吧。。能不能给一个选择的空间呢。。
