### ISSUE TITLE
检测的数据源不匹配

### ISSUE THREAD

**Issue by eeezae** [jxxghp/nas-tools#2657]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 最新
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

nastool检索数据结果，能检索出4条数据，但是提示不匹配，无任何返回
<img width="809" alt="image" src="https://user-images.githubusercontent.com/34007837/209458057-3700d02e-220b-46d5-a0f4-14020145f3f6.png">
<img width="435" alt="image" src="https://user-images.githubusercontent.com/34007837/209458116-0459ff39-7e77-459f-a14c-cd5759a76c9e.png">

实际结果可以搜到4个
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/34007837/209458073-3b99f272-5d07-4b7b-9240-baa4a1f56df8.png">

> 描述以下你期望的结果
希望能够正确检索出所需要的数据

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by yipapa** [comment]
你这个看起来应该是规则问题吧

**Comment by jxxghp** [comment]
你得贴日志

![image](https://user-images.githubusercontent.com/51039935/209467146-51496e61-5490-4796-b542-ab39e6fa3446.png)

**Comment by eeezae** [comment]
<img width="413" alt="image" src="https://user-images.githubusercontent.com/34007837/209850019-04b983ef-5c58-4501-98ec-e62265eccde0.png">
没有设置过滤规则，从过滤测试里测试的时候文件名都是匹配的上的。

**Comment by eeezae** [comment]
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/34007837/209850178-40d3e0aa-16b1-46d2-b34b-67b67bdf6cb4.png">
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/34007837/209850274-4260285d-ba51-4a6b-9b6b-ae652a22d8e8.png">

**Comment by eeezae** [comment]
测试的时候使用日常观影这个规则也是没有问题的，但是实际搜索的时候还是搜不出来，这个现象不只这一部片源和这一个站点

**Comment by eeezae** [comment]
docker重启过，刚刚拉了最新的版本
