### ISSUE TITLE
对于动漫剧场版的分类不正确

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [jxxghp/nas-tools#2658]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.2 026c31d3
>
> 环境: docker
>

## 你遇到什么问题了？

> 自动识别已经识别出了tmdbid但是应该是电影，分类却被识别为动漫，导致获取不了媒体信息，只能手动转移
![image](https://user-images.githubusercontent.com/78670748/209461019-166e37f1-b949-4dcc-96b0-e8bf77614d48.png)
![image](https://user-images.githubusercontent.com/78670748/209461032-2ff782f6-7fd5-4a25-ab44-2d8034eb58b3.png)
![image](https://user-images.githubusercontent.com/78670748/209461043-f45691f2-b4f5-4c91-bd73-962fc5d48bae.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 能够正确分类此类视频

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
把文件名贴一下

**Comment by SchrodingerBarbatos** [comment]
> 把文件名贴一下

[VCB-Studio] PSYCHO-PASS The Movie [Hi10p_1080p][x264_flac].mkv

**Comment by jxxghp** [comment]
> > 把文件名贴一下
> 
> 
> 
> [VCB-Studio] PSYCHO-PASS The Movie [Hi10p_1080p][x264_flac].mkv
> 
> 我这里使用了两个规则

把The Movie屏蔽掉
