### ISSUE TITLE
个别资源出现资源搜索未返回jackett的搜索结果的问题

### ISSUE THREAD

**Issue by edwardostara** [jxxghp/nas-tools#266]
1.此为nastools的日志
![msedge_vywa4LEUdb](https://user-images.githubusercontent.com/44975278/173117047-d317382b-5280-4317-aa58-925288945cac.png)
![ij5aUdvMEB](https://user-images.githubusercontent.com/44975278/173117070-5f814549-6720-4cab-a621-f6b31ee3afba.png)

2.此为Jackett的日志
![msedge_qOuEb09HjA](https://user-images.githubusercontent.com/44975278/173117116-9cab951a-1a7e-400c-8ca2-bdaa7def55c1.png)
3.总结：
站点资源名称（与豆瓣倒是一致）与tmdb名称不一致时，工具排除了jackett的搜索结果。个人建议，如果不打算优化，能否在最终匹配的资源结果为0时，给用户返回jackett的搜索结果呢？

**Comment by jxxghp** [comment]
选快速搜索就是不匹配
