### ISSUE TITLE
qbittorrent测试失败

### ISSUE THREAD

**Issue by kafuuchino-s** [jxxghp/nas-tools#2663]
## 你使用的 NAStool 是什么版本，什么环境？
> NAStool 版本: v2.7.2 026c31d3
>
> 环境: docker环境
>

## 你遇到什么问题了？

> 我碰到了qbittorrent一直失败的问题，我的qbittorrent版本是4.1.9

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 搜索过Issues都说是环境问题，但我同样在一个ip地址的jellyfin可以正常链接，qbittorent却一直测试失败

## 你期望的结果

> 我希望能正常链接qbittorrent

## 给出程序界面截图、后台运行日志或配置文件

> ![image](https://user-images.githubusercontent.com/51790568/209479146-7f3a0ed7-e24e-408b-ac91-3b79a885d35d.png)
![image](https://user-images.githubusercontent.com/51790568/209479150-1ffe85dc-5db1-4e15-8e89-b47c598e460d.png)
![image](https://user-images.githubusercontent.com/51790568/209479156-909f2537-f8a8-4fca-8a36-d776aaff316a.png)
![image](https://user-images.githubusercontent.com/51790568/209479164-a3137e9f-d97b-4d58-9047-8f95c4e5db78.png)

以下是docker的日志
`stderr: 2022-12-26 02:51:47,783	ERROR: 【DownloaderType.QB】qBittorrent连接出错：èº«ä»½è®¤è¯å¤±è´¥æ¬¡æ°è¿å¤ï¼æ¨ç IP å°åå·²è¢«å°ç¦ã
stdout: Exception: èº«ä»½è®¤è¯å¤±è´¥æ¬¡æ°è¿å¤ï¼æ¨ç IP å°åå·²è¢«å°ç¦ã
stdout: Callstack:
stdout:   File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
stdout:     self._bootstrap_inner()
stdout:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
stdout:     self.run()
stdout:   File "/usr/lib/python3.10/threading.py", line 953, in run
stdout:     self._target(*self._args, **self._kwargs)
stdout:   File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread
stdout:     self.finish_request(request, client_address)
stdout:   File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
stdout:     self.RequestHandlerClass(request, client_address, self)
stdout:   File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
stdout:     self.handle()
stdout:   File "/usr/lib/python3.10/site-packages/werkzeug/serving.py", line 363, in handle
stdout:     super().handle()
stdout:   File "/usr/lib/python3.10/http/server.py", line 433, in handle
stdout:     self.handle_one_request()
stdout:   File "/usr/lib/python3.10/http/server.py", line 421, in handle_one_request
stdout:     method()
stdout:   File "/usr/lib/python3.10/site-packages/werkzeug/serving.py", line 335, in run_wsgi
stdout:     execute(self.server.app)
stdout:   File "/usr/lib/python3.10/site-packages/werkzeug/serving.py", line 322, in execute
stdout:     application_iter = app(environ, start_response)
stdout:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2095, in __call__
stdout:     return self.wsgi_app(environ, start_response)
stdout:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
stdout:     response = self.full_dispatch_request()
stdout:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
stdout:     rv = self.dispatch_request()
stdout:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
stdout:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
stdout:   File "/nas-tools/web/main.py", line 105, in login_check
stdout:     return func(*args, **kwargs)
stdout:   File "/nas-tools/web/main.py", line 1037, in do
stdout:     return WebAction().action(cmd, data)
stdout:   File "/nas-tools/web/action.py", line 205, in action
stdout:     return func(data)
stdout:   File "/nas-tools/web/action.py", line 1485, in __test_connection
stdout:     module_obj.init_config()
stdout:   File "/nas-tools/app/downloader/download_client.py", line 26, in init_config
stdout:     self.connect()
stdout:   File "/nas-tools/app/downloader/client/qbittorrent.py", line 39, in connect
stdout:     self.qbc = self.__login_qbittorrent()
stdout:   File "/nas-tools/app/downloader/client/qbittorrent.py", line 61, in __login_qbittorrent
stdout:     ExceptionUtils.exception_traceback(err)
stdout: Traceback (most recent call last):
stdout:   File "/nas-tools/app/downloader/client/qbittorrent.py", line 55, in __login_qbittorrent
stdout:     qbt.auth_log_in()
stdout:   File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/auth.py", line 96, in auth_log_in
stdout:     self._post(_name=APINames.Authorization, _method="login", data=creds, **kwargs)
stdout:   File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 350, in _post
stdout:     return self._request_manager(
stdout:   File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 401, in _request_manager
stdout:     return self._request(**kwargs)
stdout:   File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 463, in _request
stdout:     self._handle_error_responses(data, params, response)
stdout:   File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 644, in _handle_error_responses
stdout:     raise Forbidden403Error(response.text)
stdout: qbittorrentapi.exceptions.Forbidden403Error: èº«ä»½è®¤è¯å¤±è´¥æ¬¡æ°è¿å¤ï¼æ¨ç IP å°åå·²è¢«å°ç¦ã
stderr: 2022-12-26 02:51:47,959	ERROR: 【DownloaderType.QB】qBittorrent连接出错：èº«ä»½è®¤è¯å¤±è´¥æ¬¡æ°è¿å¤ï¼æ¨ç IP å°åå·²è¢«å°ç¦ã`

**Comment by jxxghp** [comment]
你把日志乱码的问题解决就知道什么原因了
