### ISSUE TITLE
> > 北洋和🦭已经适配了 方便截图看下数据状态么

### ISSUE THREAD

**Issue by 48542257** [jxxghp/nas-tools#2664]
> > 北洋和🦭已经适配了 方便截图看下数据状态么
> 
> 北洋和北邮是我cookies没配置好的问题，天雪还不行

hello，请问下北洋园的cookies应该怎么配置呢，我在站点管理里面能够测试通过，但是数据统计里面是空的。

_Originally posted by @maxin-cn in https://github.com/jxxghp/nas-tools/issues/450#issuecomment-1364684785_
      最新版有问题MT正常。PTHOME看不到资源。

**Comment by maxin-cn** [comment]
> ```
>     > > 北洋和🦭已经适配了 方便截图看下数据状态么
> ```
> 
> > 北洋和北邮是我cookies没配置好的问题，天雪还不行
> 
> hello，请问下北洋园的cookies应该怎么配置呢，我在站点管理里面能够测试通过，但是数据统计里面是空的。
> 
> _Originally posted by @maxin-cn in [#450 (comment)](https://github.com/jxxghp/nas-tools/issues/450#issuecomment-1364684785)_ 最新版有问题MT正常。PTHOME看不到资源。

另外，我也无法从北洋园下载，请问下你那边可以下载吗，我用的nastools是最新版本。https://github.com/jxxghp/nas-tools/issues/2128#issuecomment-1364514835

**Comment by 48542257** [comment]
这版本有问题。等大佬修复把。

**Comment by maxin-cn** [comment]
> 这版本有问题。等大佬修复把。

@48542257 我看作者更新一个版本，请问下您那边北洋园可以下载和查看数据统计吗？我这边依旧不行

**Comment by 48542257** [comment]
还是有问题。修的MT都打不开了

**Comment by 48542257** [comment]
修复修的问题更大了感觉

**Comment by maxin-cn** [comment]
@jxxghp 辛苦作者抽时间看看~

**Comment by maxin-cn** [comment]
> 修复修的问题更大了感觉

@48542257 我这里似乎可以在nastools里面使用北洋园下载了，但是数据统计还是空的，请问下您之前是怎么配置数据统计这一项的呢？

**Comment by 48542257** [comment]
@maxin-cn 数据统计只要配置好PT站点就会出现。我的PTHOME   MT还是无法打开。

**Comment by 48542257** [comment]
@maxin-cn 找到问题所在了。需要重新打开网页F12那样获取新的COOKIE.替换旧的就可以了。

**Comment by maxin-cn** [comment]
> @maxin-cn 找到问题所在了。需要重新打开网页F12那样获取新的COOKIE.替换旧的就可以了。

好的，多谢，我尝试下
