### ISSUE TITLE
新版本从搜索结果添加下载持续失败

### ISSUE THREAD

**Issue by rainow** [jxxghp/nas-tools#267]
现象：资源搜索结果正常（普通搜索），点击添加下载后提示添加成功但TR后台未显示任务，持续多个任务复现。

日志：
09:06:13 INFO - 【WEB】共检索到 19 个有效资源
09:06:13 INFO - 【WEB】分组择优后剩余 19 个有效资源
09:06:26 INFO - 【PT】添加PT任务：http://192.168.xx.xx:xxxx/dl/audiences/?jackett_apikey=xxxxxx&path=Q2ZESjhOVmt5MHlrTFlWSmhsaG9uUmFoSHc3bXJTMlpYZUZmV0VWU2RRTU4xTnRFb3hXdzE4cW1vb2NKSVJ1UVhObEpab2tnbVUzamc0aWtlMzBIaWFyeWFNQlBuVDJGV1J4bHBCSVBBSnkxUWhMV2VBS3ZkLW5DelVzd2dDbzYtZUo5cmNkd1hVR2drVHFpV21yT0d4U0RRMUJRQ0ZxYUthU25ZcG14ZHV4Q0xBSko&file=A+Dream+of+Splendor+S01E17-E18+2022+2160p+WEB-DL+H265+AAC-ADWeb
09:06:27 ERROR - 【PT】添加PT任务 http://192.168.xx.xx:xxxx/dl/audiences/?jackett_apikey=xxxxxxx&path=Q2ZESjhOVmt5MHlrTFlWSmhsaG9uUmFoSHc3bXJTMlpYZUZmV0VWU2RRTU4xTnRFb3hXdzE4cW1vb2NKSVJ1UVhObEpab2tnbVUzamc0aWtlMzBIaWFyeWFNQlBuVDJGV1J4bHBCSVBBSnkxUWhMV2VBS3ZkLW5DelVzd2dDbzYtZUo5cmNkd1hVR2drVHFpV21yT0d4U0RRMUJRQ0ZxYUthU25ZcG14ZHV4Q0xBSko&file=A+Dream+of+Splendor+S01E17-E18+2022+2160p+WEB-DL+H265+AAC-ADWeb 出错：Method "torrent-set" Argument "labels" does not exist in version 15.
09:06:28 INFO - 【MSG】发送wechat消息：title=梦华录 (2022) S01 E17-E18, text=WEB搜索的电视剧 梦华录 (2022)S01 E17-E18 已开始下载 ……

搜索结果：
![Screenshot_20220611_091028](https://user-images.githubusercontent.com/7533065/173167549-190d4081-df1a-4fb4-9955-e3c300275a15.jpg)

**Comment by lightolly** [comment]
tr是什么版本的？

**Comment by rainow** [comment]
> tr是什么版本的？

2.94，群晖套件版
![Screenshot_20220611_121001](https://user-images.githubusercontent.com/7533065/173172018-fce28f6c-b4e8-469e-b7e1-719f0292e18d.jpg)

**Comment by lightolly** [comment]
pt监控关掉看看？ 3.0以下版本tr不支持pt监控

**Comment by rainow** [comment]
> pt监控关掉看看？ 3.0以下版本tr不支持pt监控

用的目录同步，没开PT监控啊
![Screenshot_20220611_135213](https://user-images.githubusercontent.com/7533065/173175143-917ea1ef-89bb-46ec-a3df-6bce718bf8e9.jpg)

**Comment by rainow** [comment]
升新版本之前下载是正常的

> pt监控关掉看看？ 3.0以下版本tr不支持pt监控

**Comment by jxxghp** [comment]
是因为你开了只管理NASTOOL的开关啊，就会使用TAG，但你的TR版本太老不支持TAG。跟版本没关系！

**Comment by rainow** [comment]
> 



> 是因为你开了只管理NASTOOL的开关啊，就会使用TAG，但你的TR版本太老不支持TAG。跟版本没关系！

确实是，关了以后就正常了，感谢
