### ISSUE TITLE
用内建索引器下载frds（朋友）的种子失败

### ISSUE THREAD

**Issue by zhui22222** [jxxghp/nas-tools#2670]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 矿神2.7.1套件
>
> 环境: Synology
>

## 你遇到什么问题了？

> 下载朋友站点的资源会报错：
![1672039784291](https://user-images.githubusercontent.com/74883989/209519132-a3f1d88d-c96e-4c52-b165-e7f9045c0878.png)
![1672039820367](https://user-images.githubusercontent.com/74883989/209519282-651d4d0a-8437-488e-bca4-1978f28cea10.png)
估计朋友的机制不同，上图的这个种子链接点开后会跳转到https://pt.keepfrds.com/downloadnotice.php?torrentid=1976077&type=firsttime，而不会直接下载种子。

**Comment by jxxghp** [comment]
你要手工去站点下一次种子才能自动下载

**Comment by zhui22222** [comment]
不是这个原因，其他站点用这样的链接事可以直接下载的，只有朋友不行，朋友的每次都只能点开种子详情页才能下载，是每次，不是第一次了

**Comment by zhui22222** [comment]
我觉得完整的链接应该是：https://pt.keepfrds.com/downloadnotice.php?torrentid=1976077&passkey=XXXX

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/209523088-3d35a693-42ac-427c-851e-2e576640febd.png)
没问题，能正常下载

**Comment by zhui22222** [comment]
可以了，谢谢
