### ISSUE TITLE
更新2.7.2 Pushplus推送消息显示参数未配置

### ISSUE THREAD

**Issue by sently** [jxxghp/nas-tools#2676]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.2-2.7.3
>
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 更新后，pushplus的推送消息显示参数未配置，无法进行推送，测试也是失败。2.7.3也未修复该问题。

## 你期望的结果

> 希望修复问题

## 给出程序界面截图、后台运行日志或配置文件

>

**Comment by CD-D** [comment]
好家伙 我以为是我配置问题 原来都是这样呀
![image](https://user-images.githubusercontent.com/35326452/209565155-31b87129-67e1-4324-865e-cd17f4e2a152.png)

**Comment by CD-D** [comment]
> 好朋友我以为是我配置问题原来都是这样呀 ![图片](https://user-images.githubusercontent.com/35326452/209565155-31b87129-67e1-4324-865e-cd17f4e2a152.png)
补充配置
![image](https://user-images.githubusercontent.com/35326452/209565202-9fe21c7e-4519-4f37-8ac6-bfd9068ee3d3.png)
