### ISSUE TITLE
Qbittorren下载文件权限问题

### ISSUE THREAD

**Issue by tubuxing** [jxxghp/nas-tools#2682]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.1
>
> 环境: Synology 之 docker  （也安装过矿）
>
> qb 和emby 目录结构 media/qb 和 media/emby ：外接移动硬盘
>

## 你遇到什么问题了？

> Qbittorren下载好的文件无法同步到emby  日志提示 { 文件转移失败，错误码 -1 }
>
> 经过实验查找发现是qb下载后文件夹权限被设置 为 qbittorren 导致 同步失败。重新设置文件权限即可同步成功
> 
> 将qb 下载目录设置为主硬盘，以上问题也存在。
>

## 你期望的结果

> 如果每次需要修改权限才能执行同步，略显多余。求解决办法

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
qb的权限跟这个项目有什么关系？

**Comment by tubuxing** [comment]
因为，  订阅到下载到目录同步，自动化操作，到同步目录就因为qb下载创建文件设置了qb权限,导致同步出错。所以全程无法做到自动化操作。如果在同步目录前，重置一下因qb下载插件文件的权限。

**Comment by tubuxing** [comment]
> qb的权限跟这个项目有什么关系？

因为，  订阅到下载到目录同步，自动化操作，到同步目录就因为qb下载创建文件设置了qb权限,导致同步出错。所以全程无法做到自动化操作。如果在同步目录前，重置一下因qb下载插件文件的权限。
