### ISSUE TITLE
HDChina更新站点Cookie失败 

### ISSUE THREAD

**Issue by Yasin27878** [jxxghp/nas-tools#2683]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 
> v2.7.3
> 环境:
>  docker

## 你遇到什么问题了？

> 站点管理-站点维护中 更新HDChina站点cookie的失败，其他MT，柠檬等都正常

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已查找，未找到相同问题

## 你期望的结果

> 能够正常更新cookie

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/10019889/209599877-5b42560c-6d4c-4e16-9b45-ebde6e11923e.png">

> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
HDC的不是图形验证码，没法支持
