### ISSUE TITLE
动漫电影：”鬼灭之刃 无限列车篇“手动识别在tmdb等信息输入正确下仍然识别有误

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#269]
<img width="572" alt="1654933781860" src="https://user-images.githubusercontent.com/39802246/173178890-89857935-29bf-4dc6-9977-867de5a6eeb5.png">
<img width="1011" alt="1654933713628" src="https://user-images.githubusercontent.com/39802246/173178894-8f5af708-3c54-4bf2-95f9-859bd3553072.png">

所有信息都填入并且正确的情况下 不知道为啥 手动识别仍然有误 不知道是不是识别bug

**Comment by dlovew** [comment]
你的tmdb id不对，635302才是

**Comment by Tartarus2014** [comment]
https://www.themoviedb.org/tv/154634-flame-hashira-kyojuro-rengoku?language=zh-SG

这个就是啊

**Comment by Tartarus2014** [comment]
> 你的tmdb id不对，635302才是

https://www.themoviedb.org/tv/154634-flame-hashira-kyojuro-rengoku?language=zh-SG 

就是这个

**Comment by dlovew** [comment]
tv和电影你搞清楚了么？

**Comment by Tartarus2014** [comment]
> tv和电影你搞清楚了么？

还真是 谢谢
