### ISSUE TITLE
对{episode_title}的改进

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [jxxghp/nas-tools#2691]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.3 64504ab2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> {episode_title}对于tmdb一些没有名字的依然是第n集之类的能否做个屏蔽，标题名为第n集时不生效，这样重命名就不会有两个第n集
![image](https://user-images.githubusercontent.com/78670748/209625367-47e3ed71-de01-4f8a-b963-634e1eb29573.png)
![image](https://user-images.githubusercontent.com/78670748/209625174-4b742e8f-09e4-4697-8f20-d76bb9618879.png)
![image](https://user-images.githubusercontent.com/78670748/209625155-09e1bd86-79c5-4910-abfd-56d160983787.png)

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

感谢作者大大无私的奉献

**Comment by jxxghp** [comment]
后面那个第X集是自己配置的呀，你完全可以不配。
```
# 电视剧默认命名格式
DEFAULT_TV_FORMAT = '{title} ({year})/Season {season}/{title} - {season_episode}-{part} - 第 {episode} 集'
```

**Comment by SchrodingerBarbatos** [comment]
> 后面那个第X集是自己配置的呀，你完全可以不配。
> 
> ```
> # 电视剧默认命名格式
> DEFAULT_TV_FORMAT = '{title} ({year})/Season {season}/{title} - {season_episode}-{part} - 第 {episode} 集'
> ```

好的谢谢
