### ISSUE TITLE
手动识别增加批量选择

### ISSUE THREAD

**Issue by verity886** [jxxghp/nas-tools#2694]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.3
>
> 环境: docker 

## 你想要新增或者改进什么功能？

媒体管理>手动识别里记录太多，有上千条，但大部分不需要识别（例如动画原盘里的特典之类的），删除记录只能一个个选择再批量删除，无法批量选择

**Comment by jxxghp** [comment]
标题栏难道没有一个勾选框？

**Comment by verity886** [comment]
> 标题栏难道没有一个勾选框？

是我没表达清楚，我只想删除其中的一部分，例如1700条中的1200条，手动识别栏里也没有分页，勾选框一选就是全部了

**Comment by verity886** [comment]
另外还想提一个建议，手动识别里再增加一个批量手动识别，现在只能批量自动识别
主要的意义是，某些种子文件大包，会把一些动画的所有季度全放在一个目录里，同时这个文件自动识别又无法识别出来的时候，例如下图
![image](https://user-images.githubusercontent.com/37663967/209789409-9853e5d1-0ad9-406a-8b98-904946a497b6.png)
高智能方程式的saga和sin分别为不同两季，但在同一个目录，所以文件管理里面的转移目录也不行。无论是手动识别抑或是文件管理都只能手动一集集转移
