### ISSUE TITLE
签到问题

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#2696]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？
> 描述一下你遇到的问题
站点管理处 没有开启签到的站点，会依然给签到

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果
> 描述以下你期望的结果
能按照设置所签到

## 给出程序界面截图、后台运行日志或配置文件
![C389F966-1870-4A62-8955-1A0269E6E88C](https://user-images.githubusercontent.com/39802246/209744474-5f2362ae-4410-4947-a9f2-221dd6ce63a7.jpeg)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
这个改好了
