### ISSUE TITLE
刷流任务添加开关选项

### ISSUE THREAD

**Issue by xushier** [jxxghp/nas-tools#2698]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.6.3
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
目前的刷流任务没有开关选项，添加了就运行。实际使用中有时候需要停止刷流，过一段时间再启动刷流，所以可以对任务增加一个开关。
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/209753833-c9a0b0e0-1341-4ee6-9eff-f42e1540422c.png)
