### ISSUE TITLE
部分媒体整理历史记录无法删除

### ISSUE THREAD

**Issue by Hefaang** [jxxghp/nas-tools#2699]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.3
>
> 环境: docker
>

## 你遇到什么问题了？

> 少量媒体整理历史记录无法删除
媒体库中的2部电视剧，在已删除源文件和硬链接文件的情况下，无法删除媒体整理的识别记录。
点击删除后仍然存在。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 彻底删除不需要的媒体整理历史记录。

## 给出程序界面截图、后台运行日志或配置文件

>
![1](https://user-images.githubusercontent.com/116775696/209778806-cbed4e94-f622-4f42-9695-cf805426e1cc.png)

[run.txt](https://github.com/jxxghp/nas-tools/files/10312968/run.txt)

**Comment by jxxghp** [comment]
这种多季合集的历史记录目前无法处理，新产生的历史记录已经不会有问题。
可以备份然后恢复备份，所以历史记录都会清掉。

**Comment by Hefaang** [comment]
感谢解答！
