### ISSUE TITLE
建议：增加手动添加下载任务功能

### ISSUE THREAD

**Issue by firstvip** [jxxghp/nas-tools#270]
有很多从非pt站获取的种子用qb或tr下载后还需要重命名、整理、归类等而这恰是nastools的优势。
建议增加手动添加下载任务功能，可上传种子文件或提交磁力链。提交时可以考虑输入影视剧名字或imdb的ID。
个人认为这和qb或tr中的功能不是重复的，因为nastools提交下载任务后还会自动进行重命名、整理、归类、转移等动作，而qb或tr不容易实现。

**Comment by 26712681** [comment]
你监控了下载目录  管你从哪里下载  不是都实现了整理归类吗

**Comment by jxxghp** [comment]
> 你监控了下载目录  管你从哪里下载  不是都实现了整理归类吗

正解

**Comment by jxxghp** [comment]
临控下载目录或者监控下载软件都会自动硬链接和重命名的。

**Comment by firstvip** [comment]
[我一直选择了监控下载软件。
然后在qb中添加了一个磁力链任务，分类选择的电影。
qb下载的时候在nastools的正在下载中可以看到。
但是当下载完成之后，nastools的正在下载、近期下载以及手动识别、历史记录中都没有这个任务文件，也就不会重命名和链接。
是我哪里弄错了吗？

**Comment by firstvip** [comment]
![1](https://user-images.githubusercontent.com/41404652/173194439-8c56b455-5feb-443a-8774-9ddb3c6b5e27.JPG)
![2](https://user-images.githubusercontent.com/41404652/173194451-77ad721d-c8db-4501-b34e-fc05ef510b68.JPG)
![4](https://user-images.githubusercontent.com/41404652/173194458-cb379e66-4d72-4eb6-90e5-6c57e9ad8ebd.JPG)
![5](https://user-images.githubusercontent.com/41404652/173194464-b5198c96-c2ca-4b96-a520-383f13bac922.JPG)

**Comment by firstvip** [comment]
或者如果用监控目录的话是不是应该设置同步目录呀
![6](https://user-images.githubusercontent.com/41404652/173194500-187b8de3-c73b-46aa-a8ed-588dccc1ad96.JPG)
