### ISSUE TITLE
admin用户无法删除或修改密码

### ISSUE THREAD

**Issue by sfwilp** [jxxghp/nas-tools#2701]
V2.7.3
全新安装V2.7.3后使用admin用户及默认密码可以登录，但无法修改密码，添加自定义用户后用户列表也没有admin用户，无法删除，存在安全隐患。

**Comment by jxxghp** [comment]
无法修改密码？

**Comment by sfwilp** [comment]
> 
是我的问题，只看了用户管理界面，忘记了基础设置里面可以修改。
