### ISSUE TITLE
{episode_title}的识别逻辑问题

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [jxxghp/nas-tools#2704]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.3 3f8f5920
>
> 环境: docker
>

## 你遇到什么问题了？

> 这里nastools识别命名为第一季，但是 {episode_title}对于文件的重命名为特别篇（S0）的命名，貌似 {episode_title}是对原始文件名的识别，因为这里没有标明季数，不是对于识别后的对应集数的识别
![image](https://user-images.githubusercontent.com/78670748/209808854-818ee609-2bf7-4a1e-b980-f575f3d1c423.png)
![image](https://user-images.githubusercontent.com/78670748/209809237-251efe1b-e468-42b2-a2aa-8673a472b8b8.png)
![image](https://user-images.githubusercontent.com/78670748/209809262-56812228-cec8-4080-ac0c-4772e203b5e9.png)
![image](https://user-images.githubusercontent.com/78670748/209809294-cafbc118-e524-43e2-ac25-cd09e72a80e0.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 正确重命名为对应的名字

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
逻辑没问题，是名称中没有季的信息默认取第0季了，已修复

**Comment by SchrodingerBarbatos** [comment]
> 逻辑没问题，是名称中没有季的信息默认取第0季了，已修复

嗯嗯我表达的是这个意思，可能没描述清楚，感谢修复
