### ISSUE TITLE
下载设置默认设置

### ISSUE THREAD

**Issue by Wangsc1** [jxxghp/nas-tools#2712]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.3
>
> 环境: docker

## 你想要新增或者改进什么功能？
下载设置这边能否把自定义的设置设置成默认，因为默认的下载设置没有速度限制，有些站上传限制的低，每次手动下载影片都要再选择一下，大佬能否优化下🙏
![image](https://user-images.githubusercontent.com/26079238/209892338-af468f50-a915-4492-a2ee-68022d6c42b3.jpeg)

**Comment by boweic** [comment]
希望可以分站点设置默认的下载设置，从而达到不同站点上传限制不同的目的。

**Comment by jxxghp** [comment]
fa1150be54c16471a9e77c2379dca66bfe4b898b
