### ISSUE TITLE
更加细分化刮削视频配套信息

### ISSUE THREAD

**Issue by Aqr-K** [jxxghp/nas-tools#2719]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 细分刮削视频配套信息，像tmm刮削器一样细分化选择
有些视频的视频已经更新了，但是tmdb上还没更新，如单集简介或者单集名还没更新等，能否通过更加细分化的刮削选择，去掉不需要的部分，让显示出来的资料更美观，现在视频有很多是上一集刮削到了简介，下一集没有

## 这个功能有什么可以参考的资料吗？

> 类似tmm刮削器类型

**Comment by jxxghp** [comment]
说的太粗糙了，不理解要干啥

**Comment by Aqr-K** [comment]
> 说的太粗糙了，不理解要干啥
就是细分化这个元数据的刮削，把基础信息拆分成跟tmm搜刮器那种更加多元化的选择，可以减少媒体播放器扫描数据库重新刮削而导致的性能的占用，和不必要的后期二次手动刮削
![image](https://user-images.githubusercontent.com/95741669/209952592-f43f10cc-cd62-4ad4-a4c9-621499c2fecf.png)
下面的是刮削出现的问题
![image](https://user-images.githubusercontent.com/95741669/209953186-97b66f1b-bb61-47c0-85ae-c8a76f01e75f.png)
tmm刮削器的分类方式
电影类
![image](https://user-images.githubusercontent.com/95741669/209953977-e8275c9f-66af-44bc-80a5-25506e1f2488.png)
剧集与动漫等类
![image](https://user-images.githubusercontent.com/95741669/209954126-4b7e20be-e623-4cfe-9fb7-cc9fb85f3447.png)

**Comment by Aqr-K** [comment]
图片其实没问题，可以直接提取当前集里的截图。主要还是文本类的刮削，tmdb是没法做到全部实时更新的，所以能不能做到细分化选择，然后针对性去除不要的文本刮削，比如单集介绍啥的
