### ISSUE TITLE
微信自动下载失败，实际搜索正常

### ISSUE THREAD

**Issue by log-time** [jxxghp/nas-tools#272]
![Screenshot_2022-06-11-23-03-01-418_com tencent mm](https://user-images.githubusercontent.com/66826612/173193271-3ce16ec4-3376-414e-a270-cb4df45197bd.jpg)
![Screenshot_2022-06-11-23-04-28-441_myapp naszhushou](https://user-images.githubusercontent.com/66826612/173193315-eae36aec-9881-4d4a-beec-1677dc8f2a8f.jpg)

微信自动下载失败，实际搜索正常

**Comment by log-time** [comment]
是因为精确匹配的原因？

**Comment by jxxghp** [comment]
微信是自动下载的，名字要完全一致。
