### ISSUE TITLE
刷流任务里 包含 关键字功能无效

### ISSUE THREAD

**Issue by Dreamray** [jxxghp/nas-tools#2723]
> NAStool 版本: 2.7.3
> 环境: windows

> 刷流任务里 包含 关键字功能无效，比如猫站，包含  输入框内填 “PTer” （不含引号），但是添加了不含PTer的种子。目前只发现猫站有这个情况。

**Comment by jxxghp** [comment]
举例子，刷流任务的设置，种子标题跟描述

**Comment by Dreamray** [comment]
> 举例子，刷流任务的设置，种子标题跟描述

编辑任务

任务名称
pter
站点

pter
刷新间隔(分钟) 
4
下载器 

qb
保种体积(GB) 
状态

正常
选种规则
促销 

免费
Hit&Run

全部
同时下载任务数 
2
包含 
PTer
排除 
关键字或正则表达式
上传限速（KB/S） 
下载限速（KB/S） 
12288
种子大小(GB) 
5,500
做种人数限制 
3
发布时间（小时） 
0.1
以上是我复制的刷流任务设置
这是被添加的种子标题和副标题：
Dorogoy moy chelovek 1958 PAL DVD9
我亲爱的人 / My Dear Fellow! / 亲爱的人 / Dorogoy moy chelovek | 类别：剧情 爱情
