### ISSUE TITLE
建议消息推送增加对vocechat的支持

### ISSUE THREAD

**Issue by kyuuketsu** [jxxghp/nas-tools#2725]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.3 3f8f5920
> 环境: docker

## 你想要新增或者改进什么功能？
希望消息推送增加对vocechat的支持。vocechat是一款轻量的可以部署在nas上面的聊天应用软件，使用自己的聊天工具更加方便和隐私。现在这个软件也支持机器人和Webhook功能了。

## 这个功能有什么可以参考的资料吗？
关于vocechat的介绍
官网：https://voce.chat/
官方文档：https://doc.voce.chat/zh-cn/
官方 Demo： https://privoce.voce.chat/
开源地址：https://github.com/Privoce/vocechat-web

**Comment by jxxghp** [comment]
不能交互的话算了
