### ISSUE TITLE
启动定时服务失败

### ISSUE THREAD

**Issue by shaoyz2007** [jxxghp/nas-tools#2726]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.3
>
> 环境: docker 
启动定时服务失败：'CST-8' - Traceback (most recent call last): File "/nas-tools/app/scheduler.py", line 248, in run_scheduler Scheduler().run_service() File "/nas-tools/app/scheduler.py", line 45, in run_service self.SCHEDULER = BackgroundScheduler(timezone=Config().get_timezone(), File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 87, in __init__ self.configure(gconfig, **options) File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 131, in configure self._configure(config) File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/background.py", line 29, in _configure super(BackgroundScheduler, self)._configure(config) File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 701, in _configure self.timezone = astimezone(config.pop('timezone', None)) or get_localzone() File "/usr/lib/python3.10/site-packages/apscheduler/util.py", line 91, in astimezone return timezone(obj) File "/usr/lib/python3.10/site-packages/pytz/__init__.py", line 188, in timezone raise UnknownTimeZoneError(zone) pytz.exceptions.UnknownTimeZoneError: 'CST-8'

**Comment by jxxghp** [comment]
时区不对
