### ISSUE TITLE
RSS解析器里的蜜柑RSS配置如何恢复

### ISSUE THREAD

**Issue by Otiguy** [jxxghp/nas-tools#2727]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x

2.7.3
> 环境: docker or windows or Synology

群晖 docker

## 你遇到什么问题了？

> 描述一下你遇到的问题

RSS解析器里的蜜柑配置被我删了，想问怎么恢复或者正确设置？

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

搜索过

## 你期望的结果

> 描述以下你期望的结果

恢复蜜柑配置或想知道如何使用rss解析器里的蜜柑配置

## 给出程序界面截图、后台运行日志或配置文件
![Snipaste_2022-12-31_13-29-44](https://user-images.githubusercontent.com/48633984/210126172-4412c855-7085-4a0b-875c-9bed0a083e64.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
跟通用是一样的
