### ISSUE TITLE
关于完善tmdb刮削视频配套信息时，会出现的因为tmdb没有实时更新出现的问题

### ISSUE THREAD

**Issue by Aqr-K** [jxxghp/nas-tools#2730]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.3
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 有很多剧集类的会因为更新问题，提前留好了集数，但他的简介做不到实时更新，这就导致有很多时候这一集一大段简介，下一集啥也没有，很多大洞，能不能把基础信息细分成剧集名、简介、单集名、原名等等，多元化选择，直接去掉简介不刮削
就是细分化这个元数据的刮削，把基础信息拆分成跟tmm搜刮器那种更加多元化的选择，可以减少媒体播放器扫描数据库重新刮削而导致的性能的占用，和不必要的后期二次手动刮削
![image](https://user-images.githubusercontent.com/95741669/209952592-f43f10cc-cd62-4ad4-a4c9-621499c2fecf.png)
下面的是刮削出现的问题
![image](https://user-images.githubusercontent.com/95741669/209953186-97b66f1b-bb61-47c0-85ae-c8a76f01e75f.png)

还有个小提议，能否添加一个默认单集名字，如s01e01或者第一集、第二集啥的，因为还有的剧集类可能编辑的人员不是很多，就不会提前留好集数，这就导致有时候因为这一集在tmdb上什么都没有，自动变成了奇奇怪怪的名字
下图是tmdb没有任何刮削资料时，自动赋予的单集名字
![image](https://user-images.githubusercontent.com/95741669/210133047-b2f62c1b-5f0f-46da-a1f9-e3aebd1a40ae.png)

## 这个功能有什么可以参考的资料吗？

> 可以参考tmm刮削器的刮削设置分类
tmm刮削器的分类方式
电影类
![image](https://user-images.githubusercontent.com/95741669/209953977-e8275c9f-66af-44bc-80a5-25506e1f2488.png)
剧集与动漫等类
![image](https://user-images.githubusercontent.com/95741669/209954126-4b7e20be-e623-4cfe-9fb7-cc9fb85f3447.png)

**Comment by Shurelol** [comment]
一部剧，如果单集下载时，tmdb上没有简介，那么不论生成的nfo里写不写简介，在导入到媒体服务器如emby里之后，都是没有简介的，emby也需要通过tmdb等刮削。

依然需要tmdb信息更新后，通过媒体服务器再刮削，或者重新转移

**Comment by Aqr-K** [comment]
这就很占用媒体服务器的资源了，如果媒体库比较大的情况下，它的自动刮削基本都是大范围扫描很吃性能，
所以能不能内置或者优化一下默认单集名字啥的，加个开关，用来强行覆盖tmdb给的单集名字，不需要简介让他更简洁，主要是现在tmdb没有文件的时候，自动生成的单集名字太长了，剧名+s01e01+中文第几集，这就导致在下有些名字很长的国外剧的时候，因为这个刮削问题，单集名字长出天际了

**Comment by Aqr-K** [comment]
有很多时候是单集名字有了，但是简介没有，是不需要简介，但他没有分出去一个专门关掉简介的按钮
个人觉得简介跟剧透一样

**Comment by jxxghp** [comment]
nastool处理的时候tmdb没有信息，把刮削选项分再细也于事无补呀。
这种情况只能靠媒体库软件在tmdb信息全了的时候批量刷新。
