### ISSUE TITLE
搜索资源提示网络错误。

### ISSUE THREAD

**Issue by du8028934** [jxxghp/nas-tools#2741]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.4
>
> 环境: Synology
>

## 你遇到什么问题了？

> 内建索引器中，选择EXT.TO和SkrBT，还有一个我自己添加的站点hd.ai  这三个无论选择哪个，在资源上点搜索都会报网络错误。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
![image](https://user-images.githubusercontent.com/120125400/210152359-5775f76e-e84f-441d-86f2-fcbbc3d9f634.png)
但是查看日志，好像虽然显示了网络错误，但是其他的站点还是有去搜索。
![image](https://user-images.githubusercontent.com/120125400/210152383-fa5b5449-64c0-4557-a7ae-3bcbb1ba68b2.png)
是不是这俩站点临时有问题？那如果有问题是不是应该直接跳过。然后继续去搜索。然后最后告诉这俩站点有毛病。

**Comment by jxxghp** [comment]
这个因为太久了，前台请求超时了。后台还是在处理的，等一会点资源搜索就会显示。

**Comment by du8028934** [comment]
> 这个因为太久了，前台请求超时了。后台还是在处理的，等一会点资源搜索就会显示。

不是太久，在资源上点搜索马上就会跳出网络错误，并且结果并不会等一会儿就出来显。而是就没没了。

**Comment by zero617** [comment]
> > 这个因为太久了，前台请求超时了。后台还是在处理的，等一会点资源搜索就会显示。
> 
> 不是太久，在资源上点搜索马上就会跳出网络错误，并且结果并不会等一会儿就出来显。而是就没没了。

我也是同样的问题

**Comment by szjawo** [comment]
> 这个因为太久了，前台请求超时了。后台还是在处理的，等一会点资源搜索就会显示。
我也是同样的问题，不过不是点搜索马上跳网络错误，而是等搜索快完事的时候跳网络错误弹窗。另外，弹出网络错误之后，资源搜索里并不会显示刚才搜索结果。

**Comment by szjawo** [comment]
> 这个因为太久了，前台请求超时了。后台还是在处理的，等一会点资源搜索就会显示。

我也是同样的问题，不过不是点搜索马上跳网络错误，而是等搜索快完事的时候跳网络错误弹窗。另外，弹出网络错误之后，资源搜索里并不会显示刚才搜索结果。

**Comment by imba97** [comment]
同样的问题

![image](https://user-images.githubusercontent.com/10150208/210170801-b2d9c516-7038-4336-a0ea-344cdef451f7.png)

**Comment by imba97** [comment]
发现内建索引器这里少选几个可以解决

![image](https://user-images.githubusercontent.com/10150208/210177173-2269c1b3-7db2-4e26-88c7-f7d331f6f322.png)

![image](https://user-images.githubusercontent.com/10150208/210177201-7a4d8cc7-d602-4bd6-aa97-e0b33962e67a.png)

**Comment by jxxghp** [comment]
关键是有的公开站挂了，看一下是哪个

**Comment by jxxghp** [comment]
我公开站全选可以正常搜索，重现不了问题。

**Comment by Peanut-GGG** [comment]
我也出现这种问题了 日志系统能打印的再全面一点么 或者做个判断 无法访问的站点 自动跳过搜索

**Comment by Peanut-GGG** [comment]
有可能是网络问题，访问不了公开站 希望搜索资源 也可以使用代理地址

**Comment by kdskds** [comment]
选了EXT.TO 或者SkrBT，就会显示网络错误

**Comment by cecial** [comment]
> 选了EXT.TO 或者SkrBT，就会显示网络错误
确实，把这两个取消就正常了
