### ISSUE TITLE
两个站点任何资源都检索不到

### ISSUE THREAD

**Issue by git-0101** [jxxghp/nas-tools#2746]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.4
>
> 环境: docker
>

## 你遇到什么问题了？

> hdchina和ttg检索不到资源
![Screenshot_20230101_103556](https://user-images.githubusercontent.com/115487446/210159618-236daf4d-4d48-488d-8941-dac99bc7e98a.jpg)
![Screenshot_20230101_103846](https://user-images.githubusercontent.com/115487446/210159622-d47ab7f7-2983-4e8a-ae3e-ec403592c3b8.jpg)

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/210159724-5abf1a28-c420-4627-8c13-b197a9cbaae8.png)
自己的w问题

**Comment by git-0101** [comment]
好的，我再好好排查下。
新年快乐！！！

**Comment by Bdkan** [comment]
排查到问题原因没？我跟你同样的问题，群晖套件版，2.7.1版本正常，2.7.4版本ttg和hdc获取账号数据正常，但是无法搜索和获取站点资源

**Comment by git-0101** [comment]
> 排查到问题原因没？我跟你同样的问题，群晖套件版，2.7.1版本正常，2.7.4版本ttg和hdc获取账号数据正常，但是无法搜索和获取站点资源

情况基本一样，原因不明。问题不大，再等等。
