### ISSUE TITLE
新版本无法从备份中恢复配置

### ISSUE THREAD

**Issue by Aziatixic** [jxxghp/nas-tools#2748]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.4 ec5e3b5e
> 环境: docker

## 你遇到什么问题了？

>无法从备份文件恢复配置，提示文件不是zip

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

![屏幕截图 2023-01-01 174301](https://user-images.githubusercontent.com/58366414/210166612-4d3fef9f-3cae-43aa-90af-26d8a8c6bf3d.png)

**Comment by H0nze** [comment]
同问

**Comment by H0nze** [comment]
实在是没法解决，，我直接把配置文件覆盖进去了

**Comment by jxxghp** [comment]
![image](https://user-images.githubusercontent.com/51039935/210193632-cb713d47-376f-4c55-92c8-01f84757f177.png)

**Comment by jxxghp** [comment]
进系统看一下，zip文件是否存在

**Comment by Aziatixic** [comment]
你好，查到我之前的容器未配置config目录，刚刚增加目录后可以正常恢复备份！
