### ISSUE TITLE
原盘bdmv下有多盘的电影无法识别

### ISSUE THREAD

**Issue by shimingliangsml** [jxxghp/nas-tools#275]
原盘bdmv下有多盘的电影无法识别

**Comment by jxxghp** [comment]
建议贴个目录结构

**Comment by shimingliangsml** [comment]
[image: image.png]
比如在这种大包下的包含双盘的电影是无法识别出来，手动识别后也只能识别一个，另一个会显示文件已存在

Mr Huang ***@***.***> 于2022年6月14日周二 21:45写道：

**Comment by jxxghp** [comment]
这种情况极少，不打算支持了。

**Comment by mouse2008** [comment]
BDMV文件夹格式的，很多都无法识别
