### ISSUE TITLE
更新后nastools一直自动重启

### ISSUE THREAD

**Issue by dty1030** [jxxghp/nas-tools#2753]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.4
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 更新后打不开nastools

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
[
![`~3YFK~MAU}SR6@%LY$W4DI](https://user-images.githubusercontent.com/80985867/210180045-24e77638-f42d-451e-b152-7e1782bd920d.png)
](url)
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
[Nastools2 (1).pdf](https://github.com/jxxghp/nas-tools/files/10329207/Nastools2.1.pdf)

**Comment by Shurelol** [comment]
重拉镜像
