### ISSUE TITLE
高清片源网下载添加失败

### ISSUE THREAD

**Issue by imba97** [jxxghp/nas-tools#2755]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.4
>
> 环境: Synology
>

## 你遇到什么问题了？

高清片源网下载的链接是电影详情页，应该是这个导致的下载失败

![image](https://user-images.githubusercontent.com/10150208/210190275-50069f16-2c74-4496-afe9-6b58d09a1a0a.png)

高清MP4吧也是电影详情

![image](https://user-images.githubusercontent.com/10150208/210190836-21fb255b-612b-4943-b8e2-3e977d031bdd.png)

## 你期望的结果

正确的是一个 `magnet:`

![image](https://user-images.githubusercontent.com/10150208/210190299-465c2fe9-e108-48bd-92cf-819f7c3c92a0.png)

**Comment by jxxghp** [comment]
这个是日志打印的问题，会从详情页面解析出下载地址的。
高清MP4是可以下载的吧，我测试了是正常的。
高清片源网搞不定，计划取消了。

**Comment by jxxghp** [comment]
日志打印的问题修正了，但是手工把解析出来的磁力链添加到下载器都是不显示任务，就不知道是啥情况了。
