### ISSUE TITLE
如何捐赠？

### ISSUE THREAD

**Issue by ZevaXu** [jxxghp/nas-tools#2763]
我在unraid上部署了plex 加 nastool，目前用起来感觉很好，很方便，感谢大佬开发这么好用的工具。我想捐赠，但是找了很久找不到捐赠的入口，请问如何捐赠？

**Comment by jxxghp** [comment]
感谢，这个项目暂时不需要损赠

**Comment by c939984606** [comment]
这个项目真不错，工具方便，而且开源，以前我一点不懂flask，python，现在也根据大佬的源码自己摸索学习写了自己的小网站，赞
