### ISSUE TITLE
建议为rclone移动/复制添加参数选项

### ISSUE THREAD

**Issue by BoneBob** [jxxghp/nas-tools#2767]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: [v2.7.4]
>
> 环境: docker

## 你想要新增或者改进什么功能？

> rclone移动/复制可以加添加参数，这样可以根据使用的环境（比如内存大小，带宽大小）适当调整

## 这个功能有什么可以参考的资料吗？

> rclone官方给的Global Flags：https://rclone.org/flags/

**Comment by jxxghp** [comment]
给些建议值？自己没使用过rclone

**Comment by BoneBob** [comment]
rclone比较常用的一些参数：
--transfers=N - 并行文件数
--onedrive-chunk-size 块大小（Onedrive）
--drive-chunk-size 块大小（Google Drive）
这几个比较影响内存占用和传输速度，比如8G内存完全可以将transfers调到16（默认4），块大小调到100M（默认10M），这样传输速度大幅提升，而小内存比如1G可以将transfers调到1，避免被kill.
还有像--max-size这样的参数可以过滤文件大小之类的参数也有一定用处

rclone这些参数没有顺序上的严格要求，我的建议是直接让用户自己填写完整的参数，比如“--config /root/.config/rclone/rclone.conf --transfers=4 --onedrive-chunk-size 10M --delete-empty-src-dirs“这样的，然后程序调用rclone可以直接加在原有命令之后，这样既简单又能充分根据硬件条件自定义

**Comment by BoneBob** [comment]
关于rclone的参数，我找到了rclone官方提供的另一种方法，就是通过环境变量
### 比如使用Docker cli 安装加入
`-e RCLONE_FLAG_NAME = RCLONE_FLAG_VALUE`
例‘-e RCLONE_TRANSFERS = 16’
Nastool无需任何改动。官方文档：[https://rclone.org/docs/#environment-variables](url)

**Comment by jxxghp** [comment]
> 关于rclone的参数，我找到了rclone官方提供的另一种方法，就是通过环境变量
> 
> ### 比如使用Docker cli 安装加入
> 
> `-e RCLONE_OPTION_NAME = RCLONE_OPTION_VALUE`
> 
> 例如`-e RCLONE_TRANSFERS = 16`
> 
> Nastools无需任何改动。官方文档：[https://rclone.org/docs/#environment-variables](https://rclone.org/docs/#environment-variables)

这个可以。很灵活通用。

**Comment by ausar47** [comment]
请问nastools怎么使用rclone模式？我rclone挂载成Z盘映射目录的话nastools不支持

**Comment by LevineWoo** [comment]
我添加了-e RCLONE_TRANSFERS = 16这个参数，但是上传速度仍然和单线程是一样的，即使我手动识别转移多个剧集，也还是只有40m/s的上传速度。
