### ISSUE TITLE
瓷器刷流设置弹框中的【包含】【排除】都不匹配副标题文字

### ISSUE THREAD

**Issue by orzcz** [jxxghp/nas-tools#2769]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.4
>
> 环境: docker
>

## 你遇到什么问题了？

> 瓷器刷流设置弹框中的【包含】【排除】都不匹配副标题文字

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 对副标题文字进行匹配，可以帮助我排除非整集的剧集

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/26238769/210240092-b101679d-c524-44f2-a43f-c6a8326d5125.png)
![image](https://user-images.githubusercontent.com/26238769/210240273-9106b315-c66b-4df7-8392-cb16df2cb1f8.png)
![image](https://user-images.githubusercontent.com/26238769/210240313-15f947d2-2f1a-47b1-a625-edbd7536aa79.png)

希望可以修复，谢谢

**Comment by Shurelol** [comment]
刷流的种子信息来源于站点配置的rss链接

如果生成rss链接时，项目名称结构未勾选副标题，那么就没有

**Comment by orzcz** [comment]
> 刷流的种子信息来源于站点配置的rss链接
> 
> 如果生成rss链接时，项目名称结构未勾选副标题，那么就没有

我特地重新试了，勾选了副标题。也无效
