### ISSUE TITLE
微信搜索建议

### ISSUE THREAD

**Issue by leo8912** [jxxghp/nas-tools#277]
最新的版本搜索有近似词条选择，搜索条件不需要那么精确了。
提一个优化的建议，老大看看是否可行。选择电影后，还没出资源的影片自动添加订阅，这样感觉很顺滑啊（如怕出错，可以增加个几秒内回复取消订阅操作，不知是否可行）
![Screenshot_2022-06-13-10-19-21-153_com.tencent.mm.png](https://user-images.githubusercontent.com/22719866/173268161-fb61cbaf-d35b-46f5-94ba-6e3c7c1daf7b.png)

**Comment by jxxghp** [comment]
done
