### ISSUE TITLE
站点资源下载时提示失败 添加下载失败 种子信息有误

### ISSUE THREAD

**Issue by 1087966** [jxxghp/nas-tools#2772]
![微信截图_20230102232718](https://user-images.githubusercontent.com/63256222/210252223-24c44987-f4c6-4711-ad45-53ecac1fb813.png)
![PTT](https://user-images.githubusercontent.com/63256222/210252788-559353ca-83e1-4814-9382-c7edb3c931a5.png)

PT站点测试也是正常的，去网站就可以下。 但是在nastool的站点资源添加种子就提示。失败添加下载失败。
 在站点资源里打开。然后点下载提示这个错误。 请大神指点一下 啥原因，我和朋友一起安装的 一样的操作他就直接能下载 TR配置正确。 默认搜索引擎可以下正确下载。 但是每次添加站点资源的时候 就这样。 研究好几天了没搞懂。 请指教下。 谢谢

**Comment by jxxghp** [comment]
用的是什么环境的版本？你背后的图都不正常，没有显示出标题，没有标题就会报这个错。

建议重新拉取完整的Docker镜像。

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/51039935/210286223-8f5949f1-c902-43d2-8cf4-cd38b50990a2.png">

**Comment by 1087966** [comment]
> 用的是什么环境的版本？你背后的图都不正常，没有显示出标题，没有标题就会报这个错。
> 
> 建议重新拉取完整的Docker镜像。
> 
> <img alt="image" width="1391" src="https://user-images.githubusercontent.com/51039935/210286223-8f5949f1-c902-43d2-8cf4-cd38b50990a2.png">
![普通截图](https://user-images.githubusercontent.com/63256222/210291387-77dc5769-d8b8-4699-ad92-c8e692f73973.png)
我用的nas版的v2.7.4.我和朋友的一模一样，，他也这样 就可以直接下载。。 但是我就提示错误。郁闷! 请大神指点。谢谢.TR配置没有问题。。

**Comment by jxxghp** [comment]
config目录下sites.dat用最新的替换。
如果还不行，换docker版本。

**Comment by 1087966** [comment]
> config目录下sites.dat用最新的替换。 如果还不行，换docker版本。
感谢，我试一下。

**Comment by 1087966** [comment]
> config目录下sites.dat用最新的替换。 如果还不行，换docker版本。

好了。正常工作了。替换完重启就可以了。 十分感谢作者大大。
