### ISSUE TITLE
界面会出现透明

### ISSUE THREAD

**Issue by git-0101** [jxxghp/nas-tools#2773]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.4
>
> 环境: docker
>

## 你遇到什么问题了？

> 界面会出现如下图情况
![Screenshot_20230102_234551_edit_1538742854719372](https://user-images.githubusercontent.com/115487446/210261153-f6725544-5d2f-456f-a487-16f28010ecfd.jpg)

**Comment by jxxghp** [comment]
你这是啥情况
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/51039935/210286622-b52eca4c-9bd9-4b41-a66c-11cdf941a217.png">

**Comment by git-0101** [comment]
> 你这是啥情况 <img alt="image" width="1268" src="https://user-images.githubusercontent.com/51039935/210286622-b52eca4c-9bd9-4b41-a66c-11cdf941a217.png">

新年快乐！！！
偶尔会出现，有时候是整条都透明。从2.7.3开始的。对使用没有影响。就是发现了提一下，也可能是个体手机原因。
![Screenshot_20230103_082901](https://user-images.githubusercontent.com/115487446/210287124-c4cdacfb-a36e-4b27-8a3b-a81c41957c5e.jpg)

**Comment by git-0101** [comment]
> 是啥浏览器，倒没出现过。

安卓Edge，感觉可以先不管。我再在不同手机不同浏览器测试下。

**Comment by git-0101** [comment]
> 是啥浏览器，倒没出现过。

安卓Edge，感觉可以先不管。我再在不同手机不同浏览器测试下。
