### ISSUE TITLE
刷流任务里 包含 关键字功能无效

### ISSUE THREAD

**Issue by Dreamray** [jxxghp/nas-tools#2779]
NAStool 版本: 2.7.3
环境: windows

刷流任务里 包含 关键字功能无效

配置如下：
猫站，包含 输入框内填 “PTer” （不含引号）
添加了如下种子：
Dorogoy moy chelovek 1958 PAL DVD9
我亲爱的人 / My Dear Fellow! / 亲爱的人 / Dorogoy moy chelovek | 类别：剧情 爱情

标题和副标题均不含 “PTer”

其它站未测试

**Comment by orzcz** [comment]
是的。我之前也提过，还没得到回复。
https://github.com/jxxghp/nas-tools/issues/2769

**Comment by jxxghp** [comment]
是区分了大小写的原因，RSS详情里面会有站点地址，有pter关键字。
