### ISSUE TITLE
连接tmdb异常

### ISSUE THREAD

**Issue by hellodboy** [jxxghp/nas-tools#279]
21:46:18 ERROR - 【META】连接TMDB出错：eval() arg 1 must be a string, bytes or code object
在识别资源时，日志报错如上。 （5月10多号以后就一直无法连接了。 ）
推荐--tmdb热门电影、电视剧栏目点击刷不出页面。   点豆瓣热门栏目能正常显示。 
本地访问tmdb正常， 也尝试过路由器挂全局代理，都是报同样的错误。 

请问有遇到过类似问题么？谢谢

**Comment by yeats88** [comment]
同样情况 之前没挂代理也访问得好好的。。
