### ISSUE TITLE
下载管理中无法显示qbittorrent中正在下载的内容无论是手动添加的还是自动下载的

### ISSUE THREAD

**Issue by Passerby1011** [jxxghp/nas-tools#2792]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.4
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

下载管理中无法显示qbittorrent中正在下载的内容无论是手动添加的还是自动下载的
不知是不是用的非官方的原因这是qbittorrent的docker地址：https://hub.docker.com/r/superng6/qbittorrent
这个源魔改了可以自动添加并更新trackers（来自[XIU2 / TrackersListCollection](https://github.com/XIU2/TrackersListCollection)
对于国内用户很友好
该docker里qbittorrent版本为[4.5.0]
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
看到过一个已经关闭的issues，但并没有解决办法

## 你期望的结果
正常显示，如果是不适配的原因，希望可以进行适配

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/63802758/210496067-8969f454-e96a-4762-8a1a-b146b99abc06.png)
![image](https://user-images.githubusercontent.com/63802758/210496104-e0326d5a-1283-4bca-9178-6b0adeb55917.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
正常的qb版本正常使用。
