### ISSUE TITLE
请问在windows环境下 一配置ssl证书路径之后 重启 便无法访问ip:3000了

### ISSUE THREAD

**Issue by Hazard804** [jxxghp/nas-tools#280]
docker desktop环境

**Comment by Hazard804** [comment]
![image](https://user-images.githubusercontent.com/82299110/173377344-e74919a0-d6c6-46e0-b5c0-8f57b6fd6042.png)
只能直接从这里删除掉路径 便能正常启动
路径的映射都已经做好了的

**Comment by jxxghp** [comment]
你这样配置能启动才怪，你要配置到key和pem文件。

**Comment by Hazard804** [comment]
我最开始就是配置到具体的文件 但是无法启动 所以后来才改成这样子的
