### ISSUE TITLE
Nas-Tools无法连接QBittorrent

### ISSUE THREAD

**Issue by superain7** [jxxghp/nas-tools#2804]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.4
>
> 环境: docker  Synology
>

## 你遇到什么问题了？
nas-tools连接qb失败，日志如图。
<a href="https://imgse.com/i/pSkPw24"><img src="https://s1.ax1x.com/2023/01/04/pSkPw24.png" alt="pSkPw24.png" border="0" /></a>
> 描述一下你遇到的问题
群晖docker部署qb，无法连接nas-tools，
填写局域网ip及域名都无法连接成功。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
提示都这么明显了，还要别人怎么帮你？
