### ISSUE TITLE
更新2.7.4后所有定时功能出错，重装后还原恢复备份失败。

### ISSUE THREAD

**Issue by Kinnnnn3344** [jxxghp/nas-tools#2807]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.4
>
> 环境: docker or openwrt (iStoreOS 21.02.3 2022121613)
>

## 更新2.7.4后所有定时功能出错，重装后还原恢复备份失败

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 无法解决。

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
stdout: 更新程序...
stdout: HEAD is now at 5f00e87c Merge pull request #2774 from jxxghp/dev
stderr: From https://github.com/jxxghp/nas-tools
stderr:    cec81cf5..a6fcd770  dev        -> origin/dev
stdout: Already up to date.
stdout: 更新成功...
stdout: 以PUID=0，PGID=0的身份启动程序...
stdout: /usr/bin/dumb-init
stdout: 2023-01-04T22:44:56: PM2 log: Launching in no daemon mode
stdout: 2023-01-04T22:44:56: PM2 log: App [NAStool:0] starting in -fork mode-
stdout: 2023-01-04T22:44:56: PM2 log: App [NAStool:0] online
stdout: 【Config】config.yaml 配置文件不存在，已将配置文件模板复制到配置目录...
stdout: 正在加载配置：/config/config.yaml
stdout: NAStool 当前版本号：v2.7.4
stdout: 开始初始化数据库...
stdout: 数据库初始化完成
stdout: 开始更新数据库...
stdout: (sqlite3.OperationalError) duplicate column name: SAVE_PATH
stdout: [SQL: ALTER TABLE "CONFIG_USER_RSS" ADD COLUMN "SAVE_PATH" TEXT]
stdout: (Background on this error at: https://sqlalche.me/e/14/e3q8)
stdout: (sqlite3.OperationalError) duplicate column name: RSS_SITES
stdout: [SQL: ALTER TABLE "RSS_MOVIES" ADD COLUMN "RSS_SITES" TEXT]
stdout: (Background on this error at: https://sqlalche.me/e/14/e3q8)
stdout: (sqlite3.OperationalError) duplicate column name: RSS_SITES
stdout: [SQL: ALTER TABLE "RSS_TVS" ADD COLUMN "RSS_SITES" TEXT]
stdout: (Background on this error at: https://sqlalche.me/e/14/e3q8)
stdout: 'FILE_PATH'
stdout: (sqlite3.OperationalError) duplicate column name: DOWNLOADER
stdout: [SQL: ALTER TABLE "DOWNLOAD_SETTING" ADD COLUMN "DOWNLOADER" TEXT]
stdout: (Background on this error at: https://sqlalche.me/e/14/e3q8)
stdout: (sqlite3.OperationalError) no such column: ""FAVICON""
stdout: [SQL: ALTER TABLE "SITE_USER_INFO_STATS" DROP COLUMN "FAVICON"]
stdout: (Background on this error at: https://sqlalche.me/e/14/e3q8)
stdout: (sqlite3.OperationalError) duplicate column name: ADD_TIME
stdout: [SQL: ALTER TABLE "DOUBAN_MEDIAS" ADD COLUMN "ADD_TIME" TEXT]
stdout: (Background on this error at: https://sqlalche.me/e/14/e3q8)
stdout: (sqlite3.OperationalError) duplicate column name: SENDMESSAGE
stdout: [SQL: ALTER TABLE "SITE_BRUSH_TASK" ADD COLUMN "SENDMESSAGE" TEXT]
stdout: (Background on this error at: https://sqlalche.me/e/14/e3q8)
stdout: 数据库更新完成
stdout: 日志输出类型为：console
stdout: WEB管理页面用户：admin
stdout: 未启用https，请使用 http://IP:3000 访问管理页面
stdout: TMDB API Key未配置，媒体整理、搜索下载等功能将无法正常运行！
stdout: TMDB匹配模式：正常模式
stdout: 媒体管理软件设置为：emby
stdout: emby配置不完整
stdout: 未配置电影媒体库目录
stdout: 未配置电视剧媒体库目录
stdout: 下载软件设置为：qbittorrent
stdout: 默认文件转移模式为：硬链接
stdout: 索引器设置为：builtin
stdout: 微信等移动端渠道搜索已开启自动择优下载
stdout: 下载软件监控未开启，下载器监控功能已关闭
stdout: 开始启动服务...
stdout: Exception: 'CST-8'
stdout: Callstack:
stdout: Traceback (most recent call last):
stdout:   File "/nas-tools/app/scheduler.py", line 248, in run_scheduler
stdout:     Scheduler().run_service()
stdout:   File "/nas-tools/app/scheduler.py", line 45, in run_service
stdout:     self.SCHEDULER = BackgroundScheduler(timezone=Config().get_timezone(),
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
stdout:     self.configure(gconfig, **options)
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 131, in configure
stdout:     self._configure(config)
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/background.py", line 29, in _configure
stdout:     super(BackgroundScheduler, self)._configure(config)
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 701, in _configure
stdout:     self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/util.py", line 91, in astimezone
stdout:     return timezone(obj)
stdout:   File "/usr/lib/python3.10/site-packages/pytz/__init__.py", line 188, in timezone
stdout:     raise UnknownTimeZoneError(zone)
stdout: pytz.exceptions.UnknownTimeZoneError: 'CST-8'
stderr: 2023-01-04 22:44:59,667	ERROR: 启动定时服务失败：'CST-8' - Traceback (most recent call last):
stderr:   File "/nas-tools/app/scheduler.py", line 248, in run_scheduler
stderr:     Scheduler().run_service()
stderr:   File "/nas-tools/app/scheduler.py", line 45, in run_service
stderr:     self.SCHEDULER = BackgroundScheduler(timezone=Config().get_timezone(),
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
stderr:     self.configure(gconfig, **options)
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 131, in configure
stderr:     self._configure(config)
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/background.py", line 29, in _configure
stderr:     super(BackgroundScheduler, self)._configure(config)
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 701, in _configure
stderr:     self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/util.py", line 91, in astimezone
stderr:     return timezone(obj)
stderr:   File "/usr/lib/python3.10/site-packages/pytz/__init__.py", line 188, in timezone
stderr:     raise UnknownTimeZoneError(zone)
stderr: pytz.exceptions.UnknownTimeZoneError: 'CST-8'
stdout: 【Config】分类配置文件 default-category.yaml 不存在，已将配置文件模板复制到配置目录...
stdout:  * Serving Flask app 'web.main' (lazy loading)
stdout:  * Environment: production
stdout:    WARNING: This is a development server. Do not use it in a production deployment.
stdout:    Use a production WSGI server instead.
stdout:  * Debug mode: off
stdout: 更新程序...
stdout: Removing __pycache__/
stdout: Removing app/__pycache__/
stdout: Removing app/conf/__pycache__/
stdout: Removing app/db/__pycache__/
stdout: Removing app/downloader/__pycache__/
stdout: Removing app/downloader/client/__pycache__/
stdout: Removing app/helper/__pycache__/
stdout: Removing app/indexer/__pycache__/
stdout: Removing app/indexer/client/__pycache__/
stdout: Removing app/media/__pycache__/
stdout: Removing app/media/doubanapi/__pycache__/
stdout: Removing app/media/meta/__pycache__/
stdout: Removing app/media/tmdbv3api/__pycache__/
stdout: Removing app/media/tmdbv3api/objs/__pycache__/
stdout: Removing app/mediaserver/__pycache__/
stdout: Removing app/mediaserver/client/__pycache__/
stdout: Removing app/message/__pycache__/
stdout: Removing app/message/client/__pycache__/
stdout: Removing app/sites/__pycache__/
stdout: Removing app/utils/__pycache__/
stdout: Removing db_scripts/__pycache__/
stdout: Removing db_scripts/versions/__pycache__/
stdout: Removing web/__pycache__/
stdout: Removing web/backend/__pycache__/
stdout: HEAD is now at 5f00e87c Merge pull request #2774 from jxxghp/dev
stdout: Already up to date.
stdout: 更新成功...
stdout: 以PUID=0，PGID=0的身份启动程序...
stdout: /usr/bin/dumb-init
stdout: 2023-01-04T22:57:48: PM2 log: Launching in no daemon mode
stdout: 2023-01-04T22:57:48: PM2 log: App [NAStool:0] starting in -fork mode-
stdout: 2023-01-04T22:57:48: PM2 log: App [NAStool:0] online
stdout: 正在加载配置：/config/config.yaml
stdout: NAStool 当前版本号：v2.7.4
stdout: 开始初始化数据库...
stdout: 数据库初始化完成
stdout: 开始更新数据库...
stdout: 数据库更新完成
stdout: 日志输出类型为：console
stdout: WEB管理页面用户：admin
stdout: 未启用https，请使用 http://IP:3000 访问管理页面
stdout: TMDB API Key未配置，媒体整理、搜索下载等功能将无法正常运行！
stdout: TMDB匹配模式：正常模式
stdout: 媒体管理软件设置为：emby
stdout: emby配置不完整
stdout: 未配置电影媒体库目录
stdout: 未配置电视剧媒体库目录
stdout: 下载软件设置为：qbittorrent
stdout: 默认文件转移模式为：硬链接
stdout: 索引器设置为：builtin
stdout: 微信等移动端渠道搜索已开启自动择优下载
stdout: 下载软件监控未开启，下载器监控功能已关闭
stdout: 开始启动服务...
stdout: Exception: 'CST-8'
stdout: Callstack:
stdout: Traceback (most recent call last):
stdout:   File "/nas-tools/app/scheduler.py", line 248, in run_scheduler
stdout:     Scheduler().run_service()
stdout:   File "/nas-tools/app/scheduler.py", line 45, in run_service
stdout:     self.SCHEDULER = BackgroundScheduler(timezone=Config().get_timezone(),
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
stdout:     self.configure(gconfig, **options)
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 131, in configure
stdout:     self._configure(config)
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/background.py", line 29, in _configure
stdout:     super(BackgroundScheduler, self)._configure(config)
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 701, in _configure
stdout:     self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/util.py", line 91, in astimezone
stdout:     return timezone(obj)
stdout:   File "/usr/lib/python3.10/site-packages/pytz/__init__.py", line 188, in timezone
stdout:     raise UnknownTimeZoneError(zone)
stdout: pytz.exceptions.UnknownTimeZoneError: 'CST-8'
stderr: 2023-01-04 22:57:54,947	ERROR: 启动定时服务失败：'CST-8' - Traceback (most recent call last):
stderr:   File "/nas-tools/app/scheduler.py", line 248, in run_scheduler
stderr:     Scheduler().run_service()
stderr:   File "/nas-tools/app/scheduler.py", line 45, in run_service
stderr:     self.SCHEDULER = BackgroundScheduler(timezone=Config().get_timezone(),
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
stderr:     self.configure(gconfig, **options)
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 131, in configure
stderr:     self._configure(config)
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/background.py", line 29, in _configure
stderr:     super(BackgroundScheduler, self)._configure(config)
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 701, in _configure
stderr:     self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/util.py", line 91, in astimezone
stderr:     return timezone(obj)
stderr:   File "/usr/lib/python3.10/site-packages/pytz/__init__.py", line 188, in timezone
stderr:     raise UnknownTimeZoneError(zone)
stderr: pytz.exceptions.UnknownTimeZoneError: 'CST-8'
stdout:  * Serving Flask app 'web.main' (lazy loading)
stdout:  * Environment: production
stdout:    WARNING: This is a development server. Do not use it in a production deployment.
stdout:    Use a production WSGI server instead.
stdout:  * Debug mode: off
stdout: Exception: [Errno 2] No such file or directory: '/config/temp/bk_20221121024214.zip'
stdout: Callstack:
stdout: Traceback (most recent call last):
stdout:   File "/nas-tools/web/main.py", line 1539, in upload
stdout:     files.save(str(file_path))
stdout:   File "/usr/lib/python3.10/site-packages/werkzeug/datastructures.py", line 2999, in save
stdout:     dst = open(dst, "wb")
stdout: FileNotFoundError: [Errno 2] No such file or directory: '/config/temp/bk_20221121024214.zip'
stdout: Exception: /config/temp/bk_20221121024214.zip is not a zip file
stdout: Callstack:
stdout: Traceback (most recent call last):
stdout:   File "/nas-tools/web/action.py", line 2448, in __restory_backup
stdout:     shutil.unpack_archive(file_path, config_path, format='zip')
stdout:   File "/usr/lib/python3.10/shutil.py", line 1298, in unpack_archive
stdout:     func(filename, extract_dir, **dict(format_info[2]))
stdout:   File "/usr/lib/python3.10/shutil.py", line 1201, in _unpack_zipfile
stdout:     raise ReadError("%s is not a zip file" % filename)
stdout: shutil.ReadError: /config/temp/bk_20221121024214.zip is not a zip file
stdout: Exception: /config/temp/bk_20221121024214.zip is not a zip file
stdout: Callstack:
stdout: Traceback (most recent call last):
stdout:   File "/nas-tools/web/action.py", line 2448, in __restory_backup
stdout:     shutil.unpack_archive(file_path, config_path, format='zip')
stdout:   File "/usr/lib/python3.10/shutil.py", line 1298, in unpack_archive
stdout:     func(filename, extract_dir, **dict(format_info[2]))
stdout:   File "/usr/lib/python3.10/shutil.py", line 1201, in _unpack_zipfile
stdout:     raise ReadError("%s is not a zip file" % filename)
stdout: shutil.ReadError: /config/temp/bk_20221121024214.zip is not a zip file
stdout: Exception: [Errno 2] No such file or directory: '/config/temp/bk_20230104102922.zip'
stdout: Callstack:
stdout: Traceback (most recent call last):
stdout:   File "/nas-tools/web/main.py", line 1539, in upload
stdout:     files.save(str(file_path))
stdout:   File "/usr/lib/python3.10/site-packages/werkzeug/datastructures.py", line 2999, in save
stdout:     dst = open(dst, "wb")
stdout: FileNotFoundError: [Errno 2] No such file or directory: '/config/temp/bk_20230104102922.zip'
stdout: Exception: /config/temp/bk_20230104102922.zip is not a zip file
stdout: Callstack:
stdout: Traceback (most recent call last):
stdout:   File "/nas-tools/web/action.py", line 2448, in __restory_backup
stdout:     shutil.unpack_archive(file_path, config_path, format='zip')
stdout:   File "/usr/lib/python3.10/shutil.py", line 1298, in unpack_archive
stdout:     func(filename, extract_dir, **dict(format_info[2]))
stdout:   File "/usr/lib/python3.10/shutil.py", line 1201, in _unpack_zipfile
stdout:     raise ReadError("%s is not a zip file" % filename)
stdout: shutil.ReadError: /config/temp/bk_20230104102922.zip is not a zip file
stdout: Exception: [Errno 2] No such file or directory: '/config/temp/bk_20230104102922.zip'
stdout: Callstack:
stdout: Traceback (most recent call last):
stdout:   File "/nas-tools/web/main.py", line 1539, in upload
stdout:     files.save(str(file_path))
stdout:   File "/usr/lib/python3.10/site-packages/werkzeug/datastructures.py", line 2999, in save
stdout:     dst = open(dst, "wb")
stdout: FileNotFoundError: [Errno 2] No such file or directory: '/config/temp/bk_20230104102922.zip'
stdout: Exception: /config/temp/bk_20230104102922.zip is not a zip file
stdout: Callstack:
stdout: Traceback (most recent call last):
stdout:   File "/nas-tools/web/action.py", line 2448, in __restory_backup
stdout:     shutil.unpack_archive(file_path, config_path, format='zip')
stdout:   File "/usr/lib/python3.10/shutil.py", line 1298, in unpack_archive
stdout:     func(filename, extract_dir, **dict(format_info[2]))
stdout:   File "/usr/lib/python3.10/shutil.py", line 1201, in _unpack_zipfile
stdout:     raise ReadError("%s is not a zip file" % filename)
stdout: shutil.ReadError: /config/temp/bk_20230104102922.zip is not a zip file
stdout: 进程 40 检测到配置文件已修改，正在重新加载...
stdout: 正在加载配置：/config/config.yaml
stdout: Exception: 'CST-8'
stdout: Callstack:
stdout: Traceback (most recent call last):
stdout:   File "/nas-tools/app/scheduler.py", line 248, in run_scheduler
stdout:     Scheduler().run_service()
stdout:   File "/nas-tools/app/scheduler.py", line 45, in run_service
stdout:     self.SCHEDULER = BackgroundScheduler(timezone=Config().get_timezone(),
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
stdout:     self.configure(gconfig, **options)
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 131, in configure
stdout:     self._configure(config)
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/background.py", line 29, in _configure
stdout:     super(BackgroundScheduler, self)._configure(config)
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 701, in _configure
stdout:     self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/util.py", line 91, in astimezone
stdout:     return timezone(obj)
stdout:   File "/usr/lib/python3.10/site-packages/pytz/__init__.py", line 188, in timezone
stdout:     raise UnknownTimeZoneError(zone)
stdout: pytz.exceptions.UnknownTimeZoneError: 'CST-8'
stderr: 2023-01-04 23:06:22,180	ERROR: 启动定时服务失败：'CST-8' - Traceback (most recent call last):
stderr:   File "/nas-tools/app/scheduler.py", line 248, in run_scheduler
stderr:     Scheduler().run_service()
stderr:   File "/nas-tools/app/scheduler.py", line 45, in run_service
stderr:     self.SCHEDULER = BackgroundScheduler(timezone=Config().get_timezone(),
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
stderr:     self.configure(gconfig, **options)
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 131, in configure
stderr:     self._configure(config)
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/background.py", line 29, in _configure
stderr:     super(BackgroundScheduler, self)._configure(config)
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 701, in _configure
stderr:     self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/util.py", line 91, in astimezone
stderr:     return timezone(obj)
stderr:   File "/usr/lib/python3.10/site-packages/pytz/__init__.py", line 188, in timezone
stderr:     raise UnknownTimeZoneError(zone)
stderr: pytz.exceptions.UnknownTimeZoneError:    ##@['CST-8]

**Comment by jxxghp** [comment]
提示很明显，时区设错了。
docker要映射config目录才能恢复备份。
