### ISSUE TITLE
TG消息推送：消息接收出现错误: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by youyifentian** [jxxghp/nas-tools#2808]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.4
>
> 环境: docker and Synology
>

## NT可以给TG正常推送消息，但是NT接收TG消息的时候报错
![QQ截图20230105004053](https://user-images.githubusercontent.com/5012570/210605109-87d55e01-fc3d-40b4-8750-cb42d0bd29be.jpg)

![QQ截图20230105003810](https://user-images.githubusercontent.com/5012570/210604556-c6184065-e4d2-4e18-9603-8cebee9cd95e.jpg)

![QQ截图20230105003418](https://user-images.githubusercontent.com/5012570/210604333-b2e2cfa2-d8a0-426c-9e7d-479733592bb6.jpg)

**Comment by youyifentian** [comment]
![QQ截图20230105010821](https://user-images.githubusercontent.com/5012570/210610761-6201d2a6-e27c-4b2b-a020-e223a48cad3a.jpg)

**Comment by jxxghp** [comment]
确认127.0.0.1是否能连通

**Comment by youyifentian** [comment]
> 确认127.0.0.1是否能连通

我不太明白你说的127.0.0.1能否联通是啥意思，但是在基础设置里面，我0.0.0.0/0 0.0.0.0 127.0.0.1 127.0.0.1/0都试了，结果都一样，不过从日志来看，nt是收到tg发送的消息了的，但是不知道为啥没有处理反而报错了

**Comment by youyifentian** [comment]
> 确认127.0.0.1是否能连通

![2222222222222222](https://user-images.githubusercontent.com/5012570/210735096-0315ff40-7358-4bb1-9b37-4e30ae414fb6.jpg)

##像这里，打开webhook能交互的时候，即便收发正常，但还是有报错提示

**Comment by fallenyy** [comment]
> > 确认127.0.0.1是否能连通
> 
> 我不太明白你说的127.0.0.1能否联通是啥意思，但是在基础设置里面，我0.0.0.0/0 0.0.0.0 127.0.0.1 127.0.0.1/0都试了，结果都一样，不过从日志来看，nt是收到tg发送的消息了的，但是不知道为啥没有处理反而报错了

+1  请问解决了吗

**Comment by youyifentian** [comment]
> > > 确认127.0.0.1是否能连通
> > 
> > 
> > 我不太明白你说的127.0.0.1能否联通是啥意思，但是在基础设置里面，我0.0.0.0/0 0.0.0.0 127.0.0.1 127.0.0.1/0都试了，结果都一样，不过从日志来看，nt是收到tg发送的消息了的，但是不知道为啥没有处理反而报错了
> 
> +1 请问解决了吗

最新版也试了还是一个结果，只能开启webhook设置域名才可以正常使用，不搞这个了，还是老老实实用微信吧

**Comment by jxxghp** [comment]
接收到TG消息后，通过转发给127.0.0.1实现消息接收。如果127.0.0.1无法访问，就会报错

**Comment by youyifentian** [comment]
> 接收到TG消息后，通过转发给127.0.0.1实现消息接收。如果127.0.0.1无法访问，就会报错

1、我明白你说的意思了，我又看了下源码，找到问题原因了，是因为我是在nt里面配置的ssl证书，导致无法通过http://127.0.0.1:port/telegram 来接收信息了，如果去掉证书或者使用反代，就测试一切正常了，这次搞明白了，既然这样的话能不能修改一下实现nt配置证书也可以这样用呢，或者实在不行可以搞个提示，当nt配置ssl的时候，在设置tg消息通知的时候给个提示，这样也可以让大家明白问题出在哪里了。

2、另外还有一个小问题，就是比如我现在设置了关闭webhook，然后保存生效了，后面又重新编辑开启webhook并保存，这样实际好像没有成功，没有看到 “Webhook 设置成功，地址为：https://xxxxx.xxx.xx:8443/telegram ” 这样的日志，测试也无法正常交互，只有重启容器才可以真正生效。

**Comment by fallenyy** [comment]
> > 接收到TG消息后，通过转发给127.0.0.1实现消息接收。 如果127.0.0.1无法访问，就会报错
> 
> 1、我明白你说的意思了，我又看了下源码，找到问题原因了，是因为我是在nt里面配置的ssl证书，导致无法通过http://127.0.0.1:port/telegram 来接收信息了，如果去掉证书或者使用反代，就测试一切正常了，这次搞明白了，既然这样的话能不能修改一下实现nt配置证书也可以这样用呢，或者实在不行可以搞个提示，当nt配置ssl的时候，在设置tg消息通知的时候给个提示，这样也可以让大家明白问题出在哪里了。
> 
> 2、另外还有一个小问题，就是比如我现在设置了关闭webhook，然后保存生效了，后面又重新编辑开启webhook并保存，这样实际好像没有成功，没有看到 “Webhook 设置成功，地址为：https://xxxxx.xxx.xx:8443/telegram ” 这样的日志，测试也无法正常交互， 只有重启容器才可以真正生效。

谢谢提供方法，将telegram.py第303行修改为自己域名并设置相应Telegram源地址后完美解决。

**Comment by youyifentian** [comment]
> > > 接收到TG消息后，通过转发给127.0.0.1实现消息接收。 如果127.0.0.1无法访问，就会报错
> > 
> > 
> > 1、我明白你说的意思了，我又看了下源码，找到问题原因了，是因为我是在nt里面配置的ssl证书，导致无法通过http://127.0.0.1:port/telegram 来接收信息了，如果去掉证书或者使用反代，就测试一切正常了，这次搞明白了，既然这样的话能不能修改一下实现nt配置证书也可以这样用呢，或者实在不行可以搞个提示，当nt配置ssl的时候，在设置tg消息通知的时候给个提示，这样也可以让大家明白问题出在哪里了。
> > 2、另外还有一个小问题，就是比如我现在设置了关闭webhook，然后保存生效了，后面又重新编辑开启webhook并保存，这样实际好像没有成功，没有看到 “Webhook 设置成功，地址为：https://xxxxx.xxx.xx:8443/telegram ” 这样的日志，测试也无法正常交互， 只有重启容器才可以真正生效。
> 
> 谢谢提供方法，将telegram.py第303行修改为自己域名并设置相应Telegram源地址后完美解决。

额。。。。你这种跟在基础设置里面填写 外网访问地址 并在tg里面开启webhook，这种有区别吗？我感觉开启webhook实际就是这个意思。。。。

**Comment by fallenyy** [comment]
> > > > 接收到TG消息后，通过转发给127.0.0.1实现消息接收。 如果127.0.0.1无法访问，就会报错
> > > 
> > > 
> > > 1、我明白你说的意思了，我又看了下源码，找到问题原因了，是因为我是在nt里面配置的ssl证书，导致无法通过http://127.0.0.1:port/telegram 来接收信息了，如果去掉证书或者使用反代，就测试一切正常了，这次搞明白了，既然这样的话能不能修改一下实现nt配置证书也可以这样用呢，或者实在不行可以搞个提示，当nt配置ssl的时候，在设置tg消息通知的时候给个提示，这样也可以让大家明白问题出在哪里了。
> > > 2、另外还有一个小问题，就是比如我现在设置了关闭webhook，然后保存生效了，后面又重新编辑开启webhook并保存，这样实际好像没有成功，没有看到 “Webhook 设置成功，地址为：https://xxxxx.xxx.xx:8443/telegram ” 这样的日志，测试也无法正常交互， 只有重启容器才可以真正生效。
> > 
> > 
> > 谢谢提供方法，将telegram.py第303行修改为自己域名并设置相应Telegram源地址后完美解决。
> 
> 额。。。。你这种跟在基础设置里面填写 外网访问地址 并在tg里面开启webhook，这种有区别吗？我感觉开启webhook实际就是这个意思。。。。

额，这个我不清楚，我不用webhook的原因是不想把8443端口作为统一外网接口，而这能很好的解决我的问题。

**Comment by youyifentian** [comment]
> > > > > 接收到TG消息后，通过转发给127.0.0.1实现消息接收。 如果127.0.0.1无法访问，就会报错
> > > > 
> > > > 
> > > > 1、我明白你说的意思了，我又看了下源码，找到问题原因了，是因为我是在nt里面配置的ssl证书，导致无法通过http://127.0.0.1:port/telegram 来接收信息了，如果去掉证书或者使用反代，就测试一切正常了，这次搞明白了，既然这样的话能不能修改一下实现nt配置证书也可以这样用呢，或者实在不行可以搞个提示，当nt配置ssl的时候，在设置tg消息通知的时候给个提示，这样也可以让大家明白问题出在哪里了。
> > > > 2、另外还有一个小问题，就是比如我现在设置了关闭webhook，然后保存生效了，后面又重新编辑开启webhook并保存，这样实际好像没有成功，没有看到 “Webhook 设置成功，地址为：https://xxxxx.xxx.xx:8443/telegram ” 这样的日志，测试也无法正常交互， 只有重启容器才可以真正生效。
> > > 
> > > 
> > > 谢谢提供方法，将telegram.py第303行修改为自己域名并设置相应Telegram源地址后完美解决。
> > 
> > 
> > 额。。。。你这种跟在基础设置里面填写 外网访问地址 并在tg里面开启webhook，这种有区别吗？我感觉开启webhook实际就是这个意思。。。。
> 
> 额，这个我不清楚，我不用webhook的原因是不想把8443端口作为统一外网接口，而这能很好的解决我的问题。

哦哦哦，忘了8443这茬了，确实，为了测试我还专门重新分配了端口。。。。。
