### ISSUE TITLE
docker nastools 媒体整理目录为空 

### ISSUE THREAD

**Issue by xhrzg2017** [jxxghp/nas-tools#2810]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.4 5f00e87c
>
> 环境: docker 
>

## 描述一下你遇到的问题

>
   可能配置文件是2.7.3的，升级后缺参数导致文件处理部分异常。
   在旧版中可显示文件夹且路径输入栏有选择功能
  ![image](https://user-images.githubusercontent.com/34803905/210672807-5b086ed2-b023-42e2-9317-eab322f10154.png)
  通过终端查询路径，可知docker映射成功。
  ![image](https://user-images.githubusercontent.com/34803905/210672904-af13da56-7bd3-4bc0-ba35-faad9d7997cf.png)
  
  
  
  ## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已阅

## 你期望的结果

> 下版本修复

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
正在加载配置：/config/config.yaml
2023-01-05 07:56:27,584	INFO: 站点自动签到服务启动
2023-01-05 07:56:27,584	INFO: 下载文件转移服务启动
2023-01-05 07:56:27,586	INFO: RSS订阅服务启动
2023-01-05 07:56:27,588	INFO: 订阅定时搜索服务启动
2023-01-05 07:56:27,588	INFO: 媒体库同步服务启动
Pending jobs:
    Sites.signin (trigger: cron[hour='8', minute='1'], pending)
    Downloader.transfer (trigger: interval[0:05:00], pending)
    Rss.rssdownload (trigger: interval[0:30:00], pending)
    Subscribe.subscribe_search_all (trigger: interval[1 day, 0:00:00], pending)
    MediaServer.sync_mediaserver (trigger: interval[12:00:00], pending)
    MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
    Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
    Subscribe.subscribe_search (trigger: interval[0:05:00], pending)
    Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2023-01-05 07:57:27 CST)
    Subscribe.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
    MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
    get_login_wallpaper (trigger: interval[1:00:00], next run at: 2023-01-05 07:56:27 CST)
Job "Sites.signin (trigger: cron[hour='8', minute='1'], next run at: 2023-01-06 08:01:00 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/sites/sites.py", line 346, in signin
    with ThreadPool(min(len(sites), self._MAX_CONCURRENCY)) as p:
  File "/usr/lib/python3.10/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 930, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
docker run -d \
  --name=nastools \
  -e PUID=0 \
  -e PGID=0 \
  -e GIDLIST=0 \
  -e TZ=Asia/Shanghai \
  -e NASTOOL_AUTO_UPDATE=true  \
  -p 3000:3000 \
  -v /home/nastools/config:/config   \
  -v /home/qb:/qb  \
  -v /home/emby/share1:/media   \
  --restart always \
  jxxghp/nas-tools:latest
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by jxxghp** [comment]
你的文件夹没读取权限吧？
<img width="750" alt="image" src="https://user-images.githubusercontent.com/51039935/210726621-4d90c76a-785c-4cca-a498-5c73de926b61.png">
