### ISSUE TITLE
站点数据显示优化建议

### ISSUE THREAD

**Issue by log-time** [jxxghp/nas-tools#283]
大佬，这一块的显示有兴趣改进下吗？目前的方案站点多了后，基本啥都看不到了。
个人建议可以参考ptpp的布局，一个站点一行，不使用饼图或柱图，直接表格布局，最好各站点数据可以独立更新。
ps:目前站点的数据似乎是保存在user.db内的，后续是否可以考虑单独弄个数据库存储。

**Comment by lightolly** [comment]
有pptp的截图示例么

**Comment by log-time** [comment]
![Screenshot_20220615_205728](https://user-images.githubusercontent.com/66826612/173832544-bdb23db7-f56a-4863-b48b-cdd9cf771fea.png)

**Comment by log-time** [comment]
![Screenshot_20220615_210301](https://user-images.githubusercontent.com/66826612/173833520-4ab34bc9-fcea-423e-9c50-205ae00ed3ac.png)

**Comment by log-time** [comment]
![Screenshot_20220615_205630](https://user-images.githubusercontent.com/66826612/173833699-4cbb5fc0-9604-44fb-992b-5082c3a0dbd6.png)
这个近7日下载的数据似乎也有问题

**Comment by log-time** [comment]
> 有ptpp的截图示例么

个人建议在每个站点后面最好增加一个同步的按钮，最好能够显示同步时间和cookie是否有效

**Comment by log-time** [comment]
大佬，近7日数据饼图，能做成今日数据吗？站点数据7日是不是有点长了，7日应该只需要一个总数据就可以了，而且现在的方案也重复了

**Comment by log-time** [comment]
![IMG_20220618_063740](https://user-images.githubusercontent.com/66826612/174409366-b4ae18b6-fa86-4d4c-a7b2-43fc5fab4709.jpg)
用户名保留意义似乎不大，ptpp保留它是为了求邀方便。做种/下载如果保留的话能否改成保种数/保种量？
u2数据量单位有问题。

**Comment by log-time** [comment]
站点现在一会有一会没有，能连上的就显示，连不上的就不见了，在表格内能否将维护过的站点全部固定下来，连不上的先使用历史数据？cookie状态检测结果返显(是否可连接)可以放到这里来吗？

**Comment by log-time** [comment]
![Screenshot_20220618_071930](https://user-images.githubusercontent.com/66826612/174411842-940ff0e5-04bb-43e3-a3c2-81c0da39fbf6.png)
这个地方的折线图，因为总数据量不考虑魔力值兑换减少下载量或上传量的情况，正常情况下只有增加一个趋势，是否仍需要保留？

**Comment by lightolly** [comment]
> ![IMG_20220618_063740](https://user-images.githubusercontent.com/66826612/174409366-b4ae18b6-fa86-4d4c-a7b2-43fc5fab4709.jpg)
> 
> 站点的图标和站点的名字可以考虑分两列显示。用户名保留意义似乎不大，可以考虑换成等级数据或者隐藏。做种/下载如果保留的话能否改成保种数/保种量？
> 
> u2、北洋园站点数据和近七日下载数据汇总数有问题。

我在想是不是保留站点图标就行了，站点图标没有的，用名称
等级数据不太好解析，得再研究下🤣
保种数据是哪个页面有的？这个没找到
其他站点的数据兼容性问题 可能得学习下ptpp的代码了 有不少站点会魔改页面代码…

**Comment by lightolly** [comment]
> 站点现在一会有一会没有，能连上的就显示，连不上的就不见了，在表格内能否将维护过的站点全部固定下来，连不上的先使用历史数据？可以考虑增加一列返显cookie状态是否可用。

是表格里面数据也会消失么？

**Comment by log-time** [comment]
表格里会直接没有这个站点

**Comment by log-time** [comment]
ptpp的方案是点击图标可以刷新数据，最后那个按钮可以和图标结合起来

**Comment by jxxghp** [comment]
> > 站点现在一会有一会没有，能连上的就显示，连不上的就不见了，在表格内能否将维护过的站点全部固定下来，连不上的先使用历史数据？可以考虑增加一列返显cookie状态是否可用。
> 
> 是表格里面数据也会消失么？

我这边也有这个问题，解析魔力float异常出去了，后面我加了个try catch，不知道是不是还有其它点。

**Comment by log-time** [comment]
其实站点这类经常变化的，可以搞成模板，写个教程我们自己改模板yaml，以后升级压力也小

**Comment by log-time** [comment]
https://github.com/ronggang/PT-Plugin-Plus/actions/runs/2515025202
ptpp的releases版本站点适配也有点问题，要用上面的actions版本

**Comment by lightolly** [comment]
ptpp看起来是对于一些例外的解析用模板来区别定义获取规则的

**Comment by log-time** [comment]
新版本站点可以固定下来了，但是很多站点（包括馒头、套等）
ptpp及站点真实数据：
![Screenshot_20220620_180524](https://user-images.githubusercontent.com/66826612/174578865-aabe1ae0-d6db-4704-8f86-a83d44236d08.png)
![Screenshot_20220620_180849](https://user-images.githubusercontent.com/66826612/174579371-6c9c256f-9eaa-48fa-8bb4-58dbf58f0bcd.png)
nastool数据：
![Screenshot_20220620_180612](https://user-images.githubusercontent.com/66826612/174578981-81c6f646-b1cc-46f4-975f-ed55f597b675.png)
保种数据因为站点原因可能有误差，但是上传、下载数据也有差别，有点奇怪！

**Comment by lightolly** [comment]
可能是单位转化的问题，待会看看

**Comment by log-time** [comment]
期待大佬对存量各站点的适配！
ps月度流量柱图其实也是可以搞起来的

**Comment by log-time** [comment]
在站点数据这里，是否可以增加批量刷新的按钮和自动刷新的时间点
![Screenshot_20220620_220358](https://user-images.githubusercontent.com/66826612/174619184-63c19273-1443-4a8f-9322-43087e594e3b.png)

**Comment by lightolly** [comment]
> > > 新版本站点可以固定下来了，但是很多站点（包括馒头、套等）数据不准确。
> > > ptpp及站点真实数据：
> > > ![Screenshot_20220620_180524](https://user-images.githubusercontent.com/66826612/174578865-aabe1ae0-d6db-4704-8f86-a83d44236d08.png)
> > > ![Screenshot_20220620_180849](https://user-images.githubusercontent.com/66826612/174579371-6c9c256f-9eaa-48fa-8bb4-58dbf58f0bcd.png)
> > > nastool数据：
> > > ![Screenshot_20220620_180612](https://user-images.githubusercontent.com/66826612/174578981-81c6f646-b1cc-46f4-975f-ed55f597b675.png)
> > > 保种数据因为站点连接性问题可能有误差，但是上传、下载数据也有差别，有点奇怪！
> > 
> > 
> > 问题找到了，用的默认是带宽的计算KB，应该用文件大小的KiB，多谢～～
> 
> 数据显示已正常，666！ 期待大佬对魔改站点的适配

现在有哪些站点数据不正常的，帮忙列下～～

**Comment by log-time** [comment]
u2，北洋园，城市、SSD,还有所有的类似海豚等Gazelle站点

**Comment by log-time** [comment]
NASTOOL数据：
![Screenshot_20220620_232638](https://user-images.githubusercontent.com/66826612/174634866-8a57255d-b69a-4664-83bf-84579d6ce6ed.png)
PTPP数据及站点真实数据：
![Screenshot_20220620_232750](https://user-images.githubusercontent.com/66826612/174635069-5702dfd9-2e4e-450c-8bb3-0931e7d9206a.png)
![Screenshot_20220620_232656](https://user-images.githubusercontent.com/66826612/174634889-71512501-24de-4c01-a22a-51b7b63cfb88.png)

**Comment by dlovew** [comment]
报：不可说现在无法刷新，看日志是直接报错了
错误如下：
站点 不可说 获取流量数据失败：list index out of range - Traceback (most recent call last): File "/nas-tools/pt/sites.py", line 87, in __refresh_pt_data site_user_info.parse() File "/nas-tools/pt/siteuserinfo/site_user_info.py", line 78, in parse self._parse_user_detail_info(self._get_page_content(urljoin(self._base_url, self._user_detail_page))) File "/nas-tools/pt/siteuserinfo/nexus_php.py", line 90, in _parse_user_detail_info if "当前上传" == tds[0].text.strip(): IndexError: list index out of range

**Comment by log-time** [comment]
![IMG_20220621_083216](https://user-images.githubusercontent.com/66826612/174692821-7db8707f-977a-4995-97ec-9c07b4238769.jpg)

**Comment by log-time** [comment]
最新版北洋园数据已能获取，但是分享率显示为0,考虑到北洋园全站hr,不考核分享率，显示为无穷大是否更合适？

**Comment by dlovew** [comment]
柠檬的做种和下载数仍然不正确

**Comment by log-time** [comment]
聆音数据已正常。
U2的等级、用户、上传、下载以及做种体积数据均已正常，但是做种数仍然是错的。
馒头、猫、柠檬的做种体积数据仍然为0
城市所有数据均异常

**Comment by dlovew** [comment]
> > 聆音数据已正常。 U2的等级、用户、上传、下载以及做种体积数据均已正常，但是做种数仍然是错的。 馒头、猫、柠檬的做种体积数据仍然为0，柠檬的做种数也是错误的。 城市所有数据均异常
> 
> 奇怪，馒头我这边数据是对的

我馒头也正常

**Comment by log-time** [comment]
> > 聆音数据已正常。 U2的等级、用户、上传、下载以及做种体积数据均已正常，但是做种数仍然是错的。 馒头、猫、柠檬的做种体积数据仍然为0，柠檬的做种数也是错误的。 城市所有数据均异常
> 
> 奇怪，馒头我这边数据是对的

![IMG_20220623_000338](https://user-images.githubusercontent.com/66826612/175079416-55f569c4-3607-4002-bf24-fda2e5bcc167.jpg)
为啥我的不行，有做种数，没有做种体积

**Comment by log-time** [comment]
![IMG_20220623_000949](https://user-images.githubusercontent.com/66826612/175080593-385274e6-4393-44ff-9330-5f8ff83d8542.jpg)
馒头没有，ttg刷新不了

**Comment by lightolly** [comment]
可能是你的馒头的做种数太多了，个人页面中，目前做种那个可以正常点开么？

**Comment by log-time** [comment]
> 可能是你的馒头的做种数太多了，个人页面中，目前做种那个可以正常点开么？

点不开，自动弹出新页面

**Comment by log-time** [comment]
页面地址
https://kp.m-team.cc/getusertorrentlist.php?userid=****&type=seeding

**Comment by lightolly** [comment]
> 页面地址 https://kp.m-team.cc/getusertorrentlist.php?userid=****&type=seeding

我可能知道原因了，数量太多的原因

**Comment by lightolly** [comment]
ttg的是勋章问题和mt的解析周末找时间一起修复下

**Comment by lightolly** [comment]
> > ttg的是个bug，同u2的种子数应该新的pr可以解决
> 
> 
> 
> pr后，ttg可正常刷新，但是等级信息丢失

新的提交怎么样？尝试做了下修复

**Comment by log-time** [comment]
> > > ttg的是个bug，同u2的种子数应该新的pr可以解决
> > 
> > 
> > pr后，ttg可正常刷新，但是等级信息丢失
> 
> 新的提交怎么样？尝试做了下修复

不好意思，刚刚测试了下，ttg和馒头都已正常，柠檬、猫、还有城市问题依旧

**Comment by lightolly** [comment]
> > > > ttg的是个bug，同u2的种子数应该新的pr可以解决
> > > 
> > > 
> > > pr后，ttg可正常刷新，但是等级信息丢失
> > 
> > 
> > 新的提交怎么样？尝试做了下修复
> 
> 不好意思，刚刚测试了下，ttg和馒头都已正常，柠檬、猫、还有城市问题依旧

好的，其他站点还没适配的，这段时间主要忙其他事情去了
流量图的诉求主要是考虑呈现哪些维度内容？是按照周/月的时间颗粒度的所有站点数据么

**Comment by log-time** [comment]
是的，可以直观了解本周/本月各站点流量变化情况，对于后期养站效果有个直观体现

**Comment by log-time** [comment]
饼图可以考虑修改成今日数据量，在标题处可以增加汇总数

**Comment by lightolly** [comment]
有些后面新增的数据还没在历史数据中，这块需要增加下

**Comment by log-time** [comment]
![Screenshot_20220626_121906](https://user-images.githubusercontent.com/66826612/175799210-6c084e6c-e227-4870-90f2-1808429292dd.png)
柱图周/月数据切换可以考虑以类似方式实现

**Comment by log-time** [comment]
刚发现，馒头的做种数好像又错了，实际是512，现在显示是970

**Comment by lightolly** [comment]
> [站点删除后，统计数据未能同步屏蔽对应站点数据](https://github.com/jxxghp/nas-tools/issues/388)

这个可以优化下 删除的隐藏和不做统计

**Comment by log-time** [comment]
升级后，原来正常显示的不可说的等级丢失

**Comment by lightolly** [comment]
> 升级后，原来正常显示的不可说的等级丢失

这块代码没有变动 是不是网络问题没有获取成功

**Comment by log-time** [comment]
其他数据都是正常的，可以正常更新

**Comment by log-time** [comment]
似乎是上次pr饼图后的问题

**Comment by log-time** [comment]
> > [站点删除后，统计数据未能同步屏蔽对应站点数据](https://github.com/jxxghp/nas-tools/issues/388)
> 
> 这个可以优化下 删除的隐藏和不做统计

已修复

**Comment by log-time** [comment]
猫站做种数和做种体积已正常

**Comment by log-time** [comment]
一个上午使用下来，不知道是不是因为网络问题，馒头和猫的解析偶尔会失败，需要手动再更新一下才能成功。

**Comment by lightolly** [comment]
> 一个上午使用下来，不知道是不是因为网络问题，馒头和猫的解析偶尔会失败，需要手动再更新一下才能成功。

感觉像是cf国内不稳定的原因

**Comment by log-time** [comment]
每个站能增加一个cookie的检查结果反馈吗？cookie过期，目前版本刷新时间似乎也是可以正常更新的

**Comment by log-time** [comment]
![QQ图片20220705152750](https://user-images.githubusercontent.com/66826612/177273597-f8230651-1194-4cbb-8f2c-e2aeacd35573.png)
![QQ图片20220705153015](https://user-images.githubusercontent.com/66826612/177273970-47abb6f2-9f7a-4567-85cf-6743b337bd03.png)
大佬，站点设置里，观众我添加了两次（其中一个是rss官组资源），在站点数据统计这里是只显示一个站点的（这点很赞）。我本人的需求其实第二次添加的“观众-官组”只负责rss官组资源，不需要再次签到，所以添加的“观众-官组”这个站点设置中没设置签到地址和cookie，在站点数据统计这里，原有的站点“观众”被新站点“观众-官组”给替换掉了（我一共设置了三个站点的官组rss，其中朋友和观众都被新站点替换掉，柠檬可能原来就没有适配，所以还是显示的柠檬），然后又因为没有填写cookie所以数据获取不成功，全部数据均显示为0（图中有数据是我后来又添加了cookie信息，但是站点名称还是显示的新增站点名称）。我的需求是，重复配置同一站点的，数据是否可以读取优先级高的站点配置信息？

**Comment by lightolly** [comment]
> ![QQ图片20220705152750](https://user-images.githubusercontent.com/66826612/177273597-f8230651-1194-4cbb-8f2c-e2aeacd35573.png)
> 
> ![QQ图片20220705153015](https://user-images.githubusercontent.com/66826612/177273970-47abb6f2-9f7a-4567-85cf-6743b337bd03.png)
> 
> ![QQ图片20220705154711](https://user-images.githubusercontent.com/66826612/177277115-f1abc085-5c10-4e68-b13b-0290b24b2012.png)
> 
> ![QQ图片20220705154820](https://user-images.githubusercontent.com/66826612/177277348-8cd0ca65-f371-4aee-8d22-ea538e2c1369.png)
> 
> 
> 
> 大佬，站点设置里，观众我添加了两次（其中一个是rss官组资源），在站点数据统计这里是只显示一个站点的（这点很赞）。我本人的需求其实第二次添加的“观众-官组”只负责rss官组资源，不需要再次签到，所以添加的“观众-官组”这个站点设置中没设置签到地址和cookie，在站点数据统计这里，原有的站点“观众”被新站点“观众-官组”给替换掉了（我一共设置了三个站点的官组rss，其中朋友和观众都被新站点替换掉，柠檬可能原来就没有适配，所以还是显示的柠檬），然后又因为没有填写cookie所以数据获取不成功，全部数据均显示为0（图中有数据是我后来又添加了cookie信息，但是站点名称还是显示的新增站点名称）。所以现在的问题是，重复配置同一站点的，是否可以优先读取优先级高的站点配置信息？

@jxxghp 看看 我感觉这个可以改下rss那边获取的逻辑，增加下标签什么的 标识不同的rss配置

**Comment by log-time** [comment]
![Screenshot_20220706_075917](https://user-images.githubusercontent.com/66826612/177436060-a390b115-7251-457d-ae0b-38f7c4ca2be1.png)
![Screenshot_20220706_075950](https://user-images.githubusercontent.com/66826612/177436106-2952b6fc-e1d5-4ae7-9127-788b39180437.png)

聆音数据获取不完整，做种数和做种体积都是0，但是无报错。手动刷新后的数据成功获取，如下：
![Screenshot_20220706_080418](https://user-images.githubusercontent.com/66826612/177436296-216eb3e4-f8d5-43d2-acb2-263d67fb3171.png)

**Comment by lightolly** [comment]
> ![Screenshot_20220706_075917](https://user-images.githubusercontent.com/66826612/177436060-a390b115-7251-457d-ae0b-38f7c4ca2be1.png)
> 
> ![Screenshot_20220706_075950](https://user-images.githubusercontent.com/66826612/177436106-2952b6fc-e1d5-4ae7-9127-788b39180437.png)
> 
> 
> 
> 聆音数据获取不完整，做种数和做种体积都是0，但是无报错。手动刷新后的数据成功获取，如下：
> 
> ![Screenshot_20220706_080418](https://user-images.githubusercontent.com/66826612/177436296-216eb3e4-f8d5-43d2-acb2-263d67fb3171.png)
> 
> 

我这边也有概率性出现这个问题，我可能知道原因了

**Comment by lightolly** [comment]
调整了下 我这边使用目前来看都是正常了～

**Comment by log-time** [comment]
柠檬大佬有空适配吗？

**Comment by log-time** [comment]
> 调整了下 我这边使用目前来看都是正常了～

![Screenshot_20220707_213135](https://user-images.githubusercontent.com/66826612/177786286-3ccf00f1-46e6-4005-b276-906aa9b34b42.png)
测试了一整天，绝大部分站点都是正常的。但是个别站点的状态显示好像还是不准确，图中ptt没有刷新成功，但是状态提示是正常的。

**Comment by lightolly** [comment]
是的，cookies过期同站点连接失败定义成不同的错误
柠檬还没有号 现在显示什么样？

**Comment by log-time** [comment]
![YYBXJP3FU)GHWY0@LDWW%)D](https://user-images.githubusercontent.com/66826612/177904712-82960045-f794-4762-9d02-73c9a8927922.png)
保种数和保种体积是错误的，其他都正常

**Comment by lightolly** [comment]
看起来柠檬去掉了单独查询做种数的接口，合入到user页面了

**Comment by log-time** [comment]
> 看起来柠檬去掉了单独查询做种数的接口，合入到user页面了

不知道什么原因，今天就是特开心。全自动刷流来了，大佬流量图啥时候安排上？:-)

**Comment by lightolly** [comment]
> > 看起来柠檬去掉了单独查询做种数的接口，合入到user页面了
> 
> 
> 
> 不知道什么原因，今天就是特开心。全自动刷流来了，大佬的流量图近期有计划安排上吗？:-)
> 
> 
> 
> 

哈哈～ 最近出去玩去了 会有的会有的

**Comment by log-time** [comment]
大佬，这个issue图片太多，且功能基本都已实现，查看加载很不方便。我把这个issue关了，后续重开新的issue啊
