### ISSUE TITLE
下载设置为空，无选项

### ISSUE THREAD

**Issue by Wangsc1** [jxxghp/nas-tools#2839]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.4
>
> 环境: docker
>

## 你遇到什么问题了？
最新的de846494下载设置为空，无选项

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/26079238/210757764-82feedce-5d37-4811-8886-da1cb1155f72.jpeg)
![image](https://user-images.githubusercontent.com/26079238/210757788-167f4496-00b3-4481-9f35-0166fbf8165a.jpeg)

**Comment by jxxghp** [comment]
再更新下，刚好卡到过程提交了。

**Comment by Wangsc1** [comment]
> 再更新下，刚好卡到过程提交了。

更新了还是一样，web更新和重启docker都试过了

**Comment by Shurelol** [comment]
等会在更新下，还没推送完
