### ISSUE TITLE
关于2.75版本web界面优化调整的建议

### ISSUE THREAD

**Issue by JX0204** [jxxghp/nas-tools#2847]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5 5d24c31
>
> 环境: docker 

## 你想要新增或者改进什么功能？

> 现有web界面优化建议两项请作者酌情考虑：
①2.75版本调整了推荐选项布局，比之前清爽许多，分类也更清晰建议进一步优化在推荐下增加动漫选项
<img width="231" alt="image" src="https://user-images.githubusercontent.com/115469315/210828275-14b305f9-c44f-4513-96b7-12b6937150cf.png">
②站点管理》》站点维护》》站点测试中的全选复选框建议与下方对齐并增加全选字样会比较美观
<img width="214" alt="image" src="https://user-images.githubusercontent.com/115469315/210829095-b5f3733b-7e8d-4fef-a795-d4e3a083e1af.png">

以上建议请作者酌情考虑，是否可在后期调整优化；
在此感谢作者的无私付出，带来优秀的作品！！！

**Comment by jxxghp** [comment]
第2点是bug，dev已经改了。
第1点主要是现在动漫就两个分类，单独菜单撑不满一页。
