### ISSUE TITLE
关于订阅的问题

### ISSUE THREAD

**Issue by smily1223** [jxxghp/nas-tools#285]
1.订阅貌似用的是站点里面的rss地址进行更新。没有配置rss地址的话，订阅功能就用不上，所以能否加个选择订阅搜寻是用rss还是用索引器？（配置了索引器，又没配置rss，有可能不知道是哪里的问题）

2.对于一些种子，主标题是不可以识别出TMDB信息的，但是副标题可以识别出TMDB信息。（这就导致一些剧集要快速搜索出来，然后去看副标题选择正确的资源）注：其实这里不确定是哪里的问题，但是实际识别有很多没识别出来。
![image](https://user-images.githubusercontent.com/37728519/173511906-91ce9796-fc58-4d59-a8a7-8fcf898138ec.png)
![image](https://user-images.githubusercontent.com/37728519/173512596-ab064ebd-5324-4ecc-9365-18c2812ea759.png)

3.手动下载的能不能更新一下订阅信息。比如这09集是我快速搜索出来下载的，实际也能识别。但是下载完后，订阅里的信息并不会更新，是没设置rss原因吧。
![image](https://user-images.githubusercontent.com/37728519/173510093-49fd77cc-2993-4bd9-927d-ae0c6ab7a1b2.png)

**Comment by jxxghp** [comment]
1.订阅就是rss，新加订阅存量搜索一遍是为了避免加订阅时之前已经出了的能补上。后面增量的就应该用RSS啊，频繁去查PT站是不合适的。

**Comment by jxxghp** [comment]
2.副标题不是识别的，就是显示的PT资源的副标题，命名乱七八糟的是没办法都识别出来的。

**Comment by jxxghp** [comment]
3.自己手动下的就自己手动去点下刷新，不然就等下一次命中订阅更新。

**Comment by jxxghp** [comment]
还有就是你上面截图的显示的都是种子名称并没有副标题，用的是prowlarr？

**Comment by smily1223** [comment]
> 
是prowlarr

**Comment by jxxghp** [comment]
> > 
> 
> 是prowlarr
> 
> 

这个现在有问题，不会返回副标题。

**Comment by xxzj990** [comment]
> 

大大，我发现一种情况手动刷新也不行，就是名字中有中文逗号的电视剧，如下图：
![截屏2022-06-15 上午9 02 23](https://user-images.githubusercontent.com/5134154/173714315-b97d6ca6-dc21-4b84-8e98-2ae489239dfa.png)

显示为0，其实已经有2集了
