### ISSUE TITLE
媒体整理下，历史记录点击没有反应

### ISSUE THREAD

**Issue by 707214981** [jxxghp/nas-tools#2851]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.7.5
> 环境: docker or windows or Synology
> docke

## 你遇到什么问题了？

> 描述一下你遇到的问题
媒体整理下，历史记录点击没有反应

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
已经浏览过了，但是没有相关问题

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
![微信图片编辑_20230106104135](https://user-images.githubusercontent.com/93177539/210919037-797d7587-77e3-451e-a3a5-b5b6fae59c08.jpg)

> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
数据相关，无法重现，没办法分析。备份后重新恢复一下，清掉之前的历史记录。
