### ISSUE TITLE
关于手动识成功后，未识别目录里面硬链接仍然存在的问题

### ISSUE THREAD

**Issue by 188334911** [jxxghp/nas-tools#2852]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> v2.74
> 环境: docker or windows or synology
AMD64 Docker
## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
在“目录同步”里面添加目录时，设置了未识别的目录，nastools会将识别失败的文件建立相应的硬链接到未识别目录，再通过“媒体整理”栏目下的“手动识别”后，基本可以正确的识别并硬链接相应的媒体到目录，但是有个问题，手动识别并建立硬链接成功后，未识别目录下的文件仍然存在，需要手动的去删除，能不能在手动识别成功后，自动删除“未识别目录”里面的硬链接？
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
没有

**Comment by 188334911** [comment]
电影、剧集手工识别成功，未识别目录里面相应的硬链接自动删除后 ，未识别目录里面剩余的就是花絮、特典和OST之类的，可以直接导入emby建立成一个花絮、特典专用的媒体库

**Comment by jxxghp** [comment]
不想留着就不要设置未识别目录。
