### ISSUE TITLE
导出站点统计图文字看不到

### ISSUE THREAD

**Issue by luoxiao-xy** [jxxghp/nas-tools#2853]
> NAStool 版本: 2.7.5
>
> 环境: 极空间Z4s docker

![nastool_statistics (9)](https://user-images.githubusercontent.com/49856280/210923914-473cd6cc-17b1-4007-955d-fd3b8e449da6.png)

由于图片背景颜色黑色，文字颜色也是黑色导致文字看不到了。

**Comment by Shurelol** [comment]
换夜间模式下生成，或者地址不要用代理后的

**Comment by Shurelol** [comment]
黑暗模式和明亮模式来回切换下，再生成，应该就好了
