### ISSUE TITLE
SkrBT地址

### ISSUE THREAD

**Issue by youyifentian** [jxxghp/nas-tools#2859]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.5
>
> 环境: docker and Synology
>

## 你遇到什么问题了？

> 在nt里面的SkrBT搜索到的种子地址是：https://skrbtfi.top/detail/CC4DA/t8rKs3PojwUOUGK7P
打开会跳转到https://skrbtgi.top/，并不是同一个地址，然后在跳转后的网站里面搜索，也可以搜索到资源
https://skrbtgi.top/detail/49A63/lMoz9XC8C3Pf2vR-adGStljwASK
是这个网站有多个网址吗，而我这里就跳转到其他网址导致种子搜索到了，但是下载时会跳转就没了

**Comment by jxxghp** [comment]
下载时会跳转就没了——是指啥？提供日志。
这个站点是不支持直接打开页面的，有反抓。

**Comment by youyifentian** [comment]
> 下载时会跳转就没了——是指啥？提供日志。 这个站点是不支持直接打开页面的，有反抓。

![1](https://user-images.githubusercontent.com/5012570/211135343-6387d744-4f60-4a0e-94da-40c6635defe5.jpg)
![2](https://user-images.githubusercontent.com/5012570/211135350-8dbe9abf-3aab-439a-8f38-62bc196c1324.jpg)
日子里面都是搜索记录，没有别的，点击下载也只弹出了错误提示，日志没有downloander错误啥的，就只有正在查询TMDB电影：258424 ...
然后我试着点开报错里面的网址就出现了这个
![3](https://user-images.githubusercontent.com/5012570/211135397-ef9f2655-a990-4d5b-b858-b7a05de6a24f.jpg)
然后跳转之后的网站就变成了 https://skrbtgi.top/ 跟搜索结果 https://skrbtfi.top/detail/DFAE1/qgmNqlcfz1fsBvHv5z 里面的并不是同一个域名：一个是skrbtfi，跳转之后变成了skrbtgi，然后我试着在跳转之后的网站里面搜索，也可以出来结果
![4](https://user-images.githubusercontent.com/5012570/211135493-04ebae5e-5d23-4c2a-91c0-3a11e4488d2d.jpg)

你可以试着搜索一下这个，看看能不能复现这种情况

**Comment by OflyingchickenO** [comment]
它就是识别bt/magnet 地址失效了, 我停用它了
