### ISSUE TITLE
2.7.5版目录同步问题及订阅问题

### ISSUE THREAD

**Issue by DrAlanY** [jxxghp/nas-tools#2865]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5
>
> 环境: arm docker 
>

## 你遇到什么问题了？

> 当源目录中添加视频文件时，可以自动同步，目的目录会出现硬链接；当源目录中添加的是放有视频文件的文件夹时，不能触发监控，不发生自动同步，但可以通过“服务-目录同步”手动执行，在目的目录生成硬链接。
订阅的电视剧不回自动检索下载

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 各种方法都试了 

## 你期望的结果

> 指导正确设置

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![E2EF0EBA-75C7-41E8-AEA4-2B22D2F076F1](https://user-images.githubusercontent.com/121947771/211124394-598449fa-cf62-4194-b686-97fe31fc7aab.jpeg)

**Comment by jxxghp** [comment]
提示不是很明显吗？时区测设置
