### ISSUE TITLE
希望可以对远程搜索，订阅设置不同的默认过滤规则

### ISSUE THREAD

**Issue by luoxiao-xy** [jxxghp/nas-tools#2870]
希望可以对远程搜索，订阅设置不同的默认过滤规则。
现在只能设置默认规则，然后远程搜索和订阅订阅都默认使用同一个过滤规则。
对于搜索和订阅想要不同的媒体要求，只能通过手动高级搜索和添加订阅很不方便。

比如搜索：默认各种清晰度我都想搜索到。而订阅：默认我只想要4K。
对于简单的，在设置界面，可以为搜索和订阅设置不同的默认规则。

**Comment by jxxghp** [comment]
订阅界面不能选规则？

**Comment by luoxiao-xy** [comment]
> 订阅界面不能选规则？

可以选，但是不方便，特别是一键订阅。

可能在站点设置中增加  过滤规则拆分为订阅过滤规则和搜索订阅规则

现在站点配置无法将订阅和搜索分开配置过滤规则
