### ISSUE TITLE
刷流任务增加对下载目录剩余空间监控的功能

### ISSUE THREAD

**Issue by szjawo** [jxxghp/nas-tools#2873]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 刷流任务增加对下载目录剩余空间监控的功能，使刷流任务在特定目录空间不足时停止下载。

## 这个功能有什么可以参考的资料吗？

> 类似Flexget的“free_space”语句的功能

**Comment by jxxghp** [comment]
不要重复提相同的问题！
#2542
