### ISSUE TITLE
跪求两点自定义订阅的功能，应该不难添加，还有跪求请不要放弃win版

### ISSUE THREAD

**Issue by makerdegit** [jxxghp/nas-tools#2879]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.4
>
> 环境: windows

## 你想要新增或者改进什么功能？

>对于自定义订阅我想请求两个功能
        第一个是希望自定义订阅也能加入到订阅日历，由于没有pt所以比较依赖bt站的rss，用jackett转出来的rss非常好用，通过自定义订阅里的各项设置，可以精准追更，因为我看日志里是会对自定义订阅的内容去tmdb查询的，还有集数等等的识别，只有能通过查询的才可以正常下载。这样是不是也可以把自定义订阅放进订阅日历
       第二个是觉得这个自定义订阅的功能太强了，我找了很久完全没有自定义功能这么强的可以替代，所以能否开一个开关，关闭查询tmdb等等的流程，做一个普通的rss下载器，不瞒你说，rsshub有个下av的rss，我通过自定义解析器最后实现精准筛选，但是使用时发现，运行时需要tmdb查询啥的，查不到数据就拉倒了，不会进行下一步操作，所以希望加一个开关，能让我当普通rss下载器用，qb的不够用，因为不能自定义解析器，有时候一些关键字在链接的名称里而不是标题上

另外请不要放弃win版，我一直用的好好的，应该很多人的都没啥问题，win上用docker实在是太麻烦了，而且也不方便不稳定，跪求继续更新win版

## 这个功能有什么可以参考的资料吗？

> 无

**Comment by Shurelol** [comment]
第二点在计划中

**Comment by makerdegit** [comment]
> 第二点在计划中

希望第一个也能考虑一下，不知道为啥，nastool对rarbg的搜索有点差，我直接在jackett里用rarbg也发现那个api有问题，短时间多次搜索好像就会不出结果。不知道大佬有空优化一下不，因为欧美剧主要靠rarbg了，目前稳定的方法就是jackett转的rss链接。然后动漫用的蜜柑计划的rss，直接搜索的结果感觉也有点问题，而且它那个命名也不是传统规范模式，所以也用的rss比较稳定，最后结果就是基本上全用的自定义rss追剧，但订阅日历里没有显示就感觉有点难受。

**Comment by makerdegit** [comment]
偶对，因为我是win版没有发布最新版，现在2.7.5带浏览器内核了，所以我不知道对rarbg等索引的支持效果咋样了，我是按之前版本的体验说的那些
