### ISSUE TITLE
Gotify 错误 返回  ”gotify 发送测试消息失败：未获取到返回信息“

### ISSUE THREAD

**Issue by ciegyet** [jxxghp/nas-tools#2885]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: ：v2.7.5
>
> 环境: docker 
>

## 你遇到什么问题了？

> 使用Gotify 推送测试 日志 返回 ”gotify 发送测试消息失败：未获取到返回信息“

## 做出的尝试
https://github.com/jxxghp/nas-tools/commit/bcc8ae4ce1af3bc0e930debb054404a5716304ca
更换 Gotify 服务器 | 排除
更换Gotiy token 通信参数 | 排除
docker exec -it  进入容器测试 ping host 网络可以通信 | 排除

## 给出程序界面截图、后台运行日志或配置文件

> ![image](https://user-images.githubusercontent.com/20328741/211151557-947b26ec-7bfc-444d-b84d-79c3e8f16d5b.png)
> ![image](https://user-images.githubusercontent.com/20328741/211151606-6d94fba6-7e9f-474f-bbea-3619b36a3519.png)
>![image](https://user-images.githubusercontent.com/20328741/211151770-27dccc2d-7064-4b32-9e7a-99a21ea4738d.png)

**Comment by ciegyet** [comment]
最新测试：原因是不支持 HTTPS

**Comment by jxxghp** [comment]
是你自已搭的环境不支持https但又配置的https吧？
