### ISSUE TITLE
nastool里填的clash代理对自定义订阅不起作用

### ISSUE THREAD

**Issue by makerdegit** [jxxghp/nas-tools#2886]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.4
>
> 环境: windows
>

## 你遇到什么问题了？

>实测nastool里填的clash代理对自定义订阅不起作用，clash里也看不到调用，tmbd那些正常

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
#2039
