### ISSUE TITLE
下载软件监控, 文件入庫后 。 文件转移服务仍不断执行, 提示"文件转移失败,文件不存在"

### ISSUE THREAD

**Issue by OflyingchickenO** [jxxghp/nas-tools#2891]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5
>
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 我的相关配置:
1 . 设置>基础设置>下载软件监控(ARIA2c)
2. 媒体>默认文件转移方式>移动

我的理解:
文件下载完成后/做种完成后会自动入库,  之后就不会再进行文件转移服务(默认5分钟一次)

情况:
文件下载完成后,自动入库成功. 文件转移服务仍不断执行, 提示"文件转移失败,文件不存在" 。
我的A文件: 大约凌晨15分时入库, 但在早上10点多还在执行文件转移

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
yes
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 下载软件监控: 文件下载完成后/做种完成后会自动入库,  之后就不会再进行文件转移服务(默认5分钟一次),重覆报错

## 给出程序界面截图、后台运行日志或配置文件
![IMG_3149](https://user-images.githubusercontent.com/90878499/211179209-77825237-1eb7-4f8b-9d28-09306fda6e87.png)
![IMG_3150](https://user-images.githubusercontent.com/90878499/211179212-2fbded52-d9e6-4ac2-88d4-805d22614243.png)
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
ARIA2 就是不支持
