### ISSUE TITLE
服务启动失败，显示pytz.exceptions.UnknownTimeZoneError: 'CST-8'

### ISSUE THREAD

**Issue by Drunkwang** [jxxghp/nas-tools#2894]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5
> 环境: docker

## 你遇到什么问题了？

> docker内显示运行状态，但是无法启动。查看日志报错如下

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 正常运行

> Docker日志如下
stdout: 开始启动服务...
stdout: Exception: 'CST-8'
stdout: Callstack:
stdout: Traceback (most recent call last):
stdout:   File "/nas-tools/app/scheduler.py", line 248, in run_scheduler
stdout:     Scheduler().run_service()
stdout:   File "/nas-tools/app/scheduler.py", line 45, in run_service
stdout:     self.SCHEDULER = BackgroundScheduler(timezone=Config().get_timezone(),
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
stdout:     self.configure(gconfig, **options)
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 131, in configure
stdout:     self._configure(config)
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/background.py", line 29, in _configure
stdout:     super(BackgroundScheduler, self)._configure(config)
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 701, in _configure
stdout:     self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
stdout:   File "/usr/lib/python3.10/site-packages/apscheduler/util.py", line 91, in astimezone
stdout:     return timezone(obj)
stdout:   File "/usr/lib/python3.10/site-packages/pytz/__init__.py", line 188, in timezone
stdout:     raise UnknownTimeZoneError(zone)
stdout: pytz.exceptions.UnknownTimeZoneError: 'CST-8'
stderr: 2023-01-08 14:27:21,446	ERROR: 启动定时服务失败：'CST-8' - Traceback (most recent call last):
stderr:   File "/nas-tools/app/scheduler.py", line 248, in run_scheduler
stderr:     Scheduler().run_service()
stderr:   File "/nas-tools/app/scheduler.py", line 45, in run_service
stderr:     self.SCHEDULER = BackgroundScheduler(timezone=Config().get_timezone(),
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
stderr:     self.configure(gconfig, **options)
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 131, in configure
stderr:     self._configure(config)
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/background.py", line 29, in _configure
stderr:     super(BackgroundScheduler, self)._configure(config)
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 701, in _configure
stderr:     self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
stderr:   File "/usr/lib/python3.10/site-packages/apscheduler/util.py", line 91, in astimezone
stderr:     return timezone(obj)
stderr:   File "/usr/lib/python3.10/site-packages/pytz/__init__.py", line 188, in timezone
stderr:     raise UnknownTimeZoneError(zone)
stderr: pytz.exceptions.UnknownTimeZoneError: 'CST-8'

**Comment by Shurelol** [comment]
设时区
