### ISSUE TITLE
媒体库管理、媒体文件删除

### ISSUE THREAD

**Issue by laoxinH** [jxxghp/nas-tools#2897]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vv2.7.5 ec0aa372
>
> 环境: synology

## 你想要新增或者改进什么功能？
是否考虑会增加媒体库的管理功能，删除媒体文件的功能，比如删除采用硬链接的电影可以同时删除源文件
> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？
无

**Comment by Shurelol** [comment]
历史记录，文件管理
