### ISSUE TITLE
transmission需要授权

### ISSUE THREAD

**Issue by jasonchio-cn** [jxxghp/nas-tools#29]
![image](https://user-images.githubusercontent.com/36125147/159836267-9d63aade-3722-41b1-945d-7118f052ee0d.png)

transmission是以套件的形式安装在群晖6.2.3上，nas-tools配置中transmission的host、name、password都确认过是正确的
可是容器日志还是打出来需要transmission的权限，可以帮忙看一下吗
![image](https://user-images.githubusercontent.com/36125147/159836662-13f63add-c924-492e-8efb-35cf1f5b31c3.png)

**Comment by BENBENBAI** [comment]
host改成  http:192.168.123.222   试试
