### ISSUE TITLE
编译成exe,有教程么？

### ISSUE THREAD

**Issue by gyshier** [jxxghp/nas-tools#2900]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or synology

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Shurelol** [comment]
Pyinstaller

**Comment by gyshier** [comment]
> Pyinstaller

编译code里的那个PY文件呢

**Comment by gyshier** [comment]
> 

谢谢大佬解答
