### ISSUE TITLE
Qbittorrent下载失效

### ISSUE THREAD

**Issue by MrLv0816** [jxxghp/nas-tools#2901]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5
>
> 环境: Synology
>

> 查找过wiki但是没有解决

qb下载失败，测试链接正常，重新安装套件版与docker版均无效

但是通过 Qbittorrent webui添加下载任务均正常使用

![image](https://user-images.githubusercontent.com/46812909/211198534-c7a24b63-83fa-4166-88f2-32243d77c4c1.png)
![image](https://user-images.githubusercontent.com/46812909/211198590-d70bfeed-5398-4c2e-b9a0-a2ef59bc5815.png)
![image](https://user-images.githubusercontent.com/46812909/211198595-92f56e92-ae65-4a39-aeb9-455f9dc685c6.png)
![image](https://user-images.githubusercontent.com/46812909/211198631-fab17a34-3728-4c58-a316-00fc1b8feaec.png)

**Comment by BeenSen** [comment]
我也这问题哈哈哈，不过我是用的群晖套件版,QB是部署在另外一台Linux上的，测试能过，同样报错。下载目录是填写的linux的下载目录，访问目录是填的NAS下挂载的linux下载目录。

**Comment by BeenSen** [comment]
> 我也这问题哈哈哈，不过我是用的群晖套件版,QB是部署在另外一台Linux上的，测试能过，同样报错。下载目录是填写的linux的下载目录，访问目录是填的NAS下挂载的linux下载目录。

哈哈哈 我解决了，重启大法好。整个群晖重启就好了
