### ISSUE TITLE
硬链接模式下，能否增加emby删除媒体库后同步删除源文件

### ISSUE THREAD

**Issue by 188334911** [jxxghp/nas-tools#2902]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.75
> 环境: docker or windows or synology
amd 64 docker
## 你想要新增或者改进什么功能？

因为需要做种所以用的硬链接模式，我是通过emby来管理的所有媒体文件，看过之后不需要保留的媒体都直接通过emby删除，但是现在通过硬链接的模式，从emby删除后只能删除硬链接的文件，源文件没有动，需要单独再去查找源文件并删除，有时候通过不是pc（比如手机、平板、电视）的客户端管理emby的媒体文件，删除源文件就非常麻烦。
感谢作者

**Comment by Shurelol** [comment]
历史记录，文件管理

**Comment by 188334911** [comment]
> 历史记录，文件管理
感谢回答
我知道这里可以删除媒体库和源文件
我的意思是当我在emby里面点击删除按钮后，nastool能同步直接删除源文件，而不是仅仅删除硬链接文件
![del](https://user-images.githubusercontent.com/54146909/211203703-40b96583-84b2-4f76-b98a-a698cbe8134c.png)

**Comment by Shurelol** [comment]
没有计划

**Comment by 188334911** [comment]
好的~ 谢谢
