### ISSUE TITLE
ACG.RIP 匹配成功的资源没有进行下载

### ISSUE THREAD

**Issue by OflyingchickenO** [jxxghp/nas-tools#2903]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5
>
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> ACG.RIP 匹配成功的资源没有进行下载,不是个别情况,试了好几个动漫都一样

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![擷取](https://user-images.githubusercontent.com/90878499/211203500-606bea8d-ca1c-4508-9134-aed032f27df9.PNG)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
会不会下载，还得看匹配到的资源本地有没有，季集对不对得上。
日志贴全，你这没法分析。
