### ISSUE TITLE
豆瓣想看抓取功能增强

### ISSUE THREAD

**Issue by yefoenix** [jxxghp/nas-tools#2904]
## 你使用的 NAStool 是什么版本，什么环境？

synology v2.7.1 46fb995e

## 你想要新增或者改进什么功能？

豆瓣想看自动抓取功能，希望能允许针对不同用户设定不同的列表，
例如，我想抓取自己的「想看」列表，和某影评大V的「看过」列表。
（更进一步，如果能对「看过」列表里面该 id 自己的评分进行筛选就更好了，例如自动订阅 XXX 看过且给分大于8分的电影。）

## 这个功能有什么可以参考的资料吗？

暂无

**Comment by Shurelol** [comment]
建议用rsshub
