### ISSUE TITLE
替換+集偏移 /  集偏移 沒有生效

### ISSUE THREAD

**Issue by OflyingchickenO** [jxxghp/nas-tools#2906]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5
>
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

>  測試用文件名:  k山z白03j.HD1080p.mp4
不知是否我理解问题, 设定的(替换+集偏移) / (集偏移) 都不会生效
![2](https://user-images.githubusercontent.com/90878499/211228782-9635e6f7-a011-4bb9-b558-1d5dfa4a7c02.PNG)
![1](https://user-images.githubusercontent.com/90878499/211228786-cbb23688-5ee5-45f1-921f-93c2a54e7a1b.PNG)

 

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
已参考 https://github.com/jxxghp/nas-tools/issues/1431

## 你期望的结果

>> 要是可以增加以正则来直接替换就太好了。
例如 : 
测试文件名:  k山z白S303j.HD1080p
匹配使用正则: (.+?)S(\d)(\d+)j.HD1080p.mp4
被替换词: $1
替换词: 侍酒令
季偏移: $2 #可以加运算符 e.g. $2+1 >> 3+1=4
集偏移:$3 #可以加运算符 e.g. $3*2 >> 3*2=6

![3](https://user-images.githubusercontent.com/90878499/211228876-db3a4fc3-b922-4f6d-87ef-142bcfbb51c8.PNG)
![4](https://user-images.githubusercontent.com/90878499/211229042-ae78fcef-2105-458c-a0f8-e87f0c003ec8.PNG)
![5](https://user-images.githubusercontent.com/90878499/211228891-d97fc26f-e0d5-4859-88ba-05414141ce6a.PNG)
![6](https://user-images.githubusercontent.com/90878499/211228896-153ba9c4-84ac-4cf0-9bd8-dfa1f005258a.PNG)

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/211234669-85649be1-f7f1-46e2-968a-0d76f05d6e8d.png)
前后识别词注意转义
