### ISSUE TITLE
豆瓣电视剧推荐只能显示5个

### ISSUE THREAD

**Issue by git-0101** [jxxghp/nas-tools#2908]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5-Lite
>
> 环境: docker
>

## 你遇到什么问题了？

> 如题：
![Screenshot_20230109_132329](https://user-images.githubusercontent.com/115487446/211245796-dff3ec0a-fd94-4072-87e0-1b67083ad7d1.jpg)

**Comment by Shurelol** [comment]
往下滑刷新

**Comment by git-0101** [comment]
> 往下滑刷新

试了下刷新不了。
大佬，之前关于瓷器和ttg不能搜索和获取站点资源的情况，排查了各种情况，也有群友遇到了相同问题。退回2.7.1就正常了。还望大佬研究下，感激！

**Comment by git-0101** [comment]
> 往下滑刷新

试了下刷新不了。
大佬，之前关于瓷器和ttg不能搜索和获取站点资源的情况，排查了各种情况，也有群友遇到了相同问题。退回2.7.1就正常了。还望大佬研究下，感激！

**Comment by git-0101** [comment]
> > 往下滑刷新
> 
> 试了下刷新不了。 大佬，之前关于瓷器和ttg不能搜索和获取站点资源的情况，排查了各种情况，也有群友遇到了相同问题。退回2.7.1就正常了。还望大佬研究下，感激！

重启不管用，重装后豆瓣电视剧推荐好了，哈哈。

**Comment by jxxghp** [comment]
> > 往下滑刷新
> 
> 试了下刷新不了。 大佬，之前关于瓷器和ttg不能搜索和获取站点资源的情况，排查了各种情况，也有群友遇到了相同问题。退回2.7.1就正常了。还望大佬研究下，感激！

ttg和瓷要支持浏览器仿填的环境的才可以用。

**Comment by git-0101** [comment]
> > > 往下滑刷新
> > 
> > 
> > 试了下刷新不了。 大佬，之前关于瓷器和ttg不能搜索和获取站点资源的情况，排查了各种情况，也有群友遇到了相同问题。退回2.7.1就正常了。还望大佬研究下，感激！
> 
> ttg和瓷要支持浏览器仿填的环境的才可以用。

好的，明白啦！谢谢大佬！！！
