### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by Matzoh** [jxxghp/nas-tools#2911]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5
>
> 环境: docker
>

## 你遇到什么问题了？

> nastools 出现错误无法访问，需要重启容器才可以解决

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> ~~重启容器可恢复~~
> 和之前不同，重启、构建、替换三天前的config都无法启动

## 你期望的结果

> 修复 BUG

![错误截图](https://cdn.jsdelivr.net/gh/matzoh/wzx@master/uPic/2023/01/2023_01_09_iShot_2023-01-09_16.51.44.png)

![错误截图 2](https://cdn.jsdelivr.net/gh/matzoh/wzx@master/uPic/2023/01/2023_01_09_iShot_2023-01-09_16.56.12.png)

**Comment by jxxghp** [comment]
检查容器内xvfb进程还在不在
