### ISSUE TITLE
建议功能：转移后通知jellyfin刷新媒体库

### ISSUE THREAD

**Issue by firstvip** [jxxghp/nas-tools#292]
![捕获](https://user-images.githubusercontent.com/41404652/173715443-06aad80f-08c6-4d5a-9bb3-6b14d477d106.PNG)
查到大佬说jellyfin的api暂不支持通知刷新媒体库，不知道现在是否支持了或者有没有其他办法。
jellyfin默认12小时扫描媒体库，下载和转移后短时间内看不到识别后的信息，但如果把扫描媒体库间隔缩短，磁盘读写次数又高的厉害，希望能解决这个问题，感谢大佬的辛勤工作。

**Comment by jxxghp** [comment]
现在应该支持的，是测试了不工作吗

**Comment by firstvip** [comment]
需要设置jellyfin或者nastools吗？现在不会刷新
