### ISSUE TITLE
prowlarr测试成功后搜索无结果显示没有有效的索引器配置

### ISSUE THREAD

**Issue by fsxyhjgsrfz** [jxxghp/nas-tools#2924]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5
>
> 环境: docker or windows or Synology
>docker
asustor as5304t

## 你遇到什么问题了？

> 描述一下你遇到的问题
![屏幕截图 2023-01-09 011432](https://user-images.githubusercontent.com/122225422/211318079-0a060603-361b-40e9-868c-f6c6b999bd91.png)
![屏幕截图 2023-01-09 011522](https://user-images.githubusercontent.com/122225422/211318092-8f138570-ac51-4993-9b2b-607902d5a82a.png)
![屏幕截图 2023-01-09 214033](https://user-images.githubusercontent.com/122225422/211321463-8165a760-db0e-42f2-9a34-4c85bdcbabe6.png)

索引器使用prowlarr，测试成功后，搜索任何内容都是无结果，日志显示没有有效的索引器配置。prowlarr已经配置索引器并可以使用。
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
搜索过，没有找到相同问题

## 你期望的结果

> 描述以下你期望的结果
希望解决问题
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![屏幕截图 2023-01-09 213001](https://user-images.githubusercontent.com/122225422/211319392-0504605e-f379-43a2-b13e-4f7322d4bc54.png)
![屏幕截图 2023-01-09 213526](https://user-images.githubusercontent.com/122225422/211320470-8dbd0cac-a76b-476f-b0fb-2c901e3913c8.png)

**Comment by jxxghp** [comment]
你在浏览器中输入这个地址，看是否会返回数据：{self.host}替换为http://IP:PORT/  {self.api_key}替换为你的Prowlarr的Api Key

{self.host}api/v1/indexerstats?apikey={self.api_key}

**Comment by fsxyhjgsrfz** [comment]
现在过年回家了，nas不在这边看不了，要年后才能再试

**Comment by 892899273** [comment]
我也出现这个问题

**Comment by 892899273** [comment]
![Uploading F92829EA-A049-43E1-B339-60812E7B9909.png…]()

**Comment by 892899273** [comment]
![Uploading CE935F0C-0F7D-4A41-A44A-8CF4DAA69CD0.png…]()

**Comment by 892899273** [comment]
![(HDPGGM5HGY 4}@PT~4~3WG](https://user-images.githubusercontent.com/119661718/212807051-778feeac-9f3d-4475-9a2c-96a70c4ff01b.png)
![S7~P$GWS_0M`D46 L(L}YS2](https://user-images.githubusercontent.com/119661718/212807054-a0aa7f0b-e281-4712-9573-e76e26180b52.png)
