### ISSUE TITLE
电视剧类型需要imdbid检索字幕，跳过...，电视剧字幕出这个提示是要维护啥吗？

### ISSUE THREAD

**Issue by Mrxlei** [jxxghp/nas-tools#2926]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.3
>
> 环境: docker  or Synology
>

## 你遇到什么问题了？

> 电视剧类型需要imdbid检索字幕，跳过...，电视剧字幕出这个提示是要维护啥吗？

**Comment by jxxghp** [comment]
TMDB中的信息不完整导致的，需要关联上IMDBID才能精确栓索字幕
