### ISSUE TITLE
大佬们，咱就是说，AV索引器是不是也可以提上日程了【手动狗头】

### ISSUE THREAD

**Issue by youyifentian** [jxxghp/nas-tools#2927]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 未来nt-av-3.0.0
>
> 环境: docker and synology

## 你想要新增或者改进什么功能？

> 咱就是说，现在功能、内容都已经越来越成熟稳定了，也是时候提升丰富一下咱的生理生活需求了噻(狗头)，能不能feature request，全靠兄弟们了

## 这个功能有什么可以参考的资料吗？

> 大家都懂的QAQ

**Comment by Shurelol** [comment]
色情相关内容不考虑

**Comment by xuanqb** [comment]
做梦
