### ISSUE TITLE
订阅未完结的动漫会下载个合集就删除订阅了

### ISSUE THREAD

**Issue by swordzorodai** [jxxghp/nas-tools#293]
例如海贼王，添加后会自动检索下载个合集，然后就把订阅删除了，因为是未完结，也没有总集数。实际上还是每周一更的，大佬看看有办法解决吗
PS:TMDB里海贼王分了21季,
     PT站里海贼王连载命名：[连载][OPFansMaplesnow][海贼王][One Piece][1080p][1021][MKV/TVRip][2022年6月]

**Comment by jxxghp** [comment]
动漫识别是个大工程，目前已有问题：
#179

TMDB中信息不准确的，目前无解。
