### ISSUE TITLE
【刷流任务】空岛的免费过滤都无效

### ISSUE THREAD

**Issue by orzcz** [jxxghp/nas-tools#2935]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5
>
> 环境: docker
>

## 你遇到什么问题了？

> 空岛两个站的免费过滤都无效

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 空岛免费过滤可以正常使用

## 给出程序界面截图、后台运行日志或配置文件

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/26238769/211471216-95bc1546-358d-4cf6-83a9-97151221f80e.png">
<img width="668" alt="image" src="https://user-images.githubusercontent.com/26238769/211471560-93c396ed-2a6f-4ed7-8cc7-77f5023ff07d.png">

**Comment by dlovew** [comment]
今天朋友发了个岛，发现岛刷流免费过滤无效

**Comment by jxxghp** [comment]
暂时都没有测试条件，有账号的可以帮忙分析下

**Comment by orzcz** [comment]
> 暂时都没有测试条件，有账号的可以帮忙分析下

大佬没站吗？

**Comment by jxxghp** [comment]
> > 暂时都没有测试条件，有账号的可以帮忙分析下
> 
> 大佬没站吗？

岛刚有了，测了下，貌似没有问题

**Comment by orzcz** [comment]
> > > 暂时都没有测试条件，有账号的可以帮忙分析下
> > 
> > 
> > 大佬没站吗？
> 
> 岛刚有了，测了下，貌似没有问题

不是最近岛的新种都是免费的？订阅链接出现非免费的种子才能说明问题

**Comment by colchicinewf** [comment]
@jxxghp 瓷器的也是，free过滤失败，下载增加了好多

**Comment by jxxghp** [comment]
> @jxxghp 瓷器的也是，free过滤失败，下载增加了好多

是什么版本，瓷改过了，应该是正常了吧。

**Comment by colchicinewf** [comment]
> > @jxxghp 瓷器的也是，free过滤失败，下载增加了好多
> 
> 是什么版本，瓷改过了，应该是正常了吧。
V2.7.6

**Comment by Wangsc1** [comment]
> @jxxghp 瓷器的也是，free过滤失败，下载增加了好多

瓷器筛选free不怕号没了吗

**Comment by orzcz** [comment]
> > @jxxghp 瓷器的也是，free过滤失败，下载增加了好多
> 
> 瓷器筛选free不怕号没了吗

瓷不给吗？

**Comment by Wangsc1** [comment]
> > > @jxxghp 瓷器的也是，free过滤失败，下载增加了好多
> 
> > 
> 
> > 瓷器筛选free不怕号没了吗
> 
> 
> 
> 瓷不给吗？

规则拉到最底下看看

**Comment by jxxghp** [comment]
> 我看作者改了代码，现在正常了吗？

我跑了几天了，目前没问题

**Comment by orzcz** [comment]
> 我看作者改了代码，现在正常了吗？

目前没问题
