### ISSUE TITLE
经常自动被注销，需要重新登陆

### ISSUE THREAD

**Issue by JasonLeemz** [jxxghp/nas-tools#2936]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> v2.7.5
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 描述一下你遇到的问题
在使用过程中经常无规律的被强制注销，需要重新登陆才能使用。重新拉取docker还是无法解决问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
浏览过，并且上网查询好像没有人遇到过此类问题

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
帮忙排查原因，解决使用体验问题
## 给出程序界面截图、后台运行日志或配置文件
<img width="1118" alt="Xnip2023-01-10_15-27-03" src="https://user-images.githubusercontent.com/4043886/211488184-a5f3fc5e-705b-48b2-a0d6-e896bf88d2fc.png">
上面这张图是我正在检索影片
<img width="776" alt="Xnip2023-01-10_15-28-15" src="https://user-images.githubusercontent.com/4043886/211488322-781035ce-3470-4fe5-8f65-1a181de53093.png">
下面这个请求就直接变成了用户未登录
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
<img width="1821" alt="Xnip2023-01-10_15-31-01" src="https://user-images.githubusercontent.com/4043886/211488927-e773ae58-3fdb-496e-aefc-5f47a772f418.png">
根据shi'jian时间筛选日志应该是上面这条

**Comment by jxxghp** [comment]
从未遇到过，无法分析你的情况
