### ISSUE TITLE
请求添加docker latest-lite 标签

### ISSUE THREAD

**Issue by ccinls** [jxxghp/nas-tools#2939]
RT
目前每次升级还需要修改版本号

**Comment by DDSDerek** [comment]
> RT
> 目前每次升级还需要修改版本号

我提交过pr了，作者回复是 https://github.com/jxxghp/nas-tools/pull/2817#issuecomment-1371700104

**Comment by jxxghp** [comment]
不建议主要使用lite版本，有很多隐藏的问题。
