### ISSUE TITLE
arm64群晖启动报错 python3.8

### ISSUE THREAD

**Issue by tbc0309** [jxxghp/nas-tools#294]
Traceback (most recent call last):
  File "/var/packages/nastool/target/run.py", line 4, in <module>
    import log
  File "/volume1/@appstore/nastool/log.py", line 7, in <module>
    from config import LOG_LEVEL, Config, LOG_QUEUE
  File "/volume1/@appstore/nastool/config.py", line 6, in <module>
    import ruamel.yaml
ModuleNotFoundError: No module named 'ruamel'

**Comment by jxxghp** [comment]
套件启动的时候会先pip安装依赖，进里面用命令运行一下，看是不是安装不成功。

**Comment by tbc0309** [comment]
pip安装依赖，/var/packages/nastool/target# python3 -m pip install -r requirements.txt 报错如下：

Collecting ruamel.yaml.clib>=0.2.6
  Using cached ruamel.yaml.clib-0.2.6.tar.gz (180 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      sys.argv ['/tmp/pip-install-y8_6ej_l/ruamel-yaml-clib_053108702eda4cc7af612fb142ff9cd6/setup.py', 'egg_info', '--egg-base', '/tmp/pip-pip-egg-info-4724l_1x']
      test compiling /tmp/tmp_ruamel_bik59tdw/test_ruamel_yaml.c -> test_ruamel_yaml compile error: /tmp/tmp_ruamel_bik59tdw/test_ruamel_yaml.c
      Exception: command '/usr/local/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu-wrap-gcc' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by jxxghp** [comment]
感觉是这个依赖包不支持

**Comment by gclm** [comment]
同样出现这个问题arm64， 不知道 @jxxghp  有相关解决方案吗？

**Comment by jxxghp** [comment]
> 同样出现这个问题arm64， 不知道 @jxxghp 有相关解决方案吗？

试过Docker吗

**Comment by gclm** [comment]
> > 同样出现这个问题arm64， 不知道 @jxxghp 有相关解决方案吗？
> 
> 试过Docker吗
群辉试过，无法运行，使用端口监听有进程，但是网页一直不加载

**Comment by jxxghp** [comment]
大佬是在帮忙适配dsm7吗？

**Comment by tbc0309** [comment]
> 大佬是在帮忙适配dsm7吗？

修改您的代码，目前已经支持DSM7了。这个我确实不知道怎么同步到GITHUB，您解开spk包查看下增加到代码里面。

https://github.com/tbc0309/nas-tools 里面dsm7是我修改的内容，也上传了spk打包文件（dsm6、7）

arm64我测试了很多遍，ruamel.yaml安装不了，换ruamel.yaml和ruamel.yaml.clib为1.6 老版本最后还是出错，靠大佬您了。

修改的内容主要是：
1、套件使用默认的config.yaml （config.yaml我修改了默认端口和删除了演示的文件夹路径）
2、installer增加了升级套件备份配置，指定了python位置
3、start-stop-status指定了python位置
4、增加了meta.dat空文件，否则启动报错
5、套件的config.yaml默认端口改为3003（ui/config也修改了），否则和其它的套件端口冲突

**Comment by jxxghp** [comment]
> > 大佬是在帮忙适配dsm7吗？
> 
> 修改您的代码，目前已经支持DSM7了。这个我确实不知道怎么同步到GITHUB，您解开spk包查看下增加到代码里面。
> 
> https://github.com/tbc0309/nas-tools 里面dsm7是我修改的内容，也上传了spk打包文件（dsm6、7）
> 
> arm64我测试了很多遍，ruamel.yaml安装不了，换ruamel.yaml和ruamel.yaml.clib为1.6 老版本最后还是出错，靠大佬您了。
> 
> 修改的内容主要是： 1、套件使用默认的config.yaml （config.yaml我修改了默认端口和删除了演示的文件夹路径） 2、installer增加了升级套件备份配置，指定了python位置 3、start-stop-status指定了python位置 4、增加了meta.dat空文件，否则启动报错 5、套件的config.yaml默认端口改为3003（ui/config也修改了），否则和其它的套件端口冲突

感谢大佬，我来合并一下。

**Comment by jxxghp** [comment]
初步整合了下，但我没条件测试（唯一一个DSM还是6.17的python小于3.7用不了），不确定有没有问题

**Comment by tbc0309** [comment]
> 初步整合了下，但我没条件测试（唯一一个DSM还是6.17的python小于3.7用不了），不确定有没有问题

DSM6、7我都测试OK了，x86_64、arm64我都有机器，紧随您的更新我及时来反馈^_^

**Comment by tbc0309** [comment]
version="1.7.1"

这个不可以带v

**Comment by jxxghp** [comment]
> version="1.7.1"
> 
> 这个不可以带v

重新打包好了

**Comment by lightolly** [comment]
装个gcc试试可不可以安装
