### ISSUE TITLE
希望新增手动对刷流任务中希望保留的种子排除自动删除种子的功能

### ISSUE THREAD

**Issue by fuhongzhou** [jxxghp/nas-tools#2944]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望新增手动对刷流任务中希望保留的种子排除自动删除种子的功能

## 这个功能有什么可以参考的资料吗？

> 如刷流任务中迁移到媒体库的操作是关闭的，任务自动下载了某一部电影或电视剧，我希望保留这个种子持续做种，这样我可以修改种子的分类从而触发目录同步硬链接功能，虽然自动删种后媒体文件不会被删除，但无法持续做种。希望可以新增对刷流任务中的种子手动管理删除策略的功能，谢谢！

**Comment by QAQQL** [comment]
有些资源在x2free的时候被刷流下下来,自己想看了
能否出个功能,将其标记一个标签,避免被刷流删除,且能被正确同步到媒体库中
虽然不是个常用功能,但他真的很实用,望作者考虑一下
