### ISSUE TITLE
请求添加媒体库分组，具体应用如下

### ISSUE THREAD

**Issue by youyifentian** [jxxghp/nas-tools#2945]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.6
>
> 环境: docker and synology

## 你想要新增或者改进什么功能？

> 现在的媒体库中虽然电影、电视剧、动漫三种类型都可以添加多个目录，由于不太清楚这里选择每种目录的优先级或者判定具体转移到哪个目录的条件，盲猜就是按顺序来吧，但是在实际应用的时候，情况比较复杂，现在就特别需要能对媒体库进行分组

下面我就说下分组的具体应用，
1、比如多个硬盘的存储的时候，由于不能跨硬盘或分区使用硬链接，就只能复制或者移动，但如果有了分组，这样我就可以每个硬盘都建立一组媒体库，这样①可以使用硬链接，②选择移动的时候速度更快，③目录同步的时候可选同步某个媒体库组，而不是现在一旦手选目录的话就变成电影、电视剧、动漫大杂烩了，这种在下面情况更需要

2、比如我既需要rclone转移到网盘，又想同时用本地存储的时候，由于使用rclone转移或者复制是根据媒体库的配置自动转移的，那媒体库里面配置的就必须是挂载的网盘路径了，当想要用本地存储的时候，只能用目录同步，而目录同步如果不选择保存目录，就整到网盘里面了或者出错，选择保存目录的话就变成1里面所说的大杂烩了，而如果有了媒体库分组的话，就可以网盘分组1，网盘组2，本地组1，本地组2，这样无论是下载监控还是目录同步，都可以根据选择的具体媒体库组来自动识别路径，就非常的奈斯

一点拙见，希望大佬考虑下
感谢

**Comment by jxxghp** [comment]
现在的电影、电视剧、动漫就是媒体库目录分组，可以添加多个目录。目录同步时可以通过指定目的目录精确同步到具体子目录下，也可以不指定由程序选择。程序选择的逻辑是优先使用与源目录有最大相同路径的目录（避免跨盘），否则按顺序使用第一个空间足够的目录，多个盘映射为多个根目录有助于程序正常找到对应同盘的目的目录。

**Comment by youyifentian** [comment]
> 现在的电影、电视剧、动漫就是媒体库目录分组，可以添加多个目录。目录同步时可以通过指定目的目录精确同步到具体子目录下，也可以不指定由程序选择。程序选择的逻辑是优先使用与源目录有最大相同路径的目录（避免跨盘），否则按顺序使用第一个空间足够的目录，多个盘映射为多个根目录有助于程序正常找到对应同盘的目的目录。

但如，使用目录同步的时候，如果源目录里面是混合内容，就是待整理的，里面有电影、电视剧，这个时候如果同时选择了目标目录，那就会把源目录里面所有的都转移到目标目录里面而不会自动电影、电视剧分类了啊
