### ISSUE TITLE
交互的时候回复选择只有6个选择，能否多一点？

### ISSUE THREAD

**Issue by mizb** [jxxghp/nas-tools#2952]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 微信交互的时候，电影匹配返回只有6个，有时候电影名字不在内，能否可选择的数量更多一点，能自定义最好。

**Comment by sungamma** [comment]
的确存在这个问题，例如搜索激战，就是没有张家辉的激战

**Comment by jxxghp** [comment]
太多了微信的发送会收不到消息，我改成10条试试看

**Comment by jxxghp** [comment]
果然：
```
WeChat 发送消息失败：article size out of limit, hint: [1673481571339601919650795], from ip: 125.89.5.70, more info at https://open.work.weixin.qq.com/devtool/query?e=45008
```

**Comment by Shurelol** [comment]
搜不到，加年份

**Comment by mizb** [comment]
其实豆瓣的识别率最高，但是有时候tmd和豆瓣的区别就是有没有年份的问题。之前和作者提过加上或者取消年份来再次查询，辅助增加识别率。。。。被拒绝了，哈哈哈
