### ISSUE TITLE
远程搜索手动选择下载时没有URL

### ISSUE THREAD

**Issue by zhang31791416** [jxxghp/nas-tools#2954]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.7.6
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> 关闭远程搜索自动择优下载后，会收到“XXXX共搜索到到X个资源，点击选择下载”但没有链接。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 手机收到资源链接，手动选择下载

## 给出程序界面截图、后台运行日志或配置文件

> 
![Screenshot_20230111_165419_com tencent mm](https://user-images.githubusercontent.com/16771417/211761750-2d97a5bf-6f7e-4898-a74c-17f6b2325536.jpg)
![CA32437E-9D37-4617-9E3E-CBF7DD2EE3D6](https://user-images.githubusercontent.com/16771417/211761962-45687e16-b2d0-4d87-958d-dbb868672426.png)

> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
外网访问地址，麻烦多看看设置
