### ISSUE TITLE
转移文件夹黑名单 能否改成 或者 增加 含有关键词的文件夹忽略

### ISSUE THREAD

**Issue by SAENE** [jxxghp/nas-tools#2955]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 转移文件夹黑名单 能否改成 或者 增加 含有关键词的文件夹忽略
> 列如文件夹结构是 
>test dir 123
>------test dir
> ----------abc.mkv
>关键词为123时，忽略 test dir 123 这个文件夹下所有媒体文件

**Comment by jxxghp** [comment]
现在的有什么问题？

<img width="900" alt="image" src="https://user-images.githubusercontent.com/51039935/211944948-bd4c91ac-90c1-4ae0-856b-e8eef105a2ac.png">

**Comment by SAENE** [comment]
> 现在的有什么问题？
> 
> <img alt="image" width="900" src="https://user-images.githubusercontent.com/51039935/211944948-bd4c91ac-90c1-4ae0-856b-e8eef105a2ac.png">

[![l2bNw.png](https://i.328888.xyz/2023/01/12/l2bNw.png)](https://imgloc.com/i/l2bNw)

例如第一张图片，在3D彼女里有个EXTRA的文件夹，如果我设置转移文件夹黑名单为EXTRA，在EXTRA下的
[Moozzi2] 3D Kanojo Real Girl [SP00] Menu - xx (BD 1920x1080 x.264 Flac).mkv
就会被忽略，这是正常情况。


但如果例如第二张图，如果我同样设置了设置转移文件夹黑名单为EXTRA的话，那么在EXTRA/OVA目录下的视频就不会被和忽略

[![l2O4z.png](https://i.328888.xyz/2023/01/12/l2O4z.png)](https://imgloc.com/i/l2O4z)
