### ISSUE TITLE
设置转移文件夹黑名单扔转移

### ISSUE THREAD

**Issue by dinsen80951** [jxxghp/nas-tools#2958]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.6
>
> 环境: docker
>

## 你遇到什么问题了？

   设置>基本设置>转移文件夹黑名单已设置为下载目录（盘3，该目录未在目录同步内），但种子下载完成后扔执行转移至盘1下，并在盘1的硬链接目录下建立识别后文件夹，部分还下载影片图片等文件，影片没有转移，再报错。

   服务已开启下载软件监控，目录同步关闭开启同步

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已查看，未解决

## 你期望的结果

> 

## 给出程序界面截图、后台运行日志或配置文件
![1](https://user-images.githubusercontent.com/52577837/211803669-a7540a0b-201d-424d-86cc-63c0933f1879.jpg)
![2](https://user-images.githubusercontent.com/52577837/211806213-b9caf398-83d4-4423-9659-af1e20cc898a.jpg)
![3](https://user-images.githubusercontent.com/52577837/211806945-69827da1-0003-431a-87db-2d31ef7b0a02.jpg)

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/211809762-432b5a66-8caa-4c2a-805c-2383dd574e1d.png)

**Comment by dinsen80951** [comment]
> ![image](https://user-images.githubusercontent.com/16237201/211809762-432b5a66-8caa-4c2a-805c-2383dd574e1d.png)

按照提示和您的样例，设置成上级文件夹名还是转移提示失败，其他设置没变，并且有重启容器，问题依旧。
![1](https://user-images.githubusercontent.com/52577837/211957199-ade2d6e8-d8a9-4c4f-b47f-79abba9a053b.jpg)
![2](https://user-images.githubusercontent.com/52577837/211957220-544827d9-281e-4072-928b-922fd0ddae9b.jpg)
