### ISSUE TITLE
windows v2.7.6无法启动

### ISSUE THREAD

**Issue by zero617** [jxxghp/nas-tools#2959]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: windows
>

## 你遇到什么问题了？

> 无法启动

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已经浏览过Issues、Wiki及TG公众号仍无法解决

## 给出程序界面截图、后台运行日志或配置文件

> ![image](https://user-images.githubusercontent.com/67105838/211830328-b6391e91-cdfa-43b2-8988-02b0a6d72fb8.png)

**Comment by evanxyf** [comment]
+1
换回[v2.7.4](https://github.com/jxxghp/nas-tools/releases/tag/v2.7.4)无问题

**Comment by jxxghp** [comment]
@Shurelol 请求支援，不知道是什么情况了。

**Comment by Shurelol** [comment]
1、使用最新releases中发布的，或者(小秘书频道中的)[https://t.me/nastool_mi/124]
2、如果还是报错，进入user.db，删除alembic_version表后重启

**Comment by Dreamray** [comment]
> 

大佬，db文件推荐用什么打开

**Comment by Dreamray** [comment]
> 1、使用最新releases中发布的，或者(小秘书频道中的)[https://t.me/nastool_mi/124] 2、如果还是报错，进入user.db，删除alembic_version表后重启

大佬，db文件推荐用什么打开

**Comment by AndyWangM** [comment]
自己数据库里加一列就好，缺啥加啥，反正有提示，最近两个版本我都这么干。不清楚类型就直接这个repo里搜，或者直接db_versions下看最新的sql脚本

**Comment by Dreamray** [comment]
> 使用sqllite数据库软件打开user.db->删除alembic_version表->重启（所有数据完整保留）

试了，没用，还是提示这个错误

**Comment by Dreamray** [comment]
2.7.4升2.8.1依然提示这个
