### ISSUE TITLE
豆瓣资源不显示图片

### ISSUE THREAD

**Issue by iizx** [jxxghp/nas-tools#2960]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: Synology docker版
>

## 你遇到什么问题了？

> 推荐里面的豆瓣资源都不显示图片，无论是电影还是电视剧

## 你期望的结果

> 豆瓣资源的图片正常显示

**Comment by jxxghp** [comment]
图片是你的电脑直连显示的

**Comment by iizx** [comment]
啥意思？现在nastools是这样显示的豆瓣资源图片
<img width="702" alt="image" src="https://user-images.githubusercontent.com/20838914/212104712-8da94c93-23f2-470f-86ff-b54543596bd3.png">
