### ISSUE TITLE
进入手动识别页面500

### ISSUE THREAD

**Issue by AndyWangM** [jxxghp/nas-tools#2965]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> 2.7.6
> 环境: docker or windows or Synology
> WIN

## 你遇到什么问题了？

> 描述一下你遇到的问题
看后台的报错信息，应该是表里少了个MODE列，我手动加完后恢复正常

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/22785822/211954907-6b02511a-5d30-4aae-b043-3d78ea1bd932.png)
![image](https://user-images.githubusercontent.com/22785822/211954984-fb96c89a-aab2-45d8-bef0-f5113ab65d6a.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
数据库缺失字段的原因，安装v2.8.1，重启两次。
