### ISSUE TITLE
Slack回调无反应

### ISSUE THREAD

**Issue by Linnnkkk** [jxxghp/nas-tools#2968]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v2.7.6
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> slack设置成功，点击测试也显示成功了，在
实时日志里面也显示连接成功，在slackapp也能收到测试的推送。但是在使用互动功能时，slack没有反应，nastools日志没有任何信息。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

检索过全网信息，无法解决

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 正常使用slack 互动功能

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by YoshiPark** [comment]
我之前也是交互没反应，后来排查一下，发现是环境加了http_proxy和all_proxy，导致docker的网络环境发生变化，不能回传，你可以排查一下你的docker网络环境@Linnnkkk
