### ISSUE TITLE
请求优化“下载软件监控”功能：多下载器监控；使用目录同步规则

### ISSUE THREAD

**Issue by ryanfys** [jxxghp/nas-tools#2969]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: docker

## 你想要新增或者改进什么功能？

>“下载软件监控”功能：多下载器监控；使用目录同步规
 
1、目前“下载软件监控”经过使用发现是监控默认下载器，希望能增加多下载器监控；

 2、我新建了独立的文件夹下载动画剧场版，并在“目录同步”中建立了同步规则（未与其他规则冲突），但发现“下载软件监控”转移下载文件时，并不会使用“目录同步”中的规则，而是直接识别转移到了电影媒体库中，希望“下载软件监控”功能能够使用目录同步中的规则

希望大佬能够考虑！

**Comment by jxxghp** [comment]
目录同步跟下载器监控是相同功能的两种方式，选择一种使用，而不是都开。
