### ISSUE TITLE
jackett索引器搜刮到有效资源,最后却并未下载.

### ISSUE THREAD

**Issue by ztx0079** [jxxghp/nas-tools#297]
18:43:18 INFO - 【PT】动漫 派对浪客诸葛孔明 (2022) 共有 1 季
18:43:18 INFO - 【PT】派对浪客诸葛孔明 (2022) 第1季 缺失集：1、2、4、5、6、7、8、9、10、11、12
18:43:18 INFO - 【SEARCHER】开始检索 パリピ孔明 ...
18:43:18 INFO - 【JACKETT】开始并行检索 パリピ孔明，线程数：4 ...
18:43:18 INFO - 【JACKETT】开始检索Indexer：mikan ...
18:43:18 INFO - 【JACKETT】开始检索Indexer：dmhy ...
18:43:18 INFO - 【JACKETT】开始检索Indexer：chdbits ...
18:43:18 INFO - 【JACKETT】开始检索Indexer：pttime ...
18:43:18 WARN - 【JACKETT】pttime 未检索到资源
18:43:19 WARN - 【JACKETT】mikan 返回数据：28
18:43:19 WARN - 【JACKETT】chdbits 返回数据：11
18:43:19 WARN - 【JACKETT】dmhy 返回数据：25
18:43:19 INFO - 【JACKETT】chdbits 共检索到 0 条有效资源
18:43:19 INFO - 【JACKETT】mikan 共检索到 0 条有效资源
18:43:19 WARN - 【META】/ パリピ、(CV：)、KABE(CV：)、starring Lezel 未找到媒体信息!
18:43:22 WARN - 【META】/ パリピ、(CV：)、KABE(CV：)、starring Lezel 未找到媒体信息!
18:43:22 INFO - 【JACKETT】dmhy 共检索到 0 条有效资源
18:43:22 INFO - 【JACKETT】所有API检索完成，有效资源数：0
18:43:22 INFO - 派对浪客诸葛孔明 未搜索到任何资源

**Comment by jxxghp** [comment]
动漫现在识别率很差，有数据但无有效的一般都是识别不了命名。你用web的快速搜索看是否有结果

**Comment by y2kcan** [comment]
同楼主的问题差不多`我改了二级动漫分类` 1.6.1版本前分类识别正常` 比如动漫间碟过家家前10集正常识别分类` 升级后下载11集TOOL会识别分类为日韩剧` 不知是升级不能用自定义分类还是什么情况` 电影和剧集的二级分类我没改动可正常识别分类` 还有就是订阅设置站点只设置了一个站但不会显示1 要两个才有显示` 刷新订阅后日志显示全部站点都会搜索一次而不是只在我选的站点搜索

**Comment by jxxghp** [comment]
同 #303

**Comment by jxxghp** [comment]
> 同楼主的问题差不多`我改了二级动漫分类` 1.6.1版本前分类识别正常` 比如动漫间碟过家家前10集正常识别分类` 升级后下载11集TOOL会识别分类为日韩剧` 不知是升级不能用自定义分类还是什么情况` 电影和剧集的二级分类我没改动可正常识别分类` 还有就是订阅设置站点只设置了一个站但不会显示1 要两个才有显示` 刷新订阅后日志显示全部站点都会搜索一次而不是只在我选的站点搜索

这个已解决
