### ISSUE TITLE
希望在信息通知增加“版本更新通知”选项！

### ISSUE THREAD

**Issue by 21denli** [jxxghp/nas-tools#2970]
1. 现在大家都比较关心版本升级的情况，希望第一时间可以收到版本更新通知，尝试新功能！
2. 最好附上每次更新的内容。
3.[2023-01-12_17-07-07](https://user-images.githubusercontent.com/120068157/212024673-f4c16bb8-2b30-493d-b8f2-e35ef8dbc12f.jpg)

**Comment by jxxghp** [comment]
关注TG频道吧，通过程序发消息会对大家造成打扰，没有必要。
