### ISSUE TITLE
希望改进刮削时候出现网络问题能再次刮削失败的信息

### ISSUE THREAD

**Issue by DYasher** [jxxghp/nas-tools#2973]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.6
>
> 环境: synology

## 你想要新增或者改进什么功能？

> 改进刮削失败得图片重新进行下载，当图片地址连接失败和发生网络问题时候重新进行识别或再次下载，重复几次。

## 这个功能有什么可以参考的资料吗？

> 
日志：
正在下载disc图片：https://assets.fanart.tv/fanart/movies/238/moviedisc/the-godfather-514d86e38ae59.png...
disc图片下载失败，请检查网络连通性

**Comment by jxxghp** [comment]
感觉换个好点的网络环境更实际，网络不通畅不仅仅是在下图片有问题，识别等都会有问题。
