### ISSUE TITLE
[功能完善] 自定义订阅中`动作`-->`订阅`功能中添加`过滤规则`和`下载器和路径选项`

### ISSUE THREAD

**Issue by boeto** [jxxghp/nas-tools#2974]
## 你使用的 NAStool 是什么版本，什么环境？

NAStool 版本: v2.7.5 6296d9e

环境: docker

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

自定义订阅中`动作`-->`订阅`功能中添加`过滤规则`和`下载器和路径选项`，例如订阅豆瓣top250或者豆瓣豆单至指定非默认下载路径

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

<img width="1439" alt="切片1@2x" src="https://user-images.githubusercontent.com/34640489/212046693-1545679a-9faa-4ee1-a408-3eaf031ed4c8.png">

**Comment by dlovew** [comment]
另外建议是否可以指定订阅站点，字幕组等

**Comment by luoxiao-xy** [comment]
希望针对一键订阅能和搜索，能有配置默认过滤规则的地方。现在只有在过滤规则页面有一个默认，通用于一键订阅和搜索，想要分开设置每次都要单独点击，编辑订阅和高级搜索，很不方便。
