### ISSUE TITLE
Python版无法启动

### ISSUE THREAD

**Issue by wolf-joe** [jxxghp/nas-tools#2976]
## 你使用的 NAStool 是什么版本，什么环境？

拉取仓库后无法运行

## 你遇到什么问题了？

运行`run.py`后报错：
```
 File "/home/worker/git/jxxghp/nas-tools/third_party/feapder/feapder/dedup/litefilter.py", line 21, in LiteFilter
    ) -> Union[list[int], int]:
TypeError: 'type' object is not subscriptable
```
[feapder/dedup/litefilter.py#L21](https://github.com/jxxghp/feapder/blob/44baab7c17afe1e0ab1d5e0dac4fbf2799174724/feapder/dedup/litefilter.py#L21)观察到语法错误

![image](https://user-images.githubusercontent.com/58905296/212085516-9a04c20c-ca6f-4398-b8a8-e2e0c016aa4a.png)

[原仓库](https://github.com/Boris-code/feapder/blob/master/feapder/dedup/litefilter.py#L21)已经修复
![image](https://user-images.githubusercontent.com/58905296/212086268-c9e8223c-31a2-4281-9edb-46bd6a520b1a.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by wolf-joe** [comment]
修复语法错误后就能正常启动了

**Comment by jxxghp** [comment]
这个是第三方包，这段代码我没改他的，我这里没有显示错误：

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/51039935/212232592-d005c5eb-e546-4235-b19f-18e51d14e0c1.png">

**Comment by jxxghp** [comment]
fork库里的源码确实有问题，我同步下：
<img width="783" alt="image" src="https://user-images.githubusercontent.com/51039935/212232822-50fe8648-002e-44cb-843f-ff0819cd4b5c.png">

**Comment by Shurelol** [comment]
Python 本地开发没遇到这个问题

**Comment by jxxghp** [comment]
docker打包进去的也没有问题

**Comment by Shurelol** [comment]
是不是拉的时候更新子模块了？

**Comment by wolf-joe** [comment]
Python版本问题，Python 3.8及以下无法使用list[]作type hint，需要引入typing包。建议拉取最新第三方包代码。
