### ISSUE TITLE
希望增加embyWebhooks通知

### ISSUE THREAD

**Issue by yanglugit** [jxxghp/nas-tools#2977]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2,7,6
>
> 环境: docker 

## 接受embyhook通知,并且推送到微信

> embyWebhooks通知,比如刮削完成

[##](http://k.sina.com.cn/article_1823348853_6cae1875020010zsu.html)

**Comment by yanglugit** [comment]
可以参考这个插件:http://k.sina.com.cn/article_1823348853_6cae1875020010zsu.html

**Comment by yanglugit** [comment]
<img width="746" alt="Snipaste_2023-01-12_22-23-43" src="https://user-images.githubusercontent.com/49310854/212092063-ea335069-4bb4-4755-af7a-1e30d1152cff.png">

**Comment by Shurelol** [comment]
#2249
