### ISSUE TITLE
chanify的通知不显示标题

### ISSUE THREAD

**Issue by ChrisShen-github** [jxxghp/nas-tools#2979]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: Synology docker
>

## 你遇到什么问题了？

> chanify的通知不显示标题，特别是站内信的通知，不知道是哪个站发的

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已浏览过

## 你期望的结果

> 正常显示标题

## 给出程序界面截图、后台运行日志或配置文件

> ![image](https://user-images.githubusercontent.com/37608623/212094154-085ed431-f1c3-4f76-b8be-16062b635c07.jpeg)

**Comment by jxxghp** [comment]
跟客户端的设置有关系？
![image](https://user-images.githubusercontent.com/51039935/212231988-12188411-0270-4031-ab90-c48a6838d7bc.png)

**Comment by ChrisShen-github** [comment]
> 跟客户端的设置有关系？
> 
> ![image](https://user-images.githubusercontent.com/51039935/212231988-12188411-0270-4031-ab90-c48a6838d7bc.png)
> 
> 

客户端我找了好久没找到在哪里设置，然后我用官方文档上的http api发了条消息，发现是可以正常显示标题的![image](https://user-images.githubusercontent.com/37608623/212242238-12338882-27f8-45b1-8037-1b065635baed.png)![image](https://user-images.githubusercontent.com/37608623/212242246-97c1c42c-bc6f-4256-95ac-149dffe6f5a7.png)![image](https://user-images.githubusercontent.com/37608623/212242265-0a84a4a0-c2f2-4a8c-8a8b-b9417f131b19.jpeg)

**Comment by jxxghp** [comment]
无法重现问题，且未有别人反馈
