### ISSUE TITLE
关于文件移动和重命名

### ISSUE THREAD

**Issue by Dantezcx** [jxxghp/nas-tools#2980]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: docker or windows or synology
docker
## 你想要新增或者改进什么功能？
关于文件移动重命名规则
现在会在我的媒体库下面：如电视剧下面新增文件夹，比如欧美剧、日韩剧。虽然会方便管理，但希望能增加关闭这样分类的选项QAQ，因为jellyfin会识别文件夹导致下图的效果
![image](https://user-images.githubusercontent.com/27039451/212208852-7002b88e-08ca-4f34-8e03-c578109902f9.png)

**Comment by wyxls** [comment]
![image](https://user-images.githubusercontent.com/8772976/212209312-a6c7204b-66c9-4486-8c84-f673cc0e5340.png)
你要的应该是这个功能

**Comment by Dantezcx** [comment]
> ![image](https://user-images.githubusercontent.com/8772976/212209312-a6c7204b-66c9-4486-8c84-f673cc0e5340.png)
> 
> 你要的应该是这个功能

我把这个关掉了之后还是会创建二级目录文件夹…所以才来提问，关掉之后需要重启才会生效？

**Comment by wyxls** [comment]
> > ![image](https://user-images.githubusercontent.com/8772976/212209312-a6c7204b-66c9-4486-8c84-f673cc0e5340.png)
> > 你要的应该是这个功能
> 
> 我把这个关掉了之后还是会创建二级目录文件夹…所以才来提问，关掉之后需要重启才会生效？

你看一下旁边问号里的内容，可以自定义设置的

**Comment by Dantezcx** [comment]
已经可以了，我关掉之后重启一下就正常了，估计这个设置要重读配置文件> > > ![image](https://user-images.githubusercontent.com/8772976/212209312-a6c7204b-66c9-4486-8c84-f673cc0e5340.png)
> 
> > > 你要的应该是这个功能
> 
> > 
> 
> > 我把这个关掉了之后还是会创建二级目录文件夹…所以才来提问，关掉之后需要重启才会生效？
> 
> 
> 
> 你看一下旁边问号里的内容，可以自定义设置的
