### ISSUE TITLE
豆瓣想看重复订阅下载

### ISSUE THREAD

**Issue by Tsmbest** [jxxghp/nas-tools#2981]
##  你使用的NAStool是什么版本？什么环境？
NAStool 版本: 2.7.6
环境: docker 
## 你遇到什么问题
豆瓣点击了想看，已经订阅下载过了，还重复订阅下载多次，尝试删除订阅后重启nastool，查看日志再次重新订阅下载
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决
是
## 你期望的结果
希望已经入库的资源，不要重复订阅下载

## 给出程序界面截图、后台运行日志或配置文件
![Screenshot_2023-01-13-07-42-05-25_948cd9899890cbd5c2798760b2b95377.jpg](https://user-images.githubusercontent.com/35428264/212210539-e2bbeaef-21f5-4699-9ab7-24c587d3bd83.jpg)![Screenshot_2023-01-13-07-42-09-31_948cd9899890cbd5c2798760b2b95377.jpg](https://user-images.githubusercontent.com/35428264/212210543-22e0f9d5-1472-473f-a5b4-0034f06d1f51.jpg)![Screenshot_2023-01-13-07-54-21-81_948cd9899890cbd5c2798760b2b95377.jpg](https://user-images.githubusercontent.com/35428264/212210559-9db016f0-d7c9-43cf-941b-7fdba9f00abd.jpg)![Screenshot_2023-01-13-08-07-23-99_df198e732186825c8df26e3c5a10d7cd.jpg](https://user-images.githubusercontent.com/35428264/212210583-9dd9c8af-16dd-4f1d-853e-5175fe9dde59.jpg)![Screenshot_2023-01-13-08-14-37-33_df198e732186825c8df26e3c5a10d7cd.jpg](https://user-images.githubusercontent.com/35428264/212210588-5588a70d-5539-408b-9f75-a2efa42c36e8.jpg)![IMG_20230113_083437.jpg](https://user-images.githubusercontent.com/35428264/212210612-b22fd4f3-32c9-407b-845f-af802f16a651.jpg)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
贴一下豆瓣同步数据下来那一段的日志

**Comment by Tsmbest** [comment]
> 贴一下豆瓣同步数据下来那一段的日志

![image](https://user-images.githubusercontent.com/35428264/212295798-9b827252-57a3-4b47-8975-283c42d32f5a.png)
已有订阅不会重复订阅，但是取消订阅后同步豆瓣就会再次订阅

**Comment by Tsmbest** [comment]
<html>
<body>


18:13:28 | Douban | 豆瓣数据同步完成
-- | -- | --
18:13:52 | Douban | 开始同步豆瓣数据...
18:13:52 | Douban | 开始获取 TSM 的 wish 数据...
18:13:52 | Douban | 随机休眠：2.0 秒
18:13:55 | Douban | 解析到媒体：30314848
18:13:55 | Douban | 解析到媒体：35674355
18:13:55 | Douban | 用户 TSM 解析完成，共获取到 2 个媒体
18:13:55 | Douban | 开始获取 豆友MynnZ4Hxp0 的 wish 数据...
18:13:55 | Douban | 随机休眠：4.6 秒
18:13:59 | Douban | 第 1 页未获取到数据
18:13:59 | Douban | 用户 豆友MynnZ4Hxp0 解析完成，共获取到 0 个媒体
18:13:59 | Douban | 所有用户解析完成，共获取到 2 个媒体
18:13:59 | Douban | 正在通过API查询豆瓣详情：30314848
18:13:59 | Douban | 随机休眠：4.9 秒
18:14:04 | Douban | 查询到数据：瞬息全宇宙
18:14:04 | Douban | 电影：瞬息全宇宙 2022
18:14:08 | Douban | 正在通过API查询豆瓣详情：35674355
18:14:08 | Douban | 随机休眠：2.1 秒
18:14:10 | Douban | 查询到数据：中国奇谭
18:14:10 | Douban | 电视剧：中国奇谭 2023
18:14:13 | Douban | 瞬息全宇宙 2022 更新到电影订阅中...
18:14:13 | Meta | 正在查询TMDB电影：545611 ...
18:14:13 | Meta | 瞬息全宇宙 识别到 电影：TMDBID=545611, 名称=瞬息全宇宙, 上映日期=2022-03-24
18:14:14 | Message | 发送消息 nastools：title=瞬息全宇宙 (2022) 已添加订阅, text=类型：电影，评分：7.6，来自：豆瓣，用户：TSM
18:14:15 | Message | 发送消息 nastools：title=瞬息全宇宙 (2022) 已添加订阅, text=类型：电影，评分：7.6，来自：豆瓣，用户：TSM
18:14:16 | Douban | 中国奇谭 2023 更新到电视剧订阅中...
18:14:16 | Meta | 中国奇谭 识别到 电视剧：TMDBID=139162, 名称=中国奇谭, 首播日期=2023-01-01
18:14:16 | Meta | 正在查询TMDB电视剧：139162 ...
18:14:16 | Meta | 正在查询TMDB电视剧：139162 ...
18:14:16 | Douban | 中国奇谭 添加订阅失败：订阅已存在
18:14:16 | Douban | 豆瓣数据同步完成


</body>
</html>

**Comment by rastyu** [comment]
你可能豆瓣想看没有点掉，所以又同步过来了

**Comment by Tsmbest** [comment]
> 

需要手动取消想看吗？我记得以前点了想看之后就不用管了，已经入库的文件即使点了想看也不会下载的

**Comment by Tsmbest** [comment]
> 你可能豆瓣想看没有点掉，所以又同步过来了

需要手动取消想看吗？我记得以前是不需要取消的，如果已经入库了的文件即使点了想看也不会订阅下载

**Comment by jxxghp** [comment]
知道问题在哪了，没开自动搜索的话会重复添加订阅
