### ISSUE TITLE
是否可以给nastools增加一个主机名设置。

### ISSUE THREAD

**Issue by g46010051** [jxxghp/nas-tools#2982]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or synology

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
是否可以给nastools增加一个主机名设置，docker部署重启后IP就修改了然后日志传到日志中心就会出来好几个nastools的日志
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by ReddotCleaner** [comment]
docker自己就可以设置主机名，Google一下就有
