### ISSUE TITLE
消息通知希望增加对Pushover的支持

### ISSUE THREAD

**Issue by jinaoao** [jxxghp/nas-tools#2983]
## 你使用的 NAStool 是什么版本，什么环境？
> NAStool 版本: 2.7.6
>
> 环境: docker 
## 你想要新增或者改进什么功能？

> 消息通知希望增加Pushover的支持

## 这个功能有什么可以参考的资料吗？

> Pushover官网：https://pushover.net/
> Pushover API：https://pushover.net/api

**Comment by jxxghp** [comment]
没发现这个有什么优势，不能显示标题，且未汉化，还涉及收费？

**Comment by jinaoao** [comment]
> 没发现这个有什么优势，不能显示标题，且未汉化，还涉及收费？

Pushover和nastools中已支持的Pushdeer比较类似，但是Pushover有全平台的客户端包括win，且可以设置消息的优先级，手机端的客户端更完善和稳定。如果开发者不能支持Pushover，希望开发者可以提供一个接口或者以插件的形式让用户自己添加消息推送软件的支持

**Comment by lilarcor** [comment]
pushover可自定义的开关较多，比如客户端分组，分时的免打扰，铃声等。并且全平台打通

**Comment by lilarcor** [comment]
> > 没发现这个有什么优势，不能显示标题，且未汉化，还涉及收费？
> 
> Pushover和nastools中已支持的Pushdeer比较类似，但是Pushover有全平台的客户端包括win，且可以设置消息的优先级，手机端的客户端更完善和稳定。如果开发者不能支持Pushover，希望开发者可以提供一个接口或者以插件的形式让用户自己添加消息推送软件的支持

vi ii

> 没发现这个有什么优势，不能显示标题，且未汉化，还涉及收费？

确实收费，但也确实好用

**Comment by jinaoao** [comment]
> > > 没发现这个有什么优势，不能显示标题，且未汉化，还涉及收费？
> > 
> > 
> > Pushover和nastools中已支持的Pushdeer比较类似，但是Pushover有全平台的客户端包括win，且可以设置消息的优先级，手机端的客户端更完善和稳定。如果开发者不能支持Pushover，希望开发者可以提供一个接口或者以插件的形式让用户自己添加消息推送软件的支持
> 
> vi ii
> 
> > 没发现这个有什么优势，不能显示标题，且未汉化，还涉及收费？
> 
> 确实收费，但也确实好用

开发者已经close了这个issue~~~
