### ISSUE TITLE
static请求地址优化

### ISSUE THREAD

**Issue by Neptep** [jxxghp/nas-tools#2984]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5
>
> 环境: docker 
>

## 你遇到什么问题了？

> nastool本地端口我使用nginx代理到了"https://host:port/nastool"来访问，能够打开页面，但是看了下发起静态资源请求的地址还是https://host:port/static/*******。导致页面显示错乱.

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 希望请求能改成https://host:port/nastool/static/*******。。

## 给出程序界面截图、后台运行日志或配置文件

> 
![image](https://user-images.githubusercontent.com/33046108/212220472-2f2d20f4-1eea-4cab-96ee-c0a91d528f4f.png)

**Comment by jxxghp** [comment]
代码设置问题吧，我也是用Nginx代理，没有问题。

**Comment by Neptep** [comment]
> 代码设置问题吧，我也是用Nginx代理，没有问题。

可以看一下你的这部分nginx配置吗?我搜了几种配置没能成功..

**Comment by TheSeaYouAreAllWater** [comment]
> > 代码设置问题吧，我也是用Nginx代理，没有问题。
> 
> 可以看一下你的这部分nginx配置吗?我搜了几种配置没能成功..

解决了么，我也遇到这种使用nginx二级目录还是没有好的办法解决

**Comment by Neptep** [comment]
> 

没办法，资源放在了根目录，你只能把它每个资源路径都代理上才行，plex也有一样的问题。但是资源路径的名字很常用，考虑了一下还是给了nastool一个单独的端口号。

**Comment by Neptep** [comment]
> > > 代码设置问题吧，我也是用Nginx代理，没有问题。
> > 
> > 
> > 可以看一下你的这部分nginx配置吗?我搜了几种配置没能成功..
> 
> 解决了么，我也遇到这种使用nginx二级目录还是没有好的办法解决

没办法，资源放在了根目录，你只能把它每个资源路径都代理上才行，plex也有一样的问题。但是资源路径的名字很常用，考虑了一下还是给了nastool一个单独的端口号。
