### ISSUE TITLE
电影和电视剧均缺少剧情简介

### ISSUE THREAD

**Issue by rockhia** [jxxghp/nas-tools#2985]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: docker
>

近期下载的电影和电视剧均缺少剧情简介，emby关闭“启用实时监控”，nas-tool已经开启“刮削元数据和图片”等全部内容

**Comment by jxxghp** [comment]
不知道你说啥，提问题前请做些基本的分析
