### ISSUE TITLE
关于tg消息问题

### ISSUE THREAD

**Issue by Dantezcx** [jxxghp/nas-tools#2988]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

>大佬们，你们有没有tg消息交互提醒填的都没问题但是就是测试失败的QAQ，我自己申请的怎么都不行，然后填了朋友的他可以用的进去依旧是测试失败，是不是有啥别的设置呀
![image](https://user-images.githubusercontent.com/27039451/212246709-c6442ed8-95bb-4723-9f1d-6dc7b14df29a.jpeg)

**Comment by Shurelol** [comment]
能先去服务里测下网络？

**Comment by Dantezcx** [comment]
> 能先去服务里测下网络？

![image](https://user-images.githubusercontent.com/27039451/212249439-686112f6-de1d-498c-b4a7-96ba87fe3fdc.png)

**Comment by Shurelol** [comment]
发日志

**Comment by Dantezcx** [comment]
> 发日志

docker里面的日志么？

**Comment by Dantezcx** [comment]
> 发日志

14:14:52	Message	telegram 发送测试消息失败：未获取到返回信息

**Comment by Dantezcx** [comment]
可以了，和我同样问题的注意一下：创建好的bot机器人要点进去点一下开始
