### ISSUE TITLE
docker容器内无法访问api.github.com 以及 tmdbapi

### ISSUE THREAD

**Issue by ltsj** [jxxghp/nas-tools#299]
19:58:25 - 开始启动进程...
19:58:25 INFO - 【RUN】PT站自动签到服务启动...
19:58:25 INFO - 【RUN】PT下载文件转移服务启动...
19:58:25 INFO - 【RUN】豆瓣同步服务启动...20:00:23 - HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/jxxghp/nas-tools/releases/latest (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f417fa5c400>, 'Connection to api.github.com timed out. (connect timeout=10)'))

境外服务器 容器外可以直接访问api.github.com 以及 tmdbapi ，容器内无法访问 如上   但是可以用IP连接上emby 域名没试过

**Comment by Hosiang1026** [comment]
docker启动命令-添加host链接，就解决了
