### ISSUE TITLE
手动识别 -改进

### ISSUE THREAD

**Issue by Michae1G** [jxxghp/nas-tools#2991]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.7.6
> 环境: docker or windows or synology
docker
## 你想要新增或者改进什么功能？

> 首先非常感谢 ，nastool 是个很好的软件
改进：
 媒体未能识别、刮削时，nastool会将媒体文件转入到设置的未识别文件夹，同时在手动识别里显示，但是此时在 该媒体后面 的菜单里 进行手动识别识时，手动识别弹窗上自动填写的路径为 未转移到未识别文件夹 之前的路径，且该条目 无法手动修改，是否可以 将此处的  自动路径 修改为 未识别后转移到未识别文件夹后的路径，这样，只需要查询下TMDB ID 即可 重新手动查询。

目前只能从 右上角的自定义识别 里 重新填写路径 和 TMDB ID   才能识别，但 如果 未识别路径下有多个媒体，就容易出现问题，望能改进。

再次感谢。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Shurelol** [comment]
不设未识别目录即可，这个不是必须的
