### ISSUE TITLE
RARBG站点无法搜索到x265（HEVC）的资源

### ISSUE THREAD

**Issue by kofzhanganguo** [jxxghp/nas-tools#2992]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.6
>
> 环境: docker or windows or Synology
>Windows

## 你遇到什么问题了？

> 描述一下你遇到的问题

搜索RARBG里面的片源，为何搜索不到x265的片源，全部都是264的，难道需要什么设置吗？
![image](https://user-images.githubusercontent.com/32073931/212418883-2ef63f4e-aebf-4467-9397-ad73bb1f9a62.png)
![image](https://user-images.githubusercontent.com/32073931/212418970-c75d8bc5-9be8-4ea2-ba3c-c0c4bc4cee18.png)
![image](https://user-images.githubusercontent.com/32073931/212419008-ee94c478-6861-4629-9d7f-c0d6bf06b7c6.png)
过滤规则我选择的是不过滤任何，但是只有RARBG的网站，搜索不到x265的片源，其他的网站可以搜索到。
![image](https://user-images.githubusercontent.com/32073931/212419545-79d31b2e-043d-42d1-a7e4-d24b34af27bb.png)
比如这个站点，可以搜索到HEVC和265的，唯独RARBG不能，想请教一下如何才可以搜索到。

**Comment by serenity666** [comment]
站点设置里看看
