### ISSUE TITLE
网页端隔段时间打不开

### ISSUE THREAD

**Issue by lostiv** [jxxghp/nas-tools#2995]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: unraid docker
>

## 你遇到什么问题了？

> 一段时间后网页端打不开（内外网都是），但从docker日志RSS订阅等服务还是有在运行的。重启后正常，但不知道多久后网页端又会打不开。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已浏览

## 你期望的结果

> 稳定运行

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
docker日志只有rss之类的信息
![微信截图_20230114102135](https://user-images.githubusercontent.com/30612717/212446861-72cb1130-74f6-44e3-83c3-b0304a89095f.png)

[nastool.txt](https://github.com/jxxghp/nas-tools/files/10416391/nastool.txt)

**Comment by jxxghp** [comment]
用了内置的SSL证书功能吗？

**Comment by lostiv** [comment]
> 用了内置的SSL证书功能吗？

应该是吧，用的是证书的文件和密钥放在config文件路径里面。

**Comment by jxxghp** [comment]
改成用外层代理
