### ISSUE TITLE
更新之后无法完成下载

### ISSUE THREAD

**Issue by evanjiang404** [jxxghp/nas-tools#2999]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.6.7
>
> 环境: docker 
>

## 你遇到什么问题了？

> 无法连接qbittorrent 进行下载，提示下载任务已存在

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 正常下载
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
![image](https://user-images.githubusercontent.com/75173561/212480993-a4a09596-0a3c-4ced-af13-8016d4bb7488.png)

**Comment by GuoliangLai** [comment]
一样的问题，而且有些种子还提示：下载种子出错，状态码：404。
环境是：群晖系统，docker版nastools，套件版qbit4.5，nastool映射了磁盘路径。

**Comment by jxxghp** [comment]
先排除：
1、下载器能测试通过。
2、站点Cookie和UA均已设置且未失效。
3、站点手动下载过种子，不会弹出首次下载的页面提示。
如果还不能解决，有时候跟下载器的网络连接莫名原因不正常，一般重启下Docker或者NAS就会恢复。

**Comment by GuoliangLai** [comment]
> 

谢谢及时回复解决，由于对nastools不够熟悉，导致一直不知道在哪查看详细的日志情况使得没有办法快速排除问题，根据@jxxghp 所提供的方法，目前已找到原因，如下：
1.环境为nastools的docker版，同时索引器使用jackett，配置好了jackett环境，出现的问题在于从nastool搜索资源并发送到qbit下载提示下载种子出错，状态码：404。
2.一开始以为是nastools没有正确配置下载器导致无法控制下载，于是手动去网页下载种子并利用nastools指定qbit下载，发现没有问题。
3.通过2排除下载器的问题，于是去jackett手动搜索种子（可获得结果，说明cookie配置没问题）并下载，找到问题：**所下载资源的网站拒绝访问，无法下载种子** 。
所以其实是个很简单的问题，有些网站是不能用jackett下载种子的，但是能检索种子并显示，因此大家要是也出现这个问题，可以排查一下是否站点问题或jackett的问题。非常感谢@jxxghp 解答。
