### ISSUE TITLE
更新后tmdb无法正常访问，订阅管理中订阅的电影无法点开

### ISSUE THREAD

**Issue by dxbzth** [jxxghp/nas-tools#301]
api.themoviedb.org 连接正常，电脑手机都正常连接访问，但tools就是报错。
![image](https://user-images.githubusercontent.com/107115993/174085779-e641c97b-af1c-49b8-9420-085226dfded9.png)
![image](https://user-images.githubusercontent.com/107115993/174085809-245174c2-a7dc-44fa-9c17-e8e811f4d1e0.png)

**Comment by jxxghp** [comment]
这就是网络连不上啊，跟更新没关系

**Comment by nemonlee** [comment]
我这几天也是这个问题，一直连不上

**Comment by pantou1991** [comment]
我也是这个问题，无法打开订阅中的电影

**Comment by nemonlee** [comment]
> 我也是这个问题，无法打开订阅中的电影

我好了，如果你连tmdb没问题的话可以试试网络勾docker host
