### ISSUE TITLE
可以自定义剧名么? 

### ISSUE THREAD

**Issue by w3eee** [jxxghp/nas-tools#3010]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or synology

## 你想要新增或者改进什么功能？

自定义剧名. 就是定义搜索时候的别名. 很多剧在不同的资源站的命名不统一, 所以如果可以定义多个别名来搜索. 
可以大大提高搜索结果的数量. 

## 这个功能有什么可以参考的资料吗？
其实就是个别名的功能. 

例子: 
比如搜索 "关于邻家的天使大人不知不觉把我惯成了废人这件事", 在动漫花园是搜索不到东西, 因为一些字幕组的命名是 "关于邻家的天使大人不知不觉把我惯成了废人这档子事"
.... 导致的结果就是搜刮下来的资源都是没有字幕的. 就很烦. 

感谢

**Comment by Shurelol** [comment]
高级搜索
自定义订阅

**Comment by w3eee** [comment]
> 高级搜索 自定义订阅

谢谢 这样确实可以. 

顺便提个bug吧. 自定义订阅那里 已处理数量永远显示0 点进去是有记录的

**Comment by Shurelol** [comment]
在修复了，谢谢
