### ISSUE TITLE
签到失败的情况下,提供再次签到功能

### ISSUE THREAD

**Issue by qqqaaassshu** [jxxghp/nas-tools#3014]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: docker
## 你想要新增或者改进什么功能？

> 能够在签到失败的情况下,提供再次签到功能,失败尝试次数可以进行设置

## 这个功能有什么可以参考的资料吗？

> 没有可参考资料,该功能仅给大佬参考,对作者说一声 维护功能辛苦了

**Comment by shan-guo** [comment]
我也有类似的需求，否把自动签到改为配置项，自动签到时间，重试次数，一些小pt站有时候不太稳定，容易失败

**Comment by qqqaaassshu** [comment]
您的邮件我已收到

**Comment by Shurelol** [comment]
签到可以配置时间建个，可惜一天签多次
