### ISSUE TITLE
已入库的电视剧重复下载

### ISSUE THREAD

**Issue by youyifentian** [jxxghp/nas-tools#3023]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.6
>
> 环境: docker on Synology
>

## 你遇到什么问题了？

>我vx第一次搜索 一人之下第五季  可以正常下载，正常入库，然后在搜索 一人之下第五季  前面已经入库的几集并没有识别，直接又按整季缺失从头下载，反复试都是这样，但是别的同样是电视剧，比如三体，无限世界就都是正常的，可以识别已入库的，只下载缺失的，就这部不正常，是触发了什么隐藏bug么

## 给出程序界面截图、后台运行日志或配置文件

![4](https://user-images.githubusercontent.com/5012570/212714914-92956b34-c1b5-4bb3-9d40-383bebf82625.jpg)
![2](https://user-images.githubusercontent.com/5012570/212715694-87bf90ac-1d10-4add-bfb7-5e256c5f236d.jpg)
![3](https://user-images.githubusercontent.com/5012570/212715079-9d203077-9831-45f0-850f-5c5712339d14.jpg)
![1](https://user-images.githubusercontent.com/5012570/212715117-a4105f41-f73e-4804-b7cd-22a6e9d14cb5.jpg)

**Comment by Shurelol** [comment]
发出入库信息时，识别转移重命名完成，并通知emby扫描

Emby需要时间

**Comment by youyifentian** [comment]
> 关了远程自动下载，直接搜一人之下看看会不会报第五季全缺失

测试了，结果是一样的，而且现在已经距离之前入库过了很久了
![5](https://user-images.githubusercontent.com/5012570/212730910-ed992ae6-f1e7-4431-ae38-b454171d0b70.jpg)
![6](https://user-images.githubusercontent.com/5012570/212730926-77547a75-7857-412f-9b4b-23d0ac5f6796.jpg)

**Comment by Shurelol** [comment]
我说发 一人之下，不是一人之下第五季
另外去emby看下一人之下第五季的元数据打开里面有没有tmdbid

**Comment by jxxghp** [comment]
可以复现问题，已经修了
