### ISSUE TITLE
nastool打开一直循环这几句，按照教程用Sqlite的浏览器打开config下user.db删除alembic_version表后重启，无效

### ISSUE THREAD

**Issue by wang923345843** [jxxghp/nas-tools#3028]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.7.6
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

>nastool打开一直循环这几句，按照教程用Sqlite的浏览器打开config下user.db删除alembic_version表后重启，无效

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> nastool小红书删除那个表，无效，没用

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/100781270/212894213-6ec65b0b-bca4-4259-9775-e342121a3e59.png)

![image](https://user-images.githubusercontent.com/100781270/212894232-af8f25ee-f42c-4df9-a628-cf0ac0e0ef0e.png)

**Comment by Shurelol** [comment]
进数据库看看rss_movies和rss_tvs这两个表有download_setting这个字段么
