### ISSUE TITLE
种子文件名中的特殊字符似乎没有成功摘除

### ISSUE THREAD

**Issue by log-time** [jxxghp/nas-tools#303]
![IMG_20220616_234750](https://user-images.githubusercontent.com/66826612/174112355-3021465c-97e0-4151-a7dd-7bae1149e6bf.jpg)

**Comment by jxxghp** [comment]
原种子名贴来看看，看是什么神奇的命名

**Comment by log-time** [comment]
我找一下当时的日志，主要现在日志显示不完整，我试试看通过日志时间和站点信息能不能找到

**Comment by log-time** [comment]
[西葫芦的生活][My Life as a Zucchini][Ma vie de courgette][2016][WEB-DL][1080][Movies][LeagueWEB]
西葫芦的生活/翠玉瓜的岁月(港)/酷瓜人生(台)/My Life as a Courgette | 类型:剧情/动画/儿童 主演:加斯帕德·施拉特/西斯汀·穆拉特/波林·雅库 [法语中字]

**Comment by jxxghp** [comment]
这个命名也是神了，按命名规则这个被判定了日漫格式了，动漫现在用的是别人的开源模块，我改不了。非动漫应该没个这问题。

**Comment by log-time** [comment]
◎名　　字　My Life as a Zucchini
◎译　　名　西葫芦的生活
◎别　　名　翠玉瓜的岁月(港)/酷瓜人生(台)/My Life as a Courgette/My Life As A Zucchini
◎年　　份　2016
◎产　　地　瑞士 / 法国
◎类　　别　剧情/动画/儿童
◎语　　言　法语
◎上　　映　2016-05-15(戛纳电影节)/2016-09-22(瑞士)/2016-10-19(法国)
◎豆瓣评分　8.5/10 (27601)
◎豆瓣链接　https://movie.douban.com/subject/24860289/
◎IMDB评分  7.7/10 (24943)
◎IMDB链接  https://www.imdb.com/title/tt2321405/
◎片　　长　66分钟
◎导　　演　克洛德·巴拉斯
◎编　　剧　吉勒斯·帕瑞斯/瑟琳·席安玛/杰马诺·祖罗/克洛德·巴拉斯/莫根·纳瓦罗


是柠檬官种，能兼容吗？

**Comment by log-time** [comment]
我把他家动画分区的rss订阅先去掉

**Comment by jxxghp** [comment]
你上面贴这些有的是可以的，要试下才知道。那个模块的问题是如果前面加了太多信息他就处理不了。
后面有时间自己重新写动漫的识别模块。

**Comment by jxxghp** [comment]
0dd64c33fbfceb105c97c3a7f83dc21917b32614
这个提交大幅优化了动漫的识别，如仍有问题请在汇总Issues中提交。
