### ISSUE TITLE
115 cookies 下载失败

### ISSUE THREAD

**Issue by three1bro** [jxxghp/nas-tools#3035]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.6
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

>  115作为下载器下载失败，不确定是cookies的格式导致的还是其他的bug ， 当前的格式是

`USERSESSIONID=*******************; 115_lang=zh; PHPSESSID=******; HWWAFSESID=*****; HWWAFSESTIME=1669114970155; ACT_221101_COO_SOURCE=3; UID=****; CID=***; SEID=******; BENSESSCC_TAG=********`
 

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

>  可以使用115下载

## 给出程序界面截图、后台运行日志或配置文件
![Quicker_20230117_225820](https://user-images.githubusercontent.com/31007402/212933285-60c922ca-0c39-475f-b306-513158a6687d.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by wcyws** [comment]
我也有此问题，另外想问问使用115下载器下载，文件好像不会自动取回本地？只是在115上建立了链接？我的理解对吗

**Comment by owenxuan** [comment]
之前遇到过 找没有HWWAFSESTIME时间戳的cookie 就可以了

**Comment by owenxuan** [comment]
之前遇到过 
找USERSESSIONID=***; 115_lang=zh; UID=***; CID=***2; SEID=***的cookie就可以了

**Comment by wcyws** [comment]
> 之前遇到过 找USERSESSIONID=******; 115_lang=zh; UID=******; CID=******; SEID=******的cookie就可以了

这个错误在我重启docker之后得到了解决，请允许我问一些额外的问题，我还是很疑惑115下载器默认是无法download到本地的对吗，那么下载设置中的下载保存目录，与访问目录分别是干什么用的呢

**Comment by three1bro** [comment]
> 之前遇到过 找USERSESSIONID=******; 115_lang=zh; UID=******; CID=******; SEID=******的cookie就可以了

#https://github.com/jxxghp/nas-tools/issues/1098#issue-1369634123

我这边也解决了这个问题， 看之前的 issue   发现有讲测试是失败的，但是可以添加下载，我这边也是一样的情况。

但是用115添加下载后点击正在下载出不来了，不知道是不是bug， 也没有相关的issue

**Comment by three1bro** [comment]
> > 之前遇到过 找USERSESSIONID=******; 115_lang=zh; UID=******; CID=******; SEID=******的cookie就可以了
> 
> 这个错误在我重启docker之后得到了解决，请允许我问一些额外的问题，我还是很疑惑115下载器默认是无法download到本地的对吗，那么下载设置中的下载保存目录，与访问目录分别是干什么用的呢

我这边和你到同一个进度了，也在已婚下载任务添加后的步骤，是否会取回本地。

**Comment by wangsq5026** [comment]
> > 之前遇到过 找USERSESSIONID=******; 115_lang=zh; UID=******; CID=******; SEID=******的cookie就可以了
> 
> #[#1098 (comment)](https://github.com/jxxghp/nas-tools/issues/1098#issue-1369634123)
> 
> 我这边也解决了这个问题， 看之前的 issue 发现有讲测试是失败的，但是可以添加下载，我这边也是一样的情况。
> 
> 但是用115添加下载后点击正在下载出不来了，不知道是不是bug， 也没有相关的issue

现在可以下载到115网盘里面,但是在115网盘根目录,还不能自动取回到本地,到底怎么设置才对

**Comment by wangsq5026** [comment]
> > 之前遇到过 找USERSESSIONID=******; 115_lang=zh; UID=******; CID=******; SEID=******的cookie就可以了
> 
> #[#1098 (comment)](https://github.com/jxxghp/nas-tools/issues/1098#issue-1369634123)
> 
> 我这边也解决了这个问题， 看之前的 issue 发现有讲测试是失败的，但是可以添加下载，我这边也是一样的情况。
> 
> 但是用115添加下载后点击正在下载出不来了，不知道是不是bug， 也没有相关的issue

现在可以下载到115网盘里面,但是在115网盘根目录,还不能自动取回到本地,到底怎么设置才对

**Comment by wangsq5026** [comment]
> > 之前遇到过 找USERSESSIONID=******; 115_lang=zh; UID=******; CID=******; SEID=******的cookie就可以了
> 
> 这个错误在我重启docker之后得到了解决，请允许我问一些额外的问题，我还是很疑惑115下载器默认是无法download到本地的对吗，那么下载设置中的下载保存目录，与访问目录分别是干什么用的呢

下载到本地的问题解决了吗,怎么弄呀,现在就是能到115网盘根目录,不能取回到本地,如何设置才能到115网盘的指定目录和取回本地
