### ISSUE TITLE
直接传递下载链接到下载器

### ISSUE THREAD

**Issue by leihao** [jxxghp/nas-tools#3037]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: docker

## 你想要新增或者改进什么功能？

> Ani.rip的订阅链接如下 https://api.ani.rip/ani-download.xml 解析格式也非常简单,但是由于nastool代下种子的功能设计,导致下载链接无法直接传递给aria2,希望增加直接传递下载链接到下载器的功能

## 这个功能有什么可以参考的资料吗？

> 忘了是哪个版本开始的了,nastool代下种子文件再传递给下载器,导致这类直连链接无法传递给下载器,我的想法是增加选项开关,或者再解析器里增加字段,该字段的连接替代enclosure,作为直连链接传递给下载器

**Comment by Shurelol** [comment]
Ani在dmhy，nyaa，蜜柑都有发布，建议用这些站点的rss

**Comment by Shurelol** [comment]
另外这个需要自己写rss解析器

**Comment by leihao** [comment]
> Ani在dmhy，nyaa，蜜柑都有发布，建议用这些站点的rss

HTTP直连,会比BT快很多,特别是种子刚发布的时候
嘛,扩展咦下可能性而已,解析器也很简单,不是很紧急的功能
{
  "list": "//channel/item",
  "item": {
    "title": {
      "path": ".//title/text()"
    },
    "enclosure": {
      "path": ".//link/text()"
    }
  }
}

**Comment by leihao** [comment]
> Ani在dmhy，nyaa，蜜柑都有发布，建议用这些站点的rss

所以功能的另一个提案就是增加解析器的新字段,该字段链接直接推送给下载器,不走种子下载流程,类似把磁力链接交给下载器
