### ISSUE TITLE
aria2连接错误

### ISSUE THREAD

**Issue by icezxf** [jxxghp/nas-tools#3038]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: docker or windows or Synology
>istore os（openwrt）

## 你遇到什么问题了？
aria2连接不上
> 描述一下你遇到的问题
aria2正常使用，但是nastool测试连接不同 下载显示rpc 404 notfound
nastools和aria2都是在openwrt里安装的 aria2是istore直接安装的 nastool在docker里

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

没有看到问题解决
## 你期望的结果

aria2能连通

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![wx_camera_1673877225050](https://user-images.githubusercontent.com/122969420/213125487-2cabd895-a7b0-4c40-86e7-b3c9d38fc937.jpg)
![wx_camera_1673874132020](https://user-images.githubusercontent.com/122969420/213125500-9bc9c1e2-e68e-404c-8461-7c882da92221.jpg)
![wx_camera_1673874047229](https://user-images.githubusercontent.com/122969420/213125505-a1d85dd9-2baa-42a5-ba0d-b38e8fd4857b.jpg)
![wx_camera_1673874022976](https://user-images.githubusercontent.com/122969420/213125509-f59a0f4d-36e0-46a2-9d79-cd451d5ec452.jpg)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by icezxf** [comment]
ip地址改成192.168.3.3也没用

**Comment by DDSDerek** [comment]
nastools用host网络

**Comment by icezxf** [comment]
> nastools用host网络

具体该怎么操作呢

**Comment by DDSDerek** [comment]
> > nastools用host网络
> 
> 具体该怎么操作呢

![image](https://user-images.githubusercontent.com/108336573/213161987-1d046a33-60eb-41ec-939c-1e91e5fee6ac.png)
这里设置

**Comment by icezxf** [comment]
> > > nastools用host网络
> > 
> > 
> > 具体该怎么操作呢
> 
> ![image](https://user-images.githubusercontent.com/108336573/213161987-1d046a33-60eb-41ec-939c-1e91e5fee6ac.png) 这里设置

我这里设置不了怎么办
![image](https://user-images.githubusercontent.com/122969420/213189889-bc67ff5c-8b7b-41be-b31b-a52ddc3f51f8.png)


> > > nastools用host网络
> > 
> > 
> > 具体该怎么操作呢
> 
> ![image](https://user-images.githubusercontent.com/108336573/213161987-1d046a33-60eb-41ec-939c-1e91e5fee6ac.png) 这里设置

**Comment by icezxf** [comment]
> > > nastools用host网络
> > 
> > 
> > 具体该怎么操作呢
> 
> ![image](https://user-images.githubusercontent.com/108336573/213161987-1d046a33-60eb-41ec-939c-1e91e5fee6ac.png) 这里设置

我这里设置不了怎么办
![image](https://user-images.githubusercontent.com/122969420/213190088-71e0cd00-bd15-452d-86bc-6923f1d9d7d8.png)

**Comment by qq2320725215** [comment]
你部署的 aria2 服务器估计是阉割版本 （有可能是 openwrt 内的 aria2 app ， 阉割了 xmlrpc 的功能）
没有 xmlrpc 的远程调用

你可以试试 

```
docker run --name aria2   --hostname aria2  --net=host --rm -e RPC_SECRET=prc_password -e RPC_PORT=6800 -e LISTEN_PORT=6888 p3terx/aria2-pro 
```

部署完整功能的 aria2-pro ，然后再测试

**Comment by zuston** [comment]
```
docker run -d \
    --name nas-tools \
   --net host \
    --hostname nas-tools \
    -v /root/config:/config  `# 冒号左边请修改为你想在主机上保存配置文件的路径` \
    -v /mnt/sda1/nastool:/nastool    `# 媒体目录，多个目录需要分别映射进来` \
    -e PUID=0     `# 想切换为哪个用户来运行程序，该用户的uid，详见下方说明` \
    -e PGID=0     `# 想切换为哪个用户来运行程序，该用户的gid，详见下方说明` \
    -e UMASK=000  `# 掩码权限，默认000，可以考虑设置为022` \
    -e NASTOOL_AUTO_UPDATE=false `# 如需在启动容器时自动升级程程序请设置为true` \
    -e NASTOOL_CN_UPDATE=false `# 如果开启了容器启动自动升级程序，并且网络不太友好时，可以设置为true，会使用国内源进行软件更新` \
    jxxghp/nas-tools
```

端口全部放通，aria2 同连接不上，使用的是 openwrt 的软路由。正在尝试 aria2-pro

**Comment by zuston** [comment]
@qq2320725215 使用 aria2-pro 已经测试连接成功，感谢
