### ISSUE TITLE
想问一下搜索那里的过滤规则具体是什么

### ISSUE THREAD

**Issue by orzcz** [jxxghp/nas-tools#3039]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: docker
>

## 你遇到什么问题了？

> 我在搜索规则中增加了过滤DV（杜比视界）的规则，并且在站点维护中都应用了该规则。但是我在聚合搜索资源的时候，发现DV资源还是存在。聚合搜索的过滤规则是否有实现？

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 期望搜索结果应该被过滤一部分，在站点较多的时候（我是10~15个站点），找资源挺头疼的

<img width="111" alt="image" src="https://user-images.githubusercontent.com/26238769/213129791-641f6fb4-c69f-452c-9edc-a84efb5b1430.png">
<img width="428" alt="image" src="https://user-images.githubusercontent.com/26238769/213129864-0caccf2a-bfe3-4410-ac66-e2e7451d5a30.png">

**Comment by jxxghp** [comment]
#3065
