### ISSUE TITLE
自定义识别词无法替换，请指教

### ISSUE THREAD

**Issue by kofzhanganguo** [jxxghp/nas-tools#3055]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.6
>
> 环境: docker or windows or Synology
>Windows

## 你遇到什么问题了？

> 描述一下你遇到的问题

关于自定义自定义识别词问题
![image](https://user-images.githubusercontent.com/32073931/213388225-5b895dc1-21b6-4278-a5d3-040561bab26e.png)
![image](https://user-images.githubusercontent.com/32073931/213388412-c91c9a10-acc2-4669-a9f4-0eed754d26ef.png)

这个为啥没办法替换识别词啊

![image](https://user-images.githubusercontent.com/32073931/213388539-6a2649de-8189-422f-b9bc-2cbc288c244a.png)

这种名称发布的磁力，都无法自定义识别词

[国漫]防御全开第10集无水印高清下载

[[国漫]吞噬星空第71集无水印高清下载

这种名称的话，都无法替换识别词，请教一下如何设置这个参数。

**Comment by jxxghp** [comment]
用自定义订阅不开识别。
用文件名来写自定议识别词，而不是标题
