### ISSUE TITLE
手机UI资源列表没有种子详情按钮

### ISSUE THREAD

**Issue by git-0101** [jxxghp/nas-tools#3057]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: docker
>

## 你遇到什么问题了？

> 发现桌面版UI有下载按钮和查看种子详情选项，手机UI没有。不知道是否是bug，还是位置不够造成的。感觉挺有用的。如果是位置不够，现在是点击主标题下载，感觉可以改成跳转详情页，然后右下角增加一个下载按钮。如果想下载种子，就先进详情页，再在详情页里下载种子，这样就节约了一个图标位置。不知是否可行。
![Screenshot_20230119_010705](https://user-images.githubusercontent.com/115487446/213412219-d5ed8e47-2fed-4eea-aea8-b2e3646740a0.jpg)
![Screenshot_20230119_010817](https://user-images.githubusercontent.com/115487446/213412241-c27111b4-8850-48b5-aaad-5aa20259ea2d.jpg)

**Comment by Wangsc1** [comment]
横屏就有了

**Comment by git-0101** [comment]
> 横屏就有了

对，切换桌面模式就有了，但是在手机布局上字体又超级小了，不方面操作了。如果建立桌面快捷方式，基本就是个app了，不能临时改成桌面模式。现在的界面超级好看了，如果实现不了，就这样也可以了。改动不能破坏美观，嘿嘿。

**Comment by jxxghp** [comment]
确实没地方放了

**Comment by git-0101** [comment]
> 确实没地方放了

好滴。作者大大过年好！

**Comment by git-0101** [comment]
> 确实没地方放了

好滴。作者大大过年好！
