### ISSUE TITLE
1.6.1版本的文件转移时不能添加季节数字

### ISSUE THREAD

**Issue by dlovew** [jxxghp/nas-tools#306]
1.6.0版本之后才有的bug，硬链接完成转移文件时，目的路径不能正确添加季的序号
如本来应该时
\Media\Hlink\Drama\花朝秋月夜 (2022)\Season 1
实际却是
\Media\Hlink\Drama\花朝秋月夜 (2022)\Season
这会导致emby错误刮削，一般的是错误刮削到season季而不是第一季
个别会错误识别成别的电视剧
我碰到的酒是故乡醇这部剧，被错误识别成一部美剧，将season手动改为season1，刷新一下媒体库就能正确识别了

**Comment by jxxghp** [comment]
最新代码已修复
