### ISSUE TITLE
微信搜索问题1.6.1

### ISSUE THREAD

**Issue by leo8912** [jxxghp/nas-tools#307]
微信搜索发送简体字，日志显示搜索时关键词变成繁体字导致搜不到资源。
Web端搜索就正常了
![mmexport1655440613296.png](https://user-images.githubusercontent.com/22719866/174225850-abe8720b-5791-45c0-a0f8-5887e6ffbf6c.png)
![mmexport1655440615125.jpg](https://user-images.githubusercontent.com/22719866/174225867-1ae3fd83-01cd-428d-aa49-a4e6f8f9e967.jpg)

**Comment by jxxghp** [comment]
调整了下，只有原语种是英文时才用原标题去搜索。试了下这个可以了。
