### ISSUE TITLE
订阅管理-自定义订阅中“已处理数量”问题

### ISSUE THREAD

**Issue by xnoods** [jxxghp/nas-tools#3076]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.0
>
> 环境: Synology下的docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

订阅管理-自定义订阅-新建订阅任务后发现其中的包含和排除2个框中如果不填入规则，只是在最右侧的过滤规则中选取一个自己设定好的规则的话，那么订阅成功并下载后，页面中的已处理数量会变成0，不会实时增加（但是点击这个已处理会发现确实已经处理好了12个并成功下载，只是数值没更新），猜测是逻辑bug，希望修复

同步我测试了，只在新建订阅任务中的包含和排除2个框中填入对应规则后，那么订阅成功并下载后，页面中的已处理数量会实时增加，不存在上述问题～

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![telegram-cloud-photo-size-5-6221783732470265113-y](https://user-images.githubusercontent.com/18209713/213712949-7e6bcb86-bdd1-4708-b0ae-2b1c94b516be.jpg)
![image](https://user-images.githubusercontent.com/18209713/213713031-6b6bff43-e07e-464b-8d6b-0595036acb92.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
这个问题应该是修复了，等下一次命中了数字应该会增加了，等等看

**Comment by yubanmeiqin9048** [comment]
> 这个问题应该是修复了，等下一次命中了数字应该会增加了，等等看
>在v3.0.3 c258d90复现了这个问题
