### ISSUE TITLE
推送工具可否添加一个群辉版的chat

### ISSUE THREAD

**Issue by lihouyu520** [jxxghp/nas-tools#3077]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.0
>
> 环境: docker 

## 你想要新增或者改进什么功能？

> 推送消息的方式可否增加一个群辉的chat软件。

## 这个功能有什么可以参考的资料吗？

>群辉的chat套件部署简单，一键安装即可，多平台客户端齐全。支持Webhook和机器人。群辉及黑群晖的用户群体跟NAStool用户高度重合。

[https://www.synology.com/zh-tw/dsm/feature/chat]
下图是chat的界面

![QQ截图20230120221359](https://user-images.githubusercontent.com/58251824/213718935-95940f3f-9530-4ddf-a2be-28198efc40a4.jpg)

**Comment by 21denli** [comment]
我都建议增加群辉chat!优势明显！

**Comment by leihao** [comment]
我建议,直接添加一个通用的webhook,然后参数化的模板设置,功能设计可以参考ombi的,他们设计的不错
![image](https://user-images.githubusercontent.com/1472064/213754017-5e23ef5f-ce12-442d-83db-519906b7331c.png)
