### ISSUE TITLE
MetaVideo._episode_re无法识别S2E5这种格式

### ISSUE THREAD

**Issue by rainow** [jxxghp/nas-tools#308]
S2E5这种，剧集数字是1位的会识别不出来，不知道MetaVideo._episode_re 这里如果把 EP?(\d{2,4}) 改成  EP?(\d{1,4}) 会不会有太多误识别，大佬看看

[电视剧]绝命毒师-YNone-S2-ENone :: ./TV/绝命毒师 Breaking Bad（系列）/绝命毒师 Breaking Bad Season2/绝命毒师.S2E5.mp4
[电视剧]绝命毒师-YNone-S2-ENone :: ./TV/绝命毒师 Breaking Bad（系列）/绝命毒师 Breaking Bad Season2/绝命毒师.S2E9.mp4
[电视剧]绝命毒师-YNone-S2-ENone :: ./TV/绝命毒师 Breaking Bad（系列）/绝命毒师 Breaking Bad Season2/绝命毒师.S2E8.mp4
[电视剧]绝命毒师-YNone-S2-ENone :: ./TV/绝命毒师 Breaking Bad（系列）/绝命毒师 Breaking Bad Season2/绝命毒师.S2E6.mp4
[电视剧]绝命毒师-YNone-S2-E11 :: ./TV/绝命毒师 Breaking Bad（系列）/绝命毒师 Breaking Bad Season2/绝命毒师.S2E11.mp4
[电视剧]绝命毒师-YNone-S2-E10 :: ./TV/绝命毒师 Breaking Bad（系列）/绝命毒师 Breaking Bad Season2/绝命毒师.S2E10.mp4

**Comment by jxxghp** [comment]
不行的，改了误识别率巨增，不是没试过。
现在是S1.E1.这种格开的是能识别的，合在一起的没办法兼容。

**Comment by rainow** [comment]
单独识别E5肯定难，把S2E5作为一个整体来识别可行么？

> 不行的，改了误识别率巨增，不是没试过。 现在是S1.E1.这种格开的是能识别的，合在一起的没办法兼容。

**Comment by jxxghp** [comment]
> 单独识别E5肯定难，把S2E5作为一个整体来识别可行么？
> 
> 
> 
> > 不行的，改了误识别率巨增，不是没试过。 现在是S1.E1.这种格开的是能识别的，合在一起的没办法兼容。
> 
> 
> 
> 

这种资源多吗？
