### ISSUE TITLE
导航栏的订阅管理中的 电影订阅、电视剧订阅、订阅日历点击后无反应

### ISSUE THREAD

**Issue by windn0** [jxxghp/nas-tools#3080]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 

              v2.8.0 3d7059e
            
>
> 环境: docker on nas
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
首页导航栏 的订阅管理中的 电影订阅、电视剧订阅、订阅日历点击后无反应。无页面跳转

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
修复bug
## 给出程序界面截图、后台运行日志或配置文件
K2023-01-20T15:53:11.511067877Z     response = self.full_dispatch_request()
|2023-01-20T15:53:11.511075534Z   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
F2023-01-20T15:53:11.511083408Z     rv = self.handle_user_exception(e)
x2023-01-20T15:53:11.511094611Z   File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
>2023-01-20T15:53:11.511103202Z     return original_handler(e)
|2023-01-20T15:53:11.511112039Z   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
@2023-01-20T15:53:11.511155094Z     rv = self.dispatch_request()
w2023-01-20T15:53:11.511165258Z   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
p2023-01-20T15:53:11.511173351Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
|2023-01-20T15:53:11.511184513Z   File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
Y2023-01-20T15:53:11.511196274Z     return current_app.ensure_sync(func)(*args, **kwargs)
T2023-01-20T15:53:11.511204722Z   File "/nas-tools/web/main.py", line 298, in tv_rss
Z2023-01-20T15:53:11.511212604Z     RssItems = WebAction().get_tv_rss_list().get("result")
`2023-01-20T15:53:11.511220418Z   File "/nas-tools/web/action.py", line 3563, in get_tv_rss_list
a2023-01-20T15:53:11.511228277Z     return {"code": 0, "result": Subscribe().get_subscribe_tvs()}
d2023-01-20T15:53:11.511239351Z   File "/nas-tools/app/subscribe.py", line 389, in get_subscribe_tvs
_2023-01-20T15:53:11.511250849Z     rss_tvs = self.dbhelper.get_rss_tvs(rssid=rid, state=state)
e2023-01-20T15:53:11.511259044Z   File "/nas-tools/app/helper/db_helper.py", line 796, in get_rss_tvs
G2023-01-20T15:53:11.511266629Z     return self._db.query(RSSTVS).all()
u2023-01-20T15:53:11.511273959Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2772, in all
=2023-01-20T15:53:11.511281560Z     return self._iter().all()
w2023-01-20T15:53:11.511291981Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
B2023-01-20T15:53:11.511310025Z     result = self.session.execute(
{2023-01-20T15:53:11.511318960Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
i2023-01-20T15:53:11.511326691Z     result = conn._execute_20(statement, params or {}, execution_options)
2023-01-20T15:53:11.511334327Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
f2023-01-20T15:53:11.511344729Z     return meth(self, args_10style, kwargs_10style, execution_options)
�2023-01-20T15:53:11.511355652Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
M2023-01-20T15:53:11.511364671Z     return connection._execute_clauseelement(
�2023-01-20T15:53:11.511371751Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
@2023-01-20T15:53:11.511379113Z     ret = self._execute_context(
�2023-01-20T15:53:11.511386074Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
A2023-01-20T15:53:11.511393430Z     self._handle_dbapi_exception(
�2023-01-20T15:53:11.511403396Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
02023-01-20T15:53:11.511414644Z     util.raise_(
y2023-01-20T15:53:11.511433945Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
32023-01-20T15:53:11.511442473Z     raise exception
�2023-01-20T15:53:11.511452552Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
<2023-01-20T15:53:11.511463336Z     self.dialect.do_execute(
�2023-01-20T15:53:11.511470859Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
I2023-01-20T15:53:11.511478123Z     cursor.execute(statement, parameters)
{2023-01-20T15:53:11.511485087Z sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: RSS_TVS.KEYWORD
z2023-01-20T15:53:11.511499196Z [SQL: SELECT "RSS_TVS"."ID" AS "RSS_TVS_ID", "RSS_TVS"."NAME" AS "RSS_TVS_NAME", "RSS_TVS"."YEAR" AS "RSS_TVS_YEAR", "RSS_TVS"."KEYWORD" AS "RSS_TVS_KEYWORD", "RSS_TVS"."SEASON" AS "RSS_TVS_SEASON", "RSS_TVS"."TMDBID" AS "RSS_TVS_TMDBID", "RSS_TVS"."IMAGE" AS "RSS_TVS_IMAGE", "RSS_TVS"."RSS_SITES" AS "RSS_TVS_RSS_SITES", "RSS_TVS"."SEARCH_SITES" AS "RSS_TVS_SEARCH_SITES", "RSS_TVS"."OVER_EDITION" AS "RSS_TVS_OVER_EDITION", "RSS_TVS"."FILTER_ORDER" AS "RSS_TVS_FILTER_ORDER", "RSS_TVS"."FILTER_RESTYPE" AS "RSS_TVS_FILTER_RESTYPE", "RSS_TVS"."FILTER_PIX" AS "RSS_TVS_FILTER_PIX", "RSS_TVS"."FILTER_RULE" AS "RSS_TVS_FILTER_RULE", "RSS_TVS"."FILTER_TEAM" AS "RSS_TVS_FILTER_TEAM", "RSS_TVS"."SAVE_PATH" AS "RSS_TVS_SAVE_PATH", "RSS_TVS"."DOWNLOAD_SETTING" AS "RSS_TVS_DOWNLOAD_SETTING", "RSS_TVS"."FUZZY_MATCH" AS "RSS_TVS_FUZZY_MATCH", "RSS_TVS"."TOTAL_EP" AS "RSS_TVS_TOTAL_EP", "RSS_TVS"."CURRENT_EP" AS "RSS_TVS_CURRENT_EP", "RSS_TVS"."TOTAL" AS "RSS_TVS_TOTAL", "RSS_TVS"."LACK" AS "RSS_TVS_LACK", "RSS_TVS"."STATE" AS "RSS_TVS_STATE", "RSS_TVS"."DESC" AS "RSS_TVS_DESC", "RSS_TVS"."NOTE" AS "RSS_TVS_NOTE" 
/2023-01-20T15:53:11.511519160Z FROM "RSS_TVS"]
\2023-01-20T15:53:11.511530039Z (Background on this error at: https://sqlalche.me/e/14/e3q8)
f2023-01-20T15:53:18.534646067Z [2023-01-20 23:53:18,532] ERROR in app: Exception on /movie_rss [POST]
B2023-01-20T15:53:18.534696758Z Traceback (most recent call last):
�2023-01-20T15:53:18.534706231Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
<2023-01-20T15:53:18.534714338Z     self.dialect.do_execute(
�2023-01-20T15:53:18.534725719Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
I2023-01-20T15:53:18.534737529Z     cursor.execute(statement, parameters)
\2023-01-20T15:53:18.534745787Z sqlite3.OperationalError: no such column: RSS_MOVIES.KEYWORD
d2023-01-20T15:53:18.534753668Z The above exception was the direct cause of the following exception:
B2023-01-20T15:53:18.534764963Z Traceback (most recent call last):
o2023-01-20T15:53:18.534775932Z   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
K2023-01-20T15:53:18.534784402Z     response = self.full_dispatch_request()
|2023-01-20T15:53:18.534792056Z   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
F2023-01-20T15:53:18.534834684Z     rv = self.handle_user_exception(e)
x2023-01-20T15:53:18.534847979Z   File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
>2023-01-20T15:53:18.534856520Z     return original_handler(e)
|2023-01-20T15:53:18.534869721Z   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
@2023-01-20T15:53:18.534878179Z     rv = self.dispatch_request()
w2023-01-20T15:53:18.534889015Z   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
p2023-01-20T15:53:18.534900747Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
|2023-01-20T15:53:18.534909323Z   File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
Y2023-01-20T15:53:18.534917452Z     return current_app.ensure_sync(func)(*args, **kwargs)
W2023-01-20T15:53:18.534924863Z   File "/nas-tools/web/main.py", line 283, in movie_rss
]2023-01-20T15:53:18.534932676Z     RssItems = WebAction().get_movie_rss_list().get("result")
c2023-01-20T15:53:18.534940305Z   File "/nas-tools/web/action.py", line 3556, in get_movie_rss_list
d2023-01-20T15:53:18.534951375Z     return {"code": 0, "result": Subscribe().get_subscribe_movies()}
g2023-01-20T15:53:18.534962891Z   File "/nas-tools/app/subscribe.py", line 324, in get_subscribe_movies
e2023-01-20T15:53:18.534971478Z     rss_movies = self.dbhelper.get_rss_movies(rssid=rid, state=state)
h2023-01-20T15:53:18.534981487Z   File "/nas-tools/app/helper/db_helper.py", line 606, in get_rss_movies
J2023-01-20T15:53:18.534989665Z     return self._db.query(RSSMOVIES).all()
u2023-01-20T15:53:18.535000694Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2772, in all
=2023-01-20T15:53:18.535012265Z     return self._iter().all()
w2023-01-20T15:53:18.535020359Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
B2023-01-20T15:53:18.535028533Z     result = self.session.execute(
{2023-01-20T15:53:18.535039191Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
i2023-01-20T15:53:18.535051080Z     result = conn._execute_20(statement, params or {}, execution_options)
2023-01-20T15:53:18.535059719Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
f2023-01-20T15:53:18.535067631Z     return meth(self, args_10style, kwargs_10style, execution_options)
�2023-01-20T15:53:18.535079495Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
M2023-01-20T15:53:18.535091284Z     return connection._execute_clauseelement(
�2023-01-20T15:53:18.535099382Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
@2023-01-20T15:53:18.535107567Z     ret = self._execute_context(
�2023-01-20T15:53:18.535130048Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
A2023-01-20T15:53:18.535143291Z     self._handle_dbapi_exception(
�2023-01-20T15:53:18.535152023Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
02023-01-20T15:53:18.535160293Z     util.raise_(
y2023-01-20T15:53:18.535170998Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
32023-01-20T15:53:18.535182430Z     raise exception
�2023-01-20T15:53:18.535190336Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
<2023-01-20T15:53:18.535198071Z     self.dialect.do_execute(
�2023-01-20T15:53:18.535205051Z   File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
I2023-01-20T15:53:18.535213728Z     cursor.execute(statement, parameters)
~2023-01-20T15:53:18.535221007Z sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: RSS_MOVIES.KEYWORD
$2023-01-20T15:53:18.535233610Z [SQL: SELECT "RSS_MOVIES"."ID" AS "RSS_MOVIES_ID", "RSS_MOVIES"."NAME" AS "RSS_MOVIES_NAME", "RSS_MOVIES"."YEAR" AS "RSS_MOVIES_YEAR", "RSS_MOVIES"."KEYWORD" AS "RSS_MOVIES_KEYWORD", "RSS_MOVIES"."TMDBID" AS "RSS_MOVIES_TMDBID", "RSS_MOVIES"."IMAGE" AS "RSS_MOVIES_IMAGE", "RSS_MOVIES"."RSS_SITES" AS "RSS_MOVIES_RSS_SITES", "RSS_MOVIES"."SEARCH_SITES" AS "RSS_MOVIES_SEARCH_SITES", "RSS_MOVIES"."OVER_EDITION" AS "RSS_MOVIES_OVER_EDITION", "RSS_MOVIES"."FILTER_ORDER" AS "RSS_MOVIES_FILTER_ORDER", "RSS_MOVIES"."FILTER_RESTYPE" AS "RSS_MOVIES_FILTER_RESTYPE", "RSS_MOVIES"."FILTER_PIX" AS "RSS_MOVIES_FILTER_PIX", "RSS_MOVIES"."FILTER_RULE" AS "RSS_MOVIES_FILTER_RULE", "RSS_MOVIES"."FILTER_TEAM" AS "RSS_MOVIES_FILTER_TEAM", "RSS_MOVIES"."SAVE_PATH" AS "RSS_MOVIES_SAVE_PATH", "RSS_MOVIES"."DOWNLOAD_SETTING" AS "RSS_MOVIES_DOWNLOAD_SETTING", "RSS_MOVIES"."FUZZY_MATCH" AS "RSS_MOVIES_FUZZY_MATCH", "RSS_MOVIES"."STATE" AS "RSS_MOVIES_STATE", "RSS_MOVIES"."DESC" AS "RSS_MOVIES_DESC", "RSS_MOVIES"."NOTE" AS "RSS_MOVIES_NOTE" 
22023-01-20T15:53:18.535253239Z FROM "RSS_MOVIES"]
\2023-01-20T15:53:18.535261189Z (Background on this error at: https://sqlalche.me/e/14/e3q8)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
问题修复：v2.8.0版本由于数据库升级顺序问题，第一时间就完成了升级的，数据库可能无法准确更新，且不会再次触发更新操作，可按如下方式处理（从低版本直接升级到当前最新版本的没有这个问题）：
1、更新到当前最新程序、或拉取最新镜像（小版本号：3d7059e）。
2、备份配置->重新导入配置->重启（整理历史记录会丢失）；或者使用sqllite数据库软件打开user.db->删除alembic_version表->重启（所有数据完整保留）。

其中删除alembic_version表的方法也可用于解决Windows版本无法启动的问题。

**Comment by windn0** [comment]
> 问题修复：v2.8.0版本由于数据库升级顺序问题，第一时间就完成了升级的，数据库可能无法准确更新，且不会再次触发更新操作，可按如下方式处理（从低版本直接升级到当前最新版本的没有这个问题）： 1、更新到当前最新程序、或拉取最新镜像（小版本号：3d7059e）。 2、备份配置->重新导入配置->重启（整理历史记录会丢失）；或者使用sqllite数据库软件打开user.db->删除alembic_version表->重启（所有数据完整保留）。
> 
> 其中删除alembic_version表的方法也可用于解决Windows版本无法启动的问题。

按照方法1 备份配置后再导入配置并重启后，问题解决。谢谢！

**Comment by yyyyyyounger** [comment]
同问题，在2.8.0版本下，按楼上方法2 操作后成功恢复点击切换的功能。
补充一下`备份功能`的位置在这里：
![image](https://user-images.githubusercontent.com/55580370/213784713-ed8bfd14-2a9f-46a8-b4c5-276e3057fce2.png)
