### ISSUE TITLE
CookieCloud 二级目录问题

### ISSUE THREAD

**Issue by DDSDerek** [jxxghp/nas-tools#3081]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.0
>
> 环境: docker 
>

## 你遇到什么问题了？ 

CookieCloud使用反向代理+二级目录时，nastools无法正常调用。当CookieCloud只设置反向代理时，nastools可以正常调用

CookieCloud在`cef46ad`之前是不支持二级目录的，这个功能是在`cef46ad`新更新的功能。

所以有可能nastools还没有进行支持，我希望可以支持`CookieCloud使用反向代理+二级目录`这个功能，这个功能可以很方便的进行管理

![image](https://user-images.githubusercontent.com/108336573/213745594-79d9a337-a417-4804-9983-c8929c79ad90.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

**Comment by DDSDerek** [comment]
补充两张图片，第一张图片可以正常同步，第二张图片就不行

服务端用的是同一个，第二个只是多了在服务端设置二级目录这一点

![image](https://user-images.githubusercontent.com/108336573/213840580-c8b10172-3df8-4506-9801-530e7c8b5e2f.png)
![image](https://user-images.githubusercontent.com/108336573/213840587-4a659459-7dad-481d-9ae6-791e08104dc2.png)

**Comment by 2Dou** [comment]
俺也一样

**Comment by DDSDerek** [comment]
我的NAStool dev版本升级 https://github.com/jxxghp/nas-tools/pull/3413 这个提交后还是有问题
