### ISSUE TITLE
订阅 分辨率没有2160p选项

### ISSUE THREAD

**Issue by royzheng** [jxxghp/nas-tools#3083]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6 ac20f64
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 在订阅的分辨率选项里没有2160p，选4k没有作用（比如订阅狂飙的时候选4k并不会下载2160p的）

## 这个功能有什么可以参考的资料吗？

> 暂无

**Comment by jy02919061** [comment]
可以啊

**Comment by royzheng** [comment]
[https://www.z4a.net/images/2023/01/21/image3ae0cefecc89e8b8.png](https://www.z4a.net/images/2023/01/21/image3ae0cefecc89e8b8.png)

辛苦了 我说的是这个选项哦 没有2160p选项，如果选4k好像并不会命中2160p的视频

**Comment by Wangsc1** [comment]
4k就是2160p和4k，没问题

**Comment by royzheng** [comment]
> 4k就是2160p和4k，没问题

是吗？那我再复现下看看会不会，先关闭了，如果还会出现我弄个完整复现流程出来
