### ISSUE TITLE
HDR、杜比视界识别

### ISSUE THREAD

**Issue by MisakaFxxk** [jxxghp/nas-tools#3085]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5
>
> 环境: docker                 

## 你想要新增或者改进什么功能？

> 可以识别文件名中的HDR、SDR(没有HDR或DV的话就默认SDR)、杜比视界标志，并在重命名时有相关的占位符选择。

## 这个功能有什么可以参考的资料吗？

> 木有

**Comment by Wangsc1** [comment]
可以试试这个
![image](https://user-images.githubusercontent.com/26079238/213849266-7c7ef58c-3bf7-42e9-81b0-9621ddc239c2.jpeg)

**Comment by MisakaFxxk** [comment]
> 可以试试这个 ![image](https://user-images.githubusercontent.com/26079238/213849266-7c7ef58c-3bf7-42e9-81b0-9621ddc239c2.jpeg)

蟹蟹，我试试
