### ISSUE TITLE
站点资源下载不能加载预设的下载的保存目录

### ISSUE THREAD

**Issue by Jungor168** [jxxghp/nas-tools#3087]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.0
>
> 环境: docker 
>

## 你遇到什么问题了？

>  位置: 站点管理->站点资源->下载， 更新新版本后使用站点资源下载时，不能加载在下载器中设置好的的保存目录

**Comment by jxxghp** [comment]
已修复
