### ISSUE TITLE
数据统计没办法显示长传下载饼图

### ISSUE THREAD

**Issue by SinoHorn** [jxxghp/nas-tools#3089]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8
>
> 环境: docker
>

## 你遇到什么问题了？

>  更新了以后因为出现了订阅页面无法打开的问题, 于是删除了config 文件夹 单单留下了config.yaml 重新设定订阅以及rss订阅站点. 在数据统计页面原本显示的单日上传下载量, 就一直为零

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

我已经浏览过所有的解决方式并没有此问题解决.

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

>  希望可以提出解决方案

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![DCA9ABDF-6BF4-427D-A635-308BF3B91FEB](https://user-images.githubusercontent.com/123235519/213859355-5168a1e6-0c43-4118-b872-4ba167c16a3d.jpeg)

**Comment by Shurelol** [comment]
第二天才会有
