### ISSUE TITLE
同一个剧集文件夹中不同季是否可以强制识别为一个分类

### ISSUE THREAD

**Issue by rainow** [jxxghp/nas-tools#309]
之前手动下的《一人之下》，第三季和前两季的文件命名不一样，结果目录同步之后，就前两季识别成了电视剧，第三季识别成了动漫。
下面是我自己print的结果，后面是实际路径，前面是去搜线上信息之前的识别结果，最后输出的结果就是识别成了两个不同的文件夹

[电视剧]一人之下-YNone-S1-E12 :: ./TV/一人之下 The outcast/Season 1/一人之下第12集.mp4
[电视剧]一人之下-YNone-S1-E1 :: ./TV/一人之下 The outcast/Season 1/一人之下第1集.mp4
[电视剧]一人之下-YNone-S1-E3 :: ./TV/一人之下 The outcast/Season 1/一人之下第3集.mp4
[电视剧]一人之下-YNone-S1-E9 :: ./TV/一人之下 The outcast/Season 1/一人之下第9集.mp4
[电视剧]一人之下-YNone-S1-E11 :: ./TV/一人之下 The outcast/Season 1/一人之下第11集.mp4
[电视剧]一人之下-YNone-S1-E5 :: ./TV/一人之下 The outcast/Season 1/一人之下第5集.mp4
[电视剧]一人之下-YNone-S2-E1 :: ./TV/一人之下 The outcast/Season 2/01.mp4
[动漫]The Outcast-Y2020-S3-E6 :: ./TV/一人之下 The outcast/Season 3/[GM-Team][国漫][一人之下 第3季][The Outcast 3rd Season][2020][06][AVC][GB][1080P].mp4
[动漫]The Outcast-Y2020-S3-E2 :: ./TV/一人之下 The outcast/Season 3/[GM-Team][国漫][一人之下 第3季][The Outcast 3rd Season][2020][02][AVC][GB][1080P].mp4
[动漫]The Outcast-Y2020-S3-E4 :: ./TV/一人之下 The outcast/Season 3/[GM-Team][国漫][一人之下 第3季][The Outcast 3rd Season][2020][04][AVC][GB][1080P].mp4
[动漫]The Outcast-Y2020-S3-E5 :: ./TV/一人之下 The outcast/Season 3/[GM-Team][国漫][一人之下 第3季][The Outcast 3rd Season][2020][05][AVC][GB][1080P].mp4
[动漫]The Outcast-Y2020-S3-E8 :: ./TV/一人之下 The outcast/Season 3/[GM-Team][国漫][一人之下 第3季][The Outcast 3rd Season][2020][08][AVC][GB][1080P].mp4
[动漫]The Outcast-Y2020-S3-E1 :: ./TV/一人之下 The outcast/Season 3/[GM-Team][国漫][一人之下 第3季][The Outcast 3rd Season][2020][01][AVC][GB][1080P].mp4
[动漫]The Outcast-Y2020-S3-E7 :: ./TV/一人之下 The outcast/Season 3/[GM-Team][国漫][一人之下 第3季][The Outcast 3rd Season][2020][07][AVC][GB][1080P].mp4
[动漫]The Outcast-Y2020-S3-E3 :: ./TV/一人之下 The outcast/Season 3/[GM-Team][国漫][一人之下 第3季][The Outcast 3rd Season][2020][03][AVC][GB][1080P].mp4

**Comment by jxxghp** [comment]
不确定问题在哪里，调了一些代码，你试试解决了没有
