### ISSUE TITLE
资源搜索HR不显示了

### ISSUE THREAD

**Issue by git-0101** [jxxghp/nas-tools#3093]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 目前遇到两种形式的HR
第一种CHD的
![Screenshot_20230122_021242](https://user-images.githubusercontent.com/115487446/213881333-cb3517ad-615e-41ad-b051-64a661f34828.jpg)
搜索还没改版前可以显示，后来搜索的资源都没HR，不知改版后的情况

第二种HHCLUB的
![Screenshot_20230122_021159](https://user-images.githubusercontent.com/115487446/213881483-8214cd70-2346-4de2-b5e1-a765e07dcbee.jpg)
这种之前搜索也没遇到过，不知道是否可以。

目前是显示不出来
![Screenshot_20230122_021453](https://user-images.githubusercontent.com/115487446/213881758-f096bb81-3298-4d41-bb24-126650e72d0f.jpg)

**Comment by jxxghp** [comment]
#2732
