### ISSUE TITLE
关于synology chat交互

### ISSUE THREAD

**Issue by Dantezcx** [jxxghp/nas-tools#3097]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 更新最新2.8.1之后的synology chat交互问题
配置完成之后测试，接收消息没有问题
但是发送交互消息之后后台日志显示错误

收到来自 ::ffff:172.17.0.1 的非法 Synology Chat 消息

**Comment by jxxghp** [comment]
安全设置
