### ISSUE TITLE
HDC地址

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#3103]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

HDC现在地址存在打不开可能 是否可以➕WWW
变更为：
https://www.hdchina.org/index.php

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![Uploading 582214E1-01D7-45DE-99D4-F17DD932E131.jpeg…]()

**Comment by jxxghp** [comment]
加了www报错？
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/51039935/213947735-521adf1f-25e8-44d8-936c-e3a66cc8c514.png">

**Comment by Tartarus2014** [comment]
啊 不该啊 这么奇怪的么
![Uploading CA1F133B-3EEE-40FB-9CF8-3279540B1D99.jpeg…]()

**Comment by Tartarus2014** [comment]
![C21FA24B-68B2-485C-A116-29D9941F5916](https://user-images.githubusercontent.com/39802246/213975309-9ca9d1d1-f75b-4476-9aab-fdcafd7fc3dc.jpeg)

**Comment by Tartarus2014** [comment]
> 不该啊  我那测试没问题呀
> ![C21FA24B-68B2-485C-A116-29D9941F5916](https://user-images.githubusercontent.com/39802246/213975309-9ca9d1d1-f75b-4476-9aab-fdcafd7fc3dc.jpeg)
