### ISSUE TITLE
windows版的NASTOOL，添加115的COOKIE总是测试失败，但在ALICT中这个COOKIE是有效的

### ISSUE THREAD

**Issue by sunrainnet** [jxxghp/nas-tools#3104]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.8.0
>
> 环境: win10
>

## 你遇到什么问题了？

想用电脑版的115浏览器来下载，我是115的会员，但是获取的COOKIE，填到NASTOOLS中测试总是失败。但同一个COOKIE，在ALIST中是有效的，请问是什么问题？

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
搜索过没有相磁内容

## 你期望的结果

想用电脑版的115来下载

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by zhaokun0721** [comment]
请问你是怎么升级上2.8.0的 我是 2.8 2.8.1 打都打不开 win10 还是只能用2,7 6

**Comment by jxxghp** [comment]
翻下之前的Issues
