### ISSUE TITLE
unhandled exception in script

### ISSUE THREAD

**Issue by cool-ic** [jxxghp/nas-tools#3106]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.1
>
> 环境:  windows 
>

## 你遇到什么问题了？
从2.7.3，手动下载exe，更新到2.8.1，无法启动nastools主程序

![image](https://user-images.githubusercontent.com/23274085/213918125-cd200e56-b9b2-4d5c-8368-fb40f21a01a2.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是

## 你期望的结果

解决bug

## 给出程序界面截图、后台运行日志或配置文件

![image](https://user-images.githubusercontent.com/23274085/213918125-cd200e56-b9b2-4d5c-8368-fb40f21a01a2.png)

**Comment by cool-ic** [comment]
经过几次实验，从2.7.4到2.7.6升级就会报这个bug。

**Comment by jxxghp** [comment]
Win的搞不定了，删掉user.db重新配置吧
