### ISSUE TITLE
win按照说明删除数据库条目依然升级2.8报错

### ISSUE THREAD

**Issue by makerdegit** [jxxghp/nas-tools#3109]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: windows
>

## 你遇到什么问题了？

> 没想到我也遇到win的升级错误了，按照说明删除数据库对应条目依旧报错，2.8和2.8.1都不行

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 希望能解决，上次升级2.7.6也是在tg频道看你发了一个，问大家情况，那个才成功的

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/122148963/213927073-f1f8d85d-04a5-4978-8039-9699214da7c0.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by zhaokun0721** [comment]
我也是啊 打不开 等修复吧

**Comment by jxxghp** [comment]
Win的搞不定了，删掉user.db重新配置吧
