### ISSUE TITLE
CookieCloud建议增加定时或者ck过期自动同步选项

### ISSUE THREAD

**Issue by mizb** [jxxghp/nas-tools#3114]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx2.8.1
>
> 环境: docker 

## 你想要新增或者改进什么功能？

CookieCloud建议增加定时或者ck过期自动同步选项，进一步完善自动化。

**Comment by jxxghp** [comment]
浏览器里存的也不一定有效，自动可能误同步
