### ISSUE TITLE
nastools 添加下載失敗

### ISSUE THREAD

**Issue by andyson222** [jxxghp/nas-tools#3120]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v 2.7.6
>QB 版本: v 4.5
> 环境:  Synology DSM 7.1.1
>

## 你遇到什么问题了？

> 用nas tools搜尋影片後, 點擊連結下載後提示添加下載失敗, 请检查下载任务是否已存在！(之前下載過的一部影片由於下載完成後看了效果很差, 就在links和video檔案夾裡手動刪除相關影片和檔案夾, 其它都沒變更過)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 沒有找到有對應的問題

## 你期望的结果

> 可以正常添加下載連結到QB

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
![image](https://user-images.githubusercontent.com/123399693/214102421-64476a8a-f592-4a78-87b3-30352a780fab.png)

>

**Comment by jxxghp** [comment]
日志？
