### ISSUE TITLE
Nt在资源搜索位置手动添加下载，未走站点代理

### ISSUE THREAD

**Issue by MrLv0816** [jxxghp/nas-tools#3123]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.0
>
> 环境: Synology
>

## 你遇到什么问题了？

> Nt在资源搜索位置手动添加下载，未走站点代理
> 由于在资源搜索处没有使用代理访问pt站点，导致无法下载

![image](https://user-images.githubusercontent.com/46812909/214209176-6467757f-66c4-44aa-acb8-2cbe307aaa07.png)

**Comment by jxxghp** [comment]
日志？

**Comment by MrLv0816** [comment]
> 日志？

![image](https://user-images.githubusercontent.com/46812909/214644606-90d4d1e5-4a2c-4d29-8537-41ff9dacbe9c.png)

**Comment by MrLv0816** [comment]
> 日志？

站点测试均正常，rss获取，站点搜索均正常工作，只有这个下载链接会提示无法打开
