### ISSUE TITLE
Windows Server 2019下 运行nastool报错

### ISSUE THREAD

**Issue by msn014030** [jxxghp/nas-tools#3127]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.8.1
> 环境: docker or windows or Synology
>Windows Server 2019

## 你遇到什么问题了？

> 描述一下你遇到的问题
运行后报错
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
期望可以使用
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
![PDF50KD01SQCQV)U~5%3T`F](https://user-images.githubusercontent.com/69434855/214257200-422e0030-2a80-43eb-acc7-cda11af8b7e4.png)

> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
#3116
