### ISSUE TITLE
V2.8.1消息通知问题

### ISSUE THREAD

**Issue by tjxiaoyao** [jxxghp/nas-tools#3128]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.1
>
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> 升级前版本为2.7.6，同时配置了微信和slack消息通知，正常使用。升级2.8.1后，新配置了synology chat消息通知，测试正常，但是重启nastool之后wechat不能交互，只是被动受到消息，通过查看日志发现，wechat和synology chat服务没有启动，手动启动或关闭wechat和synology chat服务，日志先显示slack服务被停止，然后显示slack服务被启动，没有对wechat和synology chat的操作的日志形成。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 未发现关于此问题的描述

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
贴日志，
走webhook没有服务进程自然不存在启动停止服务日志。

**Comment by tjxiaoyao** [comment]
16:39:05	System	NAStool 当前版本号：v2.8.1
16:39:05	System	开始初始化数据库...
16:39:05	System	数据库初始化完成
16:39:05	System	开始更新数据库...
16:39:05	System	数据库更新完成
16:39:05	System	开始初始化数据...
16:39:05	System	数据初始化完成
16:39:06	System	开始启动服务...
16:39:13	System	Slack消息接收服务启动
16:39:15	System	站点自动签到服务启动
16:39:16	System	RSS订阅服务启动
16:39:16	System	订阅定时搜索服务启动
16:39:16	System	豆瓣同步服务启动
16:39:16	System	媒体库同步服务启动
16:39:16	Sync	读取到监控目录：/volume2/video/Movie，目的目录：/volume2/video/link/Movie，转移方式：硬链接
16:39:16	Sync	读取到监控目录：/volume2/video/TV，目的目录：/volume2/video/link/TV，转移方式：硬链接
16:39:33	System	/volume2/video/Movie 的监控服务启动
16:39:33	System	/volume2/video/TV 的监控服务启动
![Uploading Screenshot_20230125_164332.jpg…]()

**Comment by tjxiaoyao** [comment]
![Screenshot_20230125_164332](https://user-images.githubusercontent.com/123466681/214519112-5c822f5f-4660-4596-910d-e3865f350872.jpg)

**Comment by tjxiaoyao** [comment]
16:39:05 | System | NAStool 当前版本号：v2.8.1
-- | -- | --
16:39:05 | System | 开始初始化数据库...
16:39:05 | System | 数据库初始化完成
16:39:05 | System | 开始更新数据库...
16:39:05 | System | 数据库更新完成
16:39:05 | System | 开始初始化数据...
16:39:05 | System | 数据初始化完成
16:39:06 | System | 开始启动服务...
16:39:13 | System | Slack消息接收服务启动
16:39:15 | System | 站点自动签到服务启动
16:39:16 | System | RSS订阅服务启动
16:39:16 | System | 订阅定时搜索服务启动
16:39:16 | System | 豆瓣同步服务启动
16:39:16 | System | 媒体库同步服务启动
16:39:16 | Sync | 读取到监控目录：/volume2/video/Movie，目的目录：/volume2/video/link/Movie，转移方式：硬链接
16:39:16 | Sync | 读取到监控目录：/volume2/video/TV，目的目录：/volume2/video/link/TV，转移方式：硬链接
16:39:33 | System | /volume2/video/Movie 的监控服务启动
16:39:33 | System | /volume2/video/TV 的监控服务启动
16:52:04 | System | Slack消息接收服务已停止
16:52:07 | System | Slack消息接收服务启动
16:52:11 | System | Slack消息接收服务已停止
16:52:14 | System | Slack消息接收服务启动

**Comment by tjxiaoyao** [comment]
补充一下上面日志和截图：16:39我重启了nastool，16:40开始截图的操作，在微信里输入影片，通过微信菜单运行站点签到，结果没有反馈，日志也没有体现。之后在nastool的消息通知里关闭然后开启微信通知，结果在日志里显示slack通知被关闭然后启动

**Comment by tjxiaoyao** [comment]
非常抱歉！微信无法互动的原因找到了，是我的nastool外部端口改了，与nastool无关，实在抱歉！
