### ISSUE TITLE
自动触发的目录同步功能在对一个已同步过的资源同步后,就提前结束了同步.没有扫描到新增资源.

### ISSUE THREAD

**Issue by ztx0079** [jxxghp/nas-tools#313]
版本1.6.2
待同步目录内目前有若干待同步的资源
自动启用的目录同步只有一组对已同步过的资源的日志,其它的资源没有被扫描到.
手动启用的目录同步会完整扫描.

设置的同步目录为/media2/downloads-NasTools
尝试复制文件到 /media2/downloads-NasTools/a.mkv 可成功触发自动目录同步
尝试复制文件到 /media2/downloads-NasTools/新建文件夹/a.mkv 不会触发自动目录同步(新建文件夹为新生成的),且后续自动触发的目录同步功能也不会扫描到这个目录内的内容.

08:04:15 INFO - 【RMT】开始处理：/media2/downloads-NasTools/9 Bullets 2022 Blu-ray 1080p AVC DTS-HD MA 5.1-ltzww@CHDBits
08:04:15 INFO - 【RMT】当前为蓝光原盘文件夹：/media2/downloads-NasTools/9 Bullets 2022 Blu-ray 1080p AVC DTS-HD MA 5.1-ltzww@CHDBits
08:04:15 WARN - 【RMT】蓝光原盘目录已存在：/media2/movies/外语电影/9发子弹 (2022)
08:04:15 INFO - 【RMT】/media2/downloads-NasTools/9 Bullets 2022 Blu-ray 1080p AVC DTS-HD MA 5.1-ltzww@CHDBits 处理完成，总数：1，失败：1
08:04:15 INFO - 【RSS】电影订阅清单：铃芽户缔 闪电侠 黑豹2 银河护卫队3 阿凡达2：水之道 雷神4：爱与雷霆 目中无人
08:04:15 INFO - 【RSS】电视剧订阅清单：夏日重现 梦华录
08:04:15 INFO - 【RSS】正在处理：mikan
08:04:16 INFO - 【RSS】mikan 获取数据：100
08:04:17 INFO - 【RSS】mikan 处理结束，匹配到 0 个有效资源
08:04:17 INFO - 【RSS】正在处理：动漫花园
08:04:19 INFO - 【RSS】动漫花园 获取数据：500
08:04:21 INFO - 【RSS】动漫花园 处理结束，匹配到 0 个有效资源
08:04:21 INFO - 【RSS】正在处理：CHDBits
08:04:22 INFO - 【RSS】CHDBits 获取数据：50
08:04:22 INFO - 【RSS】CHDBits 处理结束，匹配到 0 个有效资源
08:04:22 INFO - 【RSS】所有RSS处理结束，共 0 个有效资源
08:04:22 INFO - 【RSS】未下载到任何资源
08:09:15 INFO - 【SYNC】开始转移监控目录文件...
08:09:15 INFO - 【RMT】开始处理：/media2/downloads-NasTools/9 Bullets 2022 Blu-ray 1080p AVC DTS-HD MA 5.1-ltzww@CHDBits
08:09:15 INFO - 【RMT】当前为蓝光原盘文件夹：/media2/downloads-NasTools/9 Bullets 2022 Blu-ray 1080p AVC DTS-HD MA 5.1-ltzww@CHDBits
08:09:15 WARN - 【RMT】蓝光原盘目录已存在：/media2/movies/外语电影/9发子弹 (2022)
08:09:15 INFO - 【RMT】/media2/downloads-NasTools/9 Bullets 2022 Blu-ray 1080p AVC DTS-HD MA 5.1-ltzww@CHDBits 处理完成，总数：1，失败：1

**Comment by jxxghp** [comment]
根目录下的文件是立即处理的，子目录下的文件是五分钟一批处理

**Comment by ztx0079** [comment]
> 根目录下的文件是立即处理的，子目录下的文件是五分钟一批处理

就是5分钟的批处理扫不到,这个日志就是5分钟一次的批处理日志

**Comment by hncdbai** [comment]
我也有这个问题，每次都只能手动

**Comment by jxxghp** [comment]
这个应该没有问题的，不然倒下一大片了
