### ISSUE TITLE
清理缓存后，再次目录同步会创建之前已有的文件夹

### ISSUE THREAD

**Issue by Painwt** [jxxghp/nas-tools#3130]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.8.1
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 描述一下你遇到的问题
使用 nastools 清理转移缓存和 RSS 缓存后，再次目录同步会将原先已识别过的某些视频文件重命名并再次识别
例如：海贼王 原先已经全部识别过了，形成了 海贼王（1999），但是清理转移缓存和 RSS 缓存，再次目录同步后，会将其中某一些集数再次识别，并创建另一个文件 航海王（1999），还有一些动漫名会再次识别成英文版，比如 进击的巨人，清理缓存完再次同步后会在原先有的基础上再创建一个文件 Attack on Titan，因为我这动漫和电影整理的比较多，有时候不识别的时候会手动清理缓存再次识别一下，结果就会多出来一堆已经识别过的，再次识别，就很麻烦，需要手动删除多出来的
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
希望能将同一个动漫或者电影什么的不同的中文翻译整成一个数据集，比如 海贼王、航海王、onepiece 整成一个数据集，识别后如果已经有了其中一个，如 海贼王，则不会再创建 航海王或者 onepiece 文件
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
是因为tmdb的数据变了吧，你又要去清缓存，建议解决方案？

**Comment by Painwt** [comment]
<img width="1095" alt="1" src="https://user-images.githubusercontent.com/36558599/214469969-2d78c2bd-e79d-4e77-8523-997f832c33d9.png">
<img width="1091" alt="2" src="https://user-images.githubusercontent.com/36558599/214469976-2111ae7d-3a58-494b-ab89-7be2a4ec05a7.png">
<img width="1041" alt="3" src="https://user-images.githubusercontent.com/36558599/214469986-b53e2ab2-ceb2-408b-872c-2117fca525c8.png">
我试了一下，如果TMDB设置为 zhCN 就是简体中文，名称就是海贼王；zhHK 和 zhSG 就是英文，是 ONE PIECE；zhTW 就是繁体中文，是 航海王，可以只检索对应的简体中文，虽然偶尔也会有变动，但基本只是多一个字少一个字的变动，而且比较少，不会像现在这样会对应好几个
