### ISSUE TITLE
生成nfo 文件不下载海报照片 问题

### ISSUE THREAD

**Issue by FG3H** [jxxghp/nas-tools#3139]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.1
>
> 环境: Synology
>DSM7 套件版

## 你遇到什么问题了？

> 描述一下你遇到的问题
生成nfo 文件不下载海报照片问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
## 给出程序界面截图、后台运行日志或配置文件
![屏幕截图_20230125_002501](https://user-images.githubusercontent.com/104446934/214350694-87993e05-3a4c-43f5-8f7b-19a7e1e63e10.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
贴docker日志
