### ISSUE TITLE
nastools最新版的Bark不能用了啊，测试消息是可以发出来的，但是实际下载任务是不推送消息的

### ISSUE THREAD

**Issue by haohao232323** [jxxghp/nas-tools#314]
nastools最新版的Bark不能用了啊，测试消息是可以发出来的，但是实际下载任务是不推送消息的

**Comment by haohao232323** [comment]
![image](https://user-images.githubusercontent.com/42701714/174543186-dc221ba7-8f63-4082-8610-700e8a289f82.png)

**Comment by haohao232323** [comment]
![IMG_3428](https://user-images.githubusercontent.com/42701714/174546053-67ffb92d-54c8-4690-970a-dde8c5571525.PNG)
好像只有下载不推送消息，显示推送了，但是手机没接收到

**Comment by jxxghp** [comment]
微信和TG体验会好很多

**Comment by haohao232323** [comment]
谢谢回复，请问有没有计划支持非pt站点，类似于https://www.bt-tt.com/这样的
