### ISSUE TITLE
SynologyChat 消息机器人测试不通过

### ISSUE THREAD

**Issue by zhanghengtian** [jxxghp/nas-tools#3144]
## 你使用的 NAStool 是什么版本，什么环境？
> NAStool 版本: v2.7.6>
> 环境: Synology>

## 你遇到什么问题了？
> SynologyChat 消息机器人测试不通过，机器人已经按照提示创建传入webhook和配置相关的token.

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
> 是。

## 你期望的结果
> 希望可以在SynologyChat消息机器人测试通过

## 给出程序界面截图、后台运行日志或配置文件
> 如UI BUG请提供截图及配置文件截图
>
![image](https://user-images.githubusercontent.com/47552985/214495861-b1b57341-9827-4711-a324-dbd43dd1798f.png)

**Comment by netboy2008** [comment]
我的也测试不行，通过docker部署的，查看chat测试日志，是docker的桥接的内部地址172.17.0.5，设置发布地址为这个也不行，http https 加端口，不加端口都不行

**Comment by netboy2008** [comment]
Docker部署，docker 网络与群晖网络桥接 172.17.0.0/16，群晖地址：192.168.100.100 
nastool 版本：2.8.1
chat log:
60	admin	operation	User admin chatbot webhook incoming requested, id: 6, channel_id: 5, ip: 172.17.0.5	2023/1/25 20:08
59	admin	operation	User admin chatbot webhook incoming requested, id: 6, channel_id: 5, ip: 172.17.0.5	2023/1/25 20:08
58	admin	operation	User admin chatbot webhook incoming requested, id: 6, channel_id: 5, ip: 172.17.0.5	2023/1/25 20:08
57	admin	operation	User admin chatbot webhook incoming requested, id: 6, channel_id: 5, ip: 172.17.0.5	2023/1/25 20:08
56	admin	operation	User admin chatbot webhook outgoing excuted, id: 6, channel_id: 6, url: https://172.17.0.5:3000/synology	2023/1/25 20:08
55	admin	operation	User admin chatbot webhook incoming requested, id: 6, channel_id: 5, ip: 172.17.0.5	2023/1/25 20:08
54	admin	operation	User admin chatbot webhook incoming requested, id: 6, channel_id: 5, ip: 172.17.0.5	2023/1/25 20:08
53	admin	operation	User admin chatbot webhook outgoing excuted, id: 6, channel_id: 6, url: http://172.17.0.5:3000/synology	2023/1/25 20:08
52	admin	operation	User admin chatbot webhook incoming requested, id: 6, channel_id: 5, ip: 172.17.0.5	2023/1/25 20:08
51	admin	operation	User admin chatbot webhook incoming requested, id: 6, channel_id: 5, ip: 172.17.0.5	2023/1/25 20:08
50	admin	operation	User admin chatbot webhook incoming requested, id: 6, channel_id: 5, ip: 172.17.0.5	2023/1/25 20:08
49	admin	operation	User admin chatbot webhook incoming requested, id: 6, channel_id: 5, ip: 172.17.0.5	2023/1/25 20:08
48	admin	operation	User admin chatbot webhook incoming requested, id: 6, channel_id: 5, ip: 172.17.0.5	2023/1/25 20:08
47	admin	operation	User admin chatbot webhook outgoing excuted, id: 6, channel_id: 6, url: http://192.168.100.100:3000/synology	2023/1/25 20:08
46	admin	operation	User admin chatbot webhook outgoing excuted, id: 6, channel_id: 6, url: https://192.168.100.100:3000/synology	2023/1/25 20:08

nastool log:
20:13:50		synologychat 发送测试消息失败：407-record is not valid
20:13:51		synologychat 发送测试消息失败：407-record is not valid
20:14:18		synologychat 发送测试消息失败：407-record is not valid
20:14:19		synologychat 发送测试消息失败：407-record is not valid

**Comment by Gigasnow** [comment]
遇到了相同问题，我的chat日志里面没有outgoing executed，其他都差不多

**Comment by iamzhangzhang** [comment]
我能通过SynologyChat发送。但是无法接收。测试也是失败。提示：
<html>
<body>


10:15:48 | Message | synologychat 发送测试消息失败：机器人没有对任何用户可见
-- | -- | --



</body>
</html>

**Comment by yjdandwzd** [comment]
我也是一样的

**Comment by Lobeu-m** [comment]
> 我能通过SynologyChat发送。但是无法接收。测试也是失败。提示：
> 
> 10:15:48	Message	synologychat 发送测试消息失败：机器人没有对任何用户可见
在创建机器人时去掉第二个勾

**Comment by yjdandwzd** [comment]
> > 我能通过SynologyChat发送。但是无法接收。测试也是失败。提示：
> > 10:15:48	Message	synologychat 发送测试消息失败：机器人没有对任何用户可见
> > 在创建机器人时去掉第二个勾

去掉也是一样的，还是有问题。

**Comment by Lobeu-m** [comment]
> 

我试了一下，当nastool无法连接chat时也是显示“机器人没有对任何用户可见”

**Comment by xu-kevin** [comment]
我在容器里curl 测试过 nastool 到机器人是通的啊 ，不知道怎么回事 ，大佬们解决了吗

**Comment by lueshuai** [comment]
有没有大佬解决这个问题。。。

**Comment by lueshuai** [comment]
synologychat 发送测试消息失败：404-invalid token
