### ISSUE TITLE
希望刷流对于各站可以限制每次添加的种子个数

### ISSUE THREAD

**Issue by cjllin** [jxxghp/nas-tools#3151]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.8.1
>
> 环境: docker 
## 你想要新增或者改进什么功能？
希望刷流对于各站可以限制每次添加的种子个数，而不是根据下载器正在下载的个数限制是否添加。
这样会导致跑一个站就会跑满全部下载队列，其他站无法添加下载。
感谢大佬！

**Comment by jxxghp** [comment]
理论上，你的带宽和磁盘io是公共的，要上传就要限制全局的下载速度和磁盘读写。
你如果想去我先刷那个站点，你就把这个任务的值设大点就行
