### ISSUE TITLE
推荐菜单>Bangumi模块中点击资源返回“无法查询到TMDB信息”

### ISSUE THREAD

**Issue by xiaoxiaoxiaomo** [jxxghp/nas-tools#3158]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.1
>
> 环境: Synology
>

## 你遇到什么问题了？

> Bangumi模块中点击资源返回“无法查询到TMDB信息”；用搜索同样的资源是可以正常搜索返回TMDB内容的

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/29282134/214745174-c6492d0a-727d-4214-904a-fe14dfaf0dcb.png">

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/29282134/214749915-699c5d24-82c7-40e5-88f7-28514712deeb.png">

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by DDSDerek** [comment]
@xiaoxiaoxiaomo 具体版本号是多少，最新的版本号是`088f37d`，使用这个版本测试没有问题

**Comment by xiaoxiaoxiaomo** [comment]
升级到最新的088f37d版本这个问题就没有了、
