### ISSUE TITLE
多个豆瓣ID同步,只会同步第一个ID下的数据.

### ISSUE THREAD

**Issue by ztx0079** [jxxghp/nas-tools#316]
154483622,190037437,258052680,148972055

这四个豆瓣id,只会同步第一个154483622的列表,后面3个豆瓣id都同步不到.

但是如果换个顺序190037437,258052680,148972055,154483622
四个豆瓣id均可正常同步.

**Comment by jxxghp** [comment]
看下日志里有没有报错，估计跟帐号的特殊数据有关。

**Comment by ztx0079** [comment]
貌似是因为五十度灰和五十度飞两部电影因为无法访问的原因造成的?
这两部电影在豆瓣app上是能正常访问并添加进想看列表的.
11:47:25 ERROR - 【DOUBAN】网络连接失败：https://movie.douban.com/subject/26323032/
11:47:25 WARN - 【DOUBAN】访问该页面出现问题，媒体链接：https://movie.douban.com/subject/26323032/
11:47:28 ERROR - 【DOUBAN】网络连接失败：https://movie.douban.com/subject/24840488/
11:47:28 WARN - 【DOUBAN】访问该页面出现问题，媒体链接：https://movie.douban.com/subject/24840488/


下面是分别按照俩顺序的日志.

这是按照这个顺序190037437,258052680,148972055,154483622的日志

11:45:44 INFO - 【DOUBAN】开始同步豆瓣数据...
11:45:44 INFO - 【DOUBAN】开始获取 190037437 的 do 数据...
11:45:44 INFO - 【DOUBAN】开始获取 190037437 的 wish 数据...
11:45:47 INFO - 【DOUBAN】解析到媒体：Avengers: Age of Ultron
11:45:53 INFO - 【DOUBAN】解析到媒体：Avengers: Infinity War
11:45:57 INFO - 【DOUBAN】解析到媒体：复仇者联盟
11:46:02 INFO - 【DOUBAN】解析到媒体：Avengers: Endgame
11:46:02 INFO - 【DOUBAN】开始获取 190037437 的 collect 数据...
11:46:03 INFO - 【DOUBAN】用户 190037437 解析完成，共获取到 4 个媒体
11:46:03 INFO - 【DOUBAN】开始获取 258052680 的 do 数据...
11:46:03 INFO - 【DOUBAN】开始获取 258052680 的 wish 数据...
11:46:07 INFO - 【DOUBAN】解析到媒体：疯神
11:46:09 INFO - 【DOUBAN】解析到媒体：Avatar: The Seed Bearer
11:46:14 INFO - 【DOUBAN】解析到媒体：铃芽户缔
11:46:19 INFO - 【DOUBAN】解析到媒体：闪电侠
11:46:22 INFO - 【DOUBAN】解析到媒体：Black Panther: Wakanda Forever
11:46:28 INFO - 【DOUBAN】解析到媒体：Guardians of the Galaxy Vol 3
11:46:34 INFO - 【DOUBAN】解析到媒体：Avatar: The Way of Water
11:46:38 INFO - 【DOUBAN】解析到媒体：Thor: Love and Thunder
11:46:38 INFO - 【DOUBAN】开始获取 258052680 的 collect 数据...
11:46:39 INFO - 【DOUBAN】用户 258052680 解析完成，共获取到 8 个媒体
11:46:39 INFO - 【DOUBAN】开始获取 148972055 的 do 数据...
11:46:39 INFO - 【DOUBAN】开始获取 148972055 的 wish 数据...
11:46:44 INFO - 【DOUBAN】解析到媒体：궁중잔혹사 꽃들의 전쟁
11:46:48 INFO - 【DOUBAN】解析到媒体：他是龙
11:46:52 INFO - 【DOUBAN】解析到媒体：我的解放日志
11:46:52 INFO - 【DOUBAN】开始获取 148972055 的 collect 数据...
11:46:52 INFO - 【DOUBAN】用户 148972055 解析完成，共获取到 3 个媒体
11:46:52 INFO - 【DOUBAN】开始获取 154483622 的 do 数据...
11:46:53 INFO - 【DOUBAN】开始获取 154483622 的 wish 数据...
11:46:56 INFO - 【DOUBAN】解析到媒体：Doctor Strange in the Multiverse of Madness
11:46:59 INFO - 【DOUBAN】解析到媒体：紫罗兰永恒花园
11:47:04 INFO - 【DOUBAN】解析到媒体：派对浪客诸葛孔明
11:47:08 INFO - 【DOUBAN】解析到媒体：夏日重现
11:47:12 INFO - 【DOUBAN】解析到媒体：古见同学有交流障碍症
11:47:16 INFO - 【DOUBAN】解析到媒体：目中无人
11:47:21 INFO - 【DOUBAN】解析到媒体：五十度黑
11:47:25 ERROR - 【DOUBAN】网络连接失败：https://movie.douban.com/subject/26323032/
11:47:25 WARN - 【DOUBAN】访问该页面出现问题，媒体链接：https://movie.douban.com/subject/26323032/
11:47:28 ERROR - 【DOUBAN】网络连接失败：https://movie.douban.com/subject/24840488/
11:47:28 WARN - 【DOUBAN】访问该页面出现问题，媒体链接：https://movie.douban.com/subject/24840488/
11:47:33 INFO - 【DOUBAN】解析到媒体：北欧人
11:47:38 INFO - 【DOUBAN】解析到媒体：小人物
11:47:42 INFO - 【DOUBAN】解析到媒体：月光骑士
11:47:46 INFO - 【DOUBAN】解析到媒体：Dota: Dragon's Blood
11:47:50 INFO - 【DOUBAN】解析到媒体：Dota: Dragon's Blood
11:47:54 INFO - 【DOUBAN】解析到媒体：风起陇西
11:47:57 INFO - 【DOUBAN】解析到媒体：欢迎光临
11:48:01 INFO - 【DOUBAN】解析到媒体：梦华录
11:48:04 INFO - 【DOUBAN】解析到媒体：警察荣誉
11:48:04 INFO - 【DOUBAN】开始获取 154483622 的 collect 数据...
11:48:04 INFO - 【DOUBAN】用户 154483622 解析完成，共获取到 16 个媒体
11:48:04 INFO - 【DOUBAN】所有用户解析完成，共获取到 31 个媒体
11:48:04 INFO - 【DOUBAN】开始检索豆瓣中的影视资源...
11:48:04 WARN - 【DOUBAN】疯神 未查询到媒体信息
11:48:04 WARN - 【DOUBAN】Avatar: The Seed Bearer 未查询到媒体信息
11:48:04 WARN - 【DOUBAN】궁중잔혹사 꽃들의 전쟁 未查询到媒体信息
11:48:04 INFO - 【DOUBAN】豆瓣数据同步完成






这是按照这个顺序154483622,190037437,258052680,148972055的日志

11:49:41 INFO - 【DOUBAN】开始同步豆瓣数据...
11:49:41 INFO - 【DOUBAN】开始获取 154483622 的 do 数据...
11:49:41 INFO - 【DOUBAN】开始获取 154483622 的 wish 数据...
11:49:46 INFO - 【DOUBAN】解析到媒体：Doctor Strange in the Multiverse of Madness
11:49:52 INFO - 【DOUBAN】解析到媒体：紫罗兰永恒花园
11:49:56 INFO - 【DOUBAN】解析到媒体：派对浪客诸葛孔明
11:50:00 INFO - 【DOUBAN】解析到媒体：夏日重现
11:50:05 INFO - 【DOUBAN】解析到媒体：古见同学有交流障碍症
11:50:08 INFO - 【DOUBAN】解析到媒体：目中无人
11:50:16 INFO - 【DOUBAN】解析到媒体：五十度黑
11:50:20 ERROR - 【DOUBAN】网络连接失败：https://movie.douban.com/subject/26323032/
11:50:20 WARN - 【DOUBAN】访问该页面出现问题，媒体链接：https://movie.douban.com/subject/26323032/
11:50:22 ERROR - 【DOUBAN】网络连接失败：https://movie.douban.com/subject/24840488/
11:50:23 WARN - 【DOUBAN】访问该页面出现问题，媒体链接：https://movie.douban.com/subject/24840488/
11:50:25 INFO - 【DOUBAN】解析到媒体：北欧人
11:50:30 INFO - 【DOUBAN】解析到媒体：小人物
11:50:32 INFO - 【DOUBAN】解析到媒体：月光骑士
11:50:36 INFO - 【DOUBAN】解析到媒体：Dota: Dragon's Blood
11:50:41 INFO - 【DOUBAN】解析到媒体：Dota: Dragon's Blood
11:50:46 INFO - 【DOUBAN】解析到媒体：风起陇西
11:50:51 INFO - 【DOUBAN】解析到媒体：欢迎光临
11:50:54 INFO - 【DOUBAN】解析到媒体：梦华录
11:50:57 INFO - 【DOUBAN】解析到媒体：警察荣誉
11:50:57 INFO - 【DOUBAN】开始获取 154483622 的 collect 数据...
11:50:57 INFO - 【DOUBAN】用户 154483622 解析完成，共获取到 16 个媒体
11:50:57 INFO - 【DOUBAN】开始获取 190037437 的 do 数据...
11:50:58 INFO - 【DOUBAN】开始获取 190037437 的 wish 数据...
11:50:58 INFO - 【DOUBAN】开始获取 190037437 的 collect 数据...
11:50:59 INFO - 【DOUBAN】用户 190037437 解析完成，共获取到 0 个媒体
11:50:59 INFO - 【DOUBAN】开始获取 258052680 的 do 数据...
11:50:59 INFO - 【DOUBAN】开始获取 258052680 的 wish 数据...
11:50:59 INFO - 【DOUBAN】开始获取 258052680 的 collect 数据...
11:51:00 INFO - 【DOUBAN】用户 258052680 解析完成，共获取到 0 个媒体
11:51:00 INFO - 【DOUBAN】开始获取 148972055 的 do 数据...
11:51:00 INFO - 【DOUBAN】开始获取 148972055 的 wish 数据...
11:51:00 INFO - 【DOUBAN】开始获取 148972055 的 collect 数据...
11:51:01 INFO - 【DOUBAN】用户 148972055 解析完成，共获取到 0 个媒体
11:51:01 INFO - 【DOUBAN】所有用户解析完成，共获取到 16 个媒体
11:51:01 INFO - 【DOUBAN】开始检索豆瓣中的影视资源...
11:51:01 INFO - 【DOUBAN】豆瓣数据同步完成

**Comment by jxxghp** [comment]
这两个页面确实点不进去，那应该是这个问题我兼容下

**Comment by xxzj990** [comment]
豆瓣的很多电影电视（儿童不宜的），必须登录账号才能看到页面～

**Comment by jxxghp** [comment]
提交了，试下

**Comment by ztx0079** [comment]
> 

1.6.5 问题没有解决. 

2022-06-21 13:11:05,670	INFO: 【DOUBAN】开始同步豆瓣数据...
2022-06-21 13:11:05,671	INFO: 【DOUBAN】开始获取 154483622 的 do 数据...
2022-06-21 13:11:06,099	INFO: 【DOUBAN】开始获取 154483622 的 wish 数据...
2022-06-21 13:11:13,489	INFO: 【DOUBAN】解析到媒体：不会拿捏距离的阿波连同学
2022-06-21 13:11:16,301	INFO: 【DOUBAN】解析到媒体：间谍过家家
2022-06-21 13:11:20,763	INFO: 【DOUBAN】解析到媒体：Doctor Strange in the Multiverse of Madness
2022-06-21 13:11:22,949	INFO: 【DOUBAN】解析到媒体：紫罗兰永恒花园
2022-06-21 13:11:26,377	INFO: 【DOUBAN】解析到媒体：派对浪客诸葛孔明
2022-06-21 13:11:31,137	INFO: 【DOUBAN】解析到媒体：夏日重现
2022-06-21 13:11:36,448	INFO: 【DOUBAN】解析到媒体：古见同学有交流障碍症
2022-06-21 13:11:38,862	INFO: 【DOUBAN】解析到媒体：目中无人
2022-06-21 13:11:43,193	INFO: 【DOUBAN】解析到媒体：五十度黑
2022-06-21 13:11:48,541	ERROR: 【DOUBAN】打开页面失败：https://movie.douban.com/subject/26323032/
2022-06-21 13:11:52,691	ERROR: 【DOUBAN】打开页面失败：https://movie.douban.com/subject/24840488/
2022-06-21 13:11:56,636	INFO: 【DOUBAN】解析到媒体：北欧人
2022-06-21 13:11:59,588	INFO: 【DOUBAN】解析到媒体：小人物
2022-06-21 13:12:04,711	INFO: 【DOUBAN】解析到媒体：月光骑士
2022-06-21 13:12:08,026	INFO: 【DOUBAN】解析到媒体：Dota: Dragon's Blood
2022-06-21 13:12:15,974	INFO: 【DOUBAN】解析到媒体：Dota: Dragon's Blood
2022-06-21 13:12:21,535	INFO: 【DOUBAN】解析到媒体：风起陇西
2022-06-21 13:12:27,387	INFO: 【DOUBAN】解析到媒体：欢迎光临
2022-06-21 13:12:33,561	INFO: 【DOUBAN】解析到媒体：梦华录
2022-06-21 13:12:35,903	INFO: 【DOUBAN】解析到媒体：警察荣誉
2022-06-21 13:12:35,904	INFO: 【DOUBAN】开始获取 154483622 的 collect 数据...
2022-06-21 13:12:36,299	INFO: 【DOUBAN】用户 154483622 解析完成，共获取到 18 个媒体
2022-06-21 13:12:36,300	INFO: 【DOUBAN】开始获取 190037437 的 do 数据...
2022-06-21 13:12:37,190	INFO: 【DOUBAN】开始获取 190037437 的 wish 数据...
2022-06-21 13:12:37,497	INFO: 【DOUBAN】开始获取 190037437 的 collect 数据...
2022-06-21 13:12:38,391	INFO: 【DOUBAN】用户 190037437 解析完成，共获取到 0 个媒体
2022-06-21 13:12:38,392	INFO: 【DOUBAN】开始获取 258052680 的 do 数据...
2022-06-21 13:12:38,914	INFO: 【DOUBAN】开始获取 258052680 的 wish 数据...
2022-06-21 13:12:40,391	INFO: 【DOUBAN】开始获取 258052680 的 collect 数据...
2022-06-21 13:12:40,795	INFO: 【DOUBAN】用户 258052680 解析完成，共获取到 0 个媒体
2022-06-21 13:12:40,796	INFO: 【DOUBAN】开始获取 148972055 的 do 数据...
2022-06-21 13:12:41,601	INFO: 【DOUBAN】开始获取 148972055 的 wish 数据...
2022-06-21 13:12:42,202	INFO: 【DOUBAN】开始获取 148972055 的 collect 数据...
2022-06-21 13:12:42,679	INFO: 【DOUBAN】用户 148972055 解析完成，共获取到 0 个媒体
2022-06-21 13:12:42,679	INFO: 【DOUBAN】所有用户解析完成，共获取到 18 个媒体

**Comment by ztx0079** [comment]
> 

建议先将所有ID的列表同步后,再去重,再进行媒体解析,这样应该能解决问题,并且提升一点点效率

**Comment by jxxghp** [comment]
这块是别人pr的，等有空的时候系统性改下

**Comment by ztx0079** [comment]
尝试在config配置了豆瓣的cookie, 五十度灰和五十度飞能正常解析了,但是问题依旧.

15:33:50 INFO - 【DOUBAN】开始同步豆瓣数据...
15:33:50 INFO - 【DOUBAN】开始获取 154483622 的 do 数据...
15:33:51 INFO - 【DOUBAN】开始获取 154483622 的 wish 数据...
15:33:54 INFO - 【DOUBAN】解析到媒体：我的解放日志
15:33:59 INFO - 【DOUBAN】解析到媒体：不会拿捏距离的阿波连同学
15:34:04 INFO - 【DOUBAN】解析到媒体：间谍过家家
15:34:08 INFO - 【DOUBAN】解析到媒体：Doctor Strange in the Multiverse of Madness
15:34:11 INFO - 【DOUBAN】解析到媒体：紫罗兰永恒花园
15:34:14 INFO - 【DOUBAN】解析到媒体：派对浪客诸葛孔明
15:34:20 INFO - 【DOUBAN】解析到媒体：夏日重现
15:34:25 INFO - 【DOUBAN】解析到媒体：古见同学有交流障碍症
15:34:29 INFO - 【DOUBAN】解析到媒体：目中无人
15:34:32 INFO - 【DOUBAN】解析到媒体：五十度黑
15:34:38 INFO - 【DOUBAN】解析到媒体：五十度飞
15:34:42 INFO - 【DOUBAN】解析到媒体：五十度灰
15:34:45 INFO - 【DOUBAN】解析到媒体：北欧人
15:34:54 INFO - 【DOUBAN】解析到媒体：小人物
15:35:00 INFO - 【DOUBAN】解析到媒体：月光骑士
15:35:07 INFO - 【DOUBAN】解析到媒体：Dota: Dragon's Blood
15:35:12 INFO - 【DOUBAN】解析到媒体：Dota: Dragon's Blood
15:35:16 INFO - 【DOUBAN】解析到媒体：风起陇西
15:35:20 INFO - 【DOUBAN】解析到媒体：欢迎光临
15:35:25 INFO - 【DOUBAN】解析到媒体：梦华录
15:35:31 INFO - 【DOUBAN】解析到媒体：警察荣誉
15:35:31 INFO - 【DOUBAN】开始获取 154483622 的 collect 数据...
15:35:31 INFO - 【DOUBAN】用户 154483622 解析完成，共获取到 21 个媒体
15:35:31 INFO - 【DOUBAN】开始获取 190037437 的 do 数据...
15:35:31 INFO - 【DOUBAN】开始获取 190037437 的 wish 数据...
15:35:32 INFO - 【DOUBAN】开始获取 190037437 的 collect 数据...
15:35:32 INFO - 【DOUBAN】用户 190037437 解析完成，共获取到 0 个媒体
15:35:32 INFO - 【DOUBAN】开始获取 258052680 的 do 数据...
15:35:32 INFO - 【DOUBAN】开始获取 258052680 的 wish 数据...
15:35:33 INFO - 【DOUBAN】开始获取 258052680 的 collect 数据...
15:35:33 INFO - 【DOUBAN】用户 258052680 解析完成，共获取到 0 个媒体
15:35:33 INFO - 【DOUBAN】开始获取 148972055 的 do 数据...
15:35:33 INFO - 【DOUBAN】开始获取 148972055 的 wish 数据...
15:35:34 INFO - 【DOUBAN】开始获取 148972055 的 collect 数据...
15:35:34 INFO - 【DOUBAN】用户 148972055 解析完成，共获取到 0 个媒体
15:35:34 INFO - 【DOUBAN】所有用户解析完成，共获取到 21 个媒体
15:35:34 INFO - 【DOUBAN】开始检索豆瓣中的影视资源...
15:35:34 INFO - 【DOUBAN】豆瓣数据同步完成

**Comment by jxxghp** [comment]
这个模块的代码重写了
