### ISSUE TITLE
nastool 添加下載失敗

### ISSUE THREAD

**Issue by andyson222** [jxxghp/nas-tools#3160]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.6
>qb版本：v 4.5
> 环境: synology DSM 7.1.1
>

## 你遇到什么问题了？

> 用nastool搜尋影片後，點擊下載後提示"添加下載失敗，請檢查下載任務是否已存在﹗"

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 沒有找到對應的解決方法

## 你期望的结果

> 能正常使用QB下載

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 
<img width="618" alt="螢幕截圖 2023-01-26 上午10 37 10" src="https://user-images.githubusercontent.com/123399693/214773512-810696c7-4a61-4490-b3bd-e77c85bde8dc.png">

<img width="1136" alt="螢幕截圖 2023-01-26 下午2 43 38" src="https://user-images.githubusercontent.com/123399693/214773548-14264671-413d-4e3f-b84f-c204519486cc.png">

**Comment by jxxghp** [comment]
链接直接添加到qb能下载吗？
重启nastool和qb了吗？

**Comment by andyson222** [comment]
> 链接直接添加到qb能下载吗？
> 重启nastool和qb了吗？

把連接复制出來貼在迅雷、bitcomet、QB都可以下載，但就是nastool報錯

**Comment by andyson222** [comment]
> > 链接直接添加到qb能下载吗？
> > 重启nastool和qb了吗？
> 
> 把連接复制出來貼在迅雷、bitcomet、QB都可以下載，但就是nastool報錯

<img width="606" alt="螢幕截圖 2023-01-27 上午8 53 01" src="https://user-images.githubusercontent.com/123399693/214983083-ac9818a4-9d0e-44da-a456-059c437bee21.png">
上圖是NASTOOL報的錯

下圖是在日志里复制出連結後，手動貼上在QB下載
<img width="897" alt="螢幕截圖 2023-01-27 上午8 53 19" src="https://user-images.githubusercontent.com/123399693/214983095-0e079171-ecf1-425f-811d-b4c6a87e0a12.png">

**Comment by andyson222** [comment]
解決了，你提醒了我，QB下載沒問題就應該是nastool出問題，回到nastool里把下載器測試了一下失敗了，然後想起我把QB的名稱密碼改過，修正一下後重啟nastool就可以了，感謝提醒。

**Comment by tkpdx01** [comment]
> 解決了，你提醒了我，QB下載沒問題就應該是nastool出問題，回到nastool里把下載器測試了一下失敗了，然後想起我把QB的名稱密碼改過，修正一下後重啟nastool就可以了，感謝提醒。

我的问题和你一样，终于解决了，nastools里qb不通了。。。

**Comment by tkpdx01** [comment]
> 链接直接添加到qb能下载吗？ 重启nastool和qb了吗？

大佬可以考虑把错误提示细化一下嘿嘿😀
