### ISSUE TITLE
EMBY套件版无法连接

### ISSUE THREAD

**Issue by yiwangdexingkong** [jxxghp/nas-tools#3166]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.1
>
> 环境: docker  Synology
>

## 你遇到什么问题了？

> nas-tools无妨访问套件EMBY，docker emby访问正常

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> Issues列表看到去年8月有人看到过该问题，但是没看到作者回复。

## 你期望的结果

>麻烦修复下BUG

## 给出程序界面截图、后台运行日志或配置文件

![微信图片_20230127015426](https://user-images.githubusercontent.com/99598637/214912002-b8cc69c1-2628-4f67-95da-f7bf0c83b1b3.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
正常，检查自己的环境和emby版本。
而且你也没有给任何关键信息，如果emby连不了，早大规模反馈问题了，先确定不是自已一个人的问题再提吧。
