### ISSUE TITLE
prowlarr测试成功后搜索无结果显示没有有效的索引器配置_回来了，重提

### ISSUE THREAD

**Issue by fsxyhjgsrfz** [jxxghp/nas-tools#3167]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.1
>
> 环境: docker or windows or Synology
>
docker
asustor as5304t
## 你遇到什么问题了？

> 描述一下你遇到的问题
![屏幕截图 2023-01-27 034502](https://user-images.githubusercontent.com/122225422/214934975-5d6ecbe1-d60b-4733-aeaa-7a56fe9b5639.png)
![屏幕截图 2023-01-27 034653](https://user-images.githubusercontent.com/122225422/214935496-1d8be430-b98c-4f01-89b2-223f8600d075.png)
![image](https://user-images.githubusercontent.com/122225422/214935572-964ec1da-0ecf-49b6-9ee5-ecbe38f37cf4.png)
索引器使用prowlarr，测试成功后，搜索任何内容都是无结果，日志显示没有有效的索引器配置。prowlarr已经配置索引器并可以使用。
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
[prowlarr测试成功后搜索无结果显示没有有效的索引器配置](https://github.com/jxxghp/nas-tools/issues/2924#top)
#2924
@jxxghp jxxghp closed this as not planned Won't fix, can't repro, duplicate, stale2 weeks ago

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
{self.host}api/v1/indexerstats?apikey={self.api_key}
替换为prowlarr的IP和api之后
{
  "indexers": [
    {
      "indexerId": 8,
      "indexerName": "Rarbg",
      "averageResponseTime": 1754,
      "numberOfQueries": 4,
      "numberOfGrabs": 0,
      "numberOfRssQueries": 0,
      "numberOfAuthQueries": 0,
      "numberOfFailedQueries": 0,
      "numberOfFailedGrabs": 0,
      "numberOfFailedRssQueries": 0,
      "numberOfFailedAuthQueries": 0
    },
    {
      "indexerId": 2,
      "indexerName": "MioBT",
      "averageResponseTime": 3732,
      "numberOfQueries": 4,
      "numberOfGrabs": 0,
      "numberOfRssQueries": 0,
      "numberOfAuthQueries": 0,
      "numberOfFailedQueries": 0,
      "numberOfFailedGrabs": 0,
      "numberOfFailedRssQueries": 0,
      "numberOfFailedAuthQueries": 0
    },
    {
      "indexerId": 5,
      "indexerName": "dmhy",
      "averageResponseTime": 4746,
      "numberOfQueries": 3,
      "numberOfGrabs": 0,
      "numberOfRssQueries": 0,
      "numberOfAuthQueries": 0,
      "numberOfFailedQueries": 0,
      "numberOfFailedGrabs": 0,
      "numberOfFailedRssQueries": 0,
      "numberOfFailedAuthQueries": 0
    },
    {
      "indexerId": 7,
      "indexerName": "Nyaa.si",
      "averageResponseTime": 1706,
      "numberOfQueries": 8,
      "numberOfGrabs": 0,
      "numberOfRssQueries": 0,
      "numberOfAuthQueries": 0,
      "numberOfFailedQueries": 0,
      "numberOfFailedGrabs": 0,
      "numberOfFailedRssQueries": 0,
      "numberOfFailedAuthQueries": 0
    },
    {
      "indexerId": 1,
      "indexerName": "Mikan",
      "averageResponseTime": 3220,
      "numberOfQueries": 5,
      "numberOfGrabs": 0,
      "numberOfRssQueries": 0,
      "numberOfAuthQueries": 0,
      "numberOfFailedQueries": 0,
      "numberOfFailedGrabs": 0,
      "numberOfFailedRssQueries": 0,
      "numberOfFailedAuthQueries": 0
    },
    {
      "indexerId": 10,
      "indexerName": "The Pirate Bay",
      "averageResponseTime": 928,
      "numberOfQueries": 2,
      "numberOfGrabs": 0,
      "numberOfRssQueries": 0,
      "numberOfAuthQueries": 0,
      "numberOfFailedQueries": 0,
      "numberOfFailedGrabs": 0,
      "numberOfFailedRssQueries": 0,
      "numberOfFailedAuthQueries": 0
    }
  ],
  "userAgents": [
    {
      "userAgent": "Prowlarr",
      "numberOfQueries": 26,
      "numberOfGrabs": 0
    }
  ],
  "hosts": [
    {
      "host": "LAPTOP-GFIPNOEN",
      "numberOfQueries": 26,
      "numberOfGrabs": 0
    }
  ]
}

**Comment by luxy25** [comment]
我也出现了这个错误
