### ISSUE TITLE
订阅问题

### ISSUE THREAD

**Issue by vctory-xia** [jxxghp/nas-tools#317]
是否可以给每一个订阅单独的弄一套过滤规则呢
比如剧集订阅我只想收同一组的 或者 这个订阅我只想收2160 另一个订阅想收1080 
现在的优先规则好像满足不了类似这种需求。

**Comment by log-time** [comment]
目前其实是满足的，剧集支持站点过滤，站点支持编码、压制组的过滤

**Comment by vctory-xia** [comment]
站点过滤里的规则应该针对的是该站点的所有订阅吧 假设我这个站点有两个剧集订阅， 一个我想要1080 一个我想要2160这样能精确过滤吗 感觉貌似用或的关系敲正则也能解决，但是这样感觉没有单独一个订阅可以设定单独过滤规则来的方便。 而且这样应该就需要加入剧集名分辨率组名来进行过滤吧

**Comment by jxxghp** [comment]
https://github.com/jxxghp/nas-tools/issues/343#issue-1279499581
