### ISSUE TITLE
服务-rss订阅执行时,从站点获取的数据不是rss订阅的内容

### ISSUE THREAD

**Issue by charlesSheep** [jxxghp/nas-tools#3173]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.1
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
在 '服务' 选项中,手动执行'rss订阅'任务,在站点存在符合条件的剧集更新的情况下,没有订阅到相关内容；
手动执行'订阅搜索' 则可以正常更新剧集。
手动点击相关订阅的'刷新',也可以正常更新。

查看日志发现，rss订阅任务执行时，从站点获取的内容与rss订阅清单的内容不符。
不确定是否是我rss订阅地址的设置问题;还是rss订阅任务执行时,没有带上关键字

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
已浏览过issues列表,查找过相关问题,没有找到解决方法

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
能正常更新订阅剧集

## 给出程序界面截图、后台运行日志或配置文件
<img width="713" alt="截屏2023-01-27 17 33 47" src="https://user-images.githubusercontent.com/49314251/215057639-a4d5da30-7976-44a9-98c4-a4a2d88a8c2d.png">
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
<img width="847" alt="截屏2023-01-27 17 56 52" src="https://user-images.githubusercontent.com/49314251/215059090-938a5387-207c-4107-b062-d6f5e521c2ac.png">

**Comment by Shurelol** [comment]
rss获取的内容，就是你在站点维护里填得订阅链接里的，如果有符合订阅内容的就下载
