### ISSUE TITLE
EZTV 在解析时文件显示不全

### ISSUE THREAD

**Issue by Jie2GG** [jxxghp/nas-tools#3183]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.1 3f067ee
>
> 环境: docker or debain
>

## 你遇到什么问题了？

> 搜索资源 **The Magical Revolution of the Reincarnated Princess and the Genius Young Lady** 时, 由于EZTV的搜索结果中 a 标签的文本没有完全显示文件名, 可能导致 NAStool 无法正确识别 "季" 或 "集".

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 已搜索过 issues 列表, 没有相关问题提出

## 你期望的结果

> 建议使用 a 标签下的 title 属性, 这里有完整正确的文件名

## 给出程序界面截图、后台运行日志或配置文件

> NAStool的资源搜索结果
> ![image](https://user-images.githubusercontent.com/39112172/215105536-959171ce-274d-414a-81ff-6f77afb2a287.png)
>
> EZTV站点的搜索结果
> 地址: https://eztv.re/search/the-magical-revolution-of-the-reincarnated-princess-and-the-genius-young-lady
> ![image](https://user-images.githubusercontent.com/39112172/215105710-6b11263e-c884-4168-8b44-4aebf33795d7.png)
>
> EZTV站点的DOM文档结构
> **标红的部分为完整文件名**
> ![image](https://user-images.githubusercontent.com/39112172/215106063-9a0b5f57-cd9f-4b85-9dbf-de64767f8569.png)

**Comment by jxxghp** [comment]
这样提问题，效率就高多了。
