### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by CBEpt** [jxxghp/nas-tools#3184]
## 你使用的 NAStool 是什么版本，什么环境？
> NAStool 版本: v2.8.1
> 环境: win10
## 你遇到什么问题了？
windows exe安装失败
遇到问题之前的骚操作：
按照wiki文档的[本地运行](https://github.com/jxxghp/nas-tools#2本地运行)
执行了
```
git clone -b master https://github.com/jxxghp/nas-tools --recurse-submodule 
python3 -m pip install -r requirements.txt
```
跑完才发现是给linux用的。。然后现在windows版本安装不上了, 双击exe文件，无法正常安装。。。重启也没用。。
具体错误提示如图
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
> 已在issue/wiki搜索“失败”
## 你期望的结果
> 正常安装。。
## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/103420806/215115103-90e6899b-2db8-476a-8084-206025670daf.png)

**Comment by k2y1982** [comment]
我也安装不了，同样的提示，不过我之前有安装了mysql 8.0
