### ISSUE TITLE
站点资源栏不显示海胆之家的资源

### ISSUE THREAD

**Issue by linqinpeng910927** [jxxghp/nas-tools#3190]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.81
>
> 环境: docker
>

## 你遇到什么问题了？

> https://www.haidan.video/
该网站添加站点后，在“站点管理—站点资源”里无显示，导致nastools默认的索引器没法搜索该站点。jackett索引器可以用

**Comment by XueqiangChen** [comment]
同问

**Comment by jxxghp** [comment]
海胆页面改动太大，无法支持索引。
