### ISSUE TITLE
种子数据下载成功率低

### ISSUE THREAD

**Issue by unhoo28** [jxxghp/nas-tools#320]
更新到最新版本后，磁力链接下载种子数据成功率极低，而且电视剧订阅会在种子下载失败后自动删除订阅
![2022-06-19 20 58 44](https://user-images.githubusercontent.com/14275413/174482210-6b93d004-0e69-41f5-ae31-79e71707b37f.jpg)

**Comment by jasonding121205** [comment]
我也是这问题

**Comment by jxxghp** [comment]
这种磁力链的种子是怎么来的，也是PT站的吗？

**Comment by unhoo28** [comment]
> 

jackett搜索到的

**Comment by unhoo28** [comment]
> 这种磁力链的种子是怎么来的，也是PT站的吗？

jackett搜索到的

**Comment by jxxghp** [comment]
没想到PT还有磁力链的，明天修复

**Comment by jxxghp** [comment]
修复了，试试

**Comment by unhoo28** [comment]
> 修复了，试试

大佬效率真高，下个版本试试看
