### ISSUE TITLE
支持忽略小版本更新

### ISSUE THREAD

**Issue by amtoaer** [jxxghp/nas-tools#3203]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

看了下更新逻辑，目前是加上了 commit hash 的比较，本地和仓库的版本号相同但 hash 不同也会提示更新。但这样可能会有两个问题：
1. 分支变动较为频繁，用户经常被更新红点打扰；
2. master 分支的最新提交未经过较完善的测试，直接使用有较大风险。

一般用户（比如我）不是很需要这种“实时跟进开发进度”的激进更新方式，只想要发新 release 后再更新。希望能够提供一个忽略小版本更新的开关，开启后走旧的更新逻辑，仅检查版本号。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

旧版本 NAStool 的更新逻辑。

**Comment by ReddotCleaner** [comment]
同样受到该问题困扰
