### ISSUE TITLE
新增了自定站点的电视剧订阅，无法删除

### ISSUE THREAD

**Issue by Otiguy** [jxxghp/nas-tools#3204]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: V2.8.2 9881e1a
>
> 环境: Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
>
1、通过站点管理添加了mikan的某番rss 作为特定站点，测试站点通过：
![Snipaste_2023-01-29_01-26-28](https://user-images.githubusercontent.com/48633984/215281252-29a95726-0a52-40de-bf24-d93b3f9f382e.png)
2、然后在电视剧订阅新增该站点的番剧订阅，发现不像推荐那些订阅有封面图，也没有点击弹出可以取消这个订阅。（是因为没写上tmdb？）
![Snipaste_2023-01-29_01-28-37](https://user-images.githubusercontent.com/48633984/215281807-ebe8b784-2377-49e6-bccd-e303dc094d1d.png)

从日志看，点击后会搜索“0”：
![Snipaste_2023-01-29_01-29-38](https://user-images.githubusercontent.com/48633984/215281861-bc8b210b-d14f-458d-a69b-a9eedc791d1c.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
>
wiki看不了，搜索过issues

## 你期望的结果

> 描述以下你期望的结果
>
现在只是删不了，不知道会有什么影响，会不会后续刮到更新后会进行下载，期望可以有UI交互可以删了这个订阅
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by luyufan498** [comment]
我也是，使用模糊匹配就会这样，删也shanbudiao1

**Comment by syyee** [comment]
同样出现删不了出错订阅的bug。豆瓣想看了明星大侦探第八季，然后订阅里在电影里出现了一个“大侦探 （2023）”，（应该是识别错误，可我也没开模糊匹配豆瓣辅助啥的）。想删除，点击无反应（没有正常的弹出窗），每点一次，日志只写：

正在通过API查询豆瓣详情：36166189
36166189 未找到豆瓣详细信息

**Comment by Shurelol** [comment]
豆瓣上，没有明星大侦探 第八季

只有大侦探 第八季

已经改名了

**Comment by syyee** [comment]
。。。要是没改名也不会出bug啊。问题是删不掉
