### ISSUE TITLE
无NAStool标签的下载也被管理

### ISSUE THREAD

**Issue by PoiYuudachi** [jxxghp/nas-tools#3206]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v2.8.2 9881e1a
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 描述一下你遇到的问题
我直接在qbittorrent里添加的下载也被nastool管理了，没有nastool的标签且只管理nastool添加的下载选项已打勾
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![9Z$KTDY6UN}@3LHH8GZQD)V](https://user-images.githubusercontent.com/41389186/215285695-feea6f47-1807-4f21-a6e7-1b2a693ef36d.png)
![M4@%CY_RPB2JF6X5YY6I CS](https://user-images.githubusercontent.com/41389186/215285698-cb997630-c698-41cd-a903-2cded2eb19dd.png)
![210M$5YURMBVGG455X5$AAV](https://user-images.githubusercontent.com/41389186/215285699-32eeca3c-0593-4adf-ad9b-ded26c8195bf.png)

**Comment by diao597576613** [comment]
同样遇到了

**Comment by jxxghp** [comment]
检查QB版本是否支持打标签

**Comment by diao597576613** [comment]
> 检查QB版本是否支持打标签

肯定支持啊，4.5.0之前一直好好的好像就升级2.8.1之后出现的问题
