### ISSUE TITLE
群晖套件中心搜不到nastool

### ISSUE THREAD

**Issue by uubyron** [jxxghp/nas-tools#3208]
## 你使用的 NAStool 是什么版本，什么环境？

Nastool 更新一直loading 
刷新网页后无法登录，卸载软件重新安装 下载进度一直为0
之后提示Nastool套件丢失
现在套件中心搜索不到nastool套件
>
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

![image](https://user-images.githubusercontent.com/44697007/215301610-7f5dd62d-4f04-4e6c-be06-8ecac48e2403.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by uubyron** [comment]
目前可以搜到了 但是下载速度极慢 不走进度 一直0%

**Comment by jxxghp** [comment]
套件跟本项目无关，无法解答。
