### ISSUE TITLE
大佬 能增加一个定时推送日志或者使用情况的功能吗

### ISSUE THREAD

**Issue by hzj8023** [jxxghp/nas-tools#3209]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.2
>
> 环境: synology

## 定时推送日志或者使用情况的功能

> 比如每日有谁播放了什么视频，下载了什么视频，统计后推送到微信上去，

##就是我的媒体库页面那些日志推送到微信就爽了

>

**Comment by jxxghp** [comment]
有emby/jellyfin/plex的webhook通知接口啊，你仔细看下项目页说明。
