### ISSUE TITLE
设置中 “转移最小文件大小” 过滤掉的文件是如何处理的？

### ISSUE THREAD

**Issue by Ton-yi** [jxxghp/nas-tools#3210]
我想了解一下这里小于150mb的文件是会“复制”到目标文件夹吗？还是什么都不做直接忽略掉？
有看到刮削的元数据小文件都会转移

这里设置得太小我觉得没必要 而且消耗性能？（之前试着一堆文件硬链接然后爆内存了 orz），我希望的策略是小于设定值的文件直接复制到目标文件夹，

![image](https://user-images.githubusercontent.com/73752817/215304318-9c55609c-dd82-479b-af22-22c75fd16e5e.png)

**Comment by jxxghp** [comment]
会忽略不处理，这个是用来过滤预告片之类的。

**Comment by Ton-yi** [comment]
能否增加选项 “小于____ (MB)的文件处理方式” - "硬链接“”软连接“”移动“......
