### ISSUE TITLE
修改部分源码后与预期效果不一致，希望大佬指教

### ISSUE THREAD

**Issue by youyifentian** [jxxghp/nas-tools#3211]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.2
>
> 环境: docker 源码
>

## 由于本人的特殊需求，我修改了一行代码，但是出来的效果与预期效果并不完全一致，希望大佬闲暇时刻能指导一下，内容很简单，话不多说

修改的具体文件是：[/app/scheduler.py](https://github.com/jxxghp/nas-tools/blob/master/app/scheduler.py#:~:text=self.SCHEDULER.add_job(MetaHelper().save_meta_data%2C%20%27interval%27%2C%20seconds%3DMETAINFO_SAVE_INTERVAL))

具体修改内容
![QQ截图20230129124756](https://user-images.githubusercontent.com/5012570/215305680-5d0c77f6-df93-4b99-a855-ddc5a8f50e7c.jpg)
## 这里我就有点疑惑，首先我确定已经将上述代码成功删除并正确运行，因为后面定时任务确实没有在执行并且也可以使用手动同步，这里可以相互佐证，其次基础设置里面的文件转移方式我设置的是移动，就是这个有且仅有一次的触发硬链接同步我不明白是什么情况，也没有看到哪里会调用这段代码，所以想请教大佬闲暇时候可以指点一下，非常感谢。

**Comment by jxxghp** [comment]
问题太多了，实在没空，自己研究下吧
