### ISSUE TITLE
NASTool总下载失败

### ISSUE THREAD

**Issue by uubyron** [jxxghp/nas-tools#3212]
## 你使用的 NAStool 是什么版本，什么环境？
无
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

>NASTool下载失败，下载进度条一直为0，尝试过其他套件，可以正常下载。非网络问题。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 无相关问题

## 你期望的结果

> 正常下载安装

## 给出程序界面截图、后台运行日志或配置文件

> 
![image](https://user-images.githubusercontent.com/44697007/215307319-c470d3f5-1f8a-4732-8e0b-aa9421f111f2.png)

**Comment by Purple-wind-bell** [comment]
先学会感恩。。。

**Comment by uubyron** [comment]
> 先学会感恩。。。

感恩你这SD阴阳怪气的吗？

**Comment by DDSDerek** [comment]
套件版本来这样提issue是没有问题的，如果用的是矿神的套件就去套件群里问

**Comment by ChrisShen-github** [comment]
用docker不香吗

**Comment by accors** [comment]
套件源的问题。不是本项目问题在这发issue也没用，官方不维护套件版本，建议使用docker部署。

**Comment by uubyron** [comment]
> 套件版本来这提issue是没有用的，如果用的是矿神的套件就去套件群里问
> 
> 官方已经不维护套件版本了

好的

**Comment by uubyron** [comment]
> 用docker不香吗

Docker也有 主要是小白 不太会用Docker

**Comment by uubyron** [comment]
> 套件源的问题。不是本项目问题在这发issue也没用，官方不维护套件版本，建议使用docker部署。

好的 不太懂 我以为跟nastool相关的都在这问呢
