### ISSUE TITLE
http代理增加用户名密码设置

### ISSUE THREAD

**Issue by youfly** [jxxghp/nas-tools#3213]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: [2.7.6]
>
> 环境: docker  synology

## 你想要新增或者改进什么功能？

>http代理增加用户名密码设置。

## 这个功能有什么可以参考的资料吗？

> 无

**Comment by Shurelol** [comment]
http://username:password@www.example.com:port

**Comment by youfly** [comment]
> http://username:password@www.example.com:port

谢谢，我试试。
