### ISSUE TITLE
nastool与影视库通信失败后,自定义订阅会疯狂下载

### ISSUE THREAD

**Issue by MrLv0816** [jxxghp/nas-tools#3217]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.2 a304552
>
> 环境: Synology
>

## 你遇到什么问题了？

> nastool与影视库通信失败后,自定义订阅会疯狂下载订阅内容

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 修复bug

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
补充场景及日志。
连不上媒体服务器就完全不下载，似乎也不对吧？

**Comment by MrLv0816** [comment]
> 补充场景及日志。 连不上媒体服务器就完全不下载，似乎也不对吧？

nastool与影视库通信失败后,自定义订阅会自动下载全部资源 , 断开影视库通信应当也可以正常处理本地是否存在该影视 , 而不是如上所述全部重新下载一遍
