### ISSUE TITLE
文件名识别BUG

### ISSUE THREAD

**Issue by suntini** [jxxghp/nas-tools#3220]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.2
>
> 环境: docker
>

## 你遇到什么问题了？
文件名识别BUG

> 如UI BUG请提供截图及配置文件截图
![Snipaste_2023-01-29_19-46-20](https://user-images.githubusercontent.com/29545348/215324159-a2fcfd8e-8d39-4a51-beee-f802601403ff.png)

**Comment by Shurelol** [comment]
加识别词，这个正则把文件名后面那个括号及里面的编码屏蔽了
