### ISSUE TITLE
入库完成通知：目录同步通知和下载器通知是否可以独立按需设置？

### ISSUE THREAD

**Issue by Zhangqian0375** [jxxghp/nas-tools#3221]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.2
>
> 环境: docker Synology
>

## 入库信息重复，容易引起误解

> 电影开始下载后，就会收到目录同步的入库通知，还会收到下载器的入库通知，入库信息太多，容易引起误解。

## 你期望的结果

> 下载器入库和目录同步 ，入库提醒是否可以独立分开，设置按需提醒？
目录同步入库后，emby上面都刮出来了，其实下载器还没下好。
看到目录同步的入库通知，以为下载已经完成了。
打开看不了电影，经常引起误解。

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by thsrite** [comment]
Qb设置 为未下载完成的资源增加!qb后缀

即可实现，下载完再目录同步提示入库

**Comment by Zhangqian0375** [comment]
请教在nastool哪个位置添加  !qb后缀？  感谢赐教！

**Comment by Zhangqian0375** [comment]
是否是在qb下载设置 ---选项卡--下载  勾选
![image](https://user-images.githubusercontent.com/54308056/215369820-60919061-5670-4185-b071-f5ac2649da05.png)
谢谢

**Comment by jxxghp** [comment]
目录同步和下载器监控不要同时开。

**Comment by thsrite** [comment]
> 是否是在qb下载设置 ---选项卡--下载 勾选
> ![image](https://user-images.githubusercontent.com/54308056/215369820-60919061-5670-4185-b071-f5ac2649da05.png)
> 谢谢

是这个
