### ISSUE TITLE
使用qb下载时，在nastool配置的路径无法传递到qb中，总是使用qb的默认下载目录

### ISSUE THREAD

**Issue by dlwyk** [jxxghp/nas-tools#3237]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.2
>
> 环境: docker
>
qb用的是docker环境的80x86/qbittorrent:4.4.3.1-36-minimal-amd64-full

## 你遇到什么问题了？

> 使用qb下载时，在nastool配置的路径无法传递到qb中，总是使用qb的默认下载目录
nastool设置如下
![image](https://user-images.githubusercontent.com/11608846/215426491-210df088-8a10-4365-a60c-63ae2beff68c.png)
前面的目录是qb的挂载目录，即下载目录
后面的是nastool中的挂载目录，即监控的目录

![image](https://user-images.githubusercontent.com/11608846/215426597-32763ae3-7b82-4cbc-9d7d-d1e96978169b.png)
![image](https://user-images.githubusercontent.com/11608846/215426649-6f5f3c65-7f06-4ac9-8281-470f2f520b42.png)

qb中的结果如下
![image](https://user-images.githubusercontent.com/11608846/215426860-755263f9-4823-4e2f-b7bc-45480470c028.png)
qb设置如下
![image](https://user-images.githubusercontent.com/11608846/215427489-e9a3ce9d-7b30-4cb5-b7a3-593371060513.png)

nastool中的日志如下
![image](https://user-images.githubusercontent.com/11608846/215427404-b5959d4a-985b-4a03-9d8e-fe80e0748abd.png)
显示传递的目录是None

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 希望nastoo下载的时候可以把下载目录正确传递过去

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by youyifentian** [comment]
+1
补充一下，复现步骤，下载管理=》正在下载=》新增下载，无论是种子文件还是磁力，都无法把手动选择的保存目录传递到qb

**Comment by youyifentian** [comment]
借楼在反馈一个bug
![QQ截图20230130212940](https://user-images.githubusercontent.com/5012570/215490855-720d91f2-a768-41a5-9a30-94682de34045.jpg)
![QQ截图20230130212920](https://user-images.githubusercontent.com/5012570/215490889-202f06b5-8717-46b8-95ed-db9a6dc50506.jpg)

## 站点里面配置下载设置，也生效了，但是再次编辑该站点时，这个下载设置并没有读取到配置文件里面的设置，还是默认的

**Comment by obear997** [comment]
+1 ， 遇到楼上同样的问题
