### ISSUE TITLE
订阅下载失败

### ISSUE THREAD

**Issue by iizx** [jxxghp/nas-tools#3242]
日志如下：

添加下载任务失败：满江红 (2023)
站点：高清电台
种子名称：满江红
种子链接：[//table[@id="cili"]//a[@rel="nofollow"]/@href||Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36|]
错误信息：无法从详情页面：https://gaoqing.fm/view/994063c8e9fc 解析出下载链接
2023-01-29 21:01:24

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by jxxghp** [comment]
进页面看，哪里有种子？
