### ISSUE TITLE
新增支持站点

### ISSUE THREAD

**Issue by Nutiar** [jxxghp/nas-tools#3246]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.2

> 环境: docker 

## 你想要新增或者改进什么功能？
**1.pt 站点希望增加对朱雀站点的支持**
站点网址：https://zhuque.in，站点使用TNode自研的架构
1.1.无法更新
![图片](https://user-images.githubusercontent.com/75288569/215462833-04f9b3ef-63d6-4b93-90e9-04f8cd5be42e.png)

2.1.手动添加cookie，也会提示失效
![图片](https://user-images.githubusercontent.com/75288569/215461576-89a451fb-b3fa-4bda-89e4-c6379c40e7aa.png)

**2.索引器 希望新增bt站点《漫猫动漫》**
站点网址：http://www.comicat.org/
此站更新动漫的频率很快 而且动漫挺全 希望nastool支持一下

**Comment by jxxghp** [comment]
zhuque 需要个账号

**Comment by Nutiar** [comment]
给我邮箱我邀请你

**Comment by lightolly** [comment]
zhuque需要开启浏览器仿真

> 给我邮箱我邀请你

**Comment by Nutiar** [comment]
> zhuque需要开启浏览器仿真
> 
> > 给我邮箱我邀请你
![image](https://user-images.githubusercontent.com/75288569/215518821-e82bb642-32b2-417d-8006-f06d9f63cc32.png)
好像不太行。

**Comment by luoxiao-xy** [comment]
已升级到最新，但是也必须开启浏览器仿真才能正常使用。这是bug还是只能这样？

**Comment by luoxiao-xy** [comment]
@jxxghp 现在必须开仿真才能查看数据，性能非常低，而且经常失败。希望可以不开起仿真也能读取

**Comment by jxxghp** [comment]
> @jxxghp 现在必须开仿真才能查看数据，性能非常低，而且经常失败。希望可以不开起仿真也能读取

不需要的

**Comment by luoxiao-xy** [comment]
关闭了仿真后，直接提示cookie无效
![image](https://user-images.githubusercontent.com/49856280/216334031-e3ad4d98-3cb5-4b4b-b77d-d0a5b919f9c6.png)

日志中显示 朱雀 未登录，跳过后续操作
![image](https://user-images.githubusercontent.com/49856280/216334123-9673aa16-abc1-487b-a316-a33cbe7073bf.png)
