### ISSUE TITLE
synology chat下载信息交互失败

### ISSUE THREAD

**Issue by ggboynas** [jxxghp/nas-tools#3253]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.2 4a9c5d0
>
> 环境: 同一群晖下的docker与chat
>

## 你遇到什么问题了？

> 设置好后测试正常，搜索影片信息与入库信息可正常交互，但选择影片序号后检索到下载资源只给chat发送图片，无法显示下载；开启自动择优下载后可自动下载，但下载信息发送失败。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 暂无相关问题

## 你期望的结果

> 检索到资源可实现下载链接发送，或推送添加下载的信息

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
<img width="842" alt="推送bug" src="https://user-images.githubusercontent.com/122594417/215654040-f2c296ca-6cab-4705-8d31-bf9874af5202.png">

**Comment by jxxghp** [comment]
有的能发送成功，有的又不行，怀疑跟内容有关，未找到原因。

**Comment by ggboynas** [comment]
> 有的能发送成功，有的又不行，怀疑跟内容有关，未找到原因。

我对发送失败的消息进行自定义测试，发现只要带 % 这个字符就会报错，不带的可以正常发送
<img width="486" alt="推送bug" src="https://user-images.githubusercontent.com/122594417/215773633-4e7771d8-d82e-42f7-bebf-5544e8a17581.png">
