### ISSUE TITLE
nastools的低于10M目录不同步的代码失效了

### ISSUE THREAD

**Issue by Jushb** [jxxghp/nas-tools#3262]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.2最新版
>
> 环境: docker unraid
>

## 你遇到什么问题了？

> nastools的低于10M不同步的设置失效了
，重装了很多次都不行。
很小的文件也会被同步，比如那种电影种子带了的网站介绍的几百K文件
持续很久了，上一个版本也发现有这个问题。
随便配图别介意。

**Comment by weiyideai520** [comment]
我的也是，同样的问题。

**Comment by Jushb** [comment]
目前还是这样，没有处理哈。等待大佬修复。。现在很多BT资源都带了一大堆冒充媒体后缀名的广告文件

**Comment by 120318** [comment]
你们需要提供更详细的说明，比如日志，具体资源情况之类的。
