### ISSUE TITLE
【功能需求】自定义识别当转移原为一个文件夹的时候，不显示转移进度

### ISSUE THREAD

**Issue by nxcjs** [jxxghp/nas-tools#3263]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.8.2
>
> 环境: synology 套件

## 你想要新增或者改进什么功能？

> 媒体整理-手动识别-自定义识别
当转移原为一个文件夹的时候，不显示转移进度
## 这个功能有什么可以参考的资料吗？

> 无

**Comment by jxxghp** [comment]
dev已支持
