### ISSUE TITLE
移动端UI细节

### ISSUE THREAD

**Issue by git-0101** [jxxghp/nas-tools#3266]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.2
>
> 环境: docker
>

## 你遇到什么问题了？

> 高级搜索 字样位置：
![mmexport1675157900523](https://user-images.githubusercontent.com/115487446/215724821-02242c18-714e-482f-8121-29236979808c.jpg)

![Screenshot_20230131_173846_com microsoft emmx](https://user-images.githubusercontent.com/115487446/215724808-2f915273-caee-42d1-904d-6050cdced730.jpg)

过滤规则条目排序：
![Screenshot_20230131_171049](https://user-images.githubusercontent.com/115487446/215725261-506e0485-1e9a-4c00-9aa5-c866aacdf2ae.jpg)
作者大大能修复成之前那样一个方框条目一行么，从上到下排列，简洁有序，哈哈。

**Comment by jxxghp** [comment]
高级搜索的提示去掉了

**Comment by git-0101** [comment]
> 高级搜索的提示去掉了

好的。攒！
