### ISSUE TITLE
升级后HDChina站点无法搜索资源

### ISSUE THREAD

**Issue by Jnwei1202** [jxxghp/nas-tools#3269]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>V2.8.2
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> 描述一下你遇到的问题
1、升级后HDChina站点无法搜索资源
2、订阅手动刷新两次才会从  正在订阅 转为 正在搜索，原来一次就会变，其实后台好像已经开台搜索

**Comment by git-0101** [comment]
遇到了同样的问题。瓷器和ttg站点资源获取不到，搜索也显示无结果。2.7.2版本站点资源获取速度和搜索速度非常快，和其它站点一样。现在搜索最后估计卡这两站点基本要等10秒以上才能结束。
希望作者大大，忙完这阵的推荐改版，UI搜索改版后，能够对比下2.7.2版本相关的代码，优化到以前那么快速百搜百中。辛苦了！

**Comment by jxxghp** [comment]
> 遇到了同样的问题。瓷器和ttg站点资源获取不到，搜索也显示无结果。2.7.2版本站点资源获取速度和搜索速度非常快，和其它站点一样。现在搜索最后估计卡这两站点基本要等10秒以上才能结束。
> 
> 希望作者大大，忙完这阵的推荐改版，UI搜索改版后，能够对比下2.7.2版本相关的代码，优化到以前那么快速百搜百中。辛苦了！

那是因为ttg和瓷要开浏览器渲染才能访问和拿到free标志，所以很慢。

**Comment by git-0101** [comment]
> > 遇到了同样的问题。瓷器和ttg站点资源获取不到，搜索也显示无结果。2.7.2版本站点资源获取速度和搜索速度非常快，和其它站点一样。现在搜索最后估计卡这两站点基本要等10秒以上才能结束。
> > 希望作者大大，忙完这阵的推荐改版，UI搜索改版后，能够对比下2.7.2版本相关的代码，优化到以前那么快速百搜百中。辛苦了！
> 
> 那是因为ttg和瓷要开浏览器渲染才能访问和拿到free标志，所以很慢。

这个因素也确实。这两站资源挺好，不然使用Lite版也挺好。

**Comment by jxxghp** [comment]
搜索倒是可以判一下开关，开关开了才用仿真
