### ISSUE TITLE
数据库错误死循环,强制重启后丢失账户数据无法登录.

### ISSUE THREAD

**Issue by ztx0079** [jxxghp/nas-tools#327]
1.6.5手动开启目录同步后,遇到数据库错误,并陷入死循环,只得强制重启nastools,重启后账户数据丢失,无法登录,更改config.yaml内的 login_user 及 login_password也无法登录

23:26:08 ERROR - 【SYNC】/media2/Temp/episode 处理失败：目录下未找到媒体文件，当前最小文件大小限制为 150.0M
23:26:13 ERROR - 【DB】执行SQL出错：sql:INSERT INTO MESSAGES(LEVEL, TITLE, CONTENT, DATE) VALUES (?, ?, ?, ?); parameters:('ERROR', '【SYNC】/media2/Temp/episode 处理失败', '目录下未找到媒体文件，当前最小文件大小限制为 150.0M', '2022-06-20 23:26:08'); database is locked
23:26:18 ERROR - 【DB】执行SQL出错：sql:INSERT INTO MESSAGES(LEVEL, TITLE, CONTENT, DATE) VALUES (?, ?, ?, ?); parameters:('ERROR', '【DB】执行SQL出错', "sql:INSERT INTO MESSAGES(LEVEL, TITLE, CONTENT, DATE) VALUES (?, ?, ?, ?); parameters:('ERROR', '【SYNC】/media2/Temp/episode 处理失败', '目录下未找到媒体文件，当前最小文件大小限制为 150.0M', '2022-06-20 23:26:08'); database is locked", '2022-06-20 23:26:13'); database is locked
23:26:18 ERROR - 【DB】执行SQL出错：sql:SELECT ID, LEVEL, TITLE, CONTENT, DATE FROM MESSAGES WHERE DATE > ? ORDER BY DATE DESC; parameters:('2022-06-20 23:25:37',); database is locked
23:26:18 ERROR - 【DB】执行SQL出错：sql:INSERT INTO MESSAGES(LEVEL, TITLE, CONTENT, DATE) VALUES (?, ?, ?, ?); parameters:('ERROR', '【DB】执行SQL出错', "sql:SELECT ID, LEVEL, TITLE, CONTENT, DATE FROM MESSAGES WHERE DATE > ? ORDER BY DATE DESC; parameters:('2022-06-20 23:25:37',); database is locked", '2022-06-20 23:26:18'); database is locked
23:26:23 ERROR - 【DB】执行SQL出错：sql:INSERT INTO MESSAGES(LEVEL, TITLE, CONTENT, DATE) VALUES (?, ?, ?, ?); parameters:('ERROR', '【DB】执行SQL出错', 'sql:INSERT INTO MESSAGES(LEVEL, TITLE, CONTENT, DATE) VALUES (?, ?, ?, ?); parameters:(\'ERROR\', \'【DB】执行SQL出错\', "sql:INSERT INTO MESSAGES(LEVEL, TITLE, CONTENT, DATE) VALUES (?, ?, ?, ?); parameters:(\'ERROR\', \'【SYNC】/media2/Temp/episode 处理失败\', \'目录下未找到媒体文件，当前最小文件大小限制为 150.0M\', \'2022-06-20 23:26:08\'); database is locked", \'2022-06-20 23:26:13\'); database is locked', '2022-06-20 23:26:18'); database is locked

**Comment by ztx0079** [comment]
不能登录的原因找到了, config.yaml 内容被打乱了,许多参数被注释掉了,可能跟强制重启有关?

**Comment by jxxghp** [comment]
跟这个版本没关系，以前就偶然有人出现，你看是不是数据库文件被其他占用了锁定了。

**Comment by jxxghp** [comment]
这个标题有误导，问题之前就知道了，无法重现，没找到原因，后面看看吧。问题先关了。

**Comment by log-time** [comment]
数据库如果使用mariadb能避免这类问题吗？
