### ISSUE TITLE
下载管理-正在下载，无法打开

### ISSUE THREAD

**Issue by weiyideai520** [jxxghp/nas-tools#3276]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:v2.8.3 3ea1be2
>
> 环境: docker 
>

## 你遇到什么问题了？

下载管理-正在下载，无法打开

## 错误日志如下

```
[2023-02-01 09:05:04,148] ERROR in app: Exception on /downloading [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/nas-tools/web/main.py", line 467, in downloading
    DispTorrents = WebAction().get_downloading().get("result")
  File "/nas-tools/web/action.py", line 3520, in get_downloading
    torrents = Downloader().get_downloading_progress()
  File "/nas-tools/app/downloader/downloader.py", line 395, in get_downloading_progress
    return self.default_client.get_downloading_progress(tag=tag)
TypeError: Aria2.get_downloading_progress() got an unexpected keyword argument 'tag'
```

**Comment by wcyws** [comment]
您好，我这里使用115遇到了同样的情况，日志代码如下
stderr: [2023-02-01 10:58:28,922] ERROR in app: Exception on /downloading [POST]
stderr: Traceback (most recent call last):
stderr:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
stderr:     response = self.full_dispatch_request()
stderr:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
stderr:     rv = self.handle_user_exception(e)
stderr:   File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
stderr:     return original_handler(e)
stderr:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
stderr:     rv = self.dispatch_request()
stderr:   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
stderr:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
stderr:   File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
stderr:     return current_app.ensure_sync(func)(*args, **kwargs)
stderr:   File "/nas-tools/web/main.py", line 467, in downloading
stderr:     DispTorrents = WebAction().get_downloading().get("result")
stderr:   File "/nas-tools/web/action.py", line 3520, in get_downloading
stderr:     torrents = Downloader().get_downloading_progress()
stderr:   File "/nas-tools/app/downloader/downloader.py", line 395, in get_downloading_progress
stderr:     return self.default_client.get_downloading_progress(tag=tag)
stderr: TypeError: Client115.get_downloading_progress() got an unexpected keyword argument 'tag'

**Comment by wcyws** [comment]
@jxxghp  您好，115下载器依然存在该问题，没有得到修复，版本号为最新的2.8.3 0568889

**Comment by jxxghp** [comment]
> @jxxghp  您好，115下载器依然存在该问题，没有得到修复，版本号为最新的2.8.3 0568889

还在dev分支
