### ISSUE TITLE
docker 镜像能否添加lateset-lite分支

### ISSUE THREAD

**Issue by SpringPoiu** [jxxghp/nas-tools#3278]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.2

> 环境: docker

## 你想要新增或者改进什么功能？

>建议增加latest-lite分支，方便快速最新lite版本镜像

**Comment by DDSDerek** [comment]
https://github.com/jxxghp/nas-tools/issues/2939
