### ISSUE TITLE
建议添加指定不同分类使用不同的规则

### ISSUE THREAD

**Issue by xushier** [jxxghp/nas-tools#3279]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.3
>
> 环境: docker
## 你想要新增或者改进什么功能？
建议添加指定不同分类使用不同的规则，类似分类策略。可以实现自动对电视剧和电影、国内和国外影视使用不同的规则。目前需要添加订阅后手动指定。
> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
重复问题
