### ISSUE TITLE
plex中电视剧错误，但是在nastool中显示是正确的

### ISSUE THREAD

**Issue by zlhdd108** [jxxghp/nas-tools#3282]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v2.7.6
> 环境: docker or windows or Synology
>Synology

## 你遇到什么问题了？

> 描述一下你遇到的问题
nastool中看到的数据是正确的，但是入库后发现plex里面的数据不对，将两个不同的剧集归到一个里面了，而且电视剧级别都是这种情况
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/16465666/215969227-77450bf0-fe84-447f-95cb-65ace9e57f1e.png)
![image](https://user-images.githubusercontent.com/16465666/215969275-531fa6f9-d7f0-49ef-8c91-57f332d22878.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
那得问plex

**Comment by zlhdd108** [comment]
知道问题了，是TV的二级分类导致的，把二级分类关闭就可以了；Plex识别这个国产、国外、纪录这种二级分类有问题
