### ISSUE TITLE
新增订阅 -> 保存路径 里只有  自动  一个选项

### ISSUE THREAD

**Issue by Dreamray** [jxxghp/nas-tools#3285]
> NAStool 版本: 2.8.3
>
> 环境: windows
>

> 新增订阅 -> 保存路径 里只有  自动  一个选项，未出现 下载嚣 ->  下载目录  里设置的目录

**Comment by jxxghp** [comment]
检查QB是不是开启了自动管理，下载器设置的地方

**Comment by Dreamray** [comment]
> 检查QB是不是开启了自动管理，下载器设置的地方

关了也不管用
