### ISSUE TITLE
资源搜索以及推荐无法加载内容

### ISSUE THREAD

**Issue by SaxonLee** [jxxghp/nas-tools#3289]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.3
>
> 环境: windows 
>

## 你遇到什么问题了？

> 资源推荐以及资源搜索无法加载数据

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 浏览过无发现有效结果

## 你期望的结果

> [希望看看是哪里出现问题](
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
#
![QQ截图20230201225351](https://user-images.githubusercontent.com/86994980/216077312-4a399ee4-b793-4e92-9877-51660d745409.png)

**Comment by jxxghp** [comment]
你的客户端连不上tmdb
