### ISSUE TITLE
正常访问可以打开的站点，经常提示无法访问。

### ISSUE THREAD

**Issue by ainas999** [jxxghp/nas-tools#3291]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.8.3 3ea1be2
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

正常访问可以打开的站点，经常提示无法访问。
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/118146355/216209634-da135e72-bb39-4094-9375-647e7918d82d.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
重启NAS和家里的路由器

**Comment by jxxghp** [comment]
【使用小贴示二】
1、Jellyseerr/Overseerr配合使用方法：在设定->通知->网络钩子中填入NAStool地址http://ip:port/subscribe ，以及从NAStool基础设置->安全中获取的API密钥，勾选请求“自动批准、请求已获批准”，可以通用Jellyseerr/Overseerr进行选片提交订阅给NAStool。
2、更新站点Cookie时需同时更新配套的User-Agent，可避免一些站点连通性问题，站点维护中点击卡片右上角小圆点图标可自动获取Cookie & UA。
3、如发现站点数据统计无法刷新完成、签到个别站点一直提示无法访问，且更新Cookie和UA、重启Docker后仍然无效的，可偿试重启下家里的路由/光猫，会有神奇的效果（亲测有效，我也无法解释其中的原因）。站点连通性情况跟版本升级一般没有关系，很大可能是因为升级的操作导致了重启或网络上的变化导致。
3、无法正常签到的站点，可以在站点维护中开启仿真，一般都能正常签到（此时模拟人工操作，查找签到按钮点击）。
4、不喜欢TMDB随机登录壁纸的（有时候会出现恐怖图片），现在已经可以在基础设置中更改为Bing每日壁纸。
5、使用Windows版本无法使用IP地址访问NAStool时，需要手动将配置文件中web_host配置为0.0.0.0。
6、v2.6.3版本后已经修改了TMDB缓存机制，TMDB修改词条后如需立即生效已经不需要再去全量清理TMDB缓存了，重启NAStool即可（不重启则过一段时间生效）。
7、不想看到首页媒体服务器播放记录的，可以建个新用户，取消选择“我的媒体库”即可。
8、使用微信/Telegram/Slack且调通了交互功能的情况下，可以将家人/亲友拉入微信企业/含机器人的TG群/Slack工作区，共享便利观影的快乐。
9、自动升级后无法启动的，基本上都是因为网络环境不佳无法自动安装依赖导致，此时重新拉取镜像，重置/重建（群晖为重置，portainer为重建）容器即可100%解决问题，如不行则检查新镜像是否拉取成功或是否生效。
