### ISSUE TITLE
开始内的电影折线图，统计的数字有小数点。

### ISSUE THREAD

**Issue by feixu0530** [jxxghp/nas-tools#330]
开始内的电影折线图，统计的数字有小数点。电影不能被劈开，不应该统计有小数点。

**Comment by feixu0530** [comment]
![image](https://user-images.githubusercontent.com/47844049/174718272-5d024503-c5ec-4c41-b404-6cab90daa947.png)
电影就是这个情况，连续剧是正常的：
![image](https://user-images.githubusercontent.com/47844049/174718381-acbc9f21-4b75-4279-9f87-c03b3c7f66e1.png)

**Comment by jxxghp** [comment]
小问题，先解决其它的吧
