### ISSUE TITLE
添加了下载任务，电影还没下载完成就秒转移

### ISSUE THREAD

**Issue by skjgqbc8** [jxxghp/nas-tools#3305]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.3
>
> 环境: docker  or Synology
>

## 你遇到什么问题了？

> 添加了下载任务，电影还没下载完成就秒转移

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

![image](https://user-images.githubusercontent.com/124287746/216384493-304fa660-f5be-4dd6-b23e-6d126fa1a795.png)

**Comment by skjgqbc8** [comment]
感觉是aria2是先创建文件然后再下载的机制 但是nastools检测到完整的文件名(?)就提前执行了转移的操作

**Comment by jxxghp** [comment]
更换下载器，如果ARIA2不支持未完成文件添加后缀的话。
