### ISSUE TITLE
订阅编辑，不能自定义年份和开始集数，没显示所选bt站点

### ISSUE THREAD

**Issue by Otiguy** [jxxghp/nas-tools#3307]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
2.8.3 3ea1be2
> 环境: docker or windows or Synology
>
Synology

## 你遇到什么问题了？

> 描述一下你遇到的问题

#3204 自从提了这个修复了之后，目前我遇到只要自定义编辑一些信息就会变成如图↓，所选bt站点，都没显示出来
![Snipaste_2023-02-03_02-32-26](https://user-images.githubusercontent.com/48633984/216417548-d1e8ded7-3c55-4418-8c57-3ac50ec2ae05.png)

正常的bt站点列表
![Snipaste_2023-02-03_02-34-26](https://user-images.githubusercontent.com/48633984/216418316-123b28df-bf0e-443f-a697-bb8b729e56fa.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

修复能正常自定义订阅和下载

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

![Snipaste_2023-02-03_02-41-18](https://user-images.githubusercontent.com/48633984/216419838-886be2b3-88ef-4bdb-97fe-13d3752d72a4.png)

**Comment by jxxghp** [comment]
模糊匹配是不用于搜索的，只用于RSS。
