### ISSUE TITLE
请求同时监听IPv4与IPv6地址

### ISSUE THREAD

**Issue by lywly** [jxxghp/nas-tools#3313]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.3

> 环境: windows

## 你想要新增或者改进什么功能？

> 请求同时监听IPv4与IPv6地址。其中公网IPv6用于远程访问，IPv4地址通过内网穿透后用于企业微信回调。

## 这个功能有什么可以参考的资料吗？

> 无

**Comment by jxxghp** [comment]
docker是支持的，Windows不支持。
