### ISSUE TITLE
极空间Z4S使用nastools硬链接无法刷新

### ISSUE THREAD

**Issue by ihujin** [jxxghp/nas-tools#3314]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.8.3
>
> 环境: docker 

## 你想要新增或者改进什么功能？

> 希望能将极空间的z4s增加硬链接刷新

## 这个功能有什么可以参考的资料吗？

> 在lssues区域看到作者大佬针对极空间的z4型号进行了适配，希望大佬能够将z4s型号也加入进去

**Comment by jxxghp** [comment]
我没有设置，看下这个输出的是啥，z4s？

platform.release()

**Comment by njsfcy** [comment]
在z4s的容器ssh下输入：
```
python
import platform
print(platform.release())
```
输出：
`5.17.13-generic`

**Comment by Linyue-GitHub** [comment]
@jxxghp 大佬顺便也适配一下绿联DX4600的
在DX4600的容器ssh下输入：
```
python
import platform
print(platform.release())
```
输出：
`5.10.120`

**Comment by jxxghp** [comment]
这个不行，不是明显的系统标识。另外除了z4，其它的我也不知道问题是什么。

**Comment by Linyue-GitHub** [comment]
> 这个不行，不是明显的系统标识。另外除了z4，其它的我也不知道问题是什么。
大佬，我用这个能够找到唯一标识，你看看能不能加上去
`platform.node()`
输出
`UGREEN-4FFF`
取前面的'UGREEN'就能识别到这台设备

**Comment by ihujin** [comment]
经多位机友共同测试，在硬链接文件夹生成之后可以修改文件夹名称，极空间的极影视就立马识别出了硬链接，识别出来后再将文件夹改回原来的名称极影视也正常识别，例如生成硬链接文件夹名称为：狂飙 (2023)  在生成之后可以将名称改为：狂飙 (2023)_1，这样极空间就立马刷新，绿联的产品应该也是可以的，刷新出来之后再自动将：狂飙 (2023)_1改成：狂飙 (2023)是可以正常识别的
