### ISSUE TITLE
从旧版本升级2.7.6往上的windows版无法打开

### ISSUE THREAD

**Issue by schalkiii** [jxxghp/nas-tools#3325]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.3 
>
> 环境: windows
>

## 你遇到什么问题了？

> 2.8.3 windows版无法打开。 从2.7.1升级的，之前2.7.2也无法打开

![微信截图_20230204123206](https://user-images.githubusercontent.com/30932387/216748608-bfc3347f-8ba4-4024-8d30-4597404e5ea7.png)

**Comment by schalkiii** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本: v2.8.3
> > 环境: windows
> 
> ## 你遇到什么问题了？
> > 2.8.3 windows版无法打开。 从2.7.1升级的，之前2.7.2也无法打开
> 
> [![微信截图_20230204123206](https://user-images.githubusercontent.com/30932387/216748608-bfc3347f-8ba4-4024-8d30-4597404e5ea7.png)](https://user-images.githubusercontent.com/30932387/216748608-bfc3347f-8ba4-4024-8d30-4597404e5ea7.png)

删除了alembic_version后现象依旧

**Comment by schalkiii** [comment]
逐个版本升级可升级到2.7.4。2.7.6及以后的版本会出现上述现象。 
2.7.5 release下无windows版未测试

**Comment by jxxghp** [comment]
重复问题
