### ISSUE TITLE
自定义订阅-希望能让纯文本rss不经过过滤规则

### ISSUE THREAD

**Issue by Earendil-C** [jxxghp/nas-tools#3328]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.3
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 自定义订阅中，使用“订阅”功能时会默认经过过滤规则，而这对纯文本（片单式）的不友好，因为他们只有一个标题而没有其他诸如1080p等标识，因此也不方便在过滤规则中添加规则。希望能给“订阅”选项一个不经过过滤规则的选项。

如：我使用Bangumi的个人主页rss，适当添加识别词后报文如下：
![image](https://user-images.githubusercontent.com/55442093/216759753-0bba1599-fa5b-42f4-88c5-64d1c42e7aad.png)
因为这个只有标题这个纯文本，无法通过过滤规则，因此无法添加订阅
![image](https://user-images.githubusercontent.com/55442093/216759797-d1456c53-8f42-475d-bcc4-481d294e8470.png)

**Comment by jxxghp** [comment]
不是有个过滤规则的选项吗？设一条不过滤的然后选这个。

**Comment by Earendil-C** [comment]
> 不是有个过滤规则的选项吗？设一条不过滤的然后选这个。

是的，我选了不过滤，然后发现这个不过滤是添加订阅成功的时候，新订阅的规则。然而这个报文会遵循默认规则，也就导致无法添加订阅

**Comment by Earendil-C** [comment]
![Screenshot_20230205_164856_Samsung Internet](https://user-images.githubusercontent.com/55442093/216809986-8fe2c6c0-8d9e-43aa-81a5-e21764af0803.jpg)
![Screenshot_20230205_164926_Samsung Internet](https://user-images.githubusercontent.com/55442093/216809994-73a933c6-077d-4d3a-b84a-253a9b51c1ea.jpg)

**Comment by jxxghp** [comment]
这个是bug，下个版本修复
