### ISSUE TITLE
刚群友反馈的一个问题，我试了一下好像确实存在，关于名称识别

### ISSUE THREAD

**Issue by 26712681** [jxxghp/nas-tools#333]
搜索    我才不要和你做朋友呢
快速搜索才能返回结果，普通搜索一个结果也没有
群友反馈北洋园能返回一个结果，难道北洋园命名方式不一样？
![image](https://user-images.githubusercontent.com/77581926/174709185-8067a027-74e8-405e-9a16-0d764663dccd.png)
![image](https://user-images.githubusercontent.com/77581926/174709282-c1a8c584-ccc7-4aff-a019-3683bc8b1928.png)
![257dcaef77614f66c547747a64b17bb](https://user-images.githubusercontent.com/77581926/174709427-63b0af7c-bde3-45a0-8acd-7c18349ede28.jpg)

据反馈说北洋园下载下来之后也不能自动识别。

所以请老大看看是不是整套识别逻辑，从搜索开始到下载到识别整理，哪里有需要优化的

**Comment by jxxghp** [comment]
Dont Want to be Friends with You
测试了下，这个名字tmdb的api不返回结果，但web页面有。

**Comment by dlovew** [comment]
> 

[I Don't Want To Be Friends With You](https://www.themoviedb.org/tv/104083?language=en-US)

**Comment by jxxghp** [comment]
加多个别名吧，不要'
