### ISSUE TITLE
正在下载界面无法显示

### ISSUE THREAD

**Issue by PKC278** [jxxghp/nas-tools#3330]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v2.8.3
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 描述一下你遇到的问题

正在下载页面无法显示，下载器连接的是aria2
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

是

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/52959804/216765917-b08319d2-99e0-4652-87dc-6612444805b5.png">

**Comment by jxxghp** [comment]
#3276
