### ISSUE TITLE
微信推送测试失败

### ISSUE THREAD

**Issue by 287138531** [jxxghp/nas-tools#3331]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
v2.8.3
> 环境: docker or windows or Synology
群辉  docker
## 你遇到什么问题了？
【Message】wechat 发送测试消息失败：参数未配置或配置不正确
> 描述一下你遇到的问题
不填写EncodingAESKey，Token   和消息推送代理  就能测试通过。
填写了就提示：【Message】wechat 发送测试消息失败：参数未配置或配置不正确
企业微信后台保持是能通过测试的，没问题
通过gettoken url，是能拿到token的。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
if not self.__get_access_token():
            return False, "参数未配置或配置不正确"

**Comment by 287138531** [comment]
> if not self.__get_access_token(): return False, "参数未配置或配置不正确"

给后面的人参考，我不填  消息推送代理  -反而成功了，菜单交互也是可以用的。。。尽管你高傲的关闭了iss。。。这条回复还是留给后面的人参考
