### ISSUE TITLE
v2.8.3 Plex 连接失败

### ISSUE THREAD

**Issue by ronchy1** [jxxghp/nas-tools#3334]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.3
>
> 环境: docker or windows or Synology
>

Plex 连接失败

> 描述一下你遇到的问题

升级v2.8.3后，连接Plex失败。期间在Plex端也加了SSL从HTTP转成了HTTPS。在NASTOOLS已将服务器地址转成HTTPS和更新了Token。不知是连接的问题还是对Plex HTTPS支持的问题。

![image](https://user-images.githubusercontent.com/32918026/216797664-02c4407e-fdeb-4076-8116-fbc89f5a2a96.png)

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
先试一下确定了再来提吧
