### ISSUE TITLE
高质量文件覆盖不起作用

### ISSUE THREAD

**Issue by trott90** [jxxghp/nas-tools#3335]
NAStool 版本: 2.8.2
环境: docker

当一个电影订阅选择了洗版，自定义过滤里的最高优先级是2160p，媒体设置里高质量文件覆盖选项打开， nt首先下载了一个1080p的文件，并导入媒体库，然后又下载了一个2160p的文件，也导入数据库，但nt并没有删除媒体库里原来的1080p的文件

希望在洗版下，nt下载了一个更高优先级的文件时，删除原来低优先级的文件（或者移到一个设置的回收目录）

**Comment by jxxghp** [comment]
发命名规则，发日志
