### ISSUE TITLE
qbittorrent修改web端口后，在ui测试成功，但无法下载，浏览log发现程序连接时还是使用8080端口

### ISSUE THREAD

**Issue by gnowmil** [jxxghp/nas-tools#3339]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.3
>
> 环境: docker
>

## 你遇到什么问题了？

> qbittorrent修改web端口后，在ui测试成功，但无法下载，浏览log发现程序连接时还是使用8080端口。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 希望修复。

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
qbittorrentapi.exceptions.APIConnectionError: Failed to connect to qBittorrent. Connection Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='10.0.0.22', port=8080): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14b8b2e41180>: Failed to establish a new connection: [Errno 111] Connection refused'))"))

**Comment by jxxghp** [comment]
重启
