### ISSUE TITLE
群晖Docker版的，自从升级到2.8.3版本后，文件自动转移完成后，没有实时刷新媒体服务器呢？实时刷新媒体库按钮已打开。

### ISSUE THREAD

**Issue by sammy-yuan** [jxxghp/nas-tools#3340]
群晖Docker版的，自从升级到2.8.3版本后，文件自动转移完成后，没有实时刷新媒体服务器呢？实时刷新媒体库按钮已打开。
![photo_2023-02-04_10-05-37](https://user-images.githubusercontent.com/76394856/216816819-dce02c61-7eb5-43f1-b610-cd9afd2f08aa.jpg)

**Comment by jxxghp** [comment]
就这张图，怎么排查呢

**Comment by sammy-yuan** [comment]
> 就这张图，怎么排查呢

请问需要那些？可以方便你们排查呢？

**Comment by jxxghp** [comment]
> > 就这张图，怎么排查呢
> 
> 请问需要那些？可以方便你们排查呢？

可以发一下nastool的日志，以及刷新后Emby的对应日志。这块很久都没有改动了。

**Comment by sammy-yuan** [comment]
> > > 就这张图，怎么排查呢
> > 
> > 
> > 请问需要那些？可以方便你们排查呢？
> 
> 可以发一下nastool的日志，以及刷新后Emby的对应日志。这块很久都没有改动了。

请问一下打开日志发现它才记到2022年6月8日。

![微信截图_20230206115842](https://user-images.githubusercontent.com/76394856/216881106-5930fdf2-df2e-4d21-b914-ee2a03cfbfdf.png)

**Comment by sammy-yuan** [comment]
实时日志中显示开始刷新emby媒体库，但是emby无反应。


















在 2023-02-06 11:41:10，"jxxghp" ***@***.***> 写道：

就这张图，怎么排查呢

请问需要那些？可以方便你们排查呢？

可以发一下nastool的日志，以及刷新后Emby的对应日志。这块很久都没有改动了。
