### ISSUE TITLE
是否能做个索引器聚合搜索功能？

### ISSUE THREAD

**Issue by solosing** [jxxghp/nas-tools#3343]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.3
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 你好，现在自建的索引器已经很强大了，但仍然有部分站点暂不支持，但这个时候发现有的站点jackett或者prowlarr支持，是否能做个聚合搜索，让索引功能更加强大？

## 这个功能有什么可以参考的资料吗？

> 无，我的想法是可以以内建索引器为主，jackett和prowlarr为辅，在jackett和prowlarr中添加内建索引器中不支持的站点，一键聚合搜索，在资源搜索页面整合展示，是否可行呢？

**Comment by jxxghp** [comment]
J和P已经很久没优化了，后面也是不断完善内建的，目前已经有些特性是内建索引才支持了。不考虑对其它的做进一步支持。
