### ISSUE TITLE
外网访问出现页面错误 Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by MrLv0816** [jxxghp/nas-tools#3344]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.3 3ea1be2
>
> 环境: synology

## 你想要新增或者改进什么功能？

> 因为不懂代码，所以不太清楚这个是我的问题还是nt问题，麻烦作者大大看一下
> Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH

## 这个功能有什么可以参考的资料吗？

> 无

**Comment by jxxghp** [comment]
这个应该是网络问题
