### ISSUE TITLE
自动删种任务添加硬盘余量条件

### ISSUE THREAD

**Issue by yubanmeiqin9048** [jxxghp/nas-tools#3345]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.3
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 自动删种任务添加硬盘余量条件，当硬盘容量低于设定值时删除种子

## 这个功能有什么可以参考的资料吗？

> 无

**Comment by yubanmeiqin9048** [comment]
#2542

**Comment by jxxghp** [comment]
如何确定删除哪些种子？规则可能会有点复杂吧。

**Comment by yubanmeiqin9048** [comment]
> 如何确定删除哪些种子？规则可能会有点复杂吧。

可以默认删除活动时间最长的种子，或者其他指定的条件

**Comment by 120318** [comment]
可以参考当前的auto remove之类的。

**Comment by Dreamray** [comment]
> 可以参考当前的auto remove之类的。

auto remove torrents 没有辅种处理逻辑，用这个：https://github.com/Dreamray/qB-Torrents-Auto-Delete
