### ISSUE TITLE
v2.8.3 整合Plex 不支持HTTPS

### ISSUE THREAD

**Issue by ronchy1** [jxxghp/nas-tools#3346]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.3
>
> 环境: docker

## 当Plex仅开启HTTPS，NASTOOLS不能连接Plex。

![image](https://user-images.githubusercontent.com/32918026/216827477-cfe71a23-97bd-4400-90d2-46db4432d09c.png)

**Comment by jxxghp** [comment]
证书是可信证书么，还是自签的？

**Comment by ronchy1** [comment]
可信的，从云服务申请的证书，并且在Plex端验证过配置没问题

**Comment by jxxghp** [comment]
用的是第三方模块，懒的去整了，一般都是内网使用。
