### ISSUE TITLE
bark功能拓展

### ISSUE THREAD

**Issue by zui-lang** [jxxghp/nas-tools#3354]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:2.9.0-beta
>
> 环境: docker

## 你想要新增或者改进什么功能？

> bark推送是一款强大的iOS/iPadOS通知推送软件，有大量参数可以进行调试，例如自定义图标推送(icon=https://xxxx)，通知组群分类（group=xxx），时效性通知.以及角标设置，希望可以完善这些功能，这对消息通知体验有很大帮助，或者提供高级选项可以自定义URL，提供参数让用户自行调试

## 这个功能有什么可以参考的资料吗？
https://api.day.app/API key/标题/推送内容？icon=https://user-images.githubusercontent.com/51039935/197520391-f35db354-6071-4c12-86ea-fc450f04bc85.png&url=https://github.com&group=NASTool
这个是我简单写的，增加了推送图标和分组，并且点击通知可以跳转到github，实际上可以将url替换成打开某个应用的链接

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.
url打开应用参考资料：[https://github.com/EddyVerbruggen/Custom-URL-scheme](url)
bark：[https://github.com/Finb/bark-server](url),[https://github.com/Finb/Bark](url)
参考DDNS-GO的Webhook：
![image](https://user-images.githubusercontent.com/77880495/216926867-284c3631-a09e-405e-859c-a4f9c5e604e6.png)

期待您的回复

**Comment by jxxghp** [comment]
可以加个自定义参数附到后面

**Comment by zui-lang** [comment]
是的，期待更新

**Comment by zui-lang** [comment]
顺便问一下，一些没有cookie的bt站点应该怎么添加，有rss

**Comment by zui-lang** [comment]
我在使用时，整理文件夹还遇到报错，整理文件夹的方式是移动，都是本地硬盘，请问该如何解决
![image](https://user-images.githubusercontent.com/77880495/217128466-b8d3dac7-cd9c-45cd-b579-30a295f36396.png)
