### ISSUE TITLE
docker 中自动更新失败

### ISSUE THREAD

**Issue by liubin5188** [jxxghp/nas-tools#3355]
<img width="744" alt="1" src="https://user-images.githubusercontent.com/27803726/216963318-2a5f2e8b-ead1-4a7e-9005-d89ed9a175c4.png">
<img width="743" alt="2" src="https://user-images.githubusercontent.com/27803726/216963336-dfb5c3a9-4f40-46f6-b207-e5e2fb48859e.png">
一直重复更新启动失败,之前版本忘记了

**Comment by liubin5188** [comment]
我看日志好像是自动拉取镜像的,他有更新的提示,不知道是不是自动的

**Comment by liubin5188** [comment]
我看日志好像是自动拉取镜像的,他有更新的提示,不知道是不是自动的

**Comment by accors** [comment]
不是。你要手动拉取镜像，重启更新的只是源码和依赖。

> 我看日志好像是自动拉取镜像的,他有更新的提示,不知道是不是自动的

**Comment by liubin5188** [comment]
ok ,感谢指点,回去试试
