### ISSUE TITLE
搜索/订阅 增加方言名称检索

### ISSUE THREAD

**Issue by goodjimli** [jxxghp/nas-tools#3358]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.3
>
> 环境: docker

## 你想要新增或者改进什么功能？
希望**搜索/订阅**资源的时候增加 按照不同地区网站的方言搜索 ，比如搜索俄罗斯的网站，检索资源时候 发送 英文名称和俄语名称 分别检索，中文地区发送简体/繁体/英文 检索。

为什么呢？ 因为有些资源只有中文名称，默认搜索/订阅 只会用英文名称检索，就会搜索不到资源。

难点应该是 通过何种 API/翻译 来获取资源不同语言名称和搜索结果的去重合并set.union()

**Comment by jxxghp** [comment]
现在的订阅界面，不是有个自定义搜索词吗，你想按什么搜索都行，但是否能识别还决定于种子的命名以及TMDB是否有数据。
