### ISSUE TITLE
自动搜索下载和自动添加订阅同时打开时，有时不会自动手动搜索下载只会添加订阅

### ISSUE THREAD

**Issue by likecreep** [jxxghp/nas-tools#3360]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.3
>
> 环境: docker 

当 豆瓣的 自动搜索下载 和  自动添加订阅 同时打开时， 有时 豆瓣想看 服务 并不会自搜索下载， 只会将电影放进 电影订阅里，显示 是 队列中 状态。 需要手动 在 订阅详情里 点击刷新 才会开始搜索下载。

请问这是bug，还是需要怎么设置呢？

**Comment by jxxghp** [comment]
队列中你等一等，过一会就会自动搜索。
