### ISSUE TITLE
移动端缺少图标

### ISSUE THREAD

**Issue by Wangsc1** [jxxghp/nas-tools#3363]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.0
>
> 环境: docker

移动端这两个图标一直缺失，好像就safari有这问题
![image](https://user-images.githubusercontent.com/26079238/217153452-06ba8780-6aec-451f-8c2b-0493d7373de8.jpeg)

**Comment by jxxghp** [comment]
我自己就是safari，好像没有问题。

**Comment by Wangsc1** [comment]
> 我自己就是safari，好像没有问题。

我就safari有这问题，chrome，alook都看了下没问题，算啦也没什么影响
