### ISSUE TITLE
设置默认路由，比如可以设置为榜单推荐或者站点数据

### ISSUE THREAD

**Issue by luoxiao-xy** [jxxghp/nas-tools#3364]
默认路由即之前未访问其他页面时的默认菜单页。
现在nt的默认路由是我的媒体库。
但是比如我是极空间，我有极影视就没有部署媒体库。我想将默认页面设置为榜单推荐或者站点数据。
这样我一打开我就可以追剧或者一打开就可以看到最新的PT站点数据了，而不是一直提示着无法连接媒体库
如果设置页面不好加，在环境变量加也可以。再或者如果用户没有配置媒体库，直接不出现我的媒体库页面，始终第一个也就是榜单推荐。

**Comment by teohhhh** [comment]
附议

**Comment by xiaoquexing1** [comment]
同意，如果能像MR那样直接显示推荐榜单也不错，毕竟NT主要还是追剧，默认为追剧的榜单页面很符合。不过考虑到每个人的需求不一样，建议直接给个设置项设置默认页面是什么。

**Comment by jxxghp** [comment]
提问模板里有说明，不要提涉任何其它商业产品的内容，有问题的留言我已经删掉了。
实际上还有一个方式，就是你新建一个用户，默认不要勾选媒体库这个权限，显示的就是默认第一个菜单。

**Comment by xiaoquexing1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xiaoquexing1** [comment]
> 提问模板里有说明，不要提涉任何其它商业产品的内容，有问题的留言我已经删掉了。 实际上还有一个方式，就是你新建一个用户，默认不要勾选媒体库这个权限，显示的就是默认第一个菜单。

如果是只有自己一个人用，还是不是很方便。相当于有两个账户了。还是建议按楼主所说的那样，直接给个设置项，用户自己选是用媒体库还是推荐榜单还是站点信息啥的作为首页。或者说NT后续做一个统一的dashboard仪表盘页面，来显示各种统计数据和综合性数据。这个dashboard可以让用户来添加一些小工具。也是一个不错的方案。很多管理系统都有类似的仪表盘页面作为首页

**Comment by luoxiao-xy** [comment]
> > 提问模板里有说明，不要提涉任何其它商业产品的内容，有问题的留言我已经删掉了。 实际上还有一个方式，就是你新建一个用户，默认不要勾选媒体库这个权限，显示的就是默认第一个菜单。
> 
> 如果是只有自己一个人用，还是不是很方便。相当于有两个账户了。还是建议按楼主所说的那样，直接给个设置项，用户自己选是用媒体库还是推荐榜单还是站点信息啥的作为首页。或者说NT后续做一个统一的dashboard仪表盘页面，来显示各种统计数据和综合性数据。这个dashboard可以让用户来添加一些小工具。也是一个不错的方案。很多管理系统都有类似的仪表盘页面作为首页

支持，一个专门的首页也很棒。我还YY两个其他想法，哈哈。

方案1、可以允许不配置媒体库，如果不配置媒体库，则直接不显示媒体库页面在菜单中。
方案2、设置页面可以设置隐藏模块，管理员可以配置除了设置模块以外的其他模块设置为隐藏，这样即使有权限，也不能看到。

**Comment by 120318** [comment]
方案二是好的，看优先级了。

**Comment by cikezhu** [comment]
最新版本 v2.9.0 自定义JavaScript 输入以下代码
需要注意的是
榜单推荐把'service'换成'ranking'
站点数据统计换成 'statistics'

`!window.history.state?.page && setTimeout( () => {
    // 跳转服务
    navmenu('service')
}, 300)`

**Comment by xiaoquexing1** [comment]
> 最新版本 v2.9.0 自定义JavaScript 输入以下代码 需要注意的是 榜单推荐把'service'换成'ranking' 站点数据统计换成 'statistics'
> 
> `!window.history.state?.page && setTimeout( () => { // 跳转服务 navmenu('service') }, 300)`

大佬厉害！已使用，确实效果不错。不过还是期待有个dashboard仪表盘页面来顶替首页

**Comment by luoxiao-xy** [comment]
> 最新版本 v2.9.0 自定义JavaScript 输入以下代码 需要注意的是 榜单推荐把'service'换成'ranking' 站点数据统计换成 'statistics'
> 
> `!window.history.state?.page && setTimeout( () => { // 跳转服务 navmenu('service') }, 300)`

用上了，很棒！不过普通用户怕是用不来这个哟，得翻翻issues才行。

**Comment by cikezhu** [comment]
> > 最新版本 v2.9.0 自定义JavaScript 输入以下代码 需要注意的是 榜单推荐把'service'换成'ranking' 站点数据统计换成 'statistics'
> > `!window.history.state?.page && setTimeout( () => { // 跳转服务 navmenu('service') }, 300)`
> 
> 用上了，很棒！不过普通用户怕是用不来这个哟，得翻翻issues才行。

改进版本

`if (!window.history.state?.page) {
    const my_custom_goto_page = document.querySelector("#page_content");
    const my_custom_goto_rval = setInterval(() => {
        if (!my_custom_goto_page.hasAttribute("hidden")) {
            navmenu('service');
            clearInterval(my_custom_goto_rval);
        }
    }, 50)
}`

**Comment by luoxiao-xy** [comment]
> > > 最新版本 v2.9.0 自定义JavaScript 输入以下代码 需要注意的是 榜单推荐把'service'换成'ranking' 站点数据统计换成 'statistics'
> > > `!window.history.state?.page && setTimeout( () => { // 跳转服务 navmenu('service') }, 300)`
> > 
> > 
> > 用上了，很棒！不过普通用户怕是用不来这个哟，得翻翻issues才行。
> 
> 改进版本
> 
> `if (!window.history.state?.page) { const my_custom_goto_page = document.querySelector("#page_content"); const my_custom_goto_rval = setInterval(() => { if (!my_custom_goto_page.hasAttribute("hidden")) { navmenu('service'); clearInterval(my_custom_goto_rval); } }, 50) }`

@jxxghp 现在3.0以后代码失效了。还是建议设置中可以直接设置修改默认主页。
