### ISSUE TITLE
希望实现与alist的联动

### ISSUE THREAD

**Issue by Loyoan** [jxxghp/nas-tools#3367]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.2
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望能实现alist的联动，其实就是能够在资料库中挂载webdav，尝试了很多办法比如吧webdav挂载为群晖的本地盘，再来nastool里面添加媒体文件夹，都不太理想，要么就是操作复杂，要么就是不稳定。
> 希望大佬能添加一个webdav挂载为媒体文件夹的功能，或者以订阅的方式监控webdav里的文件，有新增就通过下载器下载到本地，这样也就避免了对webdav里文件操作可能引发的问题。

>有个想法：在自定义订阅中可以添加webdav，只需实现指定文件夹下的增量检测就好了，因为使用alist的用户大部分都是薅某里网盘的分享链接，而且需要订阅的肯定是电视剧。只要检测到新增的文件就下载到本地，在设置新订阅的同时就设置好剧名、年份，下载时候系统直接重命名，下载完成直接nastool刮削处理，美滋滋

## 这个功能有什么可以参考的资料吗？

> [Alist说明文档](https://alist.nn.ci/zh/guide/)

**Comment by Loyoan** [comment]
> 网盘，啥命名的文件都有。。。。而且啥质量都有

这些问题就不关nastool的事了，nastool只是负责检查新增文件并下载，识别不出来的话直接报识别失败就行了，让用户自己手动修改辅助识别。

如果命名不规范的话用户可以先转存到自己网盘的其他文件夹，重命名以后再移动到被监控的文件夹里面就好了

所以用户需要做的就是如何找到规范命名的分享链接，或者自己把名字统一

**Comment by L-Trump** [comment]
如果在NAS上，可以使用群晖CloudSync或者威联通HBS3用双向同步的方式同步Webdav文件夹和本地文件夹，再使用目录同步功能分类同步至媒体库目录。和网盘间同步的逻辑肯定还是这些现成的应用做的好

**Comment by Loyoan** [comment]
> 如果在NAS上，可以使用群晖CloudSync或者威联通HBS3用双向同步的方式同步Webdav文件夹和本地文件夹，再使用目录同步功能分类同步至媒体库目录。和网盘间同步的逻辑肯定还是这些现成的应用做的好

CloudSync从网盘同步到本地相当于下载，需要等待一定时间才能下载到完整的文件，我现在文件同步方式采用的是移动，有没有什么设置方法可以确保文件下载完成以后再来进行同步操作呢？

**Comment by jxxghp** [comment]
不会考虑对接alist。
如果需要监控alist挂载后的路程，可以试试将配置文件中 sync/nas_sys 这个变量调整为windows看看是否能实现监控（linux监控基于事件效率高，调整为windows效率低但是兼容性强），如果不行或者有其它问题那就无解了。

**Comment by jxxghp** [comment]
```
sync:
  # 监控目录配置已转移至数据库
  # 【监控目录操作系统类型】：windows、linux。如果是windows，目录同步功能性能会比较差，会导致NAS不能休眠，除非是挂载的windows的远程共享目录或者是windows的docker，否则建议设置为linux
  nas_sys: linux
```
