### ISSUE TITLE
HDC 搜索相同资源，使用搜索或者订阅功能时无法搜索到全部资源

### ISSUE THREAD

**Issue by luyufan498** [jxxghp/nas-tools#3369]
![微信截图_20230207213950](https://user-images.githubusercontent.com/6166841/217261875-af41abe7-fbf6-4b61-8ed4-7f575ece1fbf.png)
![微信截图_20230207214127](https://user-images.githubusercontent.com/6166841/217261879-04681116-d714-4d67-bbd3-005a250e5635.png)

以上是我搜索中国奇谭时的现象，使用订阅或者搜索时，4k的几个资源都没有显示，但是在站点资源搜索时其实能看到有4K的资源

版本：2.9.0

版本：2.8.3的时候，搜索是能够搜到4K的几个种子的，但是订阅搜不到。目前是订阅能搜索到种子，但是比实际数量少。

**Comment by jxxghp** [comment]
订阅和搜索都是会识别和过滤的，具体你要看日志是什么情况过滤掉了（过滤规则、命名、与TMDB的网络都会影响）。
如果需要显示内容全可以用pp助手之类的工具。
