### ISSUE TITLE
字幕下载结果可以增加一个通知吗？

### ISSUE THREAD

**Issue by log-time** [jxxghp/nas-tools#337]
### 目前通过NASTOOL联动调用csf自动下载字幕的体验很不错，但是字幕下载请求发送后缺少下载结果的反馈，不知这一块的实现是否比较麻烦？
Jun 21 22:39:50 172.17.0.16 log.py: 【RMT】开始处理：/Media/Downloads/Video/电影/Doctor.Strange.in.the.Multiverse.of.Madness.2022.1080p.WEB-DL.DDP5.1.Atmos.H.264-EVO.mkv
Jun 21 22:39:50 172.17.0.16 log.py: 【RMT】正在转移文件：Doctor.Strange.in.the.Multiverse.of.Madness.2022.1080p.WEB-DL.DDP5.1.Atmos.H.264-EVO.mkv 到 奇异博士2：疯狂多元宇宙 (2022) - 1080p.mkv
Jun 21 22:39:50 172.17.0.16 log.py: 【RMT】文件 Doctor.Strange.in.the.Multiverse.of.Madness.2022.1080p.WEB-DL.DDP5.1.Atmos.H.264-EVO.mkv 硬链接完成
Jun 21 22:39:50 172.17.0.16 log.py: 【MSG】发送wechat消息：title=奇异博士2：疯狂多元宇宙 (2022) 转移完成, text=评分：7.4，类型：电影，类别：外语电影，质量：WEB-DL 1080p，大小：5.83G，来自：目录同步
Jun 21 22:39:51 172.17.0.16 log.py: 【EMBY】开始刷新Emby媒体库...
Jun 21 22:39:51 172.17.0.16 log.py: 【EMBY】Emby媒体库刷新完成
Jun 21 22:39:51 172.17.0.16 log.py: 【RMT】/Media/Downloads/Video/电影/Doctor.Strange.in.the.Multiverse.of.Madness.2022.1080p.WEB-DL.DDP5.1.Atmos.H.264-EVO.mkv 处理完成，总数：1，失败：0
Jun 21 22:39:51 172.17.0.16 log.py: 【SUBTITLE】通知ChineseSubFinder下载字幕: /Media/.媒体库/影视/电影/外语电影/奇异博士2：疯狂多元宇宙 (2022)/奇异博士2：疯狂多元宇宙 (2022) - 1080p.mkv
Jun 21 22:39:51 172.17.0.16 log.py: 【SUBTITLE】ChineseSubFinder任务添加成功：528dbe28df2c1935705bf149344b53536575975a2e83d1e1621a17bce363f81c
### CSF的日志：
[INFO]: 2022-06-21 22:39:55 - ------------------------------------------
[INFO]: 2022-06-21 22:39:55 - OneTimeSubtitleScanStart#528dbe28df2c1935705bf149344b53536575975a2e83d1e1621a17bce363f81c
[INFO]: 2022-06-21 22:39:55 - Queue 1 DlSub Start /Media/.媒体库/影视/电影/外语电影/奇异博士2：疯狂多元宇宙 (2022)/奇异博士2：疯狂多元宇宙 (2022) - 1080p.mkv
[INFO]: 2022-06-21 22:39:55 - Queue 1 xunlei /Media/.媒体库/影视/电影/外语电影/奇异博士2：疯狂多元宇宙 (2022)/奇异博士2：疯狂多元宇宙 (2022) - 1080p.mkv
[INFO]: 2022-06-21 22:39:55 - Queue 1 xunlei Start...
[INFO]: 2022-06-21 22:40:46 - Queue 1 xunlei End...
[INFO]: 2022-06-21 22:40:46 - Queue 1 shooter /Media/.媒体库/影视/电影/外语电影/奇异博士2：疯狂多元宇宙 (2022)/奇异博士2：疯狂多元宇宙 (2022) - 1080p.mkv
[INFO]: 2022-06-21 22:40:46 - Queue 1 shooter Start...
[INFO]: 2022-06-21 22:40:47 - Queue 1 shooter End...
[INFO]: 2022-06-21 22:40:47 - Queue 1 a4k /Media/.媒体库/影视/电影/外语电影/奇异博士2：疯狂多元宇宙 (2022)/奇异博士2：疯狂多元宇宙 (2022) - 1080p.mkv
[INFO]: 2022-06-21 22:40:47 - Queue 1 a4k Start...

2022/06/21 22:41:05 [31;1m/home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/pkg/mix_media_info/mix_media_info.go:126 [35;1mrecord not found
[0m[33m[0.040ms] [34;1m[rows:0][0m SELECT * FROM `media_infos` WHERE `tmdb_id` = "453395" LIMIT 1
[INFO]: 2022-06-21 22:41:05 - a4k searchKeyword 奇异博士2：疯狂多元宇宙 2022
[INFO]: 2022-06-21 22:41:22 - [GetPublicIP] ipCallback({ip:"*"})
[INFO]: 2022-06-21 22:41:27 - Queue 1 a4k End...
[INFO]: 2022-06-21 22:41:27 - Queue 1 csf /Media/.媒体库/影视/电影/外语电影/奇异博士2：疯狂多元宇宙 (2022)/奇异博士2：疯狂多元宇宙 (2022) - 1080p.mkv
[INFO]: 2022-06-21 22:41:27 - Queue 1 csf Start...
[INFO]: 2022-06-21 22:41:30 - Find Best Subtitle, MatchVideoFeature == true 093e3dc5f76a4f0c684c43e10cbdf217f408a0e484082b4e59d864ebd26cd50a
[INFO]: 2022-06-21 22:41:32 - will wait 5 s 2 ask download sub
[INFO]: 2022-06-21 22:41:32 - wait 2 ask download sub
[WARNING]: 2022-06-21 22:41:41 - status code: 200
[INFO]: 2022-06-21 22:41:41 - Queue 1 csf End...
[INFO]: 2022-06-21 22:41:41 - Queue 1 subhd /Media/.媒体库/影视/电影/外语电影/奇异博士2：疯狂多元宇宙 (2022)/奇异博士2：疯狂多元宇宙 (2022) - 1080p.mkv
[INFO]: 2022-06-21 22:41:41 - [GetPublicIP] ipCallback({ip:"*"})
[INFO]: 2022-06-21 22:41:41 - subhd DailyDownloadLimit: 20 Now Is: 0
[INFO]: 2022-06-21 22:41:41 - Queue 1 subhd Start...
[INFO]: 2022-06-21 22:41:41 - Search Keyword: tt9419884
[ERROR]: 2022-06-21 22:42:57 - subhd GetEx Doctor.Strange.in.the.Multiverse.of.Madness.2022.1080p.WEB-DL.DDP5.1.Atmos.H.264-EVOjames丶xz 0 0 subhd step2ex can not find download btn
[INFO]: 2022-06-21 22:42:58 - subhd /Media/.媒体库/影视/电影/外语电影/奇异博士2：疯狂多元宇宙 (2022)/奇异博士2：疯狂多元宇宙 (2022) - 1080p.mkv No subtitle found KeyWord: tt9419884
[INFO]: 2022-06-21 22:42:58 - Search Keyword: 奇异博士2：疯狂多元宇宙 2022
[INFO]: 2022-06-21 22:43:57 - [GetPublicIP] ipCallback({ip:"*"})
[INFO]: 2022-06-21 22:43:58 - Queue 1 subhd End...
[INFO]: 2022-06-21 22:43:58 - Queue 1 DlSub End /Media/.媒体库/影视/电影/外语电影/奇异博士2：疯狂多元宇宙 (2022)/奇异博士2：疯狂多元宇宙 (2022) - 1080p.mkv
[INFO]: 2022-06-21 22:43:59 - ----------------------------------
[INFO]: 2022-06-21 22:43:59 - OrgSubName: [subhd]_0_Doctor.Strange.in.the.Multiverse.of.Madness.2022.1080p.WEB-DL.DDP5.1.Atmos.H.264-EVO.简体&英文.ass
[INFO]: 2022-06-21 22:43:59 - SubDownAt: /Media/.媒体库/影视/电影/外语电影/奇异博士2：疯狂多元宇宙 (2022)/奇异博士2：疯狂多元宇宙 (2022) - 1080p.chinese(简英).default.ass
[INFO]: 2022-06-21 22:43:59 - ----------------------------------
[ERROR]: 2022-06-21 22:43:59 - SaveMultiSub: false, writeSubFile2VideoPath, Error: exit status 1
[INFO]: 2022-06-21 22:43:59 - CloseChrome Start...
[WARNING]: 2022-06-21 22:43:59 - CloseChrome exit status 1
[INFO]: 2022-06-21 22:43:59 - CloseChrome End
[INFO]: 2022-06-21 22:43:59 - OneTimeSubtitleScanEnd
[INFO]: 2022-06-21 22:43:59 - ------------------------------------------

**Comment by jxxghp** [comment]
这个是异步的，通知要csf做。

**Comment by log-time** [comment]
好的，那我先关闭吧
