### ISSUE TITLE
设置nas-tools转移方式是复制的时候，文件复制有问题，无法播放

### ISSUE THREAD

**Issue by Vencenty** [jxxghp/nas-tools#3372]
> NAStool 版本: v2.9.0
>
<img width="548" alt="image" src="https://user-images.githubusercontent.com/24696378/217272257-26bce13f-2c23-4b8c-b7bf-530ded728d08.png">

复制到目标位置以后文件大小发生变化，导致文件无法打开。

设置的文件转移方式设置为【复制】
目录同步方式也是【复制】
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/24696378/217273153-4979faf4-7bf5-425d-a0cc-1b5e23e00d67.png">

**Comment by Vencenty** [comment]
请问是BUG么，还是我设置有问题

**Comment by Sliversea** [comment]
还是换成硬链接吧，之前我用的复制也是无法播放

**Comment by jxxghp** [comment]
用复制模式的目录同步，下载器里要打开添加未完成的后缀名选项

**Comment by Vencenty** [comment]
@jxxghp 你好，我用的qbittorrent，能截图看一下吗？或者可以把这个问题写到FAQ里，我看也有人也碰到这个问题了

**Comment by Sliversea** [comment]
![image](https://user-images.githubusercontent.com/72388397/217420247-ad89b3fb-9944-492e-bede-98b41038b5f4.png)
![image](https://user-images.githubusercontent.com/72388397/217420287-5bf237c3-78bf-4b6e-a677-2450ee55c1a1.png)
上面是qb的下面是transmission的 @Vencenty

**Comment by Vencenty** [comment]
@Sliversea 万分感谢

**Comment by jxxghp** [comment]
群里的那个小秘书应该有了，可以去翻一下
