### ISSUE TITLE
pikpak始终设置测试失败

### ISSUE THREAD

**Issue by Oldming1** [jxxghp/nas-tools#3375]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.0
>
> 环境: docker

配置下载器为pikpak时，添加账号密码以及代理服务器配置后始终测试失败。同账号在alist中配置正常，排除账号密码错误原因。望大佬分析一下，谢谢
![image](https://user-images.githubusercontent.com/86954573/217300504-ef4ffa74-1d6f-471b-86f7-a92c3fded122.png)

**Comment by hzmabin** [comment]
我用手机号登录，不知道+86的格式是什么，+86139xxxxxxxx还是+86-139xxxxxxxx，望作者明示 。。。
