### ISSUE TITLE
关于订阅指定站点的问题。

### ISSUE THREAD

**Issue by 26712681** [jxxghp/nas-tools#338]
老大，这个订阅的地方站点多了好麻烦，很多站点我只是配置在里面看数据的。
现在是默认全选，每次都要点几十下鼠标。
能不能做成默认空，自己选。然后加一个“全选”按钮。
这样两者都能兼顾
![image](https://user-images.githubusercontent.com/77581926/174916228-80cf438d-1598-4b41-87d9-c4326e1a2eca.png)

**Comment by log-time** [comment]
如果默认全否问题比较多的话，手动添加时也可以增加一个批量清除站点选择的按钮，效果等同

**Comment by 26712681** [comment]
> 

有道理  默认空的话会和微信订阅的时候冲突  那就加一个全不选的按钮吧

**Comment by dlovew** [comment]
现在增加了一个订阅可以选择搜索站点，要点更多次了，这个全选或者全不选的功能很迫切，另外希望微信自动订阅可以选择站点

**Comment by jxxghp** [comment]
a9c94b9bae86496fc8cfec30c165577250a4a3aa
