### ISSUE TITLE
[BUG]更新到2.9.0后，qb指定下载目录失效。

### ISSUE THREAD

**Issue by likecreep** [jxxghp/nas-tools#3380]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.9.0
>
> 环境: docker

更新后，新下载的电影不再根据文件分类保存到设置的qb的电影下载目录 /downloads/movie， 而是始终保存到qb的默认下载目录/dowanloads/， 导致下载完成后的 转移出错，提示文件不存在。  需要手动 将 /downloads/下的文件， 移动到 /downloads/movie之后， 才能通过 nas-tools 转移。

**Comment by Ekkone** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本: 2.9.0
> > 环境: docker
> 
> 更新后，新下载的电影不再根据文件分类保存到设置的qb的电影下载目录 /downloads/movie， 而是始终保存到qb的默认下载目录/dowanloads/， 导致下载完成后的 转移出错，提示文件不存在。 需要手动 将 /downloads/下的文件， 移动到 /downloads/movie之后， 才能通过 nas-tools 转移。

我也遇到了这个问题，请问怎么解决的？

**Comment by likecreep** [comment]
> > ## 你使用的 NAStool 是什么版本，什么环境？
> > > NAStool 版本: 2.9.0
> > > 环境: docker
> > 
> > 
> > 更新后，新下载的电影不再根据文件分类保存到设置的qb的电影下载目录 /downloads/movie， 而是始终保存到qb的默认下载目录/dowanloads/， 导致下载完成后的 转移出错，提示文件不存在。 需要手动 将 /downloads/下的文件， 移动到 /downloads/movie之后， 才能通过 nas-tools 转移。
> 
> 我也遇到了这个问题，请问怎么解决的？

重启docker
