### ISSUE TITLE
关于更新后高级搜索关闭了全选的问题

### ISSUE THREAD

**Issue by 101letters** [jxxghp/nas-tools#3386]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.9.0
>
> 环境: synology

2.9版本更新后，高级搜索没办法选中全部站点，虽然解决了对站点的压力，但是通过在豆瓣搜索直接找到的资源并不能正确识别所需要的资源，所以希望大佬们还是可以考虑在高级搜索的地方开启全选的选项，不然一个站点一个站点过于麻烦了

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Zhangqian0375** [comment]
和楼主一样的需求，希望修改回来，谢谢

**Comment by jxxghp** [comment]
好吧，改回去了。
之前主要是想引导大家尽量使用默认的搜索，实在要找个别资源的再手工一个个站查，最大化减少站点压力。

**Comment by 101letters** [comment]
谢谢大佬
