### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by zui-lang** [jxxghp/nas-tools#3389]
版本2.9（好像2.8.3也有这个问题）
安装环境unraid6.11.5，docker
![image](https://user-images.githubusercontent.com/77880495/217468266-a1843829-e8e5-45ed-b43f-912a68f49fbd.png)![image](https://user-images.githubusercontent.com/77880495/217468273-8d8bcee9-c1a8-4a17-a27a-fbe7fe45c369.png)
下载器，字幕索引器，播放器，种子索引器都有这个问题，都是安装在同一服务器的docker中，但是127.0.0.1却无法使用

**Comment by jxxghp** [comment]
1、提问请按模板。
2、127.0.0.1是否可用，决定于你的docker网络配置，理解下host和bridge模式的区别。
