### ISSUE TITLE
关于订阅指定站点的问题2

### ISSUE THREAD

**Issue by 26712681** [jxxghp/nas-tools#339]
刚才订阅的一部电影 并不是走的指定的网站
是不是因为新加入的时候调用的搜索，所以指定网站并没有起作用。刚好这电影已经出了，所以在其他网站上下载了

**Comment by 26712681** [comment]
我觉得这不是问题

**Comment by dlovew** [comment]
我觉得可以优化一下，这里面有个优先级的问题，是规则优先，索引器的站点顺序，还是订阅指定的站点优先
而且后续rss也不能按照指定站点下载资源！
