### ISSUE TITLE
内存爆满导致假死，希望增加最大内存限制

### ISSUE THREAD

**Issue by Ador-able** [jxxghp/nas-tools#3393]
> NAStool 版本: v2.9.0

> 环境: docker （windows server）

正常状态下剩余可用内存为3GB

## 你想要新增或者改进什么功能？

> 希望增加最大内存限制，或者减少搜索时的并发数目，内建索引一下子创建18个chrome太占内存了，比如最高创建10个（能配置并发数目最好）

在订阅正在进行时，手动搜索其他影片，导致内存瞬间飙升，榨干全部的内存（3GB），导致报错：OSError: [Errno 12] Out of memory: '/config/tmdb.dat'

紧接着程序进入假死状态，无任何响应，容器也无法停止或删除，连带着整个docker无法正常提供服务，只能重启整个docker环境才能恢复正常。

附上相关日志：报错在600行
[log.log](https://github.com/jxxghp/nas-tools/files/10685482/log.log)

**Comment by jxxghp** [comment]
是站点全开了浏览器仿真吗？

**Comment by Ador-able** [comment]
> 是站点全开了浏览器仿真吗？

![image](https://user-images.githubusercontent.com/17660606/217718891-8c0d63b0-0ec1-408a-9d36-6c63eb8d1bae.png)
全新部署，没有配置任何站点，只连接了qbit，emby，使用内建索引（公开站点全选），每当开始搜索，会创建大量的chrome进程，如果订阅同时也在搜索，就很容易榨干全部的内存。

**Comment by jxxghp** [comment]
目前已经限制并发为10个线程，另外只有个别站点才会开浏览器，机器性能不行那几个可以不选：ext skrbt thepiratebay

docker本身也带内存限制功能。
