### ISSUE TITLE
希望大佬可以增加手动识别中自定义识别路径中可以显示文件

### ISSUE THREAD

**Issue by okxiongmao** [jxxghp/nas-tools#3394]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x v2.9.0 3ee22fa
> 环境: docker 

## 你想要新增或者改进什么功能？

> 媒体整理-手动识别-自定义识别里面输入路径需要转移的目录或文件只能看到文件夹看不到影音文件，pt站点部分资源下载下来只有一个单独视频文件 不存在于一个单独的文件夹中，希望在输入路径里面可以显示和选择文件，进行自定义识别。

**Comment by jxxghp** [comment]
通过文件管理功能转移
