### ISSUE TITLE
windwos版本2.9 一直转圈 进不去 2.7能进

### ISSUE THREAD

**Issue by yexiaozhulin** [jxxghp/nas-tools#3395]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.9
> 环境: docker or windows or synology
windows
## 你想要新增或者改进什么功能？

windows版本2.9 一直转圈，进不去。2.7能进。 我换了台windwos10能进，但这台windows11 重启 ，删除所有配置文件重新打开也进不去。手机登录也进不去。

浏览器日志
 
 GET http://localhost:3000/static/img/filetree/swf.png 404 (NOT FOUND)
index.js:2056 
 
 GET http://localhost:3000/static/img/filetree/disk-image.png 404 (NOT FOUND)
index.js:2056 
 
 GET http://localhost:3000/static/img/filetree/cdrom.png 404 (NOT FOUND)
index.js:2056 
 
 GET http://localhost:3000/static/img/filetree/plg.png 404 (NOT FOUND)
index.js:2056 
 
 GET http://localhost:3000/static/css/img/jsoneditor-icons.svg 404 (NOT FOUND)
lit-index.js:1 
 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
index.js:2056 
 
 GET http://localhost:3000/static/img/filetree/swf.png 404 (NOT FOUND)
index.js:2056 
 
 GET http://localhost:3000/static/img/filetree/disk-image.png 404 (NOT FOUND)
index.js:2056 
 
 GET http://localhost:3000/static/img/filetree/cdrom.png 404 (NOT FOUND)
index.js:2056 
 
 GET http://localhost:3000/static/img/filetree/plg.png 404 (NOT FOUND)
index.js:2056 
 
 GET http://localhost:3000/static/css/img/jsoneditor-icons.svg 404 (NOT FOUND)
DevTools failed to load source map: Could not load content for http://localhost:3000/static/css/dropzone.css.map: HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by c939984606** [comment]
电脑可以进去，但是ios chrome Safari 一直转圈圈进不去

**Comment by jxxghp** [comment]
404是加载不到资源，无论重现，分析不了是什么情况，自己研究下。
