### ISSUE TITLE
限速功能增加自定义下载器ip

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#3397]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or synology

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

播放器限速功能增加指定ip
主要是想在播放时给保种的下载器限速。。能增加个手动输入ip么。。
只支持一个客户端无所谓。。但是希望能增加自定义ip

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by link2fun** [comment]
![image](https://user-images.githubusercontent.com/19241982/217682949-b5603370-8a54-4678-9053-1d837822b419.png)
这个不是? 位置 设置 ->下载器

**Comment by Tartarus2014** [comment]
> ![image](https://user-images.githubusercontent.com/19241982/217682949-b5603370-8a54-4678-9053-1d837822b419.png)
> 这个不是? 位置 设置 ->下载器

我是下载qb和保种qb分开的 目前下载器这里只能选定一个下载器。
所以想让限速那里 可以自定义ip

**Comment by lengxii** [comment]
支持下
