### ISSUE TITLE
我的媒体库数值显示缺失bug

### ISSUE THREAD

**Issue by xnoods** [jxxghp/nas-tools#3401]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.0 226b07e
>
> 环境: synology下的docker

## 你想要新增或者改进什么功能？

> 我的媒体库--里面显示的数值缺失问题，以下是我用nas-tools分别链接emby和plex的截图

备注：plex和emby均已同步过媒体库，由于2个库的内容不一样，所以不用纠结数字问题，只是有没有的问题

设置-媒体服务器-连接plex的情况下的截图
![image](https://user-images.githubusercontent.com/18209713/217690148-628d5ae7-0de7-4179-89bf-04d400beb8b1.png)

设置-媒体服务器-连接emby的情况下的截图
![image](https://user-images.githubusercontent.com/18209713/217690031-f6f59ca3-e818-4232-9e6c-411c57c54553.png)

**Comment by jxxghp** [comment]
plex不支持显示集数
