### ISSUE TITLE
通过nastool 下载的种子无“NASTOOL” 标签

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/nas-tools#3404]
最近在研究 “只管理nastool 下载” 功能时候，发现打开开关时候无法自动转移下载文件

于是通过排查发现，我所有的种子文件，都没有成功打上 “NASTOOL” 这个标签

设置如下：
<img width="2105" alt="image" src="https://user-images.githubusercontent.com/51367628/217705172-e9d86c08-699b-448c-9caf-f9f2f8583aa6.png">

TM版本 3.00   DSM 7.1

**Comment by paysenyu** [comment]
<img width="277" alt="image" src="https://user-images.githubusercontent.com/51367628/217705473-a06f6bd8-fc87-4210-9703-eb4f5ffea4ea.png">

**Comment by jxxghp** [comment]
TR的标签不是这个用户标签，本来UI就不显示
