### ISSUE TITLE
rmt 和 sync 同时提示转移错误

### ISSUE THREAD

**Issue by vvkkhjt** [jxxghp/nas-tools#3408]
![Screenshot_20230209_114452](https://user-images.githubusercontent.com/12765476/217712896-606326b2-b4c4-4aee-adc0-d1d8cbf0ec6b.jpg)

rmt在转移 rmt和sync同时提示转移错误 no such file

已关闭下载软件监控

![Screenshot_20230209_114750](https://user-images.githubusercontent.com/12765476/217713260-ef1fe92d-2e23-4627-9985-8b06645f2500.jpg)

**Comment by jxxghp** [comment]
提问按模板，基础问题请自己研究或者交流群里寻求帮助。
