### ISSUE TITLE
pikpak测试失败

### ISSUE THREAD

**Issue by edhnt455** [jxxghp/nas-tools#3411]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.0
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？
用户名用邮箱和app中的用户名都试过了，连接不上，请问是什么原因
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by Oldming1** [comment]
更新最新版本测试是正常，但是无法添加下载，添加磁力下载提示网络错误

**Comment by jxxghp** [comment]
#3418
