### ISSUE TITLE
目录同步后删除空文件夹导致不能继续刮削下一个文件夹

### ISSUE THREAD

**Issue by pc0289** [jxxghp/nas-tools#3412]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.0
>
> 环境: windows

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

目前移动模式下，刮削文件夹后如果文件夹为空，会自动删除文件夹

遇到问题情况如下：

使用Cloud Drive挂载的115网络盘，NASTOOL自动删除文件夹时，文件夹会被删掉，但会自动重新生成相同名称的文件夹，导致刮削中止，比如刮削文件夹下存在两个文件夹A和B，A 刮削完成后会删除A文件夹，但立刻生成一个名为A的文件夹（通过创建时间可以发现是新建的），这时候就不会开始B文件夹的刮削

不确定是多文件夹导致的只能刮削其中一个文件夹，刮削完空了就认为刮削任务结束

还是由于新建了一个文件夹导致了什么内部错误，中止了下一个文件夹的刮削

希望可以解决该bug，

如果新建文件夹导致的，最简单是可以增加一个开关，可以选择刮削完成后是否删除空文件夹

如果是多文件夹导致的，希望可以刮完一个继续完成下一个

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

暂时并没有

**Comment by pc0289** [comment]
试了一下，如果在其中一个文件夹中放一个小文件，刮削完成后不是空文件夹，不会执行自动删除，就可以刮削另一个文件夹

所以只要给一个选项，可以选择不删除空文件夹就行啦

**Comment by jxxghp** [comment]
#3454
