### ISSUE TITLE
2.9版本在IOS 14系统上出现能登陆但打不开主页，一直转圈圈

### ISSUE THREAD

**Issue by c939984606** [jxxghp/nas-tools#3414]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.0
>
> 环境: docker  windows 

升级最新版后iOS 浏览器一直转圈，可以进登录页面但是，登录后一直转圈，试过升级，全新安装，docker ，windows方式，安卓手机却能访问，iOS系统版本 14.3 ，iPhone12 Pro max

![微信图片_20230209155858](https://user-images.githubusercontent.com/34211368/217751760-9d36a8e1-5ee7-4811-a60d-0e620ffca92d.jpg)

**Comment by c939984606** [comment]
上图是chrome， 另外自带的Safari访问也一样

**Comment by c939984606** [comment]
又测试 iPhone13 Pro可以打开，

**Comment by c939984606** [comment]
iPhone13 Pro Max 也可以打开，不知道是不是我手机原因？还是系统原因？

**Comment by c939984606** [comment]
找不到原因，回到老版本了，老版本一切正常

**Comment by c939984606** [comment]
经群内测试2.9版本在IOS 14系统上出现能登陆但打不开主页，一直转圈圈，2.8版本没有，ios15也没有

**Comment by jxxghp** [comment]
#3457
