### ISSUE TITLE
2.9.0版本搜索和RSS有bug

### ISSUE THREAD

**Issue by Zhangqian0375** [jxxghp/nas-tools#3419]
> NAStool 版本: v2.9.0

> 环境: docker synology

## 你想要新增或者改进什么功能？

> 之前2.8版本馒头和TTG搜索和订阅正常。
现在升级版本后搜不到结果了，站点资源里面也是空的！
希望大佬解决，谢谢

**Comment by eeezae** [comment]
我也是馒头一会有，一会去搜的时候又空了，，看站点资源列表的时候也是空的，测试连通性刮削站和pt站没有问题，日志请求没有数据，复制日志的链接进去几十条数据，也没有设置过滤规则，真心累

**Comment by jxxghp** [comment]
试一下打开馒头和TTG的浏览器仿真看看。馒头的CF墙比较牛，经常会过不了。
心累就别用了。

**Comment by jxxghp** [comment]
还有就是馒头的cookie和UA一定要一一对应，在站点维护里面设置

**Comment by Zhangqian0375** [comment]
馒头现在测试没问题了，TTG还是不行

**Comment by jxxghp** [comment]
ttg要开仿真
