### ISSUE TITLE
本地部署时，程序无法退出

### ISSUE THREAD

**Issue by skymkmk** [jxxghp/nas-tools#3424]
本地部署软件时，无法通过 Ctrl + C 和 systemctl stop 停止程序。经查，run.py 捕获了 SIGINT 和 SIGTERM 信号进行了处理，但是处理函数只对 docker 环境进行了处理，我想问一下这是有意设计成这样的吗？感谢作者的付出~

**Comment by c939984606** [comment]
ps -ef | grep "run.py" | grep -v grep | awk '{print $2}' | xargs -n1 kill

**Comment by jxxghp** [comment]
是有意的，之前未限制时群晖套件会经常出现自动退出的情况，原因不明。

**Comment by skymkmk** [comment]
好的，谢谢解答
