### ISSUE TITLE
自动删种功能“只管理NAS-TOOLS下载”bug

### ISSUE THREAD

**Issue by yanyu469** [jxxghp/nas-tools#3428]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v2.9.0 226b07e
>
> 环境: docker 

自动删种功能“只管理NAS-TOOLS下载”  选择了否，未通过nas-tools里下载的种子仍然无法通过策略进行删除
![image](https://user-images.githubusercontent.com/32787818/218027427-c747df62-6c9a-468f-96c5-4373d7c08c1c.png)

**Comment by jxxghp** [comment]
不是有这么多条件吗？都符合才会删除。哪个该删没删你得举例子，不然没法给你分析。
