### ISSUE TITLE
关于订阅的一点建议

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/nas-tools#343]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/51367628/174943395-476d27b9-d688-44fb-8dad-4dcb77466fb5.png">

请考虑在订阅处增加一个可选分辨率的选项，可以处理以下场景：

场景A： 订阅了《电影》， rss 中1080p先放出来，2160p后放出来， 结果rss自动下载了1080的资源。

场景B： 单独做站点规则排除1080p or 720p， 订阅的某些动漫只有1080p的则也会被排除。

**Comment by 26712681** [comment]
可以订阅的时候给一个增加一条规则的地方
这样可以指定格式  也可以指定其他东西  比如压制组  或者指定国语  或者特效字幕
这样是不是就能保证下载的东西绝对是自己想要的

**Comment by jxxghp** [comment]
在订阅站点里设

**Comment by paysenyu** [comment]
> 在订阅站点里设

![telegram-cloud-photo-size-5-6167874063180083088-y](https://user-images.githubusercontent.com/51367628/174982152-5bf67395-1314-489b-b45a-8fcf400b4494.jpg)

希望可以达到的效果，举个例子： 我订阅了奇异博士2，我只想要下载2160p的， 在目前默认情况下，因为1080p有人先上传了，rss 就自动获取到1080p的下载了，不符合我的需求。。
如果我在站点订阅的排除规则里面排除1080p，那么我另外订阅的动漫斗罗大陆就无法下载了，因为斗罗大陆只有1080p的。

所以现在的矛盾点就出来了，我能想到的方法是在订阅时候可以指定“关键词” 。 不知道是否有更好的办法。

**Comment by 26712681** [comment]
> 在订阅站点里设

不是一个意思哦，老大

我们提的意思是针对订阅的某一个电影，  比如订阅  蝙蝠侠  原盘|特效字幕 
希望只在rss到 这种特定版本的时候才给我下载，其他版本不要

如果是在站点上设置的话，是针对所有的电影了

**Comment by Mruser0** [comment]
高质量版本覆盖不就可以了嘛

**Comment by 26712681** [comment]
不光是下载量。他今天提到这个东西我突然想起对我们做收藏原盘也有用。
比如top榜的一些电影，我想收藏一些原盘diy的。我不想一个一个去搜索下载
我只要订阅好这个电影，指定好规则。网上更新了我要求的版本就会给我收藏下载。我觉得挺有用的

**Comment by Mruser0** [comment]
你想要的是高质量版本优先的匹配吧，但是常理来说，先出的1080p版能保证rss第一时间观看，后面谁也不清楚高质量版本出的具体时间，如果rss只订阅高质量版本收藏，那就无法保证rss第一时间追剧的初衷，个人觉得这个逻辑还是在洗版的逻辑里比较好

**Comment by log-time** [comment]
我也觉得这个逻辑放在后续洗版的逻辑里比较好，当然后续洗版的功能最好还能再完善下，现在仅仅依据文件大小进行洗版还是稍微有点简单了，不能照顾部分需求。
