### ISSUE TITLE
希望添加tvdb支持

### ISSUE THREAD

**Issue by xx569029747** [jxxghp/nas-tools#3430]
NAStool 版本:  v2.9.0 226b07e
环境: docker

你想要新增或者改进什么功能？

希望可以增加动漫类对tvdb的支持，tmdb对动漫的支持太差了，举例如：虚构推理tmdb不肯加第二季的信息，导致订阅第二季时查询不到信息无法进行订阅，而tvdb是正常的；还有目标是宝可梦大师，tmdb也不添加剧集信息，而是加到tv版那边去，也是导致无法订阅

**Comment by luxtiasco** [comment]
此种场景应使用TMDB的剧集组，能得到你所需要的`正确`分季

**Comment by xx569029747** [comment]
> 此种场景应使用TMDB的剧集组，能得到你所需要的`正确`分季

然而tmdb的分季就是错的，不清楚情况就点是吗？我又不是没举例，看下都不会是吧
