### ISSUE TITLE
是否可以支持arm架构

### ISSUE THREAD

**Issue by kingsnow129** [jxxghp/nas-tools#3431]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: latest
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 想要在nas的docker安装nas-tools，不过nas是arm架构的，可以增加支持arm架构的nas-tools么
pull的时候报错：

latest: Pulling from jxxghp/nas-tools
mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'

## 这个功能有什么可以参考的资料吗？

> 暂无，不过有不同的docker支持arm的，比如qbittorrent

**Comment by DDSDerek** [comment]
我这边解决了armv7镜像固件的问题，如果作者需要支持，我可以直接PR

**Comment by iveney** [comment]
> 我这边解决了armv7镜像构建的问题，如果作者需要支持，我可以直接PR

@DDSDerek 有兴趣，能 share 一下吗。试了一下发现似乎没有对应的 web.backend.user。
