### ISSUE TITLE
【功能需求】建议添加演员图片放入.actor目录的功能

### ISSUE THREAD

**Issue by reggiedev** [jxxghp/nas-tools#3436]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.0
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 希望添加功能，刮削的时候把演员图片放入.actor目录，最近发现一个emby的插件"Kodi .actors",可以把.actor下的图片导入到emby中从而解决演员图片缺失的问题
![1676025184723](https://user-images.githubusercontent.com/38652229/218070282-65e718c3-7feb-4d48-b6c8-a098011d49ec.png)
![图片](https://user-images.githubusercontent.com/38652229/218070395-e5b47b91-ead0-4a55-bfa7-ce6e7e19b7d1.png)
![图片](https://user-images.githubusercontent.com/38652229/218070952-c949eb61-d3cc-4ddf-9913-b895056e98ba.png)
![图片](https://user-images.githubusercontent.com/38652229/218071022-e1ed381d-3fe9-4432-900b-886b42e20211.png)

## 这个功能有什么可以参考的资料吗？

> 参考tmm的图片下载， emby插件地址https://emby.media/community/index.php?/topic/115978-media-actors-folder-import-export-standalone-plugin

**Comment by jxxghp** [comment]
emby等并不会读取，并没有什么用。
