### ISSUE TITLE
jellyfin将不同电视剧识别为国产剧的两个Season

### ISSUE THREAD

**Issue by TerminalReed** [jxxghp/nas-tools#3437]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.0 226b07e
>
> 环境: docker in QNAP

## 遇到的问题
下载了三体和狂飙两部国产剧，刮削时将下载的电视剧视为“国产剧”中国产剧的两个Season了。NASTools中电视剧目录同步的目的目录是/video/link/TV（硬链接以保种）；jellyfin媒体库目录同为/video/link/TV。两部剧未能分别显示
均由NASTools搜索下载

图片中“老版V星入侵迷你剧”为错误识别
![image](https://user-images.githubusercontent.com/30360824/218085644-570e9601-89c9-4bfc-8144-6270117758ad.png)

**Comment by Tartarus2014** [comment]
自己手动识别下不就可以了

**Comment by TerminalReed** [comment]
> 自己手动识别下不就可以了

手动识别之后依然是这个情况Orz 并且尝试将jellyfin中的媒体库路径设置为NASTools设定的电视剧媒体库路径下的/video/link/TV/国产剧，jellyfin无法读取任何电视剧信息

**Comment by Tartarus2014** [comment]
手动识别写正确剧的tmdb不就行了

**Comment by TerminalReed** [comment]
> 手动识别写正确剧的tmdb不就行了

感谢您的帮助呀，我使用一下条件进行了手动识别，结果依然不行，《我们与恶的距离》依然显示为某错误识别剧的某一季
![image](https://user-images.githubusercontent.com/30360824/218143819-3c358778-7225-4bb1-868e-74f0e3844816.png)
![image](https://user-images.githubusercontent.com/30360824/218143862-39f92186-6494-4789-86c0-195653438a0f.png)

**Comment by jxxghp** [comment]
jellyfin的识别跟这个项目的关系是？

**Comment by TerminalReed** [comment]
感觉是nastools刮削出了bug
