### ISSUE TITLE
关于向微信机器人直接发送种子链接或者磁力链接添加下载功能的建议

### ISSUE THREAD

**Issue by ycrobin** [jxxghp/nas-tools#344]
请大佬看能否实现直接向微信机器人发送种子链接或者磁力链接，就直接添加到下载器中进行下载的功能

**Comment by jxxghp** [comment]
这个功能很简单，但能说下使用场景吗

**Comment by ycrobin** [comment]
> 

其实需求很简单，我主要用NAS-TOOLS的主要目的是自动重命名和硬链接转移，我现在是QB和TR同时使用，TR用于PT站点下载和保种，QB主动添加磁力链接下载，大部分时候其实对影片的质量要求不是那么高，现在有小站是可以直接下载资源也挺方便，我需要复制磁力链接然后打开QB再去下载，如果直接复制丢微信，就给我下去也挺好。
所以很多时候我其实是手动在添加下载，选择下载路径，稍微麻烦。
另外微信端如果可以增加切换下载器的功能更好，需要去搜索PT站时候，我就切换TR，然后再搜索，需要直接小站找链接下载时候直接切换QB，然后丢磁力链接

**Comment by jxxghp** [comment]
还得指定公类，不然不知道下哪个目录。太麻烦了，没必要。
这个之前有人提过了。
