### ISSUE TITLE
站点管理->站点资源里的数据记录是来自于设置的RSS参数吗？好象又不是。建议在默认数据来源的基础上，增加RSS来源数据，并按最近发布时间排序

### ISSUE THREAD

**Issue by tianjincat** [jxxghp/nas-tools#3440]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.0
>
> 环境: docker

## 站点管理->站点资源里的数据记录是来自于设置的RSS参数吗？

> 我一般RSS只设置显示10条，我看分页显示了大量数据，我的理解应该不是来自于RSS定义。
建议：
1、在默认保留现有的数据来源基础上，增加另一个视图，数据仅来自于针对这个站点的RSS数据定义。如果是能够选择一到多个站点RSS，并在一个页面结果集里显示出来就更好了，这样一次看多站，效率会更高。
      因为很多时候只想看到符合自己定义条件RSS的数据，并针对这些数据再做选择是否下载，这样就不需要上网站去筛选下载了，会方便很多。
2、建议默认按最近发布时间排序
      因为大多数人的习惯都是默认去看最近发布的免费种子，并决定是否下载，默认按时间排序就可以省去点排序的操作，体验更好。
3、能否把种子标签(例如官方、中字、限转这些原站点定义的标签)给显示出来
      因为很多大站都有自己的官组，并针对种子标注标签，显示标签的话就非常容易判断是不是官种等。。。

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
这个主要作用是测试站点能不能访问。
搞太复杂了没必要，要详细的去pt站看就好了。
