### ISSUE TITLE
馒头 站点资源 发布时间显示问题

### ISSUE THREAD

**Issue by Feng4** [jxxghp/nas-tools#3442]
> NAStool 版本: 2.9.0
> 环境: docker 
![image](https://user-images.githubusercontent.com/27730186/218241596-b4a68823-1a1b-453f-ae68-34ffafce79c2.png)

这里发布时间显示为 促销的时间，导致刷流任务无法自动添加这个free的资源

**Comment by jxxghp** [comment]
不是一回事，没有关系
