### ISSUE TITLE
更新后订阅失败无法连接tmdb

### ISSUE THREAD

**Issue by 101letters** [jxxghp/nas-tools#3444]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:[v2.9.0 0db383e]
>
> 环境:synology矿神
![Uploading QQ截图20230211
![QQ截图20230211150547](https://user-images.githubusercontent.com/120088769/218245595-a5b62761-a895-4a89-b1b4-ca5939d77150.png)
![QQ截图20230211150556](https://user-images.githubusercontent.com/120088769/218245596-066236c9-a023-4a07-8caf-5f55e165ea88.png)
150426.png…]()
更新后订阅电视剧失败 日志已经附上 连通性是正常，不是知道是哪里出问题了，大佬们可以帮我看一下，还是我自己的网络问题

## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by 101letters** [comment]
连接TMDB出错：HTTPSConnectionPool(host='tmdb.nastool.cn', port=443): Read timed out. (read timeout=10)
但是在服务中连通性测试显示在基础设置中选用的api.tmdb.org是通的 图片加载失败就文字描述了

**Comment by zzlovebb** [comment]
我跟你一个毛病，就是今下午的问题，我挂梯子也不行，应该就是他们服务器的问题。

**Comment by jxxghp** [comment]
自己有网络条件的话，实验室使用TMDB代理服务器开关别开，太多人用压力就大了，体验也不好。
