### ISSUE TITLE
关于更新版本后，识别的问题

### ISSUE THREAD

**Issue by usherkobe** [jxxghp/nas-tools#345]
![image](https://user-images.githubusercontent.com/77767220/174979486-ef799cec-f607-45a1-b364-05f43b1f4cd6.png)
地球百子，第六季识别有误，之前版本前五季都是好的，日志如下：【RMT】拼装文件路径错误，无法从文件名中识别出集数：/Media/Drama/[地球百子].The.100.2019.S06.Complete.NF.WEB-DL.1080p.H264.DDP.5.1/[地球百子].The.100.2019.S06E01.NF.WEB-DL.1080p.H264.DDP.5.1.mp4

**Comment by jxxghp** [comment]
已修复

**Comment by usherkobe** [comment]
感谢大佬
