### ISSUE TITLE
建议在手动识别界面增加批量手动识别功能

### ISSUE THREAD

**Issue by Penpal4671** [jxxghp/nas-tools#3450]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.9.0
>
> 环境: synology

## 你想要新增或者改进什么功能？

建议在手动识别界面增加批量手动识别功能
> 你想要新增或者改进什么功能？

建议在手动识别界面增加批量手动识别功能
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
已经支持的，多看看？号提示
