### ISSUE TITLE
建议手动识别页面增加分页功能

### ISSUE THREAD

**Issue by HateBaozi** [jxxghp/nas-tools#3453]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.0
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 手动识别功能增加分页，如果失败失败的项目太多，一页加载完浏览器就死了。刚看了下，我的未识别记录有6万多条

## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by jxxghp** [comment]
是哪没弄好或者tmdb连不上吧，正常怎么会有这么多未识别。pt资源的识别率最起码在95%以上。

6万条记录，就算翻页也没办法处理的，正常使用场景，这个功能下很少会出现有未识别记录的情况

**Comment by HateBaozi** [comment]
识别成功3万多，tmdb链接没问题，就是网盘太大了，很多电视剧命名不标准

**Comment by HateBaozi** [comment]
> 是哪没弄好或者tmdb连不上吧，正常怎么会有这么多未识别。pt资源的识别率最起码在95%以上。
> 
> 6万条记录，就算翻页也没办法处理的，正常使用场景，这个功能下很少会出现有未识别记录的情况

刮削的xiaoya网盘数据，识别成功3万多，tmdb链接没问题，就是网盘太大了，很多电视剧命名不标准

**Comment by 120318** [comment]
> > 是哪没弄好或者tmdb连不上吧，正常怎么会有这么多未识别。pt资源的识别率最起码在95%以上。
> 
> > 
> 
> > 6万条记录，就算翻页也没办法处理的，正常使用场景，这个功能下很少会出现有未识别记录的情况
> 
> 
> 
> 刮削的xiaoya网盘数据，识别成功3万多，tmdb链接没问题，就是网盘太大了，很多电视剧命名不标准

可以提个pr。
