### ISSUE TITLE
docker启动支持http_proxy配置代理吗？

### ISSUE THREAD

**Issue by RWDai** [jxxghp/nas-tools#3460]
## 你使用的 NAStool 是什么版本，什么环境？
docker latest
> NAStool 版本: vx.x.x
>
> 环境: docker or windows or synology
docker
## 你想要新增或者改进什么功能？

> 你想要新增或者改进什么功能？

 http_proxy的形式支持代理
## 这个功能有什么可以参考的资料吗？

> 这个功能有什么可以参考的资料吗？是否可以列举一些，不要引用同类但商业化软件的任何内容.

**Comment by thsrite** [comment]
支持，这个跟nt没啥关系吧，任何docker配置了http_proxy和https_proxy都走代理

**Comment by RWDai** [comment]
> 支持，这个跟nt没啥关系吧，任何docker配置了http_proxy和https_proxy都走代理

主要是我试了一下 docker更新程序的时候没走代理 配置了http_proxy 我觉得有点奇怪

**Comment by RWDai** [comment]
如果可以的话我建议在docker 启动示例配置里加上
