### ISSUE TITLE
在字幕页面没有opensubtitles选项

### ISSUE THREAD

**Issue by thz-hub** [jxxghp/nas-tools#3462]
在字幕页面没有opensubtitles选项，只有ChineseSubFinder。
![image](https://user-images.githubusercontent.com/62689630/218289095-bee7ca8e-6b70-4305-8e65-1906bab9f2f4.png)

**Comment by jxxghp** [comment]
提问不按模板，用的什么版本都不说。
我猜不出来。

**Comment by Jcay60** [comment]
windows版本 2.9.0，我也遇到没有opensubtitles
