### ISSUE TITLE
优化影单页边框底色、新增用户活动日志屏蔽功能

### ISSUE THREAD

**Issue by heian12345** [jxxghp/nas-tools#3466]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v2.9.1 e3a43d4
>
> 环境: synology

## 你想要新增或者改进什么功能？

> ### 1.建议优化“探索”推荐影单页img标签阴影
现版本页面中img属性增加了“box-shadow:0 0 0 1px #888888”，灰色边框尤其是在浅色海报图的情况下显得比较明显，个人觉得不是很美观，建议取消灰色边框。
![屏幕截图 2023-02-12 133444](https://user-images.githubusercontent.com/32611208/218295211-1f4cfce4-caf5-41ee-bb00-1a7f5da9b002.png)
代码位置指引
![屏幕截图 2023-02-12 133553](https://user-images.githubusercontent.com/32611208/218295218-266c44f8-0b16-437c-bc2f-c82d39c4bac9.png)
尝试去除灰色边框后的效果，供效果参考，望作者采纳！
![屏幕截图 2023-02-12 134123](https://user-images.githubusercontent.com/32611208/218295188-0af7a0ea-63b7-437a-9b39-1277500739bd.png)

------

> ### 2.建议新增“我的媒体库”部分用户活动日志屏蔽功能
由于Emby的api接口“/emby/System/ActivityLog/Entries”无法仅获取部分用户活动日志，建议作者在“设置-媒体服务器-EMBY”中添加“仅显示某用户/排除某用户”的选项，使用者将emby的用户名填入，请求活动日志api并返回时过滤部分用户活动日志。

------

**望作者采纳，最后感谢作者为我们带来如此好用的产品，谢谢！**

**Comment by jxxghp** [comment]
1. 白银自完义css自己改。
2. 无计划
