### ISSUE TITLE
[改进需求]自主决定做种数为0的源是否下载 及 剧集标题判断逻辑似乎存在缺陷

### ISSUE THREAD

**Issue by LainHE** [jxxghp/nas-tools#3467]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.1
>
> 环境: synology

## 你想要新增或者改进什么功能？

> 1. 希望识别 `做种数为0` 后, 是否下载让用户决定, 现在感觉的确是有一些识别的问题, 我查询dmhy的源全部提示是0
> 2. 我在订阅下载动画 `158373 尼尔:机械纪元(NieR:Automata Ver1.1a)` 的时候遇到了灾难级的问题, 除了上述的做种数为0的问题, NASTOOL只能识别到 `NieR:Automata Ver1` 的样子, 然后程序就在明知道该动画TMDB编号为158373的情况下说TMDB查询不到该动画信息, 然后各种报错
>想去TMDB缓存手动将尼尔:机械纪元 改为 NieR:Automata Ver1, 结果改了之后点确定也没有任何变化
>即使想用RSS订阅也还是绕不开识别不到TMDB信息
>><img width="1030" alt="无标题" src="https://user-images.githubusercontent.com/36128030/218296751-27090cb0-83cb-491e-af75-388a98584610.png">
>><img width="839" alt="无标题1" src="https://user-images.githubusercontent.com/36128030/218296845-a7c5fc63-383a-443d-a948-20f8ca8df0ab.png">
>
>在设置中开启了 `辅助识别` 与 `增强识别` 之后, 终于算是可以下载, 但似乎无法正确判定该动画集数, 下了一集之后就 `自动取消了订阅`, 以至于连目录同步都没有做, 手动填写了总集数之后也没有办法自动识别当前集为哪一集, `只能手动识别`, 而且最全的dmhy源全都判断为做种数为0, 视频也下不全, 基本上 `只有 2, 3 集` 可以下下来, 而且需要多次尝试才可以
>>![EL4~0N2G0`Q5C PUA8~ZOH0](https://user-images.githubusercontent.com/36128030/218296175-676108ee-54e2-496f-84ef-25d7ed054714.png)
>
>个人感觉在标题判定上(正则?)可能还是有缺陷, 导致了上述的各种各样问题, 烦请开发者大大们能够改善该情况
>
>以下为dmhy源查询的返回结果

<body>

14:46:18 | Jackett | dmhy 返回数据：65
-- | -- | --
14:46:18 | Jackett | [織夢字幕組][尼爾：機械紀元 NieR Automata Ver1.1a][03集][720P][AVC][繁日雙語] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | [云光字幕组]尼尔：自动人形 Ver1.1a NieR：Automata Ver1.1a[03][简体双语][1080p]招募翻译 做种数为0
14:46:18 | Jackett | [织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][03集][1080P][AVC][简日双语] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | 【極影字幕社】 ★1月新番 【尼爾：自動人形 Ver1.1a】【NieR:Automata Ver1.1a】【02】BIG5 MP4_720P 做种数为0
14:46:18 | Jackett | [织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][03集][720P][AVC][简日双语] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | 【極影字幕社】 ★1月新番 【尼爾：自動人形 Ver1.1a】【NieR:Automata Ver1.1a】【02】BIG5 MP4_1080P 做种数为0
14:46:18 | Jackett | 【极影字幕社】 ★1月新番 【尼尔：机械纪元 Ver1.1a】【NieR:Automata Ver1.1a】【02】GB MP4_720P 做种数为0
14:46:18 | Jackett | [云光字幕组]尼尔：自动人形 Ver1.1a NieR：Automata Ver1.1a[02][简体双语][1080p]招募翻译 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | 【极影字幕社】 ★1月新番 【尼尔：机械纪元 Ver1.1a】【NieR:Automata Ver1.1a】【02】GB MP4_1080P 做种数为0
14:46:18 | Jackett | [織夢字幕組][尼爾：機械紀元 NieR Automata Ver1.1a][03集][1080P][AVC][繁日雙語] 做种数为0
14:46:18 | Jackett | [喵萌奶茶屋&LoliHouse] 尼尔：自动人形 / 尼尔：机械纪元 / NieR:Automata Ver1.1a - 03 [WebRip 1080p HEVC-10bit AAC][简繁内封字幕] Animation 识别为 尼尔：机械纪元 (2023) S01 匹配成功
14:46:18 | Jackett | [織夢字幕組][尼爾：機械紀元 NieR Automata Ver1.1a][03集][720P][AVC][繁日雙語] 做种数为0
14:46:18 | Jackett | [织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][03集][1080P][AVC][简日双语] 做种数为0
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼爾 / NieR:Automata Ver1.1a][03][1080p][繁體][招募翻譯] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | [织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][03集][720P][AVC][简日双语] 做种数为0
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼爾 / NieR:Automata Ver1.1a][03][720p][繁體][招募翻譯] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | [云光字幕组]尼尔：自动人形 Ver1.1a NieR：Automata Ver1.1a[02][简体双语][1080p]招募翻译 做种数为0
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼尔 / NieR:Automata Ver1.1a][03][1080p][简体][招募翻译] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | [喵萌奶茶屋&LoliHouse] 尼尔：自动人形 / 尼尔：机械纪元 / NieR:Automata Ver1.1a - 03 [WebRip 1080p HEVC-10bit AAC][简繁内封字幕] 做种数为0
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼尔 / NieR:Automata Ver1.1a][03][720p][简体][招募翻译] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼爾 / NieR:Automata Ver1.1a][03][1080p][繁體][招募翻譯] 做种数为0
14:46:18 | Jackett | [Lilith-Raws] 尼爾：自動人形 Ver1.1a / NieR：Automata Ver1.1a - 03 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼爾 / NieR:Automata Ver1.1a][03][720p][繁體][招募翻譯] 做种数为0
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼尔 / NieR:Automata Ver1.1a][03][1080p][简体][招募翻译] 做种数为0
14:46:18 | Jackett | [漫貓字幕社&貓戀漢化組][1月新番][尼爾：自動人形 Ver1.1a][NieR Automata Ver1.1a][02][1080P][MP4][BIG5][繁中] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼尔 / NieR:Automata Ver1.1a][03][720p][简体][招募翻译] 做种数为0
14:46:18 | Jackett | [Lilith-Raws] 尼爾：自動人形 Ver1.1a / NieR：Automata Ver1.1a - 03 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4] 做种数为0
14:46:18 | Jackett | [漫猫字幕社&猫恋汉化组][1月新番][尼尔：机械纪元 Ver1.1a][NieR Automata Ver1.1a][02][1080P][MP4][GB][简中] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | [漫貓字幕社&貓戀漢化組][1月新番][尼爾：自動人形 Ver1.1a][NieR Automata Ver1.1a][02][1080P][MP4][BIG5][繁中] 做种数为0
14:46:18 | Jackett | [漫猫字幕社&猫恋汉化组][1月新番][尼尔：机械纪元 Ver1.1a][NieR Automata Ver1.1a][02][1080P][MP4][GB][简中] 做种数为0
14:46:18 | Jackett | [漫貓字幕社&貓戀漢化組][1月新番][尼爾：自動人形 Ver1.1a][NieR Automata Ver1.1a][01v2][1080P][MP4][BIG5][繁中] 做种数为0
14:46:18 | Jackett | [漫貓字幕社&貓戀漢化組][1月新番][尼爾：自動人形 Ver1.1a][NieR Automata Ver1.1a][01v2][1080P][MP4][BIG5][繁中] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | [漫猫字幕社&猫恋汉化组][1月新番][尼尔：机械纪元 Ver1.1a][NieR Automata Ver1.1a][01v2][1080P][MP4][GB][简中] 做种数为0
14:46:18 | Jackett | [漫猫字幕社&猫恋汉化组][1月新番][尼尔：机械纪元 Ver1.1a][NieR Automata Ver1.1a][01v2][1080P][MP4][GB][简中] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | [NC-Raws] 尼爾：自動人形 Ver1.1a / NieR:Automata Ver1.1a - 03 (CR 1920x1080 AVC AAC MKV) 做种数为0
14:46:18 | Jackett | [NC-Raws] 尼爾：自動人形 Ver1.1a / NieR:Automata Ver1.1a - 03 (CR 1920x1080 AVC AAC MKV) 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | [ANi] NieRAutomata Ver11a - 尼爾：自動人形 Ver1.1a - 03 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4] 做种数为0
14:46:18 | Jackett | [ANi] NieRAutomata Ver11a - 尼爾：自動人形 Ver1.1a - 03 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | [NC-Raws] 尼尔：机械纪元 / NieR:Automata Ver1.1a - 03 (B-Global 3840x2160 HEVC AAC MKV) 做种数为0
14:46:18 | Jackett | [NC-Raws] 尼尔：机械纪元 / NieR:Automata Ver1.1a - 03 (B-Global 3840x2160 HEVC AAC MKV) 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | [NC-Raws] 尼爾：自動人形 Ver1.1a / NieR:Automata Ver1.1a - 03 (Baha 1920x1080 AVC AAC MP4) 做种数为0
14:46:18 | Jackett | [NC-Raws] 尼爾：自動人形 Ver1.1a / NieR:Automata Ver1.1a - 03 (Baha 1920x1080 AVC AAC MP4) 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | [喵萌奶茶屋&LoliHouse] 尼尔：自动人形 / 尼尔：机械纪元 / NieR:Automata Ver1.1a - 02 [WebRip 1080p HEVC-10bit AAC][简繁内封字幕] 做种数为0
14:46:18 | Jackett | [喵萌奶茶屋&LoliHouse] 尼尔：自动人形 / 尼尔：机械纪元 / NieR:Automata Ver1.1a - 02 [WebRip 1080p HEVC-10bit AAC][简繁内封字幕] Animation 识别为 尼尔：机械纪元 (2023) S01 匹配成功
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼爾 / NieR:Automata Ver1.1a][02][1080p][繁體][招募翻譯] 做种数为0
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼尔 / NieR:Automata Ver1.1a][02][1080p][简体][招募翻译] 做种数为0
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼爾 / NieR:Automata Ver1.1a][02][1080p][繁體][招募翻譯] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼爾 / NieR:Automata Ver1.1a][02][720p][繁體][招募翻譯] 做种数为0
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼尔 / NieR:Automata Ver1.1a][02][1080p][简体][招募翻译] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼尔 / NieR:Automata Ver1.1a][02][720p][简体][招募翻译] 做种数为0
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼爾 / NieR:Automata Ver1.1a][02][720p][繁體][招募翻譯] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | [云光字幕组]尼尔：自动人形 Ver1.1a NieR：Automata Ver1.1a[01][简体双语][1080p]招募翻译 做种数为0
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼尔 / NieR:Automata Ver1.1a][02][720p][简体][招募翻译] 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | [織夢字幕組][尼爾：機械紀元 NieR Automata Ver1.1a][02集][1080P][AVC][繁日雙語] 做种数为0
14:46:18 | Jackett | [云光字幕组]尼尔：自动人形 Ver1.1a NieR：Automata Ver1.1a[01][简体双语][1080p]招募翻译 不符合制作组/字幕组 LoliHouse 要求
14:46:18 | Jackett | [織夢字幕組][尼爾：機械紀元 NieR Automata Ver1.1a][02集][720P][AVC][繁日雙語] 做种数为0
14:46:18 | Jackett | Bangumi Moe 共检索到 30 条数据，过滤 28，不匹配 0，错误 0，有效 2，耗时 0 秒
14:46:18 | Jackett | [织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][02集][1080P][AVC][简日双语] 做种数为0
14:46:18 | Jackett | [织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][02集][720P][AVC][简日双语] 做种数为0
14:46:18 | Jackett | [Hi-Res][230115]TVアニメ『NieR：Automata Ver1.1a』EDテーマ「アンチノミー」／amazarashi[48kHz/24bit][FLAC] 做种数为0
14:46:18 | Jackett | [NC-Raws] 尼爾：自動人形 Ver1.1a / NieR:Automata Ver1.1a - 02 (CR 1920x1080 AVC AAC MKV) 做种数为0
14:46:18 | Jackett | [Lilith-Raws] 尼爾：自動人形 Ver1.1a / NieR：Automata Ver1.1a - 02 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4] 做种数为0
14:46:18 | Jackett | [ANi] NieRAutomata Ver11a - 尼爾：自動人形 Ver1.1a - 02 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4] 做种数为0
14:46:18 | Jackett | [NC-Raws] 尼尔：机械纪元 / NieR:Automata Ver1.1a - 02 (B-Global 3840x2160 HEVC AAC MKV) 做种数为0
14:46:18 | Jackett | [NC-Raws] 尼爾：自動人形 Ver1.1a / NieR:Automata Ver1.1a - 02 (Baha 1920x1080 AVC AAC MP4) 做种数为0
14:46:18 | Jackett | [2023.01.15] TVアニメ「NieR:Automata Ver1.1a」EDテーマ「アンチノミー」／amazarashi [MP3 320K] 做种数为0
14:46:18 | Jackett | [2023.01.15] TVアニメ「NieR:Automata Ver1.1a」EDテーマ「アンチノミー」／amazarashi [FLAC 48kHz/24bit] 做种数为0
14:46:18 | Jackett | [漫貓字幕社&貓戀漢化組][1月新番][尼爾：自動人形 Ver1.1a][NieR Automata Ver1.1a][01][1080P][MP4][BIG5][繁中] 做种数为0
14:46:18 | Jackett | [漫猫字幕社&猫恋汉化组][1月新番][尼尔：机械纪元 Ver1.1a][NieR Automata Ver1.1a][01][1080P][MP4][GB][简中] 做种数为0
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼爾 / NieR:Automata Ver1.1a][01][720p][繁體][招募翻譯] 做种数为0
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼爾 / NieR:Automata Ver1.1a][01][1080p][繁體][招募翻譯] 做种数为0
14:46:18 | Jackett | [喵萌奶茶屋&LoliHouse] 尼尔：自动人形 / 尼尔：机械纪元 / NieR:Automata Ver1.1a - 01 [WebRip 1080p HEVC-10bit AAC][简繁内封字幕] 做种数为0
14:46:18 | Jackett | 【極影字幕社】 ★1月新番 【尼爾：自動人形 Ver1.1a】【NieR:Automata Ver1.1a】【01】BIG5 MP4_720P 做种数为0
14:46:18 | Jackett | 【極影字幕社】 ★1月新番 【尼爾：自動人形 Ver1.1a】【NieR:Automata Ver1.1a】【01】BIG5 MP4_1080P 做种数为0
14:46:18 | Jackett | 【极影字幕社】 ★1月新番 【尼尔：机械纪元 Ver1.1a】【NieR:Automata Ver1.1a】【01】GB MP4_720P 做种数为0
14:46:18 | Jackett | 【极影字幕社】 ★1月新番 【尼尔：机械纪元 Ver1.1a】【NieR:Automata Ver1.1a】【01】GB MP4_1080P 做种数为0
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼尔 / NieR:Automata Ver1.1a][01][1080p][简体][招募翻译] 做种数为0
14:46:18 | Jackett | 【喵萌奶茶屋】★01月新番★[尼尔 / NieR:Automata Ver1.1a][01][720p][简体][招募翻译] 做种数为0
14:46:18 | Jackett | [織夢字幕組][尼爾：機械紀元 NieR Automata Ver1.1a][01集][1080P][AVC][繁日雙語] 做种数为0
14:46:18 | Jackett | [織夢字幕組][尼爾：機械紀元 NieR Automata Ver1.1a][01集][720P][AVC][繁日雙語] 做种数为0
14:46:18 | Jackett | [织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][01集][1080P][AVC][简日双语] 做种数为0
14:46:18 | Jackett | [织梦字幕组][尼尔：机械纪元 NieR Automata Ver1.1a][01集][720P][AVC][简日双语] 做种数为0
14:46:18 | Jackett | [Hi-Res][230108]TVアニメ『NieR：Automata Ver1.1a』OP主题歌「escalate」／Aimer[48kHz/24bit][FLAC] 做种数为0
14:46:18 | Jackett | [NC-Raws] 尼爾：自動人形 Ver1.1a / NieR:Automata Ver1.1a - 01 (CR 1920x1080 AVC AAC MKV) 做种数为0
14:46:18 | Jackett | [Lilith-Raws] 尼爾：自動人形 Ver1.1a / NieR：Automata Ver1.1a - 01 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4] 做种数为0
14:46:18 | Jackett | [ANi] NieRAutomata Ver11a - 尼爾：自動人形 Ver1.1a - 01 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4] 做种数为0
14:46:18 | Jackett | [NC-Raws] 尼尔：机械纪元 / NieR:Automata Ver1.1a - 01 (B-Global 3840x2160 HEVC AAC MKV) 做种数为0
14:46:18 | Jackett | [NC-Raws] 尼爾：自動人形 Ver1.1a / NieR:Automata Ver1.1a - 01 (Baha 1920x1080 AVC AAC MP4) 做种数为0
14:46:18 | Jackett | [2023.01.08] TVアニメ「NieR:Automata Ver1.1a」OPテーマ「escalate」／Aimer [MP3 320K] 做种数为0
14:46:18 | Jackett | [2023.01.08] TVアニメ「NieR:Automata Ver1.1a」OPテーマ「escalate」／Aimer [FLAC 48kHz/24bit] 做种数为0
14:46:18 | Jackett | dmhy 共检索到 65 条数据，过滤 65，不匹配 0，错误 0，有效 0，耗时 0 秒

</body>

**Comment by LainHE** [comment]
关于 dmhy 的查询日志, 我希望下载的是LoliHouse为制作组的 尼尔:机械纪元 动画, 所以可以通过查找功能 '喵萌奶茶屋&LoliHouse' 查询来看出, 2, 3 集是可以匹配出来的, 第1集是完全匹配不出来, 在其他源中也是相同情况, 匹配成功率非常堪忧

**Comment by jxxghp** [comment]
是的，动漫支持不好，建议不用。
