### ISSUE TITLE
开启洗版不会下载

### ISSUE THREAD

**Issue by tnanstar** [jxxghp/nas-tools#3468]
v2.9.1 e3a43d4
例如 开启洗版 日志如下  最后不会下载
<html>
<body>

16:23:39 | Indexer | 开始检索Indexer：观众 ...
-- | -- | --
16:23:39 | Spider | 开始请求：https://audiences.me/torrents.php?search_mode=0&page=0&search=%E6%96%97%E7%A0%B4%E8%8B%8D%E7%A9%B9&402=1&403=1&406=1
16:23:41 | Indexer | 观众 返回数据：78
16:23:41 | Indexer | 斗破苍穹 (2017)S05 正在洗版，过滤掉季集不完整的资源：Fights Break Sphere S05E31 2022 2160p WEB-DL H265 AAC-ADWeb [国漫连载] 斗破苍穹 年番 / 斗破苍穹第五季 \| 第31集 4K \| 国语中字
16:23:41 | Indexer | 斗破苍穹 (2017)S05 正在洗版，过滤掉季集不完整的资源：Fights Break Sphere S05E31 2022 1080p WEB-DL H265 AAC-ADWeb [国漫连载] 斗破苍穹 年番 / 斗破苍穹第五季 \| 第31集 \| 国语中字

</body>
</html>

关闭洗版 选4k会自动下载31集4K版本
不懂是设置问题还是怎样

**Comment by jxxghp** [comment]
这个日志打的这么清楚。。。
现在洗版只支持出全了的。

**Comment by tnanstar** [comment]
> 这个日志打的这么清楚。。。 现在洗版只支持出全了的。

这么说就懂了 日志是很清楚 就是不知道为啥会过滤掉 谢谢

**Comment by 120318** [comment]
对于当前的实现，如果想要支持追更的洗版，还是需要新写一部分内容的，作者有计划加入么？
