### ISSUE TITLE
希望新增音乐管理功能

### ISSUE THREAD

**Issue by zui-lang** [jxxghp/nas-tools#3469]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.9.1
>
> 环境: docker

## 你想要新增或者改进什么功能？

> 新增音乐管理功能，将下载的原因按照艺术家/专辑/歌曲的形式重命名分类，并添加歌词，封面等信息

## 这个功能有什么可以参考的资料吗？

> 调用wyy，企鹅，spotify，apple music等曲库进行识别对比。目前有类似的本地软件，音乐标签（MusicTag），我并没有找到作者发布地址，只找到下载地址，安卓（这个算是作者发布的）：https://www.coolapk.com/apk/com.xjcheng.musictageditor，Windows（应该是第三方的博客）：https://www.cnblogs.com/vinlxc/p/11347744.html

**Comment by 120318** [comment]
这将会是多么庞大的工作量呀。

**Comment by DDSDerek** [comment]
同 https://github.com/jxxghp/nas-tools/issues/2580

**Comment by Lobeu-m** [comment]
dsplayer

**Comment by netduke777** [comment]
我是用itune，但是感觉有些笨，希望能加入，万分感谢
