### ISSUE TITLE
【功能需求】订阅识别官种的不同版本

### ISSUE THREAD

**Issue by xwxw098** [jxxghp/nas-tools#3470]
现阶段的订阅仅能识别例如@ADweb这样的官种
现在有以下两个版本的官种子
The Last of Us S01E05 2023 1080p HMAX WEB-DL x264 DDP5.1 Atmos-KC@ADWeb
最后生还者 / 美国末日 / 末日余生 【第05集】【1080P SDR】【内封简英特效字幕】

The Last of Us S01E05 2023 1080p HMAX WEB-DL x264 DDP5.1 Atmos-ADWeb 
最后生还者 / The Last of Us 又名: 美国末日 / 末日余生 第05集

其名字区别于有没有KC，而我只想订阅带KC的视频
希望开发者能在细分一下订阅功能

NieR Automata S01E01 2023 1080p CR WEB-DL x264 AAC-AnimeS@ADWeb 不符合制作组/字幕组 AnimeS 要求

**Comment by log-time** [comment]
新增订阅里有个自定义的制作组/字幕组选项，了解下
![BUJFXQ3~EVV9 53F}VD`0_V](https://user-images.githubusercontent.com/66826612/218356694-a98ba56a-075f-4992-b1c9-a00a57b8d94a.png)

**Comment by jxxghp** [comment]
维护自定义制作组/字幕组，就能识别支持
<img width="955" alt="image" src="https://user-images.githubusercontent.com/51039935/218365283-3cbb33f7-1554-4035-8bdb-85b93c559f98.png">
