### ISSUE TITLE
影片卡片增加电影名称

### ISSUE THREAD

**Issue by 120318** [jxxghp/nas-tools#3473]
## 你使用的 NAStool 是什么版本，什么环境？
NAStool 版本: 最新dev分支
环境：docker

## 你想要新增或者改进什么功能？
现如今，在探索Tab以及其他地方的所有电影卡片，都是只有封面，名称需要鼠标 hover 到封面上才会显示，这其实不是很方便，因为我们从海报上并不能一目了然看出这是什么影片，每次都要不停的hover，比较浪费精力，效率不够高。

## 这个功能有什么可以参考的资料吗？
可以参考 radarr 和 sonarr 的显示方式

![image](https://user-images.githubusercontent.com/20685540/218310278-1925bf37-5d37-4304-af98-64af8504b8d3.png)
![image](https://user-images.githubusercontent.com/20685540/218310243-38b04879-f395-479a-881e-e56b673ac370.png)

**Comment by jxxghp** [comment]
大部分都是显示的中文海报，基本知道是什么。
