### ISSUE TITLE
目录监控报错：“启动目录监控失败：[Errno 28] inotify watch limit reached”

### ISSUE THREAD

**Issue by chingxuds** [jxxghp/nas-tools#348]
RT，启动后日志报以下错误

![image](https://user-images.githubusercontent.com/3142486/175245472-586f4d7d-497a-4ea9-a8d5-fc92ced3fa9c.png)

**Comment by log-time** [comment]
https://github.com/jxxghp/nas-tools/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#1%E5%90%AF%E5%8A%A8%E6%8A%A5%E9%94%99inotify-instancewatch-limit-reached-%E6%88%96-%E7%9B%AE%E5%BD%95%E5%90%8C%E6%AD%A5%E4%B8%8D%E6%98%8E%E5%8E%9F%E5%9B%A0%E4%B8%8D%E4%BC%9A%E5%90%8C%E6%AD%A5-%E6%88%96-%E7%9B%AE%E5%BD%95%E5%90%8C%E6%AD%A5%E5%8F%AA%E6%9C%89%E9%83%A8%E5%88%86%E7%9B%AE%E5%BD%95%E6%AD%A3%E5%B8%B8
