### ISSUE TITLE
过滤规则不能显示

### ISSUE THREAD

**Issue by git-0101** [jxxghp/nas-tools#3486]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.2
>
> 环境: docker
如题

**Comment by sgpublic** [comment]
我也遇到这个问题了，这种情况大概率是用的 docker，我这边备份也有问题，解决方案如下：

1. 到你的配置目录下备份一个 `config.yaml` 文件，比如 `mv config.yaml config.yaml.bak`。
2. 把 `https://github.com/jxxghp/nas-tools` 仓库内 `config` 文件夹里面的所有内容覆盖进你的配置目录，比如 `cp ./nas-tools/config/* /xxx/config/ -r`
3. 将第一步备份的 `config.yaml.bak`  恢复到配置目录下。
4. 重新启动 nas-tools 即可。

**Comment by git-0101** [comment]
> 我也遇到这个问题了，这种情况大概率是用的 docker，我这边备份也有问题，解决方案如下：
> 
> 1. 到你的配置目录下备份一个 `config.yaml` 文件，比如 `mv config.yaml config.yaml.bak`。
> 2. 把 `https://github.com/jxxghp/nas-tools` 仓库内 `config` 文件夹里面的所有内容覆盖进你的配置目录，比如 `cp ./nas-tools/config/* /xxx/config/ -r`
> 3. 将第一步备份的 `config.yaml.bak`  恢复到配置目录下。
> 4. 重新启动 nas-tools 即可。

好的，谢谢大佬！先这样解决。待作者大大修复了。

**Comment by ZiGmaX809** [comment]
> > 我也遇到这个问题了，这种情况大概率是用的 docker，我这边备份也有问题，解决方案如下：
> > 
> > 1. 到你的配置目录下备份一个 `config.yaml` 文件，比如 `mv config.yaml config.yaml.bak`。
> > 2. 把 `https://github.com/jxxghp/nas-tools` 仓库内 `config` 文件夹里面的所有内容覆盖进你的配置目录，比如 `cp ./nas-tools/config/* /xxx/config/ -r`
> > 3. 将第一步备份的 `config.yaml.bak`  恢复到配置目录下。
> > 4. 重新启动 nas-tools 即可。
> 
> 好的，谢谢大佬！先这样解决。待作者大大修复了。

应该是DB数据库文件变动导致的

**Comment by git-0101** [comment]
作者大大已修复！
