### ISSUE TITLE
新增一个站点，可是高级搜索的下拉框里面，没有新增的站点

### ISSUE THREAD

**Issue by Nothend** [jxxghp/nas-tools#3488]
版本：2.9.2
新增一个站点，可是高级搜索的下拉框里面，没有新增的站点。高级搜索里面 没有新增站点，普通搜索的结果也没有新增站点的信息。HDsky是新增的站点。

![photo_2023-02-13_10-56-52](https://user-images.githubusercontent.com/73117056/218360362-eb2e7520-3d41-423f-bda6-204436e51eab.jpg)

![photo_2023-02-13_10-57-04](https://user-images.githubusercontent.com/73117056/218360423-b20fe22b-e7d7-4219-ac82-53417228c2c8.jpg)

![微信图片_20230213105854](https://user-images.githubusercontent.com/73117056/218360587-49e9c19d-2762-4d51-bb79-2bf94468f738.png)

**Comment by jxxghp** [comment]
索引器里选中了吗？

**Comment by Nothend** [comment]
> 索引器里选中了吗？

呃 原来需要设置这里，不好意思！感谢！
