### ISSUE TITLE
请问刷流是不是先要把种子添加到RSS刷流任务才能下载？

### ISSUE THREAD

**Issue by ym0230** [jxxghp/nas-tools#3490]
请问刷流是不是先要把种子添加到RSS刷流任务才能下载？

**Comment by log-time** [comment]
刷流需要先维护站点rss信息和刷流下载器，然后在刷流任务中添加刷流任务。
日常使用建议加项目主页tg群。

**Comment by vuhe** [comment]
> 刷流需要先维护站点rss信息和刷流下载器，然后在刷流任务中添加刷流任务。
> 日常使用建议加项目主页tg群。

有 tg 群吗，主页只有一个更新提醒是这个吗
