### ISSUE TITLE
群晖Docker版启动失败

### ISSUE THREAD

**Issue by chingxuds** [jxxghp/nas-tools#350]
已尝试重置容器，重新下载镜像更新，启动后频繁退出重启，报错如下：

![image](https://user-images.githubusercontent.com/3142486/175274767-276b71cb-9b99-458e-a58f-ec4124b9dfdc.png)

**Comment by jxxghp** [comment]
应该是容器更新有延迟，等等重拉镜像。
基础镜像包有变化时可能会触发启动依赖的问题

**Comment by chingxuds** [comment]
> 应该是容器更新有延迟，等等重拉镜像。 基础镜像包有变化时可能会触发启动依赖的问题

经排查，确实是缺少了“cacheout”模块所致，但是镜像启动后20分钟都没能自动安装，最后是手动安装后解决。
