### ISSUE TITLE
关于手动修正错误识别的影视信息建议

### ISSUE THREAD

**Issue by kekylin** [jxxghp/nas-tools#353]
目前我遇到的情况是，硬链接之后有部分影视信息是识别错误的，例：
源文件名称：[龙的传人]Legend.of.the.Dragon.1990.BluRay.1080p.x265.10bit.2Audio.BOBO.mkv
硬链接之后：龙威父子 (1990) - 1080p.mkv
![image](https://user-images.githubusercontent.com/65521882/175446044-f21d77c8-9b12-4566-9c49-bf6ba4f4921e.png)

可否添加更便捷的手动修正方式，且手动修正后，直接重命名原先错误硬链接的文件名？目前的情况是手动修正后，会重新再硬链接一份文件，而原先识别错误的硬链接文件还在，需要手动删除掉。

**Comment by kekylin** [comment]
还发现了一个问题，我手动修正后，如果重新执行目录同步操作，会又重新硬链接一份错误识别的文件过去。

**Comment by jxxghp** [comment]
重新执行目录同步操作，会又重新硬链接一份错误识别的文件 的问题稍后提交修复。
第1点再说吧，多点一下也没啥。
