### ISSUE TITLE
求教一下手动识别美剧，一个文件两集的情况

### ISSUE THREAD

**Issue by 287138531** [jxxghp/nas-tools#361]
请教下，这种一个文件，就包含两集的  手动识别应该如何 填写 集数定位。
The.Expanse.S01E09E10.2015.1080p.mkv
我试过The.Expanse.S01E{ep}.2015.1080p.mkv ，会出现两集8好像。
现在只处理1-8级，还剩9和10不知道怎么搞

另外，大佬能做全局可以选文件夹吗？每次都要自己复制文件路径好麻烦

**Comment by jxxghp** [comment]
已合并代码
