### ISSUE TITLE
分享我定制的 unraid 安装 nastools 模版及配置教程

### ISSUE THREAD

**Issue by shuosiw** [jxxghp/nas-tools#364]
### unraid 安装模版

最近在部署 nastools，非常不错的项目，作者大佬也牛逼，我把一些模版以及过程都整理出来了：

* unraid 安装 nastools 容器模版：https://github.com/shuosiw/unraid/blob/master/NasTools.xml
* 使用方式见：https://github.com/shuosiw/unraid

<img width="1181" alt="3" src="https://user-images.githubusercontent.com/2578976/175561251-75a3ae3f-c927-4148-b75a-81ebc15a1b6e.png">

安装后效果

<img width="815" alt="4" src="https://user-images.githubusercontent.com/2578976/175561327-4fd20008-879e-455f-abf7-fb8ee5194cd1.png">

**在准备提交到 unraid 应用市场，到时候就可以直接在上面搜索安装**

### 教程

将我部署使用过程中的细节整理成文章，可分享给其他同学参考：

* https://post.smzdm.com/p/akkp36gr/

**Comment by log-time** [comment]
建议加到wiki里

**Comment by shuosiw** [comment]
> 建议加到wiki里

已更新：https://github.com/jxxghp/nas-tools/wiki/%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B

大佬帮忙 review 一下看看有没问题

**Comment by shuosiw** [comment]
更新了下篇，我也补充到 wiki 了：

* https://post.smzdm.com/p/aqm5pdwv/
