### ISSUE TITLE
资源订阅站点问题` 

### ISSUE THREAD

**Issue by y2kcan** [jxxghp/nas-tools#365]
![image](https://user-images.githubusercontent.com/103928359/175667735-4e816c71-0eb3-4f1d-a54a-8851d676bceb.png)
![image](https://user-images.githubusercontent.com/103928359/175666698-5a74d141-9080-458a-8c3f-9608efbd298f.png)
订阅时只选一个站点的资源`不会只搜索选择的那个站点搜索`会全部站点搜索一次` 会给各站点增加压力,订阅的资源也是下载其它站点而不是我选择的那个站点资源,希望大佬修复一下

**Comment by jxxghp** [comment]
订阅是增量走RSS，搜索是存量走索引器，是两套。订阅站点只能针对增量RSS生效。

**Comment by jxxghp** [comment]
fixed
