### ISSUE TITLE
豆瓣同步一些需登录才能正常查询的电影显示未知电影 None.

### ISSUE THREAD

**Issue by ztx0079** [jxxghp/nas-tools#366]
未配置cookie时会查询失败.
已配置cookie,这两部电影分别是五十度黑和五十度飞.

10:44:43 INFO - 【DOUBAN】正在查询豆瓣详情：26323032
10:44:43 INFO - 【DOUBAN】电影：未知电影 None
10:44:47 INFO - 【DOUBAN】正在查询豆瓣详情：24840488
10:44:47 INFO - 【DOUBAN】电影：未知电影 None

另外建议在web上也能配置豆瓣cookie.

**Comment by jxxghp** [comment]
f6d56e638e3f5a8fb1e059140e02c27a683cfb00

**Comment by ztx0079** [comment]
> [f6d56e6](https://github.com/jxxghp/nas-tools/commit/f6d56e638e3f5a8fb1e059140e02c27a683cfb00)

豆瓣cookie是配置过的,以下是配置信息.
仍然会报 无权限访问，需要配置豆瓣Cookie

# 【配置豆瓣账号信息】：配置后会自动同步豆瓣收藏，豆瓣标记想看内容后，后台自动下载
douban:
  users:
  - '190037437'
  - '258052680'
  - '148972055'
  - '154483622'
  cookie: douban-fav-remind=1; bid=WeXbmji7LnI; __gads=ID=a0232d37a08b5249-220989df11d300d8:T=1651734638:RT=1651734638:S=ALNI_MbnkkI6dVv0iY3i56JcA9JSNXA4Rg; ll="118282"; __utmz=30149280.1653901287.8.7.utmcsr=baidu|utmccn=(organic)|utmcmd=organic; __yadk_uid=1UcPNncyrn07RWgzWq1bKwzUTZsN4YmJ; _vwo_uuid_v2=DF9510CFABD5077680D36DE30015FAF7A|7863f1921be13db781a062d48efa39c0; push_doumail_num=0; push_noty_num=0; __utmv=30149280.15448; dbcl2="154483622:RbARW8qtI3w"; __utmz=223695111.1656125251.7.3.utmcsr=douban.com|utmccn=(referral)|utmcmd=referral|utmcct=/; ck=aIZH; ap_v=0,6.0; __utma=30149280.2015829200.1605617475.1656124640.1656215459.17; __utmc=30149280; __utmt=1; _pk_ref.100001.4cf6=["","",1656215781,"https://www.douban.com/"]; _pk_ses.100001.4cf6=*; __utma=223695111.736626552.1653901287.1656125251.1656215782.8; __utmb=223695111.0.10.1656215782; __utmc=223695111; __gpi=UID=000006037687db44:T=1653901286:RT=1656215782:S=ALNI_MYYXJZjvykMdgQhRhAkD76BJM361A; __utmb=30149280.9.9.1656215863763; _pk_id.100001.4cf6=234c3e60c006280d.1653901282.8.1656215874.1656125258.
  # 【同步天数】：同步多少天内加入的数据
  days: '30'
  # 【同步间隔】：多久同步一次数据，单位小时，建议不要太频繁，避免被检测到后封号
  interval: '2'
  # 【同步数据类型】：同步哪些类型的收藏数据：do 在看，wish 想看，collect 看过，用逗号分隔配置
  types: wish
  # 【自动开载开关】：同步到豆瓣的数据后是否自动检索PT站并下载（需要配置Jackett）
  auto_search: true
  # 【自动添加RSS开关】：PT站检索找不到的记录是否自动添加RSS订阅（可实现未搜索到的自动追更）
  auto_rss: true
