### ISSUE TITLE
更新1.7.1后不能下载，下载器测试问题

### ISSUE THREAD

**Issue by 512853463** [jxxghp/nas-tools#368]
![Screenshot_2022-06-25-11-39-41-92_a87fd7db6caa850b517aa6fa9d2fcd0e](https://user-images.githubusercontent.com/48006188/175759554-8521d150-e74e-4568-bec5-0f0ca7ec1b83.jpg)
更新完就这样了，3个站都不行，之前可以，配置没变
检查下载器配置发现，即使IP，端口填错也能测试成功

**Comment by jxxghp** [comment]
无法复现
