### ISSUE TITLE
是否增加自定义支持的媒体文件后缀格式？

### ISSUE THREAD

**Issue by remember-ma** [jxxghp/nas-tools#37]
看了一下代码，目前支持的媒体格式很有限
# 支持的媒体文件后缀格式
RMT_MEDIAEXT = ['.mp4', '.mkv', '.ts', '.iso', '.rmvb', '.avi', '.mov', '.mpeg', '.mpg', '.wmv', '.3gp', '.asf']
是否可以在config.yaml配置文件中增加自定义支持的媒体文件后缀格式？

**Comment by jxxghp** [comment]
还有哪种没在上面的？我直接加上

**Comment by remember-ma** [comment]
比如VIDEO_TS目录下的vob文件、flv格式等等，个人建议是增加一个配置项，按需配置。

**Comment by remember-ma** [comment]
但是也有一个问题，VIDEO_TS目录下的文件，都是VTS_01_0.VOB、VTS_01_1.VOB这种格式的命名，真正匹配媒体的时候还需要结合目录名来看，在emby下是正常识别的，但是在自动化工具的逻辑里似乎目前无法正常的识别。

**Comment by jxxghp** [comment]
放配置里增加复杂度，程序不支持配上去也没用。
