### ISSUE TITLE
关于RSS的一个建议

### ISSUE THREAD

**Issue by leo8912** [jxxghp/nas-tools#371]
站点添加多了，并且开了实验室的辅助识别，现在rss任务一次运行得10多分钟。
而现有逻辑下，得等rss任务结束才能发送下载。看了日志，好像后面的站点匹配时也并没有与第一个搜索的站点进行资源质量筛选。

如果是这样，是否第一个匹配到设定规则就先提交下载？
这样追电视剧时，资源到库时间能更及时。。。

**Comment by jxxghp** [comment]
辅助识别可以先关了，如果有效率问题。
RSS有个全局优化规则，要把所有的都筛出来后排序的。
