### ISSUE TITLE
1.7.1重拉镜像安装的bug

### ISSUE THREAD

**Issue by Mruser0** [jxxghp/nas-tools#374]
刚刚删config文件，删除镜像后重新拉最新镜像安装，设置里索引器点击无效，无法在web页面进行设置，应该是bug

**Comment by frankieyue96** [comment]
同样的问题

**Comment by Mruser0** [comment]
应该是老大在调整代码，对其它模块产生了影响，等1.7.2版本更新试试看

**Comment by jxxghp** [comment]
确实是有默认配置兼容性的问题。已修复并更新了个版本号。
