### ISSUE TITLE
【求助】请问如何清理程序执行记录或缓存，以实现同步目录的全部重新同步？

### ISSUE THREAD

**Issue by chingxuds** [jxxghp/nas-tools#375]
由于一些原因，第一次目录同步出现较多识别错误（非识别不成功，而是识别成另一部）的影视，后经手工整理原目录后，希望能够全量重新同步，然后做了以下步骤：
1、删除目的目录下的所有硬链接。
2、删除了所有同步历史记录，为了方便再有新的识别问题可以找出。这里也请教下如何批量删除，系统上并没有发现类似功能。
3、手动执行了目录同步，结果发现只有部分影视重新进行了同步，原正常影视提示“所有文件均已成功转移过，没有需要处理的文件”，但是由于硬链接已被全部删除，所以目的目录下也没有文件了。
请问该如何清理掉历史记录或缓存？

附图：
<img width="713" alt="图片" src="https://user-images.githubusercontent.com/3142486/175797914-939f67bd-d29c-4180-933f-6c221bd863d3.png">

**Comment by jxxghp** [comment]
配置文件目录备份后删除user.db

**Comment by chingxuds** [comment]
> 配置文件目录备份后删除user.db

经验证可以，多谢！
