### ISSUE TITLE
1.7.2版本RSS订阅的bug

### ISSUE THREAD

**Issue by Mruser0** [jxxghp/nas-tools#377]
1.下午删config文件删镜像重新拉镜像安装完docker镜像后，从web推荐页面添加了梦华录订阅，本地已有1-32集，5:10分馒头更了1-40集全集，5:27nastool后台自动运行RSS订阅，检索不到有效资源。
        2.从微信搜索梦华录检索后自动从这个全集种子里下载了缺失的33-40集，文件硬连接完成，web页面RSS订阅梦华录仍然没有删除（总集数40集已全部下完），仍然显示在32集，继续rss
         3.注:站点维护过滤规则和索引器jackett过滤规则一致，且同规则1.7.0版本RSS订阅正常，其它剧如狮子山下的故事也存在同样的问题。

**Comment by log-time** [comment]
rss下载完成后，订阅记录在下一周期命中该记录时删除

**Comment by Mruser0** [comment]
> rss下载完成后，订阅记录在下一周期命中该记录时删除

明白，但是已经又连续跑了好几次rss了，依然没有自动删除，种子命名和编码格式仔细对照过，符合命中条件，但是现在在手动微信搜索完成全集下载转移的情况下，仍然没有自动删除订阅

**Comment by jxxghp** [comment]
手动下的本来就不会自动删订阅，你都手动下齐了自然也不会再命中RSS。

**Comment by Mruser0** [comment]
> > rss下载完成后，订阅记录在下一周期命中该记录时删除
> 
> 明白，但是已经又连续跑了好几次rss了，依然没有自动删除，种子命名和编码格式仔细对照过，符合命中条件，但是现在在手动微信搜索完成全集下载转移的情况下，仍然没有自动删除订阅

![UYM54F4S}Q2PCPK~KDQ(P(O](https://user-images.githubusercontent.com/107661622/175817562-60da9983-911b-4c43-b6c3-63e391162c67.png)
这是重装1.7.2nastool的时间

![NG)(LZ2XT 2H5$O$3IASDV](https://user-images.githubusercontent.com/107661622/175817660-99dc42ec-6049-4faf-99fc-895d82a3841c.png)
这是添加订阅后第一次开始rss的时间，此时本地已存在1-32集，33-40集pt站未更新



![DS)9@QLS`S)}R$T`_OW) MB](https://user-images.githubusercontent.com/107661622/175817782-f4c42a06-4992-41c1-af58-ea220e8f4204.png)



这是web订阅页面的显示
![E4O0$HE}TLQ}1WBFF1T92 4](https://user-images.githubusercontent.com/107661622/175817857-c85152fc-c559-4c2f-abf4-01cd93122907.png)


这是我的pt站5:10更新的第一个梦华录全集种子
![75K_B2K(T%O}L6UV SPV71U](https://user-images.githubusercontent.com/107661622/175818006-90df4690-3f95-41f4-aa6d-1025d9ee8c07.png)


这是pt站新增种子后的rss
![E8BFDM)Z`HJZ0G(VFBF IVO](https://user-images.githubusercontent.com/107661622/175818236-e1b09ce1-0ef9-40a6-89f2-2a4c1d3d38c3.png)

然后从微信搜索下载，从这个种子里检索到了缺失的8集并下载完成

![RXG72MA9LJ68}X{@F9TM`O](https://user-images.githubusercontent.com/107661622/175818517-857ccda5-8e76-457b-80fd-e730c6b5a1e5.png)


我设置的一直是30分钟rss一次，然后到现在为止，梦华录在已经全部完成下载的情况下web订阅页面仍然还在32集订阅状态

![QR${8BUV7V28W6YW(A~U1{I](https://user-images.githubusercontent.com/107661622/175818619-0c581d7b-f6af-44e4-aeee-9aaa160b8a37.png)

这是我站点的过滤规则
![1`I}EF3(YYPER485QB(GV~E](https://user-images.githubusercontent.com/107661622/175818694-64a47d66-1d2c-4c0c-9676-cc59042aa562.png)



这是jackett的过滤规则

![_D$F36ODS`~59B`X 5(8OMV](https://user-images.githubusercontent.com/107661622/175818728-11d23d25-d889-462a-9e85-f6a73e06a156.png)


存在的问题是：
1.rss在种子符合命中条件的情况下没有准确命中并订阅下载
2.本地库在通过微信jackett搜索择优下载后没有联动rss删除订阅
3.rss在本地存在全集的情况下仍然在订阅，没有进行硬链接库存集数的判断
