### ISSUE TITLE
能否给各个功能点添加单独的开关，多个媒体目录设置单独文件转移方式，还有消息提醒开关？

### ISSUE THREAD

**Issue by leonyff** [jxxghp/nas-tools#38]
首先感谢，因为我没有PT站，没有使用豆瓣，使用手动下载配合 qb分类功能，有几个问题能否有办法：

1. 配置了企业微信消息提醒，没有配置 PT站的签到信息也会提醒，能否有提醒的开关
2. 想在是统一设置媒体文件的转移方式，是否每个文件加单独设置（有个单独的磁盘下载）
3. 另外能不能支持，prowlarr  我感觉比 jackett 好用，（虽然现还是 beta 版）

**Comment by jxxghp** [comment]
1. 签到是可以关闭的，请看配置模板中的说明，签到时间配置为空。
2. 不建议
3. prowlarr没有对外提供api
