### ISSUE TITLE
关于识别存在的问题

### ISSUE THREAD

**Issue by chingxuds** [jxxghp/nas-tools#380]
当前进行目录同步时，发现了一个奇怪的识别错误，一个系列电影中的某一部被识别成了年份、名称均不同且不相似的电影，如下图：

<img width="1600" alt="图片" src="https://user-images.githubusercontent.com/3142486/175816815-86243924-eb28-49ef-8b94-1fe5caa5f469.png">

被错误识别的电影为《致命弯道4（Wrong Turn 4 2011）》，被识别成《白化农场（Albino Farm 2009）》，两者无论是中文名、英文名还是年份均不相同，不知道为何会发生错误识别。

**Comment by jxxghp** [comment]
致命弯道4没有 Wrong Turn 4 这个别名。
刚好白化农场有，应该是用人把词条维护错了，你去TMDB看下别名就知道了。

**Comment by chingxuds** [comment]
> 致命弯道4没有 Wrong Turn 4 这个别名。 刚好白化农场有，应该是用人把词条维护错了，你去TMDB看下别名就知道了。

我查询了下，《白化农场》确实有个别名。但想请教下，我试了直接使用Wrong Turn 4和2011能够查询到对应电影，但是日志显示没查询到，这块可能的原因是什么？
![图片](https://user-images.githubusercontent.com/3142486/175876916-3106da6f-d2bc-4a9e-8020-8d9347355d95.png)
![图片](https://user-images.githubusercontent.com/3142486/175877605-ff0d751d-3e87-463d-b514-4d43fe7601ea.png)
