### ISSUE TITLE
希望手动识别的自定义识别界面增加仅硬链功能

### ISSUE THREAD

**Issue by fxqq** [jxxghp/nas-tools#381]
因为有一些资源下载了后可能是由于命名不规范或者其他原因，导致nastools识别出来是图2的结果，节目顺序都是错的，希望在手动识别界面增加仅硬链的功能，这样方便我可以把硬链后的文件按照TMDB信息规范改名后再让nastools来识别，就是先硬链不改名，手动改名后再次硬链识别改名。
<a href="http://www.picgo.net/image/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE-20220626213200.WVyjW"><img src="https://img.picgo.net/2022/06/26/_20220626213200.md.png" alt="_20220626213200.md.png" border="0"></a>
<a href="http://www.picgo.net/image/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE-20220626213324.WVX1i"><img src="https://img.picgo.net/2022/06/26/_20220626213324.md.png" alt="_20220626213324.md.png" border="0"></a>

**Comment by jxxghp** [comment]
节目顺序哪里错了？

**Comment by fxqq** [comment]
<a href="http://www.picgo.net/image/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE-20220626223617.WVUX2"><img src="https://img.picgo.net/2022/06/26/_20220626223617.md.png" alt="_20220626223617.md.png" border="0"></a>
就是源文件的part2.S01E01，在TMDB中是S01E02，但是硬链改名是还是当做S01E01的，当然这个是源文件命名和TMDB差异所致的

**Comment by JohnZp** [comment]
你要是不嫌麻烦， 可以用集数定位，中间那个功能， 直接填数字， 就可以把对应视频硬链接到对应的集数

**Comment by fxqq** [comment]
> 你要是不嫌麻烦， 可以用集数定位，中间那个功能， 直接填数字， 就可以把对应视频硬链接到对应的集数

一集一集这个倒是个办法，就是比较慢，我是想先全部硬链，然后用renamer把集数改的和TMDB一样规范这样识别改名就不会有错了

**Comment by jxxghp** [comment]
手工识别集数定位现在是支持批量处理的。
没必要因为这一个资源的命名问题花大力气去做新功能吧
