### ISSUE TITLE
企微需要固定ip加入白名单，不支持DDNS，你们都怎么解决？

### ISSUE THREAD

**Issue by ChestnutHeng** [jxxghp/nas-tools#386]

**Comment by haohao232323** [comment]
没办法解决，动态的IP加进去，重启路由器IP变了就不能用了

**Comment by ldt0621** [comment]
我也是遇到这个问题，实在不行只能换通知了

**Comment by log-time** [comment]
不知道微信有没有自动添加可信ip的api接口。
不行自己搞个固定ip的vps，整个消息转发？就是成本上去了，不如直接整telegram了。

**Comment by shuosiw** [comment]
我用的移动宽带，本身就没有公网 v4，目前是用 1M 的腾讯云小水管做 frp 穿透代理（tx vps 之前搞活动挺便宜的）

相关的教程文档也在整理了，后续更新出来

**Comment by shuosiw** [comment]
计划应该是下周，主要是 frp 设计太多命令行操作，我在想怎么写比较更容易理解hah

**Comment by shuosiw** [comment]
https://post.smzdm.com/p/apvpv78w/

@ldt0621 已经发布~
