### ISSUE TITLE
无法识别媒体信息！

### ISSUE THREAD

**Issue by liewoi** [jxxghp/nas-tools#387]
16:45:39 - The resource you requested could not be found.
16:45:39 INFO - 【RMT】开始处理：/download/anime/[VCB-Studio] K-ON!/[VCB-Studio] K-ON!! [Ma10p_1080p]
16:45:39 WARN - 【RMT】[VCB-Studio] K-ON!! [01][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:39 ERROR - 【RMT】[VCB-Studio] K-ON!! [01][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:39 WARN - 【RMT】[VCB-Studio] K-ON!! [02][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:39 ERROR - 【RMT】[VCB-Studio] K-ON!! [02][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:40 WARN - 【RMT】[VCB-Studio] K-ON!! [03][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:40 ERROR - 【RMT】[VCB-Studio] K-ON!! [03][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:40 WARN - 【RMT】[VCB-Studio] K-ON!! [04][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:40 ERROR - 【RMT】[VCB-Studio] K-ON!! [04][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:40 WARN - 【RMT】[VCB-Studio] K-ON!! [05][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:40 ERROR - 【RMT】[VCB-Studio] K-ON!! [05][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:40 WARN - 【RMT】[VCB-Studio] K-ON!! [06][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:40 ERROR - 【RMT】[VCB-Studio] K-ON!! [06][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:40 WARN - 【RMT】[VCB-Studio] K-ON!! [07][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:40 ERROR - 【RMT】[VCB-Studio] K-ON!! [07][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:41 WARN - 【RMT】[VCB-Studio] K-ON!! [08][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:41 ERROR - 【RMT】[VCB-Studio] K-ON!! [08][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:41 WARN - 【RMT】[VCB-Studio] K-ON!! [09][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:41 ERROR - 【RMT】[VCB-Studio] K-ON!! [09][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:41 WARN - 【RMT】[VCB-Studio] K-ON!! [10][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:41 ERROR - 【RMT】[VCB-Studio] K-ON!! [10][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:41 WARN - 【RMT】[VCB-Studio] K-ON!! [11][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:41 ERROR - 【RMT】[VCB-Studio] K-ON!! [11][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:42 WARN - 【RMT】[VCB-Studio] K-ON!! [12][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:42 ERROR - 【RMT】[VCB-Studio] K-ON!! [12][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:42 WARN - 【RMT】[VCB-Studio] K-ON!! [13][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:42 ERROR - 【RMT】[VCB-Studio] K-ON!! [13][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:42 WARN - 【RMT】[VCB-Studio] K-ON!! [14][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:42 ERROR - 【RMT】[VCB-Studio] K-ON!! [14][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:42 WARN - 【RMT】[VCB-Studio] K-ON!! [15][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:42 ERROR - 【RMT】[VCB-Studio] K-ON!! [15][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:43 WARN - 【RMT】[VCB-Studio] K-ON!! [16][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:43 ERROR - 【RMT】[VCB-Studio] K-ON!! [16][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:43 WARN - 【RMT】[VCB-Studio] K-ON!! [17][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:43 ERROR - 【RMT】[VCB-Studio] K-ON!! [17][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:43 WARN - 【RMT】[VCB-Studio] K-ON!! [18][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:43 ERROR - 【RMT】[VCB-Studio] K-ON!! [18][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:43 WARN - 【RMT】[VCB-Studio] K-ON!! [25][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:43 ERROR - 【RMT】[VCB-Studio] K-ON!! [25][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:44 WARN - 【RMT】[VCB-Studio] K-ON!! [26][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:44 ERROR - 【RMT】[VCB-Studio] K-ON!! [26][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:44 WARN - 【RMT】[VCB-Studio] K-ON!! [27][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:44 ERROR - 【RMT】[VCB-Studio] K-ON!! [27][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:45:44 INFO - 【RMT】/download/anime/[VCB-Studio] K-ON!/[VCB-Studio] K-ON!! [Ma10p_1080p] 处理完成，总数：21，失败：21
16:45:44 INFO - 【MSG】发送serverchan消息：title=有 21 个文件转移失败，请登录NASTool查看, text=
16:46:14 - The resource you requested could not be found.
16:46:14 INFO - 【RMT】开始处理：/download/anime/[VCB-Studio] K-ON!/[VCB-Studio] K-ON!! [Ma10p_1080p]
16:46:14 WARN - 【RMT】[VCB-Studio] K-ON!! [01][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:14 ERROR - 【RMT】[VCB-Studio] K-ON!! [01][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:14 WARN - 【RMT】[VCB-Studio] K-ON!! [02][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:14 ERROR - 【RMT】[VCB-Studio] K-ON!! [02][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:15 WARN - 【RMT】[VCB-Studio] K-ON!! [03][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:15 ERROR - 【RMT】[VCB-Studio] K-ON!! [03][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:15 WARN - 【RMT】[VCB-Studio] K-ON!! [04][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:15 ERROR - 【RMT】[VCB-Studio] K-ON!! [04][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:15 WARN - 【RMT】[VCB-Studio] K-ON!! [05][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:15 ERROR - 【RMT】[VCB-Studio] K-ON!! [05][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:16 WARN - 【RMT】[VCB-Studio] K-ON!! [06][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:16 ERROR - 【RMT】[VCB-Studio] K-ON!! [06][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:16 WARN - 【RMT】[VCB-Studio] K-ON!! [07][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:16 ERROR - 【RMT】[VCB-Studio] K-ON!! [07][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:16 WARN - 【RMT】[VCB-Studio] K-ON!! [08][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:16 ERROR - 【RMT】[VCB-Studio] K-ON!! [08][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:17 WARN - 【RMT】[VCB-Studio] K-ON!! [09][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:17 ERROR - 【RMT】[VCB-Studio] K-ON!! [09][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:17 WARN - 【RMT】[VCB-Studio] K-ON!! [10][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:17 ERROR - 【RMT】[VCB-Studio] K-ON!! [10][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:17 WARN - 【RMT】[VCB-Studio] K-ON!! [11][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:17 ERROR - 【RMT】[VCB-Studio] K-ON!! [11][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:17 WARN - 【RMT】[VCB-Studio] K-ON!! [12][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:17 ERROR - 【RMT】[VCB-Studio] K-ON!! [12][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:18 WARN - 【RMT】[VCB-Studio] K-ON!! [13][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:18 ERROR - 【RMT】[VCB-Studio] K-ON!! [13][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:18 WARN - 【RMT】[VCB-Studio] K-ON!! [14][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:18 ERROR - 【RMT】[VCB-Studio] K-ON!! [14][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:18 WARN - 【RMT】[VCB-Studio] K-ON!! [15][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:18 ERROR - 【RMT】[VCB-Studio] K-ON!! [15][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:18 WARN - 【RMT】[VCB-Studio] K-ON!! [16][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:18 ERROR - 【RMT】[VCB-Studio] K-ON!! [16][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:19 WARN - 【RMT】[VCB-Studio] K-ON!! [17][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:19 ERROR - 【RMT】[VCB-Studio] K-ON!! [17][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:19 WARN - 【RMT】[VCB-Studio] K-ON!! [18][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:19 ERROR - 【RMT】[VCB-Studio] K-ON!! [18][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:19 WARN - 【RMT】[VCB-Studio] K-ON!! [25][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:19 ERROR - 【RMT】[VCB-Studio] K-ON!! [25][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:19 WARN - 【RMT】[VCB-Studio] K-ON!! [26][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:19 ERROR - 【RMT】[VCB-Studio] K-ON!! [26][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:20 WARN - 【RMT】[VCB-Studio] K-ON!! [27][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:20 ERROR - 【RMT】[VCB-Studio] K-ON!! [27][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:46:20 INFO - 【RMT】/download/anime/[VCB-Studio] K-ON!/[VCB-Studio] K-ON!! [Ma10p_1080p] 处理完成，总数：21，失败：21
16:46:20 INFO - 【MSG】发送serverchan消息：title=有 21 个文件转移失败，请登录NASTool查看, text=
16:47:16 - The resource you requested could not be found.
16:47:16 INFO - 【RMT】开始处理：/download/anime/[VCB-Studio] K-ON!/[VCB-Studio] K-ON!! [Ma10p_1080p]
16:47:16 WARN - 【RMT】[VCB-Studio] K-ON!! [01][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:16 ERROR - 【RMT】[VCB-Studio] K-ON!! [01][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:16 WARN - 【RMT】[VCB-Studio] K-ON!! [02][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:16 ERROR - 【RMT】[VCB-Studio] K-ON!! [02][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:17 WARN - 【RMT】[VCB-Studio] K-ON!! [03][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:17 ERROR - 【RMT】[VCB-Studio] K-ON!! [03][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:17 WARN - 【RMT】[VCB-Studio] K-ON!! [04][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:17 ERROR - 【RMT】[VCB-Studio] K-ON!! [04][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:17 WARN - 【RMT】[VCB-Studio] K-ON!! [05][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:17 ERROR - 【RMT】[VCB-Studio] K-ON!! [05][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:17 WARN - 【RMT】[VCB-Studio] K-ON!! [06][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:17 ERROR - 【RMT】[VCB-Studio] K-ON!! [06][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:18 WARN - 【RMT】[VCB-Studio] K-ON!! [07][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:18 ERROR - 【RMT】[VCB-Studio] K-ON!! [07][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:18 WARN - 【RMT】[VCB-Studio] K-ON!! [08][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:18 ERROR - 【RMT】[VCB-Studio] K-ON!! [08][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:18 WARN - 【RMT】[VCB-Studio] K-ON!! [09][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:18 ERROR - 【RMT】[VCB-Studio] K-ON!! [09][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:19 WARN - 【RMT】[VCB-Studio] K-ON!! [10][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:19 ERROR - 【RMT】[VCB-Studio] K-ON!! [10][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:19 WARN - 【RMT】[VCB-Studio] K-ON!! [11][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:19 ERROR - 【RMT】[VCB-Studio] K-ON!! [11][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:19 WARN - 【RMT】[VCB-Studio] K-ON!! [12][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:19 ERROR - 【RMT】[VCB-Studio] K-ON!! [12][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:19 WARN - 【RMT】[VCB-Studio] K-ON!! [13][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:19 ERROR - 【RMT】[VCB-Studio] K-ON!! [13][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:20 WARN - 【RMT】[VCB-Studio] K-ON!! [14][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:20 ERROR - 【RMT】[VCB-Studio] K-ON!! [14][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:20 WARN - 【RMT】[VCB-Studio] K-ON!! [15][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:20 ERROR - 【RMT】[VCB-Studio] K-ON!! [15][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:20 WARN - 【RMT】[VCB-Studio] K-ON!! [16][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:20 ERROR - 【RMT】[VCB-Studio] K-ON!! [16][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:20 WARN - 【RMT】[VCB-Studio] K-ON!! [17][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:20 ERROR - 【RMT】[VCB-Studio] K-ON!! [17][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:21 WARN - 【RMT】[VCB-Studio] K-ON!! [18][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:21 ERROR - 【RMT】[VCB-Studio] K-ON!! [18][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:21 WARN - 【RMT】[VCB-Studio] K-ON!! [25][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:21 ERROR - 【RMT】[VCB-Studio] K-ON!! [25][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:21 WARN - 【RMT】[VCB-Studio] K-ON!! [26][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:21 ERROR - 【RMT】[VCB-Studio] K-ON!! [26][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:21 WARN - 【RMT】[VCB-Studio] K-ON!! [27][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:21 ERROR - 【RMT】[VCB-Studio] K-ON!! [27][Ma10p_1080p][x265_flac_2aac].mkv 无法识别媒体信息！
16:47:22 INFO - 【RMT】/download/anime/[VCB-Studio] K-ON!/[VCB-Studio] K-ON!! [Ma10p_1080p] 处理完成，总数：21，失败：21
16:47:22 INFO - 【MSG】发送serverchan消息：title=有 21 个文件转移失败，请登录NASTool查看, text=

如何解决！？

**Comment by liewoi** [comment]
手动识别依然不行

**Comment by Davonng** [comment]
看起来似乎是命名问题

**Comment by liewoi** [comment]
> 看起来似乎是命名问题

我用ep定位似乎没用

**Comment by jxxghp** [comment]
动漫命名不规范，不识别很正常
