### ISSUE TITLE
希望添加Hosts到容器中！

### ISSUE THREAD

**Issue by gxgl2022** [jxxghp/nas-tools#39]
我配置了很多次，总是无法使用themoviedb进行影视识别。后面才知道需要添加以下到Hosts中

vi /etc/hosts
在键盘上点击i，发现左下角已经变成了INSERT

在最后一行后添加如下：

13.226.238.76 api.themoviedb.org
13.224.161.90 api.themoviedb.org
13.35.7.102 api.themoviedb.org
13.225.103.26 api.themoviedb.org
13.226.191.85 api.themoviedb.org
13.225.103.110 api.themoviedb.org
52.85.79.89 api.themoviedb.org
13.225.41.40 api.themoviedb.org
13.226.251.88 api.themoviedb.org
13.225.89.239 api.thetvdb.com
13.249.175.212 api.thetvdb.com
13.35.161.120 api.thetvdb.com

我们按esc退出编辑模式，然后退出

:wq

这样就可以正常使用themoviedb

**Comment by remember-ma** [comment]
hosts各网络环境下会有区别吧，直接加到容器里没多大意义吧

**Comment by jxxghp** [comment]
容器的上网环境不适合固化到程序中。
