### ISSUE TITLE
下载器单个类别不能设置多个目录，希望添加此功能

### ISSUE THREAD

**Issue by ldt0621** [jxxghp/nas-tools#394]
![微信截图_20220628160025](https://user-images.githubusercontent.com/68332968/176126457-5fc16058-e13f-4493-b2bf-ea0e7cde045f.png)
比如电影目录只能设置1个储存路径，不能设置多个
希望可以添加此功能，来自主选择想储存的硬盘

非常感谢作者的付出，点赞👍

**Comment by jxxghp** [comment]
设多个，下载器也不知道使用哪个吧？

**Comment by ldt0621** [comment]
这是来自李登陶的自动回复邮件。
 
您好，您的邮件我已接收，我会及时回复您。祝您生活愉快。
