### ISSUE TITLE
提一个建议，求老大能实现。。

### ISSUE THREAD

**Issue by leo8912** [jxxghp/nas-tools#395]
现在的选中规则，不太懂。
是不是自定义规则＞站点免费＞做种人数
最近下载，下了好多次小站点做种人数为1的种子，下载速度非常非常慢，甚至会断。。。
能不能默认规则屏蔽掉小站的做种人数为1 的老种子。（大站新发布的种子除外，可以按种子发布时间来添加例外）。

另外，是否可以自定义设定几个规则，在订阅时，可以直接选择规则订阅。
例如，我追电视剧，只要快（并且方便外网播放），就选一个追剧规则。
有些片子需要收藏的，就选原盘规则，等等等等。

**Comment by log-time** [comment]
感觉有些孤种能下载下来就很满意了，下的慢点倒是无所谓。
添加自定义的预设规则倒是挺好的。

**Comment by leo8912** [comment]
> 

主要是大站有资源，有速度。我看了下载的几个，可能是小站是免费的原因。不知道老大的选种规则，是不是免费＞人数。

**Comment by jxxghp** [comment]
现在是优先规则>站点顺序>做种数。把想下的站点配置到前面，RSS和Jackett。prowlarr不支持。

**Comment by leo8912** [comment]
> 现在是优先规则>站点顺序>做种数。把想下的站点配置到前面，RSS和Jackett。prowlarr不支持。

那免费种子有优先吗？我再测试看看吧，我就是大站在前面的，下了几个排名末尾的两个小站。。

**Comment by jxxghp** [comment]
> > 现在是优先规则>站点顺序>做种数。把想下的站点配置到前面，RSS和Jackett。prowlarr不支持。
> 
> 那免费种子有优先吗？我再测试看看吧，我就是大站在前面的，下了几个排名末尾的两个小站。。

没有免费优先的逻辑，说清楚你的场景，是RSS订阅还是搜索，是什么渠道搜索？

**Comment by leo8912** [comment]
> > > 现在是优先规则>站点顺序>做种数。把想下的站点配置到前面，RSS和Jackett。prowlarr不支持。
> > 
> > 那免费种子有优先吗？我再测试看看吧，我就是大站在前面的，下了几个排名末尾的两个小站。。
> 
> 没有免费优先的逻辑，说清楚你的场景，是RSS订阅还是搜索，是什么渠道搜索？

第一次是前天订阅的梦华录出全集，rss最后几集的时候，下载了hdtime的一人种（不知道是不是大站是合成全集的原因）
第二次是今天添加订阅通天塔，第一次是搜索，下载了hd.ai的一人种。
这两个站点在jackett索引和rss站点优先级都是排在最后的。
