### ISSUE TITLE
硬链接的目录删除了，再次同步目录，硬链接不会再生成

### ISSUE THREAD

**Issue by simon428** [jxxghp/nas-tools#400]
日志提示已经成功转移过，不再转移。有什么办法可以再转移？

**Comment by jxxghp** [comment]
自定义转移手工搞

**Comment by So-Yp** [comment]
> 自定义转移手工制作

大佬，历史记录有时候回删除不了，于是自己手动删了硬链接目录，再次同步的时候提示已经成功转移过，请问历史记录能修复下吗？

**Comment by So-Yp** [comment]
> 自定义转移手工制作

大佬，历史记录有时候会删除不了，于是自己手动删了硬链接目录，再次同步的时候提示已经成功转移过，请问历史记录删除能修复下吗？

**Comment by jxxghp** [comment]
> > 自定义转移手工制作
> 
> 
> 
> 大佬，历史记录有时候会删除不了，于是自己手动删了硬链接目录，再次同步的时候提示已经成功转移过，请问历史记录删除能修复下吗？

历史记录删不掉的问题改了。
