### ISSUE TITLE
矿神SPK 群晖7.1系统无法使用

### ISSUE THREAD

**Issue by ziyefeixing** [jxxghp/nas-tools#409]
矿神的SPK 群晖7.0可以正常使用 7.1版本的系统可以正常安装但是无法正常使用，打不开NAS-tools。看了一下端口，安装好套件版NAS-tool后端口3003未被占用，应该是端口设置有问题，希望能排查一下。

**Comment by jxxghp** [comment]
我没有7.1的环境

**Comment by liucheng1109** [comment]
我也是无法使用，群晖套件的。7.1版本

**Comment by jiezuowhu** [comment]
+1

**Comment by gclm** [comment]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/27618687/176993223-a18ab37b-042f-42b0-8b7b-7e240ac0fd65.png">

**Comment by tbc0309** [comment]
安装后打不开是因为你的网络原因 python 安装pip以及后面的依赖拉取不到。

可以试试新做的wheelhouse依赖离线安装版本：https://github.com/tbc0309/nas-tools/tree/master/synology

@jxxghp 大佬您帮忙测试同步更新下，DSM6、7除了os_min_ver=不同，其它完全一致。

**Comment by typechoblog** [comment]
> 查看群友反馈的安装远程，问题总结：安装后打不开是因为你的网络python安装了pip以及上面的依赖拉取不到。
> 
> 可以尝试新做的wheelhouse依赖离线安装版本：https://github.com/tbc0309/nas-tools/tree/master/synology
> 
> @jxxghp大佬帮忙测试同步更新下，DSM6、7除了os_min_ver=不同，其他完全一致。（源中DSM6不需要了）
> 
> 1、修改了：scripts/installer，2、添加了wheelhouse文件夹。

使用 https://github.com/tbc0309/nas-tools/tree/master/synology 所提供的[nastool_dsm_6.x.spk](https://github.com/tbc0309/nas-tools/blob/master/synology/nastool_dsm_6.x.spk)  DSM 6.2.1-23824 Update 6 黑裙可以正常使用
