### ISSUE TITLE
手动转移增加季选择,防止剧集匹配错季。

### ISSUE THREAD

**Issue by smily1223** [jxxghp/nas-tools#41]
![image](https://user-images.githubusercontent.com/37728519/162548442-22a645da-372d-429b-bbb5-5f6033470017.png)
>希望能在手动转移增加季选择。
>因为有些剧集命名不规范，没有在命名中体现出对应季。
>这就导致了匹配出来的数据是剧集的第一季数据。

**Comment by jxxghp** [comment]
v0.4.06 已支持
