### ISSUE TITLE
收到来自 ::ffff:127.0.0.1 的非法Telegram消息：

### ISSUE THREAD

**Issue by xiuxinY** [jxxghp/nas-tools#412]
设置了Telegram通知，相应的https外网访问也都配置好了。bot接收消息正常，但是从bot发送消息会提示警告：
`
收到来自 ::ffff:127.0.0.1 的非法Telegram消息：xxxxxxxxxxxxxxx
`
日志如下：
![Snipaste_2022-07-01_10-53-10](https://figs.fiss.xyz//PicGo/202207011054605.JPG)

**Comment by jxxghp** [comment]
网络上有什么特别吗，为什么变本地地址了。
安全那里可以设置IP信任范围，设一下放开即可。

**Comment by xiuxinY** [comment]
网络走了http代理，为什么变成本地地址我也不清楚。但是安全那里设置成开放问题解决了。感谢！
