### ISSUE TITLE
ChineseSubFinder字幕下载失败 physical video file not found

### ISSUE THREAD

**Issue by woshijie120** [jxxghp/nas-tools#415]
目前正在使用ChineseSubFinder进行字幕下载，在ChineseSubFinder这个项目内下载一切正常
通过nas-tools下载后的电影/电视剧可以正常自动触发字幕下载，日志提示【SUBTITLE】ChineseSubFinder下载字幕出错：physical video file not found，请问下是调用接口的问题，还是接口本身的问题？
![error](https://user-images.githubusercontent.com/108522192/176872841-dbbe1a20-14ff-4930-9a39-80a6824cdc9e.png)

**Comment by log-time** [comment]
https://github.com/jxxghp/nas-tools/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#14chinesesubfinder%E8%B0%83%E7%94%A8%E9%94%99%E8%AF%AF-physical-video-file-not-found
