### ISSUE TITLE
硬链接的一点问题

### ISSUE THREAD

**Issue by 26712681** [jxxghp/nas-tools#419]
这是源文件夹
![image](https://user-images.githubusercontent.com/77581926/176980918-caa278c2-f0cb-4c24-83ca-d2796ca7a7e3.png)

这是链接后的文件夹
![image](https://user-images.githubusercontent.com/77581926/176981249-2236f0a2-2445-4ead-9ee9-c0720a39788b.png)

不知道为什么加上了一些原盘的文件夹在里面。

**Comment by jxxghp** [comment]
我猜是同时下了原盘和非原盘的资源，所以转一起去了。

**Comment by 26712681** [comment]
是我草率了  之前确实下过。但是刚检查还有另外一个问题
![image](https://user-images.githubusercontent.com/77581926/176984101-cf9013d6-29c1-4eb7-8352-523e7f436510.png)
原盘很多链接过去了  但是这里很多未识别的

**Comment by jxxghp** [comment]
圆盘只支持一层目录

**Comment by 26712681** [comment]
这样啊   明白了 那我得调整下目录结构了
