### ISSUE TITLE
连接TMDB出错

### ISSUE THREAD

**Issue by qqwas** [jxxghp/nas-tools#421]
自动识别出错，手动识别报如下错误，我试了直接在浏览器用url内容访问是正常的
15:35:47 ERROR - 【META】连接TMDB出错：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/search/movie?api_key=8788fcXXXXXXXXX2817333517c5c213ff&query=%E8%92%B8%E5%8F%91%E5%AF%86%E4%BB%A4%EF%BC%9A%E9%87%8D%E7%94%9F&year=2022&language=zh-CN (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

**Comment by qqwas** [comment]
已经解决

**Comment by 62080601** [comment]
请问是怎么解决的？我改了群晖的hosts也没用

**Comment by else05** [comment]
> 已经解决

我也出现这个问题，怎么处理

**Comment by Evopower** [comment]
我也是这个问题，劫持DNS也没用，很崩溃搜什么都搜不出来
