### ISSUE TITLE
部分剧集搜索不到

### ISSUE THREAD

**Issue by leo8912** [jxxghp/nas-tools#424]
之前通天塔以为是筛选到小站的，经过今天测试多次，发现是没有搜到结果
![IMG_20220703_003635.jpg](https://user-images.githubusercontent.com/22719866/177008970-415418e2-6ddf-45ab-aa5a-b5e82c24286d.jpg)
![IMG_20220703_003736.jpg](https://user-images.githubusercontent.com/22719866/177009151-cd8865a3-9d20-4676-8a5b-8673f71f9e48.jpg)

以上测试时，jackett过滤规则已全部清空

另外订阅时还发现一个问题，如果指定年份2022，订阅结果就会变成2019的一个韩剧
![IMG_20220703_003609.jpg](https://user-images.githubusercontent.com/22719866/177009011-a7a947e0-5eac-4433-b506-ab0c6e63c23e.jpg)
![Screenshot_2022-07-03-00-39-16-724_nekox.messenger.png](https://user-images.githubusercontent.com/22719866/177009014-c66329de-b0a8-4320-8f5d-f38fa97d2c65.png)

（个人觉得是不是应该参考搜索时，先给出tmdb卡片信息，然后选择具体哪个剧更好一点。
另外搜索时，选择卡片，未完结的是否可以自动添加订阅）

**Comment by jxxghp** [comment]
你在TMDB缓存查下Babel这个词条，看下是什么。我怀疑TMDB改过名字，你订阅的早，缓存的是错的，导致一直匹配不上。

**Comment by leo8912** [comment]
> 你在TMDB缓存查下Babel这个词条，看下是什么。我怀疑TMDB改过名字，你订阅的早，缓存的是错的，导致以前能匹配上但现在一直匹配不上。

![Screenshot_2022-07-03-08-54-00-160_org.mozilla.fenix-edit.jpg](https://user-images.githubusercontent.com/22719866/177020416-d038e6c5-aad9-4536-a2aa-39fba8cd3fbf.jpg)

删除缓存后确实能搜到了。那这个有什么办法能避免吗？定期更新缓存？

**Comment by leo8912** [comment]
> 你在TMDB缓存查下Babel这个词条，看下是什么。我怀疑TMDB改过名字，你订阅的早，缓存的是错的，导致以前能匹配上但现在一直匹配不上。

删除缓存后，出现识别错误。
![Screenshot_2022-07-03-09-47-30-473_com.tencent.mm.png](https://user-images.githubusercontent.com/22719866/177021314-12235c66-15e3-4e30-9519-a9668798e74a.png)
可能是上面第二个年份识别问题，指定订阅2022年份，就会识别成2019的

**Comment by jxxghp** [comment]
识别都是统一策略，个别命名跟词条的问题我也没办法。

**Comment by leo8912** [comment]
> 识别都是统一策略，个别命名跟词条的问题我也没办法。

不是这个意思。是添加订阅时，如果你添加了年份信息2022。搜索出来的就变成2019年的剧，跟你设置的信息对不上了。
如果你不指定2022年，搜索出来就是2022的剧了。。
