### ISSUE TITLE
新版本似乎每次进站点数据统计页面都需要刷新数据，影响体验

### ISSUE THREAD

**Issue by log-time** [jxxghp/nas-tools#427]
新版本似乎每次进站点数据统计页面都需要刷新数据，体验较差

**Comment by jxxghp** [comment]
@lightolly

**Comment by log-time** [comment]
我有一个想法，不知合适不合适。就是数据刷新是否可以放在后台定时来做，点击进入页面直接展示上次刷新后的数据。而不是点击该页面后才刷新，导致第一次进入该页面时等待时间较长。

**Comment by lightolly** [comment]
不应该啊，这块逻辑没有调整过来着
站点编辑过会要求重新刷新

**Comment by log-time** [comment]
不编辑站点，最新版目前每次进去都会重新刷新数据

**Comment by lightolly** [comment]
我这边目前没有这个现象 我找时间再看看

**Comment by log-time** [comment]
https://github.com/jxxghp/nas-tools/pull/432
