### ISSUE TITLE
集数定位-是否可以添加向后偏移的识别模式？

### ISSUE THREAD

**Issue by somethingwjy** [jxxghp/nas-tools#430]
**example-1** :此版JOJO的奇妙冒险S02分上下季放送
![image](https://user-images.githubusercontent.com/35595344/177131334-490dbd92-1314-4dc5-98d4-94eb7d7009df.png)
因压制者命名习惯不同，被命名为S02-part1和S02-part2   皆从01开始重新计数。

**S02-part1**
![image](https://user-images.githubusercontent.com/35595344/177131652-81c35a41-198f-4b37-a19e-c19f4db3a875.png)

**S02-part2**
![image](https://user-images.githubusercontent.com/35595344/177131545-92641c7b-e85b-47e4-88fd-37e2b2fb1a1a.png)

**example-2** :此版刃牙S01同样为上下季结构
![image](https://user-images.githubusercontent.com/35595344/177132284-4d02fa12-3c54-40e7-bfe6-9384317c3f6f.png)

FRDS组压制时，甚至将下半季命名为S02，同样重新开始计数
![image](https://user-images.githubusercontent.com/35595344/177133288-9dd4d414-4583-4f30-9b2d-dc2dfad5e8b4.png)

![image](https://user-images.githubusercontent.com/35595344/177132393-95ab16e7-4f87-449e-bf78-2e36069a5c3c.png)

以上情况时，手动批量改名需要对集数进行修正，非常麻烦。
现阶段的集数定位  应付多季合集场景时可做 "-"偏移处理，但无法进行正向偏移
![image](https://user-images.githubusercontent.com/35595344/177133090-2806e7f9-6758-4330-a2ce-99cf936392bc.png)

同时还尝试了使用变量识别集数位置，并定位（包括 25-48  以及对总集数使用-偏移）均失败，不知是否是我对用法理解错误

![image](https://user-images.githubusercontent.com/35595344/177137183-ad42c2c2-3e6f-433d-94ac-1eba1d2e6578.png)

不知大大可否给集数定位加上"+"偏移的参数？

若有正确技巧可解决此类命名，还望赐教！感谢！

**Comment by jxxghp** [comment]
@JohnZp

**Comment by JohnZp** [comment]
填正数就是正向偏移, 负数就是负向偏移

**Comment by somethingwjy** [comment]
> 填正数就是正向偏移(比如 3), 负数就是负向偏移(比如 -3)

感谢解答，特定情况下已能实现正向偏移，反馈bug如下：



**测试样例**：使用测试源文件名为  **灼眼的夏娜.S02E01**

![image](https://user-images.githubusercontent.com/35595344/177479027-9eb6400b-7950-40ea-849c-a68a6c32947c.png)

**手动识别填充信息如下**:（预期生成S02E06）

![image](https://user-images.githubusercontent.com/35595344/177479411-a3cab19c-805d-4467-8490-34b0a90d736a.png)

测试结果（**成功**）（生成S02E06）：

![image](https://user-images.githubusercontent.com/35595344/177479571-97951c38-b08f-44d4-9e88-0f3d48003c0a.png)

**若手动识别填充时，仅填写偏移量**：（不手动定位集数）（预期生成S02E08）

![image](https://user-images.githubusercontent.com/35595344/177479754-bf677ae6-de0a-48b0-8b09-1629902e4a79.png)

测试结果（**失败**）（生成S02E01） ：

![image](https://user-images.githubusercontent.com/35595344/177479806-88a4fb17-261b-40b7-96d7-ea2b25f9066b.png)

怀疑是集数偏移变量优先级过低导致未生效，望查证。

**Comment by JohnZp** [comment]
你如果填了偏移, 定位和集数圈定必须要填一个
比如中间填1, 偏移填7, 生成的就是第8集

**Comment by somethingwjy** [comment]
> 你如果填了偏移, 定位和集数圈定必须要填一个 比如中间填1, 偏移填7, 生成的就是第8集

谢谢大大  我明白了
