### ISSUE TITLE
transmission添加下载任务 返回添加失败 但是任务添加成功

### ISSUE THREAD

**Issue by iokaycn** [jxxghp/nas-tools#433]
具体报错信息
【MSG】发送wechat消息：title=添加下载任务失败：釜山行 (2016) , text=种子：Train to Busan 2016 1080p BluRay x264 DTS-WiKi韩粤双语 简繁中字
错误信息：Method "torrent-set" Argument "labels" does not exist in version 15.

 Transmission 版本：2.94 (d8e60ee44f), RPC: 15, WEB Control: 1.6.0(20190724

**Comment by log-time** [comment]
![QQ图片20220705160625](https://user-images.githubusercontent.com/66826612/177280891-4e489bc1-b819-4795-8e74-48c80cb98114.png)

**Comment by iokaycn** [comment]
3.0的版本 我也测过 也会报这个错
