### ISSUE TITLE
期望增加多版本支持, 尤其是3D版本电影

### ISSUE THREAD

**Issue by link2fun** [jxxghp/nas-tools#44]
示例
Jurassic.World.2015.1080p.Half-SBS.3D.BluRay.x264.DTS-WiKi.mkv
会被直接重命名为
侏罗纪世界 (2015) - 1080p.mkv

然而这个是3D版本的,如果我有4K版本的话,这个1080P版本的好像就会被覆盖掉

希望针对3D版本,不要被高清源覆盖掉

**Comment by jxxghp** [comment]
v0.4.15 将支持3D，今天晚些时候提交
