### ISSUE TITLE
回调地址请求不通过

### ISSUE THREAD

**Issue by KleinerSource** [jxxghp/nas-tools#445]
添加企业微信配置的时候 提示 openapi回调地址请求不通过
不管是 http 还是https  用域名还是用公网ip 都提示 这个
http://118.251.xxx.xxx:3000/wechat
https://118.251.xxx.xxx:4433/wechat
http://nas.xxxxx.cc:3000/wechat
https://nas.xxxxx.cc:4433/wechat
均无发成功配置
而且 本地访问 http://10.0.0.100:3000/wechat 会提示500 出错啦！系统出错了，请检查运行日志看看吧...
运行日志里没有错误

**Comment by WangEdward** [comment]
大佬最后是怎么解决的呀？

**Comment by zhangle83** [comment]
一样有这个问题，最后怎么解决的啊？
