### ISSUE TITLE
刷流任务报错

### ISSUE THREAD

**Issue by wangshunye12109** [jxxghp/nas-tools#457]
21:34:32 INFO - 【BRUSH】开始站点 HDDolby 的刷流任务：HD...
21:34:34 - syntax error: line 1, column 0
21:34:34 WARN - 【BRUSH】HDDolby RSS未下载到数据
21:39:32 INFO - 【BRUSH】开始站点 PTtime 的刷流任务：pttime-qb-volume2...
21:39:34 INFO - 【BRUSH】PTtime RSS获取数据：10
21:39:45 INFO - 【BRUSH】任务 pttime-qb-volume2 本次添加了 0 个下载
21:44:32 INFO - 【BRUSH】开始站点 HDDolby 的刷流任务：HD...
21:44:35 - syntax error: line 1, column 0
21:44:35 WARN - 【BRUSH】HDDolby RSS未下载到数据

一直提示syntax error: line 1, column 0

**Comment by jxxghp** [comment]
刷一下最新的代码

**Comment by wangshunye12109** [comment]
> 刷一下最新的代码

下午才更新的最新版

**Comment by jxxghp** [comment]
我没 HDDolby 测试不了。

**Comment by 26712681** [comment]
![image](https://user-images.githubusercontent.com/77581926/178128906-c614971d-f3e5-4fa2-9fd7-9af42901f81e.png)
杜比好像没有免费选择？

**Comment by wangshunye12109** [comment]
是的，没有，不只是杜比，pttime也同样错误



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月10日 10:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [jxxghp/nas-tools] 刷流任务报错 (Issue #457) |


杜比好像没有免费选择？

**Comment by 26712681** [comment]
别急，刷流刚开通，还有很多地方需要完善。 慢慢来
还有很多站点没有适配

**Comment by joezhn2020** [comment]
[https://www.awesomescreenshot.com/image/29986841?key=a2c825698be4e938964a2af45b67c3cb](url)
一直出错...

**Comment by 26712681** [comment]
你这是下载出错  自己检查配置  下载器  下载路径这些

**Comment by 26712681** [comment]
> [https://www.awesomescreenshot.com/image/29986841?key=a2c825698be4e938964a2af45b67c3cb](url) 一直出错...

你这是下载出错 自己检查配置 下载器 下载路径这些

**Comment by joezhn2020** [comment]
[https://www.awesomescreenshot.com/image/29986840?key=5cdcfb74767ecc97d05b5a31014f0d21](url)

> > [https://www.awesomescreenshot.com/image/29986841?key=a2c825698be4e938964a2af45b67c3cb](url) 一直出错...
> 
> 你这是下载出错 自己检查配置 下载器 下载路径这些
除了刷流之外所有下载都正常运行，刷流的下载器测试也成功的，
![2022-07-12](https://user-images.githubusercontent.com/61100767/178385232-b5fbaa80-9cdf-4ef3-88f7-604b6da5a8e6.png)
请问那里出问题

**Comment by jxxghp** [comment]
HDDolby如果还有问题提供RSS报文

**Comment by wangshunye12109** [comment]
感谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月10日 10:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [jxxghp/nas-tools] 刷流任务报错 (Issue #457) |

别急，刷流刚开通，还有很多地方需要完善。 慢慢来
还有很多站点没有适配

**Comment by AlleNPooh** [comment]
这个问题解决了吗？到现在我这里还是一直报这个错误。
