### ISSUE TITLE
刷流任务，上传统计有误

### ISSUE THREAD

**Issue by 26712681** [jxxghp/nas-tools#459]
感觉像是只统计了第一个下载器的上传数据。
![image](https://user-images.githubusercontent.com/77581926/178137347-bbffd3df-e407-4e75-b711-01fc55e23358.png)
![image](https://user-images.githubusercontent.com/77581926/178137352-826c7f03-d682-4a2b-8295-305f4f918273.png)
![image](https://user-images.githubusercontent.com/77581926/178137358-a56c349c-0b9e-429d-b10a-57e930c4d6fb.png)

**Comment by jxxghp** [comment]
fixed
