### ISSUE TITLE
希望加入多硬盘支持

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/nas-tools#46]
目前有多个硬盘

需要
/硬盘a/目录1 硬链接 /硬盘a/目录2
/硬盘b/目录3 硬链接 /硬盘b/目录4

在后头就可以管理。目录2和目录4。形成媒体库

**Comment by jxxghp** [comment]
v0.4.19 已支持

**Comment by appotry** [comment]
> v0.4.19 已支持

如何配置多硬盘支持？  文档里面似乎没看到
