### ISSUE TITLE
PT下载转移路径转换问题

### ISSUE THREAD

**Issue by BBshinya** [jxxghp/nas-tools#461]
下载器qbittorrent安装于winserver
nastools安装于docker desktop

设置路径映射     
qbittorrent  >>  nastools
E:\Video\Movie  >>  /library/Movie

当执行PT下载转移时： 
E:\Video\Movie\test\test.mkv  >>  /library/Movie\test\test.mkv   
转移失败

![Z01874)SY(A759~RPVZK}4A](https://user-images.githubusercontent.com/16237201/178184402-791e31de-da4e-4c9a-a243-a524023dd682.png)

如设置路径映射     
qbittorrent >> nastools
E:\Video\Movie\ >>  /library/Movie/

则当执行PT下载转移时： 
E:\Video\Movie\test\test.mkv  >>  /library/Movie/test\test.mkv    
依然转移失败

![R3)~XAKF~%RBGJ(L({F1TT8](https://user-images.githubusercontent.com/16237201/178184500-16a5824f-5b3b-42a4-9766-14b43edd90b8.png)

PS：把qbittorrent安装在docker就没问题了，但是校验和下载速度很受影响

另外，如果是下载好后进行的自动转移，就不会进行路径转换，还是用的下载器的下载路径导致转移失败。如果是手动在服务点击PT下载转移就会进行转换，成功转移

**Comment by jxxghp** [comment]
windows用\\或者/。再不行就放弃，不打算支持windows了。
