### ISSUE TITLE
月月站点适配问题

### ISSUE THREAD

**Issue by rockhia** [jxxghp/nas-tools#465]
keep friend朋友站点的标题为中文，副标题为英文。这个和大部分PT站点相反，导致使用搜索的时候无法匹配。
能否根据该站点的特点进行适配？
![Screenshot_20220711_224215_com yandex browser](https://user-images.githubusercontent.com/90016652/178291182-4c9e5ec2-cf9e-4341-b5b7-7701ab0a7013.jpg)
![Screenshot_20220711_224155_com yandex browser](https://user-images.githubusercontent.com/90016652/178291193-1ace7ef0-f21f-4c38-b3a7-78edcac701a5.jpg)

**Comment by rockhia** [comment]
RSS的信息也是反的，导致nas-tool无法兼容keep friend这个站点

**Comment by Mruser0** [comment]
换个站

**Comment by jxxghp** [comment]
应该修复了
