### ISSUE TITLE
企业微信添加的电影，总是报错下载任务添加失败，而transmission实际又在下载了！

### ISSUE THREAD

**Issue by 21tc-sea** [jxxghp/nas-tools#467]
例：我在微信端发送消息“电影 变形金刚”，它提示找到6条信息，让我输入序号，我输入2，然后开始检索，检索完以后报错“添加下载任务失败……”，提示“变形金刚共搜索到93个结果，但没有下载到任何资源”
然后我去nastools指定的下载器transmission中查看，实际已经添加了任务，也正常进入了下载……
然后我再去查看nastools的实时日志，总是能看到同样的报错信息，关键一行是（[]中的信息）：[Method "torrent-set" Argument "labels" does not exist in version 15.
11:24:18 INFO - 【SEARCHER】变形金刚 未下载到资源]
请问这个是什么原因导致的问题，怎么解决呢？
在nastools的“下载管理”中也查看不到下载任务，实际上transmission已经在下载了……

**Comment by jxxghp** [comment]
TR版本过低的问题
