### ISSUE TITLE
对资源进行手动识别，日志显示搜索字幕后为无反应

### ISSUE THREAD

**Issue by Davonng** [jxxghp/nas-tools#468]
LOG：
12:17:38 INFO - 【RMT】开始处理：/volume1/Videos/Sonic the Hedgehog 2.2022.1080p.WEB-DL.H264.AAC-EVO
12:17:38 INFO - 【RMT】文件 /volume1/Media/外语电影/刺猬索尼克2 (2022)/刺猬索尼克2 (2022) - 1080p.mkv 已存在，覆盖...
12:17:38 INFO - 【RMT】正在删除已存在的文件：刺猬索尼克2 (2022) - 1080p.mkv
12:17:38 INFO - 【RMT】正在转移文件：Sonic the Hedgehog 2.2022.1080p.WEB-DL.H264.AAC-EVO.mkv 到 刺猬索尼克2 (2022) - 1080p.mkv
12:17:38 INFO - 【RMT】文件 Sonic the Hedgehog 2.2022.1080p.WEB-DL.H264.AAC-EVO.mkv 硬链接完成
12:17:39 INFO - 【MSG】发送telegram消息：title=刺猬索尼克2 (2022) 转移完成, text=评分：7.7，类型：电影，类别：外语电影，质量：WEB-DL 1080p，大小：4.74G，来自：手动整理，1个文件已存在
12:17:40 INFO - 【NFO】正在生成电影NFO文件：刺猬索尼克2 (2022) - 1080p.mkv
12:17:41 INFO - 【RMT】/volume1/Videos/Sonic the Hedgehog 2.2022.1080p.WEB-DL.H264.AAC-EVO 处理完成，总数：1，失败：0
12:17:41 INFO - 【SUBTITLE】开始从Opensubtitle.org检索字幕: Sonic the Hedgehog 2

目录同步不存在此状况

**Comment by jxxghp** [comment]
opensubtitles连不上导致的吧

**Comment by Davonng** [comment]
> opensubtitles连不上导致的吧

通过目录同步自动刮削不存在此问题
