### ISSUE TITLE
多下载器刷流的问题

### ISSUE THREAD

**Issue by 26712681** [jxxghp/nas-tools#472]
除了下载器1，其他的触发保种体积停止后，就算时间到了，好像也不会在新增任务了。

这是下载器2
![image](https://user-images.githubusercontent.com/77581926/178496830-cb6cb340-f4af-4bed-b4a6-3216c9d7cdc1.png)
![image](https://user-images.githubusercontent.com/77581926/178496934-9bc481e4-1861-4ffb-b5e7-c65e413d45e6.png)

这是下载器3
![image](https://user-images.githubusercontent.com/77581926/178497034-5c4ae2e0-741b-48cc-b538-217ac3f2cfe4.png)
![image](https://user-images.githubusercontent.com/77581926/178497064-b8647e68-8ca2-4c49-8c9f-cb45a6946aa3.png)

**Comment by Mruser0** [comment]
我用的远程下载器，确实也有这个问题，删种后保种体积不会减去删除种子的体积，导致刷流任务无法再次新增下载任务
