### ISSUE TITLE
小小的建议

### ISSUE THREAD

**Issue by c939984606** [jxxghp/nas-tools#474]
- 消息通知能否增加 电子邮件 和 微信应用消息推送 https://developer.work.weixin.qq.com/document/path/90372
- 刷流下载器能否增加速度限制，qb和tr都是支持单个种子限速的
- 以上感谢

**Comment by jxxghp** [comment]
1.微信消息推送现在不就有吗？都有手机消息了谁还用邮件。
2.刷流都是新种，目的就是抢上传，为啥还要下载限速？

**Comment by c939984606** [comment]
> 1.微信消息推送现在不就有吗？都有手机消息了谁还用邮件。 2.刷流都是新种，目的就是抢上传，为啥还要下载限速？

1. 目前的微信通知还需要Token和AESKey，如果只需要简单的推送无需交互，只需要 corpid,corpsecret,touser,agentid 就可以
2. 刷流限速是因为，首先有的站点会有上传和下载速度限制，超了会被ban号，其次如果同时刷多个任务，很容易某一个任务占了所有带宽导致其他任务抢不上速度

**Comment by log-time** [comment]
1. 如果只需要简单的推送无需交互，Token和AESKey这部分是可以不填的。
2. 下载无所谓，上传部分站点确实有限速要求，大佬可以考虑下

**Comment by log-time** [comment]
![Screenshot_20220713_185157](https://user-images.githubusercontent.com/66826612/178717081-ce80caf9-812c-441f-8046-070e4be053c0.png)
这个是朋友的限速要求，大佬可以参考！@jxxghp
