### ISSUE TITLE
电视剧识别错误

### ISSUE THREAD

**Issue by Hotwill** [jxxghp/nas-tools#475]
像这样命名的电视剧识别错误：
少年包青天2第10集
白色强人2第10集

国内的电视剧没有季的概念，对于第二部、第三部一般都是像上面这样命名的，这种格式识别不出来，希望能够兼容

**Comment by jxxghp** [comment]
正经的资源命名都能识别，包括没季的国内电视剧。
而且你发的这个名字也能识别啊，但是tmdb都没叫xxx2的怎么去兼容？

**Comment by Hotwill** [comment]
这种需要识别成第二季

**Comment by Hotwill** [comment]
这种需要识别成第二季 @jxxghp
