### ISSUE TITLE
企业微信可以搜索到资源，点击结果没任何反应

### ISSUE THREAD

**Issue by haohao232323** [jxxghp/nas-tools#476]
![Snipaste_2022-07-13_15-41-39](https://user-images.githubusercontent.com/42701714/178678915-0dbc6793-bd1a-4b4d-8e90-80811fb38052.png)
![Snipaste_2022-07-13_15-41-51](https://user-images.githubusercontent.com/42701714/178678930-7cd3a5c1-e324-4d48-bad2-d59a1a5b144e.png)
![Snipaste_2022-07-13_15-42-15](https://user-images.githubusercontent.com/42701714/178678940-e724dcb3-aabc-46a1-8c76-0ec8ea31fa9b.png)

**Comment by log-time** [comment]
![M1}3I6})%GAN%SYTW5P5MFW](https://user-images.githubusercontent.com/66826612/178686734-e85be646-358a-4910-bb29-58a3bd1f7705.png)
这个地方需要设置一下才能实现搜索页面跳转，或者开启远程搜索自动择优下载
