### ISSUE TITLE
企业微信接收信息API保存报openapi回调地址请求不通过

### ISSUE THREAD

**Issue by zhangle83** [jxxghp/nas-tools#477]
使用dsm7的套件版本1.9.7，nastools可发来测试短信到企业微信，但是企业微信在保存API接收消息的配置时候报openapi回调地址请求不通过，导致无法保存；且通过企业微信发送消息到nastools无法收到，日志中看不到任何记录

**Comment by zhangle83** [comment]
且测试nastools中pt站签到手动执行，企业微信可以收到回复的消息；但是企业微信一直无法正常发给nastools,不管开不开微信代理

**Comment by jxxghp** [comment]
环境问题需要自己解决。
