### ISSUE TITLE
建议 支持 在配置界面 动态修改 日志等级

### ISSUE THREAD

**Issue by link2fun** [jxxghp/nas-tools#478]
刷流已经两三天没有加入新种子了, 不知道啥原因, 看源码有些日志只在 debug 模式下输出
----------
所以 希望能支持动态修改日志等级, 好能知道具体原因
-----------
另, 现在的单元测试在哪呢, 我想自己调调来着, 没找到单元测试的代码

**Comment by jxxghp** [comment]
配置文件支持改
