### ISSUE TITLE
微信回调问题请教，谢谢！

### ISSUE THREAD

**Issue by 21tc-sea** [jxxghp/nas-tools#480]
想利用自己谷歌云有固定IP的VPS来实现微信回调，折腾了好久，都不成功，大佬能否指点一下！
nastools所在局域网也有公网IP，但是动态的，做了DDNS，访问地址（例）：http://aaa.com:9800
VPS做了DDNS，域名（例）：bbb.com
已做了以下方案的尝试：
A、在VPS主机上安装nginx proxy manager，反代http://nt.bbb.com到http://aaa.com:9800。然后企业微信的“接收消息服务器配置”中的URL设置为：http://nt.bbb.com，添加VPS的IP到可信IP，返回nastools的WEBUI界面中“消息通知”－“微信”中点“测试”，连接失败。
B、在VPS中搭FRPS，在nastools所在网络旁路由上开启frpc，在frpc中配置9800转发到nastools主机192.168.1.99的3000端口。搭建成功，可通过http://bbb.com:9800访问nastools，然后把http://bbb.com:9800/wechat添加到企业微信API设置中的URL中，添加VPS的IP为可信IP，测试连接失败；
C、在方案B的基础上，在VPS的nginx proxy manager反代https://nt.bbb.com到http://bbb.com:9800，可以通过https://nt.bbb.com正常访问nastools，然后把https://nt.bbb.com添加到企业微信的API的URL中，添加VPS的IP为可信IP，测试连接失败；

以上三个方案都失败了，必须要把nastools所在网络当时的动态公网IP添加进去，才有可能成功，问题是动态公网IP不是固定的啊。
请教大佬，如果用自己的VPS来实现微信回调，我应该在上述三个方案中的哪一个的基础上去调整实现？能否具体说一说，谢谢！

**Comment by jxxghp** [comment]
1.你是要解决回调的问题还是要解决消息通知的问题？你在
2.nastool里面点测试测试的是消息通知，消息通知才需要有固定的IP，这个项目已经提供了免费的代理服务器，如果你有自己的服务器，你也可以劫持nastool.jxxghp.cn这个域名，解析到你自己的服务器IP就行（通过adguard或者openwrt都行）。
2.回调跟IP白名单是没关系的，只要通过域名能访问到你的内网，并且你的密钥都配对了就行。注意/wechat这个路径不要丢了。

**Comment by 21tc-sea** [comment]
哦，那就是回调吧，要用自己的VPS的固定IP去实现这个，操作是怎么样能不能大体说说？如果太麻烦就算了，我知道新版本已经提供了免费的微信转发服务器，只是我寻了半天的，大家说的方法，我感觉都尝试了，就搞不通，很纳闷，想搞明白到底哪个环节出了问题……
