### ISSUE TITLE
刮削时能否加入更多信息

### ISSUE THREAD

**Issue by HySand** [jxxghp/nas-tools#482]
用NASTool刮削的演员信息是这样的

> <actor>
    <name>Hailee Steinfeld</name>
    <type>Actor</type>
    <thumb>/config/metadata/People/H/Hailee Steinfeld/folder.jpg</thumb>
  </actor>

不清楚是否被Jellyfin重新刮削过，因为大多数连图片都没有显示。
而同样的文件用TMM刮削后演员部分是这样的

> <actor>
    <name>Hailee Steinfeld</name>
    <role>Vi (voice)</role>
    <thumb>https://image.tmdb.org/t/p/h632/q4UpZMEuvNCN5lL5L6xa3ICpheJ.jpg</thumb>
    <profile>https://www.themoviedb.org/person/130640</profile>
    <tmdbid>130640</tmdbid>
  </actor>

这样大概会更好看点

同样的还有评分、评级等更多信息

**Comment by jxxghp** [comment]
示例1不是nastool削的
