### ISSUE TITLE
docker设置时区无效

### ISSUE THREAD

**Issue by JKnuts** [jxxghp/nas-tools#484]
docker设置好时区之后，nastool开始页面读取jellyfin的登录时间还是中国时间

docker设置的北美时区：
![image](https://user-images.githubusercontent.com/91355283/178814032-cf308c34-8b89-448a-8429-8aac6423ab11.png)

jellyfin的时间是正确的：7月13日下午
![image](https://user-images.githubusercontent.com/91355283/178814655-3a738bd6-45c3-46a9-a867-4343d5c3812c.png)

nastool读取的仍然是北京时间：7月14日凌晨
![image](https://user-images.githubusercontent.com/91355283/178814837-b6e55e5e-a5e6-4a48-860c-8d54c721720c.png)

不知道是不是要清除一下缓存？

**Comment by baozaodetudou** [comment]
这个设置本身就不是很靠谱的，建议映射/etc/localtime

**Comment by JKnuts** [comment]
> 

看来是的，我在容器环境映射了/etc/localtime:ro，nastool里还是中国时间

**Comment by ncncncnc** [comment]
> 容器里面运行date，时间是正确的，所以不是TZ的问题，但貌似Asia/Shanghai写死在Python代码里了，希望可以通过config配置
> 
> https://github.com/jxxghp/nas-tools/search?q=shanghai

@jxxghp 求大神能支持界面上其他时区的时间显示，不要写死Asia/Shanghai
