### ISSUE TITLE
RSS订阅搜索问题

### ISSUE THREAD

**Issue by Rabbit714205** [jxxghp/nas-tools#485]
大佬，为什么有些番剧RSS订阅自动搜索没有检索到资源？在资源搜索中也是同样的情况，但是快速搜索却可以正常检索到资源，是我哪里设置出问题了吗？
![QQ截图20220714021328](https://user-images.githubusercontent.com/109240774/178830015-e4b371c0-9073-4b41-bb5e-eb4487a73933.png)

![QQ截图20220714043615](https://user-images.githubusercontent.com/109240774/178830043-aaa29f75-4daf-4b71-a7b3-f2905fae5cda.png)

**Comment by jxxghp** [comment]
订阅目前是优先用英文检索，也是别人建议的。

**Comment by Rabbit714205** [comment]
好的，可以理解

**Comment by firstwillzhang** [comment]
建议允许完全自定义订阅搜索关键字，这样就回避了番剧识别的问题，让用户可以自己去调整识别不到的番剧

**Comment by Rabbit714205** [comment]
感谢建议
