### ISSUE TITLE
勾选”只管理NASTOOLS添加的下载“后，非nastools添加的下载还是会进行识别同步

### ISSUE THREAD

**Issue by tsymr** [jxxghp/nas-tools#487]
![QQ20220714-162543](https://user-images.githubusercontent.com/11868091/178937532-de49500b-6d60-4294-90b8-0efc063ae5ed.png)
![QQ20220714-162537](https://user-images.githubusercontent.com/11868091/178937541-5ce29270-6745-4d87-a910-4bb3b5f8e6a3.png)
![QQ20220714-162529](https://user-images.githubusercontent.com/11868091/178937546-3ee5d8cc-d99e-4b47-8982-0150c51648e3.png)

此下载非nastools添加 但还是进行了识别并在媒体目录创建了空文件夹

**Comment by log-time** [comment]
![Screenshot_20220714_193442](https://user-images.githubusercontent.com/66826612/178973511-36743362-276e-4d07-821d-1c58534c2f1c.png)
这个地方有没有关闭？

**Comment by jxxghp** [comment]
看下QB里种子的标筌，是否有加上nastool。另外有些时候改了开关要重启。
