### ISSUE TITLE
WEB搜索下载动漫放错目录的问题。

### ISSUE THREAD

**Issue by smily1223** [jxxghp/nas-tools#49]
![image](https://user-images.githubusercontent.com/37728519/163337809-04284ef3-3323-438a-b036-a908d0ca45b7.png)
WEB下载动漫，发送到微信的消息显示的是电视剧。而且QB下载的目录是电视剧的目录。并不是配置的动漫的目录。

**Comment by jxxghp** [comment]
v0.4.19 已修复
