### ISSUE TITLE
PT站签到支持随机时间

### ISSUE THREAD

**Issue by JimmyBaize** [jxxghp/nas-tools#493]
有2个疑问：
1、PT站签到支持随机时间，这样更像是人手工签到。该功能是否可以合入？
     会不会有的PT站识别到每天固定时间自动签到，认定为作弊？
2、如果想贡献该功能的MR，流程是怎样的？

**Comment by jxxghp** [comment]
Pr己开放，欢迎提交

**Comment by JimmyBaize** [comment]
方案如下：
在当前配置项ptsignin_cron上扩展
`ptsignin_cron: 08:01-09:00`
表示在08:01到09:00之间随机选一个分钟执行；秒数不需要支持配置，在0-59随机选一个即可

实现方式为：
判断是否有`-` 有的话为时间范围随机格式，在起始时间启动一个data类型的Scheduler Job，在范围内随机选一个时间执行

**Comment by jxxghp** [comment]
已合并，谢谢！
