### ISSUE TITLE
搜索结果不匹配类型

### ISSUE THREAD

**Issue by woshijie120** [jxxghp/nas-tools#498]
目前使用Jackett进行搜索，新增站点GPW，可以在日志中看到搜索到结果，但是因为类型不匹配不进行显示，请问下是哪里的问题？
nastool日志显示：
![image](https://user-images.githubusercontent.com/108522192/179140319-64f4ab6c-5242-49b1-ade4-55a8a8205a13.png)
直接用Jackett搜索显示：
![111](https://user-images.githubusercontent.com/108522192/179141031-d51b5f51-13a3-447f-b960-0b09c0c1ad08.png)

**Comment by jxxghp** [comment]
命名极不规范导致
