### ISSUE TITLE
群晖版本无法安装

### ISSUE THREAD

**Issue by 2284787774** [jxxghp/nas-tools#5]
提示先安装3.8.6-0154版本的python3，我已经安装了3.8.12-6的python了

**Comment by jxxghp** [comment]
发现写死了python套件版本号，我先临时去掉了，你下最新编译的试试。
可能还会不行，套件只在我自己环境下试过，不行先用docker的吧，docker改好了试过了。

**Comment by jxxghp** [comment]
这个问题搞定了，spk安装脚本及权限的问题。
需要手工安装python3.8版本套件。
