### ISSUE TITLE
【必看】提问题前请先看这里

### ISSUE THREAD

**Issue by jxxghp** [jxxghp/nas-tools#505]
1. 问题请详细说明，附上截图和日志，描述不清且无法重现的将关闭。
2. 非极大共性或对项目发展有益的功能需求就不要提了，特别是三两句话的需求。个人精力有限干不过来。有能力实现的欢迎PR。
3. 站点适配、命名不规范导致的识别订阅系列问题，贴上名称和日志在汇总页提交，不要单独建。
4. 环境配置问题自己想办法解决，多看WIKI常见问题跟别人写的教程。

**Comment by daji2010** [comment]
在2.0之前的版本中建立的“”未开启“”的“目录同步”，在2.01版本中无法删除及修改。
![nastool](https://user-images.githubusercontent.com/99402006/185917393-9c27995a-3c5c-4dd4-9140-95c6a1e87b6f.PNG)
