### ISSUE TITLE
希望有大佬可以出一个windows docker的安装配置教程

### ISSUE THREAD

**Issue by 522654518** [jxxghp/nas-tools#506]
1.我配置 qitorrent plex jackett 微信 全部提示测试失败 我把日志等级调到info级别，但是没有出现为什么失败的日志   
2.windocker 的目录有点搞不懂  不会配置媒体库等功能

**Comment by log-time** [comment]
https://github.com/jxxghp/nas-tools/issues/461

**Comment by 522654518** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 522654518** [comment]
我的 jackett plex qitorrent 都是安装的window的exe版本 但是nastools装的docker版本 
可能这个是连接不上的原因嘛
docker玩的不好 没有人用windows玩nas嘛

**Comment by 522654518** [comment]
貌似链接不上是因为windows 防火墙的问题   win做服务器还是恼火  希望作者继续支持windows 感谢作者

**Comment by 522654518** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
