### ISSUE TITLE
配置好企业微信之后，一直测试失败

### ISSUE THREAD

**Issue by ziyefeixing** [jxxghp/nas-tools#507]
配置好企业微信之后，测试一直失败。确定参数都配置的没问题，请问这种一般是什么原因引起的呢？
![test](https://user-images.githubusercontent.com/6337146/179324015-f186fe3e-65e5-42e8-8287-9d681cbfc92f.png)

**Comment by log-time** [comment]
https://github.com/jxxghp/nas-tools/wiki/%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B
