### ISSUE TITLE
nastools的搜索功能似乎有问题

### ISSUE THREAD

**Issue by sungamma** [jxxghp/nas-tools#508]
![image](https://user-images.githubusercontent.com/33790/179326751-e6d8e842-b344-46c2-97b4-4dc815784f6d.png)
上面的是jackett的搜索结果

![image](https://user-images.githubusercontent.com/33790/179326801-3c9c8c26-d83c-4f9c-b9e3-13e6b7a61280.png)
上面是直接搜索的结果，下面是对应的日志
```
08:21:46 INFO - 【WEB】开始检索 侏罗纪世界3 ...
08:21:46 INFO - 【JACKETT】开始并行检索 Jurassic World Dominion，线程数：3 ...
08:21:46 INFO - 【JACKETT】开始检索Indexer：hdatmos ...
08:21:46 INFO - 【JACKETT】开始检索Indexer：hdchina ...
08:21:46 INFO - 【JACKETT】开始检索Indexer：mteamtp ...
08:21:46 WARN - 【JACKETT】hdatmos 未检索到资源
08:21:46 WARN - 【JACKETT】hdchina 返回数据：3
08:21:46 WARN - 【JACKETT】mteamtp 未检索到资源
08:21:46 INFO - 【JACKETT】Jurassic World Dominion 2022 2160p WEB-DL DDP5 1 Atmos HEVC-CMRG 13.13G 不符合默认过滤规则
08:21:47 INFO - 【META】Jurassic World Dominion 识别到 电影：TMDBID=507086, 名称=侏罗纪世界3, 上映日期=2022-06-01
08:21:47 INFO - 【JACKETT】Jurassic World Dominion 2022 1080p AMZN WEB-DL DDP 5 1 H 264-CMRG 未识别到媒体信息
08:21:47 INFO - 【JACKETT】Jurassic World Dominion 2022 2160p AMZN WEB-DL DDP5 1 HDR HEVC-CMRG 15.83G 不符合默认过滤规则
08:21:47 INFO - 【JACKETT】hdchina 共检索到 0 条有效资源
08:21:47 INFO - 【JACKETT】所有API检索完成，有效资源数：0
08:21:47 INFO - 【WEB】侏罗纪世界3 未检索到任何资源
```
![image](https://user-images.githubusercontent.com/33790/179326860-9a50934c-cdff-4194-940a-eab413ac3dc7.png)
上面这张图是高级搜索的结果
```
08:23:50 INFO - 【WEB】开始检索 侏罗纪世界3 ...
08:23:50 INFO - 【JACKETT】开始并行检索 侏罗纪世界3，线程数：3 ...
08:23:50 INFO - 【JACKETT】开始检索Indexer：hdatmos ...
08:23:50 INFO - 【JACKETT】开始检索Indexer：hdchina ...
08:23:50 INFO - 【JACKETT】开始检索Indexer：mteamtp ...
08:23:50 WARN - 【JACKETT】hdatmos 未检索到资源
08:23:50 WARN - 【JACKETT】hdchina 返回数据：3
08:23:50 INFO - 【JACKETT】Jurassic World Dominion 2022 2160p WEB-DL DDP5 1 Atmos HEVC-CMRG 匹配成功
08:23:50 WARN - 【JACKETT】mteamtp 未检索到资源
08:23:50 INFO - 【JACKETT】Jurassic World Dominion 2022 1080p AMZN WEB-DL DDP 5 1 H 264-CMRG 匹配成功
08:23:50 INFO - 【JACKETT】Jurassic World Dominion 2022 2160p AMZN WEB-DL DDP5 1 HDR HEVC-CMRG 匹配成功
08:23:50 INFO - 【JACKETT】hdchina 共检索到 3 条有效资源
08:23:50 INFO - 【JACKETT】所有API检索完成，有效资源数：3
08:23:50 INFO - 【WEB】共检索到 3 个有效资源
```
现在的问题是：
1. 调用jackett搜索的结果只能搜索到hdc的，其他两个搜索不到
2. 这个默认过滤规则到底怎么用，怎么设置，为何高级搜索里面又不用了

**Comment by log-time** [comment]
> 默认过滤规则建议可以先尝试使用内置的规则-日常观影，可以自动过滤、下载720p以上规范命名的资源。默认的顺序是特效字幕>中文字幕>无字幕的，资源质量优先顺序是1080p>4k>高清的。以后熟悉规则配置后，可以再根据需要调整规则适应自己的需求。
> 站点无法搜索的问题，可以先到jackett内确认下索引器的状态是否正常。

**Comment by sungamma** [comment]
我自己在日常观影增加了一条规则2160P，也进行了验证，如下图
![image](https://user-images.githubusercontent.com/33790/179328663-9d3cbf9e-6d4b-46f4-ac2f-72481ec6b25e.png)
但最终的结果是直接搜索后，还是搜索不到
![image](https://user-images.githubusercontent.com/33790/179328681-11040819-8afe-4560-aa8a-73bd01c11845.png)

**Comment by log-time** [comment]
这个种子的名称，使用名称识别测试工具测试下，可以正常识别吗？

**Comment by sungamma** [comment]
我上条回复里面就有测试识别的图片

**Comment by log-time** [comment]
> 我上条回复里面就有测试识别的图片

![Screenshot_20220716_105735](https://user-images.githubusercontent.com/66826612/179336645-e386e181-1293-414e-aaa9-ea963add5ae5.png)

**Comment by log-time** [comment]
似乎识别没问题，你看看是不是规则里的编码信息把这个种子给排除了，我看了下种子命名里似乎没有重编码的信息（[Hx]26[45])

**Comment by jxxghp** [comment]
没问题啊，可以正常识别啊。

**Comment by sungamma** [comment]
奇了怪了，回头重新拉镜像，删掉原先配置，重新配置看看。

**Comment by sungamma** [comment]
找出问题的原因了，因为在外网添加的站点，复制到nas-tools里面，改了feed的地址为127.0.0.1，但是https里面的s没有去掉。
