### ISSUE TITLE
希望适配下手机主屏幕界面

### ISSUE THREAD

**Issue by So-Yp** [jxxghp/nas-tools#512]
![0CDA0758C54EC4A95ABCE3EA6FD898C7](https://user-images.githubusercontent.com/28726827/179346325-974cc78d-74a5-4375-a1cb-2b9fa103cf35.png)
希望大佬对iPhone添加主屏幕UI进行修复
![QQ截图20220716152940](https://user-images.githubusercontent.com/28726827/179346338-4e33635c-d6a6-40c8-baad-4b0f33ee185c.png)
麻烦大佬这里订阅某个电影或者剧的时候，分辨率和编码，再详细点，这里只有4k，有的电影标题是2160P，匹配不到特定资源，谢谢

**Comment by jxxghp** [comment]
过滤规则了解一下。
