### ISSUE TITLE
使用Prowlarr检索到的部分资源无法成功添加下载

### ISSUE THREAD

**Issue by poseidon2750** [jxxghp/nas-tools#513]
出错的站点是BTSOW
经多次测试只要是这个网站的资源就会出错
如果直接从Prowlarr搜索下载可以添加成功
另外其他同样接入Prowlarr的站点在nastool能正常添加下载
这个站比较多中文电影资源，如果可以下载会非常完美~恳请大佬出手帮忙解决

日志如下:
16:18:32 INFO - 【PROWLARR】所有API检索完成，有效资源数：7
16:18:32 INFO - 【DOWNLOADER】添加PT任务：阳光灿烂的日子.1994.未删减修复版.1080P.WEB-DL.X264.AAC.国语中字-LxyLab.mkv ...
16:18:33 INFO - 【DOWNLOADER】添加PT任务：http://192.168.1.246:9696/6/download?apikey=1864bf88fa0b49a685ccd774cf9cb625&link=TjVEeTNnQ2hGdE85ekxFWXlXQVkyRHFCMDZoenY3VHlTOGNEYjl3bFQ0R2NOQWVvc2REMjc3aTJhNnovdHZGMHFsak51RzQyQzFiQkorTy9GdlJvQVZlL3ZJUjRjdFByTUpxRXBvOWJVOWY3V25zQ1VxbHhwcDF4RTBqeGhJeXQ&file=%E9%98%B3%E5%85%89%E7%81%BF%E7%83%82%E7%9A%84%E6%97%A5%E5%AD%90.1994.%E6%9C%AA%E5%88%A0%E5%87%8F%E4%BF%AE%E5%A4%8D%E7%89%88.1080P.WEB-DL.X264.AAC.%E5%9B%BD%E8%AF%AD%E4%B8%AD%E5%AD%97-LxyLab.mkv
16:18:35 ERROR - 【DOWNLOADER】添加下载任务出错：Query failed with result "invalid or corrupt torrent file".
16:18:35 ERROR - 【DOWNLOADER】添加下载任务失败：阳光灿烂的日子 (1994)
16:18:35 INFO - 【MSG】发送wechat消息：title=添加下载任务失败：阳光灿烂的日子 (1994) , text=种子：阳光灿烂的日子.1994.未删减修复版.1080P.WEB-DL.X264.AAC.国语中字-LxyLab.mkv 错误信息：Query failed with result "invalid or corrupt torrent file".
16:18:37 INFO - 【SEARCHER】阳光灿烂的日子 未下载到资源

**Comment by jxxghp** [comment]
非程序问题

**Comment by sungamma** [comment]
建议用jackett，prowlarr应该还有个副标题识别的问题，导致电视剧的集数识别不到

**Comment by poseidon2750** [comment]
> 建议用jackett，prowlarr应该还有个副标题识别的问题，导致电视剧的集数识别不到

好的，感谢建议
