### ISSUE TITLE
Connection to api.themoviedb.org timed out. (connect timeout=None)

### ISSUE THREAD

**Issue by nehzx** [jxxghp/nas-tools#515]
02:58:12 INFO - 【META】名侦探柯南：万圣节的新娘 以年份 2022 在TMDB中未找到电影信息!
02:59:22 ERROR - 【META】连接TMDB出错：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/search/movie?api_key=e4be41b89431071e978b2ff486c6adc5&query=%E5%90%8D%E4%BE%A6%E6%8E%A2%E6%9F%AF%E5%8D%97%EF%BC%9A%E4%B8%87%E5%9C%A3%E8%8A%82%E7%9A%84%E6%96%B0%E5%A8%98&year=2022&language=zh-CN (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fde8920cd60>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))
02:59:22 INFO - 【META】名侦探柯南：万圣节的新娘 以年份 2022 在TMDB中未找到电影信息!
03:00:19 ERROR - 【META】连接TMDB出错：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/search/tv?api_key=e4be41b89431071e978b2ff486c6adc5&query=%E5%90%8D%E4%BE%A6%E6%8E%A2%E6%9F%AF%E5%8D%97%EF%BC%9A%E4%B8%87%E5%9C%A3%E8%8A%82%E7%9A%84%E6%96%B0%E5%A8%98&first_air_date_year=2022&language=zh-CN (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fde8920c130>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))
03:00:19 INFO - 【META】名侦探柯南：万圣节的新娘 以年份 2022 在TMDB中未找到电视剧信息!
03:00:43 ERROR - 【META】连接TMDB出错：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/search/movie?api_key=e4be41b89431071e978b2ff486c6adc5&query=%E9%98%BF%E7%94%98%E6%AD%A3%E4%BC%A0&year=1994&language=zh-CN (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fde892772b0>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))

**Comment by jxxghp** [comment]
错误原因写的彼清楚了
