### ISSUE TITLE
能否添加Jellyfin和Prowlarr的支持

### ISSUE THREAD

**Issue by sungamma** [jxxghp/nas-tools#52]
非常感谢作者，试用了下，感觉能解决很多痛点。另外能否添加Jellyfin和Prowlarr的支持
1. Jellfyfin现在很好用，而且很方便硬解码（docker镜像nyanmisaka/jellyfin)
2. Prowlarr添加indexer应该比jacket简单吧，而且也是arr系列的，使用起来更方便

**Comment by jxxghp** [comment]
Prowlarr 没有api

**Comment by sungamma** [comment]
Prowlarr 里面的 Settings-General 下面的API没有用吗？

**Comment by baozaodetudou** [comment]
https://prowlarr.com/docs/api/

**Comment by sungamma** [comment]
大佬，你这个效率太高了。刚说jellyfin暂不考虑，结果当天就加上了支持
