### ISSUE TITLE
关于电视剧中文命名识别问题

### ISSUE THREAD

**Issue by Ice-Cream-MY** [jxxghp/nas-tools#520]
下载的电视剧剧集为中文名称且带有标题时无法正常识别
由于不是动漫问题未加入汇总，如需要加入汇总劳烦关闭我在汇总中添加
![image](https://user-images.githubusercontent.com/76402568/179410660-9ace6630-5be6-4b7f-978e-aedf984becc1.png)
![image](https://user-images.githubusercontent.com/76402568/179410722-6ea35381-fe74-4cea-b3f1-cb8b2eae31f1.png)

**Comment by Ice-Cream-MY** [comment]
> 下载的电视剧剧集为中文名称且带有标题时无法正常识别 由于不是动漫问题未加入汇总，如需要加入汇总劳烦关闭我在汇总中添加 ![image](https://user-images.githubusercontent.com/76402568/179410660-9ace6630-5be6-4b7f-978e-aedf984becc1.png) ![image](https://user-images.githubusercontent.com/76402568/179410722-6ea35381-fe74-4cea-b3f1-cb8b2eae31f1.png)

在试图使用自定义集数位置时，发现自定义无法添加标题相关的变量导致其无法确认后续剧集文件，可能有变量但是我并未使用？求教

**Comment by log-time** [comment]
集数部分用{ep}，其他命名中不同的部分可以用{a}。那个?说的很清楚

**Comment by Ice-Cream-MY** [comment]
> 集数部分用{ep}，其他命名中不同的部分可以用{a}。那个?说的很清楚

重新识别这里没有显示，？只显示了ep相关的，谢谢解答，这个中文的识别希望有机会能修复一下

**Comment by log-time** [comment]
![无标题](https://user-images.githubusercontent.com/66826612/179436103-3b33b075-ca25-4088-8931-2b2536c61278.png)

**Comment by jxxghp** [comment]
D.P. 这个东西太奇怪了，而且你的文件名还是繁体，集数命名也不规范，没办法兼容识别。
