### ISSUE TITLE
能否出一个电影和电视剧分别用不同规则匹配的功

### ISSUE THREAD

**Issue by 522654518** [jxxghp/nas-tools#521]
电影下载的4k 电视剧下载1080p
就像overseerr那样

**Comment by log-time** [comment]
指的是电影和电视可以分别设置一个默认规则吗？

**Comment by 522654518** [comment]
> 

是的 电影和电视的规则一般都不同
参考 sonarr和radarr

**Comment by 522654518** [comment]
> 指的是电影和电视可以分别设置一个默认规则吗？

电视剧一般1080p因为4k的太大 
电影就可以全都4k

**Comment by 522654518** [comment]
> 指的是电影和电视可以分别设置一个默认规则吗？

这几天体验了一下 sonarr radarr overseerr这一套流程  
他们会列出每一个indexer对规则的匹配程度 为什么匹配不上也会显示出来 
感觉可以把这些成熟的功能参考一下

**Comment by jxxghp** [comment]
> > 指的是电影和电视可以分别设置一个默认规则吗？
> 
> 
> 
> 这几天体验了一下 sonarr radarr overseerr这一套流程  
> 
> 他们会列出每一个indexer对规则的匹配程度 为什么匹配不上也会显示出来 
> 
> 感觉可以把这些成熟的功能参考一下 

其实直接用arr系就好了，实在是没精力把别人的优点都吸收过来。
