### ISSUE TITLE
plex 一直报错无法连接上

### ISSUE THREAD

**Issue by 522654518** [jxxghp/nas-tools#522]
![Screenshot_20220718_041158_com microsoft rdc androidx](https://user-images.githubusercontent.com/44149189/179423248-8cc6e614-3169-4cc6-8cc2-d432d05d595a.jpg)
windows环境

**Comment by jxxghp** [comment]
环境问题

**Comment by 522654518** [comment]
> 



> 环境问题

是windows不行 还是因为没有vpn之类的
