### ISSUE TITLE
关于索引器测试的bug

### ISSUE THREAD

**Issue by sungamma** [jxxghp/nas-tools#527]
```
http://127.0.0.1:9117/api/v2.0/indexers/hdatmos/results/torznab/
https://127.0.0.1:9117/api/v2.0/indexers/hdchina/results/torznab/
http://127.0.0.1:9117/api/v2.0/indexers/mteamtp2fa/results/torznab/
```
比如这样的，前面两个能够连接，第2个地址错误，但3个jackett连不上mteam，但是测试依然是成功的。
![image](https://user-images.githubusercontent.com/33790/179471842-a5afbfbd-aed2-40d4-8032-66f23835e14f.png)
![image](https://user-images.githubusercontent.com/33790/179471543-99f20cc3-4f81-4914-b99b-b93aef9147e6.png)
这两种情况测试也成功。
除非像这样的错误才会不成功
![image](https://user-images.githubusercontent.com/33790/179471693-d6328f91-3093-4158-97f8-ebcbf1a3b005.png)

**Comment by jxxghp** [comment]
现在是只测试第一个，全部测试时间很长。
