### ISSUE TITLE
关于刷流功能的建议

### ISSUE THREAD

**Issue by Mruser0** [jxxghp/nas-tools#528]
![mmexport1658134901981](https://user-images.githubusercontent.com/107661622/179478709-9d1b13df-3b8e-433d-b312-9066c6182980.png)
先给老大点个赞，刷流功能很好用。目前用本地下载器和远程下载器都可以正常删种。
目前如果设置保种体积，现在下载量会持续增加，触发保种体积上限后不会再新增下载任务。即使种子已经自动删完也不会新增下载。这样每次需要手动重新设置刷流任务，没有自动循环刷流。

建议保留现在的下载量对象A，作为判断刷流产生的总下载流量，新增一个刷流存量种子体积对象B,每次自动删种后抓取更新刷流存量种子体积B的值，B值作为和做种体积条件做判断的值，这样每次自动删种腾出硬盘空间后可以继续新增下载任务。

A的值可以作为新增下载流量启停刷流任务的开关

**Comment by jxxghp** [comment]
这个问题应该解决了的呀，下载量会增加，但是不是以这个值来判断的。

**Comment by Mruser0** [comment]
> 不

那就奇怪了，我是1.9.9版本，是删除刷流任务后更新到1.9.9再重建的刷流任务，现在还是没有循环起来，等晚上我删镜像和配置后重新试试看吧，谢谢老大

**Comment by Mruser0** [comment]
> 这个问题应该解决了的呀，下载量会增加，但是不是以这个值来判断的。
![44`2(T%7C)NN773IZ{C3M0C](https://user-images.githubusercontent.com/107661622/179669424-84940720-3db1-4f2c-92d8-faf57d7517f7.png)
![~UNHBYF%A2TZAU4E}3TKBZE](https://user-images.githubusercontent.com/107661622/179669460-ebaaf0f9-717a-4285-a185-736c671fc03e.png)
![G$T4(}(}D C $}YP_~_BR$N](https://user-images.githubusercontent.com/107661622/179669501-596cd3c0-5889-4db0-b2cf-54a3808bfc20.png)
我又删除镜像删容器删config文件夹后重新拉的1.9.10的最新镜像，重新配置后还是存在这个刷流无法循环的问题，这个下载器是本地下载器qb4.3.9，自动删种也正常，下载文件夹里的刷流文件也确实自动删了，但就是一直显示刷流达到保种体积，不再新增下载任务

**Comment by jxxghp** [comment]
确实还有问题，更新代码可以再试试看

**Comment by Mruser0** [comment]
> 

更新代码后重建刷流任务测试了下还是不行，跟上面描述的问题一样

**Comment by Mruser0** [comment]
![G1WCY2QR9% DEVRT 8ZS_BX](https://user-images.githubusercontent.com/107661622/179737486-a2ae998c-10ec-4e13-8dcc-561c0db181ce.png)
![PMXO0U9HE )J 0T(H{IN@QG](https://user-images.githubusercontent.com/107661622/179737655-a345a5ef-a55c-49f0-913f-0b4fb614c017.png)
刚看了下，现在好像可以了，下午观众下载到104g达到做种体积限制，刚刚又新增了3个下载，突破100g做种限制了
