### ISSUE TITLE
新版本识别问题 

### ISSUE THREAD

**Issue by ltsj** [jxxghp/nas-tools#531]
更新至 v1.9.10 后 大量原先可以识别的剧集无法识别
比如
Childhood.In.A.Capsule.S01E16.2022.1080p.KKTV.WEB-DL.x264.AAC-ADWeb.mkv
之前是识别 Childhood In A Capsule  现在只识别 Childhood
23:25:37 INFO - 【META】Childhood 以年份 2022 在TMDB中未找到电视剧信息!
23:25:37 INFO - 【META】Childhood 以年份 在TMDB中未找到电视剧信息!
23:25:37 INFO - 【META】正在从TheDbMovie网站查询：Childhood ...
23:25:38 INFO - 【META】Childhood TMDB网站返回数据过多：29
23:25:41 INFO - 【META】推断关键字为：['childhood', 'dictionary', 'childhoods', 'what does childhood mean'] ...
23:25:41 INFO - 【META】选择关键字为：childhood
23:25:41 INFO - 【META】开始辅助查询：childhood ...

**Comment by junskycool** [comment]
+1

**Comment by jxxghp** [comment]
Childhood.In.A.Capsule.S01E16.2022.1080p.KKTV.WEB-DL.x264.AAC-ADWeb.mkv

**Comment by jxxghp** [comment]
a1f757696faf24311056a5dc1c73926ab9661415
