### ISSUE TITLE
电影[the lost city]名称识别错误

### ISSUE THREAD

**Issue by JKnuts** [jxxghp/nas-tools#532]
![image](https://user-images.githubusercontent.com/91355283/179559180-eb3d36b6-3819-4ab6-8dc6-ddc4dfe5a8f7.png)

**Comment by JKnuts** [comment]
名称识别不完整
![image](https://user-images.githubusercontent.com/91355283/179578862-8a2b9d74-b770-421f-9b5d-c395ee500a62.png)

**Comment by jxxghp** [comment]
a1f757696faf24311056a5dc1c73926ab9661415
