### ISSUE TITLE
原来能识别的电视剧订阅，出现识别错误或者无法识别

### ISSUE THREAD

**Issue by mirrorhui520** [jxxghp/nas-tools#533]
### 更新了v1.9.10，然后出现电视剧“童时爱上你”、“幸福到万家”均无法继续识别和下载新集数资源的情况。
- 日志提示如下（均为无法识别媒体信息或者把本该是电视剧的识别成另一部电影，并提示资源并非电视剧无法进行订阅命中）。
![image](https://user-images.githubusercontent.com/55034021/179604654-c677104f-5739-4473-8af9-27bd1c9f424f.png)
![image](https://user-images.githubusercontent.com/55034021/179605188-2d0b35ca-3e94-4781-a367-0a9be1949f9a.png)
1. 已尝试检查并非站点问题，也并非jackett问题，命名规范也跟原来能识别的时候一样格式。
2. 已尝试开关辅助识别和豆瓣联想以及精确搜索使用英文名，问题依旧。
- 幸福到万家下载完成后，自动识别和转移失败，于手动识别处进行识别后正常转移入媒体库。
- 童时爱上你下载完成后，自动识别和转移成功（成功识别成Childhood(2019)的电影，并转移进未分类电影文件夹中），手动删除并手动添加文件夹路径识别后正常转移入媒体库。
- 使用名称识别测试PT站中提供的“童时爱上你”种子名称识别的是Childhood(2019)电影，使用中文名“童时爱上你”能准确识别。（没有开精确搜索使用英文名）
![image](https://user-images.githubusercontent.com/55034021/179618817-0399aac9-035d-4528-aead-8c0c3f013541.png)
![image](https://user-images.githubusercontent.com/55034021/179620991-1f3f977c-f529-493a-8b83-acd443549b1a.png)
- 使用名称识别测试PT站中提供的“幸福到万家”种子名称识别的是The Story of Xing(2022)电视剧，使用中文名”幸福到万家“能准确识别。（没有开精确搜索使用英文名）
![image](https://user-images.githubusercontent.com/55034021/179621597-700043e2-d6f1-4f57-a45c-fec24736e0d8.png)
![image](https://user-images.githubusercontent.com/55034021/179622062-2b049d01-758d-4a22-833e-f64304d338e6.png)

**Comment by jxxghp** [comment]
a1f757696faf24311056a5dc1c73926ab9661415
