### ISSUE TITLE
关于未识别到媒体的一点疑问谢谢

### ISSUE THREAD

**Issue by xyswordzoro** [jxxghp/nas-tools#535]
资源搜索界面直接搜索 神奇动物：邓布利多之谜  返回信息很多是未识别到媒体信息
这些种子是复核规则的，不符合的都显示不符合过滤规则
如下一些为 未识别到媒体信息：
Fantastic Beasts the Secrets of Dumbledore 2022 1080p BluRay x265 10bit DTS-ADE
Fantastic Beasts the Secrets of Dumbledore 2022 1080p BluRay x264 DTS-ADE
Fantastic Beasts The Secrets of Dumbledore 2022 1080p BluRay x264-WiKi 
Fantastic Beasts The Secrets of Dumbledore 2022 1080p HMAX WEB-DL x264 DDP5.1 Atmos-ADWeb
Fantastic Beasts The Secrets of Dumbledore 2022 1080p HMAX WEB-DL DDP5.1 Atmos H.264-SMURF 
[英国/美国][神奇动物：邓布利多之谜][Fantastic.Beasts.The.Secrets.of.Dumbledore.2022.1080p.BluRay.Hevc.10bit.Atmos.TrueHD7.1-Iceyumao@Dream] 
[英国/美国][神奇动物：邓布利多之谜][Fantastic.Beasts.the.Secrets.of.Dumbledore.2022.1080p.BluRay.x265.10bit.DTS-ADE] 
[英国/美国][神奇动物：邓布利多之谜][Fantastic.Beasts.The.Secrets.of.Dumbledore.2022.Blu-ray.1080p.Atmos.TrueHD.7.1.x264-HDH]
[英国/美国][神奇动物：邓布利多之谜][Fantastic.Beasts.The.Secrets.of.Dumbledore.2022.1080p.BluRay.x264-WiKi] 
Fantastic Beasts The Secrets of Dumbledore 2022 1080p BluRay DD5.1 x265-10bit-HDS
Fantastic Beasts The Secrets of Dumbledore 2022 V1 1080p WEB-DL DDP5.1 Atmos H264-AQLJ@HDSky

还有其他的先不复制了，规则是包含1080p过滤蓝光原盘（wiki中的排除规则）
设置 为做种数优先， 最后筛选的为一个只要2人做种的资源，网络环境没问题
麻烦大佬有时间看下，若需要完整日志 我再上传，感谢感谢

**Comment by swordzorodai** [comment]
今天刚添加的风骚律师 jackett搜索添加下载了已经   但识别不出来
WARNING: 【RMT】Better.Call.Saul.S06E08.Point.And.Shoot.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv 无法识别媒体信息！
WARNING: 【RMT】风骚律师.Better.Call.Saul.2022.S06E09.1080p.Netflix.WEB-DL.H264.DDP5.1-OurTV.mkv 无法识别媒体信息！
这俩种子是已经jackett识别过了 添加下载后 识别不了的   
基础设置里的 英文名称精确搜索  没有打开

**Comment by xyswordzoro** [comment]
应该是我网络的问题 我重新布置看看
