### ISSUE TITLE
豆瓣订阅添加了 ”未知电影“

### ISSUE THREAD

**Issue by tsymr** [jxxghp/nas-tools#536]
![image](https://user-images.githubusercontent.com/11868091/179871962-58c0ee9e-a96a-4ba1-8143-fce824795469.png)

添加了如图上订阅后无法进行点击操作。

**Comment by jxxghp** [comment]
是之前版本添加的吗，这个问题最新的版本应该没有吧

**Comment by tsymr** [comment]
> 是之前版本添加的吗，这个问题最新的版本应该没有吧

1.9.10版本添加的
