### ISSUE TITLE
对于一些不好识别的动漫一点拙见

### ISSUE THREAD

**Issue by xyswordzoro** [jxxghp/nas-tools#538]
例如：
海贼王是添加不了订阅的，放在了qb里，动漫命名不规范
![This is an image](https://s2.loli.net/2022/07/20/kE8Qc4qJIXz3MTp.jpg)
识别不到tmdb里的海贼王，而且tmdb里有俩海贼王，另一个是美剧就很尴尬，有时候会识别成美剧那个
能不能增加个功能 
当出现 关键字 自动采用tmdb的那个ID进行识别硬链接
例如：出现 one piece   直接采用tmdb的id37854进行硬链接
大佬看下提供个思路，谢谢

**Comment by jxxghp** [comment]
你举例的这个命名也太奇葩了
你的建议不太可行

**Comment by xyswordzoro** [comment]
> 你举例的这个命名也太奇葩了 你的建议不太可行

好吧 我是手动识别的时候想到的，想能不能手动指定ID变自动根据自定义的关键字指定ID
