### ISSUE TITLE
offset命令 第0集 识别问题

### ISSUE THREAD

**Issue by jdjxk** [jxxghp/nas-tools#541]
手动集数定位：Sense8.S02E{ep}.{a}.1080p.WEB-DL.x265.10bit.AC3￡cXcY@FRDS.mkv
offset：1

源文件：
![源文件](https://user-images.githubusercontent.com/46536339/180117879-a96eba7f-0c80-4674-bd05-e4615a1fdca4.png)

识别后：
![识别后](https://user-images.githubusercontent.com/46536339/180117927-7592a12f-cd35-4192-b826-2bbdd1253f99.png)

设置offset+1，第0集没有被识别，只生成2-12集
如果不设置offset+1，0-11集可以正常识别

**Comment by jxxghp** [comment]
@JohnZp

**Comment by JohnZp** [comment]
已修复

**Comment by jdjxk** [comment]
抱歉，更新 v1.9.12 后问题依旧，请再确认下？
