### ISSUE TITLE
动漫重复下载

### ISSUE THREAD

**Issue by Hazard804** [jxxghp/nas-tools#543]
![image](https://user-images.githubusercontent.com/82299110/180186811-2a3bcb76-9b1d-4ab2-9ef4-0715beef8c0d.png)
![image](https://user-images.githubusercontent.com/82299110/180186931-d0698030-f790-47c9-947d-95f3942bf58c.png)
![image](https://user-images.githubusercontent.com/82299110/180187684-b1bcf104-7c9f-4a34-9f9c-2f3d9ed297cb.png)

如上图 在订阅内该动漫已经到达第三集的情况下 仍然时不时RSS自动下载 
刚开始以为是识别成了一整季 不过在名称识别测试中测试能够识别出S01E03 
经观察我订阅的多个动漫皆有此现象 
不知这是我的哪个步骤有错误还是BUG或者名称识别的缺陷
感谢大佬

**Comment by Hazard804** [comment]
又排查了一遍发现是我自己不知道啥时候开启了 高质量文件覆盖 打扰了

**Comment by Hazard804** [comment]
![image](https://user-images.githubusercontent.com/82299110/180194388-5253bac5-f4a6-43c7-a845-124543c04d7f.png)
![image](https://user-images.githubusercontent.com/82299110/180194780-75277983-020a-44ab-8525-c6de909aeac5.png)

已经关闭关闭高质量文件覆盖 又下载了哈哈哈

**Comment by log-time** [comment]
似乎跟我之前遇到的那个连续抓rss的情形有点像

**Comment by jxxghp** [comment]
配置emby和媒体库了吗？查不到本地已有的话会下载的

**Comment by jxxghp** [comment]
已修复
