### ISSUE TITLE
订阅资源不能取消部分站点

### ISSUE THREAD

**Issue by benzking** [jxxghp/nas-tools#548]
![1658474286642](https://user-images.githubusercontent.com/2979921/180385437-eb693073-21f2-4bf9-9d67-3cc5bc8d8069.png)
取消选择部分站点按确定后不能保存，下次进入还是全选站点，
nastool版本：1.9.12 docker安装

**Comment by jxxghp** [comment]
就是这么设计的啊，不选等于全选

**Comment by benzking** [comment]
不能只选从订阅站点下载？不走jk
