### ISSUE TITLE
推送Tr下载任务出错：Query failed with result "invalid or corrupt torrent file".

### ISSUE THREAD

**Issue by frank-we** [jxxghp/nas-tools#551]
## 动漫订阅  
异世界归来的舅舅
不死者之王 第四季 OVERLORD Ⅳ
## 种子
[[桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [01][1080p][简体内嵌]](https://miobt.com/show-3bcda760f36d88e078a458b703574f11a9049c9e.html)
[猎户不鸽发布组] 不死者之王 第四季 OVERLORD Ⅳ [03] [1080p] [简中内封] [2022年7月番]
## transmission 版本
3.0.0.3
## 问题
订阅动画时，发送下载链接给 Tr 时报错，无法正常下载。
异世界归来的舅舅 推送全部失败。
不死者之王 第四季 有一个链接成功，其他失败。
当手动刷新订阅，发起下载请求全部失败后，会删除订阅，只好重新添加。
此前已成功下载电影，未出现此问题。
## 期望
成功添加种子并下载。
如果下载失败，不要删除订阅。

## 成功日志
16:19:29 INFO - 【DOWNLOADER】添加PT任务：[猎户不鸽发布组] 不死者之王 第四季 OVERLORD Ⅳ [02] [1080p] [简中内封] [2022年7月番] ...
16:19:36 INFO - 【DOWNLOADER】添加PT任务：http://ip:xxx/3/download?apikey=apikey&link=ZzZDRkJrdkdZdTNKajNvTGZ6ZStoeDhDTy9SYmVWM0dacmxjYk8wdHFNTWwwQnY0c3FpelI3TDVKU3IrVm5SM08xNGRYZzJycDRWbCt5cEgyZDZmQnFkcDVlYUpuWWtEVzJyanRuZFh1MWlPeUlnbHpvZHlEd29sNW9jVFVkRm5TQjY3clpWVFZBZGVZaGMxcTkyRFBBPT0&file=%5B%E7%8C%8E%E6%88%B7%E4%B8%8D%E9%B8%BD%E5%8F%91%E5%B8%83%E7%BB%84%5D+%E4%B8%8D%E6%AD%BB%E8%80%85%E4%B9%8B%E7%8E%8B+%E7%AC%AC%E5%9B%9B%E5%AD%A3+OVERLORD+%E2%85%A3+%5B02%5D+%5B1080p%5D+%5B%E7%AE%80%E4%B8%AD%E5%86%85%E5%B0%81%5D+%5B2022%E5%B9%B47%E6%9C%88%E7%95%AA%5D
16:19:36 INFO - 【MSG】发送wechat消息：title=OVERLORD (2015) S04 E02, text=RSS订阅的动漫 OVERLORD (2015)S04 E02 已开始下载 站点：Mikan 质量：1080p 大小：429.7M 种子：[猎户不鸽发布组] 不死者之王 第四季 OVERLORD Ⅳ [02] [1080p] [简中内封] [2022年7月番] 做种数：1 促销：免费

## 错误日志
 16:11:16 INFO - 【RSS】共有 1 个电视剧订阅需要检索
16:11:16 INFO - 【DOWNLOADER】异世界归来的舅舅 (2022) 第1季 共有 13 集
16:11:16 INFO - 【DOWNLOADER】异世界归来的舅舅 (2022) 第1季 缺失 13 集
16:11:16 INFO - 【SEARCHER】开始检索 异世界归来的舅舅 ...
16:11:16 INFO - 【PROWLARR】开始检索 异世界归来的舅舅，站点：['MioBT'] ...
16:11:16 INFO - 【PROWLARR】开始检索Indexer：MioBT ...
16:11:23 WARN - 【PROWLARR】MioBT 返回数据：17
16:11:23 INFO - 【PROWLARR】[桜都字幕組] 異世界歸來的舅舅 / Isekai Ojisan [03][1080p][繁體內嵌] 匹配成功
16:11:23 INFO - 【PROWLARR】[桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [03][1080p][简繁内封] 匹配成功
16:11:23 INFO - 【PROWLARR】[桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [03][1080p][简体内嵌] 匹配成功
16:11:23 INFO - 【PROWLARR】[桜都字幕組] 異世界歸來的舅舅 / Isekai Ojisan [03][720p][繁體內嵌] 376.0M 不符合订阅过滤规则
16:11:23 INFO - 【PROWLARR】[桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [03][720p][简体内嵌] 376.0M 不符合订阅过滤规则
16:11:23 INFO - 【PROWLARR】[猎户随缘发布组] 异世界舅舅 / 异世界归来的舅舅 Isekai Ojisan [01-02] [1080p] [简中内嵌] [2022年7月番] 匹配成功
16:11:23 INFO - 【PROWLARR】电影：Isekai 不匹配名称：['异世界归来的舅舅']
16:11:23 INFO - 【PROWLARR】电影：Isekai 不匹配名称：['异世界归来的舅舅']
16:11:23 INFO - 【PROWLARR】电影：Isekai 不匹配名称：['异世界归来的舅舅']
16:11:23 INFO - 【PROWLARR】[桜都字幕組] 異世界歸來的舅舅 / Isekai Ojisan [02][720p][繁體內嵌] 377.1M 不符合订阅过滤规则
16:11:23 INFO - 【PROWLARR】[桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [02][720p][简体内嵌] 377.1M 不符合订阅过滤规则
16:11:23 INFO - 【PROWLARR】[桜都字幕組] 異世界歸來的舅舅 / Isekai Ojisan [01][1080p][繁體內嵌] 匹配成功
16:11:23 INFO - 【PROWLARR】[桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [01][1080p][简繁内封] 匹配成功
16:11:23 INFO - 【PROWLARR】[桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [01][1080p][简体内嵌] 匹配成功
16:11:23 INFO - 【PROWLARR】[桜都字幕組] 異世界歸來的舅舅 / Isekai Ojisan [01][720p][繁體內嵌] 419.0M 不符合订阅过滤规则
16:11:23 INFO - 【PROWLARR】[桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [01][720p][简体内嵌] 419.1M 不符合订阅过滤规则
16:11:23 INFO - 【PROWLARR】[jibaketa]異世界歸來的舅舅 / 異世界舅舅 播出前1小時特別節目 (AT-X 1440x1080 x264 AAC) 1.7G 不符合订阅过滤规则
16:11:23 INFO - 【PROWLARR】MioBT 共检索到 7 条有效资源
16:11:23 INFO - 【PROWLARR】所有API检索完成，有效资源数：7
16:11:23 INFO - 【DOWNLOADER】添加PT任务：[桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [01][1080p][简体内嵌] ...
16:11:28 INFO - 【DOWNLOADER】添加PT任务：http://ip:xxx/3/download?apikey=apikey&link=SEtvRWdmVkVMOG1RWGRzWnJGQkh2aWVBVVpoZjJmKzFsRExVa2VrZGkrbVZLQUFERGJmZjdMRmhIbUVSQnd0WllQdWJ4V3psbE1FZU5KRnl2UXduNWh2VDdJQ2F3RWpqZEp1VnJHUEZaTENpd2ZMVVpaZjQ0UTNxL2V0L2JYNXVHeHdta3FvYlFMTld0YVBBTXh1U0p6RUdKOEIrR0xoZkVuTFpZTytHb0RkbW9oUzZOSTgxbFVTOFZmamJ6TnUyVlltcWw1OHRVU2JGWWdVdFZ6cWhDTUVFMFJnbHBRa0FMR0hXaGxMSGJvTk1JWXdhM3EzYVZzREtaQWdoN0NSelVUQVZjRmNVT2lKaGUyOFZ1bEJhZVVUV05YK1BkQzNBRjJTZHZ3UUxveGF1VFdCOUVxOEI2eWlwbkFNcS9ETVNJMVNnR2w3aEg5bUdkMFNIckJ6OGdiK0pEdGIyWFdPRXB1aG9KUEpXRDEwemMwUjBzMnc1MEcxUUNNV3dPN1FQOGgyZXN5ZFVYaXo5RXY3Z3RaWmRaaXJyNVJ3MHlnWmdKL0w5YUNOMlRyYm4yY0xCNHJNeXJpbGQ5cTdDR25QeXN2V2c4L3RIRzFHQ2dzUHdiWU1oUi9FelNoRjExL0lLWUd6bHU4dW1nYXp6aURmNVZxT0pFRnNOUjhCVVZKMVoxYTY2WDJWMlZZMUtKWTdWYmZWYnAyc2g3c2ZwZk1aalNReDVOLzVDbUV3cGZZTjZ2czh0U0FYTkdpcnE3N2crdTY2QUZXOE1GZVFMSHgwQlY0U21LVFZTcmI0QTFaV1owS1BwVVpVVC9tdEhCRFJzTTlpNysxQTVKZ2JUN2QvdkFoMWtqTXo2bTJPWHFzWXZCZGM1RmlPV0xZbHFNaWJaN0E5TndtMkR4NHc4MFdBemZxanVXQUNIOFBESlRRaFRteit5SnJ3SUpIbFhvYnIvbGhnWmZDQXZ3V2xua2Zad1Ntd1ZRY2xaK3FtK25zandJcnNWaUFJY0ZudjJZY3Y5Ulk0c1J3cTJuQWk3WmtEOGc4UEUxYURZMDJLZ2ZJaXoraWVocG1vRVRsZGF2UXBTZGc5eTBRYXM2cGNHczZTeFVrTGtqNlFZNkV0TW9vaEsxTkg5dFVrSnlFRGlWVGJYTFdXUTR1V3NQVUgreEJMZXdJeERiRkpOZWlRaXBPaTQvanR0TXdOWUJkVE5mWnJCY0VJZDk4bDBMaiszdDR6RlB4cEQwSE5tS1RzaUprbndXVzdVWHk4N09FZW5wTXp5cVV1L0pvRVdTS2hIK1VBWCtsd0RvaHFqK2tXTFBBOVFuMGw3Q3FuQlMzUVNHb2M4b0Zvd2pHbGt4OWszZ1h0bUlxZU9nME1mRDllbjhtT240d0hvK3dGbTR3TkZSZTBERm1vNUh1b1RDZWdmaDk2T05uTDFGWkZ0L0hmN0RyVVkzWklFNmJQVW5MS0xNcFBoNFJGU0s2eUJ4UEM5c2hBc1VENzR5eXR5TkdQWUJTLzJ3bWJzd204YzNPcjBRczlPcWV3SXZwOXhSZDVsS2lBWkV6SjdmOFhuRVFqMXFlM1NzelU2aGdhMTdnZ0lWbVJrVW8zN0dIQVVRV1dNQUUxTlhLdFgyNWkvdGd2WkhlY0NGM3prNUdLYkowMkFIYWxIK3ZIcVFRYzUzUHY5UittT21UelVRemlXeDNsVzcxT3U0bGRiLzNRdnFaRlZsbC94R1VXT0ZIcFN4UVNqRkdzeG5oMGNoZ056bHdXQ2ZrUGczSGpWUTlXUmF6ZUJVUC9XNUtUYnFVOVdOT09YNTl3VFRjMWQ3ekpBVy9EcG5rdlBoVHhMMjg1Y2xEenFVVWY1VVgzcjZYcFlTUXRLRldXcDFoSTRQZzNPcUkvTGh0emtHQUlLdHNFQjdqeFE0cEthTTc2ZG9VYklDQVU0dzhOU09ZZXJ1VXlHRndZeEg3L3dFamUrc2JldGxvNjg3Yi9QOXovMU91QTdEZGtBWUl2dWM4SU1xZVhTdmdsRlYzTDRZZ2p4dFZUV0kwWXp6UnhQc2hLdkRWQk0zZzNzWnRzNTF1RHFVUDQ0aVFHeVpGN1dHSU0wOERlRUZyYXJnQlpqUXk5YVljazFGREoybEF4WmxlUnJ5ODZrK2lHWndUMytmdjhNZGc9PQ&file=%5B%E6%A1%9C%E9%83%BD%E5%AD%97%E5%B9%95%E7%BB%84%5D+%E5%BC%82%E4%B8%96%E7%95%8C%E5%BD%92%E6%9D%A5%E7%9A%84%E8%88%85%E8%88%85+%2F+Isekai+Ojisan+%5B01%5D%5B1080p%5D%5B%E7%AE%80%E4%BD%93%E5%86%85%E5%B5%8C%5D
16:11:33 ERROR - 【DOWNLOADER】添加下载任务出错：Query failed with result "invalid or corrupt torrent file".
16:11:33 ERROR - 【DOWNLOADER】添加下载任务失败：异世界归来的舅舅 (2022)
16:11:33 INFO - 【MSG】发送wechat消息：title=添加下载任务失败：异世界归来的舅舅 (2022) S01, text=种子：[桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [01][1080p][简体内嵌] 错误信息：Query failed with result "invalid or corrupt torrent file".
16:11:33 ERROR - 【MSG】发送消息失败：参数未配置或配置不正确
16:11:33 INFO - 【SEARCHER】异世界归来的舅舅 未下载到资源
16:11:33 INFO - 【RSS】电视剧 异世界归来的舅舅 下载完成，删除订阅...

**Comment by frank-we** [comment]
切换成 Jackett 后，不死者之王 已经成功下载并订阅追剧。
以上报错问题已经解决。
出现另一个问题。
异世界归来的舅舅，匹配到7条数据，其中有123集，但实际下载只有一集，并且未正常检查缺少集数便删除订阅。
![图片](https://user-images.githubusercontent.com/66304894/180412507-438265df-736b-476c-9da5-3f7aa93bed9b.png)

**Comment by jxxghp** [comment]
问题提的很详细，优秀！
1、就 Query failed with result "invalid or corrupt torrent file"  这个错而言，是这个种子文件有问题，TR报的错，你可以在浏览器中输入这个种子地址，看是不是能下到种子文件，文件是否正常，这个错本工具解决不了。
2、下载完成后删订阅是因为这个动漫命名识别不了，没有从里面读出来集数，认为是整季了。提供的这个命名我做了兼容处理，稍后可以更新下代码试试。

**Comment by frank-we** [comment]
另外有个建议，希望手动搜索中，高级搜索添加一个 动漫类别，和媒体库同步。
我在这里搜索动漫，下载下来却下到了电视剧的文件夹中，应该是未能正确匹配媒体库。
谢谢这个优秀的工具，十分便利。
![图片](https://user-images.githubusercontent.com/66304894/180413017-2b2e9250-dda6-4d69-9896-6a1cf535cf59.png)

**Comment by frank-we** [comment]
> 问题提的很详细，优秀！ 1、就 Query failed with result "invalid or corrupt torrent file" 这个错而言，是这个种子文件有问题，TR报的错，你可以在浏览器中输入这个种子地址，看是不是能下到种子文件，文件是否正常，这个错本工具解决不了。 2、下载完成后删订阅是因为这个动漫命名识别不了，没有从里面读出来集数，认为是整季了。提供的这个命名我做了兼容处理，稍后可以更新下代码试试。

换成Jackett已经解决，感谢。
