### ISSUE TITLE
微信搜索订阅

### ISSUE THREAD

**Issue by leo8912** [jxxghp/nas-tools#554]
现在是微信搜索改了吗？发片名，不再是先搜索豆瓣词条了（已开豆瓣联想）
![Screenshot_2022-07-22-18-12-48-256_com.tencent.mm.png](https://user-images.githubusercontent.com/22719866/180417894-c6cf6341-eb54-40d4-89fa-4f8b9c4615cd.png)

**Comment by jxxghp** [comment]
确认清楚了再提

**Comment by leo8912** [comment]
> 确认清楚了再提
正常情况下应该是这样的，
![Screenshot_2022-07-22-18-26-52-698_com.tencent.mm.png](https://user-images.githubusercontent.com/22719866/180421177-2d8af902-6bfa-40b6-a144-a1ba10113726.png)
我在web端搜索订阅这个片成功了。。
![Screenshot_2022-07-22-18-36-30-258_com.microsoft.emmx.canary.png](https://user-images.githubusercontent.com/22719866/180421915-dc1f4876-5dad-4000-94d2-1d1749a76052.png)
![Screenshot_2022-07-22-18-36-16-022_com.microsoft.emmx.canary.png](https://user-images.githubusercontent.com/22719866/180421958-80ee6e2a-9a8f-48ec-b091-d78bb6ddbd69.png)

（刚又去tmdb查了下，好像没有这个片子。。。那订阅是怎么成功的？用的豆瓣数据？微信端应该跟web端订阅做一样的效果吧
