### ISSUE TITLE
电视剧RSS匹配命中后直接加入“已订阅”，未能执行下载

### ISSUE THREAD

**Issue by mirrorhui520** [jxxghp/nas-tools#555]
### 虽然最终问题得到了解决，但由于不清楚是否项目代码问题还是自己规则的问题（应该不是，我使用的规则只填了必须满足1080p），我也查看过以往的Issues和WIKI的常见问题并没有搜到相关信息，所以整理了一下发一下Issues，毕竟有可能不止是这一部电视剧会有这个问题。

- 详细过程：

    - 第一次手动执行RSS订阅前，检查了种子名称正常识别，执行后弹出了订阅成功的弹窗，查看日志先提示 童时爱上你 最后一集E20匹配成功，但下方并没有出现过E20的资源信息，程序也正常识别以往已经下载入库的集数“已成功订阅过”的信息，童时爱上你 剧集订阅处理的最后提示**匹配到1个有效资源**，如下图：
![1](https://user-images.githubusercontent.com/55034021/180489177-20468a9f-32e8-408a-9cc8-cb7d79e9800b.png)

    - 1.接下来处理完柠檬站的第二部电视剧后，**最终提示本次RSS处理共有1个有效资源，随后提示“未下载任何资源”**，过后检查过也并非是PT站的“第一次下载检测”导致，可以排除这个原因。
    2.接下来第二次执行RSS订阅，**执行前进行了“清理文件缓存”，也检查过QB的确没有执行下载，也检查过本地并没有E20集的文件，也检查过“媒体整理中的历史记录”并没有相关记录**，执行RSS订阅后查看日志提示“**20集已成功订阅过**”，如下图：
![2](https://user-images.githubusercontent.com/55034021/180489218-d62cf275-ebed-4372-9fb4-34ea19260bcd.png)

    - 没有办法，只能执行“电视剧订阅”中的订阅更新，通过jackett检索全数20集匹配成功，并于20集成功下载后执行删除电视剧订阅，如下图：
![3](https://user-images.githubusercontent.com/55034021/180489284-52e6f9a5-7825-4cbe-8501-e8fab2dae67e.png)

**Comment by jxxghp** [comment]
无法重现问题
