### ISSUE TITLE
目录同步缺失文件

### ISSUE THREAD

**Issue by nzmkNARUTO** [jxxghp/nas-tools#557]
在订阅中订阅了内容，可以正常下载，在下载完成后有些视频不会被自动同步，手动开始同步后显示“所有文件均已成功转移过，没有需要处理的文件“

日志如下：
09:42:32 INFO - 【RMT】开始处理：/nastools/download/movies/[Moozzi2] Cencoroll Connect - Movie + Tokuten BD
09:42:32 WARN - 【RMT】文件 /nastools/media/movies/外语电影/Tokuten Eizou Anthology No. 1 (1964)/Tokuten Eizou Anthology No. 1 (1964) - 1920x.mkv 已存在
09:42:32 INFO - 【RMT】/nastools/download/movies/[Moozzi2] Cencoroll Connect - Movie + Tokuten BD 处理完成，总数：1，失败：1
09:42:32 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 04 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:42:32 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E04 - 第4集.mkv 已存在
09:42:32 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 04 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:42:32 INFO - 【RMT】开始处理：/nastools/download/animes/[Yusyabu&LoliHouse] Shokei Shoujo no Virgin Road - 06 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:42:32 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:42:32 INFO - 【RMT】开始处理：/nastools/download/animes/[Yusyabu&LoliHouse] Shokei Shoujo no Virgin Road - 03 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:42:32 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:42:32 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Shokei Shoujo no Virgin Road][04][1080p][CHT].mp4
09:42:32 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:42:32 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 10 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:42:32 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E10 - 第10集.mkv 已存在
09:42:32 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 10 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:42:32 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Lycoris Recoil][03][1080p][CHS].mp4
09:42:32 WARN - 【RMT】文件 /nastools/media/animes/动漫/莉可丽丝 (2022)/Season 1/莉可丽丝 - S01E03 - 第3集.mp4 已存在
09:42:32 INFO - 【RMT】/nastools/download/animes/[Nekomoe kissaten][Lycoris Recoil][03][1080p][CHS].mp4 处理完成，总数：1，失败：1
09:42:32 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 08 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:42:32 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E08 - 第8集.mkv 已存在
09:42:32 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 08 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:42:32 INFO - 【RMT】开始处理：/nastools/download/animes/[Comicat][Violet_Evergarden][BDrip][01_13][BIG5][1080P][HEVC_Main10]
09:42:32 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:42:32 INFO - 【RMT】开始处理：/nastools/download/animes/[Yusyabu&LoliHouse] Shokei Shoujo no Virgin Road - 10 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:42:32 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:42:32 INFO - 【RMT】开始处理：/nastools/download/animes/[Kamigami] Summer Time Rendering - 14 [1080p x265 Ma10p AAC].mkv
09:42:32 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:42:32 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 03 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:42:32 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E03 - 第3集.mkv 已存在
09:42:32 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 03 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:42:32 INFO - 【RMT】开始处理：/nastools/download/animes/[Sakurato] Isekai Ojisan [03][AVC-8bit 1080p AAC][CHS].mp4
09:42:32 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:42:32 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 07 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:42:32 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E07 - 第7集.mkv 已存在
09:42:32 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 07 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:42:32 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Lycoris Recoil][02][1080p][CHS].mp4
09:42:32 WARN - 【RMT】文件 /nastools/media/animes/动漫/莉可丽丝 (2022)/Season 1/莉可丽丝 - S01E02 - 第2集.mp4 已存在
09:42:32 INFO - 【RMT】/nastools/download/animes/[Nekomoe kissaten][Lycoris Recoil][02][1080p][CHS].mp4 处理完成，总数：1，失败：1
09:42:32 INFO - 【RMT】开始处理：/nastools/download/animes/[CoolComic404][Summer Time Rendering][13][1080P][WebRip][CHS_JPN][AVC AAC].mp4
09:42:32 WARN - 【RMT】[CoolComic404][Summer Time Rendering][13][1080P][WebRip][CHS_JPN][AVC AAC].mp4 无法识别媒体信息！
09:42:32 WARN - 【RMT】[CoolComic404][Summer Time Rendering][13][1080P][WebRip][CHS_JPN][AVC AAC].mp4 按原文件名转移到unknown目录：/nastools/media/unknowns
09:42:32 INFO - 【RMT】/nastools/download/animes/[CoolComic404][Summer Time Rendering][13][1080P][WebRip][CHS_JPN][AVC AAC].mp4 硬链接到unknown完成
09:42:32 INFO - 【RMT】/nastools/download/animes/[CoolComic404][Summer Time Rendering][13][1080P][WebRip][CHS_JPN][AVC AAC].mp4 处理完成，总数：1，失败：1
09:42:32 INFO - 【MSG】发送wechat消息：title=/nastools/download/animes/[CoolComic404][Summer Time Rendering][13][1080P][WebRip][CHS_JPN][AVC AAC].mp4 有 1 个文件转移失败，请登录NASTool查看, text=
09:42:35 ERROR - 【SYNC】/nastools/download/animes 处理失败：无法识别媒体信息
09:42:35 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 01 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:42:35 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E01 - 第1集.mkv 已存在
09:42:35 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 01 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:42:35 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Shokei Shoujo no Virgin Road][08][1080p][CHS].mp4
09:42:35 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:42:35 INFO - 【RMT】开始处理：/nastools/download/animes/[Kamigami] Summer Time Rendering - 02 [1080p x265 Ma10p AAC].mkv
09:42:35 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E02 - 第2集.mkv 已存在
09:42:35 INFO - 【RMT】/nastools/download/animes/[Kamigami] Summer Time Rendering - 02 [1080p x265 Ma10p AAC].mkv 处理完成，总数：1，失败：1
09:42:35 INFO - 【RMT】开始处理：/nastools/download/animes/[CoolComic404][Summer Time Rendering][12][1080P][WebRip][CHS_JPN][AVC AAC].mp4
09:42:35 WARN - 【RMT】[CoolComic404][Summer Time Rendering][12][1080P][WebRip][CHS_JPN][AVC AAC].mp4 无法识别媒体信息！
09:42:35 WARN - 【RMT】[CoolComic404][Summer Time Rendering][12][1080P][WebRip][CHS_JPN][AVC AAC].mp4 按原文件名转移到unknown目录：/nastools/media/unknowns
09:42:35 INFO - 【RMT】/nastools/download/animes/[CoolComic404][Summer Time Rendering][12][1080P][WebRip][CHS_JPN][AVC AAC].mp4 硬链接到unknown完成
09:42:35 INFO - 【RMT】/nastools/download/animes/[CoolComic404][Summer Time Rendering][12][1080P][WebRip][CHS_JPN][AVC AAC].mp4 处理完成，总数：1，失败：1
09:42:35 INFO - 【MSG】发送wechat消息：title=/nastools/download/animes/[CoolComic404][Summer Time Rendering][12][1080P][WebRip][CHS_JPN][AVC AAC].mp4 有 1 个文件转移失败，请登录NASTool查看, text=
09:42:36 ERROR - 【SYNC】/nastools/download/animes 处理失败：无法识别媒体信息
09:42:36 INFO - 【RMT】开始处理：/nastools/download/animes/[Yusyabu&LoliHouse] Shokei Shoujo no Virgin Road - 09 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:42:36 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:42:36 INFO - 【RMT】开始处理：/nastools/download/animes/[DHR][Shokei Shoujo no Virgin Road][02][BIG5][1080P][AVC_AAC].mp4
09:42:36 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:42:36 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 09 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:42:36 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E09 - 第9集.mkv 已存在
09:42:36 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 09 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:42:36 INFO - 【RMT】开始处理：/nastools/download/animes/[Yusyabu&LoliHouse] Shokei Shoujo no Virgin Road - 12 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:42:36 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:42:36 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Summer Time Rendering][15][1080p][JPTC].mp4
09:42:36 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:42:36 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 05 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:42:36 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E05 - 第5集.mkv 已存在
09:42:36 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 05 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:42:36 INFO - 【RMT】开始处理：/nastools/download/animes/[Yusyabu&LoliHouse] Shokei Shoujo no Virgin Road - 11 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:42:36 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:42:36 INFO - 【RMT】开始处理：/nastools/download/animes/[orion origin] Isekai Ojisan [01-02] [1080p] [H265 AAC] [GB]
09:42:36 WARN - 【RMT】文件 /nastools/media/animes/动漫/异世界归来的舅舅 (2022)/Season 1/异世界归来的舅舅 - S01E02 - 第2集.mp4 已存在
09:42:36 WARN - 【RMT】文件 /nastools/media/animes/动漫/异世界归来的舅舅 (2022)/Season 1/异世界归来的舅舅 - S01E01 - 第1集.mp4 已存在
09:42:36 INFO - 【RMT】/nastools/download/animes/[orion origin] Isekai Ojisan [01-02] [1080p] [H265 AAC] [GB] 处理完成，总数：2，失败：2
09:42:36 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Shokei Shoujo no Virgin Road][05][1080p][CHT].mp4
09:42:36 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:42:36 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Shokei Shoujo no Virgin Road][07][1080p][CHS].mp4
09:42:36 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:42:36 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Lycoris Recoil][01][1080p][CHS].mp4
09:42:36 WARN - 【RMT】文件 /nastools/media/animes/动漫/莉可丽丝 (2022)/Season 1/莉可丽丝 - S01E01 - 第1集.mp4 已存在
09:42:36 INFO - 【RMT】/nastools/download/animes/[Nekomoe kissaten][Lycoris Recoil][01][1080p][CHS].mp4 处理完成，总数：1，失败：1
09:42:36 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 06 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:42:36 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E06 - 第6集.mkv 已存在
09:42:36 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 06 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:42:36 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 11 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:42:36 INFO - 【RMT】正在转移文件：[DMG&LoliHouse] Summer Time Render - 11 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 到 夏日重现 - S01E11 - 第11集.mkv
09:42:36 INFO - 【RMT】文件 [DMG&LoliHouse] Summer Time Render - 11 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 硬链接完成
09:42:36 INFO - 【NFO】正在生成电视剧NFO文件：/nastools/media/animes/动漫/夏日重现 (2022)
09:42:36 INFO - 【NFO】正在生成剧集NFO文件：夏日重现 - S01E11 - 第11集
09:42:36 INFO - 【MSG】发送wechat消息：title=夏日重现 (2022) S01 转移完成, text=评分：7.8，类型：动漫，类别：动漫，共0集，总大小：420.66M，来自：目录同步
09:42:38 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 11 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：0
09:42:38 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Shokei Shoujo no Virgin Road][01][1080p][CHS].mp4
09:42:38 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/movies/[Moozzi2] Cencoroll Connect - Movie + Tokuten BD
09:43:25 WARN - 【RMT】文件 /nastools/media/movies/外语电影/Tokuten Eizou Anthology No. 1 (1964)/Tokuten Eizou Anthology No. 1 (1964) - 1920x.mkv 已存在
09:43:25 INFO - 【RMT】/nastools/download/movies/[Moozzi2] Cencoroll Connect - Movie + Tokuten BD 处理完成，总数：1，失败：1
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 04 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:43:25 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E04 - 第4集.mkv 已存在
09:43:25 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 04 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Yusyabu&LoliHouse] Shokei Shoujo no Virgin Road - 06 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Yusyabu&LoliHouse] Shokei Shoujo no Virgin Road - 03 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Shokei Shoujo no Virgin Road][04][1080p][CHT].mp4
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 10 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:43:25 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E10 - 第10集.mkv 已存在
09:43:25 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 10 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Lycoris Recoil][03][1080p][CHS].mp4
09:43:25 WARN - 【RMT】文件 /nastools/media/animes/动漫/莉可丽丝 (2022)/Season 1/莉可丽丝 - S01E03 - 第3集.mp4 已存在
09:43:25 INFO - 【RMT】/nastools/download/animes/[Nekomoe kissaten][Lycoris Recoil][03][1080p][CHS].mp4 处理完成，总数：1，失败：1
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 08 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:43:25 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E08 - 第8集.mkv 已存在
09:43:25 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 08 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Comicat][Violet_Evergarden][BDrip][01_13][BIG5][1080P][HEVC_Main10]
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Yusyabu&LoliHouse] Shokei Shoujo no Virgin Road - 10 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Kamigami] Summer Time Rendering - 14 [1080p x265 Ma10p AAC].mkv
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 03 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:43:25 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E03 - 第3集.mkv 已存在
09:43:25 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 03 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Sakurato] Isekai Ojisan [03][AVC-8bit 1080p AAC][CHS].mp4
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 07 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:43:25 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E07 - 第7集.mkv 已存在
09:43:25 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 07 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Lycoris Recoil][02][1080p][CHS].mp4
09:43:25 WARN - 【RMT】文件 /nastools/media/animes/动漫/莉可丽丝 (2022)/Season 1/莉可丽丝 - S01E02 - 第2集.mp4 已存在
09:43:25 INFO - 【RMT】/nastools/download/animes/[Nekomoe kissaten][Lycoris Recoil][02][1080p][CHS].mp4 处理完成，总数：1，失败：1
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[CoolComic404][Summer Time Rendering][13][1080P][WebRip][CHS_JPN][AVC AAC].mp4
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 01 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:43:25 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E01 - 第1集.mkv 已存在
09:43:25 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 01 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Shokei Shoujo no Virgin Road][08][1080p][CHS].mp4
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Kamigami] Summer Time Rendering - 02 [1080p x265 Ma10p AAC].mkv
09:43:25 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E02 - 第2集.mkv 已存在
09:43:25 INFO - 【RMT】/nastools/download/animes/[Kamigami] Summer Time Rendering - 02 [1080p x265 Ma10p AAC].mkv 处理完成，总数：1，失败：1
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[CoolComic404][Summer Time Rendering][12][1080P][WebRip][CHS_JPN][AVC AAC].mp4
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Yusyabu&LoliHouse] Shokei Shoujo no Virgin Road - 09 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[DHR][Shokei Shoujo no Virgin Road][02][BIG5][1080P][AVC_AAC].mp4
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 09 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:43:25 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E09 - 第9集.mkv 已存在
09:43:25 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 09 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Yusyabu&LoliHouse] Shokei Shoujo no Virgin Road - 12 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Summer Time Rendering][15][1080p][JPTC].mp4
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 05 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:43:25 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E05 - 第5集.mkv 已存在
09:43:25 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 05 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Yusyabu&LoliHouse] Shokei Shoujo no Virgin Road - 11 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[orion origin] Isekai Ojisan [01-02] [1080p] [H265 AAC] [GB]
09:43:25 WARN - 【RMT】文件 /nastools/media/animes/动漫/异世界归来的舅舅 (2022)/Season 1/异世界归来的舅舅 - S01E02 - 第2集.mp4 已存在
09:43:25 WARN - 【RMT】文件 /nastools/media/animes/动漫/异世界归来的舅舅 (2022)/Season 1/异世界归来的舅舅 - S01E01 - 第1集.mp4 已存在
09:43:25 INFO - 【RMT】/nastools/download/animes/[orion origin] Isekai Ojisan [01-02] [1080p] [H265 AAC] [GB] 处理完成，总数：2，失败：2
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Shokei Shoujo no Virgin Road][05][1080p][CHT].mp4
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Shokei Shoujo no Virgin Road][07][1080p][CHS].mp4
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Lycoris Recoil][01][1080p][CHS].mp4
09:43:25 WARN - 【RMT】文件 /nastools/media/animes/动漫/莉可丽丝 (2022)/Season 1/莉可丽丝 - S01E01 - 第1集.mp4 已存在
09:43:25 INFO - 【RMT】/nastools/download/animes/[Nekomoe kissaten][Lycoris Recoil][01][1080p][CHS].mp4 处理完成，总数：1，失败：1
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 06 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:43:25 WARN - 【RMT】文件 /nastools/media/animes/动漫/夏日重现 (2022)/Season 1/夏日重现 - S01E06 - 第6集.mkv 已存在
09:43:25 INFO - 【RMT】/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 06 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv 处理完成，总数：1，失败：1
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[DMG&LoliHouse] Summer Time Render - 11 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件
09:43:25 INFO - 【RMT】开始处理：/nastools/download/animes/[Nekomoe kissaten][Shokei Shoujo no Virgin Road][01][1080p][CHS].mp4
09:43:25 INFO - 【RMT】所有文件均已成功转移过，没有需要处理的文件

媒体文件夹中可以看到缺失12、13集：
![image](https://user-images.githubusercontent.com/49197283/180585816-850a0f80-5b87-487e-85a4-98d73605d1c6.png)

下载文件夹中有12、13集：
![image](https://user-images.githubusercontent.com/49197283/180585856-90a32368-3100-4325-8c27-219e0f61211e.png)

文件命名方式不同，但是都是通过电视剧订阅自动下载的

**Comment by jxxghp** [comment]
有缺失文件检查文件大小限制的配置。
要重新跑在服务那里清空缓存。
