### ISSUE TITLE
订阅后无法正确识别

### ISSUE THREAD

**Issue by dnpl** [jxxghp/nas-tools#559]
新电视剧订阅后无法在TMDB正确识别(在其网站可检索到)，导致不下载;如电视剧《少年派2》。另外电视剧《沉香如屑》订阅后，日志检索标题为啥自动加了内容(变成了《沉香如屑.沉香重华》)，导致无法检索到，两个问题的日志如下
![Screenshot_2022-07-23-04-46-36-566_com android browser](https://user-images.githubusercontent.com/22452022/180591788-a89e887f-54c0-4c1b-95b1-4ec41969d008.jpg)

![Screenshot_2022-07-23-13-13-58-301_com android browser](https://user-images.githubusercontent.com/22452022/180591499-3559ee80-0a67-4bbe-a06b-f5c56bd0da1a.jpg)
![Screenshot_2022-07-23-13-13-37-136_com android browser](https://user-images.githubusercontent.com/22452022/180591521-faec2d5b-2cb6-419c-b1b2-420589027226.jpg)
![Screenshot_2022-07-23-13-13-07-155_com android browser](https://user-images.githubusercontent.com/22452022/180591525-3feeb9a1-72f0-4b28-93c5-c07431971720.jpg)

**Comment by jxxghp** [comment]
这是TMDB的词条问题，见群讨论记录
