### ISSUE TITLE
关于下载完的文件不能复制到指定文件夹

### ISSUE THREAD

**Issue by YikLiu93** [jxxghp/nas-tools#562]
![微信截图_20220724005645](https://user-images.githubusercontent.com/105213026/180615111-e631c8f9-3fb6-4264-bcc4-eaf8ef629eea.png)
如图，下载完的文件不能复制到指定的TV路径，求大佬解惑，感谢

**Comment by jxxghp** [comment]
自己配错了命名格式吧
