### ISSUE TITLE
建议放开微信白名单代理搭建方法

### ISSUE THREAD

**Issue by tvrohd** [jxxghp/nas-tools#564]
微信服务器代理被封禁，代理功能失效，授人以鱼不如授人以渔，这样以后封了也没事了

**Comment by EdisonzhoNG0623** [comment]
需求+1，正好有带公网ip的vps，可以通过自建代理企业微信的形式避免自给自足，希望大佬开个教程

**Comment by yanggea** [comment]
同求一个，这几天一直在折腾这个
