### ISSUE TITLE
建议增加真实移动文件的功能


老大你好，新版里面有没有可能加上  文件真实移动的功能呢？  硬链接软链接和复制都不适合场景

### ISSUE THREAD

**Issue by vbskycn** [jxxghp/nas-tools#565]
因为阿里云盘速度快，资源多，还不用下载，一键转，太方便了，但是别人分享的太乱了，想挂载到本地，用nastools整理一下，硬链接模式会报错！  这个工具搭配pt使用非常完美，但是 整理nas上面的有的数据也很棒，我觉得比其他的刮肖软件好多了！

**Comment by vbskycn** [comment]
老大你好，新版里面有没有可能加上  文件真实移动的功能呢？  硬链接软链接和复制都不适合场景
挂载到本地的阿里云盘可以读写，应该是可以用nastools重命名整理的吧，如果有真实移动文件的功能的话

**Comment by jxxghp** [comment]
是指直接在原文件中改名？提这个需求的还蛮多的。

**Comment by 277383761** [comment]
是的,是的,我也很想要能直接在网盘上改名并移动真实文件的功能.

**Comment by 277383761** [comment]
或者就基于源文件直接命名也行.移动不移动也无所谓

**Comment by vbskycn** [comment]
是的，应用场景就是把网盘挂到本地，但是上面的内容很乱，可以用nastools整理重命名

**Comment by edhnt455** [comment]
+1，我也有这需求！！！希望大佬能加上这功能，感谢！！！

**Comment by sleikang** [comment]
+1  同求，这个硬链接不好用，每次整理过后还得自己去删除原来的目录

**Comment by sleikang** [comment]
这个功能我已经添加了，发布到TG群里了
![image](https://user-images.githubusercontent.com/23020770/182976349-5da1a6ec-e4c9-46ef-acce-3afe6829aa8a.png)

**Comment by jxxghp** [comment]
e008c07b3f421662a0c56bcd4fcd4f33e0623008

**Comment by ershouqingge** [comment]
> 这个功能我已经添加了，发布到TG群里了 ![image](https://user-images.githubusercontent.com/23020770/182976388-1d79cf4c-79ac-4a28-89d0-88d439038027.png)

兄弟 哪个tg群啊
