### ISSUE TITLE
手动识别功能下提示未找到媒体文件，但是实际文件存在的

### ISSUE THREAD

**Issue by benzking** [jxxghp/nas-tools#566]
![1658732133554](https://user-images.githubusercontent.com/2979921/180716400-bd33db91-19ef-4bed-9171-29234b1ca31c.png)
手动识别功能下提示未找到媒体文件，但是实际文件存在的

**Comment by benzking** [comment]
请问这是什么问题呢

**Comment by xxzj990** [comment]
> 请问这是什么问题呢

你这个应该是命名不规范，这种很难支持的，找正规的资源吧，或者自己手动改完文件名再识别
