### ISSUE TITLE
文件已删除，但手动识别列表无更新

### ISSUE THREAD

**Issue by benzking** [jxxghp/nas-tools#567]
![1658732386831](https://user-images.githubusercontent.com/2979921/180717076-2aad8328-c251-476f-a180-2dac440e7036.png)
红框里的文件已删除，点击目录同步功能后，手动识别功能列表后仍存在
另外，/video/tv/阿尔罕布拉宫的回忆.2018.韩国.720P /video/tv/Heart.Signal.S02.2019.WEB-DL.1080p.H265.AAC-PuTao这两个文件夹内所有集数已成功自动识别，仍存在手动识别功能列表

**Comment by jxxghp** [comment]
这不是也有删除功能么，你手动从文件系统删的为啥还要工具去识别联动
