### ISSUE TITLE
PT下载后文件迁移问题

### ISSUE THREAD

**Issue by kalong0126** [jxxghp/nas-tools#572]
1、当我在QB中下载完文件后，最开始标签是NASTOOL，而后过了几分钟，我猜测是执行了PT下载转移的定时任务（我确实也是配置的下载软件监控），标签也变成了已整理。但奇怪的是，文件并没有转移过去，同时也没有推送消息。查看实时日志，也没有任何内容。
2、当我手动把标签改回NASTOOL，再手动点击服务中的PT下载转移，文件能成功转移，也有消息推送，也有日志。一切正常。
所以不明白第1点是怎么产生的，为什么会没有日志，很奇怪。
3、如果某些电影或电视剧在IMDB中识别不到，是否可以增加一个手动命名，再执行文件迁移的功能？现在的情况是识别不到，就不会迁移到媒体库，导致看不了。

另外我是windows环境的QB下载，将下载文件夹以SMB共享形式挂载到群晖进行运作的。媒体库也是windows环境的jellyfin。运行下来发现有个地方可以优化一下，解决文件分隔符因windows环境会出现"\\"的问题。我的改动是：
def get_replace_path(self, true_path):
        """
        对目录路径进行转换
        """
        if self.tv_save_containerpath and true_path.startswith(self.tv_save_path):
            true_path = true_path.replace(str(self.tv_save_path), str(self.tv_save_containerpath)).replace("\\\\", "/")
        if self.movie_save_containerpath and true_path.startswith(self.movie_save_path):
            true_path = true_path.replace(str(self.movie_save_path), str(self.movie_save_containerpath)).replace("\\\\", "/")
        if self.anime_save_containerpath and true_path.startswith(self.anime_save_path):
            true_path = true_path.replace(str(self.anime_save_path), str(self.anime_save_containerpath)).replace("\\\\", "/")
        return true_path

**Comment by jxxghp** [comment]
1.没有遇到过，要看日志
3.现在不是有手动识别和自定义识别吗
4.欢迎pr
