### ISSUE TITLE
张卫国的夏天 添加RSS订阅失败：张卫国的夏天 (2022) 获取剧集数失败，请确认该季是否存在！

### ISSUE THREAD

**Issue by toxufe** [jxxghp/nas-tools#573]
张卫国的夏天 添加RSS订阅失败：张卫国的夏天 (2022) 获取剧集数失败，请确认该季是否存在！
![111](https://user-images.githubusercontent.com/7663543/180964287-a962d895-d2c8-4551-b2c6-bafa7f86736f.jpg)

芒果tv 没有总集数，这种的不能订阅。
估计跟芒果源没有总集数有关系。

**Comment by jxxghp** [comment]
tmdb的数据问题，被人维护了很多空的季，手动加订阅选择第一季可以加成功。
群里有讨论过的。

**Comment by jxxghp** [comment]
改了下代码，兼容这种情况了。
