### ISSUE TITLE
关于超长番剧名称的搜索适配

### ISSUE THREAD

**Issue by link2fun** [jxxghp/nas-tools#574]
示例: 
番剧名字: `金装的维尔梅～濒临留级的魔法师联手最强灾厄勇闯魔法世界～`
各站资源发布名字:  `金装的维尔梅`

现状:
通过系统功能搜索 金装的维尔梅 会 自动带出 `金装的维尔梅～濒临留级的魔法师联手最强灾厄勇闯魔法世界～` 进行搜索, 导致搜不到资源

期望:
增加搜索关键字(别名), 允许使用别名进行资源订阅搜索

**Comment by jxxghp** [comment]
改tmdb词条

**Comment by link2fun** [comment]
> 改tmdb词条

python 新手, 如果我增加这个别名填写和搜索的功能, 会被合并么?
