### ISSUE TITLE
功能建议：希望在识别环节增加黑名单功能

### ISSUE THREAD

**Issue by firstvip** [jxxghp/nas-tools#578]
有些下载的文件或视频不想被识别，建议增加黑名单功能。

**Comment by link2fun** [comment]
> 有些下载的文件或视频不想被识别，建议增加黑名单功能。

那就别放到扫描目录里面

**Comment by firstvip** [comment]
比如我把aria2的completed目录加入了同步目录，方便下载了电影自动识别转移。但是偶尔下载回来AV他也会识别转移，所以想有没有可能有个黑名单，因为下载的AV都是有规律的命名的。

**Comment by link2fun** [comment]
> 比如我把aria2的completed目录加入了同步目录，方便下载了电影自动识别转移。但是偶尔下载回来AV他也会识别转移，所以想有没有可能有个黑名单，因为下载的AV都是有规律的命名的。

可以监控子目录的
建议开两个下载机, 放一个下载机不会尴尬么
