### ISSUE TITLE
可能存在的几个bug

### ISSUE THREAD

**Issue by sungamma** [jxxghp/nas-tools#58]
这段时间的更新，程序的可用性大大提升，稳定性也提升了很多。非常感谢大佬的付出。但是在使用过程中还是发现几个疑似的bug，具体如下：
### 关于转移识别的bug

1. 目录监控遇到不能识别的媒体文件，手动调整后识别并硬连接到相对应的目录后，但该媒体仍然在未分类目录下存在。手动删除后，再次运行目录监控，依旧会对该部分文件再次识别，但仍然是识别不了，进而又硬连接了一份到未分类目录。
2. 默认的分类方式里面的备注写在“如果有配置动漫独立目录，则实际上不会使用到tv下的动漫二级分类”，但目前的实际情况是，在把动漫识别到电视剧后，手动修改为动漫，直接硬连接到电视剧目录的动漫分支（此时是单独设立了动漫分支）
具体情况见下图
![7c14aa832cf131ddf40580619f18815](https://user-images.githubusercontent.com/33790/164888200-ec51d056-93e4-41af-a74f-a311bc9f253a.jpg)
![96c1e4b4bc20b732904686f5f9dbeee](https://user-images.githubusercontent.com/33790/164888208-43e975fb-8ace-4952-9d1d-badf23189aa0.jpg)

我觉得应该是识别过的或者转移过的都应该记录到文件内。这样可以避免重复工作

### 关于微信远程下载过滤问题
搜索了疯狂的赛车，两个PT站都能搜到，但是却提出了不符合过滤条件。采用的是默认的过滤条件:接受 4k|2160p|1080p. 日志见下图
![773fae58f40670684387f1675e22d7f](https://user-images.githubusercontent.com/33790/164888234-b9ead197-1789-4b4e-934c-e9c2f4c81ccd.jpg)

**Comment by jxxghp** [comment]
第3点是否有设置排除条件？几项规则都贴一下。

**Comment by sungamma** [comment]
prowlarr:
  # 【Prowlarr地址】
  host: http://127.0.0.1:9696
  # 【Prowlarr ApiKey】：Prowlarr设置页面获取API Key
  api_key: '63e14346a7af6'
  # 【资源过滤条件】：进行PT资源聚合检索时，符合以下条件的资源才会命中返回，对大小写不敏感，不配置则为不过滤
  res_type:
    # 【必须包含的关键字】：只有种子名称中包括这些关键字才会命中，配置为空为不启用该条件
    # 可以是普通的字符串，也可以是正则表达式，可以配置多行，多行之间是【与】的关系，即多行条件都包含时才会命中；单行内可以用'|'来表示【或】，即包括其一即命中
    # 比如如下默认配置表示下载WEB-DL类型的4K或者1080P的资源
    include:
      - '4k|2160p|1080p'
      - 'web-dl'
    # 【不能包含的关键字】：种子名称中如果有这些关键字则会被跳过，配置为空为不启用该条件
    # 可以是普通的字符串，也可以是正则表达式，可以配置多行，多行之间是【与】的关系，即多行条件都不包含时才会跳过；单行内可以用'|'来表示【或】，即包括其一即跳过
    # 如下默认配置表示跳过蓝光原盘类型的资源
    exclude:
      - 'Blu-?ray.*AVC|REMUX|UHD.*Blu-?ray.*HEVC'

**Comment by jxxghp** [comment]
> prowlarr:
>   # 【Prowlarr地址】
>   host: http://127.0.0.1:9696
>   # 【Prowlarr ApiKey】：Prowlarr设置页面获取API Key
>   api_key: '63e14346a7af6'
>   # 【资源过滤条件】：进行PT资源聚合检索时，符合以下条件的资源才会命中返回，对大小写不敏感，不配置则为不过滤
>   res_type:
>     # 【必须包含的关键字】：只有种子名称中包括这些关键字才会命中，配置为空为不启用该条件
>     # 可以是普通的字符串，也可以是正则表达式，可以配置多行，多行之间是【与】的关系，即多行条件都包含时才会命中；单行内可以用'|'来表示【或】，即包括其一即命中
>     # 比如如下默认配置表示下载WEB-DL类型的4K或者1080P的资源
>     include:
>       - '4k|2160p|1080p'
>       - 'web-dl'
>     # 【不能包含的关键字】：种子名称中如果有这些关键字则会被跳过，配置为空为不启用该条件
>     # 可以是普通的字符串，也可以是正则表达式，可以配置多行，多行之间是【与】的关系，即多行条件都不包含时才会跳过；单行内可以用'|'来表示【或】，即包括其一即跳过
>     # 如下默认配置表示跳过蓝光原盘类型的资源
>     exclude:
>       - 'Blu-?ray.*AVC|REMUX|UHD.*Blu-?ray.*HEVC'

第3点应该没问题，有的是因为分辨率，有的是因为你的排除选项。

**Comment by jxxghp** [comment]
在把动漫识别到电视剧后，手动修改为动漫---这个问题没太理解，现在动漫不会识别到电视剧吧，提供下名称

**Comment by sungamma** [comment]
死亡笔记 death note，之前识别到日韩剧内，我手动调整为动漫后，直接转移到电视剧根目录下。还有个汪汪队立大功第6季识别到欧美剧内，手动调整后，放到了电视剧/动漫 目录下。

**Comment by sungamma** [comment]
还有个问题，为啥从我的qb里面拉取数据，我这几个文件没有放在转移目录内。是新增特性吗？有开关吗
![IMG_20220423_190134_585](https://user-images.githubusercontent.com/33790/164891835-db5954cb-d6e7-48ef-bbcb-bc1de363bd0e.png)

**Comment by jxxghp** [comment]
> 还有个问题，为啥从我的qb里面拉取数据，我这几个文件没有放在转移目录内。是新增特性吗？有开关吗
> ![IMG_20220423_190134_585](https://user-images.githubusercontent.com/33790/164891835-db5954cb-d6e7-48ef-bbcb-bc1de363bd0e.png)

下载软件监控有单独的开关。

**Comment by jxxghp** [comment]
> 死亡笔记 death note，之前识别到日韩剧内，我手动调整为动漫后，直接转移到电视剧根目录下。还有个汪汪队立大功第6季识别到欧美剧内，手动调整后，放到了电视剧/动漫 目录下。

你要看下什么时候移的，动漫分类的中间变过好几次。

**Comment by sungamma** [comment]
> > 还有个问题，为啥从我的qb里面拉取数据，我这几个文件没有放在转移目录内。是新增特性吗？有开关吗
> > ![IMG_20220423_190134_585](https://user-images.githubusercontent.com/33790/164891835-db5954cb-d6e7-48ef-bbcb-bc1de363bd0e.png)
> 
> 下载软件监控有单独的开关。

我想起来了，可能是我在微信里面点击了。这个微信里面的菜单好像是程序定死了，感觉不太好删除这个功能

**Comment by sungamma** [comment]
> > 死亡笔记 death note，之前识别到日韩剧内，我手动调整为动漫后，直接转移到电视剧根目录下。还有个汪汪队立大功第6季识别到欧美剧内，手动调整后，放到了电视剧/动漫 目录下。
> 
> 你要看下什么时候移的，动漫分类的中间变过好几次。

519版本吧，昨夜更新的

**Comment by jxxghp** [comment]
手动识别分类的问题己有另一个issue
