### ISSUE TITLE
调用api.themovie.org时报Max retries exceeded with url问题

### ISSUE THREAD

**Issue by lixingchensuperx** [jxxghp/nas-tools#582]
作者您好，我在配置nastools时遇到了调用api.themovie.org时报Max retries exceeded with url问题，具体信息如下：

版本：V1.9.14
前提：已按照[矿神的方法](https://imnks.com/369.html)改好hosts文件
报错信息：

`15:14:39 INFO - 【RMT】开始处理：/PT/下载库/电影/光年正传.mkv
15:16:15 ERROR - 【META】连接TMDB出错：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/search/multi?api_key=人工马赛克&query=%E6%96%AD%E7%89%87%E4%B9%8B%E9%99%A9%E9%80%94%E5%A4%BA%E5%AE%9D&language=zh-CN (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb3bfe0ed10>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))
15:16:15 WARN - 【RMT】断片之险途夺宝.mp4 无法识别媒体信息！
15:16:15 ERROR - 【RMT】断片之险途夺宝.mp4 无法识别媒体信息！
15:16:15 INFO - 【RMT】/PT/下载库/电影/断片之险途夺宝.mp4 处理完成，总数：1，失败：1
15:16:15 INFO - 【MSG】发送wechat消息：title=/PT/下载库/电影/断片之险途夺宝.mp4 有 1 个文件转移失败，请登录NASTool查看, text=
15:16:15 ERROR - 【MSG】发送消息失败：参数未配置或配置不正确
15:16:15 ERROR - 【SYNC】/PT/下载库/电影 处理失败：无法识别媒体信息
15:16:15 INFO - 【RMT】开始处理：/PT/下载库/电影/光年正传.mkv
15:16:46 ERROR - 【META】连接TMDB出错：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/search/movie?api_key=人工马赛克&query=%E5%85%89%E5%B9%B4%E6%AD%A3%E4%BC%A0&language=zh-CN (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb3c098d8a0>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))
15:16:46 INFO - 【META】光年正传 以年份 在TMDB中未找到电影信息!
15:18:23 ERROR - 【META】连接TMDB出错：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/search/movie?api_key=人工马赛克&query=%E5%85%89%E5%B9%B4%E6%AD%A3%E4%BC%A0&language=zh-CN (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb3c098d540>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))
15:18:23 INFO - 【META】光年正传 以年份 在TMDB中未找到电影信息!`

希望予以解答，十分感谢！

**Comment by jxxghp** [comment]
就是连不上的意思

**Comment by lixingchensuperx** [comment]
我查了部分资料，貌似是最大尝试连接数导致的，请问nastools中哪里可以设置呢？

这种问题要如何解决呢？辛苦作者大大解答，谢谢！ @jxxghp

**Comment by BlueSkyClouds** [comment]
设置代理

**Comment by lixingchensuperx** [comment]
曲线救国了😂，之前我只更改了nas本地的hosts，没有更改docker中镜像的hosts

换成套件版的问题解决
