### ISSUE TITLE
docker每次启动自动更新都失败

### ISSUE THREAD

**Issue by gudumuyu** [jxxghp/nas-tools#585]
docker版每次重启后，都会自动更新，但是每次都失败，而且更新的时候连接性很差，大大延长了重启时间，晚上更新可能要十几分钟分钟，最后还是提示失败。

能否增加一个环境变量，比如auto_update = true/false，来自己选择是否自动更新呢？平常用watchtower更新镜像更方便也更快。

谢谢

**Comment by gudumuyu** [comment]
![image](https://user-images.githubusercontent.com/32303402/181403824-00328c57-bca2-4b33-bf8f-2c978915e9d8.png)

**Comment by jxxghp** [comment]
已经有了啊

**Comment by gudumuyu** [comment]
找到了，是我看的不仔细，不好意思！
