### ISSUE TITLE
添加下载失败 身份认证失败次数过多，您的 IP 地址已被封禁

### ISSUE THREAD

**Issue by woshijie120** [jxxghp/nas-tools#586]
之前环境一切正常，今天中午发现RSS搜索到了资源，但是添加下载失败，才关注到这个问题。
后面手动添加也不行，请问下该如何处理？这个封禁好像是工具内部的，因为我访问PT站点一切正常。
![image](https://user-images.githubusercontent.com/108522192/181427583-3d215b1b-9c92-4550-8d5b-13aea5dab74a.png)
前台也有提示，换了电影也一样
![image](https://user-images.githubusercontent.com/108522192/181427641-3d96c975-b3e1-4a12-8aad-3937620ce845.png)

**Comment by woshijie120** [comment]
调整了qb下载器的设置后，已经不报这个错误了，但是依然添加下载失败，从nastool的日志中看不出来原因
![image](https://user-images.githubusercontent.com/108522192/181430837-ca716134-0b35-406c-b2db-a028995881fc.png)
在配置界面测试下载，提示测试失败，但是实际qb下载器可以正常访问
![image](https://user-images.githubusercontent.com/108522192/181431204-e3e2a313-ff64-4284-97b3-8e14f530087a.png)
![image](https://user-images.githubusercontent.com/108522192/181431250-4ae34998-ff88-41b7-94ec-79b532a88fd8.png)
也怀疑过是IP对应的问题，尝试了检索器的测试，一切正常
![image](https://user-images.githubusercontent.com/108522192/181431402-94513d0b-9c66-4f75-83fb-7579186475a3.png)

**Comment by link2fun** [comment]
QB测试不通过, 你IP应该是被QB封了, 重启QB试一下,也可以去QB WEB 设置下
路径: `选项 -> WEB UI -> 验证`
```txt
连续失败后禁止客户端：	5
禁止：	3600秒
```

**Comment by woshijie120** [comment]
> QB测试不通过, 你IP应该是被QB封了, 重启QB试一下,也可以去QB WEB 设置下 路径: `选项 -> WEB UI -> 验证`
> 
> ```
> 连续失败后禁止客户端：	5
> 禁止：	3600秒
> ```

已经尝试更改设置，把连续失败后禁止访问改为10，禁止时间改为60秒，依然报错。。。
![image](https://user-images.githubusercontent.com/108522192/181452180-1380719e-3f34-4d6b-82cd-ef74ad76bf7f.png)

**Comment by woshijie120** [comment]
错误从nastool端看，依然为空

**Comment by woshijie120** [comment]
查看qb日志解决

**Comment by 18702540384** [comment]
请问怎么解决的

**Comment by codesensi** [comment]
> 查看qb日志解决

请问是怎么解决的呢？
