### ISSUE TITLE
名称识别的一点小问题

### ISSUE THREAD

**Issue by 26712681** [jxxghp/nas-tools#589]
剧集大白，命名都一样的，第四集不能识别

这是源文件命名方式
![image](https://user-images.githubusercontent.com/77581926/181470667-dc51685e-ea98-4545-a9f5-8cab3fcb4085.png)

这是处理时候的日志
![image](https://user-images.githubusercontent.com/77581926/181470369-03ed8d3b-c81a-4650-974d-6246e27e6c83.png)

这是我的设置开启情况
![image](https://user-images.githubusercontent.com/77581926/181471005-28250409-1e18-414f-b3f9-e59c5ae13a1b.png)

**Comment by jxxghp** [comment]
什么版本？

**Comment by 26712681** [comment]
> 什么版本？

最新版。1.9.14

**Comment by 26712681** [comment]
![image](https://user-images.githubusercontent.com/77581926/181475502-619f90ad-9001-4b8f-8382-060d6c9c11cd.png)
这里好像没问题，老大别管了，我观察观察再说，关了吧

**Comment by jxxghp** [comment]
> ![image](https://user-images.githubusercontent.com/77581926/181475502-619f90ad-9001-4b8f-8382-060d6c9c11cd.png)
> 
> 这里好像没问题，老大别管了，我观察观察再说，关了吧

哈哈😄，好。
