### ISSUE TITLE
jellyfin中有的电影依旧在搜索下载

### ISSUE THREAD

**Issue by sungamma** [jxxghp/nas-tools#59]
这是4-23日下载的疯狂的赛车
![image](https://user-images.githubusercontent.com/33790/164958710-ebf92412-d582-4de5-b600-8aecfb7b65f9.png)
但是4-24日继续微信发送疯狂的赛车，依旧在用PROWLARR搜索下载
日志如下:
`13:51:17 - 配置文件地址：/config/config.yaml
13:51:17 - NASTool 当前版本号：v0.5.22
13:51:17 - 日志输出类型为：file
13:51:17 - 日志将写入文件：/config/logs
13:51:17 INFO - WEB管瑞页面监听端口：3005
13:51:17 INFO - WEB管瑞页面用户：admin
13:51:17 INFO - 未启用https，请使用 http://IP:3005 访问管理页面
13:51:17 INFO - TMDB匹配模式：正常模式
13:51:17 INFO - 媒体管理软件设置为：jellyfin
13:51:17 INFO - 电影分类：华语电影 外语电影
13:51:17 INFO - 电视剧分类：纪录片 儿童 综艺 国产剧 欧美剧 日韩剧 未分类
13:51:17 INFO - 目录监控转移模式为：硬链接
13:51:17 INFO - PT下载软件设置为：qbittorrent
13:51:17 INFO - PT下载文件转移模式为：硬链接
13:51:17 INFO - PT检索软件设置为：prowlarr
13:51:17 INFO - 微信等移动端渠道搜索已开启自动择优下载
13:51:17 INFO - pt_seeding_time未配置，自动删种功能已关闭
13:51:17 INFO - pt_monitor未配置，PT下载监控功能已关闭
13:51:17 - 开始启动进程...
13:51:18 INFO - 【SYNC】读取到监控目录：/volume1/movie/QB
13:51:18 INFO - 【RUN】/volume1/movie/QB 的monitor.media_sync启动...
13:51:18 INFO - 【RUN】scheduler.rss_download启动...
13:51:18 INFO - 【RUN】scheduler.douban_sync启动...
13:52:04 INFO - 消息内容：疯狂的赛车
13:52:04 INFO - 【SEARCHER】正在识别 疯狂的赛车 的媒体信息...
13:52:05 INFO - 类型：电影，标题：疯狂的赛车，年份：2009
13:52:06 INFO - 【SEARCHER】开始检索 疯狂的赛车 ...
13:52:14 WARN - 【PROWLARR】返回数据：21
13:52:15 INFO - 【PROWLARR】Crazy Racer 2009 1080p CHN Blu-ray AVC DTS-HD MA 5.1-TAiCHi 不符合过滤条件
13:52:15 INFO - 【META】正在检索电影：Silver Medallist, 年份=2009 ...
13:52:17 WARN - 【META】Silver Medallist 未找到媒体信息!
13:52:17 INFO - 【META】正在检索电视剧：Silver Medallist, 年份=2009 ...
13:52:19 WARN - 【META】Silver Medallist 未找到媒体信息!
13:52:19 INFO - 【META】正在检索电视剧：Silver Medallist, 年份= ...
13:52:20 WARN - 【META】Silver Medallist 未找到媒体信息!
13:52:20 INFO - 【META】正在检索电影：Silver Medallist, 年份= ...
13:52:21 WARN - 【META】Silver Medallist 未找到媒体信息!
13:52:21 INFO - 【PROWLARR】Silver.Medallist.2009.HDTV.1080p.H264.AAC2.0-HDCTV 未检索到媒体信息
13:52:21 INFO - 【PROWLARR】CCTV6HD.Silver.Medalist.2009.720p.HDTV.x264-HDWTV 不符合过滤条件
13:52:23 INFO - 【PROWLARR】Guns.and.Roses.2012.1080p.BluRay.x264-WiKi 类型不匹配
13:52:25 INFO - 【PROWLARR】Crazy Racer 2009 BluRay REMUX 1080p AVC DTS-HD MA 5.1-LHD 不符合过滤条件
13:52:26 INFO - 【PROWLARR】Crazy Racer 2009 BluRay Remux 1080p AVC DTS-HD MA5 1-Dream 不符合过滤条件
13:52:26 INFO - 【PROWLARR】Crazy Racer 2009 SUBBED COMPLETE BLURAY h264 DTS-REGRET 不符合过滤条件
13:52:27 INFO - 【PROWLARR】Crazy Racer 2009 HDTV 1080i H264 AC3-CHDTV 不符合过滤条件
13:52:29 INFO - 【PROWLARR】Silver Medalist 2009 720p BluRay x264 DTS-WiKi 不符合过滤条件
13:52:30 INFO - 【PROWLARR】Silver Medalist 2009 Blu-ray REMUX 1080p AVC DTS-HD MA 5.1-CHD 不符合过滤条件
13:52:31 INFO - 【PROWLARR】Guns and Roses 2012.1080p BluRay x264-WiKi 类型不匹配
13:52:31 INFO - 【PROWLARR】Crazy Racer 2009 HDTV iPad 720p x264 AAC-NYPAD 不符合过滤条件
13:52:31 INFO - 【PROWLARR】CHC Silver Medalist 2009 720p HDTV x264-NGB 不符合过滤条件
13:52:31 INFO - 【PROWLARR】CHC Silver Medalist 2009 HDTV 1080i MPEG2-MTeamTV 不符合过滤条件
13:52:31 INFO - 【PROWLARR】共检索到 7 条有效资源
13:52:33 INFO - 【PT】添加PT任务：Silver Medalist 2009 1080p BluRay DTS x265 10bit-HDS ...
13:52:33 INFO - 【PT】添加PT任务：http://127.0.0.1:9696/3/download?apikey=xxxxx&link=xxxxx&file=Silver+Medalist+2009+1080p+BluRay+DTS+x265+10bit-HDS
13:52:33 INFO - 【MSG】发送wechat消息：title=疯狂的赛车 (2009) 评分：7.2, text=微信搜索的电影 疯狂的赛车 (2009) 已开始下载 站点：M-Team - TP 质量：BluRay 1080p 大小：6.44G 种子：Silver Medalist 2009 1080p BluRay DTS x265 10bit-HDS 描述：https://xxxx.cc/details.php?id=xxxx&hit=1
13:52:33 INFO - 【SEARCHER】实际下载了 1 个资源`
当然由于QB还在做种这个疯狂的赛车，实际上是没有新增下载。
按理说应该根据jellyfin里面的资源情况，再决定是否下载，但是实际上没有。

**Comment by sungamma** [comment]
今天又测试了下：
NAS-TOOL正常连接jellyfin
![image](https://user-images.githubusercontent.com/33790/165079183-70cdf05c-36c7-4151-b586-2e247caed120.png)
jellyfin有阿甘正传
![image](https://user-images.githubusercontent.com/33790/165079088-0d53e26c-80f5-4c4e-9396-c6f4c660cef6.png)
但是搜索阿甘正传，又重新下载了
![image](https://user-images.githubusercontent.com/33790/165079129-df7dcc98-6a36-4967-be0a-f0aebeb8ea29.png)

**Comment by jxxghp** [comment]
jellyfin api适配可能存在问题。目前emby比较完善。

**Comment by jxxghp** [comment]
v0.6.04已完成适配。媒体库刷新jellyfin的api用不了。
