### ISSUE TITLE
高级搜索下载的电影识别成电视剧

### ISSUE THREAD

**Issue by junskycool** [jxxghp/nas-tools#590]
![S20728-19130003](https://user-images.githubusercontent.com/93479084/181493745-2296e460-c62b-4d31-b35c-2d8cc9cd9648.png)
![S20728-19130866](https://user-images.githubusercontent.com/93479084/181493778-c47df509-722f-49e3-b53d-55ca3698382f.png)
直接给下到电视剧文件夹了  手动在tr更改了路径  还是能转移到电影的

**Comment by jxxghp** [comment]
后面那些数字是什么东西？

**Comment by junskycool** [comment]
> 后面那些数字是什么东西？

这我也不知道   种子页面是没有的
![S20728-19553281](https://user-images.githubusercontent.com/93479084/181499178-8b88ed0d-a664-421d-a96e-a70e54b62b46.png)
![Uploading S20728-19554591.png…]()

**Comment by junskycool** [comment]
别的站好像没有这情况。。。

**Comment by jxxghp** [comment]
> 别的站好像没有这情况。。。

就是那些数字影响了，看下是什么，为什么有。我没这个站分析不了。

**Comment by junskycool** [comment]
> > 别的站好像没有这情况。。。
> 
> 就是那些数字影响了，看下是什么，为什么有。我没这个站分析不了。
这个站我高级搜索的电视剧又识别成电影
![S20728-20114284](https://user-images.githubusercontent.com/93479084/181502131-4b7eb61a-f084-4fd0-8d5d-c052cd43a316.png)
![S20728-20122929](https://user-images.githubusercontent.com/93479084/181502182-d8c6631f-5288-43ff-b75b-2fc3453046be.png)

**Comment by junskycool** [comment]
![S20728-20311694(1)](https://user-images.githubusercontent.com/93479084/181506072-a4639326-e6bb-46eb-89bc-8566b7684af8.png)
看来高级搜索识别有点难😄

**Comment by jxxghp** [comment]
高级搜索是没有跟TMDB匹配识别的，完全依赖于种子信息的正确性，种子命名不规范就识别不了了。。。
