### ISSUE TITLE
目录同步能否排除part后缀

### ISSUE THREAD

**Issue by MichaelthA** [jxxghp/nas-tools#592]
13:44:07 INFO - 【SYNC】开始同步 /volume1/PT/xxxx.mp4.part
13:44:07 INFO - 【SYNC】/volume1/PT/xxxx.mp4.part 同步完成
13:44:07 INFO - 【SYNC】开始同步 /volume1/PT/XXX.mp4.part
13:44:07 INFO - 【SYNC】/volume1/PT/XXX.mp4.part 同步完成

**Comment by MichaelthA** [comment]
![1659073676307](https://user-images.githubusercontent.com/34961908/181691338-8766fd5e-c043-477d-a2c7-fc97dec79f15.png)

**Comment by jxxghp** [comment]
.part是什么软件产生的？  关闭了目录同步的识别开关？

**Comment by MichaelthA** [comment]
> .part是什么软件产生的？关闭了目录同步的识别开关？

part是tr下载器产生的，nastool链接的是qb，我两个下载器负责不同的站，关闭了识别开关

**Comment by jxxghp** [comment]
打开识别只会处理特定后缀，你关了就是全量同步。

**Comment by MichaelthA** [comment]
> 打开识别只会处理特定后缀，你关了就是全量同步。

如果不需要重命名是怎么处理？
