### ISSUE TITLE
自定义二级分类策略后，部分电影国区值匹配不上的问题

### ISSUE THREAD

**Issue by mirrorhui520** [jxxghp/nas-tools#594]
#### 首先，这是我目前使用的二级分类策略配置文件：
```
# 分类依据，可以是：original_language 语种、origin_country 国家或地区、genre_ids 内容类型等，只要TMDB API返回的字段中有就行
# 配置多项条件时，需要同时满足；不需要的匹配项可以删掉或者配置为空
# 匹配值对应用,号分隔，这里是匹配语种
# 分类名同时也是目录名，会按先后顺序匹配，匹配后程序会按这个名称建立二级目录
movie:
  # Bangumi电影：动漫电影
  Bangumi电影:
    genre_ids: '16'
  韩国:
    origin_country: 'KP,KR'
  欧美:
    origin_country: 'US,FR,GB,DE,ES,IT,NL,PT,RU,UK'
  日本:
    origin_country: 'JP'
  中国:
    origin_country: 'CN,TW,HK,MO'
  儿童电影:
    genre_ids: '10762'
  #未匹配以上分类，则命名为未分类
  未分类电影:

tv:
  儿童节目:
    genre_ids: '10762'
  综艺节目:
    genre_ids: '10764,10767'
  大陆剧:
    origin_country: 'CN,TW'
  港剧:
    origin_country: 'HK'
  韩剧:
    origin_country: 'KP,KR'
  欧美剧:
    origin_country: 'US,FR,GB,DE,ES,IT,NL,PT,RU,UK'
  日剧:
    origin_country: 'JP'
  # 未匹配以上分类，则命名为未分类
  未分类电视剧:

anime:
  Bangumi:
    genre_ids: '16'
```

#### 目前发现的两部电影识别正常，但无法正确匹配国区值进行正确的二级分类：
- 1.[神探](https://www.themoviedb.org/movie/14016) (2007)
  - 种子文件名称：[BTSCHOOL].神探.Mad.Detective.2007.BDRip.1080p.x265.10bit.DDP7.1.2Audio-DGB.torrent
  - 使用TMDB的API返回的值中也带有"origin_country":"HK"的```{"adult":false,"backdrop_path":"/hQQYobrobIgnT6trUV0E3ofdBEY.jpg","belongs_to_collection":null,"budget":0,"genres":[{"id":28,"name":"Action"},{"id":80,"name":"Crime"},{"id":53,"name":"Thriller"}],"homepage":"","id":14016,"imdb_id":"tt0969269","original_language":"zh","original_title":"神探","overview":"","popularity":9.843,"poster_path":"/2ECQCUJ2Fq8fwkjtakVGxXEOuXP.jpg","production_companies":[{"id":5632,"logo_path":"/hJlG4OouIf7KXuP2M7Y1bGGZPni.png","name":"Milkyway Image Company","origin_country":"HK"}],"production_countries":[{"iso_3166_1":"HK","name":"Hong Kong"}],"release_date":"2007-11-29","revenue":0,"runtime":91,"spoken_languages":[{"english_name":"Cantonese","iso_639_1":"cn","name":"广州话 / 廣州話"}],"status":"Released","tagline":"","title":"神探","video":false,"vote_average":6.975,"vote_count":140}```

  - 但从NASTOOL服务中的名称识别测试获得结果是归类到“未分类电影”中
  **（实际下载完毕目录同步后也的确硬链到了未分类电影文件夹中）**：  
![image](https://user-images.githubusercontent.com/55034021/181771990-f67e1de4-f08d-438f-a71c-c506647f9e0c.png)

- 2.[犯罪都市](https://www.themoviedb.org/movie/479718) (2017)
  - 种子文件名称：[BTSCHOOL].犯罪都市.The.Outlaws.2017.BluRay.Remux.1080p.AVC.DTS-HD.MA5.1-BTSCHOOL.torrent
  - 使用TMDB的API返回的值中也带有"origin_country":"KR"的```{"adult":false,"backdrop_path":"/67eKM9rkCOZmNVrsgXVKiCvJh1.jpg","belongs_to_collection":{"id":619802,"name":"범죄도시 시리즈","poster_path":"/sycF6WvwIt25BKkWTQRjWpplBhv.jpg","backdrop_path":"/ra2aSkkwOQRoymeg5p19PfnC9r9.jpg"},"budget":5883687,"genres":[{"id":28,"name":"Action"},{"id":80,"name":"Crime"}],"homepage":"","id":479718,"imdb_id":"tt7468056","original_language":"ko","original_title":"범죄도시","overview":"","popularity":53.474,"poster_path":"/A5MIbqxuQfQRtzGxg5UUTAxHfsM.jpg","production_companies":[{"id":81594,"logo_path":null,"name":"Michigan Venture Capital","origin_country":"KR"},{"id":84678,"logo_path":"/8pjrX8L669kQUdCqCCpv3uWOSBC.png","name":"BA Entertainment","origin_country":"KR"},{"id":88607,"logo_path":null,"name":"Union Investment Partners","origin_country":"KR"},{"id":91505,"logo_path":"/6ILCuHFX5QVtXuesPlywHXZIGt1.png","name":"Megabox Plus M","origin_country":"KR"},{"id":96989,"logo_path":null,"name":"Hong Film","origin_country":"KR"},{"id":114520,"logo_path":null,"name":"Kiwi Media Group","origin_country":"KR"},{"id":129217,"logo_path":null,"name":"Big Punch Pictures","origin_country":"KR"}],"production_countries":[{"iso_3166_1":"KR","name":"South Korea"}],"release_date":"2017-10-03","revenue":52946454,"runtime":121,"spoken_languages":[{"english_name":"Korean","iso_639_1":"ko","name":"한국어/조선말"}],"status":"Released","tagline":"","title":"범죄도시","video":false,"vote_average":7.769,"vote_count":195}```

  - 但从NASTOOL服务中的名称识别测试获得结果是归类到“未分类电影”中
  **（实际下载完毕目录同步后也的确硬链到了未分类电影文件夹中）**：
![image](https://user-images.githubusercontent.com/55034021/181774945-0529aa96-a10a-4c58-80ee-5bada6ad478a.png)

- [x] 尝试过关闭“辅助识别”和“使用豆瓣名称联想”，结果一样。
- [x] 由于我的媒体库下包含各类二级分类文件夹以及未分类文件夹，最终也可通过直接剪切过去正确分类文件夹中的方式解决。
- [ ] 但出于好奇所以折腾了一下，同时也并不清楚是否因为我自定义的配置文件写法问题导致匹配出错。
- [x] 通过在二级分类策略配置文件每个使用origin_country:来匹配的分类中加入original_language:来进行匹配，分类识别显示正确，只是，为什么使用国区匹配会匹配不上呢？电视剧和动漫却没发现有分类出错的问题。

**Comment by jxxghp** [comment]
production_companies 下面的并没有使用，使用的是第一级下面的origin_country。

**Comment by mirrorhui520** [comment]
> production_companies 下面的并没有使用，使用的是第一级下面的 origin_country。

啊。。。所以是TMDB那获取的返回值问题咯？它production_companies前面第一级的里面好多都没包含origin_country。不过还是感谢解惑，我全部origin_country的值换成original_language之后就解决了。暂时。。。
