### ISSUE TITLE
订阅后检索返回值存在bug

### ISSUE THREAD

**Issue by dnpl** [jxxghp/nas-tools#595]
更新到最新版后1.9.15后，尝试订阅了一下电视剧《少年派2》，在 JACKETT配置了相应的站点，返回值里有12条结果。最后日志均报告“JACKETT】电视剧：少年派 不匹配名称：['少年派2']”，怀疑是把搜索出的结果标题后的2给去掉了，导致出现“少年派 不匹配名称：['少年派2']”，”
日志截图如下
![jackett站点搜索结果](https://user-images.githubusercontent.com/22452022/181841131-d332b744-0022-42d6-9e64-2688ccb6029e.png)
网站手动检索（检索关键词“少年派2”）结果（数量也是12）为：
![网站检索结果](https://user-images.githubusercontent.com/22452022/181841324-931a11d6-ac07-4f7d-93b3-7fc7f022c6b6.png)。

**Comment by spring19000** [comment]
可以改订阅成，少年派  2022 第2季  这样就可以自动下载了！

**Comment by jxxghp** [comment]
tmdb词条问题
