### ISSUE TITLE
【bug】资源搜索中找到的电影，再“搜索”。提示：失败，查询不到媒体信息，请确认名称是否正确！

### ISSUE THREAD

**Issue by yixiar** [jxxghp/nas-tools#596]
环境：
一、安装正常。
二、配置了“基础配置”中的“TMDB API Key”。
三、host文件增加了api.themoviedb.org的解析。
其他说明：
一、“推荐”栏目中的包含”TMDB“的都打不开，而包含“豆瓣”的都没有问题。
二、从豆瓣中选的电影，也是搜索失败。
三、在“资源搜索”栏目中，可以搜索电影名，但是每个电影名下面的“搜索”失败。
四、在点击“服务”栏目中的“目录同步”后，从“实时日志”中可以看到：
09:23:37 INFO - 【RMT】开始处理：/media/ori/Zootopia 2016 1080p HDRip x264 AC3-JYK
09:23:37 ERROR - 【RMT】检索媒体信息出错！
09:23:37 ERROR - 【SYNC】/media/ori 处理失败：检索媒体信息出错

**Comment by yixiar** [comment]
真是奇怪的现象：
一、ssh到nas上，ping api.themoviedb.org是通的。
二、拿到nas-tools的日志，即：
15:01:27 ERROR - 【META】连接TMDB出错：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/search/movie?api_key=01ae81beb37a&query=%E9%80%9F%E5%BA%A6%E4%B8%8E%E6%BF%80%E6%83%859&year=2021&language=zh-CN (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fce39c64f40>, 'Connection to api.themoviedb.org timed out. (connect timeout=None)'))
拼上开头:https://api.themoviedb.org。形成完整的url：
https://api.themoviedb.org/3/search/movie?api_key=01ae81beb37a&query=%E9%80%9F%E5%BA%A6%E4%B8%8E%E6%BF%80%E6%83%859&year=2021&language=zh-CN 
是能正常返回内容的！
综上：网络是通的，nas-tools拼的也是对的。但是，两者加在一起就不行了！？？
几天了，一直这样！！！
奇怪！！！
求高人指点！

**Comment by jxxghp** [comment]
你的电脑能访问跟容器能不能访问是两码事
