### ISSUE TITLE
疑问搜索使用的站点优先级是否可调？

### ISSUE THREAD

**Issue by xyswordzoro** [jxxghp/nas-tools#598]
优先级好像是根据jackett的站点顺序来的，很多资源都是从观众站audiences下载的，这的顺序在jackett好像是调不了的，按照字母顺序来的，能否也像订阅那样加个优先级，不知道我理解的有没有错，谢谢

**Comment by jxxghp** [comment]
索引器配置链接的顺序前面的优先级高。
基础设置中改为站点优先。
