### ISSUE TITLE
希望添加有独立开始按钮的可手动更改路径的目录同步

### ISSUE THREAD

**Issue by yjb136698605** [jxxghp/nas-tools#599]
应用场景:
下载动漫剧集原盘的时候存在一些特典内容或者命名不规范的情况,无法有效识别到,且识别的可能较为混乱,我想手动稍微整理一下
出现的问题:
我先用ln硬连命令,但无法硬链文件夹,然后安装了hlink,但硬链文件夹报错,不知出现了什么问题,最后我采用重新添加同步目录,关闭其他目录的同步开关,单独进行不重名的目录同步操作,较为繁琐,且我在完成上述操作之后,重新打开其他目录的开始同步功能后,自动同步功能报错,需重启nastools套件
此功能可在服务中添加,可以调用同步功能代码,应该可以实现(我猜的 h~h~h),希望大佬可以看看!  感谢!

**Comment by jxxghp** [comment]
自定义识别
