### ISSUE TITLE
安裝時顯示config.ini 不存在

### ISSUE THREAD

**Issue by brucetangian** [jxxghp/nas-tools#6]
【RUN】配置文件地址：/config/config.ini
【RUN】配置文件不存在！

使用Qnap 安裝docker後顯示config.ini 不存在 ，是不能用嗎？

**Comment by jxxghp** [comment]
1、你的镜像要拉下最新的，不能跟教程对不上。
2、你要根据代码中的模板，自己编辑好配置文件放到/config目录下，并挂载到容器内。

**Comment by brucetangian** [comment]
已解決，謝謝你
