### ISSUE TITLE
页面切换的回调函数延时过长

### ISSUE THREAD

**Issue by kuusei** [jxxghp/nas-tools#60]
在 [web/templates/navigation.html](https://github.com/jxxghp/nas-tools/blob/4c12ddece63a1fa094a4be9204bbcfb6faac41dc/web/templates/navigation.html) 298行
``` js
  $("#page_content").load(page, {}, function(response,status,xhr){
    setTimeout("hide_process()", 500);
  });
```
jq在load结束之后才会回调这个匿名函数, 因此没有设置延时的必要

目前表现为, 加载完成后还会转0.5秒的圈

**Comment by jxxghp** [comment]
已改，下个版本commit
