### ISSUE TITLE
关于站点管理建议

### ISSUE THREAD

**Issue by nicholastz** [jxxghp/nas-tools#600]
由于订阅的RSS与刷流RSS不同，每次功能【RSS订阅】执行都会连同刷流的RSS一并刷新，这样经常导致rss短时间访问次数过多造成的屏蔽，能否增加此设定：**添加站点时可勾选是否参与RSS订阅**

**Comment by jxxghp** [comment]
订阅不是可以选站点吗

**Comment by nicholastz** [comment]
订阅是可以选择，但每一个订阅都需要筛选
