### ISSUE TITLE
请问有使用教程么？

### ISSUE THREAD

**Issue by liucheng1109** [jxxghp/nas-tools#601]
请问有使用教程么？

**Comment by yixiar** [comment]
网上有一些。不多。基本上就是二个版本。
而且，跟着做，有很大的可能是无法使用。
这么好的东西，却没有详细操作手册。让大多数小白，都不能口口相传。可惜了。

如果我搞通了，一定会出一个教程，把最关键的几点说清楚。让大家都用上。
