### ISSUE TITLE
名称自动解析识别还可以再改进

### ISSUE THREAD

**Issue by yixiar** [jxxghp/nas-tools#603]
![image](https://user-images.githubusercontent.com/61567159/182006365-44c69dac-0908-4e37-a8bf-a0a51221a47e.png)

其中：1984和841不知道是什么意思。这可是去年的新电影。

**Comment by junskycool** [comment]
> ![image](https://user-images.githubusercontent.com/61567159/182006365-44c69dac-0908-4e37-a8bf-a0a51221a47e.png)
> 
> 其中：1984和841不知道是什么意思。这可是去年的新电影。

你标题里面没有年份    沙丘有2个
![S20731-15455591](https://user-images.githubusercontent.com/93479084/182015598-aa54d32c-20b8-4e7a-9a76-aa49f6a1b72c.png)

**Comment by jxxghp** [comment]
无语😓
