### ISSUE TITLE
【bug】基本设置是硬链接，实际是复制一份文件

### ISSUE THREAD

**Issue by yixiar** [jxxghp/nas-tools#605]
![image](https://user-images.githubusercontent.com/61567159/182029697-44099b55-fbe5-45f4-856e-f8856997e9ac.png)

![image](https://user-images.githubusercontent.com/61567159/182029725-11813f29-10a7-4dc3-b903-1b58571ea7d5.png)

明明是“硬链接”，却是复制了一份实体文件！？

**Comment by log-time** [comment]
所以，硬链接该是什么样子的呢？

**Comment by jxxghp** [comment]
无语。。。

**Comment by yixiar** [comment]
> 所以，硬链接该是什么样子的呢？

硬链接应该是建立“链接”，不是复制啊？

不是有三个选项：硬链接、软连接和复制，吗？

如果硬链接是复制，那么和“复制”有什么区别呢？

**Comment by yixiar** [comment]
> 无语。。。

曾经是硬链接的，不知道怎么变成现状的样子了。


下图是是以前的：
![image](https://user-images.githubusercontent.com/61567159/182086033-e311df0c-6c01-4128-ab20-6d717c356d23.png)

现在的是真实的文件。

**Comment by log-time** [comment]
怎么看出来是复制了呢？你的硬盘剩余空间有变化吗？你理解的“建立链接”又是什么样子的呢？你的硬盘可以秒复制几个G的内容吗？你google过什么叫硬链接吗？

**Comment by yixiar** [comment]
> 怎么看出来是复制了呢？你的硬盘剩余空间有变化吗？你理解的“建立链接”又是什么样子的呢？你的硬盘可以秒复制几个G的内容吗？你google过什么叫硬链接吗？

是占空间的。可以看图标不一样。实际上，看属性也是不一样的。

这个是以前的硬链接：
![image](https://user-images.githubusercontent.com/61567159/182109819-b97b071c-fd6a-4b61-985f-0e5067fb868f.png)

这个是现在的拷贝电影文件
![image](https://user-images.githubusercontent.com/61567159/182110094-e65b0ef4-211f-473e-b82a-c57c195013a3.png)

**Comment by log-time** [comment]
先搞明白软链接和硬链接的区别吧。你前几天的是不是自己设置成软链接，你可以试一下。软件没问题
[硬链接与软链接的区别]（https://sowhatbigfatloser.com/hard-link-and-symbolic-link/）
