### ISSUE TITLE
订阅某个影视剧的时候，可以添加多个过滤字符串过滤下载来源 比如“某某字幕组” “中日双语” 之类的

### ISSUE THREAD

**Issue by appotry** [jxxghp/nas-tools#607]
如上 
订阅某个影视剧的时候，可以添加多个过滤字符串过滤下载来源 比如“某某字幕组” “中日双语” 之类的 

如此来下载特定版本的影视剧来源

**Comment by appotry** [comment]
最好支持 逗号，空格之类的分隔符分割多个过滤字符串

**Comment by jxxghp** [comment]
过滤规则了解一下

**Comment by appotry** [comment]
@jxxghp 有没有详细点教程说明一下过滤规则怎么用？

**Comment by appotry** [comment]
@jxxghp 另外，这个过滤放到点击订阅某个影视剧的页面体验更好，属于专用过滤

过滤规则分为通用过滤和某个影视的专用过滤
