### ISSUE TITLE
新版本出现一次重复检索

### ISSUE THREAD

**Issue by YikLiu93** [jxxghp/nas-tools#609]
![微信图片_20220801204707](https://user-images.githubusercontent.com/105213026/182151094-1b78caa6-00ac-41c6-92c2-7c80825e717c.jpg)
添加新的电视剧，检索了两次，下载了两个不同的站点的电视剧。

**Comment by YikLiu93** [comment]
时间上大概隔了四分钟左右

**Comment by nicholastz** [comment]
一样， 我今天不停的重复检索

**Comment by jxxghp** [comment]
> 一样， 我今天不停的重复检索

检索跟订阅是两码事儿，你是微信发消息重复检索吧，这个一般是网络问题收到了消息但是回复不了微信服务端，导致对方一直在重试
