### ISSUE TITLE
动漫自动识别和手动识别目录不一致

### ISSUE THREAD

**Issue by JimyZhang** [jxxghp/nas-tools#61]
不确定是配置问题还是疑似bug
目录同步识别的都在/volume1/video/nastools/动漫/动漫 目录下
手动识别的在/volume1/video/nastools/动漫 目录下
配置如下：
![image](https://user-images.githubusercontent.com/39080199/164982561-18626150-e095-49cb-b3b9-79027e6349a9.png)

![image](https://user-images.githubusercontent.com/39080199/164982660-a1a84dc2-c505-4ad8-9caf-72d4d9f5d20b.png)
![image](https://user-images.githubusercontent.com/39080199/164982700-08836b2f-4a30-404a-9ccb-9599b073706e.png)

**Comment by jxxghp** [comment]
手动识别选的是动漫还有电视剧？默认的分类配套文件动漫下还有一层动漫分类，配置动漫媒体库目录时要配置到上级目录。

**Comment by JimyZhang** [comment]
选的动漫，理解你的意思了。分类配套文件动漫下确实还有一层动漫分类，那我配置的时候媒体库的动漫路径应该是：/volume1/video/nastools，但我理解的是手动识别的时候动漫应该会转移到/volume1/video/nastools目录下吧。

**Comment by jxxghp** [comment]
已找到原因，下个版本更新
