### ISSUE TITLE
TMDB集数正常，订阅后下载几集直接删除订阅

### ISSUE THREAD

**Issue by spring19000** [jxxghp/nas-tools#610]
6:22:07 INFO - 【RSS】共有 1 个电视剧订阅需要检索
16:22:07 INFO - 【DOWNLOADER】被遗忘的时光 (2022) 第1季 共有 34 集
16:22:08 INFO - 【DOWNLOADER】被遗忘的时光 (2022) 第1季 缺失 34 集
16:22:08 INFO - 【SEARCHER】开始检索 被遗忘的时光 ...
16:22:08 INFO - 【JACKETT】开始并行检索 被遗忘的时光，线程数：7 ...
16:22:08 INFO - 【JACKETT】开始检索Indexer：pterclub ...
16:22:08 INFO - 【JACKETT】开始检索Indexer：lemonhd ...
16:22:08 INFO - 【JACKETT】开始检索Indexer：mteamtp ...
16:22:08 INFO - 【JACKETT】开始检索Indexer：hdsky ...
16:22:08 INFO - 【JACKETT】开始检索Indexer：ourbits ...
16:22:08 INFO - 【JACKETT】开始检索Indexer：pthome ...
16:22:08 INFO - 【JACKETT】开始检索Indexer：soulvoice ...
16:22:12 WARN - 【JACKETT】ourbits 未检索到数据
16:22:12 WARN - 【JACKETT】mteamtp 未检索到数据
16:22:12 WARN - 【JACKETT】lemonhd 返回数据：1016:22:18 INFO - 【MSG】发送wechat消息：title=被遗忘的时光 (2022) S01, text=RSS订阅的电视剧 被遗忘的时光 (2022)S01 已开始下载 站点：lemonhd 质量：WEB-DL 2160p 大小：14.3G 种子：Time Seems to Have Forgotten 2022 S01 2160p WEB-DL H264 AAC-LeagueWEB 做种数：19 促销：普通 描述：Time Seems to Have Forgotten 2022 S01 2160p WEB-DL H264 AAC-LeagueWEB
16:22:18 INFO - 【SEARCHER】实际下载了 1 个资源
16:22:18 INFO - 【RSS】电视剧 被遗忘的时光 下载完成，删除订阅...
TMDB:
[Season 1](https://www.themoviedb.org/tv/207108/season/1)
2022 | 34 集
《被遗忘的时光》第 1 季于 2022 年 07 月 29 日首播。
订阅下了几集就直接删除订阅，TMDB集是34集，这是咋回事啊？

**Comment by jxxghp** [comment]
Time Seems to Have Forgotten 2022 S01 2160p WEB-DL H264 AAC-LeagueWEB

这个命名里面没有集数，种子副标题是否有集数？

**Comment by lizhen789** [comment]
我的都不下载，这正常嘛

**Comment by spring19000** [comment]
正常了，TMDB重新做词条要过段时间NASTOOL才能相应，然后就可以搞了，之前的词条是1集！
