### ISSUE TITLE
【建议】手动识别增加支持豆瓣识别的功能

### ISSUE THREAD

**Issue by yixiar** [jxxghp/nas-tools#614]
自动识别只能识别themoviesdb的数据，手动识别，也只能支持tmdb的数据。
但是tmdb的数据不全。特别大陆发行的内容。
我下载是通过Nas-tools的搜索下载的，但是识别不了。怎么也识别不了。
![image](https://user-images.githubusercontent.com/61567159/182520057-6c2ae967-51bd-41d0-bd41-fd50067f8c90.png)

手动识别，也只能是找tmdb。但是tmdb里确实没有，好像豆瓣里有。
建议手动识别中增加豆瓣的介绍。自动能增加豆瓣就更好了。

**Comment by lizhen789** [comment]
最好添加不要填写id的，还有就是既然已经填写了id了，那干嘛还要填写什么名称，年份信息呢

**Comment by jxxghp** [comment]
> 最好添加不要填写id的，还有就是既然已经填写了id了，那干嘛还要填写什么名称，年份信息呢

认真研究了吗？

**Comment by lizhen789** [comment]
看到了，你新版本已经改了

**Comment by yixiar** [comment]
> 看到了，你新版本已经改了

改了吗？
好像还是要输入tmdb的id
