### ISSUE TITLE
第二次运行“不识别仅同步”无法生成硬链文件

### ISSUE THREAD

**Issue by yangruiqq** [jxxghp/nas-tools#619]
NAS系统：unRAID 6.10.3
NASTool版本：1.9.16
出现的BUG：全新安装的NT容器，第一次“不识别仅同步”生成硬链没有任何问题，但是删除生成好的硬链文件后重新“不识别仅同步”就不会有任何硬链文件生成。
![QQ截图20220804224143](https://user-images.githubusercontent.com/33513240/182877158-6093dd17-0a72-4471-a937-887509f63978.png)
![QQ截图20220804224405](https://user-images.githubusercontent.com/33513240/182877166-0c76ce01-6947-4607-8deb-3af700bb97c7.png)

**Comment by jxxghp** [comment]
服务->清空文件缓存

**Comment by yangruiqq** [comment]
尝试过，并不成功

发自我的iPhone
