### ISSUE TITLE
希望可以增加刮削imdb信息

### ISSUE THREAD

**Issue by Monkiq** [jxxghp/nas-tools#620]
目前是只有tmdb信息,而chinesesubfinder字幕下载大部分是通过imdb信息查找字幕,tmdb大部分会导致找不到字幕

**Comment by log-time** [comment]
![IMG_20220805_084610](https://user-images.githubusercontent.com/66826612/182978523-76aca94b-bc38-4997-bc13-ca1f3557b4c6.jpg)
