### ISSUE TITLE
订阅电视剧有bug

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#621]
[日志.txt](https://github.com/jxxghp/nas-tools/files/9265899/default.txt)
这是订阅的完美世界，匹配出很多集但是最后一直下载第65集，不会下载其他的。

也订阅其他的电视剧，订阅集数有时候有问题，比如只下载了30集但是订阅显示已订阅32集这种，无法下载31和32两集，需要删除重新订阅才正常

**Comment by jxxghp** [comment]
这个是命名问题，[完美世界][Perfect World][2021][WEB-DL][1080][TV Series][TV 65][LeagueWEB] 无法识别集数。

[完美世界][Perfect World][2021][WEB-DL][1080][TV Series][65][LeagueWEB] 才能识别，使用名字在服务那里测试下就知道了。
