### ISSUE TITLE
TTG站点的RSS订阅无法获取数据

### ISSUE THREAD

**Issue by rockhia** [jxxghp/nas-tools#622]
<img width="131" alt="mmexport1659683359474" src="https://user-images.githubusercontent.com/90016652/183022014-eb59f206-1185-4e2a-a416-329384d20002.png">

**Comment by jxxghp** [comment]
没有类似问题

**Comment by rockhia** [comment]
生成的链接选择uTorrent 自动下载RSS链接才能正常运行

**Comment by rockhia** [comment]
uTorrent 自动下载RSS链接
需要选择第一个
