### ISSUE TITLE
希望能在硬链接环节单独在配置文件添加映射规则

### ISSUE THREAD

**Issue by edwardostara** [jxxghp/nas-tools#63]
背景如下：
我们经常有已经存在的本地资源，在运行转移时，
nastools在硬链接自动重命名时候，把动漫识别成同名电影了。

建议如下：
可否在硬链接时候在配置文件单独添加映射规则，比如我下载到或者存在于ptanime文件夹下的资源都是动漫，pttv下的文件都是电视剧，这样，脚本首先要做的是把资源硬链接到对应目录，然后根据这个分类在tmdb搜索并重命名。

总之：
现有的逻辑是，通过搜索关键字在tmdb找到电影，再通过该电影在tmdb的信息获取分类、标签等，用以决定下面的环节的硬链接目标目录的分类整理等。是从上而下。

提出的建议是，通过附加硬链接规则，直接锁定该目录下资源的大分类，然后提取标题，再在tmdb进行搜索，再在之前逻辑下进行一系列操作，以避免同名不同型的识别错误。
不知提议是否可行？如蒙回复，不胜感激！

**Comment by jxxghp** [comment]
不是最优方案
