### ISSUE TITLE
硬链接功能完善

### ISSUE THREAD

**Issue by FLIER001** [jxxghp/nas-tools#636]
功能诉求：
- 建议增加“源文件删除，同步删除硬链接文件”功能

使用场景：
- 删除源文件，但硬链接文件不会删除，导致占用大量磁盘空间，手动删除需要重复操作，费时费力

实现方式：
- 设置中作为可选功能
- 手动点击

类似功能参考：
- hlink，prune命令
  - prune命令功能：https://hlink.likun.me/command/prune.html
  - 为什么会有prune命令？：https://hlink.likun.me/other/prune.html

**Comment by jxxghp** [comment]
不太理解，不是应该媒种库才是中心吗？哪些电影我要看要保留、哪些要删除应该是以媒体库为中心借助emby等软件来管理吧。

做种的只是我要上传量的附属品而已，为什么要删做种为中心来同步删媒体库的东西，我们的终极目的不是观影吗？

**Comment by xxzj990** [comment]
我理解有部分人的需求是还没看的要保种和媒体库都留着，看完保种和媒体库都删掉，不长期留着。是这样吧 @FLIER001

**Comment by FLIER001** [comment]
> 不太理解，不是应该媒种库才是中心吗？哪些电影我要看要保留、哪些要删除应该是以媒体库为中心借助emby等软件来管理吧。
> 
> 做种的只是我要上传量的附属品而已，为什么要删做种为中心来同步删媒体库的东西，我们的终极目的不是观影吗？

类似于三楼的理解，媒体库对部分人来说，只是一个呈现工具，最终文件的管理还是落在了对于做种的管理上，即该影片的留存与否取决于是否删除做种（保种党），具体可能有以下几种情况：
- 这部电影不好看/不符合胃口，删除做种同时希望删除媒体库
- 该种子发布了V2版本，需要删除V1版本，同时媒体库也需要同步更新
- 更换更高质量的资源，可能是相同分辨率不同压制小组，也需要手动操作，无法自动化实现

**Comment by xxzj990** [comment]
群里有个命令如下：

> 下面的命令可以把硬连接数只有1的视频文件删除（根据自己需要增加修改或删除后缀）：
> find . -mindepth 1 \( -iname "*.mkv" -o -iname "*.mp4" -o -iname "*.iso" -o -iname "*.ts" -o -iname "*.mpg" \) | while read file; do if [[ $(stat -c %h "$file") -eq 1 ]]; then rm -v "$file"; fi; done

是不是定期执行这个命令也可以实现这样的功能？

**Comment by xxzj990** [comment]
如果想先预览一下，可以用这个：

> find . -mindepth 1 \( -iname "*.mkv" -o -iname "*.mp4" -o -iname "*.iso" -o -iname "*.ts" -o -iname "*.mpg" \) | while read file; do if [[ $(stat -c %h "$file") -eq 1 ]]; then echo "$file"; fi; done

**Comment by jxxghp** [comment]
跟工具的初衷不符，不打算支持

**Comment by FLIER001** [comment]
> 如果想先预览一下，可以用这个：
> 
> > find . -mindepth 1 ( -iname "_.mkv" -o -iname "_.mp4" -o -iname "_.iso" -o -iname "_.ts" -o -iname "*.mpg" ) | while read file; do if [[ $(stat -c %h "$file") -eq 1 ]]; then echo "$file"; fi; done

谢谢！

**Comment by FLIER001** [comment]
> 群里有个命令如下：
> 
> > 下面的命令可以把硬连接数只有1的视频文件删除（根据自己需要增加修改或删除后缀）：
> > find . -mindepth 1 ( -iname "_.mkv" -o -iname "_.mp4" -o -iname "_.iso" -o -iname "_.ts" -o -iname "*.mpg" ) | while read file; do if [[ $(stat -c %h "$file") -eq 1 ]]; then rm -v "$file"; fi; done
> 
> 是不是定期执行这个命令也可以实现这样的功能？
> 
> 在群晖或者unraid里面加一个定期执行的脚本，把这个命令填上

我不知道使用此命令的安全性如何，经过本地测试，结论是不太可行。将其中的`-mindepth 1`替换成`-links 1`能得到更精确的结果，但也存在问题，如果该目录下存在本身就没有进行硬链的文件，也会一并删除。

我的解决办法就是结合使用hlink的prune命令。

再次感谢！

**Comment by FLIER001** [comment]
> > 如果想先预览一下，可以用这个：
> > > find . -mindepth 1 ( -iname "_.mkv" -o -iname "_.mp4" -o -iname "_.iso" -o -iname "_.ts" -o -iname "*.mpg" ) | while read file; do if [[ $(stat -c %h "$file") -eq 1 ]]; then echo "$file"; fi; done
> 
> 谢谢！

anyway，感谢作者提供这么好用的工具。

**Comment by FLIER001** [comment]
> 跟工具的初衷不符，不打算支持

anyway，感谢作者提供这么好用的工具，再次表达我的谢意。

**Comment by xxzj990** [comment]
> 

嗯，最新的hlink有网页端了，可以起定时任务，挺方便的

**Comment by sjtuross** [comment]
我也是把PT下载的原始文件作为中心，不管是否继续做种与否，理由就是这是原始文件

媒体库为了满足刮削需求，必定要修改目录名文件名，将来有可能不满意想重来，我可以基于原始文件重构媒体库

希望作者可以考虑同步删除硬链接的需求

**Comment by 188334911** [comment]
> 功能诉求：
> 
> * 建议增加“源文件删除，同步删除硬链接文件”功能
> 
> 使用场景：
> 
> * 删除源文件，但硬链接文件不会删除，导致占用大量磁盘空间，手动删除需要重复操作，费时费力
> 
> 实现方式：
> 
> * 设置中作为可选功能
> * 手动点击
> 
> 类似功能参考：
> 
> * hlink，prune命令
>   
>   * prune命令功能：https://hlink.likun.me/command/prune.html
>   * 为什么会有prune命令？：https://hlink.likun.me/other/prune.html

老哥，现在最新版本的你用着正常吗 ，刚用NPM装了hlink，设置好源目录和目的目录，可以正常的创建硬链接，但是我在模拟硬链接删除后自动删除原文件时，始终无法删除，


> > 
> 
> 嗯，最新的hlink有网页端了，可以起定时任务，挺方便的

老哥，现在最新版本的你用着正常吗 ，刚用NPM装了hlink，设置好源目录和目的目录，可以正常的创建硬链接，但是我在模拟硬链接删除后自动删除原文件时，始终无法删除，
能不能麻烦你贴下你的关于反向检测硬链接不存在后，自动删除源文件的配置文件？

**Comment by FLIER001** [comment]
> > 功能诉求：
> > 
> > * 建议增加“源文件删除，同步删除硬链接文件”功能
> > 
> > 使用场景：
> > 
> > * 删除源文件，但硬链接文件不会删除，导致占用大量磁盘空间，手动删除需要重复操作，费时费力
> > 
> > 实现方式：
> > 
> > * 设置中作为可选功能
> > * 手动点击
> > 
> > 类似功能参考：
> > 
> > * hlink，prune命令
> >   
> >   * prune命令功能：https://hlink.likun.me/command/prune.html
> >   * 为什么会有prune命令？：https://hlink.likun.me/other/prune.html
> 
> 老哥，现在最新版本的你用着正常吗 ，刚用NPM装了hlink，设置好源目录和目的目录，可以正常的创建硬链接，但是我在模拟硬链接删除后自动删除原文件时，始终无法删除，
> 
> > > 
> > 
> > 
> > 嗯，最新的hlink有网页端了，可以起定时任务，挺方便的
> 
> 老哥，现在最新版本的你用着正常吗 ，刚用NPM装了hlink，设置好源目录和目的目录，可以正常的创建硬链接，但是我在模拟硬链接删除后自动删除原文件时，始终无法删除， 能不能麻烦你贴下你的关于反向检测硬链接不存在后，自动删除源文件的配置文件？

旧版和新版都能够正常使用，NAS送修了，新版暂时无法截图，贴上旧版的代码：
`hlink prune  -e svg,png,nfo,jpg,txt,text,mp3,xml,srt,csf-bk,ass,ssa "源文件路径" "硬链接文件路径"`
