### ISSUE TITLE
希望添加手动指定下载目录功能

### ISSUE THREAD

**Issue by icycandy** [jxxghp/nas-tools#639]
**现状：**
1. 在`设置`->`下载器`中设置了qbittorrent的下载目录
![3](https://user-images.githubusercontent.com/724257/183416394-3befc200-55a5-46a0-9bc6-a48654588efc.png)
2. 在`资源搜索`中，点击搜索结果的海报，会弹出是否开始下载
![2](https://user-images.githubusercontent.com/724257/183416826-660ed762-9972-40fa-bc41-fad97860126e.png)

我理解这里的逻辑是会自动判断电视剧还是电影，然后下载到设置好的目录中去。

**希望的功能：**
可否在点击海报时，弹出下载目录供选择呢，这样可以自定义下载目录。比如同样是剧集，我希望把**原文件**整理到`电视剧`、`综艺`、`纪录片`等不同的目录中去。

浏览器插件PT Plugin Plus的这个功能，用得很顺手，希望nas tools也能有。
![4](https://user-images.githubusercontent.com/724257/183418023-79291dbe-c2e6-450f-8e6c-674f929726b8.png)

**Comment by icycandy** [comment]
为什么要划分成`电视剧`、`综艺`、`纪录片`等不同的子目录呢，原因有二：

一是管理更方便，在emby等界面上可以分成不同的页面来展示

二是不得不这样做，一块盘存不下所有的剧集，只能分成不同的盘来存储

**Comment by jxxghp** [comment]
我只是想做自动化工具，要手动强大，有很多其他的工具可以用。

**Comment by jxxghp** [comment]
工具的初衷就是自动化，目前已支持手工下载时选择下载器和目录同步中的目录（同步目录映射路径需要与下载器使用的下载目录一致）。
下载器目前不打算自定义添加目录，目录很多就没法自动化了。
