### ISSUE TITLE
https://dmhy.org/

### ISSUE THREAD

**Issue by unyielding2013** [jxxghp/nas-tools#641]
dmhy.org是公开pt平台，网页能搜索资源，但nastools不能搜索任何资源。

**Comment by jxxghp** [comment]
贴个日志？

**Comment by neodevx233** [comment]
话说能不能把 蜜柑计划 那个订阅功能做成模块 直接解决动漫下载那堆问题？

**Comment by unyielding2013** [comment]
> 贴个日志？

2:34:30 INFO - 【WEB】开始检索 斗罗大陆 ...
22:34:30 INFO - 【JACKETT】开始检索 斗罗大陆，站点：dmhy ...
22:34:30 INFO - 【JACKETT】开始检索Indexer：dmhy ...
22:34:34 WARN - 【JACKETT】dmhy 返回数据：80
22:34:34 INFO - 【JACKETT】 无法识别到名称
22:34:34 INFO - 【JACKETT】 无法识别到名称
22:34:34 INFO - 【JACKETT】 无法识别到名称
