### ISSUE TITLE
刷流套套哥连不上tracker

### ISSUE THREAD

**Issue by sungamma** [jxxghp/nas-tools#643]
QB 4.3.9
这是刷流自动添加的
![image](https://user-images.githubusercontent.com/33790/183535191-1f598045-b7ed-47d1-b3f0-7e0a14cecb79.png)
手动上传的TTG种子可以正常下载
![image](https://user-images.githubusercontent.com/33790/183535266-61bd1a27-0bc7-46fc-80de-36e35809929a.png)

**Comment by jxxghp** [comment]
跟工具没关系

**Comment by sungamma** [comment]
是RSS下载的种子有问题么？在哪可以找到nas-tools下载的种子呢。QB里面的BT_BACKUP里面没有这些种子
