### ISSUE TITLE
出现sql错误了

### ISSUE THREAD

**Issue by lizhen789** [jxxghp/nas-tools#644]
![image](https://user-images.githubusercontent.com/35031472/183551340-10eaf742-2ae3-4b0e-a4e5-4d6e4d98cc01.png)

**Comment by lizhen789** [comment]
这个重启过后正常了

**Comment by lizhen789** [comment]
又锁了。。。

**Comment by jxxghp** [comment]
什么版本？

**Comment by lizhen789** [comment]
v1.9.18

**Comment by jxxghp** [comment]
这个问题我已为搞定了，竟然还有。。。
