### ISSUE TITLE
没有配置的目录也被扫描了

### ISSUE THREAD

**Issue by lizhen789** [jxxghp/nas-tools#645]
![image](https://user-images.githubusercontent.com/35031472/183555718-eefbe83a-989a-46a6-a112-23ebed416132.png)
![image](https://user-images.githubusercontent.com/35031472/183555741-2c0cb28d-89ec-4d12-8622-95cafbf7bc16.png)

**Comment by jxxghp** [comment]
开了下载软件监控？
这类基础功能N久都没改，不会有大Bug的，自己先研究清楚 。
