### ISSUE TITLE
历史界面的媒体信息类型显示异常

### ISSUE THREAD

**Issue by kuusei** [jxxghp/nas-tools#65]
在窗口/屏幕比较小的情况下, 类型的宽度会被压缩,类似下图第二行
![image](https://user-images.githubusercontent.com/46283738/165274195-73ec59d6-2a75-43d2-9b48-b22a7c6191ec.png)

建议给分类标签加个 flex-shrink: 0; 效果类似上图第一行

此外三个字的标签会顶格在边缘上
![image](https://user-images.githubusercontent.com/46283738/165274830-667b2033-76ac-4a75-a0ae-aa68d4c72f7c.png)
建议略微缩放文字字体

**Comment by jxxghp** [comment]
我直接换成了图标下个版本更新

**Comment by kuusei** [comment]
![image](https://user-images.githubusercontent.com/46283738/165656110-5b743e77-2dfb-4ed1-9d8c-5d1864c26230.png)
换成图标后还是会被压的, 建议还是把  flex-shrink: 0; 加上吧
