### ISSUE TITLE
无法打开豆瓣推荐，豆瓣电影推荐，动漫推荐和综艺推荐都打不开

### ISSUE THREAD

**Issue by Mirecle** [jxxghp/nas-tools#650]
1、如题，无法打开豆瓣推荐，包括豆瓣电影推荐，动漫推荐和综艺推荐等（但是themoviedb没有问题，tmdb推荐可以正常打开）
2、一旦开启豆瓣联想，搜索功能就会失效
3、ping api.douban.com 可以ping通

截图如下：
![微信图片_20220810005350](https://user-images.githubusercontent.com/32609935/183711361-503aadcc-a163-4c45-9a04-d936418f006d.png)

日志如下：
[log.txt](https://github.com/jxxghp/nas-tools/files/9293073/log.txt)

**Comment by Mirecle** [comment]
连接科学工具，可以正常文件转移了，但是豆瓣推荐还是打不开，多次重新安装均无法解决问题

**Comment by jxxghp** [comment]
你的容器环境被你弄的只能访问外站不能访问国内网点了吧，这个是环境问题，自己研究下吧。
豆辨API的地址：https://frodo.douban.com/api/v2

**Comment by Mirecle** [comment]
您好，感谢回复，但我没有挂任何代理，只是修改了api.themoviedb.org的hosts，docker使用hosts模式

**Comment by Mirecle** [comment]
![微信截图_20220810122005](https://user-images.githubusercontent.com/32609935/183815038-6b01ff6c-a7fb-450f-9976-b2c3d9eeed02.png)
可以ping通豆瓣api

**Comment by jxxghp** [comment]
> ![微信截图_20220810122005](https://user-images.githubusercontent.com/32609935/183815038-6b01ff6c-a7fb-450f-9976-b2c3d9eeed02.png) 可以ping通豆瓣api

要在容器内ping呀

**Comment by Mirecle** [comment]
感谢已解决，在容器中修改豆瓣api对应的host ip即可解决
