### ISSUE TITLE
transmission标签问题

### ISSUE THREAD

**Issue by Joker-Ya** [jxxghp/nas-tools#652]
Docker版本nastools，套件版transmissiin

通过微信查找影片下载，虽然会返回下载错误信息，但是查看transmission，任务已经成功添加

![Screenshot_20220810_103408_com tencent mm](https://user-images.githubusercontent.com/58095839/183797705-c5e0cb16-1155-4760-9eb4-3559df2ec7dd.png)

【DOWNLOADER】添加下载任务出错：Method "torrent-set" Argument "labels" does not exist in version 15.

在下载器，transmission设置里不能添加标签
![Screenshot_20220810_101416_mark via gp_edit_251638494410560](https://user-images.githubusercontent.com/58095839/183796630-5c1ebcd0-ea9e-491e-bd29-8b4f667f18e9.jpg)

我想使用远程下载不完整自动添加订阅功能来自动订阅追剧

![Screenshot_20220810_101438_mark via gp](https://user-images.githubusercontent.com/58095839/183796708-60c3191a-8251-47f0-af25-ee3df67f9dfc.png)

由于这个错误，通过微信指令查找，并且已经添加任务成功资源，也会出现在订阅列表，导致已下载成功资源依然会被订阅

能否优化一下，如果使用的下载器是transmission，就不使用标签功能，能返回正确的添加任务成功信息，防止重复订阅

**Comment by jxxghp** [comment]
给任务加标签是基础功能，无法屏蔽，TR升级到3.0即可，日志里也有提示的。
