### ISSUE TITLE
【bug】tmdb无法识别问题

### ISSUE THREAD

**Issue by yixiar** [jxxghp/nas-tools#657]
在左侧“媒体管理”的“手动识别”栏目中，
下载了“猫和老鼠”系列集一。如下图：
![image](https://user-images.githubusercontent.com/61567159/183884052-90d25f59-ebbe-4662-893d-be8ee1f123e4.png)

这个应该是大陆发行的一套dvd光碟。tmdb中没有收录，豆瓣上有收录。
https://movie.douban.com/subject/4321270/

这个当然没法自动识别，但是也没法手动识别！？

**Comment by jxxghp** [comment]
TMDB都没有，去哪里找信息手动识别？
