### ISSUE TITLE
能否增加个刷流的规则？

### ISSUE THREAD

**Issue by spring19000** [jxxghp/nas-tools#661]
刷流的任务，有时RSS到种子时该种子剩余时间短或者发布时间比较长，不利于抢点上传，有时还会吃到50%下载量。能搞个规则，超过多少小时的种子就不下载了，或者说只下载发布时间短的种子！还有我堡，刷流不起作用！

**Comment by jxxghp** [comment]
这个检测比较困难，而且一般都是几分钟刷新种，还可以限制下载时间，一般没这问题。

**Comment by spring19000** [comment]
不是19分钟刷流频率，我设置的25分钟。盘满了，清理盘后，重新刷流，有的种子23小时FREE时间，然后等你拉的时候还有10来小时，有的种子10多小时都下不完，像岛下载进度50%就记录HR，这种情况就尴尬了，本来刷流搞点上传，结果被反薅羊毛了！这样情况再刚开始RSS排除规则里能否设置排除，还有删种规则里能添加个下载量低于多少同时时间超15小时就删种的选项吗？

**Comment by rockhia** [comment]
配合autoremove-torrent使用。有HR的用Nas-tool不好刷流，占用空间太大。手动分类，然后用上面这个docker定时删种。
这个docker满足你上述的条件，需要自己配置
