### ISSUE TITLE
目录同步失败

### ISSUE THREAD

**Issue by orzcz** [jxxghp/nas-tools#665]
`23:33:54 INFO - 【RMT】开始处理：/Download/movies/Heat.1995.REMASTERED.Blu-ray.1080p.DTS-HD.MA.5.1.x265.10bit-HDH
23:33:54 ERROR - 【RMT】文件转移时发生错误：'- ,edition,' - Traceback (most recent call last): File "/nas-tools/rmt/filetransfer.py", line 535, in transfer_media dir_exist_flag, ret_dir_path, file_exist_flag, ret_file_path = self.__is_media_exists(dist_path, media) File "/nas-tools/rmt/filetransfer.py", line 735, in __is_media_exists dir_name, file_name = self.get_moive_dest_path(media) File "/nas-tools/rmt/filetransfer.py", line 1011, in get_moive_dest_path dir_name = re.sub(r"[-_\s.]*None", "", self.__movie_dir_rmt_format.format(**format_dict)) KeyError: '- ,edition,'
23:33:54 INFO - 【RMT】/Download/movies/Heat.1995.REMASTERED.Blu-ray.1080p.DTS-HD.MA.5.1.x265.10bit-HDH 处理完成，总数：1，失败：0`

目录同步失败。

![image](https://user-images.githubusercontent.com/26238769/184172733-dc32105c-09ca-4ab2-b75e-55efabe23eb3.png)

**Comment by jxxghp** [comment]
你自己改了重命名的配置？改成啥样了。

**Comment by orzcz** [comment]
所以这里不需要设置？

**Comment by Dunky-Z** [comment]
> 

我怀疑跟我一样想用TMM的重命名格式 ，${- ,edition,}这个变量在这里应该不识别，改成${edition}吧，其实用默认的设置也挺好的。
