### ISSUE TITLE
订阅剧集后，手动添加种子，硬链接完成会出现不能RSS订阅

### ISSUE THREAD

**Issue by rockhia** [jxxghp/nas-tools#668]
订阅剧集后，手动添加种子并下载到同步目录，进行硬链接后会锁数据库，同时会出现无法正常启动RSS订阅的问题。这个问题重启无效，锁数据库后，没有生成临时文件。
![Screenshot_20220812_075654_edit_183740019937588](https://user-images.githubusercontent.com/90016652/184261705-8323a051-d877-4fca-9632-0fe2fd906371.jpg)

**Comment by rockhia** [comment]
网页重启无效。
docker重启后，RSS订阅恢复正常

**Comment by jxxghp** [comment]
同 #644
