### ISSUE TITLE
动漫缺失集数统计不准确

### ISSUE THREAD

**Issue by smily1223** [jxxghp/nas-tools#670]
![55c20d5ec07b92a5df24f0bf3839866](https://user-images.githubusercontent.com/37728519/184277411-cd5bbfe0-09a8-459b-a1fa-6b6918ef52e5.png)
![bd26a65ea97f405a241988785697450](https://user-images.githubusercontent.com/37728519/184277415-cae13f79-f51c-45f9-b956-0a20bb48bf79.png)
![df7824a055a29c02e9755a2e682b47a](https://user-images.githubusercontent.com/37728519/184277420-35646b0c-3a45-48e6-b84e-dd46e0269ef6.png)
![feab2b6e1516b105aebe874d1084611](https://user-images.githubusercontent.com/37728519/184277673-8d38fae7-edce-4d76-aeee-1aa03b7fa214.png)

总共13集，下了2，3，4，5四集，缺失的是9集才对。缺失的集是能正确检索出来，但是最后更新的显示缺失7集。EMBY用的都是TMDB。

**Comment by jxxghp** [comment]
你看上面的日志，是不是有命中两集，但是下载失败了？

**Comment by smily1223** [comment]
> 你看上面的日志，是不是有命中两集，但是下载失败了？
[新建 文本文档 (3).txt](https://github.com/jxxghp/nas-tools/files/9313986/3.txt)
这个是这段日志，没有下载记录。
而且无论下载成功还是失败都会发微信通知才对，微信并没有通知。
