### ISSUE TITLE
关于电视剧/动漫rss订阅优化的想法

### ISSUE THREAD

**Issue by Shurelol** [jxxghp/nas-tools#672]
一点拙见，见笑

### 理想的订阅情况
* 下载第一集后，之后每一集都下载同一组的资源
* 例如星汉灿烂第一集下载的资源 Love Like the Galaxy S01E01-E04 2022 1080p WEB-DL H265 AAC-ADWeb
* 那么之后每一集都下载 Love Like the Galaxy S01E** 2022 1080p WEB-DL H265 AAC-ADWeb 这样的资源
#### 优点
 * 当整季更新完成后可以辅种打包资源  Love Like the Galaxy S01 2022 1080p WEB-DL H265 AAC-ADWeb
 * 部分站点在整季发布后会删除分集，可以避免做种失效

### 添加电视剧/动漫订阅时
 * 已有资源
   * 首次添加时通过jackett进行所有站点的搜索并显示供选择（因为这时并不知道是否有资源，那个站有，那个组有，无法设置合适的正则筛选）
   ![image](https://user-images.githubusercontent.com/16237201/184350091-abe1219a-3252-4b96-9cb7-614a5663164b.png)
   * 根据个人喜欢的站点/字幕组/发布组选择一个资源，比如Love Like the Galaxy S01E01-E04 2022 1080p WEB-DL H265 AAC-ADWeb
   * 根据选择的结果，提取订阅站点audiences，提取关键字（去掉集数信息）Love Like the Galaxy S01 2022 1080p WEB-DL H265 AAC-ADWeb
   * 结合添加站点时填写的订阅地址，和提取的关键词合成rss订阅链接https://audiences/torrentrss.php?rows=50&exp=90&search=Love%20Like%20the%20Galaxy%20S01%202022%201080p%20WEB-DL%20H265%20AAC-ADWeb&linktype=dl&passkey=***
   * 之后定时运行时，根据首次运行生成的rss订阅链接请求站点更新文章信息
   ![image](https://user-images.githubusercontent.com/16237201/184466080-38da31d4-0be1-411a-ac1b-d0ca31c980cf.png)

* 暂无资源
   *  首次添加时通过jackett进行所有站点的搜索并显示无资源
   *  定时进行jackett搜索（间隔可设置较长）
   *  当jackett搜索出有资源时，通过微信或tg机器人通知，回到已有资源的情况

#### 优点
   * 订阅结果为理性的订阅情况
   * 可以精确命中想要的资源（站点/字幕组/发布组）
   * 该方法的到的资源由于在首次添加时有人为干预，一般命名规范便于识别
   * 操作简便，首次订阅只需
          1. 输入剧集名称
          2. 选择首集资源
   * 无需设置正则筛选等操作
   * 无需本地进行正则匹配，筛选在请求站点时由站点提供，且站点需要提供的文章数也少

**Comment by aaaol** [comment]
我有个不成熟的想法

**Comment by Shurelol** [comment]
> 我有个不成熟的想法 网站：https://mikanani.me/ 手动获取RSS订阅地址 手动查询TMDB进行绑定电视剧/动漫 手动绑定季 这样会稳很多

动漫基本能在一个bt站搞定，电视剧的话可能需要多个pt站，正常利用qb进行订阅，也会先ptpp查询下哪些站点有资源，再去生成rss订阅

**Comment by jxxghp** [comment]
稳定的动漫追番可以用这个：https://github.com/EstrellaXD/Auto_Bangumi

目前订阅已经可以自定义规则和指定站点，通过规则可以只过滤自己想要的发布组或者站点。这个功能其实很强大，先研究明白吧。

**Comment by xxzj990** [comment]
我理解楼主的问题应该不是过滤发布组的问题，而是想订阅一部电视剧后，第一次获取到某个组的资源后，后面的剧集全部从同一站点同一发布组获取。这样后面站点出合集的话可以直接做种，不需要再重新下载缺失部分。

过滤发布组应该无法实现，因为不确定哪个组最先发布资源
