### ISSUE TITLE
添加下载任务出错

### ISSUE THREAD

**Issue by weiyideai520** [jxxghp/nas-tools#674]
下载器：Transmission
WebUI页面测试结果为：测试成功

23:20:35 INFO - 【DOWNLOADER】添加下载任务：http://192.168.199.225:19117/dl/btsow/?jackett_apikey=erfqbaxl7yduqdn4p6r9fn5awu9sok8i&path=Q2ZESjhNVzRDYjM0QlU5RmdiUFlEM2JzZTdYQlRBa1J5Q29Yb3JFUHNSYjJmWWFuaG5LZFh3eE14Szd0TVBnLU9SQUdpV2c2SXVTTXBWaE0ybEtYVXVRdjBwUU96VE80Y3gyU3k2MllBaW1RTjd4UVU5RjF4U0VDbHlPVW5qenBweDhuOE1Fak04Mmd2Zk94TUQzaXdUMkdDY1ZidjdKekxURUxjSXBsNWthVmIyNFktQ1dTTDZZRlI5NDV2eG41Ni1JdUhVbUx2YWZLM0FHcE9tSXpSYUJ4Sjl3&file=%E5%88%BA%E7%8C%AC%E7%B4%A2%E5%B0%BC%E5%85%8B2.2022.HD+1080P.X264.AAC.English.CHS-ENG.BDYS
23:20:36 ERROR - 【DOWNLOADER】添加下载任务出错：Query failed with result "gotMetadataFromURL: http error 404: Not Found".

**Comment by pandarohe** [comment]
出现同样的问题

**Comment by weiyideai520** [comment]
应该是适配问题，将下载器替换成：Qbittorrent，就是下载了
