### ISSUE TITLE
希望能标识出已经下好的电影

### ISSUE THREAD

**Issue by weiyideai520** [jxxghp/nas-tools#675]
前提：已经绑定了Jellyfin服务器，由于之前下载过很多电影。

期望1：能直接显示本地已经存在的电影
期望2：搜索资源，如果存在了的电影需要有标识能标识出来

原因：之前下载和整理好的电影非常多，会忘记这个电影到底有没有下载过，每次下载前，我都需要打开jellyfin检查一下

**Comment by jxxghp** [comment]
你只要配置了媒体服务器，远程发关键字自动下载的时候就会提示你已存在。

**Comment by weiyideai520** [comment]
> 你只要配置了媒体服务器，远程发关键字自动下载的时候就会提示你已存在。

测试了一下，并没有提示我已经存在了。仍旧开启下载。
