### ISSUE TITLE
国漫诛仙不能下载

### ISSUE THREAD

**Issue by unyielding2013** [jxxghp/nas-tools#677]

**Comment by jxxghp** [comment]
最新的程序这些名字都可以正常识别集数，1-4集你都已经有了其中的部分所以才不下载吧。
![image](https://user-images.githubusercontent.com/51039935/184467814-e99357ca-0b7b-432a-af8d-27706f3d8514.png)

**Comment by unyielding2013** [comment]
> 最新的程序这些名字都可以正常识别集数，1-4集你都已经有了其中的部分所以才不下载吧。 ![image](https://user-images.githubusercontent.com/51039935/184467814-e99357ca-0b7b-432a-af8d-27706f3d8514.png)
关键怎么解决，把已下载的删除？
