### ISSUE TITLE
资源搜索不到，但是Jackett里面能检索到

### ISSUE THREAD

**Issue by weiyideai520** [jxxghp/nas-tools#678]
<a href="https://imgloc.com/i/T0jim"><img src="https://s1.328888.xyz/2022/08/13/T0jim.png" alt="T0jim.png" border="0"></a>
<a href="https://imgloc.com/i/T06XE"><img src="https://s1.328888.xyz/2022/08/13/T06XE.png" alt="T06XE.png" border="0"></a>

--------日志----------
12:24:47 INFO - 【WEB】开始检索 雷神4：爱与雷霆 ...
12:24:47 INFO - 【JACKETT】开始并行检索 雷神4：爱与雷霆，线程数：6 ...
12:24:47 INFO - 【JACKETT】开始检索Indexer：torrentgalaxy ...
12:24:47 INFO - 【JACKETT】开始检索Indexer：yts ...
12:24:47 INFO - 【JACKETT】开始检索Indexer：acgrip ...
12:24:47 INFO - 【JACKETT】开始检索Indexer：btsow ...
12:24:47 INFO - 【JACKETT】开始检索Indexer：rarbg ...
12:24:47 INFO - 【JACKETT】开始检索Indexer：eztv ...
12:24:47 WARN - 【JACKETT】yts 未检索到数据
12:24:47 WARN - 【JACKETT】btsow 未检索到数据
12:24:47 WARN - 【JACKETT】torrentgalaxy 未检索到数据
12:24:47 WARN - 【JACKETT】acgrip 未检索到数据
12:24:47 WARN - 【JACKETT】eztv 返回数据：63
12:24:47 INFO - 【JACKETT】All Rise S03E10 Fire and Rain HDTV x264-CRiMSON 是 电视剧，不匹配类型：电影
12:24:54 INFO - 【JACKETT】rarbg 共检索到 100 条数据，过滤 0，不匹配 24，有效资源 0，耗时 7 秒
12:24:54 INFO - 【JACKETT】所有站点检索完成，有效资源数：0，总耗时 7 秒
12:24:54 INFO - 【WEB】雷神4：爱与雷霆 未检索到任何资源

**Comment by jxxghp** [comment]
开英文搜索
