### ISSUE TITLE
订阅关键字不自动下载

### ISSUE THREAD

**Issue by xxzj990** [jxxghp/nas-tools#68]
如下图，在web页面填的电影关键字不自动下载。
![微信截图_20220428091242](https://user-images.githubusercontent.com/5134154/165656672-f99e7e1b-3e75-4540-840e-36169aa9b2d9.png)

请问是哪里配置不对吗？谢谢

**Comment by xxzj990** [comment]
我尝试手动搜索，可以搜索到【死无对证】这个电影，而且我查看了一天的日志，没有找到自动下载关键字的相关日志

**Comment by xxzj990** [comment]
我大概研究了一下代码，好像明白了。
目前关键字订阅是依赖站点RSS地址了，必须有RSS站点才会去RSS的结果里找订阅的关键字。

我的想法是，因为有Jackett，所以关键字是不是可以在没有RSS的情况下直接去Jackett查，这样功能更加强大灵活，不需要挨个配置站点RSS，只需要简单的加一个关键字或者点一下豆瓣喜欢就能追剧了。

不成熟的想法，希望大佬考虑一下～

**Comment by jxxghp** [comment]
新功能后面再说吧
