### ISSUE TITLE
Jackett配置 url 页面在哪里?

### ISSUE THREAD

**Issue by cs0663c** [jxxghp/nas-tools#684]
之前不是点一下jackett 就可以设置apl key 和url地址
现在url 地址在哪里填写??
不用填写了吗?
现在是1.9.20 Debian docker
![image](https://user-images.githubusercontent.com/59052041/184478808-bcd4ad76-d3cf-414c-acbf-ce7df528533c.png)

**Comment by jxxghp** [comment]
不看更新日志？
