### ISSUE TITLE
电影订阅功能异常

### ISSUE THREAD

**Issue by lizhen789** [jxxghp/nas-tools#685]
![image](https://user-images.githubusercontent.com/35031472/184495873-6bdddc4f-7996-4784-876f-ee3306542ec3.png)
![image](https://user-images.githubusercontent.com/35031472/184495886-fbade258-dda2-4e6e-a7ca-368302805dec.png)
![image](https://user-images.githubusercontent.com/35031472/184495894-37b83867-82a4-4cbd-9890-3523629c7b9c.png)
![image](https://user-images.githubusercontent.com/35031472/184495921-61e6b5e1-4c01-4172-a7d5-940ffe222c80.png)
没有看到任何异常日志

**Comment by jxxghp** [comment]
看更新日志
