### ISSUE TITLE
【建议】为动漫类别单独设置过滤规则来避免下载生肉

### ISSUE THREAD

**Issue by ztx0079** [jxxghp/nas-tools#687]
能否单独为动漫类别设置默认的过滤规则,而不是与电影电视套用同一套过滤规则.
电影电视剧下载生肉可以联动csf下载字幕,但是csf不支持动漫的字幕搜刮.
所以建议作者能否为动漫类别单独设置一套过滤规则,这样我们就能过滤掉生肉而只下载熟肉.

**Comment by jxxghp** [comment]
动漫是否有字幕的规则跟电影电视剧不一样？ 具体是什么规则？

**Comment by ztx0079** [comment]
> 动漫是否有字幕的规则跟电影电视剧不一样？ 具体是什么规则？

动漫字幕组很少单独发布字幕文件,基本都是和动漫一起封装好的,一般熟肉上会在命名上有 CHS|CHT|简中|简繁|中英|中日 等关键词.

所有剧集在自动添加订阅时都是采用同一套默认规则,电影电视剧可以不过滤无字幕,因为可以配合csf自动搜刮字幕使用.
但是动漫套用那套规则的话就会大概率下载到生肉,且配合不了csf. 只能是到订阅里单独给每个动漫剧集套用熟肉过滤规则.

所以才建议作者单独为动漫类别单独设置一个默认过滤规则.

**Comment by jxxghp** [comment]
现在的过滤规则是可以多层过滤的，第一层你可以优先匹配标题中有字慕字样的，如果没有则跑下一条规则兜底，两者都不影响。

**Comment by ztx0079** [comment]
> 现在的过滤规则是可以多层过滤的，第一层你可以优先匹配标题中有字慕字样的，如果没有则跑下一条规则兜底，两者都不影响。

是的,我可以设置优先级 熟肉优先级高一些.
问题是动漫组熟肉出片基本会在生肉出片后1天左右.有个时间差问题,这样就会大概率下载到生肉.

**Comment by link2fun** [comment]
> 

1. RSS 层面 预过滤 只订阅有字幕的资源
2. 开启洗版, 后面有字幕的也会下载

**Comment by CD-D** [comment]
可以试试我这个 我的是只设置一个规则，只会命中简体的资源 名为追番：
[中简]|[简中]|简体|简繁|简日|简日双语|[中国][字配]|GB|中文|chs
1080[pi]|1080

![image](https://user-images.githubusercontent.com/35326452/184612974-b0e49f8f-a01a-480a-926f-cae0255ab4e2.png)
