### ISSUE TITLE
关于建立硬链接时重新刮削的逻辑

### ISSUE THREAD

**Issue by m1xds** [jxxghp/nas-tools#69]
我观察了一下建立硬链接的实时日志和结果。
现在的问题是，在对庞大的存量已刮削的电影库进行目录同步的时候，硬链接文件夹会在通过TMDB搜索的过程中进行二次刮削。

这里面有四个问题：
第一，会增加不必要的硬盘占用；
第二，在二次刮削的过程中，硬链中的电影文件夹中，与对应的存量经TMM和emby刮削过的电影文件相比会少很多图片；
第三，当然就是会增加不必要的流程时间；
第四，已刮削好的电影在二次刮削中有相当数量会刮错，比如纸牌屋刮的是1990年版本的。
第五，源文件夹中已刮削好的，后缀为.m2ts的（蓝光里直接弄出来的），一律不出现在失败的手动记录里，也不出现在成功记录里，也不出现在未识别文件夹中，在硬链过程中是直接忽略的。

同时在硬链过程中还发现了一些个例，比如纸房子第四季第五集，直接就掉出原文件夹，其它所有集全部正常，就除了这一集（和其它集命名方式完全一样，且在原文件夹中已刮削好），还有老友记等几部中的个别集。

不知道以下方案是否可行：
建立硬链的过程的时候，自动检查是否有.jpg和nfo，如有，直接原样建立硬链，或者：
未来增加对存量电影库的选项，当选项该选项后，原样硬链不再二次刮削。
非常希望项目未来趋于完美，我在电报群中也在很努力的帮助其它用户。
非常感谢作者的奉献！

**Comment by Skyzhu881** [comment]
现在的刮削功能很“自动”，但是错误多，同时修正困难。以下是几个我遇到的问题：

1. 对于已经运行了一段时间的Transmission,  我新建了NSTOOL之后，它会有一个“媒体识别”，但是识别过程不区分电视和电影。造成了很多电视（尤其是老电视）的每一集都出现在“手动识别”中，而且无法将他们合并 
2. 手动识别，需要起码的“智能”，例如填写标题（即使不准确）、选择是电视还是电视等
3. PT下载转移 、目录同步、媒体识别三套逻辑是否有重叠？第1项有开关，但是后两项均无开关。后两项什么时候会执行不确定
4. 设置中的媒体库和目录同步功能有重叠，特别是其中的”未识别“设置逻辑奇怪。目录同步中可以针对不同类型的媒体分别设置不同的”未识别“目录，但是媒体库不能分
5. 目录同步中的”未识别“项目无法手动识别
6. TMDB缺少部分搜索结果，是否可以增加一个meta的源，比如IMDB或者豆瓣。
7. 手动刮削的时候希望可以列出结果用用户选择，因为偶尔还会有刮削结果不正确的情况

**Comment by m1xds** [comment]
> 现在的刮削功能很“自动”，但是错误多，同时修正困难。以下是几个我遇到的问题：
> 
> 1. 对于已经运行了一段时间的Transmission,  我新建了NSTOOL之后，它会有一个“媒体识别”，但是识别过程不区分电视和电影。造成了很多电视（尤其是老电视）的每一集都出现在“手动识别”中，而且无法将他们合并
> 2. 手动识别，需要起码的“智能”，例如填写标题（即使不准确）、选择是电视还是电视等
> 3. PT下载转移 、目录同步、媒体识别三套逻辑是否有重叠？第1项有开关，但是后两项均无开关。后两项什么时候会执行不确定
> 4. 设置中的媒体库和目录同步功能有重叠，特别是其中的”未识别“设置逻辑奇怪。目录同步中可以针对不同类型的媒体分别设置不同的”未识别“目录，但是媒体库不能分
> 5. 目录同步中的”未识别“项目无法手动识别
> 6. TMDB缺少部分搜索结果，是否可以增加一个meta的源，比如IMDB或者豆瓣。
> 7. 手动刮削的时候希望可以列出结果用用户选择，因为偶尔还会有刮削结果不正确的情况

兄弟你没有升级吧？建议加电报群。你说的1，2早解决了。现在几乎是一天一个新版本了。
第3点，config里面有建议，pt下载转移和目录同步最好只选一个。PT转移只管新的，目录同步是全量同步（你把同步目录直接删了就相当于关了）
45新版都早解决了。
第7点，只要你输入TMDB号，结果是200%正确率的。
