### ISSUE TITLE
电视剧订阅识别有bug

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#694]
电视剧订阅 民间怪谈录 检索不到

实测柠檬有资源
![image](https://user-images.githubusercontent.com/54088512/184573543-412577be-4c35-4959-b49b-6b91251600f3.png)

名字测试也能识别到
![image](https://user-images.githubusercontent.com/54088512/184573585-4db2052f-7304-4ce3-954e-003a5a3d1c32.png)

错误日志
11:22:46 INFO - 【JACKETT】Folk Strange Tale S01 2022 1080p WEB-DL AAC H.264-HDSWEB 未识别到媒体信息
11:22:46 INFO - 【JACKETT】Fox's Strange Talk 2022 2160p WEB-DL AAC H.265-HDSWEB 是 电影，不匹配类型：电视剧
11:22:46 INFO - 【JACKETT】LemonHD 共检索到 2 条数据，过滤 1，不匹配 1，有效资源 0，耗时 1 秒

这应该是直接拿英文名去tmdb检索了吧，没找到。能否再增加中文名去tmdb检索，两者命中一个即可。

**Comment by jxxghp** [comment]
先搞清楚再提问

**Comment by thsrite** [comment]
![image](https://user-images.githubusercontent.com/54088512/184573830-80064258-5148-414b-8d8e-db188bd87cde.png)

![image](https://user-images.githubusercontent.com/54088512/184573854-84a07e1a-ade9-40c1-a8d1-c8457129bccb.png)

![image](https://user-images.githubusercontent.com/54088512/184573869-cd3ba44d-6b12-4d50-a2fa-62b807012612.png)
为什么呢？
