### ISSUE TITLE
过滤规则命中问题

### ISSUE THREAD

**Issue by CD-D** [jxxghp/nas-tools#696]
![c87b9ac70b7bc6e82818e1ebdcdba7f](https://user-images.githubusercontent.com/35326452/184607420-51b5a38b-961d-4443-b48e-b88ea8cd5e88.png)

如上图所示，这个过滤规则只会过滤简体并且是1080p的视频。但是经过测试后名称仅有一个1080p就可以命中。按理说应该是 xxxx[简中][1080p].mp4

包含：[中国简](/|\s|\\|\|)?[简](/|\s|\\|\|)?[中简]|[简中]|简体|简繁|简日|简日双语|[中国][字配]|[GB]|中文
1080[pi]

排除：Blu-?Ray.+VC-?1|Blu-?Ray.+AVC|UHD.+blu-?ray.+HEVC|\Wsdr\W|minibd|[\W_]diy[\W_]|[\W_]3d[\W_]|REMUX

测试名称：[XKsub][Yofukashi no Uta][06][CHT_JAP][1080P][WEBrip][MP4].mp4

![4dd90b30ce739ba14f1c4881165e458](https://user-images.githubusercontent.com/35326452/184607629-02c3f34e-ddf4-4fb7-bc24-6f8d92a43b15.png)

**Comment by CD-D** [comment]
sorry,是因为规则包含中有 [GB] 这个关键字而标题中的[WEBrip] 的 B 给匹配上了。是我的问题，应该xxx|GB|xxx

**Comment by log-time** [comment]
可是为啥要把GB放在第一优先级呢？是有啥特别的含义吗？

**Comment by CD-D** [comment]
创建一个单独的过滤规则 只配置1级 另外GB是简体字幕
这个规则的意思就是种子名中包含[简体]或者[简中]或[GB]等关键字。并且是1080p或者1080分辨率的才会命重
这是我现在的规则：
中简|简中|简体|简繁|简日|简日双语|GB|中文|CHS
1080[pi]|1080







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月16日(星期二) 中午11:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [jxxghp/nas-tools] 过滤规则命中问题 (Issue #696)





 
可是为啥要把GB放在第一优先级呢？是有啥特别的含义吗？

**Comment by log-time** [comment]
感觉GB很容易误判啊。副标题一旦含有文件大小，是不是就会误判呢

**Comment by CD-D** [comment]
> 感觉GB很容易误判啊。副标题一旦含有文件大小，是不是就会误判呢

确实有这个可能，所以这个规则仅适用于追番。或者优先级降低用于兜底
