### ISSUE TITLE
Rclone 复制模式，文件夹正常复制，文件复制失败

### ISSUE THREAD

**Issue by JackieDark** [jxxghp/nas-tools#699]
![image](https://user-images.githubusercontent.com/25630765/184679560-865d8278-c5e9-4146-9f12-d40ba82b64b4.png)
查看代码 rclone 也没有将日志打印出来，无法确定问题，帮忙看下哈，谢谢。可以通过--log-file=FILE 选项打印rclone日志，可以方便排查 rclone 问题

**Comment by jxxghp** [comment]
会不会是目录不存在？之前是强行放根目录，现在会把在nt里映射的路径目的目录拼上去了。

**Comment by JackieDark** [comment]
不确定是不是目录不存在，目前现象是网盘有了的对应电影的文件夹，但是文件复制失败，没有日志查具体原因
![image](https://user-images.githubusercontent.com/25630765/184782186-eb861b38-58de-4c2e-9019-5de508dc87d1.png)

**Comment by jxxghp** [comment]
选择的什么模式？
更新下程序，贴上最新的日志（现在会打印完整路径），还有目录映射的情况

**Comment by JackieDark** [comment]
使用的是 rclone 复制模式，程序版本1.9.22。
下载目录是/电影 映射到容器的 /download/电影
媒体目录是/gd 映射到容器的 /media   /gd 就是挂载的目录
rclone配置文件也已经映射
![image](https://user-images.githubusercontent.com/25630765/184789476-36b2fe10-b8b5-43d5-84ac-c24224a8c7c4.png)

**Comment by FincerDW** [comment]
> 会不会是目录不存在？之前是强行放根目录，现在会把在nt里映射的路径目的目录拼上去了。

因为包含映射路径，就无法在原来盘里做增量了，只能做定时任务进行再转移，希望大佬看看能不能解决

**Comment by JackieDark** [comment]
调试了下，打印出os.system执行的命令，然后在容器环境直接跑是正常的，代码中就报错，看下是不是这里问题呢
<img width="693" alt="image" src="https://user-images.githubusercontent.com/25630765/184844995-ab426917-d46a-448d-9dcc-436ab60a730b.png">
<img width="927" alt="image" src="https://user-images.githubusercontent.com/25630765/184845059-31580fda-08cb-4f64-9219-f1489b4297e1.png">

**Comment by FincerDW** [comment]
> 调试了下，打印出os.system执行的命令，然后在容器环境直接跑是正常的，代码中就报错，看下是不是这里问题呢 <img alt="image" width="693" src="https://user-images.githubusercontent.com/25630765/184844995-ab426917-d46a-448d-9dcc-436ab60a730b.png"> <img alt="image" width="927" src="https://user-images.githubusercontent.com/25630765/184845059-31580fda-08cb-4f64-9219-f1489b4297e1.png">

你rclone.conf里是否包含了service_account_file，如果是，也要映射出来，我刚开始也是256，把SA文件夹映射了就行了

**Comment by JackieDark** [comment]
没有这个，我就是单独的rclone，没有sa
