### ISSUE TITLE
Transmission2.9.4版本下载报错

### ISSUE THREAD

**Issue by hermer** [jxxghp/nas-tools#702]
14:51:58 ERROR - 【DOWNLOADER】添加下载任务出错：Method "torrent-set" Argument "labels" does not exist in version 15.
14:51:58 ERROR - 【DOWNLOADER】添加下载任务 功勋 (2021) 失败：Method "torrent-set" Argument "labels" does not exist in version 15.
14:51:58 INFO - 【MSG】发送serverchan消息：title=添加下载任务失败：功勋 (2021) S01, text=种子：Medal of the Republic 2021 Complete WEB-DL 2160p H265 AAC-BtsTV 错误信息：Method "torrent-set" Argument "labels" does not exist in version 15.

![image](https://user-images.githubusercontent.com/3256129/184828306-dfe4ccd6-80ba-4ea0-9a48-eae7a45ee747.png)
实际有下载成功
![image](https://user-images.githubusercontent.com/3256129/184828400-880f5cae-1219-46b9-be3a-4114751a63a8.png)

**Comment by jxxghp** [comment]
重复问题，TR版本过低，日志里有提示。
