### ISSUE TITLE
建议增加fclone模式

### ISSUE THREAD

**Issue by del0nz** [jxxghp/nas-tools#703]
命令与rclone相同，可用fclone moveto、fclone copyto、fclone move、fclone copy。
PS：Fclone是基于Rclone的魔改版本，功能与原版Rclone相同，增加支持突破Google Drive单账号每日750G限制，需要搭配Service Account使用。fclone兼容rclone的config配置，另外增加sa配置即可。（这些与nastool本身没有太大关联，docker安装注意sa的json文件目录的映射即可）

**Comment by jxxghp** [comment]
EB大佬你竟然亲自来提问，不支持都不行了

**Comment by del0nz** [comment]
> 

Orz  大佬说笑了 233333
不好搞的话就算了，一般人750G够用了，需求可能不大。

**Comment by haig233** [comment]
https://github.com/dogbutcat/gclone

可以使用此分支，gclone修改版，同步了最新核心，并支持单文件随机变换sa，相比原版个人觉得好用不少

**Comment by jxxghp** [comment]
动基础包涉及底层变动，又会有一大堆人装不上版本。
自己想办法在容器内安装并ln rclone命令为gclone吧。
