### ISSUE TITLE
rclone复制模式，复制完就直接刷新emby，挂载的还没有导致emby库没有

### ISSUE THREAD

**Issue by wqj666666** [jxxghp/nas-tools#708]
日志信息
[IMAGE-2022-08-17-17-25-25.jpg](https://postimg.cc/0MsQVNP8)

rclone复制模式，rclone复制上传云盘完就马上直接刷新emby了，服务器挂载的云盘还没有，导致emby库没有，ChineseSubFinde也马上执行了，导致字幕下载失败，希望能在这个模式下执行刷新和ChineseSubFinde能加延迟时间

**Comment by jxxghp** [comment]
先搞清楚，你说的都是错的

**Comment by jxxghp** [comment]
配置里有个路径看到了吗
