### ISSUE TITLE
折腾两天总算差不多了，推荐索引等功能都正常了，可PT不动求助

### ISSUE THREAD

**Issue by freeangle81** [jxxghp/nas-tools#71]
ERROR - 【PT】添加PT任务出错：Failed to connect to qBittorrent. Connection Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('
我也检查了config已经设置了qb的地址和端口
感谢大佬

**Comment by jxxghp** [comment]
这个是qb连不上，qb是docker安装？docker用127.0.0.1是连不上的，自己研究或者求助群友。不是bug。

**Comment by freeangle81** [comment]
> 这个是qb连不上，qb是docker安装？docker用127.0.0.1是连不上的，自己研究或者求助群友。不是bug。

感谢回复，我的QB可以正常使用，是docker的，是不是意思qb设置时用127.0.0.1就无法使用》
