### ISSUE TITLE
下载器添加aria2时测试失败

### ISSUE THREAD

**Issue by yaojia25** [jxxghp/nas-tools#711]
下载器无法添加aria2，host，port，secret均填写无误（config文件确认），但是显示测试失败
![image](https://user-images.githubusercontent.com/31342892/185131592-a72ebabd-4b44-4e98-9d43-1ddccfc1db03.png)
aria2ng可以正常连接
![image](https://user-images.githubusercontent.com/31342892/185132099-37478565-5448-4844-a433-12b5898c1641.png)

**Comment by weiyideai520** [comment]
我的也是显示连接失败，实际上可以添加任务。但是任务无法下载

**Comment by huluohu** [comment]
我也是，搞了半天也不行
