### ISSUE TITLE
字幕转移后会丢失后缀

### ISSUE THREAD

**Issue by sleikang** [jxxghp/nas-tools#712]
![image](https://user-images.githubusercontent.com/23020770/185175970-9674adff-8aeb-4002-9b7b-4df0a9b17b9b.png)
如图，本身字幕就算带有.zh-cn然后转移完成就没有了，但是看代码是有写判断逻辑

**Comment by sleikang** [comment]
测试应该
sub_language = os.path.split(".")[-2]
改成这个吧
sub_language = file_name.split(".")[-2]

**Comment by jxxghp** [comment]
你这个截图不是转迁移后的吗？加了zh-cn，原名是什么样的？

**Comment by sleikang** [comment]
> 你这个截图不是转迁移后的吗？加了zh-cn，原名是什么样的？

这个原名就是这样转移后就没了，这个是我自己手动加上去的
