### ISSUE TITLE
电视剧订阅的BUG

### ISSUE THREAD

**Issue by xnoods** [jxxghp/nas-tools#714]
电视剧订阅的时候如果选择了单一的订阅站点和搜索站点，不全选的情况下，就会出现站点就算有了资源，也无法自动下载下来，目前测试hdchina站点就是这情况，很崩溃，希望能修复下这个bug
<img width="710" alt="image" src="https://user-images.githubusercontent.com/18209713/185276454-40e9bd5c-1803-4c18-a07b-dd702df8503c.png">

**Comment by jxxghp** [comment]
能提供下日志吗？

**Comment by xnoods** [comment]
http://gofile.me/6TDSk/hbffyDKNt
您好，上面是我的日志的文件，我就整个都给您吧，我发现自动订阅的时候无法下载，但是如果在订阅页面刷新下，就自动下载了，也就是手动

**Comment by xnoods** [comment]
我说的手动刷新是这里点一下
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/18209713/185281117-8a1d7198-78d2-4c07-8c61-dfdb350d042c.png">

**Comment by jxxghp** [comment]
RSS地址有维护吧？

**Comment by jxxghp** [comment]
你这个站有个诡异的种子有特殊字符报错了，但是有正常拉取站点的数据的，你试下单选其它站正不正常。如果其它正常就是下面这个的问题

2022-08-18 13:17:08,951	ERROR: 【RSS】处理RSS发生错误：invalid literal for int() with base 10: '7³' - Traceback (most recent call last):
  File "/nas-tools/pt/rss.py", line 148, in rssdownload
    media_info = self.media.get_media_info(title=torrent_name, subtitle=description)
  File "/nas-tools/rmt/media.py", line 573, in get_media_info
    meta_info = MetaInfo(title, subtitle=subtitle)
  File "/nas-tools/rmt/metainfo.py", line 19, in MetaInfo
    return MetaVideo(title, subtitle)
  File "/nas-tools/rmt/meta/metavideo.py", line 77, in __init__
    self.__init_episode(token)
  File "/nas-tools/rmt/meta/metavideo.py", line 347, in __init_episode
    self.begin_episode = int(token)
ValueError: invalid literal for int() with base 10: '7³'

**Comment by xnoods** [comment]
> RSS地址有维护吧？

嗯嗯，维护了的，我一直在维护

**Comment by xnoods** [comment]
> 你这个站有个诡异的种子有特殊字符报错了，但是有正常拉取站点的数据的，你试下单选其它站正不正常。 如果其它正常就是下面这个的问题
> 
> 2022-08-18 13：17：08，951 错误： 【RSS】处理RSS 发生错误：以 10 为基数的 int（） 的无效文字： '7³' - 回溯 （最近一次调用）： 文件 “/nas-tools/pt/rss.py”， 第 148 行， 在 rssdownload media_info = self.media.get_media_info（title=torrent_name， subtitle=description） 文件 “/nas-tools/rmt/media.py”， 第 573 行， 在 get_media_info meta_info = MetaInfo（title， subtitle=subtitle） 文件 “/nas-tools/rmt/metainfo.py”， 第 19 行， in MetaInfo 返回 MetaVideo（title， subtitle） 文件 “/nas-tools/rmt/meta/metavideo.py”， 第 77 行， **init** self.__init_episode（token） 文件 “/nas-tools/rmt/meta/metavideo.py”， 第 347 行， 在 __init_episode self.begin_episode = int（token） ValueError： invalid literal for int（） with base 10： '7³'

这个问题能修复吗？我经常在这个站下载电视剧，他们站的资源还可以，至于您说的其它站点，我今天也试试

**Comment by jxxghp** [comment]
> > 你这个站有个诡异的种子有特殊字符报错了，但是有正常拉取站点的数据的，你试下单选其它站正不正常。 如果其它正常就是下面这个的问题
> 
> > 
> 
> > 2022-08-18 13：17：08，951 错误： 【RSS】处理RSS 发生错误：以 10 为基数的 int（） 的无效文字： '7³' - 回溯 （最近一次调用）： 文件 “/nas-tools/pt/rss.py”， 第 148 行， 在 rssdownload media_info = self.media.get_media_info（title=torrent_name， subtitle=description） 文件 “/nas-tools/rmt/media.py”， 第 573 行， 在 get_media_info meta_info = MetaInfo（title， subtitle=subtitle） 文件 “/nas-tools/rmt/metainfo.py”， 第 19 行， in MetaInfo 返回 MetaVideo（title， subtitle） 文件 “/nas-tools/rmt/meta/metavideo.py”， 第 77 行， **init** self.__init_episode（token） 文件 “/nas-tools/rmt/meta/metavideo.py”， 第 347 行， 在 __init_episode self.begin_episode = int（token） ValueError： invalid literal for int（） with base 10： '7³'
> 
> 
> 
> 这个问题能修复吗？我经常在这个站下载电视剧，他们站的资源还可以，至于您说的其它站点，我今天也试试

这个问题改好了

**Comment by xnoods** [comment]
> > > 你这个站有个诡异的种子有特殊字符报错了，但是有正常拉取站点的数据的，你试下单选其它站正不正常。 如果其它正常就是下面这个的问题
> > 
> > 
> > > 
> > 
> > 
> > > 2022-08-18 13：17：08，951 错误： 【RSS】处理RSS 发生错误：以 10 为基数的 int（） 的无效文字： '7³' - 回溯 （最近一次调用）： 文件 “/nas-tools/pt/rss.py”， 第 148 行， 在 rssdownload media_info = self.media.get_media_info（title=torrent_name， subtitle=description） 文件 “/nas-tools/rmt/media.py”， 第 573 行， 在 get_media_info meta_info = MetaInfo（title， subtitle=subtitle） 文件 “/nas-tools/rmt/metainfo.py”， 第 19 行， in MetaInfo 返回 MetaVideo（title， subtitle） 文件 “/nas-tools/rmt/meta/metavideo.py”， 第 77 行， **init** self.__init_episode（token） 文件 “/nas-tools/rmt/meta/metavideo.py”， 第 347 行， 在 __init_episode self.begin_episode = int（token） ValueError： invalid literal for int（） with base 10： '7³'
> > 
> > 
> > 这个问题能修复吗？我经常在这个站下载电视剧，他们站的资源还可以，至于您说的其它站点，我今天也试试
> 
> 这个问题改好了

日志：http://gofile.me/6TDSk/OEFus5KkB
早上测试了下，还是不行，无法RSS订阅下载
<img width="484" alt="image" src="https://user-images.githubusercontent.com/18209713/185512794-cbdf4af3-4b06-42d4-8d29-4b9c93df9e8d.png">
站点已经有了，还是没有自动订阅下载下来
PS:已经更新程序到了最新版本
