### ISSUE TITLE
种子成功提交到Qbittorrent下载器后，是暂停状态

### ISSUE THREAD

**Issue by Dapong** [jxxghp/nas-tools#716]
我现在使用的是威联通的Docker版的【docker pull linuxserver/qbittorrent:latest】，v4.4.3 ，现在更新到最新版仍然有问题存在；
虽然官方api添加新种子说明 paused 参数默认为 false ，但linuxserver/qbittorrent新版本会出现默认paused = true (疑似bug)，所以只能明确定义 paused = "false" ，才可以解决新版本qb所带来的问题；
不知道其他版本是否会出现这个问题，但是为了避免相关问题的存在，建议把参数值明确。

**Comment by jxxghp** [comment]
给日志，你的分析不对

**Comment by Dapong** [comment]
> 给日志，你的分析不对
我自己用软件测试过以上问题，qbittorrent [linuxserver/qbittorrent:latest] 的 Add new torrent：/api/v2/torrents/add 接口
1.paused = "false" ，添加后正常下载；
2.paused = "" ，添加后暂停；
3.无paused 参数，添加后暂停。
并非每个版本的qb都会出现这个情况，但是为了保险起见，可以把 paused 参数设置为字符串 "false" 。

![image](https://user-images.githubusercontent.com/16550877/185369854-3b4f15ea-e08b-4f8e-bd5d-46f59ceb4495.png)
![image](https://user-images.githubusercontent.com/16550877/185369960-cf52adfb-3398-4f46-b12a-bfb40f31f04f.png)

**Comment by jxxghp** [comment]
竟然有版本差异，最新的提交我设为默认False了

**Comment by hanqing0521** [comment]
> 竟然有版本差异，最新的提交我设为默认False了

sad,对于qBittorrent v4.4.4 Web UI (64-bit)又暂停，并显示添加任务失败，给任务加上数字标签。

**Comment by Dapong** [comment]
> > 竟然有版本差异，最新的提交我设为默认False了
> 
> sad,对于qBittorrent v4.4.4 Web UI (64-bit)又暂停，并显示添加任务失败，给任务加上数字标签。

上次大大好像没有修复好， 【paused 参数设置为字符串 "false"】

**Comment by hanqing0521** [comment]
然后在正在下载的选项看不到qb下载的任务
