### ISSUE TITLE
nasTools资源搜索不到

### ISSUE THREAD

**Issue by neversaymiss** [jxxghp/nas-tools#718]
我在jackett里搜索可以搜索到相关资源
![image](https://user-images.githubusercontent.com/43662143/185379120-f3bedd82-9e41-4d96-87c8-e4458950e6ee.png)
在nastools里也能看见搜到的检索信息
![image](https://user-images.githubusercontent.com/43662143/185379379-2a9c3780-bd89-4551-829e-010c57eb74e3.png)
但是点击资源，就提示资源搜索不到
![image](https://user-images.githubusercontent.com/43662143/185379533-83caa79c-32ae-44d9-a04d-e329a03e0cb7.png)
日志里面显示如下
![image](https://user-images.githubusercontent.com/43662143/185379689-2bdd6584-24cf-4659-9207-1b181ab91dd4.png)
所以求助一下解决资源搜索不到的问题。

**Comment by ZevAlain** [comment]
用快速搜索试试呢

**Comment by ZevAlain** [comment]
> 我在jackett里搜索可以搜索到相关资源 ![image](https://user-images.githubusercontent.com/43662143/185379120-f3bedd82-9e41-4d96-87c8-e4458950e6ee.png) 在nastools里也能看见搜到的检索信息 ![image](https://user-images.githubusercontent.com/43662143/185379379-2a9c3780-bd89-4551-829e-010c57eb74e3.png) 但是点击资源，就提示资源搜索不到 ![image](https://user-images.githubusercontent.com/43662143/185379533-83caa79c-32ae-44d9-a04d-e329a03e0cb7.png) 日志里面显示如下 ![image](https://user-images.githubusercontent.com/43662143/185379689-2bdd6584-24cf-4659-9207-1b181ab91dd4.png) 所以求助一下解决资源搜索不到的问题。

用快速搜索试试呢

**Comment by neversaymiss** [comment]
昨天更新了nasTool，然后关机了，今天打开发现可以搜索到资源了，我也不知道怎么解决的。

**Comment by maCreay** [comment]
我的还是不行啊。。Tell Me Lies S01E01 720p WEB h264-KOGi 是 电视剧，不匹配类型：电影 
这是啥意思
