### ISSUE TITLE
新增Jackett搜索结果站点排序功能

### ISSUE THREAD

**Issue by rockhia** [jxxghp/nas-tools#719]
升级到V1.9.23版本后，不再支持搜索结果站点排序。建议恢复该功能，这样更能下载更优资源

**Comment by jxxghp** [comment]
现在使用的是jackett返回的顺序

**Comment by rockhia** [comment]
Jackett好像没办法设置站点排序，都是按站点字母顺序进行排序

**Comment by jxxghp** [comment]
后面内置索引器了，Jackett的算了。
