### ISSUE TITLE
反馈个遇到的问题，手动删除整理后的media文件夹及config文件夹后，整理功能无法使用

### ISSUE THREAD

**Issue by Idolj** [jxxghp/nas-tools#72]
最早是用的套件版，原本是想重新整理一遍存量视频，结果删除操作后，启动日志都是正常的，但是PT签到及目录同步功能点击都没有反应了，日志也没有任何进度。
后来换Docker版，起初也是正常的，同样操作后出现的一样的问题。
尝试过套件版卸载、降级、删除NASTOOL文件夹后重建，问题无法解决。
Docker也尝试过删除映像重拉、删除config文件夹后重建，也是问题依旧。
目前6.04版，在web界面选择重启后，日志出现若干行
ERROR - 【RUN】停止scheduler失败：Scheduler is not running
不知道是否是相关问题。
如有时间，麻烦给解答一下。
非常感谢！

**Comment by jxxghp** [comment]
需要提供配置、日志跟docker映射，应该是配置问题。

**Comment by Idolj** [comment]
**套件版**

1. 配置
app:
  logtype: server
  logpath: /config/logs
  logserver: 192.168.31.12:514
  web_port: 3000
  login_user: admin
  login_password: password
  ssl_cert:
  ssl_key:
  rmt_tmdbkey: **************
  rmt_match_mode: normal
  proxies:
    http:
    https:
  domain: http://**.***.***.**:13000

media:
  media_server: emby
  movie_path:
  - /volume1/media/电影
  tv_path:
  - /volume1/media/电视剧
  anime_path:
  - /volume1/media/动漫
  unknown_path:
  - /volume1/media/未识别
  category: default-category
  min_filesize: 200

emby:
  host: http://192.168.31.12:8096
  api_key: ****************

jellyfin:
  host: http://127.0.0.1:8096
  api_key:

message:
  msg_channel: wechat
  webhook_ignore:
  - admin:xx的iPhone 12
  wechat:
    corpid: ******
    corpsecret: ******
    agentid: 1000002
    Token: ********
    EncodingAESKey: ******
  serverchan:
    sckey:
  telegram:
    telegram_token:
    telegram_chat_id:
    webhook: true
  bark:
    server: https://api.day.app
    apikey:

sync:
  sync_path:
  - /volume1/Movie
  sync_mod: copy
  nas_sys: linux

pt:
  pt_client: qbittorrent
  pt_monitor: false
  rmt_mode: copy
  search_indexer: jackett
  search_auto: true
  ptsignin_cron: 08:00
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/98.0.4758.102 Safari/537.36
  pt_seeding_time:
  pt_check_interval: 1800
  rss_chinese: false

jackett:
  api_key: ********
  indexers:
  - https://192.168.31.12:9117/api/v2.0/indexers/eztv/results/torznab/
prowlarr:
  host: http://127.0.0.1:9696
  api_key:

qbittorrent:
  qbhost: 192.168.31.12
  qbport: 8085
  qbusername: admin
  qbpassword: password
  force_upload: true
  save_path: /volume2/Download
  save_containerpath: /volume2/Download

transmission:
  # 【transmission IP地址和端口】：注意如果tr启用了HTTPS证书，则需要配置为https://IP
  trhost: 127.0.0.1
  trport: 9091
  # transmission 登录用户名和密码
  trusername: admin
  trpassword: password
  save_path:
    movie:
    tv:
    anime:
  save_containerpath:
    movie:
    tv:
    anime:

douban:
  users:
  - *******
  cookie: *******
  days: 30
  interval: 6
  types: do,wish,collect
  auto_search: true
  auto_rss: true
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/98.0.4758.102 Safari/537.36


2.日志
13:01:24 - 配置文件地址：/volume1/NASTOOL/config.yaml
13:01:24 - NASTool 当前版本号：v0.6.04
13:01:24 - 日志输出类型为：server
13:01:24 - 日志将上送到服务器：192.168.31.12:514
13:01:24 INFO - WEB管瑞页面监听端口：3000
13:01:24 INFO - WEB管瑞页面用户：admin
13:01:24 INFO - 未启用https，请使用 http://IP:3000 访问管理页面
13:01:24 INFO - TMDB匹配模式：正常模式
13:01:24 INFO - 媒体管理软件设置为：emby
13:01:24 INFO - 电影分类：华语电影 外语电影
13:01:24 INFO - 电视剧分类：动漫 纪录片 儿童 综艺 国产剧 欧美剧 日韩剧 未分类
13:01:24 INFO - 动漫分类：动漫
13:01:24 INFO - 目录同步转移模式为：复制
13:01:24 INFO - PT下载软件设置为：qbittorrent
13:01:24 INFO - PT下载文件转移模式为：复制
13:01:24 INFO - PT检索软件设置为：jackett
13:01:24 INFO - 微信等移动端渠道搜索已开启自动择优下载
13:01:24 INFO - pt_seeding_time未配置，自动删种功能已关闭
13:01:24 INFO - pt_monitor未配置，PT下载监控功能已关闭
13:01:24 - 开始启动进程...
13:01:25 INFO - 【SYNC】读取到监控目录：/volume1/Movie
13:01:25 INFO - 【RUN】scheduler.rss_download启动...
13:01:25 INFO - 【RUN】/volume1/Movie 的monitor.media_sync启动...



**Docker版**

1.配置
app:
  logtype: file
  logpath: /config/logs
  logserver: 192.168.31.12:514
  web_port: '3333'
  login_user: admin
  login_password: password
  ssl_cert: ''
  ssl_key: ''
  rmt_tmdbkey: ********
  rmt_match_mode: normal
  proxies:
    https:
    http:
  domain: http://**.***.***.**:13000

media:
  media_server: emby
  movie_path:
  - /media/电影
  tv_path:
  - /media/电视剧
  anime_path:
  - /media/动漫
  unknown_path:
  - /media/未识别
  category: default-category
  min_filesize: '200'

emby:
  host: http://192.168.31.12:8096
  api_key: ********

jellyfin:
  host: http://127.0.0.1:8096
  api_key:

message:
  msg_channel: wechat
  webhook_ignore:
  - admin:xx的iPhone 12
  wechat:
    corpid: ********
    corpsecret: ********
    agentid: 1000002
    Token:********
    EncodingAESKey: ********

  serverchan:
    sckey:
  telegram:
    telegram_token:
    telegram_chat_id:
    webhook: true
  bark:
    server: https://api.day.app
    apikey:

sync:
  sync_path:
  - /movie|/media/电视剧|/media/未识别
  - /movie|/media/动漫|/media/未识别
  - /movie|/media/电影|/media/未识别
  sync_mod: copy
  nas_sys: linux

pt:
  pt_client: qbittorrent
  pt_monitor: false
  rmt_mode: copy
  search_indexer: jackett
  search_auto: true
  ptsignin_cron: 08:00
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/98.0.4758.102 Safari/537.36
  pt_seeding_time:
  pt_check_interval: 1800
  rss_chinese: false

jackett:
  api_key: ********
  indexers:
  - https://192.168.31.12:9117/api/v2.0/indexers/mteamtp/results/torznab/
prowlarr:
  host: http://127.0.0.1:9696
  api_key:

qbittorrent:
  qbhost: 192.168.31.12
  qbport: '8085'
  qbusername: admin
  qbpassword: password
  force_upload: true
  save_path:
    movie: /Download
    tv: /Download
    anime: /Download
  save_containerpath:
    movie: /download
    tv: /download
    anime: /download

transmission:
  trhost: 127.0.0.1
  trport: 9091
  trusername: admin
  trpassword: password
  save_path:
    movie:
    tv:
    anime:
  save_containerpath:
    movie:
    tv:
    anime:

douban:
  users:
  - *******
  cookie:********
  days: 30
  interval: 6
  types: do,wish,collect
  auto_search: true
  auto_rss: true
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/98.0.4758.102 Safari/537.36


2.日志

#Docker日志
2022-04-29 07:11:56 | stdout | 2022-04-29 15:11:56,205 INFO success: nas-tools entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-04-29 07:11:55 | stdout | 2022-04-29 15:11:55,204 INFO spawned: 'nas-tools' with pid 19
2022-04-29 07:11:54 | stdout | 2022-04-29 15:11:54,202 INFO supervisord started with pid 1
2022-04-29 07:11:54 | stdout | 2022-04-29 15:11:54,201 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-04-29 07:11:54 | stdout | 2022-04-29 15:11:54,201 INFO RPC interface 'supervisor' initialized
2022-04-29 07:11:54 | stdout | 2022-04-29 15:11:54,194 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-04-29 07:11:53 | stdout | 注意：日志将停止打印，请通过文件或WEB页面查看日志
2022-04-29 07:11:53 | stdout | 以PUID=0，PGID=0的身份启动程序...
2022-04-29 07:11:53 | stdout | 更新成功...
2022-04-29 07:11:53 | stdout | Already up to date.
2022-04-29 07:11:52 | stdout | 更新程序...
2022-04-29 07:11:50 | stdout | 2022-04-29 15:11:50,368 INFO stopped: nas-tools (exit status 0)
2022-04-29 07:11:50 | stdout | 2022-04-29 15:11:50,221 INFO waiting for nas-tools to die
2022-04-29 07:11:50 | stdout | 2022-04-29 15:11:50,221 WARN received SIGTERM indicating exit request

#web日志
15:11:56 - 配置文件地址：/config/config.yaml
15:11:56 - NASTool 当前版本号：v0.6.04
15:11:56 - 日志输出类型为：file
15:11:56 - 日志将写入文件：/config/logs
15:11:56 INFO - WEB管瑞页面监听端口：3333
15:11:56 INFO - WEB管瑞页面用户：admin
15:11:56 INFO - 未启用https，请使用 http://IP:3333 访问管理页面
15:11:56 INFO - TMDB匹配模式：正常模式
15:11:56 INFO - 媒体管理软件设置为：emby
15:11:56 INFO - 电影分类：华语电影 外语电影
15:11:56 INFO - 电视剧分类：动漫 纪录片 儿童 综艺 国产剧 欧美剧 日韩剧 未分类
15:11:56 INFO - 动漫分类：动漫
15:11:56 INFO - 目录同步转移模式为：复制
15:11:56 INFO - PT下载软件设置为：qbittorrent
15:11:56 INFO - PT下载文件转移模式为：复制
15:11:56 INFO - PT检索软件设置为：jackett
15:11:56 INFO - 微信等移动端渠道搜索已开启自动择优下载
15:11:56 INFO - pt_seeding_time未配置，自动删种功能已关闭
15:11:56 INFO - pt_monitor未配置，PT下载监控功能已关闭
15:11:56 - 开始启动进程...
15:11:57 INFO - 【SYNC】读取到监控目录：/movie，目的目录：/media/电视剧，未识别目录：/media/未识别
15:11:57 INFO - 【SYNC】读取到监控目录：/movie，目的目录：/media/动漫，未识别目录：/media/未识别
15:11:57 INFO - 【SYNC】读取到监控目录：/movie，目的目录：/media/电影，未识别目录：/media/未识别
15:11:57 INFO - 【RUN】scheduler.rss_download启动...
15:11:57 INFO - 【RUN】/movie 的monitor.media_sync启动...

3.Docker映射：
/docker/nastools/config             /config
/Movie                                          /movie
/media                                          /media
/Download                                   /download


-------------------------------------------------------------------
以上。
不知道我理解的对不对。
还望有空了帮我看一下。
非常感谢。

**Comment by jxxghp** [comment]
有哪些功能是正常的？看起来并没有什么问题。清理下浏览器缓存试试。

**Comment by Idolj** [comment]
只知道PT下载转移这个也是无效的。
我没啥pt下载的需求，所以其他功能虽然也设置但是没有用过。
----------------------------------------------------------------------------------------
刚试过浏览器缓存都清除了，问题没有变化。
不知道我这拨诡异的删除是做了什么孽。

**Comment by jxxghp** [comment]
15:11:56 INFO - pt_monitor未配置，PT下载监控功能已关闭
日志已经写的很清楚了，你配置没开。

**Comment by Idolj** [comment]
不是这个问题，是手动点击PT转移也没有反应。
主要还是想解决前面说的问题，最最需求的整理功能。
不知道为什么删掉配置文件夹重建后，这些功能都没有反应了。
我还有其他能删除的文件吗？现在就是希望能回到一开始初始的状态，恢复这个目录同步的功能。
我是用的黑群。
麻烦再给指个方向吧，谢谢了。

**Comment by muihiuwev** [comment]
> 不是这个问题，是手动点击PT转移也没有反应。 主要还是想解决前面说的问题，最最需求的整理功能。 不知道为什么删掉配置文件夹重建后，这些功能都没有反应了。 我还有其他能删除的文件吗？现在就是希望能回到一开始初始的状态，恢复这个目录同步的功能。 我是用的黑群。 麻烦再给指个方向吧，谢谢了。

我也转移不了，应该是只对新增下载发生作用。用命令手动转移吧。

**Comment by Idolj** [comment]
> > 不是这个问题，是手动点击PT转移也没有反应。 主要还是想解决前面说的问题，最最需求的整理功能。 不知道为什么删掉配置文件夹重建后，这些功能都没有反应了。 我还有其他能删除的文件吗？现在就是希望能回到一开始初始的状态，恢复这个目录同步的功能。 我是用的黑群。 麻烦再给指个方向吧，谢谢了。
> 
> 我也转移不了，应该是只对新增下载发生作用。用命令手动转移吧。

全部删除后重新安装，不管是套件还是Docker。
配置文件不要用备份复制回来，全部在web重新手动设置。
我试了都可以恢复正常了。
一定不要用备份的配置文件那些。
