### ISSUE TITLE
更新后之前目录同步里设置的都无法删除

### ISSUE THREAD

**Issue by manduted** [jxxghp/nas-tools#720]
如标题，点 X  不起作用，但是打开状态，或者识别那个开关会新建一个。。旧的不能删除

**Comment by jxxghp** [comment]
是什么时候更新的，昨天晚上补修改了一下

**Comment by manduted** [comment]
我发现的是昨天晚上凌晨3点过。当时发现点目录同步点不开。我然后重启了下docker。就能打开目录同步模块了，发现里面的样子跟原来不一样，刚好试一下想把原来存在的删了换个目录。点X就闪一下，也试了点头像下面的手动更新。还是这样。我就马上去github下面留的言



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mr ***@***.***&gt;; 
发送时间: 2022年8月19日(星期五) 中午11:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jxxghp/nas-tools] 更新后之前目录同步里设置的都无法删除 (Issue #720)





 
是什么时候更新的，昨天晚上补修改了一下

**Comment by manduted** [comment]
新建的确实是可以正常删除、切换开关，旧的条目无法删除，在旧的条目里点，识别重命名和状态那个两个开关里的任意一个，都会新建一个完全跟旧的相同的条目（这个新建的正常删除，切换）

**Comment by jxxghp** [comment]
把旧的配置贴出来一下，在配置文件里看

**Comment by manduted** [comment]
[](https://github.com/manduted/image/blob/main/%E6%88%AA%E5%9B%BE20220819125153.jpg)

刚才测试了下，更新后，配置文件的监控目录多了同步方式的标签，就是配置文件里的@###，而老配置是没有的，手动添加@###标签后，停止导入配置再重启dokcer就可以正常删除了

**Comment by manduted** [comment]
![](https://github.com/manduted/pic/blob/0e5857516ed77255641deffc160e37d21f5067ed/nas-tool.jpg)

刚才测试了下，更新后，配置文件的监控目录多了同步方式的标签，就是配置文件里的@###，而老配置是没有的，手动添加@###标签后，停止导入配置再重启dokcer就可以正常删除了

**Comment by manduted** [comment]
额。。粘贴不来图片

**Comment by manduted** [comment]
![nas-tool](https://user-images.githubusercontent.com/47053686/185548558-ea75aa1b-dda2-4756-9ab4-59dd1f15d922.jpg)

额。。结果添加图片，就在回复框下面。

**Comment by jxxghp** [comment]
> ![](https://github.com/manduted/pic/blob/0e5857516ed77255641deffc160e37d21f5067ed/nas-tool.jpg)
> 
> 刚才测试了下，更新后，配置文件的监控目录多了同步方式的标签，就是配置文件里的@###，而老配置是没有的，手动添加@###标签后，停止导入配置再重启dokcer就可以正常删除了

我在这个更新里 b91b7acc491efb5798c6b0756a7db6b8b752d372 处理了这个问题，我自己测试都是没问题的。

**Comment by manduted** [comment]
那就不知道了。1122-1130  都是刷新旧配置的。感觉有点莫名其妙的了。不过知道怎么手动也好办
