### ISSUE TITLE
微信远程搜索漏剧集的问题

### ISSUE THREAD

**Issue by fxqq** [jxxghp/nas-tools#722]
![Screenshot_2022-08-19-14-03-49-481_com tencent mm](https://user-images.githubusercontent.com/30470143/185555194-6947b4c4-ebc9-43e7-8070-5856a6eba09a.jpg)
![Screenshot_2022-08-19-14-03-59-059_org jellyfin mobile](https://user-images.githubusercontent.com/30470143/185555212-475af6d8-65bb-4f19-b808-d35b091de7a7.jpg)
我的媒体库里是有全集的，但搜索会提示只有第一季，其他剧集缺失，搜其他剧集也会提示只有第一季，其他季缺失，可否帮忙看下是什么原因

**Comment by jxxghp** [comment]
jellyfin还是emby?

**Comment by fxqq** [comment]
> jellyfin还是emby?

jellyfin
