### ISSUE TITLE
刷流工具在选择站点以后，促销和hit run 选项全部变成全部，没有办法筛选。

### ISSUE THREAD

**Issue by adsl2046** [jxxghp/nas-tools#723]
![FireShot Capture 001 - NASTool - 资源归集、整理自动化工具 - 192 168 3 254](https://user-images.githubusercontent.com/111563597/185574525-39ff63c5-0fba-4df4-8340-d03e25bce0e3.png)

**Comment by adsl2046** [comment]
测试观众站正常，但是大部分站点没有办法筛选。

**Comment by jxxghp** [comment]
确定？维护RSS地址了吗

**Comment by adsl2046** [comment]
> 确定？维护RSS地址了吗

网站维护忘记填rss地址了，现已恢复正常。
有个别网站无法筛选，不知是否是适配问题。https://club.hares.top，比如白兔这个站。

**Comment by alkalixin** [comment]
你好，我也遇到了相同的问题，已经填好了rss地址
* [hddolby](https://www.hddolby.com/)  促销和hr都只有`全部`选项
* [mt](https://kp.m-team.cc/index.php) 促销有`免费`，但是未显示`2x免费`。hr只有`全部`
* [hdatoms](https://hdatmos.club/) 促销正常，hr只有`全部`

**Comment by Pollo3470** [comment]
> 你好，我也遇到了相同的问题，已经填好了rss地址
> 
> * [hddolby](https://www.hddolby.com/)  促销和hr都只有`全部`选项
> * [mt](https://kp.m-team.cc/index.php) 促销有`免费`，但是未显示`2x免费`。hr只有`全部`
> * [hdatoms](https://hdatmos.club/) 促销正常，hr只有`全部`

有些站点是没有hr或者x2free的
