### ISSUE TITLE
新版，订阅搜索报错，jackett没有有效的索引器配置！

### ISSUE THREAD

**Issue by huiyanga** [jxxghp/nas-tools#732]
jackett是配置过的 ip  和api，测试也显示成功

09:39:58 INFO - 【SEARCHER】开始检索 奇异博士2：疯狂多元宇宙 ...
09:39:58 ERROR - 【JACKETT】没有有效的索引器配置！
09:39:58 INFO - 【SEARCHER】奇异博士2：疯狂多元宇宙 未搜索到任何资源

网页搜索是有结果的
09:47:21 INFO - 【WEB】开始检索 奇异博士2：疯狂多元宇宙 ...
09:47:22 INFO - 【JACKETT】开始并行检索 奇异博士2：疯狂多元宇宙，线程数：8 ...
09:47:22 INFO - 【JACKETT】开始检索Indexer：BTSCHOOL ...
09:47:22 INFO - 【JACKETT】开始检索Indexer：HDArea ...
09:47:22 INFO - 【JACKETT】开始检索Indexer：HDAtmos ...
09:47:22 INFO - 【JACKETT】开始检索Indexer：HDDolby ...
09:47:22 INFO - 【JACKETT】开始检索Indexer：HDFans ...
09:47:22 INFO - 【JACKETT】开始检索Indexer：HDtime ...
09:47:22 INFO - 【JACKETT】开始检索Indexer：LemonHD ...
09:47:22 INFO - 【JACKETT】开始检索Indexer：SoulVoice ...
09:47:25 WARN - 【JACKETT】BTSCHOOL 未检索到数据
09:47:26 WARN - 【JACKETT】HDDolby 返回数据：16
09:47:26 WARN - 【JACKETT】HDFans 返回数据：15

**Comment by singworld** [comment]
删除密码  无密码登录
