### ISSUE TITLE
因为开始下载导致的删除订阅后，有没有办法重新把豆瓣想看加入订阅

### ISSUE THREAD

**Issue by xiaosagemisery** [jxxghp/nas-tools#736]
有这样一种情况
搜索订阅资源如某一部电影，开始下载后删除订阅。但是豆瓣里这部电影还在想看中。
实际因为资源无人上传或其他原因，删除了下载任务，如何才能把这部想看的电影再加到订阅中？（除手动添加以外）

**Comment by jxxghp** [comment]
你自已删了，不就得自己手动加订阅了吗。。。
