### ISSUE TITLE
V2.0.1 站点维护信息没有了

### ISSUE THREAD

**Issue by leo8912** [jxxghp/nas-tools#737]
1、升级2.0后无法启动，必须PGID和PUID权限修改为0才能正常启动
2、站点维护信息看不到，但是签到、数据统计都能正常使用。RSS无法运行。user.db数据里也能看到站点信息
手动添加也无法应
![图片](https://user-images.githubusercontent.com/22719866/185776445-947e5f0f-a1cd-4e85-973a-0f120a6ba69e.png)

user.db权限改成了777也没有用
![图片](https://user-images.githubusercontent.com/22719866/185776515-2d32c324-1a47-4706-93e4-25ad6e262ad2.png)

**Comment by jxxghp** [comment]
bug了，已更新
