### ISSUE TITLE
群晖套件版更新v2.0.1后无法启动

### ISSUE THREAD

**Issue by yjb136698605** [jxxghp/nas-tools#741]
设备:群晖ds218+
出现问题:更新前正常使用,采取手动更新的方式进行更新,更新后打不开,显示无法访问此网页

**Comment by unyielding2013** [comment]
相同问题

**Comment by gudumuyu** [comment]
把puid和pgid改回0试试

**Comment by jxxghp** [comment]
2.0群晖还在打包测试中。

**Comment by yjb136698605** [comment]
> 2.0群晖还在打包测试中。

更新了最新发布的spk文件,已经可以进web界面了,辛苦大佬
