### ISSUE TITLE
群晖docker更新后所有站点消失，但服务还在

### ISSUE THREAD

**Issue by m1xds** [jxxghp/nas-tools#743]
更新后一切运行正常，但是站点全部消失了。
然而一切服务还是正常运行，测试了一下签到功能所有站点正常签到。
![6627055f064abe05154d2ac4491c806](https://user-images.githubusercontent.com/96166421/185781142-08337733-afa0-4f14-ade7-b585a50abdd4.png)
![69aded54e3ab010dffd9de94a50041c](https://user-images.githubusercontent.com/96166421/185781143-8ce7dfbe-0d61-44af-93c6-be284d885205.png)
@jxxghp

**Comment by jxxghp** [comment]
再更新一下代码

**Comment by m1xds** [comment]
更新两次过后已解决
