### ISSUE TITLE
Docker更新2.0.1提示重试太快，进入致命状态

### ISSUE THREAD

**Issue by Gu-c-c** [jxxghp/nas-tools#744]
INFO spawned: 'nas-tools' with pid 19
INFO exited: nas-tools (exit status 1; not expected)
INFO spawned: 'nas-tools' with pid 22
INFO exited: nas-tools (exit status 1; not expected)
INFO gave up: nas-tools entered FATAL state, too many start retries too quickly
 这是什么问题？我已经删除容器和镜像后重新下载最新镜像（保留配置文件)

**Comment by leonchanithotmail** [comment]
同问，一样的情况

**Comment by niexin-dev** [comment]
一样的情况
