### ISSUE TITLE
[需求]大佬能否开放提交订阅接口与overseerr或jellyseerr集成

### ISSUE THREAD

**Issue by Linyue-GitHub** [jxxghp/nas-tools#749]
集成的方式为利用这两个软件的webhook能力，在请求订阅时调用nt接口完成添加订阅。

jellyseerr项目地址
https://github.com/Fallenbagel/jellyseerr
overseerr项目地址
https://github.com/sct/overseerr

**Comment by Linyue-GitHub** [comment]
![image](https://user-images.githubusercontent.com/71179298/185801473-cd806ef0-084b-48d3-a704-ac216e467681.png)
![image](https://user-images.githubusercontent.com/71179298/185801485-8e85de2d-5609-41f0-bbdd-9f58181186c5.png)

**Comment by Linyue-GitHub** [comment]
界面特别精美，可作为nt选片界面，选好以后提交订阅给nt进行下载。支持多用户操作

**Comment by Linyue-GitHub** [comment]
隔壁mr的实现方式
https://yee329.notion.site/overseerr-jellyseerr-9096af92936f41d1b96888943c7603e5

**Comment by jxxghp** [comment]
不要引用商业项目的内容，避免引起争议
