### ISSUE TITLE
使用jackett和pt站下载，日志显示开始下载，实际没有下载的可能原因

### ISSUE THREAD

**Issue by Nemoljy** [jxxghp/nas-tools#75]
原因：没有在pt站web端下载过文件，给jackett返回的是这个提示页，而不是种子链接：
![image](https://user-images.githubusercontent.com/32947114/165959667-007f1f03-b05c-470b-9212-a440b4668bb9.png)

在jackett日志中是能看到的，但是我以为是ip和各种地址映射配错了，检查尝试了好几个小时，最后才想起来去看看Jackett的日志（小白第一次用Jackett，以前都是在pt站里复制种子直链而不是下载文件）
![image](https://user-images.githubusercontent.com/32947114/165960107-0d9da740-3795-41fe-b5ee-26c7d1d116e1.png)

可能是个Jackett常见问题吧，在其git上找到挺多类似的issue，比如：https://github.com/Jackett/Jackett/issues/13179
建议：
如果jackett的api会返回error结果的话可以在日志里加个提示，有个反馈。

**Comment by jxxghp** [comment]
请提供下这种情况JACKETT API返回的报文

**Comment by jxxghp** [comment]
这个问题不好解决，已加入常见问题
