### ISSUE TITLE
过滤规则中的大小不生效，即使不符合大小也会被匹配中

### ISSUE THREAD

**Issue by Dapong** [jxxghp/nas-tools#753]
当前版本为：v2.0.1 。我的默认过滤规则限制大小都为4G，但是匹配到4.8G的剧集时，仍被下载；在[过滤规则测试] 测试结果大小也不生效，改成22G仍会被匹配

![image](https://user-images.githubusercontent.com/16550877/185820829-6844d074-a4fb-430f-ad63-4facf4bb45f5.png)

![image](https://user-images.githubusercontent.com/16550877/185820426-a7d5bcf5-642d-40ba-b876-0fad577e71a4.png)

**Comment by jxxghp** [comment]
设为默认规则了吗？

**Comment by Dapong** [comment]
> 设为默认规则了吗？

设置为默认规则了

**Comment by jxxghp** [comment]
目前只有电影会校验大小，电视剧有很多集在一起，不好判定大小规则。
