### ISSUE TITLE
docker 2.0.1无法启动

### ISSUE THREAD

**Issue by niexin-dev** [jxxghp/nas-tools#754]
更新程序...
remote: Enumerating objects: 35, done.
remote: Counting objects:   2% (1/35)
remote: Counting objects:   5% (2/35)
remote: Counting objects:   8% (3/35)
remote: Counting objects:  11% (4/35)
remote: Counting objects:  14% (5/35)
remote: Counting objects:  17% (6/35)
remote: Counting objects:  20% (7/35)
remote: Counting objects:  22% (8/35)
remote: Counting objects:  25% (9/35)
remote: Counting objects:  28% (10/35)
remote: Counting objects:  31% (11/35)
remote: Counting objects:  34% (12/35)
remote: Counting objects:  37% (13/35)
remote: Counting objects:  40% (14/35)
remote: Counting objects:  42% (15/35)
remote: Counting objects:  45% (16/35)
remote: Counting objects:  48% (17/35)
remote: Counting objects:  51% (18/35)
remote: Counting objects:  54% (19/35)
remote: Counting objects:  57% (20/35)
remote: Counting objects:  60% (21/35)
remote: Counting objects:  62% (22/35)
remote: Counting objects:  65% (23/35)
remote: Counting objects:  68% (24/35)
remote: Counting objects:  71% (25/35)
remote: Counting objects:  74% (26/35)
remote: Counting objects:  77% (27/35)
remote: Counting objects:  80% (28/35)
remote: Counting objects:  82% (29/35)
remote: Counting objects:  85% (30/35)
remote: Counting objects:  88% (31/35)
remote: Counting objects:  91% (32/35)
remote: Counting objects:  94% (33/35)
remote: Counting objects:  97% (34/35)
remote: Counting objects: 100% (35/35)
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects:  50% (1/2)
remote: Compressing objects: 100% (2/2)
remote: Compressing objects: 100% (2/2), done.
remote: Total 18 (delta 16), reused 18 (delta 16), pack-reused 0
Unpacking objects:   5% (1/18)
Unpacking objects:  11% (2/18)
Unpacking objects:  16% (3/18)
Unpacking objects:  22% (4/18)
Unpacking objects:  27% (5/18)
Unpacking objects:  33% (6/18)
Unpacking objects:  38% (7/18)
Unpacking objects:  44% (8/18)
Unpacking objects:  50% (9/18)
Unpacking objects:  55% (10/18)
Unpacking objects:  61% (11/18)
Unpacking objects:  66% (12/18)
Unpacking objects:  72% (13/18)
Unpacking objects:  77% (14/18)
Unpacking objects:  83% (15/18)
Unpacking objects:  88% (16/18)
Unpacking objects:  94% (17/18)
Unpacking objects: 100% (18/18)
Unpacking objects: 100% (18/18), 2.03 KiB | 19.00 KiB/s, done.
From https://github.com/jxxghp/nas-tools
   547d8b8..6b57994  master     -> origin/master
Updating 547d8b8..6b57994
Fast-forward
 config.py               | 11 +++++++++--
 rmt/category.py         |  6 +++---
 rmt/media.py            |  4 ++--
 rmt/meta/metaanime.py   |  4 ++--
 rmt/meta/metabase.py    |  5 ++++-
 rmt/meta/metavideo.py   | 10 ++++++++--
 rmt/metainfo.py         |  7 ++++---
 utils/db_helper.py      |  5 ++---
 utils/indexer_helper.py |  5 ++++-
 utils/meta_helper.py    |  2 +-
 web/action.py           |  2 +-
 web/main.py             |  6 +++---
 12 files changed, 43 insertions(+), 24 deletions(-)
更新成功...
以PUID=1026，PGID=100的身份启动程序...
注意：日志将停止打印，请通过文件或WEB页面查看日志
2022-08-22 09:25:08,666 INFO RPC interface 'supervisor' initialized
2022-08-22 09:25:08,667 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-08-22 09:25:08,668 INFO supervisord started with pid 1
2022-08-22 09:25:09,672 INFO spawned: 'nas-tools' with pid 24
2022-08-22 09:25:14,678 INFO success: nas-tools entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2022-08-22 09:25:17,515 INFO exited: nas-tools (exit status 1; not expected)
2022-08-22 09:25:18,519 INFO spawned: 'nas-tools' with pid 27
2022-08-22 09:25:22,305 INFO exited: nas-tools (exit status 1; not expected)
2022-08-22 09:25:23,309 INFO spawned: 'nas-tools' with pid 30
2022-08-22 09:25:27,067 INFO exited: nas-tools (exit status 1; not expected)
2022-08-22 09:25:29,072 INFO spawned: 'nas-tools' with pid 33
2022-08-22 09:25:32,892 INFO exited: nas-tools (exit status 1; not expected)
2022-08-22 09:25:35,899 INFO spawned: 'nas-tools' with pid 36
2022-08-22 09:25:39,717 INFO exited: nas-tools (exit status 1; not expected)
2022-08-22 09:25:40,718 INFO gave up: nas-tools entered FATAL state, too many start retries too quickly

已经按
注意：2.0版本由于增加了基础依赖，如自动升级后无法启动，需要删除容器和镜像后重新下载最新镜像（配置文件可以保留）
已重新下载镜像

**Comment by niexin-dev** [comment]
将把puid和pgid改回0，可以运行

**Comment by jxxghp** [comment]
大家看下更新说明和频道

**Comment by niexin-dev** [comment]
> 大家看下更新说明和频道

大佬，请问你说的频道是指哪个？

**Comment by niexin-dev** [comment]
谢谢，我找到了

**Comment by zhangnew** [comment]
按更新说明重建镜像没用，群里的解决办法：

> v2.0.1启动问题解决办法
• [拉取历史版本的镜像](https://hub.docker.com/r/sungamma/nas-tools/tags) 
• PUID及PGID设置为0
• 进入容器使用python run.py命令手动启动
以上任选一种尝试（多嘴一句，建议使用docker）

我按最后一个操作成功了，执行之后，退出重启容器就好了，**建议写到 release 中**

**Comment by daji2010** [comment]
同样的问题，无法启动，“gave up: nas-tools entered FATAL state, too many start retries too quickly”请问如何解决的呀？谢谢！

**Comment by NidMo** [comment]
这问题解决了吗
