### ISSUE TITLE
[Bug]带空格的名称硬链接会出错

### ISSUE THREAD

**Issue by Kaol-Fu** [jxxghp/nas-tools#755]
如图，好像只要名称带有空格，同时空格前一部分的名称还能搜索到资源的话，就会以空格分割的第一部分作为刮削的名称了。
![image](https://user-images.githubusercontent.com/18643104/185821912-451cb9b8-2b09-42c0-8d85-24d28418f657.png)

**Comment by jxxghp** [comment]
给处TMDB中名字的截图以及文件名？

**Comment by jxxghp** [comment]
中英文混合中间还带空格的目前无解
