### ISSUE TITLE
unraid docker全新安装后不可使用。

### ISSUE THREAD

**Issue by yusanxing** [jxxghp/nas-tools#756]
![无标题](https://user-images.githubusercontent.com/32813254/185822533-a88579f6-69eb-4b95-a527-f0da3af239e9.png)

**Comment by jxxghp** [comment]
都不会更新说明和频道吗

**Comment by zhangnew** [comment]
按更新说明重建镜像没用，群里的解决办法：

>
    v2.0.1启动问题解决办法
    • [拉取历史版本的镜像](https://hub.docker.com/r/sungamma/nas-tools/tags) 
    • PUID及PGID设置为0
    • 进入容器使用python run.py命令手动启动
    以上任选一种尝试（多嘴一句，建议使用docker）

我按最后一个操作成功了，执行之后，退出重启容器就好了，**建议写到 release 中**
