### ISSUE TITLE
订阅功能匹配已有剧集问题

### ISSUE THREAD

**Issue by VectorZhao** [jxxghp/nas-tools#757]
![photo_2022-08-22_14-48-15](https://user-images.githubusercontent.com/16644993/185857806-18a76e62-3154-47c0-882c-53c9ca2a30fe.jpg)
**前提：**
媒体库以及emby里面均存在女浩克S01E01

**问题：**
女浩克在媒体目录中有了，命名方式如图中右侧所示，订阅去搜寻媒体库是否存在该资源的时候，正确的思路应该是匹配女浩克 S01E01 这些字段，匹配到了就说明媒体库里面是有这一集的，nastool好像匹配媒体所有字段？还是说去搜寻emby里面是否存在S01E01？

**Comment by jxxghp** [comment]
我不认为这是问题，就是这么设计的，没有你当前配置的目录及文件格式就会重新整理。就算是原样命名的一样也可以识别出S01E01，不按你当前配置的格式检查，程序哪知道你已存在的是需要整理的还是不需要整理的。

**Comment by VectorZhao** [comment]
> 我不认为这是问题，就是这么设计的，没有你当前配置的目录及文件格式就会重新整理。就算是原样命名的一样也可以识别出S01E01，不按你当前配置的格式检查，程序哪知道你已存在的是需要整理的还是不需要整理的。

没毛病，按照媒体重命名格式进行识别，这样做还可以保留多版本。
