### ISSUE TITLE
搜索页面搜索或者过滤某一季的剧集？

### ISSUE THREAD

**Issue by fxqq** [jxxghp/nas-tools#759]
目前的搜索是先搜tmdb的信息再点一次搜索所有站点的信息，我的生活大爆炸缺失第12季，但我没法单独搜索“生活大爆炸 S12”，搜索结果是显示的所有站点生活大爆炸的结果，能否在搜索界面能搜索某一季这样的功能

**Comment by jxxghp** [comment]
开豆瓣可以实现这个效果
![image](https://user-images.githubusercontent.com/51039935/185882153-b99833ff-c285-471e-88d1-75e61ef28e23.png)
