### ISSUE TITLE
配置站点时间过长，简直是一种灾难的体验感

### ISSUE THREAD

**Issue by rockhia** [jxxghp/nas-tools#760]
2.0.1配置站点信息输入太难了，一个站点要刷新好几分钟，体验感太差了。
能否开放一种类似config.yaml的配置方式。

**Comment by jxxghp** [comment]
不知道在说啥，什么东西刷新几分钟？

**Comment by jxxghp** [comment]
提问题不说清楚，标题就吐槽，不知道想表达什么

**Comment by rockhia** [comment]
在电脑上输入站点网址和cookie点击修改后，会持续好几分钟才能修改成功。如果中途点击网页其他地方导致配置退出后，又会出现锁数据库的问题。
示意图为手机截图
![Screenshot_20220822_181741](https://user-images.githubusercontent.com/90016652/185898934-7f3dc3c8-7be4-4b2d-80e7-77dcd2a65cc6.jpg)
难道只有也配置站点的时间比较长？

**Comment by jxxghp** [comment]
> 在电脑上输入站点网址和cookie点击修改后，会持续好几分钟才能修改成功。如果中途点击网页其他地方导致配置退出后，又会出现锁数据库的问题。
> 
> 示意图为手机截图
> 
> ![Screenshot_20220822_181741](https://user-images.githubusercontent.com/90016652/185898934-7f3dc3c8-7be4-4b2d-80e7-77dcd2a65cc6.jpg)
> 
> 难道只有也配置站点的时间比较长？

没有你说的这个问题，你可以问下其他人，要是普通问题早就有人说了。
