### ISSUE TITLE
在2.0之前的版本中建立的“”未开启“”的“目录同步”，在2.01版本中无法删除及修改。

### ISSUE THREAD

**Issue by daji2010** [jxxghp/nas-tools#761]
在2.0之前的版本中建立的“”未开启“”的“目录同步”，在2.01版本中无法删除及修改。
![nastool](https://user-images.githubusercontent.com/99402006/185917824-9bf02f2e-07a1-4d54-8768-123a5226b6e1.PNG)

**Comment by jxxghp** [comment]
手动在配置文件删掉吧

**Comment by daji2010** [comment]
请问：群辉套件版的配置文件在哪里可以找到，并修改？谢谢！

**Comment by jxxghp** [comment]
> 请问：群辉套件版的配置文件在哪里可以找到，并修改？谢谢！

/var/packages/nastool/target/config

**Comment by daji2010** [comment]
谢谢，修改完毕。
