### ISSUE TITLE
刷流功能希望能够判断种子状态

### ISSUE THREAD

**Issue by c77187326** [jxxghp/nas-tools#763]
在刷流时限制了下载任务数，有的种子刚上线没多久就被删了或者在其他地方手动下了这个种子，造成这几个种子一直下载不下来，刷流时，提示超出任务数，不再添加。这个这个刷流功能就卡死了。希望大佬能够添加判断种子状态，对tracker有问题的及时删除。

**Comment by jxxghp** [comment]
现在已经支持手工删种，自己手动删吧。
