### ISSUE TITLE
之前用的群辉套件版，想改成用docker版，新装2.01版，启动一直提示故障，无法启动，请支持，谢谢！

### ISSUE THREAD

**Issue by daji2010** [jxxghp/nas-tools#764]
之前用的群辉套件版，想改成用docker版，新装2.01版，启动一直提示故障，无法启动，“gave up: nas-tools entered FATAL state, too many start retries too quickly”，请问如何解决呀？谢谢！

**Comment by fxqq** [comment]
进入容器使用python run.py命令手动启动

**Comment by daji2010** [comment]
收到，谢谢！我捣鼓一下，我还得学习一下怎样进去容器使用Python来手动启动~。之前试了一下，提示没有找到run.py。

**Comment by jxxghp** [comment]
删掉镜像重拉，现在要用PUID、PGID为0启动。

**Comment by daji2010** [comment]
好的，谢谢！

**Comment by sususu98** [comment]
1. 进入容器
```
docker exec -it nas-tools bash
```
2. 修改文件权限
```
chmod 777 -R /usr/lib/python3.10/site-packages/feapder/network
```
可以使用普通用户启动

**Comment by Ashenonewjx** [comment]
> ```
> docker exec -it nas-tools chmod 777 -R /usr/lib/python3.10/site-packages/feapder/network
> ```
> 
> 可以使用普通用户启动
实测unraid可以用nobody(99:100)用户启动了

**Comment by daji2010** [comment]
用PUID、PGID为0启动成功了，但是在与emby及QB等联系时测试失败。

**Comment by daji2010** [comment]
不知道是不是与我之前用群辉套件时已经用过相关API连上过有关系？但是我已经停止了群辉套件，并且用了新生成的API也不行。
