### ISSUE TITLE
关于2.01无法启动的问题的解决方案讨论

### ISSUE THREAD

**Issue by Eronana** [jxxghp/nas-tools#765]
直接输出的日志如下, 没什么有价值的信息:
```
2022-08-22 21:30:56,338 INFO exited: nas-tools (exit status 1; not expected)
2022-08-22 21:30:57,340 INFO spawned: 'nas-tools' with pid 45
2022-08-22 21:31:04,338 INFO exited: nas-tools (exit status 1; not expected)
2022-08-22 21:31:05,340 INFO spawned: 'nas-tools' with pid 50
2022-08-22 21:31:07,131 INFO exited: nas-tools (exit status 1; not expected)
2022-08-22 21:31:08,133 INFO spawned: 'nas-tools' with pid 54
2022-08-22 21:31:09,588 INFO exited: nas-tools (exit status 1; not expected)
2022-08-22 21:31:11,591 INFO spawned: 'nas-tools' with pid 58
2022-08-22 21:31:13,163 INFO exited: nas-tools (exit status 1; not expected)
2022-08-22 21:31:16,167 INFO spawned: 'nas-tools' with pid 62
2022-08-22 21:31:17,614 INFO exited: nas-tools (exit status 1; not expected)
2022-08-22 21:31:18,615 INFO gave up: nas-tools entered FATAL state, too many start retries too quickly
```

能看到具体错误的日志位于`/var/log/supervisor/nas-tools-stdout---supervisor-2uzptjns.log`:
```
Traceback (most recent call last):
  File "/nas-tools/run.py", line 8, in <module>
    from pt.brushtask import BrushTask
  File "/nas-tools/pt/brushtask.py", line 13, in <module>
    from pt.rss import Rss
  File "/nas-tools/pt/rss.py", line 9, in <module>
    from pt.searcher import Searcher
  File "/nas-tools/pt/searcher.py", line 5, in <module>
    from pt.indexer.builtin import BuiltinIndexer
  File "/nas-tools/pt/indexer/builtin.py", line 6, in <module>
    from pt.indexer.spider import TorrentSpider
  File "/nas-tools/pt/indexer/spider.py", line 5, in <module>
    import feapder
  File "/usr/lib/python3.10/site-packages/feapder/__init__.py", line 30, in <module>
    from feapder.core.spiders import Spider, BatchSpider, AirSpider, TaskSpider
  File "/usr/lib/python3.10/site-packages/feapder/core/spiders/__init__.py", line 13, in <module>
    from feapder.core.spiders.air_spider import AirSpider
  File "/usr/lib/python3.10/site-packages/feapder/core/spiders/air_spider.py", line 17, in <module>
    from feapder.core.parser_control import AirSpiderParserControl
  File "/usr/lib/python3.10/site-packages/feapder/core/parser_control.py", line 20, in <module>
    from feapder.network.request import Request
  File "/usr/lib/python3.10/site-packages/feapder/network/request.py", line 24, in <module>
    from feapder.network.proxy_pool import ProxyPool
  File "/usr/lib/python3.10/site-packages/feapder/network/proxy_pool.py", line 24, in <module>
    os.mkdir(proxy_path)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.10/site-packages/feapder/network/proxy_file'
```
`feapder/network/proxy_pool.py`尝试创建文件`feapder/network/proxy_file`. 然而`feapder/network/proxy_file`的owner是root, 使用非root的user来运行肯定会没有权限.

`feapder`这个包由三天前引入: https://github.com/jxxghp/nas-tools/commit/603c3b39be3cb8d5874dda8e8c464288e5ccd2f6#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R28

通过阅读`feapder`的相关代码(https://github.com/Boris-code/feapder/blob/30397ddde44b72eb328213938dfa5f2cefaae520/feapder/network/proxy_pool.py#L20) 可以知道创建这个目录是用于缓存. 讲道理代码不应该修改package里面的东西.

于是解决方法大概有两个:
1. 给`feapder`提个PR, 换个地方作缓存
2. 改一下`docker/entrypoint.sh`, 给相关目录赋予权限或是直接改了`/usr/lib/python3.10`的owner

**Comment by jxxghp** [comment]
多谢大佬帮忙分析

**Comment by sususu98** [comment]
`/usr/lib/python3.10/site-packages/feapder/network`应该是容器启动后才生成的文件，方法2中在`entrypoint.sh`修改权限并不能解决问题

**Comment by sususu98** [comment]
> `/usr/lib/python3.10/site-packages/feapder/network`应该是容器启动后才生成的文件，方法2中在`entrypoint.sh`修改权限并不能解决问题

或者说不能完全解决问题，第一次启动容器，仍然不能启动，必须重启一下容器才可以

**Comment by Eronana** [comment]
> > `/usr/lib/python3.10/site-packages/feapder/network`应该是容器启动后才生成的文件，方法2中在`entrypoint.sh`修改权限并不能解决问题
> 
> 或者说不能完全解决问题，第一次启动容器，仍然不能启动，必须重启一下容器才可以

build的时候就有pip install了, 所以应该是有的
https://github.com/jxxghp/nas-tools/blob/6368dba70f647650a6d8041f8cbadd3729113390/docker/Dockerfile.base#L24

可以用这种方式验证:
```bash
docker run --rm -it --entrypoint /bin/ls jxxghp/nas-tools -lah /usr/lib/python3.10/site-packages/feapder/
total 72K
drwxr-xr-x   12 root     root        4.0K Aug 21 10:10 .
drwxr-xr-x    1 root     root        4.0K Aug 23 08:53 ..
-rw-r--r--    1 root     root           5 Aug 21 10:10 VERSION
-rw-r--r--    1 root     root         785 Aug 21 10:10 __init__.py
drwxr-xr-x    2 root     root        4.0K Aug 21 10:10 __pycache__
drwxr-xr-x    3 root     root        4.0K Aug 21 10:10 buffer
drwxr-xr-x    4 root     root        4.0K Aug 21 10:10 commands
drwxr-xr-x    4 root     root        4.0K Aug 21 10:10 core
drwxr-xr-x    3 root     root        4.0K Aug 21 10:10 db
drwxr-xr-x    3 root     root        4.0K Aug 21 10:10 dedup
drwxr-xr-x    5 root     root        4.0K Aug 21 10:10 network
drwxr-xr-x    3 root     root        4.0K Aug 21 10:10 pipelines
-rw-r--r--    1 root     root         353 Aug 21 10:10 requirements.txt
-rw-r--r--    1 root     root        9.0K Aug 21 10:10 setting.py
drwxr-xr-x    3 root     root        4.0K Aug 21 10:10 templates
drwxr-xr-x    4 root     root        4.0K Aug 21 10:10 utils
```

**Comment by sususu98** [comment]
奇怪，为啥加了PUID、PGID后owner还是root
```
docker run --rm -it -e PUID=1000  -e PGID=1000 -e UMASK=022 --entrypoint /bin/ls jxxghp/nas-tools -lah /usr/lib/python3.10/site-packages/feapder/
total 323K   
drwxr-xr-x   12 root     root          16 Aug 21 10:10 .
drwxr-xr-x  214 root     root         237 Aug 21 21:54 ..
-rw-r--r--    1 root     root           5 Aug 21 10:10 VERSION
-rw-r--r--    1 root     root         785 Aug 21 10:10 __init__.py
drwxr-xr-x    2 root     root           4 Aug 21 10:10 __pycache__
drwxr-xr-x    3 root     root           6 Aug 21 10:10 buffer
drwxr-xr-x    4 root     root           9 Aug 21 10:10 commands
drwxr-xr-x    4 root     root          10 Aug 21 10:10 core
drwxr-xr-x    3 root     root           8 Aug 21 10:10 db
drwxr-xr-x    3 root     root           7 Aug 21 10:10 dedup
drwxr-xr-x    5 root     root          12 Aug 21 10:10 network
drwxr-xr-x    3 root     root           7 Aug 21 10:10 pipelines
-rw-r--r--    1 root     root         353 Aug 21 10:10 requirements.txt
-rw-r--r--    1 root     root        9.0K Aug 21 10:10 setting.py
drwxr-xr-x    3 root     root          10 Aug 21 10:10 templates
drwxr-xr-x    4 root     root          13 Aug 21 10:10 utils
```

**Comment by sususu98** [comment]
```sh
docker exec -it nas-tools cat /nas-tools/docker/entrypoint.sh
#!/bin/sh

cd ${WORKDIR}
if [ "$NASTOOL_AUTO_UPDATE" = "true" ]; then
    if [ ! -s /tmp/requirements.txt.sha256sum ]; then
        sha256sum requirements.txt > /tmp/requirements.txt.sha256sum
    fi
    echo "更新程序..."
    git remote set-url origin ${REPO_URL} &>/dev/null
    echo "synology/" > .gitignore
    echo "windows/" >> .gitignore
    git pull
    if [ $? -eq 0 ]; then
        echo "更新成功..."
        hash_old=$(cat /tmp/requirements.txt.sha256sum)
        hash_new=$(sha256sum requirements.txt)
        if [ "$hash_old" != "$hash_new" ]; then
            echo "检测到requirements.txt有变化，重新安装依赖..."
            pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt
            if [ $? -ne 0 ]; then
                echo "无法安装依赖，请更新镜像..."
            else
                echo "依赖安装成功..."
                sha256sum requirements.txt > /tmp/requirements.txt.sha256sum
            fi
        fi
    else
        echo "更新失败，继续使用旧的程序来启动..."
    fi
else
    echo "程序自动升级已关闭，如需自动升级请在创建容器时设置环境变量：NASTOOL_AUTO_UPDATE=true"
fi

echo "以PUID=${PUID}，PGID=${PGID}的身份启动程序..."
echo "注意：日志将停止打印，请通过文件或WEB页面查看日志"
chown -R ${PUID}:${PGID} ${WORKDIR} /config /usr/lib/python3.10/
mkdir -p /config/logs/supervisor
umask ${UMASK}
exec su-exec ${PUID}:${PGID} /usr/bin/supervisord -n -c ${WORKDIR}/supervisord.conf
```

**Comment by Eronana** [comment]
镜像build  time使用的是root, runtime也是root, 所以这些文件的owner自然是root.
entrypoint.sh把前置工作完成之后, 再使用PUID:PGID来跑主程序

**Comment by sususu98** [comment]
重新创建 nas-tools
```
docker rm -f nas-tools
docker run -d \
    --name nas-tools \
    --hostname nas-tools \
    --network=host \
    -v $(pwd)/config:/config  `# 冒号左边请修改为你想在主机上保存配置文件的路径` \
    -e PUID=1000     `# 想切换为哪个用户来运行程序，该用户的uid，详见下方说明` \
    -e PGID=1000     `# 想切换为哪个用户来运行程序，该用户的gid，详见下方说明` \
    -e UMASK=022 \
    -e REPO_URL="https://ghproxy.com/https://github.com/jxxghp/nas-tools.git" \
    -e NASTOOL_AUTO_UPDATE=true `# 如需在启动容器时自动升级程程序请设置为true` \
    jxxghp/nas-tools
```
查看文件owner
```
docker exec -it nas-tools ls -l /usr/lib/python3.10/site-packages/feapder/
total 203
-rw-r--r--    1 root     root             5 Aug 21 10:10 VERSION
-rw-r--r--    1 root     root           785 Aug 21 10:10 __init__.py
drwxr-xr-x    2 root     root             4 Aug 21 10:10 __pycache__
drwxr-xr-x    3 root     root             6 Aug 21 10:10 buffer
drwxr-xr-x    4 root     root             9 Aug 21 10:10 commands
drwxr-xr-x    4 root     root            10 Aug 21 10:10 core
drwxr-xr-x    3 root     root             8 Aug 21 10:10 db
drwxr-xr-x    3 root     root             7 Aug 21 10:10 dedup
drwxr-xr-x    5 root     root            12 Aug 21 10:10 network
drwxr-xr-x    3 root     root             7 Aug 21 10:10 pipelines
-rw-r--r--    1 root     root           353 Aug 21 10:10 requirements.txt
-rw-r--r--    1 root     root          9167 Aug 21 10:10 setting.py
drwxr-xr-x    3 root     root            10 Aug 21 10:10 templates
drwxr-xr-x    4 root     root            13 Aug 21 10:10 utils
```
重启nas-tools容器，再次查看文件夹owner
```
docker restart nas-tools

docker exec -it nas-tools ls -l /usr/lib/python3.10/site-packages/feapder/
total 203
-rw-r--r--    1 1000     1000             5 Aug 21 10:10 VERSION
-rw-r--r--    1 1000     1000           785 Aug 21 10:10 __init__.py
drwxr-xr-x    2 1000     1000             4 Aug 21 10:10 __pycache__
drwxr-xr-x    3 1000     1000             6 Aug 21 10:10 buffer
drwxr-xr-x    4 1000     1000             9 Aug 21 10:10 commands
drwxr-xr-x    4 1000     1000            10 Aug 21 10:10 core
drwxr-xr-x    3 1000     1000             8 Aug 21 10:10 db
drwxr-xr-x    3 1000     1000             7 Aug 21 10:10 dedup
drwxr-xr-x    5 1000     1000            12 Aug 21 10:10 network
drwxr-xr-x    3 1000     1000             7 Aug 21 10:10 pipelines
-rw-r--r--    1 1000     1000           353 Aug 21 10:10 requirements.txt
-rw-r--r--    1 1000     1000          9167 Aug 21 10:10 setting.py
drwxr-xr-x    3 1000     1000            10 Aug 21 10:10 templates
drwxr-xr-x    4 1000     1000            13 Aug 21 10:10 utils
```

**Comment by Eronana** [comment]
> 重新创建 nas-tools
> 
> ```
> docker rm -f nas-tools
> docker run -d \
>     --name nas-tools \
>     --hostname nas-tools \
>     --network=host \
>     -v $(pwd)/config:/config  `# 冒号左边请修改为你想在主机上保存配置文件的路径` \
>     -e PUID=1000     `# 想切换为哪个用户来运行程序，该用户的uid，详见下方说明` \
>     -e PGID=1000     `# 想切换为哪个用户来运行程序，该用户的gid，详见下方说明` \
>     -e UMASK=022 \
>     -e REPO_URL="https://ghproxy.com/https://github.com/jxxghp/nas-tools.git" \
>     -e NASTOOL_AUTO_UPDATE=true `# 如需在启动容器时自动升级程程序请设置为true` \
>     jxxghp/nas-tools
> ```
> 
> 查看文件owner
> 
> ```
> docker exec -it nas-tools ls -l /usr/lib/python3.10/site-packages/feapder/
> total 203
> -rw-r--r--    1 root     root             5 Aug 21 10:10 VERSION
> -rw-r--r--    1 root     root           785 Aug 21 10:10 __init__.py
> drwxr-xr-x    2 root     root             4 Aug 21 10:10 __pycache__
> drwxr-xr-x    3 root     root             6 Aug 21 10:10 buffer
> drwxr-xr-x    4 root     root             9 Aug 21 10:10 commands
> drwxr-xr-x    4 root     root            10 Aug 21 10:10 core
> drwxr-xr-x    3 root     root             8 Aug 21 10:10 db
> drwxr-xr-x    3 root     root             7 Aug 21 10:10 dedup
> drwxr-xr-x    5 root     root            12 Aug 21 10:10 network
> drwxr-xr-x    3 root     root             7 Aug 21 10:10 pipelines
> -rw-r--r--    1 root     root           353 Aug 21 10:10 requirements.txt
> -rw-r--r--    1 root     root          9167 Aug 21 10:10 setting.py
> drwxr-xr-x    3 root     root            10 Aug 21 10:10 templates
> drwxr-xr-x    4 root     root            13 Aug 21 10:10 utils
> ```
> 
> 重启nas-tools容器，再次查看文件夹owner
> 
> ```
> docker restart nas-tools
> 
> docker exec -it nas-tools ls -l /usr/lib/python3.10/site-packages/feapder/
> total 203
> -rw-r--r--    1 1000     1000             5 Aug 21 10:10 VERSION
> -rw-r--r--    1 1000     1000           785 Aug 21 10:10 __init__.py
> drwxr-xr-x    2 1000     1000             4 Aug 21 10:10 __pycache__
> drwxr-xr-x    3 1000     1000             6 Aug 21 10:10 buffer
> drwxr-xr-x    4 1000     1000             9 Aug 21 10:10 commands
> drwxr-xr-x    4 1000     1000            10 Aug 21 10:10 core
> drwxr-xr-x    3 1000     1000             8 Aug 21 10:10 db
> drwxr-xr-x    3 1000     1000             7 Aug 21 10:10 dedup
> drwxr-xr-x    5 1000     1000            12 Aug 21 10:10 network
> drwxr-xr-x    3 1000     1000             7 Aug 21 10:10 pipelines
> -rw-r--r--    1 1000     1000           353 Aug 21 10:10 requirements.txt
> -rw-r--r--    1 1000     1000          9167 Aug 21 10:10 setting.py
> drwxr-xr-x    3 1000     1000            10 Aug 21 10:10 templates
> drwxr-xr-x    4 1000     1000            13 Aug 21 10:10 utils
> ```

`/usr/lib/python3.10/`这个目录里的文件还蛮多的, `chwon`需要一些时间. 等他完成再ls, 就是1000了
然后`chown`应该挪到`mkdir -p /config/logs/supervisor`的后面, 不然`/config/logs/supervisor`还是没权限😂

**Comment by appotry** [comment]
> > 重新创建 nas-tools
> > ```
> > docker rm -f nas-tools
> > docker run -d \
> >     --name nas-tools \
> >     --hostname nas-tools \
> >     --network=host \
> >     -v $(pwd)/config:/config  `# 冒号左边请修改为你想在主机上保存配置文件的路径` \
> >     -e PUID=1000     `# 想切换为哪个用户来运行程序，该用户的uid，详见下方说明` \
> >     -e PGID=1000     `# 想切换为哪个用户来运行程序，该用户的gid，详见下方说明` \
> >     -e UMASK=022 \
> >     -e REPO_URL="https://ghproxy.com/https://github.com/jxxghp/nas-tools.git" \
> >     -e NASTOOL_AUTO_UPDATE=true `# 如需在启动容器时自动升级程程序请设置为true` \
> >     jxxghp/nas-tools
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 查看文件owner
> > ```
> > docker exec -it nas-tools ls -l /usr/lib/python3.10/site-packages/feapder/
> > total 203
> > -rw-r--r--    1 root     root             5 Aug 21 10:10 VERSION
> > -rw-r--r--    1 root     root           785 Aug 21 10:10 __init__.py
> > drwxr-xr-x    2 root     root             4 Aug 21 10:10 __pycache__
> > drwxr-xr-x    3 root     root             6 Aug 21 10:10 buffer
> > drwxr-xr-x    4 root     root             9 Aug 21 10:10 commands
> > drwxr-xr-x    4 root     root            10 Aug 21 10:10 core
> > drwxr-xr-x    3 root     root             8 Aug 21 10:10 db
> > drwxr-xr-x    3 root     root             7 Aug 21 10:10 dedup
> > drwxr-xr-x    5 root     root            12 Aug 21 10:10 network
> > drwxr-xr-x    3 root     root             7 Aug 21 10:10 pipelines
> > -rw-r--r--    1 root     root           353 Aug 21 10:10 requirements.txt
> > -rw-r--r--    1 root     root          9167 Aug 21 10:10 setting.py
> > drwxr-xr-x    3 root     root            10 Aug 21 10:10 templates
> > drwxr-xr-x    4 root     root            13 Aug 21 10:10 utils
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 重启nas-tools容器，再次查看文件夹owner
> > ```
> > docker restart nas-tools
> > 
> > docker exec -it nas-tools ls -l /usr/lib/python3.10/site-packages/feapder/
> > total 203
> > -rw-r--r--    1 1000     1000             5 Aug 21 10:10 VERSION
> > -rw-r--r--    1 1000     1000           785 Aug 21 10:10 __init__.py
> > drwxr-xr-x    2 1000     1000             4 Aug 21 10:10 __pycache__
> > drwxr-xr-x    3 1000     1000             6 Aug 21 10:10 buffer
> > drwxr-xr-x    4 1000     1000             9 Aug 21 10:10 commands
> > drwxr-xr-x    4 1000     1000            10 Aug 21 10:10 core
> > drwxr-xr-x    3 1000     1000             8 Aug 21 10:10 db
> > drwxr-xr-x    3 1000     1000             7 Aug 21 10:10 dedup
> > drwxr-xr-x    5 1000     1000            12 Aug 21 10:10 network
> > drwxr-xr-x    3 1000     1000             7 Aug 21 10:10 pipelines
> > -rw-r--r--    1 1000     1000           353 Aug 21 10:10 requirements.txt
> > -rw-r--r--    1 1000     1000          9167 Aug 21 10:10 setting.py
> > drwxr-xr-x    3 1000     1000            10 Aug 21 10:10 templates
> > drwxr-xr-x    4 1000     1000            13 Aug 21 10:10 utils
> > ```
> 
> `/usr/lib/python3.10/`这个目录里的文件还蛮多的, `chwon`需要一些时间. 等他完成再ls, 就是1000了 然后`chown`应该挪到`mkdir -p /config/logs/supervisor`的后面, 不然`/config/logs/supervisor`还是没权限😂

这样就工作正常了

**Comment by DDS-ALL** [comment]
大佬们有没有尝试过在supervisor里面设置启动程序的user，而不是通过指定的user启动supervisor，在supervisor内设置启动用户并启动就不会出现/usr/lib/python3.10/权限不足的原因

**Comment by Eronana** [comment]
> 大佬们有没有尝试过在supervisor里面设置启动程序的user，而不是通过指定的user启动supervisor，在supervisor内设置启动用户并启动就不会出现/usr/lib/python3.10/权限不足的原因

听起来像是正解, 不过我不了解`supervisor`, 看看其他大佬怎么说

**Comment by DDS-ALL** [comment]
我目前正在测试，如果一起正常，我会把方法跟大家分享一下

**Comment by DDS-ALL** [comment]
不行，还是无法解决

**Comment by DDS-ALL** [comment]
但是在制作镜像的时候给/usr/lib/python3.10/下的所有文件777权限就可以了，并不需要给到指定用户，这样可以极大的减小等待的时间

**Comment by DDS-ALL** [comment]
这样就可以了，不需要启动的时候设置/usr/lib/python3.10/的所属用户和组
![](https://file.ddsrem.in:998//application/hide.php?key=amxUS3p4bDcvZVBYcEhQdllsek1sOVZsZTYrN3U4OS9oRFhVTXlhZFY2az0=)
![](https://file.ddsrem.in:998//application/hide.php?key=Umt1YlpwanRuamFXTlBLeDFCNFZXVm5MbHdweW15ZndJQWh1QktBalpCdz0=)

**Comment by DDS-ALL** [comment]
而且测试没有任何问题

**Comment by DDS-ALL** [comment]
其实python库安装好一般都是777权限的，但是这次这个程序引用的某些库不是777权限，而是755权限，导致无法正常使用，所以只有给到所有python库777权限就可以解决，无需给到文件指定的用户和组

**Comment by Eronana** [comment]
> 其实python库安装好一般都是777权限的，但是这次这个程序引用的某些库不是777权限，而是755权限，导致无法正常使用，所以只有给到所有python库777权限就可以解决，无需给到文件指定的用户和组

777是很危险的, 一般来说设计良好的系统是不会存在大量777权限的文件的.
就启动较慢的这个问题而言, 实际上只需要修改`/usr/lib/python3.10/site-packages/feapder/network`的owner

**Comment by DDS-ALL** [comment]
> 

但是这是Docker容器，对于Docker容器，设置777权限并不是一件危险的事

**Comment by DDS-ALL** [comment]
对于正常使用Linux，设置777权限肯定是不好的，但是Docker容器是封闭的，不会有任何风险，并且可以给用户更好的启动体验

**Comment by DDS-ALL** [comment]
并且也不能保证以后只是这个``/usr/lib/python3.10/site-packages/feapder/network``权限出现问题，如果有其他的出现权限问题，那么一个个设置是十分麻烦的，所以直接给777权限对于Docker来说并没有太大的问题

**Comment by Eronana** [comment]
> 并且也不能保证以后只是这个`/usr/lib/python3.10/site-packages/feapder/network`权限出现问题，如果有其他的出现权限问题，那么一个个设置是十分麻烦的，所以直接给777权限对于Docker来说并没有太大的问题

确实, 单就这个程序跑在docker的场景来说, 的确没什么问题.
其实问题的根源就在`feapder`不老实, 非要在package目录搞事情. 我python用得不多, 不清楚是否这是一个常规操作, 但是单从直觉上来说, 我觉得这种行为是不值得提倡的.

**Comment by DDS-ALL** [comment]
我感觉就让作者自己选择解决方案吧，反正这个问题总算是可以解决了

**Comment by jxxghp** [comment]
看到各位大佬热烈的讨论，热泪盈眶。。。

**Comment by Shurelol** [comment]
windows上打包处理feapder的问题，我是直接从python的site-packages复制了一份feapder放到nas-tools的根目录下，不知是否能提供参考

**Comment by ourpurple** [comment]
从1.9.20升上来的   提示 Permission denied: '/usr/lib/python3.10

chmod -R 777  /usr/lib/python3.9/

重启docker解决

**Comment by TucoBruto** [comment]
chown -R 1000:1000 /usr/lib
chmod -R a=,a+rX,u+w,g+w /usr/lib
重启即可
