### ISSUE TITLE
bug怎么越来越多了，大家别提新功能了啊

### ISSUE THREAD

**Issue by xxzj990** [jxxghp/nas-tools#766]
目前的功能完全够用了，最近更新了几版，导致很多问题。

1、自动订阅下载不到想要的电视剧了，基本所有订阅都错过了，要手动下
2、好多页面点击都是转圈，没反应
3、目前就自动整理的功能正常用

希望大家不要提新功能了，稳定才是最重要的。。。

**Comment by xxzj990** [comment]
加油～

**Comment by jxxghp** [comment]
1.前两点没这个问题，自己没弄好且没确切证据前不要无脑怪在升级上。
2.你可以不升级，没有让你一定要跟着升。

**Comment by xxzj990** [comment]
> 1.前两点没这个问题，自己没弄好且没确切证据前不要无脑怪在升级上。 2.你可以不升级，没有让你一定要跟着升。

大佬你别生气，没有责怪你的意思。本来就是用爱发电～～，慢慢来
