### ISSUE TITLE
在站点维护页面显示站点的优先级，方便多个站点维护优先级排序

### ISSUE THREAD

**Issue by appotry** [jxxghp/nas-tools#771]
在站点维护页面显示站点的优先级，方便多个站点维护优先级排序

如题，如果可以，可以考虑添加站点排序的时候，可以选择优先级，上传下载量等等

**Comment by weiyideai520** [comment]
站点 是什么东西？有人说详细说一下吗？不会用啊

**Comment by appotry** [comment]
> 站点 是什么东西？有人说详细说一下吗？不会用啊

你玩PT么？ 用过IYUU就知道是类似的东西

**Comment by appotry** [comment]
@jxxghp 添加这个几乎不费什么事，但很重要，防止不小心设置错了优先级

考虑什么时候支持这个优先级显示么？

**Comment by jxxghp** [comment]
不费事你自己来？还催上了？
