### ISSUE TITLE
连接TMDB出错

### ISSUE THREAD

**Issue by YoungCodeBro** [jxxghp/nas-tools#773]
![image](https://user-images.githubusercontent.com/65357891/186100023-073fe965-87e1-4708-893d-8017402b4489.png)
已经配置了全局clash代理，基础设置里也添加了http代理，我wget这个请求就能连接，在nas-tools就报错。
![image](https://user-images.githubusercontent.com/65357891/186100432-2bd55c11-86b1-4549-81cf-41c633ca47dd.png)

**Comment by Dr-Lee-Go** [comment]
我的也是这种情况，api.themoviedb.org测试不通过，求教各位大佬，已用helloword代理

**Comment by Dr-Lee-Go** [comment]
已经阅读到作者大佬关于相关问题6日前的答复“这个是你证书环境的问题”，但我查看目前的群晖证书并未过期，不知如何解决

**Comment by jxxghp** [comment]
网络的问题自己想办法解决，也不能在这里回答你

**Comment by YoungCodeBro** [comment]
> 已经阅读到作者大佬关于相关问题6日前的答复“这个是你证书环境的问题”，但我查看目前的群晖证书并未过期，不知如何解决

已解决，原理上是docker容器是一个独立的linux系统，所以访问不到主机外部的网络端口，通过创建容器时设置 --net=host ，将主机的网络暴露给容器，此时进入nastools添加代理，就可以成功使用代理端口了。
