### ISSUE TITLE
内置索引器下载提示： 添加下载失败 not a valid bencoded string！

### ISSUE THREAD

**Issue by zhixiangjoy** [jxxghp/nas-tools#776]
站点： https://hdfans.org/ （红豆饭）
问题描述： 使用内置索引器可以搜索资源，但这个站的所有资源下载时都会提示：添加下载失败 **not a valid bencoded string！**，如下图:
![image](https://user-images.githubusercontent.com/15685217/186131764-98f7d264-d4a0-40ca-820c-e67b50eeb06d.png)
![image](https://user-images.githubusercontent.com/15685217/186132640-480a61ca-adec-4039-835c-bf00341e5a99.png)

已确认站点的种子链接没有问题，手动在qb可以下载。
已确认nt下载器配置没有问题，另外一个站的资源完美下载。

日志如下：
```shell18:02:32 INFO - 下载软件设置为：qbittorrent  
18:02:32 INFO - 下载文件转移模式为：硬链接  
18:02:32 INFO - PT检索软件设置为：builtin  
18:02:32 INFO - 微信等移动端渠道搜索已开启自动择优下载  
18:02:32 INFO - PT保种时间未配置，自动删种功能已关闭  
18:02:32 INFO - 下载软件监控未开启，PT下载监控功能已关闭  
18:02:32 INFO - 开始启动进程...  
18:02:34 INFO - 【RUN】PT站自动签到服务启动...  
18:02:34 INFO - 【RUN】RSS订阅服务启动...  
18:02:34 INFO - 【RUN】豆瓣同步服务启动...  
18:04:29 ERROR - 【DOWNLOADER】下载种子文件出错：not a valid bencoded string  
18:07:27 ERROR - 【DOWNLOADER】下载种子文件出错：not a valid bencoded string

**Comment by jxxghp** [comment]
是哪个版本？检查下站点cookie是不是失效了

**Comment by zhixiangjoy** [comment]
> 是哪个版本？检查下站点cookie是不是失效了
v2.0.2和v2.0.1 都有这个问题哦，cookie是昨天添加的，站点统计和签到都是好的，刚重新添加了，也还是报这个错。网上查好像说是bencode库和种子问题。希望大佬能帮忙排查一下。

**Comment by yusanxing** [comment]
遇到同样问题，现在解决了吗？

**Comment by zhixiangjoy** [comment]
> 遇到同样问题，现在解决了吗？

目前还没

**Comment by zhixiangjoy** [comment]
> 遇到同样问题，现在解决了吗？

问题找到了，去站点下载任意一个种子，关闭弹出的第一提示页面，选择下次不再提示即可。
