### ISSUE TITLE
rclone复制失败，错误码 1536

### ISSUE THREAD

**Issue by kbnq** [jxxghp/nas-tools#777]
![微信截图_20220823182457](https://user-images.githubusercontent.com/22976092/186135348-f54303ac-08fb-4378-8df0-31b6c2f93ddb.png)

本地运行的，rclone复制失败

**Comment by zjc1994** [comment]
我也是这样，请问你解决了吗，gd上文件夹有了，但是文件没有

**Comment by jxxghp** [comment]
这个错误码我也不知道什么意思
