### ISSUE TITLE
通过微信检索影片会有循环日志的BUG提醒

### ISSUE THREAD

**Issue by w905581962** [jxxghp/nas-tools#78]
![image](https://user-images.githubusercontent.com/40052692/166087290-a20c20fd-e1f1-4b8d-8710-fdf54b469e3c.png)

**Comment by jxxghp** [comment]
正常是不会有的。
5秒一次有点像心跳检测，是不是在微信那里多配置了什么东西？

**Comment by w905581962** [comment]
感谢大佬恢复
应该没有这是我微信的配置，都是按照模板修改的
另外我想问下，微信发送消息有反应，但是点返回的剧集的图片没有反应，这个是正常的吗？
![image](https://user-images.githubusercontent.com/40052692/166096151-770893cf-df3d-4975-adb6-e2566e334c90.png)

**Comment by jxxghp** [comment]
app.domain没配置吧
