### ISSUE TITLE
无法跳过下载Emby里已存在的资源

### ISSUE THREAD

**Issue by MisakaF0406** [jxxghp/nas-tools#782]
前几天提了一个issues，关于跳过Emby中已存在资源，回复说已有这个功能，今天尝试了下发现仍然可以下载Emby里已存在的资源，Emby服务端版本：4.7.5.0和4.8.0.8均无法跳过。

作者大大能否看看这个功能是否正常呢，求求辽。

**Comment by jxxghp** [comment]
也不贴日志也不贴截图是要我猜吗？

**Comment by jxxghp** [comment]
基础的功能，我自己也在用，如果有问题很多人都会反馈，你自己有问题，那你得把问题说明白
