### ISSUE TITLE
设置-基础设置-媒体-实时刷新媒体库

### ISSUE THREAD

**Issue by xnoods** [jxxghp/nas-tools#786]
该功能目前虽然日志显示正常，但是实际上plex和emby均未实时刷新过，所以文件转移进去后plex和emby均无法识别到文件，必须手动刷新下库才能被识别到

**Comment by jxxghp** [comment]
最近确定不好使了，代码没动接口也调到了，但就是不刷新了。

**Comment by Jarvistark** [comment]
昨天还没有报错，今天我又试了下，提示
【EMBY】刷新媒体库对象 2443 失败，错误码：204，错误原因：No Content

**Comment by jxxghp** [comment]
> 昨天还没有报错，今天我又试了下，提示
> 
> 【EMBY】刷新媒体库对象 2443 失败，错误码：204，错误原因：No Content
> 
> 但是反倒能刷新成功了

我加了日志，以前是没打印。但是调用代码没变，你是emby什么版本？

**Comment by thsrite** [comment]
![image](https://user-images.githubusercontent.com/54088512/187374349-f3b60f54-73be-45a6-8aa6-0896f182c3d7.png)

emby lovechen 4.7.5.0

**Comment by zxcll** [comment]
新版本我这里只有剧集识别过的还可以实时刷新，新的电影和剧集就无法刷新了   EMBY4.8.0.8  之前也是正常的看日志刷新媒体库的请求都是一样的很离谱

**Comment by jxxghp** [comment]
这个应该好了
