### ISSUE TITLE
豆瓣识别不准确

### ISSUE THREAD

**Issue by psychopasss** [jxxghp/nas-tools#79]
![image](https://user-images.githubusercontent.com/11738089/166095492-43313a3c-30e3-44ef-8b29-6b1fc902088c.png)
![image](https://user-images.githubusercontent.com/11738089/166095497-ccbc2a14-d7a8-4c08-8bc8-3e530470db56.jpeg)

**Comment by psychopasss** [comment]
最新版本608

**Comment by jxxghp** [comment]
![Uploading 15C18ED2-E418-4EB2-9684-CBF200B09D8B.png…]()
年份不对。

**Comment by psychopasss** [comment]
![image](https://user-images.githubusercontent.com/11738089/166097428-9e35779f-bc8a-4563-8ab3-4d89d1fb8fb3.png)
没错啊

**Comment by psychopasss** [comment]
![image](https://user-images.githubusercontent.com/11738089/166097572-8696f65e-f8ce-47d2-ba22-f608a61b1336.png)
tmdb的 也没啥问题
