### ISSUE TITLE
【PT】站点 BT School 连接失败

### ISSUE THREAD

**Issue by ThierryCheng** [jxxghp/nas-tools#790]
版本：2.0.2
【PT】站点 BT School 连接失败：https://pt.btschool.club

**Comment by zhixiangjoy** [comment]
一样，签到和站点统计没问题，但是搜不出资源。按理说学校是反应最慢的一个，结果搜索的时候秒显示无匹配资源。

**Comment by yuan1** [comment]
一样，我是签到没问题，统计和搜索都出不来

**Comment by jxxghp** [comment]
这个站有盾，连不上很正常，人家就是访自动化工具的

**Comment by appotry** [comment]
@jxxghp FlareSolverr 就是解决cloudflare 盾的，可以考虑支持一下这个项目调用 jackett就支持调用这个
https://github.com/FlareSolverr/FlareSolverr

**Comment by RUANRUI1995** [comment]
但是PTPP可以哦 也许是可以解决的吧 大佬加油

**Comment by jxxghp** [comment]
> 但是PTPP可以哦 也许是可以解决的吧 大佬加油

PPT是基于浏览器运行的，完全虽真实环境，这个工具如果要集成浏览器，镜像包就会大一倍。
