### ISSUE TITLE
目录同步报检索媒体信息出错，但手动同步没有问题

### ISSUE THREAD

**Issue by cn421127** [jxxghp/nas-tools#791]
目录同步一直报 检索媒体信息出错，但没有具体出错信息，手动同步可以从tmdb获取到信息，很奇怪。。。
![image](https://user-images.githubusercontent.com/11304372/186391974-b997d994-1d75-428d-9820-e38ea9e4a9e6.png)
![image](https://user-images.githubusercontent.com/11304372/186392160-4366772b-db09-48c8-9039-719e854c4cc6.png)

**Comment by jxxghp** [comment]
我只能理解为网络不稳
