### ISSUE TITLE
当日志输出类型为日志中心时，添加标签选项

### ISSUE THREAD

**Issue by DDS-ALL** [jxxghp/nas-tools#793]
![F88ABCE2-9D80-4CE9-918F-5A21B06A2FB0](https://file.ddsrem.in:998//application/hide.php?key=cjRjZkV4WGR3ZjQvclc1WEV0dDAwQzlpWnFDZjJGdkJoNDd2Vlp3dU1aWT0=)
类似于这样，添加一个TAG选项，不然在日志中心的数据默认文件名都是``log.py.log``

**Comment by jxxghp** [comment]
不知道怎么加，知道的话贴代码
