### ISSUE TITLE
消息通知能否增加mirai和邮箱

### ISSUE THREAD

**Issue by SAENE** [jxxghp/nas-tools#794]
建议如题，因为这两个相对于其他的，是完全免费，没有收费的可能。
mirai:https://github.com/mamoe/mirai

**Comment by jxxghp** [comment]
pushplus支持邮箱，另一个没听过

**Comment by SAENE** [comment]
> 

我注意到了pushplus支持邮箱。mirai是开源的qq机器人，配置比微信公众号简单，对于公网ip没有要求，所以提出此意见
