### ISSUE TITLE
目录同步功能不认挂载目录

### ISSUE THREAD

**Issue by nicholastz** [jxxghp/nas-tools#799]
目前尝试过以下几种方式处理目录同步失效
  1.修改/etc/sysctl.conf
  2.更换宿主机
  3.重新拉取配置文件

最后发现，目录同步功能均无法在挂载网络硬盘、nfs的情况下监控，
注：但只要在容器内更改文件名后能监控

**Comment by jxxghp** [comment]
目录监控基于事件触发，本来就是不支持NFS挂载和网盘，只有SMB协议挂载的非WINDOWS共享目录才支持。

**Comment by nicholastz** [comment]
刚才查看了inotify 相关文档，貌似但凡只要是mount都不会触发
为了体验只能把nastools搬回弱小的群辉了。。
