### ISSUE TITLE
求个剪切模式

### ISSUE THREAD

**Issue by ati121** [jxxghp/nas-tools#80]
只有复制跟硬链接模式,求个剪切模式

**Comment by jxxghp** [comment]
剪切要动原来的目录，一不小心配错了很有可能导致数据损毁，不计划增加。

**Comment by easter90** [comment]
同求个剪切，需求是存量的这些影片，也想通过这个工具刷新到库里面，硬连接是不是还是存两个地方的。强迫症。或者能不能给同步目录来个单独的剪切，pt目前的复制倒是没问题，毕竟原有文件还要做种，到时间也会清理。存量的电影如果复制的话一是占空间，二是复制起来对于转移的工作还是有点慢。
不知道我是不是理解的对，如果理解不对还请大佬指点，谢谢！

**Comment by jxxghp** [comment]
硬链接过去，再把原来的删了就行了

**Comment by easter90** [comment]
> 硬链接过去，再把原来的删了就行了

试了一下，果然硬链接就是我想要的，不知道题主还有啥需求，我觉得硬链接转移我的数据就已经满足我的需求了，还是自己没理解硬链接的原理。目前已经完美运行了，转移的速度也蛮快的。谢谢大佬
