### ISSUE TITLE
linux的docker版在无法连接到tmdb时自动退出没有提示

### ISSUE THREAD

**Issue by noname0emmm** [jxxghp/nas-tools#804]
今天重新装了系统，开始重新配置nas-tools，发现每次填完tmdb api key后就无法启动，查看日志只提示检测到退出代码15。
反复清空配置尝试后找不到问题，突然响起tmdb hosts还没有配置，重新配置后nas-tools能正常启动了。推测是由于启动是从tmdb获取封面图片，获取失败后没有正常处理，直接抛出异常就退出了

**Comment by jxxghp** [comment]
分析过了就贴结论，别猜
