### ISSUE TITLE
目前最新版本不能识别m2ts格式文件

### ISSUE THREAD

**Issue by fxqq** [jxxghp/nas-tools#805]
之前是可以的，现在发现最新版本不能识别出m2ts格式的文件
![IMG_20220826_085713](https://user-images.githubusercontent.com/30470143/186794821-9a93e00d-8d9d-4726-bd40-95b13246e69e.jpg)
![IMG_20220826_085740](https://user-images.githubusercontent.com/30470143/186794833-2b5d9071-bcc5-40c2-9d27-e2f9269702a0.jpg)

**Comment by ZevAlain** [comment]
我也遇到了同样的问题。下载的权游有几季识别不到。

**Comment by jxxghp** [comment]
这个加上后会导致原盘出问题

**Comment by fxqq** [comment]
> 这个加上后会导致原盘出问题

(T^T)那有解决办法吗？能加个开关吗？比如我基本不看我原盘，但空有些特效字幕是m2ts格式，如果需要硬连原盘了再把识别m2ts

**Comment by Pollo3470** [comment]
我有两部电影是m2ts格式的也都无法同步，建议解决一下这个问题

**Comment by Pollo3470** [comment]
我发现天空的AQLJ特效字幕的电影和电视剧全都是m2ts，头疼

**Comment by Pollo3470** [comment]
感谢更新，帮大忙了，作者大大yyds!
