### ISSUE TITLE
下载种子文件出错：not a valid bencoded string

### ISSUE THREAD

**Issue by chcGolang** [jxxghp/nas-tools#806]
版本: v2.0.2
**界面错误提示**:
![image](https://user-images.githubusercontent.com/41823338/186803158-09ee53e0-b565-47c3-a2cd-0f8372192ed6.png)

**日志错误内容:**
```
17:55:08 WARN - 【INDEXER】audiences 返回数据：15
17:55:08 INFO - 【INDEXER】Rose War S01E35-E36 2022 2160p WEB-DL H265 AAC-ADWeb 匹配成功
17:55:08 INFO - 【INDEXER】Rose War S01E31-E34 2022 2160p WEB-DL H265 AAC-ADWeb 匹配成功
17:55:08 INFO - 【INDEXER】Rose War S01E27-E30 2022 2160p WEB-DL H265 AAC-ADWeb 匹配成功
17:55:08 INFO - 【INDEXER】Rose War S01E25-E26 2022 2160p WEB-DL H265 AAC-ADWeb 匹配成功
17:55:08 INFO - 【INDEXER】Rose War S01E23-E24 2022 2160p WEB-DL H265 AAC-ADWeb 匹配成功
17:55:08 INFO - 【INDEXER】Rose War S01E21-E22 2022 2160p WEB-DL H265 AAC-ADWeb 匹配成功
17:55:08 INFO - 【INDEXER】Rose War S01E19-E20 2022 2160p WEB-DL H265 AAC-ADWeb 匹配成功
17:55:08 INFO - 【INDEXER】Rose War S01E17-E18 2022 2160p WEB-DL H265 AAC-ADWeb 匹配成功
17:55:08 INFO - 【INDEXER】Rose War S01E15-E16 2022 2160p WEB-DL H265 AAC-ADWeb 匹配成功
17:55:08 INFO - 【INDEXER】Rose War S01E13-E14 2022 2160p WEB-DL H265 AAC-ADWeb 匹配成功
17:55:08 INFO - 【INDEXER】Rose War S01E11-E12 2022 2160p WEB-DL H265 AAC-ADWeb 匹配成功
17:55:08 INFO - 【INDEXER】Rose War S01E09-E10 2022 2160p WEB-DL H265 AAC-ADWeb 匹配成功
17:55:08 INFO - 【INDEXER】Rose War S01E07-E08 2022 2160p WEB-DL H265 AAC-ADWeb 匹配成功
17:55:08 INFO - 【INDEXER】Rose War S01E05-E06 2022 2160p WEB-DL H265 AAC-ADWeb 匹配成功
17:55:08 INFO - 【INDEXER】Rose War S01E01-E04 2022 2160p WEB-DL H265 AAC-ADWeb 匹配成功
17:55:08 INFO - 【INDEXER】audiences 共检索到 15 条数据，过滤 0，不匹配 0，有效资源 15，耗时 3 秒
17:55:08 INFO - 【INDEXER】所有站点检索完成，有效资源数：18，总耗时 3 秒
17:55:08 INFO - 【DOWNLOADER】添加下载任务：Rose War S01E35-E36 2022 2160p WEB-DL H265 AAC-ADWeb ...
17:55:10 ERROR - 【DOWNLOADER】下载种子文件出错：not a valid bencoded string
17:55:10 ERROR - 【DOWNLOADER】添加下载任务 玫瑰之战 (2022) 失败：not a valid bencoded string
17:55:10 INFO - 【MSG】发送wechat消息：title=添加下载任务失败：玫瑰之战 (2022) S01 E35-E36, text=种子：Rose War S01E35-E36 2022 2160p WEB-DL H265 AAC-ADWeb 错误信息：not a valid bencoded string
17:55:12 INFO - 【DOWNLOADER】添加下载任务：Rose War S01E31-E34 2022 2160p WEB-DL H265 AAC-ADWeb ...
17:55:15 ERROR - 【DOWNLOADER】下载种子文件出错：not a valid bencoded string
17:55:15 ERROR - 【DOWNLOADER】添加下载任务 玫瑰之战 (2022) 失败：not a valid bencoded string
17:55:15 INFO - 【MSG】发送wechat消息：title=添加下载任务失败：玫瑰之战 (2022) S01 E31-E34, text=种子：Rose War S01E31-E34 2022 2160p WEB-DL H265 AAC-ADWeb 错误信息：not a valid bencoded string
17:55:15 INFO - 【DOWNLOADER】添加下载任务：Rose War S01E27-E30 2022 2160p WEB-DL H265 AAC-ADWeb ...
17:55:18 ERROR - 【DOWNLOADER】下载种子文件出错：not a valid bencoded string
17:55:18 ERROR - 【DOWNLOADER】添加下载任务 玫瑰之战 (2022) 失败：not a valid bencoded string
17:55:18 INFO - 【MSG】发送wechat消息：title=添加下载任务失败：玫瑰之战 (2022) S01 E27-E30, text=种子：Rose War S01E27-E30 2022 2160p WEB-DL H265 AAC-ADWeb 错误信息：not a valid bencoded string
17:55:19 INFO - 【SEARCHER】玫瑰之战 未下载到资源
17:55:20 INFO - 【RSS】更新电视剧 玫瑰之战 (2022) S01 缺失集数为 4
17:57:56 ERROR - 【DOWNLOADER】下载种子文件出错：not a valid bencoded string
```

m-team站点正常, audiences 站点则错误

**Comment by jxxghp** [comment]
触发了种子第一次下载吧？你进站点手动下种子看有没有提示界面？

**Comment by chcGolang** [comment]
> 触发了种子第一次下载吧？你进站点手动下种子看有没有提示界面？

已经试过了,不行

**Comment by jxxghp** [comment]
> > 触发了种子第一次下载吧？你进站点手动下种子看有没有提示界面？
> 
> 已经试过了,不行

什么叫试过了不行？你这回答怎么往后分析。。。

**Comment by chcGolang** [comment]
> > > 触发了种子第一次下载吧？你进站点手动下种子看有没有提示界面？
> > 
> > 
> > 已经试过了,不行
> 
> 什么叫试过了不行？你这回答怎么往后分析。。。

下载种子了,没提示界面,也用种子去下载电影下了,然后回去重新试,也是一样的错误

**Comment by chcGolang** [comment]
> > > > 触发了种子第一次下载吧？你进站点手动下种子看有没有提示界面？
> > > 
> > > 
> > > 已经试过了,不行
> > 
> > 
> > 什么叫试过了不行？你这回答怎么往后分析。。。
> 
> 下载种子了,没提示界面,也用种子去下载电影下了,然后回去重新试,也是一样的错误

![image](https://user-images.githubusercontent.com/41823338/186823274-7900ee26-7661-4124-9cb8-9c04f5470aaf.png)
不知道是不是这个原因

**Comment by jxxghp** [comment]
> > > > > 触发了种子第一次下载吧？你进站点手动下种子看有没有提示界面？
> 
> > > > 
> 
> > > > 
> 
> > > > 已经试过了,不行
> 
> > > 
> 
> > > 
> 
> > > 什么叫试过了不行？你这回答怎么往后分析。。。
> 
> > 
> 
> > 下载种子了,没提示界面,也用种子去下载电影下了,然后回去重新试,也是一样的错误
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/41823338/186823274-7900ee26-7661-4124-9cb8-9c04f5470aaf.png)
> 
> 不知道是不是这个原因
> 
> 

不是，我没有这个站测试不了，看看有没有人有相同问题吧。

**Comment by Pollo3470** [comment]
> > > > > > 触发了种子第一次下载吧？你进站点手动下种子看有没有提示界面？
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > 已经试过了,不行
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 什么叫试过了不行？你这回答怎么往后分析。。。
> > 
> > 
> > > 
> > 
> > 
> > > 下载种子了,没提示界面,也用种子去下载电影下了,然后回去重新试,也是一样的错误
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/41823338/186823274-7900ee26-7661-4124-9cb8-9c04f5470aaf.png)
> > 不知道是不是这个原因
> 
> 不是，我没有这个站测试不了，看看有没有人有相同问题吧。

我的观众也是一样的问题，估计是站点适配的原因

09:41:44 INFO - 【DOWNLOADER】添加下载任务：House of the Dragon S01E01 2022 2160p HMAX WEB-DL x265 HDR DV DDP5.1 Atmos-ADWeb ...
09:42:27 ERROR - 【DOWNLOADER】下载种子文件出错：not a valid bencoded string
09:42:27 ERROR - 【DOWNLOADER】添加下载任务 龙之家族 (2022) 失败：not a valid bencoded string
09:42:27 INFO - 【MSG】发送telegram消息：title=添加下载任务失败：龙之家族 (2022) S01 E01, text=种子：House of the Dragon S01E01 2022 2160p HMAX WEB-DL x265 HDR DV DDP5.1 Atmos-ADWeb 错误信息：not a valid bencoded string
09:42:28 INFO - 【SEARCHER】龙之家族 未下载到资源

**Comment by Pollo3470** [comment]
> > > > > > > 触发了种子第一次下载吧？你进站点手动下种子看有没有提示界面？
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > > 已经试过了,不行
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > 什么叫试过了不行？你这回答怎么往后分析。。。
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 下载种子了,没提示界面,也用种子去下载电影下了,然后回去重新试,也是一样的错误
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/41823338/186823274-7900ee26-7661-4124-9cb8-9c04f5470aaf.png)
> > > 不知道是不是这个原因
> > 
> > 
> > 不是，我没有这个站测试不了，看看有没有人有相同问题吧。
> 
> 我的观众也是一样的问题，估计是站点适配的原因
> 
> 09:41:44 INFO - 【DOWNLOADER】添加下载任务：House of the Dragon S01E01 2022 2160p HMAX WEB-DL x265 HDR DV DDP5.1 Atmos-ADWeb ... 09:42:27 ERROR - 【DOWNLOADER】下载种子文件出错：not a valid bencoded string 09:42:27 ERROR - 【DOWNLOADER】添加下载任务 龙之家族 (2022) 失败：not a valid bencoded string 09:42:27 INFO - 【MSG】发送telegram消息：title=添加下载任务失败：龙之家族 (2022) S01 E01, text=种子：House of the Dragon S01E01 2022 2160p HMAX WEB-DL x265 HDR DV DDP5.1 Atmos-ADWeb 错误信息：not a valid bencoded string 09:42:28 INFO - 【SEARCHER】龙之家族 未下载到资源

朋友站也是这个问题

09:45:31 INFO - 【INDEXER】开始检索 龙之家族，站点：['朋友'] ...
09:45:31 INFO - 【INDEXER】开始检索Indexer：朋友 ...
09:45:33 WARN - 【INDEXER】朋友 返回数据：1
09:45:33 INFO - 【INDEXER】House of the Dragon S01E01 2022 2160p WEB-DL x265 AC3￡cXcY@FRDS 匹配成功
09:45:33 INFO - 【INDEXER】朋友 共检索到 1 条数据，过滤 0，不匹配 0，有效资源 1，耗时 2 秒
09:45:33 INFO - 【INDEXER】所有站点检索完成，有效资源数：1，总耗时 2 秒
09:45:33 INFO - 【DOWNLOADER】添加下载任务：House of the Dragon S01E01 2022 2160p WEB-DL x265 AC3￡cXcY@FRDS ...
09:45:54 ERROR - 【DOWNLOADER】下载种子文件出错：not a valid bencoded string
09:45:54 ERROR - 【DOWNLOADER】添加下载任务 龙之家族 (2022) 失败：not a valid bencoded string
09:45:54 INFO - 【MSG】发送telegram消息：title=添加下载任务失败：龙之家族 (2022) S01 E01, text=种子：House of the Dragon S01E01 2022 2160p WEB-DL x265 AC3￡cXcY@FRDS 错误信息：not a valid bencoded string
09:45:56 INFO - 【SEARCHER】龙之家族 未下载到资源

**Comment by Pollo3470** [comment]
> > > > > > > > 触发了种子第一次下载吧？你进站点手动下种子看有没有提示界面？
> > > > 
> > > > 
> > > > > > >
> > > > 
> > > > 
> > > > > > >
> > > > 
> > > > 
> > > > > > > 已经试过了,不行
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > 什么叫试过了不行？你这回答怎么往后分析。。。
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > 下载种子了,没提示界面,也用种子去下载电影下了,然后回去重新试,也是一样的错误
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/41823338/186823274-7900ee26-7661-4124-9cb8-9c04f5470aaf.png)
> > > > 不知道是不是这个原因
> > > 
> > > 
> > > 不是，我没有这个站测试不了，看看有没有人有相同问题吧。
> > 
> > 
> > 我的观众也是一样的问题，估计是站点适配的原因
> > 09:41:44 INFO - 【DOWNLOADER】添加下载任务：House of the Dragon S01E01 2022 2160p HMAX WEB-DL x265 HDR DV DDP5.1 Atmos-ADWeb ... 09:42:27 ERROR - 【DOWNLOADER】下载种子文件出错：not a valid bencoded string 09:42:27 ERROR - 【DOWNLOADER】添加下载任务 龙之家族 (2022) 失败：not a valid bencoded string 09:42:27 INFO - 【MSG】发送telegram消息：title=添加下载任务失败：龙之家族 (2022) S01 E01, text=种子：House of the Dragon S01E01 2022 2160p HMAX WEB-DL x265 HDR DV DDP5.1 Atmos-ADWeb 错误信息：not a valid bencoded string 09:42:28 INFO - 【SEARCHER】龙之家族 未下载到资源
> 
> 朋友站也是这个问题
> 
> 09:45:31 INFO - 【INDEXER】开始检索 龙之家族，站点：['朋友'] ... 09:45:31 INFO - 【INDEXER】开始检索Indexer：朋友 ... 09:45:33 WARN - 【INDEXER】朋友 返回数据：1 09:45:33 INFO - 【INDEXER】House of the Dragon S01E01 2022 2160p WEB-DL x265 AC3￡cXcY@FRDS 匹配成功 09:45:33 INFO - 【INDEXER】朋友 共检索到 1 条数据，过滤 0，不匹配 0，有效资源 1，耗时 2 秒 09:45:33 INFO - 【INDEXER】所有站点检索完成，有效资源数：1，总耗时 2 秒 09:45:33 INFO - 【DOWNLOADER】添加下载任务：House of the Dragon S01E01 2022 2160p WEB-DL x265 AC3￡cXcY@FRDS ... 09:45:54 ERROR - 【DOWNLOADER】下载种子文件出错：not a valid bencoded string 09:45:54 ERROR - 【DOWNLOADER】添加下载任务 龙之家族 (2022) 失败：not a valid bencoded string 09:45:54 INFO - 【MSG】发送telegram消息：title=添加下载任务失败：龙之家族 (2022) S01 E01, text=种子：House of the Dragon S01E01 2022 2160p WEB-DL x265 AC3￡cXcY@FRDS 错误信息：not a valid bencoded string 09:45:56 INFO - 【SEARCHER】龙之家族 未下载到资源

应该是索引器不支持站点导致的，rss正常

**Comment by xtomb** [comment]
hddolly也是同样的问题，可以搜索但无法下载种子。
版本：2.0.3
索引器：内建索引器
站点地址：https://www.hddolby.com/details.php?id=60938&hit=1
<img width="289" alt="image" src="https://user-images.githubusercontent.com/15191058/187950579-2959182d-6007-4030-b97c-ffb6b706f68f.png">

`2022-09-01 23:13:08,136 INFO: 【EMBY】开始刷新Emby媒体库...
2022-09-01 23:13:08,151 INFO: 【EMBY】Emby媒体库刷新完成
2022-09-01 23:13:08,151 INFO: 【RMT】/mnt/data/download/movie/Top.Gun.Maverick.2022.2160p.WEB-DL.DDP5.1.Atmos.HDR.HEVC-HDSWEB 处理完成，总数：1，失败：0
2022-09-01 23:13:08,152 INFO: 【SUBTITLE】开始从Opensubtitle.org检索字幕: Top Gun Maverick
2022-09-01 23:16:45,528 INFO: 【META】Top Gun 识别到 电影：TMDBID=744, 名称=壮志凌云, 上映日期=1986-05-16
2022-09-01 23:16:47,364 ERROR: 【DOWNLOADER】下载种子文件出错：下载种子出现异常，not a valid bencoded string
`

**Comment by jxxghp** [comment]
最新的代码，试了下是可以下载的。
