### ISSUE TITLE
RSS订阅不正确匹配

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#813]
Being a Hero S01E17 2022 1080p LINETV WEB-DL x264 AAC-ADWeb[冰雨火 第17集 | 类型: 剧情 / 犯罪 主演: 陈晓 / 王一博 / 王劲松 / 刘奕君 / 赵昭仪 *内封简繁中字*]

**Comment by thsrite** [comment]
![Uploading 950EB239-CEAF-4E2E-B829-9AF0CA7AB699.png…]()

**Comment by thsrite** [comment]
![Uploading A0C708CB-C054-44C2-B89C-BEE5C6C7ABD0.png…]()

**Comment by thsrite** [comment]
![Uploading 4B887806-2FF7-48EA-AFFA-66CD117C7B82.png…]()

**Comment by thsrite** [comment]
SO1E12 2022 1080p TVING WEB-DL ×264 AAC
ADWeb[零和岛游戏/ 第12期|类型：真人秀 主演
张圣圭 /韩惠珍/ 李伊庚 / 宋雨琦]
00:48:49 INFO- 【RSS】 开始处理：Witch Hunt SO1E04
22022 1080p TVING WEB-DL x264 AAC-ADWeb[魔女狩猎
2022/ 2022 第04期| 类型：脱口秀 主演：申东烨/
金利娜/ 金兴西]
00:48:49 INFO- 【RSS】 开始处理：Being a Hero SO1E17
拷贝
查询
翻译
学习..
共享
奕君/ 赵昭仪*内封简繁中字*
D0:48:49 INFO - 【RSSI Being a Hero SO1E17 2022
1080p LINETV WEB-DL x264 AAC-ADWeb [冰兩火 第17集
1类型：剧情/ 犯罪 主演：陈晓/王一博/ 王劲松/刘奕君/赵
昭仪*内封简繁中字*大小：1.03G促销：免费 不符合过滤
规则
00:48:49 INFO - (RSS) Being a Hero S01E17 2022
1080p LINETV WEB-DL x264 AAC-ADWeb[冰兩火 第17集
1类型：剧情/犯罪 主演：陈晓/王一博/王劲松/刘奕君/赵
昭仪 *内封简繁中字灯冰雨火（2022）不匹配订阅
00:48:49 INFO- 【RSS】 开始处理：Line of Duty S02
2014 1080p Blu-ray x265 AC3£CXCY@FRDS[重任在肩/反
腐先锋 第二季 中英字幕/官方简中字幕 BBC出品 HEVC版本]
00:48:49 INFO - (RSS] Line of Duty S02 2014 1080p
Blu-ray x265 AC3£ CXCY@FRDS[重任在肩/反腐先锋 第二
季中英字幕/官方简中字幕 BBC出品 HEVC版本]重任在肩
（2012） 不匹配订阅
00:48:49 INFO- 【RSS】 开始处理：erpent 2017 1080p
BIURay AVC DTS-HD MA 5.1[致命毒蛇 / Serpent | 类别：
惊悚]
00:48:49 INFO- 【RSS】 开始处理：The Vampire Diaries

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/187021696-50f913ac-8ae9-445e-b20a-2d7a947c32a4.png)
![image](https://user-images.githubusercontent.com/16237201/187021712-4c96ec8c-8221-4b16-96bb-4e9372550612.png)
你的过滤规则是什么？

**Comment by thsrite** [comment]
> ![image](https://user-images.githubusercontent.com/16237201/187021696-50f913ac-8ae9-445e-b20a-2d7a947c32a4.png)
> ![image](https://user-images.githubusercontent.com/16237201/187021712-4c96ec8c-8221-4b16-96bb-4e9372550612.png)
> 你的过滤规则是什么？

默认的过滤规则，没改过。而且刚才我看了看，日常观影里面没有优先级是10的过滤规则

**Comment by thsrite** [comment]
柠檬站

**Comment by jxxghp** [comment]
> D0:48:49 INFO - 【RSSI Being a Hero SO1E17 2022 1080p LINETV WEB-DL x264 AAC-ADWeb [冰兩火 第17集 类型：剧情/ 犯罪 主演：陈晓/王一博/ 王劲松/刘奕君/赵昭仪*内封简繁中字*大小：1.03G促销：免费 不符合过滤规则
> 
> 00:48:49 INFO - (RSS) Being a Hero S01E17 2022 1080p LINETV WEB-DL x264 AAC-ADWeb[冰兩火 第17集 类型：剧情/犯罪 主演：陈晓/王一博/王劲松/刘奕君/赵昭仪 *内封简繁中字灯冰雨火（2022）不匹配订阅
> 
> 000:48:49 INFO- 【RSS】 开始处理：The Vampire Diaries

你这个日志是自已改过吗？贴上原来的完整的日志，以及规划那里你点亮了小星的那个规划截图。

**Comment by thsrite** [comment]
![Uploading C944C619-4439-4ACC-ABB2-13135ADF2957.png…]()

**Comment by thsrite** [comment]
> > D0:48:49 INFO - 【RSSI Being a Hero SO1E17 2022 1080p LINETV WEB-DL x264 AAC-ADWeb [冰兩火 第17集 类型：剧情/ 犯罪 主演：陈晓/王一博/ 王劲松/刘奕君/赵昭仪_内封简繁中字_大小：1.03G促销：免费 不符合过滤规则
> > 00:48:49 INFO - (RSS) Being a Hero S01E17 2022 1080p LINETV WEB-DL x264 AAC-ADWeb[冰兩火 第17集 类型：剧情/犯罪 主演：陈晓/王一博/王劲松/刘奕君/赵昭仪 *内封简繁中字灯冰雨火（2022）不匹配订阅
> > 000:48:49 INFO- 【RSS】 开始处理：The Vampire Diaries
> 
> 你这个日志是自已改过吗？贴上原来的完整的日志，以及规划那里你点亮了小星的那个规划截图。
![IMG_1953](https://user-images.githubusercontent.com/54088512/187054700-80914dd3-df27-4332-8f54-f581f06ca9a6.PNG)
![1](https://user-images.githubusercontent.com/54088512/187054742-cc394a34-1d31-4793-ac77-0b3f12c6f3e6.png)
![2](https://user-images.githubusercontent.com/54088512/187054745-40255ac3-2f5d-4c7e-8efe-78608e23dd4f.png)
![3](https://user-images.githubusercontent.com/54088512/187054751-04fdc895-a389-45dc-a83a-d37a31b5d313.png)
![4](https://user-images.githubusercontent.com/54088512/187054754-b0199526-8113-4360-b876-d28cc14a35fc.png)
![5](https://user-images.githubusercontent.com/54088512/187054756-8c4f6cce-17d9-4483-9a79-c7ab1c8b0bfc.png)
![6](https://user-images.githubusercontent.com/54088512/187054757-db36a124-5bd9-4de4-beaa-7fc2c1009d5c.png)
![7](https://user-images.githubusercontent.com/54088512/187054758-f1faaea0-094e-415e-8dd2-12ee9224a01c.png)
