### ISSUE TITLE
aria2连接错误，报500

### ISSUE THREAD

**Issue by YoungCodeBro** [jxxghp/nas-tools#814]
查阅部分资料，aria2的url默认是ip:6800/jsonrpc，项目路由是/rpc，导致不必要的更改。
正确填写aria2下载器地址后，出现连接500的错误，调试后应该是代码内部错误，非aria2下载服务
![image](https://user-images.githubusercontent.com/65357891/186995808-ac98e65b-65c0-40e4-b715-85152dee87e2.png)

**Comment by jxxghp** [comment]
使用的就是rpc接口，可以正常使用。旧版本测试会假失败，最新代码已修复。
