### ISSUE TITLE
未完成的剧集订阅被自动删除

### ISSUE THREAD

**Issue by Pollo3470** [jxxghp/nas-tools#820]
01:41:02 INFO - 【RSS】共有 1 个电视剧订阅需要检索
01:41:03 INFO - 【META】正在查询TMDB电视剧：94997 ...
01:41:03 INFO - 【META】正在查询TMDB电视剧：94997 ...
01:41:03 INFO - 【DOWNLOADER】龙之家族 (2022) 第1季 共有 10 集
01:41:03 INFO - 【DOWNLOADER】龙之家族 (2022) 第1季 缺失 10 集
01:41:03 INFO - 【SEARCHER】开始检索 龙之家族 ...
01:41:03 INFO - 【INDEXER】开始并行检索 龙之家族，线程数：1 ...
01:41:03 INFO - 【INDEXER】开始检索Indexer：天空 ...
01:41:06 WARN - 【INDEXER】天空 返回数据：6
01:41:06 INFO - 【INDEXER】House of the Dragon S01 2022 2160p HMAX WEB-DL DDP5.1 Atmos HDR DV HEVC-AQLJ@HDSky 匹配成功
01:41:06 INFO - 【INDEXER】House of the Dragon S01 2022 1080p HMAX WEB-DL DDP5.1 Atmos H264-AQLJ@HDSky 大小：4.44G 促销：免费 不符合订阅过滤规则
01:41:06 INFO - 【INDEXER】House of the Dragon S01E01 2160p HMAX WEB-DL DDP5.1 Dovi HDR HEVC-HDSWEB 大小：8.32G 促销：免费 不符合订阅过滤规则
01:41:06 INFO - 【INDEXER】House of the Dragon S01E01 The Heirs of the Dragon DV 2160p HMAX WEB-DL DDPA5.1 H.265-NTb 大小：8.33G 促销：免费 不符合订阅过滤规则
01:41:06 INFO - 【INDEXER】House of the Dragon S01E01 The Heirs of the Dragon HDR 2160p HMAX WEB-DL DDPA5.1 H.265-NTb 大小：8.31G 促销：免费 不符合订阅过滤规则
01:41:06 INFO - 【INDEXER】House of the Dragon S01E01 The Heirs of the Dragon 1080p WEBRip DD5.1 x264-MiU 大小：2.3G 促销：免费 不符合订阅过滤规则
01:41:06 INFO - 【INDEXER】天空 共检索到 6 条数据，过滤 5，不匹配 0，有效资源 1，耗时 3 秒
01:41:06 INFO - 【INDEXER】所有站点检索完成，有效资源数：1，总耗时 3 秒
01:41:06 INFO - 【DOWNLOADER】添加下载任务：House of the Dragon S01 2022 2160p HMAX WEB-DL DDP5.1 Atmos HDR DV HEVC-AQLJ@HDSky ...
01:41:08 INFO - 【DOWNLOADER】添加下载任务：xxxxx
01:41:09 INFO - 【MSG】发送telegram消息：title=龙之家族 (2022) S01 评分：8.9, text=RSS订阅的电视剧 龙之家族 (2022)S01 已开始下载 站点：天空 质量：WEB-DL 2160p 大小：8.83G 种子：House of the Dragon S01 2022 2160p HMAX WEB-DL DDP5.1 Atmos HDR DV HEVC-AQLJ@HDSky 做种数：481 促销：免费 描述：龙之家族 / 龙族 / 权力的游戏前传 / 坦格利安 / 龙王家族 / 龙之堡【DIY 简繁英四特效字幕】家族纷争 再掀血龙狂舞 *衣柜字幕+魏书浮雕字体*
01:41:10 INFO - 【SEARCHER】实际下载了 1 个资源
01:41:10 INFO - 【RSS】电视剧 龙之家族 下载完成，删除订阅...

**Comment by jxxghp** [comment]
搜索时天空有显示副标题吗？

**Comment by Pollo3470** [comment]
有副标题

**Comment by Pollo3470** [comment]
还有一个问题，这个特效字幕版本是m2ts格式的，没有办法同步目录

**Comment by jxxghp** [comment]
> 有副标题

找一下上面这个种子的副标题

**Comment by Pollo3470** [comment]
龙之家族 / 龙族 / 权力的游戏前传 / 坦格利安 / 龙王家族 / 龙之堡【DIY 简繁英四特效字幕】家族纷争 再掀血龙狂舞 *衣柜字幕+魏书浮雕字体*

**Comment by jxxghp** [comment]
> 龙之家族 / 龙族 / 权力的游戏前传 / 坦格利安 / 龙王家族 / 龙之堡【DIY 简繁英四特效字幕】家族纷争 再掀血龙狂舞 *衣柜字幕+魏书浮雕字体*

这也没写集数啊，种子名没写、副标题也不写，谁发的种子，拉黑吧。

**Comment by Pollo3470** [comment]
> > 龙之家族 / 龙族 / 权力的游戏前传 / 坦格利安 / 龙王家族 / 龙之堡【DIY 简繁英四特效字幕】家族纷争 再掀血龙狂舞 _衣柜字幕+魏书浮雕字体_
> 
> 这也没写集数啊，种子名没写、副标题也不写，谁发的种子，拉黑吧。

啊这，确实有点离谱。那m2ts格式问题有办法解决吗

**Comment by Pollo3470** [comment]
![image](https://user-images.githubusercontent.com/90445326/187052152-39202f0c-1238-45b1-9547-2a7b88b74d9f.png)
我跟作者提出了m2ts的问题，请问一下ts格式会不会识别？

**Comment by jxxghp** [comment]
> ![image](https://user-images.githubusercontent.com/90445326/187052152-39202f0c-1238-45b1-9547-2a7b88b74d9f.png)
> 
> 我跟作者提出了m2ts的问题，请问一下ts格式会不会识别？
> 
> 
> 
> 

会，有另一个问题在，而且我打了标记

**Comment by Pollo3470** [comment]
> > 龙之家族 / 龙族 / 权力的游戏前传 / 坦格利安 / 龙王家族 / 龙之堡【DIY 简繁英四特效字幕】家族纷争 再掀血龙狂舞 _衣柜字幕+魏书浮雕字体_
> 
> 这也没写集数啊，种子名没写、副标题也不写，谁发的种子，拉黑吧。

集数的问题作者回复是忘记标注了
