### ISSUE TITLE
已经删除的电影重新下载问题

### ISSUE THREAD

**Issue by zhouxingchiaiguanxiaodan** [jxxghp/nas-tools#822]
豆瓣点了想看的电影，nastools开始下载了，看完之后我给删除了。之后我想重新下载回来，我重新点击了豆瓣的想看，发现重新下不回来了，nastools没有反应，我在nastools里边找的rss订阅也存在同样问题。查看日志发现，我在删除的时候日志有显示我删除，然后我再重新点击豆瓣同步，日志就不再显示了，好像是默认我豆瓣想看中已经下载过的电影不会再重新下载。而且我在豆瓣中把豆瓣想看的电影删除，再重新添加到想看，然后点击nastools中的豆瓣同步，也依然不会下载，日志也没有任何显示，我是不是需要改什么设置。

**Comment by jxxghp** [comment]
你都手动干预了不就得手动去下了吗
