### ISSUE TITLE
无法打开索引器界面（2.0.2）

### ISSUE THREAD

**Issue by RockyHalf** [jxxghp/nas-tools#823]
版本：v2.0.2
环境：群晖7.0.1，安装docker版本nastools
其他设置均配置完成，tmdb连通性测试通过，索引器配置的是jackett

问题：
最初配置的是用jackett进行检索，可以正常使用。
但是无法打开设置中的索引器界面，一点击就闪屏，无法对索引器界面进行修改和配置，已经尝试过重启容器，仍然无效，无法打开索引器界面。希望能解决，谢谢

**Comment by pandaxk001** [comment]
我也是同样的问题，Torznab Feed/地址等还没配置

**Comment by RockyHalf** [comment]
> 我也是同样的问题，Torznab Feed/地址等还没配置

请问Torznab Feed/地址在哪里配置呀，配置完成就可以解决了么

**Comment by RockyHalf** [comment]
> 我也是同样的问题，Torznab Feed/地址等还没配置

是jackett里面那个吗，那个我配置好过了

**Comment by xq4894253** [comment]
2.0.3同样问题，维护完站点后无法打开索引器界面

**Comment by jxxghp** [comment]
修复了
