### ISSUE TITLE
【需求】与overseerr或jellyseerr集成

### ISSUE THREAD

**Issue by Linyue-GitHub** [jxxghp/nas-tools#824]
集成的方式为利用这两个软件的webhook能力，在请求订阅时调用nt接口完成添加订阅。界面特别精美，可作为nt选片界面，选好以后提交订阅给nt进行下载。支持多用户操作，可以作为除了微信、电报、网页端订阅外的另一种选择，不再依赖VPS做代理服务器。
jellyseerr项目地址
https://github.com/Fallenbagel/jellyseerr
overseerr项目地址
https://github.com/sct/overseerr

![image](https://user-images.githubusercontent.com/71179298/187060097-58bf117f-d623-48b3-8fc7-7d23a2effbb9.png)
![image](https://user-images.githubusercontent.com/71179298/187060177-20862891-c7d9-4497-97d1-2d36b190f819.png)

**Comment by Xinse111** [comment]
希望添加！之前在群里看有人谈论这个，界面啥的确实独具一格！不依赖🪜也是一个优点，可以让家里人用起来没有什么阻碍和间歇性烦恼（指🪜问题）！

感谢作者大大🥰🥰🥰

**Comment by 1051181650** [comment]
之前交流群有人谈论这个，界面选片确实很漂亮 ，希望作者大大添加接口 ，让nt更完美 更优秀 更上一层楼  ！！ 让追剧变得更简单 ~ 越来也好 
再次特别感谢作者大大辛苦维护   ~~
