### ISSUE TITLE
m2ts格式的支持

### ISSUE THREAD

**Issue by 26712681** [jxxghp/nas-tools#826]
天空最近很多这种格式的电影，但是好像不支持

![image](https://user-images.githubusercontent.com/77581926/187066535-f242c2de-e512-41aa-9b13-8a72e5c86456.png)
![image](https://user-images.githubusercontent.com/77581926/187066551-a14b2e31-1ead-480b-8cd7-89f91587d96e.png)

**Comment by jxxghp** [comment]
更新下代码
