### ISSUE TITLE
重装后默认的过滤规则丢失

### ISSUE THREAD

**Issue by Pollo3470** [jxxghp/nas-tools#827]
重新安装了docker版nastool，过滤规则为空

**Comment by jxxghp** [comment]
打开配置文件，init_files 下面清空，重启。

**Comment by Pollo3470** [comment]
配置文件是指config.ymal吗？里面并没有找到init_files

**Comment by Pollo3470** [comment]
目前的情况是全新安装都没有预置的过滤规则
