### ISSUE TITLE
豆瓣列表页面和点击图片后的弹出的浮动页面评价不一致

### ISSUE THREAD

**Issue by Skyzhu881** [jxxghp/nas-tools#83]
在豆瓣xxx页面中，每个媒体显示的评分，与点击该媒体的图片显示的媒体介绍中显示的评分不一致
推测点击该媒体后显示的评分是从TMDB来的，而不是豆瓣

但是这个显示逻辑很迷惑人

**Comment by Skyzhu881** [comment]
补充图片
![Snipaste_2022-05-02_12-43-35](https://user-images.githubusercontent.com/7289765/166186793-c25aab6e-8085-44bf-b782-28eaa23563ab.png)
![Snipaste_2022-05-02_12-43-46](https://user-images.githubusercontent.com/7289765/166186794-eb59087e-33b1-442b-9e93-17effb8d079f.png)

**Comment by jxxghp** [comment]
豆瓣木有接口，确实略显尴...
最新代码从前一个页面传过去了。
