### ISSUE TITLE
2.03会出现2.01无法启动问题 

### ISSUE THREAD

**Issue by Howe-Huang** [jxxghp/nas-tools#830]
报错和2.01一样 我退回2.02 关闭更新，才能启动

**Comment by Howe-Huang** [comment]
报错和2.01一样  我退回2.02 关闭更新

**Comment by wangrui1573** [comment]
一样，首页无法打开

**Comment by fj8023p** [comment]
打不开+1

**Comment by link2fun** [comment]
[![image.png](https://i.postimg.cc/vT7tyrW6/image.png)](https://postimg.cc/9wM7tqgW)

docker 版 已无法启动 2.02 -> 2.03

**Comment by Howe-Huang** [comment]
更新公告里面有这么一句 
注意：如自动更新无法启动，仍需删除后拉取新镜像，如不想自动更新请拉取固定版本号镜像同时关闭自动更新开关。
我重装可以了

**Comment by link2fun** [comment]
> 更新公告里面有这么一句 注意：如自动更新无法启动，仍需删除后拉取新镜像，如不想自动更新请拉取固定版本号镜像同时关闭自动更新开关。 我重装可以了

重启无用
删除重装有用
```shell
docker stop 容器名
docker rm 容器名
docker rmi jxxghp/nas-tools 
docker pull jxxghp/nas-tools
# 然后手动创建
```
另外公告在哪写的...没看到

**Comment by Howe-Huang** [comment]
> 

发布Release2.03 界面说明

**Comment by link2fun** [comment]
> > 
> 
> 发布Release2.03 界面说明

...........可能升级的太早了, release 里面还没有发版说明.........
现在看到了, 下回先等发版说明出来再升级了......
