### ISSUE TITLE
文件转移失败，目的路径不存在！

### ISSUE THREAD

**Issue by boboink** [jxxghp/nas-tools#834]
11:47:22 INFO - 【QB】设置qBittorrent种子状态成功
11:47:22 INFO - 【RMT】开始处理：/Download/movies/Swan.Song.2021.1080p.APTV.WEB-DL.DDP5.1.Atmos.H.264-CMRG.mkv，转移方式：硬链接
11:47:24 ERROR - 【RMT】文件转移失败，目的路径不存在！
11:47:24 INFO - 【RMT】/Download/movies/Swan.Song.2021.1080p.APTV.WEB-DL.DDP5.1.Atmos.H.264-CMRG.mkv 处理完成，总数：1，失败：1
以上是日志
使用“下载文件转移”，取消目录同步，一直转移失败

**Comment by KyoMio** [comment]
下载转移请把下载器配置里面检查一下，下载器的路径填下载器容器里的下载路径，后面填本容器的路径。
