### ISSUE TITLE
[2.0.3]docker 版本无法打开网页

### ISSUE THREAD

**Issue by wcz0** [jxxghp/nas-tools#837]
version: 2.0.3
alpine好像有些问题, 不能解析域名
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/22549312/187145413-2edd84e6-fab9-4505-8f08-73e4084d11ba.png">

**Comment by KyoMio** [comment]
改个host模式试试

**Comment by wcz0** [comment]
好像是ubuntu的问题, 我用其他软件也遇到了相同的问题
