### ISSUE TITLE
请问有没有遇到“消息中心”提醒已经开始下载某影片，但是实际上qB里又没有加入下载任务的情况？

### ISSUE THREAD

**Issue by daji2010** [jxxghp/nas-tools#838]
请问有没有遇到“消息中心”提醒已经开始下载某影片，但是实际上qB里又没有加入下载任务的情况？
在“近期下载”中有记录，订阅取消，但是实际上并没有下载。

**Comment by daji2010** [comment]
试了一下，手动搜索后点击下载，显示加入下载，但是实际上没有加入，测试下载器和索引器都测试成功。

**Comment by Jamesecob** [comment]
我最近遇到qB的一个小问题可能跟你差不多，添加任务后，正在下载的确在下载，但是qB没有看到任务，后来查了下是qB的一个问题，把游览器清除缓存或者换个游览器，就能看到正常下载任务了

**Comment by lizhen789** [comment]
碰到过

**Comment by KyoMio** [comment]
好像是部分站点的适配原因，获取到的链接没办法被qb识别吧。应该是这些站点的种子链接里有特殊符号之类的。

**Comment by KyoMio** [comment]
> 好像是部分站点的适配原因，获取到的链接没办法被qb识别吧。应该是这些站点的种子链接里有特殊符号之类的，python获取链接为字符串以后碰到转义字符了可能。

**Comment by daji2010** [comment]
谢谢！
