### ISSUE TITLE
Windows v2.0.3 打开有问题

### ISSUE THREAD

**Issue by bigdongdongCLUB** [jxxghp/nas-tools#839]
<img width="451" alt="截屏2022-08-29 17 53 58" src="https://user-images.githubusercontent.com/43647204/187175500-4b9a1877-d63d-4a43-9cb0-31128b5c982e.png">
反而v2.0.2是没问题的。

**Comment by KyoMio** [comment]
缺模块了，win版本没办法，等作者重新打包吧。

**Comment by bigdongdongCLUB** [comment]
> 缺模块了，win版本没办法，等作者重新打包吧。

了解，感谢

**Comment by jxxghp** [comment]
知道了，等重新打包吧，最近变动比较大，依赖一变就很麻烦
