### ISSUE TITLE
微信下载影片问题

### ISSUE THREAD

**Issue by Skyzhu881** [jxxghp/nas-tools#84]
1. 通过微信发送“aaa”，它会错误的匹配“类型：电视剧，标题：aaa，年份：2017”
2. 通过微信发送“沙丘 2021”，通过日志看到能搜索到资源并且微信也能看到它返回的资源信息，但是最终返回信息“沙丘 2021 搜索结果中没有符合下载条件的资源”。通过日志发现两个问题
第一， 事实上搜索到资源，但是添加下载的时候：	
>>ERROR: 【PT】添加PT任务出错：timeout when connection to transmission daemon 
>>ERROR: 【PT】添加下载任务失败：沙丘 (2021)。
>而给微信发送的消息是：
>> INFO: 【MSG】发送wechat消息：title=添加PT任务失败：沙丘 (2021), text=
>>INFO: 【SEARCHER】沙丘 2021 搜索结果中没有符合下载条件的资源

第二，通过微信添加下载任务时会失败，timeout when connection to transmission daemon 。但是通过NASTOOL网页端是测试正常的，通过资源搜索之后再传送到Transmission下载正常。

![20220502191616](https://user-images.githubusercontent.com/7289765/166225542-840779df-ff9e-48a5-a6c4-10b0c0cdfe3a.jpg)
[log1.txt](https://github.com/jxxghp/nas-tools/files/8602452/log1.txt)

**Comment by Skyzhu881** [comment]
又重新看了log和最终下载的文件，发现最后一次微信添加下载任务成功了。通过网页端nastool添加的下载任务失败。。。
nastool和transmission在同一台机器，都通过docker搭建的，按说不太可能出现连接问题。。

**Comment by jxxghp** [comment]
1. tmdb里就有叫aaa的
2. 这个错是下载软件返回的，请检查环境或种子。
