### ISSUE TITLE
字幕识别问题

### ISSUE THREAD

**Issue by ltsj** [jxxghp/nas-tools#843]
使用目录转移时 后缀.zh-cn.ass的字幕会被重命名为成 .ass 其他.sc.ass .chs.ass 也是一样

**Comment by ltsj** [comment]
https://github.com/jxxghp/nas-tools/issues/712 和这个是一样的情况

**Comment by jxxghp** [comment]
我记得改过了，是新版本吗

**Comment by jxxghp** [comment]
贴个字幕名上来？  #712 改了，没发现哪里还有问题

**Comment by ltsj** [comment]
版本号 v2.0.3 原文件名 晴空 S01E02.zh-cn.ass 识别后文件名 晴空 - S01E02.ass 使用的目录转移
![image](https://user-images.githubusercontent.com/30733960/187388415-53c62fe9-f37c-4e80-90a8-b6289149cf3c.png)

**Comment by ltsj** [comment]
又试了下 chs 好像可以正确识别 zh-cn不行

**Comment by jxxghp** [comment]
没道理啊。。。
![image](https://user-images.githubusercontent.com/51039935/187449769-c27de11e-8c14-4c8b-9200-39ae31dd01b3.png)

**Comment by ltsj** [comment]
暂时不清楚啥情况 但我这边确实是这样子的 chs移动识别正常 zh-cn不行... 实在不行就不纠结了

**Comment by jxxghp** [comment]
> 暂时不清楚啥情况 但我这边确实是这样子的 chs移动识别正常 zh-cn不行... 实在不行就不纠结了

发个日志看看

**Comment by ltsj** [comment]
找到原因了 有部分字幕是 zh-cn.default.ass /(ㄒoㄒ)/~~  谢谢大佬解答
