### ISSUE TITLE
v2.0.3版本，点击【索引器选项】无反应

### ISSUE THREAD

**Issue by JKnuts** [jxxghp/nas-tools#847]
删除容器，删除镜像，群晖docker重新装的2.0.3版本
目前遇到2个问题：
1. 默认的一套过滤规则消失了，该页面直接空白
2. 点击索引器选项无反应，就闪一下

**Comment by sungamma** [comment]
这个问题我也遇到过，删掉旧的config.yml,重新配置时，索引器选项无反应。我是用回了旧的配置才OK

**Comment by jxxghp** [comment]
修复了
