### ISSUE TITLE
requirements.txt请更新下，缺少库

### ISSUE THREAD

**Issue by 5536086** [jxxghp/nas-tools#848]
requirements.txt请更新下，缺少库

**Comment by zaizhuzhu123** [comment]
哈哈 我也启动不起来了

**Comment by huluohu** [comment]
> 哈哈 我也启动不起来了

- docker exec -it nastools /bin/bash
- 执行 `python3 run.py`,看看提示缺什么
- `pip3 install xxx` ,缺什么装什么
- 都不缺了，再次执行 `python3 run.py`

**Comment by 5536086** [comment]
> 



> > 哈哈 我也启动不起来了
> 
> * docker exec -it nastools /bin/bash
> * 执行 `python3 run.py`,看看提示缺什么
> * `pip3 install xxx` ,缺什么装什么
> * 都不缺了，再次执行 `python3 run.py`

嗯，我已经弄好了，根据提示安装了新库才行

**Comment by jxxghp** [comment]
拉最新的境像还有问题吗？现在依赖分两部分，一部分在requirements.txt里，另一部分在third_party.txt里，third_party.txt里的是使用的源代码方式运行。

**Comment by jxxghp** [comment]
只要是拉取了最新镜像应该是没问题的
