### ISSUE TITLE
不识别重命名直接对目录进行硬链接同步下大小限制失效

### ISSUE THREAD

**Issue by jifengguo** [jxxghp/nas-tools#85]
不识别重命名直接对目录进行硬链接同步下大小限制失效，会把所有影响做种的图片及nfo文档也硬链接。
建议参考Hlink，提供个硬链接黑白名单供用户自定义，比大小限制更实用。大小限制没法把原盘中需要的小文件跟影响做种的图片等文件区分开来。有黑白名单，不需要大小选项也可以。

**Comment by jxxghp** [comment]
不要通过issues提功能需求

**Comment by jifengguo** [comment]
> 不要通过issues提功能需求
@jxxghp 

不提功能要求，那这个模式下硬链接大小限制失效有修复计划么？
硬链接了nfo跟图片到Emby下，Emby刮削修改了文件严重影响做种。几千上万个种子，因为这个经常一片错误。
