### ISSUE TITLE
rss订阅  馒头已配置rss却未下载到数源

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#853]
馒头已配置rss连接，且连接可以打开且返回数据

![image](https://user-images.githubusercontent.com/54088512/187356399-a3764d35-5648-4899-a28c-60fb1a9fa393.png)

**Comment by thsrite** [comment]
![image](https://user-images.githubusercontent.com/54088512/187356505-8a407845-299b-44d3-9ef2-3605c3b21f1e.png)

**Comment by jxxghp** [comment]
这个可能就是那会刚好连不上，多观察

**Comment by thsrite** [comment]
确实是，现在好了。
