### ISSUE TITLE
基础设置-服务-只管理NASTool添加的下载无效

### ISSUE THREAD

**Issue by xq4894253** [jxxghp/nas-tools#855]
下载软件监控，勾选了“只管理NASTool添加的下载”，但是下载器直接添加的种子下载结束后也会自动执行转移操作。

2.0.2套件版 2.0.3docker版均有该问题

环境：群晖6.2.3
下载器：qb 4.3.9 套件版

**Comment by jxxghp** [comment]
2.0.4版本做了一些调整，请看下是否有解决，如未解决按新模板要求上传可能相关的日志等信息，不然没法分析。
