### ISSUE TITLE
2.03版本刷流添加下载任务出错

### ISSUE THREAD

**Issue by langzizhui** [jxxghp/nas-tools#857]
![image](https://user-images.githubusercontent.com/69033923/187405559-bc00edbe-547f-4aa6-8ab9-beeff42a16da.jpeg)![image](https://user-images.githubusercontent.com/69033923/187405614-df5786a8-52c6-4a9f-9044-bdf970f1ee0f.jpeg)

qb是4.4.4套件版

**Comment by wangrui1573** [comment]
我遇到过这个错误，原因是站点的RSS地址为jacket生成的，后来我改成站点本身的就好了

**Comment by langzizhui** [comment]
> 我遇到过这个错误，原因是站点的RSS地址为jacket生成的，后来我改成站点本身的就好了

我一直就是站点本身的rss，好像不是这个原因

**Comment by JAM2199562** [comment]
> 这个没法分析，下载器返回失败且没有返回错误原因，自己排查下吧。

![image](https://user-images.githubusercontent.com/10511667/187714246-094232a8-5dc7-4b0d-94ad-b1c473c42549.png)
抓包分析了一下，我猜@langzizhui 打算刷流的PT站应该也启用了cloudflare，从流程上来看，qBittorrent在收到增加种子的请求以后直接向目标站发起了下载种子的请求，这部分流量加密的看不出，但猜测应该是cloudflare的那个检查导致的，不知道nas-tools是否能够增加一个使用flaresolverr的功能

**Comment by langzizhui** [comment]
> > 这个没法分析，下载器返回失败且没有返回错误原因，自己排查下吧。
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/10511667/187714246-094232a8-5dc7-4b0d-94ad-b1c473c42549.png)
> 
> 抓包分析了一下，我猜@langzizhui 打算刷流的PT站应该也启用了cloudflare，从流程上来看，qBittorrent在收到增加种子的请求以后直接向目标站发起了下载种子的请求，这部分流量加密的看不出，但猜测应该是cloudflare的那个检查导致的，不知道nas-tools是否能够增加一个使用flaresolverr的功能

解决了，还真是rss的原因，我复制错了，谢谢

**Comment by JAM2199562** [comment]
> > > 这个没法分析，下载器返回失败且没有返回错误原因，自己排查下吧。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/10511667/187714246-094232a8-5dc7-4b0d-94ad-b1c473c42549.png)
> > 抓包分析了一下，我猜@langzizhui 打算刷流的PT站应该也启用了cloudflare，从流程上来看，qBittorrent在收到增加种子的请求以后直接向目标站发起了下载种子的请求，这部分流量加密的看不出，但猜测应该是cloudflare的那个检查导致的，不知道nas-tools是否能够增加一个使用flaresolverr的功能
> 
> 解决了，还真是rss的原因，我复制错了，谢谢
那请问你访问的站用了cloudflare了吗？
