### ISSUE TITLE
今天突然启动不了docker了，查看日志文件提示如下，求教解决方案！

### ISSUE THREAD

**Issue by 21tc-sea** [jxxghp/nas-tools#859]
[https://pixhost.to/show/98/303121078__20220830190137.jpg](url)

**Comment by SAENE** [comment]
我的也是

**Comment by fxqq** [comment]
python run.py 如果提示缺文件，就pip3 install xxx,缺啥装啥，装完后再python run.py

**Comment by jxxghp** [comment]
有拉取最新的镜像吗？今天中午打的包。

**Comment by alkalixin** [comment]
我的也是。

**Comment by mbskter** [comment]
请问最新编译的release怎么没有群晖的安装包呀？

**Comment by 21tc-sea** [comment]
> 有拉取最新的镜像吗？今天中午打的包。

我看日志是有提示更新成功，不知道是不是APP自己会更新，以前好像不会自己更新吧？
日志“更新成功…”的下一行是“以PUID＝0，PGID＝0的身份启动程序…”，跟这个有关系吗？重启了几次了，还是这样子的，有没有什么排障的建议？

**Comment by Shurelol** [comment]
> 请问最新编译的release怎么没有群晖的安装包呀？

已停止支持，群晖套件现在矿神和裙下孤魂两个大佬在做

**Comment by 21tc-sea** [comment]
> python run.py 如果提示缺文件，就pip3 install xxx,缺啥装啥，装完后再python run.py

已经用这个办法成功解决！谢谢！

**Comment by alkalixin** [comment]
> 有拉取最新的镜像吗？今天中午打的包。

我重新下载了docker镜像，可以启动了。 但是之前的日志也是提示更新成功的

**Comment by kanmanli** [comment]
群晖里的docker镜像无法下载，是怎么回事？
日志：Failed to pull image [Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)].
不能手动升级到2.0.3，然后删除了镜像重新下载就下载不了了

**Comment by jxxghp** [comment]
无法启动的，都是没有重置和下载新镜像导致的：删除或者重置当前容器，重新下载最新镜像。配置文件目录不要删所有数据都不会丢。
