### ISSUE TITLE
jquery 加载失败，是否考虑打包到工程内，不再外部加载？

### ISSUE THREAD

**Issue by BarryLoo** [jxxghp/nas-tools#863]
### 情况如图

![image](https://user-images.githubusercontent.com/12878832/187514944-8601a01c-dc72-4312-990f-861c8f19b56c.png)

**Comment by jxxghp** [comment]
这是哪来的，本项目没有引用外部JS呀，都是打包进来的，可以看下代码。
看报错你是chrome装了什么插件?
