### ISSUE TITLE
远程访问nas-tools非常慢，反应速度差以至于无法操作。

### ISSUE THREAD

**Issue by superain7** [jxxghp/nas-tools#866]
通过域名加端口号，http://域名:端口
远程进行访问，但总是会出现图片断裂，菜单无法操作的情况。反应特别慢。
<a href="https://imgloc.com/i/aCVGy"><img src="https://s1.328888.xyz/2022/08/31/aCVGy.png" alt="aCVGy.png" border="0"></a>
请指教。

**Comment by jxxghp** [comment]
你的网络问题吧，我们都是这么玩的，没有问题
