### ISSUE TITLE
搜索报错

### ISSUE THREAD

**Issue by tobarcn** [jxxghp/nas-tools#867]
08:59:48 INFO - 【WEB】开始检索 茶杯头大冒险 第二季 ...
08:59:48 INFO - 【INDEXER】开始并行检索 茶杯头大冒险，线程数：3 ...
08:59:48 INFO - 【INDEXER】开始检索Indexer：m-team ...
08:59:48 INFO - 【INDEXER】开始检索Indexer：hdchina ...
08:59:48 INFO - 【INDEXER】开始检索Indexer：beitai ...
08:59:50 WARN - 【INDEXER】beitai 未检索到数据
08:59:50 WARN - 【SPIDER】错误：Expected an argument, got <DELIM '[' at 29> - Traceback (most recent call last): File "/nas-tools/app/indexer/client/spider.py", line 328, in parse for torn in doc(torrents_selector): File "/usr/lib/python3.10/site-packages/pyquery/pyquery.py", line 261, in __call__ result = self._copy(*args, parent=self, **kwargs) File "/usr/lib/python3.10/site-packages/pyquery/pyquery.py", line 247, in _copy return self.__class__(*args, **kwargs) File "/usr/lib/python3.10/site-packages/pyquery/pyquery.py", line 232, in __init__ xpath = self._css_to_xpath(selector) File "/usr/lib/python3.10/site-packages/pyquery/pyquery.py", line 243, in _css_to_xpath return self._translator.css_to_xpath(selector, prefix) File "/usr/lib/python3.10/site-packages/cssselect/xpath.py", line 192, in css_to_xpath for selector in parse(css)) File "/usr/lib/python3.10/site-packages/cssselect/parser.py", line 415, in parse return list(parse_selector_group(stream)) File "/usr/lib/python3.10/site-packages/cssselect/parser.py", line 428, in parse_selector_group yield Selector(*parse_selector(stream)) File "/usr/lib/python3.10/site-packages/cssselect/parser.py", line 454, in parse_selector next_selector, pseudo_element = parse_simple_selector(stream) File "/usr/lib/python3.10/site-packages/cssselect/parser.py", line 542, in parse_simple_selector result = Function(result, ident, parse_arguments(stream)) File "/usr/lib/python3.10/site-packages/cssselect/parser.py", line 563, in parse_arguments raise SelectorSyntaxError( cssselect.parser.SelectorSyntaxError: Expected an argument, got <DELIM '[' at 29>
08:59:51 WARN - 【INDEXER】hdchina 未检索到数据
08:59:53 WARN - 【INDEXER】m-team 返回数据：1

**Comment by jxxghp** [comment]
重复问题

**Comment by tobarcn** [comment]
#861
