### ISSUE TITLE
求加入企业微信webhook机器人的通知方式 以及 通知多选方式

### ISSUE THREAD

**Issue by yanyu469** [jxxghp/nas-tools#868]
企业微信webhook可以不限制条目数，接入也简单，还不受几个平台的通知条目数的限制，求考虑加入。

**Comment by huluohu** [comment]
需要有自己的服务器才行。
可参考：https://post.smzdm.com/p/aev4dp7m/

**Comment by jxxghp** [comment]
webhook一样逃不掉IP限制的问题吧，且要拉群才能用。
