### ISSUE TITLE
有未知报错，哪里能看出错代码

### ISSUE THREAD

**Issue by HBSpy** [jxxghp/nas-tools#869]
手动识别出现

>500
>出错啦！

>系统出错了，请检查运行日志看看吧...

但日志中并没有报错

>10:24:12 INFO - 【META】正在查询TMDB电视剧：19885 ...
>10:24:12 INFO - 【RMT】开始处理：/video/TV/Sherlock.S03.1080p.BluRay.x264-DON，转移方式：硬链接
>10:24:12 INFO - 【RMT】正在转移文件：3x01 The Empty Hearse.mkv 到 /video/Links/欧美剧/神探夏洛克 (2010)/Season 3/神探夏洛克 - S03E01 - 第1集.mkv
>10:24:12 INFO - 【RMT】文件 3x01 The Empty Hearse.mkv 硬链接完成
>10:24:12 INFO - 【RMT】正在转移文件：3x02 The Sign of Three.mkv 到 /video/Links/欧美剧/神探夏洛克 (2010)/Season 3/神探夏洛克 - S03E02 - 第2集.mkv
>10:24:12 INFO - 【RMT】文件 3x02 The Sign of Three.mkv 硬链接完成
>10:24:13 INFO - 【RMT】正在转移文件：3x03 His Last Vow.mkv 到 /video/Links/欧美剧/神探夏洛克 (2010)/Season 3/神探夏洛克 - S03E03 - 第3集.mkv
>10:24:13 INFO - 【RMT】文件 3x03 His Last Vow.mkv 硬链接完成

问问哪里能看具体报错的代码，也方便调试

**Comment by HBSpy** [comment]
自己贴一下 trouble shooting 过程给个参考好了

docker exec -it 到容器内部用 supervisorctl `tail -f nas-tools` 查看错误日志

> [2022-08-31 11:12:24,112] ERROR in app: Exception on /do [POST]
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
>     return current_app.ensure_sync(func)(*args, **kwargs)
>   File "/nas-tools/web/main.py", line 1400, in do
>     return WebAction().action(cmd, data)
>   File "/nas-tools/web/action.py", line 126, in action
>     return func(data)
>   File "/nas-tools/web/action.py", line 529, in __rename
>     succ_flag, ret_msg = FileTransfer().transfer_media(in_from=SyncType.MAN,
>   File "/nas-tools/app/filetransfer.py", line 713, in transfer_media
>     self.mediaserver.refresh_library_by_items(refresh_library_items)
>   File "/nas-tools/app/mediaserver/media_server.py", line 103, in refresh_library_by_items
>     return self.server.refresh_library_by_items(items)
>   File "/nas-tools/app/mediaserver/server/plex.py", line 143, in refresh_library_by_items
>     return self.__plex.library.update()
> AttributeError: 'NoneType' object has no attribute 'library'

原因为 media_server 没连上，所以 self.__plex 是 None，错误没 catch，导致 500，对话框无法正常关闭

我用的 media_server 是 plex，连不上的原因为 (429) too_many_requests，目前不知道为什么，自己在开发环境下都没问题，不知道是不是 nas-tools 用的太狠了

目前的解决方法

1. 在基础设置中关闭 实时刷新媒体库 refresh_mediaserver
2. 改改代码，把这个 500 catch 住

**Comment by jxxghp** [comment]
supervisor的日志是有输出到config/logs目录下的
