### ISSUE TITLE
feat support

### ISSUE THREAD

**Issue by GideonSenku** [jxxghp/nas-tools#870]
hello，我是 iOS/Scriptable 桌面脚本开发者，我想在iOS中写一个各个站点数据的小组件， 查看了一下关于 nas-tools 中获取站点数据的代码，接口请求在 `/statistics`，返回的数据是一个HTML文本内容，请问一下可以提供一个标准的 JSON 返回接口吗？

**Comment by jxxghp** [comment]
安排

**Comment by jxxghp** [comment]
接口地址为/api/v1/site/statistics,需要在请求头增加Authorization,密钥为基础设置中API密钥

**Comment by GideonSenku** [comment]
等我的组件好消息，这几天业务需求比较多，来不及写
