### ISSUE TITLE
ios手机页面，左侧菜单栏无法滚动，导致下面的菜单按不到

### ISSUE THREAD

**Issue by eightsheep67** [jxxghp/nas-tools#871]
ios手机页面，左侧菜单栏无法滚动，导致下面的菜单按不到

**Comment by yilin101** [comment]
确实有这个问题 不好滚动

**Comment by eightsheep67** [comment]
> 确实有这个问题 不好滚动

后面发现电脑界面也有这个问题，当你jackett设置比较多的站点，然后你在资源搜索的时候，左侧筛选展开超出屏幕的地方，你也点不到

**Comment by jxxghp** [comment]
UI太难搞了

**Comment by eightsheep67** [comment]
> UI太难搞了

感谢大佬的修复！！！！！
