### ISSUE TITLE
群辉7.0不同共享文件夹下硬链接错误，错误256

### ISSUE THREAD

**Issue by CoolLoong** [jxxghp/nas-tools#872]
# 🐞 错误汇报
同存储空间下，使用两个不同的共享文件夹，硬链接时会报错提示错误码256，但同目录硬链接没问题。

#### 两个共享文件夹
![image](https://user-images.githubusercontent.com/69153398/187592858-1f854d90-f91c-47a3-9e5c-b1d538c5023e.png)
#### docker目录映射
![image](https://user-images.githubusercontent.com/69153398/187592955-b6c074f6-68b7-4210-8ab9-e600b79ea69c.png)
#### nastool目录同步设置
![image](https://user-images.githubusercontent.com/69153398/187592980-293144a5-db48-4fa9-a663-2879037a1497.png)
#### nastool报错提示
![image](https://user-images.githubusercontent.com/69153398/187593158-4b9d8c23-4c49-4c08-a014-207378114490.png)

### ▶ 复现步骤
使用两个不同的共享文件夹挂载后进行硬链接，即可触发此Bug。

### ✔ 预期行为
应该能正常硬链接同步。

**Comment by jxxghp** [comment]
常见问题及设置的注释里都有讲，不同共享目录在底层就是认为是不同的盘。

**Comment by huluohu** [comment]
> 常见问题及设置的注释里都有讲，不同共享目录在底层就是认为是不同的盘。

<img width="362" alt="image" src="https://user-images.githubusercontent.com/7138642/187641156-979a6033-17a8-42df-970d-a1010a42ea12.png">

我放在同一个共享目录下，也跟他报同样的错，错误码256。但是奇怪的是，在目标目录下会自动把分类文件夹创建好，但是视频转移不过去。
