### ISSUE TITLE
添加功能

### ISSUE THREAD

**Issue by MiaOcean** [jxxghp/nas-tools#873]
可否请作者大佬在刷流模块中优化几个功能。
1:是否强制做种添加一个选项，现在的功能是默认强制做种，即使将下载器强制做种关闭也无效。
2:在自定义下载器中添加分类设置，这样当种子发送至下载器时了直接存放至下载器中已经设置好的分类文件夹。

**Comment by tevenfeng** [comment]
def torrents_set_force_start(self, ids):

**Comment by tevenfeng** [comment]
这里大概看了下代码分析了一下

之所以这么实现的原因，根据我的理解，是添加种子下载以后，为了保证尽快开始下载，设置了强制开始（def torrents_set_force_start(self, ids)这个函数）。

但是貌似看起来这么设置以后，下载完了就会默认是强制上传的状态。

也许可以在下载完成以后再把状态设置会正常的start，应该就可以
