### ISSUE TITLE
rclone转移与emby和字幕下载的问题

### ISSUE THREAD

**Issue by 22h33j** [jxxghp/nas-tools#874]
![微信截图](https://user-images.githubusercontent.com/70189449/187638391-fc9947e4-3282-49e0-93cb-45f612d6d9c2.png)
向群里syq大佬询问得到的回答是：
作者的机制应该是rclone传完就刷新媒体库，但是rclone传完，刷新到本地挂载目录是有延迟的，看你设置的时间，默认是5分钟，然后rclone传完马上刷新媒体库，或者调用csf下载字幕，就会出现找不到目录的情况。
希望作者大大能够确认是否是这个问题，有时间优化下就更好了。

**Comment by jxxghp** [comment]
等待时间不固定不太好解决
