### ISSUE TITLE
资源搜索结果页面建议增加排序选项

### ISSUE THREAD

**Issue by ThierryCheng** [jxxghp/nas-tools#876]
如果搜索的资源比较热门加上PT站点较多的情况下，会同时出现几十深圳上百个搜索结果。即使通过左侧的筛选项进行过滤后结果还是比较多。
因此建议是否可以增加一个排序选项，比如按照资源的大小，做种数量的多少等规则进行排序，方便下载时的筛选

**Comment by jxxghp** [comment]
这个难度比较大，放弃
