### ISSUE TITLE
2.03版本，指定用户无效

### ISSUE THREAD

**Issue by xifan2333** [jxxghp/nas-tools#878]
- 版本：2.03
- 运行环境：docker
- 问题：指定 uid gid 无效，创建文件夹为root权限
![IMG_20220831_193457_886.jpg](https://user-images.githubusercontent.com/23066537/187669449-ca0e6f34-899f-479c-975f-6a5016a37f1d.jpg)

**Comment by jxxghp** [comment]
启动脚本没有变化，不知道问题在哪里
