### ISSUE TITLE
Rss订阅识别bug

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#879]
![860E37AC-18DB-46C2-9091-FA2B6315E96E](https://user-images.githubusercontent.com/54088512/187677599-86839764-5ce6-4e0a-9226-debbb7fbcaba.png)
![AF503936-2449-483C-A62B-6966B00547C3](https://user-images.githubusercontent.com/54088512/187677614-91bb16f3-edf9-4bcb-a357-a336ed999839.png)
![63E3187C-93B8-4960-B2AB-348C7EA5EA07](https://user-images.githubusercontent.com/54088512/187677624-d3f9a02f-1ac1-42c3-b665-c78c0aab6d39.png)

**Comment by thsrite** [comment]
![71DC33BE-5CBD-41A2-83E3-605871F471AA](https://user-images.githubusercontent.com/54088512/187678185-f104bdcc-727a-4a1f-adb5-b195d510ebe7.png)
![A367D0FF-2D34-4D2C-8AB1-B526A0915D64](https://user-images.githubusercontent.com/54088512/187678205-cc9dc0ac-3352-4dd8-8489-b525a84a68e3.png)

**Comment by thsrite** [comment]
手动刷新可以匹配下载的
![E5EC1379-B2AA-43B3-8881-EE4252622FFA](https://user-images.githubusercontent.com/54088512/187678803-0b359ba5-b647-4679-8859-93f589d7eddb.png)

**Comment by jxxghp** [comment]
1. Fa Zui TMDB就没有这个别名。这个当然识别不了，除非你去TMDB加个别名。一些新出的剧，大家都不去维护词条，靠等别人维护，那体验肯定好不了。
2. 订阅勾选规则了吗？站点勾选规则了吗？ 都没有才用默认规则，服务里的规则测试用的是默认规划。识别不了和不符合规则是两码事，分开分析，用服务里不同的功能测试。

另外把名字贴出来，都是截图我也连测都没法测。

**Comment by thsrite** [comment]
![image](https://user-images.githubusercontent.com/54088512/187830170-a5ad6445-c400-4a31-9d0a-224e5f74a552.png)
![image](https://user-images.githubusercontent.com/54088512/187830183-731e91f9-b4a3-4d38-966d-b707ba0da2ab.png)
![image](https://user-images.githubusercontent.com/54088512/187830221-3d9361d0-1b99-485c-b808-e37bb704da60.png)
![image](https://user-images.githubusercontent.com/54088512/187830366-b5ce6d6f-c4fa-4520-bae1-693c66b4b6db.png)

[神印王座][Throne of Seal][2022][WEB-DL][2160][TV Series][TV 22][LeagueWEB] 
神印王座 第一季 第22集 | 类型:动画 [国语中字]

**Comment by thsrite** [comment]
订阅和站点规则都选的 日常观影

**Comment by jxxghp** [comment]
我知道是什么原因了，这个站的RSS，你试下不要勾选副标题。[][]这种格式的种子后面加个副标题后就无法识别了。

**Comment by thsrite** [comment]
![image](https://user-images.githubusercontent.com/54088512/187847139-bee21331-bf70-4a28-8b09-a45dfa15953b.png)

站点没有副标题选项，默认的都有。

**Comment by jxxghp** [comment]
做了下兼容处理

**Comment by thsrite** [comment]
> 做了下兼容处理

大佬辛苦了
