### ISSUE TITLE
刷流增加做种人数限制范围

### ISSUE THREAD

**Issue by rockhia** [jxxghp/nas-tools#880]
做种人数能否也可以设置做种人数介于两个数之间。
比如(0,2)，则只有做种人数为1，才会下载进行刷流。
这种情况可以避免做种人数为0时，长期占用规定的下载数量。
![Screenshot_20220831_203719](https://user-images.githubusercontent.com/90016652/187680479-936f1436-11be-4e2c-8d21-5c0b69e1384c.jpg)
![Screenshot_20220831_203555_me fengmlo qbRemote_edit_145222910563256](https://user-images.githubusercontent.com/90016652/187680489-8ac5b49e-ba2d-49a6-81f0-005afe8913f4.jpg)

**Comment by pen1120** [comment]
开发中
