### ISSUE TITLE
点击推荐中的4个TMDB热门、最新无反应；点击影片搜索，报连接TMDB出错。

### ISSUE THREAD

**Issue by wuyufeng1989** [jxxghp/nas-tools#882]
版本：2.0.3，运行环境docker，共2个问题
**一、点击推荐中4个TMDB热门、最新链接无反应**
![1](https://user-images.githubusercontent.com/59195829/187712857-14bd0dae-2af5-4995-95c5-8578a11dd0a9.png)
**二、点击影片搜索，提示失败、实时日志出现“连接TMDB出错”**
![2](https://user-images.githubusercontent.com/59195829/187713654-3df2b6a8-ddc7-4354-80ff-0320ad32f522.png)
[**实时日志：**]
23:00:15 ERROR - 【META】连接TMDB出错：HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/search/tv?api_key=3537791********fa655abf95&query=%E4%BA%BA%E7%94%9F%E5%A4%A7%E4%BA%8B&first_air_date_year=2022&language=zh-CN (Caused by SSLError(CertificateError("hostname 'api.themoviedb.org' doesn't match either of 'www.我的域名.top', '我的域名.top'")))
23:00:15 INFO - 【META】人生大事 以年份 2022 在TMDB中未找到电视剧信息!
**网络环境：**
我有动态公网IP，路由器openwrt做了阿里云ddns，不知道是不是和这个有关系，麻烦高手指点。

**Comment by Lolicon-A** [comment]
你进服务，测试一下连接，看看是否能连接到TMDB

**Comment by smily1223** [comment]
挂梯子，挂梯子。或者改host

**Comment by lowking** [comment]
![image](https://user-images.githubusercontent.com/33308659/187858940-d2cc46e6-9f23-4b83-935c-3dc23ea56a99.png)
一样的问题，连通性都OK

**Comment by HBSpy** [comment]
我的域名.top是个什么东西

**Comment by wuyufeng1989** [comment]
> 我的域名.top是个什么东西

就是我个人域名，我隐藏了

**Comment by wuyufeng1989** [comment]
问题根本还是api.themoviedb.org不能访问，切换自己的DNS，不要用运营商的DNS

**Comment by wuyufeng1989** [comment]
对了，前提全程搭梯子

**Comment by HBSpy** [comment]
但看报错不是证书中的域名不匹配么，你是把api.themoviedb.org代理了？

**Comment by wuyufeng1989** [comment]
> 但看报错不是证书中的域名不匹配么，你是把api.themoviedb.org代理了？

没有，我就把我路由器的DNS更换了

**Comment by wuyufeng1989** [comment]
> 但看报错不是证书中的域名不匹配么，你是把api.themoviedb.org代理了？

openwrt的WAN口DNS，LAN口DNS更换了

**Comment by Dr-Lee-Go** [comment]
各位，之前我有同样的问题，各种方法：代理、hosts、DNS都不行，最后如何成功的呢：其实问题在于群晖的证书：大家搜索“群晖添加套件源失败”时，里面提到如何安装“**证书**”，用这个方法，安装一编证书，TMDB报错问题可解决！_大家如果试了这个方法可行，记得回来把解决办法顶上去，让更多朋友看到_

**Comment by maCreay** [comment]
我是直接连接不上tmdb，已经改了hosts还是不行

**Comment by maCreay** [comment]
楼主能加个微么？我也是这个情况=  =

**Comment by liubin5188** [comment]
我也是同样问题,我的nas 自带 播放软件测试正常

**Comment by lowking** [comment]
![image](https://user-images.githubusercontent.com/33308659/188424406-7864397d-931f-42c8-9e6f-89862cfc2fa6.png)
我发现我是忘记配置TMDB api key了，配置完之后就正常了

**Comment by maCreay** [comment]
> ![image](https://user-images.githubusercontent.com/33308659/188424406-7864397d-931f-42c8-9e6f-89862cfc2fa6.png) 我发现我是忘记配置TMDB api key了，配置完之后就正常了

我现在是 可以搜索到电影，但是没有资源。radarr就可以搜到，都是用的Jackett的

**Comment by bigdongdongCLUB** [comment]
一样  这里死活 api 这个不通。。。

**Comment by maCreay** [comment]
> 一样 这里死活 api 这个不通。。。
我现在api通了 但是搜不到资源

**Comment by x1737886903** [comment]
> > 一样 这里死活 api 这个不通。。。
> > 我现在api通了 但是搜不到资源

请问解决了吗？我现在就是这情况

**Comment by viewetom** [comment]
一样不通。但是可以搜到资源。可以用。这是怎么回事
