### ISSUE TITLE
自动重命名因不允许的字符导致文件夹名错乱

### ISSUE THREAD

**Issue by eightsheep67** [jxxghp/nas-tools#884]
电影及电视剧文件夹均设置成{original_title} ({year})，比如女浩克原始名称是：She-Hulk : Attorney at Law ，因为有冒号，导致最终生成的文件夹名是“SXCXVS -1”类似的东西，能否增加规则删除命名名称中的文件夹不能带的字符。
![无标题](https://user-images.githubusercontent.com/70835718/187808598-39f40e01-9685-4087-8416-2a0f704797fe.png)

**Comment by jxxghp** [comment]
提问前先看已有Issues 
#682
