### ISSUE TITLE
订阅中使用jackett索引器搜索会自动跳过某些站点

### ISSUE THREAD

**Issue by kuroyukihime0** [jxxghp/nas-tools#887]
比如ACG.RIP, 在Jackett中测试可以正常使用
![image](https://user-images.githubusercontent.com/7975549/187837608-abccc3ac-ccd0-49e6-93f9-9c8a881809bc.png)

在订阅中启用了3个站点（ACG.RIP，Mikan，comiccat），实际跳过了ACG.RIP和Mikan，只检索了comiccat并返回未搜索到任何资源
![image](https://user-images.githubusercontent.com/7975549/187837688-a5f6ea44-790f-47c0-b7f6-f9677310b2d6.png)

**Comment by kuroyukihime0** [comment]
补充：
Jackett的log中也只有从comiccat的检索
![image](https://user-images.githubusercontent.com/7975549/187838031-46dfe24e-3d26-4f90-8d0d-27630622b87e.png)

**Comment by jxxghp** [comment]
更新下最新的代码或者镜像，删掉订阅重新加一下，这个问题我记得改过了。

**Comment by kuroyukihime0** [comment]
之前用的是群晖套件版2.0.3， 使用最新docker版本验证已经修复👍
