### ISSUE TITLE
[bug] media_info 缺失 begin_seaon 导致无法 RSS 下载

### ISSUE THREAD

**Issue by HBSpy** [jxxghp/nas-tools#890]
订阅 [桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [07][1080p][简体内嵌]

使用 anitopy 在文件名中不能取到 season

{'file_name': 'Isekai Ojisan [07][1080p][简体内嵌', 'video_resolution': '1080p', 'episode_number': '07', 'anime_title': 'Isekai Ojisan'}

导致返回的 media_info 中缺失 begin_season，导致无法正确计算 rss_no_exists

{'异世界舅舅 (2022)': [{'season': None, 'episodes': [1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13], 'total_episodes': 13}]}

导致 check_and_add_pt 中不下载资源

**Comment by jxxghp** [comment]
应该不是这个问题吧，check_and_add_pt 中匹配下载的逻辑不会直接访问begin_season，都是通过方法get_season_list。方法内部只要判定是电视剧没季的时候默认返回第1季的。

**Comment by HBSpy** [comment]
但是need_season会是None

https://github.com/jxxghp/nas-tools/blob/f5e3f55a46c252f82bb418d96a249d3bda5f41e3/app/downloader/downloader.py#L291

**Comment by HBSpy** [comment]
当前日期：20220901
[1] [7] None
[1] [6] None

**Comment by HBSpy** [comment]
感觉这个         
                            rss_no_exists[media_info.get_title_string()] = [
                                        {"season": media_info.begin_season, "episodes": [],
                                         "total_episodes": total_episodes}]
season 是不是应该从user.db里取，而不是看media_info.begin_season

**Comment by jxxghp** [comment]
> 感觉这个 rss_no_exists[media_info.get_title_string()] = [ {"season": media_info.begin_season, "episodes": [], "total_episodes": total_episodes}] season 是不是应该从user.db里取，而不是看media_info.begin_season

![image](https://user-images.githubusercontent.com/51039935/187872452-f23d26e4-7e5a-4168-8aeb-1d10c82779f6.png)
这个就是取的数据库里的，一定会有值。

我加了些日志，也麻烦更新下代码帮查查。

**Comment by HBSpy** [comment]
> 2022-09-01 16:56:21,939	INFO: 【RSS】异世界舅舅 (2022) S01 媒体库缺失剧集：[{'season': 1, 'episodes': [], 'total_episodes': 13}]
> 2022-09-01 16:56:21,940	INFO: 【RSS】开始处理：[桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [06][1080p][繁体内嵌]
> 2022-09-01 16:56:21,941	INFO: 【RSS】[桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [06][1080p][繁体内嵌] 识别为 异世界舅舅 (2022)S01 E06 匹配订阅成功
> 2022-09-01 16:56:21,941	INFO: 【RSS】种子描述：[桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [06][1080p][繁体内嵌][533.69 MB]
> 2022-09-01 16:56:21,941	INFO: 【RSS】异世界舅舅 (2022) S01 数据库记录的缺失集：[1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13]
> 2022-09-01 16:56:21,941	INFO: 【META】正在查询TMDB电视剧：127714 ...
> 2022-09-01 16:56:21,942	INFO: 【DOWNLOADER】异世界舅舅 (2022) 第1季 共有 13 集
> 2022-09-01 16:56:21,942	INFO: 【DOWNLOADER】异世界舅舅 (2022) 第1季 缺失 13 集
> 2022-09-01 16:56:21,942	INFO: 【RSS】异世界舅舅 (2022) S01 媒体库缺失剧集：[{'season': 1, 'episodes': [], 'total_episodes': 13}]
> 2022-09-01 16:56:21,943	INFO: 【RSS】test 处理结束，匹配到 9 个有效资源
> 2022-09-01 16:56:21,943	INFO: 【RSS】所有RSS处理结束，共 9 个有效资源
> 2022-09-01 16:56:21,943	INFO: 【RSS】异世界舅舅 (2022) 缺失剧集：[{'season': None, 'episodes': [1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13], 'total_episodes': 13}]
> 2022-09-01 16:56:21,943	INFO: 【RSS】未下载到任何资源



你这个是rsssearch_tv

我这边任务跑的是rssdownload

是我哪儿的用法不对么

**Comment by jxxghp** [comment]
> > 2022-09-01 16:56:21,939	INFO: 【RSS】异世界舅舅 (2022) S01 媒体库缺失剧集：[{'season': 1, 'episodes': [], 'total_episodes': 13}]
> 
> > 2022-09-01 16:56:21,940	INFO: 【RSS】开始处理：[桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [06][1080p][繁体内嵌]
> 
> > 2022-09-01 16:56:21,941	INFO: 【RSS】[桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [06][1080p][繁体内嵌] 识别为 异世界舅舅 (2022)S01 E06 匹配订阅成功
> 
> > 2022-09-01 16:56:21,941	INFO: 【RSS】种子描述：[桜都字幕组] 异世界归来的舅舅 / Isekai Ojisan [06][1080p][繁体内嵌][533.69 MB]
> 
> > 2022-09-01 16:56:21,941	INFO: 【RSS】异世界舅舅 (2022) S01 数据库记录的缺失集：[1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13]
> 
> > 2022-09-01 16:56:21,941	INFO: 【META】正在查询TMDB电视剧：127714 ...
> 
> > 2022-09-01 16:56:21,942	INFO: 【DOWNLOADER】异世界舅舅 (2022) 第1季 共有 13 集
> 
> > 2022-09-01 16:56:21,942	INFO: 【DOWNLOADER】异世界舅舅 (2022) 第1季 缺失 13 集
> 
> > 2022-09-01 16:56:21,942	INFO: 【RSS】异世界舅舅 (2022) S01 媒体库缺失剧集：[{'season': 1, 'episodes': [], 'total_episodes': 13}]
> 
> > 2022-09-01 16:56:21,943	INFO: 【RSS】test 处理结束，匹配到 9 个有效资源
> 
> > 2022-09-01 16:56:21,943	INFO: 【RSS】所有RSS处理结束，共 9 个有效资源
> 
> > 2022-09-01 16:56:21,943	INFO: 【RSS】异世界舅舅 (2022) 缺失剧集：[{'season': None, 'episodes': [1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13], 'total_episodes': 13}]
> 
> > 2022-09-01 16:56:21,943	INFO: 【RSS】未下载到任何资源
> 
> 
> 
> 
> 
> 
> 
> 你这个是rsssearch_tv
> 
> 
> 
> 我这边任务跑的是rssdownload
> 
> 
> 
> 是我哪儿的用法不对么
> 
> 

好像真的是这里的问题！！我改下。太感谢了。

**Comment by HBSpy** [comment]
客气，这项目是真的实用工具，再迭代迭代肯定是神器
