### ISSUE TITLE
jellyfin电影识别问题

### ISSUE THREAD

**Issue by Pollo3470** [jxxghp/nas-tools#892]
jellyfin在进行电影识别是默认使用搜索结果的第一个而非相关性，导致同名称同年份有多结果的电影经常识别出错，例如：

不 (2022)
![image](https://user-images.githubusercontent.com/90445326/187868308-862a0e47-d20c-4a88-9d42-4f83dde92194.png)

星际穿越 (2014)
![image](https://user-images.githubusercontent.com/90445326/187868460-ba189223-562e-4a68-9f19-5d308f4c0820.png)

请问有什么办法解决这个问题？jellyfin在自动识别电影时能否按相关性选择？

**Comment by jxxghp** [comment]
现在会按年份和名称完全匹配啊，没你说的这个问题吧

**Comment by Pollo3470** [comment]
> 现在会按年份和名称完全匹配啊，没你说的这个问题吧

nastool匹配没有问题，jellyfin匹配有这个问题

**Comment by jxxghp** [comment]
jellyfin的问题我可解决不了
