### ISSUE TITLE
刷流里的同时下载数量限制能改下吗，改成同一站点的下载限制成多少，这下载器的有时被一个pt站全部占领了，这对于多站点的有点麻烦

### ISSUE THREAD

**Issue by langzizhui** [jxxghp/nas-tools#895]
![image](https://user-images.githubusercontent.com/69033923/187904649-451bc5e1-63ae-47f2-ab38-ae44a96dbf76.jpeg)

**Comment by jxxghp** [comment]
这个参数本来就是针对下载带宽和磁盘IO来设置的，总的才有意义。
站点一个个刷，专业刷流有更专业的工具。
