### ISSUE TITLE
功能增强，希望在连接qbittorrent transmission emby的界面添加测试连接是否成功的按钮

### ISSUE THREAD

**Issue by appotry** [jxxghp/nas-tools#90]
填错了，没啥提示，直接不运行，或者要去看日志，体验不好

**Comment by appotry** [comment]
新增一个测试连接，测试连接是否成功

确认保存按钮，也应该在自动测试连接成功后才保存参数，如果连接不成功，就应该不保存该参数，拒绝保存，以防止参数出错导致程序异常

**Comment by jxxghp** [comment]
下个版本支持
