### ISSUE TITLE
目录映射问题

### ISSUE THREAD

**Issue by Cyberxxt** [jxxghp/nas-tools#902]
大佬好，已看过Docker教程关于目录映射的部分。
其中电影和电视的文件夹都是统一存放在video文件夹下的，但是因为前期规划需要，我的电影电视剧文件夹直接建在了硬盘的根目录下。即：/volume2/series和/volume2/movie两个目录。
这样的话教程中的映射貌似对这种目录结构不起作用，群晖也不能直接将volume2映射到容器中，请问有解决办法吗？
【因为有几千个种子做种所以把两个文件夹进行合并的方法不太现实...】

**Comment by jxxghp** [comment]
目录同步可以配多个，分开建links文件夹
