### ISSUE TITLE
系统无法执行搜索

### ISSUE THREAD

**Issue by Kaol-Fu** [jxxghp/nas-tools#903]
无论是在系统中的搜索框进行搜索还是通过微信发送指令都无法获取信息。但是通过订阅点开详细信息后进行搜索可以执行成功，在豆瓣热门等推荐菜单中直接点海报来搜索可以搜索成功。唯独在资源搜索页，主页面上方以及微信指令无法获取搜索信息。发送搜索指令后，查看日志问题无法收到任何的日志信息，通过浏览器的开发者工具看到，在执行搜索指令的时候，系统访问了类似: `http://192.168.1.140:5000/medialist?s=%E5%8C%BB%E9%99%A2%E4%BA%94%E6%97%A5&f=1&t=search`这样的地址，但是地址返回的却是500的错误。请问需要看哪个日志文件才能看到更具体的日志信息？下午的时候还是好好的，突然就变成这样了。把容器重启了都不行！

**Comment by Kaol-Fu** [comment]
![image](https://user-images.githubusercontent.com/18643104/187937667-051fcc60-d075-407b-922b-37f3327bc988.png)
找到问题了，是豆瓣搜索的原因，暂时把豆瓣名称联想给关了就好了。

**Comment by jxxghp** [comment]
同问题 #901
