### ISSUE TITLE
媒体管理的手动识别存在sample覆盖正片的问题

### ISSUE THREAD

**Issue by sprite2014** [jxxghp/nas-tools#904]
媒体转移方式为复制，媒体转移文件最小大小为151。出现sample覆盖正片的情况，sample文件大小为82M。

实时日志

22:49:31 INFO - 【RMT】文件 Jurassic.World.Dominion.2022.Extended.Edition.1080p.BluRay.x265.10bit.DTS-WiKi.mkv 复制完成
22:49:33 INFO - 【MSG】发送wechat消息：title=侏罗纪世界3 (2022) 转移完成, text=评分：7.089，类型：电影，类别：外语电影，质量：BluRay 1080p，大小：11.15G，来自：手动整理，1个文件已存在
22:49:33 INFO - 【META】正在查询TMDB电影：507086 ...
22:49:33 INFO - 【NFO】正在生成电影NFO文件：侏罗纪世界3 (2022) - 1080p.mkv
22:49:34 INFO - 【RMT】文件 /Movie/外语电影/侏罗纪世界3 (2022)/侏罗纪世界3 (2022) - 1080p.mkv 已存在，覆盖...
22:49:34 INFO - 【RMT】正在删除已存在的文件：/Movie/外语电影/侏罗纪世界3 (2022)/侏罗纪世界3 (2022) - 1080p.mkv
22:49:35 INFO - 【RMT】正在转移文件：Jurassic.World.Dominion.2022.Extended.Edition.1080p.BluRay.x265.10bit.DTS-WiKi.Sample.mkv 到 /Movie/外语电影/侏罗纪世界3 (2022)/侏罗纪世界3 (2022) - 1080p.mkv
22:49:36 INFO - 【RMT】文件 Jurassic.World.Dominion.2022.Extended.Edition.1080p.BluRay.x265.10bit.DTS-WiKi.Sample.mkv 复制完成
22:49:36 INFO - 【MSG】发送wechat消息：title=侏罗纪世界3 (2022) 转移完成, text=评分：7.089，类型：电影，类别：外语电影，质量：BluRay 1080p，大小：82.43M，来自：手动整理，1个文件已存在
22:49:36 INFO - 【EMBY】开始刷新Emby媒体库...
22:49:36 INFO - 【EMBY】Emby媒体库刷新完成
22:49:36 INFO - 【RMT】/DL/Jurassic.World.Dominion.2022.Extended.Edition.1080p.BluRay.x265.10bit.DTS-WiKi/ 处理完成，总数：2，失败：0

**Comment by sprite2014** [comment]
媒体整理-手动识别。
就输入了源目录，目的目录，类型和tmdb id

**Comment by jxxghp** [comment]
> 媒体整理-手动识别。 就输入了源目录，目的目录，类型和tmdb id

自定义识别？

**Comment by sprite2014** [comment]
![Uploading 5899E586-1780-4AE9-A417-F617612D9E4E.png…]()
![Uploading DBCF8E69-1E23-446F-BE58-D12E3E28F084.jpeg…]()

**Comment by sprite2014** [comment]
![Screenshot_20220908_211022](https://user-images.githubusercontent.com/40068735/189131557-c149c523-7f6f-4179-981b-4cb08f4df998.jpg)
![Screenshot_20220908_211029_com android chrome](https://user-images.githubusercontent.com/40068735/189131659-7de3e521-64f4-459e-993d-1b1fa13fb044.jpg)
![Screenshot_20220908_211055_com synology DSfile](https://user-images.githubusercontent.com/40068735/189131695-8b86e719-32a7-4663-9af1-fc02b58e93a4.jpg)
