### ISSUE TITLE
目录同步路径中包含隐藏文件夹时不生效

### ISSUE THREAD

**Issue by xtomb** [jxxghp/nas-tools#905]
版本：2.0.3
部署方式：Docker
宿主系统：Ubuntu22.4

配置目录同步如下图：
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/15191058/187952746-041ed035-3500-4853-8cdd-3b5f748db646.png">
第一条记录源目录路径包含隐藏文件夹，无法正常监控，当将路径从/mnt/data/download/.porn/movie改为 **/mnt/data/download/porn/movie** 后可正常识别到电影并进行转移。

日志截图：
<img width="824" alt="image" src="https://user-images.githubusercontent.com/15191058/187957753-20ae6ca5-89af-42ff-998d-a7e3258eaae6.png">

**Comment by 907739769** [comment]
借一步说话😁

**Comment by jxxghp** [comment]
就是故意这么设计的啊，隐藏的还同步？

**Comment by xtomb** [comment]
> 就是故意这么设计的啊，隐藏的还同步？

家里NAS是连了电视的，有些特殊的影片下载下来不希望小孩能够在电视上看到，因此下载到隐藏文件夹了。
