### ISSUE TITLE
windows下localhost:端口可以访问但127.0.0.1:端口不行

### ISSUE THREAD

**Issue by bigdongdongCLUB** [jxxghp/nas-tools#908]
如题。
用电脑本机的IP:端口也不行。
这导致局域网下的其他电脑没办法。仅远程连接nastools
是防火墙的问题吗？怎么解决求教

**Comment by jxxghp** [comment]
配置文件里，app下有个host配置，改成 0.0.0.0

**Comment by bigdongdongCLUB** [comment]
> 配置文件里，app下有个web_host配置，改成 0.0.0.0
config.yaml 里的web_host: '::' 改成web_host: ':0.0.0.0:'后再打开直接报错了。。。
大佬求助
<img width="510" alt="截屏2022-09-03 03 20 04" src="https://user-images.githubusercontent.com/43647204/188223018-e1776586-6d73-40eb-b157-10a8242101a2.png">
