### ISSUE TITLE
不使用索引器

### ISSUE THREAD

**Issue by colorsakura** [jxxghp/nas-tools#913]
如下图所示，无法连接TMDB，貌似就不使用索引器搜索，是不是程序逻辑上有问题。实际可以直接通过索引器检索出来结果。

![image](https://user-images.githubusercontent.com/32534829/188075370-c2b50829-e152-40c0-a833-805a301ac585.png)

![image](https://user-images.githubusercontent.com/32534829/188075331-9c7cf2ca-5ab2-4183-a194-7d1bb03cd6c4.png)

**Comment by huluohu** [comment]
对，貌似是如果从TMDB搜刮不到信息就不能订阅、不能下载，这样的话其实对索引器有点浪费。。。

**Comment by Travel2Here** [comment]
楼主所言极是，感觉这个产品很多逻辑和交互体验上的问题。让用户看起来很难上手。。。。其实本来的逻辑又很简单。。。没捋清楚

**Comment by hocyshaemula** [comment]
资源搜索页面 “搜索”按钮有个下拉选择 快速搜索和高级搜索 可以跳过TMDB

**Comment by jxxghp** [comment]
先搞清楚再提问吧
