### ISSUE TITLE
豆瓣想看解析正常，无法自动添加订阅，也就无法自动下载

### ISSUE THREAD

**Issue by biweems** [jxxghp/nas-tools#914]
豆瓣想看同步以后解析电影和电视剧都是正常的，但是无法转添加到订阅（设置里豆瓣相关选项都是勾上了的），2.0.3版本
手动订阅-》下载这步试验了是没问题的，感觉就是豆瓣想看-》自动添加订阅这里除了什么问题

15:09:43 INFO - 【DOUBAN】开始同步豆瓣数据...
15:09:43 INFO - 【DOUBAN】开始获取 xxxx 的 wish 数据...
15:09:43 INFO - 【DOUBAN】解析到媒体：2297265
15:09:43 INFO - 【DOUBAN】解析到媒体：35700395
15:09:43 INFO - 【DOUBAN】解析到媒体：1998799
15:09:43 INFO - 【DOUBAN】解析到媒体：35056243
15:09:43 INFO - 【DOUBAN】解析到媒体：35890182
15:09:43 INFO - 【DOUBAN】用户 xxxx 解析完成，共获取到 5 个媒体
15:09:43 INFO - 【DOUBAN】所有用户解析完成，共获取到 5 个媒体
15:09:43 INFO - 【DOUBAN】正在查询豆瓣详情：2297265
15:09:44 INFO - 【DOUBAN】电影：浪潮 2008
15:09:45 INFO - 【DOUBAN】正在查询豆瓣详情：35700395
15:09:45 INFO - 【DOUBAN】电影：坠落 2022
15:09:47 INFO - 【DOUBAN】正在查询豆瓣详情：1998799
15:09:48 INFO - 【DOUBAN】电视剧：灌篮高手 1993
15:09:52 INFO - 【DOUBAN】正在查询豆瓣详情：35056243
15:09:52 INFO - 【DOUBAN】电影：十三条命 2022
15:09:57 INFO - 【DOUBAN】正在查询豆瓣详情：35890182
15:09:57 INFO - 【DOUBAN】电视剧：脱口秀大会 第五季 2022

**Comment by biweems** [comment]
在tg群里咨询了一下，我的日志里没有“豆瓣数据同步完成”这个提示。。。不知道是不是由于这个引起的

**Comment by jxxghp** [comment]
貌似是豆瓣的接口变化后适配没改全导致的，我刚提了代码，再刷新下看看

**Comment by biweems** [comment]
可以了。。。十分十分感谢！！！

**Comment by yilin101** [comment]
> 貌似是豆瓣的接口变化后适配没改全导致的，我刚提了代码，再刷新下看看

我的豆瓣还是不行 只有手动订阅的可以

**Comment by DexterPoker** [comment]
docker2.0.4版本，豆瓣相关配置后，实时日志中没看到豆瓣相关的日志内容，有办法测试豆瓣配置信息吗？

**Comment by DexterPoker** [comment]
docker2.0.4版本，豆瓣相关配置后，实时日志中没看到豆瓣相关的日志内容，有办法测试豆瓣配置信息吗？

**Comment by yilin101** [comment]
> docker2.0.4版本，豆瓣相关配置后，实时日志中没看到豆瓣相关的日志内容，有办法测试豆瓣配置信息吗？

我发现的豆瓣服务的配置中 同步间隔是灰色2小时，只是提示字眼，但是并没有默认赋值2小时，我第一反应以为默认是设置了2小时，所以一直没有手动填写数字，导致这个豆瓣服务一直没开启，后来手动填写了2小时，就开启了，建议默认就直接是2小时就好了，设置个开关更直观。

**Comment by DexterPoker** [comment]
> > docker2.0.4版本，豆瓣相关配置后，实时日志中没看到豆瓣相关的日志内容，有办法测试豆瓣配置信息吗？
> 
> 我发现的豆瓣服务的配置中 同步间隔是灰色2小时，只是提示字眼，但是并没有默认赋值2小时，我第一反应以为默认是设置了2小时，所以一直没有手动填写数字，导致这个豆瓣服务一直没开启，后来手动填写了2小时，就开启了，建议默认就直接是2小时就好了，设置个开关更直观。

感谢大佬还真是这个问题，这个灰色的2小时我的刻板印象是默认值不可修改的默认值，防止被封杀什么操作，原来必须手工配置emmm.....

**Comment by yilin101** [comment]
> > > docker2.0.4版本，豆瓣相关配置后，实时日志中没看到豆瓣相关的日志内容，有办法测试豆瓣配置信息吗？
> > 
> > 
> > 我发现的豆瓣服务的配置中 同步间隔是灰色2小时，只是提示字眼，但是并没有默认赋值2小时，我第一反应以为默认是设置了2小时，所以一直没有手动填写数字，导致这个豆瓣服务一直没开启，后来手动填写了2小时，就开启了，建议默认就直接是2小时就好了，设置个开关更直观。
> 
> 感谢大佬还真是这个问题，这个灰色的2小时我的刻板印象是默认值不可修改的默认值，防止被封杀什么操作，原来必须手工配置emmm.....

哈哈，我不是大佬，我也摸索了好久，一直以为是哪里安装出问题了，后来发现问题居然那么简单，有点无语，建议作者把各种服务都增加个开关更直观
