### ISSUE TITLE
设置界面的一些小问题

### ISSUE THREAD

**Issue by Rocky-CN** [jxxghp/nas-tools#917]
### 问题描述
截图如下：
![image](https://user-images.githubusercontent.com/56460701/188108755-4e116814-f7c4-42f4-a97d-c3466bcf2eec.png)
1. 第一个红框，`站点`应该改为`国内站点`
2. 第二个红框，代理设置为`http://192.168.6.2:7890`后重启，在代理这一栏会吞掉http前缀，自动变为`192.168.6.2:7890`，不过能够正常工作。

**Comment by jxxghp** [comment]
第2点是这么设计的，会自动处理掉前缀。
