### ISSUE TITLE
添加下载失败，配置都测试成功，日志信息

### ISSUE THREAD

**Issue by Nailppppp** [jxxghp/nas-tools#918]
17:24:56 INFO - 【JACKETT】1337x 共检索到 34 条数据，过滤 0，不匹配 5，有效资源 29，耗时 17 秒
17:24:56 INFO - 【JACKETT】所有站点检索完成，有效资源数：29，总耗时 17 秒
17:24:56 INFO - 【WEB】共检索到 29 个有效资源
17:25:02 INFO - 【DOWNLOADER】添加下载任务：http://192.168.1.128:9117/dl/1337x/?jackett_apikey=1zkxozh4mf6nzsagg3oxax752n18jfqa&path=fsawe

提示添加下载失败

**Comment by jxxghp** [comment]
你这么问没有办法分析的，把链接贴浏览器里，看能不能下载种子。

**Comment by Nailppppp** [comment]
> 

其他功能都正常，种子和磁链都测试了可以下载，transmission单独也可以下载，在nas-tools搜索资源那里点击下载后提示添加下载失败
