### ISSUE TITLE
请求增加ipv6访问支持

### ISSUE THREAD

**Issue by TimoYoung** [jxxghp/nas-tools#92]
只有绑定ipv6地址的域名，希望能通过ipv6公网访问nas-tool并设置微信回调。
方法可供参考：
https://stackoverflow.com/questions/21673068/dual-ipv4-and-ipv6-support-in-flask-applications

**Comment by jxxghp** [comment]
试过了，怀疑是docker环境不支持，启不来

**Comment by devome** [comment]
> 试过了，怀疑是docker环境不支持，启不来

docker环境是支持的，只要docker版本够新。

**Comment by ne7erland** [comment]
root权限下
vi /usr/syno/etc/packages/Docker/dockerd.json修改docker配置文件。
修改配置文件说明+："ipv6":true打开ipv6"fixed-cidr-v6":"你的ipv6地址"
重启后docker的ipv6就开了。

**Comment by jxxghp** [comment]
更新下最新的代码，看下是不是能通过ipv6访问了

**Comment by jxxghp** [comment]
境像打包中，应该可以了。

**Comment by lywly** [comment]
> 只有绑定ipv6地址的域名，希望能通过ipv6公网访问nas-tool并设置微信回调。 方法可供参考： https://stackoverflow.com/questions/21673068/dual-ipv4-and-ipv6-support-in-flask-applications

求问ipv6公网怎么设置微信回调，ipv6地址是动态的，域名验证又不通过。求指导一下

**Comment by TimoYoung** [comment]
微信回调不支持ipv6，我已经放弃了
