### ISSUE TITLE
遇到一个目录识别的问题

### ISSUE THREAD

**Issue by cunbow** [jxxghp/nas-tools#921]
今天在做目录同步的时候，遇到一个目录添加到nastool里面会丢后缀导致转移的时候到不到目录
环境：群辉7.0.1 docker nastool:2.0.3
源地址: /volume2/Media/download/pt/绝命毒师S01-S05.Breaking.Bad.2008-2012.1080p.Blu-ray.x265.AC3￡cXcY@FRDS
添加到nastool目录同步后的地址：/mnt/Media/download/pt/绝命毒师S01-S05.Breaking.Bad.2008-2012.1080p.Blu-ray.x265.AC3￡cXcY
用目录选择器或者复制目录添加在保存的时候都会丢掉@frds

**Comment by jxxghp** [comment]
目录配置不用配到电影文件里面吧

**Comment by cunbow** [comment]
![bug](https://user-images.githubusercontent.com/42895319/188251590-9e9a89a5-01f2-40bb-95d1-8e6681636862.png)
我发的是一个电视剧合集的目录，这个目录添加到nastool的时候会丢失@FRDS后缀导致无法识别

**Comment by jxxghp** [comment]
同步目录的设置用到了@，所以有这个符号会有问题，同步目录不需要将目录设到这一层。手工识别用右上角的自定义识别输路径
