### ISSUE TITLE
剧集完成度识别不正确

### ISSUE THREAD

**Issue by xxzj990** [jxxghp/nas-tools#93]
使用版本：v0.7.02
问题：
RSS订阅了【我的出走日记】，目前下载到第8集，但是新增订阅后扫描日志显示已经完成了16集下载，并且自动删除了订阅关键字。
使用的媒体库是emby

谢谢～

**Comment by xxzj990** [comment]
相关日志如下：

> 2022-05-06 09:00:31,359	INFO: 【RSS】开始RSS检索...
> 2022-05-06 09:00:31,417	INFO: 【RSS】共有 1 个电视剧订阅需要检索
> 2022-05-06 09:00:31,448	INFO: 【SEARCHER】正在识别 我的出走日记 S01 2022 的媒体信息...
> 2022-05-06 09:00:43,682	WARNING: 【META】Change The World 未匹配到媒体信息!
> 2022-05-06 09:00:43,683	INFO: 【RSS】[连续剧/TV-Series]Change The World 2018 Complete 1080p WEB-DL H264 AAC-LeagueWEB[换了人间 全40集 [国语中字] | *1080p*][19.19 GB][qiuxifu] 未查询到媒体信息
> 2022-05-06 09:00:43,688	INFO: 【RSS】BTSCHOOL 处理结束，匹配到 0 个有效资源
> 2022-05-06 09:00:43,688	INFO: 【RSS】正在处理：FRDS
> 2022-05-06 09:00:44,243	INFO: 类型：电视剧，标题：我的出走日记，年份：2022
> 2022-05-06 09:00:44,244	INFO: 【PT】我的出走日记 (2022) 第1季 共有 16 集
> 2022-05-06 09:00:44,289	INFO: 【PT】我的出走日记 (2022) 第1季 共16集 已全部存在
> 2022-05-06 09:00:44,289	INFO: 【RSS】电视剧 我的出走日记 下载完成，删除订阅...
> 2022-05-06 09:00:44,294	INFO: 【RSS】RSS检索结束

**Comment by jxxghp** [comment]
进群看置顶常见问题

**Comment by xxzj990** [comment]
> 进群看置顶常见问题

```
常见问题：无法识别集数信息、订阅电视剧只下了部分就自动删除订阅了
1、推荐使用jackett做为索引器，prowlarr的api不会返回副标题，会导致种子命名不规范的情况下无法通过副标题拉取集数信息，从而将实际单集或多集的资源识别为整季。
2、Emby、Jellyfin开启了显示缺失集，或勾选了TVDB做为搜刮器也会导致该问题。
```

第一点目前是满足的，使用的是Jackett
第二点没有开启显示缺失集，但勾选了TVDB，我把TVDB取消勾选后还需要做什么操作吗？我看了下元信息应该是从TMDB获取的

**Comment by xxzj990** [comment]
> 2022-05-06 09:00:44,244 INFO: 【PT】我的出走日记 (2022) 第1季 共有 16 集
> 2022-05-06 09:00:44,289 INFO: 【PT】我的出走日记 (2022) 第1季 共16集 已全部存在

看这两行日志，感觉不是从emby里判断集数的，是从下载器里判断的

**Comment by xxzj990** [comment]
> > 进群看置顶常见问题
> 
> ```
> 常见问题：无法识别集数信息、订阅电视剧只下了部分就自动删除订阅了
> 1、推荐使用jackett做为索引器，prowlarr的api不会返回副标题，会导致种子命名不规范的情况下无法通过副标题拉取集数信息，从而将实际单集或多集的资源识别为整季。
> 2、Emby、Jellyfin开启了显示缺失集，或勾选了TVDB做为搜刮器也会导致该问题。
> ```
> 
> 第一点目前是满足的，使用的是Jackett 第二点没有开启显示缺失集，但勾选了TVDB，我把TVDB取消勾选后还需要做什么操作吗？我看了下元信息应该是从TMDB获取的

单独刷新了一下电视剧的元数据还是不行

**Comment by xxzj990** [comment]
> 进群看置顶常见问题

OK了，需要重新刷新元数据
