### ISSUE TITLE
名称识别是否有问题？

### ISSUE THREAD

**Issue by Lolicon-A** [jxxghp/nas-tools#934]
【高清剧集网 www.BTHDTV.com】冰雨火[第13集][国语配音+中文字幕].Being.A.Hero.2022.1080p.WEB-DL.H264.AAC-SeeWEB
这个名称居然识别成了：“剧集网 冰雨火”导致无法下载。
![image](https://user-images.githubusercontent.com/112593405/188264510-a10754d5-7a56-4de6-a9a9-91a62bc9bdf9.png)

**Comment by Lolicon-A** [comment]
这是日志截图
![image](https://user-images.githubusercontent.com/112593405/188264564-bda13fb5-7c0e-447e-9bdb-632c32f9c3f2.png)

**Comment by jxxghp** [comment]
这种命名都想识别，想啥呢。。。
