### ISSUE TITLE
添加自定义rss订阅接口

### ISSUE THREAD

**Issue by DDS-ALL** [jxxghp/nas-tools#935]
类似于radarr的这种自定义rss
![080453F0-E242-498E-A239-AD6E2DB79BA9](https://file.ddsrem.in:998//application/hide.php?key=a2doMTNoeXFFUzN3b1JWbTcrUXhKQ1pKZkQ1SDdwSm44R2J6aG1QdExFUT0=)

**Comment by Lolicon-A** [comment]
这个功能好！喜欢，希望能添加

**Comment by jxxghp** [comment]
详细说说？不了解这是啥

**Comment by Lolicon-A** [comment]
> 详细说说？不了解这是啥

应该是能支持订阅没有或不提供RSS的磁力站或论坛、bt站吧

**Comment by DDS-ALL** [comment]
添加一些其他网站的rss订阅，类似于tmdb的rss订阅，功能上类似于豆瓣的订阅，但是我想设置其他的影视网站的rss，所以想添加一个自定义rss订阅接口

**Comment by hxldbx** [comment]
其实有个类似需求，https://mikanani.me/，类似于这种动漫网站，是提供rss订阅服务的。每次的都是rss到BT里，设定好规则。再通过nastool导入，其实有些麻烦。不如直接有个rss订阅

**Comment by Lolicon-A** [comment]
> 其实有个类似需求，[https://mikanani.me/，类似于这种动漫网站，是提供rss订阅服务的。每次的都是rss到BT里，设定好规则。再通过nastool导入，其实有些麻烦。不如直接有个rss订阅](https://mikanani.me/%EF%BC%8C%E7%B1%BB%E4%BC%BC%E4%BA%8E%E8%BF%99%E7%A7%8D%E5%8A%A8%E6%BC%AB%E7%BD%91%E7%AB%99%EF%BC%8C%E6%98%AF%E6%8F%90%E4%BE%9Brss%E8%AE%A2%E9%98%85%E6%9C%8D%E5%8A%A1%E7%9A%84%E3%80%82%E6%AF%8F%E6%AC%A1%E7%9A%84%E9%83%BD%E6%98%AFrss%E5%88%B0BT%E9%87%8C%EF%BC%8C%E8%AE%BE%E5%AE%9A%E5%A5%BD%E8%A7%84%E5%88%99%E3%80%82%E5%86%8D%E9%80%9A%E8%BF%87nastool%E5%AF%BC%E5%85%A5%EF%BC%8C%E5%85%B6%E5%AE%9E%E6%9C%89%E4%BA%9B%E9%BA%BB%E7%83%A6%E3%80%82%E4%B8%8D%E5%A6%82%E7%9B%B4%E6%8E%A5%E6%9C%89%E4%B8%AArss%E8%AE%A2%E9%98%85)

你这个需求qB下载软件就能解决了。里面有RSS订阅选项

**Comment by Lolicon-A** [comment]
> 添加一些其他网站的rss订阅，类似于tmdb的rss订阅，功能上类似于豆瓣的订阅，但是我想设置其他的影视网站的rss，所以想添加一个自定义rss订阅接口



> 
你想说的是为那些没有提供RSS订阅源的网站，收集信息之后提供RSS订阅源，然后用这个RSS地址来订阅下载。

**Comment by jxxghp** [comment]
还是不理解这个是怎么玩的，举过具体的例子吧

**Comment by zxcvbnmzsedr** [comment]
比如蜜柑计划这种，提供了剧集对应的RSS订阅链接，就无需再通过Jackett进行检索

我目前想的是，在rss订阅界面上增加一个rss地址，如果有这个rss地址就优先用这个地址下载。

如下图这样：
<img width="720" alt="image" src="https://user-images.githubusercontent.com/14026790/189530998-e42df5ef-1337-45ec-9838-7d96e3910536.png">

**Comment by sjtuross** [comment]
Radarr里面的RSS主要是用来获取电影列表本身，比如某个推荐列表，然后到索引器里面去找

PT站的RSS既是列表，同时也提供下载连接

这里混了不同的需求

**Comment by jxxghp** [comment]
增加了这个功能，等版本更新。
