### ISSUE TITLE
使用Tranmission下载器无法显示正在下载的项目，是不支持还是配置的问题？

### ISSUE THREAD

**Issue by liyongwei1** [jxxghp/nas-tools#939]
开始下载后，下载的记录直接出现在了“近期下载”，而不是“正在下载”中，请问该怎么设置
![Snipaste_2022-09-03_21-23-41](https://user-images.githubusercontent.com/22850686/188272669-31b6df7d-e40d-4e91-87af-acc79cc1b845.jpg)
![Snipaste_2022-09-03_21-24-03](https://user-images.githubusercontent.com/22850686/188272670-206ef4ce-f43a-4522-9570-063c07f0419f.jpg)
![Snipaste_2022-09-03_21-24-12](https://user-images.githubusercontent.com/22850686/188272673-aaa600f4-624f-4c8f-9d8a-8a68b8b7a7fd.jpg)

**Comment by jxxghp** [comment]
没有问题
