### ISSUE TITLE
请求增加订阅自定义的功能

### ISSUE THREAD

**Issue by rockhia** [jxxghp/nas-tools#94]
《梦华录》在豆瓣上查询到5月份即将播出，但通过豆瓣收藏和手动添加订阅均无法成功。
请求增加该功能：在添加订阅时，即使未找到媒体信息也可以添加到订阅内（和5.23版本一样，在RSS更新相关影片后，可以第一时间下载，这样能感受到一种惊喜。而不是现在需要了解电视剧已经播放，或者多次操作可以找到媒体信息后才能成功订阅）

————日志————
11:40:20 INFO - 【META】正在识别电视剧：梦华录, 年份=2022 ...
11:40:21 WARN - 【META】梦华录 未找到媒体信息!
[https://z4a.net/image/2A60dH]

**Comment by rockhia** [comment]
由于TMDB缺少剧集信息，导致已经在播放的豆瓣最新电视剧也无法订阅。
![Uploading Screenshot_20220514_000219_com.kevinforeman.nzb360.jpg…]()

**Comment by rockhia** [comment]
由于TMDB缺少剧集信息，导致已经在播放的豆瓣最新电视剧《对决》也无法订阅。
![Screenshot_20220514_000219_com kevinforeman nzb360](https://user-images.githubusercontent.com/90016652/168323306-8d3f1e6c-e703-401b-b0fc-b978e0f87f58.jpg)

**Comment by jxxghp** [comment]
v1.3.5 手动添加订阅已经支持模糊匹配
