### ISSUE TITLE
电视剧字幕组过滤不能匹配

### ISSUE THREAD

**Issue by unyielding2013** [jxxghp/nas-tools#948]
House of the Dragon S01 2160p HMAX WEB-DL DDP 5.1 Atmos HDR H.265-Lee@CHDWEB 

![image](https://user-images.githubusercontent.com/61337833/188295558-53b7dd0f-5d66-4a02-a6ba-c50263112f6e.png)

**Comment by unyielding2013** [comment]
还有Lee压制组不能识别

**Comment by jxxghp** [comment]
@Shurelol

**Comment by Shurelol** [comment]
> @Shurelol

![image](https://user-images.githubusercontent.com/16237201/188314520-535eccc9-b23e-4d73-8c88-b19f05acd5a0.png)

有CHD小组会被优先匹配到，待优化

**Comment by Shurelol** [comment]
> 还有Lee压制组不能识别

CHDWEB匹配问题会进行优化，Lee压制组无法识别，请在https://github.com/jxxghp/nas-tools/issues/960提起请求
