### ISSUE TITLE
【功能请求】win端增加热更新

### ISSUE THREAD

**Issue by OlsonStarling** [jxxghp/nas-tools#956]
本来打算是用计划任务+bat脚本实现这个功能的，看到用脚本实现异常复杂，而GitHub发布编译好的exe文件命名并不是固定的（格式nastool_win_v加版本号），而且发现有人已经用python造过轮子了，不知道大佬能不能实现一下这个功能。
https://www.cnblogs.com/wztshine/p/16114523.html

**Comment by Shurelol** [comment]
建议fork一下，自己改下试试，windows的打包流程在workflows的
