### ISSUE TITLE
多个pt站点连接失败

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#958]
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/54088512/188312547-dbaa06a9-c332-4908-b9bb-88da9c072ebd.png">

oshen
u2
白兔
明教

进去容器后可以ping通，但日志说连接失败

**Comment by jxxghp** [comment]
网络问题没法分析，试试换ua、换cookie、加代理
