### ISSUE TITLE
【汇总】制作组/字幕组识别需求请在此处提交

### ISSUE THREAD

**Issue by Shurelol** [jxxghp/nas-tools#960]
* 请附上种子名称，如House of the Dragon S01 2160p HMAX WEB-DL DDP 5.1 Atmos HDR H.265-Lee@CHDWEB
* 请附上名称识别结果，如
![image](https://user-images.githubusercontent.com/16237201/188315231-c017c288-55ec-459a-8df3-4a1bb11f8d0b.png)

* 若有制作组/字幕组无法识别，请提供制作组/字幕组名称，如CHDWEB（若为官组，请提供所属站点，如chdbits）

**Comment by Pollo3470** [comment]
种子名称：House of the Dragon S01E03 2022 2160p HMAX WEB-DL DDP5.1 Atmos HDR DV HEVC-AQLJ@HDSky

识别结果：
![image](https://user-images.githubusercontent.com/90445326/188903384-7375c228-2ffe-4854-8adb-2ad5e7ad68e7.png)

问题：如果按HDSky匹配则可以正常过滤，但如果按AQLJ匹配则匹配不到

**Comment by Shurelol** [comment]
> 

收到，将添加至匹配列表，感谢反馈

**Comment by unyielding2013** [comment]
为什么不能下载？

![屏幕截图 2022-09-08 222901](https://user-images.githubusercontent.com/61337833/189149240-dfcfaea4-7753-4503-b8eb-708b1066ef2e.png)


![屏幕截图 2022-09-08 222901](https://user-images.githubusercontent.com/61337833/189149272-afff394b-4270-4d0e-ba53-7d6a0d8589bd.png)

**Comment by Shurelol** [comment]
该issue只用于制作组/字幕组识别需求提交，名称识别测试显示SMURF组能正常识别，其他问题请按问题模板提交issue。

**Comment by unyielding2013** [comment]
> 该issue只用于制作组/字幕组识别需求提交，名称识别测试显示SMURF组能正常识别，其他问题请按问题模板提交issue。

找到原因了，使用黑夹克正常，使用内建索引器就出问题了。

**Comment by Nemoljy** [comment]
种子名称:
夏日重现 [连载][Nekomoe kissaten][Summer Time Rendering][1080p][23][MP4/TVRip][2022年04月] 
夏日重现 [连载][zmsub][Summer Time Rendering][1080p][23][MP4/TVRip][2022年04月] 

识别结果:
![Screenshot_2022-09-17-02-23-37-348_com.z28j.feel.jpg](https://user-images.githubusercontent.com/32947114/190706595-e595460f-bf79-4133-a2de-303a9a5ab78b.jpg)

问题:
两个字幕组都是相同的情况，字幕组识别出来了但是片名识别不出来了，导致识别媒体失败。

**Comment by Shurelol** [comment]
> Nekomoe kissaten

![image](https://user-images.githubusercontent.com/16237201/190831186-29afae7a-7ed9-4528-85eb-644ce88a6f61.png)
![image](https://user-images.githubusercontent.com/16237201/190831204-679ed23c-9dc7-4053-84ef-9a08e65b468a.png)
喵萌奶茶屋发布的资源名称中并无“夏日重现 [连载]“干扰项，可以正常识别，建议去dmhy等字幕组发布站点下载

**Comment by Nemoljy** [comment]
> > Nekomoe kissaten
> 
> ![image](https://user-images.githubusercontent.com/16237201/190831186-29afae7a-7ed9-4528-85eb-644ce88a6f61.png) ![image](https://user-images.githubusercontent.com/16237201/190831204-679ed23c-9dc7-4053-84ef-9a08e65b468a.png) [喵萌奶茶屋发布的资源](https://share.dmhy.org/topics/view/613546_04_Summer_Time_Rendering_23_1080p.html)名称中并无“夏日重现 [连载]“干扰项，可以正常识别，建议去dmhy等字幕组发布站点下载

![image](https://user-images.githubusercontent.com/32947114/190916766-c4b8397f-bb3c-4072-a8d5-af8c8090db3a.png)


是TJUPT北洋园的资源，没有“夏日重现 [连载]“但是有“ [连载]“。
之前提ISSUE时搞错了，“夏日重现”应该是日志里加的内容
TG群和ISSUE里用TJUPU的人也挺多的，方不方便考虑优化一些这个点，把“ [连载]“这种**对名称识别无用的常见关键字**无视掉？

**Comment by Shurelol** [comment]
已提pr，后面会更新自定义识别屏蔽词相关功能

**Comment by Shurelol** [comment]
master分支已更新自定义识别词功能，设置-基础设置-实验室-自定义识别词设置

**Comment by Nemoljy** [comment]
> 设置

刚试了，可行。顶级迭代效率，牛逼！

**Comment by a154225859** [comment]
自带的索引解析CHD的种子好像有点问题，识别不出字幕组，改用JACKETT正常 
![image](https://user-images.githubusercontent.com/10487089/192113578-77fc4c4e-b486-4927-9594-01d25820be98.png)

CHD的日韩剧组 使用xiaopie识别不了
Little Women S01 1080p TVING WEB-DL AAC2.0 H.264-xiaopie@CHDWEB
![image](https://user-images.githubusercontent.com/10487089/192113409-9b959a60-4576-4260-a71a-ae49842bdd02.png)


![image](https://user-images.githubusercontent.com/10487089/192113453-e8a14d78-d680-4fcf-b31d-ef494be03104.png)

**Comment by Shurelol** [comment]
收到，将添加xiaopie至匹配列表，感谢反馈

**Comment by pikaqiu2222** [comment]
![1111](https://user-images.githubusercontent.com/77657256/193192344-025105e1-2feb-4c98-94a6-0a98b203d1c1.png)
![222](https://user-images.githubusercontent.com/77657256/193192423-a9d584bc-1318-4f47-85ae-297bd17f52f3.png)
星空组的 一个是标题识别出来后 一个就是他下载后的文件名识别
标题识别不正确 直接导致无法匹配上进行下载

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/193199506-aaee532c-2cd9-4d1c-96a0-9e7659b3723f.png)
![image](https://user-images.githubusercontent.com/16237201/193199576-f1c92e0f-6e2b-4cf2-9b71-72c6bb2eff65.png)
#### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助

**Comment by marcosteam** [comment]
Adventure.Of.The.King.2010.BluRay.720p.x264.AC3.2Audios-CMCT 识别为 Adventure Of The King 未匹配到媒体信息。
![Screenshot_2022-10-02-10-59-06-383-edit_mark via](https://user-images.githubusercontent.com/25745812/193435920-70db2964-e5c3-4f61-a794-ec465e24ff69.jpg)

**Comment by Shurelol** [comment]
### 这个电影是龙凤店？tmdb英文名不是这个，添加替换词`Adventure.Of.The.King@龙凤店`
![image](https://user-images.githubusercontent.com/16237201/193440380-1f988d34-6883-464c-8a10-0b6e1529629c.png)
![image](https://user-images.githubusercontent.com/16237201/193440367-c3a2296c-8927-45a3-9be6-49114fd2c08b.png)

#### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助

**Comment by yubanmeiqin9048** [comment]
识别出错：将PV识别为正片
[VCB-Studio] The Tatami Galaxy [PV02][Ma10p_1080p][x265_flac].mkv
![SBA6B~QNH$I7)VM0VL@M@WC](https://user-images.githubusercontent.com/64676973/194689032-9b42fe83-7716-4882-b6ab-a5b0f36506b5.png)

[VCB-Studio] The Tatami Galaxy [02][Ma10p_1080p][x265_flac].mkv
![E_8Y1$ (021 WCZ3}W@HWTO](https://user-images.githubusercontent.com/64676973/194689039-651a9ff3-1d7e-4237-b67c-defbd5b7f7ee.png)

**Comment by Shurelol** [comment]
### 使用更新后新增功能，文件转移忽略词，添加忽略词 PV[0-9][0-9]
![image](https://user-images.githubusercontent.com/16237201/194691041-eff335f3-bdf3-416a-a461-ba3274f6d4f9.png)
#### 关注[NASTool小秘书TG频道](https://t.me/nastool_mi)，获取教程自助

**Comment by shanyan-wcx** [comment]
[Airota&VCB-Studio] Liz to Aoi Tori [Ma10p_1080p][x265_flac].mkv
![image](https://user-images.githubusercontent.com/58252651/196313986-a89272c3-4d9a-4b07-b11e-d26f9a47e633.png)
这种有Ma10p的经常把Ma10p也识别到名称里

**Comment by Shurelol** [comment]
建议增加自定义识别词屏蔽Ma10p_

**Comment by shanyan-wcx** [comment]
> 建议增加自定义识别词屏蔽Ma10p_

已经加了，但是这种情况比较普遍，我觉得是不是应该适配一下

**Comment by Shurelol** [comment]
识别再怎么优化，不可能囊括所有情况。条件加多了总有误伤的。出了问题，用户又不可能自己去看源码改。不如自己加识别词灵活。

**Comment by marcosteam** [comment]
![image](https://user-images.githubusercontent.com/25745812/198015237-c26485ab-ea7b-4cf7-a577-7b563001420a.png)
![image](https://user-images.githubusercontent.com/25745812/198015010-48d71f4b-a426-449d-8e81-9c7f39beb3b6.png)
用种子名可以正常识别，用文件名就识别出错了，TMDB 的缓存是对的

**Comment by Shurelol** [comment]
识别词加年份

**Comment by Xm798** [comment]
> 幻想万华镜 ~The Memories Of Phantasm~ S01E08 永夜异变之章前篇.[届恋字幕组][BDRip 1080p HEVC-10bit AAC FLAC PGS].mkv
<img width="719" alt="image" src="https://user-images.githubusercontent.com/48074861/200544397-876ff75c-f44d-4f3b-8f9a-ecb5b8b9bc45.png">

> 幻想万华镜 ~The Memories Of Phantasm~ S01E09 永夜异变之章中篇.[灵眸汉化组].808p.mp4

<img width="714" alt="image" src="https://user-images.githubusercontent.com/48074861/200544538-a64df139-5f2d-45ea-875b-f87455c621bc.png">

> 幻想万华镜 ~The Memories Of Phantasm~ S01E02 红雾异变之章前篇.[白月字幕组].[一千零一夜修复组].4K超清修复.mp4

<img width="709" alt="image" src="https://user-images.githubusercontent.com/48074861/200544836-0b2040ef-022b-4b7c-966f-3c9d8dc39dc8.png">

> 幻想万华镜 ~The Memories Of Phantasm~ S01E02 红雾异变之章前篇.[赤砂幻影组][DVDRip][简体][480P][MKV][中日多轨配音].mkv

<img width="707" alt="image" src="https://user-images.githubusercontent.com/48074861/200544895-42089661-0f82-49b5-9675-6bdc1e3d01ad.png">

**Comment by Ruikoto** [comment]
`[风车字幕组][名侦探柯南番外-犯人犯泽先生][05][米花町狂想曲][1080P][繁体][MP4]`
无法识别
![image](https://user-images.githubusercontent.com/30781137/200762098-ce55fc8d-5472-4ae7-a22e-9f1cbb8aaf5a.png)

`六四位元字幕组★名侦探柯南 犯人犯泽先生 Detective Conan - Hannin no Hanzawa-san★05★1920x1080★AVC AAC MP4★繁体中文`
只能识别出季，集数无法识别
![image](https://user-images.githubusercontent.com/30781137/200762487-4293bd37-31ea-432c-b1e4-014fc680ba54.png)

**Comment by Ruikoto** [comment]
`[风车字幕组][名侦探柯南番外-犯人犯泽先生][05][米花町狂想曲][1080P][繁体][MP4]`
无法识别
![image](https://user-images.githubusercontent.com/30781137/200762098-ce55fc8d-5472-4ae7-a22e-9f1cbb8aaf5a.png)

`六四位元字幕组★名侦探柯南 犯人犯泽先生 Detective Conan - Hannin no Hanzawa-san★05★1920x1080★AVC AAC MP4★繁体中文`
只能识别出季，集数无法识别
![image](https://user-images.githubusercontent.com/30781137/200762487-4293bd37-31ea-432c-b1e4-014fc680ba54.png)

**Comment by marcosteam** [comment]
> `[风车字幕组][名侦探柯南番外-犯人犯泽先生][05][米花町狂想曲][1080P][繁体][MP4]` 无法识别 ![image](https://user-images.githubusercontent.com/30781137/200762098-ce55fc8d-5472-4ae7-a22e-9f1cbb8aaf5a.png)
> 
> `六四位元字幕组★名侦探柯南 犯人犯泽先生 Detective Conan - Hannin no Hanzawa-san★05★1920x1080★AVC AAC MP4★繁体中文` 只能识别出季，集数无法识别 ![image](https://user-images.githubusercontent.com/30781137/200762487-4293bd37-31ea-432c-b1e4-014fc680ba54.png)

你这种奇葩名字请使用名称替换功能将片名的 [] 符号去掉
![image](https://user-images.githubusercontent.com/25745812/200833858-eb67a6b6-57ff-4cc8-bf75-f8ead58965cb.png)

**Comment by Ruikoto** [comment]
> > `[风车字幕组][名侦探柯南番外-犯人犯泽先生][05][米花町狂想曲][1080P][繁体][MP4]` 无法识别 ![image](https://user-images.githubusercontent.com/30781137/200762098-ce55fc8d-5472-4ae7-a22e-9f1cbb8aaf5a.png)
> > `六四位元字幕组★名侦探柯南 犯人犯泽先生 Detective Conan - Hannin no Hanzawa-san★05★1920x1080★AVC AAC MP4★繁体中文` 只能识别出季，集数无法识别 ![image](https://user-images.githubusercontent.com/30781137/200762487-4293bd37-31ea-432c-b1e4-014fc680ba54.png)
> 
> 你这种奇葩名字请使用名称替换功能将片名的 [] 符号去掉 ![image](https://user-images.githubusercontent.com/25745812/200833858-eb67a6b6-57ff-4cc8-bf75-f8ead58965cb.png)

原来还有这种功能，是我弄漏了，作者辛苦！

**Comment by zbodo** [comment]
[星空字幕组的恋爱FLOPS](https://dmhy.org/topics/view/620559_FLOPS_Renai_FLOPS_05_1080P_WEBrip_MP4.html)无法正确识别

![image](https://user-images.githubusercontent.com/39948021/202601002-dd12d6ab-fabe-4973-8062-b88392e6f857.png)

**Comment by onlyLTY** [comment]
![image](https://user-images.githubusercontent.com/46625336/204050352-f0bff5f7-b10b-4fa4-95a1-5ed5b5f59e09.png)
[银色子弹字幕组][名侦探柯南][第1064集 沉浸美梦的贵妇人 最后的恋爱][简繁日多语MKV][1080P]
银色子弹字幕组无法识别

**Comment by onlyLTY** [comment]
![image](https://user-images.githubusercontent.com/46625336/204055520-71456d6b-4613-4f4a-860b-11c88cdd19e2.png)
[SBSUB][Detective_Conan][S01E1059][1080P][HEVC_AAC][CHS_CHT_JP](894E3DCA).mkv
SBSUB也无法识别

**Comment by lishan148** [comment]
![image](https://user-images.githubusercontent.com/37679147/205274402-6a00bacb-f4b1-43a8-a09f-e3326bd62d6d.png)
### OPFansMaplesnow 无法识别

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/205474223-60eb9713-dde9-4e15-b151-87821f123a1e.png)
![image](https://user-images.githubusercontent.com/16237201/205474234-44f2c519-7f5c-4571-8337-3732f5ab930e.png)

**Comment by lishan148** [comment]
> ![image](https://user-images.githubusercontent.com/16237201/205474223-60eb9713-dde9-4e15-b151-87821f123a1e.png) ![image](https://user-images.githubusercontent.com/16237201/205474234-44f2c519-7f5c-4571-8337-3732f5ab930e.png)

V2.6.1 群晖版好像还没有这个
