### ISSUE TITLE
RSS订阅的内容在下载器里下载不动，手动删除以后，更新下载器，未下载的无法重新添加

### ISSUE THREAD

**Issue by AlleNPooh** [jxxghp/nas-tools#966]
2.0.4版本，刚更新的，包括上一个版本都有发现：
比如，我在RSS中订阅了《天才基本法》这个电视剧，自动在下载器中添加了种子，但是种子的效果不好，都下不动，我就手动在qBittorrent中删除了下不动的种子，但是订阅中已完成的数据没有减少，也就不能重新增加没下载的剧集；

**Comment by HBSpy** [comment]
已下载的会记在user.db RSS_TORRENTS表中，要临时解决的话可以自行打开删一下，不过这应该是个新功能需求，做个可维护相关表内容的页面

**Comment by jxxghp** [comment]
自己手动删的手动下

**Comment by AlleNPooh** [comment]
我认为可以自动比对吧，因为确实下载器有时候找的资源不好，对比一下订阅和下载器，还有播放器的内容，应该就可以知道哪些个种子被删除了  从 Windows 版邮件发送 发件人: HBSpy发送时间: 2022年9月5日 10:42收件人: jxxghp/nas-tools抄送: AllenPooh; Author主题: Re: [jxxghp/nas-tools] RSS订阅的内容在下载器里下载不动，手动删除以后，更新下载器，未下载的无法重新添加 (Issue #966) 已下载的会记在user.db RSS_TORRENTS表中，要临时解决的话可以自行打开删一下，不过这应该是个新功能需求，做个可维护相关表内容的页面—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
