### ISSUE TITLE
【功能请求】希望消息通知可以支持自定义webhook接口

### ISSUE THREAD

**Issue by Forget1672** [jxxghp/nas-tools#968]
在消息通知中支持自定义webhook接口，通过get或post方式以json格式发送通知内容，可以实现更多推送平台或自建推送服务器的通知推送支持。具体就像群晖系统通知那种可以自定义webhook URL 和参数的形式。
![图片](https://user-images.githubusercontent.com/45268867/188346409-cf641c30-5e26-4eeb-9526-861ba13cdfa6.png)
![图片](https://user-images.githubusercontent.com/45268867/188346642-74e63005-8ca3-4a90-abfa-535e07181140.png)

**Comment by huluohu** [comment]
群晖上用docker装个bark-server，手机上装个bark app，也不是很麻烦

**Comment by flywalt** [comment]
> 

但感觉bark只能推送不能回调？

**Comment by huluohu** [comment]
> > 
> 
> 但感觉bark只能推送不能回调？

是的，bark只能接收消息

**Comment by Forget1672** [comment]
> 群晖上用docker装个bark-server，手机上装个bark app，也不是很麻烦

我自建的通知服务器，已经装了别的通知app，想把各种通知整合在一起，也方便搞些自动化啥的

**Comment by jxxghp** [comment]
pushplus可以支持自定义webhook，现在通知已经支持很多了，不打算再加了。
