### ISSUE TITLE
新版中文演员名没图片

### ISSUE THREAD

**Issue by junskycool** [jxxghp/nas-tools#970]
试过挂代理也一样的问题  emby版本号4.6.7.0
![S20905-09581012](https://user-images.githubusercontent.com/93479084/188352833-2b237325-7609-456c-8590-85bef405ee8e.png)
emby手动也能搜到演员图片
![S20905-10125575](https://user-images.githubusercontent.com/93479084/188352920-eb8438c3-e286-4b23-82fd-3d2589e65c1a.png)
![S20905-10131228](https://user-images.githubusercontent.com/93479084/188352935-b448dcbf-3bfa-48b6-9faa-801b4a14db26.png)
emby刷新元数据英文也能刮出来 英文名和演员图片

**Comment by Shurelol** [comment]
演员有没有照片是emby刮削的问题，和nastool无关

**Comment by junskycool** [comment]
> 演员有没有照片是emby刮削的问题，和nastool无关

所以这就是废了？
![S20905-11421263](https://user-images.githubusercontent.com/93479084/188357142-e41d8819-fab3-4976-8827-d3506780c524.png)
 关了nastool削刮才能正常削刮了
![S20905-11495412](https://user-images.githubusercontent.com/93479084/188357214-fbd95b09-53ef-4812-8299-bd19ef22a9f2.png)

**Comment by junskycool** [comment]
![S20905-12362416](https://user-images.githubusercontent.com/93479084/188361472-ca0c2e14-ca1e-4e7d-8f9e-c484bc9efcbe.png)
刷新元数据后
![S20905-11495412](https://user-images.githubusercontent.com/93479084/188361543-ac600fff-7d53-4818-bdc8-91733301c771.png)

**Comment by rockhia** [comment]
我这边同样存在一样的问题。
中文演员没有头像，英文名称有头像。
而且还有个麻烦事，如果emby整个库里面的英文名称没有修改的话，点击新生成的中文名称，会导致其他相关的影片不会出现。
![Screenshot_20220905_142849_com mb android tg](https://user-images.githubusercontent.com/90016652/188378878-3d66b93a-88e8-49c1-9904-e62b64e8e362.jpg)
![Screenshot_20220905_142354_com mb android tg](https://user-images.githubusercontent.com/90016652/188378922-83062036-a809-411e-ad59-9a17758d45d9.jpg)

**Comment by Shurelol** [comment]
> 我这边同样存在一样的问题。 中文演员没有头像，英文名称有头像。 而且还有个麻烦事，如果emby整个库里面的英文名称没有修改的话，点击新生成的中文名称，会导致其他相关的影片不会出现。 ![Screenshot_20220905_142849_com mb android tg](https://user-images.githubusercontent.com/90016652/188378878-3d66b93a-88e8-49c1-9904-e62b64e8e362.jpg) ![Screenshot_20220905_142354_com mb android tg](https://user-images.githubusercontent.com/90016652/188378922-83062036-a809-411e-ad59-9a17758d45d9.jpg)

刷新元数

**Comment by rockhia** [comment]
手动刷新元数后，名称会恢复英文，头像和关联影片也恢复正常。
相当于nas-tool新增的中文名称没起到该有的作用。反而还要后续增加手动操作。
这个功能有部分人是成功的，是否用群友写的插件跑过emby整个库才能用？

**Comment by junskycool** [comment]
> 手动刷新元数后，名称会恢复英文，头像和关联影片也恢复正常。 相当于nas-tool新增的中文名称没起到该有的作用。反而还要后续增加手动操作。 这个功能有部分人是成功的，是否用群友写的插件跑过emby整个库才能用？

这个提问 已经被关了。。。   不知道什么问题

**Comment by Shurelol** [comment]
> 手动刷新元数后，名称会恢复英文，头像和关联影片也恢复正常。 相当于nas-tool新增的中文名称没起到该有的作用。反而还要后续增加手动操作。 这个功能有部分人是成功的，是否用群友写的插件跑过emby整个库才能用？
![image](https://user-images.githubusercontent.com/16237201/188384916-51d29b12-615f-479e-8974-745ed1ea8315.png)
覆盖所有元数据就是这样，有什么问题？

**Comment by Shurelol** [comment]
> > 手动刷新元数后，名称会恢复英文，头像和关联影片也恢复正常。 相当于nas-tool新增的中文名称没起到该有的作用。反而还要后续增加手动操作。 这个功能有部分人是成功的，是否用群友写的插件跑过emby整个库才能用？
> 
> 这个提问 已经被关了。。。 不知道什么问题

这个问题和nastool没有关系，emby4.7.2，4.7.6测试过，能刷新元数据刷新出图片
![image](https://user-images.githubusercontent.com/16237201/188385538-63f8e778-6148-4c16-a45f-2c0c72f332a1.png)
![image](https://user-images.githubusercontent.com/16237201/188385681-a67373c6-d740-4bd3-9cad-f1268b9e0aed.png)

**Comment by junskycool** [comment]
> > > 手动刷新元数后，名称会恢复英文，头像和关联影片也恢复正常。 相当于nas-tool新增的中文名称没起到该有的作用。反而还要后续增加手动操作。 这个功能有部分人是成功的，是否用群友写的插件跑过emby整个库才能用？
> > 
> > 
> > 这个提问 已经被关了。。。 不知道什么问题
> 
> 这个问题和nastool没有关系，emby4.7.2，4.7.6测试过，能刷新元数据刷新出图片 ![image](https://user-images.githubusercontent.com/16237201/188385538-63f8e778-6148-4c16-a45f-2c0c72f332a1.png) ![image](https://user-images.githubusercontent.com/16237201/188385681-a67373c6-d740-4bd3-9cad-f1268b9e0aed.png)

还要手动刷新的话那没意义啊   而且对于不能用的情况  等于nastool的削刮功能直接费了   还不如就让emby自动刮英文

**Comment by Shurelol** [comment]
> > > > 手动刷新元数后，名称会恢复英文，头像和关联影片也恢复正常。 相当于nas-tool新增的中文名称没起到该有的作用。反而还要后续增加手动操作。 这个功能有部分人是成功的，是否用群友写的插件跑过emby整个库才能用？
> > > 
> > > 
> > > 这个提问 已经被关了。。。 不知道什么问题
> > 
> > 
> > 这个问题和nastool没有关系，emby4.7.2，4.7.6测试过，能刷新元数据刷新出图片 ![image](https://user-images.githubusercontent.com/16237201/188385538-63f8e778-6148-4c16-a45f-2c0c72f332a1.png) ![image](https://user-images.githubusercontent.com/16237201/188385681-a67373c6-d740-4bd3-9cad-f1268b9e0aed.png)
> 
> 还要手动刷新的话那没意义啊 而且对于不能用的情况 等于nastool的削刮功能直接费了 还不如就让emby自动刮英文

emby能用到几个媒体库？媒体库上点一次刷新不久行了？
![image](https://user-images.githubusercontent.com/16237201/188389224-a16bd63b-1040-47dd-949c-d46335a0ff5c.png)
觉得不好用可以关闭，或者提pr

**Comment by junskycool** [comment]
> > > > > 手动刷新元数后，名称会恢复英文，头像和关联影片也恢复正常。 相当于nas-tool新增的中文名称没起到该有的作用。反而还要后续增加手动操作。 这个功能有部分人是成功的，是否用群友写的插件跑过emby整个库才能用？
> > > > 
> > > > 
> > > > 这个提问 已经被关了。。。 不知道什么问题
> > > 
> > > 
> > > 这个问题和nastool没有关系，emby4.7.2，4.7.6测试过，能刷新元数据刷新出图片 ![image](https://user-images.githubusercontent.com/16237201/188385538-63f8e778-6148-4c16-a45f-2c0c72f332a1.png) ![image](https://user-images.githubusercontent.com/16237201/188385681-a67373c6-d740-4bd3-9cad-f1268b9e0aed.png)
> > 
> > 
> > 还要手动刷新的话那没意义啊 而且对于不能用的情况 等于nastool的削刮功能直接费了 还不如就让emby自动刮英文
> 
> emby能用到几个媒体库？媒体库上点一次刷新不久行了？ ![image](https://user-images.githubusercontent.com/16237201/188389224-a16bd63b-1040-47dd-949c-d46335a0ff5c.png) 觉得不好用可以关闭，或者提pr

这不是提了么  我之前都是2个一起开  然后更新个新版这功能等于用不了了

**Comment by rockhia** [comment]
提交BUG的大佬，用的emby是否用的也是4.6.7版本？
不排除其他版本解决了类似地问题。
确实可以铜管关闭nfo解决这个问题，我这边已经关闭了。
如果不是版本的问题，过几天应该会有更多的人提出来
