### ISSUE TITLE
更新到2.0.4后，资源搜索、订阅管理页面不能打开，如红框所示几个菜单点击后没有反应

### ISSUE THREAD

**Issue by kscu** [jxxghp/nas-tools#976]
![微信截图_20220905145430](https://user-images.githubusercontent.com/89392096/188383448-f60449e0-aa78-412d-9245-dee4a4ea79c0.png)

**Comment by jxxghp** [comment]
没有这个问题

**Comment by kscu** [comment]
是在索引器使用内建索引器时就存在以上BUG；使用Jackett索引器就没有问题。

**Comment by c939984606** [comment]
一直在用内建索引，没有这个问题

**Comment by kscu** [comment]
> 一直在用内建索引，没有这个问题

2.0.3都没问题。更新2.0.4之后出现的。
