### ISSUE TITLE
是在索引器使用内建索引器时就存在以上BUG；使用Jackett索引器就没有问题。

### ISSUE THREAD

**Issue by kscu** [jxxghp/nas-tools#978]
是在索引器使用内建索引器时就存在以上BUG；使用Jackett索引器就没有问题。

_Originally posted by @kscu in https://github.com/jxxghp/nas-tools/issues/976#issuecomment-1236755497_

**Comment by jxxghp** [comment]
我自己也在用，没问题啊，配置文件里pt那块截图发出来看下

**Comment by jxxghp** [comment]
有问题按模板重提吧
