### ISSUE TITLE
目录同步之后的tg通知显示内容错误

### ISSUE THREAD

**Issue by lowking** [jxxghp/nas-tools#979]
![image](https://user-images.githubusercontent.com/33308659/188421062-09de4ac4-016b-4822-aed8-a383799f30c8.png)

不同集，都显示S01呢

**Comment by jxxghp** [comment]
把文件名、日志发一下啊

**Comment by lowking** [comment]
> 把文件名、日志发一下啊

原始文件名：[UHA-WINGS&LoliHouse] Ao Ashi - 01 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
同步重命名后：青之芦苇 - S01E01.mkv
日志同步目录的时候日志没输出呀，我盯着看的，日志没动
