### ISSUE TITLE
【带日志】下载完成后自动转移失败，导致原始文件没了

### ISSUE THREAD

**Issue by huluohu** [jxxghp/nas-tools#980]
![5EACC036-3D05-442F-B2B5-B988EEF8E4E7](https://user-images.githubusercontent.com/7138642/188432010-f3522167-7b59-4992-9fec-eeea361de631.jpeg)
抱歉，上个issue忘了带日志了，移动方式转移文件，失败后原文件也不见了，麻烦大佬在帮忙看下。

**Comment by c939984606** [comment]
写的多清楚，首先你是移动模式，当然就没了，第二.zip格式是视频格式吗

**Comment by jxxghp** [comment]
#975
