### ISSUE TITLE
做种数为0导致的不自动下载？

### ISSUE THREAD

**Issue by lowking** [jxxghp/nas-tools#981]
![image](https://user-images.githubusercontent.com/33308659/188437844-0c868b12-66e4-4543-9e3d-1f43454fabb2.png)
实际上可以下载的

订阅完青之芦苇，就下载的1-5，其他的都不下载，看了日志似乎共同特点都是做种数为0

**Comment by jxxghp** [comment]
远程搜索时，不会下载做种数为0的

**Comment by lowking** [comment]
能不能开放下这个设置，允许做种数0自动下载？或者判断下发布时间，是近期发布的允许下载？
