### ISSUE TITLE
2.0.4 动漫花园搜索不到资源

### ISSUE THREAD

**Issue by JJJDand** [jxxghp/nas-tools#985]
## 内置动漫花园搜索不到资源，rarbg可用，日志看不出异常，尝试开关代理也是一样，群里也有几位反馈一样的问题
22:22:45 INFO - 【INDEXER】开始并行检索 鬼灭之刃，线程数：2 ...
22:22:45 INFO - 【INDEXER】开始检索Indexer：RARBG ...
22:22:45 INFO - 【INDEXER】开始检索Indexer：动漫花园 ...
22:22:48 WARN - 【INDEXER】RARBG 返回数据：2
22:22:49 INFO - 【INDEXER】Demon.Slayer.Kimetsu.no.Yaiba.S01.JAPANESE.1080p.CR.WEB-DL.AAC2.0.x264-HorribleSubs[rartv] None 匹配成功
22:22:49 INFO - 【INDEXER】Demon.Slayer.Kimetsu.no.Yaiba.S01.JAPANESE.1080p.BluRay.AAC2.0.x264.Hi10P-Kaleido-Flax[rartv] None 匹配成功
22:22:49 INFO - 【INDEXER】RARBG 共检索到 2 条数据，过滤 0，不匹配 0，有效资源 2，耗时 4 秒
22:23:26 WARN - 【INDEXER】动漫花园 未检索到数据
22:23:26 INFO - 【INDEXER】所有站点检索完成，有效资源数：2，总耗时 41 秒
![image](https://user-images.githubusercontent.com/31849833/188470727-402964da-d16e-4dcf-80f0-521314284417.png)
## 在jackett中单独搜索没有问题
![image](https://user-images.githubusercontent.com/31849833/188470508-42e58cef-acb9-4a7c-93ab-ed25310e5a06.png)
## nastool调用jackett也没有问题
![image](https://user-images.githubusercontent.com/31849833/188471365-61181c4f-0256-4a77-b28e-f2b0ebaf590e.png)

**Comment by jxxghp** [comment]
你打开了使用英文名搜索？不然RARBG怎么会有结果？（这个站都是英文的）。
自己多研究下吧。

**Comment by JJJDand** [comment]
> 你打开了使用英文名搜索？不然RARBG怎么会有结果？（这个站都是英文的）。 自己多研究下吧。

没有打开英文名搜索，我再研究下吧，谢谢回复
