### ISSUE TITLE
windows 11版本的，nastools无法局域网访问

### ISSUE THREAD

**Issue by QINGBISE** [jxxghp/nas-tools#986]
我得r86s路由上装了windows11，打开软件后，网页打开localhost:3000..
本机的ip是192.168.3.8。
想用局域网访问这个地址，192.168.3.8:3000但是打不开。
防火墙关闭了，入站出站规则也放过这些端口也还是不可以。不知道为什么？

**Comment by jxxghp** [comment]
配置文件web_host改成0.0.0.0

**Comment by QINGBISE** [comment]
好了。谢谢。
