### ISSUE TITLE
nastools能搜到电影但是提醒 未找到任何资源，radarr可以搜到

### ISSUE THREAD

**Issue by maCreay** [jxxghp/nas-tools#989]
使用的都是jackett的相同的站点。不明白怎么回事，好困扰。
![图片2](https://user-images.githubusercontent.com/112171632/188482077-e0d413d1-4ad6-4869-aef0-c2010e4064fe.png)
![图片1](https://user-images.githubusercontent.com/112171632/188482096-12da3c08-995d-4cb8-9e8a-c8450cff8fa2.png)

**Comment by jxxghp** [comment]
日志都不看，自己先研究明白吧

**Comment by maCreay** [comment]
> 日志都不看，自己先研究明白吧

刚刚接触nas，很多不懂= =。

**Comment by maCreay** [comment]
> 日志都不看，自己先研究明白吧

不是不想看，我这种小白，开不太懂。然后也没有教程可以学= =

**Comment by maCreay** [comment]
> 日志都不看，自己先研究明白吧

我就差这一个问题了
