### ISSUE TITLE
历史记录删除某一集，导致整季都被删除。

### ISSUE THREAD

**Issue by psychopasss** [jxxghp/nas-tools#99]
![telegram-cloud-photo-size-5-6321283088038080367-y](https://user-images.githubusercontent.com/11738089/167296777-66b5a12a-6c89-42fe-8855-0e7903b09593.jpg)
而且删除之后，订阅里面数字还是5
![telegram-cloud-photo-size-5-6321283088038080370-y](https://user-images.githubusercontent.com/11738089/167296790-041e3581-aaa2-4ddc-9927-9dd2ae1fa470.jpg)
立即搜索之后
![telegram-cloud-photo-size-5-6321283088038080374-y](https://user-images.githubusercontent.com/11738089/167296798-7bee6426-ac05-4db7-b183-128e31d80589.jpg)
订阅直接取消了。

**Comment by jxxghp** [comment]
提供完整日志

**Comment by jxxghp** [comment]
删除历史记录本来就不会更新订阅

**Comment by psychopasss** [comment]
现在哪里可以拿到完整日志，我找了一遍都没找到，docker logs没有，config/logs也没有。
![telegram-cloud-photo-size-5-6321283088038080390-x](https://user-images.githubusercontent.com/11738089/167298702-b876c2d1-f94f-41f7-a3d9-f7a0aa57b7a5.jpg)
![telegram-cloud-photo-size-5-6321283088038080391-y](https://user-images.githubusercontent.com/11738089/167298705-129a2ff8-8fe8-4491-8d60-543f38f94318.jpg)

**Comment by psychopasss** [comment]
> 删除历史记录本来就不会更新订阅

我重新订阅了，现在是从0开始了。但是我用rmt重新处理了之前下载的剧集，0还是没动。

**Comment by jxxghp** [comment]
你不发日志是没法查的，我自己也在订阅这个，并没有问题。
就是检查你的配置是不是file

**Comment by jxxghp** [comment]
> > 删除历史记录本来就不会更新订阅
> 
> 我重新订阅了，现在是从0开始了。但是我用rmt重新处理了之前下载的剧集，0还是没动。

订阅只有订阅命中，或者点立即搜索的时候才会更新

**Comment by psychopasss** [comment]
> 你不发日志是没法查的，我自己也在订阅这个，并没有问题。
> 日志检查你的配置是不是file
> console是终端，这个字典已经被取消了

界面上写的是文件啊。一直配置的都是文件，没动过。至于为啥出现console我也不清楚。

**Comment by psychopasss** [comment]
> > > 删除历史记录本来就不会更新订阅
> > 
> > 
> > 我重新订阅了，现在是从0开始了。但是我用rmt重新处理了之前下载的剧集，0还是没动。
> 
> 订阅只有订阅命中，或者点立即搜索的时候才会更新

我现在通过手动rmt把5集全整理好了。现在点击立即搜索就可以同步数字了吗？

**Comment by jxxghp** [comment]
> > > > 删除历史记录本来就不会更新订阅
> > > 
> > > 
> > > 我重新订阅了，现在是从0开始了。但是我用rmt重新处理了之前下载的剧集，0还是没动。
> > 
> > 
> > 订阅只有订阅命中，或者点立即搜索的时候才会更新
> 
> 我现在通过手动rmt把5集全整理好了。现在点击立即搜索就可以同步数字了吗？

会

**Comment by psychopasss** [comment]
还有一个问题，TRANSFER_UNKNOWN这个表，如果之前已经有这条了。我rmt重新，也不会出现在手动识别里面，这有点麻烦啊。不能每次手动update STATE啊

**Comment by psychopasss** [comment]
> > > > > 删除历史记录本来就不会更新订阅
> > > > 
> > > > 
> > > > 我重新订阅了，现在是从0开始了。但是我用rmt重新处理了之前下载的剧集，0还是没动。
> > > 
> > > 
> > > 订阅只有订阅命中，或者点立即搜索的时候才会更新
> > 
> > 
> > 我现在通过手动rmt把5集全整理好了。现在点击立即搜索就可以同步数字了吗？
> 
> 会

<img width="683" alt="image" src="https://user-images.githubusercontent.com/11738089/167299368-db78920a-9083-4c28-82ba-08c657d93e0e.png">
数字还是没变化

**Comment by jxxghp** [comment]
我知道你这个是什么问题了，你这个种子没有识别出集数，认为是整季所以认为下完了，通知标题是S01没有Exx

**Comment by psychopasss** [comment]
大佬还没结束啊，另一个问题是历史记录我删除第5集，导致整个季都删除了。
