### ISSUE TITLE
关于重命名格式

### ISSUE THREAD

**Issue by guanyi1024** [jxxghp/nas-tools#991]
![Snipaste_2022-09-06_02-33-59](https://user-images.githubusercontent.com/60825150/188501172-b356b32d-c12a-446b-b59b-45ce73575869.png)
剧集的季号 能否不足两位的补个0
也就是season 01这种
还有可否增加个是哪个站压制的 方便后期洗版
-CHD这种识别的后缀

**Comment by jxxghp** [comment]
前补0的意义在哪？
压制组、字幕组的识别还有待加强，等识别准确率高了再加

**Comment by jxxghp** [comment]
#997

**Comment by guanyi1024** [comment]
> 前补0的意义在哪？ 压制组、字幕组的识别还有待加强，等识别准确率高了再加

ok 首先感谢大佬得回复~
补0其实没啥意义 就是强迫症罢了（手动哭笑）
