### ISSUE TITLE
更新到2.0.4后，使用内建索引器存在资源搜索、订阅管理页面不能打开；使用jackett没有问题  

### ISSUE THREAD

**Issue by kscu** [jxxghp/nas-tools#995]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4
>
> 环境: Synology
>

## 你遇到什么问题了？是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 使用内建索引器存在资源搜索、订阅管理页面不能打开

## 你的问题能重现嘛？

> 能够重现

## 你期望的结果

> 使用内建索引器时也能正常打开以上页面

## 给出程序界面截图、后台运行日志或配置文件

> 
![1](https://user-images.githubusercontent.com/89392096/188524924-b56ed8fe-1797-4227-add1-c96ae17226b6.png)

**Comment by jxxghp** [comment]
应该是配置文件不兼容，配置文件截个图

**Comment by kscu** [comment]
> 应该是配置文件不兼容，配置文件截个图

截哪一段配置？

**Comment by kscu** [comment]
![2](https://user-images.githubusercontent.com/89392096/188539075-27f78fd4-bcac-42d9-941d-203832f20671.png)
![3](https://user-images.githubusercontent.com/89392096/188539082-8d3a74a9-98ae-4839-9efe-7445abf04b9c.png)

**Comment by jxxghp** [comment]
你试下把inder_sites最下面那个引号那行删掉看看是不是行了

**Comment by jxxghp** [comment]
不知道了，无法重现。也没听别人有问题问题。请删掉重新配置吧，应该是老配置不兼容的问题，但找不到在哪。
