### ISSUE TITLE
[FR] 未识别season的，如果有TMDB等信息，默认使用最新一季，而不是第一季

### ISSUE THREAD

**Issue by HBSpy** [jxxghp/nas-tools#996]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4
>
> 环境: docker

## 你想要新增或者改进什么功能？

如果已经识别了剧集名，并采集到了TMDB信息，且没有识别到季号，默认使用当前最新季

## 这个功能有什么可以参考的资料吗？

动漫各季的命名一般会使用季名称，识别上有难度，如

* OVERLOAD S04: OVERLOAD IV
* 来自深渊 S02: 来自深渊 烈日的黄金乡
* 邪神与厨二病少女 S03: 邪神与厨二病少女 X

大多数时候产生的新的下载或识别都是在追最新的一季，所以推荐默认使用最新季

**Comment by ltsj** [comment]
那下第一季的人怎么办？
