### ISSUE TITLE
电视剧转移的重命名规则统一问题

### ISSUE THREAD

**Issue by iceveil** [jxxghp/nas-tools#997]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4
>
> 环境: docker in qnap

## 你想要新增或者改进什么功能？

>  对电视剧转移的重命名规则中，Season文件夹的数字增加对齐，即Season 01， Season 02的形式，取代现在的Season 1， Season 2 。
将 get_season_seq 函数中 return str(self.begin_season) 调整为 return str(self.begin_season).rjust(2, "0")
并考虑是否影响到 app/rss.py中的 467:  if str(no_exist_item.get("season")) == media_info.get_season_seq() 的等式

## 这个功能有什么可以参考的资料吗？

> Plex等官方推荐命名规则都是以对齐的形式，虽然没有影响到削刮，但是统一可以使媒体库命名更整洁。

**Comment by jxxghp** [comment]
感觉没啥必要，而且一改存量的会受影响
