### ISSUE TITLE
【功能请求】刷流任务选种规则增加种子存活时间

### ISSUE THREAD

**Issue by thsrite** [jxxghp/nas-tools#998]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4
>
> 环境: docker

刷流任务选种规则增加种子存活时间（筛选发布时间多少分钟之内的种子）。
例如观众，盒子黑盒，想只rss最新发布的种子，刷点上传。

**Comment by thsrite** [comment]
![image](https://user-images.githubusercontent.com/54088512/188541807-609021e1-972b-4348-964b-65c723248925.png)

**Comment by pen1120** [comment]
用“当前做种人数”判断不就可以了嘛，一般RSS到的资源如果做种人数少，都是新资源

**Comment by thsrite** [comment]
> 用“当前做种人数”判断不就可以了嘛，一般RSS到的资源如果做种人数少，都是新资源

是一种思路，但会错过一些种子，你定时任务等待期间，种子发布后会有盒子去下载的，做种人数虽然都是1，但是已经抢不到多少上传了，对于黑盒来说，分享率会拉的很低

**Comment by jxxghp** [comment]
DONE
