### ISSUE TITLE
[FR] 识别历史记录中，重新识别对话框能自动填上当前识别的结果

### ISSUE THREAD

**Issue by HBSpy** [jxxghp/nas-tools#999]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.4
>
> 环境: docker

## 你想要新增或者改进什么功能？

识别历史记录中，重新识别对话框能自动填上当前识别的结果

如TMDBID等，极大方便

**Comment by jxxghp** [comment]
都要重新识别了，说明原来识别的是错的，填上有啥用呢

**Comment by HBSpy** [comment]
因为完全离谱的大错不多，大部分时候就改个season啥的
